SRC_DIR_REL =../../src

include $(SRC_DIR_REL)/compiler.mk
include $(SRC_DIR_REL)/util/defines.mk
include $(SRC_DIR_REL)/inter/defines.mk
include $(SRC_DIR_REL)/ddMd/defines.mk
include $(SRC_DIR_REL)/ddMd/patterns.mk
include $(SRC_DIR_REL)/util/sources.mk
include $(SRC_DIR_REL)/inter/sources.mk
include $(SRC_DIR_REL)/ddMd/sources.mk

#-----------------------------------------------------------------------


clean:
	cd chemistry; make clean
	cd storage; make clean
	cd communicate; make clean
	cd neighbor; make clean
	cd potentials; make clean
	cd configIos; make clean
	cd simulation; make clean


