#!/bin/bash
set -ev

MODE=nve
if [ $# -gt 0 ]; then
   MODE=$1
fi
PARAM=param.$MODE
echo "Parameter file : " $PARAM

# Make or clean directory out
if [ ! -d "out" ]; then
   mkdir out
else
   rm -f out/*
fi

# Run simulation, write output to out/
mpirun -np 6 ddSim -q -e -p $PARAM -c commands 

# Make or clean directory rst, if necessary
if [ ! -d "rst" ]; then
   mkdir rst
else
   rm -f rst/*
fi

# Restart simulation, write outputs to rst/
mpirun -np 6 ddSim -q -e -r restart -c commands.rst -o rst/

