#!/bin/bash
set -ev

# Clean out */out/dump directories
rm -f 0/out/dump/*
rm -f 1/out/dump/*
rm -f 2/out/dump/*

# Remove files from */out
#rm -f 0/out/* 2> 
#rm -f 1/out/* 2> 
#rm -f 2/out/* 2> 
find 0/out/* -type f -delete
find 1/out/* -type f -delete
find 2/out/* -type f -delete

# Run simulation, writing to out
mpirun -np 3 mcSim_m -e -p param -c commands 

echo " "
echo "Log file for homopolymer/N8/mdMulti/1"
cat 1/log

mv 0/log 0/out
mv 1/log 1/out
mv 2/log 2/out

# Make or clean rst directories
if [ ! -d "0/rst" ]; then
   mkdir 0/rst
else
   rm -f 0/rst/*
fi
if [ ! -d "1/rst" ]; then
   mkdir 1/rst
else
   rm -f 1/rst/*
fi
if [ ! -d "2/rst" ]; then
   mkdir 2/rst
else
   rm -f 2/rst/*
fi

mpirun -np 3 mcSim_m -e -r restart -c commands.rst -o rst/

echo " "
echo "Log file for homopolymer/N8/mdMulti/1 after restart"
cat 1/log

mv 0/log 0/rst
mv 1/log 1/rst
mv 2/log 2/rst

