#!/bin/bash
set -ev

echo " "
echo "Running testsuite/mdSim_m/A"

# Clean directories
rm -f 0/out/* 0/restart 0/log
rm -f 1/out/* 1/restart 1/log
rm -f 2/out/* 2/restart 2/log

# Run simulation, writing to out
mpirun -np 3 mdSim_m -e -p param -c command

echo " "
echo "Log file for testsuite/mdSim_m/A/1"
cat 1/log

mv 0/log 0/out
mv 1/log 1/out
mv 2/log 2/out

# Make or clean rst directories
if [ ! -d "0/rst" ]; then
   mkdir 0/rst
else
   rm -f 0/rst/*
fi
if [ ! -d "1/rst" ]; then
   mkdir 1/rst
else
   rm -f 1/rst/*
fi
if [ ! -d "2/rst" ]; then
   mkdir 2/rst
else
   rm -f 2/rst/*
fi

mpirun -np 3 mdSim_m -e -r restart -c commrst -o rst/

echo " "
echo "Log file for testsuite/mdSim_m/A/1 after restart"
cat 1/log

mv 0/log 0/rst
mv 1/log 1/rst
mv 2/log 2/rst

