#!/bin/bash -l
#PBS -l walltime=5:00:00,pmem=100mb,nodes=1:ppn=1
#PBS -o zout
#PBS -j oe
#PBS -N dpdMcNetwork

cd $HOME/molmcd/branches/evaluators/examples/network/mc/dpdMove
module load intel
module load ompi/intel
/usr/bin/time $HOME/molmcd/branches/evaluators/bin/mcSim_l < param > out/log
