#!/bin/bash

#------------------------------------------------------------------------
# Setup script:
#
# This script should be run once before the first time the program is
# compiled. It must be run from the root simpatico/ directory, in which
# this script is located.
# 
# This script:
#
# 1) Copies default or repository versions of several build configuration 
# files, named config.mk_r, to modifiable user versions, named config.mk. 
# A separate set of build configuration files is created in the src/
# directory (for in-source build) and in the obj/serial and obj/parallel
# object directories. 
#
# 2) Sets the makefile variables $(ROOT_DIR) and $(OBJ_DIR) in the main
# config.mk file in each object directory to the absolute paths of the 
# current working directory of the object directory, respectively. 
#
# 3) Creates user-modifiable copies of the sources.mk files in the user/
# subdirectory of each namespace level subdirectory of src/. 
#
# 4) Creates user modifiable copies of repository versions of some C++ 
# source files that users often need to modify to add new features. 
# Specifically, it makes copies of the factory implementation files 
# and Boundary typedef.
#------------------------------------------------------------------------

# Create main config.mk files and set the value of $(ROOT_DIR) and $(OBJ_DIR)
sed -e "s|=PWD|=$PWD|" -e "s|=OWD|src|" src/config.mk_r > src/config.mk
sed -e "s|=PWD|=$PWD|" -e "s|=OWD|obj/serial|" src/config.mk_r > obj/serial/config.mk
sed -e "s|=PWD|=$PWD|" -e "s|=OWD|obj/parallel|" src/config.mk_r > obj/parallel/config.mk

# Namespace config.mk in src/ directory (for in-source builds)
cp  src/util/config.mk_r src/util/config.mk
cp  src/inter/config.mk_r src/inter/config.mk
cp  src/mcMd/config.mk_r src/mcMd/config.mk
cp  src/ddMd/config.mk_r src/ddMd/config.mk

# Namespace config.mk in obj/serial (for out-of-source builds with no MPI)
cp  src/util/config.mk_r obj/serial/util/config.mk
cp  src/inter/config.mk_r obj/serial/inter/config.mk
cp  src/mcMd/config.mk_r obj/serial/mcMd/config.mk
cp  src/ddMd/config.mk_r obj/serial/ddMd/config.mk

# Namespace config.mk in obj/parallel (for out-of-source builds with no MPI)
cp  src/util/config.mk_r obj/parallel/util/config.mk
cp  src/inter/config.mk_r obj/parallel/inter/config.mk
cp  src/mcMd/config.mk_r obj/parallel/mcMd/config.mk
cp  src/ddMd/config.mk_r obj/parallel/ddMd/config.mk

# Copy repository versions of sources.mk files in user directories.
# These list user-contributed classes.
cp  src/inter/user/sources.mk_r src/inter/user/sources.mk
cp  src/mcMd/user/sources.mk_r src/mcMd/user/sources.mk
cp  src/ddMd/user/sources.mk_r src/ddMd/user/sources.mk

# ---------------------------------------------------------------------
# Copy repository version of Factory implementation files to user versions.

cp  src/mcMd/configIos/ConfigIoFactory.cpp_r src/mcMd/configIos/ConfigIoFactory.cpp
cp  src/mcMd/trajectoryIos/TrajectoryIoFactory.cpp_r src/mcMd/trajectoryIos/TrajectoryIoFactory.cpp
cp  src/mcMd/species/SpeciesFactory.cpp_r src/mcMd/species/SpeciesFactory.cpp
cp  src/mcMd/potentials/angle/AngleFactory.cpp_r src/mcMd/potentials/angle/AngleFactory.cpp
cp  src/mcMd/potentials/bond/BondFactory.cpp_r src/mcMd/potentials/bond/BondFactory.cpp
cp  src/mcMd/potentials/dihedral/DihedralFactory.cpp_r src/mcMd/potentials/dihedral/DihedralFactory.cpp
cp  src/mcMd/potentials/external/ExternalFactory.cpp_r src/mcMd/potentials/external/ExternalFactory.cpp
cp  src/mcMd/potentials/link/LinkFactory.cpp_r src/mcMd/potentials/link/LinkFactory.cpp
cp  src/mcMd/potentials/pair/PairFactory.cpp_r src/mcMd/potentials/pair/PairFactory.cpp
cp  src/mcMd/mcMoves/McMoveFactory.cpp_r src/mcMd/mcMoves/McMoveFactory.cpp
cp  src/mcMd/mdIntegrators/MdIntegratorFactory.cpp_r src/mcMd/mdIntegrators/MdIntegratorFactory.cpp
cp  src/mcMd/perturb/mcSystem/McPerturbationFactory.cpp_r src/mcMd/perturb/mcSystem/McPerturbationFactory.cpp
cp  src/mcMd/analyzers/mcSystem/McAnalyzerFactory.cpp_r src/mcMd/analyzers/mcSystem/McAnalyzerFactory.cpp
cp  src/mcMd/analyzers/mdSystem/MdAnalyzerFactory.cpp_r src/mcMd/analyzers/mdSystem/MdAnalyzerFactory.cpp
cp  src/mcMd/analyzers/system/SystemAnalyzerFactory.cpp_r src/mcMd/analyzers/system/SystemAnalyzerFactory.cpp
cp  src/ddMd/configIos/ConfigIoFactory.cpp_r src/ddMd/configIos/ConfigIoFactory.cpp
cp  src/ddMd/potentials/angle/AngleFactory.cpp_r src/ddMd/potentials/angle/AngleFactory.cpp
cp  src/ddMd/potentials/bond/BondFactory.cpp_r src/ddMd/potentials/bond/BondFactory.cpp
cp  src/ddMd/potentials/dihedral/DihedralFactory.cpp_r src/ddMd/potentials/dihedral/DihedralFactory.cpp
cp  src/ddMd/potentials/external/ExternalFactory.cpp_r src/ddMd/potentials/external/ExternalFactory.cpp
cp  src/ddMd/potentials/pair/PairFactory.cpp_r src/ddMd/potentials/pair/PairFactory.cpp
cp  src/ddMd/integrators/IntegratorFactory.cpp_r src/ddMd/integrators/IntegratorFactory.cpp
cp  src/ddMd/analyzers/AnalyzerFactory.cpp_r src/ddMd/analyzers/AnalyzerFactory.cpp
cp  src/ddMd/modifiers/ModifierFactory.cpp_r src/ddMd/modifiers/ModifierFactory.cpp

# Copy typedef for the class that defines boundary conditions
cp  src/util/boundary/Boundary.h_r src/util/boundary/Boundary.h

# ---------------------------------------------------------------------
# Create copies of the configure script.

cp src/configure obj/serial/configure
cp src/configure obj/parallel/configure

cd obj/parallel; ./configure -m1 
