#!/bin/bash

#------------------------------------------------------------------------
# Setup script:
#
# This script should be run once before the first time the program is
# compiled. It copies default or repository versions of configuration
# files, marked with a suffix _r, to operational versions. The user
# can then modify operational versions of these files as needed while 
# retaining clean copies of the repository versions.
#------------------------------------------------------------------------

cp config.mk_r  config.mk
cp makefile_r    makefile

