
SRC=..

include $(SRC)/makefile.cc
include makefile.inc

# ==============================================================================
.PHONY: clean all 

clean:
	-rm $(DRAFT_MCMD_DIR)/*.o 

all:    $(DRAFT_MCMD_OBJ)

# ==============================================================================
