#!/bin/bash -l
#PBS -q devel
#PBS -l walltime=0:10:00,pmem=20mb,nodes=4:ppn=8
#PBS -o zout
#PBS -j oe
#PBS -N LJDD

cd $PBS_O_WORKDIR
module load gcc
module load ompi/gnu
mpirun -np 32 $HOME/itasca/simpatico/bin/ddSim -e < param.nvt > log.32
