RESTART 25000
FINISH

SET_CONFIG_IO  LammpsConfigIo
READ_CONFIG    config
THERMALIZE     1.0
SIMULATE       2000 
OUTPUT_ANALYZERS
OUTPUT_INTEGRATOR_STATS
OUTPUT_MEMORY_STATS
WRITE_CONFIG   config
WRITE_PARAM    param

OUTPUT_EXCHANGER_STATS

