# ==============================================================================
.PHONY: clean 

clean: 
	cd util;  make clean
	cd inter; make clean
	cd mcMd;  make clean
	cd ddMd;  make clean

# ==============================================================================
