#!/usr/bin/env python

from MakeMaker import *

x = MakeMaker('.','ddMd','..')

globalInclude  = 'include $(SRC_DIR_REL)/compiler.mk\n'
globalInclude += 'include $(SRC_DIR_REL)/util/defines.mk\n'
globalInclude += 'include $(SRC_DIR_REL)/ddMd/defines.mk\n'
globalInclude += 'include $(SRC_DIR_REL)/ddMd/patterns.mk\n'
globalInclude += 'include $(SRC_DIR_REL)/util/sources.mk\n'
globalInclude += 'include $(SRC_DIR_REL)/ddMd/sources.mk\n'
x.setGlobalInclude(globalInclude)

x.setLinkObjs('$(ddMd_LIB) $(util_LIB)')
x.addLibrary('$(ddMd_LIB)', '$(ddMd_OBJS)')
x.make()
