SRC_DIR=../../../..

include $(SRC_DIR)/makefile.all
include $(SRC_DIR)/util/makefile.inc
include $(SRC_DIR)/test/makefile.inc

all:
	make Test

clean:	 
	rm -f Test 

Test: Test.cpp ParamTestComposite.h
	$(CXX) $(TESTFLAGS) $(DEFINES) $(INCLUDES) -o Test Test.cpp $(util_OBJS)

