#!/usr/bin/env python

from MakeMaker import *

x = MakeMaker('.','mcMd','..')

globalInclude  = 'include $(SRC_DIR_REL)/compiler.mk\n'
globalInclude += 'include $(SRC_DIR_REL)/util/defines.mk\n'
globalInclude += 'include $(SRC_DIR_REL)/mcMd/defines.mk\n'
globalInclude += 'include $(SRC_DIR_REL)/mcMd/patterns.mk\n'
globalInclude += 'include $(SRC_DIR_REL)/util/sources.mk\n'
globalInclude += 'include $(SRC_DIR_REL)/mcMd/sources.mk\n'
x.setGlobalInclude(globalInclude)

x.setLinkObjs('$(mcMd_LIB) $(util_LIB)')
x.addLibrary('$(mcMd_LIB)', '$(mcMd_OBJS)')
x.make()
