# -----------------------------------------------------------------------
# File: src/mcMd/patterns.mk
#
# This makefile fragment contains the pattern rule used to compile all
# source files in the directory tree rooted at the directory src/mcMd, 
# which contains the source code for the McMd namespace.  It must be 
# directly included by all makefile files in this directory tree, and 
# indirectly includes all relevant namespace-level configuration 
# (config.mk) and source-file list (source.mk) files from the src/mcMd, 
# src/simp and src/util directories.  This file must be included in 
# each makefile in src/mcMd after the definition of $(SRC_BLD_REL) and 
# after inclusion of the main build directory config file, 
# $(BLD_DIR)/config.mk.
# -----------------------------------------------------------------------
# Makefile fragment includes

# Namespace level build configuration files 
# Define *_DEFS macro definitions, paths to libraries and executables
include $(BLD_DIR)/util/config.mk
include $(BLD_DIR)/simp/config.mk
include $(BLD_DIR)/mcMd/config.mk

# Namespace level source file lists
# Include recipes to build library targets
include $(SRC_DIR)/util/sources.mk
include $(SRC_DIR)/simp/sources.mk
include $(SRC_DIR)/mcMd/sources.mk

# -----------------------------------------------------------------------
# Makefile variable definitions

# Lists of all C++ macro definitions needed in different contexts
UTIL_DEFINES = $(UTIL_DEFS)
SIMP_DEFINES = $(UTIL_DEFS) $(SIMP_DEFS)
MCMD_DEFINES = $(UTIL_DEFS) $(SIMP_DEFS) $(MCMD_DEFS)

# Lists of dependencies on build configuration files.
# Added to lists of dependencies generated by $(MAKEDEP) 
UTIL_CFGS= -A$(BLD_DIR)/config.mk
UTIL_CFGS+= -A$(BLD_DIR)/util/config.mk
SIMP_CFGS= $(UTIL_CFGS)
SIMP_CFGS+= -A$(BLD_DIR)/simp/config.mk
MCMD_CFGS= $(SIMP_CFGS)
MCMD_CFGS+= -A$(BLD_DIR)/mcMd/config.mk

# All libraries needed to link executables in src/mcMd
LIBS=$(mcMd_LIB) $(simp_LIB) $(util_LIB)

# -----------------------------------------------------------------------
# Pattern rules

# Rule to compile all *.cpp class source files in src/mcMd
$(BLD_DIR)/mcMd/%.o: $(SRC_DIR)/mcMd/%.cpp
	@SDIR=$$(dirname "$@"); if [ ! -d "$$SDIR" ]; then mkdir -p "$$SDIR"; fi
	$(CXX) $(INCLUDES) $(MCMD_DEFINES) $(CXXFLAGS) -c -o $@ $<
ifdef MAKEDEP
	$(MAKEDEP) $(INCLUDES) $(MCMD_DEFINES) $(CXXFLAGS) $(MCMD_CFGS) -S$(SRC_DIR) -B$(BLD_DIR) $<
endif

# Rule to compile all *.cpp class source files in src/simp
$(BLD_DIR)/simp/%.o: $(SRC_DIR)/simp/%.cpp
	@SDIR=$$(dirname "$@"); if [ ! -d "$$SDIR" ]; then mkdir -p "$$SDIR"; fi
	$(CXX) $(INCLUDES) $(SIMP_DEFINES) $(CXXFLAGS) -c -o $@ $<
ifdef MAKEDEP
	$(MAKEDEP) $(INCLUDES) $(SIMP_DEFINES) $(CXXFLAGS) $(SIMP_CFGS) -S$(SRC_DIR) -B$(BLD_DIR) $<
endif

# Rule to compile all *.cpp class source files in src/util
$(BLD_DIR)/util/%.o: $(SRC_DIR)/util/%.cpp
	@SDIR=$$(dirname "$@"); if [ ! -d "$$SDIR" ]; then mkdir -p "$$SDIR"; fi
	$(CXX) $(INCLUDES) $(UTIL_DEFINES) $(CXXFLAGS) -c -o $@ $<
ifdef MAKEDEP
	$(MAKEDEP) $(INCLUDES) $(UTIL_DEFINES) $(CXXFLAGS) $(UTIL_CFGS) -S$(SRC_DIR) -B$(BLD_DIR) $<
endif

# Rule to compile all *.cc test programs in src/mcMd/tests
$(BLD_DIR)/mcMd/tests/%.o: $(SRC_DIR)/mcMd/tests/%.cc 
	$(CXX) $(INCLUDES) $(MCMD_DEFINES) $(TESTFLAGS) -c -o $@ $<
ifdef MAKEDEP
	$(MAKEDEP) $(INCLUDES) $(MCMD_DEFINES) $(TESTFLAGS) $(MCMD_CFGS) -S$(SRC_DIR) -B$(BLD_DIR) $<
endif

# Rule to link all *.cc test programs in src/mcMd/tests
$(BLD_DIR)/mcMd/tests/%: $(BLD_DIR)/mcMd/tests/%.o $(LIBS)
	$(CXX) -o $@ $@.o $(LIBS) $(LDFLAGS)

