#!/bin/bash
set -e

#-----------------------------------------------------------------------
# Set working directory to directory containing script, if not already.

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )"
if [ "$SCRIPT_DIR" != "$PWD" ]; then
   echo "Resetting working directory to directory containing script"
   unset CDPATH
   \cd $PWD
fi

#-----------------------------------------------------------------------

cd $SCRIPT_DIR/homopolymer/N8/md
./run.nve 
./clean

cd $SCRIPT_DIR/homopolymer/N8/mc/combine 
./run
./clean

cd $SCRIPT_DIR/homopolymer/N8/mdMulti
./run
./clean

cd $SCRIPT_DIR/homopolymer/N8/mdMulti
./run
./clean
