# ==========================================================================
# test cell list directory 

NEIGHBOR_TEST_DIR=$(SRC)/mcMd/neighbor/tests
 
# file macros
CELL_TEST=$(NEIGHBOR_TEST_DIR)/CellTest
CELLLIST_TEST=$(NEIGHBOR_TEST_DIR)/CellListTest
PAIRLIST_TEST=$(NEIGHBOR_TEST_DIR)/PairListTest
NEIGHBOR_TEST_COMPOSITE=$(NEIGHBOR_TEST_DIR)/NeighborTestComposite

# Targets
$(CELL_TEST).h: $(CELL).h $(CELLTAG).h $(ATOM).h $(RARRAY).h $(DARRAY).h \
        $(UNIT_TEST).h $(UNIT_TEST_RUNNER).h
	touch $@
 
$(CELLLIST_TEST).h: $(CELLLIST).h $(CELL).h $(ORTHORHOMBICBOUNDARY).h \
        $(ATOM).h $(RARRAY).h $(RANDOM).h $(UNIT_TEST).h $(UNIT_TEST_RUNNER).h
	touch $@
 
$(PAIRLIST_TEST).h: $(PAIRLIST).h \
        $(UNIT_TEST).h $(UNIT_TEST_RUNNER).h
	touch $@

$(NEIGHBOR_TEST_COMPOSITE).h: $(CELL_TEST).h $(CELLLIST_TEST).h \
        $(PAIRLIST_TEST).h $(COMPOSITE_TEST_RUNNER).h
	touch $@
 
# ==========================================================================
