#!/bin/bash
set -e

#-----------------------------------------------------------------------
# Set working directory to directory containing script, if not already.

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )"
echo "Script directory is: " $SCRIPT_DIR
EXAMPLE_DIR="$SCRIPT_DIR/.."
echo "Example directory is: " "$EXAMPLE_DIR"
if [ "$EXAMPLE_DIR" != "$PWD" ]; then
   echo "Resetting working directory to examples/ directory"
   unset CDPATH
   \cd $EXAMPLE_DIR
fi
echo "Working directory is: " "$PWD"

#-----------------------------------------------------------------------

cd $EXAMPLE_DIR/homopolymer/N8/md
./run
./clean

cd $EXAMPLE_DIR/homopolymer/N8/mc/combine 
./run
./clean

cd $EXAMPLE_DIR/semigrand
./run
./clean

cd $EXAMPLE_DIR/homopolymer/N8/mdMulti
./run
./clean

cd $EXAMPLE_DIR/homopolymer/N8/mdMulti
./run
./clean

cd $EXAMPLE_DIR/diblock/N32/dd
./run
./clean
