# ==============================================================================
.PHONY: clean 

clean: 
	cd atomicMaker;  make clean
	cd chainMaker; make clean
	cd rings; make clean
	cd hoomd; make clean

# ==============================================================================
