# ==============================================================================
.PHONY: clean 

clean: 
	cd atomicMaker;  $(MAKE) clean
	cd chainMaker; $(MAKE) clean
	cd rings; $(MAKE) clean
	cd hoomd; $(MAKE) clean

# ==============================================================================
