Simpatico: McMd::RingTetraRebridgeMove Class Reference
McMd::RingTetraRebridgeMove Class Reference
Monte Carlo Moves
Detailed Description
Molecule move that attempt the exchange of interior pieces of one close rings.
Analogous to the twist/untwist operations.
Definition at line 29 of file RingTetraRebridgeMove.h.
#include <RingTetraRebridgeMove.h>
Public Member Functions
RingTetraRebridgeMove (McSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read species to which displacement is applied.
virtual bool move ()
Generate and accept or reject configuration bias move.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to an archive.
Protected Member Functions
bool scanBridge (Molecule *molPtr, int aId, int &cId)
Scan potential rebridging sites.
int modId (int id, int n)
Shift Atom index along a Ring.
Protected Attributes
int speciesId_
Integer index for molecular species.
int nAtom_
Number of atoms per molecule.
double upperBridge_
Upper bounds for trial length of a bridge.
double lowerBridge_
Lower bounds for trial length of a bridge.
DArray< Vector > R_
Arrays of atom positions of the correct molecule shape.
Constructor & Destructor Documentation
McMd::RingTetraRebridgeMove::RingTetraRebridgeMove (McSystem & system)
Constructor.
Parameters:
system parent McSystem
Definition at line 29 of file RingTetraRebridgeMove.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::RingTetraRebridgeMove::readParameters (std::istream & in) [virtual]
Read species to which displacement is applied.
Parameters:
in input parameter stream
Reimplemented from McMd::McMove.
Definition at line 40 of file RingTetraRebridgeMove.cpp.
References Util::DArray< Data >::allocate(), lowerBridge_, McMd::Species::nAtom(), nAtom_, R_, McMd::McMove::readProbability(), McMd::McMove::simulation(), McMd::System::simulation(), McMd::Simulation::species(), speciesId_, McMd::SystemMove::system(), upperBridge_, and UTIL_THROW.
bool McMd::RingTetraRebridgeMove::move () [virtual]
Generate and accept or reject configuration bias move.
Reimplemented from McMd::McMove.
Definition at line 113 of file RingTetraRebridgeMove.cpp.
References McMd::Molecule::atom(), McMd::SystemMove::boltzmann(), McMd::Molecule::bond(), McMd::McMove::incrementNAccept(), McMd::McMove::incrementNAttempt(), Util::Random::metropolis(), modId(), nAtom_, McMd::McSystem::pairPotential(), McMd::Atom::position(), McMd::McMove::random(), McMd::System::randomMolecule(), scanBridge(), speciesId_, McMd::SystemMove::system(), McMd::GroupRebridgeBase::tetraEnergy(), McMd::Group< NAtom >::typeId(), Util::Random::uniformInt(), and McMd::McPairPotential::updateAtomCell().
void McMd::RingTetraRebridgeMove::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive
Reimplemented from McMd::McMove.
Definition at line 65 of file RingTetraRebridgeMove.cpp.
References Util::DArray< Data >::allocate(), lowerBridge_, McMd::Species::nAtom(), nAtom_, R_, McMd::McMove::simulation(), McMd::System::simulation(), McMd::Simulation::species(), speciesId_, McMd::SystemMove::system(), upperBridge_, and UTIL_THROW.
void McMd::RingTetraRebridgeMove::save (Serializable::OArchive & ar) [virtual]
Save state to an archive.
Parameters:
ar saving (output) archive
Reimplemented from McMd::McMove.
Definition at line 93 of file RingTetraRebridgeMove.cpp.
References lowerBridge_, nAtom_, speciesId_, and upperBridge_.
bool McMd::RingTetraRebridgeMove::scanBridge (Molecule * molPtr, int aId, int & cId) [protected]
Scan potential rebridging sites.
Parameters:
molPtr Pointer of the molecule to be rebridged.
aId The first atom Id of the first group to be rebridged.
cId The first atom Id of the second group to be rebridged.
Definition at line 217 of file RingTetraRebridgeMove.cpp.
References McMd::Molecule::atom(), McMd::SystemMove::boundary(), McMd::System::boundary(), Util::OrthorhombicBoundary::distanceSq(), lowerBridge_, modId(), nAtom_, McMd::Atom::position(), R_, McMd::McMove::random(), Util::Vector::square(), Util::Vector::subtract(), McMd::SystemMove::system(), Util::Random::uniformInt(), and upperBridge_.
Referenced by move().
int McMd::RingTetraRebridgeMove::modId (int id, int n) [inline, protected]
Shift Atom index along a Ring.
Parameters:
id Atom id to be regulated, which can be negative.
n Number of atoms in the Ring.
Definition at line 105 of file RingTetraRebridgeMove.h.
Referenced by move(), and scanBridge().
Member Data Documentation
int McMd::RingTetraRebridgeMove::speciesId_ [protected]
Integer index for molecular species.
Definition at line 70 of file RingTetraRebridgeMove.h.
Referenced by loadParameters(), move(), readParameters(), and save().
int McMd::RingTetraRebridgeMove::nAtom_ [protected]
Number of atoms per molecule.
Definition at line 73 of file RingTetraRebridgeMove.h.
Referenced by loadParameters(), move(), readParameters(), save(), and scanBridge().
double McMd::RingTetraRebridgeMove::upperBridge_ [protected]
Upper bounds for trial length of a bridge.
Definition at line 76 of file RingTetraRebridgeMove.h.
Referenced by loadParameters(), readParameters(), save(), and scanBridge().
double McMd::RingTetraRebridgeMove::lowerBridge_ [protected]
Lower bounds for trial length of a bridge.
Definition at line 79 of file RingTetraRebridgeMove.h.
Referenced by loadParameters(), readParameters(), save(), and scanBridge().
DArray<Vector> McMd::RingTetraRebridgeMove::R_ [protected]
Arrays of atom positions of the correct molecule shape.
Definition at line 82 of file RingTetraRebridgeMove.h.
Referenced by loadParameters(), readParameters(), and scanBridge().
The documentation for this class was generated from the following files:
RingTetraRebridgeMove.h
RingTetraRebridgeMove.cpp