Simpatico: McMd::RigidDisplaceMove Class Reference
McMd::RigidDisplaceMove Class Reference
Monte Carlo Moves
Detailed Description
Random rigid displacement of a molecule.
Definition at line 28 of file RigidDisplaceMove.h.
#include <RigidDisplaceMove.h>
Public Member Functions
RigidDisplaceMove (McSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read species to which displacement is applied.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize internal state to/from archive.
virtual bool move ()
Generate, attempt and accept or reject a move.
Constructor & Destructor Documentation
McMd::RigidDisplaceMove::RigidDisplaceMove (McSystem & system)
Constructor.
Definition at line 30 of file RigidDisplaceMove.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::RigidDisplaceMove::readParameters (std::istream & in) [virtual]
Read species to which displacement is applied.
Parameters:
in input parameter stream
Reimplemented from McMd::McMove.
Definition at line 39 of file RigidDisplaceMove.cpp.
References Util::DArray< Data >::allocate(), McMd::Species::nAtom(), Util::ParamComposite::readBlank(), McMd::McMove::readProbability(), McMd::McMove::simulation(), and McMd::Simulation::species().
void McMd::RigidDisplaceMove::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::McMove.
Definition at line 53 of file RigidDisplaceMove.cpp.
References Util::DArray< Data >::allocate(), McMd::Species::nAtom(), McMd::McMove::simulation(), McMd::Simulation::species(), and UTIL_THROW.
void McMd::RigidDisplaceMove::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::McMove.
Definition at line 68 of file RigidDisplaceMove.cpp.
template<class Archive > void McMd::RigidDisplaceMove::serialize (Archive & ar, const unsigned int version)
Serialize internal state to/from archive.
Parameters:
ar archive
version id for archive version
Reimplemented from Util::ParamComponent.
bool McMd::RigidDisplaceMove::move () [virtual]
Generate, attempt and accept or reject a move.
Reimplemented from McMd::McMove.
Definition at line 79 of file RigidDisplaceMove.cpp.
References McMd::Molecule::atom(), McMd::McPairPotential::atomEnergy(), McMd::ExternalPotential::atomEnergy(), McMd::SystemMove::boltzmann(), McMd::SystemMove::boundary(), Util::Dimension, McMd::McSystem::externalPotential(), McMd::McMove::incrementNAccept(), McMd::McMove::incrementNAttempt(), Util::Random::metropolis(), McMd::McSystem::pairPotential(), McMd::Atom::position(), McMd::McMove::random(), McMd::System::randomMolecule(), Util::OrthorhombicBoundary::shift(), McMd::SystemMove::system(), Util::Random::uniform(), and McMd::McPairPotential::updateAtomCell().
The documentation for this class was generated from the following files:
RigidDisplaceMove.h
RigidDisplaceMove.cpp