Simpatico: McMd::CfbEndMove Class Reference
McMd::CfbEndMove Class Reference
Monte Carlo Moves
Detailed Description
Configuration bias end regrowth move for flexible linear chains.
Definition at line 28 of file CfbEndMove.h.
#include <CfbEndMove.h>
Public Member Functions
CfbEndMove (McSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read species to which displacement is applied.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual bool move ()
Generate and accept or reject configuration bias move.
Protected Attributes
DArray< Vector > oldPos_
Array of old positions of temporarily deleted atoms (temporary).
int speciesId_
Integer index for molecular species.
int nRegrow_
Number of particles at end to attempt to regrow.
Friends
class CbEndMoveTest
Make unit test class a friend.
Constructor & Destructor Documentation
McMd::CfbEndMove::CfbEndMove (McSystem & system)
Constructor.
Definition at line 32 of file CfbEndMove.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::CfbEndMove::readParameters (std::istream & in) [virtual]
Read species to which displacement is applied.
Reimplemented from McMd::CfbEndBase.
Definition at line 41 of file CfbEndMove.cpp.
References Util::DArray< Data >::allocate(), McMd::CfbEndBase::MaxTrial_, nRegrow_, McMd::CfbEndBase::nTrial_, oldPos_, McMd::McMove::readProbability(), McMd::McMove::simulation(), McMd::Simulation::species(), speciesId_, and UTIL_THROW.
void McMd::CfbEndMove::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::McMove.
Definition at line 66 of file CfbEndMove.cpp.
References Util::DArray< Data >::allocate(), McMd::CfbEndBase::MaxTrial_, nRegrow_, McMd::CfbEndBase::nTrial_, oldPos_, McMd::McMove::simulation(), McMd::Simulation::species(), speciesId_, and UTIL_THROW.
void McMd::CfbEndMove::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::McMove.
Definition at line 91 of file CfbEndMove.cpp.
References nRegrow_, McMd::CfbEndBase::nTrial_, and speciesId_.
bool McMd::CfbEndMove::move () [virtual]
Generate and accept or reject configuration bias move.
Reimplemented from McMd::McMove.
Definition at line 102 of file CfbEndMove.cpp.
References McMd::McPairPotential::addAtom(), McMd::CfbEndBase::addEndAtom(), McMd::Molecule::atom(), McMd::Molecule::bond(), McMd::McPairPotential::deleteAtom(), McMd::CfbEndBase::deleteEndAtom(), McMd::McMove::incrementNAccept(), McMd::McMove::incrementNAttempt(), Util::Random::metropolis(), McMd::Molecule::nAtom(), nRegrow_, oldPos_, McMd::McSystem::pairPotential(), McMd::Atom::position(), McMd::McMove::random(), McMd::System::randomMolecule(), speciesId_, McMd::SystemMove::system(), McMd::Group< NAtom >::typeId(), McMd::McPairPotential::updateAtomCell(), and UTIL_THROW.
Friends And Related Function Documentation
friend class CbEndMoveTest [friend]
Make unit test class a friend.
Definition at line 74 of file CfbEndMove.h.
Member Data Documentation
DArray<Vector> McMd::CfbEndMove::oldPos_ [protected]
Array of old positions of temporarily deleted atoms (temporary).
Definition at line 65 of file CfbEndMove.h.
Referenced by loadParameters(), move(), and readParameters().
int McMd::CfbEndMove::speciesId_ [protected]
Integer index for molecular species.
Definition at line 68 of file CfbEndMove.h.
Referenced by loadParameters(), move(), readParameters(), and save().
int McMd::CfbEndMove::nRegrow_ [protected]
Number of particles at end to attempt to regrow.
Definition at line 71 of file CfbEndMove.h.
Referenced by loadParameters(), move(), readParameters(), and save().
The documentation for this class was generated from the following files:
CfbEndMove.h
CfbEndMove.cpp