Simpatico: Util::XdrFileOArchive Class Reference
Util::XdrFileOArchive Class Reference
Util namespace » Serialization
Detailed Description
Saving / output archive for binary XDR file.
XDR is a standard protocol for writing and reading binary in a portable format. This archive saves data to an associated file in XDR format. It depends on the unix xdr library <rpc/xdr.h>. Because this library is written in C (not C++), this archive uses a standard C library file handle, not a C++ iostream.
Definition at line 39 of file XdrFileOArchive.h.
#include <XdrFileOArchive.h>
Public Member Functions
XdrFileOArchive ()
Constructor.
XdrFileOArchive (std::string filename)
Constructor.
virtual ~XdrFileOArchive ()
Destructor.
void init (FILE *file)
Associate with an open file and initialize.
FILE * file ()
Get the underlying ifstream by reference.
template<typename T >
XdrFileOArchive & operator& (T &data)
Save one object.
template<typename T >
XdrFileOArchive & operator<< (T &data)
Save one object.
XDR * xdrPtr ()
Get a pointer to the enclosed XDR object.
Static Public Member Functions
static bool is_saving ()
Returns true;.
static bool is_loading ()
Returns false;.
Constructor & Destructor Documentation
Util::XdrFileOArchive::XdrFileOArchive ()
Constructor.
Definition at line 17 of file XdrFileOArchive.cpp.
Util::XdrFileOArchive::XdrFileOArchive (std::string filename)
Constructor.
Parameters
filename name of file to open for reading.
Definition at line 26 of file XdrFileOArchive.cpp.
References UTIL_THROW.
Util::XdrFileOArchive::~XdrFileOArchive () virtual
Destructor.
Definition at line 43 of file XdrFileOArchive.cpp.
Member Function Documentation
bool Util::XdrFileOArchive::is_saving () inline static
Returns true;.
Definition at line 111 of file XdrFileOArchive.h.
bool Util::XdrFileOArchive::is_loading () inline static
Returns false;.
Definition at line 114 of file XdrFileOArchive.h.
void Util::XdrFileOArchive::init (FILE * file)
Associate with an open file and initialize.
Parameters
file C file handle, must be open for writing.
Definition at line 49 of file XdrFileOArchive.cpp.
References file(), and xdrPtr().
FILE * Util::XdrFileOArchive::file () inline
Get the underlying ifstream by reference.
Definition at line 142 of file XdrFileOArchive.h.
Referenced by init().
template<typename T > XdrFileOArchive & Util::XdrFileOArchive::operator& (T & data) inline
Save one object.
Definition at line 123 of file XdrFileOArchive.h.
template<typename T > XdrFileOArchive & Util::XdrFileOArchive::operator<< (T & data) inline
Save one object.
Definition at line 133 of file XdrFileOArchive.h.
XDR * Util::XdrFileOArchive::xdrPtr () inline
Get a pointer to the enclosed XDR object.
Definition at line 148 of file XdrFileOArchive.h.
References xdrPtr().
Referenced by init(), and xdrPtr().
The documentation for this class was generated from the following files:
XdrFileOArchive.h
XdrFileOArchive.cpp