Simpatico: McMd::Diblock Class Reference
McMd::Diblock Class Reference
Species
Detailed Description
A linear diblock copolymer chain.
In this implementation, all of the bonds have the same type Id.
Definition at line 25 of file Diblock.h.
#include <Diblock.h>
Public Member Functions
Diblock ()
Default constructor.
virtual ~Diblock ()
Destructor.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
Public Member Functions inherited from McMd::Linear
Linear ()
Constructor.
virtual ~Linear ()
Destructor.
virtual void generateMolecules (int nMolecule, DArray< double > exclusionRadius, System &system, BondPotential *bondPotentialPtr, const Boundary &boundary)
Generate random molecules.
Public Member Functions inherited from McMd::Species
Species ()
Constructor.
virtual ~Species ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters and allocate molecules for this species.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
void setId (int id)
Set integer id for this Species.
int nAtom () const
Get number of atoms per molecule for this Species.
int nBond () const
Get number of bonds per molecule for this Species.
int nAngle () const
Get number of angles per molecule for this Species.
int nDihedral () const
Get number of dihedrals per molecule for this Species.
int atomTypeId (int iAtom) const
Get atom type index for a specific atom, by local atom index.
const SpeciesBond & speciesBond (int iBond) const
Get a specific SpeciesBond object, by local bond index.
void getAtomBonds (const Atom &atom, AtomBondArray &bonds) const
Get array of pointers to Bonds that contain an Atom.
const SpeciesAngle & speciesAngle (int iAngle) const
Get a specific SpeciesAngle object, by local angle index.
void getAtomAngles (const Atom &atom, AtomAngleArray &angles) const
Get array of pointers to Angles that contain an Atom.
const SpeciesDihedral & speciesDihedral (int iDihedral) const
Get a specific SpeciesDihedral object, by local angle index.
void getAtomDihedrals (const Atom &atom, AtomDihedralArray &dihedrals) const
Get array of pointers to Dihedrals that contain an Atom.
int id () const
Get integer id of this Species.
int capacity () const
Get total number of Molecule objects allocated for this Species.
Reservoir & reservoir ()
Get the reservoir for this Species by reference.
bool isValid () const
Return true if Species is valid, or throw an Exception.
bool isMutable () const
Is this a mutable Species?
SpeciesMutator & mutator ()
Return the species mutator object by reference.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
virtual void readSpeciesParam (std::istream &in)
Read block lengths length and and types.
virtual void loadSpeciesParam (Serializable::IArchive &ar)
Load species structure from an Archive.
virtual int calculateAtomTypeId (int index) const
Return the atom type for a specific atom.
virtual int calculateBondTypeId (int index) const
Return same bond type for any bond in any chain.
virtual int calculateAngleTypeId (int index) const
Return same angle type for any angle in any chain.
virtual int calculateDihedralTypeId (int index) const
Return same dihedral type for any dihedral in any chain.
Protected Member Functions inherited from McMd::Linear
void buildLinear ()
Build the chemical structure for a linear molecule.
Protected Member Functions inherited from McMd::Species
void allocate ()
Allocate chemical structure arrays.
void setAtomType (int atomId, int atomType)
Set the type for one atom in a generic molecule of this Species.
void makeBond (int bondId, int atomId1, int atomId2, int bondType)
Add a bond to the chemical structure of a generic molecule.
void makeAngle (int angleId, int atomId1, int atomId2, int atomId3, int angleType)
Add an angle to the chemical structure of a generic molecule.
void makeDihedral (int dihedralId, int atomId1, int atomId2, int atomId3, int atomId4, int dihedralType)
Add a dihedral to the chemical structure of a generic molecule.
void setMutatorPtr (SpeciesMutator *mutatorPtr)
Set a pointer to an associated SpeciesMutator for a mutable species.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
int blockLengths_ [2]
Number of particles in each block.
int atomTypes_ [2]
Particle type ids for each block.
Protected Attributes inherited from McMd::Linear
int hasAngles_
Does this chain have angle potentials (0 = false, 1 = true).
int hasDihedrals_
Does this chain have dihedral potentials (0 = false, 1 = true).
Protected Attributes inherited from McMd::Species
DArray< int > atomTypeIds_
Array of atom type Ids, indexed by local atom id.
DArray< SpeciesBond > speciesBonds_
Array of SpeciesBonds for all bonds, indexed by local bond id.
DArray< SpeciesAngle > speciesAngles_
Array of SpeciesAngles for all angles, indexed by local angle id.
DArray< SpeciesDihedral > speciesDihedrals_
Array of SpeciesDihedrals for all dihedrals, indexed by local dihedral id.
int nAtom_
Number of atoms per molecule.
int nBond_
Number of bonds per molecule.
int nAngle_
Number of angles per molecule.
int nDihedral_
Number of dihedrals per molecule.
int moleculeCapacity_
Number of molecules associated with the species.
int id_
Integer index for this Species.
Additional Inherited Members
Public Types inherited from McMd::Species
typedef SpeciesGroup< 2 > SpeciesBond
A SpeciesBond has the local atom ids and a type id for one bond.
typedef FSArray< const Bond
*, MaxBondPerAtom > AtomBondArray
Array of pointers to Bond objects that contain a specific Atom.
typedef SpeciesGroup< 3 > SpeciesAngle
A SpeciesAngle has the local atom ids and a type id for an angle.
typedef FSArray< const Angle
*, MaxAnglePerAtom > AtomAngleArray
Array of pointers to Angle objects that contain a specific Atom.
typedef SpeciesGroup< 4 > SpeciesDihedral
A SpeciesDihedral has the local atom ids and a type id for an angle.
typedef FSArray< const
Dihedral *, MaxDihedralPerAtom > AtomDihedralArray
Array of pointers to Angle objects that contain a specific Atom.
typedef ArrayStack< Molecule > Reservoir
A stack of unused Molecule objects available for this Species.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Public Attributes inherited from McMd::Species
static const int MaxBondPerAtom = 4
Maximum number of bonds that can be connected to one atom.
static const int MaxAnglePerAtom = 18
Maximum number of angles groups that can contain one atom.
static const int MaxDihedralPerAtom = 72
Maximum number of dihedral groups that can contain one atom.
Protected Types inherited from McMd::Species
typedef FSArray< int,
MaxBondPerAtom > AtomBondIdArray
An array of local integer bond ids for all bonds containing one atom.
typedef FSArray< int,
MaxAnglePerAtom > AtomAngleIdArray
An array of local integer angle ids for all angles containing one atom.
typedef FSArray< int,
MaxDihedralPerAtom > AtomDihedralIdArray
An array of local integer angle ids for all dihedrals containing one atom.
Static Protected Attributes inherited from McMd::Species
static const int NullIndex = -1
Null (unknown) value for any non-negative index.
Constructor & Destructor Documentation
McMd::Diblock::Diblock ()
Default constructor.
Definition at line 22 of file Diblock.cpp.
References atomTypes_, blockLengths_, McMd::Species::NullIndex, and Util::ParamComposite::setClassName().
virtual McMd::Diblock::~Diblock () inline virtual
Destructor.
Definition at line 34 of file Diblock.h.
Member Function Documentation
void McMd::Diblock::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from McMd::Species.
Definition at line 139 of file Diblock.cpp.
References atomTypes_, blockLengths_, McMd::Linear::hasAngles_, McMd::Linear::hasDihedrals_, McMd::Species::moleculeCapacity_, McMd::Species::nAngle_, McMd::Species::nDihedral_, Util::BinaryFileOArchive::pack(), and Util::Parameter::saveOptional().
void McMd::Diblock::readSpeciesParam (std::istream & in) protected virtual
Read block lengths length and and types.
Parameters
in input stream
Reimplemented from McMd::Species.
Definition at line 41 of file Diblock.cpp.
References atomTypes_, blockLengths_, McMd::Linear::buildLinear(), McMd::Linear::hasAngles_, McMd::Linear::hasDihedrals_, McMd::Species::nAngle_, McMd::Species::nAtom_, McMd::Species::nBond_, McMd::Species::nDihedral_, and UTIL_THROW.
void McMd::Diblock::loadSpeciesParam (Serializable::IArchive & ar) protected virtual
Load species structure from an Archive.
Parameters
ar input/loading archive
Reimplemented from McMd::Species.
Definition at line 89 of file Diblock.cpp.
References atomTypes_, blockLengths_, McMd::Linear::buildLinear(), McMd::Linear::hasAngles_, McMd::Linear::hasDihedrals_, McMd::Species::nAngle_, McMd::Species::nAtom_, McMd::Species::nBond_, McMd::Species::nDihedral_, and UTIL_THROW.
int McMd::Diblock::calculateAtomTypeId (int index) const protected virtual
Return the atom type for a specific atom.
Parameters
index index of atom within the molecule
Returns
atom type for the specified atom
Implements McMd::Linear.
Definition at line 162 of file Diblock.cpp.
References atomTypes_, and blockLengths_.
int McMd::Diblock::calculateBondTypeId (int index) const protected virtual
Return same bond type for any bond in any chain.
Parameters
index index of bond within the molecule
Returns
bond type index for the specified bond
Implements McMd::Linear.
Definition at line 174 of file Diblock.cpp.
int McMd::Diblock::calculateAngleTypeId (int index) const protected virtual
Return same angle type for any angle in any chain.
Parameters
index angle index, in range 0, ..., nAngle_ - 1
Returns
bond type index
Implements McMd::Linear.
Definition at line 181 of file Diblock.cpp.
int McMd::Diblock::calculateDihedralTypeId (int index) const protected virtual
Return same dihedral type for any dihedral in any chain.
Parameters
index dihedral index, in range 0, ..., nDihedral_ - 1
Returns
dihedral type index
Implements McMd::Linear.
Definition at line 189 of file Diblock.cpp.
Member Data Documentation
int McMd::Diblock::blockLengths_[2] protected
Number of particles in each block.
Definition at line 47 of file Diblock.h.
Referenced by calculateAtomTypeId(), Diblock(), loadSpeciesParam(), readSpeciesParam(), and save().
int McMd::Diblock::atomTypes_[2] protected
Particle type ids for each block.
Definition at line 50 of file Diblock.h.
Referenced by calculateAtomTypeId(), Diblock(), loadSpeciesParam(), readSpeciesParam(), and save().
The documentation for this class was generated from the following files:
Diblock.h
Diblock.cpp