Simpatico: Util::CArray2DParam< Type > Class Template Reference
Util::CArray2DParam< Type > Class Template Reference
Parameter File IO
Detailed Description
template<class Type>
class Util::CArray2DParam< Type >
A Parameter associated with a 2D built-in C array.
Definition at line 31 of file CArray2DParam.h.
#include <CArray2DParam.h>
Public Member Functions
CArray2DParam (const char *label, Type *value, int m, int n)
Constructor.
void readParam (std::istream &in)
Read 2D array from file.
void writeParam (std::ostream &out)
Write 2D C array to file.
void load (Serializable::IArchive &ar)
Load 2D C array from archive.
void save (Serializable::OArchive &ar)
Save 2D C array to an archive.
Public Member Functions inherited from Util::Parameter
Parameter (const char *label)
Constructor.
virtual ~Parameter ()
Destructor.
std::string label ()
Return label string.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
virtual void resetParam ()
Nontrivial implementation provided by ParamComposite subclass.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have a communicator?
MPI::Intracomm & ioCommunicator () const
Get the communicator.
Protected Attributes
Type * value_
Pointer to first element in associated 1D C array.
int m_
Number of rows in array[m][n].
int n_
Number of columns in array[m][n].
Protected Attributes inherited from Util::Parameter
Label label_
Label object that contains parameter label string.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Public Attributes inherited from Util::Parameter
static const int Width = 20
Width of data field for a scalar variable (numerical or string).
static const int Precision = 12
Precision for io of floating point data field.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Constructor & Destructor Documentation
template<class Type > Util::CArray2DParam< Type >::CArray2DParam (const char * label, Type * value, int m, int n)
Constructor.
Example:
double                matrix[3][2];
CArray2DParam<double> param("matrix", matrix[0], 3, 2);
Parameters
label parameter label (usually a literal C-string)
value pointer to first element of associated 1D array
m number of rows
n number of columns
Definition at line 94 of file CArray2DParam.h.
Member Function Documentation
template<class Type > void Util::CArray2DParam< Type >::readParam (std::istream & in) virtual
Read 2D array from file.
Implements Util::ParamComponent.
Definition at line 105 of file CArray2DParam.h.
References Util::ParamComponent::echo(), and Util::Log::file().
Referenced by Util::ParamComposite::readCArray2D().
template<class Type > void Util::CArray2DParam< Type >::writeParam (std::ostream & out) virtual
Write 2D C array to file.
Implements Util::ParamComponent.
Definition at line 130 of file CArray2DParam.h.
References Util::Parameter::Precision, and Util::Parameter::Width.
template<class Type > void Util::CArray2DParam< Type >::load (Serializable::IArchive & ar) virtual
Load 2D C array from archive.
Parameters
ar loading (input) archive.
Reimplemented from Util::ParamComponent.
Definition at line 155 of file CArray2DParam.h.
References Util::ParamComponent::echo(), and Util::Log::file().
Referenced by Util::ParamComposite::loadCArray2D().
template<class Type > void Util::CArray2DParam< Type >::save (Serializable::OArchive & ar) virtual
Save 2D C array to an archive.
Parameters
ar saving (output) archive.
Reimplemented from Util::ParamComponent.
Definition at line 179 of file CArray2DParam.h.
Member Data Documentation
template<class Type> Type* Util::CArray2DParam< Type >::value_ protected
Pointer to first element in associated 1D C array.
Definition at line 79 of file CArray2DParam.h.
template<class Type> int Util::CArray2DParam< Type >::m_ protected
Number of rows in array[m][n].
Definition at line 82 of file CArray2DParam.h.
template<class Type> int Util::CArray2DParam< Type >::n_ protected
Number of columns in array[m][n].
Definition at line 85 of file CArray2DParam.h.
The documentation for this class was generated from the following file:
CArray2DParam.h