Simpatico: McMd::BondPotential Class Reference
McMd::BondPotential Class Reference
Bond Potentials
Detailed Description
Abstract Bond Potential class.
Definition at line 34 of file mcMd/potentials/bond/BondPotential.h.
#include <BondPotential.h>
Public Member Functions
BondPotential ()
Constructor .
virtual ~BondPotential ()
Destructor (does nothing)
Bond Interaction Interface
virtual double energy (double rSq, int type) const =0
Returns potential energy for one bond.
virtual double forceOverR (double rSq, int type) const =0
Returns force/distance for one bond, for use in MD.
virtual double randomBondLength (Util::Random *random, double beta, int type) const =0
Return bond length chosen from equilibrium distribution.
virtual void set (std::string name, int type, double value)=0
Modify an interaction parameter, identified by a string.
virtual double get (std::string name, int type) const =0
Get an interaction parameter value, identified by a string.
virtual std::string interactionClassName () const =0
Return name of pair interaction class (e.g., "HarmonicBond").
System energy, force, and stress.
virtual double atomEnergy (const Atom &atom) const =0
Calculate the covalent bond energy for one Atom.
virtual void addForces ()=0
Add bond forces to all atomic forces.
virtual double energy () const =0
Calculate the total nonBonded pair energy for the associated System.
virtual void computeStress (double &stress) const =0
Compute total nonbonded pressure.
virtual void computeStress (Util::Vector &stress) const =0
Compute x, y, z nonbonded pressures.
virtual void computeStress (Util::Tensor &stress) const =0
Compute stress tensor.
Constructor & Destructor Documentation
McMd::BondPotential::BondPotential ()
Constructor .
Constructor.
Definition at line 16 of file mcMd/potentials/bond/BondPotential.cpp.
References Util::ParamComposite::setClassName().
McMd::BondPotential::~BondPotential () [virtual]
Destructor (does nothing)
Definition at line 23 of file mcMd/potentials/bond/BondPotential.cpp.
Member Function Documentation
virtual double McMd::BondPotential::energy (double rSq, int type) const [pure virtual]
Returns potential energy for one bond.
Parameters:
rSq square of distance between bonded particles.
type type of bond.
Implemented in McMd::BondPotentialImpl< Interaction >, and McMd::LinkPotentialImpl< Interaction >.
Referenced by McMd::CfbEndBase::addEndAtom(), McMd::CfbRebridgeBase::addMiddleAtom(), McMd::CfbEndBase::deleteEndAtom(), McMd::CfbRebridgeBase::deleteMiddleAtom(), McMd::GroupRebridgeBase::octaEnergy(), McMd::McSystem::potentialEnergy(), McMd::MdSystem::potentialEnergy(), McMd::McNVTChemicalPotential::sample(), McMd::MdEnergyOutput::sample(), McMd::McEnergyOutput::sample(), and McMd::GroupRebridgeBase::tetraEnergy().
virtual double McMd::BondPotential::forceOverR (double rSq, int type) const [pure virtual]
Returns force/distance for one bond, for use in MD.
A positive return value represents a repulsive radial force.
Parameters:
rSq square of distance between bonded particles.
type type of bond.
Returns:
scalar repulsive force divided by distance.
Implemented in McMd::BondPotentialImpl< Interaction >, and McMd::LinkPotentialImpl< Interaction >.
virtual double McMd::BondPotential::randomBondLength (Util::Random * random, double beta, int type) const [pure virtual]
Return bond length chosen from equilibrium distribution.
This function returns a bond length chosen from the Boltzmann distribution of lengths for bonds of random orientation. The distribution P(l) of values of the length l is proportional to l*l*exp[-beta*phi(l) ], where phi(l) is the bond energy.
Parameters:
random pointer to random number generator object.
beta inverse temperature
type bond type
Returns:
bond length chosen from equilibrium distribution.
Implemented in McMd::BondPotentialImpl< Interaction >, and McMd::LinkPotentialImpl< Interaction >.
Referenced by McMd::CfbEndBase::addEndAtom(), and McMd::McNVTChemicalPotential::sample().
virtual void McMd::BondPotential::set (std::string name, int type, double value) [pure virtual]
Modify an interaction parameter, identified by a string.
Parameters:
name parameter name
type bond type index
value new value of parameter
Implemented in McMd::BondPotentialImpl< Interaction >, and McMd::LinkPotentialImpl< Interaction >.
Referenced by McMd::MdSimulation::readCommands(), and McMd::McSimulation::readCommands().
virtual double McMd::BondPotential::get (std::string name, int type) const [pure virtual]
Get an interaction parameter value, identified by a string.
Parameters:
name parameter name
type bond type index 1
Implemented in McMd::BondPotentialImpl< Interaction >, and McMd::LinkPotentialImpl< Interaction >.
virtual std::string McMd::BondPotential::interactionClassName () const [pure virtual]
Return name of pair interaction class (e.g., "HarmonicBond").
Implemented in McMd::BondPotentialImpl< Interaction >, and McMd::LinkPotentialImpl< Interaction >.
virtual double McMd::BondPotential::atomEnergy (const Atom & atom) const [pure virtual]
Calculate the covalent bond energy for one Atom.
Parameters:
atom Atom object of interest
Returns:
bond potential energy of atom
Implemented in McMd::BondPotentialImpl< Interaction >, and McMd::LinkPotentialImpl< Interaction >.
Referenced by McMd::McSystem::atomPotentialEnergy().
virtual void McMd::BondPotential::addForces () [pure virtual]
Add bond forces to all atomic forces.
Implemented in McMd::BondPotentialImpl< Interaction >, and McMd::LinkPotentialImpl< Interaction >.
Referenced by McMd::MdSystem::calculateForces().
virtual double McMd::BondPotential::energy () const [pure virtual]
Calculate the total nonBonded pair energy for the associated System.
Implemented in McMd::BondPotentialImpl< Interaction >, and McMd::LinkPotentialImpl< Interaction >.
virtual void McMd::BondPotential::computeStress (double & stress) const [pure virtual]
Compute total nonbonded pressure.
Parameters:
stress (output) pressure.
Implemented in McMd::BondPotentialImpl< Interaction >, and McMd::LinkPotentialImpl< Interaction >.
virtual void McMd::BondPotential::computeStress (Util::Vector & stress) const [pure virtual]
Compute x, y, z nonbonded pressures.
Parameters:
stress (output) pressures.
Implemented in McMd::BondPotentialImpl< Interaction >, and McMd::LinkPotentialImpl< Interaction >.
virtual void McMd::BondPotential::computeStress (Util::Tensor & stress) const [pure virtual]
Compute stress tensor.
Parameters:
stress (output) pressures.
Implemented in McMd::BondPotentialImpl< Interaction >, and McMd::LinkPotentialImpl< Interaction >.
The documentation for this class was generated from the following files:
mcMd/potentials/bond/BondPotential.h
mcMd/potentials/bond/BondPotential.cpp