Simpatico: McMd::ExternalPotential Class Reference
McMd::ExternalPotential Class Reference abstract
External Potentials
Detailed Description
Abstract External Potential class.
Definition at line 35 of file mcMd/potentials/external/ExternalPotential.h.
#include <ExternalPotential.h>
Public Member Functions
ExternalPotential ()
Constructor .
virtual ~ExternalPotential ()
Destructor (does nothing)
virtual void addForces ()=0
Add external force of an Atom to the total force acting on it.
virtual double energy () const =0
Return total external energy of this System.
virtual double atomEnergy (const Atom &atom) const =0
Calculate the external energy for one Atom.
virtual std::string interactionClassName () const =0
Return name of external interaction class (e.g., "LamellarOrderingExternal").
virtual double energy (const Vector &position, int i) const =0
Returns external potential energy of a single particle.
virtual void getForce (const Vector &position, int type, Vector &force) const =0
Returns force caused by the external potential.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
std::string className () const
Get class name string.
virtual void readParam (std::istream &in)
Read a parameter file block.
virtual void readParameters (std::istream &in)
Read body of parameter block, without opening and closing lines.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an archive.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void resetParam ()
Resets ParamComposite to its empty state.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add a new Param < Type > object, and read its value.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add a C array parameter, and read its elements.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and read its elements.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n)
Add and read a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
Begin & readBegin (std::istream &in, const char *label)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a child ParamComposite.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add a new Param < Type > object, and load its value.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add a C array parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and load its elements.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n)
Add and load a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a DMatrix < Type > C two-dimensional matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
template<typename Type >
ScalarParam< Type > & add (const char *label, Type &value)
Add a new Param < Type > object to the format array.
template<typename Type >
CArrayParam< Type > & addCArray (const char *label, Type *value, int n)
Add a C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (const char *label, DArray< Type > &array, int n)
Add a DArray<Type> parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (const char *label, FArray< Type, N > &array)
Add a FArray<Type> parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (const char *label, Type *value, int m, int n)
Add a C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & addDMatrix (const char *label, DMatrix< Type > &matrix, int m, int n)
Add a C two-dimensional array parameter.
Begin & addBegin (const char *label)
Add a class label and opening bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Add a new Blank object, representing a blank line.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have a communicator?
MPI::Intracomm & ioCommunicator () const
Get the communicator.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
Constructor & Destructor Documentation
McMd::ExternalPotential::ExternalPotential () inline
Constructor .
Definition at line 43 of file mcMd/potentials/external/ExternalPotential.h.
virtual McMd::ExternalPotential::~ExternalPotential () inline virtual
Destructor (does nothing)
Definition at line 49 of file mcMd/potentials/external/ExternalPotential.h.
Member Function Documentation
virtual double McMd::ExternalPotential::energy (const Vector & position, int i) const pure virtual
Returns external potential energy of a single particle.
Parameters
position atomic position Vector
i atom type.
Returns
external potential energy
Implemented in McMd::ExternalPotentialImpl< Interaction >.
Referenced by McMd::McSystem::potentialEnergy(), McMd::MdSystem::potentialEnergy(), McMd::McExternalEnergyAverage::sample(), McMd::MdEnergyOutput::sample(), and McMd::McEnergyOutput::sample().
virtual void McMd::ExternalPotential::getForce (const Vector & position, int type, Vector & force) const pure virtual
Returns force caused by the external potential.
Parameters
position atom position
type atom type id
force force on the atom (on output)
Implemented in McMd::ExternalPotentialImpl< Interaction >.
virtual void McMd::ExternalPotential::addForces () pure virtual
Add external force of an Atom to the total force acting on it.
Implemented in McMd::ExternalPotentialImpl< Interaction >.
Referenced by McMd::MdSystem::calculateForces().
virtual double McMd::ExternalPotential::energy () const pure virtual
Return total external energy of this System.
Implemented in McMd::ExternalPotentialImpl< Interaction >.
virtual double McMd::ExternalPotential::atomEnergy (const Atom & atom) const pure virtual
Calculate the external energy for one Atom.
Implemented in McMd::ExternalPotentialImpl< Interaction >.
Referenced by McMd::CfbEndBase::addEndAtom(), McMd::CfbRebridgeBase::addMiddleAtom(), McMd::McSystem::atomPotentialEnergy(), McMd::CfbEndBase::deleteEndAtom(), McMd::CfbRebridgeBase::deleteMiddleAtom(), McMd::EndSwapMove::move(), and McMd::RigidDisplaceMove::move().
virtual std::string McMd::ExternalPotential::interactionClassName () const pure virtual
Return name of external interaction class (e.g., "LamellarOrderingExternal").
Implemented in McMd::ExternalPotentialImpl< Interaction >.
The documentation for this class was generated from the following file:
mcMd/potentials/external/ExternalPotential.h