Simpatico: Tools::ConfigWriter Class Reference
Tools::ConfigWriter Class Reference
Detailed Description
Abstract reader/writer for configuration files.
Each concrete subclass of ConfigWriter implements a specific file format by implementing the pure virtual readConfig and writeConfig methods.
Definition at line 27 of file tools/config/ConfigWriter.h.
#include <ConfigWriter.h>
Public Member Functions
ConfigWriter ()
Default constructor.
ConfigWriter (Configuration &configuration, bool needsAuxiliaryFile=false)
Constructor.
virtual ~ConfigWriter ()
Destructor.
virtual void writeConfig (std::ofstream &file)=0
Write configuration file.
bool needsAuxiliaryFile () const
Return true if an auxiliary file is needed.
virtual void readAuxiliaryFile (std::ifstream &file)
Read auxiliary file (empty default implementation).
Constructor & Destructor Documentation
Tools::ConfigWriter::ConfigWriter ()
Default constructor.
Definition at line 18 of file tools/config/ConfigWriter.cpp.
References Util::ParamComposite::setClassName().
Tools::ConfigWriter::ConfigWriter (Configuration & configuration, bool needsAuxiliaryFile = false)
Constructor.
Parameters:
configuration parent Configuration object
needsAuxiliaryFile Does this class need to read an auxiliary file?
Definition at line 25 of file tools/config/ConfigWriter.cpp.
References Util::ParamComposite::setClassName().
Tools::ConfigWriter::~ConfigWriter () [virtual]
Destructor.
Definition at line 33 of file tools/config/ConfigWriter.cpp.
Member Function Documentation
virtual void Tools::ConfigWriter::writeConfig (std::ofstream & file) [pure virtual]
Write configuration file.
Parameters:
file output file
Implemented in Tools::DdMdConfigWriter, and Tools::HoomdConfigWriter.
Referenced by Tools::Processor::readCommands(), and Tools::Processor::writeConfig().
bool Tools::ConfigWriter::needsAuxiliaryFile () const [inline]
Return true if an auxiliary file is needed.
Definition at line 89 of file tools/config/ConfigWriter.h.
virtual void Tools::ConfigWriter::readAuxiliaryFile (std::ifstream & file) [inline, virtual]
Read auxiliary file (empty default implementation).
Parameters:
file auxiliary file, open for reading.
Reimplemented in Tools::HoomdConfigWriter.
Definition at line 67 of file tools/config/ConfigWriter.h.
Referenced by Tools::Processor::readCommands().
The documentation for this class was generated from the following files:
tools/config/ConfigWriter.h
tools/config/ConfigWriter.cpp