Simpatico: McMd::McExternalPerturbation< Interaction > Class Template Reference
McMd::McExternalPerturbation< Interaction > Class Template Reference
Free Energy Perturbation
Detailed Description
template<class Interaction>
class McMd::McExternalPerturbation< Interaction >
A Perturbation in the external potential external parameter.
An McExternalPerturbation describes a Hamiltonian with a variable external parameter.
Definition at line 37 of file McExternalPerturbation.h.
#include <McExternalPerturbation.h>
Public Member Functions
McExternalPerturbation (McSystem &system, int size, int rank)
Constructor.
virtual ~McExternalPerturbation ()
Destructor.
virtual void readParameters (std::istream &in)
Read external parameter from file.
virtual void setParameter ()
Set external parameter for this System.
virtual double parameter (int i) const
Return the external parameter for this System.
virtual double derivative (int i) const
Return external potential energy / (kT *external parameter)
Interaction & interaction () const
Return the external potential interaction.
Public Member Functions inherited from McMd::LinearPerturbation< McSystem >
LinearPerturbation (McSystem &system, int size, int rank)
Constructor.
virtual ~LinearPerturbation ()
Destructor.
virtual double difference (DArray< double > iPartnerParameter) const
Returns the difference W(partner) - W(current).
McSystem & system () const
Get the associated System by reference.
Public Member Functions inherited from McMd::Perturbation
Perturbation (int size, int rank)
Constructor.
virtual ~Perturbation ()
Destructor.
void readParameters (std::istream &in)
Read perturbation parameter(s) from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void setParameter (DArray< double > parameter)
Sets the perturbation parameter value.
double parameter (int i, int id)
Get parameter i of system id.
int getNParameters () const
Gets the number of parameters per system.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Attributes inherited from McMd::Perturbation
int size_
Number of systems (e.g., communicator size)
int rank_
Index for this system (e.g., communicator size)
int nParameters_
Number of perturbation parameters associated with a System.
int mode_
mode 0: parameters of all replica systems are specified.
DArray< double > parameter_
Value of the perturbation parameter for the associated System.
DArray< double > initialParameter_
Value of the perturbation parameter for the first replica System.
DArray< double > finalParameter_
Value of the perturbation parameter for the last replica System.
DMatrix< double > parameters_
Value of the perturbation parameter for all the replica Systems.
Constructor & Destructor Documentation
template<class Interaction > McMd::McExternalPerturbation< Interaction >::McExternalPerturbation (McSystem & system, int size, int rank)
Constructor.
Parameters
system parent McSystem.
size number of systems
rank id of this system
Definition at line 29 of file McExternalPerturbation.cpp.
template<class Interaction > McMd::McExternalPerturbation< Interaction >::~McExternalPerturbation< Interaction > () virtual
Destructor.
Definition at line 39 of file McExternalPerturbation.cpp.
Member Function Documentation
template<class Interaction > void McMd::McExternalPerturbation< Interaction >::readParameters (std::istream & in) virtual
Read external parameter from file.
Parameters
in input stream (file or std in).
Reimplemented from Util::ParamComposite.
Definition at line 46 of file McExternalPerturbation.cpp.
References McMd::Perturbation::getNParameters(), and McMd::Perturbation::readParameters().
template<class Interaction > void McMd::McExternalPerturbation< Interaction >::setParameter () virtual
Set external parameter for this System.
Implements McMd::Perturbation.
Definition at line 73 of file McExternalPerturbation.cpp.
template<class Interaction > double McMd::McExternalPerturbation< Interaction >::parameter (int i) const virtual
Return the external parameter for this System.
Parameters
i index of the perturbation parameter. In this case, i is always 0 since nParameters = 1.
Implements McMd::Perturbation.
Definition at line 82 of file McExternalPerturbation.cpp.
References UTIL_THROW.
template<class Interaction > double McMd::McExternalPerturbation< Interaction >::derivative (int i) const virtual
Return external potential energy / (kT *external parameter)
Parameters
i index of the perturbation parameter. In this case, i is always 0 since nParameters = 1.
Implements McMd::Perturbation.
Definition at line 94 of file McExternalPerturbation.cpp.
References Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), and UTIL_THROW.
template<class Interaction > Interaction & McMd::McExternalPerturbation< Interaction >::interaction () const
Return the external potential interaction.
Definition at line 55 of file McExternalPerturbation.cpp.
References McMd::ExternalPotentialImpl< Interaction >::interaction(), and UTIL_THROW.
The documentation for this class was generated from the following files:
McExternalPerturbation.h
McExternalPerturbation.cpp