Simpatico: McMd::AtomMSD Class Reference
McMd::AtomMSD Class Reference
Analyzers
Detailed Description
Autocorrelation for vector separation of two atoms on a molecule.
See also:
parameter file format
Definition at line 28 of file mcMd/analyzers/system/AtomMSD.h.
#include <AtomMSD.h>
Public Member Functions
AtomMSD (System &system)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Determine number of molecules and allocate memory.
virtual void sample (long iStep)
Evaluate end-to-end vectors of all chains, add to ensemble.
virtual void output ()
Output results to file after simulation is completed.
Constructor & Destructor Documentation
McMd::AtomMSD::AtomMSD (System & system)
Constructor.
Parameters:
system reference to parent System
Definition at line 30 of file mcMd/analyzers/system/AtomMSD.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::AtomMSD::readParameters (std::istream & in) [virtual]
Read parameters from file.
Parameters:
in input parameter stream
Reimplemented from McMd::Analyzer.
Definition at line 47 of file mcMd/analyzers/system/AtomMSD.cpp.
References Util::DArray< Data >::allocate(), McMd::Species::capacity(), McMd::Species::nAtom(), McMd::Analyzer::readInterval(), McMd::Analyzer::readOutputFileName(), Util::MeanSqDispArray< Data >::setParam(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemAnalyzer< System >::system(), and UTIL_THROW.
void McMd::AtomMSD::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from McMd::Analyzer.
Definition at line 89 of file mcMd/analyzers/system/AtomMSD.cpp.
References Util::DArray< Data >::allocate(), McMd::Species::capacity(), McMd::Analyzer::loadInterval(), McMd::Analyzer::loadOutputFileName(), McMd::Species::nAtom(), Util::MeanSqDispArray< Data >::setParam(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemAnalyzer< System >::system(), and UTIL_THROW.
void McMd::AtomMSD::save (Serializable::OArchive & ar) [virtual]
Save state to archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::Analyzer.
Definition at line 135 of file mcMd/analyzers/system/AtomMSD.cpp.
template<class Archive > void McMd::AtomMSD::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Analyzer.
Definition at line 126 of file mcMd/analyzers/system/AtomMSD.h.
References McMd::serialize().
void McMd::AtomMSD::setup () [virtual]
Determine number of molecules and allocate memory.
Reimplemented from McMd::Analyzer.
Definition at line 141 of file mcMd/analyzers/system/AtomMSD.cpp.
References McMd::Molecule::atom(), McMd::System::boundary(), Util::MeanSqDispArray< Data >::clear(), McMd::System::molecule(), McMd::System::nMolecule(), McMd::Atom::position(), Util::MeanSqDispArray< Data >::setNEnsemble(), Util::OrthorhombicBoundary::shift(), McMd::SystemAnalyzer< System >::system(), and UTIL_THROW.
void McMd::AtomMSD::sample (long iStep) [virtual]
Evaluate end-to-end vectors of all chains, add to ensemble.
Parameters:
iStep counter for number of steps
Implements McMd::Analyzer.
Definition at line 166 of file mcMd/analyzers/system/AtomMSD.cpp.
References McMd::Molecule::atom(), McMd::System::boundary(), Util::Dimension, Util::OrthorhombicBoundary::distanceSq(), McMd::Analyzer::isAtInterval(), Util::OrthorhombicBoundary::lengths(), McMd::System::molecule(), McMd::Atom::position(), Util::MeanSqDispArray< Data >::sample(), Util::OrthorhombicBoundary::shift(), McMd::SystemAnalyzer< System >::system(), and UTIL_THROW.
void McMd::AtomMSD::output () [virtual]
Output results to file after simulation is completed.
Reimplemented from McMd::Analyzer.
Definition at line 207 of file mcMd/analyzers/system/AtomMSD.cpp.
References Util::MeanSqDispArray< Data >::bufferCapacity(), McMd::Analyzer::fileMaster(), Util::MeanSqDispArray< Data >::nEnsemble(), Util::MeanSqDispArray< Data >::nSample(), Util::FileMaster::openOutputFile(), Util::MeanSqDispArray< Data >::output(), McMd::Analyzer::outputFileName(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
mcMd/analyzers/system/AtomMSD.h
mcMd/analyzers/system/AtomMSD.cpp