Simpatico: DdMd::FileMaster Class Reference
DdMd::FileMaster Class Reference
Detailed Description
A FileMaster manages a set of input and output files.
A FileMaster manages a set of input and output files in which all input file paths share a common input prefix and all output file paths share a common output prefix. The openInputFile() and openOutputFile() methods each open a file using a path that is constructed by prepending the input or output prefix, respectively, to a filename string parameter. A FileMaster also provides access to a separate parameter file.
The input and output prefix strings are read from file by the readParam() method. To use input files that are all in one directory and create output files in another, these prefix strings should be set to the desired directory names, followed by a trailing "/" directory separator. For example, to put all input and output files in directories named "in" and "out", the prefix strings should be set to "in/" and "out/", respectively.
The setDirectoryId(int rank) method is designed for use in parallel MPI programs, to allow files associated with different processors to be put in different directory trees. If this method is called with a rank parameter n, openInputFile() and openOutputFile() will thereafter prepend a string "n/" to all file paths before the inputPrefix and output prefix strings. Calling setDirectoryId(n) and placing prefixes "in/" and "out/" in the parameter file that is read by readParam thus causes the strings "n/in/" and "n/out/" to be prepended to the names of files opened by openInputFile() and openOutputFile().
The paramFile() method returns a default parameter input stream, using different conventions for serial and parallel operation. If no directory id has been set, as is normally the case for a serial program, paramFile() returns a reference to the standard input, std::cin. In parallel programs, if setDirectoryId() has been called, but setParamFileStdIn() has also been called, paramFile() again returns a reference to std::cin. If a directory id has been set by calling setDirectoryId() has been and setParamFileStdIn() has not be called, however, paramFile() returns a reference to a file named "n/param". This file is opened for reading the first time it is returned by paramFile(), and is closed by the FileMaster destructor.
Definition at line 67 of file ddMd/util/FileMaster.h.
#include <FileMaster.h>
Public Member Functions
FileMaster ()
Constructor.
FileMaster (const McMd::FileMaster &other)
Constructor.
FileMaster (const FileMaster &copy)
Copy constructor.
virtual ~FileMaster ()
Destructor.
void setRootPrefix (const std::string &rootPrefix)
Set the path from current directory to root data directory.
void setDirectoryId (int directoryId)
Set an integer directory identifier for this processor.
void setParamFileStdIn ()
Set paramFile() to return std::cin even if a directory id is set.
void setInputPrefix (const std::string &inputPrefix)
Set the input file prefix string.
void setOutputPrefix (const std::string &outputPrefix)
Set the output file prefix string.
void setCommandFileName (const std::string &commandFileName)
Set the command file name.
virtual void readParam (std::istream &in)
Read parameter file.
std::istream & paramFile ()
Get a default parameter stream by reference.
std::istream & commandFile ()
Get the command input stream by reference.
void openInputFile (const std::string &filename, std::ifstream &in) const
Open an input file named [directoryIdPrefix] + inputPrefix + filename.
void openOutputFile (const std::string &filename, std::ofstream &out) const
Open an output file named [directoryIdPrefix] + inputPrefix + filename.
void openParamIFile (const std::string &name, const char *ext, std::ifstream &in) const
Open an input restart parameter file.
void openParamOFile (const std::string &name, const char *ext, std::ofstream &out) const
Open a restart parameter file for writing.
void openRestartIFile (const std::string &name, const char *ext, std::ifstream &in) const
Open an input restart dump file.
void openRestartOFile (const std::string &name, const char *ext, std::ofstream &out) const
Open a restart dump file for writing.
std::string commandFileName () const
Return the command file name.
bool isParamFileStdIn () const
Is paramFile() set to return std::cin ?
Constructor & Destructor Documentation
home david code simpatico src ddMd util FileMaster cpp DdMd::FileMaster::FileMaster ()
Constructor.
Definition at line 24 of file ddMd/util/FileMaster.cpp.
DdMd::FileMaster::FileMaster (const McMd::FileMaster & other)
Constructor.
Definition at line 39 of file ddMd/util/FileMaster.cpp.
DdMd::FileMaster::FileMaster (const FileMaster & copy)
Copy constructor.
Parameters:
copy FileMaster object to be copied
Definition at line 54 of file ddMd/util/FileMaster.cpp.
DdMd::FileMaster::~FileMaster () [virtual]
Destructor.
Definition at line 66 of file ddMd/util/FileMaster.cpp.
Member Function Documentation
void DdMd::FileMaster::setRootPrefix (const std::string & rootPrefix)
Set the path from current directory to root data directory.
Parameters:
rootPrefix root prefix for all file names.
Definition at line 81 of file ddMd/util/FileMaster.cpp.
void DdMd::FileMaster::setDirectoryId (int directoryId)
Set an integer directory identifier for this processor.
This method should be called only for parallel operation. The directoryId is normally set to be the MPI rank of this processor. After calling setDirectoryId(n) with an integer n, a prefix "n/" will be prepended to the paths of all input and output file files that are opened by openInputFile() and openOutputFile().
Parameters:
directoryId integer directory name for input and output files.
Definition at line 87 of file ddMd/util/FileMaster.cpp.
void DdMd::FileMaster::setParamFileStdIn ()
Set paramFile() to return std::cin even if a directory id is set.
Definition at line 99 of file ddMd/util/FileMaster.cpp.
void DdMd::FileMaster::setInputPrefix (const std::string & inputPrefix)
Set the input file prefix string.
Parameters:
inputPrefix input file prefix string
Definition at line 105 of file ddMd/util/FileMaster.cpp.
void DdMd::FileMaster::setOutputPrefix (const std::string & outputPrefix)
Set the output file prefix string.
Parameters:
outputPrefix output file prefix string
Definition at line 111 of file ddMd/util/FileMaster.cpp.
void DdMd::FileMaster::setCommandFileName (const std::string & commandFileName)
Set the command file name.
Parameters:
commandFileName name of command file
Definition at line 117 of file ddMd/util/FileMaster.cpp.
References commandFileName().
void DdMd::FileMaster::readParam (std::istream & in) [virtual]
Read parameter file.
Reads the inputPrefix and outputPrefix string variables.
Parameters:
in pararameter file input stream
Reimplemented from Util::ParamComposite.
Definition at line 123 of file ddMd/util/FileMaster.cpp.
References Util::ParamComposite::readBegin(), and Util::ParamComposite::readEnd().
std::istream & DdMd::FileMaster::paramFile ()
Get a default parameter stream by reference.
If setDirectoryId() has not been called, of if setParamFileStdIn() has been called, this method returns std::cin.
If setDirectoryId() has been called and setParamFileStdInd() has not, this method returns a reference to a file "n/param". This file is opened for reading the first time it is returned by this method.
Definition at line 135 of file ddMd/util/FileMaster.cpp.
References UTIL_THROW.
Referenced by commandFile().
std::istream & DdMd::FileMaster::commandFile ()
Get the command input stream by reference.
If the commandFileName string is equal to the string literal "paramfile", this method returns the same stream as paramFile(). Otherwise, it returns a reference to a file whose name is given by the commandFileName string. If setDirectoryId(int) has not been called, the path to this file (absolute or relative to the working directory) is equal to the commandFileName string. If setDirectory() has been called with an integer argument n, the path to this file is obtained adding "n/" as a prefix to the commandFileName. In either case, if the commandFileName is not "paramfile", the required file is opened for reading the first time it is returned by this method.
Definition at line 172 of file ddMd/util/FileMaster.cpp.
References paramFile(), and UTIL_THROW.
void DdMd::FileMaster::openInputFile (const std::string & filename, std::ifstream & in) const
Open an input file named [directoryIdPrefix] + inputPrefix + filename.
The directoryIdPrefix "n/" is added as a prefix to the path name if and only if setDirectoryId(int) has been called with an argument n.
Parameters:
filename file name, without any prefix
in ifstream object to associated with a file
Definition at line 211 of file ddMd/util/FileMaster.cpp.
References UTIL_THROW.
void DdMd::FileMaster::openOutputFile (const std::string & filename, std::ofstream & out) const
Open an output file named [directoryIdPrefix] + inputPrefix + filename.
The directoryIdPrefix "n/" is added as a prefix to the path name if and only if setDirectoryId(int) has been called with an argument n.
Parameters:
filename file name, without any prefix
out ofstream object to associated with a file
Definition at line 236 of file ddMd/util/FileMaster.cpp.
References UTIL_THROW.
Referenced by DdMd::OutputTemperature::setup(), DdMd::OutputPressure::setup(), and DdMd::OutputBoxdim::setup().
void DdMd::FileMaster::openParamIFile (const std::string & name, const char * ext, std::ifstream & in) const
Open an input restart parameter file.
Parameters:
name base file name, without any prefix
ext file name extension.
in ifstream object to open
Definition at line 261 of file ddMd/util/FileMaster.cpp.
References UTIL_THROW.
void DdMd::FileMaster::openParamOFile (const std::string & name, const char * ext, std::ofstream & out) const
Open a restart parameter file for writing.
Parameters:
name base file name, without any prefix or extension
ext file name extension.
out ofstream object to open
Definition at line 283 of file ddMd/util/FileMaster.cpp.
References UTIL_THROW.
void DdMd::FileMaster::openRestartIFile (const std::string & name, const char * ext, std::ifstream & in) const
Open an input restart dump file.
Parameters:
name base file name, without any prefix or extension
ext file name extension.
in ifstream object to open
Definition at line 305 of file ddMd/util/FileMaster.cpp.
References UTIL_THROW.
void DdMd::FileMaster::openRestartOFile (const std::string & name, const char * ext, std::ofstream & out) const
Open a restart dump file for writing.
Parameters:
name base file name, without any prefix or extension
ext file name extension.
out ofstream object to open
Definition at line 326 of file ddMd/util/FileMaster.cpp.
References UTIL_THROW.
std::string DdMd::FileMaster::commandFileName () const [inline]
Return the command file name.
Definition at line 309 of file ddMd/util/FileMaster.h.
Referenced by setCommandFileName().
bool DdMd::FileMaster::isParamFileStdIn () const
Is paramFile() set to return std::cin ?
Definition at line 350 of file ddMd/util/FileMaster.cpp.
The documentation for this class was generated from the following files:
ddMd/util/FileMaster.h
ddMd/util/FileMaster.cpp