Simpatico: McMd::McCommandFactory Class Reference
McMd::McCommandFactory Class Reference
McMd namespace » Commands » MC Commands
Detailed Description
CommandFactory for an McSimulation.
Definition at line 28 of file McCommandFactory.h.
#include <McCommandFactory.h>
Public Member Functions
McCommandFactory (McSimulation &simulation, McSystem &system)
Constructor.
virtual Command * factory (const std::string &className) const
Return pointer to a new Command object.
Public Member Functions inherited from Util::Factory< Command >
Factory ()
Constructor.
virtual ~Factory ()
Destructor.
void addSubfactory (Factory< Command > &subfactory)
Add a new subfactory to the list.
Command * readObject (std::istream &in, ParamComposite &parent, std::string &className, bool &isEnd)
Read a class name, instantiate an object, and read its parameters.
Command * loadObject (Serializable::IArchive &ar, ParamComposite &parent, std::string &className)
Load a class name, instantiate an object, and load the object.
Protected Member Functions
McSystem & system () const
Return reference to parent McSystem.
McSimulation & simulation () const
Return reference to parent McSimulation.
Protected Member Functions inherited from Util::Factory< Command >
Command * trySubfactories (const std::string &className) const
Search through subfactories for match.
void setIoCommunicator (MPI::Intracomm &communicator)
Set associated Mpi communicator.
bool hasIoCommunicator () const
Does this factory have a param communicator?
Constructor & Destructor Documentation
McMd::McCommandFactory::McCommandFactory (McSimulation & simulation, McSystem & system)
Constructor.
Parameters
simulation parent McSimulation
system parent McSystem
Definition at line 24 of file McCommandFactory.cpp.
Member Function Documentation
Command * McMd::McCommandFactory::factory (const std::string & className) const virtual
Return pointer to a new Command object.
Parameters
className name of a subclass of Command.
Returns
base class pointer to a new instance of className.
Implements Util::Factory< Command >.
Definition at line 33 of file McCommandFactory.cpp.
References system(), and Util::Factory< Command >::trySubfactories().
McSystem& McMd::McCommandFactory::system () const inline protected
Return reference to parent McSystem.
Definition at line 54 of file McCommandFactory.h.
Referenced by factory().
McSimulation& McMd::McCommandFactory::simulation () const inline protected
Return reference to parent McSimulation.
Definition at line 60 of file McCommandFactory.h.
The documentation for this class was generated from the following files:
McCommandFactory.h
McCommandFactory.cpp