Simpatico: McMd::AtomDisplaceMove Class Reference
McMd::AtomDisplaceMove Class Reference
Monte Carlo Moves
Detailed Description
Random displacement of one atom.
Definition at line 26 of file AtomDisplaceMove.h.
#include <AtomDisplaceMove.h>
Public Member Functions
AtomDisplaceMove (McSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read species to which displacement is applied.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual bool move ()
Generate, attempt and accept or reject a move.
Constructor & Destructor Documentation
McMd::AtomDisplaceMove::AtomDisplaceMove (McSystem & system)
Constructor.
Definition at line 31 of file AtomDisplaceMove.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::AtomDisplaceMove::readParameters (std::istream & in) [virtual]
Read species to which displacement is applied.
Reimplemented from McMd::McMove.
Definition at line 40 of file AtomDisplaceMove.cpp.
References McMd::McMove::readProbability().
void McMd::AtomDisplaceMove::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::McMove.
Definition at line 50 of file AtomDisplaceMove.cpp.
void McMd::AtomDisplaceMove::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::McMove.
Definition at line 60 of file AtomDisplaceMove.cpp.
bool McMd::AtomDisplaceMove::move () [virtual]
Generate, attempt and accept or reject a move.
Reimplemented from McMd::McMove.
Definition at line 70 of file AtomDisplaceMove.cpp.
References McMd::Molecule::atom(), McMd::McSystem::atomPotentialEnergy(), McMd::SystemMove::boltzmann(), McMd::SystemMove::boundary(), Util::Dimension, McMd::McMove::incrementNAccept(), McMd::McMove::incrementNAttempt(), Util::Random::metropolis(), McMd::Molecule::nAtom(), McMd::McSystem::pairPotential(), McMd::Atom::position(), McMd::McMove::random(), McMd::System::randomMolecule(), Util::OrthorhombicBoundary::shift(), McMd::SystemMove::system(), Util::Random::uniform(), Util::Random::uniformInt(), and McMd::McPairPotential::updateAtomCell().
The documentation for this class was generated from the following files:
AtomDisplaceMove.h
AtomDisplaceMove.cpp