Simpatico: Util::PArray< Data > Class Template Reference
Util::PArray< Data > Class Template Reference
Pointer Arrays
Detailed Description
template<typename Data>
class Util::PArray< Data >
An array that only holds pointers to its elements.
A PArray<Data> is an array that is implemented by storing pointers to Data objects, rather than actual Data objects. The array suscript [] operator returns a reference to an associated Data object, as for Array<Data>. A PArray<Data> is not responsible for destroying the associated Data objects.
A PArray cannot be instantiated, because its constructor is protected. PArray is a base class for DPArray and for ArraySet.
Definition at line 33 of file PArray.h.
#include <PArray.h>
Public Member Functions
virtual ~PArray ()
Destructor.
int capacity () const
Return allocated size.
int size () const
Return logical size.
void begin (PArrayIterator< Data > &iterator) const
Set a PArrayIterator to the beginning of this PArray.
void begin (ConstPArrayIterator< Data > &iterator) const
Set a ConstPArrayIterator to the beginning of this PArray.
Data & operator[] (int i) const
Mimic C array subscripting.
Protected Member Functions
PArray ()
Constructor (protected to prevent instantiation).
Protected Attributes
Data ** ptrs_
PArray of of pointers to Data objects.
int capacity_
Allocated size of ptrs_ array.
int size_
Logical size (number of elements with initialized data).
Constructor & Destructor Documentation
template<typename Data > Util::PArray< Data >::~PArray () [virtual]
Destructor.
Definition at line 123 of file PArray.h.
template<typename Data > Util::PArray< Data >::PArray () [inline, protected]
Constructor (protected to prevent instantiation).
Definition at line 113 of file PArray.h.
Member Function Documentation
template<typename Data > int Util::PArray< Data >::capacity () const [inline]
Return allocated size.
Returns:
Number of elements allocated in array.
Definition at line 130 of file PArray.h.
template<typename Data > int Util::PArray< Data >::size () const [inline]
Return logical size.
Returns:
logical size of this array.
Definition at line 137 of file PArray.h.
Referenced by DdMd::AtomStorage::addNewAtom(), DdMd::AtomStorage::clearGhosts(), DdMd::Exchanger::exchangeAtoms(), McMd::LinkMaster::isValid(), and DdMd::AtomStorage::newAtomPtr().
template<typename Data> void Util::PArray< Data >::begin (PArrayIterator< Data > & iterator) const [inline]
Set a PArrayIterator to the beginning of this PArray.
Set an PArrayIterator to the beginning of this PArray.
Parameters:
iterator PArrayIterator, initialized on output.
Definition at line 146 of file PArray.h.
References Util::PArrayIterator< Data >::setCurrent(), Util::PArrayIterator< Data >::setEnd(), and Util::PArrayIterator< Data >::setNull().
Referenced by DdMd::AtomStorage::begin().
template<typename Data> void Util::PArray< Data >::begin (ConstPArrayIterator< Data > & iterator) const [inline]
Set a ConstPArrayIterator to the beginning of this PArray.
Set an ConstPArrayIterator to the beginning of this PArray.
Parameters:
iterator PArrayIterator, initialized on output.
iterator ConstPArrayIterator, initialized on output.
Definition at line 162 of file PArray.h.
References Util::ConstPArrayIterator< Data >::setCurrent(), Util::ConstPArrayIterator< Data >::setEnd(), and Util::ConstPArrayIterator< Data >::setNull().
template<typename Data > Data & Util::PArray< Data >::operator[] (int i) const [inline]
Mimic C array subscripting.
Subscript - return a reference.
Parameters:
i array index
Returns:
reference to element i
Definition at line 179 of file PArray.h.
Member Data Documentation
template<typename Data> Data** Util::PArray< Data >::ptrs_ [protected]
PArray of of pointers to Data objects.
Definition at line 87 of file PArray.h.
Referenced by Util::APArray< Data >::APArray(), Util::DPArray< Data >::DPArray(), and Util::DPArray< Data >::operator=().
template<typename Data> int Util::PArray< Data >::capacity_ [protected]
Allocated size of ptrs_ array.
Definition at line 90 of file PArray.h.
Referenced by Util::APArray< Data >::APArray(), and Util::DPArray< Data >::DPArray().
template<typename Data> int Util::PArray< Data >::size_ [protected]
Logical size (number of elements with initialized data).
Definition at line 93 of file PArray.h.
Referenced by Util::APArray< Data >::APArray(), Util::DPArray< Data >::DPArray(), Util::APArray< Data >::operator=(), and Util::DPArray< Data >::operator=().
The documentation for this class was generated from the following file:
PArray.h