Simpatico: DdMd::BondPotential Class Reference
DdMd::BondPotential Class Reference abstract
Bond Potentials
Detailed Description
Abstract base class for computing bond forces and energies.
Definition at line 29 of file ddMd/potentials/bond/BondPotential.h.
#include <BondPotential.h>
Public Member Functions
BondPotential (Simulation &simulation)
Constructor.
BondPotential ()
Default constructor.
~BondPotential ()
Destructor.
void associate (Boundary &boundary, GroupStorage< 2 > &storage)
Create association with related objects.
virtual void setNBondType (int nBondType)=0
Set the maximum number of atom types.
Interaction interface
virtual double bondEnergy (double rsq, int bondTypeId) const =0
Compute and return pair energy for a single pair.
virtual double bondForceOverR (double rsq, int bondTypeId) const =0
Compute and return force / separation for a single pair.
virtual double randomBondLength (Random *random, double beta, int bondTypeId) const =0
Return a random bond length, chosen from a Boltzmann distribution.
virtual void set (std::string name, int bondTypeId, double value)=0
Modify a bond interaction parameter, identified by a string.
virtual double get (std::string name, int bondTypeId) const =0
Get a bond parameter value, identified by a string.
virtual std::string interactionClassName () const =0
Return pair interaction class name (e.g., "HarmonicBond").
Public Member Functions inherited from DdMd::Potential
Potential ()
Constructor.
virtual ~Potential ()
Destructor.
void setReverseUpdateFlag (bool reverseUpdateFlag)
Set flag to identify if reverse communication is enabled.
bool reverseUpdateFlag () const
Get flag to identify if reverse communication is enabled.
virtual void computeForces ()=0
Add force contributions to all atomic forces.
virtual void computeEnergy (MPI::Intracomm &communicator)=0
Compute potential energy on all processors.
double energy () const
Return the total potential, from all processors.
void unsetEnergy ()
Mark the energy as unknown (nullify).
bool isEnergySet () const
Is the energy set (known)?
virtual void computeStress (MPI::Intracomm &communicator)
Compute stress on all processors.
virtual void computeForcesAndStress (MPI::Intracomm &communicator)
Compute forces and stress for all processors.
Tensor stress () const
Return the stress tensor.
double pressure () const
Return the pressure.
void unsetStress ()
Mark the stress as unknown (nullify).
bool isStressSet () const
Is the stress set (known)?
virtual bool isValid (MPI::Intracomm &communicator) const
Is the potential in a valid internal state?
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void readParameters (std::istream &in)
Read the body of parameter block, without begin and end lines.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
Boundary & boundary () const
Return boundary by reference.
GroupStorage< 2 > & storage () const
Return bond storage by reference.
Protected Member Functions inherited from DdMd::Potential
void setEnergy (double energy)
Set a value for the total energy.
void setStress (const Tensor &stress)
Set a value for the total stress.
void incrementPairStress (const Vector &f, const Vector &dr, Tensor &stress) const
Add a pair contribution to the stress tensor.
void reduceEnergy (double localEnergy, MPI::Intracomm &communicator)
Add local energies from all processors, set energy on master.
void reduceStress (Tensor &localStress, MPI::Intracomm &communicator)
Add local stresses from all processors, set total on master.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Constructor & Destructor Documentation
DdMd::BondPotential::BondPotential (Simulation & simulation)
Constructor.
This is the constructor that is used during a simulation.
Parameters
simulation parent Simulation object
Definition at line 18 of file ddMd/potentials/bond/BondPotential.cpp.
References Util::ParamComposite::setClassName().
DdMd::BondPotential::BondPotential ()
Default constructor.
This constructor is provided only to simplify unit testing.
Definition at line 26 of file ddMd/potentials/bond/BondPotential.cpp.
References Util::ParamComposite::setClassName().
DdMd::BondPotential::~BondPotential ()
Destructor.
Definition at line 43 of file ddMd/potentials/bond/BondPotential.cpp.
Member Function Documentation
void DdMd::BondPotential::associate (Boundary & boundary, GroupStorage< 2 > & storage)
Create association with related objects.
Call iff object instantiated with default constructor, for unit testing.
Parameters
boundary associated Boundary object.
storage associated GroupStorage<2> object.
Definition at line 34 of file ddMd/potentials/bond/BondPotential.cpp.
References boundary(), and storage().
virtual void DdMd::BondPotential::setNBondType (int nBondType) pure virtual
Set the maximum number of atom types.
The implementation by a subclass should set the nBondType of the associated Interaction. This should be called by the main constructor of a concrete subclass, to set nBondType to simulation.nBondType(), or by a user if the object is instantiated with default constructor for unit testing.
Parameters
nBondType maximum number of bond types (max index + 1).
Implemented in DdMd::BondPotentialImpl< Interaction >.
virtual double DdMd::BondPotential::bondEnergy (double rsq, int bondTypeId) const pure virtual
Compute and return pair energy for a single pair.
Parameters
rsq square of distance between atoms
bondTypeId bond type index
Implemented in DdMd::BondPotentialImpl< Interaction >.
virtual double DdMd::BondPotential::bondForceOverR (double rsq, int bondTypeId) const pure virtual
Compute and return force / separation for a single pair.
Parameters
rsq square of distance between atoms
bondTypeId bond type index
Implemented in DdMd::BondPotentialImpl< Interaction >.
virtual double DdMd::BondPotential::randomBondLength (Random * random, double beta, int bondTypeId) const pure virtual
Return a random bond length, chosen from a Boltzmann distribution.
This function should return the length of a random bond vector from the Boltzmann distribution for the specified bond interaction, giving a probability distribution r^2 exp(-U(r) / kT), where U(r) is the bond potential.
Parameters
random pointer to a random number generator
beta inverse thermal energy 1/T, with T in units of energy
bondTypeId bond type index
Implemented in DdMd::BondPotentialImpl< Interaction >.
virtual void DdMd::BondPotential::set (std::string name, int bondTypeId, double value) pure virtual
Modify a bond interaction parameter, identified by a string.
Parameters
name parameter variable name
bondTypeId bond type index
value new value of parameter
Implemented in DdMd::BondPotentialImpl< Interaction >.
virtual double DdMd::BondPotential::get (std::string name, int bondTypeId) const pure virtual
Get a bond parameter value, identified by a string.
Parameters
name interaction parameter name
bondTypeId bond type index
Implemented in DdMd::BondPotentialImpl< Interaction >.
virtual std::string DdMd::BondPotential::interactionClassName () const pure virtual
Return pair interaction class name (e.g., "HarmonicBond").
Implemented in DdMd::BondPotentialImpl< Interaction >.
Boundary & DdMd::BondPotential::boundary () const inline protected
Return boundary by reference.
Definition at line 159 of file ddMd/potentials/bond/BondPotential.h.
Referenced by associate().
GroupStorage< 2 > & DdMd::BondPotential::storage () const inline protected
Return bond storage by reference.
Definition at line 162 of file ddMd/potentials/bond/BondPotential.h.
Referenced by associate().
The documentation for this class was generated from the following files:
ddMd/potentials/bond/BondPotential.h
ddMd/potentials/bond/BondPotential.cpp