Simpatico: DdMd::OrderParamNucleation Class Reference
DdMd::OrderParamNucleation Class Reference
Analyzers
Detailed Description
OrderParamNucleation is designed to evaluate a sort of composition profile in the specific case of nucleating a lamellar ordered phase in a small region at the center of a simulation cell.
Composition profile is calculated in terma of a quantity called cos factor which is simple the cosine component of a typical structure factor calculation. The cos factor is evaluated per atom type and for the specific wavevector corresponding to the direction perpendicular to lamellae (specified by the parameter perpIndex).
The cos factors are accumulated in different bins based on the atom position in the direction parallel to lamellae (specified by the parameter parallelIndex).
OrderParamNucleation{
   interval                      1000
   outputFileName    OrderParamNucleation
   perpIndex                        2
   parallelIndex                    0
   periodicity                      3
   nBin                           100
}
Definition at line 55 of file OrderParamNucleation.h.
#include <OrderParamNucleation.h>
Public Member Functions
OrderParamNucleation (Simulation &simulation)
Constructor.
~OrderParamNucleation ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void clear ()
Clear accumulators.
void sample (long iStep)
Add particles to OrderParamNucleation accumulators.
virtual void output ()
Output results to predefined output file.
Public Member Functions inherited from DdMd::Analyzer
Analyzer (Simulation &simulation)
Constructor.
virtual ~Analyzer ()
Destructor.
virtual void setup ()
Setup before simulation.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Attributes
std::ofstream outputFile_
Output file stream.
int nAtomType_
Number of atom types, copied from Simulation::nAtomType().
DMatrix< double > cosFactors_
Cos factors of size nAtomType*nBin.
DMatrix< double > totalCosFactors_
Total cos factors of size nAtomType*nBin (gathered from all processors)
int perpIndex_
Index of direction perpendicular to lamellae (direction of external field)
int parallelIndex_
Index of direction parallel to the lamellar surfaces.
int periodicity_
Number of periods in the perpendicular direction.
int nBin_
Number of bins to divide the length along parallel direction.
int nSample_
Number of samples thus far.
bool isInitialized_
Has readParam been called?
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from DdMd::Analyzer
static void initStatic ()
Define and initialize baseInterval.
Static Public Attributes inherited from DdMd::Analyzer
static long baseInterval = 1
The interval for an Analyzer must be a multiple of baseInterval.
Protected Member Functions inherited from DdMd::Analyzer
void readInterval (std::istream &in)
Read parameter interval from file.
void loadInterval (Serializable::IArchive &ar)
Load parameter interval from input archive.
void saveInterval (Serializable::OArchive &ar)
Save interval parameter to an archive.
void readOutputFileName (std::istream &in)
Read outputFileName from file.
void loadOutputFileName (Serializable::IArchive &ar)
Load output file name to an archive.
void saveOutputFileName (Serializable::OArchive &ar)
Save output file name to an archive.
Simulation & simulation ()
Get the parent Simulation by reference.
const std::string & outputFileName () const
Return outputFileName string.
std::string outputFileName (const std::string &suffix) const
Return outputFileName string with added suffix.
Constructor & Destructor Documentation
DdMd::OrderParamNucleation::OrderParamNucleation (Simulation & simulation)
Constructor.
Parameters
simulation reference to parent Simulation object
Definition at line 26 of file OrderParamNucleation.cpp.
References Util::ParamComposite::setClassName().
DdMd::OrderParamNucleation::~OrderParamNucleation ()
Destructor.
Definition at line 31 of file OrderParamNucleation.cpp.
Member Function Documentation
void DdMd::OrderParamNucleation::readParameters (std::istream & in) virtual
Read parameters from file.
Read parameters from file, and allocate data array.
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 35 of file OrderParamNucleation.cpp.
References Util::DMatrix< Data >::allocate(), cosFactors_, Util::Dimension, isInitialized_, DdMd::Simulation::nAtomType(), nAtomType_, nBin_, parallelIndex_, periodicity_, perpIndex_, DdMd::Analyzer::readInterval(), DdMd::Analyzer::readOutputFileName(), DdMd::Analyzer::simulation(), totalCosFactors_, and UTIL_THROW.
void DdMd::OrderParamNucleation::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from DdMd::Analyzer.
Definition at line 61 of file OrderParamNucleation.cpp.
References Util::DMatrix< Data >::allocate(), cosFactors_, Util::Dimension, isInitialized_, DdMd::Analyzer::loadInterval(), DdMd::Analyzer::loadOutputFileName(), DdMd::Simulation::nAtomType(), nAtomType_, nBin_, parallelIndex_, periodicity_, perpIndex_, DdMd::Analyzer::simulation(), totalCosFactors_, and UTIL_THROW.
void DdMd::OrderParamNucleation::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from DdMd::Analyzer.
Definition at line 88 of file OrderParamNucleation.cpp.
References nBin_, parallelIndex_, periodicity_, perpIndex_, DdMd::Analyzer::saveInterval(), and DdMd::Analyzer::saveOutputFileName().
void DdMd::OrderParamNucleation::clear () virtual
Clear accumulators.
Reimplemented from DdMd::Analyzer.
Definition at line 101 of file OrderParamNucleation.cpp.
References cosFactors_, isInitialized_, nAtomType_, nBin_, nSample_, totalCosFactors_, and UTIL_THROW.
void DdMd::OrderParamNucleation::sample (long iStep) virtual
Add particles to OrderParamNucleation accumulators.
Parameters
iStep step counter
Implements DdMd::Analyzer.
Definition at line 121 of file OrderParamNucleation.cpp.
References DdMd::Simulation::atomStorage(), DdMd::AtomStorage::begin(), DdMd::Simulation::boundary(), DdMd::Domain::communicator(), cosFactors_, DdMd::Simulation::domain(), DdMd::Analyzer::isAtInterval(), Util::OrthorhombicBoundary::lengths(), nAtomType_, nBin_, Util::PArrayIterator< Data >::notEnd(), nSample_, parallelIndex_, periodicity_, perpIndex_, Util::Constants::Pi, Util::product(), DdMd::Analyzer::simulation(), and totalCosFactors_.
void DdMd::OrderParamNucleation::output () virtual
Output results to predefined output file.
Reimplemented from DdMd::Analyzer.
Definition at line 174 of file OrderParamNucleation.cpp.
References DdMd::Simulation::boundary(), DdMd::Simulation::fileMaster(), nAtomType_, nBin_, nSample_, Util::FileMaster::openOutputFile(), outputFile_, DdMd::Analyzer::outputFileName(), DdMd::Analyzer::simulation(), totalCosFactors_, Util::OrthorhombicBoundary::volume(), and Util::ParamComposite::writeParam().
Member Data Documentation
std::ofstream DdMd::OrderParamNucleation::outputFile_ protected
Output file stream.
Definition at line 113 of file OrderParamNucleation.h.
Referenced by output().
int DdMd::OrderParamNucleation::nAtomType_ protected
Number of atom types, copied from Simulation::nAtomType().
Definition at line 116 of file OrderParamNucleation.h.
Referenced by clear(), loadParameters(), output(), readParameters(), and sample().
DMatrix<double> DdMd::OrderParamNucleation::cosFactors_ protected
Cos factors of size nAtomType*nBin.
Definition at line 119 of file OrderParamNucleation.h.
Referenced by clear(), loadParameters(), readParameters(), and sample().
DMatrix<double> DdMd::OrderParamNucleation::totalCosFactors_ protected
Total cos factors of size nAtomType*nBin (gathered from all processors)
Definition at line 122 of file OrderParamNucleation.h.
Referenced by clear(), loadParameters(), output(), readParameters(), and sample().
int DdMd::OrderParamNucleation::perpIndex_ protected
Index of direction perpendicular to lamellae (direction of external field)
Definition at line 125 of file OrderParamNucleation.h.
Referenced by loadParameters(), readParameters(), sample(), and save().
int DdMd::OrderParamNucleation::parallelIndex_ protected
Index of direction parallel to the lamellar surfaces.
Definition at line 128 of file OrderParamNucleation.h.
Referenced by loadParameters(), readParameters(), sample(), and save().
int DdMd::OrderParamNucleation::periodicity_ protected
Number of periods in the perpendicular direction.
Definition at line 131 of file OrderParamNucleation.h.
Referenced by loadParameters(), readParameters(), sample(), and save().
int DdMd::OrderParamNucleation::nBin_ protected
Number of bins to divide the length along parallel direction.
Definition at line 134 of file OrderParamNucleation.h.
Referenced by clear(), loadParameters(), output(), readParameters(), sample(), and save().
int DdMd::OrderParamNucleation::nSample_ protected
Number of samples thus far.
Definition at line 137 of file OrderParamNucleation.h.
Referenced by clear(), output(), and sample().
bool DdMd::OrderParamNucleation::isInitialized_ protected
Has readParam been called?
Definition at line 140 of file OrderParamNucleation.h.
Referenced by clear(), loadParameters(), and readParameters().
The documentation for this class was generated from the following files:
OrderParamNucleation.h
OrderParamNucleation.cpp