Simpatico: Inter::NucleationExternal Class Reference
Inter::NucleationExternal Class Reference
External Interactions
Detailed Description
A clipped cosine potential that induces ordering along directions specified by waveIntVectors, w_i.
/ / / / w_i.(x-shift_[0]) w_i.(y-shift_[1]) w_i.(z-shift_[2]) \ \ \ \ u = prefactor[atomType] externalParameter tanh | clipParameter| C_ + Sum | cos | 2 pi ------------------ + ------------------ + ------------------ + phase_i | | | | \ \ i \ \ Lx Ly Lz / / / /
Prefactor (which depends on the atomType), externalParameter, waveIntVectors, interfaceWidth and periodicity are given as inputs in the parameter file. ClipParameter is the inverse of 2*pi*periodicity*interfaceWidth.
Definition at line 37 of file NucleationExternal.h.
#include <NucleationExternal.h>
Public Member Functions
NucleationExternal ()
Default constructor.
NucleationExternal (const NucleationExternal &other)
Copy constructor.
NucleationExternal & operator= (const NucleationExternal &other)
Assignment.
void setNAtomType (int nAtomType)
Set nAtomType value.
void setExternalParameter (double externalParameter)
Sets external parameter.
void setBoundary (Boundary &boundary)
Set pointer to Boundary.
void readParameters (std::istream &in)
Read potential parameters, and initialize other variables.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
double externalParameter () const
Returns external parameter.
double energy (const Vector &position, int i) const
Returns external potential energy of a single particle.
void getForce (const Vector &position, int type, Vector &force) const
Returns force caused by the external potential.
std::string className () const
Return name string "NucleationExternal".
Constructor & Destructor Documentation
Inter::NucleationExternal::NucleationExternal ()
Default constructor.
Definition at line 20 of file NucleationExternal.cpp.
References Util::ParamComposite::setClassName().
Inter::NucleationExternal::NucleationExternal (const NucleationExternal & other)
Copy constructor.
Definition at line 36 of file NucleationExternal.cpp.
References Util::DArray< Data >::allocate(), and Util::Dimension.
Member Function Documentation
NucleationExternal & Inter::NucleationExternal::operator= (const NucleationExternal & other)
Assignment.
Definition at line 70 of file NucleationExternal.cpp.
References Util::DArray< Data >::allocate(), and Util::Dimension.
void Inter::NucleationExternal::setNAtomType (int nAtomType)
Set nAtomType value.
Parameters:
nAtomType number of atom types.
Definition at line 103 of file NucleationExternal.cpp.
References UTIL_THROW.
void Inter::NucleationExternal::setExternalParameter (double externalParameter)
Sets external parameter.
Parameters:
externalParameter external parameter of system
Definition at line 114 of file NucleationExternal.cpp.
References externalParameter(), and UTIL_THROW.
void Inter::NucleationExternal::setBoundary (Boundary & boundary)
Set pointer to Boundary.
Parameters:
boundary Boundary object (used to calculate length along perpendicular direction).
Definition at line 128 of file NucleationExternal.cpp.
void Inter::NucleationExternal::readParameters (std::istream & in) [virtual]
Read potential parameters, and initialize other variables.
Precondition:
nAtomType must have been set, by calling setNAtomType().
Boundary must have been set, by calling setBoundary().
Parameters:
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 134 of file NucleationExternal.cpp.
References Util::DArray< Data >::allocate(), and UTIL_THROW.
void Inter::NucleationExternal::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 168 of file NucleationExternal.cpp.
References Util::DArray< Data >::allocate(), and UTIL_THROW.
void Inter::NucleationExternal::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 192 of file NucleationExternal.cpp.
double Inter::NucleationExternal::externalParameter () const
Returns external parameter.
Returns:
external parameter
Definition at line 208 of file NucleationExternal.cpp.
Referenced by setExternalParameter().
double Inter::NucleationExternal::energy (const Vector & position, int i) const [inline]
Returns external potential energy of a single particle.
Parameters:
position atomic position Vector
i atom type.
Returns:
external potential energy
Definition at line 186 of file NucleationExternal.h.
References Util::Vector::dot().
void Inter::NucleationExternal::getForce (const Vector & position, int type, Vector & force) const [inline]
Returns force caused by the external potential.
Parameters:
position atom position
type atom type id
force force on the atom (on output)
Definition at line 217 of file NucleationExternal.h.
References Util::Vector::dot(), and Util::Vector::zero().
std::string Inter::NucleationExternal::className () const
Return name string "NucleationExternal".
Reimplemented from Util::ParamComposite.
Definition at line 216 of file NucleationExternal.cpp.
The documentation for this class was generated from the following files:
NucleationExternal.h
NucleationExternal.cpp