Simpatico: Inter::SimplePeriodicExternal Class Reference
Inter::SimplePeriodicExternal Class Reference
External Interactions
Detailed Description
A clipped cosine potential that induces ordering along directions specified by waveIntVectors, w_i.
/ / / w_i.x w_i.y w_i.z \ \ \ u = prefactor[atomType] externalParameter tanh | clipParameter Sum | cos | 2 pi ------- + ------- + ------- | | | \ i \ \ Lx Ly Lz / / /
Prefactor (which depends on the atomType), externalParameter, waveIntVectors, interfaceWidth and periodicity are given as inputs in the parameter file. ClipParameter is the inverse of 2*pi*periodicity*interfaceWidth.
Definition at line 37 of file SimplePeriodicExternal.h.
#include <SimplePeriodicExternal.h>
Public Member Functions
SimplePeriodicExternal ()
Default constructor.
SimplePeriodicExternal (const SimplePeriodicExternal &other)
Copy constructor.
SimplePeriodicExternal & operator= (const SimplePeriodicExternal &other)
Assignment.
void setNAtomType (int nAtomType)
Set nAtomType value.
void setExternalParameter (double externalParameter)
Sets external parameter.
void setBoundary (Boundary &boundary)
Set pointer to Boundary.
void readParameters (std::istream &in)
Read potential parameters, and initialize other variables.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
double externalParameter () const
Returns external parameter.
double energy (const Vector &position, int i) const
Returns external potential energy of a single particle.
void getForce (const Vector &position, int type, Vector &force) const
Returns force caused by the external potential.
std::string className () const
Return name string "SimplePeriodicExternal".
Constructor & Destructor Documentation
Inter::SimplePeriodicExternal::SimplePeriodicExternal ()
Default constructor.
Definition at line 23 of file SimplePeriodicExternal.cpp.
References Util::ParamComposite::setClassName().
Inter::SimplePeriodicExternal::SimplePeriodicExternal (const SimplePeriodicExternal & other)
Copy constructor.
Definition at line 36 of file SimplePeriodicExternal.cpp.
References Util::DArray< Data >::allocate(), and Util::Dimension.
Member Function Documentation
SimplePeriodicExternal & Inter::SimplePeriodicExternal::operator= (const SimplePeriodicExternal & other)
Assignment.
Definition at line 60 of file SimplePeriodicExternal.cpp.
References Util::Dimension.
void Inter::SimplePeriodicExternal::setNAtomType (int nAtomType)
Set nAtomType value.
Parameters:
nAtomType number of atom types.
Definition at line 83 of file SimplePeriodicExternal.cpp.
References UTIL_THROW.
void Inter::SimplePeriodicExternal::setExternalParameter (double externalParameter)
Sets external parameter.
Parameters:
externalParameter external parameter of system
Definition at line 94 of file SimplePeriodicExternal.cpp.
References externalParameter(), and UTIL_THROW.
void Inter::SimplePeriodicExternal::setBoundary (Boundary & boundary)
Set pointer to Boundary.
Parameters:
boundary Boundary object (used to calculate length along perpendicular direction).
Definition at line 108 of file SimplePeriodicExternal.cpp.
void Inter::SimplePeriodicExternal::readParameters (std::istream & in) [virtual]
Read potential parameters, and initialize other variables.
Precondition:
nAtomType must have been set, by calling setNAtomType().
Boundary must have been set, by calling setBoundary().
Parameters:
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 114 of file SimplePeriodicExternal.cpp.
References Util::DArray< Data >::allocate(), and UTIL_THROW.
void Inter::SimplePeriodicExternal::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 142 of file SimplePeriodicExternal.cpp.
References Util::DArray< Data >::allocate(), and UTIL_THROW.
void Inter::SimplePeriodicExternal::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 161 of file SimplePeriodicExternal.cpp.
double Inter::SimplePeriodicExternal::externalParameter () const
Returns external parameter.
Returns:
external parameter
Definition at line 172 of file SimplePeriodicExternal.cpp.
Referenced by setExternalParameter().
double Inter::SimplePeriodicExternal::energy (const Vector & position, int i) const [inline]
Returns external potential energy of a single particle.
Parameters:
position atomic position Vector
i atom type.
Returns:
external potential energy
Definition at line 171 of file SimplePeriodicExternal.h.
References Util::Vector::dot().
void Inter::SimplePeriodicExternal::getForce (const Vector & position, int type, Vector & force) const [inline]
Returns force caused by the external potential.
Parameters:
position atom position
type atom type id
force force on the atom (on output)
Definition at line 193 of file SimplePeriodicExternal.h.
References Util::Vector::dot(), and Util::Vector::zero().
std::string Inter::SimplePeriodicExternal::className () const
Return name string "SimplePeriodicExternal".
Reimplemented from Util::ParamComposite.
Definition at line 180 of file SimplePeriodicExternal.cpp.
The documentation for this class was generated from the following files:
SimplePeriodicExternal.h
SimplePeriodicExternal.cpp