Simpatico: McMd::MdEwaldPotential Class Reference
McMd::MdEwaldPotential Class Reference
McMd namespace » Potential Energies » Coulomb Potentials
Detailed Description
Ewald Coulomb potential class for MD simulations.
This class implements the k-space sums in the Ewald method for computing the Coulomb energy and forces.
Definition at line 46 of file MdEwaldPotential.h.
#include <MdEwaldPotential.h>
Public Member Functions
MdEwaldPotential (System &system)
Constructor.
virtual ~MdEwaldPotential ()
Destructor (does nothing).
Initialization
virtual void readParameters (std::istream &in)
Read parameters and initialize.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
Parameters (get/set)
void set (std::string name, double value)
Set a parameter value, identified by a string.
double get (std::string name) const
Get a parameter value, identified by a string.
System energy and stress.
virtual void makeWaves ()
Generate wavevectors for the current boundary and kCutoff.
int nWave () const
Current number of wavevectors with |k| < kCutoff.
virtual void addForces ()
Add k-space Coulomb forces for all atoms.
virtual void computeEnergy ()
Calculate the long range kspace part of Coulomb energy.
virtual void computeStress ()
Compute kspace part of Coulomb pressure.
Miscellaneous Accessors
EwaldRSpaceAccumulator & rSpaceAccumulator ()
EwaldInteraction & ewaldInteraction ()
Public Member Functions inherited from McMd::MdCoulombPotential
MdCoulombPotential ()
Constructor.
virtual ~MdCoulombPotential ()
Destructor (does nothing).
bool hasWaves ()
Are wavevectors and k-space influence function up to date?
void unsetWaves ()
Unset all data that depends on the Boundary.
virtual void unsetEnergy ()
Unset k-space energy.
double kSpaceEnergy ()
Get long-range k-space part of Coulomb energy.
double rSpaceEnergy ()
Return short-range r-space part of Coulomb energy.
double energy ()
Get total Coulomb energy.
virtual void unsetStress ()
Unset k-space stress.
Tensor kSpaceStress ()
Get long-range k-space part of Coulomb stress.
Tensor rSpaceStress ()
Return short-range r-space part of Coulomb stress.
Tensor stress ()
Get total Coulomb stress.
void computeStress (Tensor &stress)
Get total Coulomb stress.
void computeStress (Vector &pressures)
Get diagonal components of Coulomb stress.
double pressure ()
Get total Coulomb pressure.
void computeStress (double &pressure)
Get the total Coulomb pressure.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes inherited from McMd::MdCoulombPotential
EwaldRSpaceAccumulator rSpaceAccumulator_
Short-range real space energy and stress contributions.
Setable< double > kSpaceEnergy_
K-space part of Coulomb energy.
Setable< Tensor > kSpaceStress_
K-space part of Coulomb stress.
bool isInitialized_
Have parameters been set?
bool hasWaves_
Are waves and k-space potential up to date? Unset if boundary or parameters change.
Constructor & Destructor Documentation
McMd::MdEwaldPotential::MdEwaldPotential (System & system)
Constructor.
Parameters
system parent system.
Definition at line 32 of file MdEwaldPotential.cpp.
McMd::MdEwaldPotential::~MdEwaldPotential () virtual
Destructor (does nothing).
Definition at line 46 of file MdEwaldPotential.cpp.
Member Function Documentation
void McMd::MdEwaldPotential::readParameters (std::istream & in) virtual
Read parameters and initialize.
Parameters
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 52 of file MdEwaldPotential.cpp.
References Util::ParamComposite::addParamComposite(), and Simp::EwaldInteraction::readParameters().
void McMd::MdEwaldPotential::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 65 of file MdEwaldPotential.cpp.
References Util::ParamComposite::addParamComposite(), and Simp::EwaldInteraction::loadParameters().
void McMd::MdEwaldPotential::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 77 of file MdEwaldPotential.cpp.
References Simp::EwaldInteraction::save().
void McMd::MdEwaldPotential::set (std::string name, double value) virtual
Set a parameter value, identified by a string.
Parameters
name parameter name
value new value of parameter
Reimplemented from McMd::MdCoulombPotential.
Definition at line 86 of file MdEwaldPotential.cpp.
References Simp::EwaldInteraction::set(), and McMd::MdCoulombPotential::unsetWaves().
double McMd::MdEwaldPotential::get (std::string name) const virtual
Get a parameter value, identified by a string.
Parameters
name parameter name
Reimplemented from McMd::MdCoulombPotential.
Definition at line 99 of file MdEwaldPotential.cpp.
References Simp::EwaldInteraction::get().
void McMd::MdEwaldPotential::makeWaves () virtual
Generate wavevectors for the current boundary and kCutoff.
Implements McMd::MdCoulombPotential.
Definition at line 124 of file MdEwaldPotential.cpp.
References Util::Vector::abs(), Util::GArray< Data >::append(), McMd::System::begin(), Util::OrthorhombicBoundary::bravaisBasisVector(), Util::GArray< Data >::clear(), Util::Dimension, Util::Vector::dot(), McMd::MdCoulombPotential::hasWaves(), McMd::MdCoulombPotential::hasWaves_, Simp::EwaldInteraction::kSpacePotential(), Util::Vector::multiply(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::Constants::Pi, Util::OrthorhombicBoundary::reciprocalBasisVector(), Util::GArray< Data >::reserve(), Util::GArray< Data >::resize(), Util::GArray< Data >::size(), Util::Vector::square(), Util::OrthorhombicBoundary::transformCartToGen(), and UTIL_CHECK.
int McMd::MdEwaldPotential::nWave () const inline virtual
Current number of wavevectors with |k| < kCutoff.
Implements McMd::MdCoulombPotential.
Definition at line 113 of file MdEwaldPotential.cpp.
void McMd::MdEwaldPotential::addForces () virtual
Add k-space Coulomb forces for all atoms.
Implements McMd::MdCoulombPotential.
Definition at line 287 of file MdEwaldPotential.cpp.
References McMd::System::begin(), Util::Dimension, Util::Constants::Im, Util::Vector::multiply(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::Constants::Pi, Util::OrthorhombicBoundary::reciprocalBasisVector(), Util::GArray< Data >::size(), Util::OrthorhombicBoundary::transformCartToGen(), Util::OrthorhombicBoundary::volume(), and Util::Vector::zero().
void McMd::MdEwaldPotential::computeEnergy () virtual
Calculate the long range kspace part of Coulomb energy.
Implements McMd::MdCoulombPotential.
Definition at line 377 of file MdEwaldPotential.cpp.
References Simp::EwaldInteraction::alpha(), McMd::System::begin(), McMd::MdCoulombPotential::energy(), Simp::EwaldInteraction::epsilon(), McMd::MdCoulombPotential::kSpaceEnergy_, Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::Constants::Pi, Util::Setable< T >::set(), and Util::OrthorhombicBoundary::volume().
void McMd::MdEwaldPotential::computeStress () virtual
Compute kspace part of Coulomb pressure.
Implements McMd::MdCoulombPotential.
Definition at line 427 of file MdEwaldPotential.cpp.
References Util::Tensor::add(), Simp::EwaldInteraction::alpha(), Util::Tensor::dyad(), Util::Tensor::Identity, McMd::MdCoulombPotential::kSpaceStress_, Util::Vector::multiply(), Util::OrthorhombicBoundary::reciprocalBasisVector(), Util::OrthorhombicBoundary::volume(), and Util::Tensor::zero().
The documentation for this class was generated from the following files:
MdEwaldPotential.h
MdEwaldPotential.cpp