Simpatico: Util::FArrayParam< Type, N > Class Template Reference
Util::FArrayParam< Type, N > Class Template Reference
Parameter File IO
Detailed Description
template<class Type, int N>
class Util::FArrayParam< Type, N >
A Parameter associated with a FArray container.
Definition at line 28 of file FArrayParam.h.
#include <FArrayParam.h>
Public Member Functions
FArrayParam (const char *label, FArray< Type, N > &array)
Constructor.
void readParam (std::istream &in)
Read FArray parameter from stream.
void writeParam (std::ostream &out)
Write FArray parameter to stream.
void load (Serializable::IArchive &ar)
Load from an archive.
void save (Serializable::OArchive &ar)
Save to an archive.
Protected Attributes
FArray< Type, N > * arrayPtr_
Pointer to associated FArray.
Constructor & Destructor Documentation
template<class Type , int N> Util::FArrayParam< Type, N >::FArrayParam (const char * label, FArray< Type, N > & array)
Constructor.
Parameters:
label label string for parameter file
array associated FArray variable
Definition at line 80 of file FArrayParam.h.
Member Function Documentation
template<class Type , int N> void Util::FArrayParam< Type, N >::readParam (std::istream & in) [virtual]
Read FArray parameter from stream.
Parameters:
in input stream
Implements Util::ParamComponent.
Definition at line 89 of file FArrayParam.h.
References Util::ParamComponent::echo(), and Util::Log::file().
Referenced by Util::ParamComposite::readFArray().
template<class Type , int N> void Util::FArrayParam< Type, N >::writeParam (std::ostream & out) [virtual]
Write FArray parameter to stream.
Parameters:
out output stream
Implements Util::ParamComponent.
Definition at line 111 of file FArrayParam.h.
References Util::Parameter::Precision, and Util::Parameter::Width.
template<class Type , int N> void Util::FArrayParam< Type, N >::load (Serializable::IArchive & ar) [virtual]
Load from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from Util::ParamComponent.
Definition at line 132 of file FArrayParam.h.
Referenced by Util::ParamComposite::loadFArray().
template<class Type , int N> void Util::FArrayParam< Type, N >::save (Serializable::OArchive & ar) [virtual]
Save to an archive.
Parameters:
ar saving (output) archive.
Reimplemented from Util::ParamComponent.
Definition at line 150 of file FArrayParam.h.
Member Data Documentation
template<class Type, int N> FArray<Type, N>* Util::FArrayParam< Type, N >::arrayPtr_ [protected]
Pointer to associated FArray.
Definition at line 72 of file FArrayParam.h.
The documentation for this class was generated from the following file:
FArrayParam.h