Simpatico: DdMd::Simulation Class Reference
DdMd::Simulation Class Reference
Simulations
Detailed Description
Main object for a domain-decomposition MD simulation.
A DdMd::Simulation contains and coordinates all the components of a parallel MD simulation.
Definition at line 73 of file ddMd/simulation/Simulation.h.
#include <Simulation.h>
Public Member Functions
Simulation (MPI::Intracomm &communicator=MPI::COMM_WORLD)
Constructor.
~Simulation ()
Destructor.
bool isValid ()
Return true if this Simulation is valid, or throw an Exception.
Initialize
void setOptions (int argc, char *const *argv)
Process command line options.
virtual void readParam ()
Read parameters from default parameter file.
virtual void readParam (std::istream &in)
Read parameters.
virtual void readParameters (std::istream &in)
Read parameters, allocate memory and initialize.
void setReverseUpdateFlag (bool reverseUpdateFlag)
Set flag to identify if reverse communication is enabled.
Serialization (Restart files)
void load (const std::string &filename)
Load internal state from a restart file.
virtual void loadParameters (Serializable::IArchive &ar)
Load parameters from a restart archive.
void save (const std::string &filename)
Save state to a restart file.
virtual void save (Serializable::OArchive &ar)
Save internal state to restart archive.
Run Time Actions
void readCommands ()
Read and execute commands from the default command file.
void readCommands (std::istream &in)
Read and execute commands from a specific command file.
void setBoltzmannVelocities (double temperature)
Set random velocities chosen from Boltzmann distribution.
void zeroForces ()
Set forces for all local atoms to zero.
Config File IO
void readConfig (const std::string &filename)
Read configuration file on master and distribute atoms.
void writeConfig (const std::string &filename)
Write configuration file.
Factory< ConfigIo > & configIoFactory ()
Get the configuration file reader/writer factory by reference.
void setConfigIo (std::string &classname)
Create a new configuration file reader/writer.
Force, energy and stress calculators
void computeForces ()
Compute forces for all local atoms.
void computeForcesAndVirial ()
Compute forces for all local atoms and virial stress.
void computeKineticEnergy ()
Compute total kinetic energy.
double kineticEnergy ()
Return precomputed total kinetic energy.
void unsetKineticEnergy ()
Mark kinetic energy as unknown.
void computePotentialEnergies ()
Calculate and store total potential energy on all processors.
double potentialEnergy () const
Return precomputed total potential energy.
void unsetPotentialEnergies ()
Mark all potential energies as unknown.
void computePairEnergies ()
Compute pair energies for each pair of atom types.
DMatrix< double > pairEnergies () const
Return precomputed pair energies.
void computeExternalEnergy ()
Compute pair energies for each pair of atom types.
double externalEnergy () const
Return precomputed pair energies.
void computeKineticStress ()
Calculate and store kinetic stress.
Tensor kineticStress () const
Return total kinetic stress.
double kineticPressure () const
Return total kinetic pressure.
void unsetKineticStress ()
Mark kinetic stress as unknown.
void computeVirialStress ()
Calculate and store all virial stress contributions.
Tensor virialStress () const
Return total virial stress.
double virialPressure () const
Return total virial pressure.
void unsetVirialStress ()
Mark all virial stress contributions as unknown.
Potential Energy Classes (Objects, Style Strings and Factories)
PairPotential & pairPotential ()
Get the PairPotential by reference.
std::string pairStyle () const
Return nonbonded pair style string.
Factory< PairPotential > & pairFactory ()
Get the Factory<PairPotential> by reference.
BondPotential & bondPotential ()
Get the PairPotential by reference.
std::string bondStyle () const
Return covalent bond style string.
Factory< BondPotential > & bondFactory ()
Get the Factory<BondPotential> by reference.
AnglePotential & anglePotential ()
Get the AnglePotential by reference.
std::string angleStyle () const
Return angle potential style string.
Factory< AnglePotential > & angleFactory ()
Get the AngleFactory by reference.
DihedralPotential & dihedralPotential ()
Get the DihedralPotential by reference.
std::string dihedralStyle () const
Return dihedral potential style string.
Factory< DihedralPotential > & dihedralFactory ()
Get the associated Dihedral Factory by reference.
ExternalPotential & externalPotential ()
Get the ExternalPotential by reference.
std::string externalStyle () const
Return external potential style string.
Factory< ExternalPotential > & externalFactory ()
Get the associated External Factory by reference.
Atom and Group Containers
AtomStorage & atomStorage ()
Get the AtomStorage by reference.
BondStorage & bondStorage ()
Get the BondStorage by reference.
AngleStorage & angleStorage ()
Get the AngleStorage by reference.
DihedralStorage & dihedralStorage ()
Get the DihedralStorage by reference.
Miscellaneous Accessors (return members by reference)
Domain & domain ()
Get the Domain by reference.
Boundary & boundary ()
Get the Boundary by reference.
AtomType & atomType (int i)
Get an AtomType descriptor by reference.
Integrator & integrator ()
Get the Integrator by reference.
EnergyEnsemble & energyEnsemble ()
Get the EnergyEnsemble by reference.
BoundaryEnsemble & boundaryEnsemble ()
Get the BoundaryEnsemble by reference.
FileMaster & fileMaster ()
Get the associated FileMaster by reference.
Random & random ()
Get the Random number generator by reference.
Exchanger & exchanger ()
Get the Exchanger by reference.
Buffer & buffer ()
Get the Buffer by reference.
ModifierManager & modifierManager ()
Return the ModifierManager by reference.
AnalyzerManager & analyzerManager ()
Return the AnalyzerManager by reference.
Factory< Integrator > & integratorFactory ()
Get the Integrator factory by reference.
Accessors (return by value)
int nAtomType ()
Get maximum number of atom types.
int nBondType ()
Get maximum number of bond types.
int nAngleType ()
Get maximum number of angle types.
int nDihedralType ()
Get maximum number of dihedral types.
bool hasExternal ()
Does this simulation have an external potential?
MaskPolicy maskedPairPolicy () const
Return the value of the mask policy (MaskNone or MaskBonded).
bool reverseUpdateFlag () const
Is reverse communication enabled?
Signals
Signal & modifySignal ()
Signal to force unsetting of quantities that depend on x, v, or f.
Signal & positionSignal ()
Signal to indicate change in atomic positions.
Signal & velocitySignal ()
Signal to indicate change in atomic velocities.
Signal & exchangeSignal ()
Signal to indicate exchange of atoms and groups.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
void readFileMaster (std::istream &in)
Read the FileMaster.
void loadFileMaster (Serializable::IArchive &ar)
Load FileMaster from an archive.
void saveFileMaster (Serializable::OArchive &ar)
Save FileMaster to archive.
void readPotentialStyles (std::istream &in)
Read potential styles and maskedPairPolicy.
void loadPotentialStyles (Serializable::IArchive &ar)
Load potential styles.
void savePotentialStyles (Serializable::OArchive &ar)
Save potential styles to archive.
void readEnsembles (std::istream &in)
Read energy and boundary ensembles.
void loadEnsembles (Serializable::IArchive &ar)
Load energy and boundary ensembles from an input archive.
void saveEnsembles (Serializable::OArchive &ar)
Save energy and boundary ensembles to archive.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Constructor & Destructor Documentation
DdMd::Simulation::Simulation (MPI::Intracomm & communicator = MPI::COMM_WORLD)
Constructor.
Parameters
communicator MPI communicator for MD processors.
Definition at line 80 of file ddMd/simulation/Simulation.cpp.
References Util::IntVector::commitMpiType(), Util::Vector::commitMpiType(), Util::initStatic(), DdMd::AtomType::initStatic(), and UTIL_THROW.
DdMd::Simulation::~Simulation ()
Destructor.
Definition at line 211 of file ddMd/simulation/Simulation.cpp.
Member Function Documentation
void DdMd::Simulation::setOptions (int argc, char *const * argv)
Process command line options.
Options:
-e Enable echoing of the parameter file to the log file as it is read.
-s nSystem [int] Enable multi system simulation, using different groups of processors for different systems. Integer argument nSystem is the number of systems. The rank of the communicator passed to the constructor must be an integer multiple of nSystem.
-r filename [string] Restarts a simulation from a checkpoint file. The name of the checkpoint file is filename + ".rst", i..e., it is obtained by adding a suffix ".rst" to the filename argument. Also sets the default command file name to filename + ".cmd".
The parameters are the same as those passed to any C/C++ main program, which contain the command line arguments:
Parameters
argc number of command line arguments
argv C-array of C-string argument strings
Definition at line 292 of file ddMd/simulation/Simulation.cpp.
References Util::Log::file(), Util::ParamComponent::setEcho(), Util::Log::setFile(), and UTIL_THROW.
void DdMd::Simulation::readParam () virtual
Read parameters from default parameter file.
Definition at line 372 of file ddMd/simulation/Simulation.cpp.
void DdMd::Simulation::readParam (std::istream & in) virtual
Read parameters.
This version includes the opening and closing blocks. Does nothing and returns if load() was called previously.
Reimplemented from Util::ParamComposite.
Definition at line 378 of file ddMd/simulation/Simulation.cpp.
void DdMd::Simulation::readParameters (std::istream & in) virtual
Read parameters, allocate memory and initialize.
Reimplemented from Util::ParamComposite.
Definition at line 398 of file ddMd/simulation/Simulation.cpp.
References unsetKineticEnergy(), unsetKineticStress(), DdMd::GroupStorage< 3 >::unsetNTotal(), DdMd::GroupStorage< 4 >::unsetNTotal(), DdMd::GroupStorage< 2 >::unsetNTotal(), unsetPotentialEnergies(), unsetVirialStress(), and UTIL_THROW.
void DdMd::Simulation::setReverseUpdateFlag (bool reverseUpdateFlag)
Set flag to identify if reverse communication is enabled.
Parameters
reverseUpdateFlag true if reverse communication is enabled.
Definition at line 1374 of file ddMd/simulation/Simulation.cpp.
void DdMd::Simulation::load (const std::string & filename)
Load internal state from a restart file.
Call on all processors. This function opens an archive file with a name given by concatentaing filename + ".rst" on the ioProcessor, calls load(Serializable::OArchive&), and closes the file. It also sets the default command file name to filename + ".cmd".
Parameters
filename base filename (add suffixes ".rst" and ".cmd")
Definition at line 791 of file ddMd/simulation/Simulation.cpp.
References Util::BinaryFileIArchive::file(), and UTIL_THROW.
void DdMd::Simulation::loadParameters (Serializable::IArchive & ar) virtual
Load parameters from a restart archive.
Call on all processors, but loads from archive only on ioProcessor. This function loads both parameter information and the system configuration.
Do not call this directly. Instead call load(const std::string&) or load(Serializable::IArchive&).
Parameters
ar input archive (open for reading on ioProcessor).
Reimplemented from Util::ParamComposite.
Definition at line 590 of file ddMd/simulation/Simulation.cpp.
References unsetKineticEnergy(), unsetKineticStress(), DdMd::GroupStorage< 3 >::unsetNTotal(), DdMd::GroupStorage< 4 >::unsetNTotal(), DdMd::GroupStorage< 2 >::unsetNTotal(), unsetPotentialEnergies(), unsetVirialStress(), and UTIL_THROW.
void DdMd::Simulation::save (const std::string & filename)
Save state to a restart file.
Call on all processors. Only writes from communicator ioProcessor. This function opens an archive file with a name given by filename
".rst" on the ioProcessor, calls save(Serializable::OArchive&), and closes the file.
Definition at line 908 of file ddMd/simulation/Simulation.cpp.
References Util::BinaryFileOArchive::file().
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::Simulation::save (Serializable::OArchive & ar) virtual
Save internal state to restart archive.
Used to implement save(std::string).
Reimplemented from Util::ParamComposite.
Definition at line 821 of file ddMd/simulation/Simulation.cpp.
References Util::Parameter::saveOptional().
void DdMd::Simulation::readCommands ()
Read and execute commands from the default command file.
This function calls readCommands(std::istream&) internally. The default command file is defined by the FileMaster. The file name is normally input in the parameter file.
Precondition
Same as readCommands(std::istream&)
Definition at line 1368 of file ddMd/simulation/Simulation.cpp.
void DdMd::Simulation::readCommands (std::istream & in)
Read and execute commands from a specific command file.
Precondition
Simulation must be initialized, by call to (read|load)Parameters.
AtomStorage coordinates are scaled / generalized (not Cartesian)
Parameters
in command file
Definition at line 1111 of file ddMd/simulation/Simulation.cpp.
References Util::Log::file(), Util::getNextLine(), Util::Memory::max(), and UTIL_THROW.
void DdMd::Simulation::setBoltzmannVelocities (double temperature)
Set random velocities chosen from Boltzmann distribution.
Parameters
temperature absolute temperature kT, in energy units.
Definition at line 1385 of file ddMd/simulation/Simulation.cpp.
References Util::Dimension, and Util::PArrayIterator< Data >::notEnd().
void DdMd::Simulation::zeroForces ()
Set forces for all local atoms to zero.
Definition at line 1404 of file ddMd/simulation/Simulation.cpp.
Referenced by DdMd::Integrator::computeForces(), and DdMd::Integrator::computeForcesAndVirial().
void DdMd::Simulation::readConfig (const std::string & filename)
Read configuration file on master and distribute atoms.
Upon return, all processors should have all atoms and groups, and a full set of ghost atoms, but values for the atomic forces are undefined.
Precondition
AtomStorage is set for scaled / generalized coordinates.
Postcondition
AtomStorage is set for scaled / generalized coordinates.
Parameters
filename name of input configuration file.
Definition at line 1917 of file ddMd/simulation/Simulation.cpp.
void DdMd::Simulation::writeConfig (const std::string & filename)
Write configuration file.
Precondition
AtomStorage coordinates are generalized / scaled
Parameters
filename name of output configuration file.
Definition at line 1933 of file ddMd/simulation/Simulation.cpp.
Referenced by DdMd::WriteConfig::sample().
Factory< ConfigIo > & DdMd::Simulation::configIoFactory ()
Get the configuration file reader/writer factory by reference.
Definition at line 2064 of file ddMd/simulation/Simulation.cpp.
void DdMd::Simulation::setConfigIo (std::string & classname)
Create a new configuration file reader/writer.
This method creates a new instance of the specified subclass of ConfigIo, and retains a pointer to the new object.
Parameters
classname name of ConfigIo subclass.
Definition at line 2076 of file ddMd/simulation/Simulation.cpp.
References DdMd::ConfigIo::initialize(), and UTIL_THROW.
void DdMd::Simulation::computeForces ()
Compute forces for all local atoms.
Upon return, forces are correct for all local atoms. Values of the forces on ghost atoms are undefined.
This method zeros all forces, adds forces from all potential energies, and carries out reverse communication if required (i.e., if reverseUpdateFlag is true).
Definition at line 1410 of file ddMd/simulation/Simulation.cpp.
Referenced by DdMd::Integrator::setupAtoms().
void DdMd::Simulation::computeForcesAndVirial ()
Compute forces for all local atoms and virial stress.
Upon return, forces are correct for all local atoms and virial stress values are set for all Potential objects. Values of the forces on ghost atoms are undefined.
This method zeros all forces, adds forces from all potential energies, and carries out reverse communication if required (i.e., if reverseUpdateFlag is true). It also calculates and sets each virial stress contribution.
Definition at line 1444 of file ddMd/simulation/Simulation.cpp.
Referenced by DdMd::Integrator::setupAtoms().
void DdMd::Simulation::computeKineticEnergy ()
Compute total kinetic energy.
Reduce operation: Must be called on all processors. Value is returned by calling kineticEnergy on master.
Definition at line 1480 of file ddMd/simulation/Simulation.cpp.
References Util::PArrayIterator< Data >::notEnd().
Referenced by DdMd::NphIntegrator::integrateStep1(), DdMd::NptIntegrator::integrateStep1(), DdMd::NvtIntegrator::integrateStep2(), DdMd::NphIntegrator::integrateStep2(), DdMd::NptIntegrator::integrateStep2(), DdMd::OutputTemperature::sample(), DdMd::OutputEnergy::sample(), DdMd::LogEnergy::sample(), DdMd::NvtIntegrator::setup(), DdMd::NphIntegrator::setup(), and DdMd::NptIntegrator::setup().
double DdMd::Simulation::kineticEnergy ()
Return precomputed total kinetic energy.
Call only on master node.
Returns
total kinetic energy for all nodes on master.
Definition at line 1518 of file ddMd/simulation/Simulation.cpp.
Referenced by DdMd::NphIntegrator::integrateStep1(), DdMd::NptIntegrator::integrateStep1(), DdMd::NvtIntegrator::integrateStep2(), DdMd::NphIntegrator::integrateStep2(), DdMd::NptIntegrator::integrateStep2(), DdMd::OutputTemperature::sample(), DdMd::LogEnergy::sample(), DdMd::OutputEnergy::sample(), and DdMd::NvtIntegrator::setup().
void DdMd::Simulation::unsetKineticEnergy ()
Mark kinetic energy as unknown.
Definition at line 1524 of file ddMd/simulation/Simulation.cpp.
Referenced by loadParameters(), and readParameters().
void DdMd::Simulation::computePotentialEnergies ()
Calculate and store total potential energy on all processors.
Reduce operation: Must be called on all nodes.
Definition at line 1609 of file ddMd/simulation/Simulation.cpp.
Referenced by DdMd::NphIntegrator::integrateStep2(), DdMd::NptIntegrator::integrateStep2(), DdMd::OutputEnergy::sample(), and DdMd::LogEnergy::sample().
double DdMd::Simulation::potentialEnergy () const
Return precomputed total potential energy.
Call only on master processor, after computePotentialEnergies. Calls the energy() methods of each of the potential classes.
Returns
total potential energy (only correct on master node).
Definition at line 1677 of file ddMd/simulation/Simulation.cpp.
Referenced by DdMd::NphIntegrator::integrateStep2(), and DdMd::NptIntegrator::integrateStep2().
void DdMd::Simulation::unsetPotentialEnergies ()
Mark all potential energies as unknown.
Definition at line 1709 of file ddMd/simulation/Simulation.cpp.
Referenced by loadParameters(), and readParameters().
void DdMd::Simulation::computePairEnergies ()
Compute pair energies for each pair of atom types.
Reduce operation: Must be called on all nodes.
Definition at line 1842 of file ddMd/simulation/Simulation.cpp.
Referenced by DdMd::OutputPairEnergies::sample().
DMatrix< double > DdMd::Simulation::pairEnergies () const
Return precomputed pair energies.
Call only on master processor, after computePairEnergies.
Returns
total pair energies (only correct on master node).
Definition at line 1855 of file ddMd/simulation/Simulation.cpp.
References Util::DMatrix< Data >::allocate().
Referenced by DdMd::OutputPairEnergies::sample().
void DdMd::Simulation::computeExternalEnergy ()
Compute pair energies for each pair of atom types.
Reduce operation: Must be called on all nodes.
double DdMd::Simulation::externalEnergy () const
Return precomputed pair energies.
Call only on master processor, after computePairEnergies.
Returns
total pair energies (only correct on master node).
void DdMd::Simulation::computeKineticStress ()
Calculate and store kinetic stress.
Reduce operation: Must be called on all nodes.
Definition at line 1534 of file ddMd/simulation/Simulation.cpp.
References Util::Dimension, Util::PArrayIterator< Data >::notEnd(), and Util::Tensor::zero().
Referenced by DdMd::NphIntegrator::integrateStep1(), DdMd::NptIntegrator::integrateStep1(), DdMd::NphIntegrator::integrateStep2(), DdMd::NptIntegrator::integrateStep2(), DdMd::OutputBoxdim::sample(), DdMd::OutputPressure::sample(), DdMd::OutputStressTensor::sample(), DdMd::VirialStressTensorAverage::sample(), and DdMd::NptIntegrator::setup().
Tensor DdMd::Simulation::kineticStress () const
Return total kinetic stress.
Call only on master processor, after computeKineticStress.
Returns
total kinetic stress (only correct on master node).
Definition at line 1581 of file ddMd/simulation/Simulation.cpp.
Referenced by DdMd::NphIntegrator::integrateStep1(), DdMd::NptIntegrator::integrateStep1(), DdMd::NphIntegrator::integrateStep2(), DdMd::NptIntegrator::integrateStep2(), DdMd::OutputStressTensor::sample(), and DdMd::VirialStressTensorAverage::sample().
double DdMd::Simulation::kineticPressure () const
Return total kinetic pressure.
Call only on master processor, after computeKineticStress.
Returns
total kinetic pressure only correct on master node).
Definition at line 1587 of file ddMd/simulation/Simulation.cpp.
References Util::Dimension.
Referenced by DdMd::OutputPressure::sample().
void DdMd::Simulation::unsetKineticStress ()
Mark kinetic stress as unknown.
Definition at line 1600 of file ddMd/simulation/Simulation.cpp.
Referenced by loadParameters(), and readParameters().
void DdMd::Simulation::computeVirialStress ()
Calculate and store all virial stress contributions.
Reduce operation: Must be called on all nodes. This calls the computeStress() method of each potential class.
Definition at line 1740 of file ddMd/simulation/Simulation.cpp.
Referenced by DdMd::NphIntegrator::integrateStep1(), DdMd::NptIntegrator::integrateStep1(), DdMd::NphIntegrator::integrateStep2(), DdMd::NptIntegrator::integrateStep2(), DdMd::OutputBoxdim::sample(), DdMd::OutputPressure::sample(), DdMd::OutputStressTensor::sample(), and DdMd::VirialStressTensorAverage::sample().
Tensor DdMd::Simulation::virialStress () const
Return total virial stress.
Call only on master processor, after computeVirialStress. This method calls the stress() method of each potential class (pair, bond, etc.) and adds and returns the sum.
Returns
total virial stress (only correct on master node).
Definition at line 1787 of file ddMd/simulation/Simulation.cpp.
References Util::Tensor::zero().
Referenced by DdMd::NphIntegrator::integrateStep1(), DdMd::NptIntegrator::integrateStep1(), DdMd::NphIntegrator::integrateStep2(), DdMd::NptIntegrator::integrateStep2(), DdMd::OutputStressTensor::sample(), and DdMd::VirialStressTensorAverage::sample().
double DdMd::Simulation::virialPressure () const
Return total virial pressure.
Call only on master processor, after computeVirialStress. Similar to virialStress, but returns average of diagonal elements.
Returns
total virial pressure (only correct on master node).
Definition at line 1815 of file ddMd/simulation/Simulation.cpp.
Referenced by DdMd::OutputPressure::sample().
void DdMd::Simulation::unsetVirialStress ()
Mark all virial stress contributions as unknown.
This method calls unsetStress for each potential energy.
Definition at line 1866 of file ddMd/simulation/Simulation.cpp.
Referenced by loadParameters(), and readParameters().
PairPotential & DdMd::Simulation::pairPotential () inline
Get the PairPotential by reference.
Definition at line 1052 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::LogEnergy::sample(), and DdMd::OutputEnergy::sample().
std::string DdMd::Simulation::pairStyle () const
Return nonbonded pair style string.
Definition at line 1963 of file ddMd/simulation/Simulation.cpp.
Factory< PairPotential > & DdMd::Simulation::pairFactory ()
Get the Factory<PairPotential> by reference.
Definition at line 1951 of file ddMd/simulation/Simulation.cpp.
BondPotential & DdMd::Simulation::bondPotential () inline
Get the PairPotential by reference.
Definition at line 1059 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::LogEnergy::sample(), and DdMd::OutputEnergy::sample().
std::string DdMd::Simulation::bondStyle () const
Return covalent bond style string.
Definition at line 1983 of file ddMd/simulation/Simulation.cpp.
Factory< BondPotential > & DdMd::Simulation::bondFactory ()
Get the Factory<BondPotential> by reference.
Definition at line 1971 of file ddMd/simulation/Simulation.cpp.
AnglePotential & DdMd::Simulation::anglePotential () inline
Get the AnglePotential by reference.
Definition at line 1067 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::LogEnergy::sample(), and DdMd::OutputEnergy::sample().
std::string DdMd::Simulation::angleStyle () const
Return angle potential style string.
Definition at line 2003 of file ddMd/simulation/Simulation.cpp.
Factory< AnglePotential > & DdMd::Simulation::angleFactory ()
Get the AngleFactory by reference.
Definition at line 1991 of file ddMd/simulation/Simulation.cpp.
DihedralPotential & DdMd::Simulation::dihedralPotential () inline
Get the DihedralPotential by reference.
Definition at line 1078 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::LogEnergy::sample(), and DdMd::OutputEnergy::sample().
std::string DdMd::Simulation::dihedralStyle () const
Return dihedral potential style string.
Definition at line 2023 of file ddMd/simulation/Simulation.cpp.
Factory< DihedralPotential > & DdMd::Simulation::dihedralFactory ()
Get the associated Dihedral Factory by reference.
Definition at line 2011 of file ddMd/simulation/Simulation.cpp.
ExternalPotential & DdMd::Simulation::externalPotential () inline
Get the ExternalPotential by reference.
Definition at line 1089 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::OutputEnergy::sample().
std::string DdMd::Simulation::externalStyle () const
Return external potential style string.
Definition at line 2043 of file ddMd/simulation/Simulation.cpp.
Factory< ExternalPotential > & DdMd::Simulation::externalFactory ()
Get the associated External Factory by reference.
Definition at line 2031 of file ddMd/simulation/Simulation.cpp.
AtomStorage & DdMd::Simulation::atomStorage () inline
Get the AtomStorage by reference.
Definition at line 1028 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::ConfigIo::ConfigIo(), DdMd::OutputTemperature::sample(), DdMd::OrderParamNucleation::sample(), DdMd::AsymmSF::sample(), DdMd::StructureFactor::sample(), and DdMd::VanHove::sample().
BondStorage & DdMd::Simulation::bondStorage () inline
Get the BondStorage by reference.
Definition at line 1032 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::ConfigIo::ConfigIo().
AngleStorage & DdMd::Simulation::angleStorage () inline
Get the AngleStorage by reference.
Definition at line 1037 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::ConfigIo::ConfigIo().
DihedralStorage & DdMd::Simulation::dihedralStorage () inline
Get the DihedralStorage by reference.
Definition at line 1042 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::ConfigIo::ConfigIo().
Domain & DdMd::Simulation::domain () inline
Get the Domain by reference.
Definition at line 1025 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::ConfigIo::ConfigIo(), DdMd::NphIntegrator::integrateStep1(), DdMd::NptIntegrator::integrateStep1(), DdMd::NphIntegrator::integrateStep2(), DdMd::NptIntegrator::integrateStep2(), DdMd::OutputBoxdim::sample(), DdMd::OutputEnergy::sample(), DdMd::LogEnergy::sample(), DdMd::OutputTemperature::sample(), DdMd::OutputPairEnergies::sample(), DdMd::OutputPressure::sample(), DdMd::OutputStressTensor::sample(), DdMd::VirialStressTensorAverage::sample(), DdMd::OrderParamNucleation::sample(), DdMd::AsymmSF::sample(), DdMd::StructureFactor::sample(), and DdMd::VanHove::sample().
Boundary & DdMd::Simulation::boundary () inline
Get the Boundary by reference.
Definition at line 1022 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::ConfigIo::ConfigIo(), DdMd::ExternalPotentialImpl< Interaction >::ExternalPotentialImpl(), DdMd::NphIntegrator::integrateStep1(), DdMd::NptIntegrator::integrateStep1(), DdMd::NphIntegrator::integrateStep2(), DdMd::NptIntegrator::integrateStep2(), DdMd::VanHove::makeWaveVectors(), DdMd::StructureFactor::makeWaveVectors(), DdMd::AsymmSF::makeWaveVectors(), DdMd::OrderParamNucleation::output(), DdMd::OutputBoxdim::sample(), DdMd::OrderParamNucleation::sample(), DdMd::StructureFactorGrid::sample(), DdMd::AsymmSF::sample(), and DdMd::StructureFactor::sample().
AtomType & DdMd::Simulation::atomType (int i) inline
Get an AtomType descriptor by reference.
Parameters
i index of desired atom type.
Definition at line 1196 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::NptIntegrator::integrateStep2(), DdMd::NvtIntegrator::setup(), DdMd::NveIntegrator::setup(), DdMd::NphIntegrator::setup(), and DdMd::NptIntegrator::setup().
Integrator & DdMd::Simulation::integrator () inline
Get the Integrator by reference.
Definition at line 1099 of file ddMd/simulation/Simulation.h.
EnergyEnsemble & DdMd::Simulation::energyEnsemble () inline
Get the EnergyEnsemble by reference.
Definition at line 1111 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::NvtIntegrator::integrateStep1(), DdMd::NptIntegrator::integrateStep1(), DdMd::NvtIntegrator::integrateStep2(), DdMd::NvtIntegrator::NvtIntegrator(), DdMd::NvtIntegrator::setup(), and DdMd::NptIntegrator::setup().
BoundaryEnsemble & DdMd::Simulation::boundaryEnsemble () inline
Get the BoundaryEnsemble by reference.
Definition at line 1120 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::NphIntegrator::integrateStep1(), DdMd::NptIntegrator::integrateStep1(), DdMd::NphIntegrator::setup(), and DdMd::NptIntegrator::setup().
FileMaster & DdMd::Simulation::fileMaster () inline
Get the associated FileMaster by reference.
Definition at line 1129 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::OutputBoxdim::loadParameters(), DdMd::OutputEnergy::loadParameters(), DdMd::OutputTemperature::loadParameters(), DdMd::OutputPairEnergies::loadParameters(), DdMd::OutputPressure::loadParameters(), DdMd::OutputStressTensor::loadParameters(), DdMd::VirialStressTensorAverage::loadParameters(), DdMd::AsymmSFGrid::output(), DdMd::OrderParamNucleation::output(), DdMd::StructureFactorGrid::output(), DdMd::AsymmSF::output(), DdMd::StructureFactor::output(), DdMd::VanHove::output(), DdMd::OutputBoxdim::readParameters(), DdMd::OutputEnergy::readParameters(), DdMd::OutputTemperature::readParameters(), DdMd::OutputPairEnergies::readParameters(), DdMd::OutputPressure::readParameters(), DdMd::OutputStressTensor::readParameters(), DdMd::VirialStressTensorAverage::readParameters(), DdMd::StructureFactorGrid::sample(), and DdMd::StructureFactor::sample().
Random & DdMd::Simulation::random () inline
Get the Random number generator by reference.
Definition at line 1105 of file ddMd/simulation/Simulation.h.
Exchanger & DdMd::Simulation::exchanger () inline
Get the Exchanger by reference.
Definition at line 1046 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::Integrator::clear().
Buffer & DdMd::Simulation::buffer () inline
Get the Buffer by reference.
Definition at line 1049 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::Integrator::clear(), and DdMd::ConfigIo::ConfigIo().
ModifierManager & DdMd::Simulation::modifierManager () inline
Return the ModifierManager by reference.
Definition at line 1139 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::TwoStepIntegrator::run().
AnalyzerManager & DdMd::Simulation::analyzerManager () inline
Return the AnalyzerManager by reference.
Definition at line 1149 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::Integrator::clear(), and DdMd::TwoStepIntegrator::run().
Factory< Integrator > & DdMd::Simulation::integratorFactory ()
Get the Integrator factory by reference.
Definition at line 2052 of file ddMd/simulation/Simulation.cpp.
int DdMd::Simulation::nAtomType () inline
Get maximum number of atom types.
Definition at line 1158 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::LammpsConfigIo::LammpsConfigIo(), DdMd::NvtIntegrator::loadParameters(), DdMd::NphIntegrator::loadParameters(), DdMd::NveIntegrator::loadParameters(), DdMd::NptIntegrator::loadParameters(), DdMd::OrderParamNucleation::loadParameters(), DdMd::StructureFactorGrid::loadParameters(), DdMd::StructureFactor::loadParameters(), DdMd::VanHove::loadParameters(), DdMd::PairPotentialImpl< Interaction >::PairPotentialImpl(), DdMd::NvtIntegrator::readParameters(), DdMd::NveIntegrator::readParameters(), DdMd::NphIntegrator::readParameters(), DdMd::NptIntegrator::readParameters(), DdMd::OrderParamNucleation::readParameters(), DdMd::AsymmSFGrid::readParameters(), DdMd::StructureFactorGrid::readParameters(), DdMd::AsymmSF::readParameters(), DdMd::StructureFactor::readParameters(), DdMd::VanHove::readParameters(), and DdMd::OutputPairEnergies::sample().
int DdMd::Simulation::nBondType () inline
Get maximum number of bond types.
Definition at line 1165 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::LammpsConfigIo::LammpsConfigIo(), DdMd::OutputEnergy::sample(), and DdMd::LogEnergy::sample().
int DdMd::Simulation::nAngleType () inline
Get maximum number of angle types.
Definition at line 1173 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::LammpsConfigIo::LammpsConfigIo(), DdMd::OutputEnergy::sample(), and DdMd::LogEnergy::sample().
int DdMd::Simulation::nDihedralType () inline
Get maximum number of dihedral types.
Definition at line 1181 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::LammpsConfigIo::LammpsConfigIo(), DdMd::OutputEnergy::sample(), and DdMd::LogEnergy::sample().
bool DdMd::Simulation::hasExternal () inline
Does this simulation have an external potential?
Definition at line 1189 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::OutputEnergy::sample().
MaskPolicy DdMd::Simulation::maskedPairPolicy () const inline
Return the value of the mask policy (MaskNone or MaskBonded).
Definition at line 1199 of file ddMd/simulation/Simulation.h.
bool DdMd::Simulation::reverseUpdateFlag () const inline
Is reverse communication enabled?
Definition at line 1202 of file ddMd/simulation/Simulation.h.
Signal & DdMd::Simulation::modifySignal () inline
Signal to force unsetting of quantities that depend on x, v, or f.
Signal to force unsetting of all computed quantities.
Definition at line 1206 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::TwoStepIntegrator::run().
Signal & DdMd::Simulation::positionSignal () inline
Signal to indicate change in atomic positions.
Definition at line 1210 of file ddMd/simulation/Simulation.h.
Signal & DdMd::Simulation::velocitySignal () inline
Signal to indicate change in atomic velocities.
Definition at line 1214 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::NvtIntegrator::integrateStep2(), DdMd::NphIntegrator::integrateStep2(), DdMd::NveIntegrator::integrateStep2(), and DdMd::NptIntegrator::integrateStep2().
Signal & DdMd::Simulation::exchangeSignal () inline
Signal to indicate exchange of atoms and groups.
Signal to indicate exchange of atom ownership.
Definition at line 1218 of file ddMd/simulation/Simulation.h.
Referenced by DdMd::TwoStepIntegrator::run().
bool DdMd::Simulation::isValid ()
Return true if this Simulation is valid, or throw an Exception.
Definition at line 2094 of file ddMd/simulation/Simulation.cpp.
References Util::bcast().
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::Simulation::readFileMaster (std::istream & in) protected
Read the FileMaster.
Parameters
in input parameter stream
Definition at line 952 of file ddMd/simulation/Simulation.cpp.
void DdMd::Simulation::loadFileMaster (Serializable::IArchive & ar) protected
Load FileMaster from an archive.
Parameters
ar input/loading archive
Definition at line 962 of file ddMd/simulation/Simulation.cpp.
void DdMd::Simulation::saveFileMaster (Serializable::OArchive & ar) protected
Save FileMaster to archive.
Parameters
ar output/saving archive
Definition at line 972 of file ddMd/simulation/Simulation.cpp.
void DdMd::Simulation::readPotentialStyles (std::istream & in) protected
Read potential styles and maskedPairPolicy.
Parameters
in input parameter stream
Definition at line 978 of file ddMd/simulation/Simulation.cpp.
void DdMd::Simulation::loadPotentialStyles (Serializable::IArchive & ar) protected
Load potential styles.
Parameters
ar input/loading archive
Definition at line 1016 of file ddMd/simulation/Simulation.cpp.
void DdMd::Simulation::savePotentialStyles (Serializable::OArchive & ar) protected
Save potential styles to archive.
Parameters
ar output/saving archive
Definition at line 1050 of file ddMd/simulation/Simulation.cpp.
void DdMd::Simulation::readEnsembles (std::istream & in) protected
Read energy and boundary ensembles.
Parameters
in input parameter stream
Definition at line 1082 of file ddMd/simulation/Simulation.cpp.
void DdMd::Simulation::loadEnsembles (Serializable::IArchive & ar) protected
Load energy and boundary ensembles from an input archive.
Parameters
ar input/loading archive
Definition at line 1091 of file ddMd/simulation/Simulation.cpp.
void DdMd::Simulation::saveEnsembles (Serializable::OArchive & ar) protected
Save energy and boundary ensembles to archive.
Parameters
ar output/saving archive
Definition at line 1100 of file ddMd/simulation/Simulation.cpp.
The documentation for this class was generated from the following files:
ddMd/simulation/Simulation.h
ddMd/simulation/Simulation.cpp