Simpatico: McMd::MdEnergyOutput Class Reference
McMd::MdEnergyOutput Class Reference
MD Analyzers
Detailed Description
Analyzer to output total potential and kinetic energies.
Definition at line 25 of file MdEnergyOutput.h.
#include <MdEnergyOutput.h>
Public Member Functions
virtual void readParameters (std::istream &in)
Read output file and nStepPerSample.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void sample (long iStep)
Evaluate energy and print.
virtual void output ()
Output final summary and file format.
Member Function Documentation
void McMd::MdEnergyOutput::readParameters (std::istream & in) [virtual]
Read output file and nStepPerSample.
Parameters:
in input parameter stream
Reimplemented from McMd::Analyzer.
Definition at line 29 of file MdEnergyOutput.cpp.
References McMd::Analyzer::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Analyzer::outputFileName(), McMd::Analyzer::readInterval(), and McMd::Analyzer::readOutputFileName().
void McMd::MdEnergyOutput::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::Analyzer.
Definition at line 39 of file MdEnergyOutput.cpp.
References McMd::Analyzer::fileMaster(), McMd::Analyzer::loadInterval(), McMd::Analyzer::loadOutputFileName(), Util::FileMaster::openOutputFile(), and McMd::Analyzer::outputFileName().
void McMd::MdEnergyOutput::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::Analyzer.
Definition at line 49 of file MdEnergyOutput.cpp.
template<class Archive > void McMd::MdEnergyOutput::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Analyzer.
Definition at line 86 of file MdEnergyOutput.h.
References McMd::serialize().
void McMd::MdEnergyOutput::sample (long iStep) [virtual]
Evaluate energy and print.
Implements McMd::Analyzer.
Definition at line 55 of file MdEnergyOutput.cpp.
References McMd::MdSystem::anglePotential(), McMd::MdSystem::bondPotential(), McMd::MdSystem::dihedralPotential(), McMd::PairPotential::energy(), McMd::AnglePotential::energy(), McMd::BondPotential::energy(), McMd::ExternalPotential::energy(), McMd::DihedralPotential::energy(), McMd::MdSystem::externalPotential(), McMd::Analyzer::isAtInterval(), McMd::MdSystem::kineticEnergy(), McMd::MdSystem::linkPotential(), McMd::MdSystem::pairPotential(), and McMd::SystemAnalyzer< MdSystem >::system().
void McMd::MdEnergyOutput::output () [virtual]
Output final summary and file format.
Reimplemented from McMd::Analyzer.
Definition at line 113 of file MdEnergyOutput.cpp.
References McMd::Analyzer::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Analyzer::outputFileName(), McMd::SystemAnalyzer< MdSystem >::system(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
MdEnergyOutput.h
MdEnergyOutput.cpp