Simpatico: McMd::CfbRebridgeMove Class Reference
McMd::CfbRebridgeMove Class Reference
Monte Carlo Moves
Detailed Description
Config-bias move for internal segment of a flexible linear polymer.
See Also
param file format
Definition at line 30 of file CfbRebridgeMove.h.
#include <CfbRebridgeMove.h>
Public Member Functions
CfbRebridgeMove (McSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read species to which displacement is applied.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual bool move ()
Generate and accept or reject configuration bias move.
Public Member Functions inherited from McMd::CfbRebridgeBase
CfbRebridgeBase (McSystem &system)
Constructor.
virtual ~CfbRebridgeBase ()
Destructor.
virtual void setup ()
Initialize the arrays for preferential angle, effective spring constant and normalization factor.
Public Member Functions inherited from McMd::CfbEndBase
CfbEndBase (McSystem &system)
Constructor.
virtual ~CfbEndBase ()
Destructor.
void deleteEndAtom (Atom *endPtr, Atom *pvtPtr, int bondType, double &rosenbluth, double &energy)
CFB algorithm for deleting an end atom from a flexible chain.
void addEndAtom (Atom *endPtr, Atom *pvtPtr, int bondType, double &rosenbluth, double &energy)
Configuration bias algorithm for adding an atom to a chain end.
Public Member Functions inherited from McMd::SystemMove
SystemMove (McSystem &system)
Constructor.
virtual ~SystemMove ()
Destructor.
Public Member Functions inherited from McMd::McMove
McMove (Simulation &simulation)
Constructor.
virtual ~McMove ()
Destructor.
void setProbability (double probability)
Set the probability for this McMove.
double probability () const
Return probability for this McMove.
long nAttempt () const
Return number of moves that have been attempted.
long nAccept () const
Return number of moves that have been accepted.
virtual void output ()
Output statistics for this move (called at the end of the simulation)
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Attributes
DArray< Vector > oldPos_
Array of old positions of temporarily deleted atoms.
int speciesId_
Integer index for molecular species.
int nRegrow_
Number of particles at end to attempt to regrow.
Protected Attributes inherited from McMd::CfbRebridgeBase
double length21_
Equilibrium bond lengths (2-1 bond).
double length10_
Equilibrium bond lengths (1-0 bonds).
double kappa10_
Spring constant (1-0 bond).
Protected Attributes inherited from McMd::CfbEndBase
int nTrial_
Actual number of trial positions for each regrown atom.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from McMd::CfbRebridgeBase
void deleteMiddleAtom (Atom *partPtr, Atom *prevPtr, Atom *nextPtr, int prevBType, int nextBType, double &rosenbluth, double &energy)
Configuration bias algorithm for deleting a particle between two monomers and compute the corresponding Rosenbluth factor.
void addMiddleAtom (Atom *partPtr, Atom *prevPtr, Atom *nextPtr, int prevBType, int nextBType, double &rosenbluth, double &energy)
Configuration bias algorithm for adding the last particle with special bias in favor of closing the bridge.
void deleteSequence (int nActive, int sign, Atom *endPtr, int *bonds, double &rosenbluth, double &energy)
Configuration bias algorithm for deleting a consequtive sequence of atoms.
void addSequence (int nActive, int sign, Atom *beginPtr, int *bonds, double &rosenbluth, double &energy)
Configuration bias algorithm for adding a consequtive sequence of atoms.
Static Protected Attributes inherited from McMd::CfbEndBase
static const int MaxTrial_ = 20
Maximum allowed number of trial positions for a regrown atom.
Constructor & Destructor Documentation
McMd::CfbRebridgeMove::CfbRebridgeMove (McSystem & system)
Constructor.
Definition at line 29 of file CfbRebridgeMove.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::CfbRebridgeMove::readParameters (std::istream & in) virtual
Read species to which displacement is applied.
Reimplemented from McMd::CfbRebridgeBase.
Definition at line 38 of file CfbRebridgeMove.cpp.
References nRegrow_, oldPos_, McMd::CfbRebridgeBase::readParameters(), McMd::McMove::readProbability(), McMd::CfbRebridgeBase::setup(), McMd::McMove::simulation(), McMd::Simulation::species(), speciesId_, and UTIL_THROW.
void McMd::CfbRebridgeMove::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from McMd::CfbRebridgeBase.
Definition at line 65 of file CfbRebridgeMove.cpp.
References McMd::CfbRebridgeBase::loadParameters(), McMd::McMove::loadParameters(), nRegrow_, oldPos_, McMd::CfbRebridgeBase::setup(), McMd::McMove::simulation(), McMd::Simulation::species(), speciesId_, and UTIL_THROW.
void McMd::CfbRebridgeMove::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from McMd::CfbRebridgeBase.
Definition at line 88 of file CfbRebridgeMove.cpp.
References nRegrow_, McMd::CfbRebridgeBase::save(), McMd::McMove::save(), and speciesId_.
bool McMd::CfbRebridgeMove::move () virtual
Generate and accept or reject configuration bias move.
Reimplemented from McMd::McMove.
Definition at line 108 of file CfbRebridgeMove.cpp.
References McMd::CfbRebridgeBase::addSequence(), McMd::Molecule::atom(), McMd::Molecule::bond(), McMd::CfbRebridgeBase::deleteSequence(), McMd::McMove::incrementNAccept(), McMd::McMove::incrementNAttempt(), Util::Random::metropolis(), McMd::Molecule::nAtom(), nRegrow_, oldPos_, McMd::McSystem::pairPotential(), McMd::Atom::position(), McMd::McMove::random(), McMd::System::randomMolecule(), speciesId_, McMd::SystemMove::system(), McMd::Group< NAtom >::typeId(), Util::Random::uniformInt(), McMd::McPairPotential::updateAtomCell(), and UTIL_THROW.
Member Data Documentation
DArray<Vector> McMd::CfbRebridgeMove::oldPos_ protected
Array of old positions of temporarily deleted atoms.
Definition at line 67 of file CfbRebridgeMove.h.
Referenced by loadParameters(), move(), and readParameters().
int McMd::CfbRebridgeMove::speciesId_ protected
Integer index for molecular species.
Definition at line 70 of file CfbRebridgeMove.h.
Referenced by loadParameters(), move(), readParameters(), and save().
int McMd::CfbRebridgeMove::nRegrow_ protected
Number of particles at end to attempt to regrow.
Definition at line 73 of file CfbRebridgeMove.h.
Referenced by loadParameters(), move(), readParameters(), and save().
The documentation for this class was generated from the following files:
CfbRebridgeMove.h
CfbRebridgeMove.cpp