Simpatico: McMd::GroupRebridgeBase Class Reference
McMd::GroupRebridgeBase Class Reference
McMd namespace » Monte Carlo Moves
Detailed Description
Base class for rebridging a group of atoms forming a tetrahedron.
Definition at line 32 of file GroupRebridgeBase.h.
#include <GroupRebridgeBase.h>
Public Member Functions
GroupRebridgeBase (McSystem &system)
Constructor.
virtual ~GroupRebridgeBase ()
Destructor.
void tetraEnergy (Atom *aPtr, Atom *bPtr, Atom *cPtr, Atom *dPtr, int bondType, double &energy)
Calculate the energy cost for rebriding a tetra group.
double angleEnergy (const Atom &a, const Atom &b, const Atom &c, int type)
Calculate the angle energy for a bead triple.
void octaEnergy (Atom *aPtr, Atom *bPtr, Atom *cPtr, Atom *dPtr, Atom *mPtr, Atom *nPtr, int bondType, double &energy)
Calculate the energy cost for rebriding an octa group.
Public Member Functions inherited from McMd::SystemMove
SystemMove (McSystem &system)
Constructor.
virtual ~SystemMove ()
Destructor.
Public Member Functions inherited from McMd::McMove
McMove (Simulation &simulation)
Constructor.
virtual ~McMove ()
Destructor.
virtual void readParameters (std::istream &in)
Read required parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void setProbability (double probability)
Set the probability for this McMove.
virtual void setup ()
Setup before the beginning of each simulation run.
virtual bool move ()
Generate, attempt, and accept or reject a Monte Carlo move.
double probability () const
Return probability for this McMove.
long nAttempt () const
Return number of moves that have been attempted.
long nAccept () const
Return number of moves that have been accepted.
virtual void output ()
Output statistics for this move (called at the end of the simulation)
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from McMd::SystemMove
McSystem & system ()
Get parent McSystem.
Boundary & boundary ()
Get Boundary object of parent McSystem.
EnergyEnsemble & energyEnsemble ()
Get EnergyEnsemble object of parent McSystem.
double boltzmann (double energy)
Boltzmann weight associated with an energy difference.
Protected Member Functions inherited from McMd::McMove
void incrementNAttempt ()
Increment the number of attempted moves.
void incrementNAccept ()
Increment the number of accepted moves.
Simulation & simulation ()
Get parent Simulation object.
Random & random ()
Get Random number generator of parent Simulation.
void readProbability (std::istream &in)
Read the probability from file.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Constructor & Destructor Documentation
McMd::GroupRebridgeBase::GroupRebridgeBase (McSystem & system)
Constructor.
Definition at line 24 of file GroupRebridgeBase.cpp.
References McMd::McSystem::hasDihedralPotential(), and UTIL_THROW.
McMd::GroupRebridgeBase::~GroupRebridgeBase () virtual
Destructor.
Definition at line 38 of file GroupRebridgeBase.cpp.
Member Function Documentation
void McMd::GroupRebridgeBase::tetraEnergy (Atom * aPtr, Atom * bPtr, Atom * cPtr, Atom * dPtr, int bondType, double & energy)
Calculate the energy cost for rebriding a tetra group.
Parameters
aPtr ptr to a atom
bPtr ptr to b atom
cPtr ptr to c atom
dPtr ptr to d atom
bondType bondType
energy energy cost of rebridging
Definition at line 53 of file GroupRebridgeBase.cpp.
References angleEnergy(), McMd::Group< NAtom >::atom(), McMd::McSystem::bondPotential(), McMd::SystemMove::boundary(), Util::OrthorhombicBoundary::distanceSq(), McMd::PairPotential::energy(), McMd::BondPotential::energy(), McMd::getAtomAngles(), McMd::getAtomBonds(), McMd::McSystem::pairPotential(), McMd::Atom::position(), Util::FSArray< Data, Capacity >::size(), McMd::SystemMove::system(), and McMd::Atom::typeId().
Referenced by McMd::RingTetraRebridgeMove::move().
double McMd::GroupRebridgeBase::angleEnergy (const Atom & a, const Atom & b, const Atom & c, int type) inline
Calculate the angle energy for a bead triple.
a – b – c
Parameters
a atom a
b atom b
c atom c
type angle type
Definition at line 95 of file GroupRebridgeBase.h.
References Util::Vector::abs(), Util::Vector::dot(), and McMd::Atom::position().
Referenced by tetraEnergy().
void McMd::GroupRebridgeBase::octaEnergy (Atom * aPtr, Atom * bPtr, Atom * cPtr, Atom * dPtr, Atom * mPtr, Atom * nPtr, int bondType, double & energy)
Calculate the energy cost for rebriding an octa group.
Parameters
aPtr ptr to a atom
bPtr ptr to b atom
cPtr ptr to c atom
dPtr ptr to d atom
mPtr ptr to d atom
nPtr ptr to d atom
bondType bondType
energy energy cost of rebridging
Definition at line 188 of file GroupRebridgeBase.cpp.
References McMd::McSystem::bondPotential(), McMd::SystemMove::boundary(), Util::OrthorhombicBoundary::distanceSq(), McMd::PairPotential::energy(), McMd::BondPotential::energy(), McMd::McSystem::pairPotential(), McMd::Atom::position(), McMd::SystemMove::system(), and McMd::Atom::typeId().
The documentation for this class was generated from the following files:
GroupRebridgeBase.h
GroupRebridgeBase.cpp