Simpatico: DdMd::AnalyzerFactory Class Reference
DdMd::AnalyzerFactory Class Reference
DdMd namespace » Analyzers
Detailed Description
Factory for DdMd::Analyzer objects.
Definition at line 27 of file AnalyzerFactory.h.
#include <AnalyzerFactory.h>
Public Member Functions
AnalyzerFactory (Simulation &simulation)
Constructor.
virtual Analyzer * factory (const std::string &className) const
Return pointer to a new Analyzer object.
Public Member Functions inherited from Util::Factory< Analyzer >
Factory ()
Constructor.
virtual ~Factory ()
Destructor.
void addSubfactory (Factory< Analyzer > &subfactory)
Add a new subfactory to the list.
Analyzer * readObject (std::istream &in, ParamComposite &parent, std::string &className, bool &isEnd)
Read a class name, instantiate an object, and read its parameters.
Analyzer * loadObject (Serializable::IArchive &ar, ParamComposite &parent, std::string &className)
Load a class name, instantiate an object, and load the object.
Protected Member Functions
Simulation & simulation () const
Return reference to parent Simulation.
Protected Member Functions inherited from Util::Factory< Analyzer >
Analyzer * trySubfactories (const std::string &className) const
Search through subfactories for match.
void setIoCommunicator (MPI::Intracomm &communicator)
Set associated Mpi communicator.
bool hasIoCommunicator () const
Does this factory have a param communicator?
Constructor & Destructor Documentation
Tools::AnalyzerFactory::AnalyzerFactory (Simulation & simulation)
Constructor.
Parameters
simulation parent Simulation
Definition at line 62 of file ddMd/analyzers/AnalyzerFactory.cpp.
Member Function Documentation
Analyzer * Tools::AnalyzerFactory::factory (const std::string & className) const virtual
Return pointer to a new Analyzer object.
Parameters
className name of a subclass of Analyzer.
Returns
base class pointer to a new instance of className.
Implements Util::Factory< Analyzer >.
Definition at line 69 of file ddMd/analyzers/AnalyzerFactory.cpp.
References simulation(), and Util::Factory< Analyzer >::trySubfactories().
Simulation& DdMd::AnalyzerFactory::simulation () const inline protected
Return reference to parent Simulation.
Definition at line 52 of file AnalyzerFactory.h.
Referenced by factory().
The documentation for this class was generated from the following files:
AnalyzerFactory.h
ddMd/analyzers/AnalyzerFactory.cpp