Simpatico: McMd::SmpConfigIo Class Reference
McMd::SmpConfigIo Class Reference
McMd namespace » Configuration File IO
Detailed Description
Common configuration file format for simpatico.
Definition at line 31 of file SmpConfigIo.h.
#include <SmpConfigIo.h>
Public Member Functions
SmpConfigIo (System &system)
Constructor.
virtual ~SmpConfigIo ()
Destructor.
virtual void read (std::istream &in)
Read configuration (particle positions) from file.
virtual void write (std::ostream &out)
Write configuration (particle positions) to file.
Public Member Functions inherited from McMd::ConfigIo
ConfigIo (System &system)
Constructor.
virtual ~ConfigIo ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from McMd::ConfigIo
System & system () const
Get a reference to the parent System.
Simulation & simulation () const
Get a reference to the parent Simulation.
Boundary & boundary () const
Get the Boundary.
Constructor & Destructor Documentation
McMd::SmpConfigIo::SmpConfigIo (System & system)
Constructor.
Definition at line 34 of file SmpConfigIo.cpp.
McMd::SmpConfigIo::~SmpConfigIo () virtual
Destructor.
Definition at line 41 of file SmpConfigIo.cpp.
Member Function Documentation
void McMd::SmpConfigIo::read (std::istream & in) virtual
Read configuration (particle positions) from file.
Parameters
in input file stream.
Implements McMd::ConfigIo.
Definition at line 47 of file SmpConfigIo.cpp.
References McMd::System::addMolecule(), Util::DArray< Data >::allocate(), Simp::Species::atomTypeId(), McMd::Molecule::begin(), McMd::ConfigIo::boundary(), Simp::Species::capacity(), McMd::Simulation::getMolecule(), Util::FlagSet::isActive(), Util::Label::isClear(), Util::Label::match(), Simp::Species::matchStructure(), Simp::Species::nAtom(), Util::ArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::FlagSet::setActualOrdered(), Simp::OrthorhombicBoundary::shift(), McMd::ConfigIo::simulation(), McMd::Simulation::species(), McMd::ConfigIo::system(), UTIL_CHECK, and UTIL_THROW.
void McMd::SmpConfigIo::write (std::ostream & out) virtual
Write configuration (particle positions) to file.
Parameters
out output file stream.
Implements McMd::ConfigIo.
Definition at line 237 of file SmpConfigIo.cpp.
References McMd::System::begin(), McMd::ConfigIo::boundary(), Util::Label::isClear(), Simp::Species::nAtom(), McMd::System::nMolecule(), Util::ConstArrayIterator< Data >::notEnd(), Util::ConstPArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), McMd::ConfigIo::simulation(), McMd::Simulation::species(), McMd::ConfigIo::system(), UTIL_CHECK, and Simp::Species::writeStructure().
The documentation for this class was generated from the following files:
SmpConfigIo.h
SmpConfigIo.cpp