Simpatico: McMd::AnglePotential Class Reference
McMd::AnglePotential Class Reference abstract
McMd namespace » Potential Energies » Angle Potentials
Detailed Description
Interface for a Angle Interaction.
Definition at line 33 of file mcMd/potentials/angle/AnglePotential.h.
#include <AnglePotential.h>
Public Member Functions
AnglePotential ()
Constructor.
virtual ~AnglePotential ()
Destructor (does nothing)
Angle Interaction interface
virtual double energy (double cosTheta, int type) const =0
Returns potential energy for one angle.
virtual void force (const Vector &R1, const Vector &R2, Vector &F1, Vector &F2, int type) const =0
Returns forces along two bonds at the angle, for use in MD and stress calculation.
virtual double randomAngle (Util::Random *random, double beta, int type) const =0
Return bond angle chosen from equilibrium distribution.
virtual double randomCosineAngle (Util::Random *random, double beta, int type) const =0
Return bond angle chosen from equilibrium distribution.
virtual void set (std::string name, int type, double value)=0
Modify an interaction parameter, identified by a string.
virtual double get (std::string name, int type) const =0
Get an interaction parameter value, identified by a string.
virtual std::string interactionClassName () const =0
Return name of pair interaction class (e.g., "HarmonicAngle").
System energy, force, and stress.
virtual double atomEnergy (const Atom &atom) const
Calculate the covalent bond energy for one Atom.
virtual void addForces ()
Add bond forces to all atomic forces.
virtual double energy () const =0
Calculate the total angle potential energy for the System.
virtual void computeStress (double &stress) const =0
Compute total angle potential isotropic pressure contribution.
virtual void computeStress (Util::Vector &stress) const =0
Compute x, y, z angle potential pressure components.
virtual void computeStress (Util::Tensor &stress) const =0
Compute angle potential stress tensor contribution.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void readParameters (std::istream &in)
Read the body of parameter block, without begin and end lines.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Constructor & Destructor Documentation
McMd::AnglePotential::AnglePotential ()
Constructor.
Definition at line 16 of file mcMd/potentials/angle/AnglePotential.cpp.
References Util::ParamComposite::setClassName().
McMd::AnglePotential::~AnglePotential () virtual
Destructor (does nothing)
Definition at line 22 of file mcMd/potentials/angle/AnglePotential.cpp.
Member Function Documentation
virtual double McMd::AnglePotential::energy (double cosTheta, int type) const pure virtual
Returns potential energy for one angle.
Parameters
cosTheta cosine of the bend angle.
type type of bend angle.
Implemented in McMd::AnglePotentialImpl< Interaction >.
Referenced by McMd::CfbLinear::addAtom(), McMd::CfbLinear::deleteAtom(), McMd::CfbEndBase::deleteEndAtom(), McMd::McSystem::potentialEnergy(), McMd::MdSystem::potentialEnergy(), McMd::McNVTChemicalPotential::sample(), McMd::MdEnergyOutput::sample(), and McMd::McEnergyOutput::sample().
virtual void McMd::AnglePotential::force (const Vector & R1, const Vector & R2, Vector & F1, Vector & F2, int type) const pure virtual
Returns forces along two bonds at the angle, for use in MD and stress calculation.
Parameters
R1 bond vector from atom 1 to 2.
R2 bond vector from atom 2 to 3.
F1 return force along R1 direction.
F2 return force along R2 direction.
type type of angle.
Implemented in McMd::AnglePotentialImpl< Interaction >.
virtual double McMd::AnglePotential::randomAngle (Util::Random * random, double beta, int type) const pure virtual
Return bond angle chosen from equilibrium distribution.
This function returns a bond length chosen from the Boltzmann distribution of lengths for bonds of random orientation. The distribution P(l) of values of the length l is proportional to l*l*exp[-beta*phi(l) ], where phi(l) is the bond energy.
Parameters
random pointer to random number generator object.
beta inverse temperature
type integer angle typd index
Returns
angle chosen from equilibrium distribution.
Implemented in McMd::AnglePotentialImpl< Interaction >.
Referenced by McMd::McNVTChemicalPotential::sample().
virtual double McMd::AnglePotential::randomCosineAngle (Util::Random * random, double beta, int type) const pure virtual
Return bond angle chosen from equilibrium distribution.
This function returns a bond length chosen from the Boltzmann distribution of lengths for bonds of random orientation. The distribution P(l) of values of the length l is proportional to l*l*exp[-beta*phi(l) ], where phi(l) is the bond energy.
Parameters
random pointer to random number generator object.
beta inverse temperature
type bond type
Returns
angle cosine chosen from equilibrium distribution.
Implemented in McMd::AnglePotentialImpl< Interaction >.
virtual void McMd::AnglePotential::set (std::string name, int type, double value) pure virtual
Modify an interaction parameter, identified by a string.
Parameters
name parameter name
type angle type index
value new value of parameter
Implemented in McMd::AnglePotentialImpl< Interaction >.
Referenced by McMd::MdSimulation::readCommands(), and McMd::McSimulation::readCommands().
virtual double McMd::AnglePotential::get (std::string name, int type) const pure virtual
Get an interaction parameter value, identified by a string.
Parameters
name parameter name
type angle type index 1
Implemented in McMd::AnglePotentialImpl< Interaction >.
virtual std::string McMd::AnglePotential::interactionClassName () const pure virtual
Return name of pair interaction class (e.g., "HarmonicAngle").
Implemented in McMd::AnglePotentialImpl< Interaction >.
virtual double McMd::AnglePotential::atomEnergy (const Atom & atom) const inline virtual
Calculate the covalent bond energy for one Atom.
Default method throws an exception.This allows testing of subclasses that only work for MD simulation, and crash gracefully if used for MC.
Parameters
atom Atom object of interest
Returns
bond potential energy of atom
Reimplemented in McMd::AnglePotentialImpl< Interaction >.
Definition at line 141 of file mcMd/potentials/angle/AnglePotential.h.
References UTIL_THROW.
Referenced by McMd::CfbRebridgeBase::addMiddleAtom(), McMd::McSystem::atomPotentialEnergy(), and McMd::CfbRebridgeBase::deleteMiddleAtom().
virtual void McMd::AnglePotential::addForces () inline virtual
Add bond forces to all atomic forces.
Default version throws an exception.This allows testing of subclasses that only work for MC simulation, and crash gracefully if used for MD.
Reimplemented in McMd::AnglePotentialImpl< Interaction >.
Definition at line 153 of file mcMd/potentials/angle/AnglePotential.h.
References UTIL_THROW.
Referenced by McMd::MdSystem::calculateForces().
virtual double McMd::AnglePotential::energy () const pure virtual
Calculate the total angle potential energy for the System.
Implemented in McMd::AnglePotentialImpl< Interaction >.
virtual void McMd::AnglePotential::computeStress (double & stress) const pure virtual
Compute total angle potential isotropic pressure contribution.
Parameters
stress (output) pressure.
Implemented in McMd::AnglePotentialImpl< Interaction >.
virtual void McMd::AnglePotential::computeStress (Util::Vector & stress) const pure virtual
Compute x, y, z angle potential pressure components.
Parameters
stress (output) pressure components.
Implemented in McMd::AnglePotentialImpl< Interaction >.
virtual void McMd::AnglePotential::computeStress (Util::Tensor & stress) const pure virtual
Compute angle potential stress tensor contribution.
Parameters
stress (output) stress tensor contribution.
Implemented in McMd::AnglePotentialImpl< Interaction >.
The documentation for this class was generated from the following files:
mcMd/potentials/angle/AnglePotential.h
mcMd/potentials/angle/AnglePotential.cpp