Simpatico: McMd::LinkPotentialImpl< Interaction > Class Template Reference
McMd::LinkPotentialImpl< Interaction > Class Template Reference
Detailed Description
template<class Interaction>
class McMd::LinkPotentialImpl< Interaction >
Template implementation of an BondPotential for links.
A LinkPotential implements the BondPotential interface, and uses an instance of a bond interaction class, but uses the LinkMaster of the parent System to identify linked atoms.
Definition at line 39 of file LinkPotentialImpl.h.
#include <LinkPotentialImpl.h>
Public Member Functions
LinkPotentialImpl (System &system)
Constructor.
LinkPotentialImpl (LinkPotentialImpl< Interaction > &other)
Copy constructor.
virtual ~LinkPotentialImpl ()
Destructor.
virtual void readParameters (std::istream &in)
Read potential energy.
Interaction & interaction ()
Return bond interaction by reference.
const Interaction & interaction () const
Return bond interaction by const reference.
Bond interaction interface.
virtual double energy (double rsq, int bondTypeId) const
Return pair energy for a single pair.
virtual double forceOverR (double rsq, int bondTypeId) const
Return force / separation for a single pair.
virtual double randomBondLength (Random *random, double beta, int bondTypeId) const
Return force / separation for a single pair.
void set (std::string name, int type, double value)
Modify a parameter, identified by a string.
double get (std::string name, int type) const
Get a parameter value, identified by a string.
virtual std::string interactionClassName () const
Return pair interaction class name (e.g., "HarmonicBond").
System energy, force and stress.
virtual double atomEnergy (const Atom &atom) const
Calculate the link potential energy for one Atom.
virtual double energy () const
Return total link potential energy of the System.
virtual void addForces ()
Compute and increment link forces for all atoms.
virtual void computeStress (double &stress) const
Compute total nonbonded pressure.
virtual void computeStress (Util::Vector &stress) const
Compute x, y, z nonbonded pressures.
virtual void computeStress (Util::Tensor &stress) const
Compute stress tensor.
Public Member Functions inherited from McMd::BondPotential
BondPotential ()
Constructor .
virtual ~BondPotential ()
Destructor (does nothing)
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
std::string className () const
Get class name string.
virtual void readParam (std::istream &in)
Read a parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an archive.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void resetParam ()
Resets ParamComposite to its empty state.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add a new Param < Type > object, and read its value.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add a C array parameter, and read its elements.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and read its elements.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n)
Add and read a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
Begin & readBegin (std::istream &in, const char *label)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a child ParamComposite.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add a new Param < Type > object, and load its value.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add a C array parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and load its elements.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n)
Add and load a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a DMatrix < Type > C two-dimensional matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
template<typename Type >
ScalarParam< Type > & add (const char *label, Type &value)
Add a new Param < Type > object to the format array.
template<typename Type >
CArrayParam< Type > & addCArray (const char *label, Type *value, int n)
Add a C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (const char *label, DArray< Type > &array, int n)
Add a DArray<Type> parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (const char *label, FArray< Type, N > &array)
Add a FArray<Type> parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (const char *label, Type *value, int m, int n)
Add a C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & addDMatrix (const char *label, DMatrix< Type > &matrix, int m, int n)
Add a C two-dimensional array parameter.
Begin & addBegin (const char *label)
Add a class label and opening bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Add a new Blank object, representing a blank line.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have a communicator?
MPI::Intracomm & ioCommunicator () const
Get the communicator.
Public Member Functions inherited from McMd::SubSystem
SubSystem (System &parent)
Constructor.
virtual ~SubSystem ()
Destructor.
System & system () const
Get the parent System by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
Protected Member Functions inherited from McMd::SubSystem
Boundary & boundary () const
Get the Boundary by reference.
Simulation & simulation () const
Get the parent Simulation by reference.
int nMolecule (int speciesId) const
Get the number of molecules of one Species in this SubSystem.
int nAtom () const
Return the total number of atoms in this SubSystem.
bool isEmpty () const
Is this an empty SubSystem (i.e., one with no molecules) ?
void begin (int speciesId, System::MoleculeIterator &iterator)
Initialize an iterator for molecules of one species in this SubSystem.
void begin (int speciesId, System::ConstMoleculeIterator &iterator) const
Initialize a const iterator for molecules of one species in this SubSystem.
bool hasBonds () const
Does a bond potential exist?
bool hasAngles () const
Does an angle potential exist?
bool hasDihedrals () const
Does a dihedral potential exist?
bool hasLinks () const
Does a link potential exist?
bool hasExternal () const
Does an external potential exist?
Constructor & Destructor Documentation
template<class Interaction > McMd::LinkPotentialImpl< Interaction >::LinkPotentialImpl (System & system)
Constructor.
Definition at line 209 of file LinkPotentialImpl.h.
References Util::ParamComposite::setClassName().
template<class Interaction > McMd::LinkPotentialImpl< Interaction >::LinkPotentialImpl (LinkPotentialImpl< Interaction > & other)
Copy constructor.
Definition at line 224 of file LinkPotentialImpl.h.
References Util::ParamComposite::setClassName().
template<class Interaction > McMd::LinkPotentialImpl< Interaction >::~LinkPotentialImpl () virtual
Destructor.
Definition at line 237 of file LinkPotentialImpl.h.
Member Function Documentation
template<class Interaction > void McMd::LinkPotentialImpl< Interaction >::readParameters (std::istream & in) virtual
Read potential energy.
This method reads the bond potential Interaction parameter block. Before calling Interaction::readParameters(), it passes simulation().nBondType() to Interaction::setNBondType().
Reimplemented from Util::ParamComposite.
Definition at line 244 of file LinkPotentialImpl.h.
template<class Interaction > double McMd::LinkPotentialImpl< Interaction >::energy (double rsq, int bondTypeId) const virtual
Return pair energy for a single pair.
Implements McMd::BondPotential.
Definition at line 259 of file LinkPotentialImpl.h.
template<class Interaction > double McMd::LinkPotentialImpl< Interaction >::forceOverR (double rsq, int bondTypeId) const virtual
Return force / separation for a single pair.
Implements McMd::BondPotential.
Definition at line 267 of file LinkPotentialImpl.h.
template<class Interaction > double McMd::LinkPotentialImpl< Interaction >::randomBondLength (Random * random, double beta, int bondTypeId) const virtual
Return force / separation for a single pair.
Implements McMd::BondPotential.
Definition at line 276 of file LinkPotentialImpl.h.
template<class Interaction> void McMd::LinkPotentialImpl< Interaction >::set (std::string name, int type, double value) inline virtual
Modify a parameter, identified by a string.
Parameters
name parameter name
type bond type index
value new value of parameter
Implements McMd::BondPotential.
Definition at line 95 of file LinkPotentialImpl.h.
template<class Interaction> double McMd::LinkPotentialImpl< Interaction >::get (std::string name, int type) const inline virtual
Get a parameter value, identified by a string.
Parameters
name parameter name
type bond type index 1
Implements McMd::BondPotential.
Definition at line 104 of file LinkPotentialImpl.h.
template<class Interaction > std::string McMd::LinkPotentialImpl< Interaction >::interactionClassName () const virtual
Return pair interaction class name (e.g., "HarmonicBond").
Implements McMd::BondPotential.
Definition at line 406 of file LinkPotentialImpl.h.
template<class Interaction > double McMd::LinkPotentialImpl< Interaction >::atomEnergy (const Atom & atom) const virtual
Calculate the link potential energy for one Atom.
Parameters
atom Atom object of interest
Returns
bond energy of one atom.
Implements McMd::BondPotential.
Definition at line 283 of file LinkPotentialImpl.h.
References McMd::Link::atom0(), McMd::Link::atom1(), McMd::Atom::position(), Util::SSet< Data, Capacity >::size(), and McMd::Link::typeId().
template<class Interaction > double McMd::LinkPotentialImpl< Interaction >::energy () const virtual
Return total link potential energy of the System.
Implements McMd::BondPotential.
Definition at line 308 of file LinkPotentialImpl.h.
References McMd::Link::atom0(), McMd::Link::atom1(), McMd::Atom::position(), and McMd::Link::typeId().
template<class Interaction > void McMd::LinkPotentialImpl< Interaction >::addForces () virtual
Compute and increment link forces for all atoms.
Implements McMd::BondPotential.
Definition at line 328 of file LinkPotentialImpl.h.
References McMd::Link::atom0(), McMd::Link::atom1(), McMd::Atom::force(), McMd::Atom::position(), and McMd::Link::typeId().
template<class Interaction > void McMd::LinkPotentialImpl< Interaction >::computeStress (double & stress) const virtual
Compute total nonbonded pressure.
Parameters
stress (output) pressure.
Implements McMd::BondPotential.
Definition at line 381 of file LinkPotentialImpl.h.
template<class Interaction > void McMd::LinkPotentialImpl< Interaction >::computeStress (Util::Vector & stress) const virtual
Compute x, y, z nonbonded pressures.
Parameters
stress (output) pressures.
Implements McMd::BondPotential.
Definition at line 385 of file LinkPotentialImpl.h.
template<class Interaction > void McMd::LinkPotentialImpl< Interaction >::computeStress (Util::Tensor & stress) const virtual
Compute stress tensor.
Parameters
stress (output) pressures.
Implements McMd::BondPotential.
Definition at line 390 of file LinkPotentialImpl.h.
template<class Interaction > Interaction & McMd::LinkPotentialImpl< Interaction >::interaction () inline
Return bond interaction by reference.
Definition at line 395 of file LinkPotentialImpl.h.
template<class Interaction > const Interaction & McMd::LinkPotentialImpl< Interaction >::interaction () const inline
Return bond interaction by const reference.
Definition at line 399 of file LinkPotentialImpl.h.
The documentation for this class was generated from the following file:
LinkPotentialImpl.h