Simpatico: Util::PackedData Class Reference
Util::PackedData Class Reference
Detailed Description
Memory block for packed heterogeneous binary data.
A PackedData object encapsulates a unsigned char array that may be used to store packed, heterogenous binary data. A PackedData object must be allocated before it can be used.
To pack data, first call beginPacking(), followed by a series of calls of the pack methods. During packing, the cursor() method returns the address of the next available unwritten byte. The overloaded pack method templates write either a single object or an array of objects to memory at the current cursor location, and then updates the cursor. Packing is terminated by calling beginUnpacking(), which sets the cursor to the beginning in preparation for unpacking.
To unpack data, call beginUnpacking(), followed by a series of calls of the unpack methods. During unpacking, cursor() points to the first unread byte, and endPacked() points to end of the packed block (one byte after the last). Unpacking is terminated by calling beginPacking(), which resets the cursor to the beginning in preparation for re-packing.
The pack and unpack methods may not be intermingled. One or more calls to pack must be preceded by a call of beginPacking(), and one or more calls to unpack must be preceded by a call to beginUnpacking().
Example:
 PackedData buffer;
 int capacity = 128;
 buffer.allocate(capacity);
 const int n  = 2;
 // Variables to be packed int buffer
 int i = 3;
 double d = 5.0;
 double a[n]  a;
 a[0] = 9.0;
 a[1] = 8.0;
 buffer.beginPacking();
 buffer.pack(i);
 buffer.pack(d);
 buffer.pack(a, n);
 // Variables to be unpacked from buffer
 int j;
 double e;
 double[n] b;
 buffer.beginUnpacking();
 buffer.unpack(j);
 buffer.unpack(e);
 buffer.unpack(b, n);
Definition at line 79 of file PackedData.h.
#include <PackedData.h>
Public Types
typedef char Byte
Define a "Byte" type.
Public Member Functions
PackedData ()
Constructor.
~PackedData ()
Destructor.
void allocate (int capacity)
Allocate memory block.
void beginPacking ()
Begin packing, set cursor to the beginning.
void beginUnpacking ()
Begin unpacking, set cursor to the beginning.
template<typename T >
void pack (const T &data)
Pack one object.
template<typename T >
void pack (const T *array, int n)
Pack a C array of objects of type T.
template<typename T >
void unpack (T &data)
Unpack one object.
template<typename T >
void unpack (T *array, int n)
Unpack a C array and update cursor .
Byte * begin () const
Return pointer to beginning of block.
Byte * endAllocated () const
Return pointer to end of allocated block (one Byte past the last).
Byte * endPacked () const
Return pointer to end of packed block (one Byte past the last).
Byte * cursor () const
Return pointer to cursor position (cursor).
bool isAllocated () const
Has memory been allocated?
int capacity () const
Return capacity in Bytes.
Member Typedef Documentation
typedef char Util::PackedData::Byte
Define a "Byte" type.
Definition at line 87 of file PackedData.h.
Constructor & Destructor Documentation
home david code simpatico src util containers PackedData cpp Util::PackedData::PackedData ()
Constructor.
Definition at line 20 of file PackedData.cpp.
Util::PackedData::~PackedData ()
Destructor.
Definition at line 32 of file PackedData.cpp.
Member Function Documentation
void Util::PackedData::allocate (int capacity)
Allocate memory block.
Parameters:
capacity sizeof of block, in Bytes.
Definition at line 38 of file PackedData.cpp.
References capacity(), and UTIL_THROW.
void Util::PackedData::beginPacking ()
Begin packing, set cursor to the beginning.
Definition at line 54 of file PackedData.cpp.
void Util::PackedData::beginUnpacking ()
Begin unpacking, set cursor to the beginning.
Definition at line 64 of file PackedData.cpp.
template<typename T > void Util::PackedData::pack (const T & data)
Pack one object.
Upon return, the cursor points to next unwritten Byte.
Parameters:
data variable to be packed.
Definition at line 279 of file PackedData.h.
References UTIL_THROW.
Referenced by Util::RingBuffer< Data >::pack(), and Util::DArray< Data >::pack().
template<typename T > void Util::PackedData::pack (const T * array, int n)
Pack a C array of objects of type T.
Upon return, the cursor points to next unwritten Byte.
Parameters:
array pointer to first element in array.
n number of elements in array.
Definition at line 297 of file PackedData.h.
References UTIL_THROW.
template<typename T > void Util::PackedData::unpack (T & data)
Unpack one object.
Upon return, the cursor points to next unread Byte.
Parameters:
data object to be unpacked
Definition at line 317 of file PackedData.h.
References UTIL_THROW.
Referenced by Util::RingBuffer< Data >::unpack(), and Util::DArray< Data >::unpack().
template<typename T > void Util::PackedData::unpack (T * array, int n)
Unpack a C array and update cursor .
Upon return, the cursor points to next unread Byte.
Parameters:
array pointer to first element in array.
n number of elements in array.
Definition at line 335 of file PackedData.h.
References UTIL_THROW.
PackedData::Byte * Util::PackedData::begin () const [inline]
Return pointer to beginning of block.
Definition at line 252 of file PackedData.h.
PackedData::Byte * Util::PackedData::endAllocated () const [inline]
Return pointer to end of allocated block (one Byte past the last).
Definition at line 258 of file PackedData.h.
PackedData::Byte * Util::PackedData::endPacked () const [inline]
Return pointer to end of packed block (one Byte past the last).
Definition at line 264 of file PackedData.h.
PackedData::Byte * Util::PackedData::cursor () const [inline]
Return pointer to cursor position (cursor).
Definition at line 270 of file PackedData.h.
bool Util::PackedData::isAllocated () const [inline]
Has memory been allocated?
Definition at line 240 of file PackedData.h.
int Util::PackedData::capacity () const [inline]
Return capacity in Bytes.
Definition at line 246 of file PackedData.h.
Referenced by allocate().
The documentation for this class was generated from the following files:
PackedData.h
PackedData.cpp