Simpatico: McMd::CompositionProfile Class Reference
McMd::CompositionProfile Class Reference
Detailed Description
CompositionProfile evaluates the distribution of monomer positions along several user-specified directions.
A direction vector is specified as an IntVector containing integer Miller indices.
The dot product of monomer position vector and unit direction vector is added to distribution function of particular monomer type and direction vector.
Definition at line 34 of file CompositionProfile.h.
#include <CompositionProfile.h>
Public Member Functions
CompositionProfile (System &system)
Constructor.
~CompositionProfile ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void setup ()
Clear accumulators.
void sample (long iStep)
Add particle positions to histogram.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize internal state to/from archive.
virtual void output ()
Output results to predefined output file.
Protected Member Functions
void makeWaveVectors ()
Update wavevectors.
Protected Attributes
std::ofstream outputFile_
Output file stream.
DArray< Distribution > accumulators_
Distribution statistical accumulators.
DArray< IntVector > intVectors_
Array of Miller index vectors for directions.
DArray< Vector > waveVectors_
Array of direction vectors.
int nDirection_
Number of directions.
int nSample_
Number of samples thus far.
int nAtomType_
Number of atom types, copied from Simulation::nAtomType().
int nBins_
Number of bins for density profile.
bool isFirstStep_
True if this is the first step.
bool isInitialized_
Has readParam been called?
DArray< Distribution > currentAccumulators_
Distribution statistical accumulators.
Constructor & Destructor Documentation
McMd::CompositionProfile::CompositionProfile (System & system)
Constructor.
Parameters:
system reference to parent System object
Definition at line 25 of file CompositionProfile.cpp.
References Util::ParamComposite::setClassName().
McMd::CompositionProfile::~CompositionProfile ()
Destructor.
Definition at line 31 of file CompositionProfile.cpp.
Member Function Documentation
void McMd::CompositionProfile::readParameters (std::istream & in) [virtual]
Read parameters from file.
Read parameters from file, and allocate direction vectors.
Input format:
int interval sampling interval
string outputFileName output file base name
int nDirection number of directions
DArray<IntVector> intVectors IntVector directions
Parameters:
in input parameter stream
Reimplemented from McMd::Analyzer.
Definition at line 35 of file CompositionProfile.cpp.
References accumulators_, Util::DArray< Data >::allocate(), currentAccumulators_, intVectors_, isInitialized_, McMd::Simulation::nAtomType(), nAtomType_, nBins_, nDirection_, McMd::Analyzer::readInterval(), McMd::Analyzer::readOutputFileName(), McMd::System::simulation(), McMd::SystemAnalyzer< System >::system(), and waveVectors_.
void McMd::CompositionProfile::setup () [virtual]
Clear accumulators.
Reimplemented from McMd::Analyzer.
Definition at line 104 of file CompositionProfile.cpp.
References accumulators_, currentAccumulators_, makeWaveVectors(), nAtomType_, nBins_, nDirection_, and nSample_.
void McMd::CompositionProfile::sample (long iStep) [virtual]
Add particle positions to histogram.
Parameters:
iStep step counter
Implements McMd::Analyzer.
Definition at line 130 of file CompositionProfile.cpp.
References accumulators_, McMd::System::begin(), McMd::System::boundary(), currentAccumulators_, Util::Dimension, Util::Vector::dot(), McMd::Analyzer::fileMaster(), intVectors_, McMd::Analyzer::isAtInterval(), isFirstStep_, Util::OrthorhombicBoundary::lengths(), nAtomType_, nDirection_, Util::ConstArrayIterator< Data >::notEnd(), Util::ConstPArrayIterator< Data >::notEnd(), nSample_, McMd::Simulation::nSpecies(), Util::FileMaster::openOutputFile(), McMd::Analyzer::outputFileName(), Util::product(), McMd::System::simulation(), McMd::SystemAnalyzer< System >::system(), and waveVectors_.
void McMd::CompositionProfile::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::Analyzer.
Definition at line 59 of file CompositionProfile.cpp.
References accumulators_, intVectors_, isInitialized_, McMd::Simulation::nAtomType(), nAtomType_, nDirection_, nSample_, McMd::System::simulation(), McMd::SystemAnalyzer< System >::system(), UTIL_THROW, and waveVectors_.
void McMd::CompositionProfile::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::Analyzer.
Definition at line 88 of file CompositionProfile.cpp.
References accumulators_, intVectors_, isFirstStep_, nAtomType_, nBins_, nDirection_, nSample_, and waveVectors_.
template<class Archive > void McMd::CompositionProfile::serialize (Archive & ar, const unsigned int version)
Serialize internal state to/from archive.
Parameters:
ar archive
version index for archive version
Reimplemented from McMd::Analyzer.
Definition at line 156 of file CompositionProfile.h.
References McMd::serialize().
void McMd::CompositionProfile::output () [virtual]
Output results to predefined output file.
Reimplemented from McMd::Analyzer.
Definition at line 244 of file CompositionProfile.cpp.
References accumulators_, Util::Dimension, McMd::Analyzer::fileMaster(), nAtomType_, nDirection_, Util::FileMaster::openOutputFile(), outputFile_, McMd::Analyzer::outputFileName(), waveVectors_, and Util::ParamComposite::writeParam().
void McMd::CompositionProfile::makeWaveVectors () [protected]
Update wavevectors.
Calculate floating point wavevectors.
Definition at line 226 of file CompositionProfile.cpp.
References McMd::System::boundary(), Util::Dimension, intVectors_, nDirection_, Util::OrthorhombicBoundary::reciprocalBasisVector(), McMd::SystemAnalyzer< System >::system(), waveVectors_, and Util::Vector::Zero.
Referenced by setup().
Member Data Documentation
std::ofstream McMd::CompositionProfile::outputFile_ [protected]
Output file stream.
Definition at line 109 of file CompositionProfile.h.
Referenced by output().
DArray<Distribution> McMd::CompositionProfile::accumulators_ [protected]
Distribution statistical accumulators.
Definition at line 112 of file CompositionProfile.h.
Referenced by loadParameters(), output(), readParameters(), sample(), save(), and setup().
DArray<IntVector> McMd::CompositionProfile::intVectors_ [protected]
Array of Miller index vectors for directions.
Definition at line 115 of file CompositionProfile.h.
Referenced by loadParameters(), makeWaveVectors(), readParameters(), sample(), and save().
DArray<Vector> McMd::CompositionProfile::waveVectors_ [protected]
Array of direction vectors.
Definition at line 118 of file CompositionProfile.h.
Referenced by loadParameters(), makeWaveVectors(), output(), readParameters(), sample(), and save().
int McMd::CompositionProfile::nDirection_ [protected]
Number of directions.
Definition at line 124 of file CompositionProfile.h.
Referenced by loadParameters(), makeWaveVectors(), output(), readParameters(), sample(), save(), and setup().
int McMd::CompositionProfile::nSample_ [protected]
Number of samples thus far.
Definition at line 127 of file CompositionProfile.h.
Referenced by loadParameters(), sample(), save(), and setup().
int McMd::CompositionProfile::nAtomType_ [protected]
Number of atom types, copied from Simulation::nAtomType().
Definition at line 130 of file CompositionProfile.h.
Referenced by loadParameters(), output(), readParameters(), sample(), save(), and setup().
int McMd::CompositionProfile::nBins_ [protected]
Number of bins for density profile.
Definition at line 133 of file CompositionProfile.h.
Referenced by readParameters(), save(), and setup().
bool McMd::CompositionProfile::isFirstStep_ [protected]
True if this is the first step.
Definition at line 136 of file CompositionProfile.h.
Referenced by sample(), and save().
bool McMd::CompositionProfile::isInitialized_ [protected]
Has readParam been called?
Definition at line 139 of file CompositionProfile.h.
Referenced by loadParameters(), and readParameters().
DArray<Distribution> McMd::CompositionProfile::currentAccumulators_ [protected]
Distribution statistical accumulators.
Definition at line 142 of file CompositionProfile.h.
Referenced by readParameters(), sample(), and setup().
The documentation for this class was generated from the following files:
CompositionProfile.h
CompositionProfile.cpp