Simpatico: DdMd::StructureFactorGrid Class Reference
DdMd::StructureFactorGrid Class Reference
DdMd namespace » Analyzers » Scattering Analyzers
Detailed Description
StructureFactorGrid evaluates structure factors in Fourier space.
This class evaluates the structures factors for all wavevectors within a grid, within a region in which each of the h, k, l integer wavevector components (i.e., Miller indices) has an absolute magnitude less than or equal to a parameter hMax.
The class also requires a user to specify a variable lattice of enum type LatticeSystem whose value (e.g., Cubic, Orthorhombic, Triclinic) determines the symmetry group that is used to group group equivalent wavevectors into "stars". Use Triclinic to impose no symmetry.
Example: Here is parameter file for a system with nAtomType = 2, with two monomer types 0 and 1, for calculating the total, 00, and 01 correlation functions on a grid with Miller indices up and including 5:
StructureFactorGrid{
   interval                     1000
   outputFileName     StructureFactorGrid
   nAtomTypeIdPair                  3
   atomTypeIdPairs          -1     -1
                             0      0
                             0      1
   hMax                             5
   lattice                      Cubic
}
At the end of a simulation, all of the structure factors are output in a file with a suffix *.dat. Each line in this file contains the 3 Miller indices of a wavevector, the absolute magnitude of the wavevector, and a list of nAtomTypeIdPair structure factor values for the wavevector, one for each atomTypeId pair.
See also
param file format
Definition at line 61 of file ddMd/analyzers/scattering/StructureFactorGrid.h.
#include <StructureFactorGrid.h>
Public Member Functions
StructureFactorGrid (Simulation &simulation)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void clear ()
Clear all accumulators and counters.
virtual void sample (long iStep)
Add particles to StructureFactor accumulators.
virtual void output ()
Output structure factors, averaged over stars.
Public Member Functions inherited from DdMd::StructureFactor
StructureFactor (Simulation &simulation)
Constructor.
~StructureFactor ()
Destructor.
Public Member Functions inherited from DdMd::Analyzer
Analyzer (Simulation &simulation)
Constructor.
virtual ~Analyzer ()
Destructor.
virtual void setup ()
Setup before simulation.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from DdMd::Analyzer
static void initStatic ()
Define and initialize baseInterval.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Public Attributes inherited from DdMd::StructureFactor
static const int Samples = 100000
Number of analyzer samples in simulation.
Static Public Attributes inherited from DdMd::Analyzer
static long baseInterval = 1
The interval for an Analyzer must be a multiple of baseInterval.
Protected Member Functions inherited from DdMd::StructureFactor
void makeWaveVectors ()
Update wavevectors.
Protected Member Functions inherited from DdMd::Analyzer
void readInterval (std::istream &in)
Read parameter interval from file.
void loadInterval (Serializable::IArchive &ar)
Load parameter interval from input archive.
void saveInterval (Serializable::OArchive &ar)
Save interval parameter to an archive.
void readOutputFileName (std::istream &in)
Read outputFileName from file.
void loadOutputFileName (Serializable::IArchive &ar)
Load output file name to an archive.
void saveOutputFileName (Serializable::OArchive &ar)
Save output file name to an archive.
Simulation & simulation ()
Get the parent Simulation by reference.
const std::string & outputFileName () const
Return outputFileName string.
std::string outputFileName (const std::string &suffix) const
Return outputFileName string with added suffix.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes inherited from DdMd::StructureFactor
std::ofstream outputFile_
Output file stream.
DMatrix< double > structureFactors_
Structure factor accumulators.
DMatrix< std::complex< double > > fourierModes_
Fourier modes of concentration.
DMatrix< std::complex< double > > totalFourierModes_
Total fourier modes of concentration.
DArray< IntVector > waveIntVectors_
Array of Miller index IntVectors for wavevectors.
DArray< Vector > waveVectors_
Array of floating point wave vectors.
DMatrix< double > modes_
Array of mode vectors.
int nWave_
Number of wavevectors.
int nMode_
Number of mode vectors.
int nSample_
Number of samples thus far.
int nAtomType_
Number of atom types, copied from Simulation::nAtomType().
bool isInitialized_
Has readParam been called?
bool isFirstStep_
Is this the first step?
Constructor & Destructor Documentation
DdMd::StructureFactorGrid::StructureFactorGrid (Simulation & simulation)
Constructor.
Parameters
simulation reference to parent DdMd::Simulation object
Definition at line 27 of file ddMd/analyzers/scattering/StructureFactorGrid.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void DdMd::StructureFactorGrid::readParameters (std::istream & in) virtual
Read parameters from file.
Input format:
int interval sampling interval
string outputFileName output file base name
int nMode number of modes
DMatrix<double> modes mode vectors
int hMax maximum Miller index
LatticeSystem lattice lattice system (string)
Parameters
in input parameter stream
Reimplemented from DdMd::StructureFactor.
Definition at line 38 of file ddMd/analyzers/scattering/StructureFactorGrid.cpp.
References Util::SymmetryGroup< Symmetry >::add(), Util::DMatrix< Data >::allocate(), Util::DArray< Data >::allocate(), DdMd::StructureFactor::fourierModes_, Util::SymmetryGroup< Symmetry >::makeCompleteGroup(), Util::PointGroup::makeStar(), DdMd::StructureFactor::modes_, DdMd::Simulation::nAtomType(), DdMd::StructureFactor::nAtomType_, DdMd::StructureFactor::nMode_, DdMd::StructureFactor::nSample_, DdMd::StructureFactor::nWave_, Util::PointSymmetry::R(), DdMd::Analyzer::readInterval(), DdMd::Analyzer::readOutputFileName(), DdMd::Analyzer::simulation(), Util::FSArray< Data, Capacity >::size(), DdMd::StructureFactor::structureFactors_, DdMd::StructureFactor::totalFourierModes_, UTIL_THROW, DdMd::StructureFactor::waveIntVectors_, and DdMd::StructureFactor::waveVectors_.
void DdMd::StructureFactorGrid::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from DdMd::StructureFactor.
Definition at line 242 of file ddMd/analyzers/scattering/StructureFactorGrid.cpp.
References Util::DMatrix< Data >::allocate(), Util::DArray< Data >::allocate(), DdMd::StructureFactor::fourierModes_, DdMd::Analyzer::loadInterval(), DdMd::Analyzer::loadOutputFileName(), DdMd::StructureFactor::modes_, DdMd::Simulation::nAtomType(), DdMd::StructureFactor::nAtomType_, DdMd::StructureFactor::nMode_, DdMd::StructureFactor::nSample_, DdMd::StructureFactor::nWave_, DdMd::Analyzer::simulation(), DdMd::StructureFactor::structureFactors_, DdMd::StructureFactor::totalFourierModes_, DdMd::StructureFactor::waveIntVectors_, and DdMd::StructureFactor::waveVectors_.
void DdMd::StructureFactorGrid::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from DdMd::StructureFactor.
Definition at line 283 of file ddMd/analyzers/scattering/StructureFactorGrid.cpp.
References DdMd::StructureFactor::modes_, DdMd::StructureFactor::nMode_, DdMd::StructureFactor::nSample_, DdMd::StructureFactor::nWave_, DdMd::Analyzer::saveInterval(), DdMd::Analyzer::saveOutputFileName(), DdMd::StructureFactor::structureFactors_, and DdMd::StructureFactor::waveIntVectors_.
void DdMd::StructureFactorGrid::clear () virtual
Clear all accumulators and counters.
Reimplemented from DdMd::StructureFactor.
Definition at line 302 of file ddMd/analyzers/scattering/StructureFactorGrid.cpp.
void DdMd::StructureFactorGrid::sample (long iStep) virtual
Add particles to StructureFactor accumulators.
Parameters
iStep step counter
Reimplemented from DdMd::StructureFactor.
Definition at line 305 of file ddMd/analyzers/scattering/StructureFactorGrid.cpp.
References DdMd::Simulation::boundary(), Util::Dimension, DdMd::Simulation::fileMaster(), DdMd::Analyzer::isAtInterval(), DdMd::StructureFactor::isFirstStep_, DdMd::StructureFactor::nMode_, Util::FileMaster::openOutputFile(), DdMd::Analyzer::outputFileName(), DdMd::StructureFactor::sample(), DdMd::Analyzer::simulation(), DdMd::StructureFactor::totalFourierModes_, UTIL_THROW, Util::OrthorhombicBoundary::volume(), DdMd::StructureFactor::waveIntVectors_, and DdMd::StructureFactor::waveVectors_.
void DdMd::StructureFactorGrid::output () virtual
Output structure factors, averaged over stars.
Reimplemented from DdMd::StructureFactor.
Definition at line 357 of file ddMd/analyzers/scattering/StructureFactorGrid.cpp.
References Util::Dimension, DdMd::Simulation::fileMaster(), DdMd::StructureFactor::nMode_, DdMd::StructureFactor::nSample_, Util::FileMaster::openOutputFile(), DdMd::StructureFactor::outputFile_, DdMd::Analyzer::outputFileName(), DdMd::Analyzer::simulation(), DdMd::StructureFactor::structureFactors_, DdMd::StructureFactor::waveIntVectors_, DdMd::StructureFactor::waveVectors_, and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
ddMd/analyzers/scattering/StructureFactorGrid.h
ddMd/analyzers/scattering/StructureFactorGrid.cpp