Simpatico: McMd::LinearRouseAutoCorr Class Reference
McMd::LinearRouseAutoCorr Class Reference
Diagnostics
Detailed Description
Autocorrelation for Rouse mode coefficients of a linear molecule.
Definition at line 34 of file LinearRouseAutoCorr.h.
#include <LinearRouseAutoCorr.h>
Public Member Functions
LinearRouseAutoCorr (System &system)
Constructor.
virtual ~LinearRouseAutoCorr ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Set number of molecules, initialize eigenvector, and clear accumulator.
virtual void sample (long iStep)
Evaluate end-to-end vectors of all chains, add to ensemble.
virtual void output ()
Output results after simulation is completed.
Constructor & Destructor Documentation
McMd::LinearRouseAutoCorr::LinearRouseAutoCorr (System & system)
Constructor.
Parameters:
system reference to parent System
Definition at line 29 of file LinearRouseAutoCorr.cpp.
References Util::ParamComposite::setClassName().
McMd::LinearRouseAutoCorr::~LinearRouseAutoCorr () [virtual]
Destructor.
Definition at line 46 of file LinearRouseAutoCorr.cpp.
Member Function Documentation
void McMd::LinearRouseAutoCorr::readParameters (std::istream & in) [virtual]
Read parameters from file.
Parameters:
in input parameter stream
Reimplemented from McMd::Diagnostic.
Definition at line 52 of file LinearRouseAutoCorr.cpp.
References Util::DArray< Data >::allocate(), McMd::Species::capacity(), McMd::Species::nAtom(), McMd::Diagnostic::readInterval(), McMd::Diagnostic::readOutputFileName(), Util::AutoCorrArray< Data, Product >::setParam(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::LinearRouseAutoCorr::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::Diagnostic.
Definition at line 91 of file LinearRouseAutoCorr.cpp.
References Util::DArray< Data >::allocate(), McMd::Species::capacity(), McMd::Species::nAtom(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::LinearRouseAutoCorr::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::Diagnostic.
Definition at line 138 of file LinearRouseAutoCorr.cpp.
template<class Archive > void McMd::LinearRouseAutoCorr::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Diagnostic.
Definition at line 139 of file LinearRouseAutoCorr.h.
References McMd::serialize().
void McMd::LinearRouseAutoCorr::setup () [virtual]
Set number of molecules, initialize eigenvector, and clear accumulator.
Reimplemented from McMd::Diagnostic.
Definition at line 144 of file LinearRouseAutoCorr.cpp.
References Util::AutoCorrArray< Data, Product >::clear(), McMd::System::nMolecule(), Util::AutoCorrArray< Data, Product >::setNEnsemble(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::LinearRouseAutoCorr::sample (long iStep) [virtual]
Evaluate end-to-end vectors of all chains, add to ensemble.
Parameters:
iStep counter for number of steps
Implements McMd::Diagnostic.
Definition at line 176 of file LinearRouseAutoCorr.cpp.
References McMd::Molecule::atom(), McMd::System::boundary(), Util::OrthorhombicBoundary::distanceSq(), McMd::Diagnostic::isAtInterval(), McMd::System::molecule(), Util::Vector::multiply(), McMd::Atom::position(), Util::AutoCorrArray< Data, Product >::sample(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::LinearRouseAutoCorr::output () [virtual]
Output results after simulation is completed.
Reimplemented from McMd::Diagnostic.
Definition at line 214 of file LinearRouseAutoCorr.cpp.
References McMd::Diagnostic::fileMaster(), Util::FileMaster::openOutputFile(), Util::AutoCorrArray< Data, Product >::output(), McMd::Diagnostic::outputFileName(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
LinearRouseAutoCorr.h
LinearRouseAutoCorr.cpp