Simpatico: Tools::ConfigReader Class Reference
Tools::ConfigReader Class Reference
Config File Readers
Detailed Description
Abstract reader/writer for configuration files.
Each concrete subclass of ConfigReader implements a specific file format by implementing the pure virtual readConfig and writeConfig methods.
Definition at line 27 of file ConfigReader.h.
#include <ConfigReader.h>
Public Member Functions
ConfigReader ()
Default constructor.
ConfigReader (Configuration &configuration, bool needsAuxiliaryFile=false)
Constructor.
virtual ~ConfigReader ()
Destructor.
virtual void readConfig (std::ifstream &file)=0
Read a configuration file.
bool needsAuxiliaryFile () const
Return true if an auxiliary file is needed.
virtual void readAuxiliaryFile (std::ifstream &file)
Read auxiliary file.
Protected Member Functions
bool setAtomContexts ()
Set atom context data for all atoms, assuming consecutive ids.
void addAtomsToSpecies ()
Add all atoms to Species containers and associated molecules.
Configuration & configuration ()
Get parent Configuration by reference.
Constructor & Destructor Documentation
Tools::ConfigReader::ConfigReader ()
Default constructor.
Definition at line 21 of file ConfigReader.cpp.
References Util::ParamComposite::setClassName().
Tools::ConfigReader::ConfigReader (Configuration & configuration, bool needsAuxiliaryFile = false)
Constructor.
Parameters:
configuration parent Configuration object
needsAuxiliaryFile Does this class need to read an auxiliary file?
Definition at line 28 of file ConfigReader.cpp.
References Util::ParamComposite::setClassName().
Tools::ConfigReader::~ConfigReader () [virtual]
Destructor.
Definition at line 37 of file ConfigReader.cpp.
Member Function Documentation
virtual void Tools::ConfigReader::readConfig (std::ifstream & file) [pure virtual]
Read a configuration file.
Parameters:
file input file
Implemented in Tools::HoomdConfigReader, and Tools::DdMdConfigReader.
Referenced by Tools::Processor::readCommands(), and Tools::Processor::readConfig().
bool Tools::ConfigReader::needsAuxiliaryFile () const [inline]
Return true if an auxiliary file is needed.
Definition at line 106 of file ConfigReader.h.
virtual void Tools::ConfigReader::readAuxiliaryFile (std::ifstream & file) [inline, virtual]
Read auxiliary file.
Empty default implementation.
Parameters:
file auxiliary file, open for reading.
Reimplemented in Tools::HoomdConfigReader.
Definition at line 69 of file ConfigReader.h.
Referenced by Tools::Processor::readCommands().
bool Tools::ConfigReader::setAtomContexts () [protected]
Set atom context data for all atoms, assuming consecutive ids.
Returns:
true for normal completion, false if error is detected.
Definition at line 43 of file ConfigReader.cpp.
References Tools::Atom::atomId, Tools::Configuration::atoms(), Tools::Species::capacity(), Tools::Species::clear(), configuration(), Tools::Atom::moleculeId, Tools::Species::nAtom(), Tools::Configuration::nSpecies(), Tools::AtomStorage::ptr(), Tools::AtomStorage::size(), Tools::Configuration::species(), and Tools::Atom::speciesId.
Referenced by Tools::DdMdConfigReader::readConfig(), and Tools::HoomdConfigReader::readConfig().
void Tools::ConfigReader::addAtomsToSpecies () [protected]
Add all atoms to Species containers and associated molecules.
Definition at line 94 of file ConfigReader.cpp.
References Tools::Species::addAtom(), Tools::Configuration::atoms(), Tools::AtomStorage::begin(), Tools::Species::clear(), configuration(), Tools::Species::isValid(), Util::ArrayIterator< Data >::notEnd(), Tools::Configuration::nSpecies(), Tools::Configuration::species(), and UTIL_THROW.
Referenced by Tools::DdMdConfigReader::readConfig(), and Tools::HoomdConfigReader::readConfig().
Configuration& Tools::ConfigReader::configuration () [inline, protected]
Get parent Configuration by reference.
Definition at line 89 of file ConfigReader.h.
Referenced by addAtomsToSpecies(), Tools::DdMdConfigReader::readConfig(), Tools::HoomdConfigReader::readConfig(), and setAtomContexts().
The documentation for this class was generated from the following files:
ConfigReader.h
ConfigReader.cpp