Simpatico: DdMd::PairPotentialImpl< Interaction > Class Template Reference
DdMd::PairPotentialImpl< Interaction > Class Template Reference
DdMd namespace » Potential Energies » Pair Potentials
Detailed Description
template<class Interaction>
class DdMd::PairPotentialImpl< Interaction >
Implementation template for a PairPotential.
This template provides a concrete implementation of the PairPotential base class for a specific nonbonded pair interaction class, representing a specific functional form for the pair potential (e.g., cutoff Lennard-Jones). The template argument Interaction represents the specified pair interaction class (e.g., LJPair for cutoff Lennard-Jones), which is normally a class in the Simp namespace from the src/simp/pair directory.
Definition at line 42 of file PairPotentialImpl.h.
#include <PairPotentialImpl.h>
Public Member Functions
PairPotentialImpl (Simulation &simulation)
Constructor.
PairPotentialImpl ()
Default constructor (for unit testing).
virtual ~PairPotentialImpl ()
Destructor.
virtual void setNAtomType (int nAtomType)
Set the maximum number of atom types.
virtual void readParameters (std::istream &in)
Read pair potential interaction and pair list blocks.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
Interaction interface
virtual double pairEnergy (double rsq, int iAtomType, int jAtomType) const
Return energy for a single pair.
virtual double pairForceOverR (double rsq, int iAtomType, int jAtomType) const
Return force / separation for a single pair.
void set (std::string name, int i, int j, double value)
Modify a pair interaction parameter, identified by a string.
double get (std::string name, int i, int j) const
Get a parameter value, identified by a string.
virtual double maxPairCutoff () const
Return maximum cutoff.
virtual std::string interactionClassName () const
Return pair interaction class name (e.g., "LJPair").
const Interaction & interaction () const
Return underlying pair interaction object by const reference.
Interaction & interaction ()
Return underlying pair interaction object by reference.
Total Energy, Force and Stress
virtual void computeForces ()
Compute non-bonded pair forces for all atoms in this Simulation.
virtual void computeEnergy (MPI::Intracomm &communicator)
Compute the total nonBonded pair energy for all processors.
virtual void computeStress (MPI::Intracomm &communicator)
Compute the total nonBonded stress for all processors.
virtual void computePairEnergies (MPI::Intracomm &communicator)
Compute total pair energies for all processors Compute nonbonded forces and sress for all processors.
virtual void computeForcesAndStress (MPI::Intracomm &communicator)
Compute nonbonded forces and sress for all processors.
Public Member Functions inherited from DdMd::PairPotential
PairPotential (Simulation &simulation)
Constructor.
PairPotential ()
Default constructor.
virtual ~PairPotential ()
Destructor.
double skin () const
Get value of the pair list skin.
double cutoff () const
Get value of the pair list cutoff (maxPairCutoff + skin).
int methodId () const
Return integer id for algorithm (0=PAIR, 1=CELL, 2=NSQ)
void associate (Domain &domain, Boundary &boundary, AtomStorage &storage)
Associate with related objects.
void initialize (const Boundary &maxBoundary, double skin, int pairCapacity)
Set parameters and allocate memory.
void setMethodId (int methodId)
Set id to specify algorithm for energy, force calculations.
void buildCellList ()
Build a cell list.
void buildPairList ()
Build the Verlet Pair list.
DMatrix< double > pairEnergies () const
Return total pair energies, from all processors.
void unsetPairEnergies ()
Mark pair energy as unknown (nullify).
void computeNPair (MPI::Intracomm &communicator)
Compute twice the number of pairs within the force cutoff.
int nPair () const
Return twice the number of pairs within the specified force cutoff.
CellList & cellList ()
Get the CellList by reference.
PairList & pairList ()
Get the PairList by reference.
Public Member Functions inherited from DdMd::Potential
Potential ()
Constructor.
virtual ~Potential ()
Destructor.
void setReverseUpdateFlag (bool reverseUpdateFlag)
Set flag to identify if reverse communication is enabled.
bool reverseUpdateFlag () const
Get flag to identify if reverse communication is enabled.
double energy () const
Return the total potential, from all processors.
void unsetEnergy ()
Mark the energy as unknown (nullify).
bool isEnergySet () const
Is the energy set (known)?
Tensor stress () const
Return the stress tensor.
double pressure () const
Return the pressure.
void unsetStress ()
Mark the stress as unknown (nullify).
bool isStressSet () const
Is the stress set (known)?
virtual bool isValid (MPI::Intracomm &communicator) const
Is the potential in a valid internal state?
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from DdMd::PairPotential
Boundary & boundary ()
Get the PairList by const reference.
Domain & domain ()
Get the PairList by const reference.
AtomStorage & storage ()
Get the AtomStorage by reference.
void setPairEnergies (DMatrix< double > pairEnergies)
Set values for pair energies.
Protected Member Functions inherited from DdMd::Potential
void setEnergy (double energy)
Set a value for the total energy.
void setStress (const Tensor &stress)
Set a value for the total stress.
void incrementPairStress (const Vector &f, const Vector &dr, Tensor &stress) const
Add a pair contribution to the stress tensor.
void reduceEnergy (double localEnergy, MPI::Intracomm &communicator)
Add local energies from all processors, set energy on master.
void reduceStress (Tensor &localStress, MPI::Intracomm &communicator)
Add local stresses from all processors, set total on master.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes inherited from DdMd::PairPotential
CellList cellList_
CellList to construct PairList or calculate nonbonded pair forces.
PairList pairList_
Verlet pair list, to calculate nonbonded pair forces.
Boundary maxBoundary_
Boundary used to allocate space for the cell list.
double skin_
Difference between pairlist cutoff and pair potential cutoff.
double cutoff_
Minimum cell size = pair potential cutoff + skin.
int nCellCut_
Approximate number of cells per cutoff distance in each direction.
int pairCapacity_
Maximum number of nonbonded pairs in pair list.
Constructor & Destructor Documentation
template<class Interaction > DdMd::PairPotentialImpl< Interaction >::PairPotentialImpl (Simulation & simulation)
Constructor.
Sets nNAtomType to simulation.nAtomType().
Parameters
simulation parent Simulation object.
Definition at line 338 of file PairPotentialImpl.h.
References DdMd::Simulation::nAtomType(), and DdMd::PairPotentialImpl< Interaction >::setNAtomType().
template<class Interaction > DdMd::PairPotentialImpl< Interaction >::PairPotentialImpl ()
Default constructor (for unit testing).
Definition at line 351 of file PairPotentialImpl.h.
template<class Interaction > DdMd::PairPotentialImpl< Interaction >::~PairPotentialImpl () virtual
Destructor.
Definition at line 361 of file PairPotentialImpl.h.
Member Function Documentation
template<class Interaction > void DdMd::PairPotentialImpl< Interaction >::setNAtomType (int nAtomType) virtual
Set the maximum number of atom types.
This function is required iff the object is instantiated using the default constructor, which is intended for use only for unit testing. It is called internally by the constructor PairPotentialImpl(Simulation&) that is used during a simulation.
Implements DdMd::PairPotential.
Definition at line 372 of file PairPotentialImpl.h.
References DdMd::PairPotentialImpl< Interaction >::interaction(), and UTIL_CHECK.
Referenced by DdMd::PairPotentialImpl< Interaction >::PairPotentialImpl().
template<class Interaction > void DdMd::PairPotentialImpl< Interaction >::readParameters (std::istream & in) virtual
Read pair potential interaction and pair list blocks.
This method initializes the pair potential. It reads the the maxBoundary, PairList and pair potential Interaction parameter blocks, in that order, and initializes an internal PairList.
Precondition
nAtomType must be set to a positive value
This object may not already be initialized
Parameters
in input parameter stream.
Reimplemented from DdMd::PairPotential.
Definition at line 383 of file PairPotentialImpl.h.
References Util::ParamComposite::addParamComposite(), DdMd::PairPotentialImpl< Interaction >::interaction(), DdMd::PairPotential::readParameters(), and UTIL_CHECK.
template<class Interaction > void DdMd::PairPotentialImpl< Interaction >::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
This function initializes the pair potential during a restart.
Precondition
nAtomType must be set to a positive value
This object may not already be initialized
Parameters
ar input/loading archive
Reimplemented from DdMd::PairPotential.
Definition at line 403 of file PairPotentialImpl.h.
References Util::ParamComposite::addParamComposite(), DdMd::PairPotentialImpl< Interaction >::interaction(), DdMd::PairPotential::loadParameters(), and UTIL_CHECK.
template<class Interaction > void DdMd::PairPotentialImpl< Interaction >::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Call only on master processor.
Parameters
ar output/saving archive
Reimplemented from DdMd::PairPotential.
Definition at line 419 of file PairPotentialImpl.h.
References DdMd::PairPotentialImpl< Interaction >::interaction(), and DdMd::PairPotential::save().
template<class Interaction > double DdMd::PairPotentialImpl< Interaction >::pairEnergy (double rsq, int iAtomType, int jAtomType) const virtual
Return energy for a single pair.
Parameters
rsq square distance between atoms in pair
iAtomType atom type index of 1st atom
jAtomType atom type index of 2nd atom
Returns
energy of pair
Implements DdMd::PairPotential.
Definition at line 429 of file PairPotentialImpl.h.
References DdMd::PairPotentialImpl< Interaction >::interaction().
template<class Interaction > double DdMd::PairPotentialImpl< Interaction >::pairForceOverR (double rsq, int iAtomType, int jAtomType) const virtual
Return force / separation for a single pair.
Parameters
rsq square distance between atoms in pair
iAtomType atom type index of 1st atom
jAtomType atom type index of 2nd atom
Returns
repulsive force (< 0 if attractive) over distance
Implements DdMd::PairPotential.
Definition at line 437 of file PairPotentialImpl.h.
References DdMd::PairPotentialImpl< Interaction >::interaction().
template<class Interaction> void DdMd::PairPotentialImpl< Interaction >::set (std::string name, int i, int j, double value) inline virtual
Modify a pair interaction parameter, identified by a string.
Parameters
name parameter name
i type index of first atom
j type index of first atom
value new value of parameter
Implements DdMd::PairPotential.
Definition at line 147 of file PairPotentialImpl.h.
template<class Interaction> double DdMd::PairPotentialImpl< Interaction >::get (std::string name, int i, int j) const inline virtual
Get a parameter value, identified by a string.
Parameters
name parameter name
i type index of first atom
j type index of first atom
Implements DdMd::PairPotential.
Definition at line 157 of file PairPotentialImpl.h.
template<class Interaction > double DdMd::PairPotentialImpl< Interaction >::maxPairCutoff () const virtual
Return maximum cutoff.
Implements DdMd::PairPotential.
Definition at line 451 of file PairPotentialImpl.h.
References DdMd::PairPotentialImpl< Interaction >::interaction().
template<class Interaction > std::string DdMd::PairPotentialImpl< Interaction >::interactionClassName () const virtual
Return pair interaction class name (e.g., "LJPair").
Implements DdMd::PairPotential.
Definition at line 458 of file PairPotentialImpl.h.
References DdMd::PairPotentialImpl< Interaction >::interaction().
template<class Interaction> const Interaction& DdMd::PairPotentialImpl< Interaction >::interaction () const inline
Return underlying pair interaction object by const reference.
Definition at line 173 of file PairPotentialImpl.h.
Referenced by DdMd::PairPotentialImpl< Interaction >::interactionClassName(), DdMd::PairPotentialImpl< Interaction >::loadParameters(), DdMd::PairPotentialImpl< Interaction >::maxPairCutoff(), DdMd::PairPotentialImpl< Interaction >::pairEnergy(), DdMd::PairPotentialImpl< Interaction >::pairForceOverR(), DdMd::PairPotentialImpl< Interaction >::readParameters(), DdMd::PairPotentialImpl< Interaction >::save(), and DdMd::PairPotentialImpl< Interaction >::setNAtomType().
template<class Interaction> Interaction& DdMd::PairPotentialImpl< Interaction >::interaction () inline
Return underlying pair interaction object by reference.
Definition at line 179 of file PairPotentialImpl.h.
template<class Interaction > void DdMd::PairPotentialImpl< Interaction >::computeForces () virtual
Compute non-bonded pair forces for all atoms in this Simulation.
Adds non-bonded pair forces to the current values of the forces for all atoms in this simulation. Before calculating forces, the method checks if the pair list is current, and rebuilds it if necessary.
Implements DdMd::Potential.
Definition at line 465 of file PairPotentialImpl.h.
References DdMd::PairPotential::methodId().
Referenced by DdMd::PairPotentialImpl< Interaction >::computeForcesAndStress().
template<class Interaction > void DdMd::PairPotentialImpl< Interaction >::computeEnergy (MPI::Intracomm & communicator) virtual
Compute the total nonBonded pair energy for all processors.
Call on all processors.
Implements DdMd::Potential.
Definition at line 483 of file PairPotentialImpl.h.
References DdMd::PairList::begin(), DdMd::CellList::begin(), DdMd::AtomStorage::begin(), DdMd::PairPotential::cellList_, DdMd::Potential::energy(), DdMd::Atom::force(), DdMd::Cell::getNeighbors(), DdMd::PairIterator::getPair(), DdMd::Potential::isEnergySet(), DdMd::Atom::isGhost(), DdMd::PairPotential::methodId(), DdMd::Cell::nAtom(), DdMd::Cell::nextCellPtr(), DdMd::PairIterator::notEnd(), Util::PArrayIterator< Data >::notEnd(), DdMd::PairList::nPair(), DdMd::PairPotential::pairList_, DdMd::Atom::position(), DdMd::Potential::reduceEnergy(), DdMd::Potential::reverseUpdateFlag(), Util::FSArray< Data, Capacity >::size(), Util::Vector::square(), DdMd::PairPotential::storage(), Util::Vector::subtract(), DdMd::Atom::typeId(), and UTIL_THROW.
template<class Interaction > void DdMd::PairPotentialImpl< Interaction >::computeStress (MPI::Intracomm & communicator) virtual
Compute the total nonBonded stress for all processors.
Call on all processors.
Reimplemented from DdMd::Potential.
Definition at line 956 of file PairPotentialImpl.h.
References DdMd::PairList::begin(), DdMd::PairPotential::boundary(), DdMd::PairIterator::getPair(), DdMd::Potential::incrementPairStress(), DdMd::Atom::isGhost(), DdMd::Potential::isStressSet(), DdMd::PairIterator::notEnd(), DdMd::PairPotential::pairList_, DdMd::Atom::position(), DdMd::Potential::reduceStress(), DdMd::Potential::reverseUpdateFlag(), Util::Vector::square(), Util::Vector::subtract(), DdMd::Atom::typeId(), Simp::OrthorhombicBoundary::volume(), and Util::Tensor::zero().
template<class Interaction > void DdMd::PairPotentialImpl< Interaction >::computePairEnergies (MPI::Intracomm & communicator) virtual
Compute total pair energies for all processors Compute nonbonded forces and sress for all processors.
Call on all processors.
Implements DdMd::PairPotential.
Definition at line 1098 of file PairPotentialImpl.h.
References Util::DMatrix< Data >::allocate(), DdMd::PairList::begin(), DdMd::PairIterator::getPair(), DdMd::Atom::isGhost(), DdMd::PairIterator::notEnd(), DdMd::PairPotential::pairList_, DdMd::Atom::position(), DdMd::Potential::reverseUpdateFlag(), DdMd::PairPotential::setPairEnergies(), Util::Vector::square(), Util::Vector::subtract(), DdMd::Atom::typeId(), and DdMd::PairPotential::unsetPairEnergies().
template<class Interaction > void DdMd::PairPotentialImpl< Interaction >::computeForcesAndStress (MPI::Intracomm & communicator) virtual
Compute nonbonded forces and sress for all processors.
Call on all processors.
Reimplemented from DdMd::Potential.
Definition at line 1023 of file PairPotentialImpl.h.
References DdMd::PairList::begin(), DdMd::PairPotential::boundary(), DdMd::PairPotentialImpl< Interaction >::computeForces(), DdMd::Atom::force(), DdMd::PairIterator::getPair(), DdMd::Potential::incrementPairStress(), DdMd::Atom::isGhost(), DdMd::Potential::isStressSet(), DdMd::PairIterator::notEnd(), DdMd::PairPotential::pairList_, DdMd::Atom::position(), DdMd::Potential::reduceStress(), DdMd::Potential::reverseUpdateFlag(), Util::Vector::square(), Util::Vector::subtract(), DdMd::Atom::typeId(), Simp::OrthorhombicBoundary::volume(), and Util::Tensor::zero().
The documentation for this class was generated from the following file:
PairPotentialImpl.h