Simpatico: McMd::MdMove Class Reference
McMd::MdMove Class Reference
Monte Carlo Moves
Detailed Description
MdMove is a simple NVE molecular Dynamics MC move.
An MdMove simply runs a (typically) short NVE simulation with initial velocities chosen from a Boltzmann distribution. All attempted moves are accepted.
MdMove rigorously satisfies detailed balance only in the limit of vanishing step size dt. The closely related HybridMdMove does satisfy detailed balance, for all dt, but generally accepts a fraction of attempted moves.
Definition at line 38 of file MdMove.h.
#include <MdMove.h>
Public Member Functions
MdMove (McSystem &system)
Constructor.
~MdMove ()
Destructor.
virtual void readParameters (std::istream &in)
Read nStep, dt, skin, maxNPair from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
bool move ()
Generate, attempt and accept or reject a move.
Constructor & Destructor Documentation
McMd::MdMove::MdMove (McSystem & system)
Constructor.
Constructs a component MdSystem object.
Definition at line 25 of file MdMove.cpp.
References Util::ParamComposite::setClassName().
McMd::MdMove::~MdMove ()
Destructor.
Definition at line 37 of file MdMove.cpp.
Member Function Documentation
void McMd::MdMove::readParameters (std::istream & in) [virtual]
Read nStep, dt, skin, maxNPair from file.
Parameters:
in input parameter stream.
Reimplemented from McMd::McMove.
Definition at line 47 of file MdMove.cpp.
References Util::ParamComposite::readParamComposite(), and McMd::McMove::readProbability().
void McMd::MdMove::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::McMove.
Definition at line 57 of file MdMove.cpp.
References Util::ParamComposite::loadParamComposite().
void McMd::MdMove::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::McMove.
Definition at line 67 of file MdMove.cpp.
References McMd::MdSystem::saveParameters().
bool McMd::MdMove::move () [virtual]
Generate, attempt and accept or reject a move.
Reimplemented from McMd::McMove.
Definition at line 77 of file MdMove.cpp.
References McMd::McPairPotential::buildCellList(), McMd::MdPairPotential::buildPairList(), McMd::MdSystem::calculateForces(), McMd::SystemMove::energyEnsemble(), McMd::McMove::incrementNAccept(), McMd::McMove::incrementNAttempt(), McMd::MdSystem::mdIntegrator(), McMd::McSystem::pairPotential(), McMd::MdSystem::pairPotential(), McMd::MdSystem::setBoltzmannVelocities(), McMd::MdIntegrator::step(), and McMd::SystemMove::system().
The documentation for this class was generated from the following files:
MdMove.h
MdMove.cpp