Simpatico: SpAn::Analyzer Class Reference
SpAn::Analyzer Class Reference
Analyzers
Detailed Description
Abstract base for periodic output and/or analysis actions.
The periodic action of an Analyzer can involve sampling of a physical property and adding it to statistical accumulator, outputting it to file, or both. This periodic action must be implemented by the pure virtual sample() method.
The sample() method should take the desired action only when the processor step index is an integer multiple of the associated interval parameter.
The virtual sample() method does not take any parameters. An Analyzer must thus access its parent Processor via a pointer, which is usually initialized in its subclass constructor.
Definition at line 42 of file spAn/analyzers/Analyzer.h.
#include <Analyzer.h>
Public Member Functions
Analyzer (Processor &processor)
Constructor.
virtual ~Analyzer ()
Destructor.
virtual void setup ()
Setup before processor.
virtual void clear ()
Clear statistical accumulators.
virtual void sample (long iStep)=0
Calculate, analyze and/or output a physical quantity.
virtual void output ()
Output any results at the end of an analysis.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Protected Member Functions
void readInterval (std::istream &in)
Read parameter interval from file.
void readOutputFileName (std::istream &in)
Read outputFileName from file.
Processor & processor ()
Get the parent Processor by reference.
const std::string & outputFileName () const
Return outputFileName string.
std::string outputFileName (const std::string &suffix) const
Return outputFileName string with added suffix.
Constructor & Destructor Documentation
SpAn::Analyzer::Analyzer (Processor & processor)
Constructor.
Definition at line 23 of file spAn/analyzers/Analyzer.cpp.
SpAn::Analyzer::~Analyzer () [virtual]
Destructor.
Definition at line 33 of file spAn/analyzers/Analyzer.cpp.
Member Function Documentation
virtual void SpAn::Analyzer::setup () [inline, virtual]
Setup before processor.
This method is called just before the beginning of the main loop. It may be used to complete any initialization or checks that require knowledge of the configuration.
The default implementation is empty.
Reimplemented in SpAn::AtomMSD, and SpAn::LogStep.
Definition at line 68 of file spAn/analyzers/Analyzer.h.
virtual void SpAn::Analyzer::clear () [inline, virtual]
Clear statistical accumulators.
The default implementation is empty.
Definition at line 76 of file spAn/analyzers/Analyzer.h.
virtual void SpAn::Analyzer::sample (long iStep) [pure virtual]
Calculate, analyze and/or output a physical quantity.
Take an action if iStep is a multiple of interval. If iStep is not a multiple of interval, this method should do nothing and return immediately.
Parameters:
iStep current step index.
Implemented in SpAn::AtomMSD, and SpAn::LogStep.
virtual void SpAn::Analyzer::output () [inline, virtual]
Output any results at the end of an analysis.
The default implementation is empty.
Reimplemented in SpAn::AtomMSD, and SpAn::LogStep.
Definition at line 95 of file spAn/analyzers/Analyzer.h.
int SpAn::Analyzer::interval () const [inline]
Get interval value.
Definition at line 165 of file spAn/analyzers/Analyzer.h.
bool SpAn::Analyzer::isAtInterval (long counter) const [inline]
Return true iff counter is a multiple of the interval.
Parameters:
counter processor step counter
Definition at line 171 of file spAn/analyzers/Analyzer.h.
Referenced by SpAn::AtomMSD::sample().
void SpAn::Analyzer::readInterval (std::istream & in) [protected]
Read parameter interval from file.
This function throws an exception if the value of interval is not a multiple of Analyzer::baseInterval, or if baseInterval has not been set to a nonzero positive value.
Parameters:
in input parameter file stream.
Definition at line 39 of file spAn/analyzers/Analyzer.cpp.
References UTIL_THROW.
Referenced by SpAn::AtomMSD::readParameters().
void SpAn::Analyzer::readOutputFileName (std::istream & in) [protected]
Read outputFileName from file.
Parameters:
in input parameter file
Definition at line 58 of file spAn/analyzers/Analyzer.cpp.
Referenced by SpAn::AtomMSD::readParameters().
Processor & SpAn::Analyzer::processor () [inline, protected]
Get the parent Processor by reference.
Definition at line 183 of file spAn/analyzers/Analyzer.h.
Referenced by SpAn::AtomMSD::output(), SpAn::AtomMSD::readParameters(), SpAn::AtomMSD::sample(), and SpAn::AtomMSD::setup().
const std::string & SpAn::Analyzer::outputFileName () const [inline, protected]
Return outputFileName string.
Definition at line 177 of file spAn/analyzers/Analyzer.h.
Referenced by SpAn::AtomMSD::output().
std::string SpAn::Analyzer::outputFileName (const std::string & suffix) const [protected]
Return outputFileName string with added suffix.
Definition at line 64 of file spAn/analyzers/Analyzer.cpp.
The documentation for this class was generated from the following files:
spAn/analyzers/Analyzer.h
spAn/analyzers/Analyzer.cpp