Simpatico: Util::ArraySet< Data > Class Template Reference
Util::ArraySet< Data > Class Template Reference
Pointer Arrays
Detailed Description
template<typename Data>
class Util::ArraySet< Data >
A container for pointers to a subset of elements of an associated array.
An ArraySet is a PArray that stores pointers to a subset of the elements of an associated Array container or bare C array. Pointers to the elements of this set are stored in a contiguous sequence, with indices in the range 0, ..., size() - 1. The order in which these pointers are stored is mutable, and generally changes whenever an element is removed.
The append() method appends a pointer to a new element to the end of the sequence and increments the size. The remove() method removes a specified element, then moves the pointer of the last element to the space vacated by the removed element (unless the removed element was the last in the sequence), and decrements the size. The order in which the remaining elements of an ArraySet are stored thus can change whenever an element is removed.
An ArraySet provides O(N) sequential access to all elements of a set, O(1) insertion and deletion, and O(1) access to a randomly chosen element.
Definition at line 46 of file ArraySet.h.
#include <ArraySet.h>
Public Member Functions
ArraySet ()
Constructor.
virtual ~ArraySet ()
Destructor.
void allocate (const Data *array, int capacity)
Associate with a C array and allocate required memory.
void allocate (const Array< Data > &array)
Associate with an Array container and allocate required memory.
Mutators
void append (Data &data)
Append an element to the set.
void remove (const Data &data)
Remove an element from the set.
Data & pop ()
Pop the topmost from the set.
void clear ()
Reset to empty state.
Accessors
int index (const Data &data) const
Return the current index of an element within the set, if any.
bool isAllocated () const
Return true if the ArraySet is initialized, false otherwise.
bool isValid () const
Return true if the ArraySet is valid, or throw an exception.
void dump () const
Write the internal state of the ArraySet to std::cout.
Constructor & Destructor Documentation
template<typename Data > Util::ArraySet< Data >::ArraySet ()
Constructor.
Definition at line 187 of file ArraySet.h.
template<typename Data > Util::ArraySet< Data >::~ArraySet () [virtual]
Destructor.
Definition at line 196 of file ArraySet.h.
Member Function Documentation
template<typename Data> void Util::ArraySet< Data >::allocate (const Data * array, int capacity)
Associate with a C array and allocate required memory.
This method associates an ArraySet with a bare C array, and allocates all memory required by the ArraySet.
An ArraySet may only be allocated once. This method throws an Exception if it is called more than once.
Parameters:
array associated C array of Data objects
capacity number of elements in the array
Definition at line 210 of file ArraySet.h.
References UTIL_THROW.
template<typename Data> void Util::ArraySet< Data >::allocate (const Array< Data > & array)
Associate with an Array container and allocate required memory.
Invokes allocate(&array[0], array.capacity()) internally.
Parameters:
array associated Array<Data> container
Definition at line 237 of file ArraySet.h.
References Util::Array< Data >::capacity().
template<typename Data> void Util::ArraySet< Data >::append (Data & data)
Append an element to the set.
This appends a new element to the end of the sequence. This does not change the order of other elements.
Parameters:
data array element to be added.
Definition at line 244 of file ArraySet.h.
References UTIL_THROW.
Referenced by McMd::LinkMaster::addLink(), DdMd::AtomStorage::addNewAtom(), and DdMd::AtomStorage::addNewGhost().
template<typename Data> void Util::ArraySet< Data >::remove (const Data & data)
Remove an element from the set.
Removal of an element generally changes the order of the remaining elements.
Throws an Exception if data is not in this ArraySet.
Parameters:
data array element to be added.
Definition at line 268 of file ArraySet.h.
References UTIL_THROW.
Referenced by DdMd::AtomStorage::removeAtom(), DdMd::AtomStorage::removeGhost(), and McMd::LinkMaster::removeLink().
template<typename Data > Data & Util::ArraySet< Data >::pop ()
Pop the topmost from the set.
Popping the top element does not change the order of the remaining elements.
Definition at line 301 of file ArraySet.h.
References UTIL_THROW.
Referenced by DdMd::AtomStorage::clearAtoms(), and DdMd::AtomStorage::clearGhosts().
template<typename Data > void Util::ArraySet< Data >::clear ()
Reset to empty state.
Definition at line 319 of file ArraySet.h.
template<typename Data> int Util::ArraySet< Data >::index (const Data & data) const
Return the current index of an element within the set, if any.
Return the current index of an element within the set, or return a negative value -1 if the element is not in the set.
This method returns the current index of the pointer to object data within this ArraySet, in the range 0 < index < size() -1. The method returns -1 if data is an element of the associated array but is not in the ArraySet.
Throws an exception if data is not in the associated array.
Parameters:
data array element of interest.
Returns:
current index of pointer to element within this ArraySet.
Definition at line 335 of file ArraySet.h.
References UTIL_THROW.
template<typename Data > bool Util::ArraySet< Data >::isAllocated () const [inline]
Return true if the ArraySet is initialized, false otherwise.
Definition at line 348 of file ArraySet.h.
template<typename Data > bool Util::ArraySet< Data >::isValid () const
Return true if the ArraySet is valid, or throw an exception.
Definition at line 355 of file ArraySet.h.
References UTIL_THROW.
template<typename Data> void Util::ArraySet< Data >::dump () const
Write the internal state of the ArraySet to std::cout.
The documentation for this class was generated from the following file:
ArraySet.h