Simpatico: McMd::McSystemAccess Class Reference
McMd::McSystemAccess Class Reference
McMd namespace » Monte Carlo Moves
Detailed Description
Provides faster access to an McSystem.
Definition at line 30 of file McSystemAccess.h.
#include <McSystemAccess.h>
Public Member Functions
McSystemAccess (McSystem &mcSystem)
Constructor.
virtual ~McSystemAccess ()
Destructor.
Public Member Functions inherited from McMd::SubSystem
SubSystem (System &parent)
Constructor.
virtual ~SubSystem ()
Destructor.
System & system () const
Get the parent System by reference.
Protected Member Functions
McPairPotential & pairPotential () const
Get the McPairPotential.
BondPotential & bondPotential () const
Get the BondPotential.
AnglePotential & anglePotential () const
Get the AnglePotential.
DihedralPotential & dihedralPotential () const
Get the DihedralPotential.
ExternalPotential & externalPotential () const
Get the ExternalPotential.
Protected Member Functions inherited from McMd::SubSystem
Boundary & boundary () const
Get the Boundary by reference.
Simulation & simulation () const
Get the parent Simulation by reference.
int nMolecule (int speciesId) const
Get the number of molecules of one Species in this SubSystem.
int nAtom () const
Return the total number of atoms in this SubSystem.
bool isEmpty () const
Is this an empty SubSystem (i.e., one with no molecules) ?
void begin (int speciesId, System::MoleculeIterator &iterator)
Initialize an iterator for molecules of one species in this SubSystem.
void begin (int speciesId, System::ConstMoleculeIterator &iterator) const
Initialize a const iterator for molecules of one species in this SubSystem.
bool hasBonds () const
Does a bond potential exist?
bool hasAngles () const
Does an angle potential exist?
bool hasDihedrals () const
Does a dihedral potential exist?
bool hasLinks () const
Does a link potential exist?
bool hasExternal () const
Does an external potential exist?
Constructor & Destructor Documentation
McMd::McSystemAccess::McSystemAccess (McSystem & mcSystem)
Constructor.
Parameters
mcSystem parent McSystem
Definition at line 21 of file McSystemAccess.cpp.
References McMd::McSystem::anglePotential(), McMd::McSystem::bondPotential(), McMd::McSystem::dihedralPotential(), McMd::McSystem::externalPotential(), McMd::SubSystem::hasAngles(), McMd::SubSystem::hasBonds(), McMd::SubSystem::hasDihedrals(), McMd::SubSystem::hasExternal(), and McMd::McSystem::pairPotential().
McMd::McSystemAccess::~McSystemAccess () virtual
Destructor.
Definition at line 67 of file McSystemAccess.cpp.
Member Function Documentation
McPairPotential & McMd::McSystemAccess::pairPotential () const inline protected
Get the McPairPotential.
Definition at line 114 of file McSystemAccess.h.
BondPotential & McMd::McSystemAccess::bondPotential () const inline protected
Get the BondPotential.
Definition at line 122 of file McSystemAccess.h.
AnglePotential & McMd::McSystemAccess::anglePotential () const inline protected
Get the AnglePotential.
Definition at line 130 of file McSystemAccess.h.
DihedralPotential & McMd::McSystemAccess::dihedralPotential () const inline protected
Get the DihedralPotential.
Definition at line 138 of file McSystemAccess.h.
ExternalPotential & McMd::McSystemAccess::externalPotential () const inline protected
Get the ExternalPotential.
Definition at line 146 of file McSystemAccess.h.
The documentation for this class was generated from the following files:
McSystemAccess.h
McSystemAccess.cpp