Simpatico: Util::Tensor Class Reference
Util::Tensor Class Reference
Util namespace » Space (Vector, Tensor)
Detailed Description
A Tensor represents a Cartesian tensor.
Definition at line 32 of file Tensor.h.
#include <Tensor.h>
Public Member Functions
Constructors
Tensor ()
Default constructor.
Tensor (const Tensor &t)
Copy constructor.
Tensor (double scalar)
Constructor, initialize all elements to a scalar value.
Tensor (const double a[][Dimension])
Construct Tensor from double [][Dimension] 2D C array.
Assignment
Tensor & operator= (const Tensor &t)
Copy assignment.
Tensor & operator= (const double a[][Dimension])
Assignment from C double [Dimension][Dimension] 2D array.
Arithmetic Assignment
void operator+= (const Tensor &dt)
Add tensor dt to this tensor.
void operator-= (const Tensor &dt)
Subtract tensor dt from this tensor.
void operator*= (double s)
Multiply this tensor by scalar s.
void operator/= (double s)
Divide this tensor by scalar s.
Array Subscript
const double & operator() (int i, int j) const
Return one element by value.
double & operator() (int i, int j)
Return one element by non-const reference.
Tensor valued functions (result assigned to invoking object)
Tensor & zero ()
Set all elements of this tensor to zero.
Tensor & identity ()
Set this to the identity (unity) tensor.
Tensor & setRow (int i, const Vector &r)
Set row i of this Tensor to elements of Vector r.
Tensor & setColumn (int i, const Vector &r)
Set column i of this Tensor to elements of Vector r.
Tensor & add (const Tensor &t1, const Tensor &t2)
Add tensors t1 and t2.
Tensor & subtract (const Tensor &t1, const Tensor &t2)
Subtract tensor t2 from t1.
Tensor & multiply (const Tensor &t, double s)
Multiply a tensor t by a scalar s.
Tensor & divide (const Tensor &t, double s)
Divide a Tensor t by a scalar s.
Tensor & transpose (const Tensor &t)
Compute transpose of a tensor.
Tensor & transpose ()
Transpose this tensor.
Tensor & symmetrize (const Tensor &t)
Compute symmetric part of a tensor t.
Tensor & symmetrize ()
Symmetrize this tensor.
Tensor & dyad (const Vector &v1, const Vector &v2)
Create dyad of two vectors.
Miscellaneous
double trace () const
Return the trace of this tensor.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this to/from an archive.
Friends
bool operator== (const Tensor &t1, const Tensor &t2)
Equality for Tensors.
bool operator== (const Tensor &t1, const double t2[][Dimension])
Equality of Tensor and 2D C array.
std::istream & operator>> (std::istream &in, Tensor &tensor)
istream extractor for a Tensor.
std::ostream & operator<< (std::ostream &out, const Tensor &tensor)
ostream inserter for a Tensor.
Static Members
static const Tensor Zero = Tensor(0.0)
Constant Tensor with all zero elements.
static const Tensor Identity = Tensor().identity()
Constant idenity Tensor (diagonal diagonal elements all 1).
static void initStatic ()
Call to guarantee initialization of Zero and Identity tensors.
static void commitMpiType ()
Commit MPI datatype MpiTraits<Tensor>::type.
Constructor & Destructor Documentation
Util::Tensor::Tensor () inline
Default constructor.
Definition at line 399 of file Tensor.h.
Util::Tensor::Tensor (const Tensor & t) inline
Copy constructor.
Definition at line 406 of file Tensor.h.
References Util::DimensionSq.
Util::Tensor::Tensor (double scalar) inline explicit
Constructor, initialize all elements to a scalar value.
Parameters
scalar initial value for all elements.
Definition at line 417 of file Tensor.h.
References Util::DimensionSq.
Util::Tensor::Tensor (const double a[][Dimension]) inline explicit
Construct Tensor from double [][Dimension] 2D C array.
Parameters
a 2D array a[Dimension][Dimension]
Definition at line 428 of file Tensor.h.
References Util::Dimension.
Member Function Documentation
Tensor & Util::Tensor::operator= (const Tensor & t) inline
Copy assignment.
Parameters
t Tensor to assign.
Definition at line 468 of file Tensor.h.
References Util::DimensionSq.
Tensor & Util::Tensor::operator= (const double a[][Dimension]) inline
Assignment from C double [Dimension][Dimension] 2D array.
Parameters
a 2D array a[Dimension][Dimension]
Definition at line 480 of file Tensor.h.
References Util::Dimension.
void Util::Tensor::operator+= (const Tensor & dt) inline
Add tensor dt to this tensor.
Upon return, *this = *this + dt.
Parameters
dt tensor increment (input)
Definition at line 495 of file Tensor.h.
References Util::DimensionSq.
void Util::Tensor::operator-= (const Tensor & dt) inline
Subtract tensor dt from this tensor.
Upon return, *this = *this - dt.
Parameters
dt tensor increment (input)
Definition at line 506 of file Tensor.h.
References Util::DimensionSq.
void Util::Tensor::operator*= (double s) inline
Multiply this tensor by scalar s.
Upon return, *this = (*this)*s.
Parameters
s scalar multiplier
Definition at line 517 of file Tensor.h.
References Util::DimensionSq.
void Util::Tensor::operator/= (double s) inline
Divide this tensor by scalar s.
Upon return, *this = (*this)/s.
Parameters
s scalar divisor (input)
Definition at line 528 of file Tensor.h.
References Util::DimensionSq.
const double & Util::Tensor::operator() (int i, int j) const inline
Return one element by value.
Parameters
i row element index
j column element index
Returns
element (i, j) of the tensor
Definition at line 539 of file Tensor.h.
References Util::Dimension.
double & Util::Tensor::operator() (int i, int j) inline
Return one element by non-const reference.
Parameters
i row element index
j column element index
Returns
element i of the tensor
Definition at line 552 of file Tensor.h.
References Util::Dimension.
Tensor & Util::Tensor::zero () inline
Set all elements of this tensor to zero.
Returns
reference to this tensor
Definition at line 441 of file Tensor.h.
References Util::DimensionSq.
Referenced by DdMd::BondTensorAutoCorr::computeData(), DdMd::BondPotentialImpl< Interaction >::computeForcesAndStress(), DdMd::PairPotentialImpl< Interaction >::computeForcesAndStress(), DdMd::Simulation::computeKineticStress(), McMd::MdEwaldPotential::computeStress(), McMd::MdSpmePotential::computeStress(), McMd::MdEwaldPairPotentialImpl< Interaction >::computeStress(), DdMd::AnglePotentialImpl< Interaction >::computeStress(), DdMd::BondPotentialImpl< Interaction >::computeStress(), DdMd::DihedralPotentialImpl< Interaction >::computeStress(), DdMd::PairPotentialImpl< Interaction >::computeStress(), McMd::Cluster::momentTensor(), DdMd::Potential::reduceStress(), Util::setToZero(), and DdMd::Simulation::virialStress().
Tensor & Util::Tensor::identity () inline
Set this to the identity (unity) tensor.
Returns
reference to this tensor
Definition at line 453 of file Tensor.h.
References Util::Dimension, and Util::DimensionSq.
Tensor & Util::Tensor::setRow (int i, const Vector & r) inline
Set row i of this Tensor to elements of Vector r.
Returns
reference to this tensor
Definition at line 737 of file Tensor.h.
References Util::Dimension.
Tensor & Util::Tensor::setColumn (int i, const Vector & r) inline
Set column i of this Tensor to elements of Vector r.
Returns
reference to this tensor
Definition at line 749 of file Tensor.h.
References Util::Dimension.
Tensor & Util::Tensor::add (const Tensor & t1, const Tensor & t2) inline
Add tensors t1 and t2.
Upon return, *this = t1 + t2.
Parameters
t1 tensor
t2 tensor
Returns
reference to this tensor
Definition at line 567 of file Tensor.h.
References Util::DimensionSq.
Referenced by McMd::MdStressAutoCorr::computeStress(), McMd::MdSpmePotential::computeStress(), McMd::MdEwaldPotential::computeStress(), DdMd::StressAutoCorrelation::data(), DdMd::VirialStressTensor::sample(), DdMd::VirialStressTensorAverage::sample(), DdMd::OutputStressTensor::sample(), DdMd::StressAutoCorr::sample(), McMd::StressAutoCorr< SystemType >::sample(), and McMd::StressTensorAverage< SystemType >::sample().
Tensor & Util::Tensor::subtract (const Tensor & t1, const Tensor & t2) inline
Subtract tensor t2 from t1.
Upon return, *this == t1 - t2.
Parameters
t1 tensor (input)
t2 tensor (input)
Returns
reference to this tensor
Definition at line 581 of file Tensor.h.
References Util::DimensionSq.
Tensor & Util::Tensor::multiply (const Tensor & t, double s) inline
Multiply a tensor t by a scalar s.
Upon return, *this == v*s.
Parameters
t tensor factor
s scalar factor
Returns
reference to this tensor
Definition at line 595 of file Tensor.h.
References Util::DimensionSq.
Tensor & Util::Tensor::divide (const Tensor & t, double s) inline
Divide a Tensor t by a scalar s.
Upon return, *this = v/s;
Parameters
t tensor input
s scalar denominator
Returns
reference to this tensor
Definition at line 609 of file Tensor.h.
References Util::DimensionSq.
Tensor & Util::Tensor::transpose (const Tensor & t) inline
Compute transpose of a tensor.
Upon return, *this is the transpose of t
Parameters
t input tensor
Returns
reference to this tensor
Definition at line 636 of file Tensor.h.
References Util::Dimension.
Tensor & Util::Tensor::transpose () inline
Transpose this tensor.
Upon return, *this is transposed.
Returns
reference to this tensor
Definition at line 657 of file Tensor.h.
References Util::Dimension.
Tensor & Util::Tensor::symmetrize (const Tensor & t) inline
Compute symmetric part of a tensor t.
Upon return, *this = [t + t.transpose()]/2
Parameters
t tensor input
Returns
reference to this tensor
Definition at line 678 of file Tensor.h.
References Util::Dimension.
Tensor & Util::Tensor::symmetrize () inline
Symmetrize this tensor.
Upon return, this is symmetrized, equal to half the sum of the original tensor and its transpose.
Returns
reference to this tensor
Definition at line 701 of file Tensor.h.
References Util::Dimension.
Tensor & Util::Tensor::dyad (const Vector & v1, const Vector & v2) inline
Create dyad of two vectors.
Upon return, *this equals the dyad v1 ^ v2. Equivalently: (*this)(i , j) == v1[i]*v2[j]
Parameters
v1 vector input
v2 vector input
Returns
reference to this tensor
Definition at line 763 of file Tensor.h.
References Util::Dimension.
Referenced by McMd::MdEwaldPotential::computeStress(), McMd::MdSpmePotential::computeStress(), McMd::Cluster::momentTensor(), and McMd::IntraBondTensorAutoCorr< SystemType >::sample().
double Util::Tensor::trace () const inline
Return the trace of this tensor.
Definition at line 621 of file Tensor.h.
References Util::Dimension.
Referenced by DdMd::NphIntegrator::integrateStep1(), DdMd::NptIntegrator::integrateStep1(), DdMd::NphIntegrator::integrateStep2(), and DdMd::NptIntegrator::integrateStep2().
template<class Archive > void Util::Tensor::serialize (Archive & ar, const unsigned int version) inline
Serialize this to/from an archive.
Parameters
ar archive
version archive version id
Definition at line 720 of file Tensor.h.
References Util::DimensionSq.
void Util::Tensor::initStatic () static
Call to guarantee initialization of Zero and Identity tensors.
Call this function once to guarantee that this file is linked.
Definition at line 27 of file Tensor.cpp.
References UTIL_THROW.
Referenced by Util::initStatic().
void Util::Tensor::commitMpiType () static
Commit MPI datatype MpiTraits<Tensor>::type.
Definition at line 125 of file Tensor.cpp.
References Util::MpiStructBuilder::addMember(), Util::MpiStructBuilder::commit(), Util::Dimension, and Util::MpiStructBuilder::setBase().
Friends And Related Function Documentation
bool operator== (const Tensor & t1, const Tensor & t2) friend
Equality for Tensors.
Definition at line 43 of file Tensor.cpp.
bool operator== (const Tensor & t1, const double t2[][Dimension]) friend
Equality of Tensor and 2D C array.
Definition at line 56 of file Tensor.cpp.
std::istream& operator>> (std::istream & in, Tensor & tensor) friend
istream extractor for a Tensor.
Input elements of a tensor from stream, without line breaks.
Parameters
in input stream
tensor Tensor to be read from stream
Returns
modified input stream
Definition at line 93 of file Tensor.cpp.
std::ostream& operator<< (std::ostream & out, const Tensor & tensor) friend
ostream inserter for a Tensor.
Output elements of a tensor to stream, without line breaks.
Parameters
out output stream
tensor Tensor to be written to stream
Returns
modified output stream
Definition at line 104 of file Tensor.cpp.
Member Data Documentation
const Tensor Util::Tensor::Zero = Tensor(0.0) static
Constant Tensor with all zero elements.
Definition at line 297 of file Tensor.h.
const Tensor Util::Tensor::Identity = Tensor().identity() static
Constant idenity Tensor (diagonal diagonal elements all 1).
Definition at line 302 of file Tensor.h.
Referenced by McMd::MdEwaldPotential::computeStress(), and McMd::MdSpmePotential::computeStress().
The documentation for this class was generated from the following files:
Tensor.h
Tensor.cpp