Simpatico: McMd::CfbHomoReptationMove Class Reference
McMd::CfbHomoReptationMove Class Reference
Monte Carlo Moves
Detailed Description
Configuration bias reptation move for a Linear species.
A reptation move uses a configuration bias algorithm to add a segment to one end of a chain (the head) and delete one from the other (the tail). The direction of the move (i.e., which end is the head) is chosen at random. The only parameter is nTrial, the number of trial positions for the new position of the head monomer.
Definition at line 31 of file CfbHomoReptationMove.h.
#include <CfbHomoReptationMove.h>
Public Member Functions
CfbHomoReptationMove (McSystem &system)
Constructor.
virtual void readParam (std::istream &in)
Read species to which displacement is applied.
virtual bool move ()
Generate and accept or reject configuration bias move.
Protected Attributes
int speciesId_
Integer index for molecular species.
Constructor & Destructor Documentation
McMd::CfbHomoReptationMove::CfbHomoReptationMove (McSystem & system)
Constructor.
Definition at line 35 of file CfbHomoReptationMove.cpp.
Member Function Documentation
void McMd::CfbHomoReptationMove::readParam (std::istream & in) [virtual]
Read species to which displacement is applied.
Reimplemented from McMd::CfbEndBase.
Definition at line 43 of file CfbHomoReptationMove.cpp.
References UTIL_THROW.
bool McMd::CfbHomoReptationMove::move () [virtual]
Generate and accept or reject configuration bias move.
Reimplemented from McMd::McMove.
Definition at line 67 of file CfbHomoReptationMove.cpp.
References McMd::Mask::append(), McMd::Molecule::atom(), McMd::Molecule::bond(), McMd::Mask::clear(), McMd::Atom::mask(), McMd::Molecule::nAtom(), McMd::Atom::position(), McMd::Atom::setTypeId(), McMd::Atom::typeId(), and McMd::Group< NAtom >::typeId().
Member Data Documentation
int McMd::CfbHomoReptationMove::speciesId_ [protected]
Integer index for molecular species.
Definition at line 54 of file CfbHomoReptationMove.h.
The documentation for this class was generated from the following files:
CfbHomoReptationMove.h
CfbHomoReptationMove.cpp