Simpatico: Util::ArrayStack< Data > Class Template Reference
Util::ArrayStack< Data > Class Template Reference
Pointer Arrays
Detailed Description
template<typename Data>
class Util::ArrayStack< Data >
A stack of fixed capacity.
Pointers to elements are stored in an allocatable, non-resizable array.
Definition at line 25 of file ArrayStack.h.
#include <ArrayStack.h>
Public Member Functions
ArrayStack ()
Default constructor.
virtual ~ArrayStack ()
Destructor.
void allocate (int capacity)
Initialize and allocate required memory.
Mutators
void push (Data &data)
Push an element onto the Stack.
Data & pop ()
Pop an element off the stack.
Accessors
int capacity () const
Return capacity of the underlying array.
int size () const
Get the number of elements in the stack.
Data & peek ()
Return a reference to the top element (don't pop).
const Data & peek () const
Return a const ref to the top element (don't pop).
bool isValid () const
Return true if the ArrayStack is valid, or throw an exception.
bool isAllocated () const
Return true only if the ArrayStack has been allocated.
Constructor & Destructor Documentation
template<typename Data > Util::ArrayStack< Data >::ArrayStack ()
Default constructor.
Definition at line 126 of file ArrayStack.h.
template<typename Data > Util::ArrayStack< Data >::~ArrayStack () [virtual]
Destructor.
Definition at line 136 of file ArrayStack.h.
Member Function Documentation
template<typename Data > void Util::ArrayStack< Data >::allocate (int capacity)
Initialize and allocate required memory.
Parameters:
capacity maximum size of stack.
Definition at line 147 of file ArrayStack.h.
References UTIL_THROW.
Referenced by McMd::Species::loadParameters(), and McMd::Species::readParameters().
template<typename Data> void Util::ArrayStack< Data >::push (Data & data)
Push an element onto the Stack.
Parameters:
data element to be added to stack.
Definition at line 183 of file ArrayStack.h.
References UTIL_THROW.
Referenced by DdMd::AtomDistributor::addAtom(), DdMd::AtomStorage::clearAtoms(), DdMd::AtomStorage::clearGhosts(), DdMd::AtomDistributor::newAtomPtr(), McMd::System::removeAllMolecules(), DdMd::AtomStorage::removeAtom(), DdMd::AtomStorage::removeGhost(), McMd::LinkMaster::removeLink(), McMd::McNVTChemicalPotential::sample(), and DdMd::AtomDistributor::send().
template<typename Data > Data & Util::ArrayStack< Data >::pop ()
Pop an element off the stack.
Returns:
the top element (which is popped off stack).
Definition at line 196 of file ArrayStack.h.
References UTIL_THROW.
Referenced by McMd::LinkMaster::addLink(), McMd::Linear::generateMolecules(), McMd::System::loadConfig(), DdMd::AtomStorage::newAtomPtr(), DdMd::AtomDistributor::newAtomPtr(), DdMd::AtomStorage::newGhostPtr(), McMd::McMdConfigIo::read(), McMd::PmcConfigIo::read(), McMd::DdMdConfigIo::read(), McMd::LammpsConfigIo::read(), McMd::DCDTrajectoryIo::readHeader(), and McMd::McNVTChemicalPotential::sample().
template<typename Data > int Util::ArrayStack< Data >::capacity () const
Return capacity of the underlying array.
Returns:
Number of elements allocated in array.
Definition at line 169 of file ArrayStack.h.
Referenced by McMd::LinkMaster::isValid(), and DdMd::AtomDistributor::send().
template<typename Data > int Util::ArrayStack< Data >::size () const [inline]
Get the number of elements in the stack.
Definition at line 176 of file ArrayStack.h.
Referenced by DdMd::AtomDistributor::addAtom(), McMd::LinkMaster::isValid(), DdMd::AtomStorage::isValid(), DdMd::AtomStorage::newAtomPtr(), DdMd::AtomDistributor::newAtomPtr(), DdMd::AtomStorage::newGhostPtr(), and DdMd::AtomDistributor::send().
template<typename Data > Data & Util::ArrayStack< Data >::peek () [inline]
Return a reference to the top element (don't pop).
Definition at line 211 of file ArrayStack.h.
template<typename Data > const Data & Util::ArrayStack< Data >::peek () const [inline]
Return a const ref to the top element (don't pop).
Definition at line 218 of file ArrayStack.h.
template<typename Data > bool Util::ArrayStack< Data >::isValid () const
Return true if the ArrayStack is valid, or throw an exception.
Definition at line 225 of file ArrayStack.h.
References UTIL_THROW.
Referenced by McMd::Species::isValid().
template<typename Data > bool Util::ArrayStack< Data >::isAllocated () const [inline]
Return true only if the ArrayStack has been allocated.
Definition at line 261 of file ArrayStack.h.
Referenced by McMd::Species::isValid().
The documentation for this class was generated from the following file:
ArrayStack.h