Simpatico: DdMd::AtomCollector Class Reference
DdMd::AtomCollector Class Reference
MPI Communication
Detailed Description
Class for collecting Atoms from processors to master processor.
An AtomCollector collects atoms from all processors to the master in order to output a configuration file.
Usage:
    AtomStorage storage;
    Domain domain;
    Buffer buffer;
    AtomCollector collector;
    // Initialization
    collector.associate(domain, storage, buffer);
    // Communication
    if (domain.gridRank() == 0) {  // if master processor
       collector.setup();
       Atom* atomPtr = collector.nextPtr();
       while (atomPtr) {
          // Write *atomPtr to file;
          atomPtr = collector.nextPtr();
       }
    } else { // if not master
       collector.send();
    }
Definition at line 57 of file AtomCollector.h.
#include <AtomCollector.h>
Public Member Functions
AtomCollector ()
Constructor.
~AtomCollector ()
Destructor.
void associate (Domain &domain, AtomStorage &storage, Buffer &buffer)
Initialize pointers to associated objects.
void setCapacity (int recvArrayCapacity)
Set cache capacity on master processor.
void setup ()
Setup master processor for receiving.
Atom * nextPtr ()
Return a pointer to the next available atom, or null.
void send ()
Send all atoms to the master.
Constructor & Destructor Documentation
DdMd::AtomCollector::AtomCollector ()
Constructor.
Definition at line 23 of file AtomCollector.cpp.
References Util::ParamComposite::setClassName().
DdMd::AtomCollector::~AtomCollector ()
Destructor.
Definition at line 37 of file AtomCollector.cpp.
Member Function Documentation
void DdMd::AtomCollector::associate (Domain & domain, AtomStorage & storage, Buffer & buffer)
Initialize pointers to associated objects.
Call on all processors, only once, before first call to setup.
Definition at line 45 of file AtomCollector.cpp.
Referenced by DdMd::AtomStorage::associate().
void DdMd::AtomCollector::setCapacity (int recvArrayCapacity)
Set cache capacity on master processor.
Call oly once on master processors, before first call to setup. Calling on other processors has no effect, but does no harm.
Parameters:
recvArrayCapacity size of array used to receive atoms.
Definition at line 56 of file AtomCollector.cpp.
References Util::Array< Data >::capacity(), and UTIL_THROW.
void DdMd::AtomCollector::setup ()
Setup master processor for receiving.
Call only on the master processor, just before each receive loop.
Definition at line 70 of file AtomCollector.cpp.
References DdMd::AtomArray::allocate(), DdMd::AtomStorage::begin(), Util::Array< Data >::capacity(), DdMd::Domain::isInitialized(), DdMd::Buffer::isInitialized(), DdMd::Domain::isMaster(), and UTIL_THROW.
Referenced by DdMd::SerializeConfigIo::saveConfig(), DdMd::DdMdConfigIo::writeConfig(), DdMd::LammpsConfigIo::writeConfig(), DdMd::DdMdOrderedConfigIo::writeConfig(), DdMd::LammpsDumpWriter::writeFrame(), DdMd::DdMdTrajectoryWriter::writeFrame(), DdMd::DdMdGroupTrajectoryWriter::writeFrame(), and DdMd::DdMdGroupTrajectoryWriter::writeHeader().
Atom * DdMd::AtomCollector::nextPtr ()
Return a pointer to the next available atom, or null.
Call only on the master processor, within loop over atoms.
Returns:
address of next atom, or null if no more are available.
Definition at line 110 of file AtomCollector.cpp.
References DdMd::Buffer::beginRecvBlock(), Util::Array< Data >::capacity(), DdMd::Domain::communicator(), DdMd::Buffer::endRecvBlock(), Util::PArrayIterator< Data >::get(), DdMd::Domain::grid(), DdMd::Domain::isInitialized(), DdMd::Domain::isMaster(), Util::PArrayIterator< Data >::notEnd(), DdMd::Buffer::recv(), DdMd::Buffer::recvSize(), Util::Grid::size(), and UTIL_THROW.
Referenced by DdMd::SerializeConfigIo::saveConfig(), DdMd::DdMdConfigIo::writeConfig(), DdMd::LammpsConfigIo::writeConfig(), DdMd::DdMdOrderedConfigIo::writeConfig(), DdMd::LammpsDumpWriter::writeFrame(), DdMd::DdMdTrajectoryWriter::writeFrame(), DdMd::DdMdGroupTrajectoryWriter::writeFrame(), and DdMd::DdMdGroupTrajectoryWriter::writeHeader().
void DdMd::AtomCollector::send ()
Send all atoms to the master.
Call on all processors except the master.
Definition at line 207 of file AtomCollector.cpp.
References DdMd::AtomStorage::begin(), DdMd::Buffer::beginSendBlock(), DdMd::Buffer::clearSendBuffer(), DdMd::Domain::communicator(), DdMd::Buffer::endSendBlock(), Util::PArrayIterator< Data >::isEnd(), DdMd::Domain::isInitialized(), DdMd::Buffer::isInitialized(), DdMd::Domain::isMaster(), DdMd::Buffer::send(), and UTIL_THROW.
Referenced by DdMd::SerializeConfigIo::saveConfig(), DdMd::DdMdConfigIo::writeConfig(), DdMd::LammpsConfigIo::writeConfig(), DdMd::DdMdOrderedConfigIo::writeConfig(), DdMd::LammpsDumpWriter::writeFrame(), DdMd::DdMdTrajectoryWriter::writeFrame(), DdMd::DdMdGroupTrajectoryWriter::writeFrame(), and DdMd::DdMdGroupTrajectoryWriter::writeHeader().
The documentation for this class was generated from the following files:
AtomCollector.h
AtomCollector.cpp