Simpatico: Inter::LamellarOrderingExternal Class Reference
Inter::LamellarOrderingExternal Class Reference
External Interactions
Detailed Description
A clipped cosine potential that induces lamellar ordering along the direction specified by perpDirection_.
perpDirection_ = 0: x direction = 1: y direction = 2: z direction
/ / z \ \ u = prefactor[atomType] externalParameter tanh | clipParameter cos | 2 pi periodicity --- | | \ \ Lz / /
Prefactor (which depends on the atomType), externalParameter, interfaceWidth (relative to the box length along the direction perpendicular to lamellae) and periodicity are given as inputs in the parameter file. ClipParameter is the inverse of 2*pi*periodicity*interfaceWidth.
Definition at line 39 of file LamellarOrderingExternal.h.
#include <LamellarOrderingExternal.h>
Public Member Functions
LamellarOrderingExternal ()
Default constructor.
LamellarOrderingExternal (const LamellarOrderingExternal &other)
Copy constructor.
LamellarOrderingExternal & operator= (const LamellarOrderingExternal &other)
Assignment.
void setNAtomType (int nAtomType)
Set nAtomType value.
void setExternalParameter (double externalParameter)
Sets external parameter.
void setBoundary (Boundary &boundary)
Set pointer to Boundary.
void readParameters (std::istream &in)
Read potential parameters, and initialize other variables.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
double externalParameter () const
Returns external parameter.
double energy (double d, int i) const
Returns external potential energy of a particle of type i.
double energy (const Vector &position, int i) const
Returns external potential energy of a single particle.
double forceScalar (double d, int type) const
Returns magnitude of the external force.
void getForce (const Vector &position, int type, Vector &force) const
Returns force caused by the external potential.
std::string className () const
Return name string "LamellarOrderingExternal".
Constructor & Destructor Documentation
Inter::LamellarOrderingExternal::LamellarOrderingExternal ()
Default constructor.
Definition at line 23 of file LamellarOrderingExternal.cpp.
References Util::ParamComposite::setClassName().
Inter::LamellarOrderingExternal::LamellarOrderingExternal (const LamellarOrderingExternal & other)
Copy constructor.
Definition at line 36 of file LamellarOrderingExternal.cpp.
References Util::DArray< Data >::allocate().
Member Function Documentation
LamellarOrderingExternal & Inter::LamellarOrderingExternal::operator= (const LamellarOrderingExternal & other)
Assignment.
Definition at line 54 of file LamellarOrderingExternal.cpp.
void Inter::LamellarOrderingExternal::setNAtomType (int nAtomType)
Set nAtomType value.
Parameters:
nAtomType number of atom types.
Definition at line 73 of file LamellarOrderingExternal.cpp.
References UTIL_THROW.
void Inter::LamellarOrderingExternal::setExternalParameter (double externalParameter)
Sets external parameter.
Parameters:
externalParameter external parameter of system
Definition at line 84 of file LamellarOrderingExternal.cpp.
References externalParameter(), and UTIL_THROW.
void Inter::LamellarOrderingExternal::setBoundary (Boundary & boundary)
Set pointer to Boundary.
Parameters:
boundary Boundary object (used to calculate length along perpendicular direction).
Definition at line 98 of file LamellarOrderingExternal.cpp.
void Inter::LamellarOrderingExternal::readParameters (std::istream & in) [virtual]
Read potential parameters, and initialize other variables.
Precondition:
nAtomType must have been set, by calling setNAtomType().
Boundary must have been set, by calling setBoundary().
Parameters:
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 104 of file LamellarOrderingExternal.cpp.
References Util::DArray< Data >::allocate(), Util::Dimension, and UTIL_THROW.
void Inter::LamellarOrderingExternal::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 130 of file LamellarOrderingExternal.cpp.
References Util::DArray< Data >::allocate(), Util::Dimension, and UTIL_THROW.
void Inter::LamellarOrderingExternal::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 151 of file LamellarOrderingExternal.cpp.
double Inter::LamellarOrderingExternal::externalParameter () const
Returns external parameter.
Returns:
external parameter
Definition at line 161 of file LamellarOrderingExternal.cpp.
Referenced by setExternalParameter().
double Inter::LamellarOrderingExternal::energy (double d, int i) const [inline]
Returns external potential energy of a particle of type i.
Parameters:
d component of position along the perpendicular direction
i type of particle (prefactor depends on atomtype)
Returns:
external potential energy
Definition at line 186 of file LamellarOrderingExternal.h.
double Inter::LamellarOrderingExternal::energy (const Vector & position, int i) const [inline]
Returns external potential energy of a single particle.
Parameters:
position atomic position Vector
i atom type.
Returns:
external potential energy
Definition at line 205 of file LamellarOrderingExternal.h.
double Inter::LamellarOrderingExternal::forceScalar (double d, int type) const [inline]
Returns magnitude of the external force.
Parameters:
d component of position along the perpendicular direction
type atom type id (not used)
Returns:
force scalar
Definition at line 218 of file LamellarOrderingExternal.h.
void Inter::LamellarOrderingExternal::getForce (const Vector & position, int type, Vector & force) const [inline]
Returns force caused by the external potential.
Parameters:
position atom position
type atom type id
force force on the atom (on output)
Definition at line 238 of file LamellarOrderingExternal.h.
References Util::Vector::zero().
std::string Inter::LamellarOrderingExternal::className () const
Return name string "LamellarOrderingExternal".
Reimplemented from Util::ParamComposite.
Definition at line 167 of file LamellarOrderingExternal.cpp.
The documentation for this class was generated from the following files:
LamellarOrderingExternal.h
LamellarOrderingExternal.cpp