Simpatico: McMd::SystemInterface Class Reference
McMd::SystemInterface Class Reference
McMd namespace » Systems
Detailed Description
An interface to a System.
A SystemInterface is an interface for a system that is intended to be used as a protected or private base class for classes that evaluate properties of a system. It provides functions to directly access:
an ArraySet of Molecule objects of each Species.
a Boundary.
Definition at line 42 of file SystemInterface.h.
#include <SystemInterface.h>
Public Member Functions
SystemInterface (System &parent)
Constructor.
virtual ~SystemInterface ()
Destructor.
System & system () const
Get the parent System by reference.
Protected Member Functions
Accessors (Miscellaneous)
Boundary & boundary () const
Get the Boundary by reference.
Simulation & simulation () const
Get the parent Simulation by reference.
Molecule Set Accessors
int nMolecule (int speciesId) const
Get the number of molecules of one Species in this SystemInterface.
int nAtom () const
Return the total number of atoms in this SystemInterface.
bool isEmpty () const
Is this an empty SystemInterface (i.e., one with no molecules) ?
void begin (int speciesId, System::MoleculeIterator &iterator)
Initialize an iterator for molecules of one species in this SystemInterface.
void begin (int speciesId, System::ConstMoleculeIterator &iterator) const
Initialize a const iterator for molecules of one species in this SystemInterface.
Potential Energy Queries
bool hasLinks () const
Does a link potential exist?
Constructor & Destructor Documentation
McMd::SystemInterface::SystemInterface (System & parent)
Constructor.
Parameters
parent parent System
Definition at line 24 of file SystemInterface.cpp.
McMd::SystemInterface::~SystemInterface () virtual
Destructor.
Definition at line 52 of file SystemInterface.cpp.
Member Function Documentation
System & McMd::SystemInterface::system () const inline
Get the parent System by reference.
Definition at line 214 of file SystemInterface.h.
Referenced by McMd::ExternalPotentialImpl< Interaction >::readParameters().
Boundary & McMd::SystemInterface::boundary () const inline protected
Get the Boundary by reference.
Definition at line 223 of file SystemInterface.h.
Referenced by McMd::LinkPotentialImpl< Interaction >::addForces(), McMd::BondPotentialImpl< Interaction >::addForces(), McMd::MdEwaldPairPotentialImpl< Interaction >::addForces(), McMd::MdPairPotentialImpl< Interaction >::addForces(), McMd::DihedralPotentialImpl< Interaction >::addForces(), McMd::AnglePotentialImpl< Interaction >::addForces(), McMd::LinkPotentialImpl< Interaction >::atomEnergy(), McMd::BondPotentialImpl< Interaction >::atomEnergy(), McMd::McPairPotentialImpl< Interaction >::atomEnergy(), McMd::DihedralPotentialImpl< Interaction >::atomEnergy(), McMd::AnglePotentialImpl< Interaction >::atomEnergy(), McMd::McPairPotential::buildCellList(), McMd::MdPairPotential::buildPairList(), McMd::LinkPotentialImpl< Interaction >::computeEnergy(), McMd::BondPotentialImpl< Interaction >::computeEnergy(), McMd::McPairPotentialImpl< Interaction >::computeEnergy(), McMd::MdPairPotentialImpl< Interaction >::computeEnergy(), McMd::MdEwaldPairPotentialImpl< Interaction >::computeEnergy(), McMd::DihedralPotentialImpl< Interaction >::computeEnergy(), McMd::AnglePotentialImpl< Interaction >::computeEnergy(), McMd::MdEwaldPairPotentialImpl< Interaction >::computeStress(), McMd::MdPairPotential::isPairListCurrent(), McMd::McPairPotentialImpl< Interaction >::moleculeEnergy(), and McMd::ExternalPotentialImpl< Interaction >::readParameters().
Simulation & McMd::SystemInterface::simulation () const inline protected
Get the parent Simulation by reference.
Definition at line 205 of file SystemInterface.h.
Referenced by McMd::ExternalPotentialImpl< Interaction >::addForces(), McMd::BondPotentialImpl< Interaction >::addForces(), McMd::DihedralPotentialImpl< Interaction >::addForces(), McMd::AnglePotentialImpl< Interaction >::addForces(), McMd::McPairPotential::buildCellList(), McMd::MdPairPotential::buildPairList(), McMd::BondPotentialImpl< Interaction >::computeEnergy(), McMd::DihedralPotentialImpl< Interaction >::computeEnergy(), McMd::AnglePotentialImpl< Interaction >::computeEnergy(), McMd::ExternalPotentialImpl< Interaction >::energy(), isEmpty(), McMd::McPairPotentialImpl< Interaction >::loadParameters(), McMd::BondPotentialImpl< Interaction >::loadParameters(), McMd::AnglePotentialImpl< Interaction >::loadParameters(), McMd::ExternalPotentialImpl< Interaction >::loadParameters(), McMd::DihedralPotentialImpl< Interaction >::loadParameters(), McMd::MdPairPotentialImpl< Interaction >::loadParameters(), McMd::MdEwaldPairPotentialImpl< Interaction >::loadParameters(), nAtom(), McMd::McPairPotentialImpl< Interaction >::readParameters(), McMd::BondPotentialImpl< Interaction >::readParameters(), McMd::AnglePotentialImpl< Interaction >::readParameters(), McMd::ExternalPotentialImpl< Interaction >::readParameters(), McMd::DihedralPotentialImpl< Interaction >::readParameters(), McMd::LinkPotentialImpl< Interaction >::readParameters(), McMd::MdPairPotentialImpl< Interaction >::readParameters(), and McMd::MdEwaldPairPotentialImpl< Interaction >::readParameters().
int McMd::SystemInterface::nMolecule (int speciesId) const inline protected
Get the number of molecules of one Species in this SystemInterface.
Parameters
speciesId integer Id for a Species.
Returns
number of molecules of specified Species in this SystemInterface.
Definition at line 232 of file SystemInterface.h.
Referenced by isEmpty(), and nAtom().
int McMd::SystemInterface::nAtom () const protected
Return the total number of atoms in this SystemInterface.
Definition at line 69 of file SystemInterface.cpp.
References Simp::Species::nAtom(), nMolecule(), McMd::Simulation::nSpecies(), simulation(), and McMd::Simulation::species().
bool McMd::SystemInterface::isEmpty () const protected
Is this an empty SystemInterface (i.e., one with no molecules) ?
Definition at line 58 of file SystemInterface.cpp.
References nMolecule(), McMd::Simulation::nSpecies(), and simulation().
void McMd::SystemInterface::begin (int speciesId, System::MoleculeIterator & iterator) inline protected
Initialize an iterator for molecules of one species in this SystemInterface.
Parameters
speciesId integer Id for the desired Species (input)
iterator molecule iterator (output)
Definition at line 242 of file SystemInterface.h.
Referenced by McMd::ExternalPotentialImpl< Interaction >::addForces(), McMd::BondPotentialImpl< Interaction >::addForces(), McMd::DihedralPotentialImpl< Interaction >::addForces(), McMd::AnglePotentialImpl< Interaction >::addForces(), McMd::McPairPotential::buildCellList(), McMd::MdPairPotential::buildPairList(), McMd::BondPotentialImpl< Interaction >::computeEnergy(), McMd::DihedralPotentialImpl< Interaction >::computeEnergy(), McMd::AnglePotentialImpl< Interaction >::computeEnergy(), and McMd::ExternalPotentialImpl< Interaction >::energy().
void McMd::SystemInterface::begin (int speciesId, System::ConstMoleculeIterator & iterator) const inline protected
Initialize a const iterator for molecules of one species in this SystemInterface.
Parameters
speciesId integer Id for the desired Species (input)
iterator molecule iterator (output)
Definition at line 252 of file SystemInterface.h.
References hasLinks().
bool McMd::SystemInterface::hasLinks () const inline protected
Does a link potential exist?
Definition at line 282 of file SystemInterface.h.
Referenced by begin().
The documentation for this class was generated from the following files:
SystemInterface.h
SystemInterface.cpp