Simpatico: McMd::BoundaryAverage Class Reference
McMd::BoundaryAverage Class Reference
Diagnostics
Detailed Description
Average of boundary lengths and volume of simulation cell.
Definition at line 26 of file BoundaryAverage.h.
#include <BoundaryAverage.h>
Public Member Functions
BoundaryAverage (System &system)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Clear accumulator.
virtual void sample (long iStep)
Evaluate volume and lengths of simulation cell, and add to ensemble.
virtual void output ()
Output results to file after simulation is completed.
Constructor & Destructor Documentation
McMd::BoundaryAverage::BoundaryAverage (System & system)
Constructor.
Parameters:
system reference to parent System
Definition at line 29 of file BoundaryAverage.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::BoundaryAverage::readParameters (std::istream & in) [virtual]
Read parameters from file.
Parameters:
in input parameter stream
Reimplemented from McMd::Diagnostic.
Definition at line 40 of file BoundaryAverage.cpp.
References Util::DArray< Data >::allocate(), Util::Dimension, McMd::Diagnostic::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), McMd::Diagnostic::readInterval(), and McMd::Diagnostic::readOutputFileName().
void McMd::BoundaryAverage::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 63 of file BoundaryAverage.cpp.
References McMd::Diagnostic::fileMaster(), Util::FileMaster::openOutputFile(), and McMd::Diagnostic::outputFileName().
void McMd::BoundaryAverage::save (Serializable::OArchive & ar) [virtual]
Save state to archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 79 of file BoundaryAverage.cpp.
template<class Archive > void McMd::BoundaryAverage::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Diagnostic.
Definition at line 106 of file BoundaryAverage.h.
References McMd::serialize().
void McMd::BoundaryAverage::setup () [virtual]
Clear accumulator.
Reimplemented from McMd::Diagnostic.
Definition at line 85 of file BoundaryAverage.cpp.
References Util::Dimension, and UTIL_THROW.
void McMd::BoundaryAverage::sample (long iStep) [virtual]
Evaluate volume and lengths of simulation cell, and add to ensemble.
Parameters:
iStep counter for number of steps
Implements McMd::Diagnostic.
Definition at line 99 of file BoundaryAverage.cpp.
References McMd::System::boundary(), Util::Dimension, McMd::Diagnostic::isAtInterval(), Util::OrthorhombicBoundary::lengths(), McMd::SystemDiagnostic< System >::system(), and Util::OrthorhombicBoundary::volume().
void McMd::BoundaryAverage::output () [virtual]
Output results to file after simulation is completed.
Reimplemented from McMd::Diagnostic.
Definition at line 117 of file BoundaryAverage.cpp.
References Util::Dimension, McMd::Diagnostic::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
BoundaryAverage.h
BoundaryAverage.cpp