Simpatico: McMd::SpeciesGroup< NAtom > Class Template Reference
McMd::SpeciesGroup< NAtom > Class Template Reference
McMd namespace » Species
Detailed Description
template<int NAtom>
class McMd::SpeciesGroup< NAtom >
A Group of covalently interacting atoms within any molecule of one Species.
Class SpeciesGroup is used in the implementation of class Species to define the covalent chemical structure for any molecule of a particular species. The chemical structure of a Species is defined by a set of SpeciesGroup<2> (bond), SpeciesGroup<3> (angle), and SpeciesGroup<4> (dihedral) objects. Each SpeciesGroup<NAtom> object contains an array of NAtom local integer atom indices, which identities a group of atoms that are involved in a an NAtom-body covalent interaction. Each local atom index i must lie in the range 0 <= i < nAtom. A local atom index identifies the position of of an Atom within a generic molecule of the associated species. Each SpeciesGroup also has an integer group type index to distinguish different types of bonds, angles, and dihedrals, with different potential parameters.
The difference between a SpeciesGroup and a Group is that a Group contains an array of pointers to specific Atom objects that all belong to a specific Molecule. Each SpeciesGroup is thus a prototype for constructing one Group for each Molecule within a Species.
Definition at line 20 of file SpeciesGroup.h.
#include <SpeciesGroup.h>
Public Member Functions
SpeciesGroup ()
Constructor.
void setAtomId (int i, int atomId)
Set index for one atom in the group.
void setTypeId (int typeId)
Set the group type id for this group.
int atomId (int i) const
Get the local id for a specific Atom.
int typeId () const
Get the type id for this covalent group.
Static Public Member Functions
static void commitMpiType ()
Commit associated MPI DataType.
Static Public Attributes
static const int NullIndex = -1
Null (unknown) value for non-negative atom and group type indices.
Friends
std::istream & operator>> (std::istream &in, SpeciesGroup< NAtom > &speciesGroup)
istream extractor for a SpeciesGroup.
std::ostream & operator<< (std::ostream &out, const SpeciesGroup< NAtom > &speciesGroup)
ostream inserter for a SpeciesGroup.
template<class Archive >
void serialize (Archive &ar, SpeciesGroup< NAtom > &speciesGroup, const unsigned int version)
Serialize one SpeciesGroup<NAtom>.
template<class Archive >
void serialize (Archive &ar, SpeciesGroup< NAtom > &speciesGroup, const unsigned int version)
Serialize one SpeciesGroup<NAtom>.
Constructor & Destructor Documentation
template<int NAtom> McMd::SpeciesGroup< NAtom >::SpeciesGroup () inline
Constructor.
Definition at line 149 of file SpeciesGroup.h.
References McMd::SpeciesGroup< NAtom >::NullIndex.
Member Function Documentation
template<int NAtom> void McMd::SpeciesGroup< NAtom >::setAtomId (int i, int atomId) inline
Set index for one atom in the group.
Parameters
i index of atom within group (0, .., NAtom - 1)
atomId index of atom to be added.
Definition at line 161 of file SpeciesGroup.h.
References McMd::SpeciesGroup< NAtom >::atomId().
template<int NAtom> void McMd::SpeciesGroup< NAtom >::setTypeId (int typeId) inline
Set the group type id for this group.
Parameters
typeId value of covalent group typeId
Definition at line 168 of file SpeciesGroup.h.
References McMd::SpeciesGroup< NAtom >::typeId().
template<int NAtom> int McMd::SpeciesGroup< NAtom >::atomId (int i) const inline
Get the local id for a specific Atom.
Parameters
i index within group (0, ..., NAtom - 1)
Definition at line 175 of file SpeciesGroup.h.
Referenced by McMd::Species::isValid(), McMd::Simulation::isValid(), McMd::Species::loadSpeciesParam(), McMd::Species::readSpeciesParam(), McMd::Simulation::save(), and McMd::SpeciesGroup< NAtom >::setAtomId().
template<int NAtom> int McMd::SpeciesGroup< NAtom >::typeId () const inline
Get the type id for this covalent group.
Definition at line 182 of file SpeciesGroup.h.
References McMd::SpeciesGroup< NAtom >::operator>>, and McMd::SpeciesGroup< NAtom >::serialize.
Referenced by McMd::Simulation::isValid(), McMd::CfbReptationMove::loadParameters(), McMd::CfbReptateMove::loadParameters(), McMd::CfbReptationMove::readParameters(), McMd::Simulation::save(), and McMd::SpeciesGroup< NAtom >::setTypeId().
template<int NAtom> void McMd::SpeciesGroup< NAtom >::commitMpiType () static
Commit associated MPI DataType.
Commit MPI Datatype.
Definition at line 61 of file SpeciesGroup.tpp.
References Util::MpiStructBuilder::addMember(), Util::MpiStructBuilder::commit(), and Util::MpiStructBuilder::setBase().
Friends And Related Function Documentation
template<int NAtom> std::istream& operator>> (std::istream & in, SpeciesGroup< NAtom > & speciesGroup) friend
istream extractor for a SpeciesGroup.
The format is as follows:
 atomIds[0] atomIds[1] ...  atomId[NAtom-1]  typeId
Parameters
in input stream
speciesGroup SpeciesGroup to be read from stream
Returns
modified input stream
Definition at line 27 of file SpeciesGroup.tpp.
Referenced by McMd::SpeciesGroup< NAtom >::typeId().
template<int NAtom> std::ostream& operator<< (std::ostream & out, const SpeciesGroup< NAtom > & speciesGroup) friend
ostream inserter for a SpeciesGroup.
The format is as follows, output one one line with no line break:
 atomIds[0] atomIds[1] ...  atomId[NAtom-1] typeId
Parameters
out output stream
speciesGroup SpeciesGroup to be written to stream
Returns
modified output stream
Definition at line 41 of file SpeciesGroup.tpp.
template<int NAtom> template<class Archive > void serialize (Archive & ar, SpeciesGroup< NAtom > & speciesGroup, const unsigned int version) friend
Serialize one SpeciesGroup<NAtom>.
Default implementation calls serialize member function of data object. Can be overridden by any explicit specialization.
Parameters
ar archive object
speciesGroup object to be serialized
version archive version id
Referenced by McMd::SpeciesGroup< NAtom >::typeId().
template<int NAtom> template<class Archive > void serialize (Archive & ar, SpeciesGroup< NAtom > & speciesGroup, const unsigned int version) friend
Serialize one SpeciesGroup<NAtom>.
Default implementation calls serialize member function of data object. Can be overridden by any explicit specialization.
Parameters
ar archive object
speciesGroup object to be serialized
version archive version id
Member Data Documentation
template<int NAtom> const int McMd::SpeciesGroup< NAtom >::NullIndex = -1 static
Null (unknown) value for non-negative atom and group type indices.
Definition at line 76 of file SpeciesGroup.h.
Referenced by McMd::SpeciesGroup< NAtom >::SpeciesGroup().
The documentation for this class was generated from the following files:
SpeciesGroup.h
SpeciesGroup.tpp