Simpatico: DdMd::OutputBoxdim Class Reference
DdMd::OutputBoxdim Class Reference
Analyzers
Detailed Description
Periodically write simulation energies to file.
See also:
param file format
Definition at line 26 of file OutputBoxdim.h.
#include <OutputBoxdim.h>
Public Member Functions
OutputBoxdim (Simulation &simulation)
Constructor.
virtual ~OutputBoxdim ()
Destructor.
virtual void readParameters (std::istream &in)
Read dumpPrefix and interval.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void clear ()
Clear nSample counter.
virtual void setup ()
Open output file.
virtual void sample (long iStep)
Output box dimensions to file.
Constructor & Destructor Documentation
DdMd::OutputBoxdim::OutputBoxdim (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object.
Definition at line 24 of file OutputBoxdim.cpp.
References Util::ParamComposite::setClassName().
virtual DdMd::OutputBoxdim::~OutputBoxdim () [inline, virtual]
Destructor.
Definition at line 41 of file OutputBoxdim.h.
Member Function Documentation
void DdMd::OutputBoxdim::readParameters (std::istream & in) [virtual]
Read dumpPrefix and interval.
Parameters:
in input parameter file
Reimplemented from Util::ParamComposite.
Definition at line 33 of file OutputBoxdim.cpp.
References DdMd::Simulation::fileMaster(), Util::FileMaster::openOutputFile(), DdMd::Analyzer::outputFileName(), DdMd::Analyzer::readInterval(), DdMd::Analyzer::readOutputFileName(), and DdMd::Analyzer::simulation().
void DdMd::OutputBoxdim::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from DdMd::Analyzer.
Definition at line 49 of file OutputBoxdim.cpp.
References Util::MpiLoader< IArchive >::load(), DdMd::Analyzer::loadInterval(), and DdMd::Analyzer::loadOutputFileName().
void DdMd::OutputBoxdim::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from DdMd::Analyzer.
Definition at line 63 of file OutputBoxdim.cpp.
References DdMd::Analyzer::saveInterval(), and DdMd::Analyzer::saveOutputFileName().
void DdMd::OutputBoxdim::clear () [virtual]
Clear nSample counter.
Reimplemented from DdMd::Analyzer.
Definition at line 73 of file OutputBoxdim.cpp.
void DdMd::OutputBoxdim::setup () [virtual]
Open output file.
Reimplemented from DdMd::Analyzer.
Definition at line 79 of file OutputBoxdim.cpp.
References DdMd::Simulation::fileMaster(), Util::FileMaster::openOutputFile(), DdMd::Analyzer::outputFileName(), and DdMd::Analyzer::simulation().
void DdMd::OutputBoxdim::sample (long iStep) [virtual]
Output box dimensions to file.
Parameters:
iStep MD step index
Implements DdMd::Analyzer.
Definition at line 91 of file OutputBoxdim.cpp.
References DdMd::Simulation::boundary(), DdMd::Simulation::computeKineticStress(), DdMd::Simulation::computeVirialStress(), DdMd::Simulation::domain(), DdMd::Analyzer::isAtInterval(), DdMd::Domain::isMaster(), Util::OrthorhombicBoundary::lengths(), DdMd::Analyzer::simulation(), and Util::OrthorhombicBoundary::volume().
The documentation for this class was generated from the following files:
OutputBoxdim.h
OutputBoxdim.cpp