Simpatico: McMd::BondLengthDist Class Reference
McMd::BondLengthDist Class Reference
MC/MD Analyzers
Detailed Description
BondLengthDist evaluates the distribution function of the lengths of the bonds.
See also:
parameter file format
Definition at line 30 of file BondLengthDist.h.
#include <BondLengthDist.h>
Public Member Functions
BondLengthDist (System &system)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Clear accumulator.
void sample (long iStep)
Add particle pairs to BondLengthDist histogram.
virtual void output ()
Output results to output file.
Constructor & Destructor Documentation
McMd::BondLengthDist::BondLengthDist (System & system)
Constructor.
Parameters:
system reference to parent System object
Definition at line 26 of file BondLengthDist.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::BondLengthDist::readParameters (std::istream & in) [virtual]
Read parameters from file.
Read parameters from file, and allocate data array.
Parameters:
in input parameter stream
Reimplemented from McMd::Analyzer.
Definition at line 35 of file BondLengthDist.cpp.
References Util::Distribution::clear(), McMd::Analyzer::readInterval(), McMd::Analyzer::readOutputFileName(), Util::Distribution::setParam(), and UTIL_THROW.
void McMd::BondLengthDist::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from McMd::Analyzer.
Definition at line 55 of file BondLengthDist.cpp.
References Util::feq(), McMd::Analyzer::loadInterval(), McMd::Analyzer::loadOutputFileName(), and UTIL_THROW.
void McMd::BondLengthDist::save (Serializable::OArchive & ar) [virtual]
Save state to archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::Analyzer.
Definition at line 86 of file BondLengthDist.cpp.
template<class Archive > void McMd::BondLengthDist::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Analyzer.
Definition at line 118 of file BondLengthDist.h.
References McMd::serialize().
void McMd::BondLengthDist::setup () [virtual]
Clear accumulator.
Reimplemented from McMd::Analyzer.
Definition at line 92 of file BondLengthDist.cpp.
References Util::Distribution::clear(), and UTIL_THROW.
void McMd::BondLengthDist::sample (long iStep) [virtual]
Add particle pairs to BondLengthDist histogram.
Add particle pairs to RDF histogram.
Parameters:
iStep step counter
Implements McMd::Analyzer.
Definition at line 101 of file BondLengthDist.cpp.
References McMd::System::boundary(), Util::OrthorhombicBoundary::distanceSq(), McMd::Analyzer::isAtInterval(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), Util::Distribution::sample(), and McMd::SystemAnalyzer< System >::system().
void McMd::BondLengthDist::output () [virtual]
Output results to output file.
Output results to file after simulation is completed.
Reimplemented from McMd::Analyzer.
Definition at line 122 of file BondLengthDist.cpp.
References McMd::Analyzer::fileMaster(), Util::FileMaster::openOutputFile(), Util::Distribution::output(), McMd::Analyzer::outputFileName(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
BondLengthDist.h
BondLengthDist.cpp