Simpatico: MdCf::Species Class Reference
MdCf::Species Class Reference
Chemical Structure
Detailed Description
A set of identical molecules.
Definition at line 27 of file mdCf/chemistry/Species.h.
#include <Species.h>
Public Member Functions
Species ()
Constructor.
void setId (int id)
Set the index for this species.
void initialize (int nAtom, int capacity)
Initialize memory for this species and set sizes.
void initialize ()
Initialize memory for this species.
void addAtom (Atom &atom)
Add an atom to the species.
void clear ()
Clear all molecules, reset to empty.
void begin (MoleculeIterator &iterator)
Initialize an iterator over molecules.
Molecule & molecule (int i)
Return a specific molecule by reference.
int id () const
Return integer id for this species.
int nAtom () const
Return number of atoms per molecule.
int size () const
Return number of molecules in this species (=maximum id + 1)
int capacity () const
Return maximum number of molecules in this species.
Friends
std::istream & operator>> (std::istream &in, Species &species)
istream extractor (>>) for a Species.
std::ostream & operator<< (std::ostream &out, const Species &species)
ostream inserter (<<) for a Species.
Constructor & Destructor Documentation
MdCf::Species::Species ()
Constructor.
Definition at line 20 of file mdCf/chemistry/Species.cpp.
Member Function Documentation
void MdCf::Species::setId (int id)
Set the index for this species.
Parameters
id species index
Definition at line 28 of file mdCf/chemistry/Species.cpp.
References id().
void MdCf::Species::initialize (int nAtom, int capacity)
Initialize memory for this species and set sizes.
Parameters
nAtom number of atoms per molecule (exact)
capacity maximum number of molecules in species
Definition at line 31 of file mdCf/chemistry/Species.cpp.
References capacity(), initialize(), and nAtom().
Referenced by MdCf::operator>>().
void MdCf::Species::initialize ()
Initialize memory for this species.
Definition at line 42 of file mdCf/chemistry/Species.cpp.
References UTIL_THROW.
Referenced by initialize().
void MdCf::Species::addAtom (Atom & atom)
Add an atom to the species.
Parameters
atom Atom object to be added, must have AtomContext info.
Definition at line 95 of file mdCf/chemistry/Species.cpp.
References MdCf::Atom::atomId, MdCf::Atom::moleculeId, MdCf::Atom::speciesId, and UTIL_THROW.
Referenced by MdCf::DdMdConfigIo::readConfig().
void MdCf::Species::clear ()
Clear all molecules, reset to empty.
Definition at line 81 of file mdCf/chemistry/Species.cpp.
void MdCf::Species::begin (MoleculeIterator & iterator)
Initialize an iterator over molecules.
Definition at line 124 of file mdCf/chemistry/Species.cpp.
Molecule & MdCf::Species::molecule (int i) inline
Return a specific molecule by reference.
Parameters
i molecule index
Definition at line 150 of file mdCf/chemistry/Species.h.
int MdCf::Species::id () const inline
Return integer id for this species.
Definition at line 156 of file mdCf/chemistry/Species.h.
Referenced by setId().
int MdCf::Species::nAtom () const inline
Return number of atoms per molecule.
Definition at line 160 of file mdCf/chemistry/Species.h.
Referenced by initialize().
int MdCf::Species::size () const inline
Return number of molecules in this species (=maximum id + 1)
Definition at line 164 of file mdCf/chemistry/Species.h.
int MdCf::Species::capacity () const inline
Return maximum number of molecules in this species.
Definition at line 168 of file mdCf/chemistry/Species.h.
Referenced by initialize().
Friends And Related Function Documentation
std::istream& operator>> (std::istream & in, Species & species) friend
istream extractor (>>) for a Species.
Parameters
in input stream
species Species to be read from stream
Returns
modified input stream
Definition at line 171 of file mdCf/chemistry/Species.cpp.
std::ostream& operator<< (std::ostream & out, const Species & species) friend
ostream inserter (<<) for a Species.
Format on one line with no line break:
Parameters
out output stream
species Species to be written to stream
Returns
modified output stream
Definition at line 182 of file mdCf/chemistry/Species.cpp.
The documentation for this class was generated from the following files:
mdCf/chemistry/Species.h
mdCf/chemistry/Species.cpp