Simpatico: Util::AutoCorrArray< Data, Product > Class Template Reference
Util::AutoCorrArray< Data, Product > Class Template Reference
Util namespace » Accumulators
Detailed Description
template<typename Data, typename Product>
class Util::AutoCorrArray< Data, Product >
Auto-correlation function for an ensemble of sequences.
This class calculates an autocorrelation function for a ensemble of statistically equivalent sequences x(i) of values of a variable of type Data. The resulting autocorrelation function is an array of values of type Product, where C(j) = <x(i-j), x(i)>. Here <A,B> denotes an inner product of type Product for objects A and B of type Data.
The meaning of <A,B> for two Data values is defined for various data types by the overloaded functions product(Data, Data) defined in file "product.h" . These functions define a product as an arithmetic product for floating point numbers, and use the following definitions for complex numbers and Vector objects:
double  product(double, double)   = A*B
complex product(complex, complex) = conjug(A)*B
double  product(Vector,  Vector)  = A.dot(B)
The meaning of setting a variable to zero is defined for various types of data by the overloaded functions setToZero(Data&) that are defined in file setToZero.h.
Definition at line 57 of file AutoCorrArray.h.
#include <AutoCorrArray.h>
Public Member Functions
AutoCorrArray ()
Default constructor.
~AutoCorrArray ()
Default destructor.
virtual void readParameters (std::istream &in)
Read parameters, allocate memory and clear history.
void setParam (int ensembleCapacity, int bufferCapacity)
Allocate memory, and clear history.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void setNEnsemble (int nEnsemble)
Set actual number of sequences in ensemble.
void clear ()
Reset to empty state.
void sample (const Array< Data > &values)
Sample an array of current values.
void output (std::ostream &out)
Output the autocorrelation function.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this AutoCorrArray to/from an archive.
int bufferCapacity () const
Return maximum number of samples in history for each sequence.
int nEnsemble () const
Return nEnsemble.
int nSample () const
Return the total number of samples per sequence thus far.
Data average () const
Return average of sampled values.
double corrTime () const
Numerical integral of autocorrelation function.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Constructor & Destructor Documentation
template<typename Data , typename Product > Util::AutoCorrArray< Data, Product >::AutoCorrArray ()
Default constructor.
Definition at line 205 of file AutoCorrArray.h.
References Util::ParamComposite::setClassName(), and Util::setToZero().
template<typename Data , typename Product > Util::AutoCorrArray< Data, Product >::~AutoCorrArray ()
Default destructor.
Definition at line 222 of file AutoCorrArray.h.
Member Function Documentation
template<typename Data , typename Product > void Util::AutoCorrArray< Data, Product >::readParameters (std::istream & in) virtual
Read parameters, allocate memory and clear history.
Reads parameters ensembleCapacity and bufferCapacity, allocates memory, sets nEnsemble=ensembleCapacity, and calls clear().
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 229 of file AutoCorrArray.h.
template<typename Data , typename Product > void Util::AutoCorrArray< Data, Product >::setParam (int ensembleCapacity, int bufferCapacity)
Allocate memory, and clear history.
Sets parameters ensembleCapacity and bufferCapacity, allocates memory, sets nEnsemble=ensembleCapacity, and calls clear().
Parameters
ensembleCapacity maximum number of sequences in ensemble
bufferCapacity maximum number of values in each history
Definition at line 241 of file AutoCorrArray.h.
References Util::AutoCorrArray< Data, Product >::bufferCapacity().
template<typename Data , typename Product > void Util::AutoCorrArray< Data, Product >::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 253 of file AutoCorrArray.h.
template<typename Data , typename Product > void Util::AutoCorrArray< Data, Product >::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 269 of file AutoCorrArray.h.
template<typename Data , typename Product > void Util::AutoCorrArray< Data, Product >::setNEnsemble (int nEnsemble)
Set actual number of sequences in ensemble.
Precondition
readParam() or setParam() must have been called previously
nEnsemble <= ensembleCapacity
Parameters
nEnsemble actual number of sequences in ensemble
Definition at line 276 of file AutoCorrArray.h.
References Util::AutoCorrArray< Data, Product >::nEnsemble(), and UTIL_THROW.
template<typename Data , typename Product > void Util::AutoCorrArray< Data, Product >::clear ()
Reset to empty state.
Definition at line 291 of file AutoCorrArray.h.
References Util::DArray< Data >::allocate(), and Util::setToZero().
template<typename Data, typename Product > void Util::AutoCorrArray< Data, Product >::sample (const Array< Data > & values)
Sample an array of current values.
Parameters
values Array of current values
Definition at line 331 of file AutoCorrArray.h.
References Util::product().
template<typename Data , typename Product > void Util::AutoCorrArray< Data, Product >::output (std::ostream & out)
Output the autocorrelation function.
Definition at line 386 of file AutoCorrArray.h.
template<typename Data , typename Product > template<class Archive > void Util::AutoCorrArray< Data, Product >::serialize (Archive & ar, const unsigned int version)
Serialize this AutoCorrArray to/from an archive.
Parameters
ar input or output archive
version file version id
Definition at line 436 of file AutoCorrArray.h.
template<typename Data , typename Product > int Util::AutoCorrArray< Data, Product >::bufferCapacity () const
Return maximum number of samples in history for each sequence.
Definition at line 354 of file AutoCorrArray.h.
Referenced by Util::AutoCorrArray< Data, Product >::setParam().
template<typename Data , typename Product > int Util::AutoCorrArray< Data, Product >::nEnsemble () const
Return nEnsemble.
Definition at line 361 of file AutoCorrArray.h.
Referenced by Util::AutoCorrArray< Data, Product >::setNEnsemble().
template<typename Data , typename Product > int Util::AutoCorrArray< Data, Product >::nSample () const
Return the total number of samples per sequence thus far.
Definition at line 368 of file AutoCorrArray.h.
template<typename Data , typename Product > Data Util::AutoCorrArray< Data, Product >::average () const
Return average of sampled values.
Definition at line 375 of file AutoCorrArray.h.
template<typename Data , typename Product > double Util::AutoCorrArray< Data, Product >::corrTime () const
Numerical integral of autocorrelation function.
Definition at line 407 of file AutoCorrArray.h.
References Util::product(), and Util::setToZero().
The documentation for this class was generated from the following file:
AutoCorrArray.h