Simpatico: McMd::McConfigIo Class Reference
McMd::McConfigIo Class Reference
McMd namespace » Configuration File IO
Detailed Description
ConfigIo for MC simulations (no atom velocities).
Definition at line 29 of file McConfigIo.h.
#include <McConfigIo.h>
Public Member Functions
McConfigIo (System &system)
Constructor.
virtual ~McConfigIo ()
Destructor.
Public Member Functions inherited from McMd::McMdConfigIo
McMdConfigIo (System &system)
Constructor.
virtual ~McMdConfigIo ()
Destructor.
virtual void read (std::istream &in)
Read configuration (particle positions) from file.
virtual void write (std::ostream &out)
Write configuration (particle positions) to file.
Public Member Functions inherited from McMd::ConfigIo
ConfigIo (System &system)
Constructor.
virtual ~ConfigIo ()
Destructor.
Protected Member Functions
virtual void readAtom (std::istream &out, Atom &atom)
Read data for one atom.
virtual void writeAtom (std::ostream &out, const Atom &atom)
Write data for one atom.
Protected Member Functions inherited from McMd::ConfigIo
System & system () const
Get a reference to the parent System.
Simulation & simulation () const
Get a reference to the parent Simulation.
Boundary & boundary () const
Get the Boundary.
Constructor & Destructor Documentation
McMd::McConfigIo::McConfigIo (System & system)
Constructor.
Definition at line 19 of file McConfigIo.cpp.
McMd::McConfigIo::~McConfigIo () virtual
Destructor.
Definition at line 26 of file McConfigIo.cpp.
Member Function Documentation
void McMd::McConfigIo::readAtom (std::istream & out, Atom & atom) protected virtual
Read data for one atom.
Implements McMd::McMdConfigIo.
Definition at line 32 of file McConfigIo.cpp.
References McMd::ConfigIo::boundary(), McMd::Atom::position(), and Util::OrthorhombicBoundary::shift().
void McMd::McConfigIo::writeAtom (std::ostream & out, const Atom & atom) protected virtual
Write data for one atom.
Implements McMd::McMdConfigIo.
Definition at line 41 of file McConfigIo.cpp.
References McMd::Atom::position().
The documentation for this class was generated from the following files:
McConfigIo.h
McConfigIo.cpp