Simpatico: Tools::HoomdConfigReader Class Reference
Tools::HoomdConfigReader Class Reference
Config File Readers
Detailed Description
Reader for Hoomd-blue XML configuration files.
Definition at line 33 of file HoomdConfigReader.h.
#include <HoomdConfigReader.h>
Public Member Functions
HoomdConfigReader ()
Default constructor.
HoomdConfigReader (Configuration &configuration)
Constructor.
virtual void readConfig (std::ifstream &file)
Read configuration file in DdMd default format.
virtual void readAuxiliaryFile (std::ifstream &file)
Read auxiliary file with type map information.
Constructor & Destructor Documentation
Tools::HoomdConfigReader::HoomdConfigReader ()
Default constructor.
Tools::HoomdConfigReader::HoomdConfigReader (Configuration & configuration)
Constructor.
Parameters:
configuration parent Configuration object.
Definition at line 31 of file HoomdConfigReader.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void Tools::HoomdConfigReader::readConfig (std::ifstream & file) [virtual]
Read configuration file in DdMd default format.
Parameters:
file input file stream
Implements Tools::ConfigReader.
Definition at line 71 of file HoomdConfigReader.cpp.
References Tools::ConfigReader::addAtomsToSpecies(), Tools::Configuration::angles(), Tools::Configuration::bonds(), Tools::ConfigReader::configuration(), Tools::Configuration::dihedrals(), Util::Log::file(), Util::XmlStartTag::finish(), Util::getNextLine(), Tools::Configuration::impropers(), Util::XmlAttribute::label(), Util::XmlEndTag::label(), Util::XmlStartTag::label(), Util::XmlEndTag::match(), Util::XmlXmlTag::match(), Util::XmlStartTag::matchAttribute(), Util::XmlStartTag::matchLabel(), Tools::ConfigReader::setAtomContexts(), UTIL_THROW, and Util::XmlAttribute::value().
void Tools::HoomdConfigReader::readAuxiliaryFile (std::ifstream & file) [virtual]
Read auxiliary file with type map information.
Parameters:
file input file stream
Reimplemented from Tools::ConfigReader.
Definition at line 39 of file HoomdConfigReader.cpp.
References Util::checkString(), Util::getNextLine(), and Tools::TypeMap::read().
The documentation for this class was generated from the following files:
HoomdConfigReader.h
HoomdConfigReader.cpp