Simpatico: DdMd::SerializeConfigIo Class Reference
DdMd::SerializeConfigIo Class Reference
ConfigIos
Detailed Description
Save / load configuration from / to an archive.
The virtual functions readConfig and writeConfig, which take file objects parameters, read from or write to files that stores archives of type Serializable::IArchive or Serializable::OArchive. The loadConfig and saveConfig methods take archive object arguments.
Definition at line 31 of file SerializeConfigIo.h.
#include <SerializeConfigIo.h>
Public Member Functions
SerializeConfigIo ()
Default constructor.
SerializeConfigIo (Simulation &simulation)
Constructor.
virtual void readConfig (std::ifstream &file, MaskPolicy maskPolicy)
Read configuration file.
virtual void writeConfig (std::ofstream &file)
Write configuration file.
void loadConfig (Serializable::IArchive &ar, MaskPolicy maskPolicy)
Load configuration from an archive.
void saveConfig (Serializable::OArchive &ar)
Save configuration.
Constructor & Destructor Documentation
DdMd::SerializeConfigIo::SerializeConfigIo ()
Default constructor.
Definition at line 44 of file SerializeConfigIo.cpp.
References Util::ParamComposite::setClassName().
DdMd::SerializeConfigIo::SerializeConfigIo (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object.
Definition at line 51 of file SerializeConfigIo.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void DdMd::SerializeConfigIo::readConfig (std::ifstream & file, MaskPolicy maskPolicy) [virtual]
Read configuration file.
Call on all processors, but reads from file only on master.
This function opens and reads a file on the master, and distributes atom data among the processors. This calls loadConfig() internally, and thus has all the preconditions of loadConfig().
Parameters:
file input file stream (must be open on master)
maskPolicy MaskPolicy to be used in setting atom masks
Implements DdMd::ConfigIo.
Definition at line 295 of file SerializeConfigIo.cpp.
References DdMd::ConfigIo::domain(), loadConfig(), and UTIL_THROW.
void DdMd::SerializeConfigIo::writeConfig (std::ofstream & file) [virtual]
Write configuration file.
Call on all processors, but file must be open only on master.
This function opens and writes a file on the master, collecting atom data from all processors. It calls saveConfig() internally.
Parameters:
file output file stream (must be open on master)
Implements DdMd::ConfigIo.
Definition at line 310 of file SerializeConfigIo.cpp.
References DdMd::ConfigIo::domain(), saveConfig(), and UTIL_THROW.
void DdMd::SerializeConfigIo::loadConfig (Serializable::IArchive & ar, MaskPolicy maskPolicy)
Load configuration from an archive.
Call on all processors, but save from archive only on master.
Precondition:
There are no atoms, ghosts, or groups.
AtomStorage is set for scaled / generalized coordinates
Postcondition:
atomic coordinates are scaled / generalized
there are no ghosts
Parameters:
ar input archive
maskPolicy MaskPolicy to be used in setting atom masks
Definition at line 84 of file SerializeConfigIo.cpp.
References DdMd::AtomDistributor::addAtom(), DdMd::ConfigIo::angleDistributor(), DdMd::ConfigIo::angleStorage(), DdMd::ConfigIo::atomDistributor(), DdMd::AtomContext::atomId, DdMd::ConfigIo::atomStorage(), Util::bcast(), DdMd::ConfigIo::bondDistributor(), DdMd::ConfigIo::bondStorage(), DdMd::ConfigIo::boundary(), DdMd::Atom::context(), DdMd::ConfigIo::dihedralDistributor(), DdMd::ConfigIo::dihedralStorage(), DdMd::ConfigIo::domain(), DdMd::Atom::groups(), DdMd::Atom::hasAtomContext(), DdMd::GroupStorage< N >::isValid(), DdMd::AtomContext::moleculeId, DdMd::AtomDistributor::newAtomPtr(), DdMd::Atom::position(), DdMd::AtomDistributor::receive(), DdMd::AtomDistributor::send(), DdMd::ConfigIo::setAtomMasks(), DdMd::Atom::setId(), DdMd::Atom::setTypeId(), DdMd::AtomDistributor::setup(), DdMd::AtomContext::speciesId, DdMd::AtomStorage::totalAtomCapacity(), Util::OrthorhombicBoundary::transformCartToGen(), UTIL_THROW, DdMd::AtomDistributor::validate(), and DdMd::Atom::velocity().
Referenced by readConfig().
void DdMd::SerializeConfigIo::saveConfig (Serializable::OArchive & ar)
Save configuration.
Call on all processors, but uses archive only on master.
This function allows the AtomStorage to be set for either generalized or Cartesian coordinates, but always saves Cartesian atom coordinates to the archive. In either case, it does not modify any Atom position values, or change the coordinates system setting of the AtomStorage.
Usage: Atomic coordinates are Cartesian on input and output when this function is used by an Integrator to write a restart file, but are scaled / generalized on input and ouput when it is called by writeConfig() to implement the WRITE_CONFIG command within the Simulation::readCommand() function.
Parameters:
ar output archive
Definition at line 227 of file SerializeConfigIo.cpp.
References DdMd::ConfigIo::angleCollector(), DdMd::ConfigIo::angleStorage(), DdMd::ConfigIo::atomCollector(), DdMd::AtomContext::atomId, DdMd::ConfigIo::atomStorage(), DdMd::ConfigIo::bondCollector(), DdMd::ConfigIo::bondStorage(), DdMd::ConfigIo::boundary(), DdMd::GroupStorage< N >::capacity(), DdMd::AtomStorage::computeNAtomTotal(), DdMd::Atom::context(), DdMd::ConfigIo::dihedralCollector(), DdMd::ConfigIo::dihedralStorage(), DdMd::ConfigIo::domain(), DdMd::Atom::groups(), DdMd::Atom::hasAtomContext(), DdMd::Atom::id(), DdMd::AtomStorage::isCartesian(), DdMd::AtomContext::moleculeId, DdMd::AtomStorage::nAtomTotal(), DdMd::AtomCollector::nextPtr(), DdMd::Atom::position(), DdMd::AtomCollector::send(), DdMd::AtomCollector::setup(), DdMd::AtomContext::speciesId, Util::OrthorhombicBoundary::transformGenToCart(), DdMd::Atom::typeId(), and DdMd::Atom::velocity().
Referenced by writeConfig().
The documentation for this class was generated from the following files:
SerializeConfigIo.h
SerializeConfigIo.cpp