Simpatico: McMd::StructureFactorP Class Reference
McMd::StructureFactorP Class Reference
McMd namespace » Analyzers » MC/MD Analyzers
Detailed Description
StructureFactorP evaluates partial structure factors in Fourier space.
A partial structure factor for a wavevector k defined as an expectation value
where, V is system volume, and is a Fourier component
in which the sum is taken over all particles in a set defined by the particle type index a.
If 0 <= a < nAtomType, then, is given by a sum over all atoms of type a.
If a < 0, then is given by a sum over all atoms, of all types. By convention, we use a= -1 to indicate this.
This class can evaluate multiple types of structures factors, corresponding to different choices for the type pair ab, for multiple wavevectors. The input format thus requires the user to specify one or more atom typeId pairs, and one or more wavevectors. Each wavevector is specified as an IntVector containing integer Miller indices. These are the coeficients in an expansion of a reciprocal lattice wavevector in terms of recprocal lattice basis vectors for the periodic unit cell.
In a system with nAtomType = 2, with two monomer types 0 and 1, the parameter file input for calculating the total, 00 and 01 correlation functions for 5 wavevectors along the x axis in an orthorhombic unit cell might look like this:
StructureFactorP{
   interval                     1000
   outputFileName     StructureFactorP
   nAtomTypeIdPair                  3
   atomTypeIdPairs          -1     -1
                             0      0
                             0      1
   nWave                            5
   waveIntVectors     8      0      0
                      9      0      0
                     10      0      0
                     11      0      0
                     12      0      0
}
At the end of a simulation, all of the structure factors are output in a file with a suffix *.dat. Each line in this file contains the 3 Miller indices of a wavevector, the absolute magnitude of the wavevector, and a list of nAtomTypeIdPair structure factor values for the wavevector, one for each atomTypeId pair.
See also
parameter file format
Definition at line 89 of file StructureFactorP.h.
#include <StructureFactorP.h>
Public Member Functions
StructureFactorP (System &system)
Constructor.
~StructureFactorP ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Clear accumulators.
void sample (long iStep)
Add particle pairs to StructureFactorP histogram.
virtual void output ()
Output results to predefined output file.
Public Member Functions inherited from McMd::SystemAnalyzer< System >
SystemAnalyzer (System &system)
Constructor.
virtual ~SystemAnalyzer ()
Destructor.
Public Member Functions inherited from McMd::Analyzer
Analyzer ()
Default constructor.
virtual ~Analyzer ()
Destructor.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
void makeWaveVectors ()
Update wavevectors.
Protected Member Functions inherited from McMd::SystemAnalyzer< System >
System & system ()
Return reference to parent system.
Protected Member Functions inherited from McMd::Analyzer
void setFileMaster (FileMaster &fileMaster)
Set the FileMaster to use to open files.
void readInterval (std::istream &in)
Read interval from file, with error checking.
void readOutputFileName (std::istream &in)
Read outputFileName from file.
void loadInterval (Serializable::IArchive &ar)
Load interval from archive, with error checking.
void loadOutputFileName (Serializable::IArchive &ar)
Load output file name from archive.
FileMaster & fileMaster ()
Get the FileMaster by reference.
const std::string & outputFileName () const
Return outputFileName string.
std::string outputFileName (const std::string &suffix) const
Return outputFileName string with added suffix.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
std::ofstream outputFile_
Output file stream.
DMatrix< double > structureFactors_
Structure factor accumulators.
DArray< IntVector > waveIntVectors_
Array of miller index IntVectors for wavevectors.
DArray< Vector > waveVectors_
Array of wave vectors (temporary)
DArray< Pair< int > > atomTypeIdPairs_
Array of atom type indices (-1 indicates a sum of all types)
int nWave_
Number of wavevectors.
int nAtomTypeIdPair_
Number of selected atom type pairs.
int nSample_
Number of samples thus far.
int nAtomType_
Number of atom types, copied from Simulation::nAtomType().
bool isInitialized_
Has readParam been called?
Protected Attributes inherited from McMd::Analyzer
std::string outputFileName_
Base name of output file(s).
long interval_
Number of simulation steps between subsequent actions.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from McMd::Analyzer
static void initStatic ()
Define and initialize baseInterval.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Public Attributes inherited from McMd::Analyzer
static long baseInterval = 1
The interval for an Analyzer must be a multiple of baseInterval.
Constructor & Destructor Documentation
McMd::StructureFactorP::StructureFactorP (System & system)
Constructor.
Parameters
system reference to parent System object
Definition at line 29 of file StructureFactorP.cpp.
References Util::ParamComposite::setClassName().
McMd::StructureFactorP::~StructureFactorP ()
Destructor.
Definition at line 36 of file StructureFactorP.cpp.
Member Function Documentation
void McMd::StructureFactorP::readParameters (std::istream & in) virtual
Read parameters from file.
Input format:
int interval sampling interval
string outputFileName output file base name
int nAtomTypeIdPair number of Atom typeId pairs
DArray<Pair<int>> atomTypeIdPairs integer typeId pairs
int nWave number of wavevectors
DArray<IntVector> waveIntVectors IntVector wavevectors
Parameters
in input parameter stream
Reimplemented from McMd::Analyzer.
Reimplemented in McMd::StructureFactorPGrid.
Definition at line 42 of file StructureFactorP.cpp.
References Util::DMatrix< Data >::allocate(), atomTypeIdPairs_, isInitialized_, McMd::Simulation::nAtomType(), nAtomType_, nAtomTypeIdPair_, nWave_, McMd::Analyzer::readInterval(), McMd::Analyzer::readOutputFileName(), McMd::System::simulation(), structureFactors_, McMd::SystemAnalyzer< System >::system(), waveIntVectors_, and waveVectors_.
void McMd::StructureFactorP::loadParameters (Serializable::IArchive & ar) virtual
Load state from an archive.
Parameters
ar loading (input) archive.
Reimplemented from McMd::Analyzer.
Reimplemented in McMd::StructureFactorPGrid.
Definition at line 68 of file StructureFactorP.cpp.
References Util::DMatrix< Data >::allocate(), atomTypeIdPairs_, isInitialized_, McMd::Analyzer::loadParameters(), McMd::Simulation::nAtomType(), nAtomType_, nAtomTypeIdPair_, nSample_, nWave_, McMd::System::simulation(), structureFactors_, McMd::SystemAnalyzer< System >::system(), UTIL_THROW, waveIntVectors_, and waveVectors_.
void McMd::StructureFactorP::save (Serializable::OArchive & ar) virtual
Save state to an archive.
Parameters
ar saving (output) archive.
Reimplemented from McMd::Analyzer.
Reimplemented in McMd::StructureFactorPGrid.
Definition at line 107 of file StructureFactorP.cpp.
template<class Archive > void McMd::StructureFactorP::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters
ar archive
version archive version id
Definition at line 217 of file StructureFactorP.h.
References McMd::Analyzer::serialize().
Referenced by McMd::StructureFactorPGrid::serialize().
void McMd::StructureFactorP::setup () virtual
Clear accumulators.
Reimplemented from McMd::Analyzer.
Reimplemented in McMd::StructureFactorPGrid.
Definition at line 113 of file StructureFactorP.cpp.
References isInitialized_, nAtomTypeIdPair_, nSample_, nWave_, structureFactors_, and UTIL_THROW.
void McMd::StructureFactorP::sample (long iStep) virtual
Add particle pairs to StructureFactorP histogram.
Increment Structure Factor.
Parameters
iStep step counter
Implements McMd::Analyzer.
Definition at line 132 of file StructureFactorP.cpp.
References atomTypeIdPairs_, McMd::System::begin(), McMd::System::boundary(), Util::Vector::dot(), Util::Constants::Im, McMd::Analyzer::isAtInterval(), makeWaveVectors(), nAtomType_, nAtomTypeIdPair_, Util::ConstArrayIterator< Data >::notEnd(), Util::ConstPArrayIterator< Data >::notEnd(), nSample_, McMd::Simulation::nSpecies(), nWave_, Util::product(), McMd::System::simulation(), structureFactors_, McMd::SystemAnalyzer< System >::system(), Util::OrthorhombicBoundary::volume(), and waveVectors_.
void McMd::StructureFactorP::output () virtual
Output results to predefined output file.
Reimplemented from McMd::Analyzer.
Reimplemented in McMd::StructureFactorPGrid.
Definition at line 223 of file StructureFactorP.cpp.
References atomTypeIdPairs_, Util::Dimension, McMd::Analyzer::fileMaster(), nAtomTypeIdPair_, nSample_, nWave_, Util::FileMaster::openOutputFile(), outputFile_, McMd::Analyzer::outputFileName(), structureFactors_, Util::toString(), waveIntVectors_, waveVectors_, and Util::ParamComposite::writeParam().
void McMd::StructureFactorP::makeWaveVectors () protected
Update wavevectors.
Calculate floating point wavevectors.
Definition at line 205 of file StructureFactorP.cpp.
References McMd::System::boundary(), Util::Dimension, nWave_, Util::OrthorhombicBoundary::reciprocalBasisVector(), McMd::SystemAnalyzer< System >::system(), waveIntVectors_, waveVectors_, and Util::Vector::Zero.
Referenced by sample().
Member Data Documentation
std::ofstream McMd::StructureFactorP::outputFile_ protected
Output file stream.
Definition at line 166 of file StructureFactorP.h.
Referenced by McMd::StructureFactorPGrid::output(), and output().
DMatrix<double> McMd::StructureFactorP::structureFactors_ protected
Structure factor accumulators.
First index is wavevector, second index is atom typeId pair.
Definition at line 173 of file StructureFactorP.h.
Referenced by McMd::StructureFactorPGrid::loadParameters(), loadParameters(), McMd::StructureFactorPGrid::output(), output(), McMd::StructureFactorPGrid::readParameters(), readParameters(), sample(), and setup().
DArray<IntVector> McMd::StructureFactorP::waveIntVectors_ protected
Array of miller index IntVectors for wavevectors.
Definition at line 183 of file StructureFactorP.h.
Referenced by McMd::StructureFactorPGrid::loadParameters(), loadParameters(), makeWaveVectors(), McMd::StructureFactorPGrid::output(), output(), McMd::StructureFactorPGrid::readParameters(), readParameters(), and McMd::StructureFactorPGrid::save().
DArray<Vector> McMd::StructureFactorP::waveVectors_ protected
Array of wave vectors (temporary)
Definition at line 186 of file StructureFactorP.h.
Referenced by McMd::StructureFactorPGrid::loadParameters(), loadParameters(), makeWaveVectors(), McMd::StructureFactorPGrid::output(), output(), McMd::StructureFactorPGrid::readParameters(), readParameters(), and sample().
DArray< Pair<int> > McMd::StructureFactorP::atomTypeIdPairs_ protected
Array of atom type indices (-1 indicates a sum of all types)
Definition at line 189 of file StructureFactorP.h.
Referenced by McMd::StructureFactorPGrid::loadParameters(), loadParameters(), McMd::StructureFactorPGrid::output(), output(), McMd::StructureFactorPGrid::readParameters(), readParameters(), and sample().
int McMd::StructureFactorP::nWave_ protected
Number of wavevectors.
Definition at line 192 of file StructureFactorP.h.
Referenced by McMd::StructureFactorPGrid::loadParameters(), loadParameters(), makeWaveVectors(), output(), McMd::StructureFactorPGrid::readParameters(), readParameters(), sample(), McMd::StructureFactorPGrid::save(), and setup().
int McMd::StructureFactorP::nAtomTypeIdPair_ protected
Number of selected atom type pairs.
Definition at line 195 of file StructureFactorP.h.
Referenced by McMd::StructureFactorPGrid::loadParameters(), loadParameters(), McMd::StructureFactorPGrid::output(), output(), McMd::StructureFactorPGrid::readParameters(), readParameters(), sample(), and setup().
int McMd::StructureFactorP::nSample_ protected
Number of samples thus far.
Definition at line 198 of file StructureFactorP.h.
Referenced by McMd::StructureFactorPGrid::loadParameters(), loadParameters(), McMd::StructureFactorPGrid::output(), output(), McMd::StructureFactorPGrid::readParameters(), sample(), and setup().
int McMd::StructureFactorP::nAtomType_ protected
Number of atom types, copied from Simulation::nAtomType().
Definition at line 201 of file StructureFactorP.h.
Referenced by McMd::StructureFactorPGrid::loadParameters(), loadParameters(), McMd::StructureFactorPGrid::readParameters(), readParameters(), and sample().
bool McMd::StructureFactorP::isInitialized_ protected
Has readParam been called?
Definition at line 204 of file StructureFactorP.h.
Referenced by loadParameters(), readParameters(), and setup().
The documentation for this class was generated from the following files:
StructureFactorP.h
StructureFactorP.cpp