Simpatico: Tools::AnalyzerManager Class Reference
Tools::AnalyzerManager Class Reference
Analyzers
Detailed Description
Manager for a list of Analyzer objects.
Definition at line 24 of file tools/analyzers/AnalyzerManager.h.
#include <AnalyzerManager.h>
Public Member Functions
AnalyzerManager ()
Constructor.
virtual ~AnalyzerManager ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameter block (without begin and end).
void setup ()
Call setup method of each Analyzer.
void clear ()
Call clear method of each Analyzer.
void sample (long iStep)
Call sample method of each Analyzer, if scheduled.
void output ()
Call output method of each analyzer.
Constructor & Destructor Documentation
Tools::AnalyzerManager::AnalyzerManager ()
Constructor.
Definition at line 18 of file tools/analyzers/AnalyzerManager.cpp.
References Util::ParamComposite::setClassName().
Tools::AnalyzerManager::~AnalyzerManager () [virtual]
Destructor.
Definition at line 25 of file tools/analyzers/AnalyzerManager.cpp.
Member Function Documentation
void Tools::AnalyzerManager::readParameters (std::istream & in) [virtual]
Read parameter block (without begin and end).
Parameters:
in input parameter file stream.
Reimplemented from Util::Manager< Analyzer >.
Definition at line 33 of file tools/analyzers/AnalyzerManager.cpp.
void Tools::AnalyzerManager::setup ()
Call setup method of each Analyzer.
Definition at line 41 of file tools/analyzers/AnalyzerManager.cpp.
References Util::Manager< Analyzer >::size().
Referenced by Tools::Processor::analyzeConfigs(), and Tools::Processor::analyzeTrajectory().
void Tools::AnalyzerManager::clear ()
Call clear method of each Analyzer.
Definition at line 51 of file tools/analyzers/AnalyzerManager.cpp.
References Util::Manager< Analyzer >::size().
void Tools::AnalyzerManager::sample (long iStep)
Call sample method of each Analyzer, if scheduled.
Calls sample methods of each analyzer only if iStep is a multiple of the analyzer interval
Parameters:
iStep time step counter
Definition at line 61 of file tools/analyzers/AnalyzerManager.cpp.
References Util::Manager< Analyzer >::size().
Referenced by Tools::Processor::analyzeConfigs(), and Tools::Processor::analyzeTrajectory().
void Tools::AnalyzerManager::output ()
Call output method of each analyzer.
Definition at line 73 of file tools/analyzers/AnalyzerManager.cpp.
References Util::Manager< Analyzer >::size().
Referenced by Tools::Processor::analyzeConfigs(), and Tools::Processor::analyzeTrajectory().
The documentation for this class was generated from the following files:
tools/analyzers/AnalyzerManager.h
tools/analyzers/AnalyzerManager.cpp