Simpatico: Util::Array< Data > Class Template Reference
Util::Array< Data > Class Template Reference
Util namespace » Container Templates » Object Arrays
Detailed Description
template<typename Data>
class Util::Array< Data >
Array container class template.
An Array is a sequence that supports random access via an overloaded operator [], and that wraps a dynamically allocated C array.
Array is a base class for DArray, which is dynamically allocated, and RArray, which acts as a reference to another DArray or FSArray.
When compiled in debug mode (i.e., when NDEBUG is not defined) the subscript operator [] checks the validity of the element index.
Definition at line 28 of file AutoCorrArray.h.
#include <Array.h>
Public Member Functions
virtual ~Array ()
Destructor.
int capacity () const
Return allocated size.
void begin (ArrayIterator< Data > &iterator)
Set an iterator to begin this Array.
void begin (ConstArrayIterator< Data > &iterator) const
Set a const iterator to begin this Array.
Data & operator[] (int i)
Get an element by non-const reference.
const Data & operator[] (int i) const
Get an element by const reference.
Data * cArray ()
Return pointer to underlying C array.
const Data * cArray () const
Return pointer to const to underlying C array.
Protected Member Functions
Array ()
Default constructor.
Protected Attributes
Data * data_
Pointer to an array of Data elements.
int capacity_
Allocated size of the data_ array.
Constructor & Destructor Documentation
template<typename Data > Util::Array< Data >::~Array () virtual
Destructor.
Definition at line 146 of file Array.h.
template<typename Data > Util::Array< Data >::Array () protected
Default constructor.
Protected to prevent direct instantiation.
Definition at line 137 of file Array.h.
Member Function Documentation
template<typename Data > int Util::Array< Data >::capacity () const inline
Return allocated size.
Returns
Number of elements allocated in array.
Definition at line 153 of file Array.h.
References Util::Array< Data >::capacity_.
Referenced by Util::DRaggedMatrix< Data >::allocate(), Util::DArray< Data >::allocate(), Util::ArraySet< Data >::allocate(), Util::AutoCorrStage< Data, Product >::allocate(), Util::RArray< DdMd::AtomType >::associate(), Tools::CellList::atomCapacity(), DdMd::CellList::atomCapacity(), Util::bcast(), Util::AutoCorr< Data, Product >::clear(), Util::Distribution::Distribution(), Simp::Species::initializeAtomGroupIdArrays(), Util::IntDistribution::IntDistribution(), Tools::CellList::isValid(), Simp::Species::isValid(), DdMd::CellList::isValid(), DdMd::AtomCollector::nextPtr(), Util::IntDistribution::operator=(), Util::Distribution::operator=(), Util::DArray< Data >::operator=(), Util::Polynomial< T >::Polynomial(), Util::DArrayParam< Type >::readValue(), Util::recv(), Util::DArrayParam< Type >::saveValue(), Util::send(), Util::DArray< Data >::serialize(), DdMd::AtomCollector::setCapacity(), DdMd::AtomDistributor::setCapacity(), McMd::NveVvIntegrator::setup(), DdMd::NvtIntegrator::setup(), DdMd::NveIntegrator::setup(), DdMd::NphIntegrator::setup(), DdMd::NptIntegrator::setup(), McMd::NvtLangevinIntegrator::setup(), DdMd::NvtLangevinIntegrator::setup(), McMd::NphIntegrator::setup(), DdMd::AtomCollector::setup(), McMd::Generator::setupCellList(), and Util::DArrayParam< Type >::writeParam().
template<typename Data> void Util::Array< Data >::begin (ArrayIterator< Data > & iterator) inline
Set an iterator to begin this Array.
Parameters
iterator ArrayIterator, initialized on output.
Definition at line 160 of file Array.h.
References Util::Array< Data >::capacity_, Util::Array< Data >::data_, Util::ArrayIterator< Data >::setCurrent(), and Util::ArrayIterator< Data >::setEnd().
template<typename Data> void Util::Array< Data >::begin (ConstArrayIterator< Data > & iterator) const inline
Set a const iterator to begin this Array.
Parameters
iterator ConstArrayIterator, initialized on output.
Definition at line 172 of file Array.h.
References Util::Array< Data >::capacity_, Util::Array< Data >::data_, Util::ConstArrayIterator< Data >::setCurrent(), and Util::ConstArrayIterator< Data >::setEnd().
template<typename Data > Data & Util::Array< Data >::operator[] (int i) inline
Get an element by non-const reference.
Mimic C-array subscripting.
Parameters
i array index
Returns
non-const reference to element i
Definition at line 184 of file Array.h.
References Util::Array< Data >::capacity_, and Util::Array< Data >::data_.
template<typename Data > const Data & Util::Array< Data >::operator[] (int i) const inline
Get an element by const reference.
Mimics C-array subscripting.
Parameters
i array index
Returns
const reference to element i
Definition at line 196 of file Array.h.
References Util::Array< Data >::capacity_, and Util::Array< Data >::data_.
template<typename Data > Data * Util::Array< Data >::cArray () inline
Return pointer to underlying C array.
Definition at line 208 of file Array.h.
References Util::Array< Data >::data_.
Referenced by McMd::DCDTrajectoryReader::readFrame(), and Util::Distribution::reduce().
template<typename Data > const Data * Util::Array< Data >::cArray () const inline
Return pointer to const to underlying C array.
Definition at line 215 of file Array.h.
References Util::Array< Data >::data_.
Member Data Documentation
template<typename Data> Data* Util::Array< Data >::data_ protected
Pointer to an array of Data elements.
Definition at line 103 of file Array.h.
Referenced by Util::DArray< Data >::allocate(), Util::RArray< DdMd::AtomType >::associate(), Util::Array< Data >::begin(), Util::Array< Data >::cArray(), Util::DArray< Data >::DArray(), Util::DArray< Data >::deallocate(), Util::DArray< Data >::isAllocated(), Util::DArray< Data >::operator=(), Util::Array< Data >::operator[](), Util::RArray< DdMd::AtomType >::RArray(), Util::DArray< Data >::serialize(), and Util::DArray< Data >::~DArray().
template<typename Data> int Util::Array< Data >::capacity_ protected
Allocated size of the data_ array.
Definition at line 106 of file Array.h.
Referenced by Util::DArray< Data >::allocate(), Util::RArray< DdMd::AtomType >::associate(), Util::Array< Data >::begin(), Util::Array< Data >::capacity(), Util::DArray< Data >::DArray(), Util::DArray< Data >::deallocate(), Util::DArray< Data >::operator=(), Util::Array< Data >::operator[](), Util::RArray< DdMd::AtomType >::RArray(), Util::DArray< Data >::serialize(), and Util::DArray< Data >::~DArray().
The documentation for this class was generated from the following files:
AutoCorrArray.h
Array.h