Simpatico: Util::Timer Class Reference
Util::Timer Class Reference
Utilities
Detailed Description
Wall clock timer.
A Timer keeps track of the time elapsed during one or more interval. Each interval begins when start() is called and ends when stop() is called. If start() and stop() are invoked repeatedly, the timer accumulates the time elapses in multiple intervals. The accumulated time is returned by the time() method, and can be reset to zero by the clear() method.
Definition at line 30 of file Timer.h.
#include <Timer.h>
Public Member Functions
Timer ()
Constructor.
void start ()
Start the clock.
void stop ()
Stop the clock, increment time.
void clear ()
Set accumulated time to zero.
double time ()
Get the accumulated time, in seconds.
bool isRunning ()
Is the timer running?
Constructor & Destructor Documentation
Util::Timer::Timer () [inline]
Constructor.
Definition at line 69 of file Timer.h.
Member Function Documentation
void Util::Timer::start () [inline]
Start the clock.
Definition at line 78 of file Timer.h.
References UTIL_THROW.
Referenced by McMd::McSimulation::analyze(), McMd::MdSimulation::analyzeDumps(), McMd::MdSimulation::analyzeTrajectory(), McMd::McSimulation::simulate(), and McMd::MdSimulation::simulate().
void Util::Timer::stop () [inline]
Stop the clock, increment time.
Definition at line 89 of file Timer.h.
References UTIL_THROW.
Referenced by McMd::McSimulation::analyze(), McMd::MdSimulation::analyzeDumps(), McMd::MdSimulation::analyzeTrajectory(), McMd::McSimulation::simulate(), and McMd::MdSimulation::simulate().
void Util::Timer::clear () [inline]
Set accumulated time to zero.
Definition at line 101 of file Timer.h.
double Util::Timer::time () [inline]
Get the accumulated time, in seconds.
Definition at line 110 of file Timer.h.
Referenced by McMd::McSimulation::analyze(), McMd::MdSimulation::analyzeDumps(), McMd::MdSimulation::analyzeTrajectory(), McMd::McSimulation::simulate(), and McMd::MdSimulation::simulate().
bool Util::Timer::isRunning () [inline]
Is the timer running?
Definition at line 116 of file Timer.h.
The documentation for this class was generated from the following file:
Timer.h