Simpatico: McMd::McPairPotentialImpl< Interaction > Class Template Reference
McMd::McPairPotentialImpl< Interaction > Class Template Reference
McMd namespace » Potential Energies » Pair Potentials
Detailed Description
template<class Interaction>
class McMd::McPairPotentialImpl< Interaction >
Implementation template for an McPairPotential.
Definition at line 34 of file McPairPotentialImpl.h.
#include <McPairPotentialImpl.h>
Public Member Functions
McPairPotentialImpl (System &system)
Constructor.
virtual ~McPairPotentialImpl ()
Destructor.
virtual void readParameters (std::istream &in)
Reads maxBoundary and pair potential Interaction blocks.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
Interaction interface
virtual double energy (double rsq, int iAtomType, int jAtomType) const
Return pair energy for a single pair.
virtual double forceOverR (double rsq, int iAtomType, int jAtomType) const
Return force / separation for a single pair.
virtual double maxPairCutoff () const
Return maximum cutoff.
void set (std::string name, int i, int j, double value)
Get a parameter value, identified by a string.
double get (std::string name, int i, int j) const
Get a parameter value, identified by a string.
virtual std::string interactionClassName () const
Return pair interaction class name (e.g., "LJPair").
Interaction & interaction ()
Return reference to underlying pair interaction.
const Interaction & interaction () const
Return reference to underlying pair interaction.
System energy and stress calculators
double atomEnergy (const Atom &atom) const
Calculate the nonbonded pair energy for one Atom.
double moleculeEnergy (const Molecule &molecule) const
Calculate the nonbonded pair energy for an entire Molecule.
double energy ()
Return total nonbonded pair potential energy of this System.
virtual void computeStress (double &stress) const
Compute total nonbonded pressure.
virtual void computeStress (Util::Vector &stress) const
Compute x, y, z nonbonded pressures.
virtual void computeStress (Util::Tensor &stress) const
Compute stress tensor.
Public Member Functions inherited from McMd::McPairPotential
McPairPotential (System &system)
Constructor.
virtual ~McPairPotential ()
Destructor.
void buildCellList ()
Build the CellList with current configuration.
void addAtom (Atom &atom)
Add an Atom to the CellList.
void deleteAtom (Atom &atom)
Remove an Atom from the CellList.
void updateAtomCell (Atom &atom)
Update the cell list to reflect a new position.
void moveAtom (Atom &atom, const Vector &position)
Move an Atom position, and update the CellList.
const CellList & cellList () const
Get the cellList by const reference.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Public Member Functions inherited from McMd::SubSystem
SubSystem (System &parent)
Constructor.
virtual ~SubSystem ()
Destructor.
System & system () const
Get the parent System by reference.
Public Member Functions inherited from McMd::PairPotential
virtual ~PairPotential ()
Destructor (does nothing)
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Member Functions inherited from McMd::SubSystem
Boundary & boundary () const
Get the Boundary by reference.
Simulation & simulation () const
Get the parent Simulation by reference.
int nMolecule (int speciesId) const
Get the number of molecules of one Species in this SubSystem.
int nAtom () const
Return the total number of atoms in this SubSystem.
bool isEmpty () const
Is this an empty SubSystem (i.e., one with no molecules) ?
void begin (int speciesId, System::MoleculeIterator &iterator)
Initialize an iterator for molecules of one species in this SubSystem.
void begin (int speciesId, System::ConstMoleculeIterator &iterator) const
Initialize a const iterator for molecules of one species in this SubSystem.
bool hasBonds () const
Does a bond potential exist?
bool hasAngles () const
Does an angle potential exist?
bool hasDihedrals () const
Does a dihedral potential exist?
bool hasLinks () const
Does a link potential exist?
bool hasExternal () const
Does an external potential exist?
Protected Attributes inherited from McMd::McPairPotential
CellList::NeighborArray neighbors_
Array to hold neighbors returned by a CellList.
CellList cellList_
Cell list for atom positions.
Boundary maxBoundary_
Alias for global atoms_ DArray of parent simulation.
Constructor & Destructor Documentation
template<class Interaction > McMd::McPairPotentialImpl< Interaction >::McPairPotentialImpl (System & system)
Constructor.
Definition at line 208 of file McPairPotentialImpl.h.
template<class Interaction > McMd::McPairPotentialImpl< Interaction >::~McPairPotentialImpl () virtual
Destructor.
Definition at line 216 of file McPairPotentialImpl.h.
Member Function Documentation
template<class Interaction > void McMd::McPairPotentialImpl< Interaction >::readParameters (std::istream & in) virtual
Reads maxBoundary and pair potential Interaction blocks.
This method reads the maxBoundary and Interaction parameter blocks, and then allocates memory for an internal CellList. It passes simulation().nAtomType() as an argument Interaction::setNAtomType() before calling Interaction::readParameters().
Reimplemented from Util::ParamComposite.
Definition at line 223 of file McPairPotentialImpl.h.
template<class Interaction > void McMd::McPairPotentialImpl< Interaction >::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 245 of file McPairPotentialImpl.h.
template<class Interaction > void McMd::McPairPotentialImpl< Interaction >::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 266 of file McPairPotentialImpl.h.
template<class Interaction > double McMd::McPairPotentialImpl< Interaction >::energy (double rsq, int iAtomType, int jAtomType) const virtual
Return pair energy for a single pair.
Implements McMd::PairPotential.
Definition at line 276 of file McPairPotentialImpl.h.
template<class Interaction > double McMd::McPairPotentialImpl< Interaction >::forceOverR (double rsq, int iAtomType, int jAtomType) const virtual
Return force / separation for a single pair.
Implements McMd::PairPotential.
Definition at line 283 of file McPairPotentialImpl.h.
template<class Interaction > double McMd::McPairPotentialImpl< Interaction >::maxPairCutoff () const virtual
Return maximum cutoff.
Implements McMd::PairPotential.
Definition at line 296 of file McPairPotentialImpl.h.
template<class Interaction> void McMd::McPairPotentialImpl< Interaction >::set (std::string name, int i, int j, double value) inline virtual
Get a parameter value, identified by a string.
Parameters
name parameter name
i type index of first atom
j type index of first atom
value parameter value
Implements McMd::PairPotential.
Definition at line 99 of file McPairPotentialImpl.h.
template<class Interaction> double McMd::McPairPotentialImpl< Interaction >::get (std::string name, int i, int j) const inline virtual
Get a parameter value, identified by a string.
Parameters
name parameter name
i type index of first atom
j type index of first atom
Implements McMd::PairPotential.
Definition at line 109 of file McPairPotentialImpl.h.
template<class Interaction > std::string McMd::McPairPotentialImpl< Interaction >::interactionClassName () const virtual
Return pair interaction class name (e.g., "LJPair").
Implements McMd::PairPotential.
Definition at line 525 of file McPairPotentialImpl.h.
template<class Interaction > Interaction & McMd::McPairPotentialImpl< Interaction >::interaction () inline
Return reference to underlying pair interaction.
Definition at line 514 of file McPairPotentialImpl.h.
Referenced by McMd::McPairPerturbation< Interaction >::interaction().
template<class Interaction > const Interaction & McMd::McPairPotentialImpl< Interaction >::interaction () const inline
Return reference to underlying pair interaction.
Definition at line 518 of file McPairPotentialImpl.h.
template<class Interaction > double McMd::McPairPotentialImpl< Interaction >::atomEnergy (const Atom & atom) const virtual
Calculate the nonbonded pair energy for one Atom.
Parameters
atom Atom object of interest
Returns
nonbonded pair potential energy of atom
Implements McMd::McPairPotential.
Definition at line 303 of file McPairPotentialImpl.h.
References McMd::Atom::id(), McMd::Mask::isMasked(), McMd::Atom::mask(), McMd::Atom::position(), and McMd::Atom::typeId().
template<class Interaction > double McMd::McPairPotentialImpl< Interaction >::moleculeEnergy (const Molecule & molecule) const virtual
Calculate the nonbonded pair energy for an entire Molecule.
Parameters
molecule Molecule object of interest
Returns
nonbonded pair potential energy of atom
Implements McMd::McPairPotential.
Definition at line 340 of file McPairPotentialImpl.h.
References McMd::Molecule::atom(), McMd::Atom::id(), McMd::Mask::isMasked(), McMd::Atom::mask(), McMd::Atom::molecule(), McMd::Molecule::nAtom(), McMd::Atom::position(), and McMd::Atom::typeId().
template<class Interaction > double McMd::McPairPotentialImpl< Interaction >::energy () virtual
Return total nonbonded pair potential energy of this System.
Implements McMd::PairPotential.
Definition at line 386 of file McPairPotentialImpl.h.
References McMd::Atom::id(), McMd::Mask::isMasked(), McMd::Atom::mask(), McMd::Atom::position(), and McMd::Atom::typeId().
template<class Interaction > void McMd::McPairPotentialImpl< Interaction >::computeStress (double & stress) const virtual
Compute total nonbonded pressure.
Parameters
stress (output) pressure.
Implements McMd::PairPotential.
Definition at line 497 of file McPairPotentialImpl.h.
template<class Interaction > void McMd::McPairPotentialImpl< Interaction >::computeStress (Util::Vector & stress) const virtual
Compute x, y, z nonbonded pressures.
Parameters
stress (output) pressures.
Implements McMd::PairPotential.
Definition at line 502 of file McPairPotentialImpl.h.
template<class Interaction > void McMd::McPairPotentialImpl< Interaction >::computeStress (Util::Tensor & stress) const virtual
Compute stress tensor.
Parameters
stress (output) pressures.
Implements McMd::PairPotential.
Definition at line 508 of file McPairPotentialImpl.h.
The documentation for this class was generated from the following file:
McPairPotentialImpl.h