Simpatico: DdMd::OutputTemperature Class Reference
DdMd::OutputTemperature Class Reference
Analyzers
Detailed Description
Periodically output kinetic temperature to file.
See also:
param file format
Definition at line 26 of file OutputTemperature.h.
#include <OutputTemperature.h>
Public Member Functions
OutputTemperature (Simulation &simulation)
Constructor.
virtual ~OutputTemperature ()
Destructor.
virtual void readParameters (std::istream &in)
Read interval and output file name.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void clear ()
Clear nSample counter.
virtual void setup ()
Setup - open output file.
virtual void sample (long iStep)
Dump configuration to file.
Constructor & Destructor Documentation
DdMd::OutputTemperature::OutputTemperature (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object.
Definition at line 24 of file OutputTemperature.cpp.
References Util::ParamComposite::setClassName().
virtual DdMd::OutputTemperature::~OutputTemperature () [inline, virtual]
Destructor.
Definition at line 41 of file OutputTemperature.h.
Member Function Documentation
void DdMd::OutputTemperature::readParameters (std::istream & in) [virtual]
Read interval and output file name.
Parameters:
in input parameter file
Reimplemented from Util::ParamComposite.
Definition at line 33 of file OutputTemperature.cpp.
References DdMd::Simulation::fileMaster(), Util::FileMaster::openOutputFile(), DdMd::Analyzer::outputFileName(), DdMd::Analyzer::readInterval(), DdMd::Analyzer::readOutputFileName(), and DdMd::Analyzer::simulation().
void DdMd::OutputTemperature::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from DdMd::Analyzer.
Definition at line 51 of file OutputTemperature.cpp.
References DdMd::Simulation::fileMaster(), Util::MpiLoader< IArchive >::load(), DdMd::Analyzer::loadInterval(), DdMd::Analyzer::loadOutputFileName(), Util::FileMaster::openOutputFile(), DdMd::Analyzer::outputFileName(), and DdMd::Analyzer::simulation().
void DdMd::OutputTemperature::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from DdMd::Analyzer.
Definition at line 73 of file OutputTemperature.cpp.
References DdMd::Analyzer::saveInterval(), and DdMd::Analyzer::saveOutputFileName().
void DdMd::OutputTemperature::clear () [virtual]
Clear nSample counter.
Reimplemented from DdMd::Analyzer.
Definition at line 83 of file OutputTemperature.cpp.
void DdMd::OutputTemperature::setup () [virtual]
Setup - open output file.
Reimplemented from DdMd::Analyzer.
Definition at line 89 of file OutputTemperature.cpp.
References DdMd::Simulation::fileMaster(), Util::FileMaster::openOutputFile(), DdMd::Analyzer::outputFileName(), and DdMd::Analyzer::simulation().
void DdMd::OutputTemperature::sample (long iStep) [virtual]
Dump configuration to file.
Parameters:
iStep MD step index
Implements DdMd::Analyzer.
Definition at line 101 of file OutputTemperature.cpp.
References DdMd::Simulation::atomStorage(), DdMd::Simulation::computeKineticEnergy(), DdMd::AtomStorage::computeNAtomTotal(), DdMd::Simulation::domain(), DdMd::Analyzer::isAtInterval(), DdMd::Domain::isMaster(), DdMd::Simulation::kineticEnergy(), DdMd::AtomStorage::nAtomTotal(), and DdMd::Analyzer::simulation().
The documentation for this class was generated from the following files:
OutputTemperature.h
OutputTemperature.cpp