Simpatico: Util::ParamComposite Class Reference
Util::ParamComposite Class Reference
Parameter File IO
Detailed Description
An object that can read multiple parameters from file.
Any class that reads a block of parameters from a parameter file must be derived from ParamComposite. Each such class must implement either the readParameters() function or the readParam() function, but not both. The readParameters(), if reimplemented, should read the body of the associated parameter file block, without opening or closing lines. The readParam() function reads the the entire block, including opening line and closing lines. The default implementation of readParam() reads the opening line of the block, calls readParameters() to read the body of the block, and then reads the closing line. Most subclasses of ParamComposite re-implement the readParameters() function, and rely on the default implementation of readParam() to add the Begin and End lines.
The writeParam() function, if called after readParam(), writes the associated parameter block using the same file format as that used to read the data in the earlier call to readParam().
Implementation details: -----------------------
After parameter file block is read from file, the file format is stored as a private array of ParaComponent* pointers. We will refer to this in what follows as the format_ array. Each pointer in this array may point to a Parameter, ParamComposite, Begin, End, or Blank object. Pointers to these objects are added to the format array as the associated objects are read from file, and are stored in the same order as they appear in the parameter file. The default implementation of the writeParam() function simply calls the writeParam() function of each child ParamComponent.
Subclass implementation details: --------------------------------
The readParameters() function of each subclass of ParamComposite should be implemented using protected member functions of ParamComposite with names that begin with "read". The read<T>() function template can be used to read an individual parameter, while readParamComposite reads the nested subblock associated with a child ParamComposite. There are also more specialized methods (e.g., readDArray<T>to read different types of arrays and matrices of parameters, and to read optional parameters. See the users manual for further details.
The setClassName() and className() functions may be used to set and get a std::string containing the subclass name. The setClassName() function should be called in the constructor of each subclass of ParamComposite. The class name set in the constructor of a subclass will replace any name set by a base class, because of the order in which constructors are called. The default implementation of ParamComposite::readParam() checks if the class name that appears in the opening line of a parameter block agrees with the class name returned by the className() function, and throws an exception if it does not.
Definition at line 88 of file ParamComposite.h.
#include <ParamComposite.h>
Public Member Functions
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
Read and write functions for the composite
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void readParameters (std::istream &in)
Read the body of parameter block, without begin and end lines.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
Serialization: Load and save functions for this composite
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
read* functions for child components
Each of these functions invokes an associated add* function to create a new ParamComponent object, and then invoke the readParam() function of the new object to read the associated line or block of a parameter file.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
load* functions for child components
Each of these functions invokes an associated add*() function to create a new ParamComponent object, and then invokes the load() function of the new object to load the associated parameter value from an input archive.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
add* functions for child components
These function each add a ParamComponent object to the format array, but do not read any data from an input stream.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
Accessors
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Protected Member Functions
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Constructor & Destructor Documentation
Util::ParamComposite::ParamComposite ()
Constructor.
Definition at line 23 of file ParamComposite.cpp.
Util::ParamComposite::ParamComposite (const ParamComposite & other)
Copy constructor.
Definition at line 55 of file ParamComposite.cpp.
Util::ParamComposite::ParamComposite (int capacity)
Constructor.
Reserve space for capacity elements in the format array.
Parameters:
capacity maximum length of parameter list
Definition at line 36 of file ParamComposite.cpp.
References UTIL_THROW.
Util::ParamComposite::~ParamComposite () [virtual]
Virtual destructor.
Definition at line 68 of file ParamComposite.cpp.
Member Function Documentation
void Util::ParamComposite::resetParam () [virtual]
Resets ParamComposite to its empty state.
This function deletes Parameter, Begin, End, and Blank objects in the format array (i.e., all "leaf" objects in the format tree), invokes the resetParam() function of any child ParamComposite in the format array, and clears the format array.
Reimplemented from Util::ParamComponent.
Definition at line 209 of file ParamComposite.cpp.
void Util::ParamComposite::readParam (std::istream & in) [virtual]
Read the parameter file block.
Inherited from ParamComponent. This function reads the entire parameter block for this ParamComposite, including the opening line "ClassName{" and the closing bracket "}". The default implementation calls the virtual readParameters function to read the body of the block, and adds Begin and End objects.
Exceptions:
Throws if the string in the opening line does not match classname().
Parameters:
in input stream for reading
Implements Util::ParamComponent.
Reimplemented in DdMd::Simulation, Util::Manager< Data >, Util::Manager< Species >, Util::Manager< Modifier >, Util::Manager< McMove >, Util::Manager< Analyzer >, McMd::McSimulation, McMd::MdSimulation, Util::SpeciesEnsemble, and Tools::ChainMaker.
Definition at line 88 of file ParamComposite.cpp.
References readBegin(), readEnd(), and readParameters().
Referenced by readParamComposite().
void Util::ParamComposite::readParamOptional (std::istream & in) [virtual]
Read optional parameter file block.
Read an optional ParamComposite. This function attempts to reads the beginning "ClassName{" line, and then continues to read the rest of the block if and only if the beginning line matches. The default implementation calls the readParameters(std::istream&) member function to read the body of the block.
Parameters:
in input stream for reading
Reimplemented in Util::Manager< Data >, Util::Manager< Species >, Util::Manager< Modifier >, Util::Manager< McMove >, and Util::Manager< Analyzer >.
Definition at line 101 of file ParamComposite.cpp.
References Util::Begin::isActive(), readBegin(), readEnd(), and readParameters().
Referenced by readParamCompositeOptional().
virtual void Util::ParamComposite::readParameters (std::istream & in) [inline, virtual]
Read the body of parameter block, without begin and end lines.
Most subclasses of ParamComposite should overload this function. The default implementation is empty. Every subclass must overload either readParameters or readParam, but not both.
Parameters:
in input stream for reading
Reimplemented in DdMd::Buffer, Util::FileMaster, McMd::System, McMd::Species, DdMd::Simulation, DdMd::GroupDistributor< N >, DdMd::AtomDistributor, McMd::IntraStructureFactor, McMd::StructureFactorP, McMd::Simulation, Util::Manager< Data >, Util::Manager< Species >, Util::Manager< Modifier >, Util::Manager< McMove >, Util::Manager< Analyzer >, McMd::VanHove, DdMd::VanHove, DdMd::StructureFactor, DdMd::AsymmSF, Inter::OrthoBoxExternal, Inter::LocalLamellarOrderingExternal, McMd::McSimulation, McMd::MdSimulation, DdMd::PairPotential, McMd::IntraStructureFactorGrid, Inter::BoxExternal, McMd::ReplicaMove, Inter::SlitExternal, DdMd::GroupStorage< N >, DdMd::GroupStorage< 2 >, DdMd::GroupStorage< 3 >, DdMd::GroupStorage< 4 >, McMd::MdSystem, DdMd::AtomStorage, Inter::LamellarOrderingExternal, DdMd::StructureFactorGrid, Inter::GeneralPeriodicExternal, Inter::NucleationExternal, Inter::PeriodicExternal, Inter::SimplePeriodicExternal, McMd::StructureFactorGrid, McMd::StructureFactorPGrid, McMd::PairList, DdMd::AsymmSFGrid, Inter::FeneBond, McMd::BlockRadiusGyration, McMd::RadiusGyration, McMd::StructureFactor, DdMd::OrderParamNucleation, Util::AutoCorrArray< Data, Product >, McMd::Analyzer, Util::AutoCorrArray< Tensor, double >, Util::AutoCorrArray< Vector, double >, Inter::HarmonicBond, Inter::CosineDihedral, McMd::IntraPairAutoCorr, Tools::Processor, Util::AutoCorr< Data, Product >, Inter::LJPair, DdMd::Domain, Util::AutoCorr< double, double >, Util::AutoCorr< std::complex< double >, std::complex< double > >, McMd::IntraBondTensorAutoCorr< SystemType >, McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >, McMd::IntraBondTensorAutoCorr< MdSystem >, McMd::IntraBondTensorAutoCorr< McSystem >, Inter::CosineAngle, Inter::HarmonicAngle, Inter::CosineSqAngle, McMd::LinkMaster, Tools::Configuration, Inter::HarmonicL0Bond, Inter::MultiHarmonicDihedral, McMd::McSystem, Util::Random, Inter::DpdPair, DdMd::ExternalPotentialImpl< Interaction >, McMd::Perturbation, McMd::LinkPotentialImpl< Interaction >, DdMd::AnglePotentialImpl< Interaction >, Util::Average, Util::MeanSqDispArray< Data >, Inter::CompositeBond< BareBond, BarePair >, McMd::McPairPerturbation< Interaction >, McMd::MdPairPotentialImpl< Interaction >, Util::MeanSqDispArray< Vector >, McMd::CompositionProfile, McMd::NphIntegrator, McMd::AnglePotentialImpl< Interaction >, McMd::DihedralPotentialImpl< Interaction >, DdMd::TrajectoryWriter, Tools::TrajectoryWriter, DdMd::BondPotentialImpl< Interaction >, DdMd::PairPotentialImpl< Interaction >, Util::EnergyEnsemble, McMd::McExternalPerturbation< Interaction >, McMd::BondPotentialImpl< Interaction >, McMd::ExternalPotentialImpl< Interaction >, DdMd::DihedralPotentialImpl< Interaction >, Util::Distribution, Util::BoundaryEnsemble, McMd::RDF, McMd::MdMove, McMd::NvtDpdVvIntegrator, Util::IntDistribution, McMd::ConfigWriter, DdMd::ConfigWriter, McMd::NvtNhIntegrator, McMd::McPairPotentialImpl< Interaction >, DdMd::ModifierManager, McMd::BennettsMethod, McMd::IntraBondStressAutoCorr< SystemType >, McMd::LinearRouseAutoCorr, McMd::DpdMove, McMd::IntraBondStressAutoCorr< MdSystem >, McMd::IntraBondStressAutoCorr< McSystem >, McMd::McMove, McMd::MdPairEnergyCoefficients, McMd::McMoveManager, Util::RadialDistribution, McMd::RingRouseAutoCorr, McMd::CfbEndBase, McMd::HybridNphMdMove, DdMd::VirialStressTensorAverage, Inter::CompensatedPair< BarePair, LinkPotential >, McMd::McMuExchange, DdMd::AutoCorrAnalyzer< Data, Product >, Tools::AtomMSD, DdMd::AutoCorrAnalyzer< Tensor, double >, McMd::McVirialStressTensorAverage, McMd::MdVirialStressTensorAverage, McMd::PressureAverage< SystemType >, McMd::StressAutoCorr< SystemType >, McMd::StressTensorAverage< SystemType >, McMd::CfbRebridgeBase, McMd::CfbReptationMove, DdMd::OutputPairEnergies, DdMd::OutputPressure, DdMd::StressAutoCorr, DdMd::VirialStressTensor, McMd::PressureAverage< MdSystem >, McMd::PressureAverage< McSystem >, McMd::StressAutoCorr< MdSystem >, McMd::ComMSD, McMd::HybridMdMove, McMd::CfbRingRebridgeMove, DdMd::ExternalEnergyAverage, DdMd::LogEnergy, DdMd::OutputBoxdim, DdMd::OutputEnergy, DdMd::OutputTemperature, DdMd::PairEnergyAverage, DdMd::Integrator, McMd::EndSwapMove, DdMd::OutputStressTensor, DdMd::NptIntegrator, McMd::McNVTChemicalPotential, McMd::McPairEnergyAverage, McMd::BondLengthDist, McMd::HomopolymerSG, DdMd::AnalyzerManager, DdMd::NphIntegrator, McMd::RingTetraRebridgeMove, DdMd::NveIntegrator, Util::AutoCorrelation< Data, Product >, Inter::WcaPair, McMd::AnalyzerManager, McMd::AtomMSD, McMd::RingOctaRebridgeMove, Util::AutoCorrelation< Tensor, double >, McMd::AverageAnalyzer< SystemType >, DdMd::NvtIntegrator, DdMd::DihedralStorage, Tools::AnalyzerManager, McMd::AverageAnalyzer< McSystem >, McMd::BoundaryAverage, McMd::RigidDisplaceMove, McMd::CfbEndMove, McMd::CfbRebridgeMove, DdMd::DdMdGroupTrajectoryWriter, McMd::TypeDistribution, McMd::McEnergyPerturbation, DdMd::AngleStorage, DdMd::BondStorage, Tools::LogStep, McMd::McEnergyOutput, McMd::PerturbDerivative, McMd::CfbDoubleRebridgeMove, McMd::NveVvIntegrator, McMd::MdEnergyOutput, McMd::MdKineticEnergyAverage, McMd::SemiGrandDistribution, McMd::AtomDisplaceMove, McMd::HomopolymerSemiGrandMove, McMd::MdPotentialEnergyAverage, and McMd::LogProgress.
Definition at line 167 of file ParamComposite.h.
Referenced by readParam(), and readParamOptional().
void Util::ParamComposite::writeParam (std::ostream & out) [virtual]
Write all parameters to an output stream.
The default implementation iterates through the format array, and calls the readParam member function of each ParamComponent in the array.
Parameters:
out output stream for reading
Implements Util::ParamComponent.
Reimplemented in Inter::MultiHarmonicDihedral.
Definition at line 119 of file ParamComposite.cpp.
Referenced by McMd::McNVTChemicalPotential::output(), McMd::McMuExchange::output(), Tools::AtomMSD::output(), McMd::MdEnergyOutput::output(), McMd::McEnergyOutput::output(), McMd::MdPotentialEnergyAverage::output(), McMd::AverageAnalyzer< SystemType >::output(), McMd::MdKineticEnergyAverage::output(), McMd::PerturbDerivative::output(), DdMd::ExternalEnergyAverage::output(), DdMd::PairEnergyAverage::output(), McMd::MdPairEnergyCoefficients::output(), McMd::BoundaryAverage::output(), McMd::McPairEnergyAverage::output(), DdMd::StressAutoCorr::output(), McMd::AtomMSD::output(), McMd::BondLengthDist::output(), McMd::ComMSD::output(), DdMd::AsymmSFGrid::output(), McMd::RingRouseAutoCorr::output(), McMd::LinearRouseAutoCorr::output(), McMd::BlockRadiusGyration::output(), McMd::RDF::output(), McMd::CompositionProfile::output(), DdMd::OrderParamNucleation::output(), McMd::IntraPairAutoCorr::output(), McMd::StructureFactor::output(), McMd::RadiusGyration::output(), DdMd::StructureFactorGrid::output(), McMd::StructureFactorPGrid::output(), McMd::StructureFactorGrid::output(), DdMd::AsymmSF::output(), McMd::IntraStructureFactorGrid::output(), DdMd::StructureFactor::output(), DdMd::VanHove::output(), McMd::VanHove::output(), McMd::StructureFactorP::output(), McMd::IntraStructureFactor::output(), McMd::MdSimulation::readCommands(), and McMd::McSimulation::readCommands().
void Util::ParamComposite::load (Serializable::IArchive & ar) [virtual]
Load all parameters from an input archive.
This function is inherited from Serializable. The default implementation for a ParamComposite calls loadParameters, and adds Begin and End lines to the format array.. All subclasses of ParamComposite should overload the virtual loadParameters member function.
Parameters:
ar input/loading archive.
Reimplemented from Util::ParamComponent.
Reimplemented in McMd::McNVTChemicalPotential, Util::AutoCorrelation< Data, Product >, and Util::AutoCorrelation< Tensor, double >.
Definition at line 131 of file ParamComposite.cpp.
References addBegin(), addEnd(), Util::ParamComponent::echo(), Util::Log::file(), Util::MpiFileIo::isIoProcessor(), loadParameters(), Util::End::writeParam(), and Util::Begin::writeParam().
Referenced by loadOptional(), and loadParamComposite().
void Util::ParamComposite::loadOptional (Serializable::IArchive & ar) [virtual]
Load an optional ParamComposite.
Loads isActive, and calls load(ar) if active.
Parameters:
ar input/loading archive.
Definition at line 152 of file ParamComposite.cpp.
References Util::bcast< bool >(), className(), Util::ParamComponent::echo(), Util::Log::file(), Util::MpiFileIo::hasIoCommunicator(), Util::ParamComponent::indent(), Util::MpiFileIo::ioCommunicator(), Util::MpiFileIo::isIoProcessor(), load(), and UTIL_THROW.
Referenced by loadParamCompositeOptional().
virtual void Util::ParamComposite::loadParameters (Serializable::IArchive & ar) [inline, virtual]
Load state from archive, without adding Begin and End lines.
This default implementation is empty, and should be re-implemented by all subclasses that have an internal state which should be saved in a restart file. Subclass implementations should load the entire internal state from the archive, including persistent private data that does not appear in the parameter file format.
Parameters:
ar input/loading archive.
Reimplemented in DdMd::Buffer, Util::FileMaster, DdMd::Simulation, McMd::System, McMd::Species, McMd::IntraStructureFactor, McMd::StructureFactorP, McMd::Simulation, Util::Manager< Data >, Util::Manager< Species >, Util::Manager< Modifier >, Util::Manager< McMove >, Util::Manager< Analyzer >, McMd::VanHove, DdMd::VanHove, DdMd::StructureFactor, DdMd::Analyzer, McMd::BlockRadiusGyration, DdMd::AtomStorage, Inter::OrthoBoxExternal, Inter::LocalLamellarOrderingExternal, DdMd::PairPotential, McMd::McSimulation, McMd::MdSimulation, McMd::IntraStructureFactorGrid, DdMd::GroupStorage< N >, DdMd::GroupStorage< 2 >, DdMd::GroupStorage< 3 >, DdMd::GroupStorage< 4 >, Inter::BoxExternal, McMd::ReplicaMove, Inter::SlitExternal, McMd::MdSystem, Inter::LamellarOrderingExternal, Util::AutoCorrArray< Data, Product >, DdMd::StructureFactorGrid, Util::AutoCorrArray< Tensor, double >, Util::AutoCorrArray< Vector, double >, Inter::GeneralPeriodicExternal, Inter::NucleationExternal, Inter::PeriodicExternal, Inter::SimplePeriodicExternal, McMd::StructureFactorGrid, McMd::StructureFactorPGrid, McMd::PairList, Util::AutoCorr< Data, Product >, Util::AutoCorr< double, double >, Util::AutoCorr< std::complex< double >, std::complex< double > >, Inter::FeneBond, Inter::MultiHarmonicDihedral, McMd::Analyzer, McMd::RadiusGyration, McMd::StructureFactor, DdMd::OrderParamNucleation, Util::Average, Util::MeanSqDispArray< Data >, Inter::HarmonicBond, Inter::CosineDihedral, McMd::CompositionProfile, McMd::IntraPairAutoCorr, Util::MeanSqDispArray< Vector >, Inter::LJPair, DdMd::Domain, McMd::McMuExchange, McMd::IntraBondTensorAutoCorr< SystemType >, McMd::IntraBondTensorAutoCorr< MdSystem >, McMd::IntraBondTensorAutoCorr< McSystem >, Inter::CosineAngle, Inter::HarmonicAngle, Inter::CosineSqAngle, Inter::HarmonicL0Bond, Util::Distribution, McMd::McSystem, Util::Random, Inter::DpdPair, Util::IntDistribution, DdMd::AnglePotentialImpl< Interaction >, McMd::ConfigWriter, McMd::Perturbation, McMd::McPairPerturbation< Interaction >, McMd::MdPairPotentialImpl< Interaction >, DdMd::BondPotentialImpl< Interaction >, McMd::NphIntegrator, McMd::AnglePotentialImpl< Interaction >, McMd::DihedralPotentialImpl< Interaction >, DdMd::TrajectoryWriter, DdMd::DihedralPotentialImpl< Interaction >, DdMd::ExternalPotentialImpl< Interaction >, DdMd::PairPotentialImpl< Interaction >, Util::EnergyEnsemble, McMd::BondPotentialImpl< Interaction >, McMd::ExternalPotentialImpl< Interaction >, Util::RadialDistribution, Util::BoundaryEnsemble, McMd::RDF, McMd::MdMove, McMd::NvtDpdVvIntegrator, DdMd::ConfigWriter, McMd::NvtNhIntegrator, McMd::McPairPotentialImpl< Interaction >, McMd::BennettsMethod, McMd::IntraBondStressAutoCorr< SystemType >, McMd::LinearRouseAutoCorr, McMd::DpdMove, McMd::IntraBondStressAutoCorr< MdSystem >, McMd::IntraBondStressAutoCorr< McSystem >, McMd::McMove, McMd::MdPairEnergyCoefficients, McMd::McMoveManager, McMd::RingRouseAutoCorr, McMd::HybridNphMdMove, DdMd::VirialStressTensorAverage, McMd::RingTetraRebridgeMove, DdMd::AutoCorrAnalyzer< Data, Product >, DdMd::AutoCorrAnalyzer< Tensor, double >, McMd::McVirialStressTensorAverage, McMd::MdVirialStressTensorAverage, McMd::PressureAverage< SystemType >, McMd::StressAutoCorr< SystemType >, McMd::StressTensorAverage< SystemType >, McMd::CfbRebridgeBase, McMd::CfbReptationMove, DdMd::OutputPairEnergies, DdMd::OutputPressure, DdMd::StressAutoCorr, DdMd::VirialStressTensor, McMd::PressureAverage< MdSystem >, McMd::PressureAverage< McSystem >, McMd::StressAutoCorr< MdSystem >, McMd::ComMSD, McMd::HybridMdMove, McMd::CfbRingRebridgeMove, DdMd::ExternalEnergyAverage, DdMd::LogEnergy, DdMd::OutputBoxdim, DdMd::OutputEnergy, DdMd::OutputTemperature, DdMd::PairEnergyAverage, DdMd::Integrator, McMd::EndSwapMove, DdMd::OutputStressTensor, DdMd::NptIntegrator, McMd::McPairEnergyAverage, McMd::BondLengthDist, DdMd::AnalyzerManager, DdMd::NveIntegrator, McMd::AnalyzerManager, McMd::AtomMSD, McMd::RingOctaRebridgeMove, DdMd::NphIntegrator, McMd::AverageAnalyzer< SystemType >, DdMd::NvtIntegrator, McMd::AverageAnalyzer< McSystem >, McMd::BoundaryAverage, McMd::RigidDisplaceMove, McMd::CfbEndMove, McMd::CfbRebridgeMove, DdMd::DdMdGroupTrajectoryWriter, McMd::TypeDistribution, McMd::McEnergyOutput, McMd::PerturbDerivative, McMd::CfbDoubleRebridgeMove, McMd::NveVvIntegrator, McMd::MdEnergyOutput, McMd::MdKineticEnergyAverage, McMd::SemiGrandDistribution, McMd::AtomDisplaceMove, McMd::HomopolymerSemiGrandMove, McMd::MdPotentialEnergyAverage, and McMd::LogProgress.
Definition at line 218 of file ParamComposite.h.
Referenced by load().
void Util::ParamComposite::save (Serializable::OArchive & ar) [virtual]
Saves all parameters to an archive.
This simple default implementation calls the save function for all items in the parameter file format array. This is not sufficient for classes that contain any persistent private data that does not appear in the parameter file format.
If a class also defines a serialize function template, which allows instances to be serialized to any type of archive, then the save function can be implemented as follows:
    void save(Serializable::OArchive& ar)
    { ar & *this; }
Parameters:
ar output/saving archive.
Reimplemented from Util::ParamComponent.
Reimplemented in DdMd::Buffer, Util::FileMaster, DdMd::Simulation, McMd::Species, McMd::IntraStructureFactor, McMd::StructureFactorP, McMd::Simulation, Util::Manager< Data >, Util::Manager< Species >, Util::Manager< Modifier >, Util::Manager< McMove >, Util::Manager< Analyzer >, McMd::VanHove, DdMd::VanHove, DdMd::Analyzer, DdMd::StructureFactor, DdMd::AtomStorage, Inter::OrthoBoxExternal, Inter::LocalLamellarOrderingExternal, DdMd::PairPotential, McMd::McSimulation, DdMd::GroupStorage< N >, DdMd::GroupStorage< 2 >, DdMd::GroupStorage< 3 >, DdMd::GroupStorage< 4 >, McMd::MdSimulation, McMd::IntraStructureFactorGrid, Inter::BoxExternal, McMd::ReplicaMove, Inter::SlitExternal, McMd::BlockRadiusGyration, Inter::LamellarOrderingExternal, Util::AutoCorrArray< Data, Product >, DdMd::StructureFactorGrid, Util::AutoCorrArray< Tensor, double >, Util::AutoCorrArray< Vector, double >, Inter::GeneralPeriodicExternal, Inter::NucleationExternal, Inter::PeriodicExternal, Inter::SimplePeriodicExternal, McMd::StructureFactorGrid, McMd::StructureFactorPGrid, McMd::PairList, Util::AutoCorr< Data, Product >, Util::AutoCorr< double, double >, Util::AutoCorr< std::complex< double >, std::complex< double > >, Inter::FeneBond, McMd::Analyzer, Inter::MultiHarmonicDihedral, McMd::RadiusGyration, McMd::StructureFactor, DdMd::OrderParamNucleation, Util::Average, Util::MeanSqDispArray< Data >, Inter::HarmonicBond, Inter::CosineDihedral, McMd::CompositionProfile, McMd::IntraPairAutoCorr, Util::MeanSqDispArray< Vector >, Inter::LJPair, DdMd::Domain, McMd::IntraBondTensorAutoCorr< SystemType >, McMd::IntraBondTensorAutoCorr< MdSystem >, McMd::IntraBondTensorAutoCorr< McSystem >, Inter::CosineAngle, Inter::HarmonicAngle, Inter::CosineSqAngle, Inter::HarmonicL0Bond, Util::Distribution, Util::Random, Inter::DpdPair, Util::IntDistribution, DdMd::AnglePotentialImpl< Interaction >, McMd::Perturbation, McMd::MdPairPotentialImpl< Interaction >, DdMd::BondPotentialImpl< Interaction >, McMd::NphIntegrator, McMd::AnglePotentialImpl< Interaction >, McMd::DihedralPotentialImpl< Interaction >, DdMd::TrajectoryWriter, DdMd::DihedralPotentialImpl< Interaction >, DdMd::PairPotentialImpl< Interaction >, Util::EnergyEnsemble, McMd::BondPotentialImpl< Interaction >, McMd::ExternalPotentialImpl< Interaction >, Util::RadialDistribution, Util::BoundaryEnsemble, McMd::RDF, McMd::MdMove, McMd::NvtDpdVvIntegrator, McMd::McMuExchange, DdMd::ConfigWriter, DdMd::ExternalPotentialImpl< Interaction >, McMd::NvtNhIntegrator, McMd::McPairPotentialImpl< Interaction >, McMd::BennettsMethod, McMd::IntraBondStressAutoCorr< SystemType >, McMd::LinearRouseAutoCorr, McMd::DpdMove, McMd::IntraBondStressAutoCorr< MdSystem >, McMd::IntraBondStressAutoCorr< McSystem >, McMd::McNVTChemicalPotential, McMd::McMove, McMd::MdPairEnergyCoefficients, McMd::McMoveManager, McMd::ConfigWriter, McMd::RingRouseAutoCorr, McMd::HybridNphMdMove, DdMd::VirialStressTensorAverage, McMd::RingTetraRebridgeMove, DdMd::AutoCorrAnalyzer< Data, Product >, DdMd::AutoCorrAnalyzer< Tensor, double >, McMd::McVirialStressTensorAverage, McMd::MdVirialStressTensorAverage, McMd::PressureAverage< SystemType >, McMd::StressAutoCorr< SystemType >, McMd::StressTensorAverage< SystemType >, McMd::CfbRebridgeBase, McMd::CfbReptationMove, DdMd::OutputPairEnergies, DdMd::OutputPressure, DdMd::StressAutoCorr, DdMd::VirialStressTensor, McMd::PressureAverage< MdSystem >, McMd::PressureAverage< McSystem >, McMd::StressAutoCorr< MdSystem >, McMd::ComMSD, McMd::HybridMdMove, McMd::CfbRingRebridgeMove, DdMd::ExternalEnergyAverage, DdMd::LogEnergy, DdMd::OutputBoxdim, DdMd::OutputEnergy, DdMd::OutputTemperature, DdMd::PairEnergyAverage, DdMd::Integrator, McMd::EndSwapMove, DdMd::OutputStressTensor, DdMd::NptIntegrator, McMd::McPairEnergyAverage, McMd::BondLengthDist, DdMd::AnalyzerManager, DdMd::NveIntegrator, Util::AutoCorrelation< Data, Product >, McMd::AnalyzerManager, McMd::AtomMSD, McMd::RingOctaRebridgeMove, Util::AutoCorrelation< Tensor, double >, McMd::AverageAnalyzer< SystemType >, DdMd::NvtIntegrator, McMd::AverageAnalyzer< McSystem >, McMd::BoundaryAverage, McMd::RigidDisplaceMove, McMd::CfbEndMove, McMd::CfbRebridgeMove, DdMd::DdMdGroupTrajectoryWriter, DdMd::NphIntegrator, McMd::TypeDistribution, McMd::McEnergyOutput, McMd::PerturbDerivative, McMd::CfbDoubleRebridgeMove, McMd::NveVvIntegrator, McMd::MdEnergyOutput, McMd::MdKineticEnergyAverage, McMd::SemiGrandDistribution, McMd::AtomDisplaceMove, McMd::HomopolymerSemiGrandMove, McMd::MdPotentialEnergyAverage, McMd::Homopolymer, McMd::Diblock, McMd::Point, and McMd::HomoRing.
Definition at line 188 of file ParamComposite.cpp.
Referenced by McMd::System::saveLinkMaster(), saveOptional(), McMd::McSystem::saveParameters(), and McMd::MdSystem::saveParameters().
void Util::ParamComposite::saveOptional (Serializable::OArchive & ar)
Saves isActive flag, and then calls save() iff isActive is true.
Parameters:
ar output/saving archive.
Definition at line 198 of file ParamComposite.cpp.
References save().
Referenced by McMd::Diblock::save(), DdMd::PairPotential::save(), and McMd::Simulation::save().
void Util::ParamComposite::readParamComposite (std::istream & in, ParamComposite & child, bool next = true)
Add and read a required child ParamComposite.
Parameters:
in input stream for reading
child child ParamComposite object
next true if the indent level is one higher than parent.
Definition at line 260 of file ParamComposite.cpp.
References addParamComposite(), and readParam().
Referenced by McMd::System::readEnsembles(), McMd::System::readFileMaster(), McMd::System::readLinkMaster(), Tools::ChainMaker::readParam(), McMd::HybridMdMove::readParameters(), McMd::HybridNphMdMove::readParameters(), McMd::DpdMove::readParameters(), McMd::MdMove::readParameters(), McMd::McSystem::readParameters(), Tools::Processor::readParameters(), McMd::MdSystem::readParameters(), McMd::MdSimulation::readParameters(), McMd::McSimulation::readParameters(), McMd::Simulation::readParameters(), and McMd::System::readReplicaMove().
void Util::ParamComposite::readParamCompositeOptional (std::istream & in, ParamComposite & child, bool next = true)
Add and attempt to read an optional child ParamComposite.
Parameters:
in input stream for reading
child child ParamComposite object
next true if the indent level is one higher than parent.
Definition at line 271 of file ParamComposite.cpp.
References addParamComposite(), and readParamOptional().
Referenced by Tools::Processor::readParameters().
template<typename Type > ScalarParam< Type > & Util::ParamComposite::read (std::istream & in, const char * label, Type & value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
Parameters:
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
isRequired Is this a required parameter?
Definition at line 830 of file ParamComposite.h.
References addComponent(), isRequired(), Util::Parameter::readParam(), and setParent().
template<typename Type > ScalarParam< Type > & Util::ParamComposite::read (std::istream & in, const char * label, Type & value)
Add and read a new required ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, true).
Parameters:
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 846 of file ParamComposite.h.
template<typename Type > CArrayParam< Type > & Util::ParamComposite::readCArray (std::istream & in, const char * label, Type * value, int n, bool isRequired)
Add and read a C array parameter.
Parameters:
in input stream for reading
label Label string for new array
value pointer to array
n number of elements
isRequired Is this a required parameter?
Returns:
reference to the new CArrayParam<Type> object
Definition at line 872 of file ParamComposite.h.
References addComponent(), isRequired(), Util::Parameter::readParam(), and setParent().
template<typename Type > CArrayParam<Type>& Util::ParamComposite::readCArray (std::istream & in, const char * label, Type * value, int n) [inline]
Add and read a required C array parameter.
Definition at line 322 of file ParamComposite.h.
template<typename Type > DArrayParam< Type > & Util::ParamComposite::readDArray (std::istream & in, const char * label, DArray< Type > & array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
Parameters:
in input stream for reading
label Label string for new array
array DArray object
n number of elements
isRequired Is this a required parameter?
Returns:
reference to the new DArrayParam<Type> object
Definition at line 906 of file ParamComposite.h.
References addComponent(), isRequired(), Util::Parameter::readParam(), and setParent().
template<typename Type > DArrayParam<Type>& Util::ParamComposite::readDArray (std::istream & in, const char * label, DArray< Type > & array, int n) [inline]
Add a required DArray < Type > parameter.
Definition at line 345 of file ParamComposite.h.
template<typename Type , int N> FArrayParam< Type, N > & Util::ParamComposite::readFArray (std::istream & in, const char * label, FArray< Type, N > & array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
Parameters:
in input stream for reading
label Label string for new array
array FArray object
isRequired Is this a required parameter?
Returns:
reference to the new FArrayParam<Type, N> object
Definition at line 940 of file ParamComposite.h.
References addComponent(), isRequired(), Util::Parameter::readParam(), and setParent().
template<typename Type , int N> FArrayParam<Type, N>& Util::ParamComposite::readFArray (std::istream & in, const char * label, FArray< Type, N > & array) [inline]
Add and read a required FArray < Type, N > array parameter.
Definition at line 368 of file ParamComposite.h.
template<typename Type > CArray2DParam< Type > & Util::ParamComposite::readCArray2D (std::istream & in, const char * label, Type * value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
This reads m rows of n elements into an array of type array[][np].
Parameters:
in input stream for reading
label Label string for new array
value pointer to array
m number of rows (1st dimension)
n logical number of columns (2nd dimension)
np physical number of columns (elements allocated per row)
isRequired Is this a required parameter?
Returns:
reference to the CArray2DParam<Type> object
Definition at line 974 of file ParamComposite.h.
References addComponent(), isRequired(), Util::Parameter::readParam(), and setParent().
template<typename Type > CArray2DParam<Type>& Util::ParamComposite::readCArray2D (std::istream & in, const char * label, Type * value, int m, int n, int np) [inline]
Add and read a required CArray2DParam < Type > C 2D array parameter.
Definition at line 395 of file ParamComposite.h.
template<typename Type > DMatrixParam< Type > & Util::ParamComposite::readDMatrix (std::istream & in, const char * label, DMatrix< Type > & matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
Parameters:
in input stream for reading
label Label string for new array
matrix DMatrix object
m number of rows (1st dimension)
n number of columns (2nd dimension)
isRequired Is this a required parameter?
Returns:
reference to the DMatrixParam<Type> object
Definition at line 1010 of file ParamComposite.h.
References addComponent(), isRequired(), Util::Parameter::readParam(), and setParent().
template<typename Type > DMatrixParam<Type>& Util::ParamComposite::readDMatrix (std::istream & in, const char * label, DMatrix< Type > & matrix, int m, int n) [inline]
Add and read a required DMatrix < Type > C matrix parameter.
Definition at line 420 of file ParamComposite.h.
Begin & Util::ParamComposite::readBegin (std::istream & in, const char * label, bool isRequired = true)
Add and read a class label and opening bracket.
Parameters:
in input stream for reading
label class name string, without trailing bracket
isRequired Is this the beginning of a required element?
Returns:
reference to the new Begin object
Definition at line 316 of file ParamComposite.cpp.
References addComponent(), Util::Begin::isActive(), Util::Begin::readParam(), and setParent().
Referenced by Util::SpeciesEnsemble::readParam(), McMd::MdSimulation::readParam(), McMd::McSimulation::readParam(), readParam(), and readParamOptional().
End & Util::ParamComposite::readEnd (std::istream & in)
Add and read the closing bracket.
Parameters:
in input stream for reading
Returns:
reference to the new End object
Definition at line 344 of file ParamComposite.cpp.
References addEnd(), and Util::End::readParam().
Referenced by Util::SpeciesEnsemble::readParam(), McMd::MdSimulation::readParam(), McMd::McSimulation::readParam(), readParam(), and readParamOptional().
Blank & Util::ParamComposite::readBlank (std::istream & in)
Add and read a new Blank object, representing a blank line.
Parameters:
in input stream for reading
Returns:
reference to the new Blank object
Definition at line 367 of file ParamComposite.cpp.
References addBlank(), and Util::Blank::readParam().
Referenced by McMd::RigidDisplaceMove::readParameters().
void Util::ParamComposite::loadParamComposite (Serializable::IArchive & ar, ParamComposite & child, bool next = true)
Add and load a required child ParamComposite.
Parameters:
ar input archive for loading
child child ParamComposite object
next true if the indent level is one higher than parent.
Definition at line 282 of file ParamComposite.cpp.
References addParamComposite(), and load().
Referenced by McMd::System::loadEnsembles(), McMd::System::loadFileMaster(), McMd::System::loadLinkMaster(), Util::Factory< Data >::loadObject(), McMd::HybridMdMove::loadParameters(), McMd::HybridNphMdMove::loadParameters(), McMd::DpdMove::loadParameters(), McMd::MdMove::loadParameters(), McMd::McSystem::loadParameters(), McMd::MdSystem::loadParameters(), McMd::MdSimulation::loadParameters(), McMd::McSimulation::loadParameters(), McMd::Simulation::loadParameters(), and McMd::System::loadReplicaMove().
void Util::ParamComposite::loadParamCompositeOptional (Serializable::IArchive & ar, ParamComposite & child, bool next = true)
Add and load an optional child ParamComposite if isActive.
This functional loads the isActive flag, and then calls the load function of the child iff isActive is true.
Parameters:
ar input archive for loading
child child ParamComposite object
next true if the indent level is one higher than parent.
Definition at line 293 of file ParamComposite.cpp.
References addParamComposite(), and loadOptional().
template<typename Type > ScalarParam< Type > & Util::ParamComposite::loadParameter (Serializable::IArchive & ar, const char * label, Type & value, bool isRequired)
Add and load a new ScalarParam < Type > object.
Parameters:
ar archive for loading
label Label string
value reference to the Type variable
isRequired Is this a required parameter?
Returns:
reference to the new ScalarParam < Type > object
Definition at line 854 of file ParamComposite.h.
References addComponent(), isRequired(), Util::Parameter::load(), and setParent().
Referenced by DdMd::StressAutoCorr::loadParameters(), and McMd::McMuExchange::loadParameters().
template<typename Type > ScalarParam<Type>& Util::ParamComposite::loadParameter (Serializable::IArchive & ar, const char * label, Type & value) [inline]
Add and load new required ScalarParam < Type > object.
Equivalent to loadParameter < Type > (ar, label, value, true).
Parameters:
ar archive for loading
label label string
value reference to the Type variable
Returns:
reference to the new ScalarParam < Type > object
Definition at line 509 of file ParamComposite.h.
template<typename Type > CArrayParam< Type > & Util::ParamComposite::loadCArray (Serializable::IArchive & ar, const char * label, Type * value, int n, bool isRequired)
Add a C array parameter and load its elements.
Parameters:
ar archive for loading
label label string for new array
value pointer to array
n number of elements
isRequired Is this a required parameter?
Returns:
reference to the new CArrayParam<Type> object
Definition at line 888 of file ParamComposite.h.
References addComponent(), isRequired(), Util::Parameter::load(), and setParent().
template<typename Type > CArrayParam<Type>& Util::ParamComposite::loadCArray (Serializable::IArchive & ar, const char * label, Type * value, int n) [inline]
Add and load a required CArrayParam< Type > array parameter.
Equivalent to loadCArray < Type > (ar, label, value, n, true).
Parameters:
ar archive for loading
label label string for new array
value pointer to array
n number of elements
Returns:
reference to the new CArrayParam<Type> object
Definition at line 541 of file ParamComposite.h.
template<typename Type > DArrayParam< Type > & Util::ParamComposite::loadDArray (Serializable::IArchive & ar, const char * label, DArray< Type > & array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
Parameters:
ar archive for loading
label Label string for new array
array DArray object
n number of elements (logical size)
isRequired Is this a required parameter?
Returns:
reference to the new DArrayParam<Type> object
Definition at line 922 of file ParamComposite.h.
References addComponent(), isRequired(), Util::Parameter::load(), and setParent().
Referenced by McMd::McMuExchange::loadParameters().
template<typename Type > DArrayParam<Type>& Util::ParamComposite::loadDArray (Serializable::IArchive & ar, const char * label, DArray< Type > & array, int n) [inline]
Add and load a required DArray< Type > array parameter.
Equivalent to loadDArrayParam < Type > (ar, label, array, n, true).
Parameters:
ar archive for loading
label Label string for new array
array DArray object
n number of elements (logical size)
Returns:
reference to the new DArrayParam<Type> object
Definition at line 573 of file ParamComposite.h.
template<typename Type , int N> FArrayParam< Type, N > & Util::ParamComposite::loadFArray (Serializable::IArchive & ar, const char * label, FArray< Type, N > & array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
Parameters:
ar archive for loading
label label string for new array
array FArray object
isRequired Is this a required parameter?
Returns:
reference to the new FArrayParam<Type, N> object
Definition at line 956 of file ParamComposite.h.
References addComponent(), isRequired(), Util::Parameter::load(), and setParent().
template<typename Type , int N> FArrayParam<Type, N>& Util::ParamComposite::loadFArray (Serializable::IArchive & ar, const char * label, FArray< Type, N > & array) [inline]
Add and load a required FArray < Type > array parameter.
Equivalent to loadFArrayParam < Type > (ar, label, array, true).
Parameters:
ar archive for loading
label label string for new array
array FArray object
Returns:
reference to the new FArrayParam<Type, N> object
Definition at line 603 of file ParamComposite.h.
template<typename Type > CArray2DParam< Type > & Util::ParamComposite::loadCArray2D (Serializable::IArchive & ar, const char * label, Type * value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
Parameters:
ar archive for loading
label Label string for new array
value pointer to array
m number of rows (1st dimension)
n logical number of columns (2nd dimension)
np physical number of columns (elements allocated per row)
isRequired Is this a required parameter?
Returns:
reference to the CArray2DParam<Type> object
Definition at line 991 of file ParamComposite.h.
References addComponent(), isRequired(), Util::Parameter::load(), and setParent().
template<typename Type > CArray2DParam<Type>& Util::ParamComposite::loadCArray2D (Serializable::IArchive & ar, const char * label, Type * value, int m, int n, int np) [inline]
Add and load a required < Type > matrix parameter.
Equivalent to loadCArray2DParam < Type > (ar, label, value, m, n, np, true).
Parameters:
ar archive for loading
label Label string for new array
value pointer to array
m number of rows (1st dimension)
n logical number of columns (2nd dimension)
np physical number of columns (elements allocated per row)
Returns:
reference to the CArray2DParam<Type> object
Definition at line 639 of file ParamComposite.h.
template<typename Type > DMatrixParam< Type > & Util::ParamComposite::loadDMatrix (Serializable::IArchive & ar, const char * label, DMatrix< Type > & matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
Parameters:
ar archive for loading
label Label string for new array
matrix DMatrix object
m number of rows (1st dimension)
n number of columns (2nd dimension)
isRequired Is this a required parameter?
Returns:
reference to the DMatrixParam<Type> object
Definition at line 1027 of file ParamComposite.h.
References addComponent(), isRequired(), Util::Parameter::load(), and setParent().
template<typename Type > DMatrixParam<Type>& Util::ParamComposite::loadDMatrix (Serializable::IArchive & ar, const char * label, DMatrix< Type > & matrix, int m, int n) [inline]
Add and load a required DMatrixParam < Type > parameter.
Equivalent to loadDMatrix < Type > (ar, label, value, m, n, true).
Parameters:
ar archive for loading
label Label string for new array
matrix DMatrix object
m number of rows (1st dimension)
n number of columns (2nd dimension)
Returns:
reference to the DMatrixParam<Type> object
Definition at line 673 of file ParamComposite.h.
void Util::ParamComposite::addParamComposite (ParamComposite & child, bool next = true)
Add a child ParamComposite object to the format array.
Parameters:
child child ParamComposite object
next true if the indent level is one higher than parent.
Definition at line 249 of file ParamComposite.cpp.
References addComponent(), and setParent().
Referenced by loadParamComposite(), loadParamCompositeOptional(), Util::Factory< Data >::readObject(), readParamComposite(), and readParamCompositeOptional().
Begin & Util::ParamComposite::addBegin (const char * label)
Create and add a Begin object representing a class name and bracket.
Parameters:
label class name string, without trailing bracket
Returns:
reference to the new begin object.
Definition at line 305 of file ParamComposite.cpp.
References addComponent(), and setParent().
Referenced by load().
End & Util::ParamComposite::addEnd ()
Create and add a closing bracket.
Returns:
reference to the new End object.
Definition at line 333 of file ParamComposite.cpp.
References addComponent(), and setParent().
Referenced by load(), and readEnd().
Blank & Util::ParamComposite::addBlank ()
Create and add a new Blank object, representing a blank line.
Returns:
reference to the new Blank object
Definition at line 356 of file ParamComposite.cpp.
References addComponent(), and setParent().
Referenced by readBlank().
std::string Util::ParamComposite::className () const [inline]
Get class name string.
Reimplemented in Inter::CosineAngle, Inter::CosineSqAngle, Inter::HarmonicAngle, Inter::LamellarOrderingExternal, Inter::MultiHarmonicDihedral, Inter::CosineDihedral, Inter::LocalLamellarOrderingExternal, Inter::GeneralPeriodicExternal, Inter::NucleationExternal, Inter::PeriodicExternal, Inter::SimplePeriodicExternal, Inter::OrthoBoxExternal, Inter::BoxExternal, and Inter::SlitExternal.
Definition at line 808 of file ParamComposite.h.
Referenced by Util::Manager< Data >::beginReadManager(), loadOptional(), McMd::MdSystem::loadParameters(), McMd::System::loadPerturbation(), McMd::MdSimulation::readParam(), McMd::McSimulation::readParam(), McMd::MdSystem::readParameters(), McMd::System::readPerturbation(), McMd::MdSystem::saveParameters(), McMd::System::savePerturbation(), and setClassName().
bool Util::ParamComposite::isRequired () const [inline]
Is this ParamComposite required in the input file?
Definition at line 814 of file ParamComposite.h.
Referenced by loadCArray(), loadCArray2D(), loadDArray(), loadDMatrix(), loadFArray(), loadParameter(), read(), readCArray(), readCArray2D(), readDArray(), readDMatrix(), readFArray(), Tools::Configuration::readParameters(), and setIsRequired().
bool Util::ParamComposite::isActive () const [inline]
Is this parameter active?
Definition at line 820 of file ParamComposite.h.
Referenced by McMd::LinkMaster::removeLink(), and setIsActive().
void Util::ParamComposite::setClassName (const char * className) [protected]
Set class name string.
Should be set in subclass constructor.
Definition at line 377 of file ParamComposite.cpp.
References className().
Referenced by Tools::AnalyzerManager::AnalyzerManager(), McMd::AnalyzerManager::AnalyzerManager(), DdMd::AnalyzerManager::AnalyzerManager(), DdMd::AnglePotential::AnglePotential(), McMd::AnglePotential::AnglePotential(), DdMd::AngleStorage::AngleStorage(), DdMd::AtomCollector::AtomCollector(), McMd::AtomDisplaceMove::AtomDisplaceMove(), DdMd::AtomDistributor::AtomDistributor(), Tools::AtomMSD::AtomMSD(), McMd::AtomMSD::AtomMSD(), DdMd::AtomStorage::AtomStorage(), Util::AutoCorr< Data, Product >::AutoCorr(), DdMd::AutoCorrAnalyzer< Data, Product >::AutoCorrAnalyzer(), Util::AutoCorrArray< Data, Product >::AutoCorrArray(), Util::Average::Average(), McMd::BennettsMethod::BennettsMethod(), McMd::BlockRadiusGyration::BlockRadiusGyration(), McMd::BondLengthDist::BondLengthDist(), DdMd::BondPotential::BondPotential(), McMd::BondPotential::BondPotential(), DdMd::BondStorage::BondStorage(), DdMd::BondTensorAutoCorr::BondTensorAutoCorr(), McMd::BoundaryAverage::BoundaryAverage(), Util::BoundaryEnsemble::BoundaryEnsemble(), Inter::BoxExternal::BoxExternal(), DdMd::Buffer::Buffer(), McMd::CfbDoubleRebridgeMove::CfbDoubleRebridgeMove(), McMd::CfbEndMove::CfbEndMove(), McMd::CfbRebridgeMove::CfbRebridgeMove(), McMd::CfbReptationMove::CfbReptationMove(), McMd::CfbRingRebridgeMove::CfbRingRebridgeMove(), McMd::ComMSD::ComMSD(), Inter::CompensatedPair< BarePair, LinkPotential >::CompensatedPair(), Inter::CompositeBond< BareBond, BarePair >::CompositeBond(), McMd::CompositionProfile::CompositionProfile(), DdMd::ConfigIo::ConfigIo(), Tools::ConfigReader::ConfigReader(), Tools::Configuration::Configuration(), Tools::ConfigWriter::ConfigWriter(), McMd::ConfigWriter::ConfigWriter(), DdMd::ConfigWriter::ConfigWriter(), Inter::CosineAngle::CosineAngle(), Inter::CosineDihedral::CosineDihedral(), Inter::CosineSqAngle::CosineSqAngle(), DdMd::DdMdConfigIo::DdMdConfigIo(), Tools::DdMdConfigReader::DdMdConfigReader(), Tools::DdMdConfigWriter::DdMdConfigWriter(), DdMd::DdMdOrderedConfigIo::DdMdOrderedConfigIo(), Tools::DdMdTrajectoryReader::DdMdTrajectoryReader(), McMd::Diblock::Diblock(), DdMd::DihedralPotential::DihedralPotential(), DdMd::DihedralStorage::DihedralStorage(), Util::Distribution::Distribution(), DdMd::Domain::Domain(), McMd::DpdMove::DpdMove(), Inter::DpdPair::DpdPair(), McMd::EndSwapMove::EndSwapMove(), Util::EnergyEnsemble::EnergyEnsemble(), DdMd::ExternalEnergyAverage::ExternalEnergyAverage(), DdMd::ExternalPotential::ExternalPotential(), Inter::FeneBond::FeneBond(), Util::FileMaster::FileMaster(), Inter::GeneralPeriodicExternal::GeneralPeriodicExternal(), DdMd::GroupCollector< N >::GroupCollector(), DdMd::GroupDistributor< N >::GroupDistributor(), Inter::HarmonicAngle::HarmonicAngle(), Inter::HarmonicBond::HarmonicBond(), Inter::HarmonicL0Bond::HarmonicL0Bond(), McMd::HomopolymerSemiGrandMove::HomopolymerSemiGrandMove(), McMd::HomoRing::HomoRing(), Tools::HoomdConfigReader::HoomdConfigReader(), Tools::HoomdConfigWriter::HoomdConfigWriter(), McMd::HybridMdMove::HybridMdMove(), McMd::HybridNphMdMove::HybridNphMdMove(), Util::IntDistribution::IntDistribution(), McMd::IntraPairAutoCorr::IntraPairAutoCorr(), McMd::IntraStructureFactor::IntraStructureFactor(), McMd::IntraStructureFactorGrid::IntraStructureFactorGrid(), Inter::LamellarOrderingExternal::LamellarOrderingExternal(), Tools::LammpsDumpReader::LammpsDumpReader(), McMd::LinearRouseAutoCorr::LinearRouseAutoCorr(), McMd::LinkMaster::LinkMaster(), McMd::LinkPotentialImpl< Interaction >::LinkPotentialImpl(), Inter::LJPair::LJPair(), Inter::LocalLamellarOrderingExternal::LocalLamellarOrderingExternal(), DdMd::LogEnergy::LogEnergy(), McMd::McBondEnergyAverage::McBondEnergyAverage(), McMd::McEnergyAverage::McEnergyAverage(), McMd::McEnergyOutput::McEnergyOutput(), McMd::McExternalEnergyAverage::McExternalEnergyAverage(), McMd::McIntraBondStressAutoCorr::McIntraBondStressAutoCorr(), McMd::McIntraBondTensorAutoCorr::McIntraBondTensorAutoCorr(), McMd::McMoveManager::McMoveManager(), McMd::McMuExchange::McMuExchange(), McMd::McPairEnergyAverage::McPairEnergyAverage(), McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >::McPairExternalPerturbation(), McMd::McPairPerturbation< Interaction >::McPairPerturbation(), McMd::McPairPotential::McPairPotential(), McMd::McPressureAverage::McPressureAverage(), McMd::McSimulation::McSimulation(), McMd::McSystem::McSystem(), McMd::McVirialStressTensorAverage::McVirialStressTensorAverage(), McMd::MdIntraBondStressAutoCorr::MdIntraBondStressAutoCorr(), McMd::MdIntraBondTensorAutoCorr::MdIntraBondTensorAutoCorr(), McMd::MdKineticEnergyAverage::MdKineticEnergyAverage(), McMd::MdMove::MdMove(), McMd::MdPairEnergyCoefficients::MdPairEnergyCoefficients(), McMd::MdPairPotential::MdPairPotential(), McMd::MdPotentialEnergyAverage::MdPotentialEnergyAverage(), McMd::MdSimulation::MdSimulation(), McMd::MdStressAutoCorr::MdStressAutoCorr(), McMd::MdSystem::MdSystem(), McMd::MdVirialStressTensorAverage::MdVirialStressTensorAverage(), DdMd::ModifierManager::ModifierManager(), Inter::MultiHarmonicDihedral::MultiHarmonicDihedral(), DdMd::NphIntegrator::NphIntegrator(), McMd::NphIntegrator::NphIntegrator(), DdMd::NptIntegrator::NptIntegrator(), Inter::NucleationExternal::NucleationExternal(), DdMd::NveIntegrator::NveIntegrator(), McMd::NveVvIntegrator::NveVvIntegrator(), McMd::NvtDpdVvIntegrator::NvtDpdVvIntegrator(), DdMd::NvtIntegrator::NvtIntegrator(), McMd::NvtNhIntegrator::NvtNhIntegrator(), DdMd::OrderParamNucleation::OrderParamNucleation(), Inter::OrthoBoxExternal::OrthoBoxExternal(), DdMd::OutputBoxdim::OutputBoxdim(), DdMd::OutputEnergy::OutputEnergy(), DdMd::OutputPairEnergies::OutputPairEnergies(), DdMd::OutputPressure::OutputPressure(), DdMd::OutputStressTensor::OutputStressTensor(), DdMd::OutputTemperature::OutputTemperature(), DdMd::PairEnergyAverage::PairEnergyAverage(), McMd::PairList::PairList(), DdMd::PairPotential::PairPotential(), Inter::PeriodicExternal::PeriodicExternal(), McMd::Perturbation::Perturbation(), McMd::PerturbDerivative::PerturbDerivative(), DdMd::Potential::Potential(), Tools::Processor::Processor(), Tools::ProcessorAnalyzerManager::ProcessorAnalyzerManager(), Util::RadialDistribution::RadialDistribution(), McMd::RadiusGyration::RadiusGyration(), Util::Random::Random(), McMd::RDF::RDF(), McMd::ReplicaMove::ReplicaMove(), McMd::RigidDisplaceMove::RigidDisplaceMove(), McMd::RingOctaRebridgeMove::RingOctaRebridgeMove(), McMd::RingRouseAutoCorr::RingRouseAutoCorr(), McMd::RingTetraRebridgeMove::RingTetraRebridgeMove(), McMd::SemiGrandDistribution::SemiGrandDistribution(), DdMd::SerializeConfigIo::SerializeConfigIo(), Inter::SimplePeriodicExternal::SimplePeriodicExternal(), McMd::Simulation::Simulation(), Inter::SlitExternal::SlitExternal(), McMd::Species::Species(), McMd::SpeciesManager::SpeciesManager(), DdMd::StressAutoCorr::StressAutoCorr(), DdMd::StressAutoCorrelation::StressAutoCorrelation(), McMd::StructureFactor::StructureFactor(), DdMd::StructureFactor::StructureFactor(), McMd::StructureFactorGrid::StructureFactorGrid(), DdMd::StructureFactorGrid::StructureFactorGrid(), McMd::StructureFactorP::StructureFactorP(), McMd::StructureFactorPGrid::StructureFactorPGrid(), Tools::TrajectoryReader::TrajectoryReader(), Tools::TrajectoryWriter::TrajectoryWriter(), DdMd::TrajectoryWriter::TrajectoryWriter(), McMd::TypeDistribution::TypeDistribution(), DdMd::VanHove::VanHove(), McMd::VanHove::VanHove(), DdMd::VirialStressTensor::VirialStressTensor(), and DdMd::VirialStressTensorAverage::VirialStressTensorAverage().
void Util::ParamComposite::setIsRequired (bool isRequired) [protected]
Set or unset the isActive flag.
Required to re-implement readParam[Optional].
Parameters:
isRequired flag to set true or false.
Definition at line 383 of file ParamComposite.cpp.
References isRequired().
void Util::ParamComposite::setIsActive (bool isActive) [protected]
Set or unset the isActive flag.
Required to re-implement readParam[Optional].
Parameters:
isActive flag to set true or false.
Definition at line 394 of file ParamComposite.cpp.
References isActive(), and UTIL_THROW.
void Util::ParamComposite::setParent (ParamComponent & param, bool next = true) [protected]
Set this to the parent of a child component.
This function sets the indent and (ifdef UTIL_MPI) the ioCommunicator of the child component.
Parameters:
param child ParamComponent
next if true, set indent level one higher than for parent.
Definition at line 224 of file ParamComposite.cpp.
References Util::MpiFileIo::hasIoCommunicator(), Util::MpiFileIo::ioCommunicator(), Util::ParamComponent::setIndent(), and Util::MpiFileIo::setIoCommunicator().
Referenced by addBegin(), addBlank(), addEnd(), addParamComposite(), loadCArray(), loadCArray2D(), loadDArray(), loadDMatrix(), loadFArray(), loadParameter(), read(), readBegin(), readCArray(), readCArray2D(), readDArray(), readDMatrix(), and readFArray().
void Util::ParamComposite::addComponent (ParamComponent & param, bool isLeaf = true) [protected]
Add a new ParamComponent object to the format array.
Parameters:
param Parameter object
isLeaf Is this a leaf or a ParamComposite node?
Definition at line 237 of file ParamComposite.cpp.
Referenced by addBegin(), addBlank(), addEnd(), addParamComposite(), loadCArray(), loadCArray2D(), loadDArray(), loadDMatrix(), loadFArray(), loadParameter(), read(), readBegin(), readCArray(), readCArray2D(), readDArray(), readDMatrix(), and readFArray().
The documentation for this class was generated from the following files:
ParamComposite.h
ParamComposite.cpp