Simpatico: Inter::OrthoBoxExternal Class Reference
Inter::OrthoBoxExternal Class Reference
External Interactions
Detailed Description
A repulsive 9-3 potential confining particles inside an orthogonal box along directions specified by indConfine_.
indConfine_ = 0: x & y & z directions = 1: y & z directions = 2: z directions = 3: no confinement
4 epsilon pi rho / sigma^9 sigma^6 25 \ u = --------------— | ------— - 7.5 -----— + -------— | 45 sigma^(-3) \ r^9 r^6 sqrt(10) /
The coefficients are obtained by integrating the repulsive LJPair potential in a half space with default density rho = 0.7. Member variables include strength of the potential epsilon, the range of interaction sigma, and the cutoff length 0.4^(1/6) = 0.85837422. Member functions evaluate energy and force for individual particles. The internal cutoff 0.506079 = 0.129615^(1/3) is set to yield a cutoff potential of 80 for the default density 0.7.
The potential is independent on the type of atoms.
Definition at line 46 of file OrthoBoxExternal.h.
#include <OrthoBoxExternal.h>
Public Member Functions
OrthoBoxExternal ()
Default constructor.
OrthoBoxExternal (const OrthoBoxExternal &other)
Copy constructor.
OrthoBoxExternal & operator= (const OrthoBoxExternal &other)
Assignment.
Mutators
void setNAtomType (int nAtomType)
Set nAtomType value.
void setBoundary (Boundary &boundary)
Set pointer to Boundary.
void setExternalParameter (double externalParameter)
Sets external parameter.
void readParameters (std::istream &in)
Read potential parameters, and initialize other variables.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
Accessors
std::string className () const
Return name string "LJPair" for this evaluator class.
double externalParameter () const
Returns external parameter.
double energy (double d, int i) const
Returns external potential energy of a particle of type i.
double energy (const Vector &position, int i) const
Returns external potential energy of a single particle.
double forceScalar (double d, int i) const
Returns magnitude of the repulsive force.
void getForce (const Vector &position, int type, Vector &force) const
Returns force caused by the external potential.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
std::string className () const
Get class name string.
virtual void readParam (std::istream &in)
Read a parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an archive.
void resetParam ()
Resets ParamComposite to its empty state.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add a new Param < Type > object, and read its value.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add a C array parameter, and read its elements.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and read its elements.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n)
Add and read a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
Begin & readBegin (std::istream &in, const char *label)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a child ParamComposite.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add a new Param < Type > object, and load its value.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add a C array parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and load its elements.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n)
Add and load a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a DMatrix < Type > C two-dimensional matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
template<typename Type >
ScalarParam< Type > & add (const char *label, Type &value)
Add a new Param < Type > object to the format array.
template<typename Type >
CArrayParam< Type > & addCArray (const char *label, Type *value, int n)
Add a C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (const char *label, DArray< Type > &array, int n)
Add a DArray<Type> parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (const char *label, FArray< Type, N > &array)
Add a FArray<Type> parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (const char *label, Type *value, int m, int n)
Add a C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & addDMatrix (const char *label, DMatrix< Type > &matrix, int m, int n)
Add a C two-dimensional array parameter.
Begin & addBegin (const char *label)
Add a class label and opening bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Add a new Blank object, representing a blank line.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have a communicator?
MPI::Intracomm & ioCommunicator () const
Get the communicator.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
Constructor & Destructor Documentation
Inter::OrthoBoxExternal::OrthoBoxExternal ()
Default constructor.
Definition at line 23 of file OrthoBoxExternal.cpp.
References Util::ParamComposite::setClassName().
Inter::OrthoBoxExternal::OrthoBoxExternal (const OrthoBoxExternal & other)
Copy constructor.
Definition at line 33 of file OrthoBoxExternal.cpp.
Member Function Documentation
OrthoBoxExternal & Inter::OrthoBoxExternal::operator= (const OrthoBoxExternal & other)
Assignment.
Definition at line 48 of file OrthoBoxExternal.cpp.
void Inter::OrthoBoxExternal::setNAtomType (int nAtomType)
Set nAtomType value.
Parameters
nAtomType number of atom types.
Definition at line 65 of file OrthoBoxExternal.cpp.
References UTIL_THROW.
void Inter::OrthoBoxExternal::setBoundary (Boundary & boundary)
Set pointer to Boundary.
Parameters
boundary Boundary object (used to calculate distances).
Definition at line 79 of file OrthoBoxExternal.cpp.
void Inter::OrthoBoxExternal::setExternalParameter (double externalParameter)
Sets external parameter.
Set epsilon to the externalParameter.
Parameters
externalParameter external parameter of system
Definition at line 85 of file OrthoBoxExternal.cpp.
References externalParameter(), and UTIL_THROW.
void Inter::OrthoBoxExternal::readParameters (std::istream & in) virtual
Read potential parameters, and initialize other variables.
Precondition
nAtomType must have been set, by calling setNAtomType().
Boundary must have been set, by calling setBoundary().
Parameters
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 98 of file OrthoBoxExternal.cpp.
References Util::Dimension, and UTIL_THROW.
void Inter::OrthoBoxExternal::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 126 of file OrthoBoxExternal.cpp.
References Util::Dimension, and UTIL_THROW.
void Inter::OrthoBoxExternal::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 150 of file OrthoBoxExternal.cpp.
std::string Inter::OrthoBoxExternal::className () const
Return name string "LJPair" for this evaluator class.
Return name string "OrthoBoxExternal" for this evaluator class.
Definition at line 172 of file OrthoBoxExternal.cpp.
double Inter::OrthoBoxExternal::externalParameter () const
Returns external parameter.
Return epsilon for externalParameter.
Returns
external parameter
Definition at line 164 of file OrthoBoxExternal.cpp.
Referenced by setExternalParameter().
double Inter::OrthoBoxExternal::energy (double d, int i) const inline
Returns external potential energy of a particle of type i.
Parameters
d distance to the nearest boundary
i type of particle (not used)
Returns
external potential energy
Definition at line 214 of file OrthoBoxExternal.h.
double Inter::OrthoBoxExternal::energy (const Vector & position, int i) const inline
Returns external potential energy of a single particle.
Parameters
position atomic position Vector
i atom type.
Returns
external potential energy
Definition at line 230 of file OrthoBoxExternal.h.
References Util::Dimension.
double Inter::OrthoBoxExternal::forceScalar (double d, int i) const inline
Returns magnitude of the repulsive force.
Multiply this quantity by the components of the separation vector to obtain the force vector.
Parameters
d distance from the nearest wall.
i atom type id (not used)
Returns
force scalar
Definition at line 247 of file OrthoBoxExternal.h.
void Inter::OrthoBoxExternal::getForce (const Vector & position, int type, Vector & force) const inline
Returns force caused by the external potential.
Parameters
position atom position
type atom type id
force force on the atom (on output)
Definition at line 264 of file OrthoBoxExternal.h.
References Util::Dimension, and Util::Vector::zero().
The documentation for this class was generated from the following files:
OrthoBoxExternal.h
OrthoBoxExternal.cpp