Simpatico: McMd::MdDiagnosticFactory Class Reference
McMd::MdDiagnosticFactory Class Reference
Diagnostics
Detailed Description
DiagnosticFactory for an MdSimulation.
Definition at line 29 of file MdDiagnosticFactory.h.
#include <MdDiagnosticFactory.h>
Public Member Functions
MdDiagnosticFactory (MdSimulation &simulation, MdSystem &system)
Constructor.
virtual Diagnostic * factory (const std::string &className) const
Return pointer to a new Diagnostic object.
Protected Member Functions
MdSystem & system () const
Return reference to parent MdSystem.
MdSimulation & simulation () const
Return reference to parent MdSimulation.
Constructor & Destructor Documentation
McMd::MdDiagnosticFactory::MdDiagnosticFactory (MdSimulation & simulation, MdSystem & system)
Constructor.
Parameters:
simulation parent simulation
system parent system
Definition at line 42 of file MdDiagnosticFactory.cpp.
References Util::Factory< Diagnostic >::trySubfactories().
Member Function Documentation
Diagnostic * McMd::MdDiagnosticFactory::factory (const std::string & className) const [virtual]
Return pointer to a new Diagnostic object.
Parameters:
className name of a subclass of Diagnostic.
Returns:
base class pointer to a new instance of className.
Implements Util::Factory< Diagnostic >.
Definition at line 52 of file MdDiagnosticFactory.cpp.
References system().
MdSystem& McMd::MdDiagnosticFactory::system () const [inline, protected]
Return reference to parent MdSystem.
Definition at line 55 of file MdDiagnosticFactory.h.
Referenced by factory().
MdSimulation& McMd::MdDiagnosticFactory::simulation () const [inline, protected]
Return reference to parent MdSimulation.
Definition at line 61 of file MdDiagnosticFactory.h.
The documentation for this class was generated from the following files:
MdDiagnosticFactory.h
MdDiagnosticFactory.cpp