Simpatico: McMd::StressCalculator Class Reference
McMd::StressCalculator Class Reference
McMd namespace » Potential Energies
Detailed Description
Interface for a stress calculator.
Definition at line 28 of file StressCalculator.h.
#include <StressCalculator.h>
Public Member Functions
virtual void computeStress ()
Compute and store the stress tensor.
virtual void unsetStress ()
Mark the stress as unknown.
void computeStress (Tensor &stress)
Get pair stress tensor.
void computeStress (Vector &pressures)
Get the xx, yy, zz non-Coulomb pair pressures.
void computeStress (double &pressure)
Get the scalar pressure.
bool createsStress () const
Return false if subclass does not generate stress.
Protected Member Functions
StressCalculator (bool createsStress=true)
Constructor (protected to prevent direct instantiation).
Constructor & Destructor Documentation
McMd::StressCalculator::StressCalculator (bool createsStress = true) protected
Constructor (protected to prevent direct instantiation).
Derived class constructor must set hasStress true or false.
Definition at line 19 of file StressCalculator.cpp.
Member Function Documentation
virtual void McMd::StressCalculator::computeStress () inline virtual
Compute and store the stress tensor.
Default implementation throws an Exception, to allow testing and graceful failure potentials that do not create stress.
Reimplemented in McMd::AnglePotentialImpl< Interaction >, McMd::DihedralPotentialImpl< Interaction >, McMd::MdPairPotentialImpl< Interaction >, McMd::MdEwaldPairPotentialImpl< Interaction >, McMd::McPairPotentialImpl< Interaction >, McMd::BondPotentialImpl< Interaction >, and McMd::LinkPotentialImpl< Interaction >.
Definition at line 40 of file StressCalculator.h.
References UTIL_THROW.
Referenced by computeStress(), McMd::MdSystem::kineticEnergy(), and McMd::McSystem::unsetPotentialEnergies().
void McMd::StressCalculator::unsetStress () virtual
Mark the stress as unknown.
Reimplemented in McMd::MdEwaldPairPotentialImpl< Interaction >.
Definition at line 32 of file StressCalculator.cpp.
Referenced by McMd::McSystem::unsetVirialStress(), and McMd::MdSystem::unsetVirialStress().
void McMd::StressCalculator::computeStress (Tensor & stress)
Get pair stress tensor.
If necessary, this function calls computeStress() before accessing value.
Parameters
stress (output) pair stress tensor
Definition at line 38 of file StressCalculator.cpp.
References computeStress(), and UTIL_CHECK.
void McMd::StressCalculator::computeStress (Vector & pressures)
Get the xx, yy, zz non-Coulomb pair pressures.
If necessary, this function calls computeStress() before accessing values.
Parameters
pressures (output) diagonal pair stress components
Definition at line 54 of file StressCalculator.cpp.
References computeStress(), Util::Dimension, and UTIL_CHECK.
void McMd::StressCalculator::computeStress (double & pressure)
Get the scalar pressure.
If necessary, this function calls computeStress() before accessing values.
Parameters
pressure (output) scalar pair pressure.
Definition at line 72 of file StressCalculator.cpp.
References computeStress(), Util::Dimension, and UTIL_CHECK.
bool McMd::StressCalculator::createsStress () const
Return false if subclass does not generate stress.
Definition at line 26 of file StressCalculator.cpp.
The documentation for this class was generated from the following files:
StressCalculator.h
StressCalculator.cpp