Simpatico: DdMd::VanHove Class Reference
DdMd::VanHove Class Reference
DdMd namespace » Analyzers » Scattering Analyzers
Detailed Description
Evaluates the van Hove function S(k,t) for one or more wavevector k.
The van Hove function S(k,t) is defined here as an expectation value
where V is system volume, and is given by a sum
over all atoms in the system, where is a user-specified coefficient for monomers of type a.
The Van Hove class can calculate S(k,t) for a list of wavevectors. Each wavevector is specified as an IntVector containing integer indices. These indices are the coefficients in an expansion of a reciprocal lattice wavevector in terms of recprocal lattice basis vectors.
In a system with nAtomType = 2, with two monomer types 0 and 1, the parameter file input for calculating the autocorrelation of an order parameter for 5 wavevectors along the x axis in an orthorhombic unit cell might look like this:
VanHove{
   interval                      1000
   outputFileName             VanHove
   atomTypeCoeffs              1.0000      -1.0000
   nBuffer                        100
   nWave                            5
   waveIntVectors     8      0      0
                      9      0      0
                     10      0      0
                     11      0      0
                     12      0      0
}
At the end of a simulation, all of the autocorrelation functions are output in a file with a suffix *.dat. Each line in this file contains the 3 Miller indices of a wavevector, the absolute magnitude of the wavevector, and a list of nAtomTypeIdPair structure factor values for the wavevector, one for each atomTypeId pair.
See also
param file format
Definition at line 77 of file ddMd/analyzers/scattering/VanHove.h.
#include <VanHove.h>
Public Member Functions
VanHove (Simulation &simulation)
Constructor.
~VanHove ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to an archive.
virtual void clear ()
Clear accumulators.
void sample (long iStep)
Add particle pairs to VanHove histogram.
virtual void output ()
Output results to predefined output file.
Public Member Functions inherited from DdMd::Analyzer
Analyzer (Simulation &simulation)
Constructor.
virtual ~Analyzer ()
Destructor.
virtual void setup ()
Setup before simulation.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
void makeWaveVectors ()
Update wavevectors.
Protected Member Functions inherited from DdMd::Analyzer
void readInterval (std::istream &in)
Read parameter interval from file.
void loadInterval (Serializable::IArchive &ar)
Load parameter interval from input archive.
void saveInterval (Serializable::OArchive &ar)
Save interval parameter to an archive.
void readOutputFileName (std::istream &in)
Read outputFileName from file.
void loadOutputFileName (Serializable::IArchive &ar)
Load output file name to an archive.
void saveOutputFileName (Serializable::OArchive &ar)
Save output file name to an archive.
Simulation & simulation ()
Get the parent Simulation by reference.
const std::string & outputFileName () const
Return outputFileName string.
std::string outputFileName (const std::string &suffix) const
Return outputFileName string with added suffix.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
std::ofstream outputFile_
Output file stream.
DArray< AutoCorr< std::complex< double >, std::complex< double > > > accumulators_
Autocorrelation function accumulators.
DArray< std::complex< double > > fourierModes_
Fourier modes. First index is wavevector, second is atom type.
DArray< IntVector > waveIntVectors_
Array of miller index vectors for wavevectors.
DArray< Vector > waveVectors_
Array of wave vectors.
DArray< double > atomTypeCoeffs_
Array of coefficients for atom types.
int nWave_
Number of wavevectors.
int nBuffer_
Number of samples stored in history buffer.
int nSample_
Number of samples thus far.
int nAtomType_
Number of atom types, copied from Simulation::nAtomType().
bool isInitialized_
Has readParam been called?
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from DdMd::Analyzer
static void initStatic ()
Define and initialize baseInterval.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Public Attributes inherited from DdMd::Analyzer
static long baseInterval = 1
The interval for an Analyzer must be a multiple of baseInterval.
Constructor & Destructor Documentation
DdMd::VanHove::VanHove (Simulation & simulation)
Constructor.
Parameters
simulation reference to parent Simulation object
Definition at line 35 of file ddMd/analyzers/scattering/VanHove.cpp.
References Util::ParamComposite::setClassName().
DdMd::VanHove::~VanHove ()
Destructor.
Definition at line 43 of file ddMd/analyzers/scattering/VanHove.cpp.
Member Function Documentation
void DdMd::VanHove::readParameters (std::istream & in) virtual
Read parameters from file.
Input format:
int interval sampling interval
string outputFileName output file base name
DArray<double> atomTypeCoeffs array of type coefficients
int nBuffer number of samples in buffer
int nWave number of wavevectors
DArray<IntVector> waveIntVectors IntVector wavevectors
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 49 of file ddMd/analyzers/scattering/VanHove.cpp.
References accumulators_, Util::DArray< Data >::allocate(), atomTypeCoeffs_, fourierModes_, isInitialized_, DdMd::Simulation::nAtomType(), nAtomType_, nBuffer_, nWave_, DdMd::Analyzer::readInterval(), DdMd::Analyzer::readOutputFileName(), DdMd::Analyzer::simulation(), waveIntVectors_, and waveVectors_.
void DdMd::VanHove::loadParameters (Serializable::IArchive & ar) virtual
Load state from an archive.
Parameters
ar loading (input) archive.
Reimplemented from DdMd::Analyzer.
Definition at line 79 of file ddMd/analyzers/scattering/VanHove.cpp.
References accumulators_, Util::DArray< Data >::allocate(), atomTypeCoeffs_, fourierModes_, isInitialized_, DdMd::Analyzer::loadInterval(), DdMd::Analyzer::loadOutputFileName(), DdMd::Simulation::nAtomType(), nAtomType_, nBuffer_, nSample_, nWave_, DdMd::Analyzer::simulation(), waveIntVectors_, and waveVectors_.
void DdMd::VanHove::save (Serializable::OArchive & ar) virtual
Save state to an archive.
Parameters
ar saving (output) archive.
Reimplemented from DdMd::Analyzer.
Definition at line 110 of file ddMd/analyzers/scattering/VanHove.cpp.
References accumulators_, atomTypeCoeffs_, nBuffer_, nSample_, nWave_, DdMd::Analyzer::saveInterval(), DdMd::Analyzer::saveOutputFileName(), DdMd::Analyzer::simulation(), and waveIntVectors_.
void DdMd::VanHove::clear () virtual
Clear accumulators.
Reimplemented from DdMd::Analyzer.
Definition at line 129 of file ddMd/analyzers/scattering/VanHove.cpp.
References accumulators_, isInitialized_, nBuffer_, nSample_, nWave_, DdMd::Analyzer::simulation(), and UTIL_THROW.
void DdMd::VanHove::sample (long iStep) virtual
Add particle pairs to VanHove histogram.
Increment Structure Factor.
Parameters
iStep step counter
Implements DdMd::Analyzer.
Definition at line 145 of file ddMd/analyzers/scattering/VanHove.cpp.
References accumulators_, DdMd::Simulation::atomStorage(), atomTypeCoeffs_, DdMd::AtomStorage::begin(), DdMd::Domain::communicator(), DdMd::Simulation::domain(), Util::Vector::dot(), fourierModes_, Util::Constants::Im, DdMd::Analyzer::isAtInterval(), makeWaveVectors(), Util::PArrayIterator< Data >::notEnd(), nSample_, nWave_, Util::product(), DdMd::Analyzer::simulation(), and waveVectors_.
void DdMd::VanHove::output () virtual
Output results to predefined output file.
Reimplemented from DdMd::Analyzer.
Definition at line 227 of file ddMd/analyzers/scattering/VanHove.cpp.
References accumulators_, Util::Dimension, DdMd::Simulation::fileMaster(), nWave_, Util::FileMaster::openOutputFile(), outputFile_, DdMd::Analyzer::outputFileName(), DdMd::Analyzer::simulation(), waveIntVectors_, waveVectors_, and Util::ParamComposite::writeParam().
void DdMd::VanHove::makeWaveVectors () protected
Update wavevectors.
Calculate floating point wavevectors.
Definition at line 210 of file ddMd/analyzers/scattering/VanHove.cpp.
References DdMd::Simulation::boundary(), Util::Dimension, nWave_, Simp::OrthorhombicBoundary::reciprocalBasisVector(), DdMd::Analyzer::simulation(), waveIntVectors_, waveVectors_, and Util::Vector::Zero.
Referenced by sample().
Member Data Documentation
std::ofstream DdMd::VanHove::outputFile_ protected
Output file stream.
Definition at line 143 of file ddMd/analyzers/scattering/VanHove.h.
Referenced by output().
DArray< AutoCorr< std::complex<double>, std::complex<double> > > DdMd::VanHove::accumulators_ protected
Autocorrelation function accumulators.
Definition at line 147 of file ddMd/analyzers/scattering/VanHove.h.
Referenced by clear(), loadParameters(), output(), readParameters(), sample(), and save().
DArray< std::complex<double> > DdMd::VanHove::fourierModes_ protected
Fourier modes. First index is wavevector, second is atom type.
Definition at line 150 of file ddMd/analyzers/scattering/VanHove.h.
Referenced by loadParameters(), readParameters(), and sample().
DArray<IntVector> DdMd::VanHove::waveIntVectors_ protected
Array of miller index vectors for wavevectors.
Definition at line 155 of file ddMd/analyzers/scattering/VanHove.h.
Referenced by loadParameters(), makeWaveVectors(), output(), readParameters(), and save().
DArray<Vector> DdMd::VanHove::waveVectors_ protected
Array of wave vectors.
Definition at line 158 of file ddMd/analyzers/scattering/VanHove.h.
Referenced by loadParameters(), makeWaveVectors(), output(), readParameters(), and sample().
DArray<double> DdMd::VanHove::atomTypeCoeffs_ protected
Array of coefficients for atom types.
Definition at line 161 of file ddMd/analyzers/scattering/VanHove.h.
Referenced by loadParameters(), readParameters(), sample(), and save().
int DdMd::VanHove::nWave_ protected
Number of wavevectors.
Definition at line 164 of file ddMd/analyzers/scattering/VanHove.h.
Referenced by clear(), loadParameters(), makeWaveVectors(), output(), readParameters(), sample(), and save().
int DdMd::VanHove::nBuffer_ protected
Number of samples stored in history buffer.
Definition at line 167 of file ddMd/analyzers/scattering/VanHove.h.
Referenced by clear(), loadParameters(), readParameters(), and save().
int DdMd::VanHove::nSample_ protected
Number of samples thus far.
Definition at line 170 of file ddMd/analyzers/scattering/VanHove.h.
Referenced by clear(), loadParameters(), sample(), and save().
int DdMd::VanHove::nAtomType_ protected
Number of atom types, copied from Simulation::nAtomType().
Definition at line 173 of file ddMd/analyzers/scattering/VanHove.h.
Referenced by loadParameters(), and readParameters().
bool DdMd::VanHove::isInitialized_ protected
Has readParam been called?
Definition at line 176 of file ddMd/analyzers/scattering/VanHove.h.
Referenced by clear(), loadParameters(), and readParameters().
The documentation for this class was generated from the following files:
ddMd/analyzers/scattering/VanHove.h
ddMd/analyzers/scattering/VanHove.cpp