Simpatico: DdMd::AtomDistributor Class Reference
DdMd::AtomDistributor Class Reference
MPI Communication
Detailed Description
Class for distributing Atoms among processors.
A AtomDistributor is used to distribute items among processors during startup, when the master process must read a configuration file.
Usage:
    AtomDistributor   distributor;
    AtomStorage   storage;
    Atom*         ptr;
    std::ifstream file
    if (rank = 0) {  // If master processor
       distributor.setup();
       // Read from file
       for (i = 0; i < nAtom; ++i) {
           ptr = distributor.newAtomPtr();
           // Read properties of Atom *ptr from file
           file >> ptr->position();
           // ...
           // Cache active atom *ptr for sending.
           distributor.addAtom(storage);
       }
       // Send all remaining.
       distributor.send();
    } else { // If not master processor
       distributor.receive(storage);
    }
The addAtom(storage) method can send items if required by memory limits, and the send() method then sends all remaining atoms.
Definition at line 75 of file AtomDistributor.h.
#include <AtomDistributor.h>
Public Member Functions
AtomDistributor ()
Constructor.
~AtomDistributor ()
Destructor.
void associate (Domain &domain, Boundary &boundary, AtomStorage &storage, Buffer &buffer)
Set pointers to boundary, domain, and buffer.
void initialize (int cacheCapacity=100)
Set cacheCapacity, allocate memory and initialize object.
virtual void readParameters (std::istream &in)
Read cacheCapacity, allocate memory and initialize object.
void setup ()
Initialize buffer before the loop over atoms.
Atom * newAtomPtr ()
Returns pointer an address available for a new Atom.
int addAtom ()
Process the active atom for sending.
void send ()
Send all atoms that have not be sent previously.
void receive ()
Receive all atoms sent by master processor.
int validate ()
Validate distribution of atoms after completion.
Constructor & Destructor Documentation
DdMd::AtomDistributor::AtomDistributor ()
Constructor.
Definition at line 29 of file AtomDistributor.cpp.
References Util::ParamComposite::setClassName().
DdMd::AtomDistributor::~AtomDistributor ()
Destructor.
Definition at line 51 of file AtomDistributor.cpp.
Member Function Documentation
void DdMd::AtomDistributor::associate (Domain & domain, Boundary & boundary, AtomStorage & storage, Buffer & buffer)
Set pointers to boundary, domain, and buffer.
This method must be called on all nodes, before any other.
Parameters:
boundary Boundary object (periodic boundary conditions)
domain Domain object (processor grid)
storage AtomStorage object (processor grid)
buffer Buffer used for communication
Definition at line 57 of file AtomDistributor.cpp.
Referenced by DdMd::ConfigIo::associate().
void DdMd::AtomDistributor::initialize (int cacheCapacity = 100)
Set cacheCapacity, allocate memory and initialize object.
This method and readParameters both allocate all required memory and initialize the AtomDistributor. Memory for a temporary read cache is alocated only on the master.
If cacheCapacity < 0, this sets a default value large enough to accomodate full send buffers for all processors simultaneously.
Preconditions: The initialize method must have been called, the Buffer must be allocated, and the Domain must be initialized.
Parameters:
cacheCapacity max number of atoms cached for sending
Definition at line 71 of file AtomDistributor.cpp.
Referenced by DdMd::ConfigIo::initialize(), DdMd::ConfigIo::load(), and DdMd::ConfigIo::readParameters().
void DdMd::AtomDistributor::readParameters (std::istream & in) [virtual]
Read cacheCapacity, allocate memory and initialize object.
This method reads cacheCapacity from file, and then goes through the same initialization steps as AtomDistributor::initialize().
Parameters:
in input stream from which parameter is read.
Reimplemented from Util::ParamComposite.
Definition at line 80 of file AtomDistributor.cpp.
void DdMd::AtomDistributor::setup ()
Initialize buffer before the loop over atoms.
This method should be called only by the master processor, just before entering the loop to read atoms from file.
Definition at line 150 of file AtomDistributor.cpp.
References DdMd::Buffer::beginSendBlock(), and DdMd::Buffer::clearSendBuffer().
Referenced by DdMd::SerializeConfigIo::loadConfig(), DdMd::DdMdConfigIo::readConfig(), DdMd::DdMdOrderedConfigIo::readConfig(), and DdMd::LammpsConfigIo::readConfig().
Atom * DdMd::AtomDistributor::newAtomPtr ()
Returns pointer an address available for a new Atom.
This method should be called only by the master processor. It returns the address within the internal cache for a new Atom object. Every call to newAtomPtr() must be followed by a matching call to addAtom().
Returns:
address for a new Atom.
Definition at line 162 of file AtomDistributor.cpp.
References DdMd::Buffer::beginSendBlock(), DdMd::Atom::clear(), DdMd::Buffer::clearSendBuffer(), DdMd::Domain::communicator(), DdMd::Buffer::endSendBlock(), DdMd::Domain::gridRank(), DdMd::Domain::isInitialized(), DdMd::Atom::packAtom(), Util::ArrayStack< Data >::pop(), Util::ArrayStack< Data >::push(), DdMd::Buffer::send(), Util::ArrayStack< Data >::size(), and UTIL_THROW.
Referenced by DdMd::SerializeConfigIo::loadConfig(), DdMd::DdMdConfigIo::readConfig(), DdMd::DdMdOrderedConfigIo::readConfig(), and DdMd::LammpsConfigIo::readConfig().
int DdMd::AtomDistributor::addAtom ()
Process the active atom for sending.
This method may be called only by the master processor, after a matching call to newAtomPtr(). It identifies which processor owns the active atom, i.e., the atom returned by the most recent call to newAtomPtr. After shifting the position of this atom to lie within the primary cell, it identifies the rank of the processor that owns this atom, based on its position. If this atom is owned by the master (rank == 0), the atom is added to the AtomStorage on the master node. Otherwise, the atom is added to a cache of stored atoms, and a pointer to this atom is added to a sendList for the relevant processor.
Atoms are actually transmitted to other processors as needed: Whenever addition of an atom to the cache would exceed either the cache capacity or the capacity of the sendlist for the owner processor, this method sends a buffer to the processor with the the largest sendList, before caching the current atom and marking it for later sending.
The coordinates of the active atom must be expressed in scaled / generalized [0, 1] coordinates when it is added.
Returns:
rank of processor that owns the active atom.
Definition at line 232 of file AtomDistributor.cpp.
References DdMd::AtomStorage::addNewAtom(), DdMd::Buffer::beginSendBlock(), DdMd::Buffer::clearSendBuffer(), DdMd::Domain::communicator(), DdMd::Buffer::endSendBlock(), DdMd::Domain::grid(), DdMd::Domain::gridRank(), DdMd::AtomStorage::isCartesian(), DdMd::Domain::isInitialized(), DdMd::AtomStorage::newAtomPtr(), DdMd::Domain::ownerRank(), DdMd::Atom::packAtom(), DdMd::Atom::position(), Util::ArrayStack< Data >::push(), DdMd::Buffer::send(), Util::OrthorhombicBoundary::shiftGen(), Util::Grid::size(), Util::ArrayStack< Data >::size(), and UTIL_THROW.
Referenced by DdMd::SerializeConfigIo::loadConfig(), DdMd::DdMdConfigIo::readConfig(), DdMd::DdMdOrderedConfigIo::readConfig(), and DdMd::LammpsConfigIo::readConfig().
void DdMd::AtomDistributor::send ()
Send all atoms that have not be sent previously.
This method should be called only by the master processor, after completion of a loop over all atoms to be sent.
Definition at line 349 of file AtomDistributor.cpp.
References DdMd::Buffer::beginSendBlock(), Util::ArrayStack< Data >::capacity(), DdMd::Buffer::clearSendBuffer(), DdMd::Domain::communicator(), DdMd::AtomStorage::computeNAtomTotal(), DdMd::Buffer::endSendBlock(), DdMd::Domain::grid(), DdMd::Domain::gridRank(), DdMd::Domain::isInitialized(), DdMd::AtomStorage::nAtom(), DdMd::AtomStorage::nAtomTotal(), DdMd::Atom::packAtom(), Util::ArrayStack< Data >::push(), DdMd::Buffer::send(), Util::Grid::size(), Util::ArrayStack< Data >::size(), DdMd::AtomStorage::unsetNAtomTotal(), and UTIL_THROW.
Referenced by DdMd::SerializeConfigIo::loadConfig(), DdMd::DdMdConfigIo::readConfig(), DdMd::DdMdOrderedConfigIo::readConfig(), and DdMd::LammpsConfigIo::readConfig().
void DdMd::AtomDistributor::receive ()
Receive all atoms sent by master processor.
This should be called by all processes except the master.
Upon return, all processors should have the correct atoms, with scaled / generalized atom coordinates set correctly.
Definition at line 427 of file AtomDistributor.cpp.
References DdMd::AtomStorage::addNewAtom(), DdMd::Buffer::beginRecvBlock(), DdMd::Domain::communicator(), DdMd::AtomStorage::computeNAtomTotal(), DdMd::Buffer::endRecvBlock(), DdMd::Domain::gridRank(), DdMd::Domain::isInitialized(), DdMd::AtomStorage::newAtomPtr(), DdMd::Domain::ownerRank(), DdMd::Atom::position(), DdMd::Buffer::recv(), DdMd::Buffer::recvSize(), DdMd::Atom::unpackAtom(), DdMd::AtomStorage::unsetNAtomTotal(), and UTIL_THROW.
Referenced by DdMd::SerializeConfigIo::loadConfig(), DdMd::DdMdConfigIo::readConfig(), DdMd::DdMdOrderedConfigIo::readConfig(), and DdMd::LammpsConfigIo::readConfig().
int DdMd::AtomDistributor::validate ()
Validate distribution of atoms after completion.
This method checks call AtomStorage::isValid(), checks that the total number of atoms on all processors is equal to nAtom, and checks that every atom is in the correct processor domain.
On the master processor
Returns:
total number of atoms distributed on master, 0 on slaves.
Definition at line 475 of file AtomDistributor.cpp.
References DdMd::AtomStorage::begin(), DdMd::Domain::communicator(), DdMd::AtomStorage::computeNAtomTotal(), Util::Dimension, DdMd::Domain::domainBound(), DdMd::Domain::isMaster(), DdMd::AtomStorage::isValid(), DdMd::AtomStorage::nAtom(), DdMd::AtomStorage::nAtomTotal(), Util::ConstPArrayIterator< Data >::notEnd(), and UTIL_THROW.
Referenced by DdMd::SerializeConfigIo::loadConfig(), DdMd::DdMdConfigIo::readConfig(), DdMd::DdMdOrderedConfigIo::readConfig(), and DdMd::LammpsConfigIo::readConfig().
The documentation for this class was generated from the following files:
AtomDistributor.h
AtomDistributor.cpp