Simpatico: McMd::DpdMove Class Reference
McMd::DpdMove Class Reference
Monte Carlo Moves
Detailed Description
DpdMove is a short dissipative particle dynamics (DPD) simulation.
An DpdMove simply runs a (typically) short DPD MD simulation. Unlike the MdMove and HybridMd move, it does not generate new initial velocities at the beginning of the move, but simply uses the existing atomic velocities generated by previous hybrid moves. Also, unlike the HybridMd move, it does not rigorously satisfy detailed balance, and is rigorously correct only in the limit of vanishing time step dt.
Definition at line 36 of file DpdMove.h.
#include <DpdMove.h>
Public Member Functions
DpdMove (McSystem &system)
Constructor.
~DpdMove ()
Destructor.
virtual void readParameters (std::istream &in)
Read nStep, dt, skin, maxNPair from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to an archive.
virtual void setup ()
Initialize before a run.
bool move ()
Generate, attempt and accept or reject a move.
Constructor & Destructor Documentation
McMd::DpdMove::DpdMove (McSystem & system)
Constructor.
Constructs a component MdSystem object.
Definition at line 28 of file DpdMove.cpp.
References Util::ParamComposite::setClassName().
McMd::DpdMove::~DpdMove ()
Destructor.
Definition at line 40 of file DpdMove.cpp.
Member Function Documentation
void McMd::DpdMove::readParameters (std::istream & in) [virtual]
Read nStep, dt, skin, maxNPair from file.
Reimplemented from McMd::McMove.
Definition at line 50 of file DpdMove.cpp.
References Util::ParamComposite::readParamComposite(), and McMd::McMove::readProbability().
void McMd::DpdMove::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from McMd::McMove.
Definition at line 60 of file DpdMove.cpp.
References Util::ParamComposite::loadParamComposite().
void McMd::DpdMove::save (Serializable::OArchive & ar) [virtual]
Save state to an archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::McMove.
Definition at line 70 of file DpdMove.cpp.
References McMd::MdSystem::saveParameters().
void McMd::DpdMove::setup () [virtual]
Initialize before a run.
Reimplemented from McMd::McMove.
Definition at line 80 of file DpdMove.cpp.
References McMd::MdSystem::mdIntegrator(), and McMd::MdIntegrator::setup().
bool McMd::DpdMove::move () [virtual]
Generate, attempt and accept or reject a move.
Reimplemented from McMd::McMove.
Definition at line 86 of file DpdMove.cpp.
References McMd::McPairPotential::buildCellList(), McMd::MdPairPotential::buildPairList(), McMd::MdSystem::calculateForces(), McMd::McMove::incrementNAccept(), McMd::McMove::incrementNAttempt(), McMd::MdSystem::mdIntegrator(), McMd::McSystem::pairPotential(), McMd::MdSystem::pairPotential(), McMd::MdIntegrator::step(), and McMd::SystemMove::system().
The documentation for this class was generated from the following files:
DpdMove.h
DpdMove.cpp