Simpatico: McMd::Species Class Reference
McMd::Species Class Reference
McMd namespace » Species
Detailed Description
A Species represents a set of chemically similar molecules.
A Species has:
A description of the structure of a molecule of this species.
A capacity, which is the maximum allowed number of Molecules of this Species, or the number for which space should be allocated.
The chemical structure of each molecule within a Species is defined by specifying the type of each atom and constructing a list of bond, angle and dihedral covalent groups. Information about covalent groups is stored internally in a set of SpeciesGroup<N> objects with N=2,3, and 4. This chemical structure is defined within the virtual protected readSpeciesParam(std::istream&) function, which is called by readParam.
Implementations of readSpeciesParam() must read whatever parameters are required to define the chemical structure of some class of molecular structures. The default implementation of Species::readSpeciesParam() is general enough to describe any molecular structure, and simply reads all of the required information about atom types and groups from file. Subclasses of Species generally hard-code some or all of the information required to describe a structure into the class definition, and require correspondingly less information to to be specified in the parameter file. For example, the parameter file format for a class that represents a flexible linear homopolymer might require only the number of monomers per chain, a single atom type index and a single bond type index. A subclass that represents a specific chemical structure (e.g., a water molecule) might not require any data from the parameter file.
A subclasses of Species may also represent a "mutable" species. A mutable species is one in which each molecule can be in any of a finite number of different internal states, in which the chemical structure is slightly different in different states. A mutable species could, for example, be used implement a semi-grand ensemble for a polymer mixture, in which each polymer can be of either of two types. A subclass that represents a mutable species must have an associated SpeciesMutator. See documentation for Species::setMutatorPtr().
Definition at line 66 of file mcMd/species/Species.h.
#include <Species.h>
Public Types
typedef SpeciesGroup< 2 > SpeciesBond
A SpeciesBond has the local atom ids and a type id for one bond.
typedef FSArray< int, MaxBondPerAtom > AtomBondIdArray
An array of local integer bond ids for all bonds containing one atom.
typedef SpeciesGroup< 3 > SpeciesAngle
A SpeciesAngle has local atom ids and a type id for one angle.
typedef FSArray< int, MaxAnglePerAtom > AtomAngleIdArray
An array of local angle ids for all angles containing one atom.
typedef SpeciesGroup< 4 > SpeciesDihedral
A SpeciesDihedral has local atom ids and a type id for one dihedral.
typedef FSArray< int, MaxDihedralPerAtom > AtomDihedralIdArray
An array of local angle ids for all dihedrals containing one atom.
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Public Member Functions
Species ()
Constructor.
virtual ~Species ()
Destructor.
Initialization
virtual void readParameters (std::istream &in)
Read parameters and initialize structure for this species.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void setId (int id)
Set integer id for this Species.
Chemical Structure Accessors
int nAtom () const
Get number of atoms per molecule for this Species.
int atomTypeId (int iAtom) const
Get atom type index for a specific atom, by local atom index.
int nBond () const
Get number of bonds per molecule for this Species.
const SpeciesBond & speciesBond (int iBond) const
Get a specific SpeciesBond object, by local bond index.
const AtomBondIdArray & atomBondIds (int atomId) const
Get array of ids for Bonds that contain one Atom.
int nAngle () const
Get number of angles per molecule for this Species.
const SpeciesAngle & speciesAngle (int iAngle) const
Get a specific SpeciesAngle object, by local angle index.
const AtomAngleIdArray & atomAngleIds (int atomId) const
Get array of ids for angles that contain one Atom.
int nDihedral () const
Get number of dihedrals per molecule for this Species.
const SpeciesDihedral & speciesDihedral (int iDihedral) const
Get a specific SpeciesDihedral object, by local angle index.
const AtomDihedralIdArray & atomDihedralIds (int atomId) const
Get array of ids for dihedrals that contain one Atom.
Interface for mutable species.
bool isMutable () const
Is this a mutable Species?
SpeciesMutator & mutator ()
Return the species mutator object by reference.
Miscellaneous Accessors
int id () const
Get integer id of this Species.
int capacity () const
Maximum allowed number of molecules for this Species.
bool isValid () const
Return true if Species is valid, or throw an Exception.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Static Public Attributes
static const int MaxBondPerAtom = 4
Maximum number of bonds that can be connected to one atom.
static const int MaxAnglePerAtom = 18
Maximum number of angles groups that can contain one atom.
static const int MaxDihedralPerAtom = 72
Maximum number of dihedral groups that can contain one atom.
Protected Member Functions
virtual void readSpeciesParam (std::istream &in)
Define chemical structure for this Species.
virtual void loadSpeciesParam (Serializable::IArchive &ar)
Define chemical structure for this Species.
void allocate ()
Allocate chemical structure arrays.
void setAtomType (int atomId, int atomType)
Set the type for one atom in a generic molecule of this Species.
void makeBond (int bondId, int atomId1, int atomId2, int bondType)
Add a bond to the chemical structure of a generic molecule.
void makeAngle (int angleId, int atomId1, int atomId2, int atomId3, int angleType)
Add an angle to the chemical structure of a generic molecule.
void makeDihedral (int dihedralId, int atomId1, int atomId2, int atomId3, int atomId4, int dihedralType)
Add a dihedral to the chemical structure of a generic molecule.
void setMutatorPtr (SpeciesMutator *mutatorPtr)
Set a pointer to an associated SpeciesMutator for a mutable species.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
int id_
Integer index for this Species.
int moleculeCapacity_
Number of molecules associated with the species.
int nAtom_
Number of atoms per molecule.
DArray< int > atomTypeIds_
Array of atom type Ids, indexed by local atom id.
int nBond_
Number of bonds per molecule.
DArray< SpeciesBond > speciesBonds_
Array of SpeciesBonds for all bonds, indexed by local bond id.
int nAngle_
Number of angles per molecule.
DArray< SpeciesAngle > speciesAngles_
Array of SpeciesAngles for all angles, indexed by local angle id.
int nDihedral_
Number of dihedrals per molecule.
DArray< SpeciesDihedral > speciesDihedrals_
Array of SpeciesDihedrals for all dihedrals, indexed by local dihedral id.
Static Protected Attributes
static const int NullIndex = -1
Null (unknown) value for any non-negative index.
Additional Inherited Members
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Member Typedef Documentation
typedef SpeciesGroup<2> McMd::Species::SpeciesBond
A SpeciesBond has the local atom ids and a type id for one bond.
Definition at line 76 of file mcMd/species/Species.h.
typedef FSArray<int, MaxBondPerAtom> McMd::Species::AtomBondIdArray
An array of local integer bond ids for all bonds containing one atom.
Definition at line 79 of file mcMd/species/Species.h.
typedef SpeciesGroup<3> McMd::Species::SpeciesAngle
A SpeciesAngle has local atom ids and a type id for one angle.
Definition at line 87 of file mcMd/species/Species.h.
typedef FSArray<int, MaxAnglePerAtom> McMd::Species::AtomAngleIdArray
An array of local angle ids for all angles containing one atom.
Definition at line 90 of file mcMd/species/Species.h.
typedef SpeciesGroup<4> McMd::Species::SpeciesDihedral
A SpeciesDihedral has local atom ids and a type id for one dihedral.
Definition at line 98 of file mcMd/species/Species.h.
typedef FSArray<int, MaxDihedralPerAtom> McMd::Species::AtomDihedralIdArray
An array of local angle ids for all dihedrals containing one atom.
Definition at line 101 of file mcMd/species/Species.h.
Constructor & Destructor Documentation
McMd::Species::Species ()
Constructor.
Definition at line 25 of file mcMd/species/Species.cpp.
References Util::ParamComposite::setClassName().
McMd::Species::~Species () virtual
Destructor.
Definition at line 48 of file mcMd/species/Species.cpp.
Member Function Documentation
void McMd::Species::readParameters (std::istream & in) virtual
Read parameters and initialize structure for this species.
This function reads the parameter moleculeCapacity (the maximum allowed number of molecules of this Species) and invokes the virtual Species::readSpeciesParam() function to define the chemical structure of the Species.
Parameters
in input stream.
Reimplemented from Util::ParamComposite.
Reimplemented in McMd::HomopolymerSG.
Definition at line 54 of file mcMd/species/Species.cpp.
References isValid(), moleculeCapacity_, and readSpeciesParam().
Referenced by McMd::HomopolymerSG::readParameters().
void McMd::Species::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 68 of file mcMd/species/Species.cpp.
References isValid(), loadSpeciesParam(), and moleculeCapacity_.
void McMd::Species::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Reimplemented in McMd::Homopolymer, McMd::Diblock, McMd::Multiblock, McMd::Point, and McMd::HomoRing.
Definition at line 228 of file mcMd/species/Species.cpp.
References atomTypeIds_, id_, moleculeCapacity_, nAngle_, nAtom_, nBond_, nDihedral_, speciesAngles_, speciesBonds_, and speciesDihedrals_.
void McMd::Species::setId (int id)
Set integer id for this Species.
Parameters
id integer id
Definition at line 259 of file mcMd/species/Species.cpp.
References id(), id_, and UTIL_THROW.
Referenced by McMd::Simulation::loadParameters(), and McMd::Simulation::readParameters().
int McMd::Species::nAtom () const inline
Get number of atoms per molecule for this Species.
Definition at line 521 of file mcMd/species/Species.h.
Referenced by McMd::TrajectoryReader::addMolecules(), McMd::LinearGenerator::attemptPlaceMolecule(), McMd::Linear::buildLinear(), McMd::Ring::buildRing(), McMd::Simulation::isValid(), McMd::AtomMSD::loadParameters(), McMd::RigidDisplaceMove::loadParameters(), McMd::CfbLinearEndMove::loadParameters(), McMd::EndSwapMove::loadParameters(), McMd::RingTetraRebridgeMove::loadParameters(), McMd::RingRouseAutoCorr::loadParameters(), McMd::LinearRouseAutoCorr::loadParameters(), McMd::IntraPairAutoCorr::loadParameters(), McMd::McMuExchange::loadParameters(), McMd::RadiusGyration::loadParameters(), McMd::BlockRadiusGyration::loadParameters(), McMd::SubSystem::nAtom(), McMd::System::nAtom(), McMd::DdMdConfigIo::read(), McMd::LammpsConfigIo::read(), McMd::RigidDisplaceMove::readParameters(), McMd::AtomMSD::readParameters(), McMd::CfbLinearEndMove::readParameters(), McMd::RingTetraRebridgeMove::readParameters(), McMd::EndSwapMove::readParameters(), McMd::CfbReptationMove::readParameters(), McMd::ComMSD::readParameters(), McMd::RingRouseAutoCorr::readParameters(), McMd::McMuExchange::readParameters(), McMd::LinearRouseAutoCorr::readParameters(), McMd::IntraPairAutoCorr::readParameters(), McMd::RadiusGyration::readParameters(), McMd::BlockRadiusGyration::readParameters(), McMd::Simulation::save(), McMd::HomopolymerSG::setMoleculeState(), McMd::RingRouseAutoCorr::setup(), McMd::DdMdConfigIo::write(), and McMd::LammpsConfigIo::write().
int McMd::Species::atomTypeId (int iAtom) const inline
Get atom type index for a specific atom, by local atom index.
Parameters
iAtom local index for an atom within a molecule.
Definition at line 527 of file mcMd/species/Species.h.
Referenced by McMd::CfbLinear::addAtom(), McMd::Simulation::isValid(), McMd::McMuExchange::loadParameters(), McMd::CfbReptationMove::readParameters(), McMd::McMuExchange::readParameters(), and McMd::Simulation::save().
int McMd::Species::nBond () const inline
Get number of bonds per molecule for this Species.
Definition at line 534 of file mcMd/species/Species.h.
Referenced by McMd::BondPotentialImpl< Interaction >::addForces(), McMd::Linear::buildLinear(), McMd::Ring::buildRing(), McMd::Activate::deactivate(), McMd::BondPotentialImpl< Interaction >::energy(), McMd::Simulation::isValid(), McMd::CfbReptationMove::loadParameters(), McMd::CfbReptateMove::loadParameters(), McMd::IntraBondStressAutoCorr< SystemType >::loadParameters(), McMd::IntraBondTensorAutoCorr< SystemType >::loadParameters(), McMd::Activate::reactivate(), McMd::DdMdConfigIo::read(), McMd::LammpsConfigIo::read(), McMd::CfbReptationMove::readParameters(), McMd::CfbReptateMove::readParameters(), McMd::IntraBondStressAutoCorr< SystemType >::readParameters(), McMd::IntraBondTensorAutoCorr< SystemType >::readParameters(), McMd::Simulation::save(), McMd::DdMdConfigIo::write(), and McMd::LammpsConfigIo::write().
const Species::SpeciesBond & McMd::Species::speciesBond (int iBond) const inline
Get a specific SpeciesBond object, by local bond index.
Parameters
iBond local index of a SpeciesBond within a molecule.
Definition at line 541 of file mcMd/species/Species.h.
Referenced by isValid(), McMd::Simulation::isValid(), McMd::CfbReptationMove::loadParameters(), McMd::CfbReptateMove::loadParameters(), loadSpeciesParam(), McMd::CfbReptationMove::readParameters(), readSpeciesParam(), and McMd::Simulation::save().
const Species::AtomBondIdArray & McMd::Species::atomBondIds (int atomId) const inline
Get array of ids for Bonds that contain one Atom.
Parameters
atomId local index for atom of interest
Definition at line 548 of file mcMd/species/Species.h.
Referenced by McMd::Activate::deactivate(), McMd::getAtomBonds(), and McMd::Activate::reactivate().
int McMd::Species::nAngle () const inline
Get number of angles per molecule for this Species.
Definition at line 556 of file mcMd/species/Species.h.
Referenced by McMd::AnglePotentialImpl< Interaction >::addForces(), McMd::Linear::buildLinear(), McMd::Ring::buildRing(), McMd::Activate::deactivate(), McMd::AnglePotentialImpl< Interaction >::energy(), McMd::Simulation::isValid(), McMd::Activate::reactivate(), McMd::Simulation::save(), McMd::DdMdConfigIo::write(), McMd::LammpsConfigIo::write(), and McMd::CfbLinear::~CfbLinear().
const Species::SpeciesAngle & McMd::Species::speciesAngle (int iAngle) const inline
Get a specific SpeciesAngle object, by local angle index.
Parameters
iAngle local index of a SpeciesAngle within a molecule.
Definition at line 563 of file mcMd/species/Species.h.
Referenced by isValid(), McMd::Simulation::isValid(), loadSpeciesParam(), readSpeciesParam(), and McMd::Simulation::save().
const Species::AtomAngleIdArray & McMd::Species::atomAngleIds (int atomId) const inline
Get array of ids for angles that contain one Atom.
Parameters
atomId local index for atom of interest
Definition at line 570 of file mcMd/species/Species.h.
Referenced by McMd::Activate::deactivate(), McMd::getAtomAngles(), and McMd::Activate::reactivate().
int McMd::Species::nDihedral () const inline
Get number of dihedrals per molecule for this Species.
Definition at line 578 of file mcMd/species/Species.h.
Referenced by McMd::DihedralPotentialImpl< Interaction >::addForces(), McMd::Linear::buildLinear(), McMd::Ring::buildRing(), McMd::Activate::deactivate(), McMd::DihedralPotentialImpl< Interaction >::energy(), McMd::Simulation::isValid(), McMd::Activate::reactivate(), McMd::Simulation::save(), McMd::DdMdConfigIo::write(), McMd::LammpsConfigIo::write(), and McMd::CfbLinear::~CfbLinear().
const Species::SpeciesDihedral & McMd::Species::speciesDihedral (int iDihedral) const inline
Get a specific SpeciesDihedral object, by local angle index.
Parameters
iDihedral local index of a SpeciesDihedral within a molecule.
Definition at line 585 of file mcMd/species/Species.h.
Referenced by isValid(), McMd::Simulation::isValid(), loadSpeciesParam(), readSpeciesParam(), and McMd::Simulation::save().
const Species::AtomDihedralIdArray & McMd::Species::atomDihedralIds (int atomId) const inline
Get array of ids for dihedrals that contain one Atom.
Parameters
atomId local index for atom of interest
Definition at line 592 of file mcMd/species/Species.h.
Referenced by McMd::Activate::deactivate(), McMd::getAtomDihedrals(), and McMd::Activate::reactivate().
bool McMd::Species::isMutable () const inline
Is this a mutable Species?
Definition at line 599 of file mcMd/species/Species.h.
Referenced by McMd::Generator::generate(), isValid(), McMd::Simulation::isValid(), McMd::SemiGrandDistribution::loadParameters(), McMd::TypeDistribution::loadParameters(), McMd::EndSwapMove::loadParameters(), McMd::McMdConfigIo::read(), and McMd::McMdConfigIo::write().
SpeciesMutator & McMd::Species::mutator () inline
Return the species mutator object by reference.
Definition at line 605 of file mcMd/species/Species.h.
Referenced by McMd::Generator::generate(), McMd::SemiGrandDistribution::loadParameters(), McMd::TypeDistribution::loadParameters(), McMd::HomopolymerSemiGrandMove::move(), McMd::McMdConfigIo::read(), McMd::HomopolymerSG::readSpeciesParam(), and McMd::McMdConfigIo::write().
int McMd::Species::id () const inline
Get integer id of this Species.
Definition at line 509 of file mcMd/species/Species.h.
Referenced by McMd::System::addMolecule(), McMd::Generator::generate(), isValid(), McMd::System::moleculeId(), McMd::System::removeMolecule(), McMd::Simulation::returnMolecule(), McMd::MdPairEnergyCoefficients::sample(), McMd::Simulation::save(), McMd::RingOctaRebridgeMove::scanBridge(), setId(), and McMd::McMdConfigIo::write().
int McMd::Species::capacity () const inline
Maximum allowed number of molecules for this Species.
Definition at line 515 of file mcMd/species/Species.h.
Referenced by McMd::TrajectoryReader::addMolecules(), McMd::Simulation::allocateMoleculeSet(), McMd::ClusterIdentifier::initialize(), McMd::Simulation::isValid(), McMd::SemiGrandDistribution::loadParameters(), McMd::AtomMSD::loadParameters(), McMd::ComMSD::loadParameters(), McMd::RingRouseAutoCorr::loadParameters(), McMd::LinearRouseAutoCorr::loadParameters(), McMd::IntraBondStressAutoCorr< SystemType >::loadParameters(), McMd::MdPairEnergyCoefficients::loadParameters(), McMd::IntraBondTensorAutoCorr< SystemType >::loadParameters(), McMd::IntraPairAutoCorr::loadParameters(), McMd::McMuExchange::loadParameters(), McMd::DdMdConfigIo::read(), McMd::LammpsConfigIo::read(), McMd::LammpsDumpReader::readFrame(), McMd::DCDTrajectoryReader::readFrame(), McMd::DdMdTrajectoryReader::readFrame(), McMd::AtomMSD::readParameters(), McMd::CfbReptationMove::readParameters(), McMd::ComMSD::readParameters(), McMd::CfbReptateMove::readParameters(), McMd::RingRouseAutoCorr::readParameters(), McMd::McMuExchange::readParameters(), McMd::LinearRouseAutoCorr::readParameters(), McMd::IntraBondStressAutoCorr< SystemType >::readParameters(), McMd::MdPairEnergyCoefficients::readParameters(), McMd::IntraBondTensorAutoCorr< SystemType >::readParameters(), McMd::IntraPairAutoCorr::readParameters(), McMd::HomopolymerSG::readSpeciesParam(), McMd::MdPairEnergyCoefficients::sample(), McMd::Simulation::save(), and McMd::MdPairEnergyCoefficients::~MdPairEnergyCoefficients().
bool McMd::Species::isValid () const
Return true if Species is valid, or throw an Exception.
Definition at line 411 of file mcMd/species/Species.cpp.
References McMd::SpeciesGroup< NAtom >::atomId(), atomTypeIds_, id(), Util::DArray< Data >::isAllocated(), isMutable(), moleculeCapacity_, nAngle_, nAtom_, nBond_, nDihedral_, speciesAngle(), speciesBond(), speciesDihedral(), and UTIL_THROW.
Referenced by McMd::Simulation::isValid(), loadParameters(), and readParameters().
void McMd::Species::readSpeciesParam (std::istream & in) protected virtual
Define chemical structure for this Species.
This virtual function must define the structure of a molecule of this species, and read any data required to do so. The default implementation Species::readSpeciesParam reads nAtom_, nBond_, nAngle_, and the elements of the arrays atomTypeIds_ and speciesBonds_, speciesAngles_.
Re-implementations of this function by subclasses may hard-code some or all of the information contained in these variables, and may define a more compact file format for any parameters that are read from file.
Parameters
in input parameter file stream.
Reimplemented in McMd::Homopolymer, McMd::Multiblock, McMd::Diblock, McMd::HomopolymerSG, McMd::Point, and McMd::HomoRing.
Definition at line 82 of file mcMd/species/Species.cpp.
References allocate(), McMd::SpeciesGroup< NAtom >::atomId(), atomTypeIds_, nAngle_, nAtom_, nBond_, nDihedral_, speciesAngle(), speciesAngles_, speciesBond(), speciesBonds_, speciesDihedral(), and speciesDihedrals_.
Referenced by readParameters().
void McMd::Species::loadSpeciesParam (Serializable::IArchive & ar) protected virtual
Define chemical structure for this Species.
Analogous to readSpeciesParam, but reads data from a Serializable::IArchive rather than an input stream. This function must define the same parameter file format as readSpeciesParam.
Parameters
ar input parameter file stream.
Reimplemented in McMd::Homopolymer, McMd::Multiblock, McMd::Diblock, McMd::Point, and McMd::HomoRing.
Definition at line 155 of file mcMd/species/Species.cpp.
References allocate(), McMd::SpeciesGroup< NAtom >::atomId(), atomTypeIds_, nAngle_, nAtom_, nBond_, nDihedral_, speciesAngle(), speciesAngles_, speciesBond(), speciesBonds_, speciesDihedral(), and speciesDihedrals_.
Referenced by loadParameters().
void McMd::Species::allocate () protected
Allocate chemical structure arrays.
This function allocates the arrays that are used to define the chemical structure of a generic molecule, such as atomTypeIds_, speciesBonds_, atomBondIdArrays_, speciesAngles_, etc.
Precondition: nAtom_, nBond_, nAngles_, etc. must have nonzero values on entry.
Definition at line 277 of file mcMd/species/Species.cpp.
References Util::DArray< Data >::allocate(), atomTypeIds_, nAngle_, nAtom_, nBond_, nDihedral_, speciesAngles_, speciesBonds_, and speciesDihedrals_.
Referenced by McMd::Linear::buildLinear(), McMd::Ring::buildRing(), McMd::Point::loadSpeciesParam(), loadSpeciesParam(), McMd::Point::readSpeciesParam(), and readSpeciesParam().
void McMd::Species::setAtomType (int atomId, int atomType) protected
Set the type for one atom in a generic molecule of this Species.
Parameters
atomId local atom id, in range 0,..., nAtom - 1;
atomType atom type index
Definition at line 313 of file mcMd/species/Species.cpp.
References atomTypeIds_.
Referenced by McMd::Linear::buildLinear(), and McMd::Ring::buildRing().
void McMd::Species::makeBond (int bondId, int atomId1, int atomId2, int bondType) protected
Add a bond to the chemical structure of a generic molecule.
This function creates and adds a SpeciesBond object, and also adds a reference to the list of bonds that are connected to each atom.
Parameters
bondId local index of bond within a molecule
atomId1 local index of 1st atom in bond
atomId2 local index of 2nd atom in bond
bondType bond type index
Definition at line 322 of file mcMd/species/Species.cpp.
References nAtom_, nBond_, and speciesBonds_.
Referenced by McMd::Linear::buildLinear(), and McMd::Ring::buildRing().
void McMd::Species::makeAngle (int angleId, int atomId1, int atomId2, int atomId3, int angleType) protected
Add an angle to the chemical structure of a generic molecule.
This function creates and adds a SpeciesAngle object, and also adds a reference to the list of angles that are connected to each atom.
Parameters
angleId local index of angle within a molecule
atomId1 local index of 1st atom in angle
atomId2 local index of 2nd atom in angle
atomId3 local index of 3rd atom in angle
angleType angle type index
Definition at line 348 of file mcMd/species/Species.cpp.
References nAngle_, nAtom_, and speciesAngles_.
Referenced by McMd::Linear::buildLinear(), and McMd::Ring::buildRing().
void McMd::Species::makeDihedral (int dihedralId, int atomId1, int atomId2, int atomId3, int atomId4, int dihedralType) protected
Add a dihedral to the chemical structure of a generic molecule.
This function creates and adds a SpeciesDihedral object, and also adds a reference to the list of dihedrals that are connected to each atom.
Parameters
dihedralId local index of dihedral within a molecule
atomId1 local index of 1st atom in dihedral
atomId2 local index of 2nd atom in dihedral
atomId3 local index of 3rd atom in dihedral
atomId4 local index of 4th atom in dihedral
dihedralType dihedral type index
Definition at line 378 of file mcMd/species/Species.cpp.
References nAtom_, nDihedral_, and speciesDihedrals_.
Referenced by McMd::Linear::buildLinear(), and McMd::Ring::buildRing().
void McMd::Species::setMutatorPtr (SpeciesMutator * mutatorPtr) protected
Set a pointer to an associated SpeciesMutator for a mutable species.
A mutable subclass of Species must have an associated SpeciesMutator object. The constructor of each such subclass should pass a pointer to the SpeciesMutator to setMutatorPtr. After this function is called, Species::isMutator() will return true, the associated SpeciesMutator will be accessible via the Species::mutator() function. If a mutable Species subclass is derived from both Species and SpeciesMutator (recommended), the function setMutatorPtr(this) should be invoked within the subclass constructor to pass the address of the SpeciesMutator sub-object to the Species subobject.
Parameters
mutatorPtr pointer to an associated SpeciesMutator object
Definition at line 271 of file mcMd/species/Species.cpp.
Referenced by McMd::HomopolymerSG::HomopolymerSG().
Member Data Documentation
const int McMd::Species::MaxBondPerAtom = 4 static
Maximum number of bonds that can be connected to one atom.
Definition at line 73 of file mcMd/species/Species.h.
const int McMd::Species::MaxAnglePerAtom = 18 static
Maximum number of angles groups that can contain one atom.
Definition at line 84 of file mcMd/species/Species.h.
const int McMd::Species::MaxDihedralPerAtom = 72 static
Maximum number of dihedral groups that can contain one atom.
Definition at line 95 of file mcMd/species/Species.h.
const int McMd::Species::NullIndex = -1 static protected
Null (unknown) value for any non-negative index.
Definition at line 269 of file mcMd/species/Species.h.
Referenced by McMd::HomopolymerSG::calculateAtomTypeId(), and McMd::Diblock::Diblock().
int McMd::Species::id_ protected
Integer index for this Species.
Definition at line 277 of file mcMd/species/Species.h.
Referenced by McMd::HomoRing::save(), save(), and setId().
int McMd::Species::moleculeCapacity_ protected
Number of molecules associated with the species.
Definition at line 280 of file mcMd/species/Species.h.
Referenced by isValid(), loadParameters(), readParameters(), McMd::HomoRing::save(), McMd::Point::save(), McMd::Multiblock::save(), McMd::Diblock::save(), and save().
int McMd::Species::nAtom_ protected
Number of atoms per molecule.
Definition at line 285 of file mcMd/species/Species.h.
Referenced by allocate(), isValid(), McMd::HomoRing::loadSpeciesParam(), McMd::Diblock::loadSpeciesParam(), McMd::Multiblock::loadSpeciesParam(), loadSpeciesParam(), makeAngle(), makeBond(), makeDihedral(), McMd::Point::Point(), McMd::HomoRing::readSpeciesParam(), McMd::HomopolymerSG::readSpeciesParam(), McMd::Diblock::readSpeciesParam(), McMd::Multiblock::readSpeciesParam(), readSpeciesParam(), McMd::HomoRing::save(), and save().
DArray<int> McMd::Species::atomTypeIds_ protected
Array of atom type Ids, indexed by local atom id.
Element atomTypeIds_[id] is the atom type index for atom id of any molecule of this species, where 0 <= id < nAtom_.
Definition at line 293 of file mcMd/species/Species.h.
Referenced by allocate(), isValid(), McMd::Point::loadSpeciesParam(), loadSpeciesParam(), McMd::Point::readSpeciesParam(), readSpeciesParam(), save(), and setAtomType().
int McMd::Species::nBond_ protected
Number of bonds per molecule.
Definition at line 299 of file mcMd/species/Species.h.
Referenced by allocate(), isValid(), McMd::HomoRing::loadSpeciesParam(), McMd::Diblock::loadSpeciesParam(), McMd::Multiblock::loadSpeciesParam(), loadSpeciesParam(), makeBond(), McMd::HomoRing::readSpeciesParam(), McMd::HomopolymerSG::readSpeciesParam(), McMd::Diblock::readSpeciesParam(), McMd::Multiblock::readSpeciesParam(), readSpeciesParam(), and save().
DArray<SpeciesBond> McMd::Species::speciesBonds_ protected
Array of SpeciesBonds for all bonds, indexed by local bond id.
Element speciesBonds_[id] is the SpeciesBond object for bond number id in any molecule of this Species, where 0 <= id < nBond_.
Definition at line 307 of file mcMd/species/Species.h.
Referenced by allocate(), loadSpeciesParam(), makeBond(), readSpeciesParam(), and save().
int McMd::Species::nAngle_ protected
Number of angles per molecule.
Definition at line 314 of file mcMd/species/Species.h.
Referenced by allocate(), isValid(), McMd::HomoRing::loadSpeciesParam(), McMd::Diblock::loadSpeciesParam(), McMd::Multiblock::loadSpeciesParam(), loadSpeciesParam(), makeAngle(), McMd::HomoRing::readSpeciesParam(), McMd::HomopolymerSG::readSpeciesParam(), McMd::Diblock::readSpeciesParam(), McMd::Multiblock::readSpeciesParam(), readSpeciesParam(), McMd::Multiblock::save(), McMd::Diblock::save(), and save().
DArray<SpeciesAngle> McMd::Species::speciesAngles_ protected
Array of SpeciesAngles for all angles, indexed by local angle id.
Element speciesAngles_[id] is the SpeciesAngle object for angle number id in any molecule of this Species, where 0 <= id < nAngle_.
Definition at line 322 of file mcMd/species/Species.h.
Referenced by allocate(), loadSpeciesParam(), makeAngle(), readSpeciesParam(), and save().
int McMd::Species::nDihedral_ protected
Number of dihedrals per molecule.
Definition at line 329 of file mcMd/species/Species.h.
Referenced by allocate(), isValid(), McMd::HomoRing::loadSpeciesParam(), McMd::Diblock::loadSpeciesParam(), McMd::Multiblock::loadSpeciesParam(), loadSpeciesParam(), makeDihedral(), McMd::HomoRing::readSpeciesParam(), McMd::HomopolymerSG::readSpeciesParam(), McMd::Diblock::readSpeciesParam(), McMd::Multiblock::readSpeciesParam(), readSpeciesParam(), McMd::Multiblock::save(), McMd::Diblock::save(), and save().
DArray<SpeciesDihedral> McMd::Species::speciesDihedrals_ protected
Array of SpeciesDihedrals for all dihedrals, indexed by local dihedral id.
Element speciesDihedrals_[id] is the SpeciesDihedral object for dihedral number id in any molecule of this Species, where 0 <= id < nAngle_.
Definition at line 337 of file mcMd/species/Species.h.
Referenced by allocate(), loadSpeciesParam(), makeDihedral(), readSpeciesParam(), and save().
The documentation for this class was generated from the following files:
mcMd/species/Species.h
mcMd/species/Species.cpp