Simpatico: DdMd::DihedralPotential Class Reference
DdMd::DihedralPotential Class Reference abstract
Dihedral Potentials
Detailed Description
An DihedralPotential calculates dihedral forces and energies for a parent Simulation.
Definition at line 29 of file ddMd/potentials/dihedral/DihedralPotential.h.
#include <DihedralPotential.h>
Public Member Functions
DihedralPotential (Simulation &simulation)
Constructor.
DihedralPotential ()
Default constructor (for unit testing).
~DihedralPotential ()
Destructor.
void associate (Boundary &boundary, GroupStorage< 4 > &storage)
Associate with related objects.
Interaction interface
virtual void setNDihedralType (int nDihedralType)=0
Set the maximum number of atom types.
virtual double dihedralEnergy (const Vector &R1, const Vector &R2, const Vector &R3, int type) const =0
Returns potential energy for one dihedral.
virtual void dihedralForce (const Vector &R1, const Vector &R2, const Vector &R3, Vector &F1, Vector &F2, Vector &F3, int type) const =0
Returns derivatives of energy with respect to bond vectors forming the dihedral group.
virtual void set (std::string name, int type, double value)=0
Modify a dihedral interaction parameter, identified by a string.
virtual double get (std::string name, int type) const =0
Get a dihedral parameter value, identified by a string.
virtual std::string interactionClassName () const =0
Return pair interaction class name (e.g., "HarmonicDihedral").
Public Member Functions inherited from DdMd::Potential
Potential ()
Constructor.
virtual ~Potential ()
Destructor.
void setReverseUpdateFlag (bool reverseUpdateFlag)
Set flag to identify if reverse communication is enabled.
bool reverseUpdateFlag () const
Get flag to identify if reverse communication is enabled.
virtual void computeForces ()=0
Add force contributions to all atomic forces.
virtual void computeEnergy (MPI::Intracomm &communicator)=0
Compute potential energy on all processors.
double energy () const
Return the total potential, from all processors.
void unsetEnergy ()
Mark the energy as unknown (nullify).
bool isEnergySet () const
Is the energy set (known)?
virtual void computeStress (MPI::Intracomm &communicator)
Compute stress on all processors.
virtual void computeForcesAndStress (MPI::Intracomm &communicator)
Compute forces and stress for all processors.
Util::Tensor stress () const
Return the stress tensor.
double pressure () const
Return the pressure.
void unsetStress ()
Mark the stress as unknown (nullify).
bool isStressSet () const
Is the stress set (known)?
virtual bool isValid (MPI::Intracomm &communicator) const
Is the potential in a valid internal state?
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
std::string className () const
Get class name string.
virtual void readParam (std::istream &in)
Read a parameter file block.
virtual void readParameters (std::istream &in)
Read body of parameter block, without opening and closing lines.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an archive.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void resetParam ()
Resets ParamComposite to its empty state.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add a new Param < Type > object, and read its value.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add a C array parameter, and read its elements.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and read its elements.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n)
Add and read a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
Begin & readBegin (std::istream &in, const char *label)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a child ParamComposite.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add a new Param < Type > object, and load its value.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add a C array parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and load its elements.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n)
Add and load a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a DMatrix < Type > C two-dimensional matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
template<typename Type >
ScalarParam< Type > & add (const char *label, Type &value)
Add a new Param < Type > object to the format array.
template<typename Type >
CArrayParam< Type > & addCArray (const char *label, Type *value, int n)
Add a C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (const char *label, DArray< Type > &array, int n)
Add a DArray<Type> parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (const char *label, FArray< Type, N > &array)
Add a FArray<Type> parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (const char *label, Type *value, int m, int n)
Add a C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & addDMatrix (const char *label, DMatrix< Type > &matrix, int m, int n)
Add a C two-dimensional array parameter.
Begin & addBegin (const char *label)
Add a class label and opening bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Add a new Blank object, representing a blank line.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have a communicator?
MPI::Intracomm & ioCommunicator () const
Get the communicator.
Protected Member Functions
Boundary & boundary () const
Return boundary by reference.
GroupStorage< 4 > & storage () const
Return bond storage by reference.
Protected Member Functions inherited from DdMd::Potential
void setEnergy (double energy)
Set a value for the total energy.
void setStress (const Tensor &stress)
Set a value for the total stress.
void incrementPairStress (const Vector &f, const Vector &dr, Tensor &stress) const
Add a pair contribution to the stress tensor.
void reduceEnergy (double localEnergy, MPI::Intracomm &communicator)
Add local energies from all processors, set energy on master.
void reduceStress (Tensor &localStress, MPI::Intracomm &communicator)
Add local stresses from all processors, set total on master.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Constructor & Destructor Documentation
DdMd::DihedralPotential::DihedralPotential (Simulation & simulation)
Constructor.
Definition at line 21 of file ddMd/potentials/dihedral/DihedralPotential.cpp.
References Util::ParamComposite::setClassName().
DdMd::DihedralPotential::DihedralPotential ()
Default constructor (for unit testing).
Definition at line 29 of file ddMd/potentials/dihedral/DihedralPotential.cpp.
References Util::ParamComposite::setClassName().
DdMd::DihedralPotential::~DihedralPotential ()
Destructor.
Definition at line 46 of file ddMd/potentials/dihedral/DihedralPotential.cpp.
Member Function Documentation
void DdMd::DihedralPotential::associate (Boundary & boundary, GroupStorage< 4 > & storage)
Associate with related objects.
Call iff object instantiated with default constructor.
Parameters
boundary associated Boundary object.
storage associated dihedral storage object.
Definition at line 37 of file ddMd/potentials/dihedral/DihedralPotential.cpp.
References boundary(), and storage().
virtual void DdMd::DihedralPotential::setNDihedralType (int nDihedralType) pure virtual
Set the maximum number of atom types.
Implemented in DdMd::DihedralPotentialImpl< Interaction >.
virtual double DdMd::DihedralPotential::dihedralEnergy (const Vector & R1, const Vector & R2, const Vector & R3, int type) const pure virtual
Returns potential energy for one dihedral.
0   2    3
o   o----o
 \ /
  o
  1
Parameters
R1 bond vector from atom 0 to 1
R2 bond vector from atom 1 to 2
R3 bond vector from atom 2 to 3
type type of dihedral
Implemented in DdMd::DihedralPotentialImpl< Interaction >.
virtual void DdMd::DihedralPotential::dihedralForce (const Vector & R1, const Vector & R2, const Vector & R3, Vector & F1, Vector & F2, Vector & F3, int type) const pure virtual
Returns derivatives of energy with respect to bond vectors forming the dihedral group.
Parameters
R1 bond vector from atom 0 to 1
R2 bond vector from atom 1 to 2
R3 bond vector from atom 2 to 3
F1 force along R1 direction (upon return)
F2 force along R2 direction (upon return)
F3 force along R2 direction (upon return)
type type of dihedral
Implemented in DdMd::DihedralPotentialImpl< Interaction >.
virtual void DdMd::DihedralPotential::set (std::string name, int type, double value) pure virtual
Modify a dihedral interaction parameter, identified by a string.
Parameters
name parameter variable name
type dihedral type index
value new value of parameter
Implemented in DdMd::DihedralPotentialImpl< Interaction >.
virtual double DdMd::DihedralPotential::get (std::string name, int type) const pure virtual
Get a dihedral parameter value, identified by a string.
Parameters
name parameter variable name
type dihedral type index
Implemented in DdMd::DihedralPotentialImpl< Interaction >.
virtual std::string DdMd::DihedralPotential::interactionClassName () const pure virtual
Return pair interaction class name (e.g., "HarmonicDihedral").
Implemented in DdMd::DihedralPotentialImpl< Interaction >.
Boundary & DdMd::DihedralPotential::boundary () const inline protected
Return boundary by reference.
Definition at line 148 of file ddMd/potentials/dihedral/DihedralPotential.h.
Referenced by associate().
GroupStorage< 4 > & DdMd::DihedralPotential::storage () const inline protected
Return bond storage by reference.
Definition at line 152 of file ddMd/potentials/dihedral/DihedralPotential.h.
Referenced by associate().
The documentation for this class was generated from the following files:
ddMd/potentials/dihedral/DihedralPotential.h
ddMd/potentials/dihedral/DihedralPotential.cpp