Simpatico: McMd::ClusterIdentifier Class Reference
McMd::ClusterIdentifier Class Reference
Detailed Description
Identifies clusters of molecules, such as micelles.
Definition at line 34 of file ClusterIdentifier.h.
#include <ClusterIdentifier.h>
Public Member Functions
ClusterIdentifier (System &system)
Constructor.
~ClusterIdentifier ()
Destructor.
virtual void initialize (int speciesId, int atomTypeId, double cutoff)
Clear accumulator.
void identifyClusters ()
Identify all clusters (main operation).
int nCluster () const
Get number of clusters.
ClusterLink & link (int moleculeId)
Get a specific ClusterLink, by id of the associated molecule.
Cluster & cluster (int id)
Get a specific cluster, indexed in the order identified.
bool isValid () const
Return true if valid, or throw Exception otherwise.
Constructor & Destructor Documentation
McMd::ClusterIdentifier::ClusterIdentifier (System & system)
Constructor.
Parameters
system reference to parent System object
Definition at line 27 of file ClusterIdentifier.cpp.
McMd::ClusterIdentifier::~ClusterIdentifier ()
Destructor.
Definition at line 41 of file ClusterIdentifier.cpp.
Member Function Documentation
void McMd::ClusterIdentifier::initialize (int speciesId, int atomTypeId, double cutoff) virtual
Clear accumulator.
Parameters
speciesId index of species in clusters
atomTypeId typeId of atoms in micelle core
cutoff pair distance cutoff
Definition at line 48 of file ClusterIdentifier.cpp.
References McMd::Cluster::addLink(), McMd::Simulation::atomCapacity(), McMd::Molecule::begin(), McMd::System::boundary(), Simp::Species::capacity(), cluster(), McMd::ClusterLink::clusterId(), Util::OrthorhombicBoundary::distanceSq(), McMd::CellList::getNeighbors(), McMd::Cluster::id(), McMd::Molecule::id(), McMd::ClusterLink::molecule(), McMd::Atom::molecule(), Util::ArrayIterator< Data >::notEnd(), McMd::Atom::position(), McMd::CellList::setAtomCapacity(), McMd::System::simulation(), Util::FSArray< Data, Capacity >::size(), McMd::Simulation::species(), and UTIL_THROW.
Referenced by McMd::ClusterHistogram::loadParameters(), and McMd::ClusterHistogram::readParameters().
void McMd::ClusterIdentifier::identifyClusters ()
Identify all clusters (main operation).
Definition at line 128 of file ClusterIdentifier.cpp.
References McMd::CellList::addAtom(), McMd::Cluster::addLink(), McMd::System::begin(), McMd::System::boundary(), McMd::Cluster::clear(), McMd::ClusterLink::clusterId(), Util::PArrayIterator< Data >::get(), isValid(), McMd::ClusterLink::molecule(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Cluster::setId(), McMd::CellList::setup(), and Util::OrthorhombicBoundary::shift().
Referenced by McMd::ClusterHistogram::sample().
int McMd::ClusterIdentifier::nCluster () const inline
Get number of clusters.
Definition at line 69 of file ClusterIdentifier.h.
Referenced by isValid(), and McMd::ClusterHistogram::sample().
ClusterLink& McMd::ClusterIdentifier::link (int moleculeId) inline
Get a specific ClusterLink, by id of the associated molecule.
Parameters
moleculeId molecule index.
Definition at line 77 of file ClusterIdentifier.h.
Cluster& McMd::ClusterIdentifier::cluster (int id) inline
Get a specific cluster, indexed in the order identified.
The id argument of this function is a consecutive array index, with 0 <= id < nCluster, which need not be equal to the cluster identifier returned by Cluster::id().
Parameters
id cluster array index, 0 <- id < nCluster.
Definition at line 89 of file ClusterIdentifier.h.
Referenced by initialize(), and McMd::ClusterHistogram::sample().
bool McMd::ClusterIdentifier::isValid () const
Return true if valid, or throw Exception otherwise.
Definition at line 196 of file ClusterIdentifier.cpp.
References McMd::System::begin(), McMd::ClusterLink::clusterId(), Util::ConstPArrayIterator< Data >::get(), McMd::ClusterLink::molecule(), nCluster(), McMd::System::nMolecule(), Util::ConstPArrayIterator< Data >::notEnd(), and UTIL_THROW.
Referenced by identifyClusters().
The documentation for this class was generated from the following files:
ClusterIdentifier.h
ClusterIdentifier.cpp