Simpatico: Tools::TrajectoryWriter Class Reference
Tools::TrajectoryWriter Class Reference abstract
Analyzers
Detailed Description
Based class for classes that write trajectories to a single file.
Definition at line 29 of file tools/analyzers/TrajectoryWriter.h.
#include <TrajectoryWriter.h>
Public Member Functions
TrajectoryWriter (Processor &processor, bool isBinary)
Constructor.
TrajectoryWriter (Configuration &configuration, FileMaster &fileMaster, bool isBinary)
Constructor.
virtual ~TrajectoryWriter ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters and initialize.
virtual void setup ()
Open the trajectory file.
virtual void sample (long iStep)
Write frame to file.
virtual void clear ()
Clear nSample counter.
virtual void output ()
Close ouput file.
Public Member Functions inherited from Tools::Analyzer
Analyzer (Configuration &configuration)
Constructor.
Analyzer (Processor &processor)
Constructor.
Analyzer (Configuration &configuration, FileMaster &fileMaster)
Constructor.
virtual ~Analyzer ()
Destructor.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
bool isBinary () const
Is the file format binary (true) or text (false)?
virtual void writeHeader (std::ofstream &out)
Write data that should appear once, at beginning of the file.
virtual void writeFrame (std::ofstream &out, long iStep)=0
Write data that should appear in every frame.
Boundary & boundary ()
Get Boundary by reference.
AtomStorage & atoms ()
Get AtomStorage by reference.
GroupStorage< 2 > & bonds ()
Get bond storage by reference.
GroupStorage< 3 > & angles ()
Get angle storage by reference.
GroupStorage< 4 > & dihedrals ()
Get dihedral storage by reference.
Protected Member Functions inherited from Tools::Analyzer
void readInterval (std::istream &in)
Read parameter interval from file.
void readOutputFileName (std::istream &in)
Read outputFileName from file.
Configuration & configuration ()
Get the parent Configuration by reference.
FileMaster & fileMaster ()
Get an associated FileMaster by reference.
const std::string & outputFileName () const
Return outputFileName string.
std::string outputFileName (const std::string &suffix) const
Return outputFileName string with added suffix.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Constructor & Destructor Documentation
Tools::TrajectoryWriter::TrajectoryWriter (Processor & processor, bool isBinary)
Constructor.
Parameters
processor parent Processor object
isBinary Is the trajectory file a binary file?
Definition at line 26 of file tools/analyzers/TrajectoryWriter.cpp.
References Tools::Configuration::angles(), Tools::Configuration::atoms(), Tools::Configuration::bonds(), Tools::Configuration::boundary(), Tools::Configuration::dihedrals(), and Util::ParamComposite::setClassName().
Tools::TrajectoryWriter::TrajectoryWriter (Configuration & configuration, Util::FileMaster & fileMaster, bool isBinary)
Constructor.
Parameters
configuration parent Configuration object
fileMaster associated FileMaster object
isBinary Is the trajectory file a binary file?
Definition at line 63 of file tools/analyzers/TrajectoryWriter.cpp.
References Tools::Configuration::angles(), Tools::Configuration::atoms(), Tools::Configuration::bonds(), Tools::Configuration::boundary(), Tools::Configuration::dihedrals(), and Util::ParamComposite::setClassName().
virtual Tools::TrajectoryWriter::~TrajectoryWriter () inline virtual
Destructor.
Definition at line 55 of file tools/analyzers/TrajectoryWriter.h.
Member Function Documentation
void Tools::TrajectoryWriter::readParameters (std::istream & in) virtual
Read parameters and initialize.
Parameters
in input parameter file
Reimplemented from Util::ParamComposite.
Definition at line 100 of file tools/analyzers/TrajectoryWriter.cpp.
References Tools::Analyzer::readInterval(), and Tools::Analyzer::readOutputFileName().
void Tools::TrajectoryWriter::setup () virtual
Open the trajectory file.
Reimplemented from Tools::Analyzer.
Definition at line 136 of file tools/analyzers/TrajectoryWriter.cpp.
References Tools::Analyzer::fileMaster(), isBinary(), Util::FileMaster::openOutputFile(), Tools::Analyzer::outputFileName(), and writeHeader().
void Tools::TrajectoryWriter::sample (long iStep) virtual
Write frame to file.
Parameters
iStep MC step index
Implements Tools::Analyzer.
Definition at line 150 of file tools/analyzers/TrajectoryWriter.cpp.
References Tools::Analyzer::isAtInterval(), and writeFrame().
void Tools::TrajectoryWriter::clear () virtual
Clear nSample counter.
Reimplemented from Tools::Analyzer.
Definition at line 161 of file tools/analyzers/TrajectoryWriter.cpp.
Referenced by output().
void Tools::TrajectoryWriter::output () virtual
Close ouput file.
Reimplemented from Tools::Analyzer.
Definition at line 172 of file tools/analyzers/TrajectoryWriter.cpp.
References clear().
bool Tools::TrajectoryWriter::isBinary () const inline protected
Is the file format binary (true) or text (false)?
Definition at line 197 of file tools/analyzers/TrajectoryWriter.h.
Referenced by setup().
virtual void Tools::TrajectoryWriter::writeHeader (std::ofstream & out) inline protected virtual
Write data that should appear once, at beginning of the file.
Called by sample on first invocation. Default implementation is empty.
Parameters
out output file stream
Definition at line 117 of file tools/analyzers/TrajectoryWriter.h.
Referenced by setup().
virtual void Tools::TrajectoryWriter::writeFrame (std::ofstream & out, long iStep) protected pure virtual
Write data that should appear in every frame.
Called by sample on every step.
Parameters
out output file stream
iStep MD time step index
Referenced by sample().
Boundary & Tools::TrajectoryWriter::boundary () inline protected
Get Boundary by reference.
Definition at line 200 of file tools/analyzers/TrajectoryWriter.h.
AtomStorage & Tools::TrajectoryWriter::atoms () inline protected
Get AtomStorage by reference.
Definition at line 203 of file tools/analyzers/TrajectoryWriter.h.
GroupStorage< 2 > & Tools::TrajectoryWriter::bonds () inline protected
Get bond storage by reference.
Definition at line 207 of file tools/analyzers/TrajectoryWriter.h.
GroupStorage< 3 > & Tools::TrajectoryWriter::angles () inline protected
Get angle storage by reference.
Definition at line 212 of file tools/analyzers/TrajectoryWriter.h.
GroupStorage< 4 > & Tools::TrajectoryWriter::dihedrals () inline protected
Get dihedral storage by reference.
Definition at line 217 of file tools/analyzers/TrajectoryWriter.h.
The documentation for this class was generated from the following files:
tools/analyzers/TrajectoryWriter.h
tools/analyzers/TrajectoryWriter.cpp