Simpatico: Util::Notifier< Event > Class Template Reference
Util::Notifier< Event > Class Template Reference
Utilities
Detailed Description
template<typename Event>
class Util::Notifier< Event >
Abstract template for a notifier (or subject) in the Observer design pattern.
In the observer design pattern, a Notifier manages a list of registered Observer objects, and provides a method to notify all observers when some event occurs. A list of observer objects is maintained as a list of Observer pointers. The method Notifier::notifyObservers(Event&) method calls the the update(Event&) method of every Observer in the list.
The typename parameter Event is the type of the object that must be passed to the update() method of each observer. This type can name either a primitive C data type or a class, but must encode whatever information is required for any Observer to respond appropriately when notified.
Definition at line 41 of file Notifier.h.
#include <Notifier.h>
Public Member Functions
void registerObserver (Observer< Event > &observer)
Register an observer.
void removeObserver (Observer< Event > &observer)
Remove a diagnostic observer from the container list.
void notifyObservers (const Event &event)
Notify the list of observers about an Event.
Member Function Documentation
template<typename Event> void Util::Notifier< Event >::registerObserver (Observer< Event > & observer)
Register an observer.
Parameters:
observer observer object
Definition at line 80 of file Notifier.h.
template<typename Event> void Util::Notifier< Event >::removeObserver (Observer< Event > & observer)
Remove a diagnostic observer from the container list.
Parameters:
observer observer object
Definition at line 89 of file Notifier.h.
template<typename Event> void Util::Notifier< Event >::notifyObservers (const Event & event)
Notify the list of observers about an Event.
Definition at line 98 of file Notifier.h.
Referenced by McMd::LinkMaster::addLink(), McMd::ReplicaMove::move(), McMd::LinkMaster::removeLink(), McMd::LinkMaster::reSetAtom(), and McMd::LinkMaster::reSetAtoms().
The documentation for this class was generated from the following file:
Notifier.h