Simpatico: McMd::McPerturbationFactory Class Reference
McMd::McPerturbationFactory Class Reference
McMd namespace » Free Energy Perturbation
Detailed Description
Default Factory for subclasses of Perturbation.
Definition at line 28 of file McPerturbationFactory.h.
#include <McPerturbationFactory.h>
Public Member Functions
McPerturbationFactory (McSystem &system)
Constructor.
Perturbation * factory (const std::string &className) const
Method to create any species supplied with Simpatico.
Public Member Functions inherited from Util::Factory< Perturbation >
Factory ()
Constructor.
virtual ~Factory ()
Destructor.
void addSubfactory (Factory< Perturbation > &subfactory)
Add a new subfactory to the list.
Perturbation * readObject (std::istream &in, ParamComposite &parent, std::string &className, bool &isEnd)
Read a class name, instantiate an object, and read its parameters.
Perturbation * loadObject (Serializable::IArchive &ar, ParamComposite &parent, std::string &className)
Load a class name, instantiate an object, and load the object.
Additional Inherited Members
Protected Member Functions inherited from Util::Factory< Perturbation >
Perturbation * trySubfactories (const std::string &className) const
Search through subfactories for match.
void setIoCommunicator (MPI::Intracomm &communicator)
Set associated Mpi communicator.
bool hasIoCommunicator () const
Does this factory have a param communicator?
Constructor & Destructor Documentation
McMd::McPerturbationFactory::McPerturbationFactory (McSystem & system)
Constructor.
Parameters
system Parent McSystem
Definition at line 42 of file McPerturbationFactory.cpp.
Member Function Documentation
Perturbation * McMd::McPerturbationFactory::factory (const std::string & className) const virtual
Method to create any species supplied with Simpatico.
Parameters
className name of the Perturbation subclass
Returns
Perturbation* pointer to new instance of className
Implements Util::Factory< Perturbation >.
Definition at line 49 of file McPerturbationFactory.cpp.
References McMd::Simulation::communicator(), McMd::PairPotential::interactionClassName(), McMd::McSystem::pairPotential(), McMd::System::simulation(), Util::Factory< Perturbation >::trySubfactories(), and UTIL_THROW.
The documentation for this class was generated from the following files:
McPerturbationFactory.h
McPerturbationFactory.cpp