Simpatico: McMd::PairPotential Class Reference
McMd::PairPotential Class Reference abstract
McMd namespace » Potential Energies » Pair Potentials
Detailed Description
Interface for a Pair Potential.
Definition at line 35 of file mcMd/potentials/pair/PairPotential.h.
#include <PairPotential.h>
Public Member Functions
virtual ~PairPotential ()
Destructor (does nothing)
Pair Interaction Interface
virtual double energy (double rsq, int iAtomType, int jAtomType) const =0
Return pair energy for a single pair.
virtual double forceOverR (double rsq, int iAtomType, int jAtomType) const =0
Return force / separation for a single pair.
virtual void set (std::string name, int i, int j, double value)=0
Modify a parameter, identified by a string.
virtual double get (std::string name, int i, int j) const =0
Get a parameter value, identified by a string.
virtual double maxPairCutoff () const =0
Return maximum cutoff distance.
virtual std::string interactionClassName () const =0
Return name of pair interaction class (e.g., "LJPair").
Public Member Functions inherited from McMd::EnergyCalculator
virtual void computeEnergy ()=0
Calculate the total nonBonded pair energy for the associated System.
virtual void unsetEnergy ()
Mark the energy as unknown.
double energy ()
Return the energy contribution, compute if necessary.
Public Member Functions inherited from McMd::StressCalculator
virtual void computeStress ()
Compute and store the stress tensor.
virtual void unsetStress ()
Mark the stress as unknown.
void computeStress (Tensor &stress)
Get pair stress tensor.
void computeStress (Vector &pressures)
Get the xx, yy, zz non-Coulomb pair pressures.
void computeStress (double &pressure)
Get the scalar pressure.
bool createsStress () const
Return false if subclass does not generate stress.
Additional Inherited Members
Protected Member Functions inherited from McMd::StressCalculator
StressCalculator (bool createsStress=true)
Constructor (protected to prevent direct instantiation).
Constructor & Destructor Documentation
virtual McMd::PairPotential::~PairPotential () inline virtual
Destructor (does nothing)
Definition at line 43 of file mcMd/potentials/pair/PairPotential.h.
Member Function Documentation
virtual double McMd::PairPotential::energy (double rsq, int iAtomType, int jAtomType) const pure virtual
Return pair energy for a single pair.
Implemented in McMd::MdPairPotentialImpl< Interaction >, McMd::MdEwaldPairPotentialImpl< Interaction >, and McMd::McPairPotentialImpl< Interaction >.
Referenced by McMd::GroupRebridgeBase::octaEnergy(), McMd::McSystem::potentialEnergy(), McMd::MdSystem::potentialEnergy(), McMd::McMuExchange::sample(), McMd::MdEnergyOutput::sample(), McMd::McEnergyOutput::sample(), McMd::MdPairEnergyCoefficients::sample(), McMd::MdEnergyAnalyzer::sample(), McMd::McEnergyAnalyzer::sample(), and McMd::GroupRebridgeBase::tetraEnergy().
virtual double McMd::PairPotential::forceOverR (double rsq, int iAtomType, int jAtomType) const pure virtual
Return force / separation for a single pair.
Implemented in McMd::MdPairPotentialImpl< Interaction >, McMd::MdEwaldPairPotentialImpl< Interaction >, and McMd::McPairPotentialImpl< Interaction >.
virtual void McMd::PairPotential::set (std::string name, int i, int j, double value) pure virtual
Modify a parameter, identified by a string.
Parameters
name parameter name
i type index of first atom
j type index of first atom
value new value of parameter
Implemented in McMd::MdPairPotentialImpl< Interaction >, McMd::MdEwaldPairPotentialImpl< Interaction >, and McMd::McPairPotentialImpl< Interaction >.
Referenced by McMd::McCommandManager::readStandardCommand(), and McMd::MdCommandManager::readStandardCommand().
virtual double McMd::PairPotential::get (std::string name, int i, int j) const pure virtual
Get a parameter value, identified by a string.
Parameters
name parameter name
i type index of first atom
j type index of first atom
Implemented in McMd::MdPairPotentialImpl< Interaction >, McMd::MdEwaldPairPotentialImpl< Interaction >, and McMd::McPairPotentialImpl< Interaction >.
virtual double McMd::PairPotential::maxPairCutoff () const pure virtual
Return maximum cutoff distance.
Implemented in McMd::MdPairPotentialImpl< Interaction >, McMd::MdEwaldPairPotentialImpl< Interaction >, and McMd::McPairPotentialImpl< Interaction >.
Referenced by McMd::McPairPotential::buildCellList(), McMd::NvtDpdVvIntegrator::loadParameters(), and McMd::NvtDpdVvIntegrator::readParameters().
virtual std::string McMd::PairPotential::interactionClassName () const pure virtual
Return name of pair interaction class (e.g., "LJPair").
Implemented in McMd::MdPairPotentialImpl< Interaction >, McMd::MdEwaldPairPotentialImpl< Interaction >, and McMd::McPairPotentialImpl< Interaction >.
Referenced by McMd::McPerturbationFactory::factory(), and McMd::PairFactory::mdFactory().
The documentation for this class was generated from the following file:
mcMd/potentials/pair/PairPotential.h