Simpatico: Inter::CosineSqAngle Class Reference
Inter::CosineSqAngle Class Reference
Angle Interactions
Detailed Description
A three body angle potential, as a function of angle cosine.
This class implements an angle potential: kappa (cos[theta0] - cos[theta])^2.
Definition at line 32 of file CosineSqAngle.h.
#include <CosineSqAngle.h>
Public Member Functions
CosineSqAngle ()
Default constructor.
CosineSqAngle (const CosineSqAngle &other)
Copy constructor.
CosineSqAngle & operator= (const CosineSqAngle &other)
Assignment.
void setNAngleType (int nAngleType)
Set the number of angle types.
void readParameters (std::istream &in)
Read angle interaction parameters from input stream.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void set (std::string name, int type, double value)
Modify a parameter, identified by a string.
double energy (double cosTheta, int type) const
Returns potential energy for one angle.
void force (const Vector &R1, const Vector &R2, Vector &F1, Vector &F2, int type) const
Compute angle forces.
double randomAngle (Random *random, double beta, int type) const
Return bond angle chosen from equilibrium distribution.
double randomCosineAngle (Random *random, double beta, int type) const
Return bond angle cosine chosen from equilibrium distribution.
double get (std::string name, int type) const
Get a parameter value, identified by a string.
std::string className () const
Return name string "CosineSqAngle" for this evaluator class.
Constructor & Destructor Documentation
Inter::CosineSqAngle::CosineSqAngle ()
Default constructor.
Definition at line 20 of file CosineSqAngle.cpp.
References Util::ParamComposite::setClassName().
Inter::CosineSqAngle::CosineSqAngle (const CosineSqAngle & other)
Copy constructor.
Definition at line 34 of file CosineSqAngle.cpp.
Member Function Documentation
CosineSqAngle & Inter::CosineSqAngle::operator= (const CosineSqAngle & other)
Assignment.
Definition at line 47 of file CosineSqAngle.cpp.
void Inter::CosineSqAngle::setNAngleType (int nAngleType)
Set the number of angle types.
Parameters:
nAngleType number of angle types
Definition at line 61 of file CosineSqAngle.cpp.
References UTIL_THROW.
void Inter::CosineSqAngle::readParameters (std::istream & in) [virtual]
Read angle interaction parameters from input stream.
Format: kappa CArray<double>
Precondition:
nAngleType must be set, by calling setNAngleType().
Parameters:
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 72 of file CosineSqAngle.cpp.
References Util::Constants::Pi, and UTIL_THROW.
void Inter::CosineSqAngle::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 92 of file CosineSqAngle.cpp.
References UTIL_THROW.
void Inter::CosineSqAngle::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 107 of file CosineSqAngle.cpp.
References Util::BinaryFileOArchive::pack().
void Inter::CosineSqAngle::set (std::string name, int type, double value)
Modify a parameter, identified by a string.
Parameters:
name parameter name
type angle type index
value new value of parameter
Definition at line 170 of file CosineSqAngle.cpp.
References UTIL_THROW.
double Inter::CosineSqAngle::energy (double cosTheta, int type) const [inline]
Returns potential energy for one angle.
Parameters:
cosTheta cosine of the bend angle.
type type of bend angle.
Definition at line 182 of file CosineSqAngle.h.
Referenced by randomAngle(), and randomCosineAngle().
void Inter::CosineSqAngle::force (const Vector & R1, const Vector & R2, Vector & F1, Vector & F2, int type) const [inline]
Compute angle forces.
Computes forces F1 and F2 along the two bonds in the angle.
Parameters:
R1 bond vector from atom 1 to 2.
R2 bond vector from atom 2 to 3.
F1 return force along R1 direction.
F2 return force along R2 direction.
type type of angle.
Definition at line 196 of file CosineSqAngle.h.
References Util::Vector::abs(), Util::Vector::dot(), and Util::Vector::multiply().
double Inter::CosineSqAngle::randomAngle (Random * random, double beta, int type) const
Return bond angle chosen from equilibrium distribution.
This function returns a bond angle chosen from the Boltzmann distribution of angle for bonds of random orientation. The distribution P(theta) of values of the angle theta is proportional to sin(theta)*exp[-beta*phi(theta) ], where phi(theta) is the bond energy.
Parameters:
random pointer to random number generator object.
beta inverse temperature
type bond type
Returns:
random bond length chosen from equilibrium distribution.
Definition at line 121 of file CosineSqAngle.cpp.
References energy(), Util::Constants::Pi, and Util::Random::uniform().
double Inter::CosineSqAngle::randomCosineAngle (Random * random, double beta, int type) const
Return bond angle cosine chosen from equilibrium distribution.
This function returns a bond angle chosen from the Boltzmann distribution of angle for bonds of random orientation. The distribution P(theta) of values of the angle theta is proportional to sin(theta)*exp[-beta*phi(theta) ], where phi(theta) is the bond energy.
Parameters:
random pointer to random number generator object.
beta inverse temperature
type bond type
Returns:
random bond length chosen from equilibrium distribution.
Definition at line 147 of file CosineSqAngle.cpp.
References energy(), and Util::Random::uniform().
double Inter::CosineSqAngle::get (std::string name, int type) const
Get a parameter value, identified by a string.
Parameters:
name parameter name
type angle type index
Returns:
parameter value
Definition at line 185 of file CosineSqAngle.cpp.
References UTIL_THROW.
std::string Inter::CosineSqAngle::className () const
Return name string "CosineSqAngle" for this evaluator class.
Reimplemented from Util::ParamComposite.
Definition at line 202 of file CosineSqAngle.cpp.
The documentation for this class was generated from the following files:
CosineSqAngle.h
CosineSqAngle.cpp