Simpatico: Util::XmlStartTag Class Reference
Util::XmlStartTag Class Reference
Util namespace » Xml Tag Parsers
Detailed Description
Parser for an XML start tag.
Usage:
XmlStartTag tag;
XmlAttribute attribute;
std::string line;
tag.matchLabel(line, 0);
while (matchAttribute(attribute)) {
   // process attribute;
}
tag.finish();
Definition at line 36 of file XmlStartTag.h.
#include <XmlStartTag.h>
Public Member Functions
XmlStartTag ()
Constructor.
~XmlStartTag ()
Destructor.
bool matchLabel (const std::string &string, int begin)
Match opening bracket and any label.
void matchLabel (const std::string expected, const std::string &string, int begin)
Match opening bracket and a specific required label.
bool matchAttribute (XmlAttribute &attribute)
Attempt to match an attribute.
void finish ()
Check if end bracket was found.
const std::string label ()
Label string.
bool endBracket ()
True if a closing bracket was found.
Public Member Functions inherited from Util::XmlBase
XmlBase ()
Constructor.
~XmlBase ()
Destructor.
void setString (const std::string &string, int cursor=0)
Initialize string and cursor.
void setCursor (int cursor)
Set cursor.
void skip ()
Skip leading white space, if any.
void next ()
Advance to the next character.
const std::string & string () const
Return the associated string.
int cursor () const
Return the index of the current character.
int c () const
Return the current character.
bool isEnd () const
Has the cursor reached the end of the string?
Constructor & Destructor Documentation
Util::XmlStartTag::XmlStartTag ()
Constructor.
Definition at line 14 of file XmlStartTag.cpp.
Util::XmlStartTag::~XmlStartTag ()
Destructor.
Definition at line 18 of file XmlStartTag.cpp.
Member Function Documentation
bool Util::XmlStartTag::matchLabel (const std::string & string, int begin)
Match opening bracket and any label.
Parameters
string containing text of XML tag
begin index of first character
Returns
true if match, false otherwise
Definition at line 21 of file XmlStartTag.cpp.
References Util::XmlBase::c(), Util::XmlBase::cursor(), Util::XmlBase::isEnd(), Util::XmlBase::next(), Util::XmlBase::setString(), Util::XmlBase::skip(), and Util::XmlBase::string().
Referenced by matchLabel(), and Tools::HoomdConfigReader::readConfig().
void Util::XmlStartTag::matchLabel (const std::string expected, const std::string & string, int begin)
Match opening bracket and a specific required label.
Throws exception if no match.
Parameters
expected expected label string
string containing text of XML tag
begin index of first character
Definition at line 58 of file XmlStartTag.cpp.
References Util::Log::file(), label(), matchLabel(), and UTIL_THROW.
bool Util::XmlStartTag::matchAttribute (XmlAttribute & attribute)
Attempt to match an attribute.
Parameters
attribute on return, matched attribute, if any
Returns
true if an attribute is found, false otherwise
Definition at line 71 of file XmlStartTag.cpp.
References Util::XmlBase::c(), Util::XmlBase::isEnd(), Util::XmlAttribute::match(), Util::XmlBase::next(), and Util::XmlBase::skip().
Referenced by Tools::HoomdConfigReader::readConfig().
void Util::XmlStartTag::finish ()
Check if end bracket was found.
Throws exception if no end bracket was found.
Definition at line 93 of file XmlStartTag.cpp.
References endBracket(), Util::Log::file(), Util::XmlBase::string(), and UTIL_THROW.
Referenced by Tools::HoomdConfigReader::readConfig().
const std::string Util::XmlStartTag::label () inline
Label string.
Definition at line 90 of file XmlStartTag.h.
Referenced by matchLabel(), and Tools::HoomdConfigReader::readConfig().
bool Util::XmlStartTag::endBracket () inline
True if a closing bracket was found.
Definition at line 96 of file XmlStartTag.h.
Referenced by finish().
The documentation for this class was generated from the following files:
XmlStartTag.h
XmlStartTag.cpp