Simpatico: DdMd::Analyzer Class Reference
DdMd::Analyzer Class Reference abstract
DdMd namespace » Analyzers » Analyzer Base
Detailed Description
Abstract base for periodic output and/or analysis actions.
The periodic action associated with an Analyzer is implemented by the pure virtual sample() method. This action often involves computation of a physical property, which may be either added it to statistical accumulator or output to a file, or both. The sample() method is called periodically during a simulation, with a period determined by the interval member variable. The interval for each analyzer must be a multiple of the static member variable Analyzer::baseInterval.
An AnalyzerManager object acts as a container for Analyzers that are associated with a simulation. The AnalyzerManager::sample() function is called every time step, and calls the sample() function of each Analyzer only on time steps when the simulation step index is an integer multiple of the interval for that Analyzer.
An Analyzer has access to its parent Simulation via the protected Analyzer::simulation() method, which returns the parent Simulation by reference.
Definition at line 49 of file ddMd/analyzers/Analyzer.h.
#include <Analyzer.h>
Public Member Functions
Analyzer (Simulation &simulation)
Constructor.
virtual ~Analyzer ()
Destructor.
virtual void setup ()
Setup before simulation.
virtual void clear ()
Clear statistical accumulators.
virtual void sample (long iStep)=0
Calculate, analyze and/or output a physical quantity.
virtual void output ()
Output any results at the end of a simulation.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void readParameters (std::istream &in)
Read the body of parameter block, without begin and end lines.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Static Public Member Functions
static void initStatic ()
Define and initialize baseInterval.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Public Attributes
static long baseInterval = 1
The interval for an Analyzer must be a multiple of baseInterval.
Protected Member Functions
void readInterval (std::istream &in)
Read parameter interval from file.
void loadInterval (Serializable::IArchive &ar)
Load parameter interval from input archive.
void saveInterval (Serializable::OArchive &ar)
Save interval parameter to an archive.
void readOutputFileName (std::istream &in)
Read outputFileName from file.
void loadOutputFileName (Serializable::IArchive &ar)
Load output file name to an archive.
void saveOutputFileName (Serializable::OArchive &ar)
Save output file name to an archive.
Simulation & simulation ()
Get the parent Simulation by reference.
const std::string & outputFileName () const
Return outputFileName string.
std::string outputFileName (const std::string &suffix) const
Return outputFileName string with added suffix.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Constructor & Destructor Documentation
DdMd::Analyzer::Analyzer (Simulation & simulation)
Constructor.
Definition at line 26 of file ddMd/analyzers/Analyzer.cpp.
DdMd::Analyzer::~Analyzer () virtual
Destructor.
Definition at line 36 of file ddMd/analyzers/Analyzer.cpp.
Member Function Documentation
virtual void DdMd::Analyzer::setup () inline virtual
Setup before simulation.
This method is called just before the beginning of the main simulation loop within the Integrator::run() method. It may be used to complete any initialization or checks that require knowledge of the configuration. It will be called every time run is invoked, not just the first.
The default implementation is empty.
Reimplemented in DdMd::SymmTensorAverageAnalyzer, DdMd::EnergyAnalyzer, DdMd::TensorAverageAnalyzer, DdMd::AverageAnalyzer, DdMd::TrajectoryWriter, DdMd::AutoCorrAnalyzer< Data, Product >, DdMd::AutoCorrAnalyzer< Tensor, double >, DdMd::OutputPressure, DdMd::StressAutoCorr, DdMd::OutputEnergy, DdMd::OutputTemperature, DdMd::OutputBoxdim, and DdMd::OutputStressTensor.
Definition at line 77 of file ddMd/analyzers/Analyzer.h.
virtual void DdMd::Analyzer::clear () inline virtual
Clear statistical accumulators.
This method is called by the Integrator::clear() method, which is called before the main simulation loop only the first time that the integrator is run, and when invoked explicitly thereafter.
The default implementation is empty.
Reimplemented in DdMd::VanHove, DdMd::StructureFactor, DdMd::StructureFactorGrid, DdMd::OrderParamNucleation, DdMd::TrajectoryWriter, DdMd::SymmTensorAverageAnalyzer, DdMd::TensorAverageAnalyzer, DdMd::AverageAnalyzer, DdMd::EnergyAnalyzer, DdMd::ConfigWriter, DdMd::AutoCorrAnalyzer< Data, Product >, DdMd::AutoCorrAnalyzer< Tensor, double >, DdMd::LogEnergy, DdMd::VirialStressTensorAverage, DdMd::OutputPairEnergies, DdMd::OutputPressure, DdMd::StressAutoCorr, DdMd::VirialStressTensor, DdMd::ExternalEnergyAverage, DdMd::OutputEnergy, DdMd::OutputTemperature, DdMd::PairEnergyAverage, DdMd::OutputBoxdim, and DdMd::OutputStressTensor.
Definition at line 90 of file ddMd/analyzers/Analyzer.h.
virtual void DdMd::Analyzer::sample (long iStep) pure virtual
Calculate, analyze and/or output a physical quantity.
Take an action if iStep is a multiple of interval. If iStep is not a multiple of interval, this method should do nothing and return immediately.
Parameters
iStep current simulation step index.
Implemented in DdMd::VanHove, DdMd::StructureFactor, DdMd::StructureFactorGrid, DdMd::OrderParamNucleation, DdMd::TensorAverageAnalyzer, DdMd::SymmTensorAverageAnalyzer, DdMd::EnergyAnalyzer, DdMd::AverageAnalyzer, DdMd::TrajectoryWriter, DdMd::ConfigWriter, DdMd::AutoCorrAnalyzer< Data, Product >, DdMd::AutoCorrAnalyzer< Tensor, double >, DdMd::OutputPressure, DdMd::StressAutoCorr, DdMd::OutputEnergy, DdMd::OutputTemperature, DdMd::OutputBoxdim, DdMd::OutputStressTensor, DdMd::LogEnergy, DdMd::VirialStressTensorAverage, DdMd::OutputPairEnergies, DdMd::VirialStressTensor, DdMd::ExternalEnergyAverage, and DdMd::PairEnergyAverage.
virtual void DdMd::Analyzer::output () inline virtual
Output any results at the end of a simulation.
The default implementation is empty.
Reimplemented in DdMd::VanHove, DdMd::StructureFactor, DdMd::StructureFactorGrid, DdMd::OrderParamNucleation, DdMd::TensorAverageAnalyzer, DdMd::SymmTensorAverageAnalyzer, DdMd::TrajectoryWriter, DdMd::EnergyAnalyzer, DdMd::AverageAnalyzer, DdMd::AutoCorrAnalyzer< Data, Product >, DdMd::AutoCorrAnalyzer< Tensor, double >, DdMd::StressAutoCorr, DdMd::VirialStressTensorAverage, DdMd::ExternalEnergyAverage, and DdMd::PairEnergyAverage.
Definition at line 109 of file ddMd/analyzers/Analyzer.h.
virtual void DdMd::Analyzer::loadParameters (Serializable::IArchive & ar) inline virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Reimplemented in DdMd::VanHove, DdMd::StructureFactor, DdMd::StructureFactorGrid, DdMd::OrderParamNucleation, DdMd::TrajectoryWriter, DdMd::SymmTensorAverageAnalyzer, DdMd::TensorAverageAnalyzer, DdMd::AverageAnalyzer, DdMd::EnergyAnalyzer, DdMd::ConfigWriter, DdMd::AutoCorrAnalyzer< Data, Product >, DdMd::AutoCorrAnalyzer< Tensor, double >, DdMd::LogEnergy, DdMd::VirialStressTensorAverage, DdMd::OutputPairEnergies, DdMd::OutputPressure, DdMd::StressAutoCorr, DdMd::VirialStressTensor, DdMd::ExternalEnergyAverage, DdMd::OutputEnergy, DdMd::OutputTemperature, DdMd::PairEnergyAverage, DdMd::OutputBoxdim, DdMd::OutputStressTensor, DdMd::PairEnergyAnalyzer, and DdMd::DdMdGroupTrajectoryWriter.
Definition at line 117 of file ddMd/analyzers/Analyzer.h.
virtual void DdMd::Analyzer::save (Serializable::OArchive & ar) inline virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Reimplemented in DdMd::VanHove, DdMd::StructureFactor, DdMd::StructureFactorGrid, DdMd::OrderParamNucleation, DdMd::TrajectoryWriter, DdMd::SymmTensorAverageAnalyzer, DdMd::TensorAverageAnalyzer, DdMd::AverageAnalyzer, DdMd::EnergyAnalyzer, DdMd::ConfigWriter, DdMd::AutoCorrAnalyzer< Data, Product >, DdMd::AutoCorrAnalyzer< Tensor, double >, DdMd::LogEnergy, DdMd::VirialStressTensorAverage, DdMd::OutputPairEnergies, DdMd::OutputPressure, DdMd::StressAutoCorr, DdMd::VirialStressTensor, DdMd::ExternalEnergyAverage, DdMd::OutputEnergy, DdMd::OutputTemperature, DdMd::PairEnergyAverage, DdMd::OutputBoxdim, DdMd::OutputStressTensor, DdMd::PairEnergyAnalyzer, and DdMd::DdMdGroupTrajectoryWriter.
Definition at line 125 of file ddMd/analyzers/Analyzer.h.
int DdMd::Analyzer::interval () const inline
Get interval value.
Definition at line 237 of file ddMd/analyzers/Analyzer.h.
Referenced by DdMd::AverageAnalyzer::sample(), DdMd::EnergyAnalyzer::sample(), DdMd::SymmTensorAverageAnalyzer::sample(), and DdMd::TensorAverageAnalyzer::sample().
bool DdMd::Analyzer::isAtInterval (long counter) const inline
Return true iff counter is a multiple of the interval.
Parameters
counter simulation step counter
Definition at line 243 of file ddMd/analyzers/Analyzer.h.
Referenced by DdMd::ExternalEnergyAverage::sample(), DdMd::PairEnergyAverage::sample(), DdMd::OutputPairEnergies::sample(), DdMd::VirialStressTensor::sample(), DdMd::VirialStressTensorAverage::sample(), DdMd::LogEnergy::sample(), DdMd::OutputStressTensor::sample(), DdMd::OutputEnergy::sample(), DdMd::OutputTemperature::sample(), DdMd::OutputBoxdim::sample(), DdMd::OutputPressure::sample(), DdMd::StressAutoCorr::sample(), DdMd::AutoCorrAnalyzer< Data, Product >::sample(), DdMd::ConfigWriter::sample(), DdMd::TrajectoryWriter::sample(), DdMd::AverageAnalyzer::sample(), DdMd::EnergyAnalyzer::sample(), DdMd::SymmTensorAverageAnalyzer::sample(), DdMd::TensorAverageAnalyzer::sample(), DdMd::OrderParamNucleation::sample(), DdMd::StructureFactorGrid::sample(), DdMd::StructureFactor::sample(), and DdMd::VanHove::sample().
void DdMd::Analyzer::initStatic () static
Define and initialize baseInterval.
Definition at line 20 of file ddMd/analyzers/Analyzer.cpp.
void DdMd::Analyzer::readInterval (std::istream & in) protected
Read parameter interval from file.
This function throws an exception if the value of interval is not a multiple of Analyzer::baseInterval, or if baseInterval has not been set to a nonzero positive value.
Parameters
in input parameter file stream.
Definition at line 42 of file ddMd/analyzers/Analyzer.cpp.
References baseInterval, and UTIL_THROW.
Referenced by DdMd::OutputStressTensor::readParameters(), DdMd::OutputBoxdim::readParameters(), DdMd::OutputEnergy::readParameters(), DdMd::ExternalEnergyAverage::readParameters(), DdMd::OutputTemperature::readParameters(), DdMd::PairEnergyAverage::readParameters(), DdMd::VirialStressTensor::readParameters(), DdMd::OutputPairEnergies::readParameters(), DdMd::OutputPressure::readParameters(), DdMd::StressAutoCorr::readParameters(), DdMd::VirialStressTensorAverage::readParameters(), DdMd::LogEnergy::readParameters(), DdMd::AutoCorrAnalyzer< Data, Product >::readParameters(), DdMd::EnergyAnalyzer::readParameters(), DdMd::ConfigWriter::readParameters(), DdMd::AverageAnalyzer::readParameters(), DdMd::SymmTensorAverageAnalyzer::readParameters(), DdMd::TensorAverageAnalyzer::readParameters(), DdMd::TrajectoryWriter::readParameters(), DdMd::OrderParamNucleation::readParameters(), DdMd::StructureFactorGrid::readParameters(), DdMd::StructureFactor::readParameters(), and DdMd::VanHove::readParameters().
void DdMd::Analyzer::loadInterval (Serializable::IArchive & ar) protected
Load parameter interval from input archive.
This function throws an exception if the value of interval is not a multiple of Analyzer::baseInterval, or if baseInterval has not been set to a nonzero positive value.
Parameters
ar input archive
Definition at line 74 of file ddMd/analyzers/Analyzer.cpp.
References baseInterval, and UTIL_THROW.
Referenced by DdMd::OutputStressTensor::loadParameters(), DdMd::OutputBoxdim::loadParameters(), DdMd::OutputEnergy::loadParameters(), DdMd::ExternalEnergyAverage::loadParameters(), DdMd::OutputTemperature::loadParameters(), DdMd::PairEnergyAverage::loadParameters(), DdMd::VirialStressTensor::loadParameters(), DdMd::OutputPairEnergies::loadParameters(), DdMd::OutputPressure::loadParameters(), DdMd::StressAutoCorr::loadParameters(), DdMd::VirialStressTensorAverage::loadParameters(), DdMd::LogEnergy::loadParameters(), DdMd::AutoCorrAnalyzer< Data, Product >::loadParameters(), DdMd::EnergyAnalyzer::loadParameters(), DdMd::ConfigWriter::loadParameters(), DdMd::AverageAnalyzer::loadParameters(), DdMd::SymmTensorAverageAnalyzer::loadParameters(), DdMd::TensorAverageAnalyzer::loadParameters(), DdMd::TrajectoryWriter::loadParameters(), DdMd::OrderParamNucleation::loadParameters(), DdMd::StructureFactorGrid::loadParameters(), DdMd::StructureFactor::loadParameters(), and DdMd::VanHove::loadParameters().
void DdMd::Analyzer::saveInterval (Serializable::OArchive & ar) protected
Save interval parameter to an archive.
Parameters
ar output archive
Definition at line 103 of file ddMd/analyzers/Analyzer.cpp.
Referenced by DdMd::OutputStressTensor::save(), DdMd::OutputBoxdim::save(), DdMd::OutputEnergy::save(), DdMd::ExternalEnergyAverage::save(), DdMd::OutputTemperature::save(), DdMd::PairEnergyAverage::save(), DdMd::VirialStressTensor::save(), DdMd::OutputPairEnergies::save(), DdMd::OutputPressure::save(), DdMd::StressAutoCorr::save(), DdMd::VirialStressTensorAverage::save(), DdMd::LogEnergy::save(), DdMd::AutoCorrAnalyzer< Data, Product >::save(), DdMd::EnergyAnalyzer::save(), DdMd::ConfigWriter::save(), DdMd::AverageAnalyzer::save(), DdMd::SymmTensorAverageAnalyzer::save(), DdMd::TensorAverageAnalyzer::save(), DdMd::TrajectoryWriter::save(), DdMd::OrderParamNucleation::save(), DdMd::StructureFactorGrid::save(), DdMd::StructureFactor::save(), and DdMd::VanHove::save().
void DdMd::Analyzer::readOutputFileName (std::istream & in) protected
Read outputFileName from file.
Parameters
in input parameter file
Definition at line 109 of file ddMd/analyzers/Analyzer.cpp.
Referenced by DdMd::OutputStressTensor::readParameters(), DdMd::ExternalEnergyAverage::readParameters(), DdMd::OutputEnergy::readParameters(), DdMd::OutputBoxdim::readParameters(), DdMd::OutputTemperature::readParameters(), DdMd::PairEnergyAverage::readParameters(), DdMd::OutputPairEnergies::readParameters(), DdMd::VirialStressTensor::readParameters(), DdMd::OutputPressure::readParameters(), DdMd::StressAutoCorr::readParameters(), DdMd::VirialStressTensorAverage::readParameters(), DdMd::AutoCorrAnalyzer< Data, Product >::readParameters(), DdMd::EnergyAnalyzer::readParameters(), DdMd::ConfigWriter::readParameters(), DdMd::AverageAnalyzer::readParameters(), DdMd::SymmTensorAverageAnalyzer::readParameters(), DdMd::TensorAverageAnalyzer::readParameters(), DdMd::TrajectoryWriter::readParameters(), DdMd::OrderParamNucleation::readParameters(), DdMd::StructureFactorGrid::readParameters(), DdMd::StructureFactor::readParameters(), and DdMd::VanHove::readParameters().
void DdMd::Analyzer::loadOutputFileName (Serializable::IArchive & ar) protected
Load output file name to an archive.
Parameters
ar input archive
Definition at line 115 of file ddMd/analyzers/Analyzer.cpp.
Referenced by DdMd::OutputStressTensor::loadParameters(), DdMd::ExternalEnergyAverage::loadParameters(), DdMd::OutputEnergy::loadParameters(), DdMd::OutputBoxdim::loadParameters(), DdMd::OutputTemperature::loadParameters(), DdMd::PairEnergyAverage::loadParameters(), DdMd::OutputPairEnergies::loadParameters(), DdMd::VirialStressTensor::loadParameters(), DdMd::OutputPressure::loadParameters(), DdMd::StressAutoCorr::loadParameters(), DdMd::VirialStressTensorAverage::loadParameters(), DdMd::AutoCorrAnalyzer< Data, Product >::loadParameters(), DdMd::EnergyAnalyzer::loadParameters(), DdMd::ConfigWriter::loadParameters(), DdMd::AverageAnalyzer::loadParameters(), DdMd::SymmTensorAverageAnalyzer::loadParameters(), DdMd::TensorAverageAnalyzer::loadParameters(), DdMd::TrajectoryWriter::loadParameters(), DdMd::OrderParamNucleation::loadParameters(), DdMd::StructureFactorGrid::loadParameters(), DdMd::StructureFactor::loadParameters(), and DdMd::VanHove::loadParameters().
void DdMd::Analyzer::saveOutputFileName (Serializable::OArchive & ar) protected
Save output file name to an archive.
Parameters
ar output archive
Definition at line 121 of file ddMd/analyzers/Analyzer.cpp.
Referenced by DdMd::OutputStressTensor::save(), DdMd::ExternalEnergyAverage::save(), DdMd::OutputEnergy::save(), DdMd::OutputBoxdim::save(), DdMd::OutputTemperature::save(), DdMd::PairEnergyAverage::save(), DdMd::OutputPairEnergies::save(), DdMd::VirialStressTensor::save(), DdMd::OutputPressure::save(), DdMd::StressAutoCorr::save(), DdMd::VirialStressTensorAverage::save(), DdMd::AutoCorrAnalyzer< Data, Product >::save(), DdMd::EnergyAnalyzer::save(), DdMd::ConfigWriter::save(), DdMd::AverageAnalyzer::save(), DdMd::SymmTensorAverageAnalyzer::save(), DdMd::TensorAverageAnalyzer::save(), DdMd::TrajectoryWriter::save(), DdMd::OrderParamNucleation::save(), DdMd::StructureFactorGrid::save(), DdMd::StructureFactor::save(), and DdMd::VanHove::save().
Simulation & DdMd::Analyzer::simulation () inline protected
Get the parent Simulation by reference.
Definition at line 255 of file ddMd/analyzers/Analyzer.h.
Referenced by DdMd::ExternalEnergyAverage::clear(), DdMd::PairEnergyAverage::clear(), DdMd::StressAutoCorr::clear(), DdMd::VirialStressTensorAverage::clear(), DdMd::AutoCorrAnalyzer< Data, Product >::clear(), DdMd::EnergyAnalyzer::clear(), DdMd::AverageAnalyzer::clear(), DdMd::SymmTensorAverageAnalyzer::clear(), DdMd::TensorAverageAnalyzer::clear(), DdMd::StructureFactor::clear(), DdMd::VanHove::clear(), DdMd::PressureAnalyzer::compute(), DdMd::StressAnalyzer::compute(), DdMd::VirialStressAnalyzer::compute(), DdMd::ExternalEnergyAnalyzer::compute(), DdMd::KineticEnergyAnalyzer::compute(), DdMd::PairEnergyAnalyzer::compute(), DdMd::BondTensorAutoCorr::computeData(), DdMd::StressAutoCorrelation::computeData(), DdMd::BondTensorAutoCorr::data(), DdMd::StressAutoCorrelation::data(), DdMd::OutputStressTensor::loadParameters(), DdMd::PairEnergyAverage::loadParameters(), DdMd::OutputEnergy::loadParameters(), DdMd::ExternalEnergyAverage::loadParameters(), DdMd::OutputTemperature::loadParameters(), DdMd::StressAutoCorr::loadParameters(), DdMd::OutputPairEnergies::loadParameters(), DdMd::OutputPressure::loadParameters(), DdMd::VirialStressTensor::loadParameters(), DdMd::VirialStressTensorAverage::loadParameters(), DdMd::AutoCorrAnalyzer< Data, Product >::loadParameters(), DdMd::EnergyAnalyzer::loadParameters(), DdMd::AverageAnalyzer::loadParameters(), DdMd::SymmTensorAverageAnalyzer::loadParameters(), DdMd::TensorAverageAnalyzer::loadParameters(), DdMd::OrderParamNucleation::loadParameters(), DdMd::StructureFactorGrid::loadParameters(), DdMd::StructureFactor::loadParameters(), DdMd::VanHove::loadParameters(), DdMd::VanHove::makeWaveVectors(), DdMd::StructureFactor::makeWaveVectors(), DdMd::PairEnergyAverage::output(), DdMd::ExternalEnergyAverage::output(), DdMd::VirialStressTensorAverage::output(), DdMd::StressAutoCorr::output(), DdMd::AutoCorrAnalyzer< Data, Product >::output(), DdMd::AverageAnalyzer::output(), DdMd::EnergyAnalyzer::output(), DdMd::SymmTensorAverageAnalyzer::output(), DdMd::TensorAverageAnalyzer::output(), DdMd::OrderParamNucleation::output(), DdMd::StructureFactorGrid::output(), DdMd::StructureFactor::output(), DdMd::VanHove::output(), DdMd::OutputStressTensor::readParameters(), DdMd::PairEnergyAverage::readParameters(), DdMd::OutputBoxdim::readParameters(), DdMd::OutputEnergy::readParameters(), DdMd::ExternalEnergyAverage::readParameters(), DdMd::OutputTemperature::readParameters(), DdMd::StressAutoCorr::readParameters(), DdMd::OutputPairEnergies::readParameters(), DdMd::OutputPressure::readParameters(), DdMd::VirialStressTensor::readParameters(), DdMd::VirialStressTensorAverage::readParameters(), DdMd::AutoCorrAnalyzer< Data, Product >::readParameters(), DdMd::EnergyAnalyzer::readParameters(), DdMd::AverageAnalyzer::readParameters(), DdMd::SymmTensorAverageAnalyzer::readParameters(), DdMd::TensorAverageAnalyzer::readParameters(), DdMd::OrderParamNucleation::readParameters(), DdMd::StructureFactorGrid::readParameters(), DdMd::StructureFactor::readParameters(), DdMd::VanHove::readParameters(), DdMd::PairEnergyAverage::sample(), DdMd::ExternalEnergyAverage::sample(), DdMd::OutputPairEnergies::sample(), DdMd::VirialStressTensor::sample(), DdMd::LogEnergy::sample(), DdMd::VirialStressTensorAverage::sample(), DdMd::OutputStressTensor::sample(), DdMd::OutputTemperature::sample(), DdMd::OutputEnergy::sample(), DdMd::OutputBoxdim::sample(), DdMd::StressAutoCorr::sample(), DdMd::OutputPressure::sample(), DdMd::AutoCorrAnalyzer< Data, Product >::sample(), DdMd::ConfigWriter::sample(), DdMd::AverageAnalyzer::sample(), DdMd::EnergyAnalyzer::sample(), DdMd::SymmTensorAverageAnalyzer::sample(), DdMd::TensorAverageAnalyzer::sample(), DdMd::OrderParamNucleation::sample(), DdMd::StructureFactorGrid::sample(), DdMd::StructureFactor::sample(), DdMd::VanHove::sample(), DdMd::ExternalEnergyAverage::save(), DdMd::StressAutoCorr::save(), DdMd::VirialStressTensorAverage::save(), DdMd::AutoCorrAnalyzer< Data, Product >::save(), DdMd::EnergyAnalyzer::save(), DdMd::AverageAnalyzer::save(), DdMd::TensorAverageAnalyzer::save(), DdMd::SymmTensorAverageAnalyzer::save(), DdMd::VanHove::save(), DdMd::OutputStressTensor::setup(), DdMd::OutputBoxdim::setup(), DdMd::OutputTemperature::setup(), DdMd::OutputEnergy::setup(), DdMd::OutputPressure::setup(), DdMd::TrajectoryWriter::setup(), DdMd::AverageAnalyzer::setup(), DdMd::TensorAverageAnalyzer::setup(), DdMd::EnergyAnalyzer::setup(), DdMd::SymmTensorAverageAnalyzer::setup(), DdMd::VirialStressAnalyzer::value(), DdMd::StressAnalyzer::value(), DdMd::PressureAnalyzer::value(), DdMd::ExternalEnergyAnalyzer::value(), DdMd::KineticEnergyAnalyzer::value(), DdMd::PairEnergyAnalyzer::value(), and DdMd::PairEnergyAverage::~PairEnergyAverage().
const std::string & DdMd::Analyzer::outputFileName () const inline protected
Return outputFileName string.
Definition at line 249 of file ddMd/analyzers/Analyzer.h.
Referenced by DdMd::OutputStressTensor::loadParameters(), DdMd::OutputEnergy::loadParameters(), DdMd::OutputTemperature::loadParameters(), DdMd::VirialStressTensor::loadParameters(), DdMd::OutputPressure::loadParameters(), DdMd::OutputPairEnergies::loadParameters(), DdMd::VirialStressTensorAverage::loadParameters(), DdMd::PairEnergyAverage::output(), DdMd::ExternalEnergyAverage::output(), DdMd::StressAutoCorr::output(), DdMd::AutoCorrAnalyzer< Data, Product >::output(), DdMd::AverageAnalyzer::output(), DdMd::EnergyAnalyzer::output(), DdMd::SymmTensorAverageAnalyzer::output(), DdMd::TensorAverageAnalyzer::output(), DdMd::OrderParamNucleation::output(), DdMd::StructureFactorGrid::output(), DdMd::StructureFactor::output(), DdMd::VanHove::output(), DdMd::OutputStressTensor::readParameters(), DdMd::OutputBoxdim::readParameters(), DdMd::OutputEnergy::readParameters(), DdMd::OutputTemperature::readParameters(), DdMd::OutputPressure::readParameters(), DdMd::VirialStressTensor::readParameters(), DdMd::OutputPairEnergies::readParameters(), DdMd::VirialStressTensorAverage::readParameters(), DdMd::ConfigWriter::sample(), DdMd::StructureFactorGrid::sample(), DdMd::StructureFactor::sample(), DdMd::OutputStressTensor::setup(), DdMd::OutputBoxdim::setup(), DdMd::OutputEnergy::setup(), DdMd::OutputTemperature::setup(), DdMd::OutputPressure::setup(), DdMd::TrajectoryWriter::setup(), DdMd::AverageAnalyzer::setup(), DdMd::TensorAverageAnalyzer::setup(), DdMd::EnergyAnalyzer::setup(), and DdMd::SymmTensorAverageAnalyzer::setup().
std::string DdMd::Analyzer::outputFileName (const std::string & suffix) const protected
Return outputFileName string with added suffix.
Definition at line 127 of file ddMd/analyzers/Analyzer.cpp.
Member Data Documentation
long DdMd::Analyzer::baseInterval = 1 static
The interval for an Analyzer must be a multiple of baseInterval.
Definition at line 145 of file ddMd/analyzers/Analyzer.h.
Referenced by loadInterval(), DdMd::AnalyzerManager::loadParameters(), DdMd::Integrator::loadParameters(), readInterval(), DdMd::AnalyzerManager::readParameters(), DdMd::Integrator::readParameters(), DdMd::AnalyzerManager::sample(), and DdMd::AnalyzerManager::save().
The documentation for this class was generated from the following files:
ddMd/analyzers/Analyzer.h
ddMd/analyzers/Analyzer.cpp