Simpatico: MdCf::Processor Class Reference
MdCf::Processor Class Reference
MdCf namespace
Detailed Description
A post-processor for analyzing outputs of MD simulations.
Definition at line 28 of file Processor.h.
#include <Processor.h>
Public Member Functions
Processor ()
Constructor.
~Processor ()
Destructor.
void readParam (const char *filename)
Open, read, and close parameter file.
void readParameters (std::istream &in)
Read parameters.
void setConfigIo (std::string configIoName)
Set ConfigIo style.
ConfigIo & configIo ()
Return the ConfigIo (create default if necessary).
void readConfig (std::ifstream &in)
Read a single configuration file.
void readConfig (const char *filename)
Open, read and close a configuration file.
void readConfig (const std::string &filename)
Open, read and close a configuration file.
void writeConfig (std::ofstream &out)
Write a single configuration file.
void writeConfig (const std::string &filename)
Open, write and close a configuration file.
void analyzeDumps (int min, int max, std::string fileBaseName)
Read and analyze a sequence of numbered configuration files.
void analyzeTrajectory (std::string &filename)
Analyze a trajectory file.
Public Member Functions inherited from MdCf::Storage
Storage ()
Constructor.
~Storage ()
Destructor.
void readParam (const char *filename)
Open, read, and close parameter file.
void readParameters (std::istream &in)
Read parameters.
void clear ()
Clear all atoms and groups.
Boundary & boundary ()
Get the Boundary by non-const reference.
AtomStorage & atoms ()
Get the AtomStorage.
GroupStorage< 2 > & bonds ()
Get the Bond Storage.
GroupStorage< 3 > & angles ()
Get the Angle Storage.
GroupStorage< 4 > & dihedrals ()
Get the Dihedral Storage.
int nSpecies () const
Number of species.
Species & species (int i)
Get a particular species identified by index.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Constructor & Destructor Documentation
MdCf::Processor::Processor ()
Constructor.
Definition at line 20 of file Processor.cpp.
References Util::ParamComposite::setClassName().
MdCf::Processor::~Processor ()
Destructor.
Definition at line 29 of file Processor.cpp.
Member Function Documentation
void MdCf::Processor::readParam (const char * filename)
Open, read, and close parameter file.
Definition at line 39 of file Processor.cpp.
void MdCf::Processor::readParameters (std::istream & in) virtual
Read parameters.
Reimplemented from Util::ParamComposite.
Definition at line 50 of file Processor.cpp.
References Util::ParamComposite::readParamComposite(), and MdCf::Storage::readParameters().
void MdCf::Processor::setConfigIo (std::string configIoName)
Set ConfigIo style.
Definition at line 61 of file Processor.cpp.
References MdCf::ConfigIoFactory::factory(), and UTIL_THROW.
ConfigIo & MdCf::Processor::configIo ()
Return the ConfigIo (create default if necessary).
Definition at line 75 of file Processor.cpp.
Referenced by readConfig(), and writeConfig().
void MdCf::Processor::readConfig (std::ifstream & in)
Read a single configuration file.
Definition at line 89 of file Processor.cpp.
References MdCf::Storage::clear(), configIo(), and MdCf::ConfigIo::readConfig().
Referenced by analyzeDumps(), and readConfig().
void MdCf::Processor::readConfig (const char * filename)
Open, read and close a configuration file.
Definition at line 98 of file Processor.cpp.
References readConfig().
void MdCf::Processor::readConfig (const std::string & filename)
Open, read and close a configuration file.
Definition at line 109 of file Processor.cpp.
References readConfig().
void MdCf::Processor::writeConfig (std::ofstream & out)
Write a single configuration file.
Definition at line 115 of file Processor.cpp.
References configIo(), and MdCf::ConfigIo::writeConfig().
void MdCf::Processor::writeConfig (const std::string & filename)
Open, write and close a configuration file.
Definition at line 121 of file Processor.cpp.
References configIo(), and MdCf::ConfigIo::writeConfig().
void MdCf::Processor::analyzeDumps (int min, int max, std::string fileBaseName)
Read and analyze a sequence of numbered configuration files.
This function reads and analyzes a sequence of configuration files that were generated by running a previous simulation. The function reads files with names of the form inputPrefix() + n for integer suffixes min <= n <= max.
Parameters
min integer suffix of first configuration file name
max integer suffix of last configuration file name
fileBaseName root name for dump files (without integer suffix)
Definition at line 134 of file Processor.cpp.
References MdCf::Storage::clear(), Util::Log::file(), MdCf::AnalyzerManager::output(), readConfig(), MdCf::AnalyzerManager::sample(), MdCf::AnalyzerManager::setup(), and UTIL_THROW.
void MdCf::Processor::analyzeTrajectory (std::string & filename)
Analyze a trajectory file.
The documentation for this class was generated from the following files:
Processor.h
Processor.cpp