Simpatico: McMd::BlockRadiusGyration Class Reference
McMd::BlockRadiusGyration Class Reference
Diagnostics
Detailed Description
Radius of gyration of different blocks in a molecule.
The radius of gyration R_{g,i} of a block of atom type i is the root mean-squared separation of atoms in a block from the center of mass of block. For a species of molecule with N_i atoms of type i, with positions ,we define
where is the center of mass of block, and where denotes an ensemble average over all molecules of a specified species.
This class calculates the radius of gyration of blocks by accumulating an average value for the above quantity, and optionally outputs block averages to file at an interval specified by the input parameter nSamplePerBlock. No block averages are output if nSamplePerBlock = 0.
Definition at line 50 of file BlockRadiusGyration.h.
#include <BlockRadiusGyration.h>
Public Member Functions
BlockRadiusGyration (System &system)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters from file, and allocate data array.
virtual void setup ()
Clear accumulator.
virtual void sample (long iStep)
Evaluate squared radii of gyration for all molecules, add to ensemble.
virtual void output ()
Output results at end of simulation.
virtual void save (Serializable::OArchive &ar)
Save state to archive.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
Constructor & Destructor Documentation
McMd::BlockRadiusGyration::BlockRadiusGyration (System & system)
Constructor.
Parameters:
system reference to parent System object
Definition at line 28 of file BlockRadiusGyration.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::BlockRadiusGyration::readParameters (std::istream & in) [virtual]
Read parameters from file, and allocate data array.
Read parameters from file, and allocate arrays.
Input format:
int interval : sampling interval
string outputFileName : base name for output file(s)
int nSamplePerBlock : interval for output of block averages
int speciesId : integer id for Species of interest
No block averages are output if nSamplePerBlock = 0. Otherwise, block averages are output to a file named (outputFileName).dat.
Parameters:
in parameter input stream
Reimplemented from McMd::Diagnostic.
Definition at line 47 of file BlockRadiusGyration.cpp.
References Util::DArray< Data >::allocate(), McMd::Diagnostic::fileMaster(), McMd::Species::nAtom(), McMd::Simulation::nAtomType(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), McMd::Diagnostic::readInterval(), McMd::Diagnostic::readOutputFileName(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::BlockRadiusGyration::setup () [virtual]
Clear accumulator.
Reimplemented from McMd::Diagnostic.
Definition at line 165 of file BlockRadiusGyration.cpp.
References UTIL_THROW.
void McMd::BlockRadiusGyration::sample (long iStep) [virtual]
Evaluate squared radii of gyration for all molecules, add to ensemble.
Parameters:
iStep step counter
Implements McMd::Diagnostic.
Definition at line 177 of file BlockRadiusGyration.cpp.
References McMd::Molecule::atom(), McMd::System::boundary(), Util::OrthorhombicBoundary::distanceSq(), McMd::Diagnostic::isAtInterval(), McMd::System::molecule(), McMd::System::nMolecule(), McMd::Atom::position(), Util::Vector::square(), Util::Vector::subtract(), McMd::SystemDiagnostic< System >::system(), and McMd::Atom::typeId().
void McMd::BlockRadiusGyration::output () [virtual]
Output results at end of simulation.
Reimplemented from McMd::Diagnostic.
Definition at line 262 of file BlockRadiusGyration.cpp.
References McMd::Diagnostic::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), and Util::ParamComposite::writeParam().
void McMd::BlockRadiusGyration::save (Serializable::OArchive & ar) [virtual]
Save state to archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 159 of file BlockRadiusGyration.cpp.
void McMd::BlockRadiusGyration::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 98 of file BlockRadiusGyration.cpp.
References Util::DArray< Data >::allocate(), McMd::Diagnostic::fileMaster(), McMd::Species::nAtom(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
template<class Archive > void McMd::BlockRadiusGyration::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Reimplemented from McMd::Diagnostic.
Definition at line 166 of file BlockRadiusGyration.h.
References McMd::serialize().
The documentation for this class was generated from the following files:
BlockRadiusGyration.h
BlockRadiusGyration.cpp