Simpatico: Tools::ProcessorAnalyzerFactory Class Reference
Tools::ProcessorAnalyzerFactory Class Reference
Analyzers
Detailed Description
Factory for Tools::Analyzer objects.
Definition at line 26 of file ProcessorAnalyzerFactory.h.
#include <ProcessorAnalyzerFactory.h>
Public Member Functions
ProcessorAnalyzerFactory (Processor &processor)
Constructor.
virtual Analyzer * factory (const std::string &className) const
Return pointer to a new Analyzer object.
Protected Member Functions
Processor & processor () const
Return reference to parent Processor.
Constructor & Destructor Documentation
Tools::ProcessorAnalyzerFactory::ProcessorAnalyzerFactory (Processor & processor)
Constructor.
Parameters:
processor associated physical Processor
Definition at line 24 of file ProcessorAnalyzerFactory.cpp.
Member Function Documentation
Analyzer * Tools::ProcessorAnalyzerFactory::factory (const std::string & className) const [virtual]
Return pointer to a new Analyzer object.
Parameters:
className name of a subclass of Analyzer.
Returns:
base class pointer to a new instance of className.
Implements Util::Factory< Analyzer >.
Definition at line 31 of file ProcessorAnalyzerFactory.cpp.
References processor(), and Util::Factory< Analyzer >::trySubfactories().
Processor& Tools::ProcessorAnalyzerFactory::processor () const [inline, protected]
Return reference to parent Processor.
Definition at line 51 of file ProcessorAnalyzerFactory.h.
Referenced by factory().
The documentation for this class was generated from the following files:
ProcessorAnalyzerFactory.h
ProcessorAnalyzerFactory.cpp