Simpatico: McMd::McBondEnergyAverage Class Reference
McMd::McBondEnergyAverage Class Reference
Diagnostics
Detailed Description
McBondEnergyAverage averages of bond potential energy.
Definition at line 26 of file McBondEnergyAverage.h.
#include <McBondEnergyAverage.h>
Public Member Functions
McBondEnergyAverage (McSystem &system)
Constructor.
virtual void sample (long iStep)
Evaluate total bond energy, and add to ensemble.
Constructor & Destructor Documentation
McMd::McBondEnergyAverage::McBondEnergyAverage (McSystem & system)
Constructor.
Definition at line 22 of file McBondEnergyAverage.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::McBondEnergyAverage::sample (long iStep) [virtual]
Evaluate total bond energy, and add to ensemble.
Implements McMd::Diagnostic.
Definition at line 29 of file McBondEnergyAverage.cpp.
References McMd::AverageDiagnostic< McSystem >::accumulator_, McMd::AverageDiagnostic< McSystem >::outputFile_, Util::Average::sample(), and McMd::SystemDiagnostic< McSystem >::system().
The documentation for this class was generated from the following files:
McBondEnergyAverage.h
McBondEnergyAverage.cpp