Simpatico: Util::DArray< Data > Class Template Reference
Util::DArray< Data > Class Template Reference
Object Arrays
Detailed Description
template<typename Data>
class Util::DArray< Data >
Dynamically allocatable Array class template.
A DArray wraps a dynamically allocated C Array. Unlike an STL std::vector, a DArray cannot be resized after it is allocated.
Definition at line 28 of file DArray.h.
#include <DArray.h>
Public Member Functions
DArray ()
Default constructor.
DArray (const DArray< Data > &other)
Copy constructor.
DArray< Data > & operator= (const DArray< Data > &other)
Assignment operator.
virtual ~DArray ()
Destructor.
void allocate (int capacity)
Allocate the underlying C array.
void deallocate ()
Dellocate the underlying C array.
bool isAllocated () const
Return true if the DArray has been allocated, false otherwise.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize a DArray to/from an Archive.
Constructor & Destructor Documentation
template<class Data > Util::DArray< Data >::DArray ()
Default constructor.
Definition at line 106 of file DArray.h.
template<class Data> Util::DArray< Data >::DArray (const DArray< Data > & other)
Copy constructor.
Allocates new memory and copies all elements by value.
Parameters:
other the DArray to be copied.
Definition at line 118 of file DArray.h.
References Util::DArray< Data >::allocate(), Util::Array< Data >::capacity_, Util::Array< Data >::data_, Util::DArray< Data >::isAllocated(), and UTIL_THROW.
template<class Data > Util::DArray< Data >::~DArray () [virtual]
Destructor.
Deletes underlying C array, if allocated previously.
Definition at line 135 of file DArray.h.
Member Function Documentation
template<class Data> DArray< Data > & Util::DArray< Data >::operator= (const DArray< Data > & other)
Assignment operator.
If this DArray is not allocated, allocates and copies all elements.
If this and the other DArray are both allocated, the capacities must be exactly equal. If so, this method copies all elements.
Parameters:
other the RHS DArray
Definition at line 154 of file DArray.h.
References Util::Array< Data >::capacity(), Util::Array< Data >::capacity_, Util::DArray< Data >::isAllocated(), and UTIL_THROW.
template<class Data > void Util::DArray< Data >::allocate (int capacity)
Allocate the underlying C array.
Throw an Exception if the DArray is already allocated.
Parameters:
capacity number of elements to allocate.
Definition at line 186 of file DArray.h.
References UTIL_THROW.
Referenced by Tools::AtomStorage::allocate(), DdMd::AtomMap::allocate(), McMd::PairList::allocate(), Tools::CellList::allocate(), DdMd::CellList::allocate(), McMd::Species::allocate(), McMd::System::allocateMoleculeSets(), McMd::SpeciesMutator::allocateSpeciesMutator(), McMd::BennettsMethod::BennettsMethod(), Util::DArray< Data >::DArray(), Util::Distribution::Distribution(), Inter::GeneralPeriodicExternal::GeneralPeriodicExternal(), McMd::HybridMdMove::HybridMdMove(), McMd::HybridNphMdMove::HybridNphMdMove(), Util::IntDistribution::IntDistribution(), Inter::LamellarOrderingExternal::LamellarOrderingExternal(), McMd::CfbDoubleRebridgeMove::loadParameters(), McMd::NveVvIntegrator::loadParameters(), McMd::CfbEndMove::loadParameters(), McMd::CfbRebridgeMove::loadParameters(), McMd::RigidDisplaceMove::loadParameters(), DdMd::NvtIntegrator::loadParameters(), McMd::AtomMSD::loadParameters(), DdMd::NphIntegrator::loadParameters(), DdMd::NveIntegrator::loadParameters(), McMd::EndSwapMove::loadParameters(), DdMd::NptIntegrator::loadParameters(), McMd::CfbRingRebridgeMove::loadParameters(), McMd::ComMSD::loadParameters(), McMd::RingTetraRebridgeMove::loadParameters(), McMd::RingRouseAutoCorr::loadParameters(), McMd::MdPairEnergyCoefficients::loadParameters(), McMd::BennettsMethod::loadParameters(), McMd::LinearRouseAutoCorr::loadParameters(), McMd::Perturbation::loadParameters(), McMd::McMuExchange::loadParameters(), McMd::IntraPairAutoCorr::loadParameters(), McMd::StructureFactor::loadParameters(), Inter::MultiHarmonicDihedral::loadParameters(), McMd::PairList::loadParameters(), McMd::StructureFactorPGrid::loadParameters(), Inter::NucleationExternal::loadParameters(), Inter::GeneralPeriodicExternal::loadParameters(), Inter::PeriodicExternal::loadParameters(), Inter::SimplePeriodicExternal::loadParameters(), McMd::StructureFactorGrid::loadParameters(), DdMd::StructureFactorGrid::loadParameters(), Inter::LamellarOrderingExternal::loadParameters(), McMd::IntraStructureFactorGrid::loadParameters(), Inter::LocalLamellarOrderingExternal::loadParameters(), McMd::BlockRadiusGyration::loadParameters(), DdMd::StructureFactor::loadParameters(), DdMd::VanHove::loadParameters(), McMd::VanHove::loadParameters(), McMd::Simulation::loadParameters(), McMd::StructureFactorP::loadParameters(), McMd::IntraStructureFactor::loadParameters(), Inter::LocalLamellarOrderingExternal::LocalLamellarOrderingExternal(), McMd::ReplicaMove::move(), Inter::MultiHarmonicDihedral::MultiHarmonicDihedral(), Inter::NucleationExternal::NucleationExternal(), Util::IntDistribution::operator=(), Util::Distribution::operator=(), Inter::MultiHarmonicDihedral::operator=(), Inter::NucleationExternal::operator=(), Inter::PeriodicExternal::operator=(), McMd::CfbReptationMove::output(), Inter::PeriodicExternal::PeriodicExternal(), McMd::MdSimulation::readCommands(), McMd::McSimulation::readCommands(), McMd::LammpsDumpIo::readHeader(), McMd::DCDTrajectoryIo::readHeader(), McMd::CfbDoubleRebridgeMove::readParameters(), McMd::NveVvIntegrator::readParameters(), McMd::TypeDistribution::readParameters(), McMd::CfbEndMove::readParameters(), McMd::CfbRebridgeMove::readParameters(), McMd::RigidDisplaceMove::readParameters(), McMd::BoundaryAverage::readParameters(), DdMd::NvtIntegrator::readParameters(), McMd::AtomMSD::readParameters(), DdMd::NveIntegrator::readParameters(), McMd::RingTetraRebridgeMove::readParameters(), DdMd::NphIntegrator::readParameters(), McMd::EndSwapMove::readParameters(), DdMd::NptIntegrator::readParameters(), McMd::ComMSD::readParameters(), DdMd::PairEnergyAverage::readParameters(), McMd::CfbRingRebridgeMove::readParameters(), McMd::CfbReptationMove::readParameters(), Tools::AtomMSD::readParameters(), McMd::McMuExchange::readParameters(), Util::RadialDistribution::readParameters(), McMd::RingRouseAutoCorr::readParameters(), McMd::McMoveManager::readParameters(), McMd::MdPairEnergyCoefficients::readParameters(), McMd::BennettsMethod::readParameters(), McMd::LinearRouseAutoCorr::readParameters(), McMd::NvtNhIntegrator::readParameters(), Util::IntDistribution::readParameters(), Util::Distribution::readParameters(), McMd::RDF::readParameters(), McMd::NvtDpdVvIntegrator::readParameters(), McMd::CompositionProfile::readParameters(), McMd::NphIntegrator::readParameters(), McMd::Perturbation::readParameters(), Tools::Configuration::readParameters(), McMd::IntraPairAutoCorr::readParameters(), McMd::StructureFactor::readParameters(), McMd::RadiusGyration::readParameters(), McMd::BlockRadiusGyration::readParameters(), DdMd::AsymmSFGrid::readParameters(), Inter::PeriodicExternal::readParameters(), Inter::SimplePeriodicExternal::readParameters(), Inter::NucleationExternal::readParameters(), McMd::StructureFactorGrid::readParameters(), Inter::GeneralPeriodicExternal::readParameters(), McMd::StructureFactorPGrid::readParameters(), DdMd::StructureFactorGrid::readParameters(), Inter::LamellarOrderingExternal::readParameters(), McMd::IntraStructureFactorGrid::readParameters(), Inter::LocalLamellarOrderingExternal::readParameters(), DdMd::AsymmSF::readParameters(), DdMd::StructureFactor::readParameters(), DdMd::VanHove::readParameters(), McMd::VanHove::readParameters(), McMd::Simulation::readParameters(), McMd::StructureFactorP::readParameters(), McMd::IntraStructureFactor::readParameters(), Inter::MultiHarmonicDihedral::setNDihedralType(), Util::RadialDistribution::setParam(), Util::IntDistribution::setParam(), Util::Distribution::setParam(), and Inter::SimplePeriodicExternal::SimplePeriodicExternal().
template<class Data > void Util::DArray< Data >::deallocate ()
Dellocate the underlying C array.
Throw an Exception if the DArray is not allocated.
Definition at line 204 of file DArray.h.
References UTIL_THROW.
template<class Data > bool Util::DArray< Data >::isAllocated () const [inline]
Return true if the DArray has been allocated, false otherwise.
Definition at line 217 of file DArray.h.
Referenced by Util::bcast(), Util::DArray< Data >::DArray(), McMd::LinkMaster::isValid(), McMd::Species::isValid(), DdMd::NvtIntegrator::loadParameters(), DdMd::NphIntegrator::loadParameters(), DdMd::NveIntegrator::loadParameters(), DdMd::NptIntegrator::loadParameters(), Inter::MultiHarmonicDihedral::operator=(), Util::DArray< Data >::operator=(), McMd::LammpsDumpIo::readFrame(), McMd::LammpsDumpIo::readHeader(), DdMd::NvtIntegrator::readParameters(), DdMd::NveIntegrator::readParameters(), DdMd::NphIntegrator::readParameters(), DdMd::NptIntegrator::readParameters(), McMd::NvtNhIntegrator::readParameters(), Util::recv(), and Util::send().
template<class Data > template<class Archive > void Util::DArray< Data >::serialize (Archive & ar, const unsigned int version)
Serialize a DArray to/from an Archive.
Parameters:
ar archive
version archive version id
Definition at line 225 of file DArray.h.
References UTIL_THROW.
The documentation for this class was generated from the following file:
DArray.h