Simpatico: McMd::AnglePotentialImpl< Interaction > Class Template Reference
McMd::AnglePotentialImpl< Interaction > Class Template Reference
Angle Potentials
Detailed Description
template<class Interaction>
class McMd::AnglePotentialImpl< Interaction >
Implementation template for an AnglePotential.
Definition at line 34 of file mcMd/potentials/angle/AnglePotentialImpl.h.
#include <AnglePotentialImpl.h>
Public Member Functions
AnglePotentialImpl (System &system)
Constructor.
AnglePotentialImpl (AnglePotentialImpl< Interaction > &other)
Constructor (copied from McAnglePotential)
virtual ~AnglePotentialImpl ()
Destructor.
virtual void readParam (std::istream &in)
Read angle potential parameters.
Interactions Interface
double energy (double cosTheta, int type) const
Returns potential energy for one angle.
void force (const Vector &R1, const Vector &R2, Vector &F1, Vector &F2, int type) const
Returns forces along two bonds at the angle, for use in MD and stress calculation.
void set (std::string name, int type, double value)
Modify a parameter, identified by a string.
double get (std::string name, int type) const
Get a parameter value, identified by a string.
virtual std::string interactionClassName () const
Return pair interaction class name (e.g., "CosineAngle").
Interaction & interaction ()
Return angle interaction by reference.
const Interaction & interaction () const
Return angle interaction by const reference.
System Energy and Force Calculators
virtual double atomEnergy (const Atom &atom) const
Calculate the angle energy for one Atom.
virtual void addForces ()
Calculate the angle energy for one Atom.
virtual double energy () const
Return total angle potential energy of this System.
virtual void computeStress (double &stress) const
Compute total angle pressure.
virtual void computeStress (Util::Vector &stress) const
Compute x, y, z angle pressures.
virtual void computeStress (Util::Tensor &stress) const
Compute angle stress tensor.
Constructor & Destructor Documentation
template<class Interaction > McMd::AnglePotentialImpl< Interaction >::AnglePotentialImpl (System & system)
Constructor.
Definition at line 204 of file mcMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > McMd::AnglePotentialImpl< Interaction >::AnglePotentialImpl (AnglePotentialImpl< Interaction > & other)
Constructor (copied from McAnglePotential)
Definition at line 215 of file mcMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > McMd::AnglePotentialImpl< Interaction >::~AnglePotentialImpl () [virtual]
Destructor.
Definition at line 227 of file mcMd/potentials/angle/AnglePotentialImpl.h.
Member Function Documentation
template<class Interaction > void McMd::AnglePotentialImpl< Interaction >::readParam (std::istream & in) [virtual]
Read angle potential parameters.
This method reads the angle potential Interaction parameter block. Before calling Evalutor::readParam(), it passes simulation().nBondType() to Interaction::setNAtomType().
Parameters:
in input parameter stream.
Reimplemented from Util::ParamComposite.
Definition at line 239 of file mcMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > double McMd::AnglePotentialImpl< Interaction >::energy (double cosTheta, int type) const [virtual]
Returns potential energy for one angle.
Parameters:
cosTheta cosine of the bend angle.
type type of bend angle.
Implements McMd::AnglePotential.
Definition at line 254 of file mcMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > void McMd::AnglePotentialImpl< Interaction >::force (const Vector & R1, const Vector & R2, Vector & F1, Vector & F2, int type) const [virtual]
Returns forces along two bonds at the angle, for use in MD and stress calculation.
Parameters:
R1 bond vector from atom 1 to 2.
R2 bond vector from atom 2 to 3.
F1 return force along R1 direction.
F2 return force along R2 direction.
type type of angle.
Implements McMd::AnglePotential.
Definition at line 262 of file mcMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction> void McMd::AnglePotentialImpl< Interaction >::set (std::string name, int type, double value) [inline, virtual]
Modify a parameter, identified by a string.
Parameters:
name parameter name
type angle type index
value new value of parameter
Implements McMd::AnglePotential.
Definition at line 96 of file mcMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction> double McMd::AnglePotentialImpl< Interaction >::get (std::string name, int type) const [inline, virtual]
Get a parameter value, identified by a string.
Parameters:
name parameter name
type angle type index
Returns:
parameter value
Implements McMd::AnglePotential.
Definition at line 106 of file mcMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > std::string McMd::AnglePotentialImpl< Interaction >::interactionClassName () const [virtual]
Return pair interaction class name (e.g., "CosineAngle").
Implements McMd::AnglePotential.
Definition at line 431 of file mcMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > Interaction & McMd::AnglePotentialImpl< Interaction >::interaction () [inline]
Return angle interaction by reference.
Definition at line 420 of file mcMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > const Interaction & McMd::AnglePotentialImpl< Interaction >::interaction () const [inline]
Return angle interaction by const reference.
Definition at line 424 of file mcMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > double McMd::AnglePotentialImpl< Interaction >::atomEnergy (const Atom & atom) const [virtual]
Calculate the angle energy for one Atom.
Parameters:
atom Atom object of interest
Returns:
angle energy of one atom.
Reimplemented from McMd::AnglePotential.
Definition at line 270 of file mcMd/potentials/angle/AnglePotentialImpl.h.
References McMd::Group< NAtom >::atom(), Util::Vector::dot(), McMd::Atom::molecule(), McMd::Atom::position(), McMd::Molecule::species(), and McMd::Group< NAtom >::typeId().
template<class Interaction > void McMd::AnglePotentialImpl< Interaction >::addForces () [virtual]
Calculate the angle energy for one Atom.
Reimplemented from McMd::AnglePotential.
Definition at line 329 of file mcMd/potentials/angle/AnglePotentialImpl.h.
References McMd::Atom::force(), Util::PArrayIterator< Data >::notEnd(), and McMd::Atom::position().
template<class Interaction > double McMd::AnglePotentialImpl< Interaction >::energy () const [virtual]
Return total angle potential energy of this System.
Implements McMd::AnglePotential.
Definition at line 298 of file mcMd/potentials/angle/AnglePotentialImpl.h.
References Util::Vector::dot(), and Util::ConstPArrayIterator< Data >::notEnd().
template<class Interaction > void McMd::AnglePotentialImpl< Interaction >::computeStress (double & stress) const [virtual]
Compute total angle pressure.
Parameters:
stress (output) pressure.
Implements McMd::AnglePotential.
Definition at line 406 of file mcMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > void McMd::AnglePotentialImpl< Interaction >::computeStress (Util::Vector & stress) const [virtual]
Compute x, y, z angle pressures.
Parameters:
stress (output) pressures.
Implements McMd::AnglePotential.
Definition at line 410 of file mcMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > void McMd::AnglePotentialImpl< Interaction >::computeStress (Util::Tensor & stress) const [virtual]
Compute angle stress tensor.
Parameters:
stress (output) pressures.
Implements McMd::AnglePotential.
Definition at line 415 of file mcMd/potentials/angle/AnglePotentialImpl.h.
The documentation for this class was generated from the following file:
mcMd/potentials/angle/AnglePotentialImpl.h