Simpatico: McMd::IntraBondStressAutoCorr< SystemType > Class Template Reference
McMd::IntraBondStressAutoCorr< SystemType > Class Template Reference
Diagnostics
Detailed Description
template<class SystemType>
class McMd::IntraBondStressAutoCorr< SystemType >
Autocorrelation for bond stress of a molecule.
Definition at line 34 of file IntraBondStressAutoCorr.h.
#include <IntraBondStressAutoCorr.h>
Public Member Functions
IntraBondStressAutoCorr (SystemType &system)
Constructor.
virtual ~IntraBondStressAutoCorr ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Set number of molecules and clear accumulator.
virtual void sample (long iStep)
Evaluate end-to-end vectors of all chains, add to ensemble.
virtual void output ()
Output results after simulation is completed.
Constructor & Destructor Documentation
template<class SystemType> McMd::IntraBondStressAutoCorr< SystemType >::IntraBondStressAutoCorr (SystemType & system)
Constructor.
Parameters:
system reference to parent System
Definition at line 32 of file IntraBondStressAutoCorr.tpp.
template<class SystemType > McMd::IntraBondStressAutoCorr< SystemType >::~IntraBondStressAutoCorr () [virtual]
Destructor.
Definition at line 47 of file IntraBondStressAutoCorr.tpp.
Member Function Documentation
template<class SystemType > void McMd::IntraBondStressAutoCorr< SystemType >::readParameters (std::istream & in) [virtual]
Read parameters from file.
Parameters:
in input parameter stream
Reimplemented from McMd::Diagnostic.
Definition at line 54 of file IntraBondStressAutoCorr.tpp.
References UTIL_THROW.
template<class SystemType > void McMd::IntraBondStressAutoCorr< SystemType >::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::Diagnostic.
Definition at line 89 of file IntraBondStressAutoCorr.tpp.
References McMd::Diagnostic::loadParameters(), and UTIL_THROW.
template<class SystemType > void McMd::IntraBondStressAutoCorr< SystemType >::save (Serializable::OArchive & ar) [virtual]
Save internal state to archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::Diagnostic.
Definition at line 130 of file IntraBondStressAutoCorr.tpp.
template<class SystemType > template<class Archive > void McMd::IntraBondStressAutoCorr< SystemType >::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Diagnostic.
Reimplemented in McMd::McIntraBondStressAutoCorr, and McMd::MdIntraBondStressAutoCorr.
Definition at line 146 of file IntraBondStressAutoCorr.h.
References McMd::serialize().
template<class SystemType > void McMd::IntraBondStressAutoCorr< SystemType >::setup () [virtual]
Set number of molecules and clear accumulator.
Reimplemented from McMd::Diagnostic.
Definition at line 137 of file IntraBondStressAutoCorr.tpp.
References UTIL_THROW.
template<class SystemType > void McMd::IntraBondStressAutoCorr< SystemType >::sample (long iStep) [virtual]
Evaluate end-to-end vectors of all chains, add to ensemble.
Parameters:
iStep counter for number of steps
Implements McMd::Diagnostic.
Definition at line 156 of file IntraBondStressAutoCorr.tpp.
References Util::Dimension, Util::ConstArrayIterator< Data >::notEnd(), Util::ConstPArrayIterator< Data >::notEnd(), and UTIL_THROW.
template<class SystemType > void McMd::IntraBondStressAutoCorr< SystemType >::output () [virtual]
Output results after simulation is completed.
Reimplemented from McMd::Diagnostic.
Definition at line 206 of file IntraBondStressAutoCorr.tpp.
The documentation for this class was generated from the following files:
IntraBondStressAutoCorr.h
IntraBondStressAutoCorr.tpp