Simpatico: McMd::LammpsDumpReader Class Reference
McMd::LammpsDumpReader Class Reference
Detailed Description
TrajectoryReader for Lammps dump trajectory files.
This class assumes that atom ids are ordered by molecule and species, with consecutive ids for atoms in the same molecule and consecutive blocks for molecules in the same species. It does not require that the atoms be ordered consecutively by id within the dump file.
Definition at line 30 of file mcMd/trajectory/LammpsDumpReader.h.
#include <LammpsDumpReader.h>
Public Member Functions
LammpsDumpReader (System &system)
Constructor.
virtual ~LammpsDumpReader ()
Destructor.
void open (std::string filename)
Open file.
bool readFrame ()
Read a single frame.
void close ()
Close file.
Public Member Functions inherited from McMd::TrajectoryReader
TrajectoryReader (System &system)
Constructor.
virtual ~TrajectoryReader ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from McMd::TrajectoryReader
System & system () const
Get a reference to the parent System.
Simulation & simulation () const
Get a reference to the parent Simulation.
Boundary & boundary () const
Get the Boundary.
virtual void addMolecules ()
Add all molecules to system.
Protected Attributes inherited from McMd::TrajectoryReader
int nAtomTotal_
Total number of atoms (all species)
Constructor & Destructor Documentation
McMd::LammpsDumpReader::LammpsDumpReader (System & system)
Constructor.
Definition at line 28 of file mcMd/trajectory/LammpsDumpReader.cpp.
McMd::LammpsDumpReader::~LammpsDumpReader () virtual
Destructor.
Definition at line 35 of file mcMd/trajectory/LammpsDumpReader.cpp.
Member Function Documentation
void McMd::LammpsDumpReader::open (std::string filename) virtual
Open file.
Parameters
filename input file name.
Implements McMd::TrajectoryReader.
Definition at line 41 of file mcMd/trajectory/LammpsDumpReader.cpp.
References McMd::TrajectoryReader::addMolecules(), McMd::TrajectoryReader::nAtomTotal_, and UTIL_THROW.
bool McMd::LammpsDumpReader::readFrame () virtual
Read a single frame.
Frames are assumed to be read consecutively.
Returns
true if this frame is available, false if end of file
Implements McMd::TrajectoryReader.
Definition at line 68 of file mcMd/trajectory/LammpsDumpReader.cpp.
References McMd::Molecule::begin(), McMd::TrajectoryReader::boundary(), McMd::Species::capacity(), Util::checkString(), Util::Dimension, Util::getNextLine(), McMd::System::molecule(), McMd::TrajectoryReader::nAtomTotal_, Util::ArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::OrthorhombicBoundary::setOrthorhombic(), Util::OrthorhombicBoundary::shift(), McMd::TrajectoryReader::simulation(), McMd::Simulation::species(), McMd::TrajectoryReader::system(), and UTIL_THROW.
void McMd::LammpsDumpReader::close () virtual
Close file.
Implements McMd::TrajectoryReader.
Definition at line 170 of file mcMd/trajectory/LammpsDumpReader.cpp.
The documentation for this class was generated from the following files:
mcMd/trajectory/LammpsDumpReader.h
mcMd/trajectory/LammpsDumpReader.cpp