Simpatico: Tools::AtomMSD Class Reference
Tools::AtomMSD Class Reference
Analyzers
Detailed Description
Mean-squared displacement of specific atoms in specific species.
Definition at line 26 of file tools/analyzers/AtomMSD.h.
#include <AtomMSD.h>
Public Member Functions
AtomMSD (Processor &processor)
Constructor.
AtomMSD (Configuration &configuration, FileMaster &fileMaster)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void setup ()
Determine number of molecules and allocate memory.
virtual void sample (long iStep)
Evaluate end-to-end vectors of all chains, add to ensemble.
virtual void output ()
Output results to file after simulation is completed.
Constructor & Destructor Documentation
Tools::AtomMSD::AtomMSD (Processor & processor)
Constructor.
Parameters:
processor reference to parent Processor
Definition at line 27 of file tools/analyzers/AtomMSD.cpp.
References Util::ParamComposite::setClassName().
Tools::AtomMSD::AtomMSD (Configuration & configuration, FileMaster & fileMaster)
Constructor.
Parameters:
configuration reference to parent Configuration
fileMaster reference to associated FileMaster
Definition at line 44 of file tools/analyzers/AtomMSD.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void Tools::AtomMSD::readParameters (std::istream & in) [virtual]
Read parameters from file.
Parameters:
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 61 of file tools/analyzers/AtomMSD.cpp.
References Util::DArray< Data >::allocate(), Tools::Species::capacity(), Tools::Analyzer::configuration(), Tools::Species::nAtom(), Tools::Analyzer::readInterval(), Tools::Analyzer::readOutputFileName(), Util::MeanSqDispArray< Data >::setParam(), Tools::Configuration::species(), and UTIL_THROW.
void Tools::AtomMSD::setup () [virtual]
Determine number of molecules and allocate memory.
Reimplemented from Tools::Analyzer.
Definition at line 106 of file tools/analyzers/AtomMSD.cpp.
References Tools::Species::begin(), Tools::Configuration::boundary(), Util::MeanSqDispArray< Data >::clear(), Tools::Analyzer::configuration(), Util::ArrayIterator< Data >::notEnd(), Util::MeanSqDispArray< Data >::setNEnsemble(), Util::OrthorhombicBoundary::shift(), Tools::Species::size(), Tools::Configuration::species(), and UTIL_THROW.
void Tools::AtomMSD::sample (long iStep) [virtual]
Evaluate end-to-end vectors of all chains, add to ensemble.
Parameters:
iStep counter for number of steps
Implements Tools::Analyzer.
Definition at line 138 of file tools/analyzers/AtomMSD.cpp.
References Tools::Species::begin(), Tools::Configuration::boundary(), Tools::Analyzer::configuration(), Util::Dimension, Util::OrthorhombicBoundary::distanceSq(), Tools::Analyzer::isAtInterval(), Util::OrthorhombicBoundary::lengths(), Util::ArrayIterator< Data >::notEnd(), Util::MeanSqDispArray< Data >::sample(), Util::OrthorhombicBoundary::shift(), Tools::Species::size(), Tools::Configuration::species(), and UTIL_THROW.
void Tools::AtomMSD::output () [virtual]
Output results to file after simulation is completed.
Reimplemented from Tools::Analyzer.
Definition at line 186 of file tools/analyzers/AtomMSD.cpp.
References Util::MeanSqDispArray< Data >::bufferCapacity(), Tools::Analyzer::fileMaster(), Util::MeanSqDispArray< Data >::nEnsemble(), Util::MeanSqDispArray< Data >::nSample(), Util::FileMaster::openOutputFile(), Util::MeanSqDispArray< Data >::output(), Tools::Analyzer::outputFileName(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
tools/analyzers/AtomMSD.h
tools/analyzers/AtomMSD.cpp