Simpatico: Tools::DdMdConfigWriter Class Reference
Tools::DdMdConfigWriter Class Reference
Detailed Description
Native / default DdMd format for configuration files.
Definition at line 29 of file DdMdConfigWriter.h.
#include <DdMdConfigWriter.h>
Public Member Functions
DdMdConfigWriter (bool hasMolecules=false)
Default constructor.
DdMdConfigWriter (Configuration &configuration, bool hasMolecules=false)
Constructor.
virtual void writeConfig (std::ofstream &file)
Write configuration file in DdMd default format.
Constructor & Destructor Documentation
Tools::DdMdConfigWriter::DdMdConfigWriter (bool hasMolecules = false)
Default constructor.
Tools::DdMdConfigWriter::DdMdConfigWriter (Configuration & configuration, bool hasMolecules = false)
Constructor.
Parameters:
configuration parent Configuration object.
hasMolecules true if file format has DdMd::AtomContext info
Definition at line 28 of file DdMdConfigWriter.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void Tools::DdMdConfigWriter::writeConfig (std::ofstream & file) [virtual]
Write configuration file in DdMd default format.
Parameters:
file output file stream (must be open on master)
Implements Tools::ConfigWriter.
Definition at line 55 of file DdMdConfigWriter.cpp.
References Tools::Configuration::atoms(), Tools::AtomStorage::begin(), Tools::Configuration::boundary(), Util::ArrayIterator< Data >::notEnd(), Tools::AtomStorage::size(), and UTIL_THROW.
The documentation for this class was generated from the following files:
DdMdConfigWriter.h
DdMdConfigWriter.cpp