Simpatico: McMd::McStressAutoCorrelation Class Reference
McMd::McStressAutoCorrelation Class Reference
Detailed Description
Analyzer to calculate average isotropic pressure.
See here for the parameter file format and any other user documentation.
Definition at line 23 of file McStressAutoCorrelation.h.
#include <McStressAutoCorrelation.h>
Public Member Functions
McStressAutoCorrelation (McSystem &system)
Constructor.
~McStressAutoCorrelation ()
Destructor.
Constructor & Destructor Documentation
McMd::McStressAutoCorrelation::McStressAutoCorrelation (McSystem & system)
Constructor.
Parameters
system parent McSystem
Definition at line 17 of file McStressAutoCorrelation.cpp.
McMd::McStressAutoCorrelation::~McStressAutoCorrelation ()
Destructor.
Definition at line 24 of file McStressAutoCorrelation.cpp.
References Util::DArray< Data >::allocate(), McMd::McSystem::computeStress(), McMd::McSystem::computeVirialStress(), McMd::System::energyEnsemble(), and Simp::EnergyEnsemble::temperature().
The documentation for this class was generated from the following files:
McStressAutoCorrelation.h
McStressAutoCorrelation.cpp