Simpatico: DdMd::NptIntegrator Class Reference
DdMd::NptIntegrator Class Reference
MD Integrators
Detailed Description
A reversible symplectic NPT integrator.
Algorithm is based on Martyna,Tobias and Klein (J. Chem. Phys. 101, 4177-4189, 1994).
Definition at line 26 of file NptIntegrator.h.
#include <NptIntegrator.h>
Public Member Functions
NptIntegrator (Simulation &simulation)
Constructor.
~NptIntegrator ()
Destructor.
void readParameters (std::istream &in)
Read required parameters.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
Public Member Functions inherited from DdMd::TwoStepIntegrator
TwoStepIntegrator (Simulation &simulation)
Constructor.
~TwoStepIntegrator ()
Destructor.
void run (int nStep)
Run a simulation.
Public Member Functions inherited from DdMd::Integrator
Integrator (Simulation &simulation)
Constructor.
~Integrator ()
Destructor.
virtual void clear ()
Set integrator to initial state and clears all statistics.
virtual void outputStatistics (std::ostream &out)
Output timing statistics from a run.
double time () const
Get average time per processor of previous run.
int iStep () const
Get current time step index.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Public Member Functions inherited from DdMd::SimulationAccess
SimulationAccess (Simulation &simulation)
Constructor.
~SimulationAccess ()
Destructor.
Simulation & simulation ()
Get the parent simulation.
Boundary & boundary ()
Get the Boundary.
AtomStorage & atomStorage ()
Get the AtomStorage.
GroupStorage< 2 > & bondStorage ()
Get the BondStorage.
GroupStorage< 3 > & angleStorage ()
Get the AngleStorage.
GroupStorage< 4 > & dihedralStorage ()
Get the angleStorage.
PairPotential & pairPotential ()
Get the PairPotential.
BondPotential & bondPotential ()
Get the PairPotential.
AnglePotential & anglePotential ()
Get the AnglePotential.
DihedralPotential & dihedralPotential ()
Get the DihedralPotential.
ExternalPotential & externalPotential ()
Get the ExternalPotential.
EnergyEnsemble & energyEnsemble ()
Get the EnergyEnsemble.
BoundaryEnsemble & boundaryEnsemble ()
Get the BoundaryEnsemble.
Random & random ()
Get the Random number generator.
Domain & domain ()
Get the Domain.
Exchanger & exchanger ()
Get the Exchanger.
FileMaster & fileMaster ()
Get the FileMaster.
int nAtomType ()
Get maximum number of atom types.
int nBondType ()
Get maximum number of bond types.
int nAngleType ()
Get maximum number of angle types.
int nDihedralType ()
Get maximum number of dihedral types.
bool hasExternal ()
Does this simulation have an external potential?
AtomType & atomType (int i)
Get an AtomType descriptor for atomtype i.
MaskPolicy maskedPairPolicy () const
Return the value of the mask policy (MaskNone or MaskBonded).
bool reverseUpdateFlag () const
Are forces evaluated by reverse communication (true) or not (false)?
Protected Member Functions
virtual void initDynamicalState ()
Initialize internal state variables xi, eta, and nu to zero.
void setup ()
Setup state just before main loop.
virtual void integrateStep1 ()
Execute first step of two-step integrator.
virtual void integrateStep2 ()
Execute secodn step of two-step integrator.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Types inherited from DdMd::Integrator
enum TimeId
Timestamps for loop timing.
Protected Attributes inherited from DdMd::Integrator
int iStep_
Current step number.
Constructor & Destructor Documentation
DdMd::NptIntegrator::NptIntegrator (Simulation & simulation)
Constructor.
Definition at line 33 of file NptIntegrator.cpp.
References Util::ParamComposite::setClassName().
DdMd::NptIntegrator::~NptIntegrator ()
Destructor.
Definition at line 40 of file NptIntegrator.cpp.
Member Function Documentation
void DdMd::NptIntegrator::readParameters (std::istream & in) virtual
Read required parameters.
For velocity-verlet algorithm, reads the time step dt.
Reimplemented from DdMd::Integrator.
Definition at line 46 of file NptIntegrator.cpp.
References Util::DArray< Data >::allocate(), Util::DArray< Data >::isAllocated(), DdMd::SimulationAccess::nAtomType(), DdMd::Simulation::nAtomType(), DdMd::Integrator::readParameters(), and DdMd::SimulationAccess::simulation().
void DdMd::NptIntegrator::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from DdMd::Integrator.
Definition at line 65 of file NptIntegrator.cpp.
References Util::DArray< Data >::allocate(), Util::DArray< Data >::isAllocated(), Util::MpiLoader< IArchive >::load(), DdMd::Integrator::loadParameters(), DdMd::SimulationAccess::nAtomType(), DdMd::Simulation::nAtomType(), and DdMd::SimulationAccess::simulation().
void DdMd::NptIntegrator::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from DdMd::Integrator.
Definition at line 87 of file NptIntegrator.cpp.
References DdMd::Integrator::save().
void DdMd::NptIntegrator::initDynamicalState () protected virtual
Initialize internal state variables xi, eta, and nu to zero.
Reimplemented from DdMd::Integrator.
Definition at line 102 of file NptIntegrator.cpp.
void DdMd::NptIntegrator::setup () protected virtual
Setup state just before main loop.
Implements DdMd::Integrator.
Definition at line 109 of file NptIntegrator.cpp.
References DdMd::SimulationAccess::atomStorage(), DdMd::Simulation::atomType(), Util::bcast(), DdMd::Simulation::boundaryEnsemble(), Util::Array< Data >::capacity(), DdMd::Integrator::clear(), DdMd::Simulation::computeKineticEnergy(), DdMd::Simulation::computeKineticStress(), DdMd::AtomStorage::computeNAtomTotal(), DdMd::SimulationAccess::domain(), DdMd::Simulation::energyEnsemble(), DdMd::Integrator::isSetup(), DdMd::AtomType::mass(), DdMd::AtomStorage::nAtomTotal(), DdMd::SimulationAccess::nAtomType(), Util::BoundaryEnsemble::pressure(), DdMd::Integrator::setIsSetup(), DdMd::Integrator::setupAtoms(), DdMd::SimulationAccess::simulation(), and Util::EnergyEnsemble::temperature().
void DdMd::NptIntegrator::integrateStep1 () protected virtual
Execute first step of two-step integrator.
Implements DdMd::TwoStepIntegrator.
Definition at line 147 of file NptIntegrator.cpp.
References DdMd::SimulationAccess::atomStorage(), Util::bcast(), DdMd::AtomStorage::begin(), DdMd::Simulation::boundary(), DdMd::Simulation::boundaryEnsemble(), DdMd::Simulation::computeKineticEnergy(), DdMd::Simulation::computeKineticStress(), DdMd::Simulation::computeVirialStress(), DdMd::SimulationAccess::domain(), DdMd::Simulation::domain(), DdMd::Simulation::energyEnsemble(), DdMd::Domain::isMaster(), DdMd::Simulation::kineticEnergy(), DdMd::Simulation::kineticStress(), Util::OrthorhombicBoundary::lengths(), Util::Vector::multiply(), Util::PArrayIterator< Data >::notEnd(), Util::BoundaryEnsemble::pressure(), Util::OrthorhombicBoundary::setOrthorhombic(), DdMd::SimulationAccess::simulation(), Util::EnergyEnsemble::temperature(), Util::Tensor::trace(), DdMd::Simulation::virialStress(), and Util::OrthorhombicBoundary::volume().
void DdMd::NptIntegrator::integrateStep2 () protected virtual
Execute secodn step of two-step integrator.
Implements DdMd::TwoStepIntegrator.
Definition at line 286 of file NptIntegrator.cpp.
References DdMd::SimulationAccess::atomStorage(), DdMd::Simulation::atomType(), Util::bcast(), DdMd::AtomStorage::begin(), DdMd::Simulation::boundary(), DdMd::Domain::communicator(), DdMd::Simulation::computeKineticEnergy(), DdMd::Simulation::computeKineticStress(), DdMd::Simulation::computePotentialEnergies(), DdMd::Simulation::computeVirialStress(), DdMd::SimulationAccess::domain(), DdMd::Simulation::domain(), Util::Vector::dot(), DdMd::Domain::isMaster(), DdMd::Simulation::kineticEnergy(), DdMd::Simulation::kineticStress(), Util::Vector::multiply(), Util::PArrayIterator< Data >::notEnd(), Util::Signal< T >::notify(), DdMd::Simulation::potentialEnergy(), DdMd::SimulationAccess::simulation(), Util::Tensor::trace(), DdMd::Simulation::velocitySignal(), DdMd::Simulation::virialStress(), and Util::OrthorhombicBoundary::volume().
The documentation for this class was generated from the following files:
NptIntegrator.h
NptIntegrator.cpp