Simpatico: DdMd::BondTensorAutoCorr Class Reference
DdMd::BondTensorAutoCorr Class Reference
Analyzers
Detailed Description
Calculate stress autocorrelation function.
Definition at line 24 of file BondTensorAutoCorr.h.
#include <BondTensorAutoCorr.h>
Public Member Functions
BondTensorAutoCorr (Simulation &simulation)
Constructor.
virtual ~BondTensorAutoCorr ()
Destructor.
Protected Member Functions
virtual void computeData ()
Compute Data value, call on all processors.
virtual Tensor data ()
Get Data value, call only on master.
Constructor & Destructor Documentation
DdMd::BondTensorAutoCorr::BondTensorAutoCorr (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object.
Definition at line 22 of file BondTensorAutoCorr.cpp.
References Util::ParamComposite::setClassName().
DdMd::BondTensorAutoCorr::~BondTensorAutoCorr () [virtual]
Destructor.
Definition at line 30 of file BondTensorAutoCorr.cpp.
Member Function Documentation
void DdMd::BondTensorAutoCorr::computeData () [protected, virtual]
Compute Data value, call on all processors.
Default implementation is empty.
Reimplemented from DdMd::AutoCorrAnalyzer< Tensor, double >.
Definition at line 36 of file BondTensorAutoCorr.cpp.
References DdMd::GroupStorage< N >::begin(), DdMd::Simulation::bondStorage(), DdMd::Simulation::boundary(), DdMd::Domain::communicator(), Util::Dimension, Util::OrthorhombicBoundary::distanceSq(), DdMd::Simulation::domain(), DdMd::Atom::isGhost(), Util::PArrayIterator< Group< N > >::notEnd(), DdMd::Atom::position(), DdMd::Analyzer::simulation(), and Util::Tensor::zero().
Tensor DdMd::BondTensorAutoCorr::data () [protected, virtual]
Get Data value, call only on master.
Implements DdMd::AutoCorrAnalyzer< Tensor, double >.
Definition at line 95 of file BondTensorAutoCorr.cpp.
References Util::Dimension, and DdMd::Analyzer::simulation().
The documentation for this class was generated from the following files:
BondTensorAutoCorr.h
BondTensorAutoCorr.cpp