Simpatico: McMd::McSystemInterface Class Reference
McMd::McSystemInterface Class Reference
McMd namespace » Systems
Detailed Description
An interface to an McSystem.
Definition at line 30 of file McSystemInterface.h.
#include <McSystemInterface.h>
Public Member Functions
McSystemInterface (McSystem &mcSystem)
Constructor.
virtual ~McSystemInterface ()
Destructor.
Public Member Functions inherited from McMd::SystemInterface
SystemInterface (System &parent)
Constructor.
virtual ~SystemInterface ()
Destructor.
System & system () const
Get the parent System by reference.
Protected Member Functions
McPairPotential & pairPotential () const
Get the McPairPotential.
BondPotential & bondPotential () const
Get the BondPotential.
AnglePotential & anglePotential () const
Get the AnglePotential.
DihedralPotential & dihedralPotential () const
Get the DihedralPotential.
ExternalPotential & externalPotential () const
Get the ExternalPotential.
Protected Member Functions inherited from McMd::SystemInterface
Boundary & boundary () const
Get the Boundary by reference.
Simulation & simulation () const
Get the parent Simulation by reference.
int nMolecule (int speciesId) const
Get the number of molecules of one Species in this SystemInterface.
int nAtom () const
Return the total number of atoms in this SystemInterface.
bool isEmpty () const
Is this an empty SystemInterface (i.e., one with no molecules) ?
void begin (int speciesId, System::MoleculeIterator &iterator)
Initialize an iterator for molecules of one species in this SystemInterface.
void begin (int speciesId, System::ConstMoleculeIterator &iterator) const
Initialize a const iterator for molecules of one species in this SystemInterface.
bool hasBonds () const
Does a bond potential exist?
bool hasAngles () const
Does an angle potential exist?
bool hasDihedrals () const
Does a dihedral potential exist?
bool hasLinks () const
Does a link potential exist?
bool hasExternal () const
Does an external potential exist?
Constructor & Destructor Documentation
McMd::McSystemInterface::McSystemInterface (McSystem & mcSystem)
Constructor.
Parameters
mcSystem parent McSystem
Definition at line 21 of file McSystemInterface.cpp.
References McMd::McSystem::anglePotential(), McMd::McSystem::bondPotential(), McMd::McSystem::dihedralPotential(), McMd::McSystem::externalPotential(), McMd::SystemInterface::hasAngles(), McMd::SystemInterface::hasBonds(), McMd::SystemInterface::hasDihedrals(), McMd::SystemInterface::hasExternal(), and McMd::McSystem::pairPotential().
McMd::McSystemInterface::~McSystemInterface () virtual
Destructor.
Definition at line 67 of file McSystemInterface.cpp.
Member Function Documentation
McPairPotential & McMd::McSystemInterface::pairPotential () const inline protected
Get the McPairPotential.
Definition at line 114 of file McSystemInterface.h.
BondPotential & McMd::McSystemInterface::bondPotential () const inline protected
Get the BondPotential.
Definition at line 122 of file McSystemInterface.h.
AnglePotential & McMd::McSystemInterface::anglePotential () const inline protected
Get the AnglePotential.
Definition at line 130 of file McSystemInterface.h.
DihedralPotential & McMd::McSystemInterface::dihedralPotential () const inline protected
Get the DihedralPotential.
Definition at line 138 of file McSystemInterface.h.
ExternalPotential & McMd::McSystemInterface::externalPotential () const inline protected
Get the ExternalPotential.
Definition at line 146 of file McSystemInterface.h.
The documentation for this class was generated from the following files:
McSystemInterface.h
McSystemInterface.cpp