Simpatico: Inter::HarmonicAngle Class Reference
Inter::HarmonicAngle Class Reference
Angle Interactions
Detailed Description
A angle potential that is harmonic in the angle.
This class implements an angle potential:
V(theta) = 0.5 kappa (theta - theta0)^2.
Definition at line 32 of file HarmonicAngle.h.
#include <HarmonicAngle.h>
Public Member Functions
HarmonicAngle ()
Default constructor.
HarmonicAngle (const HarmonicAngle &other)
Copy constructor.
HarmonicAngle & operator= (const HarmonicAngle &other)
Assignment.
void setNAngleType (int nAngleType)
Set the number of angle types.
void readParameters (std::istream &in)
Read angle interaction parameters from input stream.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void set (std::string name, int type, double value)
Modify a parameter, identified by a string.
double energy (double cosTheta, int type) const
Returns potential energy for one angle.
void force (const Vector &b1, const Vector &b2, Vector &F1, Vector &F2, int type) const
Compute angle forces.
double randomAngle (Random *random, double beta, int type) const
Return bond angle chosen from equilibrium distribution.
double randomCosineAngle (Random *random, double beta, int type) const
Return bond angle cosine chosen from equilibrium distribution.
double get (std::string name, int type) const
Get a parameter value, identified by a string.
std::string className () const
Return name string "HarmonicAngle" for this evaluator class.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Constructor & Destructor Documentation
Inter::HarmonicAngle::HarmonicAngle ()
Default constructor.
Definition at line 24 of file HarmonicAngle.cpp.
References Util::ParamComposite::setClassName().
Inter::HarmonicAngle::HarmonicAngle (const HarmonicAngle & other)
Copy constructor.
Definition at line 37 of file HarmonicAngle.cpp.
Member Function Documentation
HarmonicAngle & Inter::HarmonicAngle::operator= (const HarmonicAngle & other)
Assignment.
Definition at line 49 of file HarmonicAngle.cpp.
void Inter::HarmonicAngle::setNAngleType (int nAngleType)
Set the number of angle types.
Parameters
nAngleType number of angle types
Definition at line 62 of file HarmonicAngle.cpp.
References UTIL_THROW.
void Inter::HarmonicAngle::readParameters (std::istream & in) virtual
Read angle interaction parameters from input stream.
Format: kappa CArray<double> theta0 CArray<double>
Precondition
nAngleType must be set, by calling setNAngleType().
Parameters
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 73 of file HarmonicAngle.cpp.
References Util::Constants::Pi, and UTIL_THROW.
void Inter::HarmonicAngle::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 93 of file HarmonicAngle.cpp.
References UTIL_THROW.
void Inter::HarmonicAngle::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 107 of file HarmonicAngle.cpp.
References Util::BinaryFileOArchive::pack().
void Inter::HarmonicAngle::set (std::string name, int type, double value)
Modify a parameter, identified by a string.
Parameters
name parameter name
type angle type index
value new value of parameter
Definition at line 169 of file HarmonicAngle.cpp.
References UTIL_THROW.
double Inter::HarmonicAngle::energy (double cosTheta, int type) const inline
Returns potential energy for one angle.
Parameters
cosTheta cosine of the bend angle.
type type of bend angle.
Definition at line 181 of file HarmonicAngle.h.
Referenced by randomAngle(), and randomCosineAngle().
void Inter::HarmonicAngle::force (const Vector & b1, const Vector & b2, Vector & F1, Vector & F2, int type) const inline
Compute angle forces.
Computes forces F1 and F2 along the two bonds in the angle.
Parameters
b1 bond vector from atom 1 to 2.
b2 bond vector from atom 2 to 3.
F1 return force along b1 direction.
F2 return force along b2 direction.
type type of angle.
Definition at line 194 of file HarmonicAngle.h.
References Inter::BendForce::computeDerivatives(), Inter::BendForce::d1, Inter::BendForce::d2, Util::Vector::multiply(), Inter::Bend::sinTheta(), Inter::Bend::theta(), and Util::Vector::zero().
double Inter::HarmonicAngle::randomAngle (Random * random, double beta, int type) const
Return bond angle chosen from equilibrium distribution.
This function returns a bond angle chosen from the Boltzmann distribution of angle for bonds of random orientation. The distribution P(theta) of values of the angle theta is proportional to sin(theta)*exp[-beta*phi(theta) ], where phi(theta) is the bond energy.
Parameters
random pointer to random number generator object.
beta inverse temperature
type bond type
Returns
random bond length chosen from equilibrium distribution.
Definition at line 120 of file HarmonicAngle.cpp.
References energy(), Util::Constants::Pi, and Util::Random::uniform().
double Inter::HarmonicAngle::randomCosineAngle (Random * random, double beta, int type) const
Return bond angle cosine chosen from equilibrium distribution.
This function returns a bond angle chosen from the Boltzmann distribution of angle for bonds of random orientation. The distribution P(theta) of values of the angle theta is proportional to sin(theta)*exp[-beta*phi(theta) ], where phi(theta) is the bond energy.
Parameters
random pointer to random number generator object.
beta inverse temperature
type bond type
Returns
random bond length chosen from equilibrium distribution.
Definition at line 146 of file HarmonicAngle.cpp.
References energy(), and Util::Random::uniform().
double Inter::HarmonicAngle::get (std::string name, int type) const
Get a parameter value, identified by a string.
Parameters
name parameter name
type angle type index
Returns
parameter value
Definition at line 184 of file HarmonicAngle.cpp.
References UTIL_THROW.
std::string Inter::HarmonicAngle::className () const
Return name string "HarmonicAngle" for this evaluator class.
Definition at line 201 of file HarmonicAngle.cpp.
The documentation for this class was generated from the following files:
HarmonicAngle.h
HarmonicAngle.cpp