Simpatico: McMd::TrajectoryReader Class Reference
McMd::TrajectoryReader Class Reference abstract
McMd namespace » Trajectory Readers
Detailed Description
Trajectory file reader (base class).
Definition at line 29 of file mcMd/trajectory/TrajectoryReader.h.
#include <TrajectoryReader.h>
Public Member Functions
TrajectoryReader (System &system)
Constructor.
virtual ~TrajectoryReader ()
Destructor.
virtual void open (std::string filename)=0
Open trajectory file and read header, if any.
virtual bool readFrame ()=0
Read a single frame.
virtual void close ()=0
Close the trajectory file.
Protected Member Functions
System & system () const
Get a reference to the parent System.
Simulation & simulation () const
Get a reference to the parent Simulation.
Boundary & boundary () const
Get the Boundary.
virtual void addMolecules ()
Add all molecules to system.
Protected Attributes
int nAtomTotal_
Total number of atoms (all species)
Constructor & Destructor Documentation
McMd::TrajectoryReader::TrajectoryReader (System & system)
Constructor.
Definition at line 22 of file mcMd/trajectory/TrajectoryReader.cpp.
McMd::TrajectoryReader::~TrajectoryReader () virtual
Destructor.
Definition at line 32 of file mcMd/trajectory/TrajectoryReader.cpp.
Member Function Documentation
virtual void McMd::TrajectoryReader::open (std::string filename) pure virtual
Open trajectory file and read header, if any.
By convention, this function treats the trajectory filename as the name of an input file, and opens the file using the FileMaster:openInutFile function. This function prepends the input prefix (if any) to the file path. If compiled with MPI enabled, so that each processor simulates a different system, it also prepends a processor id prefix before the input prefix.
Parameters
filename trajectory input file name.
Implemented in McMd::DCDTrajectoryReader, McMd::DdMdTrajectoryReader, and McMd::LammpsDumpReader.
Referenced by McMd::MdSimulation::analyzeTrajectory(), and McMd::McSimulation::analyzeTrajectory().
virtual bool McMd::TrajectoryReader::readFrame () pure virtual
Read a single frame.
Frames are assumed to be read consecutively.
This function reads a frame from the trajectory file that was opened by the open() function.
Returns
true if a frame is avaiable, false if at end of file
Implemented in McMd::DCDTrajectoryReader, McMd::DdMdTrajectoryReader, and McMd::LammpsDumpReader.
Referenced by McMd::MdSimulation::analyzeTrajectory(), and McMd::McSimulation::analyzeTrajectory().
virtual void McMd::TrajectoryReader::close () pure virtual
Close the trajectory file.
Implemented in McMd::DCDTrajectoryReader, McMd::DdMdTrajectoryReader, and McMd::LammpsDumpReader.
Referenced by McMd::MdSimulation::analyzeTrajectory(), and McMd::McSimulation::analyzeTrajectory().
System & McMd::TrajectoryReader::system () const inline protected
Get a reference to the parent System.
Definition at line 110 of file mcMd/trajectory/TrajectoryReader.h.
Referenced by addMolecules(), McMd::LammpsDumpReader::readFrame(), McMd::DCDTrajectoryReader::readFrame(), and McMd::DdMdTrajectoryReader::readFrame().
Simulation & McMd::TrajectoryReader::simulation () const inline protected
Get a reference to the parent Simulation.
Definition at line 119 of file mcMd/trajectory/TrajectoryReader.h.
Referenced by addMolecules(), McMd::LammpsDumpReader::open(), McMd::DdMdTrajectoryReader::open(), McMd::LammpsDumpReader::readFrame(), McMd::DdMdTrajectoryReader::readFrame(), and McMd::DCDTrajectoryReader::readFrame().
Boundary & McMd::TrajectoryReader::boundary () const inline protected
Get the Boundary.
Definition at line 128 of file mcMd/trajectory/TrajectoryReader.h.
Referenced by McMd::LammpsDumpReader::readFrame(), McMd::DCDTrajectoryReader::readFrame(), and McMd::DdMdTrajectoryReader::readFrame().
void McMd::TrajectoryReader::addMolecules () protected virtual
Add all molecules to system.
Definition at line 38 of file mcMd/trajectory/TrajectoryReader.cpp.
References McMd::System::addMolecule(), McMd::Species::capacity(), McMd::Simulation::getMolecule(), McMd::Species::nAtom(), nAtomTotal_, McMd::Simulation::nSpecies(), simulation(), McMd::Simulation::species(), and system().
Referenced by McMd::LammpsDumpReader::open(), McMd::DCDTrajectoryReader::open(), and McMd::DdMdTrajectoryReader::open().
Member Data Documentation
int McMd::TrajectoryReader::nAtomTotal_ protected
Total number of atoms (all species)
Definition at line 76 of file mcMd/trajectory/TrajectoryReader.h.
Referenced by addMolecules(), McMd::LammpsDumpReader::open(), McMd::DCDTrajectoryReader::open(), McMd::DdMdTrajectoryReader::open(), McMd::LammpsDumpReader::readFrame(), and McMd::DdMdTrajectoryReader::readFrame().
The documentation for this class was generated from the following files:
mcMd/trajectory/TrajectoryReader.h
mcMd/trajectory/TrajectoryReader.cpp