Simpatico: Format Class Reference
Format Class Reference
Output Format
Detailed Description
Base class for output wrappers for formatted C++ ostream output.
Public members are all getters and setters for static variables defaultWidth and defaultPrecision.
Definition at line 24 of file Format.h.
#include <Format.h>
Static Public Member Functions
static void initStatic ()
Initialize or reset default width and precision values.
static void setDefaultWidth (int width)
Set the default output field width.
static void setDefaultPrecision (int precision)
Set the default output precision.
static int defaultWidth ()
Return the default output field width.
static int defaultPrecision ()
Return the default output precision.
Member Function Documentation
void initStatic () [static]
Initialize or reset default width and precision values.
Definition at line 50 of file Format.cpp.
Referenced by Util::initStatic(), LammpsConfigIo::write(), and DdMdConfigIo::write().
void setDefaultWidth (int width) [static]
Set the default output field width.
Set Format::defaultWidth_.
Definition at line 23 of file Format.cpp.
Referenced by LammpsConfigIo::write().
void setDefaultPrecision (int precision) [static]
Set the default output precision.
Definition at line 29 of file Format.cpp.
Referenced by LammpsConfigIo::write().
int defaultWidth () [static]
Return the default output field width.
Definition at line 35 of file Format.cpp.
int defaultPrecision () [static]
Return the default output precision.
Definition at line 41 of file Format.cpp.
The documentation for this class was generated from the following files:
Format.h
Format.cpp