Simpatico: McMd::NphIntegrator Class Reference
McMd::NphIntegrator Class Reference
Molecular Dynamics Integrators
Detailed Description
An explictly reversible/measure-preserving Parrinello-Rahman type NPH integrator.
TwoStepNPH can be used in three modes:
isotropic volume flucutations, cubic box
anisotropic volume fluctuations, orthorhombic box (three independent lengths)
anisotropic volume fluctuations, tetragonal box (two independent lengths, Ly = Lz)
The first mode is an implementation of the Andersen barostat, the second and the third mode are based on the adapted Parrinello-Rahman equations of motion.
The integration scheme used to implement the equations of motion is explicitly reversible and measure-preserving. It is based on the Trotter expansion technique introduced by Tuckerman et al. J. Chem. Phys. 97, pp. 1990 (1992).
Definition at line 41 of file mcMd/mdIntegrators/NphIntegrator.h.
#include <NphIntegrator.h>
Public Member Functions
NphIntegrator (MdSystem &system)
Constructor.
virtual ~NphIntegrator ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from file and initialize this MdSystem.
virtual void loadParameters (Serializable::IArchive &ar)
Load the internal state to an archive.
virtual void save (Serializable::OArchive &ar)
Save the internal state to an archive.
virtual void setup ()
Setup private variables before main loop.
virtual void step ()
Take a complete NVE MD integration step.
virtual double barostatEnergy ()
Get the barostat energy.
virtual double barostatMass () const
Get the barostat mass.
virtual LatticeSystem mode () const
Get the integrator mode.
virtual void setEta (unsigned int index, double eta)
Get the barostat momentum.
Constructor & Destructor Documentation
McMd::NphIntegrator::NphIntegrator (MdSystem & system)
Constructor.
Definition at line 32 of file mcMd/mdIntegrators/NphIntegrator.cpp.
References Util::ParamComposite::setClassName(), and Util::Vector::zero().
McMd::NphIntegrator::~NphIntegrator () [virtual]
Destructor.
Definition at line 45 of file mcMd/mdIntegrators/NphIntegrator.cpp.
Member Function Documentation
void McMd::NphIntegrator::readParameters (std::istream & in) [virtual]
Read parameters from file and initialize this MdSystem.
Parameters:
in input file stream.
Reimplemented from Util::ParamComposite.
Definition at line 51 of file mcMd/mdIntegrators/NphIntegrator.cpp.
References Util::DArray< Data >::allocate(), McMd::MdIntegrator::dt_, McMd::Simulation::nAtomType(), and McMd::MdIntegrator::simulation().
void McMd::NphIntegrator::loadParameters (Serializable::IArchive & ar) [virtual]
Load the internal state to an archive.
Parameters:
ar archive object.
Reimplemented from Util::ParamComposite.
Definition at line 65 of file mcMd/mdIntegrators/NphIntegrator.cpp.
References McMd::MdIntegrator::dt_.
void McMd::NphIntegrator::save (Serializable::OArchive & ar) [virtual]
Save the internal state to an archive.
Parameters:
ar archive object.
Reimplemented from Util::ParamComposite.
Definition at line 78 of file mcMd/mdIntegrators/NphIntegrator.cpp.
References McMd::MdIntegrator::dt_, and Util::serializeEnum().
void McMd::NphIntegrator::setup () [virtual]
Setup private variables before main loop.
Reimplemented from McMd::MdIntegrator.
Definition at line 91 of file mcMd/mdIntegrators/NphIntegrator.cpp.
References McMd::Simulation::atomType(), Util::Array< Data >::capacity(), McMd::MdIntegrator::dt_, McMd::AtomType::mass(), and McMd::MdIntegrator::simulation().
Referenced by McMd::HybridNphMdMove::move().
void McMd::NphIntegrator::step () [virtual]
Take a complete NVE MD integration step.
Implements McMd::MdIntegrator.
Definition at line 101 of file mcMd/mdIntegrators/NphIntegrator.cpp.
References Util::Vector::add(), McMd::System::begin(), McMd::System::boundary(), McMd::System::boundaryEnsemble(), McMd::MdPairPotential::buildPairList(), McMd::MdSystem::calculateForces(), McMd::MdSystem::computeStress(), McMd::MdIntegrator::dt_, McMd::Atom::force(), Util::OrthorhombicBoundary::lengths(), Util::Vector::multiply(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), McMd::MdSystem::pairPotential(), McMd::Atom::position(), Util::BoundaryEnsemble::pressure(), Util::OrthorhombicBoundary::setOrthorhombic(), McMd::MdIntegrator::simulation(), McMd::MdIntegrator::system(), McMd::Atom::typeId(), and McMd::Atom::velocity().
Referenced by McMd::HybridNphMdMove::move().
double McMd::NphIntegrator::barostatEnergy () [virtual]
Get the barostat energy.
Definition at line 325 of file mcMd/mdIntegrators/NphIntegrator.cpp.
Referenced by McMd::HybridNphMdMove::move().
double McMd::NphIntegrator::barostatMass () const [virtual]
Get the barostat mass.
Definition at line 341 of file mcMd/mdIntegrators/NphIntegrator.cpp.
Referenced by McMd::HybridNphMdMove::loadParameters(), and McMd::HybridNphMdMove::readParameters().
LatticeSystem McMd::NphIntegrator::mode () const [virtual]
Get the integrator mode.
Definition at line 347 of file mcMd/mdIntegrators/NphIntegrator.cpp.
Referenced by McMd::HybridNphMdMove::loadParameters(), and McMd::HybridNphMdMove::readParameters().
void McMd::NphIntegrator::setEta (unsigned int index, double eta) [virtual]
Get the barostat momentum.
Set the barostat momentum component of an index to a value eta
Parameters:
index index of momentum component.
eta value to which momentum component must be set.
Definition at line 359 of file mcMd/mdIntegrators/NphIntegrator.cpp.
Referenced by McMd::HybridNphMdMove::move().
The documentation for this class was generated from the following files:
mcMd/mdIntegrators/NphIntegrator.h
mcMd/mdIntegrators/NphIntegrator.cpp