Simpatico: DdMd::WriteConfig Class Reference
DdMd::WriteConfig Class Reference
Diagnostics
Detailed Description
Periodically dump simulation configuration to a new file.
This class uses the Simulation::writeConfig() method to write the entire simulation configuration periodically, at interval read from file. Names of configuration dump files are constructed by concatenating the Simulation outputPrefix, a dumpPrefix, the literal string "config.", and an integer that is incremented after each dump. The dump prefix is a string that is read by the read() method of this class. For example, if Simulation::outputPrefix is "out/" and dumpPrefix is "dump/", the configurations will be written to files "out/dump/config.0", "out/dump/config.1", etc.
Definition at line 34 of file WriteConfig.h.
#include <WriteConfig.h>
Public Member Functions
WriteConfig (Simulation &simulation)
Constructor.
virtual ~WriteConfig ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters and initialize.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void clear ()
Clear nSample counter.
virtual void sample (long iStep)
Dump configuration to file.
Public Member Functions inherited from DdMd::Diagnostic
Diagnostic (Simulation &simulation)
Default constructor.
virtual ~Diagnostic ()
Destructor.
virtual void setup ()
Setup before simulation.
virtual void output ()
Output any results at the end of a simulation.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
std::string className () const
Get class name string.
virtual void readParam (std::istream &in)
Read a parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an archive.
void resetParam ()
Resets ParamComposite to its empty state.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add a new Param < Type > object, and read its value.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add a C array parameter, and read its elements.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and read its elements.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n)
Add and read a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
Begin & readBegin (std::istream &in, const char *label)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a child ParamComposite.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add a new Param < Type > object, and load its value.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add a C array parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and load its elements.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n)
Add and load a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a DMatrix < Type > C two-dimensional matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
template<typename Type >
ScalarParam< Type > & add (const char *label, Type &value)
Add a new Param < Type > object to the format array.
template<typename Type >
CArrayParam< Type > & addCArray (const char *label, Type *value, int n)
Add a C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (const char *label, DArray< Type > &array, int n)
Add a DArray<Type> parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (const char *label, FArray< Type, N > &array)
Add a FArray<Type> parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (const char *label, Type *value, int m, int n)
Add a C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & addDMatrix (const char *label, DMatrix< Type > &matrix, int m, int n)
Add a C two-dimensional array parameter.
Begin & addBegin (const char *label)
Add a class label and opening bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Add a new Blank object, representing a blank line.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have a communicator?
MPI::Intracomm & ioCommunicator () const
Get the communicator.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from DdMd::Diagnostic
static void initStatic ()
Define and initialize baseInterval.
Static Public Attributes inherited from DdMd::Diagnostic
static long baseInterval = 1
The interval for a Diagnostic must be a multiple of baseInterval.
Protected Member Functions inherited from DdMd::Diagnostic
void readInterval (std::istream &in)
Read parameter interval from file.
void loadInterval (Serializable::IArchive &ar)
Load parameter interval from input archive.
void saveInterval (Serializable::OArchive &ar)
Save interval parameter to an archive.
void readOutputFileName (std::istream &in)
Read outputFileName from file.
void loadOutputFileName (Serializable::IArchive &ar)
Load output file name to an archive.
void saveOutputFileName (Serializable::OArchive &ar)
Save output file name to an archive.
Simulation & simulation ()
Get the parent Simulation by reference.
const std::string & outputFileName () const
Return outputFileName string.
std::string outputFileName (const std::string &suffix) const
Return outputFileName string with added suffix.
Constructor & Destructor Documentation
DdMd::WriteConfig::WriteConfig (Simulation & simulation)
Constructor.
Parameters
simulation parent Simulation object.
Definition at line 25 of file WriteConfig.cpp.
References Util::ParamComposite::setClassName().
virtual DdMd::WriteConfig::~WriteConfig () inline virtual
Destructor.
Definition at line 49 of file WriteConfig.h.
Member Function Documentation
void DdMd::WriteConfig::readParameters (std::istream & in) virtual
Read parameters and initialize.
Parameters
in input parameter file
Reimplemented from Util::ParamComposite.
Definition at line 34 of file WriteConfig.cpp.
References DdMd::Diagnostic::readInterval(), and DdMd::Diagnostic::readOutputFileName().
void DdMd::WriteConfig::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from DdMd::Diagnostic.
Definition at line 44 of file WriteConfig.cpp.
References Util::MpiLoader< IArchive >::load(), DdMd::Diagnostic::loadInterval(), and DdMd::Diagnostic::loadOutputFileName().
void DdMd::WriteConfig::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from DdMd::Diagnostic.
Definition at line 58 of file WriteConfig.cpp.
References DdMd::Diagnostic::saveInterval(), and DdMd::Diagnostic::saveOutputFileName().
void DdMd::WriteConfig::clear () virtual
Clear nSample counter.
Reimplemented from DdMd::Diagnostic.
Definition at line 68 of file WriteConfig.cpp.
void DdMd::WriteConfig::sample (long iStep) virtual
Dump configuration to file.
Parameters
iStep MC step index
Implements DdMd::Diagnostic.
Definition at line 74 of file WriteConfig.cpp.
References DdMd::Diagnostic::isAtInterval(), DdMd::Diagnostic::outputFileName(), DdMd::Diagnostic::simulation(), Util::toString(), and DdMd::Simulation::writeConfig().
The documentation for this class was generated from the following files:
WriteConfig.h
WriteConfig.cpp