Simpatico: Util::Random Class Reference
Util::Random Class Reference
Util namespace » Random
Detailed Description
Random number generator.
This class provides functions that return several forms of random numbers, using an internal Mersenne-Twister random number generator.
The generator may be seeded either by reading a seed from file, using the readParam() method, or by using setSeed() to set or reset it explicitly. In either case, inputting a positive integer causes that value to be used as a seed, but inputting a value of 0 causes the use of a seed that is generated from the system clock.
If the program is compiled with MPI, and MPI is initialized, then any automatically generated seed is also offset by a value that depends on the rank of the processor within the MPI world communicator, so that different processor use different seeds.
Definition at line 46 of file Random.h.
#include <Random.h>
Public Member Functions
Random ()
Constructor.
virtual ~Random ()
Destructor.
virtual void readParameters (std::istream &in)
Read seed from file, initialize RNG.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from file.
virtual void save (Serializable::OArchive &ar)
Save internal state to file.
void setSeed (SeedType seed)
Sets of random seed, and initializes random number generator.
double uniform ()
Return a random floating point number x, uniformly distributed in the range 0 <= x < 1.
double uniform (double range1, double range2)
Return a random floating point number x, uniformly distributed in the range range1 <= x < range2.
long uniformInt (long range1, long range2)
Return random long int x uniformly distributed in range1 <= x < range2.
void getPoint (double minR[], double maxR[], double r[])
Generate a random point in a box.
double gaussian (void)
Return a Gaussian random number with zero average and unit variance.
void unitVector (Vector &v)
Generate unit vector with uniform probability over the unit sphere.
bool metropolis (double ratio)
Metropolis algorithm for whether to accept a MC move.
long drawFrom (double probability[], long size)
Choose one of several outcomes with a specified set of probabilities.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
long seed ()
Returns value of random seed (private member variable seed_).
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Constructor & Destructor Documentation
Util::Random::Random ()
Constructor.
Definition at line 13 of file Random.cpp.
References Util::ParamComposite::setClassName().
Util::Random::~Random () virtual
Destructor.
Definition at line 22 of file Random.cpp.
Member Function Documentation
void Util::Random::readParameters (std::istream & in) virtual
Read seed from file, initialize RNG.
Parameters
in input stream.
Reimplemented from Util::ParamComposite.
Definition at line 28 of file Random.cpp.
References setSeed().
void Util::Random::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from file.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 37 of file Random.cpp.
void Util::Random::save (Serializable::OArchive & ar) virtual
Save internal state to file.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 46 of file Random.cpp.
Referenced by McMd::Simulation::save().
void Util::Random::setSeed (Random::SeedType seed)
Sets of random seed, and initializes random number generator.
Parameters
seed value for random seed (private member variable idum)
Definition at line 57 of file Random.cpp.
References seed(), and setSeed().
Referenced by readParameters(), and setSeed().
double Util::Random::uniform () inline
Return a random floating point number x, uniformly distributed in the range 0 <= x < 1.
Returns
random double precision number
Definition at line 203 of file Random.h.
Referenced by drawFrom(), gaussian(), getPoint(), DdMd::NvtLangevinIntegrator::integrateStep2(), metropolis(), McMd::AtomDisplaceMove::move(), McMd::RigidDisplaceMove::move(), Inter::CosineSqAngle::randomAngle(), Inter::HarmonicAngle::randomAngle(), Inter::CosineAngle::randomAngle(), Inter::HarmonicBond::randomBondLength(), Inter::FeneBond::randomBondLength(), Inter::CosineSqAngle::randomCosineAngle(), Inter::HarmonicAngle::randomCosineAngle(), Inter::CosineAngle::randomCosineAngle(), Util::MonoclinicBoundary::randomPosition(), Util::OrthorhombicBoundary::randomPosition(), McMd::NvtLangevinIntegrator::step(), uniformInt(), and unitVector().
double Util::Random::uniform (double range1, double range2) inline
Return a random floating point number x, uniformly distributed in the range range1 <= x < range2.
Returns
random double precision number
Definition at line 212 of file Random.h.
long Util::Random::uniformInt (long range1, long range2) inline
Return random long int x uniformly distributed in range1 <= x < range2.
Parameters range1 and range2 must be within the range of long integers.
Returns
random integer
Definition at line 224 of file Random.h.
References uniform().
Referenced by McMd::RingTetraRebridgeMove::move(), McMd::AtomDisplaceMove::move(), McMd::CfbRebridgeMove::move(), McMd::RingOctaRebridgeMove::move(), McMd::CfbRingRebridgeMove::move(), McMd::ReplicaMove::move(), McMd::LinkMaster::randomLink(), McMd::System::randomMolecule(), McMd::RingOctaRebridgeMove::scanBridge(), and McMd::RingTetraRebridgeMove::scanBridge().
void Util::Random::getPoint (double minR[], double maxR[], double r[]) inline
Generate a random point in a box.
Parameters
minR[] array of minimum coordinate values along three axes
maxR[] array of maximum coordinate values along three axes
r[] random position such that minR[axis] < r[axis] < maxR[axis]
Definition at line 251 of file Random.h.
References uniform().
double Util::Random::gaussian (void)
Return a Gaussian random number with zero average and unit variance.
Returns
Gaussian distributed random number.
Definition at line 92 of file Random.cpp.
References uniform().
Referenced by Util::Ar1Process::init(), McMd::HybridNphMdMove::move(), Util::Ar1Process::operator()(), Inter::HarmonicL0Bond::randomBondLength(), Inter::HarmonicBond::randomBondLength(), Inter::FeneBond::randomBondLength(), and McMd::MdSystem::setBoltzmannVelocities().
void Util::Random::unitVector (Vector & v)
Generate unit vector with uniform probability over the unit sphere.
Parameters
v random unit vector (upon return)
Definition at line 122 of file Random.cpp.
References uniform().
Referenced by McMd::CfbLinear::addAtom(), McMd::CfbEndBase::addEndAtom(), McMd::CfbRebridgeBase::addMiddleAtom(), McMd::CfbLinear::deleteAtom(), McMd::CfbEndBase::deleteEndAtom(), McMd::CfbRebridgeBase::deleteMiddleAtom(), and McMd::McNVTChemicalPotential::sample().
bool Util::Random::metropolis (double ratio) inline
Metropolis algorithm for whether to accept a MC move.
If ratio > 1, this function return true. If 0 < ratio < 1, this function returns true with probability ratio, and false with probability 1 - ratio.
Parameters
ratio ratio of old to new equilibrium weights
Returns
true if accepted, false if rejected
Definition at line 260 of file Random.h.
References uniform().
Referenced by McMd::RingTetraRebridgeMove::move(), McMd::AtomDisplaceMove::move(), McMd::CfbDoubleRebridgeMove::move(), McMd::CfbEndMove::move(), McMd::CfbLinearEndMove::move(), McMd::CfbRebridgeMove::move(), McMd::RingOctaRebridgeMove::move(), McMd::CfbReptationMove::move(), McMd::EndSwapMove::move(), McMd::HomopolymerSemiGrandMove::move(), McMd::HybridMdMove::move(), McMd::CfbRingRebridgeMove::move(), McMd::CfbReptateMove::move(), McMd::RigidDisplaceMove::move(), and McMd::HybridNphMdMove::move().
long Util::Random::drawFrom (double probability[], long size) inline
Choose one of several outcomes with a specified set of probabilities.
Precondition: Elements of probability array must add to 1.0
Parameters
probability[] array of probabilities, for indices 0,...,size-1
size number of options
Returns
random integer index of element of probability[] array
Definition at line 237 of file Random.h.
References uniform().
Referenced by McMd::CfbLinear::addAtom(), McMd::CfbEndBase::addEndAtom(), McMd::CfbRebridgeBase::addMiddleAtom(), McMd::McMoveManager::chooseMove(), and McMd::McNVTChemicalPotential::sample().
template<class Archive > void Util::Random::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Definition at line 284 of file Random.h.
long Util::Random::seed () inline
Returns value of random seed (private member variable seed_).
Returns
value of random number generator seed.
Definition at line 277 of file Random.h.
Referenced by setSeed().
The documentation for this class was generated from the following files:
Random.h
Random.cpp