Simpatico: SpAn::Configuration Class Reference
SpAn::Configuration Class Reference
Storage
Detailed Description
An instantaneous molecular dynamics configuration.
A Configuration has:
a Util::Boundary
an AtomStorage container for atoms
a GroupStorage for each type of covalent group
Definition at line 40 of file Configuration.h.
#include <Configuration.h>
Public Member Functions
Configuration ()
Constructor.
~Configuration ()
Destructor.
void readParam (const char *filename)
Open, read, and close parameter file.
void readParameters (std::istream &in)
Read parameters.
void clear ()
Clear all atoms and groups.
Boundary & boundary ()
Get the Boundary by non-const reference.
AtomStorage & atoms ()
Get the AtomStorage.
GroupStorage< 2 > & bonds ()
Get the Bond Configuration.
GroupStorage< 3 > & angles ()
Get the Angle Configuration.
GroupStorage< 4 > & dihedrals ()
Get the Dihedral Configuration.
int nSpecies () const
Number of species.
Species & species (int i)
Get a particular species identified by index.
Constructor & Destructor Documentation
SpAn::Configuration::Configuration ()
Constructor.
Definition at line 19 of file Configuration.cpp.
References Util::ParamComposite::setClassName().
SpAn::Configuration::~Configuration ()
Destructor.
Definition at line 36 of file Configuration.cpp.
Member Function Documentation
void SpAn::Configuration::readParam (const char * filename)
Open, read, and close parameter file.
Reimplemented in SpAn::Processor.
Definition at line 42 of file Configuration.cpp.
void SpAn::Configuration::readParameters (std::istream & in) [virtual]
Read parameters.
Reimplemented from Util::ParamComposite.
Reimplemented in SpAn::Processor.
Definition at line 53 of file Configuration.cpp.
References SpAn::AtomStorage::allocate(), Util::DSArray< Data >::allocate(), Util::DArray< Data >::allocate(), and Util::ParamComposite::isRequired().
void SpAn::Configuration::clear ()
Clear all atoms and groups.
Definition at line 106 of file Configuration.cpp.
References SpAn::AtomStorage::clear(), and Util::DSArray< Data >::clear().
Referenced by SpAn::Processor::analyzeDumps(), and SpAn::Processor::readConfig().
Boundary & SpAn::Configuration::boundary () [inline]
Get the Boundary by non-const reference.
Definition at line 170 of file Configuration.h.
Referenced by SpAn::DdMdConfigIo::readConfig(), SpAn::AtomMSD::sample(), SpAn::AtomMSD::setup(), and SpAn::DdMdConfigIo::writeConfig().
AtomStorage & SpAn::Configuration::atoms () [inline]
Get the AtomStorage.
Definition at line 173 of file Configuration.h.
Referenced by SpAn::DdMdConfigIo::readConfig(), and SpAn::DdMdConfigIo::writeConfig().
GroupStorage< 2 > & SpAn::Configuration::bonds () [inline]
Get the Bond Configuration.
Definition at line 177 of file Configuration.h.
GroupStorage< 3 > & SpAn::Configuration::angles () [inline]
Get the Angle Configuration.
Definition at line 182 of file Configuration.h.
GroupStorage< 4 > & SpAn::Configuration::dihedrals () [inline]
Get the Dihedral Configuration.
Definition at line 187 of file Configuration.h.
int SpAn::Configuration::nSpecies () const [inline]
Number of species.
If nSpecies == 0, all species and molecule info is disabled.
Definition at line 191 of file Configuration.h.
Referenced by SpAn::DdMdConfigIo::readConfig().
Species & SpAn::Configuration::species (int i) [inline]
Get a particular species identified by index.
Parameters:
i species index
Definition at line 194 of file Configuration.h.
Referenced by SpAn::DdMdConfigIo::readConfig(), SpAn::AtomMSD::readParameters(), SpAn::AtomMSD::sample(), and SpAn::AtomMSD::setup().
The documentation for this class was generated from the following files:
Configuration.h
Configuration.cpp