Simpatico: McMd::MdAnalyzerFactory Class Reference
McMd::MdAnalyzerFactory Class Reference
MD Analyzers
Detailed Description
AnalyzerFactory for an MdSimulation.
Definition at line 29 of file MdAnalyzerFactory.h.
#include <MdAnalyzerFactory.h>
Public Member Functions
MdAnalyzerFactory (MdSimulation &simulation, MdSystem &system)
Constructor.
virtual Analyzer * factory (const std::string &className) const
Return pointer to a new Analyzer object.
Protected Member Functions
MdSystem & system () const
Return reference to parent MdSystem.
MdSimulation & simulation () const
Return reference to parent MdSimulation.
Constructor & Destructor Documentation
McMd::MdAnalyzerFactory::MdAnalyzerFactory (MdSimulation & simulation, MdSystem & system)
Constructor.
Parameters:
simulation parent simulation
system parent system
Definition at line 30 of file MdAnalyzerFactory.cpp.
Member Function Documentation
Analyzer * McMd::MdAnalyzerFactory::factory (const std::string & className) const [virtual]
Return pointer to a new Analyzer object.
Parameters:
className name of a subclass of Analyzer.
Returns:
base class pointer to a new instance of className.
Implements Util::Factory< Analyzer >.
Definition at line 40 of file MdAnalyzerFactory.cpp.
References McMd::SystemAnalyzerFactory::factory(), system(), and Util::Factory< Analyzer >::trySubfactories().
MdSystem& McMd::MdAnalyzerFactory::system () const [inline, protected]
Return reference to parent MdSystem.
Definition at line 55 of file MdAnalyzerFactory.h.
Referenced by factory().
MdSimulation& McMd::MdAnalyzerFactory::simulation () const [inline, protected]
Return reference to parent MdSimulation.
Definition at line 61 of file MdAnalyzerFactory.h.
The documentation for this class was generated from the following files:
MdAnalyzerFactory.h
MdAnalyzerFactory.cpp