Simpatico: Util::AverageStage Class Reference
Util::AverageStage Class Reference
Accumulators
Detailed Description
A hierarchical block average algorithm.
This class implements a hierarchical block averaging algorithm that calculates the average and variance of a sequence of values, and also calculates the variance for sequences of block averages, for multiple block sizes. The algorithm is implemented by a chain of AverageStage objects, in which each object is assigned an integer chainId. The "primary" AverageStage object (chainId=0) in this chain calculates the average and variance for a "primary" sequence of measured values that are passed as parameters to its sample method. This object hold a pointer to an AverageStage with chainId=1 that calculates the variance of a sequence in which each value is the average of a block of blockFactor consecutive values in the primary sequence. The object with chainId=1 holds a pointer to an object with chainId=2 that calculates the variance of a sequence in which each value is the average of a block of blockFactor values of the sequence processed by chainId=1, or blockFactor**2 values of the primary sequence. In general, the object with chainId=n calculates the variance of a sequence in which each value is an average of blockFactor**n values of the primary sequence. The integer parameter blockFactor is passed to the constructor of the primary AverageStage object as a parameter, which is set to blockFactor=2 by default. New stages are added to this chain of objects dynamically as the length of the primary sequence grows: After the primary AverageStage has sampled m values, there exists one AverageStage objects for each value of 0 <= * stageId <= n, where n is the largest integer for which blockFactor**n <= m.
The outputError() method of the primary AverageStage outputs a sequence of estimates of the error of the average that are derived different stages of block averaging. The estimate obtained from each stage is given by sqrt(variance/nSample), where variance is the variance of the sequence of block averages processed by that stage, and nSample is the number of such block averages thus far. This estimate is accurate only when the block averages are long enough to be uncorrelated. A reliable estimate of the error of the average can be obtained if and only if several stages of block averaging yield statistically indistinguishable error estimates.
Algorithm:
The averaging algorithm is implemented by the sample() method. Each time the sample method is called with a new value, the method increments a sum of values and sum of squares,from which the average and variance can be calculated. It also increments a block sum that is reset to zero every blockFactor samples. Each AverageStage object can hold a pointer to a child AverageStage object. When an AverageStage is instantiated, that pointer is null. After the first blockFactor samples, however, the sample method creates a new child object. At this point, and every blockFactor steps thereafter, the sample method of the parent passes a block average to the sample method of its child and then resets the block sum to zero. The resulting chain of objects is extended as needed: After blockFactor*blockFactor samples have been passed to a parent, so that blockFactor block average values have been passed to a child object, the child will create a grandchild. The public interface of the primary AverageStage object allows all of the objects in the resulting chain to report error estimates, via the recursive outputError() method, but does not allow any other form of access to descendants of the primary AverageStage object.
Definition at line 83 of file AverageStage.h.
#include <AverageStage.h>
Public Member Functions
AverageStage (int blockFactor=2)
Constructor.
virtual ~AverageStage ()
Destructor.
virtual void clear ()
Initialize all accumulators and recursively destroy all children.
virtual void registerDescendant (AverageStage *descendantPtr)
Register the creation of a descendant stage.
virtual void sample (double value)
Add a sampled value to the ensemble.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Add a sampled value to the ensemble.
Accessors
double average () const
Return the average of all sampled values.
double variance () const
Return the variance of all sampled values.
double stdDeviation () const
Return the standard deviation of all sampled values.
double error () const
Return an estimate for the std deviation of the average.
long nSample () const
Return the number of sampled values.
long stageInterval () const
Return the number of sampled values per block at this stage.
Protected Member Functions
bool hasChild () const
Does this object have a child AverageStage for block averages?
AverageStage & child ()
Return the child AverageStage by reference.
Constructor & Destructor Documentation
Util::AverageStage::AverageStage (int blockFactor = 2)
Constructor.
This constructor creates a primary AverageStage object with stageId = 0 and stageInterval = 1. A private constructor is used to recursively create children of this object.
Parameters
blockFactor ratio of block sizes of subsequent stages
Definition at line 23 of file AverageStage.cpp.
Referenced by sample(), and serialize().
Util::AverageStage::~AverageStage () virtual
Destructor.
Recursively destroy all children.
Definition at line 58 of file AverageStage.cpp.
Member Function Documentation
void Util::AverageStage::clear () virtual
Initialize all accumulators and recursively destroy all children.
Reimplemented in Util::Average.
Definition at line 68 of file AverageStage.cpp.
Referenced by Util::Average::clear().
void Util::AverageStage::registerDescendant (AverageStage * descendantPtr) virtual
Register the creation of a descendant stage.
This should be called only by a root stage.
Parameters
descendantPtr pointer to a descendant AverageStage.
Reimplemented in Util::Average.
Definition at line 52 of file AverageStage.cpp.
Referenced by sample(), and serialize().
void Util::AverageStage::sample (double value) virtual
Add a sampled value to the ensemble.
Parameters
value sampled value
Reimplemented in Util::Average.
Definition at line 83 of file AverageStage.cpp.
References AverageStage(), registerDescendant(), and sample().
Referenced by sample().
template<class Archive > void Util::AverageStage::serialize (Archive & ar, const unsigned int version)
Add a sampled value to the ensemble.
Parameters
ar input or output archive
version file version id
Definition at line 261 of file AverageStage.h.
References AverageStage(), hasChild(), and registerDescendant().
Referenced by Util::Average::loadParameters(), and Util::Average::serialize().
double Util::AverageStage::average () const
Return the average of all sampled values.
Definition at line 118 of file AverageStage.cpp.
Referenced by McMd::McVirialStressTensorAverage::output(), DdMd::VirialStressTensorAverage::output(), McMd::MdVirialStressTensorAverage::output(), and Util::Average::output().
double Util::AverageStage::variance () const
Return the variance of all sampled values.
Definition at line 124 of file AverageStage.cpp.
Referenced by error(), Util::Average::output(), and stdDeviation().
double Util::AverageStage::stdDeviation () const
Return the standard deviation of all sampled values.
Returns
sqrt(variance())
Definition at line 135 of file AverageStage.cpp.
References variance().
Referenced by Util::Average::output().
double Util::AverageStage::error () const
Return an estimate for the std deviation of the average.
Returns
sqrt(variance()/nSample())
Definition at line 153 of file AverageStage.cpp.
References variance().
Referenced by McMd::McVirialStressTensorAverage::output(), DdMd::VirialStressTensorAverage::output(), McMd::MdVirialStressTensorAverage::output(), and Util::Average::output().
long Util::AverageStage::nSample () const
Return the number of sampled values.
Definition at line 141 of file AverageStage.cpp.
Referenced by Util::Average::output().
long Util::AverageStage::stageInterval () const
Return the number of sampled values per block at this stage.
Definition at line 147 of file AverageStage.cpp.
Referenced by Util::Average::output().
bool Util::AverageStage::hasChild () const inline protected
Does this object have a child AverageStage for block averages?
Definition at line 246 of file AverageStage.h.
Referenced by serialize().
AverageStage & Util::AverageStage::child () inline protected
Return the child AverageStage by reference.
Definition at line 252 of file AverageStage.h.
The documentation for this class was generated from the following files:
AverageStage.h
AverageStage.cpp