Simpatico: Tools::HoomdConfigWriter Class Reference
Tools::HoomdConfigWriter Class Reference
Detailed Description
Hoomd-blue XML format for configuration files.
Definition at line 27 of file HoomdConfigWriter.h.
#include <HoomdConfigWriter.h>
Public Member Functions
HoomdConfigWriter ()
Default constructor.
HoomdConfigWriter (Configuration &configuration)
Constructor.
virtual void writeConfig (std::ofstream &file)
Write configuration file in DdMd default format.
virtual void readAuxiliaryFile (std::ifstream &file)
Read auxiliary file with type map information.
Constructor & Destructor Documentation
Tools::HoomdConfigWriter::HoomdConfigWriter ()
Default constructor.
Tools::HoomdConfigWriter::HoomdConfigWriter (Configuration & configuration)
Constructor.
Parameters:
configuration parent Configuration object.
Definition at line 30 of file HoomdConfigWriter.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void Tools::HoomdConfigWriter::writeConfig (std::ofstream & file) [virtual]
Write configuration file in DdMd default format.
Parameters:
file output file stream (must be open on master)
Implements Tools::ConfigWriter.
Definition at line 96 of file HoomdConfigWriter.cpp.
References Tools::Configuration::atoms(), Tools::AtomStorage::begin(), Tools::Configuration::boundary(), Util::Dimension, Util::OrthorhombicBoundary::lengths(), Tools::TypeMap::name(), Util::ArrayIterator< Data >::notEnd(), Util::OrthorhombicBoundary::shift(), Tools::AtomStorage::size(), Util::OrthorhombicBoundary::transformCartToGen(), Util::OrthorhombicBoundary::transformGenToCart(), and UTIL_THROW.
void Tools::HoomdConfigWriter::readAuxiliaryFile (std::ifstream & file) [virtual]
Read auxiliary file with type map information.
Parameters:
file input file stream
Reimplemented from Tools::ConfigWriter.
Definition at line 38 of file HoomdConfigWriter.cpp.
References Util::checkString(), Util::getNextLine(), and Tools::TypeMap::read().
The documentation for this class was generated from the following files:
HoomdConfigWriter.h
HoomdConfigWriter.cpp