Simpatico: McMd::AverageDiagnostic< SystemType > Class Template Reference
McMd::AverageDiagnostic< SystemType > Class Template Reference
Diagnostics
Detailed Description
template<class SystemType>
class McMd::AverageDiagnostic< SystemType >
AverageDiagnostic averages of total potential energy.
Definition at line 26 of file AverageDiagnostic.h.
#include <AverageDiagnostic.h>
Public Member Functions
AverageDiagnostic (SystemType &system)
Constructor.
~AverageDiagnostic ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters and initialize.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Clear accumulators.
virtual void output ()
Output results at end of simulation.
Protected Attributes
std::ofstream outputFile_
Output file stream.
Average accumulator_
Average object - statistical accumulator.
int nSamplePerBlock_
Number of samples per block average output.
Constructor & Destructor Documentation
template<class SystemType> McMd::AverageDiagnostic< SystemType >::AverageDiagnostic (SystemType & system)
Constructor.
Definition at line 96 of file AverageDiagnostic.h.
template<class SystemType > McMd::AverageDiagnostic< SystemType >::~AverageDiagnostic ()
Destructor.
Definition at line 107 of file AverageDiagnostic.h.
Member Function Documentation
template<class SystemType > void McMd::AverageDiagnostic< SystemType >::readParameters (std::istream & in) [virtual]
Read parameters and initialize.
Reimplemented from McMd::Diagnostic.
Definition at line 114 of file AverageDiagnostic.h.
References McMd::Diagnostic::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), McMd::Diagnostic::readInterval(), and McMd::Diagnostic::readOutputFileName().
template<class SystemType > void McMd::AverageDiagnostic< SystemType >::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 135 of file AverageDiagnostic.h.
References McMd::Diagnostic::fileMaster(), McMd::Diagnostic::loadParameters(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), and UTIL_THROW.
template<class SystemType > void McMd::AverageDiagnostic< SystemType >::save (Serializable::OArchive & ar) [virtual]
Save state to an archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 159 of file AverageDiagnostic.h.
template<class SystemType > template<class Archive > void McMd::AverageDiagnostic< SystemType >::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar archive
version archive version id
Reimplemented from McMd::Diagnostic.
Definition at line 168 of file AverageDiagnostic.h.
References McMd::Diagnostic::serialize().
template<class SystemType > void McMd::AverageDiagnostic< SystemType >::setup () [virtual]
Clear accumulators.
Reimplemented from McMd::Diagnostic.
Definition at line 180 of file AverageDiagnostic.h.
template<class SystemType > void McMd::AverageDiagnostic< SystemType >::output () [virtual]
Output results at end of simulation.
Reimplemented from McMd::Diagnostic.
Definition at line 187 of file AverageDiagnostic.h.
References McMd::Diagnostic::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), and Util::ParamComposite::writeParam().
Member Data Documentation
template<class SystemType> std::ofstream McMd::AverageDiagnostic< SystemType >::outputFile_ [protected]
Output file stream.
Definition at line 82 of file AverageDiagnostic.h.
template<class SystemType> Average McMd::AverageDiagnostic< SystemType >::accumulator_ [protected]
Average object - statistical accumulator.
Definition at line 85 of file AverageDiagnostic.h.
template<class SystemType> int McMd::AverageDiagnostic< SystemType >::nSamplePerBlock_ [protected]
Number of samples per block average output.
Definition at line 88 of file AverageDiagnostic.h.
The documentation for this class was generated from the following file:
AverageDiagnostic.h