Simpatico: Util::AutoCorrelation< Data, Product > Class Template Reference
Util::AutoCorrelation< Data, Product > Class Template Reference
Accumulators
Detailed Description
template<typename Data, typename Product>
class Util::AutoCorrelation< Data, Product >
Auto-correlation function, using hierarchical algorithm.
This class represents the primary stage of a linked list of AutoCorrStage objects that implement a hierarchical blocking algorithm for an auto-correlation function.
Definition at line 29 of file AutoCorrelation.h.
#include <AutoCorrelation.h>
Public Member Functions
AutoCorrelation ()
Constructor.
virtual void readParameters (std::istream &in)
Read parameters from file and initialize.
virtual void load (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
int maxDelay () const
Return maximum delay, in primary samples.
Protected Member Functions
virtual void registerDescendant (AutoCorrStage< Data, Product > *ptr)
Register a descendant stage.
Constructor & Destructor Documentation
template<typename Data , typename Product > Util::AutoCorrelation< Data, Product >::AutoCorrelation ()
Constructor.
Definition at line 23 of file AutoCorrelation.tpp.
References Util::GArray< Data >::append().
Member Function Documentation
template<typename Data , typename Product > void Util::AutoCorrelation< Data, Product >::readParameters (std::istream & in) [virtual]
Read parameters from file and initialize.
Parameters:
in input parameter file
Reimplemented from Util::ParamComposite.
Definition at line 33 of file AutoCorrelation.tpp.
template<typename Data , typename Product > void Util::AutoCorrelation< Data, Product >::load (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 46 of file AutoCorrelation.tpp.
template<typename Data , typename Product > void Util::AutoCorrelation< Data, Product >::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 58 of file AutoCorrelation.tpp.
template<typename Data , typename Product > int Util::AutoCorrelation< Data, Product >::maxDelay () const
Return maximum delay, in primary samples.
Definition at line 65 of file AutoCorrelation.tpp.
References Util::AutoCorrStage< Data, Product >::bufferSize(), and Util::AutoCorrStage< Data, Product >::stageInterval().
template<typename Data, typename Product> void Util::AutoCorrelation< Data, Product >::registerDescendant (AutoCorrStage< Data, Product > * ptr) [protected, virtual]
Register a descendant stage.
This should be called only by a root stage.
Parameters:
ptr pointer to a descendant AutoCorrelation.
Reimplemented from Util::AutoCorrStage< Data, Product >.
Definition at line 80 of file AutoCorrelation.tpp.
The documentation for this class was generated from the following files:
AutoCorrelation.h
AutoCorrelation.tpp