Simpatico: McMd::McVirialStressTensorAverage Class Reference
McMd::McVirialStressTensorAverage Class Reference
Analyzers
Detailed Description
Periodically write (tensor) StressTensor to file.
Definition at line 27 of file McVirialStressTensorAverage.h.
#include <McVirialStressTensorAverage.h>
Public Member Functions
McVirialStressTensorAverage (McSystem &system)
Constructor.
virtual ~McVirialStressTensorAverage ()
Destructor.
virtual void readParameters (std::istream &in)
Read dumpPrefix and interval.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void clear ()
Clear nSample counter.
virtual void sample (long iStep)
Sample virial stress to accumulators.
virtual void output ()
Dump configuration to file.
Constructor & Destructor Documentation
McMd::McVirialStressTensorAverage::McVirialStressTensorAverage (McSystem & system)
Constructor.
Parameters:
system parent McSystem object.
Definition at line 28 of file McVirialStressTensorAverage.cpp.
References Util::ParamComposite::setClassName().
virtual McMd::McVirialStressTensorAverage::~McVirialStressTensorAverage () [inline, virtual]
Destructor.
Definition at line 42 of file McVirialStressTensorAverage.h.
Member Function Documentation
void McMd::McVirialStressTensorAverage::readParameters (std::istream & in) [virtual]
Read dumpPrefix and interval.
Parameters:
in input parameter file
Reimplemented from McMd::Analyzer.
Definition at line 47 of file McVirialStressTensorAverage.cpp.
References McMd::System::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Analyzer::outputFileName(), McMd::Analyzer::readInterval(), McMd::Analyzer::readOutputFileName(), Util::Average::setNSamplePerBlock(), and McMd::SystemAnalyzer< McSystem >::system().
void McMd::McVirialStressTensorAverage::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::Analyzer.
Definition at line 74 of file McVirialStressTensorAverage.cpp.
References McMd::Analyzer::fileMaster(), Util::Average::loadParameters(), Util::FileMaster::openOutputFile(), and McMd::Analyzer::outputFileName().
void McMd::McVirialStressTensorAverage::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::Analyzer.
Definition at line 98 of file McVirialStressTensorAverage.cpp.
void McMd::McVirialStressTensorAverage::clear () [virtual]
Clear nSample counter.
Definition at line 105 of file McVirialStressTensorAverage.cpp.
References Util::Average::clear(), and UTIL_THROW.
void McMd::McVirialStressTensorAverage::sample (long iStep) [virtual]
Sample virial stress to accumulators.
Parameters:
iStep MD step index
Implements McMd::Analyzer.
Definition at line 127 of file McVirialStressTensorAverage.cpp.
References McMd::McSystem::computeVirialStress(), McMd::Analyzer::isAtInterval(), Util::Average::sample(), and McMd::SystemAnalyzer< McSystem >::system().
void McMd::McVirialStressTensorAverage::output () [virtual]
Dump configuration to file.
Reimplemented from McMd::Analyzer.
Definition at line 151 of file McVirialStressTensorAverage.cpp.
References Util::AverageStage::average(), and Util::AverageStage::error().
The documentation for this class was generated from the following files:
McVirialStressTensorAverage.h
McVirialStressTensorAverage.cpp