Simpatico: McMd::McMuExchange Class Reference
McMd::McMuExchange Class Reference
MC Analyzers
Detailed Description
Exchange chemical potential for semigrand ensemble.
This class calculates the excess free energy cost of transforming a randomly chosen molecule of a specified species into another species by a hypothetical "alchemical" transformation of the atom types of some or all atoms in the molecule.
Definition at line 38 of file McMuExchange.h.
#include <McMuExchange.h>
Public Member Functions
McMuExchange (McSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters and initialize.
virtual void setup ()
Clear accumulators.
virtual void sample (long iStep)
Evaluate energy per particle, and add to ensemble.
virtual void output ()
Output results at end of simulation.
virtual void save (Serializable::OArchive &ar)
Save state to binary file archive.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from a binary file archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
Constructor & Destructor Documentation
McMd::McMuExchange::McMuExchange (McSystem & system)
Constructor.
Definition at line 34 of file McMuExchange.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::McMuExchange::readParameters (std::istream & in) [virtual]
Read parameters and initialize.
Reimplemented from McMd::Analyzer.
Definition at line 53 of file McMuExchange.cpp.
References Util::DSArray< Data >::allocate(), Util::DArray< Data >::allocate(), Util::DSArray< Data >::append(), McMd::Species::atomTypeId(), McMd::Species::capacity(), McMd::Species::nAtom(), McMd::Analyzer::readInterval(), McMd::Analyzer::readOutputFileName(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemAnalyzer< McSystem >::system(), and UTIL_THROW.
void McMd::McMuExchange::setup () [virtual]
Clear accumulators.
Reimplemented from McMd::Analyzer.
Definition at line 89 of file McMuExchange.cpp.
References Util::Array< Data >::capacity(), McMd::System::nMolecule(), McMd::SystemAnalyzer< McSystem >::system(), and UTIL_THROW.
void McMd::McMuExchange::sample (long iStep) [virtual]
Evaluate energy per particle, and add to ensemble.
Implements McMd::Analyzer.
Definition at line 106 of file McMuExchange.cpp.
References McMd::System::begin(), Util::EnergyEnsemble::beta(), McMd::McPairPotential::cellList(), Util::OrthorhombicBoundary::distanceSq(), McMd::PairPotential::energy(), McMd::System::energyEnsemble(), McMd::CellList::getNeighbors(), McMd::Atom::id(), McMd::Analyzer::isAtInterval(), McMd::Mask::isMasked(), McMd::Atom::mask(), McMd::Atom::molecule(), Util::PArrayIterator< Data >::notEnd(), McMd::McSystem::pairPotential(), McMd::Atom::position(), Util::FSArray< Data, Capacity >::size(), Util::DSArray< Data >::size(), McMd::SystemAnalyzer< McSystem >::system(), McMd::Atom::typeId(), and UTIL_THROW.
void McMd::McMuExchange::output () [virtual]
Output results at end of simulation.
Reimplemented from McMd::Analyzer.
Definition at line 202 of file McMuExchange.cpp.
References McMd::Analyzer::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Analyzer::outputFileName(), and Util::ParamComposite::writeParam().
void McMd::McMuExchange::save (Serializable::OArchive & ar) [virtual]
Save state to binary file archive.
Parameters:
ar binary saving (output) archive.
Reimplemented from McMd::Analyzer.
Definition at line 242 of file McMuExchange.cpp.
References McMd::Analyzer::interval_, McMd::Analyzer::outputFileName_, and UTIL_THROW.
void McMd::McMuExchange::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from a binary file archive.
Parameters:
ar binary loading (input) archive.
Reimplemented from McMd::Analyzer.
Definition at line 261 of file McMuExchange.cpp.
References Util::DSArray< Data >::allocate(), Util::DArray< Data >::allocate(), Util::DSArray< Data >::append(), McMd::Species::atomTypeId(), McMd::Species::capacity(), Util::ParamComposite::loadDArray(), McMd::Analyzer::loadInterval(), McMd::Analyzer::loadOutputFileName(), Util::ParamComposite::loadParameter(), McMd::Species::nAtom(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemAnalyzer< McSystem >::system(), and UTIL_THROW.
template<class Archive > void McMd::McMuExchange::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Analyzer.
Definition at line 155 of file McMuExchange.h.
The documentation for this class was generated from the following files:
McMuExchange.h
McMuExchange.cpp