Simpatico: McMd::ReplicaMove Class Reference
McMd::ReplicaMove Class Reference
Free Energy Perturbation
Detailed Description
Replica exchange Monte Carlo move using Gibbs sampling.
This class implements a rather general form of the algorithm for a replica exchange / parallel tempering move. The algorithm assumes that the Boltzmann weight W(X,p) for a system in configuration X depends upon some floating point parameter p in a manner that is described by an Perturbation object associated with the parent System. The ReplicaMove constructor requires a parent System as a parameter, and requires that the System has an associated Perturbation object when the ReplicaMove is constructed.
This move implements a version replica exchange that uses the Gibbs sampler technique to sample permutations in replica space from the corresponding distribution. The sampling is done by running a small (inexpensive) Markov chain Monte Carlo simulation of nSamling steps at every replica exchange step, at the end of which a permutation is obtained that is used to swap configurations between replicas. This implies that all configurations are permuted simultaneously (but there may be configurations which stay on the same processor).
The technique is described in detail in John D. Chodera and Michael R. Shirts, J. Chem. Phys. 135, 194110 (2011)
Definition at line 64 of file ReplicaMove.h.
#include <ReplicaMove.h>
Public Member Functions
ReplicaMove (System &system)
Constructor.
virtual ~ReplicaMove ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual bool move ()
Attempt, and accept or reject a replica exchange move.
long interval () const
Get interval (number of steps between successives attempts).
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
void notifyObservers (sendRecvPair partners)
Notify observers of a successful replica exchange.
long nAttempt ()
Number of swap attempts.
long nAccept ()
Number of accepted swaps.
Protected Member Functions
System & system ()
Return the associated system by reference.
Constructor & Destructor Documentation
McMd::ReplicaMove::ReplicaMove (System & system)
Constructor.
Definition at line 37 of file ReplicaMove.cpp.
References McMd::Simulation::communicator(), McMd::System::fileMaster(), McMd::Perturbation::getNParameters(), McMd::System::hasPerturbation(), Util::FileMaster::openOutputFile(), McMd::System::perturbation(), Util::ParamComposite::setClassName(), McMd::System::simulation(), and UTIL_THROW.
McMd::ReplicaMove::~ReplicaMove () [virtual]
Destructor.
Definition at line 81 of file ReplicaMove.cpp.
Member Function Documentation
void McMd::ReplicaMove::readParameters (std::istream & in) [virtual]
Read parameters.
The parameter block takes the parameter interval, which sets the interval between successive replica exchange attempts.
At every replica exchange attempt, the permutation is sampled from a MCMC run of nSampling steps. Empirically, nSampling should be on the order of P^3 .. P^5, where P is the number of processors.
Parameters:
in input stream from which to read parameters.
Reimplemented from Util::ParamComposite.
Definition at line 90 of file ReplicaMove.cpp.
References McMd::Simulation::atomCapacity(), McMd::System::simulation(), system(), and UTIL_THROW.
void McMd::ReplicaMove::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 110 of file ReplicaMove.cpp.
References McMd::Simulation::atomCapacity(), McMd::System::simulation(), system(), and UTIL_THROW.
void McMd::ReplicaMove::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 135 of file ReplicaMove.cpp.
References McMd::Simulation::atomCapacity(), McMd::System::simulation(), and system().
Referenced by McMd::System::saveReplicaMove().
bool McMd::ReplicaMove::move () [virtual]
Attempt, and accept or reject a replica exchange move.
Definition at line 150 of file ReplicaMove.cpp.
References Util::MemoryOArchive::allocate(), Util::MemoryIArchive::allocate(), Util::DArray< Data >::allocate(), McMd::System::begin(), McMd::System::boundary(), McMd::Perturbation::derivative(), Util::OrthorhombicBoundary::lengths(), Util::memorySize(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), notifyObservers(), McMd::Simulation::nSpecies(), McMd::Perturbation::parameter(), McMd::System::perturbation(), McMd::Simulation::random(), Util::MemoryIArchive::recv(), Util::MemoryOArchive::send(), Util::OrthorhombicBoundary::setOrthorhombic(), McMd::System::simulation(), system(), and Util::Random::uniformInt().
Referenced by McMd::McSimulation::simulate().
long McMd::ReplicaMove::interval () const [inline]
Get interval (number of steps between successives attempts).
Definition at line 195 of file ReplicaMove.h.
bool McMd::ReplicaMove::isAtInterval (long counter) const [inline]
Return true iff counter is a multiple of the interval.
Parameters:
counter simulation step counter
Definition at line 201 of file ReplicaMove.h.
void McMd::ReplicaMove::notifyObservers (sendRecvPair partners)
Notify observers of a successful replica exchange.
Parameters:
partners a pair of indices of partner replicas. Needs to be known for communication.
Referenced by move().
long McMd::ReplicaMove::nAttempt () [inline]
Number of swap attempts.
Definition at line 207 of file ReplicaMove.h.
Referenced by McMd::McSimulation::simulate().
long McMd::ReplicaMove::nAccept () [inline]
Number of accepted swaps.
Definition at line 213 of file ReplicaMove.h.
Referenced by McMd::McSimulation::simulate().
System & McMd::ReplicaMove::system () [inline, protected]
Return the associated system by reference.
Definition at line 219 of file ReplicaMove.h.
Referenced by loadParameters(), move(), readParameters(), and save().
The documentation for this class was generated from the following files:
ReplicaMove.h
ReplicaMove.cpp