Simpatico: Inter::OrderingExternal Class Reference
Inter::OrderingExternal Class Reference
External Interactions
Detailed Description
A clipped cosine potential that induces ordering along directions specified by waveIntVectors, w_i.
                                            /                   /     /      w_i.x     w_i.y     w_i.z  \  \  \
u = prefactor[atomType] externalParameter tanh | clipParameter Sum | cos | 2 pi ----— + ----— + ----— | | | \ i \ \ Lx Ly Lz / / /
Prefactor (which depends on the atomType), externalParameter, waveIntVectors, interfaceWidth and periodicity are given as inputs in the parameter file. ClipParameter is the inverse of 2*pi*periodicity*interfaceWidth.
Definition at line 37 of file OrderingExternal.h.
#include <OrderingExternal.h>
Public Member Functions
OrderingExternal ()
Default constructor.
OrderingExternal (const OrderingExternal &other)
Copy constructor.
OrderingExternal & operator= (const OrderingExternal &other)
Assignment.
void setNAtomType (int nAtomType)
Set nAtomType value.
void setExternalParameter (double externalParameter)
Sets external parameter.
void setBoundary (Boundary &boundary)
Set pointer to Boundary.
void readParameters (std::istream &in)
Read potential parameters, and initialize other variables.
double externalParameter () const
Returns external parameter.
double energy (const Vector &position, int i) const
Returns external potential energy of a single particle.
void getForce (const Vector &position, int type, Vector &force) const
Returns force caused by the external potential.
std::string className () const
Return name string "OrderingExternal".
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
std::string className () const
Get class name string.
virtual void readParam (std::istream &in)
Read a parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an archive.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void resetParam ()
Resets ParamComposite to its empty state.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add a new Param < Type > object, and read its value.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add a C array parameter, and read its elements.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and read its elements.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n)
Add and read a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
Begin & readBegin (std::istream &in, const char *label)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a child ParamComposite.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add a new Param < Type > object, and load its value.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add a C array parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and load its elements.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n)
Add and load a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a DMatrix < Type > C two-dimensional matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
template<typename Type >
ScalarParam< Type > & add (const char *label, Type &value)
Add a new Param < Type > object to the format array.
template<typename Type >
CArrayParam< Type > & addCArray (const char *label, Type *value, int n)
Add a C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (const char *label, DArray< Type > &array, int n)
Add a DArray<Type> parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (const char *label, FArray< Type, N > &array)
Add a FArray<Type> parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (const char *label, Type *value, int m, int n)
Add a C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & addDMatrix (const char *label, DMatrix< Type > &matrix, int m, int n)
Add a C two-dimensional array parameter.
Begin & addBegin (const char *label)
Add a class label and opening bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Add a new Blank object, representing a blank line.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have a communicator?
MPI::Intracomm & ioCommunicator () const
Get the communicator.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
Constructor & Destructor Documentation
Inter::OrderingExternal::OrderingExternal ()
Default constructor.
Definition at line 23 of file OrderingExternal.cpp.
References Util::ParamComposite::setClassName().
Inter::OrderingExternal::OrderingExternal (const OrderingExternal & other)
Copy constructor.
Definition at line 36 of file OrderingExternal.cpp.
References Util::DArray< Data >::allocate(), and Util::Dimension.
Member Function Documentation
OrderingExternal & Inter::OrderingExternal::operator= (const OrderingExternal & other)
Assignment.
Definition at line 60 of file OrderingExternal.cpp.
References Util::Dimension.
void Inter::OrderingExternal::setNAtomType (int nAtomType)
Set nAtomType value.
Parameters
nAtomType number of atom types.
Definition at line 83 of file OrderingExternal.cpp.
References UTIL_THROW.
void Inter::OrderingExternal::setExternalParameter (double externalParameter)
Sets external parameter.
Parameters
externalParameter external parameter of system
Definition at line 94 of file OrderingExternal.cpp.
References externalParameter(), and UTIL_THROW.
void Inter::OrderingExternal::setBoundary (Boundary & boundary)
Set pointer to Boundary.
Parameters
boundary Boundary object (used to calculate length along perpendicular direction).
Definition at line 108 of file OrderingExternal.cpp.
void Inter::OrderingExternal::readParameters (std::istream & in) virtual
Read potential parameters, and initialize other variables.
Precondition
nAtomType must have been set, by calling setNAtomType().
Boundary must have been set, by calling setBoundary().
Parameters
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 114 of file OrderingExternal.cpp.
References Util::DArray< Data >::allocate(), and UTIL_THROW.
double Inter::OrderingExternal::externalParameter () const
Returns external parameter.
Returns
external parameter
Definition at line 139 of file OrderingExternal.cpp.
Referenced by setExternalParameter().
double Inter::OrderingExternal::energy (const Vector & position, int i) const inline
Returns external potential energy of a single particle.
Parameters
position atomic position Vector
i atom type.
Returns
external potential energy
Definition at line 157 of file OrderingExternal.h.
References Util::Vector::dot().
void Inter::OrderingExternal::getForce (const Vector & position, int type, Vector & force) const inline
Returns force caused by the external potential.
Parameters
position atom position
type atom type id
force force on the atom (on output)
Definition at line 179 of file OrderingExternal.h.
References Util::Vector::dot(), and Util::Vector::zero().
std::string Inter::OrderingExternal::className () const
Return name string "OrderingExternal".
Definition at line 147 of file OrderingExternal.cpp.
The documentation for this class was generated from the following files:
OrderingExternal.h
OrderingExternal.cpp