Simpatico: Tools::Species Class Reference
Tools::Species Class Reference
Chemical Structure
Detailed Description
A set of identical molecules.
Definition at line 27 of file tools/chemistry/Species.h.
#include <Species.h>
Public Member Functions
Species ()
Constructor.
void setId (int id)
Set the index for this species.
void initialize (int nAtom, int capacity)
Initialize memory for this species and set sizes.
void addAtom (Atom &atom)
Add an atom to the species.
void clear ()
Clear all molecules, reset to empty.
void begin (Iterator &iterator)
Initialize an iterator over molecules.
Molecule & molecule (int i)
Return a specific molecule by reference.
int id () const
Return integer id for this species.
int nAtom () const
Return number of atoms per molecule.
int size () const
Return number of molecules in this species (=maximum id + 1)
int capacity () const
Return maximum number of molecules in this species.
bool isValid () const
Return true if valid, or throw Exception.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
Friends
std::istream & operator>> (std::istream &in, Species &species)
istream extractor (>>) for a Species.
std::ostream & operator<< (std::ostream &out, const Species &species)
ostream inserter (<<) for a Species.
Constructor & Destructor Documentation
Tools::Species::Species ()
Constructor.
Definition at line 19 of file tools/chemistry/Species.cpp.
Member Function Documentation
void Tools::Species::setId (int id)
Set the index for this species.
Parameters:
id species index
Definition at line 27 of file tools/chemistry/Species.cpp.
References id().
void Tools::Species::initialize (int nAtom, int capacity)
Initialize memory for this species and set sizes.
Parameters:
nAtom number of atoms per molecule (exact)
capacity maximum number of molecules in species
Definition at line 30 of file tools/chemistry/Species.cpp.
References capacity(), initialize(), nAtom(), and UTIL_THROW.
Referenced by initialize(), and Tools::operator>>().
void Tools::Species::addAtom (Atom & atom)
Add an atom to the species.
Parameters:
atom Atom object to be added, must have AtomContext info.
Definition at line 99 of file tools/chemistry/Species.cpp.
References Tools::Atom::atomId, Tools::Atom::moleculeId, Util::DSArray< Data >::resize(), Util::DSArray< Data >::size(), Tools::Atom::speciesId, and UTIL_THROW.
Referenced by Tools::ConfigReader::addAtomsToSpecies().
void Tools::Species::clear ()
Clear all molecules, reset to empty.
Definition at line 85 of file tools/chemistry/Species.cpp.
References Util::Array< Data >::capacity(), Util::DSArray< Data >::resize(), and Util::DSArray< Data >::size().
Referenced by Tools::ConfigReader::addAtomsToSpecies(), and Tools::ConfigReader::setAtomContexts().
void Tools::Species::begin (Iterator & iterator)
Initialize an iterator over molecules.
Definition at line 132 of file tools/chemistry/Species.cpp.
References Util::DSArray< Data >::begin().
Referenced by Tools::AtomMSD::sample(), and Tools::AtomMSD::setup().
Molecule & Tools::Species::molecule (int i) [inline]
Return a specific molecule by reference.
Parameters:
i molecule index
Definition at line 180 of file tools/chemistry/Species.h.
int Tools::Species::id () const [inline]
Return integer id for this species.
Definition at line 186 of file tools/chemistry/Species.h.
Referenced by setId().
int Tools::Species::nAtom () const [inline]
Return number of atoms per molecule.
Definition at line 192 of file tools/chemistry/Species.h.
Referenced by initialize(), Tools::AtomMSD::readParameters(), and Tools::ConfigReader::setAtomContexts().
int Tools::Species::size () const [inline]
Return number of molecules in this species (=maximum id + 1)
Definition at line 198 of file tools/chemistry/Species.h.
Referenced by Tools::AtomMSD::sample(), and Tools::AtomMSD::setup().
int Tools::Species::capacity () const [inline]
Return maximum number of molecules in this species.
Definition at line 204 of file tools/chemistry/Species.h.
Referenced by initialize(), Tools::AtomMSD::readParameters(), and Tools::ConfigReader::setAtomContexts().
bool Tools::Species::isValid () const
Return true if valid, or throw Exception.
Definition at line 138 of file tools/chemistry/Species.cpp.
References Tools::Atom::atomId, Util::Array< Data >::capacity(), Util::DSArray< Data >::capacity(), Tools::Molecule::id(), Tools::Atom::moleculeId, Util::DSArray< Data >::size(), Tools::Atom::speciesId, and UTIL_THROW.
Referenced by Tools::ConfigReader::addAtomsToSpecies().
template<class Archive > void Tools::Species::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Definition at line 211 of file tools/chemistry/Species.h.
Friends And Related Function Documentation
std::istream& operator>> (std::istream & in, Species & species) [friend]
istream extractor (>>) for a Species.
Parameters:
in input stream
species Species to be read from stream
Returns:
modified input stream
Definition at line 200 of file tools/chemistry/Species.cpp.
std::ostream& operator<< (std::ostream & out, const Species & species) [friend]
ostream inserter (<<) for a Species.
Format on one line with no line break:
Parameters:
out output stream
species Species to be written to stream
Returns:
modified output stream
Definition at line 211 of file tools/chemistry/Species.cpp.
The documentation for this class was generated from the following files:
tools/chemistry/Species.h
tools/chemistry/Species.cpp