Simpatico: Util::DSArray< Data > Class Template Reference
Util::DSArray< Data > Class Template Reference
Util namespace » Container Templates » Object Arrays
Detailed Description
template<typename Data>
class Util::DSArray< Data >
Dynamically allocated array with variable logical size.
A DSArray < Data > is a wrapper for a dynamically allocated C array, with continuous elements and a logical size that may be less than or equal to its physical capacity. The logical size is the number of contiguous elements that have been added using the append() method.
Definition at line 30 of file DSArray.h.
#include <DSArray.h>
Public Member Functions
DSArray ()
Constructor.
DSArray (const DSArray< Data > &other)
Copy constructor.
DSArray< Data > & operator= (const DSArray< Data > &other)
Assignment, element by element.
virtual ~DSArray ()
Destructor.
void allocate (int capacity)
Allocates the underlying C array.
void append (const Data &data)
Append data to the end of the array.
void resize (int size)
Modify logical size without modifying data.
void clear ()
Set logical size to zero.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize a DSArray to/from an Archive.
void begin (ArrayIterator< Data > &iterator)
Set an ArrayIterator to the beginning of this Array.
void begin (ConstArrayIterator< Data > &iterator) const
Set a ConstArrayIterator to the beginning of this Array.
Data & operator[] (int i)
Mimic C array subscripting.
const Data & operator[] (int i) const
Mimic C array subscripting.
int capacity () const
Return physical capacity of array.
int size () const
Return logical size of this array (i.e., number of elements).
bool isAllocated () const
Return true if the DSArray has been allocated, false otherwise.
Protected Attributes
Data * data_
C array of Data elements.
int size_
Logical size of array (number of elements used).
int capacity_
Capacity (physical size) of underlying C array.
Constructor & Destructor Documentation
template<class Data > Util::DSArray< Data >::DSArray ()
Constructor.
Definition at line 170 of file DSArray.h.
template<class Data> Util::DSArray< Data >::DSArray (const DSArray< Data > & other)
Copy constructor.
Parameters
other the DSArray to be copied.
Definition at line 180 of file DSArray.h.
References Util::DSArray< Data >::capacity_, Util::DSArray< Data >::data_, Util::DSArray< Data >::isAllocated(), Util::DSArray< Data >::size_, and UTIL_THROW.
template<class Data > Util::DSArray< Data >::~DSArray () virtual
Destructor.
Definition at line 233 of file DSArray.h.
Member Function Documentation
template<class Data> DSArray< Data > & Util::DSArray< Data >::operator= (const DSArray< Data > & other)
Assignment, element by element.
Capacity of LHS must be either zero or equal that of RHS DSArray.
Parameters
other the RHS DSArray
Definition at line 204 of file DSArray.h.
References Util::DSArray< Data >::capacity_, Util::DSArray< Data >::isAllocated(), Util::DSArray< Data >::size_, and UTIL_THROW.
template<class Data > void Util::DSArray< Data >::allocate (int capacity)
Allocates the underlying C array.
Throw an exception if the DSArray has already been allocated - A DSArray can only be allocated once.
Parameters
capacity number of elements to allocate
Definition at line 247 of file DSArray.h.
References UTIL_THROW.
Referenced by McMd::McMuExchange::loadParameters(), McMd::McMuExchange::readParameters(), and Tools::Configuration::readParameters().
template<class Data> void Util::DSArray< Data >::append (const Data & data) inline
Append data to the end of the array.
Parameters
data Data to add to end of array.
Definition at line 345 of file DSArray.h.
References UTIL_THROW.
Referenced by McMd::McMuExchange::loadParameters(), and McMd::McMuExchange::readParameters().
template<class Data > void Util::DSArray< Data >::resize (int size) inline
Modify logical size without modifying data.
The size parameter must be non-negative and may not exceed the physical allocated capacity.
This function simply changes the logical size without modifying any elements of the underlying physical array. When the size increases, added elements are uninitialized.
Parameters
size new logical size, 0 <= size < capacity.
The size parameter must be non-negative and may not exceed the capacity.
This function simply changes the logical size of without modifying any elements of the underlying physical array. If the size increases, added elements are uninitialized.
Parameters
size new logical size, 0 <= size < capacity.
Definition at line 367 of file DSArray.h.
template<class Data > void Util::DSArray< Data >::clear () inline
Set logical size to zero.
Definition at line 374 of file DSArray.h.
Referenced by Tools::Configuration::clear().
template<class Data > template<class Archive > void Util::DSArray< Data >::serialize (Archive & ar, const unsigned int version)
Serialize a DSArray to/from an Archive.
Parameters
ar archive
version archive version id
Definition at line 265 of file DSArray.h.
References UTIL_THROW.
template<class Data> void Util::DSArray< Data >::begin (ArrayIterator< Data > & iterator) inline
Set an ArrayIterator to the beginning of this Array.
Parameters
iterator ArrayIterator, initialized on output.
Definition at line 302 of file DSArray.h.
References Util::ArrayIterator< Data >::setCurrent(), and Util::ArrayIterator< Data >::setEnd().
Referenced by McMd::MdPairEnergyCoefficients::sample().
template<class Data> void Util::DSArray< Data >::begin (ConstArrayIterator< Data > & iterator) const inline
Set a ConstArrayIterator to the beginning of this Array.
Parameters
iterator ConstArrayIterator, initialized on output.
Definition at line 313 of file DSArray.h.
References Util::ConstArrayIterator< Data >::setCurrent(), and Util::ConstArrayIterator< Data >::setEnd().
template<class Data > Data & Util::DSArray< Data >::operator[] (int i) inline
Mimic C array subscripting.
Parameters
i array index
Returns
reference to element i
Definition at line 323 of file DSArray.h.
template<class Data > const Data & Util::DSArray< Data >::operator[] (int i) const inline
Mimic C array subscripting.
Parameters
i array index
Returns
const reference to element i
Definition at line 334 of file DSArray.h.
template<class Data > int Util::DSArray< Data >::capacity () const inline
Return physical capacity of array.
Definition at line 381 of file DSArray.h.
template<class Data > int Util::DSArray< Data >::size () const inline
Return logical size of this array (i.e., number of elements).
Definition at line 388 of file DSArray.h.
Referenced by McMd::McMuExchange::sample().
template<class Data > bool Util::DSArray< Data >::isAllocated () const inline
Return true if the DSArray has been allocated, false otherwise.
Definition at line 395 of file DSArray.h.
Referenced by Util::DSArray< Data >::DSArray(), and Util::DSArray< Data >::operator=().
Member Data Documentation
template<typename Data> Data* Util::DSArray< Data >::data_ protected
C array of Data elements.
Definition at line 154 of file DSArray.h.
Referenced by Util::DSArray< Data >::DSArray().
template<typename Data> int Util::DSArray< Data >::size_ protected
Logical size of array (number of elements used).
Definition at line 157 of file DSArray.h.
Referenced by Util::DSArray< Data >::DSArray(), and Util::DSArray< Data >::operator=().
template<typename Data> int Util::DSArray< Data >::capacity_ protected
Capacity (physical size) of underlying C array.
Definition at line 160 of file DSArray.h.
Referenced by Util::DSArray< Data >::DSArray(), and Util::DSArray< Data >::operator=().
The documentation for this class was generated from the following file:
DSArray.h