Simpatico: Tools::Processor Class Reference
Tools::Processor Class Reference
Tools namespace » Storage
Detailed Description
A post-processor for analyzing outputs of MD simulations.
Definition at line 30 of file Processor.h.
#include <Processor.h>
Public Member Functions
Processor ()
Constructor.
~Processor ()
Destructor.
Initialization
void setOptions (int argc, char *const *argv)
Process command line options.
void readParam ()
Read parameter file specified in command line.
void readParam (const char *filename)
Open, read, and close parameter file.
void readParameters (std::istream &in)
Read parameters.
void readCommands ()
Read command file specified in command line.
void readCommands (std::istream &in)
Read and execute commands from a command file.
ConfigReader Interface
void setConfigReader (const std::string &configReaderName)
Set ConfigReader style (creates a ConfigReader).
ConfigReader & configReader ()
Return the current ConfigReader (create default if necessary).
void readConfig (std::ifstream &in)
Read a single configuration file.
void readConfig (const std::string &filename)
Open, read and close a configuration file.
void analyzeConfigs (const std::string &baseFileName, int min, int max, int interval=1)
Read and analyze a sequence of numbered configuration files.
ConfigWriter Interface
void setConfigWriter (const std::string &configWriterName)
Set ConfigWriter style (creates a ConfigWriter).
ConfigWriter & configWriter ()
Return the current ConfigWriter (create default if necessary).
void writeConfig (std::ofstream &in)
Write a single configuration file.
void writeConfig (const std::string &filename)
Open, write and close a configuration file.
Trajectory File Interface
void setTrajectoryReader (const std::string &trajectoryStyle)
Set TrajectoryReader style (creates a TrajectoryReader).
TrajectoryReader & trajectoryReader ()
Return the current TrajectoryReader (create default if necessary).
void analyzeTrajectory (const std::string &filename)
Open, read, analyze and close a single trajectory file.
Miscellaneous functions
FileMaster & fileMaster ()
Return FileMaster if active, or throw Exception.
Public Member Functions inherited from Tools::Configuration
Configuration ()
Constructor.
~Configuration ()
Destructor.
void readParam (const char *filename)
Open, read, and close parameter file.
void readParameters (std::istream &in)
Read parameters.
void clear ()
Clear all atoms and groups.
Boundary & boundary ()
Get the Boundary by non-const reference.
AtomStorage & atoms ()
Get the AtomStorage.
GroupStorage< 2 > & bonds ()
Get the Bond storage.
GroupStorage< 3 > & angles ()
Get the Angle storage.
GroupStorage< 4 > & dihedrals ()
Get the Dihedral storage.
GroupStorage< 4 > & impropers ()
Get the Improper dihedral storage.
int nSpecies () const
Number of species.
Species & species (int i)
Get a particular species identified by index.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Constructor & Destructor Documentation
Tools::Processor::Processor ()
Constructor.
Definition at line 25 of file Processor.cpp.
References Util::ParamComposite::setClassName().
Tools::Processor::~Processor ()
Destructor.
Definition at line 37 of file Processor.cpp.
Member Function Documentation
void Tools::Processor::setOptions (int argc, char *const * argv)
Process command line options.
Parameters
argc number of arguments
argv array of argument C-strings
Definition at line 50 of file Processor.cpp.
References Util::Log::file(), Util::FileMaster::setCommandFileName(), Util::ParamComponent::setEcho(), and Util::FileMaster::setParamFileName().
void Tools::Processor::readParam ()
Read parameter file specified in command line.
Definition at line 76 of file Processor.cpp.
References Util::FileMaster::paramFile(), Util::FileMaster::paramFileName(), and UTIL_THROW.
Referenced by readParam().
void Tools::Processor::readParam (const char * filename)
Open, read, and close parameter file.
Parameters
filename input parameter file name
Definition at line 87 of file Processor.cpp.
References readParam().
void Tools::Processor::readParameters (std::istream & in) virtual
Read parameters.
Parameters
in input command file stream
Reimplemented from Util::ParamComposite.
Definition at line 98 of file Processor.cpp.
References Util::ParamComposite::readParamComposite(), Util::ParamComposite::readParamCompositeOptional(), and Tools::Configuration::readParameters().
void Tools::Processor::readCommands ()
Read command file specified in command line.
Definition at line 108 of file Processor.cpp.
References Util::FileMaster::commandFile(), and Util::FileMaster::commandFileName().
void Tools::Processor::readCommands (std::istream & in)
Read and execute commands from a command file.
Parameters
in input command file stream
Definition at line 121 of file Processor.cpp.
References analyzeTrajectory(), configReader(), configWriter(), Util::Log::file(), Util::FileMaster::openInputFile(), Util::FileMaster::openOutputFile(), Tools::ConfigWriter::readAuxiliaryFile(), Tools::ConfigReader::readAuxiliaryFile(), Tools::ConfigReader::readConfig(), setConfigReader(), setConfigWriter(), setTrajectoryReader(), and Tools::ConfigWriter::writeConfig().
void Tools::Processor::setConfigReader (const std::string & configReaderName)
Set ConfigReader style (creates a ConfigReader).
Parameters
configReaderName identifier for ConfigReader subclass
Definition at line 211 of file Processor.cpp.
References Tools::ConfigReaderFactory::factory(), and UTIL_THROW.
Referenced by readCommands().
ConfigReader & Tools::Processor::configReader ()
Return the current ConfigReader (create default if necessary).
Definition at line 227 of file Processor.cpp.
Referenced by readCommands(), and readConfig().
void Tools::Processor::readConfig (std::ifstream & in)
Read a single configuration file.
Definition at line 239 of file Processor.cpp.
References Tools::Configuration::clear(), configReader(), and Tools::ConfigReader::readConfig().
Referenced by analyzeConfigs(), and readConfig().
void Tools::Processor::readConfig (const std::string & filename)
Open, read and close a configuration file.
Definition at line 248 of file Processor.cpp.
References readConfig().
void Tools::Processor::analyzeConfigs (const std::string & baseFileName, int min, int max, int interval = 1)
Read and analyze a sequence of numbered configuration files.
This function reads and analyzes a sequence of configuration files that were generated by running a previous simulation. The function reads files with names of the form inputPrefix() + n for integer suffixes min <= n <= max with subsequent values differing by the specified interval.
Parameters
baseFileName root name for dump files (without int suffix)
min integer suffix of first configuration file name
max integer suffix of last configuration file name
interval interval between subsequent timestep values
Definition at line 259 of file Processor.cpp.
References Tools::Configuration::clear(), Util::Log::file(), Tools::AnalyzerManager::output(), readConfig(), Tools::AnalyzerManager::sample(), Tools::AnalyzerManager::setup(), and UTIL_THROW.
void Tools::Processor::setConfigWriter (const std::string & configWriterName)
Set ConfigWriter style (creates a ConfigWriter).
Parameters
configWriterName identifier for ConfigWriter subclass
Definition at line 327 of file Processor.cpp.
References Tools::ConfigWriterFactory::factory(), and UTIL_THROW.
Referenced by readCommands().
ConfigWriter & Tools::Processor::configWriter ()
Return the current ConfigWriter (create default if necessary).
Definition at line 341 of file Processor.cpp.
Referenced by readCommands(), and writeConfig().
void Tools::Processor::writeConfig (std::ofstream & in)
Write a single configuration file.
Definition at line 353 of file Processor.cpp.
References configWriter(), and Tools::ConfigWriter::writeConfig().
Referenced by writeConfig().
void Tools::Processor::writeConfig (const std::string & filename)
Open, write and close a configuration file.
Definition at line 359 of file Processor.cpp.
References writeConfig().
void Tools::Processor::setTrajectoryReader (const std::string & trajectoryStyle)
Set TrajectoryReader style (creates a TrajectoryReader).
Parameters
trajectoryStyle TrajectoryReader subclass identifier
Definition at line 372 of file Processor.cpp.
References Tools::TrajectoryReaderFactory::factory(), and UTIL_THROW.
Referenced by readCommands().
TrajectoryReader & Tools::Processor::trajectoryReader ()
Return the current TrajectoryReader (create default if necessary).
Definition at line 387 of file Processor.cpp.
Referenced by analyzeTrajectory().
void Tools::Processor::analyzeTrajectory (const std::string & filename)
Open, read, analyze and close a single trajectory file.
Parameters
filename name of trajectory file.
Definition at line 399 of file Processor.cpp.
References Util::Log::file(), Util::FileMaster::openInputFile(), Tools::AnalyzerManager::output(), Tools::TrajectoryReader::readFrame(), Tools::TrajectoryReader::readHeader(), Tools::AnalyzerManager::sample(), Tools::AnalyzerManager::setup(), trajectoryReader(), and UTIL_THROW.
Referenced by readCommands().
FileMaster & Tools::Processor::fileMaster ()
Return FileMaster if active, or throw Exception.
Definition at line 442 of file Processor.cpp.
The documentation for this class was generated from the following files:
Processor.h
Processor.cpp