Simpatico: DdMd::ConfigIo Class Reference
DdMd::ConfigIo Class Reference abstract
ConfigIos
Detailed Description
Abstract reader/writer for configuration files.
Each concrete subclass of ConfigIo implements a specific file format by implementing the pure virtual readConfig and writeConfig methods.
Definition at line 43 of file ddMd/configIos/ConfigIo.h.
#include <ConfigIo.h>
Public Member Functions
ConfigIo ()
Default constructor.
ConfigIo (Simulation &simulation)
Constructor.
virtual ~ConfigIo ()
Destructor.
void associate (Domain &domain, Boundary &boundary, AtomStorage &atomStorage, BondStorage &bondStorage, AngleStorage &angleStorage, DihedralStorage &dihedralStorage, Buffer &buffer)
Associate with related objects.
virtual void initialize (int atomCacheCapacity=100, int bondCacheCapacity=100, int angleCacheCapacity=100, int dihedralCacheCapacity=100)
Set cache sizes and allocate memory.
virtual void readParameters (std::istream &in)
Read cache size and allocate memory.
virtual void load (Serializable::IArchive &ar)
Load internal state of configIo (not configuration) from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state of ConfigIo (not configuration) to an archive.
virtual void readConfig (std::ifstream &file, MaskPolicy maskPolicy)=0
Read a configuration file.
virtual void writeConfig (std::ofstream &file)=0
Write configuration file.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
void setAtomMasks ()
Set Mask data on all atoms.
Domain & domain ()
Get the Domain by reference.
Boundary & boundary ()
Get Boundary by reference.
AtomStorage & atomStorage ()
Get AtomStorage by reference.
AtomDistributor & atomDistributor ()
Get the AtomDistributor by reference.
AtomCollector & atomCollector ()
Get the AtomCollector by reference.
BondStorage & bondStorage ()
Get BondStorage by reference.
GroupDistributor< 2 > & bondDistributor ()
Get the AtomDistributor by reference.
GroupCollector< 2 > & bondCollector ()
Get the bond collector by reference.
AngleStorage & angleStorage ()
Get AngleStorage by reference.
GroupDistributor< 3 > & angleDistributor ()
Get the angle distributor by reference.
GroupCollector< 3 > & angleCollector ()
Get the angle collector by reference.
DihedralStorage & dihedralStorage ()
Get DihedralStorage by reference.
GroupDistributor< 4 > & dihedralDistributor ()
Get the dihedral distributor by reference.
GroupCollector< 4 > & dihedralCollector ()
Get the dihedral collector by reference.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Constructor & Destructor Documentation
DdMd::ConfigIo::ConfigIo ()
Default constructor.
Definition at line 47 of file ddMd/configIos/ConfigIo.cpp.
References Util::ParamComposite::setClassName().
DdMd::ConfigIo::ConfigIo (Simulation & simulation)
Constructor.
Parameters
simulation parent Simulation object.
Definition at line 75 of file ddMd/configIos/ConfigIo.cpp.
References DdMd::Simulation::angleStorage(), associate(), DdMd::Simulation::atomStorage(), DdMd::Simulation::bondStorage(), DdMd::Simulation::boundary(), DdMd::Simulation::buffer(), DdMd::Simulation::dihedralStorage(), DdMd::Simulation::domain(), and Util::ParamComposite::setClassName().
DdMd::ConfigIo::~ConfigIo () virtual
Destructor.
Definition at line 119 of file ddMd/configIos/ConfigIo.cpp.
Member Function Documentation
void DdMd::ConfigIo::associate (Domain & domain, Boundary & boundary, AtomStorage & atomStorage, BondStorage & bondStorage, AngleStorage & angleStorage, DihedralStorage & dihedralStorage, Buffer & buffer)
Associate with related objects.
Required iff instantiated with default constructor.
Definition at line 125 of file ddMd/configIos/ConfigIo.cpp.
References angleStorage(), DdMd::AtomCollector::associate(), DdMd::GroupCollector< N >::associate(), DdMd::AtomDistributor::associate(), DdMd::GroupDistributor< N >::associate(), atomStorage(), bondStorage(), boundary(), dihedralStorage(), and domain().
Referenced by ConfigIo().
void DdMd::ConfigIo::initialize (int atomCacheCapacity = 100, int bondCacheCapacity = 100, int angleCacheCapacity = 100, int dihedralCacheCapacity = 100) virtual
Set cache sizes and allocate memory.
Parameters
atomCacheCapacity size of internal atom cache.
bondCacheCapacity size of internal bond cache.
angleCacheCapacity size of internal angle cache.
dihedralCacheCapacity size of internal dihedral cache.
Definition at line 169 of file ddMd/configIos/ConfigIo.cpp.
References DdMd::AtomCollector::allocate(), DdMd::GroupCollector< N >::allocate(), DdMd::AtomDistributor::initialize(), and DdMd::GroupDistributor< N >::initialize().
Referenced by DdMd::Simulation::setConfigIo().
void DdMd::ConfigIo::readParameters (std::istream & in) virtual
Read cache size and allocate memory.
Reimplemented from Util::ParamComposite.
Definition at line 204 of file ddMd/configIos/ConfigIo.cpp.
References DdMd::AtomCollector::allocate(), DdMd::GroupCollector< N >::allocate(), DdMd::AtomDistributor::initialize(), and DdMd::GroupDistributor< N >::initialize().
void DdMd::ConfigIo::load (Serializable::IArchive & ar) virtual
Load internal state of configIo (not configuration) from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 229 of file ddMd/configIos/ConfigIo.cpp.
References DdMd::AtomCollector::allocate(), DdMd::GroupCollector< N >::allocate(), DdMd::AtomDistributor::initialize(), DdMd::GroupDistributor< N >::initialize(), and Util::MpiLoader< IArchive >::load().
void DdMd::ConfigIo::save (Serializable::OArchive & ar) virtual
Save internal state of ConfigIo (not configuration) to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 257 of file ddMd/configIos/ConfigIo.cpp.
virtual void DdMd::ConfigIo::readConfig (std::ifstream & file, MaskPolicy maskPolicy) pure virtual
Read a configuration file.
This method reads a configuration file from the master processor, and distributes atoms and groups among the processors. It should be implemented using an AtomDistributor object. When Atoms are added to the AtomDistributor on the master processor, the atomic coordinates should be in generalized / scaled coordinates, such that 0 <= position[i] < 1.0 for i =0,..,2. Atomic positions that lie slightly outside the domain [0.0 ,1.0] will automatically be shifted into this domain by the AtomDistributor::addAtom() method before being assigned to processors or distributed.
Upon entry (preconditions):
The configuration file must be open for reading.
The AtomStorage must be set for generalized / scaled coordinates.
Upon return (postconditions):
Each processor owns all atoms in its domain, and no others. Each atom is owned by one and only one processor.
Each atom position is in the primary simulation cell.
Atom coordinates are in scaled form, between 0.0 and 1.0.
Each processor owns every group that contains one or more of the atoms that it owns, and no empty groups. A group may be ``owned" by more than one processor.
All Atom Mask data is set correctly for specified maskPolicy.
There are no ghost atoms on any processor.
Parameters
file input file stream (must be open on master).
maskPolicy MaskPolicy to be used in setting atom masks
Implemented in DdMd::DdMdOrderedConfigIo, DdMd::DdMdConfigIo, DdMd::LammpsConfigIo, and DdMd::SerializeConfigIo.
virtual void DdMd::ConfigIo::writeConfig (std::ofstream & file) pure virtual
Write configuration file.
This function writes a file on the master processor by collecting atom and group data from all processors. Implementations must work correctly when atom positions stored in either Cartesian or scaled / generalized coordinates on entry and exit, by testing AtomStorage::isCartesian(), and converting coordinate systems as needed before writing each position file. Atomic positions may be written in Cartesian or generalized coordinates, depending on the file format, but the same convention should be used in writeConfig() and readConfig() in each class. Some file formats may allow atom and groups to be written in arbitrary order. Atomic positions may be written "as is", and may lie slightly outside the primary cell, because they will be shifted back by the AtomDistributor used to implement readConfig(). This function may not modify actual Atom positions or change the AtomStorage isCartesian() flag.
Usage:
When used within Simulation::readCommands() to implement the WRITE_CONFIG command, atomic coordinates will be scaled / generalized on both entry and exit.
When used within an Analyzer, to dump configuration files, atomic coordinates will be Cartesian on entry and exit.
Parameters
file output file stream (must be open on master processor).
Implemented in DdMd::DdMdOrderedConfigIo, DdMd::DdMdConfigIo, DdMd::LammpsConfigIo, and DdMd::SerializeConfigIo.
void DdMd::ConfigIo::setAtomMasks () protected
Set Mask data on all atoms.
Definition at line 337 of file ddMd/configIos/ConfigIo.cpp.
References DdMd::Mask::append(), atomStorage(), DdMd::GroupStorage< N >::begin(), DdMd::AtomStorage::begin(), bondStorage(), DdMd::AtomMap::find(), DdMd::AtomStorage::map(), DdMd::Atom::mask(), Util::PArrayIterator< Group< N > >::notEnd(), and Util::PArrayIterator< Data >::notEnd().
Referenced by DdMd::SerializeConfigIo::loadConfig(), and DdMd::LammpsConfigIo::readConfig().
Domain & DdMd::ConfigIo::domain () inline protected
Get the Domain by reference.
Definition at line 341 of file ddMd/configIos/ConfigIo.h.
Referenced by associate(), DdMd::SerializeConfigIo::loadConfig(), DdMd::SerializeConfigIo::readConfig(), DdMd::LammpsConfigIo::readConfig(), DdMd::SerializeConfigIo::saveConfig(), DdMd::SerializeConfigIo::writeConfig(), and DdMd::LammpsConfigIo::writeConfig().
Boundary & DdMd::ConfigIo::boundary () inline protected
Get Boundary by reference.
Definition at line 344 of file ddMd/configIos/ConfigIo.h.
Referenced by associate(), DdMd::SerializeConfigIo::loadConfig(), DdMd::LammpsConfigIo::readConfig(), DdMd::SerializeConfigIo::saveConfig(), and DdMd::LammpsConfigIo::writeConfig().
AtomStorage & DdMd::ConfigIo::atomStorage () inline protected
Get AtomStorage by reference.
Definition at line 347 of file ddMd/configIos/ConfigIo.h.
Referenced by associate(), DdMd::SerializeConfigIo::loadConfig(), DdMd::LammpsConfigIo::readConfig(), DdMd::SerializeConfigIo::saveConfig(), setAtomMasks(), and DdMd::LammpsConfigIo::writeConfig().
AtomDistributor & DdMd::ConfigIo::atomDistributor () inline protected
Get the AtomDistributor by reference.
Definition at line 350 of file ddMd/configIos/ConfigIo.h.
Referenced by DdMd::SerializeConfigIo::loadConfig(), and DdMd::LammpsConfigIo::readConfig().
AtomCollector & DdMd::ConfigIo::atomCollector () inline protected
Get the AtomCollector by reference.
Definition at line 353 of file ddMd/configIos/ConfigIo.h.
Referenced by DdMd::SerializeConfigIo::saveConfig(), and DdMd::LammpsConfigIo::writeConfig().
BondStorage & DdMd::ConfigIo::bondStorage () inline protected
Get BondStorage by reference.
Definition at line 357 of file ddMd/configIos/ConfigIo.h.
Referenced by associate(), DdMd::SerializeConfigIo::loadConfig(), DdMd::LammpsConfigIo::readConfig(), DdMd::SerializeConfigIo::saveConfig(), setAtomMasks(), and DdMd::LammpsConfigIo::writeConfig().
GroupDistributor< 2 > & DdMd::ConfigIo::bondDistributor () inline protected
Get the AtomDistributor by reference.
Definition at line 360 of file ddMd/configIos/ConfigIo.h.
Referenced by DdMd::SerializeConfigIo::loadConfig(), and DdMd::LammpsConfigIo::readConfig().
GroupCollector< 2 > & DdMd::ConfigIo::bondCollector () inline protected
Get the bond collector by reference.
Definition at line 363 of file ddMd/configIos/ConfigIo.h.
Referenced by DdMd::SerializeConfigIo::saveConfig(), and DdMd::LammpsConfigIo::writeConfig().
AngleStorage & DdMd::ConfigIo::angleStorage () inline protected
Get AngleStorage by reference.
Definition at line 368 of file ddMd/configIos/ConfigIo.h.
Referenced by associate(), DdMd::SerializeConfigIo::loadConfig(), DdMd::SerializeConfigIo::saveConfig(), and DdMd::LammpsConfigIo::writeConfig().
GroupDistributor< 3 > & DdMd::ConfigIo::angleDistributor () inline protected
Get the angle distributor by reference.
Definition at line 371 of file ddMd/configIos/ConfigIo.h.
Referenced by DdMd::SerializeConfigIo::loadConfig().
GroupCollector< 3 > & DdMd::ConfigIo::angleCollector () inline protected
Get the angle collector by reference.
Definition at line 374 of file ddMd/configIos/ConfigIo.h.
Referenced by DdMd::SerializeConfigIo::saveConfig(), and DdMd::LammpsConfigIo::writeConfig().
DihedralStorage & DdMd::ConfigIo::dihedralStorage () inline protected
Get DihedralStorage by reference.
Definition at line 379 of file ddMd/configIos/ConfigIo.h.
Referenced by associate(), DdMd::SerializeConfigIo::loadConfig(), DdMd::SerializeConfigIo::saveConfig(), and DdMd::LammpsConfigIo::writeConfig().
GroupDistributor< 4 > & DdMd::ConfigIo::dihedralDistributor () inline protected
Get the dihedral distributor by reference.
Definition at line 382 of file ddMd/configIos/ConfigIo.h.
Referenced by DdMd::SerializeConfigIo::loadConfig().
GroupCollector< 4 > & DdMd::ConfigIo::dihedralCollector () inline protected
Get the dihedral collector by reference.
Definition at line 385 of file ddMd/configIos/ConfigIo.h.
Referenced by DdMd::SerializeConfigIo::saveConfig(), and DdMd::LammpsConfigIo::writeConfig().
The documentation for this class was generated from the following files:
ddMd/configIos/ConfigIo.h
ddMd/configIos/ConfigIo.cpp