Simpatico: DdMd::StressAutoCorr Class Reference
DdMd::StressAutoCorr Class Reference
Analyzers
Detailed Description
Periodically write (tensor) StressTensor to file.
Definition at line 27 of file ddMd/analyzers/StressAutoCorr.h.
#include <StressAutoCorr.h>
Public Member Functions
StressAutoCorr (Simulation &simulation)
Constructor.
virtual ~StressAutoCorr ()
Destructor.
virtual void readParameters (std::istream &in)
Read dumpPrefix and interval.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void clear ()
Clear nSample counter.
virtual void setup ()
Setup accumulator!
virtual void sample (long iStep)
Sample virial stress to accumulators.
virtual void output ()
Dump configuration to file.
Constructor & Destructor Documentation
DdMd::StressAutoCorr::StressAutoCorr (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object.
Definition at line 24 of file StressAutoCorr.cpp.
References Util::ParamComposite::setClassName().
virtual DdMd::StressAutoCorr::~StressAutoCorr () [inline, virtual]
Destructor.
Definition at line 42 of file ddMd/analyzers/StressAutoCorr.h.
Member Function Documentation
void DdMd::StressAutoCorr::readParameters (std::istream & in) [virtual]
Read dumpPrefix and interval.
Parameters:
in input parameter file
Reimplemented from Util::ParamComposite.
Definition at line 35 of file StressAutoCorr.cpp.
References DdMd::Simulation::domain(), DdMd::Domain::isMaster(), DdMd::Analyzer::readInterval(), DdMd::Analyzer::readOutputFileName(), Util::AutoCorrStage< Data, Product >::setParam(), and DdMd::Analyzer::simulation().
void DdMd::StressAutoCorr::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from DdMd::Analyzer.
Definition at line 51 of file StressAutoCorr.cpp.
References DdMd::Analyzer::loadInterval(), DdMd::Analyzer::loadOutputFileName(), Util::ParamComposite::loadParameter(), and DdMd::Analyzer::simulation().
void DdMd::StressAutoCorr::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from DdMd::Analyzer.
Definition at line 68 of file StressAutoCorr.cpp.
References DdMd::Analyzer::saveInterval(), DdMd::Analyzer::saveOutputFileName(), DdMd::Analyzer::simulation(), and UTIL_THROW.
void DdMd::StressAutoCorr::clear () [virtual]
Clear nSample counter.
Reimplemented from DdMd::Analyzer.
Definition at line 84 of file StressAutoCorr.cpp.
References Util::AutoCorrStage< Data, Product >::clear(), DdMd::Analyzer::simulation(), and UTIL_THROW.
Referenced by setup().
void DdMd::StressAutoCorr::setup () [virtual]
Setup accumulator!
Reimplemented from DdMd::Analyzer.
Definition at line 101 of file StressAutoCorr.cpp.
References clear(), and UTIL_THROW.
void DdMd::StressAutoCorr::sample (long iStep) [virtual]
Sample virial stress to accumulators.
Parameters:
iStep MD step index
Implements DdMd::Analyzer.
Definition at line 112 of file StressAutoCorr.cpp.
References Util::Tensor::add(), DdMd::Simulation::boundary(), DdMd::Simulation::computeKineticStress(), DdMd::Simulation::computeVirialStress(), Util::Dimension, DdMd::Simulation::domain(), DdMd::Analyzer::isAtInterval(), DdMd::Domain::isMaster(), DdMd::Simulation::kineticStress(), Util::AutoCorrStage< Data, Product >::sample(), DdMd::Analyzer::simulation(), UTIL_THROW, DdMd::Simulation::virialStress(), and Util::OrthorhombicBoundary::volume().
void DdMd::StressAutoCorr::output () [virtual]
Dump configuration to file.
Reimplemented from DdMd::Analyzer.
Definition at line 154 of file StressAutoCorr.cpp.
References Util::AutoCorrStage< Data, Product >::bufferCapacity(), DdMd::Simulation::fileMaster(), Util::AutoCorrStage< Data, Product >::nSample(), Util::FileMaster::openOutputFile(), Util::AutoCorrStage< Data, Product >::output(), DdMd::Analyzer::outputFileName(), DdMd::Analyzer::simulation(), UTIL_THROW, and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
ddMd/analyzers/StressAutoCorr.h
StressAutoCorr.cpp