Simpatico: SpAn::AtomStorage Class Reference
SpAn::AtomStorage Class Reference
Storage
Detailed Description
Container for a set of atoms.
Definition at line 29 of file spAn/storage/AtomStorage.h.
#include <AtomStorage.h>
Public Member Functions
AtomStorage ()
Constructor.
~AtomStorage ()
Destructor.
void allocate (int capacity)
Allocate and initialize memory.
Atom * newPtr ()
Return pointer to location for new atom.
void add ()
Finalize addition of atom (allows lookup by id).
void clear ()
Clear all atoms and groups.
Atom * ptr (int id)
Get a pointer to an atom by global id.
void begin (Iterator &iter)
Initialize an iterator for atoms.
int capacity () const
Get atom capacity (maximum id + 1).
int size () const
Get number of atoms.
Constructor & Destructor Documentation
SpAn::AtomStorage::AtomStorage ()
Constructor.
Definition at line 19 of file spAn/storage/AtomStorage.cpp.
SpAn::AtomStorage::~AtomStorage ()
Destructor.
Definition at line 26 of file spAn/storage/AtomStorage.cpp.
Member Function Documentation
void SpAn::AtomStorage::allocate (int capacity)
Allocate and initialize memory.
Parameters:
capacity Maximum number of atoms
Definition at line 32 of file spAn/storage/AtomStorage.cpp.
References Util::DSArray< Data >::allocate(), Util::DArray< Data >::allocate(), and clear().
Referenced by SpAn::Configuration::readParameters().
Atom * SpAn::AtomStorage::newPtr ()
Return pointer to location for new atom.
Returns:
pointer to location of new atom
Definition at line 42 of file spAn/storage/AtomStorage.cpp.
References Util::DSArray< Data >::resize(), size(), Util::DSArray< Data >::size(), and UTIL_THROW.
Referenced by SpAn::DdMdConfigIo::readConfig().
void SpAn::AtomStorage::add ()
Finalize addition of atom (allows lookup by id).
Definition at line 56 of file spAn/storage/AtomStorage.cpp.
References SpAn::Atom::id, and UTIL_THROW.
Referenced by SpAn::DdMdConfigIo::readConfig().
void SpAn::AtomStorage::clear ()
Clear all atoms and groups.
Definition at line 69 of file spAn/storage/AtomStorage.cpp.
References Util::Array< Data >::capacity(), capacity(), and Util::DSArray< Data >::clear().
Referenced by allocate(), and SpAn::Configuration::clear().
Atom * SpAn::AtomStorage::ptr (int id) [inline]
Get a pointer to an atom by global id.
Definition at line 121 of file spAn/storage/AtomStorage.h.
void SpAn::AtomStorage::begin (AtomStorage::Iterator & iter) [inline]
Initialize an iterator for atoms.
Definition at line 128 of file spAn/storage/AtomStorage.h.
Referenced by SpAn::DdMdConfigIo::readConfig(), and SpAn::DdMdConfigIo::writeConfig().
int SpAn::AtomStorage::capacity () const [inline]
Get atom capacity (maximum id + 1).
Definition at line 115 of file spAn/storage/AtomStorage.h.
Referenced by clear(), and SpAn::DdMdConfigIo::readConfig().
int SpAn::AtomStorage::size () const [inline]
Get number of atoms.
Definition at line 108 of file spAn/storage/AtomStorage.h.
Referenced by newPtr(), and SpAn::DdMdConfigIo::writeConfig().
The documentation for this class was generated from the following files:
spAn/storage/AtomStorage.h
spAn/storage/AtomStorage.cpp