Simpatico: DdMd::Potential Class Reference
DdMd::Potential Class Reference abstract
DdMd namespace » Potential Energies
Detailed Description
A Potential represents a potential energy contribution.
A Potential provides methods to calculate potential energy, and associated atomic forces and stress.
Definition at line 28 of file Potential.h.
#include <Potential.h>
Public Member Functions
Potential ()
Constructor.
virtual ~Potential ()
Destructor.
void setReverseUpdateFlag (bool reverseUpdateFlag)
Set flag to identify if reverse communication is enabled.
bool reverseUpdateFlag () const
Get flag to identify if reverse communication is enabled.
Total Energy, Force and Stress
virtual void computeForces ()=0
Add force contributions to all atomic forces.
virtual void computeEnergy (MPI::Intracomm &communicator)=0
Compute potential energy on all processors.
double energy () const
Return the total potential, from all processors.
void unsetEnergy ()
Mark the energy as unknown (nullify).
bool isEnergySet () const
Is the energy set (known)?
virtual void computeStress (MPI::Intracomm &communicator)
Compute stress on all processors.
virtual void computeForcesAndStress (MPI::Intracomm &communicator)
Compute forces and stress for all processors.
Tensor stress () const
Return the stress tensor.
double pressure () const
Return the pressure.
void unsetStress ()
Mark the stress as unknown (nullify).
bool isStressSet () const
Is the stress set (known)?
virtual bool isValid (MPI::Intracomm &communicator) const
Is the potential in a valid internal state?
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void readParameters (std::istream &in)
Read the body of parameter block, without begin and end lines.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
void setEnergy (double energy)
Set a value for the total energy.
void setStress (const Tensor &stress)
Set a value for the total stress.
void incrementPairStress (const Vector &f, const Vector &dr, Tensor &stress) const
Add a pair contribution to the stress tensor.
void reduceEnergy (double localEnergy, MPI::Intracomm &communicator)
Add local energies from all processors, set energy on master.
void reduceStress (Tensor &localStress, MPI::Intracomm &communicator)
Add local stresses from all processors, set total on master.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Constructor & Destructor Documentation
DdMd::Potential::Potential ()
Constructor.
Definition at line 18 of file Potential.cpp.
References Util::ParamComposite::setClassName().
DdMd::Potential::~Potential () virtual
Destructor.
Definition at line 27 of file Potential.cpp.
Member Function Documentation
void DdMd::Potential::setReverseUpdateFlag (bool reverseUpdateFlag)
Set flag to identify if reverse communication is enabled.
Parameters
reverseUpdateFlag true if reverse communication is enabled.
Definition at line 33 of file Potential.cpp.
References reverseUpdateFlag().
bool DdMd::Potential::reverseUpdateFlag () const inline
Get flag to identify if reverse communication is enabled.
Definition at line 228 of file Potential.h.
Referenced by DdMd::PairPotential::buildPairList(), DdMd::PairPotentialImpl< Interaction >::computeEnergy(), DdMd::PairPotentialImpl< Interaction >::computeForcesAndStress(), DdMd::PairPotentialImpl< Interaction >::computePairEnergies(), DdMd::PairPotentialImpl< Interaction >::computeStress(), DdMd::PairPotential::nPair(), and setReverseUpdateFlag().
virtual void DdMd::Potential::computeForces () pure virtual
Add force contributions to all atomic forces.
Implemented in DdMd::PairPotentialImpl< Interaction >, DdMd::DihedralPotentialImpl< Interaction >, DdMd::ExternalPotentialImpl< Interaction >, DdMd::BondPotentialImpl< Interaction >, and DdMd::AnglePotentialImpl< Interaction >.
Referenced by DdMd::Integrator::computeForces(), and DdMd::Integrator::computeForcesAndVirial().
virtual void DdMd::Potential::computeEnergy (MPI::Intracomm & communicator) pure virtual
Compute potential energy on all processors.
This method must be called on all processors. The result is stored on the master processor, and may be retrieved by calling energy() on this processor.
Implemented in DdMd::PairPotentialImpl< Interaction >, DdMd::DihedralPotentialImpl< Interaction >, DdMd::ExternalPotentialImpl< Interaction >, DdMd::BondPotentialImpl< Interaction >, and DdMd::AnglePotentialImpl< Interaction >.
Referenced by DdMd::ExternalEnergyAnalyzer::compute().
double DdMd::Potential::energy () const
Return the total potential, from all processors.
This method should only be called on the master (rank 0) processor, after a previous call to computeEnergy.
Definition at line 39 of file Potential.cpp.
References Util::Setable< T >::value().
Referenced by DdMd::ExternalPotentialImpl< Interaction >::computeEnergy(), DdMd::PairPotentialImpl< Interaction >::computeEnergy(), DdMd::ExternalEnergyAverage::sample(), DdMd::LogEnergy::sample(), DdMd::OutputEnergy::sample(), DdMd::EnergyAnalyzer::sample(), and DdMd::ExternalEnergyAnalyzer::value().
void DdMd::Potential::unsetEnergy ()
Mark the energy as unknown (nullify).
This should be called whenever atom positions or boundary changes.
Definition at line 51 of file Potential.cpp.
References Util::Setable< T >::unset().
bool DdMd::Potential::isEnergySet () const
Is the energy set (known)?
Definition at line 57 of file Potential.cpp.
References Util::Setable< T >::isSet().
Referenced by DdMd::AnglePotentialImpl< Interaction >::computeEnergy(), DdMd::BondPotentialImpl< Interaction >::computeEnergy(), DdMd::DihedralPotentialImpl< Interaction >::computeEnergy(), and DdMd::PairPotentialImpl< Interaction >::computeEnergy().
virtual void DdMd::Potential::computeStress (MPI::Intracomm & communicator) inline virtual
Compute stress on all processors.
This method must be called on all processors. The result is stored on the master processor, and may be retrieved by calling stress() on this processor.
Reimplemented in DdMd::PairPotentialImpl< Interaction >, DdMd::DihedralPotentialImpl< Interaction >, DdMd::BondPotentialImpl< Interaction >, and DdMd::AnglePotentialImpl< Interaction >.
Definition at line 104 of file Potential.h.
void DdMd::Potential::computeForcesAndStress (MPI::Intracomm & communicator) virtual
Compute forces and stress for all processors.
Call on all processors. The default implementation just calls computeForces() and computeStress() methods. Subclasses should combine into a single loop.
Reimplemented in DdMd::PairPotentialImpl< Interaction >, and DdMd::BondPotentialImpl< Interaction >.
Definition at line 103 of file Potential.cpp.
Referenced by DdMd::Integrator::computeForcesAndVirial().
Tensor DdMd::Potential::stress () const
Return the stress tensor.
This method should only be called on the master (rank 0) processor, after a previous call to computeStress.
Definition at line 63 of file Potential.cpp.
double DdMd::Potential::pressure () const
Return the pressure.
This method should only be called on the master (rank 0) processor, after a previous call to computeStress.
Definition at line 69 of file Potential.cpp.
References Util::Dimension.
void DdMd::Potential::unsetStress ()
Mark the stress as unknown (nullify).
This should be called whenever atom positions or boundary changes.
Definition at line 88 of file Potential.cpp.
bool DdMd::Potential::isStressSet () const
Is the stress set (known)?
Definition at line 94 of file Potential.cpp.
Referenced by DdMd::BondPotentialImpl< Interaction >::computeForcesAndStress(), DdMd::PairPotentialImpl< Interaction >::computeForcesAndStress(), DdMd::AnglePotentialImpl< Interaction >::computeStress(), DdMd::BondPotentialImpl< Interaction >::computeStress(), DdMd::DihedralPotentialImpl< Interaction >::computeStress(), and DdMd::PairPotentialImpl< Interaction >::computeStress().
bool DdMd::Potential::isValid (MPI::Intracomm & communicator) const virtual
Is the potential in a valid internal state?
Return true if valid, or throws an Exception. Must be called on all processors.
Parameters
communicator domain communicator for all domain procs
Definition at line 164 of file Potential.cpp.
References Util::Setable< T >::isValid().
void DdMd::Potential::setEnergy (double energy) protected
Set a value for the total energy.
Definition at line 45 of file Potential.cpp.
References Util::Setable< T >::set().
Referenced by DdMd::ExternalPotentialImpl< Interaction >::computeEnergy(), and reduceEnergy().
void DdMd::Potential::setStress (const Tensor & stress) protected
Set a value for the total stress.
Definition at line 82 of file Potential.cpp.
Referenced by reduceStress().
void DdMd::Potential::incrementPairStress (const Vector & f, const Vector & dr, Tensor & stress) const inline protected
Add a pair contribution to the stress tensor.
Parameters
f pair force = f1 = -f2
dr pair separation = r1 - r2
stress virial, incremented by dyad dr f
Definition at line 235 of file Potential.h.
References Util::Dimension.
Referenced by DdMd::BondPotentialImpl< Interaction >::computeForcesAndStress(), DdMd::PairPotentialImpl< Interaction >::computeForcesAndStress(), DdMd::AnglePotentialImpl< Interaction >::computeStress(), DdMd::BondPotentialImpl< Interaction >::computeStress(), DdMd::DihedralPotentialImpl< Interaction >::computeStress(), and DdMd::PairPotentialImpl< Interaction >::computeStress().
void DdMd::Potential::reduceEnergy (double localEnergy, MPI::Intracomm & communicator) protected
Add local energies from all processors, set energy on master.
Call on all processors.
Parameters
localEnergy energy contribution from this processor
communicator domain communicator
Definition at line 120 of file Potential.cpp.
References setEnergy().
Referenced by DdMd::AnglePotentialImpl< Interaction >::computeEnergy(), DdMd::BondPotentialImpl< Interaction >::computeEnergy(), DdMd::ExternalPotentialImpl< Interaction >::computeEnergy(), DdMd::DihedralPotentialImpl< Interaction >::computeEnergy(), and DdMd::PairPotentialImpl< Interaction >::computeEnergy().
void DdMd::Potential::reduceStress (Tensor & localStress, MPI::Intracomm & communicator) protected
Add local stresses from all processors, set total on master.
Call on all processors.
Parameters
localStress stress contribution from this processor
communicator domain communicator
Definition at line 142 of file Potential.cpp.
References Util::Dimension, setStress(), and Util::Tensor::zero().
Referenced by DdMd::BondPotentialImpl< Interaction >::computeForcesAndStress(), DdMd::PairPotentialImpl< Interaction >::computeForcesAndStress(), DdMd::AnglePotentialImpl< Interaction >::computeStress(), DdMd::BondPotentialImpl< Interaction >::computeStress(), DdMd::DihedralPotentialImpl< Interaction >::computeStress(), and DdMd::PairPotentialImpl< Interaction >::computeStress().
The documentation for this class was generated from the following files:
Potential.h
Potential.cpp