Simpatico: DdMd::ModifierFactory Class Reference
DdMd::ModifierFactory Class Reference
Modifiers
Detailed Description
Factory for DdMd::Modifier objects.
Definition at line 27 of file ModifierFactory.h.
#include <ModifierFactory.h>
Public Member Functions
ModifierFactory ()
Default constructor (for unit testing)
ModifierFactory (Simulation &simulation)
Constructor.
virtual Modifier * factory (const std::string &className) const
Return pointer to a new Modifier object.
Protected Member Functions
Simulation & simulation () const
Return reference to parent Simulation.
Constructor & Destructor Documentation
DdMd::ModifierFactory::ModifierFactory ()
Default constructor (for unit testing)
Definition at line 21 of file ModifierFactory.cpp.
DdMd::ModifierFactory::ModifierFactory (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object
Definition at line 28 of file ModifierFactory.cpp.
Member Function Documentation
Modifier * DdMd::ModifierFactory::factory (const std::string & className) const [virtual]
Return pointer to a new Modifier object.
Parameters:
className name of a subclass of Modifier.
Returns:
base class pointer to a new instance of className.
Implements Util::Factory< Modifier >.
Definition at line 35 of file ModifierFactory.cpp.
References simulation(), and Util::Factory< Modifier >::trySubfactories().
Simulation& DdMd::ModifierFactory::simulation () const [inline, protected]
Return reference to parent Simulation.
Definition at line 57 of file ModifierFactory.h.
Referenced by factory().
The documentation for this class was generated from the following files:
ModifierFactory.h
ModifierFactory.cpp