Simpatico: Util::DMatrixParam< Type > Class Template Reference
Util::DMatrixParam< Type > Class Template Reference
Parameter File IO
Detailed Description
template<class Type>
class Util::DMatrixParam< Type >
A Parameter associated with a 2D built-in C array.
Definition at line 31 of file DMatrixParam.h.
#include <DMatrixParam.h>
Public Member Functions
DMatrixParam (const char *label, DMatrix< Type > &matrix, int m, int n)
Constructor.
void readParam (std::istream &in)
Read DMatrix from file.
void writeParam (std::ostream &out)
Write DMatrix to file.
void load (Serializable::IArchive &ar)
Load DMatrix from archive.
void save (Serializable::OArchive &ar)
Save DMatrix to an archive.
Public Member Functions inherited from Util::Parameter
Parameter (const char *label)
Constructor.
virtual ~Parameter ()
Destructor.
std::string label ()
Return label string.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
virtual void resetParam ()
Nontrivial implementation provided by ParamComposite subclass.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have a communicator?
MPI::Intracomm & ioCommunicator () const
Get the communicator.
Protected Attributes
DMatrix< Type > * matrixPtr_
Pointer to associated DMatrix.
int m_
Number of rows in array[m][n].
int n_
Number of columns in array[m][n].
Protected Attributes inherited from Util::Parameter
Label label_
Label object that contains parameter label string.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Public Attributes inherited from Util::Parameter
static const int Width = 20
Width of data field for a scalar variable (numerical or string).
static const int Precision = 12
Precision for io of floating point data field.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Constructor & Destructor Documentation
template<class Type > Util::DMatrixParam< Type >::DMatrixParam (const char * label, DMatrix< Type > & matrix, int m, int n)
Constructor.
Parameters
label parameter label (usually a literal C-string)
matrix DMatrix object
m number of rows
n number of columns
Definition at line 88 of file DMatrixParam.h.
Member Function Documentation
template<class Type > void Util::DMatrixParam< Type >::readParam (std::istream & in) virtual
Read DMatrix from file.
Implements Util::ParamComponent.
Definition at line 99 of file DMatrixParam.h.
References Util::ParamComponent::echo(), Util::Log::file(), and UTIL_THROW.
Referenced by Util::ParamComposite::readDMatrix().
template<class Type > void Util::DMatrixParam< Type >::writeParam (std::ostream & out) virtual
Write DMatrix to file.
Implements Util::ParamComponent.
Definition at line 142 of file DMatrixParam.h.
References Util::Parameter::Precision, UTIL_THROW, and Util::Parameter::Width.
template<class Type > void Util::DMatrixParam< Type >::load (Serializable::IArchive & ar) virtual
Load DMatrix from archive.
Parameters
ar loading (input) archive.
Reimplemented from Util::ParamComponent.
Definition at line 177 of file DMatrixParam.h.
References Util::ParamComponent::echo(), and Util::Log::file().
Referenced by Util::ParamComposite::loadDMatrix().
template<class Type > void Util::DMatrixParam< Type >::save (Serializable::OArchive & ar) virtual
Save DMatrix to an archive.
Parameters
ar saving (output) archive.
Reimplemented from Util::ParamComponent.
Definition at line 205 of file DMatrixParam.h.
Member Data Documentation
template<class Type> DMatrix<Type>* Util::DMatrixParam< Type >::matrixPtr_ protected
Pointer to associated DMatrix.
Definition at line 74 of file DMatrixParam.h.
template<class Type> int Util::DMatrixParam< Type >::m_ protected
Number of rows in array[m][n].
Definition at line 77 of file DMatrixParam.h.
template<class Type> int Util::DMatrixParam< Type >::n_ protected
Number of columns in array[m][n].
Definition at line 80 of file DMatrixParam.h.
The documentation for this class was generated from the following file:
DMatrixParam.h