Simpatico: McMd::McEnergyPerturbation Class Reference
McMd::McEnergyPerturbation Class Reference
Free Energy Perturbation
Detailed Description
A Perturbation with a variable inverse temperature.
An McEnergyPerturbation is a series of systems with the same Hamiltonian at different temperatures. The perturbation parameter is beta = 1/kT.
Definition at line 27 of file McEnergyPerturbation.h.
#include <McEnergyPerturbation.h>
Public Member Functions
McEnergyPerturbation (McSystem &system, int size, int rank)
Constructor.
virtual void readParameters (std::istream &in)
Read beta parameter (inverse temperature) from file.
virtual void setParameter ()
Set inverse temperature of the parent system.
virtual double parameter (int i) const
Get inverse temperature of the parent system.
virtual double derivative (int i) const
Get derivative of the Boltzmann weight with respect to the perturbation parameter.
Constructor & Destructor Documentation
McMd::McEnergyPerturbation::McEnergyPerturbation (McSystem & system, int size, int rank)
Constructor.
Definition at line 24 of file McEnergyPerturbation.cpp.
Member Function Documentation
void McMd::McEnergyPerturbation::readParameters (std::istream & in) [virtual]
Read beta parameter (inverse temperature) from file.
Parameters:
in input stream (file or std in).
Reimplemented from McMd::Perturbation.
Definition at line 32 of file McEnergyPerturbation.cpp.
References McMd::Perturbation::getNParameters().
void McMd::McEnergyPerturbation::setParameter () [virtual]
Set inverse temperature of the parent system.
Implements McMd::Perturbation.
Definition at line 43 of file McEnergyPerturbation.cpp.
References McMd::System::energyEnsemble(), McMd::Perturbation::parameter_, Util::EnergyEnsemble::setTemperature(), and McMd::LinearPerturbation< McSystem >::system().
double McMd::McEnergyPerturbation::parameter (int i) const [virtual]
Get inverse temperature of the parent system.
Parameters:
i index of the perturbation parameter. In this case, i is always 0 since nParameters = 1.
Implements McMd::Perturbation.
Definition at line 49 of file McEnergyPerturbation.cpp.
References McMd::System::energyEnsemble(), McMd::LinearPerturbation< McSystem >::system(), Util::EnergyEnsemble::temperature(), and UTIL_THROW.
double McMd::McEnergyPerturbation::derivative (int i) const [virtual]
Get derivative of the Boltzmann weight with respect to the perturbation parameter.
For a system in which W = beta*H depends on a parameter x, this method returns the value of dW/dx for the current system configuration.
Parameters:
i index of the perturbation parameter. In this case, i is always 0 since nParameters = 1.
Implements McMd::Perturbation.
Definition at line 61 of file McEnergyPerturbation.cpp.
References McMd::McSystem::potentialEnergy(), McMd::LinearPerturbation< McSystem >::system(), and UTIL_THROW.
The documentation for this class was generated from the following files:
McEnergyPerturbation.h
McEnergyPerturbation.cpp