Simpatico: DdMd::SimulationAccess Class Reference
DdMd::SimulationAccess Class Reference
Simulations
Detailed Description
Provides access to members of Simulation object.
A SimulationAccess holds pointers to the objects owned by a a parent simulation, and values of some variables (such as nAtomType, nBondType, etc.) that are not allowed to change after initialization.
It can only be instantiated after all of the objects for which it holds pointers, and after values are set for the variables nAtomType, nBondType, etc.
Definition at line 62 of file SimulationAccess.h.
#include <SimulationAccess.h>
Public Member Functions
SimulationAccess (Simulation &simulation)
Constructor.
~SimulationAccess ()
Destructor.
Accessors (Miscellaneous)
Simulation & simulation ()
Get the parent simulation.
Boundary & boundary ()
Get the Boundary.
AtomStorage & atomStorage ()
Get the AtomStorage.
GroupStorage< 2 > & bondStorage ()
Get the BondStorage.
GroupStorage< 3 > & angleStorage ()
Get the AngleStorage.
GroupStorage< 4 > & dihedralStorage ()
Get the angleStorage.
PairPotential & pairPotential ()
Get the PairPotential.
BondPotential & bondPotential ()
Get the PairPotential.
AnglePotential & anglePotential ()
Get the AnglePotential.
DihedralPotential & dihedralPotential ()
Get the DihedralPotential.
ExternalPotential & externalPotential ()
Get the ExternalPotential.
EnergyEnsemble & energyEnsemble ()
Get the EnergyEnsemble.
BoundaryEnsemble & boundaryEnsemble ()
Get the BoundaryEnsemble.
Random & random ()
Get the Random number generator.
Domain & domain ()
Get the Domain.
Exchanger & exchanger ()
Get the Exchanger.
FileMaster & fileMaster ()
Get the FileMaster.
int nAtomType ()
Get maximum number of atom types.
int nBondType ()
Get maximum number of bond types.
int nAngleType ()
Get maximum number of angle types.
int nDihedralType ()
Get maximum number of dihedral types.
bool hasExternal ()
Does this simulation have an external potential?
AtomType & atomType (int i)
Get an AtomType descriptor for atomtype i.
MaskPolicy maskedPairPolicy () const
Return the value of the mask policy (MaskNone or MaskBonded).
bool reverseUpdateFlag () const
Are forces evaluated by reverse communication (true) or not (false)?
Constructor & Destructor Documentation
DdMd::SimulationAccess::SimulationAccess (Simulation & simulation)
Constructor.
Parameters
simulation parent Simulation object.
Definition at line 20 of file SimulationAccess.cpp.
DdMd::SimulationAccess::~SimulationAccess ()
Destructor.
Definition at line 78 of file SimulationAccess.cpp.
Member Function Documentation
Simulation & DdMd::SimulationAccess::simulation () inline
Get the parent simulation.
Definition at line 295 of file SimulationAccess.h.
Referenced by DdMd::Integrator::clear(), DdMd::Integrator::computeForces(), DdMd::Integrator::computeForcesAndVirial(), DdMd::NvtIntegrator::integrateStep1(), DdMd::NphIntegrator::integrateStep1(), DdMd::NptIntegrator::integrateStep1(), DdMd::NvtIntegrator::integrateStep2(), DdMd::NphIntegrator::integrateStep2(), DdMd::NveIntegrator::integrateStep2(), DdMd::NptIntegrator::integrateStep2(), DdMd::NvtIntegrator::loadParameters(), DdMd::NphIntegrator::loadParameters(), DdMd::NveIntegrator::loadParameters(), DdMd::NptIntegrator::loadParameters(), DdMd::NvtIntegrator::readParameters(), DdMd::NveIntegrator::readParameters(), DdMd::NphIntegrator::readParameters(), DdMd::NptIntegrator::readParameters(), DdMd::TwoStepIntegrator::run(), DdMd::NvtIntegrator::setup(), DdMd::NveIntegrator::setup(), DdMd::NphIntegrator::setup(), DdMd::NptIntegrator::setup(), and DdMd::Integrator::setupAtoms().
Boundary & DdMd::SimulationAccess::boundary () inline
Get the Boundary.
Definition at line 298 of file SimulationAccess.h.
Referenced by DdMd::TwoStepIntegrator::run(), and DdMd::Integrator::setupAtoms().
AtomStorage & DdMd::SimulationAccess::atomStorage () inline
Get the AtomStorage.
Definition at line 301 of file SimulationAccess.h.
Referenced by DdMd::Integrator::clear(), DdMd::Integrator::computeForces(), DdMd::Integrator::computeForcesAndVirial(), DdMd::NvtIntegrator::integrateStep1(), DdMd::NphIntegrator::integrateStep1(), DdMd::NveIntegrator::integrateStep1(), DdMd::NptIntegrator::integrateStep1(), DdMd::NvtIntegrator::integrateStep2(), DdMd::NphIntegrator::integrateStep2(), DdMd::NveIntegrator::integrateStep2(), DdMd::NptIntegrator::integrateStep2(), DdMd::Integrator::isExchangeNeeded(), DdMd::Integrator::outputStatistics(), DdMd::TwoStepIntegrator::run(), DdMd::NvtIntegrator::setup(), DdMd::NphIntegrator::setup(), DdMd::NptIntegrator::setup(), and DdMd::Integrator::setupAtoms().
GroupStorage< 2 > & DdMd::SimulationAccess::bondStorage () inline
Get the BondStorage.
Definition at line 305 of file SimulationAccess.h.
Referenced by DdMd::Integrator::clear().
GroupStorage< 3 > & DdMd::SimulationAccess::angleStorage () inline
Get the AngleStorage.
Definition at line 310 of file SimulationAccess.h.
Referenced by DdMd::Integrator::clear().
GroupStorage< 4 > & DdMd::SimulationAccess::dihedralStorage () inline
Get the angleStorage.
Definition at line 315 of file SimulationAccess.h.
Referenced by DdMd::Integrator::clear().
PairPotential & DdMd::SimulationAccess::pairPotential () inline
Get the PairPotential.
Definition at line 319 of file SimulationAccess.h.
Referenced by DdMd::Integrator::clear(), DdMd::Integrator::computeForces(), DdMd::Integrator::computeForcesAndVirial(), DdMd::Integrator::outputStatistics(), DdMd::TwoStepIntegrator::run(), and DdMd::Integrator::setupAtoms().
BondPotential & DdMd::SimulationAccess::bondPotential () inline
Get the PairPotential.
Definition at line 323 of file SimulationAccess.h.
Referenced by DdMd::Integrator::computeForces(), and DdMd::Integrator::computeForcesAndVirial().
AnglePotential & DdMd::SimulationAccess::anglePotential () inline
Get the AnglePotential.
Definition at line 328 of file SimulationAccess.h.
Referenced by DdMd::Integrator::computeForces(), and DdMd::Integrator::computeForcesAndVirial().
DihedralPotential & DdMd::SimulationAccess::dihedralPotential () inline
Get the DihedralPotential.
Definition at line 333 of file SimulationAccess.h.
Referenced by DdMd::Integrator::computeForces(), and DdMd::Integrator::computeForcesAndVirial().
ExternalPotential & DdMd::SimulationAccess::externalPotential () inline
Get the ExternalPotential.
Definition at line 338 of file SimulationAccess.h.
Referenced by DdMd::Integrator::computeForces(), and DdMd::Integrator::computeForcesAndVirial().
EnergyEnsemble & DdMd::SimulationAccess::energyEnsemble () inline
Get the EnergyEnsemble.
Definition at line 342 of file SimulationAccess.h.
BoundaryEnsemble & DdMd::SimulationAccess::boundaryEnsemble () inline
Get the BoundaryEnsemble.
Definition at line 345 of file SimulationAccess.h.
Referenced by DdMd::TwoStepIntegrator::run(), and DdMd::Integrator::setupAtoms().
Random & DdMd::SimulationAccess::random () inline
Get the Random number generator.
Definition at line 348 of file SimulationAccess.h.
Domain & DdMd::SimulationAccess::domain () inline
Get the Domain.
Definition at line 351 of file SimulationAccess.h.
Referenced by DdMd::Integrator::computeForcesAndVirial(), DdMd::NphIntegrator::integrateStep1(), DdMd::NptIntegrator::integrateStep1(), DdMd::NvtIntegrator::integrateStep2(), DdMd::NphIntegrator::integrateStep2(), DdMd::NptIntegrator::integrateStep2(), DdMd::Integrator::isExchangeNeeded(), DdMd::Integrator::outputStatistics(), DdMd::TwoStepIntegrator::run(), DdMd::NvtIntegrator::setup(), DdMd::NphIntegrator::setup(), and DdMd::NptIntegrator::setup().
Exchanger & DdMd::SimulationAccess::exchanger () inline
Get the Exchanger.
Definition at line 354 of file SimulationAccess.h.
Referenced by DdMd::Integrator::computeForces(), DdMd::Integrator::computeForcesAndVirial(), DdMd::TwoStepIntegrator::run(), and DdMd::Integrator::setupAtoms().
FileMaster & DdMd::SimulationAccess::fileMaster () inline
Get the FileMaster.
Definition at line 357 of file SimulationAccess.h.
int DdMd::SimulationAccess::nAtomType () inline
Get maximum number of atom types.
Definition at line 360 of file SimulationAccess.h.
Referenced by DdMd::NvtIntegrator::loadParameters(), DdMd::NphIntegrator::loadParameters(), DdMd::NveIntegrator::loadParameters(), DdMd::NptIntegrator::loadParameters(), DdMd::NvtIntegrator::readParameters(), DdMd::NveIntegrator::readParameters(), DdMd::NphIntegrator::readParameters(), DdMd::NptIntegrator::readParameters(), DdMd::NvtIntegrator::setup(), DdMd::NphIntegrator::setup(), DdMd::NveIntegrator::setup(), and DdMd::NptIntegrator::setup().
int DdMd::SimulationAccess::nBondType () inline
Get maximum number of bond types.
Definition at line 364 of file SimulationAccess.h.
Referenced by DdMd::Integrator::computeForces(), DdMd::Integrator::computeForcesAndVirial(), and DdMd::Integrator::outputStatistics().
int DdMd::SimulationAccess::nAngleType () inline
Get maximum number of angle types.
Definition at line 369 of file SimulationAccess.h.
Referenced by DdMd::Integrator::computeForces(), DdMd::Integrator::computeForcesAndVirial(), and DdMd::Integrator::outputStatistics().
int DdMd::SimulationAccess::nDihedralType () inline
Get maximum number of dihedral types.
Definition at line 374 of file SimulationAccess.h.
Referenced by DdMd::Integrator::computeForces(), DdMd::Integrator::computeForcesAndVirial(), and DdMd::Integrator::outputStatistics().
bool DdMd::SimulationAccess::hasExternal () inline
Does this simulation have an external potential?
Definition at line 379 of file SimulationAccess.h.
Referenced by DdMd::Integrator::computeForces(), DdMd::Integrator::computeForcesAndVirial(), and DdMd::Integrator::outputStatistics().
AtomType & DdMd::SimulationAccess::atomType (int i) inline
Get an AtomType descriptor for atomtype i.
Definition at line 383 of file SimulationAccess.h.
MaskPolicy DdMd::SimulationAccess::maskedPairPolicy () const inline
Return the value of the mask policy (MaskNone or MaskBonded).
Definition at line 386 of file SimulationAccess.h.
bool DdMd::SimulationAccess::reverseUpdateFlag () const inline
Are forces evaluated by reverse communication (true) or not (false)?
Definition at line 389 of file SimulationAccess.h.
Referenced by DdMd::Integrator::computeForces(), and DdMd::Integrator::computeForcesAndVirial().
The documentation for this class was generated from the following files:
SimulationAccess.h
SimulationAccess.cpp