Simpatico: Util::BoundaryEnsemble Class Reference
Util::BoundaryEnsemble Class Reference
Detailed Description
Statistical ensemble for changes in the periodic unit cell size.
A boundary ensemble has a type, which can be rigid or isobaric, and stores a pressure if it is isobaric.
Definition at line 27 of file BoundaryEnsemble.h.
#include <BoundaryEnsemble.h>
Public Types
enum Type
Enumeration of the allowed types of BoundaryEnsemble.
Public Member Functions
BoundaryEnsemble (Type type=UNKNOWN)
Constructor.
void setPressure (double pressure)
Set the pressure.
virtual void readParameters (std::istream &in)
Read the type and (if necessary) pressure from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
Accessors
bool isRigid () const
Is this an Rigid ensemble?
bool isIsobaric () const
Is this an Isobaric ensemble?
double pressure () const
Get the target pressure.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
std::string className () const
Get class name string.
virtual void readParam (std::istream &in)
Read a parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an archive.
void resetParam ()
Resets ParamComposite to its empty state.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add a new Param < Type > object, and read its value.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add a C array parameter, and read its elements.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and read its elements.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n)
Add and read a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
Begin & readBegin (std::istream &in, const char *label)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a child ParamComposite.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add a new Param < Type > object, and load its value.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add a C array parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and load its elements.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n)
Add and load a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a DMatrix < Type > C two-dimensional matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
template<typename Type >
ScalarParam< Type > & add (const char *label, Type &value)
Add a new Param < Type > object to the format array.
template<typename Type >
CArrayParam< Type > & addCArray (const char *label, Type *value, int n)
Add a C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (const char *label, DArray< Type > &array, int n)
Add a DArray<Type> parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (const char *label, FArray< Type, N > &array)
Add a FArray<Type> parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (const char *label, Type *value, int m, int n)
Add a C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & addDMatrix (const char *label, DMatrix< Type > &matrix, int m, int n)
Add a C two-dimensional array parameter.
Begin & addBegin (const char *label)
Add a class label and opening bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Add a new Blank object, representing a blank line.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have a communicator?
MPI::Intracomm & ioCommunicator () const
Get the communicator.
Static Public Member Functions
static void commitMpiType ()
Commit associated MPI DataType.
Additional Inherited Members
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
Member Enumeration Documentation
enum Util::BoundaryEnsemble::Type
Enumeration of the allowed types of BoundaryEnsemble.
Definition at line 35 of file BoundaryEnsemble.h.
Constructor & Destructor Documentation
Util::BoundaryEnsemble::BoundaryEnsemble (Type type = UNKNOWN)
Constructor.
Definition at line 22 of file BoundaryEnsemble.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void Util::BoundaryEnsemble::setPressure (double pressure)
Set the pressure.
Definition at line 30 of file BoundaryEnsemble.cpp.
References isIsobaric(), pressure(), and UTIL_THROW.
void Util::BoundaryEnsemble::readParameters (std::istream & in) virtual
Read the type and (if necessary) pressure from file.
The type is specified in the input file by a string literal "rigid" or "isobaric".
Reimplemented from Util::ParamComposite.
Definition at line 41 of file BoundaryEnsemble.cpp.
References isIsobaric().
void Util::BoundaryEnsemble::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 52 of file BoundaryEnsemble.cpp.
References isIsobaric().
void Util::BoundaryEnsemble::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 63 of file BoundaryEnsemble.cpp.
References isIsobaric().
Referenced by McMd::System::saveEnsembles().
bool Util::BoundaryEnsemble::isRigid () const inline
Is this an Rigid ensemble?
Definition at line 139 of file BoundaryEnsemble.h.
bool Util::BoundaryEnsemble::isIsobaric () const inline
Is this an Isobaric ensemble?
Definition at line 145 of file BoundaryEnsemble.h.
Referenced by loadParameters(), readParameters(), save(), and setPressure().
double Util::BoundaryEnsemble::pressure () const inline
Get the target pressure.
Definition at line 133 of file BoundaryEnsemble.h.
Referenced by DdMd::NphIntegrator::integrateStep1(), DdMd::NptIntegrator::integrateStep1(), McMd::HybridNphMdMove::move(), setPressure(), DdMd::NphIntegrator::setup(), DdMd::NptIntegrator::setup(), and McMd::NphIntegrator::step().
void Util::BoundaryEnsemble::commitMpiType () static
Commit associated MPI DataType.
Commit MPI Datatype.
Definition at line 118 of file BoundaryEnsemble.cpp.
References Util::MpiStructBuilder::addMember(), Util::MpiStructBuilder::commit(), and Util::MpiStructBuilder::setBase().
The documentation for this class was generated from the following files:
BoundaryEnsemble.h
BoundaryEnsemble.cpp