Simpatico: McMd::FileMaster Class Reference
McMd::FileMaster Class Reference
Detailed Description
A FileMaster manages a set of input and output files.
A FileMaster manages a set of input and output files in which all input file paths share a common input prefix and all output file paths share a common output prefix. The openInputFile() and openOutputFile() methods each open a file using a path that is constructed by prepending the input or output prefix, respectively, to a filename string parameter. A FileMaster also provides access to a separate parameter file.
The base input and output prefix strings are read from file by the readParam() method. To use input files that are all in one directory and create output files in another, these prefix strings should be set to the desired directory names, followed by a trailing "/" directory separator. For example, to put all input and output files in directories named "in" and "out", the prefix strings should be set to "in/" and "out/", respectively.
The setDirectoryId(int rank) method is designed for use in parallel MPI programs, to allow files associated with different processors to be put in different directory trees. If this method is called with a rank parameter n, openInputFile() and openOutputFile() will thereafter prepend a string "n/" to all file paths before the inputPrefix and output prefix strings. Calling setDirectoryId(n) and placing prefixes "in/" and "out/" in the parameter file that is read by readParam thus causes the strings "n/in/" and "n/out/" to be prepended to the names of files opened by openInputFile() and openOutputFile().
The paramFile() method returns a default parameter input stream, using different conventions for serial and parallel operation. If no directory id has been set, as is normally the case for a serial program, paramFile() returns a reference to the standard input, std::cin. In parallel programs, if setDirectoryId() has been called, but setParamFileStdIn() has also been called, paramFile() again returns a reference to std::cin. If a directory id has been set by calling setDirectoryId() has been and setParamFileStdIn() has not be called, however, paramFile() returns a reference to a file named "n/param". This file is opened for reading the first time it is returned by paramFile(), and is closed by the FileMaster destructor.
Definition at line 67 of file mcMd/util/FileMaster.h.
#include <FileMaster.h>
Public Member Functions
FileMaster ()
Constructor.
FileMaster (const FileMaster &copy)
Copy constructor.
virtual ~FileMaster ()
Destructor.
void setRootPrefix (const std::string &rootPrefix)
Set the path from current directory to root data directory.
void setDirectoryId (int directoryId)
Set an integer directory identifier for this processor.
void setParamFileStdIn ()
Set paramFile() to return std::cin even if a directory id is set.
void setInputPrefix (const std::string &inputPrefix)
Set the input file prefix string.
void setOutputPrefix (const std::string &outputPrefix)
Set the output file prefix string.
void setCommandFileName (const std::string &commandFileName)
Set the command file name.
virtual void readParam (std::istream &in)
Read parameter file.
std::istream & paramFile ()
Get a default parameter stream by reference.
std::istream & commandFile ()
Get the command input stream by reference.
void openInputFile (const std::string &filename, std::ifstream &in) const
Open an input file named [directoryIdPrefix] + inputPrefix + filename.
void openOutputFile (const std::string &filename, std::ofstream &out) const
Open an output file named [directoryIdPrefix] + inputPrefix + filename.
void openParamIFile (const std::string &name, const char *ext, std::ifstream &in) const
Open an input restart parameter file.
void openParamOFile (const std::string &name, const char *ext, std::ofstream &out) const
Open a restart parameter file for writing.
void openRestartIFile (const std::string &name, const char *ext, std::ifstream &in) const
Open an input restart dump file.
void openRestartOFile (const std::string &name, const char *ext, std::ofstream &out) const
Open a restart dump file for writing.
std::string commandFileName () const
Return the command file name.
bool isParamFileStdIn () const
Is paramFile() set to return std::cin ?
Friends
class DdMd::FileMaster
Constructor & Destructor Documentation
home david code simpatico src mcMd util FileMaster cpp McMd::FileMaster::FileMaster ()
Constructor.
Definition at line 23 of file mcMd/util/FileMaster.cpp.
McMd::FileMaster::FileMaster (const FileMaster & copy)
Copy constructor.
Parameters:
copy FileMaster object to be copied
Definition at line 38 of file mcMd/util/FileMaster.cpp.
McMd::FileMaster::~FileMaster () [virtual]
Destructor.
Definition at line 50 of file mcMd/util/FileMaster.cpp.
Member Function Documentation
void McMd::FileMaster::setRootPrefix (const std::string & rootPrefix)
Set the path from current directory to root data directory.
Parameters:
rootPrefix root prefix for all file names.
Definition at line 65 of file mcMd/util/FileMaster.cpp.
void McMd::FileMaster::setDirectoryId (int directoryId)
Set an integer directory identifier for this processor.
This method should be called only for parallel operation. The directoryId is normally set to be the MPI rank of this processor. After calling setDirectoryId(n) with an integer n, a prefix "n/" will be prepended to the paths of all input and output file files that are opened by openInputFile() and openOutputFile().
Parameters:
directoryId integer directory name for input and output files.
Definition at line 71 of file mcMd/util/FileMaster.cpp.
void McMd::FileMaster::setParamFileStdIn ()
Set paramFile() to return std::cin even if a directory id is set.
Definition at line 83 of file mcMd/util/FileMaster.cpp.
void McMd::FileMaster::setInputPrefix (const std::string & inputPrefix)
Set the input file prefix string.
Parameters:
inputPrefix input file prefix string
Definition at line 89 of file mcMd/util/FileMaster.cpp.
void McMd::FileMaster::setOutputPrefix (const std::string & outputPrefix)
Set the output file prefix string.
Parameters:
outputPrefix output file prefix string
Definition at line 95 of file mcMd/util/FileMaster.cpp.
void McMd::FileMaster::setCommandFileName (const std::string & commandFileName)
Set the command file name.
Parameters:
commandFileName name of command file
Definition at line 101 of file mcMd/util/FileMaster.cpp.
References commandFileName().
Referenced by McMd::MdSimulation::readRestart(), and McMd::McSimulation::readRestart().
void McMd::FileMaster::readParam (std::istream & in) [virtual]
Read parameter file.
Reads the inputPrefix and outputPrefix string variables.
Parameters:
in pararameter file input stream
Reimplemented from Util::ParamComposite.
Definition at line 107 of file mcMd/util/FileMaster.cpp.
References Util::ParamComposite::readBegin(), and Util::ParamComposite::readEnd().
std::istream & McMd::FileMaster::paramFile ()
Get a default parameter stream by reference.
If setDirectoryId() has not been called, of if setParamFileStdIn() has been called, this method returns std::cin.
If setDirectoryId() has been called and setParamFileStdInd() has not, this method returns a reference to a file "n/param". This file is opened for reading the first time it is returned by this method.
Definition at line 119 of file mcMd/util/FileMaster.cpp.
References UTIL_THROW.
Referenced by commandFile().
std::istream & McMd::FileMaster::commandFile ()
Get the command input stream by reference.
If the commandFileName string is equal to the string literal "paramfile", this method returns the same stream as paramFile(). Otherwise, it returns a reference to a file whose name is given by the commandFileName string. If setDirectoryId(int) has not been called, the path to this file (absolute or relative to the working directory) is equal to the commandFileName string. If setDirectory() has been called with an integer argument n, the path to this file is obtained adding "n/" as a prefix to the commandFileName. In either case, if the commandFileName is not "paramfile", the required file is opened for reading the first time it is returned by this method.
Definition at line 156 of file mcMd/util/FileMaster.cpp.
References paramFile(), and UTIL_THROW.
void McMd::FileMaster::openInputFile (const std::string & filename, std::ifstream & in) const
Open an input file named [directoryIdPrefix] + inputPrefix + filename.
The directoryIdPrefix "n/" is added as a prefix to the path name if and only if setDirectoryId(int) has been called with an argument n.
Parameters:
filename file name, without any prefix
in ifstream object to associated with a file
Definition at line 195 of file mcMd/util/FileMaster.cpp.
References UTIL_THROW.
Referenced by McMd::McSimulation::analyze(), McMd::MdSimulation::analyzeDumps(), McMd::MdSimulation::readCommands(), and McMd::McSimulation::readCommands().
void McMd::FileMaster::openOutputFile (const std::string & filename, std::ofstream & out) const
Open an output file named [directoryIdPrefix] + inputPrefix + filename.
The directoryIdPrefix "n/" is added as a prefix to the path name if and only if setDirectoryId(int) has been called with an argument n.
Parameters:
filename file name, without any prefix
out ofstream object to associated with a file
Definition at line 220 of file mcMd/util/FileMaster.cpp.
References UTIL_THROW.
Referenced by McMd::VanHove::output(), McMd::MdPotentialEnergyAverage::output(), McMd::MdPairEnergyCoefficients::output(), McMd::MdKineticEnergyAverage::output(), McMd::MdEnergyOutput::output(), McMd::McStressAutoCorr::output(), McMd::McPairEnergyAverage::output(), McMd::McExternalEnergyAverage::output(), McMd::McEnergyOutput::output(), McMd::McEnergyAverage::output(), McMd::AverageDiagnostic< SystemType >::output(), McMd::MdSimulation::readCommands(), McMd::McSimulation::readCommands(), McMd::MdPotentialEnergyAverage::readParam(), McMd::MdPairEnergyCoefficients::readParam(), McMd::MdKineticEnergyAverage::readParam(), McMd::MdEnergyOutput::readParam(), McMd::McPairEnergyAverage::readParam(), McMd::McExternalEnergyAverage::readParam(), McMd::McEnergyOutput::readParam(), McMd::McEnergyAverage::readParam(), and McMd::AverageDiagnostic< SystemType >::readParam().
void McMd::FileMaster::openParamIFile (const std::string & name, const char * ext, std::ifstream & in) const
Open an input restart parameter file.
Parameters:
name base file name, without any prefix
ext file name extension.
in ifstream object to open
Definition at line 245 of file mcMd/util/FileMaster.cpp.
References UTIL_THROW.
Referenced by McMd::MdSimulation::readRestart(), and McMd::McSimulation::readRestart().
void McMd::FileMaster::openParamOFile (const std::string & name, const char * ext, std::ofstream & out) const
Open a restart parameter file for writing.
Parameters:
name base file name, without any prefix or extension
ext file name extension.
out ofstream object to open
Definition at line 267 of file mcMd/util/FileMaster.cpp.
References UTIL_THROW.
Referenced by McMd::MdSimulation::writeRestart(), and McMd::McSimulation::writeRestart().
void McMd::FileMaster::openRestartIFile (const std::string & name, const char * ext, std::ifstream & in) const
Open an input restart dump file.
Parameters:
name base file name, without any prefix or extension
ext file name extension.
in ifstream object to open
Definition at line 289 of file mcMd/util/FileMaster.cpp.
References UTIL_THROW.
Referenced by McMd::MdSimulation::readRestart(), and McMd::McSimulation::readRestart().
void McMd::FileMaster::openRestartOFile (const std::string & name, const char * ext, std::ofstream & out) const
Open a restart dump file for writing.
Parameters:
name base file name, without any prefix or extension
ext file name extension.
out ofstream object to open
Definition at line 310 of file mcMd/util/FileMaster.cpp.
References UTIL_THROW.
Referenced by McMd::MdSimulation::writeRestart(), and McMd::McSimulation::writeRestart().
std::string McMd::FileMaster::commandFileName () const [inline]
Return the command file name.
Definition at line 307 of file mcMd/util/FileMaster.h.
Referenced by setCommandFileName().
bool McMd::FileMaster::isParamFileStdIn () const
Is paramFile() set to return std::cin ?
Definition at line 334 of file mcMd/util/FileMaster.cpp.
The documentation for this class was generated from the following files:
mcMd/util/FileMaster.h
mcMd/util/FileMaster.cpp