Simpatico: Util::Manager< Data > Class Template Reference
Util::Manager< Data > Class Template Reference
Managers and Factories
Detailed Description
template<typename Data>
class Util::Manager< Data >
Template container for pointers to objects with a common base class.
A Manager<Data> has an array of Data* pointers to Data objects, an array of corresponding subclass names, and a pointer to a Factory<Data> object. The default implementation of the Manager<Data>::readParam() method uses an associated Factory<Data> object to recognize the class name string that begins a polymorphic block in a parameter file (which must refer to a known subclass of Data) and to instantiate an object of the specified subclass.
Subclasses of Manager<Data> are used to manage arrays of Species, McMove, and Analyzer objects.
Definition at line 38 of file Manager.h.
#include <Manager.h>
Public Member Functions
Manager ()
Constructor.
virtual ~Manager ()
Destructor.
void addSubfactory (Factory< Data > &subfactory)
Set a SubFactory for this Manager.
void setFactory (Factory< Data > &factory)
Associate a Factory with this Manager.
void setFactory (Factory< Data > *factoryPtr)
Associated a Factory with this Manager (pass by pointer).
virtual void readParam (std::istream &in)
Read and create a set of objects.
virtual void readParamOptional (std::istream &in)
Optioanlly read and create a set of objects.
virtual void readParameters (std::istream &in)
Read child blocks, return when closing bracket encountered.
virtual void loadParameters (Serializable::IArchive &ar)
Load a set of objects to an output archive.
virtual void save (Serializable::OArchive &ar)
Save a set of objects to an output archive.
void append (Data &data, const std::string &name)
Append a Data object to the end of the sequence.
int size () const
Get logical size.
std::string className (int i) const
Get the subclass name for object number i.
Factory< Data > & factory ()
Return a reference to the factory.
bool hasFactory () const
Return true if this Manager has a Factory, false otherwise.
Data & operator[] (int i) const
Mimic C array subscripting.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
void beginReadManager (std::istream &in)
Read (or attempt to read) opening line: "ManagerName{".
void endReadManager ()
Add closing bracket to output format.
virtual void initFactory ()
Create factory if necessary.
virtual Factory< Data > * newDefaultFactory () const
Create an instance of the default Factory<Data> class.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
Factory< Data > * factoryPtr_
Pointer to an associated Factory<Data> object.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Constructor & Destructor Documentation
template<typename Data > Util::Manager< Data >::Manager ()
Constructor.
Definition at line 222 of file Manager.h.
template<typename Data > Util::Manager< Data >::~Manager () virtual
Destructor.
Definition at line 236 of file Manager.h.
Member Function Documentation
template<typename Data> void Util::Manager< Data >::addSubfactory (Factory< Data > & subfactory)
Set a SubFactory for this Manager.
Parameters
subfactory Referernce to a sub-Factory to be added.
Definition at line 265 of file Manager.h.
template<typename Data> void Util::Manager< Data >::setFactory (Factory< Data > & factory)
Associate a Factory with this Manager.
Parameters
factory Reference to a Factory object
Definition at line 274 of file Manager.h.
template<typename Data> void Util::Manager< Data >::setFactory (Factory< Data > * factoryPtr)
Associated a Factory with this Manager (pass by pointer).
Parameters
factoryPtr pointer to a Factory<Data> object.
Definition at line 287 of file Manager.h.
template<typename Data > void Util::Manager< Data >::readParam (std::istream & in) virtual
Read and create a set of objects.
The default implementation of this method reads a sequence of blocks for different subclasses of Data, terminated by a closing bracket. For each block it:
reads a className string for a subclass of Data,
uses factory object to create a new instance of className.
invokes the readParam() method of the new object.
The implementation of the factory must recognize all valid className string values, and invoke the appropriate constructor for each. The loop over blocks terminates when it encounters a closing bracket '}' surrounded by white space.
Parameters
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 300 of file Manager.h.
template<typename Data > void Util::Manager< Data >::readParamOptional (std::istream & in) virtual
Optioanlly read and create a set of objects.
Equivalent to readParam(), except that this function does nothing if the first line does not match the expected label, whereas readParam() throws an Exception
Parameters
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 313 of file Manager.h.
template<typename Data > void Util::Manager< Data >::readParameters (std::istream & in) virtual
Read child blocks, return when closing bracket encountered.
Parameters
in input stream
Reimplemented from Util::ParamComposite.
Reimplemented in DdMd::ModifierManager, McMd::McMoveManager, DdMd::AnalyzerManager, McMd::AnalyzerManager, and Tools::AnalyzerManager.
Definition at line 346 of file Manager.h.
References UTIL_THROW.
Referenced by Tools::AnalyzerManager::readParameters(), McMd::AnalyzerManager::readParameters(), DdMd::AnalyzerManager::readParameters(), McMd::McMoveManager::readParameters(), and DdMd::ModifierManager::readParameters().
template<typename Data > void Util::Manager< Data >::loadParameters (Serializable::IArchive & ar) virtual
Load a set of objects to an output archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Reimplemented in McMd::McMoveManager, DdMd::AnalyzerManager, and McMd::AnalyzerManager.
Definition at line 393 of file Manager.h.
References UTIL_THROW.
Referenced by McMd::AnalyzerManager::loadParameters(), DdMd::AnalyzerManager::loadParameters(), and McMd::McMoveManager::loadParameters().
template<typename Data > void Util::Manager< Data >::save (Serializable::OArchive & ar) virtual
Save a set of objects to an output archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Reimplemented in McMd::McMoveManager, DdMd::AnalyzerManager, and McMd::AnalyzerManager.
Definition at line 430 of file Manager.h.
Referenced by McMd::AnalyzerManager::save(), DdMd::AnalyzerManager::save(), and McMd::McMoveManager::save().
template<typename Data> void Util::Manager< Data >::append (Data & data, const std::string & name)
Append a Data object to the end of the sequence.
Parameters
data Data object to be appended
name subclass name
Definition at line 444 of file Manager.h.
template<typename Data > int Util::Manager< Data >::size () const inline
Get logical size.
Returns
logical size of this array.
Definition at line 476 of file Manager.h.
Referenced by McMd::Simulation::nSpecies().
template<typename Data > std::string Util::Manager< Data >::className (int i) const
Get the subclass name for object number i.
Parameters
i integer index of object
Returns
class name of managed object
Definition at line 455 of file Manager.h.
References UTIL_THROW.
template<typename Data > Factory< Data > & Util::Manager< Data >::factory ()
Return a reference to the factory.
Definition at line 255 of file Manager.h.
Referenced by McMd::Simulation::analyzerFactory(), McMd::McSimulation::mcMoveFactory(), and McMd::Simulation::speciesFactory().
template<typename Data > bool Util::Manager< Data >::hasFactory () const
Return true if this Manager has a Factory, false otherwise.
Definition at line 467 of file Manager.h.
template<typename Data > Data & Util::Manager< Data >::operator[] (int i) const inline
Mimic C array subscripting.
Parameters
i array index
Returns
reference to element i
Definition at line 486 of file Manager.h.
template<typename Data > void Util::Manager< Data >::beginReadManager (std::istream & in) protected
Read (or attempt to read) opening line: "ManagerName{".
Definition at line 328 of file Manager.h.
References Util::ParamComposite::className(), and Util::Begin::isActive().
template<typename Data > void Util::Manager< Data >::endReadManager () protected
Add closing bracket to output format.
Definition at line 381 of file Manager.h.
References Util::ParamComponent::echo(), Util::Log::file(), and Util::End::writeParam().
template<typename Data > void Util::Manager< Data >::initFactory () protected virtual
Create factory if necessary.
Definition at line 499 of file Manager.h.
template<typename Data > Factory< Data > * Util::Manager< Data >::newDefaultFactory () const protected virtual
Create an instance of the default Factory<Data> class.
Returns
a pointer to a new Factory<Data> object.
Reimplemented in DdMd::AnalyzerManager, DdMd::ModifierManager, McMd::MdAnalyzerManager, McMd::McAnalyzerManager, Tools::ProcessorAnalyzerManager, and McMd::SpeciesManager.
Definition at line 512 of file Manager.h.
References UTIL_THROW.
Member Data Documentation
template<typename Data> Factory<Data>* Util::Manager< Data >::factoryPtr_ protected
Pointer to an associated Factory<Data> object.
Definition at line 172 of file Manager.h.
The documentation for this class was generated from the following file:
Manager.h