Simpatico: McMd::McStressAutoCorr Class Reference
McMd::McStressAutoCorr Class Reference
Diagnostics
Detailed Description
Shear stress autocorrelation function.
Definition at line 26 of file McStressAutoCorr.h.
#include <McStressAutoCorr.h>
Public Member Functions
McStressAutoCorr (McSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Set number of molecules and clear accumulator.
virtual void sample (long iStep)
Evaluate separation vector for all chains, add to ensemble.
virtual void output ()
Output results after simulation is completed.
Constructor & Destructor Documentation
McMd::McStressAutoCorr::McStressAutoCorr (McSystem & system)
Constructor.
Parameters:
system reference to parent System
Definition at line 26 of file McStressAutoCorr.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::McStressAutoCorr::readParameters (std::istream & in) [virtual]
Read parameters from file.
Input format:
int interval sampling interval
string outputFileName output file name
int capacity capacity of array of previous values.
Parameters:
in input parameter stream
Reimplemented from McMd::Diagnostic.
Definition at line 37 of file McStressAutoCorr.cpp.
References McMd::Diagnostic::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), McMd::Diagnostic::readInterval(), McMd::Diagnostic::readOutputFileName(), Util::AutoCorr< Data, Product >::setParam(), and UTIL_THROW.
void McMd::McStressAutoCorr::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::Diagnostic.
Definition at line 58 of file McStressAutoCorr.cpp.
References McMd::Diagnostic::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), and UTIL_THROW.
void McMd::McStressAutoCorr::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::Diagnostic.
Definition at line 79 of file McStressAutoCorr.cpp.
template<class Archive > void McMd::McStressAutoCorr::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Diagnostic.
Definition at line 111 of file McStressAutoCorr.h.
References McMd::serialize().
void McMd::McStressAutoCorr::setup () [virtual]
Set number of molecules and clear accumulator.
Reimplemented from McMd::Diagnostic.
Definition at line 86 of file McStressAutoCorr.cpp.
References Util::AutoCorr< Data, Product >::clear().
void McMd::McStressAutoCorr::sample (long iStep) [virtual]
Evaluate separation vector for all chains, add to ensemble.
Parameters:
iStep counter for number of steps
Implements McMd::Diagnostic.
Definition at line 92 of file McStressAutoCorr.cpp.
References McMd::System::boundary(), McMd::McSystem::computeStress(), Util::Dimension, McMd::Diagnostic::isAtInterval(), Util::AutoCorr< Data, Product >::sample(), Util::Tensor::symmetrize(), McMd::SystemDiagnostic< McSystem >::system(), Util::Tensor::trace(), and Util::OrthorhombicBoundary::volume().
void McMd::McStressAutoCorr::output () [virtual]
Output results after simulation is completed.
Reimplemented from McMd::Diagnostic.
Definition at line 112 of file McStressAutoCorr.cpp.
References Util::AutoCorr< Data, Product >::average(), Util::AutoCorr< Data, Product >::bufferCapacity(), McMd::Diagnostic::fileMaster(), Util::AutoCorr< Data, Product >::nSample(), Util::FileMaster::openOutputFile(), Util::AutoCorr< Data, Product >::output(), McMd::Diagnostic::outputFileName(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
McStressAutoCorr.h
McStressAutoCorr.cpp