Simpatico: McMd::VanHove Class Reference
McMd::VanHove Class Reference
Analyzers
Detailed Description
Evaluates the van Hove function S(k,t) for one or more wavevector k.
The van Hove function S(k,t) is defined here as an expectation value
where V is system volume, and is given by a sum
over all atoms in the system, where is a user-specified coefficient for monomers of type a.
The Van Hove class can calculate S(k,t) for a list of wavevectors. Each wavevector is specified as an IntVector containing integer Miller indices. These are the coefficients in an expansion of a reciprocal lattice wavevector in terms of recprocal lattice basis vectors.
In a system with nAtomType = 2, with two monomer types 0 and 1, the parameter file input for calculating the autocorrelation of an order parameter for 5 wavevectors along the x axis in an orthorhombic unit cell might look like this:
 VanHove{
    interval                      1000
    outputFileName             VanHove
    atomTypeCoeffs              1.0000      -1.0000
    nBuffer                        100
    nWave                            5
    waveIntVectors     8      0      0
                       9      0      0
                      10      0      0
                      11      0      0
                      12      0      0
 }
At the end of a simulation, all of the autocorrelation functions are output in a file with a suffix *.dat. Each line in this file contains the 3 Miller indices of a wavevector, the absolute magnitude of the wavevector, and a list of nAtomTypeIdPair structure factor values for the wavevector, one for each atomTypeId pair.
See also:
parameter file format
Definition at line 77 of file mcMd/analyzers/system/VanHove.h.
#include <VanHove.h>
Public Member Functions
VanHove (System &system)
Constructor.
~VanHove ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Clear accumulators.
void sample (long iStep)
Add particle pairs to VanHove histogram.
virtual void output ()
Output results to predefined output file.
Constructor & Destructor Documentation
McMd::VanHove::VanHove (System & system)
Constructor.
Parameters:
system reference to parent System object
Definition at line 33 of file mcMd/analyzers/system/VanHove.cpp.
References Util::ParamComposite::setClassName().
McMd::VanHove::~VanHove ()
Destructor.
Definition at line 41 of file mcMd/analyzers/system/VanHove.cpp.
Member Function Documentation
void McMd::VanHove::readParameters (std::istream & in) [virtual]
Read parameters from file.
Input format:
int interval sampling interval
string outputFileName output file base name
DArray<double> atomTypeCoeffs array of type coefficients
int nBuffer number of samples in buffer
int nWave number of wavevectors
DArray<IntVector> waveIntVectors IntVector wavevectors
Parameters:
in input parameter stream
Reimplemented from McMd::Analyzer.
Definition at line 47 of file mcMd/analyzers/system/VanHove.cpp.
References Util::DArray< Data >::allocate(), McMd::Simulation::nAtomType(), McMd::Analyzer::readInterval(), McMd::Analyzer::readOutputFileName(), McMd::System::simulation(), and McMd::SystemAnalyzer< System >::system().
void McMd::VanHove::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from McMd::Analyzer.
Definition at line 73 of file mcMd/analyzers/system/VanHove.cpp.
References Util::DArray< Data >::allocate(), McMd::SystemAnalyzer< System >::system(), and UTIL_THROW.
void McMd::VanHove::save (Serializable::OArchive & ar) [virtual]
Save state to an archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::Analyzer.
Definition at line 108 of file mcMd/analyzers/system/VanHove.cpp.
template<class Archive > void McMd::VanHove::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar archive
version archive version id
Reimplemented from McMd::Analyzer.
Definition at line 194 of file mcMd/analyzers/system/VanHove.h.
References McMd::serialize().
void McMd::VanHove::setup () [virtual]
Clear accumulators.
Reimplemented from McMd::Analyzer.
Definition at line 114 of file mcMd/analyzers/system/VanHove.cpp.
References UTIL_THROW.
void McMd::VanHove::sample (long iStep) [virtual]
Add particle pairs to VanHove histogram.
Increment Structure Factor.
Parameters:
iStep step counter
Implements McMd::Analyzer.
Definition at line 127 of file mcMd/analyzers/system/VanHove.cpp.
References McMd::System::begin(), Util::Vector::dot(), Util::Constants::Im, McMd::Analyzer::isAtInterval(), Util::ConstArrayIterator< Data >::notEnd(), Util::ConstPArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::product(), McMd::System::simulation(), and McMd::SystemAnalyzer< System >::system().
void McMd::VanHove::output () [virtual]
Output results to predefined output file.
Reimplemented from McMd::Analyzer.
Definition at line 199 of file mcMd/analyzers/system/VanHove.cpp.
References Util::Dimension, McMd::Analyzer::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Analyzer::outputFileName(), Util::toString(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
mcMd/analyzers/system/VanHove.h
mcMd/analyzers/system/VanHove.cpp