Simpatico: Util::GPArray< Data > Class Template Reference
Util::GPArray< Data > Class Template Reference
Pointer Arrays
Detailed Description
template<typename Data>
class Util::GPArray< Data >
An automatically growable PArray.
An GPArray is a PArray that grows as needed as objects are appended. Like any PArray, it holds pointers to objects, rather than objects. The associated objects are not destroyed when a PArray is deallocated or destroyed.
Definition at line 28 of file GPArray.h.
#include <GPArray.h>
Public Member Functions
GPArray ()
Constructor.
GPArray (const GPArray< Data > &other)
Copy constructor, copy pointers.
GPArray< Data > & operator= (const GPArray< Data > &other)
Assignment, element by element.
virtual ~GPArray ()
Destructor.
void append (Data &data)
Append an element to the end of the sequence.
void reserve (int capacity)
Reserve memory for specified number of elements.
void deallocate ()
Deallocate (delete) underlying array of pointers.
void clear ()
Reset to empty state.
bool isAllocated () const
Is this GPArray allocated?
Constructor & Destructor Documentation
template<typename Data > Util::GPArray< Data >::GPArray () [inline]
Constructor.
Definition at line 113 of file GPArray.h.
template<typename Data> Util::GPArray< Data >::GPArray (const GPArray< Data > & other)
Copy constructor, copy pointers.
Allocates new Data* array and copies pointers to Data objects.
Parameters:
other the GPArray to be copied.
Allocates a new Data* array and copies all pointer values.
Parameters:
other the GPArray to be copied.
Definition at line 125 of file GPArray.h.
References Util::PArray< Data >::capacity_, Util::PArray< Data >::ptrs_, and Util::PArray< Data >::size_.
template<typename Data > Util::GPArray< Data >::~GPArray () [virtual]
Destructor.
Deletes array of pointers, if allocated previously. Does not delete the associated Data objects.
Definition at line 176 of file GPArray.h.
References Util::Memory::deallocate().
Member Function Documentation
template<typename Data> GPArray< Data > & Util::GPArray< Data >::operator= (const GPArray< Data > & other)
Assignment, element by element.
Preconditions:
Both this and other GPArrays must be allocated.
Capacity of this GPArray must be >= size of RHS GPArray.
Parameters:
other the rhs GPArray
Definition at line 160 of file GPArray.h.
References Util::PArray< Data >::size_.
template<typename Data> void Util::GPArray< Data >::append (Data & data)
Append an element to the end of the sequence.
Resizes array if space is inadequate.
Parameters:
data Data object to be appended
Definition at line 235 of file GPArray.h.
Referenced by DdMd::Exchanger::addGroupExchanger().
template<typename Data > void Util::GPArray< Data >::reserve (int capacity)
Reserve memory for specified number of elements.
Resizes and copies array if requested capacity is less than the current capacity. Does nothing if requested capacity is greater than current capacity.
Parameters:
capacity number of elements for which to reserve space.
Definition at line 189 of file GPArray.h.
References UTIL_THROW.
Referenced by DdMd::Exchanger::Exchanger(), and DdMd::GroupStorage< N >::GroupStorage().
template<typename Data > void Util::GPArray< Data >::deallocate ()
Deallocate (delete) underlying array of pointers.
Definition at line 221 of file GPArray.h.
template<typename Data > void Util::GPArray< Data >::clear () [inline]
Reset to empty state.
Definition at line 268 of file GPArray.h.
template<class Data > bool Util::GPArray< Data >::isAllocated () const [inline]
Is this GPArray allocated?
Definition at line 275 of file GPArray.h.
The documentation for this class was generated from the following file:
GPArray.h