Simpatico: DdMd::GroupDistributor< N > Class Template Reference
DdMd::GroupDistributor< N > Class Template Reference
MPI Communication
Detailed Description
template<int N>
class DdMd::GroupDistributor< N >
Class template for distributing Group<N> objects among processors.
A GroupDistributor is used to distribute items among processors during startup, when the master process must read a configuration file. Each ConfigIo has a GroupDistributor for each group type.
Precondition:
The usage pattern described below must be invoked after all local atoms are distributed, but when there are no ghosts.
Usage:
GroupDistributor  distributor;
GroupStorage<N>   groupStorage;
DArray<int>       atomOwners;
Group<N>*         ptr;
std::ifstream file
if (rank = 0) {  // If master processor
   distributor.setup();
   // Read from file
   for (i = 0; i < nGroup; ++i) {
       ptr = distributor.newPtr();
       // Read properties of Group<N> *ptr from file
       file >> ptr->position();
       // ...
       // Cache active Group<N> for sending.
       distributor.add();
   }
   // Send all remaining.
   distributor.send();
} else { // If not master processor
   distributor.receive();
}
The add(groupStorage) method can send items if required by memory limits, and the send() method then sends all remaining groups.
Posconditions:
At the end end of the above pattern, each processor has a copy of every Group that contains one or more Atoms that it owns.
All pointers to local atoms are set, and pointer to missing atoms are set to null. Missing atoms will later be assigned to ghosts.
Definition at line 86 of file GroupDistributor.h.
#include <GroupDistributor.h>
Public Member Functions
GroupDistributor ()
Constructor.
~GroupDistributor ()
Destructor.
void associate (Domain &domain, AtomStorage &atomStorage, GroupStorage< N > &groupStorage, Buffer &buffer)
Create required associations with related objects.
void setup ()
Initialize Buffer for sending.
void initialize (int cacheCapacity=-1)
Set cacheCapacity, allocate memory and initialize object.
virtual void readParameters (std::istream &in)
Read cacheCapacity, allocate memory and initialize object.
Group< N > * newPtr ()
Returns pointer an address available for a new Group<N>.
void add ()
Add a group to the cache for sending, send if necessary.
void send ()
Send all atoms that have not be sent previously.
void receive ()
Receive all atoms sent by master processor.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
void allocate ()
Allocate memory and initialize object.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Constructor & Destructor Documentation
template<int N> DdMd::GroupDistributor< N >::GroupDistributor ()
Constructor.
Definition at line 27 of file GroupDistributor.tpp.
References Util::ParamComposite::setClassName().
template<int N> DdMd::GroupDistributor< N >::~GroupDistributor ()
Destructor.
Definition at line 45 of file GroupDistributor.tpp.
Member Function Documentation
template<int N> void DdMd::GroupDistributor< N >::associate (Domain & domain, AtomStorage & atomStorage, GroupStorage< N > & groupStorage, Buffer & buffer)
Create required associations with related objects.
Parameters
domain associated Domain object defines the processor grid
atomStorage associated AtomStorage manages memory for atoms
groupStorage associated GroupStorage manages memory for groups
buffer associated buffer provides memory for communication
Definition at line 52 of file GroupDistributor.tpp.
Referenced by DdMd::ConfigIo::associate().
template<int N> void DdMd::GroupDistributor< N >::setup ()
Initialize Buffer for sending.
Definition at line 102 of file GroupDistributor.tpp.
template<int N> void DdMd::GroupDistributor< N >::initialize (int cacheCapacity = -1)
Set cacheCapacity, allocate memory and initialize object.
This method sets cacheCapacity from file, and then goes through the same initialization steps as readParam.
Parameters
cacheCapacity max number of groups cached for sending
Definition at line 67 of file GroupDistributor.tpp.
Referenced by DdMd::ConfigIo::initialize(), DdMd::ConfigIo::load(), and DdMd::ConfigIo::readParameters().
template<int N> void DdMd::GroupDistributor< N >::readParameters (std::istream & in) virtual
Read cacheCapacity, allocate memory and initialize object.
This method and setParam both allocate all required memory and initialize the GroupDistributor. Memory for a temporary read cache is alocated only on the master.
Preconditions: The initialize method must have been called, the Buffer must be allocated, and the Domain must be initialized.
Parameters
in input stream from which parameter is read.
Reimplemented from Util::ParamComposite.
Definition at line 77 of file GroupDistributor.tpp.
template<int N> Group< N > * DdMd::GroupDistributor< N >::newPtr ()
Returns pointer an address available for a new Group<N>.
This method should be called only by the master processor. It returns the address within the internal cache for a new Group<N> object. Each call to newPtr() must be followed by a matching call to add().
Returns
address for a new Group<N> object.
Definition at line 114 of file GroupDistributor.tpp.
References UTIL_THROW.
template<int N> void DdMd::GroupDistributor< N >::add ()
Add a group to the cache for sending, send if necessary.
If the addition of this atom to the cache would make the cache full, this method broadcasts the cache to all processors.
Definition at line 156 of file GroupDistributor.tpp.
References DdMd::Group< N >::pack(), and UTIL_THROW.
template<int N> void DdMd::GroupDistributor< N >::send ()
Send all atoms that have not be sent previously.
This method should be called only by the master processor, after completion of a loop over all atoms to be sent.
Definition at line 206 of file GroupDistributor.tpp.
References UTIL_THROW.
template<int N> void DdMd::GroupDistributor< N >::receive ()
Receive all atoms sent by master processor.
This should be called by all processes except the master.
Definition at line 269 of file GroupDistributor.tpp.
References DdMd::Group< N >::unpack(), and UTIL_THROW.
template<int N> void DdMd::GroupDistributor< N >::allocate () protected
Allocate memory and initialize object.
This method allocates all required memory and leaves the object ready for use. It is called by setParam and readParam.
Definition at line 87 of file GroupDistributor.tpp.
References UTIL_THROW.
The documentation for this class was generated from the following files:
GroupDistributor.h
GroupDistributor.tpp