Simpatico: DdMd::Domain Class Reference
DdMd::Domain Class Reference
MPI Communication
Detailed Description
Decomposition of the system into domains associated with processors.
Definition at line 30 of file Domain.h.
#include <Domain.h>
Public Member Functions
Domain ()
Constructor.
virtual ~Domain ()
Destructor.
void setGridCommunicator (MPI::Intracomm &communicator)
Set the grid communicator.
void setBoundary (Boundary &boundary)
Set the associated Boundary object.
virtual void readParameters (std::istream &in)
Read parameters and initialize.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
const Grid & grid () const
Return processor Grid by const reference.
int gridCoordinate (int i) const
Get coordinate of processor within grid in specified direction.
int gridDimension (int i) const
Get dimension of processor grid in specified direction.
bool gridIsPeriodic (int i) const
Is the grid periodic in the specified direction?
int gridRank () const
Get rank of this processor in the processor grid.
bool isMaster () const
Is this the master processor (gridRank == 0) ?
int sourceRank (int i, int j) const
Rank of the processor from which to receive for transfer (i, j).
int destRank (int i, int j) const
Rank of the processor to which to send for transfer (i, j).
int shift (int i, int j) const
Shift to be applied to sent coordinates in transfer (i, j).
MPI::Intracomm & communicator () const
Return Cartesian communicator by reference.
double domainBound (int i, int j) const
Get one boundary of the domain owned by this processor.
int ownerRank (const Vector &position) const
Return rank of the processor whose domain contains a position.
bool isInDomain (const Vector &position) const
Is a position in the domain owned by this processor?
bool isInitialized () const
Has this Domain been initialized by calling readParam?
bool hasBoundary () const
Has an associated Boundary been set?
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
std::string className () const
Get class name string.
virtual void readParam (std::istream &in)
Read a parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an archive.
void resetParam ()
Resets ParamComposite to its empty state.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add a new Param < Type > object, and read its value.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add a C array parameter, and read its elements.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and read its elements.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n)
Add and read a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
Begin & readBegin (std::istream &in, const char *label)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a child ParamComposite.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add a new Param < Type > object, and load its value.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add a C array parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and load its elements.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n)
Add and load a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a DMatrix < Type > C two-dimensional matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
template<typename Type >
ScalarParam< Type > & add (const char *label, Type &value)
Add a new Param < Type > object to the format array.
template<typename Type >
CArrayParam< Type > & addCArray (const char *label, Type *value, int n)
Add a C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (const char *label, DArray< Type > &array, int n)
Add a DArray<Type> parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (const char *label, FArray< Type, N > &array)
Add a FArray<Type> parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (const char *label, Type *value, int m, int n)
Add a C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & addDMatrix (const char *label, DMatrix< Type > &matrix, int m, int n)
Add a C two-dimensional array parameter.
Begin & addBegin (const char *label)
Add a class label and opening bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Add a new Blank object, representing a blank line.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have a communicator?
MPI::Intracomm & ioCommunicator () const
Get the communicator.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
Constructor & Destructor Documentation
DdMd::Domain::Domain ()
Constructor.
Definition at line 22 of file Domain.cpp.
References Util::ParamComposite::setClassName().
DdMd::Domain::~Domain () virtual
Destructor.
Definition at line 41 of file Domain.cpp.
Member Function Documentation
void DdMd::Domain::setGridCommunicator (MPI::Intracomm & communicator)
Set the grid communicator.
Parameters
communicator Intramcommunicator to be used.
Definition at line 48 of file Domain.cpp.
void DdMd::Domain::setBoundary (Boundary & boundary)
Set the associated Boundary object.
Parameters
boundary Boundary object.
Definition at line 61 of file Domain.cpp.
void DdMd::Domain::readParameters (std::istream & in) virtual
Read parameters and initialize.
Parameters
in parameter input stream
Reimplemented from Util::ParamComposite.
Definition at line 67 of file Domain.cpp.
References hasBoundary(), and UTIL_THROW.
void DdMd::Domain::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 93 of file Domain.cpp.
References hasBoundary(), and UTIL_THROW.
void DdMd::Domain::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 118 of file Domain.cpp.
const Grid & DdMd::Domain::grid () const inline
Return processor Grid by const reference.
Definition at line 267 of file Domain.h.
Referenced by DdMd::AtomDistributor::addAtom(), DdMd::AtomCollector::nextPtr(), and DdMd::AtomDistributor::send().
int DdMd::Domain::gridCoordinate (int i) const inline
Get coordinate of processor within grid in specified direction.
Parameters
i index of Cartesian direction 0 <= i < Dimension
Definition at line 276 of file Domain.h.
int DdMd::Domain::gridDimension (int i) const inline
Get dimension of processor grid in specified direction.
Dimension of processor grid in specified direction.
Parameters
i index of Cartesian direction 0 <= i < Dimension
Definition at line 285 of file Domain.h.
bool DdMd::Domain::gridIsPeriodic (int i) const inline
Is the grid periodic in the specified direction?
Is the grid periodic in a specified direction?
Parameters
i index of Cartesian direction 0 <= i < Dimension
Definition at line 294 of file Domain.h.
int DdMd::Domain::gridRank () const inline
Get rank of this processor in the processor grid.
Definition at line 303 of file Domain.h.
Referenced by DdMd::AtomDistributor::addAtom(), DdMd::AtomDistributor::newAtomPtr(), DdMd::AtomDistributor::receive(), and DdMd::AtomDistributor::send().
bool DdMd::Domain::isMaster () const inline
Is this the master processor (gridRank == 0) ?
Definition at line 312 of file Domain.h.
Referenced by DdMd::NphIntegrator::integrateStep1(), DdMd::NptIntegrator::integrateStep1(), DdMd::NphIntegrator::integrateStep2(), DdMd::NptIntegrator::integrateStep2(), DdMd::AtomCollector::nextPtr(), DdMd::Exchanger::outputStatistics(), DdMd::OutputBoxdim::sample(), DdMd::OutputEnergy::sample(), DdMd::OutputTemperature::sample(), DdMd::OutputPressure::sample(), DdMd::OutputPairEnergies::sample(), DdMd::AtomCollector::send(), and DdMd::AtomCollector::setup().
int DdMd::Domain::sourceRank (int i, int j) const inline
Rank of the processor from which to receive for transfer (i, j).
Parameters
i index of Cartesian direction 0 <= i < Dimension
j index for positive (j = 0) or negative transfer (j = 1)
Definition at line 321 of file Domain.h.
Referenced by DdMd::Exchanger::reverseUpdate(), and DdMd::Exchanger::update().
int DdMd::Domain::destRank (int i, int j) const inline
Rank of the processor to which to send for transfer (i, j).
Parameters
i index of Cartesian direction 0 <= i < Dimension
j index for positive (j = 0) or negative transfer (j = 1)
Definition at line 330 of file Domain.h.
Referenced by DdMd::Exchanger::reverseUpdate(), and DdMd::Exchanger::update().
int DdMd::Domain::shift (int i, int j) const inline
Shift to be applied to sent coordinates in transfer (i, j).
When communicating an atomic position that is stored on the sending processsor as x = {x[0], x[1], x[2]}, the value of coordinate x[i] should be sent as x[i] - shift(i, j)*length[i] during transfer (i, j), where length[i] is the length of the unit cell in direction i.
Parameters
i index of Cartesian direction 0 <= i < Dimension
j index for positive (j = 0) or negative (j = 1) transfer
Definition at line 339 of file Domain.h.
Referenced by DdMd::Exchanger::update().
MPI::Intracomm & DdMd::Domain::communicator () const inline
Return Cartesian communicator by reference.
Definition at line 256 of file Domain.h.
Referenced by DdMd::AtomDistributor::addAtom(), DdMd::NptIntegrator::integrateStep2(), DdMd::Integrator::isExchangeNeeded(), DdMd::SerializeConfigIo::loadConfig(), DdMd::AtomDistributor::newAtomPtr(), DdMd::AtomCollector::nextPtr(), DdMd::Integrator::outputStatistics(), DdMd::Exchanger::outputStatistics(), DdMd::DdMdConfigIo::readConfig(), DdMd::DdMdOrderedConfigIo::readConfig(), DdMd::LammpsConfigIo::readConfig(), DdMd::AtomDistributor::receive(), DdMd::Exchanger::reverseUpdate(), DdMd::StructureFactor::sample(), DdMd::AtomCollector::send(), DdMd::AtomDistributor::send(), and DdMd::Exchanger::update().
double DdMd::Domain::domainBound (int i, int j) const
Get one boundary of the domain owned by this processor.
This processor owns a domain in which coordinate x[i] lies in the range domainBound(i, 0) < x[i] < domainBound(i, 1) for all 0 <= i < Dimension.
Parameters
i index of Cartesian direction 0 <= i < Dimension
j index for lower (j=0) or upper (j=1) boundary.
Returns
boundary coordinate value
Definition at line 193 of file Domain.cpp.
Referenced by DdMd::PairPotential::buildCellList().
int DdMd::Domain::ownerRank (const Vector & position) const
Return rank of the processor whose domain contains a position.
Parameters
position position vector
Returns
rank of processor that owns this position.
Definition at line 215 of file Domain.cpp.
References Util::Dimension, Util::Log::file(), Util::Grid::rank(), and UTIL_THROW.
Referenced by DdMd::AtomDistributor::addAtom(), and DdMd::AtomDistributor::receive().
bool DdMd::Domain::isInDomain (const Vector & position) const
Is a position in the domain owned by this processor?
Parameters
position position vector
Returns
true if within the domain, false otherwise.
Definition at line 245 of file Domain.cpp.
References Util::Dimension.
bool DdMd::Domain::isInitialized () const inline
Has this Domain been initialized by calling readParam?
Definition at line 348 of file Domain.h.
Referenced by DdMd::AtomDistributor::addAtom(), DdMd::AtomDistributor::newAtomPtr(), DdMd::AtomCollector::nextPtr(), DdMd::AtomDistributor::receive(), DdMd::AtomCollector::send(), DdMd::AtomDistributor::send(), and DdMd::AtomCollector::setup().
bool DdMd::Domain::hasBoundary () const inline
Has an associated Boundary been set?
Definition at line 354 of file Domain.h.
Referenced by loadParameters(), and readParameters().
The documentation for this class was generated from the following files:
Domain.h
Domain.cpp