Simpatico: McMd::DCDTrajectoryIo Class Reference
McMd::DCDTrajectoryIo Class Reference
Trajectory File IO
Detailed Description
TrajectoryIo for CHARMM ".dcd" data files.
Currently it has only been tested with Hoomd generated trajectory files.
It is assumed that the atoms belonging to all species and molecules of a species occur in the file consecutively.
Definition at line 29 of file DCDTrajectoryIo.h.
#include <DCDTrajectoryIo.h>
Public Member Functions
DCDTrajectoryIo (System &system)
Constructor.
virtual ~DCDTrajectoryIo ()
Destructor.
void readHeader (std::fstream &file)
Read trajectory file header and initialize simulation parameters.
void readFrame (std::fstream &file)
Read a single frame.
Public Member Functions inherited from McMd::TrajectoryIo
TrajectoryIo (System &system)
Constructor.
virtual ~TrajectoryIo ()
Destructor.
virtual void writeHeader (std::fstream &file)
Write trajectory file header.
virtual void writeFrame (std::fstream &file)
Write a single frame.
int nFrames () const
Return number of frames in trajectory file.
Additional Inherited Members
Protected Member Functions inherited from McMd::TrajectoryIo
System & system () const
Get a reference to the parent System.
Simulation & simulation () const
Get a reference to the parent Simulation.
Boundary & boundary () const
Get the Boundary.
Protected Attributes inherited from McMd::TrajectoryIo
int nFrames_
The number of frames in the trajectory file.
Constructor & Destructor Documentation
McMd::DCDTrajectoryIo::DCDTrajectoryIo (System & system)
Constructor.
Definition at line 38 of file DCDTrajectoryIo.cpp.
McMd::DCDTrajectoryIo::~DCDTrajectoryIo () virtual
Destructor.
Definition at line 45 of file DCDTrajectoryIo.cpp.
Member Function Documentation
void McMd::DCDTrajectoryIo::readHeader (std::fstream & file) virtual
Read trajectory file header and initialize simulation parameters.
Parameters
file input file stream.
Reimplemented from McMd::TrajectoryIo.
Definition at line 55 of file DCDTrajectoryIo.cpp.
References McMd::System::addMolecule(), Util::DArray< Data >::allocate(), McMd::Species::capacity(), McMd::Species::nAtom(), McMd::Species::nBond(), McMd::TrajectoryIo::nFrames_, McMd::Simulation::nSpecies(), Util::ArrayStack< Data >::pop(), McMd::Species::reservoir(), McMd::TrajectoryIo::simulation(), McMd::Simulation::species(), McMd::TrajectoryIo::system(), and UTIL_THROW.
void McMd::DCDTrajectoryIo::readFrame (std::fstream & file) virtual
Read a single frame.
Frames are assumed to be read consecutively.
Parameters
file input file stream.
Reimplemented from McMd::TrajectoryIo.
Definition at line 99 of file DCDTrajectoryIo.cpp.
References McMd::Molecule::begin(), McMd::TrajectoryIo::boundary(), McMd::Species::capacity(), Util::Array< Data >::cArray(), McMd::System::molecule(), Util::ArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), McMd::TrajectoryIo::simulation(), McMd::Simulation::species(), McMd::TrajectoryIo::system(), and UTIL_THROW.
The documentation for this class was generated from the following files:
DCDTrajectoryIo.h
DCDTrajectoryIo.cpp