Simpatico: SpAn::AtomMSD Class Reference
SpAn::AtomMSD Class Reference
Analyzers
Detailed Description
Mean-squared displacement of specific atom in molecules of specific species.
Definition at line 26 of file spAn/analyzers/AtomMSD.h.
#include <AtomMSD.h>
Public Member Functions
AtomMSD (Processor &processor)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void setup ()
Determine number of molecules and allocate memory.
virtual void sample (long iStep)
Evaluate end-to-end vectors of all chains, add to ensemble.
virtual void output ()
Output results to file after simulation is completed.
Constructor & Destructor Documentation
SpAn::AtomMSD::AtomMSD (Processor & processor)
Constructor.
Parameters:
processor reference to parent Processor
Definition at line 30 of file spAn/analyzers/AtomMSD.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void SpAn::AtomMSD::readParameters (std::istream & in) [virtual]
Read parameters from file.
Parameters:
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 47 of file spAn/analyzers/AtomMSD.cpp.
References Util::DArray< Data >::allocate(), SpAn::Species::capacity(), SpAn::Species::nAtom(), SpAn::Analyzer::processor(), SpAn::Analyzer::readInterval(), SpAn::Analyzer::readOutputFileName(), Util::MeanSqDispArray< Data >::setParam(), SpAn::Configuration::species(), and UTIL_THROW.
void SpAn::AtomMSD::setup () [virtual]
Determine number of molecules and allocate memory.
Reimplemented from SpAn::Analyzer.
Definition at line 89 of file spAn/analyzers/AtomMSD.cpp.
References SpAn::Species::begin(), SpAn::Configuration::boundary(), Util::MeanSqDispArray< Data >::clear(), Util::ArrayIterator< Data >::notEnd(), SpAn::Analyzer::processor(), Util::MeanSqDispArray< Data >::setNEnsemble(), Util::OrthorhombicBoundary::shift(), SpAn::Species::size(), SpAn::Configuration::species(), and UTIL_THROW.
void SpAn::AtomMSD::sample (long iStep) [virtual]
Evaluate end-to-end vectors of all chains, add to ensemble.
Parameters:
iStep counter for number of steps
Implements SpAn::Analyzer.
Definition at line 119 of file spAn/analyzers/AtomMSD.cpp.
References SpAn::Species::begin(), SpAn::Configuration::boundary(), Util::Dimension, Util::OrthorhombicBoundary::distanceSq(), SpAn::Analyzer::isAtInterval(), Util::OrthorhombicBoundary::lengths(), Util::ArrayIterator< Data >::notEnd(), SpAn::Analyzer::processor(), Util::MeanSqDispArray< Data >::sample(), Util::OrthorhombicBoundary::shift(), SpAn::Configuration::species(), and UTIL_THROW.
void SpAn::AtomMSD::output () [virtual]
Output results to file after simulation is completed.
Reimplemented from SpAn::Analyzer.
Definition at line 166 of file spAn/analyzers/AtomMSD.cpp.
References Util::MeanSqDispArray< Data >::bufferCapacity(), SpAn::Processor::fileMaster(), Util::MeanSqDispArray< Data >::nEnsemble(), Util::MeanSqDispArray< Data >::nSample(), Util::FileMaster::openOutputFile(), Util::MeanSqDispArray< Data >::output(), SpAn::Analyzer::outputFileName(), SpAn::Analyzer::processor(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
spAn/analyzers/AtomMSD.h
spAn/analyzers/AtomMSD.cpp