Simpatico: McMd::McMove Class Reference
McMd::McMove Class Reference
McMd namespace » Monte Carlo Moves
Detailed Description
McMove is an abstract base class for Monte Carlo moves.
The virtual move() method must generate a trial move, decide whether to accept or reject it, and update the associated System or Systems if it is accepted.
Definition at line 31 of file McMove.h.
#include <McMove.h>
Public Member Functions
McMove (Simulation &simulation)
Constructor.
virtual ~McMove ()
Destructor.
virtual void readParameters (std::istream &in)
Read required parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void setProbability (double probability)
Set the probability for this McMove.
virtual void setup ()
Setup before the beginning of each simulation run.
virtual bool move ()
Generate, attempt, and accept or reject a Monte Carlo move.
double probability () const
Return probability for this McMove.
long nAttempt () const
Return number of moves that have been attempted.
long nAccept () const
Return number of moves that have been accepted.
virtual void output ()
Output statistics for this move (called at the end of the simulation)
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
void incrementNAttempt ()
Increment the number of attempted moves.
void incrementNAccept ()
Increment the number of accepted moves.
Simulation & simulation ()
Get parent Simulation object.
Random & random ()
Get Random number generator of parent Simulation.
void readProbability (std::istream &in)
Read the probability from file.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Constructor & Destructor Documentation
McMd::McMove::McMove (Simulation & simulation)
Constructor.
Parameters
simulation parent Simulation object.
Definition at line 20 of file McMove.cpp.
McMd::McMove::~McMove () virtual
Destructor.
Empty default implementation.
Definition at line 30 of file McMove.cpp.
Member Function Documentation
void McMd::McMove::readParameters (std::istream & in) virtual
Read required parameters from file.
Empty default implementation.
Reimplemented from Util::ParamComposite.
Reimplemented in McMd::MdMove, McMd::CfbLinear, McMd::DpdMove, McMd::HybridNphMdMove, McMd::CfbEndBase, McMd::HybridMdMove, McMd::CfbRebridgeBase, McMd::CfbReptateMove, McMd::EndSwapMove, McMd::CfbRingRebridgeMove, McMd::CfbReptationMove, McMd::CfbRebridgeMove, McMd::CfbLinearEndMove, McMd::RingTetraRebridgeMove, McMd::RigidDisplaceMove, McMd::CfbEndMove, McMd::RingOctaRebridgeMove, McMd::CfbDoubleRebridgeMove, McMd::AtomDisplaceMove, McMd::HomopolymerSemiGrandMove, McMd::GcSliplinkMove, McMd::Sliplinker, McMd::SliplinkerAll, McMd::SliplinkerEnd, and McMd::SliplinkMove.
Definition at line 36 of file McMove.cpp.
void McMd::McMove::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Reimplemented in McMd::MdMove, McMd::CfbLinear, McMd::DpdMove, McMd::HybridNphMdMove, McMd::HybridMdMove, McMd::RingTetraRebridgeMove, McMd::CfbRebridgeBase, McMd::CfbReptateMove, McMd::EndSwapMove, McMd::CfbRingRebridgeMove, McMd::CfbReptationMove, McMd::CfbRebridgeMove, McMd::CfbLinearEndMove, McMd::RigidDisplaceMove, McMd::CfbEndMove, McMd::RingOctaRebridgeMove, McMd::CfbDoubleRebridgeMove, McMd::AtomDisplaceMove, and McMd::HomopolymerSemiGrandMove.
Definition at line 48 of file McMove.cpp.
Referenced by McMd::HomopolymerSemiGrandMove::loadParameters(), McMd::AtomDisplaceMove::loadParameters(), McMd::CfbDoubleRebridgeMove::loadParameters(), McMd::RingOctaRebridgeMove::loadParameters(), McMd::CfbEndMove::loadParameters(), McMd::RigidDisplaceMove::loadParameters(), McMd::CfbLinearEndMove::loadParameters(), McMd::CfbRebridgeMove::loadParameters(), McMd::CfbReptationMove::loadParameters(), McMd::CfbRingRebridgeMove::loadParameters(), McMd::EndSwapMove::loadParameters(), McMd::CfbReptateMove::loadParameters(), McMd::RingTetraRebridgeMove::loadParameters(), McMd::HybridMdMove::loadParameters(), McMd::HybridNphMdMove::loadParameters(), McMd::DpdMove::loadParameters(), and McMd::MdMove::loadParameters().
void McMd::McMove::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Reimplemented in McMd::MdMove, McMd::CfbLinear, McMd::DpdMove, McMd::HybridNphMdMove, McMd::HybridMdMove, McMd::RingTetraRebridgeMove, McMd::CfbRebridgeBase, McMd::CfbReptateMove, McMd::EndSwapMove, McMd::CfbRingRebridgeMove, McMd::CfbReptationMove, McMd::CfbRebridgeMove, McMd::CfbLinearEndMove, McMd::RigidDisplaceMove, McMd::CfbEndMove, McMd::RingOctaRebridgeMove, McMd::CfbDoubleRebridgeMove, McMd::AtomDisplaceMove, and McMd::HomopolymerSemiGrandMove.
Definition at line 58 of file McMove.cpp.
Referenced by McMd::HomopolymerSemiGrandMove::save(), McMd::AtomDisplaceMove::save(), McMd::CfbDoubleRebridgeMove::save(), McMd::RingOctaRebridgeMove::save(), McMd::CfbEndMove::save(), McMd::RigidDisplaceMove::save(), McMd::CfbLinearEndMove::save(), McMd::CfbRebridgeMove::save(), McMd::CfbReptationMove::save(), McMd::CfbRingRebridgeMove::save(), McMd::EndSwapMove::save(), McMd::CfbReptateMove::save(), McMd::RingTetraRebridgeMove::save(), McMd::HybridMdMove::save(), McMd::HybridNphMdMove::save(), McMd::DpdMove::save(), and McMd::MdMove::save().
void McMd::McMove::setProbability (double probability) inline
Set the probability for this McMove.
Parameters
probability Probability of this move being chosen.
Definition at line 221 of file McMove.h.
void McMd::McMove::setup () virtual
Setup before the beginning of each simulation run.
This method zeros the statistical accumulators nAttempt and nAccept. Derived class implementations should complete any other initialization that is required at the beginning of each simulation run within a sequence of several such runs.
Reimplemented in McMd::DpdMove, and McMd::CfbRebridgeBase.
Definition at line 68 of file McMove.cpp.
bool McMd::McMove::move () virtual
Generate, attempt, and accept or reject a Monte Carlo move.
Implementations of this by subclasses should:
Generate a move (e.g., choose new atomic positions)
Decide to accept or reject (use random::metropolis)
Implement the move if accepted
Trivial default implemention always returns false.
Returns
true if accepted, false if rejected
Reimplemented in McMd::DpdMove, McMd::MdMove, McMd::HybridNphMdMove, McMd::RigidDisplaceMove, McMd::HybridMdMove, McMd::CfbReptateMove, McMd::EndSwapMove, McMd::CfbRingRebridgeMove, McMd::CfbReptationMove, McMd::HomopolymerSemiGrandMove, McMd::CfbRebridgeMove, McMd::CfbLinearEndMove, McMd::CfbEndMove, McMd::RingOctaRebridgeMove, McMd::CfbDoubleRebridgeMove, McMd::AtomDisplaceMove, McMd::RingTetraRebridgeMove, McMd::GcSliplinkMove, McMd::Sliplinker, McMd::SliplinkerAll, McMd::SliplinkerEnd, and McMd::SliplinkMove.
Definition at line 77 of file McMove.cpp.
Referenced by McMd::McSimulation::simulate().
double McMd::McMove::probability () const inline
Return probability for this McMove.
Definition at line 215 of file McMove.h.
long McMd::McMove::nAttempt () const inline
Return number of moves that have been attempted.
Definition at line 177 of file McMove.h.
long McMd::McMove::nAccept () const inline
Return number of moves that have been accepted.
Definition at line 183 of file McMove.h.
void McMd::McMove::output () virtual
Output statistics for this move (called at the end of the simulation)
Reimplemented in McMd::CfbReptateMove, and McMd::CfbReptationMove.
Definition at line 86 of file McMove.cpp.
void McMd::McMove::incrementNAttempt () inline protected
Increment the number of attempted moves.
Definition at line 191 of file McMove.h.
Referenced by McMd::GcSliplinkMove::move(), McMd::Sliplinker::move(), McMd::SliplinkerAll::move(), McMd::SliplinkerEnd::move(), McMd::SliplinkMove::move(), McMd::RingTetraRebridgeMove::move(), McMd::AtomDisplaceMove::move(), McMd::CfbDoubleRebridgeMove::move(), McMd::RingOctaRebridgeMove::move(), McMd::CfbEndMove::move(), McMd::CfbLinearEndMove::move(), McMd::CfbRebridgeMove::move(), McMd::HomopolymerSemiGrandMove::move(), McMd::CfbReptationMove::move(), McMd::EndSwapMove::move(), McMd::CfbRingRebridgeMove::move(), McMd::CfbReptateMove::move(), McMd::HybridMdMove::move(), McMd::RigidDisplaceMove::move(), McMd::HybridNphMdMove::move(), McMd::MdMove::move(), and McMd::DpdMove::move().
void McMd::McMove::incrementNAccept () inline protected
Increment the number of accepted moves.
Definition at line 197 of file McMove.h.
Referenced by McMd::GcSliplinkMove::move(), McMd::Sliplinker::move(), McMd::SliplinkerAll::move(), McMd::SliplinkerEnd::move(), McMd::SliplinkMove::move(), McMd::RingTetraRebridgeMove::move(), McMd::AtomDisplaceMove::move(), McMd::CfbDoubleRebridgeMove::move(), McMd::RingOctaRebridgeMove::move(), McMd::CfbEndMove::move(), McMd::CfbLinearEndMove::move(), McMd::CfbRebridgeMove::move(), McMd::HomopolymerSemiGrandMove::move(), McMd::CfbReptationMove::move(), McMd::EndSwapMove::move(), McMd::CfbRingRebridgeMove::move(), McMd::CfbReptateMove::move(), McMd::HybridMdMove::move(), McMd::RigidDisplaceMove::move(), McMd::HybridNphMdMove::move(), McMd::MdMove::move(), and McMd::DpdMove::move().
Simulation & McMd::McMove::simulation () inline protected
Get parent Simulation object.
Definition at line 203 of file McMove.h.
Referenced by McMd::HybridMdMove::HybridMdMove(), McMd::HybridNphMdMove::HybridNphMdMove(), McMd::HomopolymerSemiGrandMove::loadParameters(), McMd::CfbDoubleRebridgeMove::loadParameters(), McMd::CfbEndMove::loadParameters(), McMd::RigidDisplaceMove::loadParameters(), McMd::RingOctaRebridgeMove::loadParameters(), McMd::CfbRebridgeMove::loadParameters(), McMd::CfbReptationMove::loadParameters(), McMd::CfbRingRebridgeMove::loadParameters(), McMd::EndSwapMove::loadParameters(), McMd::CfbReptateMove::loadParameters(), McMd::RingTetraRebridgeMove::loadParameters(), McMd::SliplinkerAll::move(), McMd::Sliplinker::move(), McMd::SliplinkerEnd::move(), McMd::HybridMdMove::move(), McMd::HybridNphMdMove::move(), McMd::HomopolymerSemiGrandMove::readParameters(), McMd::CfbDoubleRebridgeMove::readParameters(), McMd::CfbEndMove::readParameters(), McMd::RingOctaRebridgeMove::readParameters(), McMd::RigidDisplaceMove::readParameters(), McMd::RingTetraRebridgeMove::readParameters(), McMd::CfbRebridgeMove::readParameters(), McMd::CfbReptationMove::readParameters(), McMd::EndSwapMove::readParameters(), McMd::CfbRingRebridgeMove::readParameters(), McMd::CfbReptateMove::readParameters(), and McMd::CfbLinear::~CfbLinear().
Random & McMd::McMove::random () inline protected
Get Random number generator of parent Simulation.
Definition at line 209 of file McMove.h.
Referenced by McMd::CfbLinear::addAtom(), McMd::CfbEndBase::addEndAtom(), McMd::CfbRebridgeBase::addMiddleAtom(), McMd::CfbLinear::deleteAtom(), McMd::CfbEndBase::deleteEndAtom(), McMd::CfbRebridgeBase::deleteMiddleAtom(), McMd::GcSliplinkMove::move(), McMd::SliplinkerEnd::move(), McMd::Sliplinker::move(), McMd::SliplinkerAll::move(), McMd::SliplinkMove::move(), McMd::RingTetraRebridgeMove::move(), McMd::AtomDisplaceMove::move(), McMd::CfbDoubleRebridgeMove::move(), McMd::CfbEndMove::move(), McMd::RingOctaRebridgeMove::move(), McMd::CfbLinearEndMove::move(), McMd::CfbRebridgeMove::move(), McMd::HomopolymerSemiGrandMove::move(), McMd::CfbReptationMove::move(), McMd::EndSwapMove::move(), McMd::CfbRingRebridgeMove::move(), McMd::CfbReptateMove::move(), McMd::HybridMdMove::move(), McMd::HybridNphMdMove::move(), McMd::RigidDisplaceMove::move(), McMd::RingOctaRebridgeMove::scanBridge(), and McMd::RingTetraRebridgeMove::scanBridge().
void McMd::McMove::readProbability (std::istream & in) protected
Read the probability from file.
Definition at line 42 of file McMove.cpp.
Referenced by McMd::GcSliplinkMove::readParameters(), McMd::SliplinkerAll::readParameters(), McMd::SliplinkerEnd::readParameters(), McMd::SliplinkMove::readParameters(), McMd::HomopolymerSemiGrandMove::readParameters(), McMd::AtomDisplaceMove::readParameters(), McMd::CfbDoubleRebridgeMove::readParameters(), McMd::RingOctaRebridgeMove::readParameters(), McMd::RigidDisplaceMove::readParameters(), McMd::CfbEndMove::readParameters(), McMd::RingTetraRebridgeMove::readParameters(), McMd::CfbLinearEndMove::readParameters(), McMd::CfbRebridgeMove::readParameters(), McMd::CfbReptationMove::readParameters(), McMd::CfbRingRebridgeMove::readParameters(), McMd::EndSwapMove::readParameters(), McMd::CfbReptateMove::readParameters(), McMd::HybridMdMove::readParameters(), McMd::HybridNphMdMove::readParameters(), McMd::DpdMove::readParameters(), and McMd::MdMove::readParameters().
The documentation for this class was generated from the following files:
McMove.h
McMove.cpp