Simpatico: Tools::TrajectoryReader Class Reference
Tools::TrajectoryReader Class Reference
Trajectory File Readers
Detailed Description
Abstract trajectory file reader.
Each concrete subclass of TrajectoryReader implements a specific trajectory file format.
Definition at line 27 of file TrajectoryReader.h.
#include <TrajectoryReader.h>
Public Member Functions
TrajectoryReader (Configuration &configuration, bool isBinary=false)
Constructor.
virtual ~TrajectoryReader ()
Destructor.
bool isBinary () const
Is the file format binary (true) or text (false)?
virtual void readHeader (std::ifstream &file)
Read a header (if any).
virtual bool readFrame (std::ifstream &file)=0
Read a frame.
Protected Member Functions
Configuration & configuration ()
Return parent Configuraiton by reference.
Constructor & Destructor Documentation
Tools::TrajectoryReader::TrajectoryReader (Configuration & configuration, bool isBinary = false)
Constructor.
Parameters:
configuration parent Configuration object
isBinary Is the trajectory file a binary format?
Definition at line 18 of file TrajectoryReader.cpp.
References Util::ParamComposite::setClassName().
Tools::TrajectoryReader::~TrajectoryReader () [virtual]
Destructor.
Definition at line 26 of file TrajectoryReader.cpp.
Member Function Documentation
bool Tools::TrajectoryReader::isBinary () const [inline]
Is the file format binary (true) or text (false)?
Definition at line 86 of file TrajectoryReader.h.
virtual void Tools::TrajectoryReader::readHeader (std::ifstream & file) [inline, virtual]
Read a header (if any).
Parameters:
file input file
Reimplemented in Tools::DdMdTrajectoryReader.
Definition at line 55 of file TrajectoryReader.h.
Referenced by Tools::Processor::analyzeTrajectory().
virtual bool Tools::TrajectoryReader::readFrame (std::ifstream & file) [pure virtual]
Read a frame.
Parameters:
file input file
Returns:
true if a frame was found, false if eof
Implemented in Tools::DdMdTrajectoryReader, and Tools::LammpsDumpReader.
Referenced by Tools::Processor::analyzeTrajectory().
Configuration& Tools::TrajectoryReader::configuration () [inline, protected]
Return parent Configuraiton by reference.
Definition at line 70 of file TrajectoryReader.h.
Referenced by Tools::LammpsDumpReader::readFrame(), and Tools::DdMdTrajectoryReader::readFrame().
The documentation for this class was generated from the following files:
TrajectoryReader.h
TrajectoryReader.cpp