Simpatico: DdMd::Cell Class Reference
DdMd::Cell Class Reference
DdMd namespace » Nonbonded Neighbors
Detailed Description
A single Cell in a CellList.
An initialized Cell has an array of CellAtom objects, a pointer to the next Cell in a linked list, and a pointer to an array of integer offsets to neighboring cells.
A linked list of cells is created by a parent CellList. The method CellList::begin() returns a pointer to the first Cell in the list. This linked list normally contains only the cells with local atoms, and excludes cells of ghost atoms.
The method Cell::getNeighbors() returns an array containing pointers to atoms in this cell and all neighboring cells, with the atoms in in this cell listed first.
Here is an example of code to iterate over all local cells in a CellList, and over all pairs of neighboring atoms:
CellList cellList;                // parent CellList
Cell::NeighborArray neighbors;    // array of Atom* pointers
const Cell* cellPtr;              // pointer to Cell in linked list
Atom*  atom1Ptr;                  // pointer to Atom in this cell.
Atom*  atom2Ptr;                  // pointer to neighbor Atom
// Iterate over cells in list.
cellPtr = cellList.begin();
while (cellPtr) {
   cellPtr->getNeighbors(neighbors);
   // Iterate over atoms in this cell.
   for (i = 0; i < cellPtr->nAtom(); ++i) {
      atom1Ptr = neighbors[i];
      // Iterate over neighbor atoms.
      for (j = 0; j < neighbors.size(); ++j) {
         atom2Ptr = neighbors[j];
      }
   }
}
Definition at line 71 of file ddMd/neighbor/Cell.h.
#include <Cell.h>
Public Types
typedef FSArray< std::pair< int, int >, OffSetArrayCapacity > OffsetArray
An array of strips of relative ids for columns of neighboring cells.
typedef FSArray< CellAtom *, MaxNeighborAtom > NeighborArray
Static array for holding neighbors in a cell list.
Public Member Functions
Cell ()
Constructor.
void setNextCell (Cell &nextCell)
Set the pointer to the next cell in the list.
void setLastCell ()
Set this to be the last cell in the list.
const Cell * nextCellPtr () const
Return a pointer to neighbor cell i.
void setId (int id)
Set id for this Cell.
void setOffsetArray (OffsetArray &offsets)
Set the pointer to an array of integer offsets.
void setIsGhostCell (bool isGhostCell=true)
Mark as a ghost or local cell.
void clear ()
Reset to empty before incrementing capacity.
void incrementCapacity ()
Increment the capacity counter.
CellAtom * initialize (CellAtom *begin)
Associate the Cell with an array of CellAtom objects.
void append (Atom *atomPtr)
Append an Atom to an initialized cell.
int id () const
Get identifier for this Cell.
int nAtom () const
Number of atoms in cell.
int atomCapacity () const
Capacity of array segment.
CellAtom * atomPtr (int i) const
Return a pointer to atom i.
bool isGhostCell () const
Is this a ghost cell?
void getNeighbors (NeighborArray &neighbors, bool reverseUpdateFlag=false) const
Fill an array with pointers to atoms in a cell and neighboring cells.
Static Public Attributes
static const int MaxNeighborAtom = 2000
Maximum possible number of atoms in this an neighboring cells.
static const int MaxNCellCut = 4
Maximum number of cell per cutoff length.
static const int OffSetArrayCapacity = (2*MaxNCellCut + 1)*(2*MaxNCellCut + 1) + 3
Maximum allowed number of neighboring cells.
Member Typedef Documentation
typedef FSArray< std::pair<int,int>, OffSetArrayCapacity> DdMd::Cell::OffsetArray
An array of strips of relative ids for columns of neighboring cells.
Every cell has a pointer to a Cell::OffsetArray, which uses relative cell indices (offsets relative to the cell id of the primary cell) to identify neighboring cells. Each std::pair<int, int> element in in an OffsetArra contains relative addresses for the the first cell (pair.first) and last cell (pair.second) cell in a contiguous strip of cells that could contain atoms that lie within a cutoff length of some point in the primary cell. The contents of the OffsetArray are calculated in the CellList::makeGrid() function.
Definition at line 105 of file ddMd/neighbor/Cell.h.
typedef FSArray<CellAtom*, MaxNeighborAtom> DdMd::Cell::NeighborArray
Static array for holding neighbors in a cell list.
Definition at line 110 of file ddMd/neighbor/Cell.h.
Constructor & Destructor Documentation
DdMd::Cell::Cell ()
Constructor.
Definition at line 15 of file ddMd/neighbor/Cell.cpp.
References setOffsetArray().
Member Function Documentation
void DdMd::Cell::setNextCell (Cell & nextCell)
Set the pointer to the next cell in the list.
Definition at line 30 of file ddMd/neighbor/Cell.cpp.
Referenced by DdMd::CellList::allocate().
void DdMd::Cell::setLastCell ()
Set this to be the last cell in the list.
Definition at line 33 of file ddMd/neighbor/Cell.cpp.
Referenced by DdMd::CellList::allocate().
const Cell * DdMd::Cell::nextCellPtr () const inline
Return a pointer to neighbor cell i.
Definition at line 317 of file ddMd/neighbor/Cell.h.
Referenced by DdMd::PairList::build(), DdMd::PairPotentialImpl< Interaction >::computeEnergy(), and DdMd::PairPotential::nPair().
void DdMd::Cell::setId (int id) inline
Set id for this Cell.
Parameters
id integer identifier for this Cell
Definition at line 258 of file ddMd/neighbor/Cell.h.
void DdMd::Cell::setOffsetArray (OffsetArray & offsets)
Set the pointer to an array of integer offsets.
Parameters
offsets array offsets for strips of neighboring cells
Referenced by Cell().
void DdMd::Cell::setIsGhostCell (bool isGhostCell = true)
Mark as a ghost or local cell.
Definition at line 27 of file ddMd/neighbor/Cell.cpp.
References isGhostCell().
Referenced by DdMd::CellList::allocate().
void DdMd::Cell::clear () inline
Reset to empty before incrementing capacity.
Does not nullify nextCell pointer is isGhostCell bool.
Definition at line 267 of file ddMd/neighbor/Cell.h.
void DdMd::Cell::incrementCapacity () inline
Increment the capacity counter.
This must be called within a loop over atoms, once per atom that belongs in this cell. This loop must completed before initialize is called.
Definition at line 261 of file ddMd/neighbor/Cell.h.
CellAtom * DdMd::Cell::initialize (CellAtom * begin) inline
Associate the Cell with an array of CellAtom objects.
The final capacity of the cell must be known when this method is called. It associate the Cell with a C array of capacity Atom* pointers, starting at position begin. It returns a pointer to an element one past the end of this array segment.
Parameters
begin first element in associated array segment.
Returns
end of array segment (element one past the end)
Definition at line 274 of file ddMd/neighbor/Cell.h.
void DdMd::Cell::append (Atom * atomPtr) inline
Append an Atom to an initialized cell.
Definition at line 284 of file ddMd/neighbor/Cell.h.
int DdMd::Cell::id () const inline
Get identifier for this Cell.
Definition at line 295 of file ddMd/neighbor/Cell.h.
Referenced by getNeighbors().
int DdMd::Cell::nAtom () const inline
Number of atoms in cell.
Definition at line 301 of file ddMd/neighbor/Cell.h.
Referenced by DdMd::PairList::build(), DdMd::PairPotentialImpl< Interaction >::computeEnergy(), DdMd::CellList::isValid(), and DdMd::PairPotential::nPair().
int DdMd::Cell::atomCapacity () const inline
Capacity of array segment.
Definition at line 323 of file ddMd/neighbor/Cell.h.
Referenced by DdMd::CellList::isValid().
CellAtom * DdMd::Cell::atomPtr (int i) const inline
Return a pointer to atom i.
Definition at line 307 of file ddMd/neighbor/Cell.h.
Referenced by DdMd::CellList::isValid().
bool DdMd::Cell::isGhostCell () const inline
Is this a ghost cell?
Definition at line 329 of file ddMd/neighbor/Cell.h.
Referenced by getNeighbors(), and setIsGhostCell().
void DdMd::Cell::getNeighbors (NeighborArray & neighbors, bool reverseUpdateFlag = false) const
Fill an array with pointers to atoms in a cell and neighboring cells.
Upon return, the FSArray neighbors contains pointers to all of the atoms in this cell and neighboring cells. The first nAtom() elements contain pointers to atoms in this cell.
To avoid double counting of pairs, the method only returns atoms from neighboring local cells with a cell id greater than this->id(), and from neighboring ghost cells.
Parameters
neighbors Array of pointers to neighbor Atoms
reverseUpdateFlag Is reverse communication enabled?
Definition at line 46 of file ddMd/neighbor/Cell.cpp.
References Util::FSArray< Data, Capacity >::append(), Util::FSArray< Data, Capacity >::clear(), id(), isGhostCell(), and Util::FSArray< Data, Capacity >::size().
Referenced by DdMd::PairList::build(), DdMd::PairPotentialImpl< Interaction >::computeEnergy(), and DdMd::PairPotential::nPair().
Member Data Documentation
const int DdMd::Cell::MaxNeighborAtom = 2000 static
Maximum possible number of atoms in this an neighboring cells.
Definition at line 81 of file ddMd/neighbor/Cell.h.
const int DdMd::Cell::MaxNCellCut = 4 static
Maximum number of cell per cutoff length.
Definition at line 86 of file ddMd/neighbor/Cell.h.
Referenced by DdMd::CellList::allocate().
const int DdMd::Cell::OffSetArrayCapacity = (2*MaxNCellCut + 1)*(2*MaxNCellCut + 1) + 3 static
Maximum allowed number of neighboring cells.
Definition at line 91 of file ddMd/neighbor/Cell.h.
The documentation for this class was generated from the following files:
ddMd/neighbor/Cell.h
ddMd/neighbor/Cell.cpp