Simpatico: McMd::NveVvIntegrator Class Reference
McMd::NveVvIntegrator Class Reference
Molecular Dynamics Integrators
Detailed Description
An NVE Verlet molecular dynamics integrator.
Definition at line 25 of file NveVvIntegrator.h.
#include <NveVvIntegrator.h>
Public Member Functions
NveVvIntegrator (MdSystem &system)
Constructor.
virtual ~NveVvIntegrator ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from file and initialize this MdSystem.
virtual void loadParameters (Serializable::IArchive &ar)
Load the internal state to an archive.
virtual void save (Serializable::OArchive &ar)
Save the internal state to an archive.
virtual void setup ()
Setup private variables before main loop.
virtual void step ()
Take a complete NVE MD integration step.
Constructor & Destructor Documentation
McMd::NveVvIntegrator::NveVvIntegrator (MdSystem & system)
Constructor.
Definition at line 30 of file NveVvIntegrator.cpp.
References Util::ParamComposite::setClassName().
McMd::NveVvIntegrator::~NveVvIntegrator () [virtual]
Destructor.
Definition at line 37 of file NveVvIntegrator.cpp.
Member Function Documentation
void McMd::NveVvIntegrator::readParameters (std::istream & in) [virtual]
Read parameters from file and initialize this MdSystem.
Parameters:
in input file stream.
Reimplemented from Util::ParamComposite.
Definition at line 43 of file NveVvIntegrator.cpp.
References Util::DArray< Data >::allocate(), McMd::MdIntegrator::dt_, McMd::Simulation::nAtomType(), and McMd::MdIntegrator::simulation().
void McMd::NveVvIntegrator::loadParameters (Serializable::IArchive & ar) [virtual]
Load the internal state to an archive.
Parameters:
ar archive object.
Reimplemented from Util::ParamComposite.
Definition at line 53 of file NveVvIntegrator.cpp.
References Util::DArray< Data >::allocate(), McMd::MdIntegrator::dt_, McMd::Simulation::nAtomType(), and McMd::MdIntegrator::simulation().
void McMd::NveVvIntegrator::save (Serializable::OArchive & ar) [virtual]
Save the internal state to an archive.
Parameters:
ar archive object.
Reimplemented from Util::ParamComposite.
Definition at line 64 of file NveVvIntegrator.cpp.
References McMd::MdIntegrator::dt_.
void McMd::NveVvIntegrator::setup () [virtual]
Setup private variables before main loop.
Reimplemented from McMd::MdIntegrator.
Definition at line 73 of file NveVvIntegrator.cpp.
References McMd::Simulation::atomType(), Util::Array< Data >::capacity(), McMd::MdIntegrator::dt_, McMd::AtomType::mass(), and McMd::MdIntegrator::simulation().
void McMd::NveVvIntegrator::step () [virtual]
Take a complete NVE MD integration step.
Implements McMd::MdIntegrator.
Definition at line 97 of file NveVvIntegrator.cpp.
References McMd::System::begin(), McMd::MdPairPotential::buildPairList(), McMd::MdSystem::calculateForces(), McMd::MdIntegrator::dt_, McMd::Atom::force(), Util::Vector::multiply(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), McMd::MdSystem::pairPotential(), McMd::Atom::position(), McMd::MdIntegrator::simulation(), McMd::MdIntegrator::system(), McMd::Atom::typeId(), and McMd::Atom::velocity().
The documentation for this class was generated from the following files:
NveVvIntegrator.h
NveVvIntegrator.cpp