Simpatico: McMd::StressAutoCorr< SystemType > Class Template Reference
McMd::StressAutoCorr< SystemType > Class Template Reference
MC/MD Analyzers
Detailed Description
template<class SystemType>
class McMd::StressAutoCorr< SystemType >
Compute stress autocorrelation for an isotropic system.
Typename SystemType can be McSystem or MdSystem.
Definition at line 28 of file mcMd/analyzers/system/StressAutoCorr.h.
#include <StressAutoCorr.h>
Public Member Functions
StressAutoCorr (SystemType &system)
Constructor.
virtual ~StressAutoCorr ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from file and initialize.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Setup before beginning of loop.
virtual void sample (long iStep)
Sample stress tensor and add to accumulator.
virtual void output ()
Output results to file (parameters and autocorrelation function).
Protected Member Functions
virtual void computeStress (Tensor &stress)=0
Compute total stress tensor.
Constructor & Destructor Documentation
template<class SystemType> McMd::StressAutoCorr< SystemType >::StressAutoCorr (SystemType & system)
Constructor.
Parameters:
system parent SystemType object.
Definition at line 137 of file mcMd/analyzers/system/StressAutoCorr.h.
template<class SystemType > McMd::StressAutoCorr< SystemType >::~StressAutoCorr () [virtual]
Destructor.
Definition at line 151 of file mcMd/analyzers/system/StressAutoCorr.h.
Member Function Documentation
template<class SystemType > void McMd::StressAutoCorr< SystemType >::readParameters (std::istream & in) [virtual]
Read parameters from file and initialize.
Parameters:
in input parameter file
Reimplemented from McMd::Analyzer.
Definition at line 158 of file mcMd/analyzers/system/StressAutoCorr.h.
template<class SystemType > void McMd::StressAutoCorr< SystemType >::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::Analyzer.
Definition at line 176 of file mcMd/analyzers/system/StressAutoCorr.h.
References McMd::Analyzer::loadParameters(), and UTIL_THROW.
template<class SystemType > void McMd::StressAutoCorr< SystemType >::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::Analyzer.
Definition at line 194 of file mcMd/analyzers/system/StressAutoCorr.h.
template<class SystemType > template<class Archive > void McMd::StressAutoCorr< SystemType >::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Analyzer.
Definition at line 204 of file mcMd/analyzers/system/StressAutoCorr.h.
References McMd::Analyzer::serialize().
template<class SystemType > void McMd::StressAutoCorr< SystemType >::setup () [virtual]
Setup before beginning of loop.
Reimplemented from McMd::Analyzer.
Definition at line 216 of file mcMd/analyzers/system/StressAutoCorr.h.
References UTIL_THROW.
template<class SystemType > void McMd::StressAutoCorr< SystemType >::sample (long iStep) [virtual]
Sample stress tensor and add to accumulator.
Parameters:
iStep MD or MC step index
Implements McMd::Analyzer.
Definition at line 228 of file mcMd/analyzers/system/StressAutoCorr.h.
References Util::Tensor::add(), and Util::Dimension.
template<class SystemType > void McMd::StressAutoCorr< SystemType >::output () [virtual]
Output results to file (parameters and autocorrelation function).
Reimplemented from McMd::Analyzer.
Definition at line 271 of file mcMd/analyzers/system/StressAutoCorr.h.
template<class SystemType> virtual void McMd::StressAutoCorr< SystemType >::computeStress (Tensor & stress) [protected, pure virtual]
Compute total stress tensor.
Parameters:
stress Stress tensor (on return).
Implemented in McMd::MdStressAutoCorr.
The documentation for this class was generated from the following file:
mcMd/analyzers/system/StressAutoCorr.h