Simpatico: Util::AutoCorr< Data, Product > Class Template Reference
Util::AutoCorr< Data, Product > Class Template Reference
Statistical Accumulators
Detailed Description
template<typename Data, typename Product>
class Util::AutoCorr< Data, Product >
Auto-correlation function for one sequence of Data values.
This class calculates an autocorrelation function for a sequence x(i) of values of a variable or object of type Data. The resulting autocorrelation function is and array of values of type Product, where C(j) = <x(i-j), x(i)>. Here <A,B> denotes an inner product of type Product for objects A and B of type Data.
The meaning of the inner product is defined for various data types b the overloaded function Product product(Data, Data) that is defined for double, complex and Vector data in the product.h file.
The zero value for variables of type Data is returned by the overloaded function void setToZero(Data) method defined in the setToData.h file.
Definition at line 49 of file AutoCorr.h.
#include <AutoCorr.h>
Public Member Functions
AutoCorr ()
Default constructor.
void clear ()
Reset to empty state.
void readParam (std::istream &in)
Read buffer capacity, allocate memory and initialize.
void setParam (int bufferCapacity)
Set buffer capacity, allocate memory and initialize.
void sample (Data value)
Sample a value.
void output (std::ostream &out)
Output the autocorrelation function.
int bufferCapacity () const
Return capacity of history buffer.
int nSample () const
Return number of values sampled thus far.
Data average () const
Return average of all sampled values.
double corrTime () const
Numerical integration of autocorrelation function.
Product autoCorrelation (int t) const
Return autocorrelation at a given lag time.
void pack (char *&current, char *end) const
Pack array into a block of memory.
void unpack (char *&current, char *end)
Unpack array from a block of memory.
int packedSize () const
Return packed size of this AutoCorr.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serial to or from an Archive.
Constructor & Destructor Documentation
template<typename Data , typename Product > Util::AutoCorr< Data, Product >::AutoCorr ()
Default constructor.
Definition at line 187 of file AutoCorr.h.
References Util::setToZero().
Member Function Documentation
template<typename Data , typename Product > void Util::AutoCorr< Data, Product >::clear ()
Reset to empty state.
Definition at line 223 of file AutoCorr.h.
References Util::setToZero().
Referenced by McMd::McStressAutoCorr::setup().
template<typename Data , typename Product > void Util::AutoCorr< Data, Product >::readParam (std::istream & in) [virtual]
Read buffer capacity, allocate memory and initialize.
Parameters:
in input parameter stream.
Reimplemented from Util::ParamComposite.
Definition at line 199 of file AutoCorr.h.
template<typename Data , typename Product > void Util::AutoCorr< Data, Product >::setParam (int bufferCapacity)
Set buffer capacity, allocate memory and initialize.
Parameters:
bufferCapacity maximum number of values in history buffer.
Definition at line 213 of file AutoCorr.h.
Referenced by McMd::McStressAutoCorr::readParam().
template<typename Data, typename Product > void Util::AutoCorr< Data, Product >::sample (Data value)
Sample a value.
Parameters:
value current value
Definition at line 271 of file AutoCorr.h.
References Util::product().
Referenced by McMd::McStressAutoCorr::sample().
template<typename Data , typename Product > void Util::AutoCorr< Data, Product >::output (std::ostream & out)
Output the autocorrelation function.
Parameters:
out output stream.
Definition at line 311 of file AutoCorr.h.
References Util::product().
Referenced by McMd::McStressAutoCorr::output().
template<typename Data , typename Product > int Util::AutoCorr< Data, Product >::bufferCapacity () const
Return capacity of history buffer.
Definition at line 286 of file AutoCorr.h.
Referenced by McMd::McStressAutoCorr::output().
template<typename Data , typename Product > int Util::AutoCorr< Data, Product >::nSample () const
Return number of values sampled thus far.
Definition at line 293 of file AutoCorr.h.
Referenced by McMd::McStressAutoCorr::output().
template<typename Data , typename Product > Data Util::AutoCorr< Data, Product >::average () const
Return average of all sampled values.
Definition at line 300 of file AutoCorr.h.
Referenced by McMd::McStressAutoCorr::output().
template<typename Data , typename Product > double Util::AutoCorr< Data, Product >::corrTime () const
Numerical integration of autocorrelation function.
Definition at line 337 of file AutoCorr.h.
References Util::product(), and Util::setToZero().
template<typename Data , typename Product > Product Util::AutoCorr< Data, Product >::autoCorrelation (int t) const
Return autocorrelation at a given lag time.
Parameters:
t the lag time
Definition at line 371 of file AutoCorr.h.
References Util::product().
template<typename Data , typename Product > void Util::AutoCorr< Data, Product >::pack (char *& current, char * end) const
Pack array into a block of memory.
Parameters:
current pointer to current position in write buffer
end pointer to end (one char* past last) of buffer
Definition at line 394 of file AutoCorr.h.
References UTIL_THROW.
template<typename Data , typename Product > void Util::AutoCorr< Data, Product >::unpack (char *& current, char * end)
Unpack array from a block of memory.
Parameters:
current pointer to current position in read buffer
end pointer to end (one char* past last) of buffer
Definition at line 421 of file AutoCorr.h.
References UTIL_THROW.
template<typename Data , typename Product > int Util::AutoCorr< Data, Product >::packedSize () const
Return packed size of this AutoCorr.
Returns:
required sizeof packed buffer for this AutoCorr, in bytes.
Definition at line 448 of file AutoCorr.h.
template<typename Data , typename Product > template<class Archive > void Util::AutoCorr< Data, Product >::serialize (Archive & ar, const unsigned int version)
Serial to or from an Archive.
Parameters:
ar input or output archive
version id for file version
Reimplemented from Util::ParamComponent.
Definition at line 461 of file AutoCorr.h.
The documentation for this class was generated from the following file:
AutoCorr.h