Simpatico: McMd::McEnergyAverage Class Reference
McMd::McEnergyAverage Class Reference
Diagnostics
Detailed Description
McEnergyAverage averages of total potential energy.
Definition at line 27 of file McEnergyAverage.h.
#include <McEnergyAverage.h>
Public Member Functions
McEnergyAverage (McSystem &system)
Constructor.
virtual void readParam (std::istream &in)
Read parameters and initialize.
virtual void setup ()
Clear accumulator.
virtual void sample (long iStep)
Calculate, analyze and/or output a physical quantity.
virtual void output ()
Output results at end of simulation.
virtual void save (Serializable::OArchiveType &ar)
Save state to binary file archive.
virtual void load (Serializable::IArchiveType &ar)
Load state from a binary file archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
Constructor & Destructor Documentation
McMd::McEnergyAverage::McEnergyAverage (McSystem & system)
Constructor.
Definition at line 26 of file McEnergyAverage.cpp.
Member Function Documentation
void McMd::McEnergyAverage::readParam (std::istream & in) [virtual]
Read parameters and initialize.
Reimplemented from Util::ParamComposite.
Definition at line 37 of file McEnergyAverage.cpp.
References McMd::Diagnostic::fileMaster(), Util::Average::nSamplePerBlock(), McMd::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), McMd::Diagnostic::readInterval(), McMd::Diagnostic::readOutputFileName(), and Util::Average::setNSamplePerBlock().
void McMd::McEnergyAverage::setup () [virtual]
Clear accumulator.
Reimplemented from McMd::Diagnostic.
Definition at line 57 of file McEnergyAverage.cpp.
References Util::Average::clear().
void McMd::McEnergyAverage::sample (long iStep) [virtual]
Calculate, analyze and/or output a physical quantity.
Take an action if iStep is a multiple of interval. If iStep is not a multiple of interval, this method should do nothing and return immediately.
Parameters:
iStep current simulation step index.
Implements McMd::Diagnostic.
Definition at line 63 of file McEnergyAverage.cpp.
References McMd::Diagnostic::isAtInterval(), Util::Average::sample(), and McMd::SystemDiagnostic< McSystem >::system().
void McMd::McEnergyAverage::output () [virtual]
Output results at end of simulation.
Reimplemented from McMd::Diagnostic.
Definition at line 73 of file McEnergyAverage.cpp.
References McMd::Diagnostic::fileMaster(), Util::Average::nSamplePerBlock(), McMd::FileMaster::openOutputFile(), Util::Average::output(), McMd::Diagnostic::outputFileName(), and Util::ParamComposite::writeParam().
void McMd::McEnergyAverage::save (Serializable::OArchiveType & ar) [virtual]
Save state to binary file archive.
Parameters:
ar binary saving (output) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 92 of file McEnergyAverage.cpp.
void McMd::McEnergyAverage::load (Serializable::IArchiveType & ar) [virtual]
Load state from a binary file archive.
Parameters:
ar binary loading (input) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 98 of file McEnergyAverage.cpp.
template<class Archive > void McMd::McEnergyAverage::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Diagnostic.
Definition at line 99 of file McEnergyAverage.h.
References UTIL_THROW.
The documentation for this class was generated from the following files:
McEnergyAverage.h
McEnergyAverage.cpp