Simpatico: McMd::PmcConfigIo Class Reference
McMd::PmcConfigIo Class Reference
Configuration File IO
Detailed Description
ConfigIo for PMC configuration files.
Definition at line 32 of file PmcConfigIo.h.
#include <PmcConfigIo.h>
Public Member Functions
PmcConfigIo (System &system)
Constructor.
virtual ~PmcConfigIo ()
Destructor.
void read (std::istream &in)
Read configuration (particle positions) from file.
void write (std::ostream &out)
Write configuration (particle positions) to file.
Constructor & Destructor Documentation
McMd::PmcConfigIo::PmcConfigIo (System & system)
Constructor.
Definition at line 32 of file PmcConfigIo.cpp.
McMd::PmcConfigIo::~PmcConfigIo () [virtual]
Destructor.
Definition at line 39 of file PmcConfigIo.cpp.
Member Function Documentation
void McMd::PmcConfigIo::read (std::istream & in) [virtual]
Read configuration (particle positions) from file.
Parameters:
in input file stream.
Implements McMd::ConfigIo.
Definition at line 42 of file PmcConfigIo.cpp.
References McMd::Molecule::begin(), Util::Log::file(), McMd::Species::nAtom(), Util::ArrayIterator< Data >::notEnd(), McMd::Species::reservoir(), and UTIL_THROW.
void McMd::PmcConfigIo::write (std::ostream & out) [virtual]
Write configuration (particle positions) to file.
Parameters:
out output file stream.
Implements McMd::ConfigIo.
Definition at line 97 of file PmcConfigIo.cpp.
References Util::ArrayIterator< Data >::notEnd(), and Util::PArrayIterator< Data >::notEnd().
The documentation for this class was generated from the following files:
PmcConfigIo.h
PmcConfigIo.cpp