Simpatico: McMd::McExternalEnergyAverage Class Reference
McMd::McExternalEnergyAverage Class Reference
Diagnostics
Detailed Description
McExternalEnergyAverage averages of total external energy.
Definition at line 29 of file McExternalEnergyAverage.h.
#include <McExternalEnergyAverage.h>
Public Member Functions
McExternalEnergyAverage (McSystem &system)
Constructor.
virtual void readParam (std::istream &in)
Read parameters and initialize.
virtual void setup ()
Clear accumulator.
virtual void sample (long iStep)
Calculate, analyze and/or output a physical quantity.
virtual void output ()
Output results at end of simulation.
virtual void save (Serializable::OArchiveType &ar)
Save state to binary file archive.
virtual void load (Serializable::IArchiveType &ar)
Load state from a binary file archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
Constructor & Destructor Documentation
McMd::McExternalEnergyAverage::McExternalEnergyAverage (McSystem & system)
Constructor.
Definition at line 31 of file McExternalEnergyAverage.cpp.
Member Function Documentation
void McMd::McExternalEnergyAverage::readParam (std::istream & in) [virtual]
Read parameters and initialize.
Reimplemented from Util::ParamComposite.
Definition at line 42 of file McExternalEnergyAverage.cpp.
References McMd::Diagnostic::fileMaster(), McMd::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), McMd::Diagnostic::readInterval(), McMd::Diagnostic::readOutputFileName(), and Util::Average::setNSamplePerBlock().
void McMd::McExternalEnergyAverage::setup () [virtual]
Clear accumulator.
Reimplemented from McMd::Diagnostic.
Definition at line 62 of file McExternalEnergyAverage.cpp.
References Util::Average::clear().
void McMd::McExternalEnergyAverage::sample (long iStep) [virtual]
Calculate, analyze and/or output a physical quantity.
Take an action if iStep is a multiple of interval. If iStep is not a multiple of interval, this method should do nothing and return immediately.
Parameters:
iStep current simulation step index.
Implements McMd::Diagnostic.
Definition at line 68 of file McExternalEnergyAverage.cpp.
References McMd::System::begin(), McMd::ExternalPotential::energy(), McMd::McSystem::externalPotential(), McMd::Diagnostic::isAtInterval(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::Average::sample(), McMd::System::simulation(), and McMd::SystemDiagnostic< McSystem >::system().
void McMd::McExternalEnergyAverage::output () [virtual]
Output results at end of simulation.
Reimplemented from McMd::Diagnostic.
Definition at line 94 of file McExternalEnergyAverage.cpp.
References McMd::Diagnostic::fileMaster(), Util::Average::nSamplePerBlock(), McMd::FileMaster::openOutputFile(), Util::Average::output(), McMd::Diagnostic::outputFileName(), and Util::ParamComposite::writeParam().
void McMd::McExternalEnergyAverage::save (Serializable::OArchiveType & ar) [virtual]
Save state to binary file archive.
Parameters:
ar binary saving (output) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 114 of file McExternalEnergyAverage.cpp.
void McMd::McExternalEnergyAverage::load (Serializable::IArchiveType & ar) [virtual]
Load state from a binary file archive.
Parameters:
ar binary loading (input) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 120 of file McExternalEnergyAverage.cpp.
template<class Archive > void McMd::McExternalEnergyAverage::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Diagnostic.
Definition at line 102 of file McExternalEnergyAverage.h.
References Util::serializeCheck(), and UTIL_THROW.
The documentation for this class was generated from the following files:
McExternalEnergyAverage.h
McExternalEnergyAverage.cpp