Simpatico: McMd::MigratingVanHove Class Reference
McMd::MigratingVanHove Class Reference
Diagnostics
Detailed Description
MigratingVanHove class evaluates VanHove function of a configuration by monitoring its trajectory through different states in space.
MigratingVanHove is derived from Observer class (of Observer design pattern) and is therefore notified of any changes in state by a Notifier (eg. ReplicaExchange, here). Notification is done by invoking the update(sendRecvPair& partners) method, which sends (and receives) all information encapsulated in VanHove function of current state to (and from) its partner (subsequent) state.
Definition at line 51 of file MigratingVanHove.h.
#include <MigratingVanHove.h>
Public Member Functions
MigratingVanHove (System &system)
Constructor.
~MigratingVanHove ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void setup ()
Clear accumulators.
void sample (long iStep)
Add particle pairs to VanHove histogram.
virtual void update (const sendRecvPair &partners)
Send (and receive) VanHove information to (and from) partners.
virtual void output ()
Output results to predefined output file.
virtual void save (Serializable::OArchive &ar)
Save state to archive.
virtual void load (Serializable::IArchive &ar)
Load state from an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
Constructor & Destructor Documentation
McMd::MigratingVanHove::MigratingVanHove (System & system)
Constructor.
Parameters:
system reference to parent System object
Definition at line 42 of file MigratingVanHove.cpp.
References McMd::Simulation::communicator(), Util::ParamComposite::setClassName(), and McMd::System::simulation().
McMd::MigratingVanHove::~MigratingVanHove ()
Destructor.
Definition at line 53 of file MigratingVanHove.cpp.
Member Function Documentation
void McMd::MigratingVanHove::readParameters (std::istream & in) [virtual]
Read parameters from file.
Read parameters from file, and allocate data array.
Input format:
int interval sampling interval
string outputFileName output file base name
DArray<double> atomTypeCoeffs array of type coefficients
int nBuffer number of samples in history
int nWave number of wavevectors
DArray<IntVector> waveIntVectors IntVector wavevectors
Parameters:
in input parameter stream
Reimplemented from McMd::Diagnostic.
Definition at line 57 of file MigratingVanHove.cpp.
References Util::DArray< Data >::allocate(), McMd::Simulation::nAtomType(), McMd::Diagnostic::readInterval(), McMd::Diagnostic::readOutputFileName(), McMd::System::simulation(), and McMd::SystemDiagnostic< System >::system().
void McMd::MigratingVanHove::setup () [virtual]
Clear accumulators.
Reimplemented from McMd::Diagnostic.
Definition at line 86 of file MigratingVanHove.cpp.
References Util::Notifier< Event >::registerObserver().
void McMd::MigratingVanHove::sample (long iStep) [virtual]
Add particle pairs to VanHove histogram.
Increment Structure Factor.
Parameters:
iStep step counter
Implements McMd::Diagnostic.
Definition at line 97 of file MigratingVanHove.cpp.
References McMd::System::begin(), Util::Vector::dot(), Util::Constants::Im, McMd::Diagnostic::isAtInterval(), Util::ConstArrayIterator< Data >::notEnd(), Util::ConstPArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::product(), McMd::System::simulation(), and McMd::SystemDiagnostic< System >::system().
void McMd::MigratingVanHove::update (const sendRecvPair & partners) [virtual]
Send (and receive) VanHove information to (and from) partners.
Parameters:
partners pair of indices specifying partner states
Definition at line 195 of file MigratingVanHove.cpp.
References Util::MemoryOArchive::allocate(), Util::MemoryIArchive::allocate(), Util::MemoryOArchive::iSend(), Util::memorySize(), and Util::MemoryIArchive::recv().
void McMd::MigratingVanHove::output () [virtual]
Output results to predefined output file.
Reimplemented from McMd::Diagnostic.
Definition at line 167 of file MigratingVanHove.cpp.
References Util::Dimension, McMd::Diagnostic::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), and Util::ParamComposite::writeParam().
void McMd::MigratingVanHove::save (Serializable::OArchive & ar) [virtual]
Save state to archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 228 of file MigratingVanHove.cpp.
void McMd::MigratingVanHove::load (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from Util::ParamComposite.
Definition at line 234 of file MigratingVanHove.cpp.
template<class Archive > void McMd::MigratingVanHove::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Diagnostic.
Definition at line 184 of file MigratingVanHove.h.
References Util::serializeCheck(), and UTIL_THROW.
The documentation for this class was generated from the following files:
MigratingVanHove.h
MigratingVanHove.cpp