Simpatico: Util::MeanSqDispArray< Data > Class Template Reference
Util::MeanSqDispArray< Data > Class Template Reference
Accumulators
Detailed Description
template<typename Data>
class Util::MeanSqDispArray< Data >
Mean-squared displacement (MSD) vs.
time for an ensembles of sequences.
This class calculates the mean-squared difference <|x(i) - x(i-j)|^2> for an ensemble of statistically equivalent sequences x(i) of values of a variable of type Data. The meaning of |a - b|^2 is defined for int, double, and Vector data by explicit specializations of the private method double sqDiff(Data&, Data).
Definition at line 41 of file MeanSqDispArray.h.
#include <MeanSqDispArray.h>
Public Member Functions
void readParameters (std::istream &in)
Read parameters, allocate memory and clear history.
void setParam (int ensembleCapacity, int bufferCapacity)
Set parameters, allocate memory, and clear history.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this MeanSqDispArray to/from an archive.
void setNEnsemble (int nEnsemble)
Set actual number of sequences in ensemble.
void clear ()
Reset to empty state.
void sample (const Array< Data > &values)
Sample an array of current values.
void output (std::ostream &out)
Output the autocorrelation function.
int bufferCapacity ()
Return capacity of the history buffer for each sequence.
int nEnsemble ()
Return number of sequences in the ensemble.
int nSample ()
Return number of values sampled from each sequence thus far.
Member Function Documentation
template<typename Data > void Util::MeanSqDispArray< Data >::readParameters (std::istream & in) [virtual]
Read parameters, allocate memory and clear history.
Reads parameters nEnsemble and capacity, allocates memory, and then calls clear().
Parameters:
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 217 of file MeanSqDispArray.h.
template<typename Data > void Util::MeanSqDispArray< Data >::setParam (int ensembleCapacity, int bufferCapacity)
Set parameters, allocate memory, and clear history.
Sets parameters nEnsemble and capacity, allocates memory and then calls clear().
Parameters:
ensembleCapacity number of sequence in ensemble
bufferCapacity number of variable values per sequence
Definition at line 230 of file MeanSqDispArray.h.
Referenced by McMd::AtomMSD::loadParameters(), McMd::ComMSD::loadParameters(), SpAn::AtomMSD::readParameters(), McMd::AtomMSD::readParameters(), and McMd::ComMSD::readParameters().
template<typename Data > void Util::MeanSqDispArray< Data >::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 256 of file MeanSqDispArray.h.
template<typename Data > void Util::MeanSqDispArray< Data >::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 287 of file MeanSqDispArray.h.
template<typename Data > template<class Archive > void Util::MeanSqDispArray< Data >::serialize (Archive & ar, const unsigned int version)
Serialize this MeanSqDispArray to/from an archive.
Parameters:
ar input or output archive
version file version id
Reimplemented from Util::ParamComponent.
Definition at line 272 of file MeanSqDispArray.h.
template<typename Data > void Util::MeanSqDispArray< Data >::setNEnsemble (int nEnsemble)
Set actual number of sequences in ensemble.
Precondition:
readParameters() or setParam() must have been called previously
nEnsemble <= ensembleCapacity
Parameters:
nEnsemble actual number of sequences in ensemble
Definition at line 243 of file MeanSqDispArray.h.
References UTIL_THROW.
Referenced by SpAn::AtomMSD::setup(), McMd::AtomMSD::setup(), and McMd::ComMSD::setup().
template<typename Data > void Util::MeanSqDispArray< Data >::clear ()
Reset to empty state.
Definition at line 294 of file MeanSqDispArray.h.
References Util::setToZero().
Referenced by SpAn::AtomMSD::setup(), McMd::AtomMSD::setup(), and McMd::ComMSD::setup().
template<typename Data> void Util::MeanSqDispArray< Data >::sample (const Array< Data > & values) [inline]
Sample an array of current values.
Parameters:
values Array of current values
Definition at line 340 of file MeanSqDispArray.h.
Referenced by SpAn::AtomMSD::sample(), McMd::AtomMSD::sample(), and McMd::ComMSD::sample().
template<typename Data > void Util::MeanSqDispArray< Data >::output (std::ostream & out)
Output the autocorrelation function.
Definition at line 408 of file MeanSqDispArray.h.
Referenced by SpAn::AtomMSD::output(), McMd::AtomMSD::output(), and McMd::ComMSD::output().
template<typename Data> int Util::MeanSqDispArray< Data >::bufferCapacity () [inline]
Return capacity of the history buffer for each sequence.
Definition at line 130 of file MeanSqDispArray.h.
Referenced by SpAn::AtomMSD::output(), McMd::AtomMSD::output(), and McMd::ComMSD::output().
template<typename Data> int Util::MeanSqDispArray< Data >::nEnsemble () [inline]
Return number of sequences in the ensemble.
Definition at line 136 of file MeanSqDispArray.h.
Referenced by SpAn::AtomMSD::output(), McMd::AtomMSD::output(), and McMd::ComMSD::output().
template<typename Data> int Util::MeanSqDispArray< Data >::nSample () [inline]
Return number of values sampled from each sequence thus far.
Definition at line 142 of file MeanSqDispArray.h.
Referenced by SpAn::AtomMSD::output(), McMd::AtomMSD::output(), and McMd::ComMSD::output().
The documentation for this class was generated from the following file:
MeanSqDispArray.h