Simpatico: Tools::AtomStorage Class Reference
Tools::AtomStorage Class Reference
Tools namespace » Storage
Detailed Description
Container for a set of atoms.
Definition at line 29 of file tools/storage/AtomStorage.h.
#include <AtomStorage.h>
Public Member Functions
AtomStorage ()
Constructor.
~AtomStorage ()
Destructor.
void allocate (int capacity)
Allocate and initialize memory.
Atom * newPtr ()
Return pointer to location for new atom.
void add ()
Finalize addition of atom (allows lookup by id).
void clear ()
Clear all atoms and groups.
Atom * ptr (int id)
Get a pointer to an atom by global id.
void begin (Iterator &iter)
Initialize an iterator for atoms.
int capacity () const
Get atom capacity (maximum id + 1).
int size () const
Get number of atoms.
Constructor & Destructor Documentation
Tools::AtomStorage::AtomStorage ()
Constructor.
Definition at line 16 of file tools/storage/AtomStorage.cpp.
Tools::AtomStorage::~AtomStorage ()
Destructor.
Definition at line 23 of file tools/storage/AtomStorage.cpp.
Member Function Documentation
void Tools::AtomStorage::allocate (int capacity)
Allocate and initialize memory.
Parameters
capacity Maximum number of atoms
Definition at line 29 of file tools/storage/AtomStorage.cpp.
References clear().
Referenced by Tools::Configuration::readParameters().
Atom * Tools::AtomStorage::newPtr ()
Return pointer to location for new atom.
Returns
pointer to location of new atom
Definition at line 39 of file tools/storage/AtomStorage.cpp.
References size(), and UTIL_THROW.
Referenced by Tools::DdMdConfigReader::readConfig(), and Tools::HoomdConfigReader::readConfig().
void Tools::AtomStorage::add ()
Finalize addition of atom (allows lookup by id).
Definition at line 53 of file tools/storage/AtomStorage.cpp.
References Tools::Atom::id, and UTIL_THROW.
Referenced by Tools::DdMdConfigReader::readConfig(), and Tools::HoomdConfigReader::readConfig().
void Tools::AtomStorage::clear ()
Clear all atoms and groups.
Definition at line 66 of file tools/storage/AtomStorage.cpp.
References capacity().
Referenced by allocate(), and Tools::Configuration::clear().
Atom * Tools::AtomStorage::ptr (int id) inline
Get a pointer to an atom by global id.
Returns a null pointer if no such atom is present.
Parameters
id global index / tag of desired atom.
Definition at line 125 of file tools/storage/AtomStorage.h.
Referenced by Tools::HoomdConfigReader::readConfig(), Tools::LammpsDumpReader::readFrame(), Tools::DdMdTrajectoryReader::readFrame(), and Tools::ConfigReader::setAtomContexts().
void Tools::AtomStorage::begin (AtomStorage::Iterator & iter) inline
Initialize an iterator for atoms.
Definition at line 132 of file tools/storage/AtomStorage.h.
Referenced by Tools::ConfigReader::addAtomsToSpecies(), Tools::PairEnergy::sample(), Tools::DdMdConfigWriter::writeConfig(), Tools::HoomdConfigWriter::writeConfig(), and Tools::LammpsDumpWriter::~LammpsDumpWriter().
int Tools::AtomStorage::capacity () const inline
Get atom capacity (maximum id + 1).
Definition at line 119 of file tools/storage/AtomStorage.h.
Referenced by clear(), and Tools::DdMdConfigReader::readConfig().
int Tools::AtomStorage::size () const inline
Get number of atoms.
Definition at line 112 of file tools/storage/AtomStorage.h.
Referenced by newPtr(), Tools::HoomdConfigReader::readConfig(), Tools::ConfigReader::setAtomContexts(), Tools::DdMdConfigWriter::writeConfig(), Tools::HoomdConfigWriter::writeConfig(), and Tools::LammpsDumpWriter::~LammpsDumpWriter().
The documentation for this class was generated from the following files:
tools/storage/AtomStorage.h
tools/storage/AtomStorage.cpp