Simpatico: McMd::MdStressAutoCorr Class Reference
McMd::MdStressAutoCorr Class Reference
MD Analyzers
Detailed Description
Analyzer to calculate average isotropic pressure.
This analyzer computes the stress autocorrelation function
for an isotropic liquid, where is the shear stress relaxation modulus. This function is given by a sum
where is the system volume, is the total stress tensor (virial + kinetic), and
is the pressure.
Definition at line 43 of file MdStressAutoCorr.h.
#include <MdStressAutoCorr.h>
Public Member Functions
MdStressAutoCorr (MdSystem &system)
Constructor.
~MdStressAutoCorr ()
Destructor.
Protected Member Functions
void computeStress (Tensor &stress)
Compute total stress tensor.
Constructor & Destructor Documentation
McMd::MdStressAutoCorr::MdStressAutoCorr (MdSystem & system)
Constructor.
Parameters:
system parent McSystem
Definition at line 17 of file MdStressAutoCorr.cpp.
References Util::ParamComposite::setClassName().
McMd::MdStressAutoCorr::~MdStressAutoCorr ()
Destructor.
Definition at line 24 of file MdStressAutoCorr.cpp.
Member Function Documentation
void McMd::MdStressAutoCorr::computeStress (Tensor & stress) [protected, virtual]
Compute total stress tensor.
Parameters:
stress computed stress tensor (on return).
Implements McMd::StressAutoCorr< MdSystem >.
Definition at line 30 of file MdStressAutoCorr.cpp.
References Util::Tensor::add(), McMd::MdSystem::computeKineticStress(), McMd::MdSystem::computeVirialStress(), and McMd::SystemAnalyzer< MdSystem >::system().
The documentation for this class was generated from the following files:
MdStressAutoCorr.h
MdStressAutoCorr.cpp