Simpatico: Util::List< Data > Class Template Reference
Util::List< Data > Class Template Reference
Util namespace » Container Templates » Linked List
Detailed Description
template<typename Data>
class Util::List< Data >
Linked list class template.
This list implementation is based on an underlying C array of Node<Data> objects. This array may be used by several List objects, and so must be allocated outside the Link class and provided via the initialize method.
Definition at line 32 of file List.h.
#include <List.h>
Public Member Functions
List ()
Default constructor.
virtual ~List ()
Destructor (does nothing).
void initialize (Node< Data > *nodes, int capacity)
Provide an array of Node<Data> objects for this List.
int size () const
Get the number of elements.
int capacity () const
Get capacity of the array.
void pushBack (Node< Data > &node)
Push a node onto the the back of the List.
void pushFront (Node< Data > &node)
Push a node onto the the front of the List.
Node< Data > & popBack ()
Remove a node from the back of the list.
Node< Data > & popFront ()
Remove a node from the front of the list.
void insertNext (Node< Data > &node, Node< Data > &newNode)
Insert newNode into list after node.
void insertPrev (Node< Data > &node, Node< Data > &newNode)
Insert newNode into list before node.
void insert (Node< Data > &node)
Insert node into list in sequential order.
void remove (Node< Data > &node)
Remove node from list.
void begin (ListIterator< Data > &iterator) const
Set an iterator to the front of this List.
bool isValid () const
Check validity of linked list.
Constructor & Destructor Documentation
template<typename Data > Util::List< Data >::List ()
Default constructor.
Definition at line 192 of file List.h.
template<typename Data> virtual Util::List< Data >::~List () inline virtual
Destructor (does nothing).
Definition at line 45 of file List.h.
References Util::List< Data >::begin(), Util::List< Data >::capacity(), Util::List< Data >::initialize(), Util::List< Data >::insert(), Util::List< Data >::insertNext(), Util::List< Data >::insertPrev(), Util::List< Data >::isValid(), Util::List< Data >::popBack(), Util::List< Data >::popFront(), Util::List< Data >::pushBack(), Util::List< Data >::pushFront(), and Util::List< Data >::size().
Member Function Documentation
template<typename Data > void Util::List< Data >::initialize (Node< Data > * nodes, int capacity)
Provide an array of Node<Data> objects for this List.
Definition at line 206 of file List.h.
References Util::List< Data >::capacity().
Referenced by Util::List< Data >::~List().
template<typename Data > int Util::List< Data >::size () const inline
Get the number of elements.
Returns
Number of elements in this list.
Definition at line 217 of file List.h.
Referenced by Util::List< Data >::~List().
template<typename Data > int Util::List< Data >::capacity () const inline
Get capacity of the array.
Returns
Number of elements allocated in the associated arrays.
Definition at line 224 of file List.h.
Referenced by Util::List< Data >::initialize(), and Util::List< Data >::~List().
template<typename Data > void Util::List< Data >::pushBack (Node< Data > & node)
Push a node onto the the back of the List.
Parameters
node Node object from associated node array.
Definition at line 231 of file List.h.
References Util::Node< Data >::setList(), and Util::Node< Data >::setNext().
Referenced by Util::List< Data >::~List().
template<typename Data > void Util::List< Data >::pushFront (Node< Data > & node)
Push a node onto the the front of the List.
Parameters
node Node object from associated node array.
Definition at line 251 of file List.h.
References Util::Node< Data >::setList(), and Util::Node< Data >::setPrev().
Referenced by Util::List< Data >::~List().
template<typename Data > Node< Data > & Util::List< Data >::popBack ()
Remove a node from the back of the list.
Returns
Node that was removed from this list.
Definition at line 273 of file List.h.
References Util::Node< Data >::clear(), Util::Node< Data >::prev(), and UTIL_THROW.
Referenced by Util::List< Data >::~List().
template<typename Data > Node< Data > & Util::List< Data >::popFront ()
Remove a node from the front of the list.
Returns
Node that was removed from this list.
Definition at line 298 of file List.h.
References Util::Node< Data >::clear(), Util::Node< Data >::next(), and UTIL_THROW.
Referenced by Util::List< Data >::~List().
template<typename Data > void Util::List< Data >::insertNext (Node< Data > & node, Node< Data > & newNode)
Insert newNode into list after node.
Parameters
node Node in the existing list.
newNode new node, to be inserted as the next after node.
Definition at line 323 of file List.h.
References Util::Node< Data >::attachNext(), Util::Node< Data >::next(), and Util::Node< Data >::setNext().
Referenced by Util::List< Data >::~List().
template<typename Data > void Util::List< Data >::insertPrev (Node< Data > & node, Node< Data > & newNode)
Insert newNode into list before node.
Parameters
node Node in the existing list.
newNode new Node, to be inserted previous to node.
Definition at line 340 of file List.h.
References Util::Node< Data >::attachPrev(), Util::Node< Data >::prev(), and Util::Node< Data >::setPrev().
Referenced by Util::List< Data >::~List().
template<typename Data > void Util::List< Data >::insert (Node< Data > & node)
Insert node into list in sequential order.
Parameters
node Node to be inserted into the list.
Definition at line 386 of file List.h.
References Util::Node< Data >::attachNext(), Util::Node< Data >::list(), Util::Node< Data >::next(), Util::Node< Data >::setList(), Util::Node< Data >::setNext(), and Util::Node< Data >::setPrev().
Referenced by Util::List< Data >::~List().
template<typename Data > void Util::List< Data >::remove (Node< Data > & node)
Remove node from list.
Parameters
node Node to be removed from the list.
Definition at line 357 of file List.h.
References Util::Node< Data >::clear(), Util::Node< Data >::list(), Util::Node< Data >::next(), and Util::Node< Data >::prev().
template<typename Data > void Util::List< Data >::begin (ListIterator< Data > & iterator) const
Set an iterator to the front of this List.
Parameters
iterator ListIterator, initialized on output.
Definition at line 449 of file List.h.
References Util::ListIterator< Data >::setCurrent().
Referenced by Util::ListIterator< Data >::ListIterator(), and Util::List< Data >::~List().
template<typename Data > bool Util::List< Data >::isValid () const
Check validity of linked list.
Returns
true if the list is valid, false otherwise.
Definition at line 459 of file List.h.
References Util::Node< Data >::list(), Util::Node< Data >::next(), Util::Node< Data >::prev(), and UTIL_THROW.
Referenced by Util::List< Data >::~List().
The documentation for this class was generated from the following file:
List.h