Simpatico: DdMd::OutputEnergy Class Reference
DdMd::OutputEnergy Class Reference
Diagnostics
Detailed Description
Periodically write simulation energies to file.
Definition at line 24 of file OutputEnergy.h.
#include <OutputEnergy.h>
Public Member Functions
OutputEnergy (Simulation &simulation)
Constructor.
virtual ~OutputEnergy ()
Destructor.
virtual void readParameters (std::istream &in)
Read dumpPrefix and interval.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void clear ()
Clear nSample counter.
virtual void sample (long iStep)
Dump configuration to file.
Constructor & Destructor Documentation
DdMd::OutputEnergy::OutputEnergy (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object.
Definition at line 37 of file OutputEnergy.cpp.
References Util::ParamComposite::setClassName().
virtual DdMd::OutputEnergy::~OutputEnergy () [inline, virtual]
Destructor.
Definition at line 39 of file OutputEnergy.h.
Member Function Documentation
void DdMd::OutputEnergy::readParameters (std::istream & in) [virtual]
Read dumpPrefix and interval.
Parameters:
in input parameter file
Reimplemented from Util::ParamComposite.
Definition at line 46 of file OutputEnergy.cpp.
References DdMd::Diagnostic::readInterval(), and DdMd::Diagnostic::readOutputFileName().
void DdMd::OutputEnergy::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from DdMd::Diagnostic.
Definition at line 56 of file OutputEnergy.cpp.
References Util::MpiLoader< IArchive >::load(), DdMd::Diagnostic::loadInterval(), and DdMd::Diagnostic::loadOutputFileName().
void DdMd::OutputEnergy::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from DdMd::Diagnostic.
Definition at line 68 of file OutputEnergy.cpp.
References DdMd::Diagnostic::saveInterval(), and DdMd::Diagnostic::saveOutputFileName().
void DdMd::OutputEnergy::clear () [virtual]
Clear nSample counter.
Reimplemented from DdMd::Diagnostic.
Definition at line 79 of file OutputEnergy.cpp.
void DdMd::OutputEnergy::sample (long iStep) [virtual]
Dump configuration to file.
Parameters:
iStep MC step index
Implements DdMd::Diagnostic.
Definition at line 85 of file OutputEnergy.cpp.
References DdMd::Simulation::anglePotential(), DdMd::Simulation::computeKineticEnergy(), DdMd::Simulation::computePotentialEnergies(), DdMd::Simulation::dihedralPotential(), DdMd::Simulation::domain(), DdMd::Potential::energy(), Util::Log::file(), DdMd::Diagnostic::isAtInterval(), DdMd::Domain::isMaster(), DdMd::Simulation::kineticEnergy(), DdMd::Simulation::nAngleType(), DdMd::Simulation::nDihedralType(), DdMd::Simulation::pairPotential(), and DdMd::Diagnostic::simulation().
The documentation for this class was generated from the following files:
OutputEnergy.h
OutputEnergy.cpp