Simpatico: DdMd::TensorAverageAnalyzer Class Reference
DdMd::TensorAverageAnalyzer Class Reference abstract
DdMd namespace » Analyzers » Analyzer Base
Detailed Description
Analyzer that computes averages and block averages of a single Tensor.
This class evaluates the average of a sequence of Tensor values, and optionally writes block averages to a data file during the run. It is intended for use as a base class for classes that evaluate averages for specific tensor-valued physical variables.
Definition at line 35 of file TensorAverageAnalyzer.h.
#include <TensorAverageAnalyzer.h>
Public Member Functions
TensorAverageAnalyzer (Simulation &simulation)
Constructor.
virtual ~TensorAverageAnalyzer ()
Destructor.
virtual void readParameters (std::istream &in)
Read interval, outputFileName and (optionally) nSamplePerBlock.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void clear ()
Clear accumulator on master, do nothing on other processors.
virtual void setup ()
Setup before loop - open output file.
virtual void sample (long iStep)
Compute a sampled value and add update accumulator.
virtual void output ()
Write final average and error analysis to file.
Public Member Functions inherited from DdMd::Analyzer
Analyzer (Simulation &simulation)
Constructor.
virtual ~Analyzer ()
Destructor.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
virtual void compute ()=0
Compute value of sampled quantity.
virtual Tensor value ()=0
Get current value, set by compute function.
Protected Member Functions inherited from DdMd::Analyzer
void readInterval (std::istream &in)
Read parameter interval from file.
void loadInterval (Serializable::IArchive &ar)
Load parameter interval from input archive.
void saveInterval (Serializable::OArchive &ar)
Save interval parameter to an archive.
void readOutputFileName (std::istream &in)
Read outputFileName from file.
void loadOutputFileName (Serializable::IArchive &ar)
Load output file name to an archive.
void saveOutputFileName (Serializable::OArchive &ar)
Save output file name to an archive.
Simulation & simulation ()
Get the parent Simulation by reference.
const std::string & outputFileName () const
Return outputFileName string.
std::string outputFileName (const std::string &suffix) const
Return outputFileName string with added suffix.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from DdMd::Analyzer
static void initStatic ()
Define and initialize baseInterval.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Public Attributes inherited from DdMd::Analyzer
static long baseInterval = 1
The interval for an Analyzer must be a multiple of baseInterval.
Constructor & Destructor Documentation
DdMd::TensorAverageAnalyzer::TensorAverageAnalyzer (Simulation & simulation)
Constructor.
Parameters
simulation parent Simulation object.
Definition at line 27 of file TensorAverageAnalyzer.cpp.
References Util::ParamComposite::setClassName().
DdMd::TensorAverageAnalyzer::~TensorAverageAnalyzer () virtual
Destructor.
Definition at line 38 of file TensorAverageAnalyzer.cpp.
Member Function Documentation
void DdMd::TensorAverageAnalyzer::readParameters (std::istream & in) virtual
Read interval, outputFileName and (optionally) nSamplePerBlock.
The optional variable nSamplePerBlock defaults to 0, which disables computation and output of block averages. Setting nSamplePerBlock = 1 outputs every sampled value.
Parameters
in input parameter file
Reimplemented from Util::ParamComposite.
Definition at line 48 of file TensorAverageAnalyzer.cpp.
References DdMd::Simulation::domain(), DdMd::Domain::isMaster(), DdMd::Analyzer::readInterval(), DdMd::Analyzer::readOutputFileName(), Util::TensorAverage::setNSamplePerBlock(), and DdMd::Analyzer::simulation().
void DdMd::TensorAverageAnalyzer::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from DdMd::Analyzer.
Definition at line 65 of file TensorAverageAnalyzer.cpp.
References DdMd::Simulation::domain(), DdMd::Domain::isMaster(), Util::ParamComposite::isRequired(), DdMd::Analyzer::loadInterval(), DdMd::Analyzer::loadOutputFileName(), DdMd::Analyzer::simulation(), and UTIL_THROW.
void DdMd::TensorAverageAnalyzer::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from DdMd::Analyzer.
Definition at line 88 of file TensorAverageAnalyzer.cpp.
References Util::ParamComposite::isActive(), DdMd::Analyzer::saveInterval(), Util::Parameter::saveOptional(), DdMd::Analyzer::saveOutputFileName(), and DdMd::Analyzer::simulation().
void DdMd::TensorAverageAnalyzer::clear () virtual
Clear accumulator on master, do nothing on other processors.
Reimplemented from DdMd::Analyzer.
Definition at line 102 of file TensorAverageAnalyzer.cpp.
References Util::TensorAverage::clear(), and DdMd::Analyzer::simulation().
void DdMd::TensorAverageAnalyzer::setup () virtual
Setup before loop - open output file.
Reimplemented from DdMd::Analyzer.
Definition at line 112 of file TensorAverageAnalyzer.cpp.
References DdMd::Simulation::fileMaster(), Util::FileMaster::openOutputFile(), DdMd::Analyzer::outputFileName(), and DdMd::Analyzer::simulation().
void DdMd::TensorAverageAnalyzer::sample (long iStep) virtual
Compute a sampled value and add update accumulator.
If block averaging is enabled (nSamplePerBlock > 0), then this function also periodically outputs block averages.
Parameters
iStep MD time step index
Implements DdMd::Analyzer.
Definition at line 125 of file TensorAverageAnalyzer.cpp.
References compute(), Util::Dimension, DdMd::Analyzer::interval(), DdMd::Analyzer::isAtInterval(), Util::TensorAverage::isBlockComplete(), Util::TensorAverage::sample(), DdMd::Analyzer::simulation(), UTIL_THROW, and value().
void DdMd::TensorAverageAnalyzer::output () virtual
Write final average and error analysis to file.
Reimplemented from DdMd::Analyzer.
Definition at line 153 of file TensorAverageAnalyzer.cpp.
References Util::Dimension, DdMd::Simulation::fileMaster(), Util::FileMaster::openOutputFile(), DdMd::Analyzer::outputFileName(), DdMd::Analyzer::simulation(), and Util::ParamComposite::writeParam().
virtual void DdMd::TensorAverageAnalyzer::compute () protected pure virtual
Compute value of sampled quantity.
Call on all processors.
Referenced by sample().
virtual Tensor DdMd::TensorAverageAnalyzer::value () protected pure virtual
Get current value, set by compute function.
Call only on master.
Referenced by sample().
The documentation for this class was generated from the following files:
TensorAverageAnalyzer.h
TensorAverageAnalyzer.cpp