Simpatico: SpAn::DdMdConfigIo Class Reference
SpAn::DdMdConfigIo Class Reference
ConfigIos
Detailed Description
Native / default DdMd format for configuration files.
Definition at line 29 of file spAn/configIos/DdMdConfigIo.h.
#include <DdMdConfigIo.h>
Public Member Functions
DdMdConfigIo (bool hasMolecules=false)
Default constructor.
DdMdConfigIo (Configuration &configuration, bool hasMolecules=false)
Constructor.
virtual void readConfig (std::ifstream &file)
Read configuration file in DdMd default format.
virtual void writeConfig (std::ofstream &file)
Write configuration file in DdMd default format.
Constructor & Destructor Documentation
SpAn::DdMdConfigIo::DdMdConfigIo (bool hasMolecules = false)
Default constructor.
SpAn::DdMdConfigIo::DdMdConfigIo (Configuration & configuration, bool hasMolecules = false)
Constructor.
Parameters:
configuration parent Configuration object.
hasMolecules true if file format has DdMd::AtomContext info
Definition at line 31 of file spAn/configIos/DdMdConfigIo.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void SpAn::DdMdConfigIo::readConfig (std::ifstream & file) [virtual]
Read configuration file in DdMd default format.
Parameters:
file input file stream
Implements SpAn::ConfigIo.
Definition at line 39 of file spAn/configIos/DdMdConfigIo.cpp.
References SpAn::AtomStorage::add(), SpAn::Species::addAtom(), SpAn::Atom::atomId, SpAn::Configuration::atoms(), SpAn::AtomStorage::begin(), SpAn::Configuration::boundary(), SpAn::AtomStorage::capacity(), SpAn::Species::clear(), SpAn::Atom::id, SpAn::Species::isValid(), SpAn::Atom::moleculeId, SpAn::AtomStorage::newPtr(), Util::ArrayIterator< Data >::notEnd(), SpAn::Configuration::nSpecies(), SpAn::Atom::position, SpAn::Configuration::species(), SpAn::Atom::speciesId, SpAn::Atom::typeId, UTIL_THROW, and SpAn::Atom::velocity.
void SpAn::DdMdConfigIo::writeConfig (std::ofstream & file) [virtual]
Write configuration file in DdMd default format.
Parameters:
file output file stream (must be open on master)
Implements SpAn::ConfigIo.
Definition at line 150 of file spAn/configIos/DdMdConfigIo.cpp.
References SpAn::Configuration::atoms(), SpAn::AtomStorage::begin(), SpAn::Configuration::boundary(), Util::ArrayIterator< Data >::notEnd(), SpAn::AtomStorage::size(), and UTIL_THROW.
The documentation for this class was generated from the following files:
spAn/configIos/DdMdConfigIo.h
spAn/configIos/DdMdConfigIo.cpp