Simpatico: McMd::Diagnostic Class Reference
McMd::Diagnostic Class Reference abstract
Diagnostics
Detailed Description
Abstract base for periodic output and/or analysis actions.
The periodic action associated with a Diagnostic can involve sampling of a physical property and adding it to statistical accumulator, outputting it to file, or both. This periodic action must be implemented by the pure virtual sample() method.
The sample() method should take the desired action only when the simulation step index is an integer multiple of the associated interval parameter. The interval must be a positive integer that is a multiple of the static member Diagnostic::baseInterval.
The virtual sample() method does not take any parameters. A Diagnostic must thus access its parent Simulation and/or System via a pointer, which is usually initialized in its subclass constructor.
Diagnostic subclasses that are associated with one System, McSystem or MdSystem (i.e., almost all of them) should be derived from the SystemDiagnostic<class SystemType> class template. This takes a reference to the parent system as parameter to its constructor. A Diagnostic subclass that can be used with any System should be derived from SystemDiagnostic<System>, and one that can be used only with a MdSystem or McSystem should be derived from SystemDiagnostic<MdSystem> or SystemDiagnostic<MdSystem>, respectively.
Definition at line 52 of file mcMd/diagnostics/Diagnostic.h.
#include <Diagnostic.h>
Public Member Functions
Diagnostic ()
Default constructor.
virtual ~Diagnostic ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from archive.
virtual void loadParameters (Serializable::IArchive &ar)
Load parameters from archive.
virtual void save (Serializable::OArchive &ar)
Load parameters to archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Complete any required initialization.
virtual void sample (long iStep)=0
Calculate, analyze and/or output a physical quantity.
virtual void output ()
Output any results at the end of the simulation.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
std::string className () const
Get class name string.
virtual void readParam (std::istream &in)
Read a parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an archive.
void resetParam ()
Resets ParamComposite to its empty state.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add a new Param < Type > object, and read its value.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add a C array parameter, and read its elements.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and read its elements.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n)
Add and read a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
Begin & readBegin (std::istream &in, const char *label)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a child ParamComposite.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add a new Param < Type > object, and load its value.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add a C array parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and load its elements.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n)
Add and load a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a DMatrix < Type > C two-dimensional matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
template<typename Type >
ScalarParam< Type > & add (const char *label, Type &value)
Add a new Param < Type > object to the format array.
template<typename Type >
CArrayParam< Type > & addCArray (const char *label, Type *value, int n)
Add a C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (const char *label, DArray< Type > &array, int n)
Add a DArray<Type> parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (const char *label, FArray< Type, N > &array)
Add a FArray<Type> parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (const char *label, Type *value, int m, int n)
Add a C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & addDMatrix (const char *label, DMatrix< Type > &matrix, int m, int n)
Add a C two-dimensional array parameter.
Begin & addBegin (const char *label)
Add a class label and opening bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Add a new Blank object, representing a blank line.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have a communicator?
MPI::Intracomm & ioCommunicator () const
Get the communicator.
Static Public Member Functions
static void initStatic ()
Define and initialize baseInterval.
Static Public Attributes
static long baseInterval = 1
The interval for a Diagnostic must be a multiple of baseInterval.
Protected Member Functions
void setFileMaster (FileMaster &fileMaster)
Set the FileMaster to use to open files.
void readInterval (std::istream &in)
Read interval from file, with error checking.
void readOutputFileName (std::istream &in)
Read outputFileName from file.
void loadInterval (Serializable::IArchive &ar)
Load interval from archive, with error checking.
void loadOutputFileName (Serializable::IArchive &ar)
Load output file name from archive.
FileMaster & fileMaster ()
Get the FileMaster by reference.
const std::string & outputFileName () const
Return outputFileName string.
std::string outputFileName (const std::string &suffix) const
Return outputFileName string with added suffix.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
std::string outputFileName_
Base name of output file(s).
long interval_
Number of simulation steps between subsequent actions.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Constructor & Destructor Documentation
McMd::Diagnostic::Diagnostic ()
Default constructor.
Definition at line 30 of file mcMd/diagnostics/Diagnostic.cpp.
McMd::Diagnostic::~Diagnostic () virtual
Destructor.
Definition at line 40 of file mcMd/diagnostics/Diagnostic.cpp.
Member Function Documentation
void McMd::Diagnostic::readParameters (std::istream & in) virtual
Read parameters from archive.
Default implementation, reads interval and outputFileName.
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Reimplemented in McMd::StructureFactorP, McMd::IntraStructureFactor, McMd::StructureFactor, McMd::VanHove, McMd::IntraStructureFactorGrid, McMd::StructureFactorGrid, McMd::StructureFactorPGrid, McMd::MigratingVanHove, McMd::BlockRadiusGyration, McMd::RadiusGyration, McMd::IntraPairAutoCorr, McMd::CompositionProfile, McMd::RDF, McMd::DumpConfig, McMd::BennettsMethod, McMd::IntraBondStressAutoCorr< SystemType >, McMd::IntraBondTensorAutoCorr< SystemType >, McMd::LinearRouseAutoCorr, McMd::IntraBondStressAutoCorr< MdSystem >, McMd::IntraBondStressAutoCorr< McSystem >, McMd::IntraBondTensorAutoCorr< MdSystem >, McMd::IntraBondTensorAutoCorr< McSystem >, McMd::MdPairEnergyCoefficients, McMd::RingRouseAutoCorr, McMd::McStressAutoCorr, McMd::McPairEnergyAverage, McMd::ComMSD, McMd::BondLengthDist, McMd::PressureAverage< SystemType >, McMd::PressureAverage< MdSystem >, McMd::PressureAverage< McSystem >, McMd::AtomMSD, McMd::BoundaryAverage, McMd::TypeDistribution, McMd::McEnergyOutput, McMd::PerturbDerivative, McMd::MdEnergyOutput, McMd::MdKineticEnergyAverage, McMd::SemiGrandDistribution, McMd::AverageDiagnostic< SystemType >, McMd::AverageDiagnostic< McSystem >, McMd::MdPotentialEnergyAverage, and McMd::LogProgress.
Definition at line 46 of file mcMd/diagnostics/Diagnostic.cpp.
References readInterval(), and readOutputFileName().
Referenced by McMd::RDF::readParameters().
void McMd::Diagnostic::loadParameters (Serializable::IArchive & ar) virtual
Load parameters from archive.
Default implementation, loads interval and outputFileName.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Reimplemented in McMd::StructureFactorP, McMd::IntraStructureFactor, McMd::StructureFactor, McMd::VanHove, McMd::BlockRadiusGyration, McMd::IntraStructureFactorGrid, McMd::StructureFactorGrid, McMd::StructureFactorPGrid, McMd::RadiusGyration, McMd::CompositionProfile, McMd::IntraPairAutoCorr, McMd::DumpConfig, McMd::RDF, McMd::BennettsMethod, McMd::IntraBondStressAutoCorr< SystemType >, McMd::IntraBondTensorAutoCorr< SystemType >, McMd::LinearRouseAutoCorr, McMd::IntraBondStressAutoCorr< MdSystem >, McMd::IntraBondStressAutoCorr< McSystem >, McMd::IntraBondTensorAutoCorr< MdSystem >, McMd::IntraBondTensorAutoCorr< McSystem >, McMd::MdPairEnergyCoefficients, McMd::RingRouseAutoCorr, McMd::McStressAutoCorr, McMd::McPairEnergyAverage, McMd::ComMSD, McMd::BondLengthDist, McMd::PressureAverage< SystemType >, McMd::PressureAverage< MdSystem >, McMd::PressureAverage< McSystem >, McMd::AtomMSD, McMd::BoundaryAverage, McMd::TypeDistribution, McMd::McEnergyOutput, McMd::PerturbDerivative, McMd::MdEnergyOutput, McMd::MdKineticEnergyAverage, McMd::SemiGrandDistribution, McMd::AverageDiagnostic< SystemType >, McMd::AverageDiagnostic< McSystem >, McMd::MdPotentialEnergyAverage, and McMd::LogProgress.
Definition at line 86 of file mcMd/diagnostics/Diagnostic.cpp.
References loadInterval(), and loadOutputFileName().
Referenced by McMd::AverageDiagnostic< SystemType >::loadParameters(), McMd::SemiGrandDistribution::loadParameters(), McMd::PerturbDerivative::loadParameters(), McMd::McEnergyOutput::loadParameters(), McMd::TypeDistribution::loadParameters(), McMd::BoundaryAverage::loadParameters(), McMd::PressureAverage< SystemType >::loadParameters(), McMd::ComMSD::loadParameters(), McMd::McPairEnergyAverage::loadParameters(), McMd::McStressAutoCorr::loadParameters(), McMd::RingRouseAutoCorr::loadParameters(), McMd::IntraBondStressAutoCorr< SystemType >::loadParameters(), McMd::BennettsMethod::loadParameters(), McMd::IntraBondTensorAutoCorr< SystemType >::loadParameters(), McMd::LinearRouseAutoCorr::loadParameters(), McMd::RDF::loadParameters(), McMd::DumpConfig::loadParameters(), McMd::IntraPairAutoCorr::loadParameters(), McMd::CompositionProfile::loadParameters(), McMd::RadiusGyration::loadParameters(), McMd::StructureFactorGrid::loadParameters(), McMd::StructureFactorPGrid::loadParameters(), McMd::IntraStructureFactorGrid::loadParameters(), McMd::BlockRadiusGyration::loadParameters(), McMd::VanHove::loadParameters(), McMd::StructureFactor::loadParameters(), and McMd::StructureFactorP::loadParameters().
void McMd::Diagnostic::save (Serializable::OArchive & ar) virtual
Load parameters to archive.
Default implementation saves interval and outputFileName.
Parameters
ar loading/saving archive
Reimplemented from Util::ParamComposite.
Reimplemented in McMd::StructureFactorP, McMd::IntraStructureFactor, McMd::StructureFactor, McMd::VanHove, McMd::MigratingVanHove, McMd::IntraStructureFactorGrid, McMd::BlockRadiusGyration, McMd::StructureFactorGrid, McMd::StructureFactorPGrid, McMd::RadiusGyration, McMd::CompositionProfile, McMd::IntraPairAutoCorr, McMd::RDF, McMd::BennettsMethod, McMd::IntraBondStressAutoCorr< SystemType >, McMd::IntraBondTensorAutoCorr< SystemType >, McMd::LinearRouseAutoCorr, McMd::IntraBondStressAutoCorr< MdSystem >, McMd::IntraBondStressAutoCorr< McSystem >, McMd::IntraBondTensorAutoCorr< MdSystem >, McMd::IntraBondTensorAutoCorr< McSystem >, McMd::MdPairEnergyCoefficients, McMd::RingRouseAutoCorr, McMd::DumpConfig, McMd::McStressAutoCorr, McMd::McPairEnergyAverage, McMd::ComMSD, McMd::BondLengthDist, McMd::PressureAverage< SystemType >, McMd::PressureAverage< MdSystem >, McMd::PressureAverage< McSystem >, McMd::AtomMSD, McMd::BoundaryAverage, McMd::TypeDistribution, McMd::McEnergyOutput, McMd::PerturbDerivative, McMd::MdEnergyOutput, McMd::MdKineticEnergyAverage, McMd::SemiGrandDistribution, McMd::AverageDiagnostic< SystemType >, McMd::AverageDiagnostic< McSystem >, and McMd::MdPotentialEnergyAverage.
Definition at line 129 of file mcMd/diagnostics/Diagnostic.cpp.
References interval_, and outputFileName_.
template<class Archive > void McMd::Diagnostic::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Saves interval and outputFileName.
Parameters
ar archive
version archive version id
Definition at line 255 of file mcMd/diagnostics/Diagnostic.h.
Referenced by McMd::MdPotentialEnergyAverage::serialize(), McMd::AverageDiagnostic< SystemType >::serialize(), McMd::MdKineticEnergyAverage::serialize(), McMd::MdEnergyOutput::serialize(), McMd::SemiGrandDistribution::serialize(), McMd::PerturbDerivative::serialize(), McMd::McEnergyOutput::serialize(), McMd::TypeDistribution::serialize(), McMd::BoundaryAverage::serialize(), McMd::AtomMSD::serialize(), McMd::BondLengthDist::serialize(), McMd::PressureAverage< SystemType >::serialize(), McMd::McPairEnergyAverage::serialize(), McMd::ComMSD::serialize(), McMd::McStressAutoCorr::serialize(), McMd::RingRouseAutoCorr::serialize(), McMd::BennettsMethod::serialize(), McMd::LinearRouseAutoCorr::serialize(), McMd::IntraBondStressAutoCorr< SystemType >::serialize(), McMd::IntraBondTensorAutoCorr< SystemType >::serialize(), McMd::DumpConfig::serialize(), McMd::RDF::serialize(), McMd::IntraPairAutoCorr::serialize(), McMd::CompositionProfile::serialize(), McMd::RadiusGyration::serialize(), McMd::BlockRadiusGyration::serialize(), McMd::VanHove::serialize(), McMd::StructureFactor::serialize(), McMd::IntraStructureFactor::serialize(), and McMd::StructureFactorP::serialize().
virtual void McMd::Diagnostic::setup () inline virtual
Complete any required initialization.
This method must be called just before the beginning of the main simulation loop, after an initial configuration is known. It may be used to complete any initialization that cannot be completed in the readParam method, because knowledge of the configuration is needed.
The default implementation is an empty function.
Reimplemented in McMd::StructureFactorP, McMd::IntraStructureFactor, McMd::StructureFactor, McMd::VanHove, McMd::IntraStructureFactorGrid, McMd::StructureFactorGrid, McMd::StructureFactorPGrid, McMd::RadiusGyration, McMd::IntraPairAutoCorr, McMd::MigratingVanHove, McMd::RDF, McMd::DumpConfig, McMd::IntraBondStressAutoCorr< SystemType >, McMd::IntraBondTensorAutoCorr< SystemType >, McMd::LinearRouseAutoCorr, McMd::IntraBondStressAutoCorr< MdSystem >, McMd::IntraBondStressAutoCorr< McSystem >, McMd::IntraBondTensorAutoCorr< MdSystem >, McMd::IntraBondTensorAutoCorr< McSystem >, McMd::BlockRadiusGyration, McMd::BennettsMethod, McMd::RingRouseAutoCorr, McMd::McStressAutoCorr, McMd::McPairEnergyAverage, McMd::ComMSD, McMd::BondLengthDist, McMd::PressureAverage< SystemType >, McMd::PressureAverage< MdSystem >, McMd::PressureAverage< McSystem >, McMd::AtomMSD, McMd::BoundaryAverage, McMd::PerturbDerivative, McMd::MdKineticEnergyAverage, McMd::CompositionProfile, McMd::AverageDiagnostic< SystemType >, McMd::AverageDiagnostic< McSystem >, and McMd::MdPotentialEnergyAverage.
Definition at line 118 of file mcMd/diagnostics/Diagnostic.h.
virtual void McMd::Diagnostic::sample (long iStep) pure virtual
Calculate, analyze and/or output a physical quantity.
Take an action if iStep is a multiple of interval. If iStep is not a multiple of interval, this method should do nothing and return immediately.
Parameters
iStep current simulation step index.
Implemented in McMd::StructureFactorP, McMd::IntraStructureFactor, McMd::StructureFactor, McMd::VanHove, McMd::IntraStructureFactorGrid, McMd::StructureFactorGrid, McMd::RadiusGyration, McMd::IntraPairAutoCorr, McMd::MigratingVanHove, McMd::RDF, McMd::DumpConfig, McMd::IntraBondStressAutoCorr< SystemType >, McMd::IntraBondTensorAutoCorr< SystemType >, McMd::LinearRouseAutoCorr, McMd::IntraBondStressAutoCorr< MdSystem >, McMd::IntraBondStressAutoCorr< McSystem >, McMd::IntraBondTensorAutoCorr< MdSystem >, McMd::IntraBondTensorAutoCorr< McSystem >, McMd::BlockRadiusGyration, McMd::BennettsMethod, McMd::RingRouseAutoCorr, McMd::McStressAutoCorr, McMd::ComMSD, McMd::McPairEnergyAverage, McMd::MdPairEnergyCoefficients, McMd::BondLengthDist, McMd::AtomMSD, McMd::BoundaryAverage, McMd::PressureAverage< SystemType >, McMd::PressureAverage< MdSystem >, McMd::PressureAverage< McSystem >, McMd::CompositionProfile, McMd::PerturbDerivative, McMd::MdKineticEnergyAverage, McMd::MdPotentialEnergyAverage, McMd::TypeDistribution, McMd::McEnergyOutput, McMd::MdEnergyOutput, McMd::SemiGrandDistribution, McMd::LogProgress, McMd::McExternalEnergyAverage, McMd::McBondEnergyAverage, and McMd::McEnergyAverage.
virtual void McMd::Diagnostic::output () inline virtual
Output any results at the end of the simulation.
The default implementation is an empty function.
Reimplemented in McMd::StructureFactorP, McMd::IntraStructureFactor, McMd::StructureFactor, McMd::VanHove, McMd::IntraStructureFactorGrid, McMd::RadiusGyration, McMd::StructureFactorGrid, McMd::StructureFactorPGrid, McMd::IntraPairAutoCorr, McMd::MigratingVanHove, McMd::CompositionProfile, McMd::RDF, McMd::IntraBondStressAutoCorr< SystemType >, McMd::IntraBondTensorAutoCorr< SystemType >, McMd::LinearRouseAutoCorr, McMd::IntraBondStressAutoCorr< MdSystem >, McMd::IntraBondStressAutoCorr< McSystem >, McMd::IntraBondTensorAutoCorr< MdSystem >, McMd::IntraBondTensorAutoCorr< McSystem >, McMd::BlockRadiusGyration, McMd::BennettsMethod, McMd::RingRouseAutoCorr, McMd::McStressAutoCorr, McMd::ComMSD, McMd::McPairEnergyAverage, McMd::AtomMSD, McMd::BondLengthDist, McMd::BoundaryAverage, McMd::MdPairEnergyCoefficients, McMd::PressureAverage< SystemType >, McMd::PressureAverage< MdSystem >, McMd::PressureAverage< McSystem >, McMd::PerturbDerivative, McMd::MdKineticEnergyAverage, McMd::MdPotentialEnergyAverage, McMd::TypeDistribution, McMd::McEnergyOutput, McMd::MdEnergyOutput, McMd::SemiGrandDistribution, McMd::AverageDiagnostic< SystemType >, and McMd::AverageDiagnostic< McSystem >.
Definition at line 137 of file mcMd/diagnostics/Diagnostic.h.
int McMd::Diagnostic::interval () const inline
Get interval value.
Definition at line 234 of file mcMd/diagnostics/Diagnostic.h.
bool McMd::Diagnostic::isAtInterval (long counter) const inline
Return true iff counter is a multiple of the interval.
Parameters
counter simulation step counter
Definition at line 240 of file mcMd/diagnostics/Diagnostic.h.
Referenced by McMd::McEnergyAverage::sample(), McMd::McExternalEnergyAverage::sample(), McMd::MdEnergyOutput::sample(), McMd::SemiGrandDistribution::sample(), McMd::McEnergyOutput::sample(), McMd::TypeDistribution::sample(), McMd::MdPotentialEnergyAverage::sample(), McMd::MdKineticEnergyAverage::sample(), McMd::PerturbDerivative::sample(), McMd::CompositionProfile::sample(), McMd::BoundaryAverage::sample(), McMd::AtomMSD::sample(), McMd::MdPairEnergyCoefficients::sample(), McMd::BondLengthDist::sample(), McMd::McPairEnergyAverage::sample(), McMd::ComMSD::sample(), McMd::McStressAutoCorr::sample(), McMd::RingRouseAutoCorr::sample(), McMd::BennettsMethod::sample(), McMd::BlockRadiusGyration::sample(), McMd::LinearRouseAutoCorr::sample(), McMd::DumpConfig::sample(), McMd::RDF::sample(), McMd::MigratingVanHove::sample(), McMd::IntraPairAutoCorr::sample(), McMd::RadiusGyration::sample(), McMd::VanHove::sample(), McMd::StructureFactor::sample(), McMd::IntraStructureFactor::sample(), and McMd::StructureFactorP::sample().
void McMd::Diagnostic::initStatic () static
Define and initialize baseInterval.
Definition at line 24 of file mcMd/diagnostics/Diagnostic.cpp.
References baseInterval.
Referenced by McMd::Simulation::Simulation().
void McMd::Diagnostic::setFileMaster (FileMaster & fileMaster) protected
Set the FileMaster to use to open files.
Definition at line 138 of file mcMd/diagnostics/Diagnostic.cpp.
References fileMaster().
Referenced by McMd::SystemDiagnostic< SystemType >::SystemDiagnostic().
void McMd::Diagnostic::readInterval (std::istream & in) protected
Read interval from file, with error checking.
Parameters
in input parameter file stream
Definition at line 55 of file mcMd/diagnostics/Diagnostic.cpp.
References baseInterval, interval_, and UTIL_THROW.
Referenced by McMd::MdPotentialEnergyAverage::readParameters(), McMd::AverageDiagnostic< SystemType >::readParameters(), McMd::MdKineticEnergyAverage::readParameters(), McMd::MdEnergyOutput::readParameters(), McMd::SemiGrandDistribution::readParameters(), McMd::PerturbDerivative::readParameters(), McMd::McEnergyOutput::readParameters(), McMd::TypeDistribution::readParameters(), McMd::BoundaryAverage::readParameters(), McMd::AtomMSD::readParameters(), McMd::BondLengthDist::readParameters(), McMd::McPairEnergyAverage::readParameters(), McMd::ComMSD::readParameters(), McMd::McStressAutoCorr::readParameters(), McMd::RingRouseAutoCorr::readParameters(), McMd::MdPairEnergyCoefficients::readParameters(), McMd::BennettsMethod::readParameters(), McMd::LinearRouseAutoCorr::readParameters(), McMd::DumpConfig::readParameters(), McMd::CompositionProfile::readParameters(), McMd::IntraPairAutoCorr::readParameters(), readParameters(), McMd::BlockRadiusGyration::readParameters(), McMd::RadiusGyration::readParameters(), McMd::MigratingVanHove::readParameters(), McMd::StructureFactorGrid::readParameters(), McMd::StructureFactorPGrid::readParameters(), McMd::IntraStructureFactorGrid::readParameters(), McMd::VanHove::readParameters(), McMd::StructureFactor::readParameters(), McMd::IntraStructureFactor::readParameters(), and McMd::StructureFactorP::readParameters().
void McMd::Diagnostic::readOutputFileName (std::istream & in) protected
Read outputFileName from file.
Parameters
in input parameter file stream.
Definition at line 80 of file mcMd/diagnostics/Diagnostic.cpp.
References outputFileName_.
Referenced by McMd::MdPotentialEnergyAverage::readParameters(), McMd::AverageDiagnostic< SystemType >::readParameters(), McMd::MdKineticEnergyAverage::readParameters(), McMd::MdEnergyOutput::readParameters(), McMd::SemiGrandDistribution::readParameters(), McMd::PerturbDerivative::readParameters(), McMd::McEnergyOutput::readParameters(), McMd::TypeDistribution::readParameters(), McMd::BoundaryAverage::readParameters(), McMd::AtomMSD::readParameters(), McMd::BondLengthDist::readParameters(), McMd::McPairEnergyAverage::readParameters(), McMd::ComMSD::readParameters(), McMd::McStressAutoCorr::readParameters(), McMd::RingRouseAutoCorr::readParameters(), McMd::MdPairEnergyCoefficients::readParameters(), McMd::BennettsMethod::readParameters(), McMd::LinearRouseAutoCorr::readParameters(), McMd::DumpConfig::readParameters(), McMd::CompositionProfile::readParameters(), McMd::IntraPairAutoCorr::readParameters(), readParameters(), McMd::BlockRadiusGyration::readParameters(), McMd::RadiusGyration::readParameters(), McMd::MigratingVanHove::readParameters(), McMd::StructureFactorGrid::readParameters(), McMd::StructureFactorPGrid::readParameters(), McMd::IntraStructureFactorGrid::readParameters(), McMd::VanHove::readParameters(), McMd::StructureFactor::readParameters(), McMd::IntraStructureFactor::readParameters(), and McMd::StructureFactorP::readParameters().
void McMd::Diagnostic::loadInterval (Serializable::IArchive & ar) protected
Load interval from archive, with error checking.
Parameters
ar input/loading archive
Definition at line 95 of file mcMd/diagnostics/Diagnostic.cpp.
References baseInterval, interval_, and UTIL_THROW.
Referenced by McMd::MdPotentialEnergyAverage::loadParameters(), McMd::MdEnergyOutput::loadParameters(), McMd::MdKineticEnergyAverage::loadParameters(), McMd::AtomMSD::loadParameters(), McMd::BondLengthDist::loadParameters(), McMd::MdPairEnergyCoefficients::loadParameters(), loadParameters(), and McMd::IntraStructureFactor::loadParameters().
void McMd::Diagnostic::loadOutputFileName (Serializable::IArchive & ar) protected
Load output file name from archive.
Parameters
ar input/loading archive
Definition at line 123 of file mcMd/diagnostics/Diagnostic.cpp.
References outputFileName_.
Referenced by McMd::MdPotentialEnergyAverage::loadParameters(), McMd::MdEnergyOutput::loadParameters(), McMd::MdKineticEnergyAverage::loadParameters(), McMd::AtomMSD::loadParameters(), McMd::BondLengthDist::loadParameters(), McMd::MdPairEnergyCoefficients::loadParameters(), loadParameters(), and McMd::IntraStructureFactor::loadParameters().
FileMaster & McMd::Diagnostic::fileMaster () protected
Get the FileMaster by reference.
This can be used to open multiple output files.
Definition at line 144 of file mcMd/diagnostics/Diagnostic.cpp.
Referenced by McMd::MdPotentialEnergyAverage::loadParameters(), McMd::AverageDiagnostic< SystemType >::loadParameters(), McMd::MdKineticEnergyAverage::loadParameters(), McMd::MdEnergyOutput::loadParameters(), McMd::PerturbDerivative::loadParameters(), McMd::McEnergyOutput::loadParameters(), McMd::BoundaryAverage::loadParameters(), McMd::McPairEnergyAverage::loadParameters(), McMd::McStressAutoCorr::loadParameters(), McMd::MdPairEnergyCoefficients::loadParameters(), McMd::BennettsMethod::loadParameters(), McMd::RadiusGyration::loadParameters(), McMd::BlockRadiusGyration::loadParameters(), McMd::AverageDiagnostic< SystemType >::output(), McMd::MdEnergyOutput::output(), McMd::SemiGrandDistribution::output(), McMd::McEnergyOutput::output(), McMd::TypeDistribution::output(), McMd::MdPotentialEnergyAverage::output(), McMd::MdKineticEnergyAverage::output(), McMd::PerturbDerivative::output(), McMd::MdPairEnergyCoefficients::output(), McMd::BoundaryAverage::output(), McMd::BondLengthDist::output(), McMd::AtomMSD::output(), McMd::McPairEnergyAverage::output(), McMd::ComMSD::output(), McMd::McStressAutoCorr::output(), McMd::RingRouseAutoCorr::output(), McMd::BennettsMethod::output(), McMd::BlockRadiusGyration::output(), McMd::LinearRouseAutoCorr::output(), McMd::RDF::output(), McMd::CompositionProfile::output(), McMd::MigratingVanHove::output(), McMd::IntraPairAutoCorr::output(), McMd::StructureFactorPGrid::output(), McMd::StructureFactorGrid::output(), McMd::RadiusGyration::output(), McMd::IntraStructureFactorGrid::output(), McMd::VanHove::output(), McMd::StructureFactor::output(), McMd::IntraStructureFactor::output(), McMd::StructureFactorP::output(), McMd::MdPotentialEnergyAverage::readParameters(), McMd::AverageDiagnostic< SystemType >::readParameters(), McMd::MdEnergyOutput::readParameters(), McMd::MdKineticEnergyAverage::readParameters(), McMd::McEnergyOutput::readParameters(), McMd::PerturbDerivative::readParameters(), McMd::BoundaryAverage::readParameters(), McMd::McPairEnergyAverage::readParameters(), McMd::McStressAutoCorr::readParameters(), McMd::MdPairEnergyCoefficients::readParameters(), McMd::BennettsMethod::readParameters(), McMd::BlockRadiusGyration::readParameters(), McMd::RadiusGyration::readParameters(), McMd::DumpConfig::sample(), McMd::StructureFactorGrid::sample(), McMd::IntraStructureFactorGrid::sample(), and setFileMaster().
const std::string & McMd::Diagnostic::outputFileName () const inline protected
Return outputFileName string.
Definition at line 246 of file mcMd/diagnostics/Diagnostic.h.
Referenced by McMd::MdPotentialEnergyAverage::loadParameters(), McMd::AverageDiagnostic< SystemType >::loadParameters(), McMd::MdKineticEnergyAverage::loadParameters(), McMd::MdEnergyOutput::loadParameters(), McMd::PerturbDerivative::loadParameters(), McMd::McEnergyOutput::loadParameters(), McMd::BoundaryAverage::loadParameters(), McMd::McPairEnergyAverage::loadParameters(), McMd::McStressAutoCorr::loadParameters(), McMd::MdPairEnergyCoefficients::loadParameters(), McMd::BennettsMethod::loadParameters(), McMd::RadiusGyration::loadParameters(), McMd::BlockRadiusGyration::loadParameters(), McMd::AverageDiagnostic< SystemType >::output(), McMd::MdEnergyOutput::output(), McMd::SemiGrandDistribution::output(), McMd::McEnergyOutput::output(), McMd::TypeDistribution::output(), McMd::MdPotentialEnergyAverage::output(), McMd::MdKineticEnergyAverage::output(), McMd::PerturbDerivative::output(), McMd::MdPairEnergyCoefficients::output(), McMd::BoundaryAverage::output(), McMd::BondLengthDist::output(), McMd::AtomMSD::output(), McMd::McPairEnergyAverage::output(), McMd::ComMSD::output(), McMd::McStressAutoCorr::output(), McMd::RingRouseAutoCorr::output(), McMd::BennettsMethod::output(), McMd::BlockRadiusGyration::output(), McMd::LinearRouseAutoCorr::output(), McMd::RDF::output(), McMd::CompositionProfile::output(), McMd::MigratingVanHove::output(), McMd::IntraPairAutoCorr::output(), McMd::StructureFactorPGrid::output(), McMd::RadiusGyration::output(), McMd::StructureFactorGrid::output(), McMd::IntraStructureFactorGrid::output(), McMd::VanHove::output(), McMd::StructureFactor::output(), McMd::IntraStructureFactor::output(), McMd::StructureFactorP::output(), McMd::MdPotentialEnergyAverage::readParameters(), McMd::AverageDiagnostic< SystemType >::readParameters(), McMd::MdEnergyOutput::readParameters(), McMd::MdKineticEnergyAverage::readParameters(), McMd::PerturbDerivative::readParameters(), McMd::McEnergyOutput::readParameters(), McMd::BoundaryAverage::readParameters(), McMd::McPairEnergyAverage::readParameters(), McMd::McStressAutoCorr::readParameters(), McMd::MdPairEnergyCoefficients::readParameters(), McMd::BennettsMethod::readParameters(), McMd::RadiusGyration::readParameters(), McMd::BlockRadiusGyration::readParameters(), McMd::DumpConfig::sample(), McMd::StructureFactorGrid::sample(), and McMd::IntraStructureFactorGrid::sample().
std::string McMd::Diagnostic::outputFileName (const std::string & suffix) const protected
Return outputFileName string with added suffix.
Definition at line 153 of file mcMd/diagnostics/Diagnostic.cpp.
References outputFileName_.
Member Data Documentation
long McMd::Diagnostic::baseInterval = 1 static
The interval for a Diagnostic must be a multiple of baseInterval.
Definition at line 157 of file mcMd/diagnostics/Diagnostic.h.
Referenced by initStatic(), loadInterval(), McMd::DiagnosticManager::loadParameters(), readInterval(), McMd::DiagnosticManager::readParam(), McMd::DiagnosticManager::sample(), McMd::DiagnosticManager::save(), McMd::McSimulation::simulate(), and McMd::MdSimulation::simulate().
std::string McMd::Diagnostic::outputFileName_ protected
Base name of output file(s).
Definition at line 217 of file mcMd/diagnostics/Diagnostic.h.
Referenced by loadOutputFileName(), outputFileName(), readOutputFileName(), and save().
long McMd::Diagnostic::interval_ protected
Number of simulation steps between subsequent actions.
Definition at line 220 of file mcMd/diagnostics/Diagnostic.h.
Referenced by loadInterval(), readInterval(), and save().
The documentation for this class was generated from the following files:
mcMd/diagnostics/Diagnostic.h
mcMd/diagnostics/Diagnostic.cpp