Simpatico: McMd::IntraPairAutoCorr Class Reference
McMd::IntraPairAutoCorr Class Reference
Diagnostics
Detailed Description
Autocorrelation for vector separation of any two monomers on a molecule.
This class evaluates the autocorrelation function for the vector that separates two atoms with indices atom1Id and atom2Id on a molecule of species speciesId. It can be used to evaluate the autocorrelation function for individual bonds or for the end-to-end vector of a linear polymer.
If atom1Id = i and atom2Id = j, let . This class calculates and outputs the function
where is a time separation, and where denotes an * average over values of the time t and over all molecules in a species. Here, denotes a dot product of values of the vector at different times.
Definition at line 46 of file IntraPairAutoCorr.h.
#include <IntraPairAutoCorr.h>
Public Member Functions
IntraPairAutoCorr (System &system)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Set number of molecules and clear accumulator.
virtual void sample (long iStep)
Evaluate separation vector for all chains, add to ensemble.
virtual void output ()
Output results after simulation is completed.
Constructor & Destructor Documentation
McMd::IntraPairAutoCorr::IntraPairAutoCorr (System & system)
Constructor.
Parameters:
system reference to parent System
Definition at line 29 of file IntraPairAutoCorr.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::IntraPairAutoCorr::readParameters (std::istream & in) [virtual]
Read parameters from file.
Input format:
int interval sampling interval
string outputFileName output file name
int speciesId integer Id for molecular Species
int atom1Id local atom Id for 1st atom
int atom2Id local atom Id for 2nd atom
int capacity capacity of array of previous values.
Parameters:
in input parameter stream
Reimplemented from McMd::Diagnostic.
Definition at line 45 of file IntraPairAutoCorr.cpp.
References Util::DArray< Data >::allocate(), McMd::Species::capacity(), McMd::Species::nAtom(), McMd::Diagnostic::readInterval(), McMd::Diagnostic::readOutputFileName(), Util::AutoCorrArray< Data, Product >::setParam(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::IntraPairAutoCorr::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 91 of file IntraPairAutoCorr.cpp.
References Util::DArray< Data >::allocate(), McMd::Species::capacity(), McMd::Species::nAtom(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::IntraPairAutoCorr::save (Serializable::OArchive & ar) [virtual]
Save state to archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 126 of file IntraPairAutoCorr.cpp.
template<class Archive > void McMd::IntraPairAutoCorr::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Diagnostic.
Definition at line 153 of file IntraPairAutoCorr.h.
References McMd::serialize().
void McMd::IntraPairAutoCorr::setup () [virtual]
Set number of molecules and clear accumulator.
Reimplemented from McMd::Diagnostic.
Definition at line 132 of file IntraPairAutoCorr.cpp.
References Util::AutoCorrArray< Data, Product >::clear(), McMd::System::nMolecule(), Util::AutoCorrArray< Data, Product >::setNEnsemble(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::IntraPairAutoCorr::sample (long iStep) [virtual]
Evaluate separation vector for all chains, add to ensemble.
Parameters:
iStep counter for number of steps
Implements McMd::Diagnostic.
Definition at line 147 of file IntraPairAutoCorr.cpp.
References McMd::Molecule::atom(), McMd::System::boundary(), Util::OrthorhombicBoundary::distanceSq(), McMd::Diagnostic::isAtInterval(), McMd::System::molecule(), McMd::Atom::position(), Util::AutoCorrArray< Data, Product >::sample(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::IntraPairAutoCorr::output () [virtual]
Output results after simulation is completed.
Reimplemented from McMd::Diagnostic.
Definition at line 185 of file IntraPairAutoCorr.cpp.
References Util::AutoCorrArray< Data, Product >::average(), Util::AutoCorrArray< Data, Product >::bufferCapacity(), McMd::Diagnostic::fileMaster(), Util::AutoCorrArray< Data, Product >::nEnsemble(), Util::AutoCorrArray< Data, Product >::nSample(), Util::FileMaster::openOutputFile(), Util::AutoCorrArray< Data, Product >::output(), McMd::Diagnostic::outputFileName(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
IntraPairAutoCorr.h
IntraPairAutoCorr.cpp