Simpatico: Inter::MultiHarmonicDihedral Class Reference
Inter::MultiHarmonicDihedral Class Reference
Dihedral Interactions
Detailed Description
A truncated Fourier series dihedral potential.
This class defines a dihedral potential:
where phi is the dihedral potential defined in Dihedral Interactions.
Definition at line 34 of file MultiHarmonicDihedral.h.
#include <MultiHarmonicDihedral.h>
Classes
struct Parameter
Public Member Functions
MultiHarmonicDihedral ()
Default constructor.
MultiHarmonicDihedral (const MultiHarmonicDihedral &other)
Copy constructor.
MultiHarmonicDihedral & operator= (const MultiHarmonicDihedral &other)
Assignment.
void setNDihedralType (int nDihedralType)
Set the number of dihedral types.
void readParameters (std::istream &in)
Read dihedral interaction parameters from input stream.
void writeParam (std::ostream &out)
Write Fourier coefficients to output stream.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void set (std::string name, int type, double value)
Modify a parameter, identified by a string.
double energy (const Vector &b1, const Vector &b2, const Vector &b3, int type) const
Returns potential energy for one dihedral group.
void force (const Vector &b1, const Vector &b2, const Vector &b3, Vector &f1, Vector &f2, Vector &f3, int type) const
Returns derivatives of energy with respect to bond vectors forming the dihedral group.
double get (std::string name, int type) const
Get a parameter value, identified by a string.
std::string className () const
Return name string "MultiHarmonicDihedral".
Constructor & Destructor Documentation
Inter::MultiHarmonicDihedral::MultiHarmonicDihedral ()
Default constructor.
Definition at line 21 of file MultiHarmonicDihedral.cpp.
References Util::ParamComposite::setClassName().
Inter::MultiHarmonicDihedral::MultiHarmonicDihedral (const MultiHarmonicDihedral & other)
Copy constructor.
Definition at line 30 of file MultiHarmonicDihedral.cpp.
References Util::DArray< Data >::allocate().
Member Function Documentation
MultiHarmonicDihedral & Inter::MultiHarmonicDihedral::operator= (const MultiHarmonicDihedral & other)
Assignment.
Definition at line 54 of file MultiHarmonicDihedral.cpp.
References Util::DArray< Data >::allocate(), Util::DArray< Data >::isAllocated(), and UTIL_THROW.
void Inter::MultiHarmonicDihedral::setNDihedralType (int nDihedralType)
Set the number of dihedral types.
Parameters:
nDihedralType number of dihedral types
Definition at line 86 of file MultiHarmonicDihedral.cpp.
References Util::DArray< Data >::allocate(), and UTIL_THROW.
void Inter::MultiHarmonicDihedral::readParameters (std::istream & in) [virtual]
Read dihedral interaction parameters from input stream.
Precondition:
nDihedralType must be set, by calling setNDihedralType().
Parameters:
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 98 of file MultiHarmonicDihedral.cpp.
References UTIL_THROW.
void Inter::MultiHarmonicDihedral::writeParam (std::ostream & out) [virtual]
Write Fourier coefficients to output stream.
Precondition:
nDihedralType must be set, by calling setNDihedralType().
Parameters:
out output stream
Reimplemented from Util::ParamComposite.
Definition at line 118 of file MultiHarmonicDihedral.cpp.
void Inter::MultiHarmonicDihedral::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 137 of file MultiHarmonicDihedral.cpp.
References Util::DArray< Data >::allocate(), and UTIL_THROW.
void Inter::MultiHarmonicDihedral::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 166 of file MultiHarmonicDihedral.cpp.
void Inter::MultiHarmonicDihedral::set (std::string name, int type, double value)
Modify a parameter, identified by a string.
Parameters:
name parameter name
type dihedral type index
value new value of parameter
Definition at line 191 of file MultiHarmonicDihedral.cpp.
References UTIL_THROW.
double Inter::MultiHarmonicDihedral::energy (const Vector & b1, const Vector & b2, const Vector & b3, int type) const [inline]
Returns potential energy for one dihedral group.
0 2 3 o o----o \ / o 1
Parameters:
b1 bond vector from atom 0 to 1
b2 bond vector from atom 1 to 2
b3 bond vector from atom 2 to 3
type type id for dihedral group
Definition at line 204 of file MultiHarmonicDihedral.h.
References Inter::Torsion::computeAngle(), and Inter::Torsion::cosPhi.
void Inter::MultiHarmonicDihedral::force (const Vector & b1, const Vector & b2, const Vector & b3, Vector & f1, Vector & f2, Vector & f3, int type) const [inline]
Returns derivatives of energy with respect to bond vectors forming the dihedral group.
Parameters:
b1 bond vector from atom 1 to 2 (input)
b2 bond vector from atom 2 to 3 (input)
b3 bond vector from atom 3 to 4 (input)
f1 derivative of energy w/respect to b1 (output)
f2 derivative of energy w/respect to b2 (output)
f3 derivative of energy w/respect to b3 (output)
type type id for dihedral group
Definition at line 229 of file MultiHarmonicDihedral.h.
References Inter::TorsionForce::computeDerivatives(), Inter::Torsion::cosPhi, Inter::TorsionForce::d1, Inter::TorsionForce::d2, Inter::TorsionForce::d3, Util::Vector::multiply(), and Util::Vector::zero().
double Inter::MultiHarmonicDihedral::get (std::string name, int type) const
Get a parameter value, identified by a string.
Parameters:
name parameter name (k0, k1, k2, k3, or k4)
type dihedral type index
Returns:
parameter value
Definition at line 217 of file MultiHarmonicDihedral.cpp.
References UTIL_THROW.
std::string Inter::MultiHarmonicDihedral::className () const
Return name string "MultiHarmonicDihedral".
Reimplemented from Util::ParamComposite.
Definition at line 244 of file MultiHarmonicDihedral.cpp.
The documentation for this class was generated from the following files:
MultiHarmonicDihedral.h
MultiHarmonicDihedral.cpp