Simpatico: McMd::McDiagnosticFactory Class Reference
McMd::McDiagnosticFactory Class Reference
Diagnostics
Detailed Description
DiagnosticFactory for an McSimulation.
Definition at line 29 of file McDiagnosticFactory.h.
#include <McDiagnosticFactory.h>
Public Member Functions
McDiagnosticFactory (McSimulation &simulation, McSystem &system)
Constructor.
virtual Diagnostic * factory (const std::string &className) const
Return pointer to a new Diagnostic object.
Protected Member Functions
McSystem & system () const
Return reference to parent McSystem.
McSimulation & simulation () const
Return reference to parent McSimulation.
Constructor & Destructor Documentation
McMd::McDiagnosticFactory::McDiagnosticFactory (McSimulation & simulation, McSystem & system)
Constructor.
Parameters:
simulation parent McSimulation
system parent McSystem
Definition at line 45 of file McDiagnosticFactory.cpp.
References system(), and Util::Factory< Diagnostic >::trySubfactories().
Member Function Documentation
Diagnostic * McMd::McDiagnosticFactory::factory (const std::string & className) const [virtual]
Return pointer to a new Diagnostic object.
Parameters:
className name of a subclass of Diagnostic.
Returns:
base class pointer to a new instance of className.
Implements Util::Factory< Diagnostic >.
Definition at line 55 of file McDiagnosticFactory.cpp.
McSystem& McMd::McDiagnosticFactory::system () const [inline, protected]
Return reference to parent McSystem.
Definition at line 55 of file McDiagnosticFactory.h.
Referenced by McDiagnosticFactory().
McSimulation& McMd::McDiagnosticFactory::simulation () const [inline, protected]
Return reference to parent McSimulation.
Definition at line 61 of file McDiagnosticFactory.h.
The documentation for this class was generated from the following files:
McDiagnosticFactory.h
McDiagnosticFactory.cpp