Simpatico: McMd::MdPairPotential Class Reference
McMd::MdPairPotential Class Reference
Pair Potentials
Detailed Description
An PairPotential for MD simulation.
Definition at line 36 of file MdPairPotential.h.
#include <MdPairPotential.h>
Public Member Functions
MdPairPotential (System &system)
Constructor.
virtual ~MdPairPotential ()
Destructor.
virtual void addForces ()=0
Calculate non-bonded pair forces for all atoms in this System.
PairList Management (non-virtual)
void buildPairList ()
Build the internal PairList.
bool isPairListCurrent ()
Return true if PairList is current, false if obsolete.
void clearPairListStatistics ()
Clear all statistical accumulators stored in PairList.
const PairList & pairList () const
Return a const reference to the internal PairList.
Protected Attributes
PairList pairList_
Verlet neighbor pair list for nonbonded interactions.
Boundary maxBoundary_
Maximum boundary (used to allocated memory for PairList).
Constructor & Destructor Documentation
McMd::MdPairPotential::MdPairPotential (System & system)
Constructor.
Definition at line 25 of file MdPairPotential.cpp.
References Util::ParamComposite::setClassName().
McMd::MdPairPotential::~MdPairPotential () [virtual]
Destructor.
Definition at line 33 of file MdPairPotential.cpp.
Member Function Documentation
virtual void McMd::MdPairPotential::addForces () [pure virtual]
Calculate non-bonded pair forces for all atoms in this System.
Adds non-bonded pair forces to the current values of the forces for all atoms in this system. Before calculating forces, this function checks if the pair list is current, and rebuilds it if necessary.
Implemented in McMd::MdPairPotentialImpl< Interaction >.
Referenced by McMd::MdSystem::calculateForces().
void McMd::MdPairPotential::buildPairList ()
Build the internal PairList.
Before building the PairList, this method also shifts all atom positions into the primary image of the periodic boundary. In an MD simulation, the positions are allowed to wander out of the primary image between calls to this function.
Definition at line 39 of file MdPairPotential.cpp.
References McMd::PairList::addAtom(), McMd::SubSystem::begin(), McMd::SubSystem::boundary(), McMd::PairList::build(), McMd::PairList::clear(), McMd::PairList::makeGrid(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), pairList_, Util::OrthorhombicBoundary::shift(), and McMd::SubSystem::simulation().
Referenced by McMd::MdSimulation::analyzeDumps(), McMd::MdSimulation::analyzeTrajectory(), McMd::MdSystem::loadConfig(), McMd::HybridMdMove::move(), McMd::HybridNphMdMove::move(), McMd::MdMove::move(), McMd::DpdMove::move(), McMd::MdSimulation::readCommands(), McMd::MdSystem::readConfig(), McMd::NvtDpdVvIntegrator::setup(), McMd::NveVvIntegrator::step(), McMd::NvtNhIntegrator::step(), McMd::NvtDpdVvIntegrator::step(), and McMd::NphIntegrator::step().
bool McMd::MdPairPotential::isPairListCurrent ()
Return true if PairList is current, false if obsolete.
A PairList is considered current iff it has been built previously, and no particle has moved by a distance greater than skin/2 since the PairList was last built.
Definition at line 78 of file MdPairPotential.cpp.
References McMd::SubSystem::boundary(), McMd::PairList::isCurrent(), and pairList_.
void McMd::MdPairPotential::clearPairListStatistics ()
Clear all statistical accumulators stored in PairList.
Definition at line 72 of file MdPairPotential.cpp.
References McMd::PairList::clearStatistics(), and pairList_.
Referenced by McMd::MdSystem::loadConfig(), McMd::MdSystem::readConfig(), and McMd::NvtDpdVvIntegrator::setup().
const PairList & McMd::MdPairPotential::pairList () const [inline]
Return a const reference to the internal PairList.
Definition at line 111 of file MdPairPotential.h.
Referenced by McMd::MdSystem::isValid(), and McMd::MdSimulation::simulate().
Member Data Documentation
PairList McMd::MdPairPotential::pairList_ [protected]
Verlet neighbor pair list for nonbonded interactions.
Definition at line 99 of file MdPairPotential.h.
Referenced by buildPairList(), clearPairListStatistics(), and isPairListCurrent().
Boundary McMd::MdPairPotential::maxBoundary_ [protected]
Maximum boundary (used to allocated memory for PairList).
Definition at line 102 of file MdPairPotential.h.
The documentation for this class was generated from the following files:
MdPairPotential.h
MdPairPotential.cpp