Simpatico: DdMd::DdMdGroupTrajectoryWriter Class Reference
DdMd::DdMdGroupTrajectoryWriter Class Reference
Detailed Description
Native binary trajectory format for ddSim, for one group.
Definition at line 23 of file DdMdGroupTrajectoryWriter.h.
#include <DdMdGroupTrajectoryWriter.h>
Public Member Functions
DdMdGroupTrajectoryWriter (Simulation &simulation)
Constructor.
virtual ~DdMdGroupTrajectoryWriter ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameter file block.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void writeHeader (std::ofstream &file)
Read trajectory file header and initialize simulation parameters.
void writeFrame (std::ofstream &file, long iStep)
Read a single frame.
Constructor & Destructor Documentation
DdMd::DdMdGroupTrajectoryWriter::DdMdGroupTrajectoryWriter (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object
Definition at line 27 of file DdMdGroupTrajectoryWriter.cpp.
DdMd::DdMdGroupTrajectoryWriter::~DdMdGroupTrajectoryWriter () [virtual]
Destructor.
Definition at line 34 of file DdMdGroupTrajectoryWriter.cpp.
Member Function Documentation
void DdMd::DdMdGroupTrajectoryWriter::readParameters (std::istream & in) [virtual]
Read parameter file block.
Reimplemented from DdMd::TrajectoryWriter.
Definition at line 40 of file DdMdGroupTrajectoryWriter.cpp.
void DdMd::DdMdGroupTrajectoryWriter::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from DdMd::TrajectoryWriter.
Definition at line 49 of file DdMdGroupTrajectoryWriter.cpp.
void DdMd::DdMdGroupTrajectoryWriter::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from DdMd::TrajectoryWriter.
Definition at line 58 of file DdMdGroupTrajectoryWriter.cpp.
void DdMd::DdMdGroupTrajectoryWriter::writeHeader (std::ofstream & file) [virtual]
Read trajectory file header and initialize simulation parameters.
Parameters:
file output file stream
Reimplemented from DdMd::TrajectoryWriter.
Definition at line 64 of file DdMdGroupTrajectoryWriter.cpp.
References DdMd::TrajectoryWriter::atomCollector(), DdMd::TrajectoryWriter::domain(), DdMd::Atom::groups(), Util::Bit::isSet(), DdMd::AtomCollector::nextPtr(), DdMd::AtomCollector::send(), and DdMd::AtomCollector::setup().
void DdMd::DdMdGroupTrajectoryWriter::writeFrame (std::ofstream & file, long iStep) [virtual]
Read a single frame.
Frames are assumed to be read consecutively.
Parameters:
file output file stream
iStep MD time step index
Implements DdMd::TrajectoryWriter.
Definition at line 86 of file DdMdGroupTrajectoryWriter.cpp.
References DdMd::TrajectoryWriter::atomCollector(), DdMd::TrajectoryWriter::atomStorage(), DdMd::TrajectoryWriter::boundary(), Util::Dimension, DdMd::TrajectoryWriter::domain(), DdMd::Atom::groups(), DdMd::Atom::id(), DdMd::AtomStorage::isCartesian(), Util::Bit::isSet(), DdMd::AtomCollector::nextPtr(), DdMd::Atom::position(), DdMd::AtomCollector::send(), DdMd::AtomCollector::setup(), and Util::OrthorhombicBoundary::transformCartToGen().
The documentation for this class was generated from the following files:
DdMdGroupTrajectoryWriter.h
DdMdGroupTrajectoryWriter.cpp