Simpatico: Util::TextFileIArchive Class Reference
Util::TextFileIArchive Class Reference
Util namespace » Serialization
Detailed Description
Loading archive for text istream.
Definition at line 30 of file TextFileIArchive.h.
#include <TextFileIArchive.h>
Public Member Functions
TextFileIArchive ()
Constructor.
TextFileIArchive (std::string filename)
Constructor.
TextFileIArchive (std::ifstream &file)
Constructor.
virtual ~TextFileIArchive ()
Destructor.
std::ifstream & file ()
Get the underlying ifstream by reference.
template<typename T >
TextFileIArchive & operator& (T &data)
Load one object.
template<typename T >
TextFileIArchive & operator>> (T &data)
Load one object.
template<typename T >
void unpack (T &data)
Load a single T object.
template<typename T >
void unpack (T *array, int n)
Load a C-array of T objects.
template<typename T >
void unpack (T *array, int m, int n, int np)
Load a 2D C array.
Static Public Member Functions
static bool is_saving ()
Returns true;.
static bool is_loading ()
Returns false;.
Constructor & Destructor Documentation
Util::TextFileIArchive::TextFileIArchive ()
Constructor.
Definition at line 18 of file TextFileIArchive.cpp.
Util::TextFileIArchive::TextFileIArchive (std::string filename)
Constructor.
Parameters
filename name of file to open for reading.
Definition at line 27 of file TextFileIArchive.cpp.
Util::TextFileIArchive::TextFileIArchive (std::ifstream & file)
Constructor.
Parameters
file output file
Definition at line 37 of file TextFileIArchive.cpp.
References UTIL_THROW.
Util::TextFileIArchive::~TextFileIArchive () virtual
Destructor.
Definition at line 51 of file TextFileIArchive.cpp.
Member Function Documentation
bool Util::TextFileIArchive::is_saving () inline static
Returns true;.
Definition at line 125 of file TextFileIArchive.h.
bool Util::TextFileIArchive::is_loading () inline static
Returns false;.
Definition at line 128 of file TextFileIArchive.h.
std::ifstream & Util::TextFileIArchive::file ()
Get the underlying ifstream by reference.
Definition at line 61 of file TextFileIArchive.cpp.
References unpack().
template<typename T > TextFileIArchive & Util::TextFileIArchive::operator& (T & data) inline
Load one object.
Definition at line 137 of file TextFileIArchive.h.
template<typename T > TextFileIArchive & Util::TextFileIArchive::operator>> (T & data) inline
Load one object.
Definition at line 147 of file TextFileIArchive.h.
template<typename T > void Util::TextFileIArchive::unpack (T & data) inline
Load a single T object.
Parameters
data object to be loaded from this archive.
Definition at line 159 of file TextFileIArchive.h.
Referenced by file(), and unpack().
template<typename T > void Util::TextFileIArchive::unpack (T * array, int n) inline
Load a C-array of T objects.
Parameters
array pointer to array of T objecs.
n number of elements in array
Definition at line 166 of file TextFileIArchive.h.
template<typename T > void Util::TextFileIArchive::unpack (T * array, int m, int n, int np)
Load a 2D C array.
Parameters
array pointer to first row or element
m logical number of rows
n logical number of columns
np physical number of columns (elements allocated per row)
Definition at line 177 of file TextFileIArchive.h.
References unpack().
The documentation for this class was generated from the following files:
TextFileIArchive.h
TextFileIArchive.cpp