Simpatico: McMd::MdPairEnergyCoefficients Class Reference
McMd::MdPairEnergyCoefficients Class Reference
MD Analyzers
Detailed Description
Analyzer to output the total pair energy and the sum of squares of the monomeric and molecular pair energy.
Definition at line 35 of file MdPairEnergyCoefficients.h.
#include <MdPairEnergyCoefficients.h>
Public Member Functions
MdPairEnergyCoefficients (MdSystem &system)
Constructor.
~MdPairEnergyCoefficients ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters and initialize.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void sample (long iStep)
Evaluate energy and print.
virtual void output ()
Output final summary and file format.
Public Member Functions inherited from McMd::SystemAnalyzer< MdSystem >
SystemAnalyzer (MdSystem &system)
Constructor.
virtual ~SystemAnalyzer ()
Destructor.
Public Member Functions inherited from McMd::Analyzer
Analyzer ()
Default constructor.
virtual ~Analyzer ()
Destructor.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Complete any required initialization.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from McMd::Analyzer
static void initStatic ()
Define and initialize baseInterval.
Static Public Attributes inherited from McMd::Analyzer
static long baseInterval = 1
The interval for an Analyzer must be a multiple of baseInterval.
Protected Member Functions inherited from McMd::SystemAnalyzer< MdSystem >
MdSystem & system ()
Return reference to parent system.
Protected Attributes inherited from McMd::Analyzer
std::string outputFileName_
Base name of output file(s).
long interval_
Number of simulation steps between subsequent actions.
Constructor & Destructor Documentation
McMd::MdPairEnergyCoefficients::MdPairEnergyCoefficients (MdSystem & system)
Constructor.
Definition at line 29 of file MdPairEnergyCoefficients.cpp.
References Util::ParamComposite::setClassName().
McMd::MdPairEnergyCoefficients::~MdPairEnergyCoefficients ()
Destructor.
Definition at line 42 of file MdPairEnergyCoefficients.cpp.
Member Function Documentation
void McMd::MdPairEnergyCoefficients::readParameters (std::istream & in) virtual
Read parameters and initialize.
Reads output file, pair selector and maximum number of neighbors per molecule
Parameters
in input parameter stream
Reimplemented from McMd::Analyzer.
Definition at line 66 of file MdPairEnergyCoefficients.cpp.
References McMd::Species::capacity(), McMd::Analyzer::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Analyzer::outputFileName(), McMd::Analyzer::readInterval(), McMd::Analyzer::readOutputFileName(), McMd::System::simulation(), McMd::Simulation::species(), and McMd::SystemAnalyzer< MdSystem >::system().
void McMd::MdPairEnergyCoefficients::loadParameters (Serializable::IArchive & ar) virtual
Load state from an archive.
Parameters
ar loading (input) archive.
Reimplemented from McMd::Analyzer.
Definition at line 99 of file MdPairEnergyCoefficients.cpp.
References McMd::Species::capacity(), McMd::Analyzer::fileMaster(), McMd::Analyzer::loadInterval(), McMd::Analyzer::loadOutputFileName(), Util::FileMaster::openOutputFile(), McMd::Analyzer::outputFileName(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemAnalyzer< MdSystem >::system(), and UTIL_THROW.
void McMd::MdPairEnergyCoefficients::save (Serializable::OArchive & ar) virtual
Save state to archive.
Parameters
ar saving (output) archive.
Reimplemented from McMd::Analyzer.
Definition at line 151 of file MdPairEnergyCoefficients.cpp.
template<class Archive > void McMd::MdPairEnergyCoefficients::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters
ar saving or loading archive
version archive version id
Definition at line 146 of file MdPairEnergyCoefficients.h.
void McMd::MdPairEnergyCoefficients::sample (long iStep) virtual
Evaluate energy and print.
Implements McMd::Analyzer.
Definition at line 157 of file MdPairEnergyCoefficients.cpp.
References Util::DSArray< Data >::begin(), McMd::PairList::begin(), McMd::Species::capacity(), Util::OrthorhombicBoundary::distanceSq(), McMd::PairPotential::energy(), McMd::PairIterator::getPair(), McMd::Molecule::id(), McMd::Species::id(), McMd::Analyzer::isAtInterval(), McMd::PairSelector::match(), McMd::Atom::molecule(), Util::ConstArrayIterator< Data >::notEnd(), McMd::PairIterator::notEnd(), McMd::Atom::position(), Util::Average::sample(), McMd::System::simulation(), McMd::Molecule::species(), McMd::Simulation::species(), McMd::SystemAnalyzer< MdSystem >::system(), and McMd::Atom::typeId().
void McMd::MdPairEnergyCoefficients::output () virtual
Output final summary and file format.
Reimplemented from McMd::Analyzer.
Definition at line 320 of file MdPairEnergyCoefficients.cpp.
References McMd::Analyzer::fileMaster(), Util::FileMaster::openOutputFile(), Util::Average::output(), McMd::Analyzer::outputFileName(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
MdPairEnergyCoefficients.h
MdPairEnergyCoefficients.cpp