Simpatico: Inter::CosineAngle Class Reference
Inter::CosineAngle Class Reference
Angle Interactions
Detailed Description
A three body angle potential, as a function of angle cosine.
This class implements an angle potential: kappa (1 - cos[theta]).
Definition at line 30 of file CosineAngle.h.
#include <CosineAngle.h>
Public Member Functions
CosineAngle ()
Default constructor.
CosineAngle (const CosineAngle &other)
Copy constructor.
~CosineAngle ()
Destructor.
CosineAngle & operator= (const CosineAngle &other)
Assignment.
void setNAngleType (int nAngleType)
Set the number of angle types.
void readParameters (std::istream &in)
Read angle interaction parameters from input stream.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void set (std::string name, int type, double value)
Modify a parameter, identified by a string.
double energy (double cosTheta, int type) const
Returns potential energy for one angle.
void force (const Vector &R1, const Vector &R2, Vector &F1, Vector &F2, int type) const
Returns angle forces.
double randomAngle (Random *random, double beta, int type) const
Return bond angle chosen from equilibrium distribution.
double randomCosineAngle (Random *random, double beta, int type) const
Return bond angle cosine chosen from equilibrium distribution.
double get (std::string name, int type) const
Get a parameter value, identified by a string.
std::string className () const
Return name string "CosineAngle" for this evaluator class.
Constructor & Destructor Documentation
Inter::CosineAngle::CosineAngle ()
Default constructor.
Definition at line 20 of file CosineAngle.cpp.
References Util::ParamComposite::setClassName().
Inter::CosineAngle::CosineAngle (const CosineAngle & other)
Copy constructor.
Definition at line 32 of file CosineAngle.cpp.
Inter::CosineAngle::~CosineAngle ()
Destructor.
Definition at line 44 of file CosineAngle.cpp.
Member Function Documentation
CosineAngle & Inter::CosineAngle::operator= (const CosineAngle & other)
Assignment.
Definition at line 50 of file CosineAngle.cpp.
void Inter::CosineAngle::setNAngleType (int nAngleType)
Set the number of angle types.
Parameters:
nAngleType number of angle types
Definition at line 64 of file CosineAngle.cpp.
References UTIL_THROW.
void Inter::CosineAngle::readParameters (std::istream & in) [virtual]
Read angle interaction parameters from input stream.
Format: kappa CArray<double>
Precondition:
nAngleType must be set, by calling setNAngleType().
Parameters:
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 75 of file CosineAngle.cpp.
References UTIL_THROW.
void Inter::CosineAngle::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 86 of file CosineAngle.cpp.
References UTIL_THROW.
void Inter::CosineAngle::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 98 of file CosineAngle.cpp.
References Util::BinaryFileOArchive::pack().
void Inter::CosineAngle::set (std::string name, int type, double value)
Modify a parameter, identified by a string.
Parameters:
name parameter name
type angle type index
value new value of parameter
Definition at line 157 of file CosineAngle.cpp.
References UTIL_THROW.
double Inter::CosineAngle::energy (double cosTheta, int type) const [inline]
Returns potential energy for one angle.
Parameters:
cosTheta cosine of the bend angle.
type type of bend angle.
Definition at line 181 of file CosineAngle.h.
Referenced by randomAngle(), and randomCosineAngle().
void Inter::CosineAngle::force (const Vector & R1, const Vector & R2, Vector & F1, Vector & F2, int type) const [inline]
Returns angle forces.
Returns force components F1 and F2 along the two bonds in the angle.
Parameters:
R1 bond vector from atom 1 to 2.
R2 bond vector from atom 2 to 3.
F1 return force along R1 direction.
F2 return force along R2 direction.
type type of angle.
Definition at line 191 of file CosineAngle.h.
References Util::Vector::abs(), Util::Vector::dot(), and Util::Vector::multiply().
double Inter::CosineAngle::randomAngle (Random * random, double beta, int type) const
Return bond angle chosen from equilibrium distribution.
This function returns a bond angle chosen from the Boltzmann distribution of angle for bonds of random orientation. The distribution P(theta) of values of the angle theta is proportional to sin(theta)*exp[-beta*phi(theta) ], where phi(theta) is the bond energy.
Parameters:
random pointer to random number generator object.
beta inverse temperature
type bond type
Returns:
random bond length chosen from equilibrium distribution.
Definition at line 110 of file CosineAngle.cpp.
References energy(), Util::Constants::Pi, and Util::Random::uniform().
double Inter::CosineAngle::randomCosineAngle (Random * random, double beta, int type) const
Return bond angle cosine chosen from equilibrium distribution.
This function returns a bond angle chosen from the Boltzmann distribution of angle for bonds of random orientation. The distribution P(theta) of values of the angle theta is proportional to sin(theta)*exp[-beta*phi(theta) ], where phi(theta) is the bond energy.
Parameters:
random pointer to random number generator object.
beta inverse temperature
type bond type
Returns:
random bond length chosen from equilibrium distribution.
Definition at line 135 of file CosineAngle.cpp.
References energy(), and Util::Random::uniform().
double Inter::CosineAngle::get (std::string name, int type) const
Get a parameter value, identified by a string.
Parameters:
name parameter name
type angle type index
Returns:
parameter value
Definition at line 169 of file CosineAngle.cpp.
References UTIL_THROW.
std::string Inter::CosineAngle::className () const
Return name string "CosineAngle" for this evaluator class.
Reimplemented from Util::ParamComposite.
Definition at line 183 of file CosineAngle.cpp.
The documentation for this class was generated from the following files:
CosineAngle.h
CosineAngle.cpp