Simpatico: McMd::Ring Class Reference
McMd::Ring Class Reference
Species
Detailed Description
A Species of ring polymers (abstract).
A Ring molecule is a loop of nMolParticle atoms with consecutive atom indices, with nMolParticle bonds between neighboring atoms.
A Ring molecule may be chemically heterogeneous - different atoms and bonds in a loop may be of different types. The chemical structure of a subclass of Ring must be specified by implementing the pure virtual functions atomTypeId() and bondTypeId().
Definition at line 31 of file Ring.h.
#include <Ring.h>
Public Member Functions
Ring ()
Constructor.
virtual ~Ring ()
Destructor.
Protected Member Functions
virtual int calculateAtomTypeId (int index) const =0
Return the atom type id for a specific atom.
virtual int calculateBondTypeId (int index) const =0
Return the bond type id for a specific bond.
virtual int calculateAngleTypeId (int index) const =0
Return the angle type id for a specific angle.
virtual int calculateDihedralTypeId (int index) const =0
Return the dihedral type id for a specific dihedral.
void buildRing ()
Build the chemical structure for a ring molecule.
Constructor & Destructor Documentation
McMd::Ring::Ring ()
Constructor.
Definition at line 21 of file Ring.cpp.
virtual McMd::Ring::~Ring () [inline, virtual]
Destructor.
Definition at line 46 of file Ring.h.
Member Function Documentation
virtual int McMd::Ring::calculateAtomTypeId (int index) const [protected, pure virtual]
Return the atom type id for a specific atom.
Parameters:
index atom index, in the range 0, ... , nAtom_-1
Returns:
type of the specified bond
Implemented in McMd::HomoRing.
Referenced by buildRing().
virtual int McMd::Ring::calculateBondTypeId (int index) const [protected, pure virtual]
Return the bond type id for a specific bond.
Bond i of a ring molecule connects atom i and atom i+1.
Parameters:
index bond index, in the range 0, ... , nBond_-1
Returns:
type of the specified bond
Implemented in McMd::HomoRing.
Referenced by buildRing().
virtual int McMd::Ring::calculateAngleTypeId (int index) const [protected, pure virtual]
Return the angle type id for a specific angle.
Angle i of a ring molecule connects atoms: (i)-(i+1)-(i+2), where atom indices mod to nAtom_.
Parameters:
index local angle index, in the range 0, ... , nAngle_ - 1
Returns:
type of the specified bond
Implemented in McMd::HomoRing.
Referenced by buildRing().
virtual int McMd::Ring::calculateDihedralTypeId (int index) const [protected, pure virtual]
Return the dihedral type id for a specific dihedral.
Dihedral i of a ring molecule connects atoms: (i)-(i+1)-(i+2)-(i+3), where atom indices mod to nAtom_.
Parameters:
index local dihedral index, in the range 0, ... , nDihedral_ - 1
Returns:
type of the specified bond
Implemented in McMd::HomoRing.
Referenced by buildRing().
void McMd::Ring::buildRing () [protected]
Build the chemical structure for a ring molecule.
This method must be called by readSpeciesParam() after values are set for nAtom and nBond. It allocates memory, assigns atom types to all the atoms in a generic molecule, and creates SpeciesGroup<2> objects for all of the bonds.
Definition at line 28 of file Ring.cpp.
References McMd::Species::allocate(), calculateAngleTypeId(), calculateAtomTypeId(), calculateBondTypeId(), calculateDihedralTypeId(), McMd::Species::makeAngle(), McMd::Species::makeBond(), McMd::Species::makeDihedral(), McMd::Species::nAngle(), McMd::Species::nAtom(), McMd::Species::nBond(), McMd::Species::nDihedral(), McMd::Species::setAtomType(), and UTIL_THROW.
Referenced by McMd::HomoRing::loadSpeciesParam(), and McMd::HomoRing::readSpeciesParam().
The documentation for this class was generated from the following files:
Ring.h
Ring.cpp