Simpatico: DdMd::DdMdTrajectoryWriter Class Reference
DdMd::DdMdTrajectoryWriter Class Reference
Detailed Description
Native binary trajectory format for ddSim.
Definition at line 23 of file DdMdTrajectoryWriter.h.
#include <DdMdTrajectoryWriter.h>
Public Member Functions
DdMdTrajectoryWriter (Simulation &simulation)
Constructor.
virtual ~DdMdTrajectoryWriter ()
Destructor.
void writeHeader (std::ofstream &file)
Read trajectory file header and initialize simulation parameters.
void writeFrame (std::ofstream &file, long iStep)
Read a single frame.
Constructor & Destructor Documentation
DdMd::DdMdTrajectoryWriter::DdMdTrajectoryWriter (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object
Definition at line 25 of file DdMdTrajectoryWriter.cpp.
DdMd::DdMdTrajectoryWriter::~DdMdTrajectoryWriter () [virtual]
Destructor.
Definition at line 32 of file DdMdTrajectoryWriter.cpp.
Member Function Documentation
void DdMd::DdMdTrajectoryWriter::writeHeader (std::ofstream & file) [virtual]
Read trajectory file header and initialize simulation parameters.
Parameters:
file output file stream
Reimplemented from DdMd::TrajectoryWriter.
Definition at line 35 of file DdMdTrajectoryWriter.cpp.
References DdMd::TrajectoryWriter::atomStorage(), DdMd::AtomStorage::computeNAtomTotal(), DdMd::TrajectoryWriter::domain(), and DdMd::AtomStorage::nAtomTotal().
void DdMd::DdMdTrajectoryWriter::writeFrame (std::ofstream & file, long iStep) [virtual]
Read a single frame.
Frames are assumed to be read consecutively.
Parameters:
file output file stream
iStep MD time step index
Implements DdMd::TrajectoryWriter.
Definition at line 48 of file DdMdTrajectoryWriter.cpp.
References DdMd::TrajectoryWriter::atomCollector(), DdMd::TrajectoryWriter::atomStorage(), DdMd::TrajectoryWriter::boundary(), Util::Dimension, DdMd::TrajectoryWriter::domain(), DdMd::Atom::id(), DdMd::AtomStorage::isCartesian(), DdMd::AtomCollector::nextPtr(), DdMd::Atom::position(), DdMd::AtomCollector::send(), DdMd::AtomCollector::setup(), and Util::OrthorhombicBoundary::transformCartToGen().
The documentation for this class was generated from the following files:
DdMdTrajectoryWriter.h
DdMdTrajectoryWriter.cpp