Simpatico: McMd::CfbReptationMove Class Reference
McMd::CfbReptationMove Class Reference
Monte Carlo Moves
Detailed Description
Configuration bias reptation move for a Linear species.
A reptation move uses a configuration bias algorithm to add a segment to one end of a chain (the head) and delete one from the other (the tail). The direction of the move (i.e., which end is the head) is chosen at random. The only parameter is nTrial, the number of trial positions for the new position of the head monomer.
Definition at line 35 of file CfbReptationMove.h.
#include <CfbReptationMove.h>
Public Member Functions
CfbReptationMove (McSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read species to which displacement is applied.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual bool move ()
Generate and accept or reject configuration bias move.
virtual void output ()
Output statistics about accepted reptation steps.
Constructor & Destructor Documentation
McMd::CfbReptationMove::CfbReptationMove (McSystem & system)
Constructor.
Definition at line 31 of file CfbReptationMove.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::CfbReptationMove::readParameters (std::istream & in) [virtual]
Read species to which displacement is applied.
Reimplemented from McMd::CfbEndBase.
Definition at line 51 of file CfbReptationMove.cpp.
References Util::DArray< Data >::allocate(), McMd::Species::atomTypeId(), McMd::Species::capacity(), McMd::Simulation::maskedPairPolicy(), McMd::CfbEndBase::MaxTrial_, McMd::Species::nAtom(), McMd::Species::nBond(), McMd::CfbEndBase::nTrial_, McMd::McMove::readProbability(), McMd::McMove::simulation(), McMd::Simulation::species(), McMd::Species::speciesBond(), McMd::SpeciesGroup< NAtom >::typeId(), and UTIL_THROW.
void McMd::CfbReptationMove::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::McMove.
Definition at line 127 of file CfbReptationMove.cpp.
References McMd::CfbEndBase::MaxTrial_, McMd::Species::nBond(), McMd::CfbEndBase::nTrial_, McMd::McMove::simulation(), McMd::Simulation::species(), McMd::Species::speciesBond(), McMd::SpeciesGroup< NAtom >::typeId(), and UTIL_THROW.
void McMd::CfbReptationMove::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::McMove.
Definition at line 172 of file CfbReptationMove.cpp.
References McMd::CfbEndBase::nTrial_.
bool McMd::CfbReptationMove::move () [virtual]
Generate and accept or reject configuration bias move.
Reimplemented from McMd::McMove.
Definition at line 193 of file CfbReptationMove.cpp.
References McMd::McPairPotential::addAtom(), McMd::CfbEndBase::addEndAtom(), McMd::Mask::append(), McMd::Molecule::atom(), McMd::Mask::clear(), McMd::McPairPotential::deleteAtom(), McMd::CfbEndBase::deleteEndAtom(), McMd::Molecule::id(), McMd::McMove::incrementNAccept(), McMd::McMove::incrementNAttempt(), McMd::Atom::mask(), Util::Random::metropolis(), McMd::Molecule::nAtom(), McMd::McSystem::pairPotential(), McMd::Atom::position(), McMd::McMove::random(), McMd::System::randomMolecule(), McMd::Atom::setTypeId(), McMd::SystemMove::system(), McMd::Atom::typeId(), and McMd::McPairPotential::updateAtomCell().
void McMd::CfbReptationMove::output () [virtual]
Output statistics about accepted reptation steps.
Reimplemented from McMd::McMove.
Definition at line 388 of file CfbReptationMove.cpp.
References Util::DArray< Data >::allocate(), McMd::System::fileMaster(), McMd::System::nMolecule(), Util::FileMaster::openOutputFile(), and McMd::SystemMove::system().
The documentation for this class was generated from the following files:
CfbReptationMove.h
CfbReptationMove.cpp