Simpatico: DdMd::Diagnostic Class Reference
DdMd::Diagnostic Class Reference abstract
Diagnostics
Detailed Description
Abstract base for periodic output and/or analysis actions.
The periodic action associated with a Diagnostic can involve sampling of a physical property and adding it to statistical accumulator, outputting it to file, or both. This periodic action must be implemented by the pure virtual sample() method.
The sample() method should take the desired action only when the simulation step index is an integer multiple of the associated interval parameter. The interval must be a positive integer that is a multiple of the static member Diagnostic::baseInterval.
The virtual sample() method does not take any parameters. A Diagnostic must thus access its parent Simulation and/or Simulation via a pointer, which is usually initialized in its subclass constructor.
Definition at line 43 of file ddMd/diagnostics/Diagnostic.h.
#include <Diagnostic.h>
Public Member Functions
Diagnostic (Simulation &simulation)
Default constructor.
virtual ~Diagnostic ()
Destructor.
virtual void setup ()
Setup before simulation.
virtual void clear ()
Clear statistical accumulators.
virtual void sample (long iStep)=0
Calculate, analyze and/or output a physical quantity.
virtual void output ()
Output any results at the end of a simulation.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
std::string className () const
Get class name string.
virtual void readParam (std::istream &in)
Read a parameter file block.
virtual void readParameters (std::istream &in)
Read body of parameter block, without opening and closing lines.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an archive.
void resetParam ()
Resets ParamComposite to its empty state.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add a new Param < Type > object, and read its value.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add a C array parameter, and read its elements.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and read its elements.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n)
Add and read a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
Begin & readBegin (std::istream &in, const char *label)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a child ParamComposite.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add a new Param < Type > object, and load its value.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add a C array parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and load its elements.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n)
Add and load a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a DMatrix < Type > C two-dimensional matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
template<typename Type >
ScalarParam< Type > & add (const char *label, Type &value)
Add a new Param < Type > object to the format array.
template<typename Type >
CArrayParam< Type > & addCArray (const char *label, Type *value, int n)
Add a C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (const char *label, DArray< Type > &array, int n)
Add a DArray<Type> parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (const char *label, FArray< Type, N > &array)
Add a FArray<Type> parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (const char *label, Type *value, int m, int n)
Add a C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & addDMatrix (const char *label, DMatrix< Type > &matrix, int m, int n)
Add a C two-dimensional array parameter.
Begin & addBegin (const char *label)
Add a class label and opening bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Add a new Blank object, representing a blank line.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have a communicator?
MPI::Intracomm & ioCommunicator () const
Get the communicator.
Static Public Member Functions
static void initStatic ()
Define and initialize baseInterval.
Static Public Attributes
static long baseInterval = 1
The interval for a Diagnostic must be a multiple of baseInterval.
Protected Member Functions
void readInterval (std::istream &in)
Read parameter interval from file.
void loadInterval (Serializable::IArchive &ar)
Load parameter interval from input archive.
void saveInterval (Serializable::OArchive &ar)
Save interval parameter to an archive.
void readOutputFileName (std::istream &in)
Read outputFileName from file.
void loadOutputFileName (Serializable::IArchive &ar)
Load output file name to an archive.
void saveOutputFileName (Serializable::OArchive &ar)
Save output file name to an archive.
Simulation & simulation ()
Get the parent Simulation by reference.
const std::string & outputFileName () const
Return outputFileName string.
std::string outputFileName (const std::string &suffix) const
Return outputFileName string with added suffix.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Constructor & Destructor Documentation
DdMd::Diagnostic::Diagnostic (Simulation & simulation)
Default constructor.
Definition at line 29 of file ddMd/diagnostics/Diagnostic.cpp.
DdMd::Diagnostic::~Diagnostic () virtual
Destructor.
Definition at line 39 of file ddMd/diagnostics/Diagnostic.cpp.
Member Function Documentation
virtual void DdMd::Diagnostic::setup () inline virtual
Setup before simulation.
This method is called just before the beginning of the main simulation loop within the Integrator::run() method. It may be used to complete any initialization or checks that require knowledge of the configuration. It will be called every time run is invoked, not just the first.
The default implementation is empty.
Definition at line 71 of file ddMd/diagnostics/Diagnostic.h.
virtual void DdMd::Diagnostic::clear () inline virtual
Clear statistical accumulators.
This method is called by the Integrator::clear() method, which is called before the main simulation loop only the first time that the integrator is run, and when invoked explicitly thereafter.
The default implementation is empty.
Reimplemented in DdMd::StructureFactor, DdMd::WriteConfig, DdMd::OutputPairEnergies, DdMd::OutputPressure, DdMd::OutputBoxdim, DdMd::OutputEnergy, and DdMd::OutputTemperature.
Definition at line 84 of file ddMd/diagnostics/Diagnostic.h.
virtual void DdMd::Diagnostic::sample (long iStep) pure virtual
Calculate, analyze and/or output a physical quantity.
Take an action if iStep is a multiple of interval. If iStep is not a multiple of interval, this method should do nothing and return immediately.
Parameters
iStep current simulation step index.
Implemented in DdMd::StructureFactor, DdMd::WriteConfig, DdMd::OutputPairEnergies, DdMd::OutputPressure, DdMd::OutputBoxdim, DdMd::OutputEnergy, and DdMd::OutputTemperature.
virtual void DdMd::Diagnostic::output () inline virtual
Output any results at the end of a simulation.
The default implementation is empty.
Reimplemented in DdMd::StructureFactor, and DdMd::StructureFactorGrid.
Definition at line 103 of file ddMd/diagnostics/Diagnostic.h.
virtual void DdMd::Diagnostic::loadParameters (Serializable::IArchive & ar) inline virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Reimplemented in DdMd::StructureFactor, DdMd::StructureFactorGrid, DdMd::WriteConfig, DdMd::OutputPairEnergies, DdMd::OutputBoxdim, DdMd::OutputEnergy, DdMd::OutputPressure, and DdMd::OutputTemperature.
Definition at line 111 of file ddMd/diagnostics/Diagnostic.h.
virtual void DdMd::Diagnostic::save (Serializable::OArchive & ar) inline virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Reimplemented in DdMd::StructureFactor, DdMd::StructureFactorGrid, DdMd::WriteConfig, DdMd::OutputPairEnergies, DdMd::OutputBoxdim, DdMd::OutputEnergy, DdMd::OutputPressure, and DdMd::OutputTemperature.
Definition at line 119 of file ddMd/diagnostics/Diagnostic.h.
int DdMd::Diagnostic::interval () const inline
Get interval value.
Definition at line 231 of file ddMd/diagnostics/Diagnostic.h.
bool DdMd::Diagnostic::isAtInterval (long counter) const inline
Return true iff counter is a multiple of the interval.
Parameters
counter simulation step counter
Definition at line 237 of file ddMd/diagnostics/Diagnostic.h.
Referenced by DdMd::OutputBoxdim::sample(), DdMd::OutputEnergy::sample(), DdMd::OutputTemperature::sample(), DdMd::OutputPressure::sample(), DdMd::OutputPairEnergies::sample(), DdMd::WriteConfig::sample(), and DdMd::StructureFactor::sample().
void DdMd::Diagnostic::initStatic () static
Define and initialize baseInterval.
Definition at line 23 of file ddMd/diagnostics/Diagnostic.cpp.
References baseInterval.
void DdMd::Diagnostic::readInterval (std::istream & in) protected
Read parameter interval from file.
This function throws an exception if the value of interval is not a multiple of Diagnostic::baseInterval, or if baseInterval has not been set to a nonzero positive value.
Parameters
in input parameter file stream.
Definition at line 45 of file ddMd/diagnostics/Diagnostic.cpp.
References baseInterval, and UTIL_THROW.
Referenced by DdMd::OutputBoxdim::readParameters(), DdMd::OutputEnergy::readParameters(), DdMd::OutputPressure::readParameters(), DdMd::OutputTemperature::readParameters(), DdMd::OutputPairEnergies::readParameters(), DdMd::WriteConfig::readParameters(), DdMd::StructureFactorGrid::readParameters(), and DdMd::StructureFactor::readParameters().
void DdMd::Diagnostic::loadInterval (Serializable::IArchive & ar) protected
Load parameter interval from input archive.
This function throws an exception if the value of interval is not a multiple of Diagnostic::baseInterval, or if baseInterval has not been set to a nonzero positive value.
Parameters
ar input archive
Definition at line 77 of file ddMd/diagnostics/Diagnostic.cpp.
References baseInterval, and UTIL_THROW.
Referenced by DdMd::OutputBoxdim::loadParameters(), DdMd::OutputEnergy::loadParameters(), DdMd::OutputPressure::loadParameters(), DdMd::OutputTemperature::loadParameters(), DdMd::OutputPairEnergies::loadParameters(), DdMd::WriteConfig::loadParameters(), DdMd::StructureFactorGrid::loadParameters(), and DdMd::StructureFactor::loadParameters().
void DdMd::Diagnostic::saveInterval (Serializable::OArchive & ar) protected
Save interval parameter to an archive.
Parameters
ar output archive
Definition at line 106 of file ddMd/diagnostics/Diagnostic.cpp.
Referenced by DdMd::OutputBoxdim::save(), DdMd::OutputEnergy::save(), DdMd::OutputPressure::save(), DdMd::OutputTemperature::save(), DdMd::OutputPairEnergies::save(), DdMd::WriteConfig::save(), DdMd::StructureFactorGrid::save(), and DdMd::StructureFactor::save().
void DdMd::Diagnostic::readOutputFileName (std::istream & in) protected
Read outputFileName from file.
Parameters
in input parameter file
Definition at line 112 of file ddMd/diagnostics/Diagnostic.cpp.
Referenced by DdMd::OutputBoxdim::readParameters(), DdMd::OutputEnergy::readParameters(), DdMd::OutputPressure::readParameters(), DdMd::OutputTemperature::readParameters(), DdMd::OutputPairEnergies::readParameters(), DdMd::WriteConfig::readParameters(), DdMd::StructureFactorGrid::readParameters(), and DdMd::StructureFactor::readParameters().
void DdMd::Diagnostic::loadOutputFileName (Serializable::IArchive & ar) protected
Load output file name to an archive.
Parameters
ar input archive
Definition at line 118 of file ddMd/diagnostics/Diagnostic.cpp.
Referenced by DdMd::OutputBoxdim::loadParameters(), DdMd::OutputEnergy::loadParameters(), DdMd::OutputPressure::loadParameters(), DdMd::OutputTemperature::loadParameters(), DdMd::OutputPairEnergies::loadParameters(), DdMd::WriteConfig::loadParameters(), DdMd::StructureFactorGrid::loadParameters(), and DdMd::StructureFactor::loadParameters().
void DdMd::Diagnostic::saveOutputFileName (Serializable::OArchive & ar) protected
Save output file name to an archive.
Parameters
ar output archive
Definition at line 126 of file ddMd/diagnostics/Diagnostic.cpp.
Referenced by DdMd::OutputBoxdim::save(), DdMd::OutputEnergy::save(), DdMd::OutputPressure::save(), DdMd::OutputTemperature::save(), DdMd::OutputPairEnergies::save(), DdMd::WriteConfig::save(), DdMd::StructureFactorGrid::save(), and DdMd::StructureFactor::save().
Simulation & DdMd::Diagnostic::simulation () inline protected
Get the parent Simulation by reference.
Definition at line 249 of file ddMd/diagnostics/Diagnostic.h.
Referenced by DdMd::StructureFactor::clear(), DdMd::OutputBoxdim::loadParameters(), DdMd::OutputPressure::loadParameters(), DdMd::OutputTemperature::loadParameters(), DdMd::OutputPairEnergies::loadParameters(), DdMd::StructureFactorGrid::loadParameters(), DdMd::StructureFactor::loadParameters(), DdMd::StructureFactor::makeWaveVectors(), DdMd::StructureFactorGrid::output(), DdMd::StructureFactor::output(), DdMd::OutputBoxdim::readParameters(), DdMd::OutputPressure::readParameters(), DdMd::OutputTemperature::readParameters(), DdMd::OutputPairEnergies::readParameters(), DdMd::StructureFactorGrid::readParameters(), DdMd::StructureFactor::readParameters(), DdMd::OutputEnergy::sample(), DdMd::OutputTemperature::sample(), DdMd::OutputBoxdim::sample(), DdMd::OutputPairEnergies::sample(), DdMd::OutputPressure::sample(), DdMd::WriteConfig::sample(), and DdMd::StructureFactor::sample().
const std::string & DdMd::Diagnostic::outputFileName () const inline protected
Return outputFileName string.
Definition at line 243 of file ddMd/diagnostics/Diagnostic.h.
Referenced by DdMd::OutputBoxdim::loadParameters(), DdMd::OutputTemperature::loadParameters(), DdMd::OutputPressure::loadParameters(), DdMd::OutputPairEnergies::loadParameters(), DdMd::StructureFactorGrid::output(), DdMd::StructureFactor::output(), DdMd::OutputTemperature::readParameters(), DdMd::OutputBoxdim::readParameters(), DdMd::OutputPressure::readParameters(), DdMd::OutputPairEnergies::readParameters(), and DdMd::WriteConfig::sample().
std::string DdMd::Diagnostic::outputFileName (const std::string & suffix) const protected
Return outputFileName string with added suffix.
Definition at line 132 of file ddMd/diagnostics/Diagnostic.cpp.
Member Data Documentation
long DdMd::Diagnostic::baseInterval = 1 static
The interval for a Diagnostic must be a multiple of baseInterval.
Definition at line 139 of file ddMd/diagnostics/Diagnostic.h.
Referenced by initStatic(), loadInterval(), DdMd::DiagnosticManager::loadParameters(), DdMd::Integrator::loadParameters(), readInterval(), DdMd::DiagnosticManager::readParam(), DdMd::Integrator::readParameters(), DdMd::TwoStepIntegrator::run(), DdMd::DiagnosticManager::sample(), and DdMd::DiagnosticManager::save().
The documentation for this class was generated from the following files:
ddMd/diagnostics/Diagnostic.h
ddMd/diagnostics/Diagnostic.cpp