Simpatico: SpAn::Processor Class Reference
SpAn::Processor Class Reference
Storage
Detailed Description
A post-processor for analyzing outputs of MD simulations.
Definition at line 29 of file Processor.h.
#include <Processor.h>
Public Member Functions
Processor ()
Constructor.
~Processor ()
Destructor.
Initialization
void setOptions (int argc, char *const *argv)
Process command line options.
void readParam (const char *filename)
Open, read, and close parameter file.
void readParameters (std::istream &in)
Read parameters.
ConfigIo Interface
void setConfigIo (const std::string &configIoName)
Set ConfigIo style (creates a ConfigIo).
ConfigIo & configIo ()
Return the current ConfigIo (create default if necessary).
void readConfig (std::ifstream &in)
Read a single configuration file.
void readConfig (const std::string &filename)
Open, read and close a configuration file.
void writeConfig (std::ofstream &out)
Write a single configuration file.
void writeConfig (const std::string &filename)
Open, write and close a configuration file.
Trajectory analysis
void analyzeDumps (int min, int max, std::string fileBaseName)
Read and analyze a sequence of numbered configuration files.
void analyzeTrajectory (std::string &filename)
Analyze a trajectory file.
Miscellaneous functions
bool hasFileMaster () const
Return true if the FileMaster is active.
FileMaster & fileMaster ()
Return FileMaster if active, or throw Exception.
Constructor & Destructor Documentation
SpAn::Processor::Processor ()
Constructor.
Definition at line 25 of file Processor.cpp.
References Util::ParamComposite::setClassName().
SpAn::Processor::~Processor ()
Destructor.
Definition at line 34 of file Processor.cpp.
Member Function Documentation
void SpAn::Processor::setOptions (int argc, char *const * argv)
Process command line options.
Parameters:
argc number of arguments
argv array of argument C-strings
void SpAn::Processor::readParam (const char * filename)
Open, read, and close parameter file.
Reimplemented from SpAn::Configuration.
Definition at line 44 of file Processor.cpp.
void SpAn::Processor::readParameters (std::istream & in) [virtual]
Read parameters.
Reimplemented from SpAn::Configuration.
Definition at line 55 of file Processor.cpp.
References Util::ParamComposite::readParamComposite(), and Util::ParamComposite::readParamCompositeOptional().
void SpAn::Processor::setConfigIo (const std::string & configIoName)
Set ConfigIo style (creates a ConfigIo).
Definition at line 67 of file Processor.cpp.
References SpAn::ConfigIoFactory::factory(), and UTIL_THROW.
ConfigIo & SpAn::Processor::configIo ()
Return the current ConfigIo (create default if necessary).
Definition at line 81 of file Processor.cpp.
Referenced by readConfig(), and writeConfig().
void SpAn::Processor::readConfig (std::ifstream & in)
Read a single configuration file.
Definition at line 93 of file Processor.cpp.
References SpAn::Configuration::clear(), configIo(), and SpAn::ConfigIo::readConfig().
Referenced by analyzeDumps(), and readConfig().
void SpAn::Processor::readConfig (const std::string & filename)
Open, read and close a configuration file.
Definition at line 102 of file Processor.cpp.
References readConfig().
void SpAn::Processor::writeConfig (std::ofstream & out)
Write a single configuration file.
Definition at line 113 of file Processor.cpp.
References configIo(), and SpAn::ConfigIo::writeConfig().
void SpAn::Processor::writeConfig (const std::string & filename)
Open, write and close a configuration file.
Definition at line 119 of file Processor.cpp.
References configIo(), and SpAn::ConfigIo::writeConfig().
void SpAn::Processor::analyzeDumps (int min, int max, std::string fileBaseName)
Read and analyze a sequence of numbered configuration files.
This function reads and analyzes a sequence of configuration files that were generated by running a previous simulation. The function reads files with names of the form inputPrefix() + n for integer suffixes min <= n <= max.
Parameters:
min integer suffix of first configuration file name
max integer suffix of last configuration file name
fileBaseName root name for dump files (without integer suffix)
Definition at line 132 of file Processor.cpp.
References SpAn::Configuration::clear(), Util::Log::file(), SpAn::AnalyzerManager::output(), readConfig(), SpAn::AnalyzerManager::sample(), SpAn::AnalyzerManager::setup(), and UTIL_THROW.
void SpAn::Processor::analyzeTrajectory (std::string & filename)
Analyze a trajectory file.
bool SpAn::Processor::hasFileMaster () const
Return true if the FileMaster is active.
Definition at line 207 of file Processor.cpp.
References Util::ParamComposite::isActive().
FileMaster & SpAn::Processor::fileMaster ()
Return FileMaster if active, or throw Exception.
Definition at line 213 of file Processor.cpp.
References Util::ParamComposite::isActive(), and UTIL_THROW.
Referenced by SpAn::AtomMSD::output().
The documentation for this class was generated from the following files:
Processor.h
Processor.cpp