Simpatico: McMd::DihedralPotentialImpl< Interaction > Class Template Reference
McMd::DihedralPotentialImpl< Interaction > Class Template Reference
McMd namespace » Potential Energies » Dihedral Potentials
Detailed Description
template<class Interaction>
class McMd::DihedralPotentialImpl< Interaction >
Implementation template for an DihedralPotential.
Definition at line 34 of file mcMd/potentials/dihedral/DihedralPotentialImpl.h.
#include <DihedralPotentialImpl.h>
Public Member Functions
DihedralPotentialImpl (System &system)
Constructor.
DihedralPotentialImpl (DihedralPotentialImpl< Interaction > &other)
Constructor (copied from DihedralPotential)
virtual ~DihedralPotentialImpl ()
Destructor.
virtual void readParameters (std::istream &in)
Read dihedral potential parameters.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
Interaction Interface.
virtual double energy (const Vector &R1, const Vector &R2, const Vector &R3, int type) const
Returns potential energy for one dihedral.
virtual void force (const Vector &R1, const Vector &R2, const Vector &R3, Vector &F1, Vector &F2, Vector &F3, int type) const
Returns derivatives of energy with respect to bond vectors forming the dihedral group.
void set (std::string name, int type, double value)
Modify a parameter, identified by a string.
double get (std::string name, int type) const
Get a parameter value, identified by a string.
virtual std::string interactionClassName () const
Return pair interaction class name (e.g., "CosineDihedral").
Interaction & interaction ()
Return dihedral potential interaction by reference.
const Interaction & interaction () const
Return dihedral potential interaction by const reference.
System Energy, Force, Stress calculators
virtual double atomEnergy (const Atom &atom) const
Compute and return the dihedral energy for one Atom.
virtual void addForces ()
Add dihedral forces to all atomic forces.
virtual void computeEnergy ()
Calculate and store dihedral energy for this System.
virtual void computeStress ()
Compute and store the total dihedral pressure.
Public Member Functions inherited from McMd::DihedralPotential
DihedralPotential ()
Constructor.
virtual ~DihedralPotential ()
Destructor (does nothing)
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Public Member Functions inherited from McMd::EnergyCalculator
virtual void unsetEnergy ()
Mark the energy as unknown.
double energy ()
Return the energy contribution, compute if necessary.
Public Member Functions inherited from McMd::StressCalculator
virtual void unsetStress ()
Mark the stress as unknown.
void computeStress (Tensor &stress)
Get pair stress tensor.
void computeStress (Vector &pressures)
Get the xx, yy, zz non-Coulomb pair pressures.
void computeStress (double &pressure)
Get the scalar pressure.
bool createsStress () const
Return false if subclass does not generate stress.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Member Functions inherited from McMd::StressCalculator
StressCalculator (bool createsStress=true)
Constructor (protected to prevent direct instantiation).
Constructor & Destructor Documentation
template<class Interaction > McMd::DihedralPotentialImpl< Interaction >::DihedralPotentialImpl (System & system)
Constructor.
Definition at line 219 of file mcMd/potentials/dihedral/DihedralPotentialImpl.h.
template<class Interaction > McMd::DihedralPotentialImpl< Interaction >::DihedralPotentialImpl (DihedralPotentialImpl< Interaction > & other)
Constructor (copied from DihedralPotential)
Definition at line 230 of file mcMd/potentials/dihedral/DihedralPotentialImpl.h.
template<class Interaction > McMd::DihedralPotentialImpl< Interaction >::~DihedralPotentialImpl () virtual
Destructor.
Definition at line 242 of file mcMd/potentials/dihedral/DihedralPotentialImpl.h.
Member Function Documentation
template<class Interaction > void McMd::DihedralPotentialImpl< Interaction >::readParameters (std::istream & in) virtual
Read dihedral potential parameters.
This method sets the number of dihedral types in the Interaction, and the calls the Interaction::readParameters() to read the parameters for the dihedral potential.
Parameters
in input parameter stream.
Reimplemented from Util::ParamComposite.
Definition at line 249 of file mcMd/potentials/dihedral/DihedralPotentialImpl.h.
References Util::ParamComposite::addParamComposite(), McMd::DihedralPotentialImpl< Interaction >::interaction(), and McMd::SystemInterface::simulation().
template<class Interaction > void McMd::DihedralPotentialImpl< Interaction >::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 264 of file mcMd/potentials/dihedral/DihedralPotentialImpl.h.
References Util::ParamComposite::addParamComposite(), McMd::DihedralPotentialImpl< Interaction >::interaction(), and McMd::SystemInterface::simulation().
template<class Interaction > void McMd::DihedralPotentialImpl< Interaction >::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 279 of file mcMd/potentials/dihedral/DihedralPotentialImpl.h.
References McMd::EnergyCalculator::energy(), and McMd::DihedralPotentialImpl< Interaction >::interaction().
template<class Interaction > double McMd::DihedralPotentialImpl< Interaction >::energy (const Vector & R1, const Vector & R2, const Vector & R3, int type) const inline virtual
Returns potential energy for one dihedral.
1 3 4 o o-—o \ / o 2
Parameters
R1 bond vector from atom 1 to 2.
R2 bond vector from atom 2 to 3.
R3 bond vector from atom 3 to 4.
type type of dihedral.
Implements McMd::DihedralPotential.
Definition at line 292 of file mcMd/potentials/dihedral/DihedralPotentialImpl.h.
References McMd::DihedralPotentialImpl< Interaction >::force(), and McMd::DihedralPotentialImpl< Interaction >::interaction().
template<class Interaction > void McMd::DihedralPotentialImpl< Interaction >::force (const Vector & R1, const Vector & R2, const Vector & R3, Vector & F1, Vector & F2, Vector & F3, int type) const inline virtual
Returns derivatives of energy with respect to bond vectors forming the dihedral group.
Parameters
R1 bond vector from atom 1 to 2.
R2 bond vector from atom 2 to 3.
R3 bond vector from atom 3 to 4.
F1 return force along R1 direction.
F2 return force along R2 direction.
F3 return force along R2 direction.
type type of dihedral.
Implements McMd::DihedralPotential.
Definition at line 300 of file mcMd/potentials/dihedral/DihedralPotentialImpl.h.
References McMd::DihedralPotentialImpl< Interaction >::interaction().
Referenced by McMd::DihedralPotentialImpl< Interaction >::energy().
template<class Interaction> void McMd::DihedralPotentialImpl< Interaction >::set (std::string name, int type, double value) inline virtual
Modify a parameter, identified by a string.
Parameters
name parameter name
type angle type index
value new value of parameter
Implements McMd::DihedralPotential.
Definition at line 124 of file mcMd/potentials/dihedral/DihedralPotentialImpl.h.
template<class Interaction> double McMd::DihedralPotentialImpl< Interaction >::get (std::string name, int type) const inline virtual
Get a parameter value, identified by a string.
Parameters
name parameter name
type angle type index
Returns
parameter value
Implements McMd::DihedralPotential.
Definition at line 134 of file mcMd/potentials/dihedral/DihedralPotentialImpl.h.
template<class Interaction > std::string McMd::DihedralPotentialImpl< Interaction >::interactionClassName () const virtual
Return pair interaction class name (e.g., "CosineDihedral").
Implements McMd::DihedralPotential.
Definition at line 490 of file mcMd/potentials/dihedral/DihedralPotentialImpl.h.
References McMd::DihedralPotentialImpl< Interaction >::interaction().
template<class Interaction > Interaction & McMd::DihedralPotentialImpl< Interaction >::interaction () inline
Return dihedral potential interaction by reference.
Definition at line 479 of file mcMd/potentials/dihedral/DihedralPotentialImpl.h.
Referenced by McMd::DihedralPotentialImpl< Interaction >::addForces(), McMd::DihedralPotentialImpl< Interaction >::atomEnergy(), McMd::DihedralPotentialImpl< Interaction >::computeEnergy(), McMd::DihedralPotentialImpl< Interaction >::energy(), McMd::DihedralPotentialImpl< Interaction >::force(), McMd::DihedralPotentialImpl< Interaction >::interactionClassName(), McMd::DihedralPotentialImpl< Interaction >::loadParameters(), McMd::DihedralPotentialImpl< Interaction >::readParameters(), and McMd::DihedralPotentialImpl< Interaction >::save().
template<class Interaction > const Interaction & McMd::DihedralPotentialImpl< Interaction >::interaction () const inline
Return dihedral potential interaction by const reference.
Definition at line 483 of file mcMd/potentials/dihedral/DihedralPotentialImpl.h.
template<class Interaction > double McMd::DihedralPotentialImpl< Interaction >::atomEnergy (const Atom & atom) const virtual
Compute and return the dihedral energy for one Atom.
Parameters
atom Atom object of interest
Returns
dihedral energy of one atom.
Reimplemented from McMd::DihedralPotential.
Definition at line 308 of file mcMd/potentials/dihedral/DihedralPotentialImpl.h.
References McMd::Group< NAtom >::atom(), McMd::SystemInterface::boundary(), Simp::OrthorhombicBoundary::distanceSq(), McMd::EnergyCalculator::energy(), McMd::getAtomDihedrals(), McMd::DihedralPotentialImpl< Interaction >::interaction(), McMd::Atom::position(), Util::FSArray< Data, Capacity >::size(), and McMd::Group< NAtom >::typeId().
template<class Interaction > void McMd::DihedralPotentialImpl< Interaction >::addForces () virtual
Add dihedral forces to all atomic forces.
Implements McMd::DihedralPotential.
Definition at line 373 of file mcMd/potentials/dihedral/DihedralPotentialImpl.h.
References McMd::SystemInterface::begin(), McMd::SystemInterface::boundary(), Simp::OrthorhombicBoundary::distanceSq(), McMd::Atom::force(), McMd::DihedralPotentialImpl< Interaction >::interaction(), Simp::Species::nDihedral(), Util::ConstArrayIterator< Data >::notEnd(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), Util::ConstPArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), McMd::Atom::position(), Util::setToZero(), McMd::SystemInterface::simulation(), McMd::Simulation::species(), and Simp::OrthorhombicBoundary::volume().
template<class Interaction > void McMd::DihedralPotentialImpl< Interaction >::computeEnergy () virtual
Calculate and store dihedral energy for this System.
Implements McMd::EnergyCalculator.
Definition at line 338 of file mcMd/potentials/dihedral/DihedralPotentialImpl.h.
References McMd::SystemInterface::begin(), McMd::SystemInterface::boundary(), Simp::OrthorhombicBoundary::distanceSq(), McMd::EnergyCalculator::energy(), McMd::DihedralPotentialImpl< Interaction >::interaction(), Simp::Species::nDihedral(), Util::ConstArrayIterator< Data >::notEnd(), Util::ConstPArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::Setable< T >::set(), McMd::SystemInterface::simulation(), and McMd::Simulation::species().
template<class Interaction > void McMd::DihedralPotentialImpl< Interaction >::computeStress () virtual
Compute and store the total dihedral pressure.
Reimplemented from McMd::StressCalculator.
Definition at line 468 of file mcMd/potentials/dihedral/DihedralPotentialImpl.h.
The documentation for this class was generated from the following file:
mcMd/potentials/dihedral/DihedralPotentialImpl.h