Simpatico: McMd::McAnalyzerFactory Class Reference
McMd::McAnalyzerFactory Class Reference
McMd namespace » Analyzers » MC Analyzers
Detailed Description
AnalyzerFactory for an McSimulation.
Definition at line 29 of file McAnalyzerFactory.h.
#include <McAnalyzerFactory.h>
Public Member Functions
McAnalyzerFactory (McSimulation &simulation, McSystem &system)
Constructor.
virtual Analyzer * factory (const std::string &className) const
Return pointer to a new Analyzer object.
Public Member Functions inherited from Util::Factory< Analyzer >
Factory ()
Constructor.
virtual ~Factory ()
Destructor.
void addSubfactory (Factory< Analyzer > &subfactory)
Add a new subfactory to the list.
Analyzer * readObject (std::istream &in, ParamComposite &parent, std::string &className, bool &isEnd)
Read a class name, instantiate an object, and read its parameters.
Analyzer * loadObject (Serializable::IArchive &ar, ParamComposite &parent, std::string &className)
Load a class name, instantiate an object, and load the object.
Protected Member Functions
McSystem & system () const
Return reference to parent McSystem.
McSimulation & simulation () const
Return reference to parent McSimulation.
Protected Member Functions inherited from Util::Factory< Analyzer >
Analyzer * trySubfactories (const std::string &className) const
Search through subfactories for match.
void setIoCommunicator (MPI::Intracomm &communicator)
Set associated Mpi communicator.
bool hasIoCommunicator () const
Does this factory have a param communicator?
Constructor & Destructor Documentation
McMd::McAnalyzerFactory::McAnalyzerFactory (McSimulation & simulation, McSystem & system)
Constructor.
Parameters
simulation parent McSimulation
system parent McSystem
Definition at line 36 of file McAnalyzerFactory.cpp.
Member Function Documentation
Analyzer * McMd::McAnalyzerFactory::factory (const std::string & className) const virtual
Return pointer to a new Analyzer object.
Parameters
className name of a subclass of Analyzer.
Returns
base class pointer to a new instance of className.
Implements Util::Factory< Analyzer >.
Definition at line 46 of file McAnalyzerFactory.cpp.
References McMd::SystemAnalyzerFactory::factory(), system(), and Util::Factory< Analyzer >::trySubfactories().
McSystem& McMd::McAnalyzerFactory::system () const inline protected
Return reference to parent McSystem.
Definition at line 55 of file McAnalyzerFactory.h.
Referenced by factory().
McSimulation& McMd::McAnalyzerFactory::simulation () const inline protected
Return reference to parent McSimulation.
Definition at line 61 of file McAnalyzerFactory.h.
The documentation for this class was generated from the following files:
McAnalyzerFactory.h
McAnalyzerFactory.cpp