Simpatico: Util::Parameter Class Reference
Util::Parameter Class Reference
Parameter File IO
Detailed Description
A single variable in a parameter file.
Parameter is a base class for objects that read and write the value of a single C++ variable from or to a parameter file. The file format for a parameter contains a string label followed by a value.
A Parameter may be required or optional element in a parameter file, depending on the value of the bool isRequired parameter of the constructor. An optional element becomes "active" when an entry with the correct label is read from a parameter file, or when a value is loaded from an archive. By convention, a required Parameter is always active, even before its value is read or loaded. The bool functions isRequired() and isActive() can be used to query the state of a Parameter.
Definition at line 37 of file Parameter.h.
#include <Parameter.h>
Public Member Functions
Parameter (const char *label, bool isRequired=true)
Constructor.
virtual ~Parameter ()
Destructor.
virtual void readParam (std::istream &in)
Read a label and (if the label matches) a parameter value.
virtual void load (Serializable::IArchive &ar)
Load from an archive.
virtual void save (Serializable::OArchive &ar)
Save to an archive.
std::string label () const
Return label string.
bool isRequired () const
Is this an optional parameter?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
virtual void writeParam (std::ostream &out)=0
Read parameter(s) to file.
virtual void resetParam ()
Nontrivial implementation provided by ParamComposite subclass.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Static Public Member Functions
template<class Type >
static void saveOptional (Serializable::OArchive &ar, Type &value, bool isActive)
Save an optional parameter value to an output archive.
template<class Type >
static void saveOptionalCArray (Serializable::OArchive &ar, Type *ptr, int n, bool isActive)
Save an optional C-array of n values to an output archive.
template<class Type >
static void saveOptionalCArray2D (Serializable::OArchive &ar, Type *ptr, int m, int n, int np, bool isActive)
Save an optional two-dimensional C array to an output archive.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Public Attributes
static const int Width = 20
Width of output field for a scalar variable.
static const int Precision = 12
Precision for io of floating point data field.
Protected Member Functions
virtual void readValue (std::istream &in)
Read parameter value from an input stream.
virtual void loadValue (Serializable::IArchive &ar)
Load bare parameter value from an archive.
virtual void saveValue (Serializable::OArchive &ar)
Save parameter value to an archive.
virtual void bcastValue ()
Broadcast parameter value within the ioCommunicator.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
Label label_
Label object that contains parameter label string.
bool isActive_
Is this parameter active (always true if isRequired).
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Constructor & Destructor Documentation
Util::Parameter::Parameter (const char * label, bool isRequired = true)
Constructor.
Parameters
label label string preceding value in file format
isRequired Is this a required parameter?
Definition at line 25 of file Parameter.cpp.
Util::Parameter::~Parameter () virtual
Destructor.
Definition at line 33 of file Parameter.cpp.
Member Function Documentation
template<class Type > void Util::Parameter::saveOptional (Serializable::OArchive & ar, Type & value, bool isActive) static
Save an optional parameter value to an output archive.
Parameters
ar output archive to which to save
value reference to value of optional parameter
isActive Is this parameter present in the parameter file?
Definition at line 211 of file Parameter.h.
References isActive().
Referenced by McMd::Diblock::save(), McMd::Homopolymer::save(), McMd::Simulation::save(), and DdMd::Simulation::save().
template<class Type > void Util::Parameter::saveOptionalCArray (Serializable::OArchive & ar, Type * ptr, int n, bool isActive) static
Save an optional C-array of n values to an output archive.
Parameters
ar output archive to which to save
ptr pointer to first element of optional C-array parameter
n number of elements in array
isActive Is this parameter present in the parameter file?
Definition at line 224 of file Parameter.h.
References isActive(), and Util::BinaryFileOArchive::pack().
template<class Type > void Util::Parameter::saveOptionalCArray2D (Serializable::OArchive & ar, Type * ptr, int m, int n, int np, bool isActive) static
Save an optional two-dimensional C array to an output archive.
Parameters
ar output archive to which to save
ptr pointer to first element optional 2D C-array parameter
m logical number of rows in array
n logical number of columns in array
np logical number of columns in array
isActive Is this parameter present in the parameter file?
Definition at line 237 of file Parameter.h.
References isActive(), and Util::BinaryFileOArchive::pack().
void Util::Parameter::readParam (std::istream & in) virtual
Read a label and (if the label matches) a parameter value.
The parameter file format for a Parameter consists of a label string followed by value. The value is read if and only if the label matches the expected value for this Parameter. If this Parameter is required and the input label not match, an error message is printed to the log file and Exception is thrown. If the Parameter is not required and the input label does not match, the label string is retained in an buffer for later processing by the readParam method of other ParamComponent objects.
Upon entry to this function, a label string is read into a label buffer if and only if the buffer is empty. This buffer is a static member of the Label class, which can retain a label between invocations of the readParameter method of different ParamComponent objects. Once a label string is read from file, it remains in the label buffer until until it is matched, at which point the buffer is cleared to allow processing of the next label.
Parameters
in input stream from which to read
Implements Util::ParamComponent.
Definition at line 39 of file Parameter.cpp.
References Util::bcast< bool >(), bcastValue(), Util::ParamComponent::echo(), Util::Log::file(), Util::MpiFileIo::hasIoCommunicator(), Util::ParamComponent::indent(), Util::MpiFileIo::ioCommunicator(), isActive_, Util::Label::isClear(), Util::MpiFileIo::isIoProcessor(), isRequired(), label_, readValue(), UTIL_THROW, Width, and Util::ParamComponent::writeParam().
Referenced by Util::ParamComposite::read(), Util::ParamComposite::readCArray(), Util::ParamComposite::readCArray2D(), Util::ParamComposite::readDArray(), Util::ParamComposite::readDMatrix(), and Util::ParamComposite::readFArray().
void Util::Parameter::load (Serializable::IArchive & ar) virtual
Load from an archive.
An optional Parameter loads the value of an isActive flag, and then loads a parameter value only if the isActive is true. A required Parameter simply loads the parameter value.
Parameters
ar input archive from which to load
Reimplemented from Util::ParamComponent.
Definition at line 92 of file Parameter.cpp.
References Util::bcast< bool >(), bcastValue(), Util::ParamComponent::echo(), Util::Log::file(), Util::MpiFileIo::hasIoCommunicator(), Util::ParamComponent::indent(), Util::MpiFileIo::ioCommunicator(), isActive_, Util::MpiFileIo::isIoProcessor(), isRequired(), label_, loadValue(), UTIL_THROW, Width, and Util::ParamComponent::writeParam().
Referenced by Util::ParamComposite::loadCArray(), Util::ParamComposite::loadCArray2D(), Util::ParamComposite::loadDArray(), Util::ParamComposite::loadDMatrix(), Util::ParamComposite::loadFArray(), and Util::ParamComposite::loadParameter().
void Util::Parameter::save (Serializable::OArchive & ar) virtual
Save to an archive.
An optional Parameter saves the value of the isActive flag, and then saves a parameter value only if the isActive is true. A required Parameter simply saves its value. The label string is not saved to the archive.
The overloaded static saveOptional functions can also be used to save optional parameter values in this format.
Parameters
ar output archive to which to save
Reimplemented from Util::ParamComponent.
Definition at line 139 of file Parameter.cpp.
References isActive_, isRequired(), and saveValue().
std::string Util::Parameter::label () const
Return label string.
Definition at line 152 of file Parameter.cpp.
References label_, and Util::Label::string().
bool Util::Parameter::isRequired () const
Is this an optional parameter?
Definition at line 158 of file Parameter.cpp.
References Util::Label::isRequired(), and label_.
Referenced by load(), readParam(), and save().
bool Util::Parameter::isActive () const
Is this parameter active?
Definition at line 164 of file Parameter.cpp.
References isActive_.
Referenced by saveOptional(), saveOptionalCArray(), and saveOptionalCArray2D().
virtual void Util::Parameter::readValue (std::istream & in) inline protected virtual
Read parameter value from an input stream.
Parameters
in input stream from which to read
Reimplemented in Util::ScalarParam< Type >, Util::CArray2DParam< Type >, Util::DMatrixParam< Type >, Util::FArrayParam< Type, N >, Util::DArrayParam< Type >, and Util::CArrayParam< Type >.
Definition at line 182 of file Parameter.h.
Referenced by readParam().
virtual void Util::Parameter::loadValue (Serializable::IArchive & ar) inline protected virtual
Load bare parameter value from an archive.
Parameters
ar input archive from which to load
Reimplemented in Util::ScalarParam< Type >, Util::CArray2DParam< Type >, Util::DMatrixParam< Type >, Util::FArrayParam< Type, N >, Util::DArrayParam< Type >, and Util::CArrayParam< Type >.
Definition at line 189 of file Parameter.h.
Referenced by load().
virtual void Util::Parameter::saveValue (Serializable::OArchive & ar) inline protected virtual
Save parameter value to an archive.
Parameters
ar output archive to which to save
Reimplemented in Util::ScalarParam< Type >, Util::CArray2DParam< Type >, Util::DMatrixParam< Type >, Util::FArrayParam< Type, N >, Util::DArrayParam< Type >, and Util::CArrayParam< Type >.
Definition at line 196 of file Parameter.h.
Referenced by save().
virtual void Util::Parameter::bcastValue () inline protected virtual
Broadcast parameter value within the ioCommunicator.
Reimplemented in Util::ScalarParam< Type >, Util::CArray2DParam< Type >, Util::DMatrixParam< Type >, Util::FArrayParam< Type, N >, Util::DArrayParam< Type >, and Util::CArrayParam< Type >.
Definition at line 202 of file Parameter.h.
Referenced by load(), and readParam().
Member Data Documentation
const int Util::Parameter::Width = 20 static
Width of output field for a scalar variable.
Definition at line 45 of file Parameter.h.
Referenced by load(), McMd::operator<<(), DdMd::operator<<(), readParam(), Util::CArrayParam< Type >::writeParam(), Util::DArrayParam< Type >::writeParam(), Util::FArrayParam< Type, N >::writeParam(), Util::DMatrixParam< Type >::writeParam(), Util::ScalarParam< Type >::writeParam(), and Util::CArray2DParam< Type >::writeParam().
const int Util::Parameter::Precision = 12 static
Precision for io of floating point data field.
Definition at line 48 of file Parameter.h.
Referenced by McMd::operator<<(), DdMd::operator<<(), Util::CArrayParam< Type >::writeParam(), Util::DArrayParam< Type >::writeParam(), Util::FArrayParam< Type, N >::writeParam(), Util::DMatrixParam< Type >::writeParam(), Util::ScalarParam< Type >::writeParam(), and Util::CArray2DParam< Type >::writeParam().
Label Util::Parameter::label_ protected
Label object that contains parameter label string.
Definition at line 172 of file Parameter.h.
Referenced by isRequired(), label(), load(), and readParam().
bool Util::Parameter::isActive_ protected
Is this parameter active (always true if isRequired).
Definition at line 175 of file Parameter.h.
Referenced by isActive(), load(), readParam(), and save().
The documentation for this class was generated from the following files:
Parameter.h
Parameter.cpp