Simpatico: DdMd::DihedralPotentialImpl< Interaction > Class Template Reference
DdMd::DihedralPotentialImpl< Interaction > Class Template Reference
Dihedral Potentials
Detailed Description
template<class Interaction>
class DdMd::DihedralPotentialImpl< Interaction >
Implementation template for a DihedralPotential.
Definition at line 34 of file ddMd/potentials/dihedral/DihedralPotentialImpl.h.
#include <DihedralPotentialImpl.h>
Public Member Functions
DihedralPotentialImpl (Simulation &simulation)
Constructor.
DihedralPotentialImpl ()
Default constructor.
virtual ~DihedralPotentialImpl ()
Destructor.
virtual void readParameters (std::istream &in)
Read potential energy parameters.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
Interaction interface
virtual void setNDihedralType (int nAtomType)
Set the maximum number of atom types.
void set (std::string name, int type, double value)
Modify an dihedral parameter, identified by a string.
double get (std::string name, int type) const
Get a parameter value, identified by a string.
virtual double dihedralEnergy (const Vector &R1, const Vector &R2, const Vector &R3, int type) const
Returns potential energy for one dihedral.
virtual void dihedralForce (const Vector &R1, const Vector &R2, const Vector &R3, Vector &F1, Vector &F2, Vector &F3, int type) const
Returns derivatives of energy with respect to bond vectors forming the dihedral group.
virtual std::string interactionClassName () const
Return pair interaction class name (e.g., "CosineDihedral").
Interaction & interaction ()
Return dihedral interaction by reference.
const Interaction & interaction () const
Return dihedral interaction by const reference.
Total Energy, Force and Stress
virtual void computeForces ()
Add the dihedral forces for all atoms.
virtual void computeEnergy (MPI::Intracomm &communicator)
Compute the total dihedral energy for all processors.
virtual void computeStress (MPI::Intracomm &communicator)
Compute the covalent dihedral stress.
Public Member Functions inherited from DdMd::DihedralPotential
DihedralPotential (Simulation &simulation)
Constructor.
DihedralPotential ()
Default constructor (for unit testing).
~DihedralPotential ()
Destructor.
void associate (Boundary &boundary, GroupStorage< 4 > &storage)
Associate with related objects.
Public Member Functions inherited from DdMd::Potential
Potential ()
Constructor.
virtual ~Potential ()
Destructor.
void setReverseUpdateFlag (bool reverseUpdateFlag)
Set flag to identify if reverse communication is enabled.
bool reverseUpdateFlag () const
Get flag to identify if reverse communication is enabled.
double energy () const
Return the total potential, from all processors.
void unsetEnergy ()
Mark the energy as unknown (nullify).
bool isEnergySet () const
Is the energy set (known)?
virtual void computeForcesAndStress (MPI::Intracomm &communicator)
Compute forces and stress for all processors.
Tensor stress () const
Return the stress tensor.
double pressure () const
Return the pressure.
void unsetStress ()
Mark the stress as unknown (nullify).
bool isStressSet () const
Is the stress set (known)?
virtual bool isValid (MPI::Intracomm &communicator) const
Is the potential in a valid internal state?
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from DdMd::DihedralPotential
Boundary & boundary () const
Return boundary by reference.
GroupStorage< 4 > & storage () const
Return bond storage by reference.
Constructor & Destructor Documentation
template<class Interaction > DdMd::DihedralPotentialImpl< Interaction >::DihedralPotentialImpl (Simulation & simulation)
Constructor.
Definition at line 221 of file ddMd/potentials/dihedral/DihedralPotentialImpl.h.
template<class Interaction > DdMd::DihedralPotentialImpl< Interaction >::DihedralPotentialImpl ()
Default constructor.
Definition at line 230 of file ddMd/potentials/dihedral/DihedralPotentialImpl.h.
template<class Interaction > DdMd::DihedralPotentialImpl< Interaction >::~DihedralPotentialImpl () virtual
Destructor.
Definition at line 239 of file ddMd/potentials/dihedral/DihedralPotentialImpl.h.
Member Function Documentation
template<class Interaction > void DdMd::DihedralPotentialImpl< Interaction >::readParameters (std::istream & in) virtual
Read potential energy parameters.
This method reads the dihedral potential Interaction parameter block. Before calling Interaction::readParameters(), it passes simulation().nDihedralType() to Interaction::setNAtomType().
Reimplemented from Util::ParamComposite.
Definition at line 257 of file ddMd/potentials/dihedral/DihedralPotentialImpl.h.
template<class Interaction > void DdMd::DihedralPotentialImpl< Interaction >::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Precondition: setNDihedralType must have been called before this.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 269 of file ddMd/potentials/dihedral/DihedralPotentialImpl.h.
template<class Interaction > void DdMd::DihedralPotentialImpl< Interaction >::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 280 of file ddMd/potentials/dihedral/DihedralPotentialImpl.h.
template<class Interaction > void DdMd::DihedralPotentialImpl< Interaction >::setNDihedralType (int nAtomType) virtual
Set the maximum number of atom types.
Implements DdMd::DihedralPotential.
Definition at line 250 of file ddMd/potentials/dihedral/DihedralPotentialImpl.h.
template<class Interaction > void DdMd::DihedralPotentialImpl< Interaction >::set (std::string name, int type, double value) inline virtual
Modify an dihedral parameter, identified by a string.
Parameters
name parameter variable name
type type index for dihedral group
value new value of parameter
Implements DdMd::DihedralPotential.
Definition at line 288 of file ddMd/potentials/dihedral/DihedralPotentialImpl.h.
template<class Interaction > double DdMd::DihedralPotentialImpl< Interaction >::get (std::string name, int type) const inline virtual
Get a parameter value, identified by a string.
Parameters
name parameter variable name
type type index of dihedral group
Implements DdMd::DihedralPotential.
Definition at line 296 of file ddMd/potentials/dihedral/DihedralPotentialImpl.h.
template<class Interaction > double DdMd::DihedralPotentialImpl< Interaction >::dihedralEnergy (const Vector & R1, const Vector & R2, const Vector & R3, int type) const inline virtual
Returns potential energy for one dihedral.
0   2    3
o   o----o
 \ /
  o
  1
Parameters
R1 bond vector from atom 0 to 1
R2 bond vector from atom 1 to 2
R3 bond vector from atom 2 to 3
type type of dihedral
Implements DdMd::DihedralPotential.
Definition at line 304 of file ddMd/potentials/dihedral/DihedralPotentialImpl.h.
template<class Interaction > void DdMd::DihedralPotentialImpl< Interaction >::dihedralForce (const Vector & R1, const Vector & R2, const Vector & R3, Vector & F1, Vector & F2, Vector & F3, int type) const inline virtual
Returns derivatives of energy with respect to bond vectors forming the dihedral group.
Parameters
R1 bond vector from atom 0 to 1
R2 bond vector from atom 1 to 2
R3 bond vector from atom 2 to 3
F1 force along R1 direction (upon return)
F2 force along R2 direction (upon return)
F3 force along R2 direction (upon return)
type type of dihedral
Implements DdMd::DihedralPotential.
Definition at line 313 of file ddMd/potentials/dihedral/DihedralPotentialImpl.h.
template<class Interaction > std::string DdMd::DihedralPotentialImpl< Interaction >::interactionClassName () const virtual
Return pair interaction class name (e.g., "CosineDihedral").
Implements DdMd::DihedralPotential.
Definition at line 321 of file ddMd/potentials/dihedral/DihedralPotentialImpl.h.
template<class Interaction > Interaction & DdMd::DihedralPotentialImpl< Interaction >::interaction () inline
Return dihedral interaction by reference.
Definition at line 328 of file ddMd/potentials/dihedral/DihedralPotentialImpl.h.
template<class Interaction > const Interaction & DdMd::DihedralPotentialImpl< Interaction >::interaction () const inline
Return dihedral interaction by const reference.
Definition at line 335 of file ddMd/potentials/dihedral/DihedralPotentialImpl.h.
template<class Interaction > void DdMd::DihedralPotentialImpl< Interaction >::computeForces () virtual
Add the dihedral forces for all atoms.
Implements DdMd::Potential.
Definition at line 342 of file ddMd/potentials/dihedral/DihedralPotentialImpl.h.
References DdMd::Atom::force(), DdMd::Atom::isGhost(), Util::PArrayIterator< Group< N > >::notEnd(), and DdMd::Atom::position().
template<class Interaction > void DdMd::DihedralPotentialImpl< Interaction >::computeEnergy (MPI::Intracomm & communicator) virtual
Compute the total dihedral energy for all processors.
Call on all processors (MPI reduce operation).
Implements DdMd::Potential.
Definition at line 401 of file ddMd/potentials/dihedral/DihedralPotentialImpl.h.
References DdMd::Atom::isGhost(), Util::PArrayIterator< Group< N > >::notEnd(), and DdMd::Atom::position().
template<class Interaction > void DdMd::DihedralPotentialImpl< Interaction >::computeStress (MPI::Intracomm & communicator) virtual
Compute the covalent dihedral stress.
Call on all processors.
Reimplemented from DdMd::Potential.
Definition at line 465 of file ddMd/potentials/dihedral/DihedralPotentialImpl.h.
References DdMd::Atom::isGhost(), Util::PArrayIterator< Group< N > >::notEnd(), DdMd::Atom::position(), and Util::Tensor::zero().
The documentation for this class was generated from the following file:
ddMd/potentials/dihedral/DihedralPotentialImpl.h