Simpatico: DdMd::BondPotentialImpl< Interaction > Class Template Reference
DdMd::BondPotentialImpl< Interaction > Class Template Reference
Bond Potentials
Detailed Description
template<class Interaction>
class DdMd::BondPotentialImpl< Interaction >
Implementation template for a BondPotential.
Definition at line 28 of file ddMd/potentials/bond/BondPotentialImpl.h.
#include <BondPotentialImpl.h>
Public Member Functions
BondPotentialImpl (Simulation &simulation)
Constructor.
BondPotentialImpl ()
Default constructor.
virtual ~BondPotentialImpl ()
Destructor.
virtual void setNBondType (int nAtomType)
Set the maximum number of atom types.
virtual void readParam (std::istream &in)
Read potential energy parameters.
Interaction interface
virtual double bondEnergy (double rsq, int bondTypeId) const
Return pair energy for a single pair.
virtual double bondForceOverR (double rsq, int bondTypeId) const
Return force / separation for a single pair.
virtual double randomBondLength (Random *random, double beta, int bondTypeId) const
Return force / separation for a single pair.
const Interaction & interaction () const
Return bond interaction by const reference.
Interaction & interaction ()
Return bond interaction by reference.
Total Energy, Force and Stress
virtual void computeForces ()
Add the bond forces for all atoms.
virtual void computeEnergy (MPI::Intracomm &communicator)
Compute the total bond energy for all processors.
virtual void computeStress (MPI::Intracomm &communicator)
Compute the covalent bond stress.
virtual void computeForcesAndStress (MPI::Intracomm &communicator)
Compute bond forces and stress.
Constructor & Destructor Documentation
template<class Interaction > DdMd::BondPotentialImpl< Interaction >::BondPotentialImpl (Simulation & simulation)
Constructor.
Definition at line 176 of file ddMd/potentials/bond/BondPotentialImpl.h.
template<class Interaction > DdMd::BondPotentialImpl< Interaction >::BondPotentialImpl ()
Default constructor.
Definition at line 185 of file ddMd/potentials/bond/BondPotentialImpl.h.
template<class Interaction > DdMd::BondPotentialImpl< Interaction >::~BondPotentialImpl () [virtual]
Destructor.
Definition at line 194 of file ddMd/potentials/bond/BondPotentialImpl.h.
Member Function Documentation
template<class Interaction > void DdMd::BondPotentialImpl< Interaction >::setNBondType (int nAtomType) [virtual]
Set the maximum number of atom types.
Implements DdMd::BondPotential.
Definition at line 206 of file ddMd/potentials/bond/BondPotentialImpl.h.
template<class Interaction > void DdMd::BondPotentialImpl< Interaction >::readParam (std::istream & in) [virtual]
Read potential energy parameters.
This method reads the bond potential Interaction parameter block. Before calling Interaction::readParam(), it passes simulation().nBondType() to Interaction::setNAtomType().
Reimplemented from Util::ParamComposite.
Definition at line 213 of file ddMd/potentials/bond/BondPotentialImpl.h.
template<class Interaction > double DdMd::BondPotentialImpl< Interaction >::bondEnergy (double rsq, int bondTypeId) const [virtual]
Return pair energy for a single pair.
Implements DdMd::BondPotential.
Definition at line 226 of file ddMd/potentials/bond/BondPotentialImpl.h.
template<class Interaction > double DdMd::BondPotentialImpl< Interaction >::bondForceOverR (double rsq, int bondTypeId) const [virtual]
Return force / separation for a single pair.
Implements DdMd::BondPotential.
Definition at line 234 of file ddMd/potentials/bond/BondPotentialImpl.h.
template<class Interaction > double DdMd::BondPotentialImpl< Interaction >::randomBondLength (Random * random, double beta, int bondTypeId) const [virtual]
Return force / separation for a single pair.
Implements DdMd::BondPotential.
Definition at line 243 of file ddMd/potentials/bond/BondPotentialImpl.h.
template<class Interaction > const Interaction & DdMd::BondPotentialImpl< Interaction >::interaction () const [inline]
Return bond interaction by const reference.
Get Interaction by const reference.
Definition at line 257 of file ddMd/potentials/bond/BondPotentialImpl.h.
template<class Interaction > Interaction & DdMd::BondPotentialImpl< Interaction >::interaction () [inline]
Return bond interaction by reference.
Get Interaction by reference.
Definition at line 250 of file ddMd/potentials/bond/BondPotentialImpl.h.
template<class Interaction > void DdMd::BondPotentialImpl< Interaction >::computeForces () [virtual]
Add the bond forces for all atoms.
Implements DdMd::Potential.
Definition at line 264 of file ddMd/potentials/bond/BondPotentialImpl.h.
References DdMd::Atom::force(), DdMd::Atom::isGhost(), Util::PArrayIterator< Group< N > >::notEnd(), and DdMd::Atom::position().
template<class Interaction > void DdMd::BondPotentialImpl< Interaction >::computeEnergy (MPI::Intracomm & communicator) [virtual]
Compute the total bond energy for all processors.
Call on all processors (MPI reduce operation).
Implements DdMd::Potential.
Definition at line 300 of file ddMd/potentials/bond/BondPotentialImpl.h.
References DdMd::Atom::isGhost(), Util::PArrayIterator< Group< N > >::notEnd(), and DdMd::Atom::position().
template<class Interaction > void DdMd::BondPotentialImpl< Interaction >::computeStress (MPI::Intracomm & communicator) [virtual]
Compute the covalent bond stress.
Call on all processors.
Implements DdMd::Potential.
Definition at line 349 of file ddMd/potentials/bond/BondPotentialImpl.h.
References DdMd::Atom::isGhost(), Util::PArrayIterator< Group< N > >::notEnd(), DdMd::Atom::position(), and Util::Tensor::zero().
template<class Interaction > void DdMd::BondPotentialImpl< Interaction >::computeForcesAndStress (MPI::Intracomm & communicator) [virtual]
Compute bond forces and stress.
Call on all processors.
Reimplemented from DdMd::Potential.
Definition at line 404 of file ddMd/potentials/bond/BondPotentialImpl.h.
References DdMd::Atom::force(), DdMd::Atom::isGhost(), Util::PArrayIterator< Group< N > >::notEnd(), DdMd::Atom::position(), and Util::Tensor::zero().
The documentation for this class was generated from the following file:
ddMd/potentials/bond/BondPotentialImpl.h