Simpatico: McMd::McNVTChemicalPotential Class Reference
McMd::McNVTChemicalPotential Class Reference
Diagnostics
Detailed Description
McEnergyAverage averages of total potential energy.
Definition at line 33 of file McNVTChemicalPotential.h.
#include <McNVTChemicalPotential.h>
Public Member Functions
McNVTChemicalPotential (McSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters and initialize.
virtual void setup ()
Clear accumulator.
virtual void sample (long iStep)
Calculate, analyze and/or output a physical quantity.
virtual void output ()
Output results at end of simulation.
virtual void save (Serializable::OArchive &ar)
Save state to binary file archive.
virtual void load (Serializable::IArchive &ar)
Load state from a binary file archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
Constructor & Destructor Documentation
McMd::McNVTChemicalPotential::McNVTChemicalPotential (McSystem & system)
Constructor.
Definition at line 39 of file McNVTChemicalPotential.cpp.
Member Function Documentation
void McMd::McNVTChemicalPotential::readParameters (std::istream & in) [virtual]
Read parameters and initialize.
Reimplemented from McMd::Diagnostic.
Definition at line 58 of file McNVTChemicalPotential.cpp.
References Util::Distribution::clear(), McMd::Diagnostic::fileMaster(), Util::Average::nSamplePerBlock(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), McMd::Diagnostic::readInterval(), McMd::Diagnostic::readOutputFileName(), Util::Average::setNSamplePerBlock(), Util::Distribution::setParam(), and UTIL_THROW.
void McMd::McNVTChemicalPotential::setup () [virtual]
Clear accumulator.
Reimplemented from McMd::Diagnostic.
Definition at line 114 of file McNVTChemicalPotential.cpp.
References Util::Average::clear().
void McMd::McNVTChemicalPotential::sample (long iStep) [virtual]
Calculate, analyze and/or output a physical quantity.
Take an action if iStep is a multiple of interval. If iStep is not a multiple of interval, this method should do nothing and return immediately.
Parameters:
iStep current simulation step index.
Implements McMd::Diagnostic.
Definition at line 120 of file McNVTChemicalPotential.cpp.
References Util::Vector::add(), McMd::McPairPotential::addAtom(), McMd::System::addMolecule(), McMd::Molecule::angle(), McMd::McSystem::anglePotential(), McMd::Molecule::atom(), McMd::McPairPotential::atomEnergy(), McMd::ExternalPotential::atomEnergy(), Util::EnergyEnsemble::beta(), McMd::Molecule::bond(), McMd::McSystem::bondPotential(), McMd::McPairPotential::deleteAtom(), Util::Random::drawFrom(), McMd::AnglePotential::energy(), McMd::BondPotential::energy(), McMd::McSystem::externalPotential(), McMd::Diagnostic::isAtInterval(), McMd::Molecule::nAtom(), McMd::McSystem::pairPotential(), Util::ArrayStack< Data >::pop(), McMd::Atom::position(), Util::ArrayStack< Data >::push(), McMd::AnglePotential::randomAngle(), McMd::BondPotential::randomBondLength(), Util::OrthorhombicBoundary::randomPosition(), McMd::System::removeMolecule(), McMd::Species::reservoir(), Util::Average::sample(), Util::OrthorhombicBoundary::shift(), McMd::Simulation::species(), McMd::Group< NAtom >::typeId(), and Util::Random::unitVector().
void McMd::McNVTChemicalPotential::output () [virtual]
Output results at end of simulation.
Reimplemented from McMd::Diagnostic.
Definition at line 330 of file McNVTChemicalPotential.cpp.
References McMd::Diagnostic::fileMaster(), Util::Average::nSamplePerBlock(), Util::FileMaster::openOutputFile(), Util::Distribution::output(), Util::Average::output(), McMd::Diagnostic::outputFileName(), and Util::ParamComposite::writeParam().
void McMd::McNVTChemicalPotential::save (Serializable::OArchive & ar) [virtual]
Save state to binary file archive.
Parameters:
ar binary saving (output) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 365 of file McNVTChemicalPotential.cpp.
void McMd::McNVTChemicalPotential::load (Serializable::IArchive & ar) [virtual]
Load state from a binary file archive.
Parameters:
ar binary loading (input) archive.
Reimplemented from Util::ParamComposite.
Definition at line 371 of file McNVTChemicalPotential.cpp.
template<class Archive > void McMd::McNVTChemicalPotential::serialize (Archive & ar, const unsigned int version) [inline]
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Diagnostic.
Definition at line 88 of file McNVTChemicalPotential.h.
References UTIL_THROW.
The documentation for this class was generated from the following files:
McNVTChemicalPotential.h
McNVTChemicalPotential.cpp