Simpatico: McMd::McPairPerturbation< Interaction > Class Template Reference
McMd::McPairPerturbation< Interaction > Class Template Reference
McMd namespace » Free Energy Perturbation
Detailed Description
template<class Interaction>
class McMd::McPairPerturbation< Interaction >
A Perturbation in the pair interaction epsilon(0,1) for any pair potential supporting setEpsilon().
An McPairPerturbation describes a Hamiltonian with a variable pair interaction between species 0 and 1. The perturbation parameter is is the pair interaction parameter epsilon(0, 1).
Definition at line 40 of file McPairPerturbation.h.
#include <McPairPerturbation.h>
Public Member Functions
McPairPerturbation (McSystem &system, int size, int rank)
Constructor.
virtual ~McPairPerturbation ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameter epsilon(0, 1) from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void setParameter ()
Set pair interaction parameter epsilon(0,1) for this System.
virtual double parameter (int i) const
Return the pair parameter epsilon(0,1) for this System.
virtual double derivative (int i) const
Return (0-1 pair energy) / (kT *epsilon(0,1))
Interaction & interaction () const
Return the pair potential interaction.
Public Member Functions inherited from McMd::LinearPerturbation< McSystem >
LinearPerturbation (McSystem &system, int size, int rank)
Constructor.
virtual ~LinearPerturbation ()
Destructor.
virtual double difference (DArray< double > iPartnerParameter) const
Returns the difference W(partner) - W(current).
McSystem & system () const
Get the associated System by reference.
Public Member Functions inherited from McMd::Perturbation
Perturbation (int size, int rank)
Constructor.
virtual ~Perturbation ()
Destructor.
void readParameters (std::istream &in)
Read perturbation parameter(s) from file.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void setParameter (DArray< double > parameter)
Sets the perturbation parameter value.
double parameter (int i, int id)
Get parameter i of system id.
int getNParameters () const
Gets the number of parameters per system.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes inherited from McMd::Perturbation
int size_
Number of systems (e.g., communicator size)
int rank_
Index for this system (e.g., communicator size)
int nParameters_
Number of perturbation parameters associated with a System.
int mode_
mode 0: parameters of all replica systems are specified.
DArray< double > parameter_
Value of the perturbation parameter for the associated System.
DArray< double > initialParameter_
Value of the perturbation parameter for the first replica System.
DArray< double > finalParameter_
Value of the perturbation parameter for the last replica System.
DMatrix< double > parameters_
Value of the perturbation parameter for all the replica Systems.
Constructor & Destructor Documentation
template<class Interaction > McMd::McPairPerturbation< Interaction >::McPairPerturbation (McSystem & system, int size, int rank)
Constructor.
Implementation.
Parameters
system parent McSystem
size number of systems (communicator size)
rank id of this system (communicator rank)
Definition at line 121 of file McPairPerturbation.h.
References Util::ParamComposite::setClassName().
template<class Interaction > McMd::McPairPerturbation< Interaction >::~McPairPerturbation< Interaction > () virtual
Destructor.
Definition at line 131 of file McPairPerturbation.h.
Member Function Documentation
template<class Interaction > void McMd::McPairPerturbation< Interaction >::readParameters (std::istream & in) virtual
Read parameter epsilon(0, 1) from file.
Parameters
in input stream (file or std in).
Reimplemented from Util::ParamComposite.
Definition at line 138 of file McPairPerturbation.h.
References McMd::Perturbation::getNParameters(), and McMd::Perturbation::readParameters().
template<class Interaction > void McMd::McPairPerturbation< Interaction >::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from McMd::Perturbation.
Definition at line 148 of file McPairPerturbation.h.
References McMd::Perturbation::getNParameters(), and McMd::Perturbation::loadParameters().
template<class Interaction > void McMd::McPairPerturbation< Interaction >::setParameter () virtual
Set pair interaction parameter epsilon(0,1) for this System.
Implements McMd::Perturbation.
Definition at line 176 of file McPairPerturbation.h.
References McMd::McPairPerturbation< Interaction >::interaction(), and McMd::Perturbation::parameter_.
template<class Interaction > double McMd::McPairPerturbation< Interaction >::parameter (int i) const virtual
Return the pair parameter epsilon(0,1) for this System.
Parameters
i index of the perturbation parameter. In this case, i is always 0 since nParameters = 1.
Implements McMd::Perturbation.
Definition at line 183 of file McPairPerturbation.h.
References McMd::McPairPerturbation< Interaction >::interaction(), and UTIL_THROW.
Referenced by McMd::McPairPerturbation< Interaction >::derivative().
template<class Interaction > double McMd::McPairPerturbation< Interaction >::derivative (int i) const virtual
Return (0-1 pair energy) / (kT *epsilon(0,1))
Parameters
i index of the perturbation parameter. In this case, i is always 0 since nParameters = 1.
Implements McMd::Perturbation.
Definition at line 195 of file McPairPerturbation.h.
References Util::EnergyEnsemble::beta(), McMd::System::boundary(), McMd::McPairPotential::cellList(), McMd::System::energyEnsemble(), McMd::CellList::getCellNeighbors(), McMd::Atom::id(), McMd::McPairPerturbation< Interaction >::interaction(), Util::EnergyEnsemble::isIsothermal(), McMd::Mask::isMasked(), McMd::Atom::mask(), McMd::McSystem::pairPotential(), McMd::McPairPerturbation< Interaction >::parameter(), McMd::Perturbation::parameter_, McMd::Atom::position(), Util::FSArray< Data, Capacity >::size(), McMd::LinearPerturbation< McSystem >::system(), McMd::CellList::totCells(), McMd::Atom::typeId(), and UTIL_THROW.
template<class Interaction > Interaction & McMd::McPairPerturbation< Interaction >::interaction () const
Return the pair potential interaction.
Definition at line 158 of file McPairPerturbation.h.
References McMd::McPairPotentialImpl< Interaction >::interaction(), McMd::McSystem::pairPotential(), McMd::LinearPerturbation< McSystem >::system(), and UTIL_THROW.
Referenced by McMd::McPairPerturbation< Interaction >::derivative(), McMd::McPairPerturbation< Interaction >::parameter(), and McMd::McPairPerturbation< Interaction >::setParameter().
The documentation for this class was generated from the following file:
McPairPerturbation.h