Simpatico: McMd::TypeDistribution Class Reference
McMd::TypeDistribution Class Reference
Analyzers
Detailed Description
Calculate distribution of type indices for mutable species.
Definition at line 27 of file TypeDistribution.h.
#include <TypeDistribution.h>
Public Member Functions
TypeDistribution (McSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read output file and nStepPerSample.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
void sample (long iStep)
Calculate, analyze and/or output a physical quantity.
virtual void output ()
Output any results at the end of the simulation.
Constructor & Destructor Documentation
McMd::TypeDistribution::TypeDistribution (McSystem & system)
Constructor.
Definition at line 26 of file TypeDistribution.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::TypeDistribution::readParameters (std::istream & in) [virtual]
Read output file and nStepPerSample.
Parameters:
in input parameters stream
Reimplemented from McMd::Analyzer.
Definition at line 40 of file TypeDistribution.cpp.
References Util::DArray< Data >::allocate(), McMd::SpeciesMutator::nState(), McMd::Analyzer::readInterval(), McMd::Analyzer::readOutputFileName(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemAnalyzer< McSystem >::system(), and UTIL_THROW.
void McMd::TypeDistribution::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive
Reimplemented from McMd::Analyzer.
Definition at line 64 of file TypeDistribution.cpp.
References McMd::Species::isMutable(), McMd::Species::mutator(), McMd::Simulation::nSpecies(), McMd::SpeciesMutator::nState(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemAnalyzer< McSystem >::system(), and UTIL_THROW.
void McMd::TypeDistribution::save (Serializable::OArchive & ar) [virtual]
Save state to an archive.
Parameters:
ar saving (output) archive
Reimplemented from McMd::Analyzer.
Definition at line 88 of file TypeDistribution.cpp.
template<class Archive > void McMd::TypeDistribution::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar archive
version archive version id
Reimplemented from McMd::Analyzer.
Definition at line 106 of file TypeDistribution.h.
References McMd::serialize().
void McMd::TypeDistribution::sample (long iStep) [virtual]
Calculate, analyze and/or output a physical quantity.
Take an action if iStep is a multiple of interval. If iStep is not a multiple of interval, this method should do nothing and return immediately.
Parameters:
iStep current simulation step index.
Implements McMd::Analyzer.
Definition at line 94 of file TypeDistribution.cpp.
References McMd::Analyzer::isAtInterval(), and McMd::SpeciesMutator::stateOccupancy().
void McMd::TypeDistribution::output () [virtual]
Output any results at the end of the simulation.
The default implementation is an empty function.
Reimplemented from McMd::Analyzer.
Definition at line 109 of file TypeDistribution.cpp.
References McMd::Analyzer::fileMaster(), Util::FileMaster::openOutputFile(), and McMd::Analyzer::outputFileName().
The documentation for this class was generated from the following files:
TypeDistribution.h
TypeDistribution.cpp