Simpatico: McMd::AnalyzerManager Class Reference
McMd::AnalyzerManager Class Reference
Managers | Analyzers
Detailed Description
Manager for a list of Analyzer objects.
Definition at line 25 of file mcMd/analyzers/AnalyzerManager.h.
#include <AnalyzerManager.h>
Public Member Functions
AnalyzerManager ()
Constructor.
virtual ~AnalyzerManager ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameter file.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to an archive.
void setup ()
Call initialize method of each Analyzer.
void sample (long iStep)
Call sample method of each Analyzer.
void output ()
Call output method of each analyzer.
Constructor & Destructor Documentation
McMd::AnalyzerManager::AnalyzerManager ()
Constructor.
Definition at line 20 of file mcMd/analyzers/AnalyzerManager.cpp.
References Util::ParamComposite::setClassName().
McMd::AnalyzerManager::~AnalyzerManager () [virtual]
Destructor.
Definition at line 27 of file mcMd/analyzers/AnalyzerManager.cpp.
Member Function Documentation
void McMd::AnalyzerManager::readParameters (std::istream & in) [virtual]
Read parameter file.
Parameters:
in input parameter file stream.
Reimplemented from Util::Manager< Analyzer >.
Definition at line 35 of file mcMd/analyzers/AnalyzerManager.cpp.
References McMd::Analyzer::baseInterval.
void McMd::AnalyzerManager::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from Util::Manager< Analyzer >.
Definition at line 76 of file mcMd/analyzers/AnalyzerManager.cpp.
References McMd::Analyzer::baseInterval.
void McMd::AnalyzerManager::save (Serializable::OArchive & ar) [virtual]
Save state to an archive.
Parameters:
ar saving (output) archive.
Reimplemented from Util::Manager< Analyzer >.
Definition at line 85 of file mcMd/analyzers/AnalyzerManager.cpp.
References McMd::Analyzer::baseInterval.
Referenced by McMd::MdSimulation::save(), and McMd::McSimulation::save().
void McMd::AnalyzerManager::setup ()
Call initialize method of each Analyzer.
This method should be called just before the main simulation loop, after an initial configuration is known.
Definition at line 44 of file mcMd/analyzers/AnalyzerManager.cpp.
References Util::Manager< Analyzer >::size().
Referenced by McMd::McSimulation::analyze(), McMd::MdSimulation::analyzeDumps(), McMd::MdSimulation::analyzeTrajectory(), McMd::McSimulation::simulate(), and McMd::MdSimulation::simulate().
void McMd::AnalyzerManager::sample (long iStep)
Call sample method of each Analyzer.
Definition at line 54 of file mcMd/analyzers/AnalyzerManager.cpp.
References McMd::Analyzer::baseInterval, and Util::Manager< Analyzer >::size().
Referenced by McMd::McSimulation::analyze(), McMd::MdSimulation::analyzeDumps(), McMd::MdSimulation::analyzeTrajectory(), McMd::McSimulation::simulate(), and McMd::MdSimulation::simulate().
void McMd::AnalyzerManager::output ()
Call output method of each analyzer.
Definition at line 66 of file mcMd/analyzers/AnalyzerManager.cpp.
References Util::Manager< Analyzer >::size().
Referenced by McMd::McSimulation::analyze(), McMd::MdSimulation::analyzeDumps(), McMd::MdSimulation::analyzeTrajectory(), McMd::McSimulation::simulate(), and McMd::MdSimulation::simulate().
The documentation for this class was generated from the following files:
mcMd/analyzers/AnalyzerManager.h
mcMd/analyzers/AnalyzerManager.cpp