Simpatico: McMd::NvtDpdVvIntegrator Class Reference
McMd::NvtDpdVvIntegrator Class Reference
Molecular Dynamics Integrators
Detailed Description
A velocity-Verlet DPD integerator.
This class implements a simple velocity-Verlet (VV) algorithm for the dissipitative particle dynamics (DPD) equations of motion.
Definition at line 38 of file NvtDpdVvIntegrator.h.
#include <NvtDpdVvIntegrator.h>
Public Member Functions
NvtDpdVvIntegrator (MdSystem &system)
Constructor.
virtual ~NvtDpdVvIntegrator ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from file and initialize this MdSystem.
virtual void loadParameters (Serializable::IArchive &ar)
Load the internal state to an archive.
virtual void save (Serializable::OArchive &ar)
Save the internal state to an archive.
virtual void setup ()
Setup private variables before main loop.
virtual void step ()
Take a complete integration step.
Constructor & Destructor Documentation
McMd::NvtDpdVvIntegrator::NvtDpdVvIntegrator (MdSystem & system)
Constructor.
Definition at line 34 of file NvtDpdVvIntegrator.cpp.
References McMd::System::energyEnsemble(), Util::EnergyEnsemble::isIsothermal(), Util::ParamComposite::setClassName(), Util::EnergyEnsemble::temperature(), and UTIL_THROW.
McMd::NvtDpdVvIntegrator::~NvtDpdVvIntegrator () [virtual]
Destructor.
Definition at line 66 of file NvtDpdVvIntegrator.cpp.
Member Function Documentation
void McMd::NvtDpdVvIntegrator::readParameters (std::istream & in) [virtual]
Read parameters from file and initialize this MdSystem.
Parameters:
in input file stream.
Reimplemented from Util::ParamComposite.
Definition at line 72 of file NvtDpdVvIntegrator.cpp.
References Util::DArray< Data >::allocate(), McMd::MdIntegrator::dt_, McMd::PairPotential::maxPairCutoff(), McMd::MdSystem::pairPotential(), McMd::MdIntegrator::simulation(), McMd::MdIntegrator::system(), and UTIL_THROW.
void McMd::NvtDpdVvIntegrator::loadParameters (Serializable::IArchive & ar) [virtual]
Load the internal state to an archive.
Parameters:
ar archive object.
Reimplemented from Util::ParamComposite.
Definition at line 93 of file NvtDpdVvIntegrator.cpp.
References McMd::MdIntegrator::dt_, McMd::PairPotential::maxPairCutoff(), McMd::MdSystem::pairPotential(), McMd::MdIntegrator::system(), and UTIL_THROW.
void McMd::NvtDpdVvIntegrator::save (Serializable::OArchive & ar) [virtual]
Save the internal state to an archive.
Parameters:
ar archive object.
Reimplemented from Util::ParamComposite.
Definition at line 115 of file NvtDpdVvIntegrator.cpp.
References McMd::MdIntegrator::dt_.
void McMd::NvtDpdVvIntegrator::setup () [virtual]
Setup private variables before main loop.
Reimplemented from McMd::MdIntegrator.
Definition at line 132 of file NvtDpdVvIntegrator.cpp.
References McMd::Simulation::atomType(), McMd::MdPairPotential::buildPairList(), McMd::MdSystem::calculateForces(), McMd::MdPairPotential::clearPairListStatistics(), McMd::MdIntegrator::dt_, McMd::System::energyEnsemble(), McMd::AtomType::mass(), McMd::Simulation::nAtomType(), McMd::MdSystem::pairPotential(), McMd::MdIntegrator::simulation(), McMd::MdIntegrator::system(), and Util::EnergyEnsemble::temperature().
void McMd::NvtDpdVvIntegrator::step () [virtual]
Take a complete integration step.
Implements McMd::MdIntegrator.
Definition at line 230 of file NvtDpdVvIntegrator.cpp.
References Util::Vector::add(), McMd::System::begin(), McMd::MdPairPotential::buildPairList(), McMd::MdSystem::calculateForces(), McMd::MdIntegrator::dt_, Util::Vector::multiply(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), McMd::MdSystem::pairPotential(), McMd::MdIntegrator::simulation(), and McMd::MdIntegrator::system().
The documentation for this class was generated from the following files:
NvtDpdVvIntegrator.h
NvtDpdVvIntegrator.cpp