Simpatico: SpAn::ConfigIo Class Reference
SpAn::ConfigIo Class Reference
ConfigIos
Detailed Description
Abstract reader/writer for configuration files.
Each concrete subclass of ConfigIo implements a specific file format by implementing the pure virtual readConfig and writeConfig methods.
Definition at line 27 of file spAn/configIos/ConfigIo.h.
#include <ConfigIo.h>
Public Member Functions
ConfigIo ()
Default constructor.
ConfigIo (Configuration &configuration)
Constructor.
virtual ~ConfigIo ()
Destructor.
virtual void readConfig (std::ifstream &file)=0
Read a configuration file.
virtual void writeConfig (std::ofstream &file)=0
Write configuration file.
Constructor & Destructor Documentation
SpAn::ConfigIo::ConfigIo ()
Default constructor.
Definition at line 21 of file spAn/configIos/ConfigIo.cpp.
References Util::ParamComposite::setClassName().
SpAn::ConfigIo::ConfigIo (Configuration & configuration)
Constructor.
Parameters:
configuration parent Configuration object
Definition at line 28 of file spAn/configIos/ConfigIo.cpp.
References Util::ParamComposite::setClassName().
SpAn::ConfigIo::~ConfigIo () [virtual]
Destructor.
Definition at line 37 of file spAn/configIos/ConfigIo.cpp.
Member Function Documentation
virtual void SpAn::ConfigIo::readConfig (std::ifstream & file) [pure virtual]
Read a configuration file.
Parameters:
file input file
Implemented in SpAn::DdMdConfigIo.
Referenced by SpAn::Processor::readConfig().
virtual void SpAn::ConfigIo::writeConfig (std::ofstream & file) [pure virtual]
Write configuration file.
Parameters:
file output file
Implemented in SpAn::DdMdConfigIo.
Referenced by SpAn::Processor::writeConfig().
The documentation for this class was generated from the following files:
spAn/configIos/ConfigIo.h
spAn/configIos/ConfigIo.cpp