Simpatico: McMd::McSystem Class Reference
McMd::McSystem Class Reference
McMd namespace » Systems
Detailed Description
A System for use in a Markov chain Monte Carlo simulation.
McSystem provides methods to evaluate energies of individual atoms, and other functions needed in MC simulations.
Definition at line 48 of file McSystem.h.
#include <McSystem.h>
Public Member Functions
McSystem ()
Constructor.
virtual ~McSystem ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from input file.
virtual void loadParameters (Serializable::IArchive &ar)
Load parameters from an archive, without configuration.
virtual void saveParameters (Serializable::OArchive &ar)
Save parameters to an archive, without configuration.
virtual void readConfig (std::istream &in)
Read system configuration from file.
virtual void loadConfig (Serializable::IArchive &ar)
Load the system configuration from an archive.
virtual bool isValid () const
Return true if McSystem is valid, or throw Exception.
Energy and Stress calculators
double atomPotentialEnergy (const Atom &atom) const
Calculate the total potential energy for one Atom.
double potentialEnergy () const
Return total potential energy of this System.
template<typename T >
void computeVirialStress (T &stress) const
Compute total virial stress (excludes kinetic contribution).
template<typename T >
void computeStress (T &stress) const
Compute total pressure (T=double), xyz pressures (T=Vector) or stress (T=Tensor).
McPairPotential & pairPotential () const
Return the McPairPotential by reference.
bool hasBondPotential () const
Does a bond potential exist?.
BondPotential & bondPotential () const
Return the BondPotential by reference.
bool hasAnglePotential () const
Does angle potential exist?.
AnglePotential & anglePotential () const
Return AnglePotential by reference.
bool hasDihedralPotential () const
Does a dihedral potential exist?.
DihedralPotential & dihedralPotential () const
Return the DihedralPotential by reference.
bool hasLinkPotential () const
Does a link potential exist?.
BondPotential & linkPotential () const
Return the McLinkPotential by reference.
bool hasExternalPotential () const
Does an external potential exist?.
ExternalPotential & externalPotential () const
Return ExternalPotential by reference.
Public Member Functions inherited from McMd::System
System ()
Default constructor.
System (const System &other)
Copy constructor.
virtual ~System ()
Destructor.
void setId (int Id)
Set the integer Id for this System.
void setSimulation (Simulation &simulation)
Set the parent Simulation.
void setFileMaster (FileMaster &filemaster)
Set the FileMaster.
void saveParameters (Serializable::OArchive &ar)
Save internal state from an archive.
Factory< ConfigIo > & configIoFactory ()
Get the configuration file reader/writer factory by reference.
void setConfigIo (std::string &classname)
Create a new configuration file reader/writer.
void writeConfig (std::ostream &out)
Write system configuration to a specified ostream.
void saveConfig (Serializable::OArchive &ar)
Save configuration.
Factory< TrajectoryReader > & trajectoryReaderFactory ()
Get the trajectory reader/writer factory by reference.
void addMolecule (Molecule &molecule)
Add a Molecule to this System.
void removeMolecule (Molecule &molecule)
Remove a specific molecule from this System.
void removeAllMolecules ()
Remove all molecules from this System.
void subscribeMoleculeSetChange (MoleculeSetObserver &observer)
Subscribe to moleculeSet change signal.
void unsubscribeMoleculeSetChange (MoleculeSetObserver &observer)
Unsubscribe from moleculeSet change signal.
int nMolecule (int speciesId) const
Get the number of molecules of one Species in this System.
int nAtom () const
Return the total number of atoms in this System.
bool isEmpty () const
Is this an empty System (i.e., one with no molecules) ?
int moleculeId (const Molecule &molecule) const
Get the index of a Molecule within its Species in this System.
Molecule & molecule (int speciesId, int moleculeId)
Get a specific Molecule in this System, by integer index.
Molecule & randomMolecule (int speciesId)
Get a random Molecule of a specified species in this System.
void begin (int speciesId, MoleculeIterator &iterator)
Initialize an iterator for molecules of one species in this System.
void begin (int speciesId, ConstMoleculeIterator &iterator) const
Initialize a const iterator for molecules of one species in this System.
PairFactory & pairFactory ()
Get the PairFactory by reference.
std::string pairStyle () const
Return nonbonded pair style string.
Factory< BondPotential > & bondFactory ()
Get the associated Factory<BondPotential> by reference.
std::string bondStyle () const
Return covalent bond style string.
Factory< AnglePotential > & angleFactory ()
Get the associated AngleFactory by reference.
std::string angleStyle () const
Return angle potential style string.
Factory< DihedralPotential > & dihedralFactory ()
Get the associated Dihedral Factory by reference.
std::string dihedralStyle () const
Return dihedral potential style string.
Factory< ExternalPotential > & externalFactory ()
Get the associated ExternalPotential factory by reference.
std::string externalStyle () const
Return external potential style string.
Factory< BondPotential > & linkFactory ()
Get the associated Link factory by reference.
std::string linkStyle () const
Return link potential style string.
LinkMaster & linkMaster () const
Get the LinkMaster by reference.
Factory< Perturbation > & perturbationFactory ()
Get the perturbation factory by reference.
void setExpectPerturbation ()
Set to expect a Perturbation in the parameter file.
bool expectPerturbation () const
Return true if we expect a perturbation.
bool hasPerturbation () const
Does this system have an associated Perturbation?
Perturbation & perturbation () const
Get the associated Perturbation by reference.
bool hasReplicaMove () const
Does this system have an associated ReplicaMove?
ReplicaMove & replicaMove () const
Get the associated ReplicaMove by reference.
int id () const
Get integer index for this System.
Simulation & simulation () const
Get the parent Simulation by reference.
Boundary & boundary () const
Get the Boundary by reference.
EnergyEnsemble & energyEnsemble () const
Get the EnergyEnsemble by reference.
BoundaryEnsemble & boundaryEnsemble () const
Get the BoundaryEnsemble by reference.
FileMaster & fileMaster () const
Get the associated FileMaster by reference.
bool isCopy () const
Was this System instantiated with the copy constructor?
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
virtual Factory< Perturbation > * newDefaultPerturbationFactory ()
Return a pointer to a new McPerturbationFactory.
void setPairPotential (McPairPotential *pairPotentialPtr)
Set the PairPotential.
Protected Member Functions inherited from McMd::System
Boundary & maxBoundary () const
Get the maximum Boundary by reference.
virtual ConfigIo * newDefaultConfigIo ()
Return a pointer to a new default ConfigIo.
virtual Factory< ConfigIo > * newDefaultConfigIoFactory ()
Return a pointer to a new default ConfigIoFactory.
virtual Factory< TrajectoryReader > * newDefaultTrajectoryReaderFactory ()
Return a pointer to a new default TrajectoryReaderFactory.
void readPerturbation (std::istream &in)
Read the perturbation parameter block (if any)
void loadPerturbation (Serializable::IArchive &ar)
Load the perturbation parameter block (if any)
void savePerturbation (Serializable::OArchive &ar)
Save the perturbation parameter block (if any)
void readReplicaMove (std::istream &in)
Read the ReplicaMove parameter block (if any)
void loadReplicaMove (Serializable::IArchive &ar)
Read the ReplicaMove parameter block (if any)
void saveReplicaMove (Serializable::OArchive &ar)
Save the ReplicaMove parameter block (if any)
void allocateMoleculeSets ()
Allocate and initialize molecule sets for all species.
void readFileMaster (std::istream &in)
Read FileMaster parameters, if none yet exists.
void loadFileMaster (Serializable::IArchive &ar)
Load FileMaster data from archive, if necessary.
void saveFileMaster (Serializable::OArchive &ar)
If necessary, save FileMaster to archive.
void readPotentialStyles (std::istream &in)
Read potential style parameter strings.
void loadPotentialStyles (Serializable::IArchive &ar)
Load potential style strings from an archive.
void savePotentialStyles (Serializable::OArchive &ar)
Save potential style strings.
void readEnsembles (std::istream &in)
Read energy and boundary ensemble parameters.
void loadEnsembles (Serializable::IArchive &ar)
Load energy and boundary ensembles from archive.
void saveEnsembles (Serializable::OArchive &ar)
Save energy and boundary ensembles.
void readLinkMaster (std::istream &in)
Read the LinkMaster parameters.
void loadLinkMaster (Serializable::IArchive &ar)
Load the LinkMaster.
void saveLinkMaster (Serializable::OArchive &ar)
Save the LinkMaster.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from McMd::System
typedef ArraySet< Molecule > MoleculeSet
A set of molecules of one Species in a System.
typedef PArrayIterator< Molecule > MoleculeIterator
Iterator for a MoleculeSet.
typedef ConstPArrayIterator< Molecule > ConstMoleculeIterator
Const Iterator for a MoleculeSet.
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Constructor & Destructor Documentation
McMd::McSystem::McSystem ()
Constructor.
Definition at line 63 of file McSystem.cpp.
References Util::ParamComposite::setClassName().
McMd::McSystem::~McSystem () virtual
Destructor.
Definition at line 92 of file McSystem.cpp.
Member Function Documentation
void McMd::McSystem::readParameters (std::istream & in) virtual
Read parameters from input file.
This method first calls System::readParameters(in).
Finally, it allocates a CellList, and builds the new CellList if an initial configuration has been read previously by System::readParam. The number of cells allocated for the CellList is determined by the dimensions of maxBoundary and the maximum nonbonded cutoff distance.
Parameters
in file stream.
Reimplemented from McMd::System.
Definition at line 123 of file McSystem.cpp.
References McMd::System::allocateMoleculeSets(), McMd::System::angleFactory(), McMd::System::angleStyle(), McMd::System::bondFactory(), McMd::System::bondStyle(), McMd::System::dihedralFactory(), McMd::System::dihedralStyle(), McMd::System::externalFactory(), McMd::System::externalStyle(), Util::Factory< Data >::factory(), McMd::System::linkFactory(), McMd::System::linkStyle(), McMd::PairFactory::mcFactory(), McMd::System::pairFactory(), McMd::System::pairStyle(), McMd::System::readEnsembles(), McMd::System::readFileMaster(), McMd::System::readLinkMaster(), Util::ParamComposite::readParamComposite(), McMd::System::readPerturbation(), McMd::System::readPotentialStyles(), McMd::System::readReplicaMove(), McMd::System::simulation(), and UTIL_THROW.
void McMd::McSystem::loadParameters (Serializable::IArchive & ar) virtual
Load parameters from an archive, without configuration.
Parameters
ar input/loading archive
Reimplemented from McMd::System.
Definition at line 219 of file McSystem.cpp.
References McMd::System::allocateMoleculeSets(), McMd::System::angleFactory(), McMd::System::angleStyle(), McMd::System::bondFactory(), McMd::System::bondStyle(), McMd::System::dihedralFactory(), McMd::System::dihedralStyle(), McMd::System::externalFactory(), McMd::System::externalStyle(), Util::Factory< Data >::factory(), McMd::System::linkFactory(), McMd::System::linkStyle(), McMd::System::loadEnsembles(), McMd::System::loadFileMaster(), McMd::System::loadLinkMaster(), Util::ParamComposite::loadParamComposite(), McMd::System::loadPerturbation(), McMd::System::loadPotentialStyles(), McMd::System::loadReplicaMove(), McMd::PairFactory::mcFactory(), McMd::System::pairFactory(), McMd::System::pairStyle(), McMd::System::simulation(), and UTIL_THROW.
void McMd::McSystem::saveParameters (Serializable::OArchive & ar) virtual
Save parameters to an archive, without configuration.
Parameters
ar output/saving archive
Definition at line 315 of file McSystem.cpp.
References Util::ParamComposite::save(), McMd::System::saveEnsembles(), McMd::System::saveFileMaster(), McMd::System::saveLinkMaster(), McMd::System::savePerturbation(), McMd::System::savePotentialStyles(), McMd::System::saveReplicaMove(), and McMd::System::simulation().
Referenced by McMd::McSimulation::save().
void McMd::McSystem::readConfig (std::istream & in) virtual
Read system configuration from file.
Calls System::readConfig() and then builds CellList.
Parameters
in configuration file input stream
Reimplemented from McMd::System.
Definition at line 379 of file McSystem.cpp.
References McMd::McPairPotential::buildCellList(), pairPotential(), and McMd::System::readConfig().
Referenced by McMd::McSimulation::analyzeConfigs(), and McMd::McSimulation::readCommands().
void McMd::McSystem::loadConfig (Serializable::IArchive & ar) virtual
Load the system configuration from an archive.
Parameters
ar input (loading) archive object.
Reimplemented from McMd::System.
Definition at line 390 of file McSystem.cpp.
References McMd::McPairPotential::buildCellList(), McMd::System::loadConfig(), and pairPotential().
Referenced by McMd::McSimulation::loadParameters().
double McMd::McSystem::atomPotentialEnergy (const Atom & atom) const
Calculate the total potential energy for one Atom.
Parameters
atom Atom object of interest
Returns
potential energy of atom
Definition at line 404 of file McSystem.cpp.
References anglePotential(), McMd::McPairPotential::atomEnergy(), McMd::ExternalPotential::atomEnergy(), McMd::DihedralPotential::atomEnergy(), McMd::BondPotential::atomEnergy(), McMd::AnglePotential::atomEnergy(), bondPotential(), dihedralPotential(), externalPotential(), hasAnglePotential(), hasBondPotential(), hasDihedralPotential(), hasExternalPotential(), hasLinkPotential(), linkPotential(), and pairPotential().
Referenced by McMd::AtomDisplaceMove::move(), and McMd::RingOctaRebridgeMove::move().
double McMd::McSystem::potentialEnergy () const
Return total potential energy of this System.
Definition at line 448 of file McSystem.cpp.
References anglePotential(), bondPotential(), dihedralPotential(), McMd::PairPotential::energy(), McMd::AnglePotential::energy(), McMd::BondPotential::energy(), McMd::ExternalPotential::energy(), McMd::DihedralPotential::energy(), externalPotential(), hasAnglePotential(), hasBondPotential(), hasDihedralPotential(), hasExternalPotential(), hasLinkPotential(), linkPotential(), and pairPotential().
Referenced by McMd::McEnergyPerturbation::derivative().
template<typename T > void McMd::McSystem::computeVirialStress (T & stress) const
Compute total virial stress (excludes kinetic contribution).
The virial stress is the sum of all pair and bonded stress components. It excludes the kinetic stress.
See also
McSystem::computeStress(T&) regarding allowed types for T.
Parameters
stress (output) pressure, pressures or Tensor.
Referenced by McMd::McVirialStressTensorAverage::sample().
template<typename T > void McMd::McSystem::computeStress (T & stress) const
Compute total pressure (T=double), xyz pressures (T=Vector) or stress (T=Tensor).
In this and all other stress / pressure calculators, typename T must be double to obtain total pressure, Util::Vector to obtain the diagonal pressure components, or Util::Tensor to obtain the full stress tensor. These templates work only for these three types. The parameter stress contains the desired value when the function returns.
The total stress is the sum of the virial stress arising from interatomic forces and an ideal gas kinetic stress.
Parameters
stress (output) pressure, xyz pressures or stress Tensor.
McPairPotential & McMd::McSystem::pairPotential () const inline
Return the McPairPotential by reference.
Definition at line 316 of file McSystem.h.
Referenced by McMd::CfbLinear::addAtom(), McMd::CfbEndBase::addEndAtom(), McMd::CfbRebridgeBase::addMiddleAtom(), McMd::CfbRebridgeBase::addSequence(), McMd::McSimulation::analyzeConfigs(), McMd::McSimulation::analyzeTrajectory(), atomPotentialEnergy(), McMd::CfbLinear::deleteAtom(), McMd::CfbEndBase::deleteEndAtom(), McMd::CfbRebridgeBase::deleteMiddleAtom(), McMd::CfbRebridgeBase::deleteSequence(), McMd::McPerturbationFactory::factory(), loadConfig(), McMd::McSystemAccess::McSystemAccess(), McMd::MdSystem::MdSystem(), McMd::RingTetraRebridgeMove::move(), McMd::AtomDisplaceMove::move(), McMd::CfbDoubleRebridgeMove::move(), McMd::CfbEndMove::move(), McMd::CfbLinearEndMove::move(), McMd::CfbRebridgeMove::move(), McMd::RingOctaRebridgeMove::move(), McMd::HomopolymerSemiGrandMove::move(), McMd::EndSwapMove::move(), McMd::CfbReptationMove::move(), McMd::CfbRingRebridgeMove::move(), McMd::HybridMdMove::move(), McMd::CfbReptateMove::move(), McMd::RigidDisplaceMove::move(), McMd::HybridNphMdMove::move(), McMd::MdMove::move(), McMd::DpdMove::move(), McMd::GroupRebridgeBase::octaEnergy(), potentialEnergy(), McMd::McSimulation::readCommands(), readConfig(), McMd::McNVTChemicalPotential::sample(), McMd::McMuExchange::sample(), McMd::McEnergyOutput::sample(), McMd::McPairEnergyAverage::sample(), McMd::RingOctaRebridgeMove::scanBridge(), McMd::McSimulation::simulate(), and McMd::GroupRebridgeBase::tetraEnergy().
bool McMd::McSystem::hasBondPotential () const inline
Does a bond potential exist?.
Definition at line 324 of file McSystem.h.
Referenced by atomPotentialEnergy(), McMd::MdSystem::MdSystem(), and potentialEnergy().
BondPotential & McMd::McSystem::bondPotential () const inline
Return the BondPotential by reference.
Definition at line 330 of file McSystem.h.
Referenced by McMd::CfbLinear::addAtom(), McMd::CfbEndBase::addEndAtom(), McMd::CfbRebridgeBase::addMiddleAtom(), atomPotentialEnergy(), McMd::CfbLinear::deleteAtom(), McMd::CfbEndBase::deleteEndAtom(), McMd::CfbRebridgeBase::deleteMiddleAtom(), McMd::McSystemAccess::McSystemAccess(), McMd::MdSystem::MdSystem(), McMd::GroupRebridgeBase::octaEnergy(), potentialEnergy(), McMd::McSimulation::readCommands(), McMd::McNVTChemicalPotential::sample(), McMd::McEnergyOutput::sample(), and McMd::GroupRebridgeBase::tetraEnergy().
bool McMd::McSystem::hasAnglePotential () const inline
Does angle potential exist?.
Definition at line 338 of file McSystem.h.
Referenced by atomPotentialEnergy(), McMd::EndSwapMove::EndSwapMove(), McMd::MdSystem::MdSystem(), and potentialEnergy().
AnglePotential & McMd::McSystem::anglePotential () const inline
Return AnglePotential by reference.
Definition at line 344 of file McSystem.h.
Referenced by McMd::CfbLinear::addAtom(), McMd::CfbEndBase::addEndAtom(), McMd::CfbRebridgeBase::addMiddleAtom(), atomPotentialEnergy(), McMd::CfbLinear::deleteAtom(), McMd::CfbEndBase::deleteEndAtom(), McMd::CfbRebridgeBase::deleteMiddleAtom(), McMd::McSystemAccess::McSystemAccess(), McMd::MdSystem::MdSystem(), potentialEnergy(), McMd::McSimulation::readCommands(), McMd::McNVTChemicalPotential::sample(), and McMd::McEnergyOutput::sample().
bool McMd::McSystem::hasDihedralPotential () const inline
Does a dihedral potential exist?.
Definition at line 352 of file McSystem.h.
Referenced by atomPotentialEnergy(), McMd::CfbEndBase::CfbEndBase(), McMd::CfbRebridgeBase::CfbRebridgeBase(), McMd::EndSwapMove::EndSwapMove(), McMd::GroupRebridgeBase::GroupRebridgeBase(), McMd::MdSystem::MdSystem(), and potentialEnergy().
DihedralPotential & McMd::McSystem::dihedralPotential () const inline
Return the DihedralPotential by reference.
Definition at line 358 of file McSystem.h.
Referenced by atomPotentialEnergy(), McMd::McSystemAccess::McSystemAccess(), McMd::MdSystem::MdSystem(), potentialEnergy(), McMd::McSimulation::readCommands(), and McMd::McEnergyOutput::sample().
bool McMd::McSystem::hasLinkPotential () const inline
Does a link potential exist?.
Definition at line 366 of file McSystem.h.
Referenced by atomPotentialEnergy(), McMd::MdSystem::MdSystem(), and potentialEnergy().
BondPotential & McMd::McSystem::linkPotential () const inline
Return the McLinkPotential by reference.
Definition at line 372 of file McSystem.h.
Referenced by atomPotentialEnergy(), McMd::MdSystem::MdSystem(), potentialEnergy(), and McMd::McEnergyOutput::sample().
bool McMd::McSystem::hasExternalPotential () const inline
Does an external potential exist?.
Definition at line 380 of file McSystem.h.
Referenced by atomPotentialEnergy(), McMd::MdSystem::MdSystem(), and potentialEnergy().
ExternalPotential & McMd::McSystem::externalPotential () const inline
Return ExternalPotential by reference.
Definition at line 386 of file McSystem.h.
Referenced by McMd::CfbLinear::addAtom(), McMd::CfbEndBase::addEndAtom(), McMd::CfbRebridgeBase::addMiddleAtom(), atomPotentialEnergy(), McMd::CfbLinear::deleteAtom(), McMd::CfbEndBase::deleteEndAtom(), McMd::CfbRebridgeBase::deleteMiddleAtom(), McMd::McPerturbationFactory::factory(), McMd::McSystemAccess::McSystemAccess(), McMd::MdSystem::MdSystem(), McMd::EndSwapMove::move(), McMd::RigidDisplaceMove::move(), potentialEnergy(), McMd::McExternalEnergyAverage::sample(), McMd::McNVTChemicalPotential::sample(), and McMd::McEnergyOutput::sample().
bool McMd::McSystem::isValid () const virtual
Return true if McSystem is valid, or throw Exception.
Reimplemented from McMd::System.
Definition at line 611 of file McSystem.cpp.
References McMd::McPairPotential::cellList(), McMd::CellList::isValid(), and McMd::System::isValid().
Referenced by McMd::McSimulation::isValid().
Factory< Perturbation > * McMd::McSystem::newDefaultPerturbationFactory () protected virtual
Return a pointer to a new McPerturbationFactory.
Reimplemented from McMd::System.
Definition at line 604 of file McSystem.cpp.
void McMd::McSystem::setPairPotential (McPairPotential * pairPotentialPtr) inline protected
Set the PairPotential.
Parameters
pairPotentialPtr pointer to pair potential
Definition at line 402 of file McSystem.h.
The documentation for this class was generated from the following files:
McSystem.h
McSystem.cpp