Simpatico: DdMd::TwoStepIntegrator Class Reference
DdMd::TwoStepIntegrator Class Reference
MD Integrators
Detailed Description
A two-step velocity-Verlet style integrator.
Definition at line 24 of file TwoStepIntegrator.h.
#include <TwoStepIntegrator.h>
Public Member Functions
TwoStepIntegrator (Simulation &simulation)
Constructor.
~TwoStepIntegrator ()
Destructor.
void run (int nStep)
Run a simulation.
Protected Member Functions
virtual void integrateStep1 ()=0
Execute first step of two-step integrator.
virtual void integrateStep2 ()=0
Execute secodn step of two-step integrator.
Constructor & Destructor Documentation
DdMd::TwoStepIntegrator::TwoStepIntegrator (Simulation & simulation)
Constructor.
Definition at line 31 of file TwoStepIntegrator.cpp.
DdMd::TwoStepIntegrator::~TwoStepIntegrator ()
Destructor.
Definition at line 38 of file TwoStepIntegrator.cpp.
Member Function Documentation
void DdMd::TwoStepIntegrator::run (int nStep) [virtual]
Run a simulation.
Parameters:
nStep number of steps
Implements DdMd::Integrator.
Definition at line 44 of file TwoStepIntegrator.cpp.
References DdMd::Simulation::analyzerManager(), DdMd::SimulationAccess::atomStorage(), DdMd::SimulationAccess::boundary(), DdMd::SimulationAccess::boundaryEnsemble(), DdMd::PairPotential::buildCellList(), DdMd::PairPotential::buildPairList(), DdMd::AtomStorage::clearSnapshot(), DdMd::Integrator::computeForces(), DdMd::Integrator::computeForcesAndVirial(), DdMd::AtomStorage::computeNAtomTotal(), DdMd::SimulationAccess::domain(), DdMd::ModifierManager::endOfStep(), DdMd::Exchanger::exchange(), DdMd::SimulationAccess::exchanger(), DdMd::Simulation::exchangeSignal(), Util::Log::file(), integrateStep1(), integrateStep2(), DdMd::Integrator::isExchangeNeeded(), DdMd::Integrator::iStep_, DdMd::Simulation::isValid(), DdMd::AtomStorage::makeSnapshot(), DdMd::Simulation::modifierManager(), DdMd::Simulation::modifySignal(), Util::Signal< T >::notify(), DdMd::SimulationAccess::pairPotential(), DdMd::ModifierManager::postExchange(), DdMd::ModifierManager::postForce(), DdMd::ModifierManager::postIntegrate1(), DdMd::ModifierManager::postNeighbor(), DdMd::ModifierManager::postUpdate(), DdMd::ModifierManager::preExchange(), DdMd::ModifierManager::preForce(), DdMd::ModifierManager::preIntegrate1(), DdMd::ModifierManager::preTransform(), DdMd::ModifierManager::preUpdate(), DdMd::AnalyzerManager::sample(), DdMd::Simulation::save(), DdMd::Integrator::saveFileName(), DdMd::Integrator::saveInterval(), DdMd::AnalyzerManager::setup(), DdMd::ModifierManager::setup(), DdMd::Integrator::setup(), DdMd::SimulationAccess::simulation(), DdMd::DdTimer::stamp(), DdMd::DdTimer::start(), DdMd::DdTimer::stop(), DdMd::Exchanger::timer(), DdMd::AtomStorage::transformCartToGen(), DdMd::AtomStorage::transformGenToCart(), DdMd::AtomStorage::unsetNAtomTotal(), DdMd::Exchanger::update(), and UTIL_THROW.
virtual void DdMd::TwoStepIntegrator::integrateStep1 () [protected, pure virtual]
Execute first step of two-step integrator.
The function simulation().modifySignal().notify() is called immediately after this function in the run method, so this function need not send this signal.
Implemented in DdMd::NptIntegrator, DdMd::NveIntegrator, DdMd::NphIntegrator, and DdMd::NvtIntegrator.
Referenced by run().
virtual void DdMd::TwoStepIntegrator::integrateStep2 () [protected, pure virtual]
Execute secodn step of two-step integrator.
This method must call simulation().velocitySignal().notify() if it modifies the velocities.
Implemented in DdMd::NptIntegrator, DdMd::NveIntegrator, DdMd::NphIntegrator, and DdMd::NvtIntegrator.
Referenced by run().
The documentation for this class was generated from the following files:
TwoStepIntegrator.h
TwoStepIntegrator.cpp