Simpatico: Inter::LocalLamellarOrderingExternal Class Reference
Inter::LocalLamellarOrderingExternal Class Reference
External Interactions
Detailed Description
A clipped cosine potential that induces lamellar ordering along the direction specified by perpDirection_ in only a fraction of box specified by the parameter fraction along box length in parallelDirection_.
perpDirection_ = 0: x direction = 1: y direction = 2: z direction parallelDirection_ = 0: x direction = 1: y direction = 2: z direction
/ / z \ \ u = prefactor[atomType] externalParameter tanh | clipParameter cos | 2 pi periodicity --- | | \ \ Lz / /
/ / x - 0.5*(1-f)*Lx \ / 0.5*(1+f)*Lx - x \ \ * 0.5* | 1 + tanh | 2 pi ------------------ | * tanh | 2 pi ------------------ | | \ \ f*Lx / \ f*Lx / /
Prefactor (which depends on the atomType), externalParameter, interfaceWidth (relative to the box length along the direction perpendicular to lamellae) and periodicity are given as inputs in the parameter file. ClipParameter is the inverse of 2*pi*periodicity*interfaceWidth.
Definition at line 48 of file LocalLamellarOrderingExternal.h.
#include <LocalLamellarOrderingExternal.h>
Public Member Functions
LocalLamellarOrderingExternal ()
Default constructor.
LocalLamellarOrderingExternal (const LocalLamellarOrderingExternal &other)
Copy constructor.
LocalLamellarOrderingExternal & operator= (const LocalLamellarOrderingExternal &other)
Assignment.
void setNAtomType (int nAtomType)
Set nAtomType value.
void setExternalParameter (double externalParameter)
Sets external parameter.
void setBoundary (Boundary &boundary)
Set pointer to Boundary.
void readParameters (std::istream &in)
Read potential parameters, and initialize other variables.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
double externalParameter () const
Returns external parameter.
double energy (const Vector &position, int i) const
Returns external potential energy of a single particle.
void getForce (const Vector &position, int type, Vector &force) const
Returns force caused by the external potential.
std::string className () const
Return name string "LocalLamellarOrderingExternal".
Constructor & Destructor Documentation
Inter::LocalLamellarOrderingExternal::LocalLamellarOrderingExternal ()
Default constructor.
Definition at line 23 of file LocalLamellarOrderingExternal.cpp.
References Util::ParamComposite::setClassName().
Inter::LocalLamellarOrderingExternal::LocalLamellarOrderingExternal (const LocalLamellarOrderingExternal & other)
Copy constructor.
Definition at line 38 of file LocalLamellarOrderingExternal.cpp.
References Util::DArray< Data >::allocate().
Member Function Documentation
LocalLamellarOrderingExternal & Inter::LocalLamellarOrderingExternal::operator= (const LocalLamellarOrderingExternal & other)
Assignment.
Definition at line 58 of file LocalLamellarOrderingExternal.cpp.
void Inter::LocalLamellarOrderingExternal::setNAtomType (int nAtomType)
Set nAtomType value.
Parameters:
nAtomType number of atom types.
Definition at line 79 of file LocalLamellarOrderingExternal.cpp.
References UTIL_THROW.
void Inter::LocalLamellarOrderingExternal::setExternalParameter (double externalParameter)
Sets external parameter.
Parameters:
externalParameter external parameter of system
Definition at line 90 of file LocalLamellarOrderingExternal.cpp.
References externalParameter(), and UTIL_THROW.
void Inter::LocalLamellarOrderingExternal::setBoundary (Boundary & boundary)
Set pointer to Boundary.
Parameters:
boundary Boundary object (used to calculate length along perpendicular direction).
Definition at line 104 of file LocalLamellarOrderingExternal.cpp.
void Inter::LocalLamellarOrderingExternal::readParameters (std::istream & in) [virtual]
Read potential parameters, and initialize other variables.
Precondition:
nAtomType must have been set, by calling setNAtomType().
Boundary must have been set, by calling setBoundary().
Parameters:
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 110 of file LocalLamellarOrderingExternal.cpp.
References Util::DArray< Data >::allocate(), Util::Dimension, and UTIL_THROW.
void Inter::LocalLamellarOrderingExternal::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 141 of file LocalLamellarOrderingExternal.cpp.
References Util::DArray< Data >::allocate(), Util::Dimension, and UTIL_THROW.
void Inter::LocalLamellarOrderingExternal::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 167 of file LocalLamellarOrderingExternal.cpp.
double Inter::LocalLamellarOrderingExternal::externalParameter () const
Returns external parameter.
Returns:
external parameter
Definition at line 179 of file LocalLamellarOrderingExternal.cpp.
Referenced by setExternalParameter().
double Inter::LocalLamellarOrderingExternal::energy (const Vector & position, int i) const [inline]
Returns external potential energy of a single particle.
Parameters:
position atomic position Vector
i atom type.
Returns:
external potential energy
Definition at line 208 of file LocalLamellarOrderingExternal.h.
References UTIL_THROW.
void Inter::LocalLamellarOrderingExternal::getForce (const Vector & position, int type, Vector & force) const [inline]
Returns force caused by the external potential.
Parameters:
position atom position
type atom type id
force force on the atom (on output)
Definition at line 239 of file LocalLamellarOrderingExternal.h.
References UTIL_THROW, and Util::Vector::zero().
std::string Inter::LocalLamellarOrderingExternal::className () const
Return name string "LocalLamellarOrderingExternal".
Reimplemented from Util::ParamComposite.
Definition at line 185 of file LocalLamellarOrderingExternal.cpp.
The documentation for this class was generated from the following files:
LocalLamellarOrderingExternal.h
LocalLamellarOrderingExternal.cpp