Simpatico: McMd::LinkMaster Class Reference
McMd::LinkMaster Class Reference
Detailed Description
Manages all Link objects in a System.
A LinkMaster allows links between Atoms, or Link objects, to be added to or removed from a system, and provides access to existing links.
Definition at line 39 of file LinkMaster.h.
#include <LinkMaster.h>
Public Types
typedef PArrayIterator< Link > LinkIterator
Iterator for set of active links.
typedef ConstPArrayIterator< Link > ConstLinkIterator
Const iterator for set of active links.
typedef SSet< Link, 400 > AtomLinkSet
A set of links involving a particular atom.
Public Member Functions
LinkMaster ()
Constructor.
void readParameters (std::istream &in)
Read linkCapacity and allocate.
void addLink (Atom &atom0, Atom &atom1, int typeId)
Add a link betwen two specific Atoms.
void removeLink (int id)
Remove a Link.
const AtomLinkSet & atomLinkSet (const Atom &atom) const
Return a set of links associated with an Atom by const reference.
AtomLinkSet & atomLinkSet (const Atom &atom)
Return a set of links associated with an Atom.
Link & link (int id) const
Return an active link by an internal set index.
void reSetAtoms (Link &link, Atom &atom0, Atom &atom1)
Modify the atoms attached to a link.
void reSetAtom (Link &link, Atom &atom, int endId)
Modify one atom attached to a link.
int nLink () const
Get the total number of active Links.
void begin (LinkIterator &iterator)
Initialize iterator to beginning of list of active links.
void begin (ConstLinkIterator &iterator) const
Initialize iterator to beginning of list of active links.
Link & randomLink (Random &random)
Get a randomly chosen link by reference.
bool isValid () const
Return true if this LinkMaster is valid, or throw an Exception.
void clear ()
Clear LinkMaster.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Public Member Functions inherited from Util::Notifier< LinkAddEvent >
void registerObserver (Observer< LinkAddEvent > &observer)
Register an observer.
void removeObserver (Observer< LinkAddEvent > &observer)
Remove an analyzer observer from the container list.
void notifyObservers (const LinkAddEvent &event)
Notify the list of observers about an Event.
Public Member Functions inherited from Util::Notifier< LinkResetEvent >
void registerObserver (Observer< LinkResetEvent > &observer)
Register an observer.
void removeObserver (Observer< LinkResetEvent > &observer)
Remove an analyzer observer from the container list.
void notifyObservers (const LinkResetEvent &event)
Notify the list of observers about an Event.
Public Member Functions inherited from Util::Notifier< LinkRemoveEvent >
void registerObserver (Observer< LinkRemoveEvent > &observer)
Register an observer.
void removeObserver (Observer< LinkRemoveEvent > &observer)
Remove an analyzer observer from the container list.
void notifyObservers (const LinkRemoveEvent &event)
Notify the list of observers about an Event.
Public Member Functions inherited from Util::Notifier< ReSetAtomEvent >
void registerObserver (Observer< ReSetAtomEvent > &observer)
Register an observer.
void removeObserver (Observer< ReSetAtomEvent > &observer)
Remove an analyzer observer from the container list.
void notifyObservers (const ReSetAtomEvent &event)
Notify the list of observers about an Event.
Additional Inherited Members
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Member Typedef Documentation
typedef PArrayIterator<Link> McMd::LinkMaster::LinkIterator
Iterator for set of active links.
Definition at line 49 of file LinkMaster.h.
typedef ConstPArrayIterator<Link> McMd::LinkMaster::ConstLinkIterator
Const iterator for set of active links.
Definition at line 52 of file LinkMaster.h.
typedef SSet<Link,400> McMd::LinkMaster::AtomLinkSet
A set of links involving a particular atom.
Definition at line 57 of file LinkMaster.h.
Constructor & Destructor Documentation
McMd::LinkMaster::LinkMaster ()
Constructor.
Definition at line 21 of file LinkMaster.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::LinkMaster::readParameters (std::istream & in) virtual
Read linkCapacity and allocate.
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 29 of file LinkMaster.cpp.
void McMd::LinkMaster::addLink (Atom & atom0, Atom & atom1, int typeId)
Add a link betwen two specific Atoms.
Add a new link.
The associated Link object is taken from a reservoir of unused links.
Parameters
atom0 first Atom object to which a Link should be attached
atom1 second Atom object to which a Link should be attached
typeId id for the type of Link
Definition at line 39 of file LinkMaster.cpp.
References Util::Log::file(), McMd::Atom::id(), Util::Notifier< Event >::notifyObservers(), McMd::Link::setIsActive(), and UTIL_THROW.
Referenced by McMd::McMdConfigIo::read().
void McMd::LinkMaster::removeLink (int id)
Remove a Link.
Precondition: The Link must be active.
Parameters
id Link index in linkSet_, the ArraySet < Link > container.
Definition at line 77 of file LinkMaster.cpp.
References McMd::Link::atom0(), McMd::Link::atom1(), McMd::Atom::id(), Util::ParamComposite::isActive(), link(), Util::Notifier< Event >::notifyObservers(), and UTIL_THROW.
Referenced by clear().
const LinkMaster::AtomLinkSet & McMd::LinkMaster::atomLinkSet (const Atom & atom) const inline
Return a set of links associated with an Atom by const reference.
Parameters
atom Atom object of interest.
Definition at line 226 of file LinkMaster.h.
References McMd::Atom::id().
LinkMaster::AtomLinkSet & McMd::LinkMaster::atomLinkSet (const Atom & atom) inline
Return a set of links associated with an Atom.
Parameters
atom Atom object of interest.
Definition at line 235 of file LinkMaster.h.
References McMd::Atom::id().
Link & McMd::LinkMaster::link (int id) const inline
Return an active link by an internal set index.
An "active" Link object is one that is attached to two atoms. Pointers to all of the active Link objects are maintained by an ArraySet < Link > container. At any instant, this container assigns every active link an index in the range 0 <= id < nLink, where nLink is the total number of active links. The index associated with any Link in the set can change, however, whenever another Link is removed from the set by calling removeLink() (not yet implemented).
Parameters
id index in the range 0 <= id < nLink.
Definition at line 255 of file LinkMaster.h.
Referenced by removeLink(), and McMd::McMdConfigIo::write().
void McMd::LinkMaster::reSetAtoms (Link & link, Atom & atom0, Atom & atom1)
Modify the atoms attached to a link.
Definition at line 115 of file LinkMaster.cpp.
References McMd::Link::atom0(), McMd::Link::atom1(), Util::Log::file(), McMd::Atom::id(), McMd::Link::isActive(), Util::Notifier< Event >::notifyObservers(), and UTIL_THROW.
void McMd::LinkMaster::reSetAtom (Link & link, Atom & atom, int endId)
Modify one atom attached to a link.
Definition at line 160 of file LinkMaster.cpp.
References McMd::Link::atom0(), McMd::Link::atom1(), Util::Log::file(), McMd::Atom::id(), McMd::Link::isActive(), Util::Notifier< Event >::notifyObservers(), and UTIL_THROW.
int McMd::LinkMaster::nLink () const inline
Get the total number of active Links.
Definition at line 261 of file LinkMaster.h.
Referenced by clear(), randomLink(), and McMd::McMdConfigIo::write().
void McMd::LinkMaster::begin (LinkMaster::LinkIterator & iterator) inline
Initialize iterator to beginning of list of active links.
Parameters
iterator Iterator for active links.
Definition at line 243 of file LinkMaster.h.
void McMd::LinkMaster::begin (LinkMaster::ConstLinkIterator & iterator) const inline
Initialize iterator to beginning of list of active links.
Parameters
iterator const Iterator for active links.
Definition at line 249 of file LinkMaster.h.
Link & McMd::LinkMaster::randomLink (Random & random)
Get a randomly chosen link by reference.
Parameters
random Random number generator.
Definition at line 205 of file LinkMaster.cpp.
References nLink(), Util::Random::uniformInt(), and UTIL_THROW.
bool McMd::LinkMaster::isValid () const
Return true if this LinkMaster is valid, or throw an Exception.
Definition at line 245 of file LinkMaster.cpp.
References McMd::Link::atom0(), McMd::Link::atom1(), McMd::Atom::id(), McMd::Link::isActive(), and UTIL_THROW.
Referenced by McMd::System::isValid().
void McMd::LinkMaster::clear ()
Clear LinkMaster.
Remove all links: clear and return them to the reservoir, empty linkSet and atomLinkSets arrays.
Definition at line 324 of file LinkMaster.cpp.
References nLink(), and removeLink().
Referenced by McMd::System::removeAllMolecules().
The documentation for this class was generated from the following files:
LinkMaster.h
LinkMaster.cpp