Simpatico: Util::FileMaster Class Reference
Util::FileMaster Class Reference
Util namespace » Miscellaneous Utilities
Detailed Description
A FileMaster manages input and output files for a simulation.
File types
A FileMaster manages a set of input and output files for a molecular simulation. It provides methods to open four different types of file, which are located in different places within a standard directory structure. These file types are:
Control input files, i.e., parameter and command files
Restart files, which can be opened for input or output
Input data files (e.g., input configuration files)
Output data files (e.g., trajectories and analysis output files)
Several member functions are provided to open different types of file:
openControlFile opens a control file for reading
openRestartIFile opens a restart file for reading
openRestartOFile opens a restart file for writing
openInputFile opens an input data file
openOutputFile opens an output data file
Each of these functions takes a base file name and a file stream as an argument, constructs a complete path by prepending an appropriate prefix to the base name, and opens the file.
Slightly different directory structures are used for file paths in simulations of a single system and for parallel simulations of multiple systems, as discussed below.
Single-system simulations
In simulations of a single system, paths to the different types of file are constructed by prepending some combination of the following elements before a base file name:
Root directory prefix: This is the path from the current working directory to the root level directory for all files associated with a simulation run. It defaults to an empty string and may be reset by calling the setRootPrefix() function.
Input prefix: This string is prepended to the base name of all input data files.
Output prefix: This string is prepended to the base name of all output data files.
Prefix strings that represent directories must end with the directory separator character "/" in order to give a valid path when prepended to a file name. The root directory prefix must be either the empty string or such a directory path. The input and output prefix strings are often also chosen to be directory paths, in order to place input and output files in different subdirectories (e.g., "in/" and "out/").
In simulations of a single systems, paths to control and restart files are constructed by concatenating the root prefix (if any) to the base file name.
Paths to input and output files are constructed are constructed by concatenating the root prefix (if any), the input or output prefix, and the base file.
Multi-system simulations
A parallel simulation of multiple systems use a directory structure in which the root directory (specified by the root directory prefix) contains a set of numbered subdirectories named "0/", "1/", "2/", etc. Each such numbered directory contains input, output and restart files that are specific to a particular system. Each such numbered directory will be referred to in what follows as the system directory for the associated system. The integer index for the system, which is also the directory name, must be set by the setDirectoryId() method before any files are opened.
In such simulations, a path to a restart files for a system is constructed by concatentaing the system directory path and the restart file base name, thus placing these files in the system directory. Paths to input and output data files are constructed by concatenating the system directory path, an input or output prefix string, and the file base name.
Two different modes of operation are possible for simulations of multiple systems, which differ in the treatment of control files. In "independent" mode, simulations of multiple systems are assumed to be completely independent and to require separate parameter and command control files for each system. In this case, the openControlFile() function for each system opens a file in the system directory for that system. In "replicated" mode, all simulations are controlled by a single parameter file and a single command file, both of which are assumed to be in the shared root directory. "Independent" mode is enabled by default. "Replicated" mode may be chosen by calling the function "setCommonControl()" before opening any any control files.
Control Files
The functions setParameterFileName() and setCommandFileName() can be used to programmatically set the parameter and command file base names before reading a parameter file. If setCommandFileName() is not called before readParameters(), the readParameters() function expects to find a "commandFileName" as the first parameter in the FileMaster parameter file block.
After parameter and command file names have been set, the paramFile() and commandFile() functions return references to the files. The first time each of these functions is called, it calls openControlFile() internally to open the appropriate file.
Definition at line 142 of file FileMaster.h.
#include <FileMaster.h>
Public Member Functions
FileMaster ()
Constructor.
FileMaster (const FileMaster &copy)
Copy constructor.
virtual ~FileMaster ()
Destructor.
Initialization
void setRootPrefix (const std::string &rootPrefix)
Set the path from current directory to root directory.
void setDirectoryId (int directoryId)
Set an integer directory identifier for this processor.
void setCommonControl ()
Enable "replicated" mode in multi-system simulations.
void setParamFileName (const std::string &paramFileName)
Set the parameter file name.
void setCommandFileName (const std::string &commandFileName)
Set the command file name.
void setInputPrefix (const std::string &inputPrefix)
Set the input file prefix string.
void setOutputPrefix (const std::string &outputPrefix)
Set the output file prefix string.
virtual void readParameters (std::istream &in)
Read parameter file.
Serialization
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from file.
virtual void save (Serializable::OArchive &ar)
Save internal state to file.
File Opening
void open (const std::string &name, std::ifstream &in, std::ios_base::openmode mode=std::ios_base::in) const
Open an input file with a known path and open mode.
void open (const std::string &name, std::ofstream &out, std::ios_base::openmode mode=std::ios_base::out) const
Open an output file with a known path and open mode.
void openControlFile (const std::string &name, std::ifstream &in) const
Open an input parameter or command file.
void openRestartIFile (const std::string &name, std::ifstream &in, std::ios_base::openmode mode=std::ios_base::in) const
Open an input restart dump file for reading.
void openRestartOFile (const std::string &name, std::ofstream &out, std::ios_base::openmode mode=std::ios_base::out) const
Open an output restart file for writing.
void openInputFile (const std::string &filename, std::ifstream &in, std::ios_base::openmode mode=std::ios_base::in) const
Open an input file.
void openOutputFile (const std::string &filename, std::ofstream &out, std::ios_base::openmode mode=std::ios_base::out) const
Open an output file.
Control Files
bool isCommonControl () const
Is set for common param and command files?
std::string paramFileName () const
Return the param file name, if any.
std::string commandFileName () const
Return the command file name.
std::istream & paramFile ()
Get a default parameter stream by reference.
std::istream & commandFile ()
Get the command input stream by reference.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Constructor & Destructor Documentation
Util::FileMaster::FileMaster ()
Constructor.
Definition at line 23 of file FileMaster.cpp.
References Util::ParamComposite::setClassName().
Util::FileMaster::FileMaster (const FileMaster & copy)
Copy constructor.
Parameters
copy FileMaster object to be copied
Definition at line 39 of file FileMaster.cpp.
Util::FileMaster::~FileMaster () virtual
Destructor.
Definition at line 55 of file FileMaster.cpp.
Member Function Documentation
void Util::FileMaster::setRootPrefix (const std::string & rootPrefix)
Set the path from current directory to root directory.
Parameters
rootPrefix root directory prefix string for all paths
Definition at line 70 of file FileMaster.cpp.
void Util::FileMaster::setDirectoryId (int directoryId)
Set an integer directory identifier for this processor.
This method should be called only for simulations of multiple systems, to set an integer identifier for the physical system associated with this processor. After calling this function with an integer n, a directory id prefix "n/" will be prepended to the paths of input, output and restart files associated with that system.
Parameters
directoryId integer subdirectory name
Definition at line 76 of file FileMaster.cpp.
Referenced by McMd::Simulation::Simulation().
void Util::FileMaster::setCommonControl ()
Enable "replicated" mode in multi-system simulations.
Call this function to enable the use of single parameter and command files to control simulations of multiple systems.
Definition at line 88 of file FileMaster.cpp.
Referenced by McMd::Simulation::setIoCommunicator().
void Util::FileMaster::setParamFileName (const std::string & paramFileName)
Set the parameter file name.
Parameters
paramFileName name of parameter file
Definition at line 106 of file FileMaster.cpp.
References paramFileName().
Referenced by Tools::Processor::setOptions(), McMd::MdSimulation::setOptions(), and McMd::McSimulation::setOptions().
void Util::FileMaster::setCommandFileName (const std::string & commandFileName)
Set the command file name.
Parameters
commandFileName name of command file
Definition at line 112 of file FileMaster.cpp.
References commandFileName().
Referenced by Tools::Processor::setOptions(), McMd::MdSimulation::setOptions(), and McMd::McSimulation::setOptions().
void Util::FileMaster::setInputPrefix (const std::string & inputPrefix)
Set the input file prefix string.
Parameters
inputPrefix input file prefix string
Definition at line 94 of file FileMaster.cpp.
Referenced by McMd::MdSimulation::setOptions(), and McMd::McSimulation::setOptions().
void Util::FileMaster::setOutputPrefix (const std::string & outputPrefix)
Set the output file prefix string.
Parameters
outputPrefix output file prefix string
Definition at line 100 of file FileMaster.cpp.
Referenced by McMd::MdSimulation::setOptions(), and McMd::McSimulation::setOptions().
void Util::FileMaster::readParameters (std::istream & in) virtual
Read parameter file.
Reads the inputPrefix and outputPrefix string variables.
Parameters
in pararameter file input stream
Reimplemented from Util::ParamComposite.
Definition at line 118 of file FileMaster.cpp.
void Util::FileMaster::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from file.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 130 of file FileMaster.cpp.
void Util::FileMaster::save (Serializable::OArchive & ar) virtual
Save internal state to file.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 145 of file FileMaster.cpp.
Referenced by McMd::Simulation::save(), and McMd::System::saveFileMaster().
void Util::FileMaster::open (const std::string & name, std::ifstream & in, std::ios_base::openmode mode = std::ios_base::in) const
Open an input file with a known path and open mode.
Adds error checking to C++ ifstream::open function.
Parameters
name complete file path
in ifstream object to associated with a file
mode read mode
Definition at line 198 of file FileMaster.cpp.
References UTIL_THROW.
Referenced by openControlFile(), openInputFile(), openOutputFile(), openRestartIFile(), and openRestartOFile().
void Util::FileMaster::open (const std::string & name, std::ofstream & out, std::ios_base::openmode mode = std::ios_base::out) const
Open an output file with a known path and open mode.
Add error checking to C++ ofstream::open function.
Parameters
name complete file path
out ofstream object to associated with a file
mode write mode
Definition at line 213 of file FileMaster.cpp.
References UTIL_THROW.
void Util::FileMaster::openControlFile (const std::string & name, std::ifstream & in) const
Open an input parameter or command file.
The path to this file constructed by concatenating: [rootPrefix] + [directoryIdPrefix] + name + "." + ext
The directoryIdPrefix is included only if a directory id has not been set and the setCommonControl() function has not been called.
Parameters
name base file name, without any prefix
in ifstream object to open
Definition at line 227 of file FileMaster.cpp.
References open().
Referenced by commandFile(), and paramFile().
void Util::FileMaster::openRestartIFile (const std::string & name, std::ifstream & in, std::ios_base::openmode mode = std::ios_base::in) const
Open an input restart dump file for reading.
The path to this file constructed by concatenating: [rootPrefix] + [directoryIdPrefix] + name + "." + ext
Parameters
name base file name, without any prefix or extension
in ifstream object to open
mode open mode
Definition at line 242 of file FileMaster.cpp.
References open().
Referenced by McMd::MdSimulation::load(), and McMd::McSimulation::load().
void Util::FileMaster::openRestartOFile (const std::string & name, std::ofstream & out, std::ios_base::openmode mode = std::ios_base::out) const
Open an output restart file for writing.
The path to this file constructed by concatenating: [rootPrefix] + [directoryIdPrefix] + name
Parameters
name base file name
out ofstream object to open
mode open mode
Definition at line 257 of file FileMaster.cpp.
References open().
Referenced by McMd::MdSimulation::save(), and McMd::McSimulation::save().
void Util::FileMaster::openInputFile (const std::string & filename, std::ifstream & in, std::ios_base::openmode mode = std::ios_base::in) const
Open an input file.
The path to this file constructed by concatenating: [rootPrefix] + [directoryIdPrefix] + inputPrefix + filename.
Parameters
filename file name, without any prefix
in ifstream object to associated with a file
mode bit mask that specifies opening mode
Definition at line 273 of file FileMaster.cpp.
References open().
Referenced by McMd::MdSimulation::analyzeConfigs(), McMd::McSimulation::analyzeConfigs(), Tools::Processor::analyzeTrajectory(), McMd::LammpsDumpReader::open(), McMd::DdMdTrajectoryReader::open(), McMd::MdSimulation::readCommand(), McMd::McSimulation::readCommand(), and Tools::Processor::readCommands().
void Util::FileMaster::openOutputFile (const std::string & filename, std::ofstream & out, std::ios_base::openmode mode = std::ios_base::out) const
Open an output file.
The path to this file constructed by concatenating: [rootPrefix] + [directoryIdPrefix] + outputPrefix + filename.
Parameters
filename file name, without any prefix
out ofstream object to associated with a file
mode bit mask that specifies opening mode
Definition at line 290 of file FileMaster.cpp.
References open().
Referenced by McMd::MdPotentialEnergyAverage::loadParameters(), McMd::PerturbDerivative::loadParameters(), McMd::BoundaryAverage::loadParameters(), McMd::MdEnergyOutput::loadParameters(), McMd::MdKineticEnergyAverage::loadParameters(), McMd::AverageAnalyzer< SystemType >::loadParameters(), McMd::McEnergyOutput::loadParameters(), DdMd::OutputStressTensor::loadParameters(), DdMd::OutputEnergy::loadParameters(), DdMd::OutputTemperature::loadParameters(), DdMd::VirialStressTensor::loadParameters(), DdMd::OutputPairEnergies::loadParameters(), DdMd::OutputPressure::loadParameters(), McMd::PressureAverage< SystemType >::loadParameters(), McMd::McPairEnergyAverage::loadParameters(), McMd::StressTensorAverage< SystemType >::loadParameters(), DdMd::VirialStressTensorAverage::loadParameters(), McMd::McVirialStressTensorAverage::loadParameters(), McMd::MdVirialStressTensorAverage::loadParameters(), McMd::BennettsMethod::loadParameters(), McMd::MdPairEnergyCoefficients::loadParameters(), McMd::MdEnergyAnalyzer::loadParameters(), McMd::McEnergyAnalyzer::loadParameters(), McMd::RadiusGyration::loadParameters(), McMd::BlockRadiusGyration::loadParameters(), McMd::LinkLengthDist::output(), McMd::G1MSD::output(), McMd::McNVTChemicalPotential::output(), McMd::SSChainDist::output(), McMd::ClusterHistogram::output(), Tools::AtomMSD::output(), McMd::McMuExchange::output(), McMd::VelProf::output(), McMd::LinkLifeTime::output(), Tools::PairEnergy::output(), McMd::CfbReptationMove::output(), McMd::CfbReptateMove::output(), McMd::LinkLTPos::output(), McMd::MdEnergyOutput::output(), McMd::AverageAnalyzer< SystemType >::output(), McMd::McEnergyOutput::output(), McMd::SemiGrandDistribution::output(), McMd::MdPotentialEnergyAverage::output(), McMd::PerturbDerivative::output(), McMd::TypeDistribution::output(), DdMd::ExternalEnergyAverage::output(), McMd::LinkMSD::output(), DdMd::PairEnergyAverage::output(), McMd::MdKineticEnergyAverage::output(), McMd::BoundaryAverage::output(), McMd::NLinkAverage::output(), McMd::InterIntraLink::output(), McMd::MdPairEnergyCoefficients::output(), McMd::AtomMSD::output(), DdMd::StressAutoCorr::output(), McMd::BondLengthDist::output(), McMd::PressureAverage< SystemType >::output(), McMd::McPairEnergyAverage::output(), DdMd::AutoCorrAnalyzer< Data, Product >::output(), McMd::StressAutoCorr< SystemType >::output(), McMd::ComMSD::output(), McMd::BennettsMethod::output(), McMd::RingRouseAutoCorr::output(), McMd::EndtoEndXYZ::output(), McMd::MdEnergyAnalyzer::output(), DdMd::AverageAnalyzer::output(), McMd::McEnergyAnalyzer::output(), DdMd::EnergyAnalyzer::output(), McMd::IntraBondStressAutoCorr< SystemType >::output(), McMd::LinearRouseAutoCorr::output(), McMd::EndtoEnd::output(), DdMd::SymmTensorAverageAnalyzer::output(), DdMd::TensorAverageAnalyzer::output(), McMd::RDF::output(), McMd::BlockRadiusGyration::output(), McMd::CompositionProfile::output(), DdMd::OrderParamNucleation::output(), McMd::IntraBondTensorAutoCorr< SystemType >::output(), McMd::StructureFactor::output(), DdMd::StructureFactorGrid::output(), McMd::IntraPairAutoCorr::output(), McMd::StructureFactorGrid::output(), McMd::StructureFactorPGrid::output(), McMd::RadiusGyration::output(), McMd::IntraStructureFactorGrid::output(), DdMd::StructureFactor::output(), DdMd::VanHove::output(), McMd::VanHove::output(), McMd::StructureFactorP::output(), McMd::IntraStructureFactor::output(), McMd::MdSimulation::readCommand(), McMd::McSimulation::readCommand(), Tools::Processor::readCommands(), McMd::MdPotentialEnergyAverage::readParameters(), McMd::PerturbDerivative::readParameters(), McMd::MdEnergyOutput::readParameters(), McMd::BoundaryAverage::readParameters(), McMd::MdKineticEnergyAverage::readParameters(), McMd::AverageAnalyzer< SystemType >::readParameters(), McMd::McEnergyOutput::readParameters(), DdMd::OutputStressTensor::readParameters(), DdMd::OutputBoxdim::readParameters(), DdMd::OutputEnergy::readParameters(), DdMd::OutputTemperature::readParameters(), DdMd::VirialStressTensor::readParameters(), DdMd::OutputPairEnergies::readParameters(), DdMd::OutputPressure::readParameters(), McMd::McPairEnergyAverage::readParameters(), McMd::McNVTChemicalPotential::readParameters(), McMd::PressureAverage< SystemType >::readParameters(), DdMd::VirialStressTensorAverage::readParameters(), McMd::McVirialStressTensorAverage::readParameters(), McMd::MdVirialStressTensorAverage::readParameters(), McMd::VelProf::readParameters(), McMd::BennettsMethod::readParameters(), McMd::MdPairEnergyCoefficients::readParameters(), McMd::LinkMSD::readParameters(), McMd::NLinkAverage::readParameters(), McMd::InterIntraLink::readParameters(), McMd::EndtoEndXYZ::readParameters(), McMd::RadiusGyration::readParameters(), McMd::EndtoEnd::readParameters(), McMd::BlockRadiusGyration::readParameters(), McMd::ReplicaMove::ReplicaMove(), McMd::Crosslinker::sample(), McMd::ClusterHistogram::sample(), McMd::CompositionProfile::sample(), McMd::ConfigWriter::sample(), McMd::StructureFactor::sample(), DdMd::StructureFactorGrid::sample(), McMd::StructureFactorGrid::sample(), DdMd::StructureFactor::sample(), McMd::IntraStructureFactorGrid::sample(), DdMd::OutputStressTensor::setup(), DdMd::OutputEnergy::setup(), DdMd::OutputBoxdim::setup(), DdMd::OutputTemperature::setup(), DdMd::OutputPressure::setup(), McMd::LammpsDumpWriter::setup(), DdMd::TrajectoryWriter::setup(), McMd::McEnergyAnalyzer::setup(), DdMd::AverageAnalyzer::setup(), McMd::MdEnergyAnalyzer::setup(), Tools::TrajectoryWriter::setup(), DdMd::EnergyAnalyzer::setup(), DdMd::TensorAverageAnalyzer::setup(), DdMd::SymmTensorAverageAnalyzer::setup(), and McMd::Simulation::Simulation().
bool Util::FileMaster::isCommonControl () const
Is set for common param and command files?
Definition at line 308 of file FileMaster.cpp.
std::string Util::FileMaster::paramFileName () const inline
Return the param file name, if any.
Definition at line 466 of file FileMaster.h.
Referenced by Tools::Processor::readParam(), and setParamFileName().
std::string Util::FileMaster::commandFileName () const inline
Return the command file name.
The base name of the command file is read from the parameter file by the readParameters() method.
Definition at line 472 of file FileMaster.h.
Referenced by Tools::Processor::readCommands(), and setCommandFileName().
std::istream & Util::FileMaster::paramFile ()
Get a default parameter stream by reference.
If setDirectoryId() has not been called, of if setCommonControl() has been called, this method returns std::cin.
If setDirectoryId() has been called and setCommonControld() has not, this method returns a reference to a file "n/param". This file is opened for reading the first time it is returned by this function.
Definition at line 155 of file FileMaster.cpp.
References openControlFile().
Referenced by Tools::Processor::readParam().
std::istream & Util::FileMaster::commandFile ()
Get the command input stream by reference.
If the commandFileName string is equal to the string literal "paramfile", this method returns the same stream as paramFile(). Otherwise, it returns a reference to a file whose name is given by the commandFileName string. If setDirectoryId(int) has not been called, the path to this file (absolute or relative to the working directory) is equal to the commandFileName string. If setDirectory() has been called with an integer argument n, the path to this file is obtained adding "n/" as a prefix to the commandFileName. In either case, if the commandFileName is not "paramfile", the required file is opened for reading the first time it is returned by this method.
Definition at line 178 of file FileMaster.cpp.
References openControlFile().
Referenced by Tools::Processor::readCommands().
The documentation for this class was generated from the following files:
FileMaster.h
FileMaster.cpp