Simpatico: Util::XmlAttribute Class Reference
Util::XmlAttribute Class Reference
Util namespace » Xml Tag Parsers
Detailed Description
Parser for an XML attribute.
Definition at line 23 of file XmlAttribute.h.
#include <XmlAttribute.h>
Public Member Functions
XmlAttribute ()
Constructor.
virtual ~XmlAttribute ()
Destructor.
bool match (const std::string &string, int begin)
Return true if an attribute is found, false otherwise.
bool match (XmlBase &parser)
If successful return true and advance cursor or parent parser.
const std::string & label ()
Return label string.
std::stringstream & value ()
Return value string, without quotes.
Public Member Functions inherited from Util::XmlBase
XmlBase ()
Constructor.
~XmlBase ()
Destructor.
void setString (const std::string &string, int cursor=0)
Initialize string and cursor.
void setCursor (int cursor)
Set cursor.
void skip ()
Skip leading white space, if any.
void next ()
Advance to the next character.
const std::string & string () const
Return the associated string.
int cursor () const
Return the index of the current character.
int c () const
Return the current character.
bool isEnd () const
Has the cursor reached the end of the string?
Constructor & Destructor Documentation
Util::XmlAttribute::XmlAttribute ()
Constructor.
Definition at line 14 of file XmlAttribute.cpp.
Util::XmlAttribute::~XmlAttribute () virtual
Destructor.
Definition at line 23 of file XmlAttribute.cpp.
Member Function Documentation
bool Util::XmlAttribute::match (const std::string & string, int begin)
Return true if an attribute is found, false otherwise.
Definition at line 26 of file XmlAttribute.cpp.
References Util::XmlBase::c(), Util::XmlBase::cursor(), Util::XmlBase::isEnd(), Util::XmlBase::next(), Util::rStrip(), Util::XmlBase::setString(), Util::XmlBase::skip(), and Util::XmlBase::string().
Referenced by match(), Util::XmlXmlTag::match(), and Util::XmlStartTag::matchAttribute().
bool Util::XmlAttribute::match (XmlBase & parser)
If successful return true and advance cursor or parent parser.
Parameters
parser parent parser object
Definition at line 82 of file XmlAttribute.cpp.
References Util::XmlBase::cursor(), match(), Util::XmlBase::setCursor(), and Util::XmlBase::string().
const std::string& Util::XmlAttribute::label () inline
Return label string.
Definition at line 53 of file XmlAttribute.h.
Referenced by Util::XmlXmlTag::match(), and Tools::HoomdConfigReader::readConfig().
std::stringstream& Util::XmlAttribute::value () inline
Return value string, without quotes.
Definition at line 59 of file XmlAttribute.h.
Referenced by Tools::HoomdConfigReader::readConfig().
The documentation for this class was generated from the following files:
XmlAttribute.h
XmlAttribute.cpp