Simpatico: DdMd::LammpsConfigIo Class Reference
DdMd::LammpsConfigIo Class Reference
ConfigIos
Detailed Description
Lammps data file format for configuration files.
LammpsConfigIo is a ConfigIo that reads and writes the LAMMPS data file format for configuration files. Atoms are output with ids in sequential order.
Definition at line 33 of file ddMd/configIos/LammpsConfigIo.h.
#include <LammpsConfigIo.h>
Public Member Functions
LammpsConfigIo ()
Default constructor.
LammpsConfigIo (Simulation &simulation)
Constructor.
virtual void readConfig (std::ifstream &file, MaskPolicy maskPolicy)
Read configuration file.
virtual void writeConfig (std::ofstream &file)
Write configuration file.
Public Member Functions inherited from DdMd::ConfigIo
ConfigIo ()
Default constructor.
ConfigIo (Simulation &simulation)
Constructor.
virtual ~ConfigIo ()
Destructor.
void associate (Domain &domain, Boundary &boundary, AtomStorage &atomStorage, BondStorage &bondStorage, AngleStorage &angleStorage, DihedralStorage &dihedralStorage, Buffer &buffer)
Associate with related objects.
virtual void initialize (int atomCacheCapacity=100, int bondCacheCapacity=100, int angleCacheCapacity=100, int dihedralCacheCapacity=100)
Set cache sizes and allocate memory.
virtual void readParameters (std::istream &in)
Read cache size and allocate memory.
virtual void load (Serializable::IArchive &ar)
Load internal state of configIo (not configuration) from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state of ConfigIo (not configuration) to an archive.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from DdMd::ConfigIo
void setAtomMasks ()
Set Mask data on all atoms.
Domain & domain ()
Get the Domain by reference.
Boundary & boundary ()
Get Boundary by reference.
AtomStorage & atomStorage ()
Get AtomStorage by reference.
AtomDistributor & atomDistributor ()
Get the AtomDistributor by reference.
AtomCollector & atomCollector ()
Get the AtomCollector by reference.
BondStorage & bondStorage ()
Get BondStorage by reference.
GroupDistributor< 2 > & bondDistributor ()
Get the AtomDistributor by reference.
GroupCollector< 2 > & bondCollector ()
Get the bond collector by reference.
AngleStorage & angleStorage ()
Get AngleStorage by reference.
GroupDistributor< 3 > & angleDistributor ()
Get the angle distributor by reference.
GroupCollector< 3 > & angleCollector ()
Get the angle collector by reference.
DihedralStorage & dihedralStorage ()
Get DihedralStorage by reference.
GroupDistributor< 4 > & dihedralDistributor ()
Get the dihedral distributor by reference.
GroupCollector< 4 > & dihedralCollector ()
Get the dihedral collector by reference.
Constructor & Destructor Documentation
DdMd::LammpsConfigIo::LammpsConfigIo ()
Default constructor.
Definition at line 47 of file ddMd/configIos/LammpsConfigIo.cpp.
DdMd::LammpsConfigIo::LammpsConfigIo (Simulation & simulation)
Constructor.
Parameters
simulation parent Simulation object.
Definition at line 54 of file ddMd/configIos/LammpsConfigIo.cpp.
References DdMd::Simulation::nAngleType(), DdMd::Simulation::nAtomType(), DdMd::Simulation::nBondType(), and DdMd::Simulation::nDihedralType().
Member Function Documentation
void DdMd::LammpsConfigIo::readConfig (std::ifstream & file, MaskPolicy maskPolicy) virtual
Read configuration file.
Call on all processors. File is used and must be open only on master. This routine opens and reads a file on the master, and distributes atom data among the processors.
Precondition
There are no atoms, ghosts, or groups.
AtomStorage is set for scaled / generalized coordinates
Postcondition
atomic coordinates are scaled / generalized
there are no ghosts
Parameters
file input file stream
maskPolicy MaskPolicy to be used in setting atom masks
Implements DdMd::ConfigIo.
Definition at line 109 of file ddMd/configIos/LammpsConfigIo.cpp.
References DdMd::AtomDistributor::addAtom(), DdMd::ConfigIo::atomDistributor(), DdMd::ConfigIo::atomStorage(), Util::bcast(), DdMd::ConfigIo::bondDistributor(), DdMd::ConfigIo::bondStorage(), DdMd::ConfigIo::boundary(), DdMd::ConfigIo::domain(), DdMd::GroupStorage< N >::isValid(), DdMd::AtomDistributor::newAtomPtr(), DdMd::Atom::position(), DdMd::AtomDistributor::receive(), DdMd::AtomDistributor::send(), DdMd::ConfigIo::setAtomMasks(), DdMd::Atom::setId(), Util::OrthorhombicBoundary::setOrthorhombic(), DdMd::Atom::setTypeId(), DdMd::AtomDistributor::setup(), Util::Vector::subtract(), DdMd::AtomStorage::totalAtomCapacity(), Util::OrthorhombicBoundary::transformCartToGen(), UTIL_THROW, and DdMd::AtomDistributor::validate().
void DdMd::LammpsConfigIo::writeConfig (std::ofstream & file) virtual
Write configuration file.
Call on all processors. File is used and must be open only on master. This routine writes a file on the master, collecting atom and group data from all processors.
Parameters
file output file stream (must be open on master)
Implements DdMd::ConfigIo.
Definition at line 339 of file ddMd/configIos/LammpsConfigIo.cpp.
References DdMd::ConfigIo::angleCollector(), DdMd::ConfigIo::angleStorage(), DdMd::ConfigIo::atomCollector(), DdMd::ConfigIo::atomStorage(), DdMd::ConfigIo::bondCollector(), DdMd::ConfigIo::bondStorage(), DdMd::ConfigIo::boundary(), DdMd::GroupStorage< N >::capacity(), DdMd::AtomStorage::computeNAtomTotal(), DdMd::GroupStorage< N >::computeNTotal(), DdMd::ConfigIo::dihedralCollector(), DdMd::ConfigIo::dihedralStorage(), Util::Dimension, DdMd::ConfigIo::domain(), DdMd::Atom::id(), DdMd::AtomStorage::isCartesian(), Util::OrthorhombicBoundary::lengths(), DdMd::AtomStorage::nAtomTotal(), DdMd::AtomCollector::nextPtr(), DdMd::GroupStorage< N >::nTotal(), DdMd::Atom::position(), DdMd::AtomCollector::send(), DdMd::AtomCollector::setup(), Util::OrthorhombicBoundary::transformGenToCart(), DdMd::Atom::typeId(), and UTIL_THROW.
The documentation for this class was generated from the following files:
ddMd/configIos/LammpsConfigIo.h
ddMd/configIos/LammpsConfigIo.cpp