Simpatico: Tools::DdMdConfigReader Class Reference
Tools::DdMdConfigReader Class Reference
Config File Readers
Detailed Description
Native / default DdMd format for configuration files.
Definition at line 29 of file DdMdConfigReader.h.
#include <DdMdConfigReader.h>
Public Member Functions
DdMdConfigReader (bool hasMolecules=false)
Default constructor.
DdMdConfigReader (Configuration &configuration, bool hasMolecules=false)
Constructor.
virtual void readConfig (std::ifstream &file)
Read configuration file in DdMd default format.
Constructor & Destructor Documentation
Tools::DdMdConfigReader::DdMdConfigReader (bool hasMolecules = false)
Default constructor.
Tools::DdMdConfigReader::DdMdConfigReader (Configuration & configuration, bool hasMolecules = false)
Constructor.
Parameters:
configuration parent Configuration object.
hasMolecules true if file format has DdMd::AtomContext info
Definition at line 28 of file DdMdConfigReader.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void Tools::DdMdConfigReader::readConfig (std::ifstream & file) [virtual]
Read configuration file in DdMd default format.
Parameters:
file input file stream
Implements Tools::ConfigReader.
Definition at line 56 of file DdMdConfigReader.cpp.
References Tools::AtomStorage::add(), Tools::ConfigReader::addAtomsToSpecies(), Tools::Atom::atomId, Tools::Configuration::atoms(), Tools::Configuration::boundary(), Tools::AtomStorage::capacity(), Tools::ConfigReader::configuration(), Tools::Atom::id, Tools::Atom::moleculeId, Tools::AtomStorage::newPtr(), Tools::Atom::position, Tools::ConfigReader::setAtomContexts(), Tools::Atom::speciesId, Tools::Atom::typeId, UTIL_THROW, and Tools::Atom::velocity.
The documentation for this class was generated from the following files:
DdMdConfigReader.h
DdMdConfigReader.cpp