Simpatico: McMd::ConfigWriter Class Reference
McMd::ConfigWriter Class Reference
MC/MD Analyzers
Detailed Description
Periodically dump system configuration to a new file.
This class uses the System::writeConfig() method to write the entire system configuration periodically, at interval read from file. Names of configuration dump files are constructed by concatenating the System outputPrefix, a dumpPrefix, the literal string "config.", and an integer that is incremented after each dump. The dump prefix is a string that is read by the read() method of this class. For example, if System::outputPrefix is "out/" and dumpPrefix is "dump/", the configurations will be written to files "out/dump/config.0", "out/dump/config.1", etc.
See also:
parameter file format
Definition at line 36 of file mcMd/analyzers/system/ConfigWriter.h.
#include <ConfigWriter.h>
Public Member Functions
ConfigWriter (System &system)
Constructor.
virtual ~ConfigWriter ()
Destructor.
virtual void readParameters (std::istream &in)
Read dumpPrefix and interval.
virtual void save (Serializable::OArchive &ar)
Save state to archive.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Clear nSample counter.
virtual void sample (long iStep)
Dump configuration to file.
Constructor & Destructor Documentation
McMd::ConfigWriter::ConfigWriter (System & system)
Constructor.
Parameters:
system parent System object.
Definition at line 23 of file mcMd/analyzers/system/ConfigWriter.cpp.
References Util::ParamComposite::setClassName().
virtual McMd::ConfigWriter::~ConfigWriter () [inline, virtual]
Destructor.
Definition at line 51 of file mcMd/analyzers/system/ConfigWriter.h.
Member Function Documentation
void McMd::ConfigWriter::readParameters (std::istream & in) [virtual]
Read dumpPrefix and interval.
Parameters:
in input parameter file
Reimplemented from McMd::Analyzer.
Definition at line 32 of file mcMd/analyzers/system/ConfigWriter.cpp.
References McMd::Analyzer::readInterval(), and McMd::Analyzer::readOutputFileName().
void McMd::ConfigWriter::save (Serializable::OArchive & ar) [virtual]
Save state to archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::Analyzer.
Definition at line 52 of file mcMd/analyzers/system/ConfigWriter.cpp.
void McMd::ConfigWriter::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from McMd::Analyzer.
Definition at line 42 of file mcMd/analyzers/system/ConfigWriter.cpp.
template<class Archive > void McMd::ConfigWriter::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Analyzer.
Definition at line 113 of file mcMd/analyzers/system/ConfigWriter.h.
References McMd::serialize().
void McMd::ConfigWriter::setup () [virtual]
Clear nSample counter.
Reimplemented from McMd::Analyzer.
Definition at line 58 of file mcMd/analyzers/system/ConfigWriter.cpp.
void McMd::ConfigWriter::sample (long iStep) [virtual]
Dump configuration to file.
Parameters:
iStep MC step index
Implements McMd::Analyzer.
Definition at line 64 of file mcMd/analyzers/system/ConfigWriter.cpp.
References McMd::Analyzer::fileMaster(), McMd::Analyzer::isAtInterval(), Util::FileMaster::openOutputFile(), McMd::Analyzer::outputFileName(), McMd::SystemAnalyzer< System >::system(), Util::toString(), and McMd::System::writeConfig().
The documentation for this class was generated from the following files:
mcMd/analyzers/system/ConfigWriter.h
mcMd/analyzers/system/ConfigWriter.cpp