Simpatico: McMd::MdWriteRestart Class Reference
McMd::MdWriteRestart Class Reference
Diagnostics
Detailed Description
Repeatedly write restart file.
Definition at line 26 of file MdWriteRestart.h.
#include <MdWriteRestart.h>
Public Member Functions
MdWriteRestart (MdSimulation &simulation)
Constructor.
virtual ~MdWriteRestart ()
Destructor.
virtual void readParameters (std::istream &in)
Read interval and outputFileName.
void sample (long iStep)
Write restart file.
Constructor & Destructor Documentation
McMd::MdWriteRestart::MdWriteRestart (MdSimulation & simulation)
Constructor.
Parameters:
simulation parent MdSimulation object
Definition at line 26 of file MdWriteRestart.cpp.
References Util::ParamComposite::setClassName().
virtual McMd::MdWriteRestart::~MdWriteRestart () [inline, virtual]
Destructor.
Definition at line 41 of file MdWriteRestart.h.
Member Function Documentation
void McMd::MdWriteRestart::readParameters (std::istream & in) [virtual]
Read interval and outputFileName.
Parameters:
in input parameter file
Reimplemented from McMd::Diagnostic.
Definition at line 34 of file MdWriteRestart.cpp.
References McMd::Diagnostic::readInterval(), and McMd::Diagnostic::readOutputFileName().
void McMd::MdWriteRestart::sample (long iStep) [virtual]
Write restart file.
Parameters:
iStep MC step index
Implements McMd::Diagnostic.
Definition at line 45 of file MdWriteRestart.cpp.
References McMd::Diagnostic::isAtInterval(), McMd::Diagnostic::outputFileName(), and McMd::MdSimulation::writeRestart().
The documentation for this class was generated from the following files:
MdWriteRestart.h
MdWriteRestart.cpp