Simpatico: McMd::StressAutoCorrelation< SystemType > Class Template Reference
McMd::StressAutoCorrelation< SystemType > Class Template Reference
Analyzers
Detailed Description
template<class SystemType>
class McMd::StressAutoCorrelation< SystemType >
Periodically write (tensor) StressTensor to file.
Typename SystemType can be McSystem or MdSystem.
Definition at line 29 of file mcMd/analyzers/system/StressAutoCorrelation.h.
#include <StressAutoCorrelation.h>
Public Member Functions
StressAutoCorrelation (SystemType &system)
Constructor.
virtual ~StressAutoCorrelation ()
Destructor.
virtual void readParameters (std::istream &in)
Read dumpPrefix and interval.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Setup accumulator.
virtual void sample (long iStep)
Sample virial stress to accumulators.
virtual void output ()
Dump configuration to file.
Constructor & Destructor Documentation
template<class SystemType> McMd::StressAutoCorrelation< SystemType >::StressAutoCorrelation (SystemType & system)
Constructor.
Parameters:
system parent SystemType object.
Definition at line 124 of file mcMd/analyzers/system/StressAutoCorrelation.h.
template<class SystemType> virtual McMd::StressAutoCorrelation< SystemType >::~StressAutoCorrelation () [inline, virtual]
Destructor.
Definition at line 44 of file mcMd/analyzers/system/StressAutoCorrelation.h.
Member Function Documentation
template<class SystemType > void McMd::StressAutoCorrelation< SystemType >::readParameters (std::istream & in) [virtual]
Read dumpPrefix and interval.
Parameters:
in input parameter file
Reimplemented from McMd::Analyzer.
Definition at line 136 of file mcMd/analyzers/system/StressAutoCorrelation.h.
template<class SystemType > void McMd::StressAutoCorrelation< SystemType >::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::Analyzer.
Definition at line 152 of file mcMd/analyzers/system/StressAutoCorrelation.h.
References McMd::Analyzer::loadParameters(), and UTIL_THROW.
template<class SystemType > void McMd::StressAutoCorrelation< SystemType >::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::Analyzer.
Definition at line 170 of file mcMd/analyzers/system/StressAutoCorrelation.h.
template<class SystemType > template<class Archive > void McMd::StressAutoCorrelation< SystemType >::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Analyzer.
Definition at line 179 of file mcMd/analyzers/system/StressAutoCorrelation.h.
References McMd::Analyzer::serialize().
template<class SystemType > void McMd::StressAutoCorrelation< SystemType >::setup () [virtual]
Setup accumulator.
Reimplemented from McMd::Analyzer.
Definition at line 190 of file mcMd/analyzers/system/StressAutoCorrelation.h.
References UTIL_THROW.
template<class SystemType > void McMd::StressAutoCorrelation< SystemType >::sample (long iStep) [virtual]
Sample virial stress to accumulators.
Parameters:
iStep MD or MC step index
Implements McMd::Analyzer.
Reimplemented in McMd::McStressAutoCorrelation.
Definition at line 202 of file mcMd/analyzers/system/StressAutoCorrelation.h.
References Util::Tensor::add(), and Util::DArray< Data >::allocate().
template<class SystemType > void McMd::StressAutoCorrelation< SystemType >::output () [virtual]
Dump configuration to file.
Reimplemented from McMd::Analyzer.
Definition at line 240 of file mcMd/analyzers/system/StressAutoCorrelation.h.
The documentation for this class was generated from the following file:
mcMd/analyzers/system/StressAutoCorrelation.h