Simpatico: McMd::CfbRebridgeBase Class Reference
McMd::CfbRebridgeBase Class Reference
Monte Carlo Moves
Detailed Description
Base class configuration bias moves internal segment regrowth moves.
Base class for configuration bias Monte Carlo moves that erase and regrow internal segments of linear polymer chains, with fixed endpoints.
Definition at line 31 of file CfbRebridgeBase.h.
#include <CfbRebridgeBase.h>
Public Member Functions
CfbRebridgeBase (McSystem &system)
Constructor.
virtual ~CfbRebridgeBase ()
Destructor.
virtual void readParameters (std::istream &in)
Read species type, nTrial, and parameters needed to evaluate the orientation bias.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void setup ()
Initialize the arrays for preferential angle, effective spring constant and normalization factor.
Public Member Functions inherited from McMd::CfbEndBase
CfbEndBase (McSystem &system)
Constructor.
virtual ~CfbEndBase ()
Destructor.
void deleteEndAtom (Atom *endPtr, Atom *pvtPtr, int bondType, double &rosenbluth, double &energy)
CFB algorithm for deleting an end atom from a flexible chain.
void addEndAtom (Atom *endPtr, Atom *pvtPtr, int bondType, double &rosenbluth, double &energy)
Configuration bias algorithm for adding an atom to a chain end.
Public Member Functions inherited from McMd::SystemMove
SystemMove (McSystem &system)
Constructor.
virtual ~SystemMove ()
Destructor.
Public Member Functions inherited from McMd::McMove
McMove (Simulation &simulation)
Constructor.
virtual ~McMove ()
Destructor.
void setProbability (double probability)
Set the probability for this McMove.
virtual bool move ()
Generate, attempt, and accept or reject a Monte Carlo move.
double probability () const
Return probability for this McMove.
long nAttempt () const
Return number of moves that have been attempted.
long nAccept () const
Return number of moves that have been accepted.
virtual void output ()
Output statistics for this move (called at the end of the simulation)
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
void deleteMiddleAtom (Atom *partPtr, Atom *prevPtr, Atom *nextPtr, int prevBType, int nextBType, double &rosenbluth, double &energy)
Configuration bias algorithm for deleting a particle between two monomers and compute the corresponding Rosenbluth factor.
void addMiddleAtom (Atom *partPtr, Atom *prevPtr, Atom *nextPtr, int prevBType, int nextBType, double &rosenbluth, double &energy)
Configuration bias algorithm for adding the last particle with special bias in favor of closing the bridge.
void deleteSequence (int nActive, int sign, Atom *endPtr, int *bonds, double &rosenbluth, double &energy)
Configuration bias algorithm for deleting a consequtive sequence of atoms.
void addSequence (int nActive, int sign, Atom *beginPtr, int *bonds, double &rosenbluth, double &energy)
Configuration bias algorithm for adding a consequtive sequence of atoms.
Protected Attributes
double length21_
Equilibrium bond lengths (2-1 bond).
double length10_
Equilibrium bond lengths (1-0 bonds).
double kappa10_
Spring constant (1-0 bond).
Protected Attributes inherited from McMd::CfbEndBase
int nTrial_
Actual number of trial positions for each regrown atom.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Protected Attributes inherited from McMd::CfbEndBase
static const int MaxTrial_ = 20
Maximum allowed number of trial positions for a regrown atom.
Constructor & Destructor Documentation
McMd::CfbRebridgeBase::CfbRebridgeBase (McSystem & system)
Constructor.
Definition at line 26 of file CfbRebridgeBase.cpp.
References McMd::McSystem::hasDihedralPotential(), and UTIL_THROW.
McMd::CfbRebridgeBase::~CfbRebridgeBase () virtual
Destructor.
Definition at line 45 of file CfbRebridgeBase.cpp.
Member Function Documentation
void McMd::CfbRebridgeBase::readParameters (std::istream & in) virtual
Read species type, nTrial, and parameters needed to evaluate the orientation bias.
Reimplemented from McMd::CfbEndBase.
Reimplemented in McMd::CfbRingRebridgeMove, McMd::CfbDoubleRebridgeMove, and McMd::CfbRebridgeMove.
Definition at line 51 of file CfbRebridgeBase.cpp.
References kappa10_, length10_, length21_, McMd::CfbEndBase::MaxTrial_, McMd::CfbEndBase::nTrial_, and UTIL_THROW.
Referenced by McMd::CfbDoubleRebridgeMove::readParameters(), McMd::CfbRebridgeMove::readParameters(), and McMd::CfbRingRebridgeMove::readParameters().
void McMd::CfbRebridgeBase::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from McMd::McMove.
Reimplemented in McMd::CfbRingRebridgeMove, McMd::CfbDoubleRebridgeMove, and McMd::CfbRebridgeMove.
Definition at line 68 of file CfbRebridgeBase.cpp.
References kappa10_, length10_, length21_, McMd::CfbEndBase::MaxTrial_, McMd::CfbEndBase::nTrial_, and UTIL_THROW.
Referenced by McMd::CfbDoubleRebridgeMove::loadParameters(), McMd::CfbRebridgeMove::loadParameters(), and McMd::CfbRingRebridgeMove::loadParameters().
void McMd::CfbRebridgeBase::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from McMd::McMove.
Reimplemented in McMd::CfbRingRebridgeMove, McMd::CfbDoubleRebridgeMove, and McMd::CfbRebridgeMove.
Definition at line 84 of file CfbRebridgeBase.cpp.
References kappa10_, length10_, length21_, and McMd::CfbEndBase::nTrial_.
Referenced by McMd::CfbDoubleRebridgeMove::save(), McMd::CfbRebridgeMove::save(), and McMd::CfbRingRebridgeMove::save().
void McMd::CfbRebridgeBase::setup () virtual
Initialize the arrays for preferential angle, effective spring constant and normalization factor.
Reimplemented from McMd::McMove.
Definition at line 95 of file CfbRebridgeBase.cpp.
References kappa10_, length10_, and length21_.
Referenced by McMd::CfbDoubleRebridgeMove::loadParameters(), McMd::CfbRebridgeMove::loadParameters(), McMd::CfbRingRebridgeMove::loadParameters(), McMd::CfbDoubleRebridgeMove::readParameters(), McMd::CfbRebridgeMove::readParameters(), and McMd::CfbRingRebridgeMove::readParameters().
void McMd::CfbRebridgeBase::deleteMiddleAtom (Atom * partPtr, Atom * prevPtr, Atom * nextPtr, int prevBType, int nextBType, double & rosenbluth, double & energy) protected
Configuration bias algorithm for deleting a particle between two monomers and compute the corresponding Rosenbluth factor.
Definition at line 154 of file CfbRebridgeBase.cpp.
References Util::Vector::add(), McMd::McSystem::anglePotential(), McMd::McPairPotential::atomEnergy(), McMd::ExternalPotential::atomEnergy(), McMd::AnglePotential::atomEnergy(), McMd::SystemMove::boltzmann(), McMd::McSystem::bondPotential(), McMd::SystemMove::boundary(), Util::OrthorhombicBoundary::distanceSq(), McMd::BondPotential::energy(), McMd::McSystem::externalPotential(), McMd::CfbEndBase::nTrial_, McMd::McSystem::pairPotential(), McMd::Atom::position(), McMd::McMove::random(), Util::OrthorhombicBoundary::shift(), McMd::SystemMove::system(), and Util::Random::unitVector().
Referenced by deleteSequence().
void McMd::CfbRebridgeBase::addMiddleAtom (Atom * partPtr, Atom * prevPtr, Atom * nextPtr, int prevBType, int nextBType, double & rosenbluth, double & energy) protected
Configuration bias algorithm for adding the last particle with special bias in favor of closing the bridge.
Definition at line 271 of file CfbRebridgeBase.cpp.
References Util::Vector::add(), McMd::McSystem::anglePotential(), McMd::McPairPotential::atomEnergy(), McMd::ExternalPotential::atomEnergy(), McMd::AnglePotential::atomEnergy(), Util::EnergyEnsemble::beta(), McMd::SystemMove::boltzmann(), McMd::McSystem::bondPotential(), McMd::SystemMove::boundary(), Util::OrthorhombicBoundary::distanceSq(), Util::Random::drawFrom(), McMd::BondPotential::energy(), McMd::SystemMove::energyEnsemble(), McMd::McSystem::externalPotential(), McMd::CfbEndBase::MaxTrial_, McMd::CfbEndBase::nTrial_, McMd::McSystem::pairPotential(), McMd::Atom::position(), McMd::McMove::random(), Util::OrthorhombicBoundary::shift(), McMd::SystemMove::system(), and Util::Random::unitVector().
Referenced by addSequence().
void McMd::CfbRebridgeBase::deleteSequence (int nActive, int sign, Atom * endPtr, int * bonds, double & rosenbluth, double & energy) protected
Configuration bias algorithm for deleting a consequtive sequence of atoms.
Definition at line 382 of file CfbRebridgeBase.cpp.
References McMd::McPairPotential::deleteAtom(), McMd::CfbEndBase::deleteEndAtom(), deleteMiddleAtom(), McMd::McSystem::pairPotential(), and McMd::SystemMove::system().
Referenced by McMd::CfbDoubleRebridgeMove::move(), and McMd::CfbRebridgeMove::move().
void McMd::CfbRebridgeBase::addSequence (int nActive, int sign, Atom * beginPtr, int * bonds, double & rosenbluth, double & energy) protected
Configuration bias algorithm for adding a consequtive sequence of atoms.
Definition at line 433 of file CfbRebridgeBase.cpp.
References McMd::McPairPotential::addAtom(), McMd::CfbEndBase::addEndAtom(), addMiddleAtom(), McMd::McSystem::pairPotential(), and McMd::SystemMove::system().
Referenced by McMd::CfbDoubleRebridgeMove::move(), and McMd::CfbRebridgeMove::move().
Member Data Documentation
double McMd::CfbRebridgeBase::length21_ protected
Equilibrium bond lengths (2-1 bond).
Definition at line 75 of file CfbRebridgeBase.h.
Referenced by loadParameters(), readParameters(), save(), and setup().
double McMd::CfbRebridgeBase::length10_ protected
Equilibrium bond lengths (1-0 bonds).
Definition at line 78 of file CfbRebridgeBase.h.
Referenced by loadParameters(), readParameters(), save(), and setup().
double McMd::CfbRebridgeBase::kappa10_ protected
Spring constant (1-0 bond).
Definition at line 81 of file CfbRebridgeBase.h.
Referenced by loadParameters(), readParameters(), save(), and setup().
The documentation for this class was generated from the following files:
CfbRebridgeBase.h
CfbRebridgeBase.cpp