Simpatico: McMd::BondPotentialImpl< Interaction > Class Template Reference
McMd::BondPotentialImpl< Interaction > Class Template Reference
McMd namespace » Potential Energies » Bond Potentials
Detailed Description
template<class Interaction>
class McMd::BondPotentialImpl< Interaction >
Implementation template for a BondPotential.
Definition at line 34 of file mcMd/potentials/bond/BondPotentialImpl.h.
#include <BondPotentialImpl.h>
Public Member Functions
BondPotentialImpl (System &system)
Constructor.
BondPotentialImpl (BondPotentialImpl< Interaction > &other)
Constructor.
virtual ~BondPotentialImpl ()
Destructor.
virtual void readParameters (std::istream &in)
Read potential energy.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
Interaction & interaction ()
Return bond interaction by reference.
const Interaction & interaction () const
Return bond interaction by const reference.
Interactions Methods
virtual double energy (double rsq, int bondTypeId) const
Return pair energy for a single pair.
virtual double forceOverR (double rsq, int bondTypeId) const
Return force / separation for a single pair.
virtual double randomBondLength (Random *random, double beta, int bondTypeId) const
Return force / separation for a single pair.
void set (std::string name, int type, double value)
Modify a parameter, identified by a string.
double get (std::string name, int type) const
Get a parameter value, identified by a string.
virtual std::string interactionClassName () const
Return pair interaction class name (e.g., "HarmonicBond").
Total Energy, Force and Stress
double atomEnergy (const Atom &atom) const
Calculate the bond energy for one Atom.
void addForces ()
Add the bond forces for all atoms.
virtual void computeEnergy ()
Calculate and store pair energy for this System.
virtual void computeStress ()
Compute and store the total nonbonded pressure.
Public Member Functions inherited from McMd::BondPotential
BondPotential ()
Constructor .
virtual ~BondPotential ()
Destructor (does nothing)
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Public Member Functions inherited from McMd::EnergyCalculator
virtual void unsetEnergy ()
Mark the energy as unknown.
double energy ()
Return the energy contribution, compute if necessary.
Public Member Functions inherited from McMd::StressCalculator
virtual void unsetStress ()
Mark the stress as unknown.
void computeStress (Tensor &stress)
Get pair stress tensor.
void computeStress (Vector &pressures)
Get the xx, yy, zz non-Coulomb pair pressures.
void computeStress (double &pressure)
Get the scalar pressure.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Constructor & Destructor Documentation
template<class Interaction > McMd::BondPotentialImpl< Interaction >::BondPotentialImpl (System & system)
Constructor.
Definition at line 198 of file mcMd/potentials/bond/BondPotentialImpl.h.
template<class Interaction > McMd::BondPotentialImpl< Interaction >::BondPotentialImpl (BondPotentialImpl< Interaction > & other)
Constructor.
Definition at line 209 of file mcMd/potentials/bond/BondPotentialImpl.h.
template<class Interaction > McMd::BondPotentialImpl< Interaction >::~BondPotentialImpl () virtual
Destructor.
Definition at line 221 of file mcMd/potentials/bond/BondPotentialImpl.h.
Member Function Documentation
template<class Interaction > void McMd::BondPotentialImpl< Interaction >::readParameters (std::istream & in) virtual
Read potential energy.
This method reads the bond potential Interaction parameter block. Before calling Interaction::readParameters(), it passes simulation().nBondType() to Interaction::setNAtomType().
Reimplemented from Util::ParamComposite.
Definition at line 233 of file mcMd/potentials/bond/BondPotentialImpl.h.
References Util::ParamComposite::addParamComposite(), McMd::BondPotentialImpl< Interaction >::interaction(), and McMd::SystemInterface::simulation().
template<class Interaction > void McMd::BondPotentialImpl< Interaction >::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 249 of file mcMd/potentials/bond/BondPotentialImpl.h.
References Util::ParamComposite::addParamComposite(), McMd::BondPotentialImpl< Interaction >::interaction(), and McMd::SystemInterface::simulation().
template<class Interaction > void McMd::BondPotentialImpl< Interaction >::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 264 of file mcMd/potentials/bond/BondPotentialImpl.h.
References McMd::BondPotentialImpl< Interaction >::interaction().
template<class Interaction > double McMd::BondPotentialImpl< Interaction >::energy (double rsq, int bondTypeId) const virtual
Return pair energy for a single pair.
Implements McMd::BondPotential.
Definition at line 276 of file mcMd/potentials/bond/BondPotentialImpl.h.
References McMd::BondPotentialImpl< Interaction >::interaction().
template<class Interaction > double McMd::BondPotentialImpl< Interaction >::forceOverR (double rsq, int bondTypeId) const virtual
Return force / separation for a single pair.
Implements McMd::BondPotential.
Definition at line 284 of file mcMd/potentials/bond/BondPotentialImpl.h.
References McMd::BondPotentialImpl< Interaction >::interaction(), and McMd::BondPotentialImpl< Interaction >::randomBondLength().
template<class Interaction > double McMd::BondPotentialImpl< Interaction >::randomBondLength (Random * random, double beta, int bondTypeId) const virtual
Return force / separation for a single pair.
Implements McMd::BondPotential.
Definition at line 293 of file mcMd/potentials/bond/BondPotentialImpl.h.
References McMd::BondPotentialImpl< Interaction >::interaction().
Referenced by McMd::BondPotentialImpl< Interaction >::forceOverR().
template<class Interaction> void McMd::BondPotentialImpl< Interaction >::set (std::string name, int type, double value) inline virtual
Modify a parameter, identified by a string.
Parameters
name parameter name
type bond type index
value new value of parameter
Implements McMd::BondPotential.
Definition at line 104 of file mcMd/potentials/bond/BondPotentialImpl.h.
template<class Interaction> double McMd::BondPotentialImpl< Interaction >::get (std::string name, int type) const inline virtual
Get a parameter value, identified by a string.
Parameters
name parameter name
type bond type index 1
Implements McMd::BondPotential.
Definition at line 113 of file mcMd/potentials/bond/BondPotentialImpl.h.
template<class Interaction > std::string McMd::BondPotentialImpl< Interaction >::interactionClassName () const virtual
Return pair interaction class name (e.g., "HarmonicBond").
Implements McMd::BondPotential.
Definition at line 451 of file mcMd/potentials/bond/BondPotentialImpl.h.
References McMd::BondPotentialImpl< Interaction >::interaction().
template<class Interaction > double McMd::BondPotentialImpl< Interaction >::atomEnergy (const Atom & atom) const virtual
Calculate the bond energy for one Atom.
Parameters
atom Atom object of interest
Returns
bond energy of one atom.
Implements McMd::BondPotential.
Definition at line 300 of file mcMd/potentials/bond/BondPotentialImpl.h.
References McMd::Group< NAtom >::atom(), McMd::SystemInterface::boundary(), Util::OrthorhombicBoundary::distanceSq(), McMd::EnergyCalculator::energy(), McMd::BondPotentialImpl< Interaction >::interaction(), McMd::Atom::position(), and McMd::Group< NAtom >::typeId().
template<class Interaction > void McMd::BondPotentialImpl< Interaction >::addForces () virtual
Add the bond forces for all atoms.
Implements McMd::BondPotential.
Definition at line 353 of file mcMd/potentials/bond/BondPotentialImpl.h.
References McMd::SystemInterface::begin(), McMd::SystemInterface::boundary(), Util::OrthorhombicBoundary::distanceSq(), McMd::Atom::force(), McMd::BondPotentialImpl< Interaction >::interaction(), Util::PArrayIterator< Data >::notEnd(), Util::ConstPArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), McMd::Atom::position(), Util::setToZero(), McMd::SystemInterface::simulation(), McMd::Simulation::species(), and Util::OrthorhombicBoundary::volume().
template<class Interaction > void McMd::BondPotentialImpl< Interaction >::computeEnergy () virtual
Calculate and store pair energy for this System.
Implements McMd::EnergyCalculator.
Definition at line 325 of file mcMd/potentials/bond/BondPotentialImpl.h.
References McMd::SystemInterface::begin(), McMd::SystemInterface::boundary(), McMd::EnergyCalculator::energy(), McMd::BondPotentialImpl< Interaction >::interaction(), Util::ConstPArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::Setable< T >::set(), McMd::SystemInterface::simulation(), and McMd::Simulation::species().
template<class Interaction > void McMd::BondPotentialImpl< Interaction >::computeStress () virtual
Compute and store the total nonbonded pressure.
Implements McMd::StressCalculator.
Definition at line 429 of file mcMd/potentials/bond/BondPotentialImpl.h.
template<class Interaction > Interaction & McMd::BondPotentialImpl< Interaction >::interaction () inline
Return bond interaction by reference.
Definition at line 439 of file mcMd/potentials/bond/BondPotentialImpl.h.
Referenced by McMd::BondPotentialImpl< Interaction >::addForces(), McMd::BondPotentialImpl< Interaction >::atomEnergy(), McMd::BondPotentialImpl< Interaction >::computeEnergy(), McMd::BondPotentialImpl< Interaction >::energy(), McMd::BondPotentialImpl< Interaction >::forceOverR(), McMd::BondPotentialImpl< Interaction >::interactionClassName(), McMd::BondPotentialImpl< Interaction >::loadParameters(), McMd::BondPotentialImpl< Interaction >::randomBondLength(), McMd::BondPotentialImpl< Interaction >::readParameters(), and McMd::BondPotentialImpl< Interaction >::save().
template<class Interaction > const Interaction & McMd::BondPotentialImpl< Interaction >::interaction () const inline
Return bond interaction by const reference.
Definition at line 444 of file mcMd/potentials/bond/BondPotentialImpl.h.
The documentation for this class was generated from the following file:
mcMd/potentials/bond/BondPotentialImpl.h