Simpatico: Util::Signal< T > Class Template Reference
Util::Signal< T > Class Template Reference
Signals (Observer Pattern)
Detailed Description
template<typename T = void>
class Util::Signal< T >
Notifier (or subject) in the Observer design pattern.
A Signal manages a list of registered functor objects, and provides a void Signal<T>::notify(const T&) method that calls them all with the same argument.
The explicit specialization Signal<void>, or Signal<>, has a notify method void Signal<>::notify() that takes no parameters, which calls a method of each observer that takes no parameters.
Definition at line 38 of file Signal.h.
#include <Signal.h>
Public Member Functions
Signal ()
Default constructor.
~Signal ()
Destructor.
template<class Observer >
void addObserver (Observer &observer, void(Observer::*methodPtr)(const T &))
Register an observer.
void clear ()
Clear all observerse from list.
int nObserver () const
Get number of registered observers.
void notify (const T &t)
Notify all observers.
Constructor & Destructor Documentation
template<typename T = void> Util::Signal< T >::Signal () inline
Default constructor.
Definition at line 48 of file Signal.h.
template<typename T > Util::Signal< T >::~Signal ()
Destructor.
Definition at line 19 of file Signal.cpp.
Member Function Documentation
template<typename T > template<class Observer > void Util::Signal< T >::addObserver (Observer & observer, void(Observer::*)(const T &) methodPtr)
Register an observer.
Parameters
observer observer object (invokes method)
methodPtr pointer to relevant method
Definition at line 111 of file Signal.h.
template<typename T > void Util::Signal< T >::clear ()
Clear all observerse from list.
Definition at line 39 of file Signal.cpp.
template<typename T > int Util::Signal< T >::nObserver () const
Get number of registered observers.
Definition at line 54 of file Signal.cpp.
template<typename T > void Util::Signal< T >::notify (const T & t)
Notify all observers.
This method notifies all registered observers by calling the appropriate method of each observer, passing each the parameter t as argument. The explicit specialization Signal<>, with T=void, is used for notification methods that take
Parameters
t Argument passed to notification methods of all observers.
Definition at line 25 of file Signal.cpp.
Referenced by DdMd::NvtIntegrator::integrateStep2(), DdMd::NphIntegrator::integrateStep2(), DdMd::NveIntegrator::integrateStep2(), DdMd::NptIntegrator::integrateStep2(), and DdMd::TwoStepIntegrator::run().
The documentation for this class was generated from the following files:
Signal.h
Signal.cpp