Simpatico: DdMd::PairEnergyAverage Class Reference
DdMd::PairEnergyAverage Class Reference
Analyzers
Detailed Description
Periodically write simulation energies to Log output.
See also:
param file format
Definition at line 27 of file PairEnergyAverage.h.
#include <PairEnergyAverage.h>
Public Member Functions
PairEnergyAverage (Simulation &simulation)
Constructor.
virtual ~PairEnergyAverage ()
Destructor.
virtual void readParameters (std::istream &in)
Read dumpPrefix and interval.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void clear ()
Clear nSample counter.
virtual void sample (long iStep)
Dump configuration to file.
virtual void output ()
Dump configuration to file.
Constructor & Destructor Documentation
DdMd::PairEnergyAverage::PairEnergyAverage (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object.
Definition at line 26 of file PairEnergyAverage.cpp.
References Util::ParamComposite::setClassName().
DdMd::PairEnergyAverage::~PairEnergyAverage () [virtual]
Destructor.
Definition at line 38 of file PairEnergyAverage.cpp.
References DdMd::Analyzer::simulation().
Member Function Documentation
void DdMd::PairEnergyAverage::readParameters (std::istream & in) [virtual]
Read dumpPrefix and interval.
Parameters:
in input parameter file
Reimplemented from Util::ParamComposite.
Definition at line 48 of file PairEnergyAverage.cpp.
References Util::DArray< Data >::allocate(), DdMd::Simulation::domain(), DdMd::Domain::isMaster(), DdMd::Analyzer::readInterval(), DdMd::Analyzer::readOutputFileName(), Util::Average::setNSamplePerBlock(), and DdMd::Analyzer::simulation().
void DdMd::PairEnergyAverage::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from DdMd::Analyzer.
Definition at line 69 of file PairEnergyAverage.cpp.
References Util::MpiLoader< IArchive >::load(), DdMd::Analyzer::loadInterval(), Util::Average::loadParameters(), Util::Average::nSamplePerBlock(), DdMd::Analyzer::simulation(), and UTIL_THROW.
void DdMd::PairEnergyAverage::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from DdMd::Analyzer.
Definition at line 90 of file PairEnergyAverage.cpp.
References DdMd::Analyzer::saveInterval(), DdMd::Analyzer::saveOutputFileName(), and DdMd::Analyzer::simulation().
void DdMd::PairEnergyAverage::clear () [virtual]
Clear nSample counter.
Reimplemented from DdMd::Analyzer.
Definition at line 104 of file PairEnergyAverage.cpp.
References Util::Average::clear(), and DdMd::Analyzer::simulation().
void DdMd::PairEnergyAverage::sample (long iStep) [virtual]
Dump configuration to file.
Parameters:
iStep MD step index
Implements DdMd::Analyzer.
Definition at line 114 of file PairEnergyAverage.cpp.
References DdMd::Simulation::computePairEnergies(), DdMd::Analyzer::isAtInterval(), DdMd::Simulation::nAtomType(), DdMd::Simulation::pairEnergies(), Util::Average::sample(), and DdMd::Analyzer::simulation().
void DdMd::PairEnergyAverage::output () [virtual]
Dump configuration to file.
Reimplemented from DdMd::Analyzer.
Definition at line 134 of file PairEnergyAverage.cpp.
References DdMd::Simulation::fileMaster(), Util::FileMaster::openOutputFile(), Util::Average::output(), DdMd::Analyzer::outputFileName(), DdMd::Analyzer::simulation(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
PairEnergyAverage.h
PairEnergyAverage.cpp