Simpatico: McMd::McSimulation Class Reference
McMd::McSimulation Class Reference
Simulations
Detailed Description
A Monte-Carlo simulation of one McSystem.
Definition at line 31 of file McSimulation.h.
#include <McSimulation.h>
Public Member Functions
McSimulation (MPI::Intracomm &communicator)
Constructor.
McSimulation ()
Constructor.
virtual ~McSimulation ()
Destructor.
void setOptions (int argc, char **argv)
Process command line options.
virtual void readParam (std::istream &in)
Read parameter file.
void readParam ()
Read parameters from the default parameter stream.
virtual void readParameters (std::istream &in)
Read parameters from a specific stream.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void readCommands (std::istream &in)
Read and execute commands from a specific input stream.
void readCommands ()
Read and execute commands from the default parameter file.
void simulate (int endStep, bool isContinuation=false)
Run an MC simulation of specified length.
void analyze (int min, int max, std::string dumpPrefix)
Read and analyze a sequence of configuration files.
void save (const std::string &filename)
Write restart files.
void load (const std::string &filename)
Read restart files.
template<class Archive >
void serialize (Archive &ar, unsigned int version)
Serialize to/from an archive.
McSystem & system ()
Get the McSystem by reference.
const McSystem & system () const
Get the McSystem by const refererence.
Factory< McMove > & mcMoveFactory ()
Get the McMove factory by reference.
virtual bool isValid () const
Return true if valid, or throw an Exception.
Public Member Functions inherited from McMd::Simulation
Simulation (MPI::Intracomm &communicator)
Constructor.
Simulation ()
Constructor.
virtual ~Simulation ()
Destructor.
virtual void setIoCommunicator (MPI::Intracomm &communicator)
Set MPI job to read one parameter file and one command file.
void setIoCommunicator ()
Set MPI job to read one parameter file and one command file.
void allocateMoleculeSet (Util::ArraySet< Molecule > &set, int speciesId) const
Allocate and initialize a molecule set for one Species.
Random & random ()
Get the random number generator by reference.
Species & species (int i)
Get a specific Species by reference.
Factory< Analyzer > & analyzerFactory ()
Return the Analyzer factory by reference.
Factory< Species > & speciesFactory ()
Return the Species Factory by reference.
FileMaster & fileMaster ()
Get the FileMaster object.
MPI::Intracomm & communicator ()
Get the MPI communicator by reference.
int nAtomType () const
Get the number of atom types.
int nBondType () const
Get the number of bond types.
int nAngleType () const
Get the number of angle types.
int nDihedralType () const
Get the number of dihedral types.
int nLinkType () const
Get the number of link types.
int hasExternal () const
Does an external potential exist?
int nSystem () const
Get the number of Systems in this Simulation.
int nSpecies () const
Get the number of Species in this Simulation.
int moleculeCapacity () const
Get the total number of Molecules allocated.
int atomCapacity () const
Get the total number of Atoms allocated.
int bondCapacity () const
Get the total number of Bonds allocated.
int angleCapacity () const
Get the total number of Angles allocated.
int dihedralCapacity () const
Get the total number of Dihedrals allocated.
MaskPolicy maskedPairPolicy () const
Return the value of the mask policy (MaskNone or MaskBonded).
const Species & species (int i) const
Get a specific Species by const reference.
const AtomType & atomType (int i) const
Get a single AtomType object by const reference.
const Array< AtomType > & atomTypes () const
Get a const Array of all AtomType objects.
int iStep () const
Get value of step index for main MC or MD loop.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
McMoveManager & mcMoveManager ()
Get the McMoveManager by reference.
Protected Member Functions inherited from McMd::Simulation
void setAnalyzerManager (AnalyzerManager *ptr)
Set the associated AnalyzerManager.
AnalyzerManager & analyzerManager ()
Get the associated AnalyzerManager by reference.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Attributes inherited from McMd::Simulation
int nSystem_
Number of Systems of interacting molecules (> 1 in Gibbs ensemble).
int iStep_
Step index for main MC or MD loop.
Constructor & Destructor Documentation
McMd::McSimulation::McSimulation (MPI::Intracomm & communicator)
Constructor.
Definition at line 60 of file McSimulation.cpp.
References McMd::Simulation::fileMaster(), McMd::Simulation::setAnalyzerManager(), Util::ParamComposite::setClassName(), McMd::System::setFileMaster(), McMd::System::setId(), McMd::System::setSimulation(), and system().
McMd::McSimulation::McSimulation ()
Constructor.
Definition at line 90 of file McSimulation.cpp.
References McMd::Simulation::fileMaster(), McMd::Simulation::setAnalyzerManager(), Util::ParamComposite::setClassName(), McMd::System::setFileMaster(), McMd::System::setId(), McMd::System::setSimulation(), and system().
McMd::McSimulation::~McSimulation () virtual
Destructor.
Definition at line 119 of file McSimulation.cpp.
Member Function Documentation
void McMd::McSimulation::setOptions (int argc, char ** argv)
Process command line options.
Options:
-e Enable echoing of the parameter file to a file.
-p Enable use of a free energy perturbation.
-r filename. Restart a simulation.
When restarting a simulation, the required parameter "filename" is the base name for the 3 required input files: filename.prm, filename.rst, and filename.cmd.
Parameters
argc number of arguments
argv vector of pointers to char* string arguments
Definition at line 128 of file McSimulation.cpp.
References Util::Log::file(), load(), Util::ParamComponent::setEcho(), McMd::System::setExpectPerturbation(), McMd::Simulation::setIoCommunicator(), system(), and UTIL_THROW.
void McMd::McSimulation::readParam (std::istream & in) virtual
Read parameter file.
Parameters
in parameter file stream
Reimplemented from Util::ParamComposite.
Definition at line 236 of file McSimulation.cpp.
References Util::ParamComposite::className(), Util::ParamComposite::readBegin(), Util::ParamComposite::readEnd(), and readParameters().
void McMd::McSimulation::readParam ()
Read parameters from the default parameter stream.
Default parameter istream is std::cin in serial mode (ifndef UTIL_MPI) and the file "n/param" for processor n in parallel mode (ifdef UTIL_MPI).
Definition at line 251 of file McSimulation.cpp.
References McMd::Simulation::fileMaster().
void McMd::McSimulation::readParameters (std::istream & in) virtual
Read parameters from a specific stream.
Parameters
in parameter file input stream.
Reimplemented from McMd::Simulation.
Definition at line 201 of file McSimulation.cpp.
References McMd::Simulation::analyzerManager(), isValid(), Util::ParamComposite::readParamComposite(), McMd::Simulation::readParameters(), system(), and UTIL_THROW.
Referenced by readParam().
void McMd::McSimulation::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from McMd::Simulation.
Definition at line 257 of file McSimulation.cpp.
References McMd::Simulation::analyzerManager(), Util::MpiFileIo::hasIoCommunicator(), McMd::Simulation::iStep_, isValid(), McMd::McSystem::loadConfig(), Util::ParamComposite::loadParamComposite(), McMd::Simulation::loadParameters(), system(), and UTIL_THROW.
void McMd::McSimulation::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from McMd::Simulation.
Definition at line 286 of file McSimulation.cpp.
References McMd::Simulation::analyzerManager(), McMd::Simulation::iStep_, McMd::AnalyzerManager::save(), McMd::McMoveManager::save(), McMd::Simulation::save(), McMd::System::saveConfig(), McMd::McSystem::saveParameters(), and system().
Referenced by save(), and simulate().
void McMd::McSimulation::readCommands (std::istream & in)
Read and execute commands from a specific input stream.
Parameters
in command file input stream.
Definition at line 349 of file McSimulation.cpp.
References Util::DArray< Data >::allocate(), analyze(), McMd::McSystem::anglePotential(), McMd::System::begin(), McMd::McSystem::bondPotential(), McMd::System::boundary(), McMd::McPairPotential::buildCellList(), McMd::Simulation::communicator(), McMd::McSystem::dihedralPotential(), Util::Log::file(), McMd::Simulation::fileMaster(), McMd::Species::generateMolecules(), Util::getNextLine(), Util::MpiFileIo::hasIoCommunicator(), Util::MpiFileIo::isIoProcessor(), McMd::Simulation::iStep_, McMd::Simulation::nAtomType(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::FileMaster::openInputFile(), Util::FileMaster::openOutputFile(), McMd::McSystem::pairPotential(), McMd::McSystem::readConfig(), McMd::PairPotential::set(), McMd::DihedralPotential::set(), McMd::BondPotential::set(), McMd::AnglePotential::set(), McMd::System::setConfigIo(), simulate(), McMd::Simulation::species(), system(), Util::OrthorhombicBoundary::transformCartToGen(), Util::OrthorhombicBoundary::transformGenToCart(), UTIL_THROW, McMd::System::writeConfig(), and Util::ParamComposite::writeParam().
void McMd::McSimulation::readCommands ()
Read and execute commands from the default parameter file.
This method opens the file with the name commandFile read by the FileMaster.
Definition at line 611 of file McSimulation.cpp.
References McMd::Simulation::fileMaster().
void McMd::McSimulation::simulate (int endStep, bool isContinuation = false)
Run an MC simulation of specified length.
This method implements the main MC loop. The step counter iStep_ is incremented until it reaches endStep. Each step involves a random selection and attempt of one Markov MC move. Upon exit, iStep_ = endStep.
If isContinuation is false, the step counter iStep_ is initialized to zero, and analyzers and mcmoves are set to default initial states before entering the main loop. If isContinuation is true, no such initialization is done for iStep_, analyzers, or the MC moves.
Parameters
endStep Final value of MC step counter iStep_.
isContinuation Is this a continuation of a previous run?
Definition at line 617 of file McSimulation.cpp.
References McMd::Simulation::analyzerManager(), McMd::Analyzer::baseInterval, McMd::McPairPotential::buildCellList(), McMd::McMoveManager::chooseMove(), Util::Log::file(), McMd::Simulation::iStep_, McMd::McMove::move(), McMd::ReplicaMove::move(), McMd::ReplicaMove::nAccept(), McMd::ReplicaMove::nAttempt(), McMd::AnalyzerManager::output(), McMd::McMoveManager::output(), McMd::McSystem::pairPotential(), McMd::System::replicaMove(), McMd::AnalyzerManager::sample(), save(), McMd::AnalyzerManager::setup(), McMd::McMoveManager::setup(), Util::Timer::start(), Util::Timer::stop(), system(), Util::Timer::time(), and UTIL_THROW.
Referenced by readCommands().
void McMd::McSimulation::analyze (int min, int max, std::string dumpPrefix)
Read and analyze a sequence of configuration files.
This method reads and analyzes a sequence of configuration files, which were normally generated by running a previous simulation using DumpConfig, and applies the sample() method of every Analyzer to each such configuration.
The method reads files with names of the form inputPrefix() + n for integer suffixes min <= n <= max. This is consistent with the output format used by the DumpConfig class.
In serial mode, the inputPrefix should be given as a path relative to the directory in which the program is executed. The inputPrefix of the simulation FileMaster is not prepended to the dump Prefix.
In parallel mode, for processor with MPI rank m, the path "m/" is prepended to the dumpPrefix, so that all files associated with this processor are in this directory, but no inputPrefix is added after the string "m/".
Parameters
min integer suffix of first configuration file name
max integer suffix of last configuration file name
dumpPrefix root name for dump files (without integer suffix)
Definition at line 748 of file McSimulation.cpp.
References McMd::Simulation::analyzerManager(), McMd::McPairPotential::buildCellList(), Util::Log::file(), McMd::Simulation::fileMaster(), McMd::Simulation::iStep_, isValid(), Util::FileMaster::openInputFile(), McMd::AnalyzerManager::output(), McMd::McSystem::pairPotential(), McMd::McSystem::readConfig(), McMd::System::removeAllMolecules(), McMd::AnalyzerManager::sample(), McMd::AnalyzerManager::setup(), Util::Timer::start(), Util::Timer::stop(), system(), Util::Timer::time(), and UTIL_THROW.
Referenced by readCommands().
void McMd::McSimulation::save (const std::string & filename)
Write restart files.
Definition at line 334 of file McSimulation.cpp.
References Util::BinaryFileOArchive::file(), McMd::Simulation::fileMaster(), McMd::Simulation::iStep_, Util::FileMaster::openRestartOFile(), and save().
void McMd::McSimulation::load (const std::string & filename)
Read restart files.
Definition at line 301 of file McSimulation.cpp.
References Util::Log::file(), Util::BinaryFileIArchive::file(), McMd::Simulation::fileMaster(), Util::FileMaster::openRestartIFile(), Util::FileMaster::setCommandFileName(), McMd::Simulation::setIoCommunicator(), system(), and UTIL_THROW.
Referenced by setOptions().
template<class Archive > void McMd::McSimulation::serialize (Archive & ar, unsigned int version)
Serialize to/from an archive.
Parameters
ar saving or loading archive
version archive version id
McSystem & McMd::McSimulation::system () inline
Get the McSystem by reference.
Definition at line 252 of file McSimulation.h.
Referenced by analyze(), isValid(), load(), loadParameters(), McSimulation(), readCommands(), readParameters(), save(), setOptions(), and simulate().
const McSystem & McMd::McSimulation::system () const inline
Get the McSystem by const refererence.
Definition at line 258 of file McSimulation.h.
Factory< McMove > & McMd::McSimulation::mcMoveFactory ()
Get the McMove factory by reference.
Definition at line 817 of file McSimulation.cpp.
References Util::Manager< Data >::factory().
bool McMd::McSimulation::isValid () const virtual
Return true if valid, or throw an Exception.
Reimplemented from McMd::Simulation.
Definition at line 823 of file McSimulation.cpp.
References McMd::McSystem::isValid(), McMd::Simulation::isValid(), system(), and UTIL_THROW.
Referenced by analyze(), loadParameters(), and readParameters().
McMoveManager & McMd::McSimulation::mcMoveManager () inline protected
Get the McMoveManager by reference.
Definition at line 264 of file McSimulation.h.
The documentation for this class was generated from the following files:
McSimulation.h
McSimulation.cpp