Simpatico: McMd::DihedralPotential Class Reference
McMd::DihedralPotential Class Reference abstract
Dihedral Potentials
Detailed Description
Interface for a Dihedral Potential.
Definition at line 32 of file mcMd/potentials/dihedral/DihedralPotential.h.
#include <DihedralPotential.h>
Public Member Functions
DihedralPotential ()
Constructor.
virtual ~DihedralPotential ()
Destructor (does nothing)
Dihedral interaction interface
virtual double energy (const Vector &R1, const Vector &R2, const Vector &R3, int type) const =0
Returns potential energy for one dihedral.
virtual void force (const Vector &R1, const Vector &R2, const Vector &R3, Vector &F1, Vector &F2, Vector &F3, int type) const =0
Returns derivatives of energy with respect to bond vectors.
virtual void set (std::string name, int type, double value)=0
Modify an interaction parameter, identified by a string.
virtual double get (std::string name, int type) const =0
Get an interaction parameter value, identified by a string.
virtual std::string interactionClassName () const =0
Return name of pair interaction class (e.g., "HarmonicDihedral").
System energy, force, and stress
virtual double atomEnergy (const Atom &atom) const
Compute and return the dihedral potential energy for one Atom.
virtual double energy () const =0
Compute and return the total Dihedral energy for the associated System.
virtual void addForces ()
Add dihedral potential forces to all atomic forces.
virtual void computeStress (double &stress) const =0
Compute total dihedral pressure.
virtual void computeStress (Util::Vector &stress) const =0
Compute x, y, z dihedral pressures.
virtual void computeStress (Util::Tensor &stress) const =0
Compute dihedral stress tensor.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void readParameters (std::istream &in)
Read the body of parameter block, without begin and end lines.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Constructor & Destructor Documentation
McMd::DihedralPotential::DihedralPotential ()
Constructor.
Definition at line 21 of file mcMd/potentials/dihedral/DihedralPotential.cpp.
McMd::DihedralPotential::~DihedralPotential () virtual
Destructor (does nothing)
Definition at line 27 of file mcMd/potentials/dihedral/DihedralPotential.cpp.
Member Function Documentation
virtual double McMd::DihedralPotential::energy (const Vector & R1, const Vector & R2, const Vector & R3, int type) const pure virtual
Returns potential energy for one dihedral.
0   2    3
o   o----o
 \ /
  o
  1
Parameters
R1 bond vector r1 - r0 from atom 0 to 1
R2 bond vector r2 - r1 from atom 1 to 2
R3 bond vector r3 - r2 from atom 2 to 3
type type index for dihedral
Implemented in McMd::DihedralPotentialImpl< Interaction >.
Referenced by McMd::McSystem::potentialEnergy(), McMd::MdSystem::potentialEnergy(), McMd::MdEnergyOutput::sample(), and McMd::McEnergyOutput::sample().
virtual void McMd::DihedralPotential::force (const Vector & R1, const Vector & R2, const Vector & R3, Vector & F1, Vector & F2, Vector & F3, int type) const pure virtual
Returns derivatives of energy with respect to bond vectors.
Parameters
R1 bond vector from atom 0 to 1 (input)
R2 bond vector from atom 1 to 2 (input)
R3 bond vector from atom 2 to 3 (input)
F1 derivative of energy w/respect to R1 (output)
F2 derivative of energy w/respect to R2 (output)
F3 derivative of energy w/respect to R3 (output)
type type index for dihedral
Implemented in McMd::DihedralPotentialImpl< Interaction >.
virtual void McMd::DihedralPotential::set (std::string name, int type, double value) pure virtual
Modify an interaction parameter, identified by a string.
Parameters
name parameter name
type dihedral type index
value new value of parameter
Implemented in McMd::DihedralPotentialImpl< Interaction >.
Referenced by McMd::MdSimulation::readCommands(), and McMd::McSimulation::readCommands().
virtual double McMd::DihedralPotential::get (std::string name, int type) const pure virtual
Get an interaction parameter value, identified by a string.
Parameters
name parameter name
type dihedral type index
Returns
value of parameter
Implemented in McMd::DihedralPotentialImpl< Interaction >.
virtual std::string McMd::DihedralPotential::interactionClassName () const pure virtual
Return name of pair interaction class (e.g., "HarmonicDihedral").
Implemented in McMd::DihedralPotentialImpl< Interaction >.
virtual double McMd::DihedralPotential::atomEnergy (const Atom & atom) const inline virtual
Compute and return the dihedral potential energy for one Atom.
Default method throws an exception.This allows testing of subclasses that only work for MD simulation, and crash gracefully if used for MC.
Parameters
atom Atom object of interest
Returns
bond potential energy of atom
Reimplemented in McMd::DihedralPotentialImpl< Interaction >.
Definition at line 119 of file mcMd/potentials/dihedral/DihedralPotential.h.
References UTIL_THROW.
Referenced by McMd::McSystem::atomPotentialEnergy().
virtual double McMd::DihedralPotential::energy () const pure virtual
Compute and return the total Dihedral energy for the associated System.
Implemented in McMd::DihedralPotentialImpl< Interaction >.
virtual void McMd::DihedralPotential::addForces () inline virtual
Add dihedral potential forces to all atomic forces.
Default version throws an exception.This allows testing of subclasses that only work for MC simulation, and crash gracefully if used for MD.
Reimplemented in McMd::DihedralPotentialImpl< Interaction >.
Definition at line 136 of file mcMd/potentials/dihedral/DihedralPotential.h.
References UTIL_THROW.
Referenced by McMd::MdSystem::calculateForces().
virtual void McMd::DihedralPotential::computeStress (double & stress) const pure virtual
Compute total dihedral pressure.
Parameters
stress (output) pressure.
Implemented in McMd::DihedralPotentialImpl< Interaction >.
virtual void McMd::DihedralPotential::computeStress (Util::Vector & stress) const pure virtual
Compute x, y, z dihedral pressures.
Parameters
stress (output) pressures.
Implemented in McMd::DihedralPotentialImpl< Interaction >.
virtual void McMd::DihedralPotential::computeStress (Util::Tensor & stress) const pure virtual
Compute dihedral stress tensor.
Parameters
stress (output) pressures.
Implemented in McMd::DihedralPotentialImpl< Interaction >.
The documentation for this class was generated from the following files:
mcMd/potentials/dihedral/DihedralPotential.h
mcMd/potentials/dihedral/DihedralPotential.cpp