Simpatico: Util::ParamComponent Class Reference
Util::ParamComponent Class Reference
Parameter File IO
Detailed Description
Abstract base class for classes that input and ouput parameters to file.
The readParam method reads a parameter or parameter list from iostream. The writeParam method writes a parameter or parameter list to an ostream. The same io format should be used by write and read methods.
Definition at line 30 of file ParamComponent.h.
#include <ParamComponent.h>
Public Member Functions
virtual ~ParamComponent ()
Destructor.
virtual void readParam (std::istream &in)=0
Read parameter(s) from file.
virtual void writeParam (std::ostream &out)=0
Read parameter(s) to file.
virtual void resetParam ()
Nontrivial implementation provided by ParamComposite subclass.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
void setParamCommunicator (MPI::Intracomm &communicator)
Set an MPI communicator for parameter IO.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Static Public Member Functions
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Set echo parameter to true enable echoing, or false to disable.
static bool echo ()
Get echo parameter.
Protected Member Functions
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
bool isParamIoProcessor () const
Should this processor do parameter file IO?
bool hasParamCommunicator () const
Has an MPI communicator been set for parameter input?
MPI::Intracomm & paramCommunicator () const
Return the parameter communicator.
Constructor & Destructor Documentation
Util::ParamComponent::~ParamComponent () [virtual]
Destructor.
Definition at line 40 of file ParamComponent.cpp.
Util::ParamComponent::ParamComponent () [protected]
Constructor.
Protected to prevent instantiation of a conceptually abstract class.
On return the indent string is empty. If UTIL_MPI is defined, no communicator is set upon construction.
Definition at line 24 of file ParamComponent.cpp.
Util::ParamComponent::ParamComponent (const ParamComponent & other) [protected]
Copy constructor.
Definition at line 32 of file ParamComponent.cpp.
Member Function Documentation
virtual void Util::ParamComponent::readParam (std::istream & in) [pure virtual]
Read parameter(s) from file.
Parameters:
in input stream
Implemented in Util::AutoCorr< Data, Product >, Util::AutoCorrArray< Data, Product >, Util::Average, Util::Distribution, Util::IntDistribution, Util::MeanSqDispArray< Data >, Util::RadialDistribution, Util::BoundaryEnsemble, Util::EnergyEnsemble, Util::SpeciesEnsemble, Util::Begin, Util::Blank, Util::CArray2DParam< Type >, Util::CArrayParam< Type >, Util::DArrayParam< Type >, Util::DMatrixParam< Type >, Util::End, Util::FArrayParam< Type, N >, Util::Manager< Data >, Util::ParamComposite, Util::ScalarParam< Type >, Util::TextComposite, Util::Random, Inter::CosineAngle, Inter::CosineSqAngle, Inter::CompositeBond< BareBond, BarePair >, Inter::FeneBond, Inter::HarmonicBond, Inter::HarmonicL0Bond, Inter::CosineDihedral, Inter::BoxExternal, Inter::OrthoBoxExternal, Inter::SlitExternal, Inter::TanhCosineExternal, Inter::CompensatedPair< BarePair, LinkPotential >, Inter::DpdPair, Inter::LJPair, McMd::DiagnosticManager, McMd::McEnergyAverage, McMd::McEnergyOutput, McMd::McExternalEnergyAverage, McMd::McPairEnergyAverage, McMd::McStressAutoCorr, McMd::McWriteRestart, McMd::MdEnergyOutput, McMd::MdKineticEnergyAverage, McMd::MdPairEnergyCoefficients, McMd::MdPotentialEnergyAverage, McMd::MdWriteRestart, McMd::SemiGrandDistribution, McMd::TypeDistribution, McMd::BennettsMethod, McMd::PerturbDerivative, McMd::LogProgress, McMd::AtomMSD, McMd::BlockRadiusGyration, McMd::BondLengthDist, McMd::BoundaryAverage, McMd::ComMSD, McMd::CompositionProfile, McMd::DumpConfig, McMd::IntraBondStressAutoCorr< SystemType >, McMd::IntraBondTensorAutoCorr< SystemType >, McMd::IntraPairAutoCorr, McMd::IntraStructureFactor, McMd::LinearRouseAutoCorr, McMd::MigratingVanHove, McMd::PressureAverage< SystemType >, McMd::RadiusGyration, McMd::RDF, McMd::RingRouseAutoCorr, McMd::StructureFactor, McMd::StructureFactorGrid, McMd::StructureFactorP, McMd::StructureFactorPGrid, McMd::VanHove, McMd::AverageDiagnostic< SystemType >, McMd::LinkMaster, McMd::CfbEndBase, McMd::CfbRebridgeBase, McMd::AtomDisplaceMove, McMd::DpdMove, McMd::HybridMdMove, McMd::HybridNphMdMove, McMd::MdMove, McMd::RigidDisplaceMove, McMd::CfbDoubleRebridgeMove, McMd::CfbEndMove, McMd::CfbHomoReptationMove, McMd::CfbRebridgeMove, McMd::CfbReptationMove, McMd::EndSwapMove, McMd::McMove, McMd::McMoveManager, McMd::CfbRingRebridgeMove, McMd::RingOctaRebridgeMove, McMd::RingTetraRebridgeMove, McMd::HomopolymerSemiGrandMove, McMd::McSimulation, McMd::McSystem, McMd::NphIntegrator, McMd::NveVvIntegrator, McMd::NvtDpdVvIntegrator, McMd::NvtNhIntegrator, McMd::MdSimulation, McMd::MdSystem, McMd::PairList, McMd::McEnergyPerturbation, McMd::McExternalPerturbation< Interaction >, McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >, McMd::McPairPerturbation< Interaction >, McMd::ReplicaMove, McMd::AnglePotentialImpl< Interaction >, McMd::BondPotentialImpl< Interaction >, McMd::DihedralPotentialImpl< Interaction >, McMd::ExternalPotentialImpl< Interaction >, McMd::LinkPotentialImpl< Interaction >, McMd::McPairPotentialImpl< Interaction >, McMd::MdPairPotentialImpl< Interaction >, McMd::Simulation, McMd::System, McMd::HomopolymerSG, McMd::Species, McMd::SpeciesManager, McMd::TetherMaster, McMd::FileMaster, DdMd::ActorManager, DdMd::AtomDistributor, DdMd::Buffer, DdMd::Domain, DdMd::GroupDistributor< N >, DdMd::ConfigIo, DdMd::DiagnosticManager, DdMd::OutputBoxdim, DdMd::OutputEnergy, DdMd::OutputPairEnergies, DdMd::OutputPressure, DdMd::OutputTemperature, DdMd::StructureFactor, DdMd::StructureFactorGrid, DdMd::WriteConfig, DdMd::NphIntegrator, DdMd::NptIntegrator, DdMd::NveIntegrator, DdMd::NvtIntegrator, DdMd::AnglePotentialImpl< Interaction >, DdMd::BondPotentialImpl< Interaction >, DdMd::DihedralPotentialImpl< Interaction >, DdMd::ExternalPotentialImpl< Interaction >, DdMd::PairPotentialImpl< Interaction >, DdMd::Simulation, DdMd::AngleStorage, DdMd::AtomStorage, DdMd::BondStorage, DdMd::DihedralStorage, DdMd::GroupStorage< N >, DdMd::FileMaster, Util::AutoCorr< Tensor, double >, Util::AutoCorr< double, double >, Util::AutoCorr< std::complex< double >, std::complex< double > >, Util::AutoCorrArray< Tensor, double >, Util::AutoCorrArray< Vector, double >, Util::MeanSqDispArray< Vector >, Util::Manager< Species >, Util::Manager< Actor >, Util::Manager< McMove >, Util::Manager< Diagnostic >, McMd::IntraBondStressAutoCorr< MdSystem >, McMd::IntraBondStressAutoCorr< McSystem >, McMd::IntraBondTensorAutoCorr< MdSystem >, McMd::IntraBondTensorAutoCorr< McSystem >, McMd::PressureAverage< MdSystem >, McMd::PressureAverage< McSystem >, McMd::AverageDiagnostic< McSystem >, DdMd::GroupDistributor< 2 >, DdMd::GroupStorage< 2 >, DdMd::GroupStorage< 3 >, and DdMd::GroupStorage< 4 >.
Referenced by serialize().
virtual void Util::ParamComponent::writeParam (std::ostream & out) [pure virtual]
Read parameter(s) to file.
Parameters:
out output stream
Implemented in Util::Begin, Util::Blank, Util::CArray2DParam< Type >, Util::CArrayParam< Type >, Util::DArrayParam< Type >, Util::DMatrixParam< Type >, Util::End, Util::FArrayParam< Type, N >, Util::ParamComposite, Util::ScalarParam< Type >, and Util::TextComposite.
Referenced by serialize().
virtual void Util::ParamComponent::resetParam () [inline, virtual]
Nontrivial implementation provided by ParamComposite subclass.
This empty default implementation is used by all leaf nodes.
Reimplemented in Util::Begin, Util::End, Util::ParamComposite, and Util::TextComposite.
Definition at line 57 of file ParamComponent.h.
void Util::ParamComponent::setIndent (const ParamComponent & parent, bool next = true)
Set indent level.
If next=true (default) set indent level one higher than that of parent. If next=false, set the same as parent.
Parameters:
parent parent ParamComponent object
next If true, set level one higher than for parent.
Definition at line 52 of file ParamComponent.cpp.
References indent().
Referenced by Util::ParamComposite::add(), Util::ParamComposite::addBegin(), Util::ParamComposite::addCArray(), Util::ParamComposite::addCArray2D(), Util::ParamComposite::addDArray(), Util::ParamComposite::addDMatrix(), Util::ParamComposite::addEnd(), Util::ParamComposite::addFArray(), Util::ParamComposite::addParamComposite(), Util::Factory< Data >::readObject(), Inter::CompositeBond< BareBond, BarePair >::readParam(), and Inter::CompensatedPair< BarePair, LinkPotential >::readParam().
std::string Util::ParamComponent::indent () const
Return indent string for this object (string of spaces).
Definition at line 46 of file ParamComponent.cpp.
Referenced by setIndent(), Util::TextComposite::writeParam(), Util::End::writeParam(), and Util::Begin::writeParam().
void Util::ParamComponent::setParamCommunicator (MPI::Intracomm & communicator)
Set an MPI communicator for parameter IO.
Reimplemented in McMd::Simulation.
Definition at line 62 of file ParamComponent.cpp.
References Util::MpiFileIo::setCommunicator().
Referenced by Util::ParamComposite::add(), Util::ParamComposite::addBegin(), Util::ParamComposite::addBlank(), Util::ParamComposite::addCArray(), Util::ParamComposite::addCArray2D(), Util::ParamComposite::addDArray(), Util::ParamComposite::addDMatrix(), Util::ParamComposite::addEnd(), Util::ParamComposite::addFArray(), Util::ParamComposite::addParamComposite(), and McMd::Simulation::setParamCommunicator().
template<class Archive > void Util::ParamComponent::serialize (Archive & ar, const unsigned int version)
Serialize this ParamComponent as a string.
Parameters:
ar saving or loading archive
version version id for archive
Reimplemented in Util::AutoCorr< Data, Product >, Util::AutoCorrArray< Data, Product >, Util::Average, Util::Distribution, Util::IntDistribution, Util::MeanSqDispArray< Data >, Util::RadialDistribution, Util::Random, McMd::Diagnostic, McMd::McEnergyAverage, McMd::McExternalEnergyAverage, McMd::McIntraBondStressAutoCorr, McMd::McIntraBondTensorAutoCorr, McMd::McPairEnergyAverage, McMd::McStressAutoCorr, McMd::MdIntraBondStressAutoCorr, McMd::MdIntraBondTensorAutoCorr, McMd::MdKineticEnergyAverage, McMd::MdPairEnergyCoefficients, McMd::MdPotentialEnergyAverage, McMd::AtomMSD, McMd::BlockRadiusGyration, McMd::BondLengthDist, McMd::BoundaryAverage, McMd::ComMSD, McMd::DumpConfig, McMd::IntraBondStressAutoCorr< SystemType >, McMd::IntraBondTensorAutoCorr< SystemType >, McMd::IntraPairAutoCorr, McMd::IntraStructureFactor, McMd::LinearRouseAutoCorr, McMd::MigratingVanHove, McMd::PressureAverage< SystemType >, McMd::RadiusGyration, McMd::RDF, McMd::StructureFactor, McMd::StructureFactorP, McMd::VanHove, McMd::McSimulation, McMd::MdSimulation, McMd::System, Util::AutoCorr< Tensor, double >, Util::AutoCorr< double, double >, Util::AutoCorr< std::complex< double >, std::complex< double > >, Util::AutoCorrArray< Tensor, double >, Util::AutoCorrArray< Vector, double >, Util::MeanSqDispArray< Vector >, McMd::IntraBondStressAutoCorr< MdSystem >, McMd::IntraBondStressAutoCorr< McSystem >, McMd::IntraBondTensorAutoCorr< MdSystem >, McMd::IntraBondTensorAutoCorr< McSystem >, McMd::PressureAverage< MdSystem >, and McMd::PressureAverage< McSystem >.
Definition at line 178 of file ParamComponent.h.
References readParam(), and writeParam().
void Util::ParamComponent::initStatic () [static]
Initialize static echo member to false.
Reimplemented in McMd::Diagnostic, and DdMd::Diagnostic.
Definition at line 86 of file ParamComponent.cpp.
Referenced by Util::initStatic().
void Util::ParamComponent::setEcho (bool echo = true) [static]
Set echo parameter to true enable echoing, or false to disable.
Definition at line 71 of file ParamComponent.cpp.
References echo().
Referenced by DdMd::Simulation::setOptions(), McMd::MdSimulation::setOptions(), and McMd::McSimulation::setOptions().
bool Util::ParamComponent::echo () [static]
Get echo parameter.
true = echoing enabled, false = disable.
Definition at line 77 of file ParamComponent.cpp.
Referenced by Util::Factory< Data >::readObject(), Util::ScalarParam< Type >::readParam(), McMd::McMoveManager::readParam(), Util::Manager< Data >::readParam(), Util::FArrayParam< Type, N >::readParam(), Util::End::readParam(), Util::DMatrixParam< Type >::readParam(), Util::DArrayParam< Type >::readParam(), Util::CArrayParam< Type >::readParam(), Util::CArray2DParam< Type >::readParam(), Util::Blank::readParam(), Util::Begin::readParam(), and setEcho().
bool Util::ParamComponent::isParamIoProcessor () const [inline, protected]
Should this processor do parameter file IO?
Always returns true if compiled without UTIL_MPI defined.
Definition at line 132 of file ParamComponent.h.
References Util::MpiFileIo::isIoProcessor().
Referenced by McMd::MdSimulation::readCommands(), McMd::McSimulation::readCommands(), McMd::McMoveManager::readParam(), Util::End::readParam(), Util::Blank::readParam(), and Util::Begin::readParam().
bool Util::ParamComponent::hasParamCommunicator () const [inline, protected]
Has an MPI communicator been set for parameter input?
Definition at line 139 of file ParamComponent.h.
References Util::MpiFileIo::hasCommunicator().
Referenced by Util::ParamComposite::add(), Util::ParamComposite::addBegin(), Util::ParamComposite::addBlank(), Util::ParamComposite::addCArray(), Util::ParamComposite::addCArray2D(), Util::ParamComposite::addDArray(), Util::ParamComposite::addDMatrix(), Util::ParamComposite::addEnd(), Util::ParamComposite::addFArray(), Util::ParamComposite::addParamComposite(), McMd::MdSimulation::readCommands(), McMd::McSimulation::readCommands(), Util::Factory< Data >::readObject(), and McMd::Perturbation::readParameters().
MPI::Intracomm& Util::ParamComponent::paramCommunicator () const [inline, protected]
Return the parameter communicator.
Definition at line 145 of file ParamComponent.h.
References Util::MpiFileIo::communicator().
Referenced by Util::ParamComposite::add(), Util::ParamComposite::addBegin(), Util::ParamComposite::addBlank(), Util::ParamComposite::addCArray(), Util::ParamComposite::addCArray2D(), Util::ParamComposite::addDArray(), Util::ParamComposite::addDMatrix(), Util::ParamComposite::addEnd(), Util::ParamComposite::addFArray(), Util::ParamComposite::addParamComposite(), Util::Factory< Data >::readObject(), and McMd::Perturbation::readParameters().
The documentation for this class was generated from the following files:
ParamComponent.h
ParamComponent.cpp