Simpatico: McMd::Linear Class Reference
McMd::Linear Class Reference
Species
Detailed Description
A Species of linear polymers (abstract).
A linear molecule is a chain of nAtom atoms with consecutive atom indices, with nAtom - 1 bonds between neighboring atoms.
A Linear molecule may be chemically heterogeneous - different atoms and bonds in a chain may be of different types. The chemical structure of a subclass of Linear must be specified by implementing the pure virtual functions atomTypeId() and bondTypeId().
Definition at line 35 of file Linear.h.
#include <Linear.h>
Public Member Functions
Linear ()
Constructor.
virtual ~Linear ()
Destructor.
virtual void generateMolecules (int nMolecule, DArray< double > exclusionRadius, System &system, BondPotential *bondPotentialPtr, const Boundary &boundary)
Generate random molecules.
Protected Member Functions
virtual int calculateAtomTypeId (int index) const =0
Return the atom type id for a specific atom.
virtual int calculateBondTypeId (int index) const =0
Return the bond type id for a specific bond.
virtual int calculateAngleTypeId (int index) const =0
Return the angle type id for a specific angle.
virtual int calculateDihedralTypeId (int index) const =0
Return the dihedral type id for a specific dihedral.
void buildLinear ()
Build the chemical structure for a linear molecule.
Protected Attributes
int hasAngles_
Does this chain have angle potentials (0 = false, 1 = true).
int hasDihedrals_
Does this chain have dihedral potentials (0 = false, 1 = true).
Constructor & Destructor Documentation
McMd::Linear::Linear ()
Constructor.
Definition at line 28 of file Linear.cpp.
McMd::Linear::~Linear () [virtual]
Destructor.
Definition at line 42 of file Linear.cpp.
Member Function Documentation
void McMd::Linear::generateMolecules (int nMolecule, DArray< double > exclusionRadius, System & system, BondPotential * bondPotentialPtr, const Boundary & boundary) [virtual]
Generate random molecules.
Parameters:
nMolecule number of molecules to genearte
exclusionRadius array of exclusion radii for every atom type
system the System
bondPotentialPtr the bond potential
boundary the boundary to generate atoms in
Reimplemented from McMd::Species.
Definition at line 187 of file Linear.cpp.
References McMd::CellList::addAtom(), McMd::System::addMolecule(), McMd::CellList::allocate(), McMd::Molecule::atom(), McMd::Simulation::atomCapacity(), McMd::Molecule::begin(), McMd::System::boundary(), McMd::Species::capacity(), McMd::CellList::deleteAtom(), Util::OrthorhombicBoundary::distanceSq(), McMd::CellList::getNeighbors(), McMd::Molecule::id(), McMd::System::molecule(), McMd::Simulation::nAtomType(), Util::ArrayIterator< Data >::notEnd(), Util::ArrayStack< Data >::pop(), McMd::Atom::position(), McMd::Simulation::random(), Util::OrthorhombicBoundary::randomPosition(), McMd::Species::reservoir(), McMd::System::simulation(), Util::FSArray< Data, Capacity >::size(), McMd::Atom::typeId(), and UTIL_THROW.
virtual int McMd::Linear::calculateAtomTypeId (int index) const [protected, pure virtual]
Return the atom type id for a specific atom.
Implementations of this function should return a type Id for a specified atom that this is calculated from the information read by readParameters(). It is used in Linear::buildLinear() to build a chain.
Parameters:
index local atom index, in the range 0, ... , nAtom_-1
Returns:
type of the specified bond
Implemented in McMd::Homopolymer, McMd::Diblock, and McMd::HomopolymerSG.
Referenced by buildLinear().
virtual int McMd::Linear::calculateBondTypeId (int index) const [protected, pure virtual]
Return the bond type id for a specific bond.
Bond i of a linear molecule connects atom i and atom i + 1.
Parameters:
index local bond index, in the range 0, ... , nBond_ - 1
Returns:
type of the specified bond
Implemented in McMd::Homopolymer, McMd::Diblock, and McMd::HomopolymerSG.
Referenced by buildLinear().
virtual int McMd::Linear::calculateAngleTypeId (int index) const [protected, pure virtual]
Return the angle type id for a specific angle.
Angle i of a linear molecule connects atoms: i-(i+1)-(i+2).
Parameters:
index local angle index, in the range 0, ... , nAngle_ - 1
Returns:
type of the specified bond
Implemented in McMd::Homopolymer, McMd::Diblock, and McMd::HomopolymerSG.
Referenced by buildLinear().
virtual int McMd::Linear::calculateDihedralTypeId (int index) const [protected, pure virtual]
Return the dihedral type id for a specific dihedral.
Dihedral i of a ring molecule connects atoms: (i)-(i+1)-(i+2)-(i+3).
Parameters:
index local dihedral index, in the range 0, ... , nDihedral_ - 1
Returns:
type of the specified bond
Implemented in McMd::Homopolymer, McMd::Diblock, and McMd::HomopolymerSG.
Referenced by buildLinear().
void McMd::Linear::buildLinear () [protected]
Build the chemical structure for a linear molecule.
This method must be called by readSpeciesParam() after values are set for nAtom and nBond. It allocates memory, assigns atom types to all the atoms in a generic molecule, and creates SpeciesGroup<2> objects for all of the bonds.
Definition at line 48 of file Linear.cpp.
References McMd::Species::allocate(), calculateAngleTypeId(), calculateAtomTypeId(), calculateBondTypeId(), calculateDihedralTypeId(), hasAngles_, hasDihedrals_, McMd::Species::makeAngle(), McMd::Species::makeBond(), McMd::Species::makeDihedral(), McMd::Species::nAngle(), McMd::Species::nAtom(), McMd::Species::nBond(), McMd::Species::nDihedral(), McMd::Species::setAtomType(), and UTIL_THROW.
Referenced by McMd::Diblock::loadSpeciesParam(), McMd::HomopolymerSG::readSpeciesParam(), and McMd::Diblock::readSpeciesParam().
Member Data Documentation
int McMd::Linear::hasAngles_ [protected]
Does this chain have angle potentials (0 = false, 1 = true).
Definition at line 69 of file Linear.h.
Referenced by buildLinear(), McMd::Diblock::loadSpeciesParam(), McMd::Diblock::readSpeciesParam(), and McMd::Diblock::save().
int McMd::Linear::hasDihedrals_ [protected]
Does this chain have dihedral potentials (0 = false, 1 = true).
Definition at line 76 of file Linear.h.
Referenced by buildLinear(), McMd::Diblock::loadSpeciesParam(), McMd::Diblock::readSpeciesParam(), and McMd::Diblock::save().
The documentation for this class was generated from the following files:
Linear.h
Linear.cpp