Simpatico: McMd::TetherMaster Class Reference
McMd::TetherMaster Class Reference
Tethers
Detailed Description
TetherMaster keeps track of all Tether objects in a System.
A TetherMaster has a private Array of Tether objects available for use in a System, a provides methods to access and manage these objects. It provides methods to add and remove Tethers (i.e., to associate Tethers with Atoms in a system) and to access active Tethers either sequentially or via the Atoms to which they are attached.
Definition at line 41 of file TetherMaster.h.
#include <TetherMaster.h>
Public Member Functions
TetherMaster ()
Constructor.
void readParam (std::istream &in)
Read tetherCapacity and allocate.
void addTether (Atom &atom, const Vector &anchor)
Add a tether to a specific Atom.
void removeTether (const Atom &atom)
Remove the Tether associated with an Atom.
void removeTether (Tether &tether)
Remove a Tether.
void pairTethers (const Atom &atom1, const Atom &atom2)
Associate the Tethers associated with two atoms as partners.
void pairTethers (Tether &tether1, Tether &tether2)
Associate two Tethers as partners.
void transferTether (Atom &oldAtom, Atom &newAtom)
Transfer a tether from one Atom to another.
void transferTether (Tether &tether, Atom &newAtom)
Transfer a tether from one Atom to another.
bool isTethered (const Atom &atom) const
Is this atom Tethered ?
Tether & tether (const Atom &atom) const
Return the Tether associated with an Atom, if any.
Tether & tether (int id) const
Return an active tether by an internal set index.
int nTether () const
Get the total number of active Tethers.
bool isValid () const
Return true if this TetherMaster is valid, or throw an Exception.
Constructor & Destructor Documentation
McMd::TetherMaster::TetherMaster ()
Constructor.
Definition at line 22 of file TetherMaster.cpp.
Member Function Documentation
void McMd::TetherMaster::readParam (std::istream & in) [virtual]
Read tetherCapacity and allocate.
Parameters:
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 30 of file TetherMaster.cpp.
void McMd::TetherMaster::addTether (Atom & atom, const Vector & anchor)
Add a tether to a specific Atom.
Add a new tether.
The associated Tether object is taken from a reservoir of unused tethers.
Preconditions: The atom must not already be attached to a tether.
Parameters:
atom Atom object to which Tether should be attached
anchor anchor point position Vector
Definition at line 43 of file TetherMaster.cpp.
References Util::Log::file(), McMd::Atom::id(), and UTIL_THROW.
void McMd::TetherMaster::removeTether (const Atom & atom)
Remove the Tether associated with an Atom.
Remove the Tether attached to an Atom, and its partner, if any.
If the Tether has a partner, also delete the partner.
Parameters:
atom Atom to which Tether is attached.
Definition at line 195 of file TetherMaster.cpp.
References McMd::Atom::id(), and UTIL_THROW.
void McMd::TetherMaster::removeTether (Tether & tether)
Remove a Tether.
Remove a Tether, and its partner, if any.
If the Tether has a partner, also delete the partner.
Precondition: The tether must be active, i.e., attached to an Atom.
Parameters:
tether Tether object to be removed / deactivated.
Definition at line 219 of file TetherMaster.cpp.
References McMd::Tether::atom(), McMd::Tether::hasAtom(), McMd::Atom::id(), and UTIL_THROW.
void McMd::TetherMaster::pairTethers (const Atom & atom1, const Atom & atom2)
Associate the Tethers associated with two atoms as partners.
Precondition: Both atoms must already be tethered.
Parameters:
atom1 first Atom object
atom2 second Atom object
Definition at line 136 of file TetherMaster.cpp.
References McMd::Atom::id(), and UTIL_THROW.
void McMd::TetherMaster::pairTethers (Tether & tether1, Tether & tether2)
Associate two Tethers as partners.
Precondition: Both tethers must be attached to atoms.
Parameters:
tether1 first Tether object
tether2 second Tether object
Definition at line 168 of file TetherMaster.cpp.
References McMd::Tether::hasAtom(), McMd::Tether::hasPartner(), and UTIL_THROW.
void McMd::TetherMaster::transferTether (Atom & oldAtom, Atom & newAtom)
Transfer a tether from one Atom to another.
Transfer a Tether from one Atom to another.
Precondition: oldAtom must be tethered, and newAtom must not. Postcondition: oldAtom will be tethered, and newAtom will not.
Parameters:
oldAtom tethered Atom on entry, untethered on return.
newAtom untethered Atom on entry, tethered on return.
Definition at line 72 of file TetherMaster.cpp.
References McMd::Atom::id(), and UTIL_THROW.
void McMd::TetherMaster::transferTether (Tether & tether, Atom & newAtom)
Transfer a tether from one Atom to another.
Precondition: tether must be attached to an atom, and newAtom must be untethered.
Parameters:
tether Tethered object, attached to a different Atom.
newAtom untethered Atom on entry, tethered on return.
Definition at line 105 of file TetherMaster.cpp.
References McMd::Tether::atom(), McMd::Tether::hasAtom(), McMd::Atom::id(), and UTIL_THROW.
bool McMd::TetherMaster::isTethered (const Atom & atom) const [inline]
Is this atom Tethered ?
Parameters:
atom Atom object of interest.
Definition at line 232 of file TetherMaster.h.
References McMd::Atom::id().
Tether & McMd::TetherMaster::tether (const Atom & atom) const [inline]
Return the Tether associated with an Atom, if any.
Get the Tether associated with an Atom.
Precondition: The Atom must be tethered, or an Exception is thrown.
Parameters:
atom Atom object of interest.
Definition at line 238 of file TetherMaster.h.
References McMd::Atom::id().
Tether & McMd::TetherMaster::tether (int id) const [inline]
Return an active tether by an internal set index.
An "active" Tether object is one that is attached to an Atom. Pointers to all of the active Tether objects are maintained by an ArraySet < Tether > container. At any instant, this container assigns every active tether an index in the range 0 <= id < nTether, where nTether is the total number of active tethers. The index associated with any Tether in the set can change, however, whenever another Tether is removed from the set by calling removeTether().
Parameters:
id index in the range 0 <= id < nTether.
Definition at line 247 of file TetherMaster.h.
int McMd::TetherMaster::nTether () const [inline]
Get the total number of active Tethers.
Definition at line 253 of file TetherMaster.h.
bool McMd::TetherMaster::isValid () const
Return true if this TetherMaster is valid, or throw an Exception.
Definition at line 302 of file TetherMaster.cpp.
References McMd::Tether::atom(), McMd::Tether::hasAtom(), McMd::Tether::hasPartner(), McMd::Atom::id(), McMd::Tether::partner(), and UTIL_THROW.
The documentation for this class was generated from the following files:
TetherMaster.h
TetherMaster.cpp