Simpatico: Util::ScalarParam< Type > Class Template Reference
Util::ScalarParam< Type > Class Template Reference
Util namespace » Parameter File IO
Detailed Description
template<class Type>
class Util::ScalarParam< Type >
Template for a Parameter object associated with a scalar variable.
This template can be used to define a Parameter subclass for any data type for which there exist inserter (<<) and extractor (>>) operators for stream io.
Definition at line 34 of file ScalarParam.h.
#include <ScalarParam.h>
Public Member Functions
ScalarParam (const char *label, Type &value, bool isRequired=true)
Constructor.
void writeParam (std::ostream &out)
Write parameter to stream.
void setValue (Type &value)
Set the pointer to point a specific variable.
Public Member Functions inherited from Util::Parameter
Parameter (const char *label, bool isRequired=true)
Constructor.
virtual ~Parameter ()
Destructor.
virtual void readParam (std::istream &in)
Read a label and (if the label matches) a parameter value.
virtual void load (Serializable::IArchive &ar)
Load from an archive.
virtual void save (Serializable::OArchive &ar)
Save to an archive.
std::string label () const
Return label string.
bool isRequired () const
Is this an optional parameter?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
virtual void resetParam ()
Nontrivial implementation provided by ParamComposite subclass.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
virtual void readValue (std::istream &in)
Read parameter value from an input stream.
virtual void loadValue (Serializable::IArchive &ar)
Load bare parameter value from an archive.
virtual void saveValue (Serializable::OArchive &ar)
Save parameter value to an archive.
virtual void bcastValue ()
Broadcast parameter value within the ioCommunicator.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::Parameter
template<class Type >
static void saveOptional (Serializable::OArchive &ar, Type &value, bool isActive)
Save an optional parameter value to an output archive.
template<class Type >
static void saveOptionalCArray (Serializable::OArchive &ar, Type *ptr, int n, bool isActive)
Save an optional C-array of n values to an output archive.
template<class Type >
static void saveOptionalCArray2D (Serializable::OArchive &ar, Type *ptr, int m, int n, int np, bool isActive)
Save an optional two-dimensional C array to an output archive.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Public Attributes inherited from Util::Parameter
static const int Width = 20
Width of output field for a scalar variable.
static const int Precision = 12
Precision for io of floating point data field.
Protected Attributes inherited from Util::Parameter
Label label_
Label object that contains parameter label string.
bool isActive_
Is this parameter active (always true if isRequired).
Constructor & Destructor Documentation
template<class Type > Util::ScalarParam< Type >::ScalarParam (const char * label, Type & value, bool isRequired = true)
Constructor.
Parameters
label label string const.
value reference to parameter value.
isRequired Is this a required parameter?
Definition at line 111 of file ScalarParam.h.
Member Function Documentation
template<class Type > void Util::ScalarParam< Type >::writeParam (std::ostream & out) virtual
Write parameter to stream.
Parameters
out output stream
Implements Util::ParamComponent.
Definition at line 139 of file ScalarParam.h.
References Util::ParamComponent::indent(), Util::Parameter::isActive(), Util::Parameter::label_, Util::Parameter::Precision, and Util::Parameter::Width.
template<class Type > void Util::ScalarParam< Type >::setValue (Type & value)
Set the pointer to point a specific variable.
Parameters
value variable that holds the parameter value.
Definition at line 155 of file ScalarParam.h.
template<class Type > void Util::ScalarParam< Type >::readValue (std::istream & in) protected virtual
Read parameter value from an input stream.
Parameters
in input stream from which to read
Reimplemented from Util::Parameter.
Definition at line 118 of file ScalarParam.h.
template<class Type > void Util::ScalarParam< Type >::loadValue (Serializable::IArchive & ar) protected virtual
Load bare parameter value from an archive.
Parameters
ar input archive from which to load
Reimplemented from Util::Parameter.
Definition at line 122 of file ScalarParam.h.
template<class Type > void Util::ScalarParam< Type >::saveValue (Serializable::OArchive & ar) protected virtual
Save parameter value to an archive.
Parameters
ar output archive to which to save
Reimplemented from Util::Parameter.
Definition at line 126 of file ScalarParam.h.
template<class Type > void Util::ScalarParam< Type >::bcastValue () protected virtual
Broadcast parameter value within the ioCommunicator.
Reimplemented from Util::Parameter.
Definition at line 131 of file ScalarParam.h.
References Util::MpiFileIo::ioCommunicator().
The documentation for this class was generated from the following file:
ScalarParam.h