Simpatico: McMd::DumpConfig Class Reference
McMd::DumpConfig Class Reference
Diagnostics
Detailed Description
Periodically dump system configuration to a new file.
This class uses the System::writeConfig() method to write the entire system configuration periodically, at interval read from file. Names of configuration dump files are constructed by concatenating the System outputPrefix, a dumpPrefix, the literal string "config.", and an integer that is incremented after each dump. The dump prefix is a string that is read by the read() method of this class. For example, if System::outputPrefix is "out/" and dumpPrefix is "dump/", the configurations will be written to files "out/dump/config.0", "out/dump/config.1", etc.
Definition at line 34 of file DumpConfig.h.
#include <DumpConfig.h>
Public Member Functions
DumpConfig (System &system)
Constructor.
virtual ~DumpConfig ()
Destructor.
virtual void readParameters (std::istream &in)
Read dumpPrefix and interval.
virtual void save (Serializable::OArchive &ar)
Save state to archive.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Clear nSample counter.
virtual void sample (long iStep)
Dump configuration to file.
Constructor & Destructor Documentation
McMd::DumpConfig::DumpConfig (System & system)
Constructor.
Parameters:
system parent System object.
Definition at line 26 of file DumpConfig.cpp.
References Util::ParamComposite::setClassName().
virtual McMd::DumpConfig::~DumpConfig () [inline, virtual]
Destructor.
Definition at line 49 of file DumpConfig.h.
Member Function Documentation
void McMd::DumpConfig::readParameters (std::istream & in) [virtual]
Read dumpPrefix and interval.
Parameters:
in input parameter file
Reimplemented from McMd::Diagnostic.
Definition at line 35 of file DumpConfig.cpp.
References McMd::Diagnostic::readInterval(), and McMd::Diagnostic::readOutputFileName().
void McMd::DumpConfig::save (Serializable::OArchive & ar) [virtual]
Save state to archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 55 of file DumpConfig.cpp.
void McMd::DumpConfig::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 45 of file DumpConfig.cpp.
template<class Archive > void McMd::DumpConfig::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Diagnostic.
Definition at line 111 of file DumpConfig.h.
References McMd::serialize().
void McMd::DumpConfig::setup () [virtual]
Clear nSample counter.
Reimplemented from McMd::Diagnostic.
Definition at line 61 of file DumpConfig.cpp.
void McMd::DumpConfig::sample (long iStep) [virtual]
Dump configuration to file.
Parameters:
iStep MC step index
Implements McMd::Diagnostic.
Definition at line 67 of file DumpConfig.cpp.
References McMd::Diagnostic::fileMaster(), McMd::Diagnostic::isAtInterval(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), McMd::SystemDiagnostic< System >::system(), Util::toString(), and McMd::System::writeConfig().
The documentation for this class was generated from the following files:
DumpConfig.h
DumpConfig.cpp