Simpatico: McMd::MdKineticEnergyAverage Class Reference
McMd::MdKineticEnergyAverage Class Reference
Analyzers
Detailed Description
MdKineticEnergyAverage averages of total kinetic energy.
Definition at line 27 of file MdKineticEnergyAverage.h.
#include <MdKineticEnergyAverage.h>
Public Member Functions
MdKineticEnergyAverage (MdSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters and initialize.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Clear accumulator.
virtual void sample (long iStep)
Calculate, analyze and/or output a physical quantity.
virtual void output ()
Output results at end of simulation.
Constructor & Destructor Documentation
McMd::MdKineticEnergyAverage::MdKineticEnergyAverage (MdSystem & system)
Constructor.
Definition at line 25 of file MdKineticEnergyAverage.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::MdKineticEnergyAverage::readParameters (std::istream & in) [virtual]
Read parameters and initialize.
Reimplemented from McMd::Analyzer.
Definition at line 35 of file MdKineticEnergyAverage.cpp.
References McMd::Analyzer::fileMaster(), Util::Average::nSamplePerBlock(), Util::FileMaster::openOutputFile(), McMd::Analyzer::outputFileName(), McMd::Analyzer::readInterval(), McMd::Analyzer::readOutputFileName(), and Util::Average::setNSamplePerBlock().
void McMd::MdKineticEnergyAverage::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::Analyzer.
Definition at line 53 of file MdKineticEnergyAverage.cpp.
References McMd::Analyzer::fileMaster(), McMd::Analyzer::loadInterval(), McMd::Analyzer::loadOutputFileName(), Util::FileMaster::openOutputFile(), and McMd::Analyzer::outputFileName().
void McMd::MdKineticEnergyAverage::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::Analyzer.
Definition at line 70 of file MdKineticEnergyAverage.cpp.
template<class Archive > void McMd::MdKineticEnergyAverage::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Analyzer.
Definition at line 100 of file MdKineticEnergyAverage.h.
References McMd::serialize().
void McMd::MdKineticEnergyAverage::setup () [virtual]
Clear accumulator.
Reimplemented from McMd::Analyzer.
Definition at line 76 of file MdKineticEnergyAverage.cpp.
References Util::Average::clear().
void McMd::MdKineticEnergyAverage::sample (long iStep) [virtual]
Calculate, analyze and/or output a physical quantity.
Take an action if iStep is a multiple of interval. If iStep is not a multiple of interval, this method should do nothing and return immediately.
Parameters:
iStep current simulation step index.
Implements McMd::Analyzer.
Definition at line 82 of file MdKineticEnergyAverage.cpp.
References McMd::Analyzer::isAtInterval(), Util::Average::sample(), and McMd::SystemAnalyzer< MdSystem >::system().
void McMd::MdKineticEnergyAverage::output () [virtual]
Output results at end of simulation.
Reimplemented from McMd::Analyzer.
Definition at line 92 of file MdKineticEnergyAverage.cpp.
References McMd::Analyzer::fileMaster(), Util::Average::nSamplePerBlock(), Util::FileMaster::openOutputFile(), Util::Average::output(), McMd::Analyzer::outputFileName(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
MdKineticEnergyAverage.h
MdKineticEnergyAverage.cpp