Simpatico: Util::DArrayParam< Type > Class Template Reference
Util::DArrayParam< Type > Class Template Reference
Parameter File IO
Detailed Description
template<class Type>
class Util::DArrayParam< Type >
A Parameter associated with a DArray container.
Definition at line 28 of file DArrayParam.h.
#include <DArrayParam.h>
Public Member Functions
void readParam (std::istream &in)
Read parameter from stream.
void writeParam (std::ostream &out)
Write parameter to stream.
void load (Serializable::IArchive &ar)
Load from an archive.
void save (Serializable::OArchive &ar)
Save to an archive.
Protected Attributes
DArray< Type > * arrayPtr_
Pointer to associated DArray.
int n_
Logical array dimension.
Member Function Documentation
template<class Type > void Util::DArrayParam< Type >::readParam (std::istream & in) [virtual]
Read parameter from stream.
Parameters:
in input stream
Implements Util::ParamComponent.
Definition at line 90 of file DArrayParam.h.
References Util::ParamComponent::echo(), Util::Log::file(), and UTIL_THROW.
Referenced by Util::ParamComposite::readDArray().
template<class Type > void Util::DArrayParam< Type >::writeParam (std::ostream & out) [virtual]
Write parameter to stream.
Parameters:
out output stream
Implements Util::ParamComponent.
Definition at line 121 of file DArrayParam.h.
References Util::Parameter::Precision, UTIL_THROW, and Util::Parameter::Width.
template<class Type > void Util::DArrayParam< Type >::load (Serializable::IArchive & ar) [virtual]
Load from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from Util::ParamComponent.
Definition at line 152 of file DArrayParam.h.
References Util::ParamComponent::echo(), Util::Log::file(), and UTIL_THROW.
Referenced by Util::ParamComposite::loadDArray().
template<class Type > void Util::DArrayParam< Type >::save (Serializable::OArchive & ar) [virtual]
Save to an archive.
Parameters:
ar saving (output) archive.
Reimplemented from Util::ParamComponent.
Definition at line 174 of file DArrayParam.h.
References UTIL_THROW.
Member Data Documentation
template<class Type> DArray<Type>* Util::DArrayParam< Type >::arrayPtr_ [protected]
Pointer to associated DArray.
Definition at line 69 of file DArrayParam.h.
template<class Type> int Util::DArrayParam< Type >::n_ [protected]
Logical array dimension.
Definition at line 72 of file DArrayParam.h.
The documentation for this class was generated from the following file:
DArrayParam.h