Simpatico: DdMd::AnglePotentialImpl< Interaction > Class Template Reference
DdMd::AnglePotentialImpl< Interaction > Class Template Reference
Angle Potentials
Detailed Description
template<class Interaction>
class DdMd::AnglePotentialImpl< Interaction >
Implementation template for a AnglePotential.
Definition at line 33 of file ddMd/potentials/angle/AnglePotentialImpl.h.
#include <AnglePotentialImpl.h>
Public Member Functions
AnglePotentialImpl (Simulation &simulation)
Constructor.
AnglePotentialImpl ()
Default constructor.
virtual ~AnglePotentialImpl ()
Destructor.
virtual void setNAngleType (int nAtomType)
Set the maximum number of atom types.
virtual void readParameters (std::istream &in)
Read potential energy parameters.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
Interaction interface
double angleEnergy (double cosTheta, int type) const
Returns potential energy for one angle.
void angleForce (const Vector &R1, const Vector &R2, Vector &F1, Vector &F2, int type) const
Returns forces along two bonds at the angle, for use in MD and stress calculation.
void set (std::string name, int type, double value)
Modify an angle parameter, identified by a string.
double get (std::string name, int type) const
Get a parameter value, identified by a string.
virtual std::string interactionClassName () const
Return pair interaction class name (e.g., "CosineAngle").
const Interaction & interaction () const
Return angle interaction by const reference.
Interaction & interaction ()
Return angle interaction by reference.
Total Energy, Force and Stress
virtual void computeForces ()
Compute angle forces for atoms.
virtual void computeEnergy (MPI::Intracomm &communicator)
Compute the total angle energy for all processors.
virtual void computeStress (MPI::Intracomm &communicator)
Compute the covalent bond stress.
Constructor & Destructor Documentation
template<class Interaction > DdMd::AnglePotentialImpl< Interaction >::AnglePotentialImpl (Simulation & simulation)
Constructor.
Definition at line 209 of file ddMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > DdMd::AnglePotentialImpl< Interaction >::AnglePotentialImpl ()
Default constructor.
Definition at line 218 of file ddMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > DdMd::AnglePotentialImpl< Interaction >::~AnglePotentialImpl () [virtual]
Destructor.
Definition at line 227 of file ddMd/potentials/angle/AnglePotentialImpl.h.
Member Function Documentation
template<class Interaction > void DdMd::AnglePotentialImpl< Interaction >::setNAngleType (int nAtomType) [virtual]
Set the maximum number of atom types.
Implements DdMd::AnglePotential.
Definition at line 238 of file ddMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > void DdMd::AnglePotentialImpl< Interaction >::readParameters (std::istream & in) [virtual]
Read potential energy parameters.
This method reads the angle potential Interaction parameter block. Before calling Interaction::readParameters(), it passes simulation().nAngleType() to Interaction::setNAtomType().
Reimplemented from Util::ParamComposite.
Definition at line 245 of file ddMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > void DdMd::AnglePotentialImpl< Interaction >::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Precondition: setNAngleType must have been called before this.
Parameters:
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 257 of file ddMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > void DdMd::AnglePotentialImpl< Interaction >::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 268 of file ddMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > double DdMd::AnglePotentialImpl< Interaction >::angleEnergy (double cosTheta, int type) const
Returns potential energy for one angle.
Parameters:
cosTheta cosine of the bend angle
type type index of angle group
Reimplemented from DdMd::AnglePotential.
Definition at line 276 of file ddMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > void DdMd::AnglePotentialImpl< Interaction >::angleForce (const Vector & R1, const Vector & R2, Vector & F1, Vector & F2, int type) const
Returns forces along two bonds at the angle, for use in MD and stress calculation.
Parameters:
R1 bond vector from atom 1 to 2
R2 bond vector from atom 2 to 3
F1 return force along R1 direction
F2 return force along R2 direction
type type index for angle group
Reimplemented from DdMd::AnglePotential.
Definition at line 284 of file ddMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction> void DdMd::AnglePotentialImpl< Interaction >::set (std::string name, int type, double value) [inline, virtual]
Modify an angle parameter, identified by a string.
Parameters:
name parameter variable name
type type index for angle group
value new value of parameter
Implements DdMd::AnglePotential.
Definition at line 114 of file ddMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction> double DdMd::AnglePotentialImpl< Interaction >::get (std::string name, int type) const [inline, virtual]
Get a parameter value, identified by a string.
Parameters:
name parameter variable name
type type index of angle group
Implements DdMd::AnglePotential.
Definition at line 123 of file ddMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > std::string DdMd::AnglePotentialImpl< Interaction >::interactionClassName () const [virtual]
Return pair interaction class name (e.g., "CosineAngle").
Implements DdMd::AnglePotential.
Definition at line 294 of file ddMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > const Interaction & DdMd::AnglePotentialImpl< Interaction >::interaction () const [inline]
Return angle interaction by const reference.
Get Interaction by const reference.
Definition at line 308 of file ddMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > Interaction & DdMd::AnglePotentialImpl< Interaction >::interaction () [inline]
Return angle interaction by reference.
Get Interaction by reference.
Definition at line 301 of file ddMd/potentials/angle/AnglePotentialImpl.h.
template<class Interaction > void DdMd::AnglePotentialImpl< Interaction >::computeForces () [virtual]
Compute angle forces for atoms.
Adds angle forces to existing Atom forces.
Implements DdMd::Potential.
Definition at line 315 of file ddMd/potentials/angle/AnglePotentialImpl.h.
References DdMd::Atom::force(), DdMd::Atom::isGhost(), Util::PArrayIterator< Group< N > >::notEnd(), and DdMd::Atom::position().
template<class Interaction > void DdMd::AnglePotentialImpl< Interaction >::computeEnergy (MPI::Intracomm & communicator) [virtual]
Compute the total angle energy for all processors.
Call on all processors (MPI reduce operation).
Implements DdMd::Potential.
Definition at line 358 of file ddMd/potentials/angle/AnglePotentialImpl.h.
References Util::Vector::dot(), DdMd::Atom::isGhost(), Util::PArrayIterator< Group< N > >::notEnd(), and DdMd::Atom::position().
template<class Interaction > void DdMd::AnglePotentialImpl< Interaction >::computeStress (MPI::Intracomm & communicator) [virtual]
Compute the covalent bond stress.
Call on all processors.
Reimplemented from DdMd::Potential.
Definition at line 409 of file ddMd/potentials/angle/AnglePotentialImpl.h.
References DdMd::Atom::isGhost(), Util::PArrayIterator< Group< N > >::notEnd(), DdMd::Atom::position(), and Util::Tensor::zero().
The documentation for this class was generated from the following file:
ddMd/potentials/angle/AnglePotentialImpl.h