Simpatico: McMd::IntraStructureFactorGrid Class Reference
McMd::IntraStructureFactorGrid Class Reference
Diagnostics
Detailed Description
IntraStructureFactorGrid evaluates structure factors in Fourier space.
This class evaluates the intramolecular contribution to the structures factor for all wavevectors within a grid, within a region in which all of the h, k, l integer wavevector components (i.e., Miller indices) has an absolute magnitude less than or equal to a parameter hMax.
The class also requires a user to specify a variable lattice of enum type LatticeSystem whose value (e.g., Cubic, Orthorhombic, Triclinic) determines the symmetry group that is used to group group equivalent wavevectors into "stars". Use Triclinic to impose no symmetry.
Example: Here is parameter file for a system with nAtomType = 2, with two monomer types 0 and 1, for calculating the total, 00, and 01 correlation functions on a grid with Miller indices up and including 5 for molecules of species 0:
 IntraStructureFactorGrid{
    interval                     1000
    outputFileName     IntraStructureFactorGrid
    speciesId                        0
    nAtomTypeIdPair                            3
    atomTypeIdPairs                    -1     -1
                              0      0
                              0      1
    hMax                             5
    lattice                      Cubic
 }
At the end of a simulation, all of the structure factors are output in a file with a suffix _avg.dat. Each line in this file contains the 3 Miller indices of a wavevector, the absolute magnitude of the wavevector, and a list of nAtomTypeIdPair structure factor values for the wavevector, one for each atomTypeId pair. During the simulation, at each sampling, a log file with suffix .dat containing the instantaneous values of the structure factors is appended to.
Definition at line 63 of file IntraStructureFactorGrid.h.
#include <IntraStructureFactorGrid.h>
Public Member Functions
IntraStructureFactorGrid (System &system)
Constructor.
~IntraStructureFactorGrid ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Set up before a simulation.
virtual void output ()
Output structure factors, averaged over stars.
virtual void sample (long iStep)
Add particles to StructureFactor accumulators.
Constructor & Destructor Documentation
McMd::IntraStructureFactorGrid::IntraStructureFactorGrid (System & system)
Constructor.
Parameters:
system reference to parent System object
Definition at line 25 of file IntraStructureFactorGrid.cpp.
References Util::ParamComposite::setClassName().
McMd::IntraStructureFactorGrid::~IntraStructureFactorGrid ()
Destructor.
Definition at line 37 of file IntraStructureFactorGrid.cpp.
Member Function Documentation
void McMd::IntraStructureFactorGrid::readParameters (std::istream & in) [virtual]
Read parameters from file.
Input format:
int interval sampling interval
int speciesId species identifier
string outputFileName output file base name
int nAtomTypeIdPair number of atomTypeIdPairs
DArray< Pair<int> > atomTypeIdPairs atomTypeIdPair vectors
int hMax maximum Miller index
Parameters:
in input parameter stream
Reimplemented from McMd::IntraStructureFactor.
Definition at line 43 of file IntraStructureFactorGrid.cpp.
References Util::SymmetryGroup< Symmetry >::add(), Util::DMatrix< Data >::allocate(), Util::DArray< Data >::allocate(), McMd::IntraStructureFactor::fourierModes_, Util::SymmetryGroup< Symmetry >::makeCompleteGroup(), Util::PointGroup::makeStar(), McMd::Simulation::nAtomType(), McMd::IntraStructureFactor::nAtomType_, McMd::IntraStructureFactor::nAtomTypeIdPair_, McMd::IntraStructureFactor::nSample_, McMd::IntraStructureFactor::nWave_, Util::PointSymmetry::R(), McMd::Diagnostic::readInterval(), McMd::Diagnostic::readOutputFileName(), McMd::System::simulation(), Util::FSArray< Data, Capacity >::size(), McMd::IntraStructureFactor::speciesId_, McMd::IntraStructureFactor::structureFactorDelta_, McMd::IntraStructureFactor::structureFactors_, McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::IntraStructureFactorGrid::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from McMd::IntraStructureFactor.
Definition at line 191 of file IntraStructureFactorGrid.cpp.
References Util::DMatrix< Data >::allocate(), Util::DArray< Data >::allocate(), McMd::IntraStructureFactor::fourierModes_, McMd::IntraStructureFactor::nAtomType_, McMd::IntraStructureFactor::nAtomTypeIdPair_, McMd::IntraStructureFactor::nSample_, McMd::IntraStructureFactor::nWave_, McMd::IntraStructureFactor::structureFactors_, McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::IntraStructureFactorGrid::save (Serializable::OArchive & ar) [virtual]
Save state to archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::IntraStructureFactor.
Definition at line 234 of file IntraStructureFactorGrid.cpp.
template<class Archive > void McMd::IntraStructureFactorGrid::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::IntraStructureFactor.
Definition at line 168 of file IntraStructureFactorGrid.h.
References McMd::serialize().
void McMd::IntraStructureFactorGrid::setup () [virtual]
Set up before a simulation.
Reimplemented from McMd::IntraStructureFactor.
Definition at line 237 of file IntraStructureFactorGrid.cpp.
void McMd::IntraStructureFactorGrid::output () [virtual]
Output structure factors, averaged over stars.
Reimplemented from McMd::IntraStructureFactor.
Definition at line 276 of file IntraStructureFactorGrid.cpp.
References Util::Dimension, McMd::Diagnostic::fileMaster(), McMd::IntraStructureFactor::nAtomTypeIdPair_, McMd::IntraStructureFactor::nSample_, Util::FileMaster::openOutputFile(), McMd::IntraStructureFactor::outputFile_, McMd::Diagnostic::outputFileName(), McMd::IntraStructureFactor::structureFactors_, and Util::ParamComposite::writeParam().
void McMd::IntraStructureFactorGrid::sample (long iStep) [virtual]
Add particles to StructureFactor accumulators.
Parameters:
iStep step counter
Reimplemented from McMd::IntraStructureFactor.
Definition at line 241 of file IntraStructureFactorGrid.cpp.
References Util::Dimension, McMd::Diagnostic::fileMaster(), McMd::IntraStructureFactor::nAtomTypeIdPair_, Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), and McMd::IntraStructureFactor::structureFactorDelta_.
The documentation for this class was generated from the following files:
IntraStructureFactorGrid.h
IntraStructureFactorGrid.cpp