Simpatico: McMd::SystemMove Class Reference
McMd::SystemMove Class Reference
Monte Carlo Moves
Detailed Description
An McMove that acts on one McSystem.
Definition at line 27 of file SystemMove.h.
#include <SystemMove.h>
Public Member Functions
SystemMove (McSystem &system)
Constructor.
virtual ~SystemMove ()
Destructor.
Protected Member Functions
McSystem & system ()
Get parent McSystem.
Boundary & boundary ()
Get Boundary object of parent McSystem.
EnergyEnsemble & energyEnsemble ()
Get EnergyEnsemble object of parent McSystem.
double boltzmann (double energy)
Boltzmann weight associated with an energy difference.
Constructor & Destructor Documentation
McMd::SystemMove::SystemMove (McSystem & system)
Constructor.
Parameters:
system parent McSystem
Definition at line 23 of file SystemMove.cpp.
References McMd::System::energyEnsemble().
McMd::SystemMove::~SystemMove () [virtual]
Destructor.
Definition at line 34 of file SystemMove.cpp.
Member Function Documentation
McSystem & McMd::SystemMove::system () [inline, protected]
Get parent McSystem.
Definition at line 81 of file SystemMove.h.
Referenced by McMd::CfbEndBase::addEndAtom(), McMd::CfbRebridgeBase::addMiddleAtom(), McMd::CfbRebridgeBase::addSequence(), McMd::CfbEndBase::deleteEndAtom(), McMd::CfbRebridgeBase::deleteMiddleAtom(), McMd::CfbRebridgeBase::deleteSequence(), McMd::RingTetraRebridgeMove::loadParameters(), McMd::RingTetraRebridgeMove::move(), McMd::AtomDisplaceMove::move(), McMd::CfbDoubleRebridgeMove::move(), McMd::CfbEndMove::move(), McMd::CfbRebridgeMove::move(), McMd::RingOctaRebridgeMove::move(), McMd::HomopolymerSemiGrandMove::move(), McMd::EndSwapMove::move(), McMd::CfbRingRebridgeMove::move(), McMd::HybridMdMove::move(), McMd::CfbReptationMove::move(), McMd::HybridNphMdMove::move(), McMd::RigidDisplaceMove::move(), McMd::MdMove::move(), McMd::DpdMove::move(), McMd::GroupRebridgeBase::octaEnergy(), McMd::CfbReptationMove::output(), McMd::RingTetraRebridgeMove::readParameters(), McMd::RingOctaRebridgeMove::scanBridge(), McMd::RingTetraRebridgeMove::scanBridge(), and McMd::GroupRebridgeBase::tetraEnergy().
Boundary & McMd::SystemMove::boundary () [inline, protected]
Get Boundary object of parent McSystem.
Definition at line 87 of file SystemMove.h.
Referenced by McMd::CfbEndBase::addEndAtom(), McMd::CfbRebridgeBase::addMiddleAtom(), McMd::CfbEndBase::deleteEndAtom(), McMd::CfbRebridgeBase::deleteMiddleAtom(), McMd::AtomDisplaceMove::move(), McMd::RigidDisplaceMove::move(), McMd::GroupRebridgeBase::octaEnergy(), McMd::RingOctaRebridgeMove::scanBridge(), McMd::RingTetraRebridgeMove::scanBridge(), and McMd::GroupRebridgeBase::tetraEnergy().
EnergyEnsemble & McMd::SystemMove::energyEnsemble () [inline, protected]
Get EnergyEnsemble object of parent McSystem.
Definition at line 93 of file SystemMove.h.
Referenced by McMd::CfbEndBase::addEndAtom(), McMd::CfbRebridgeBase::addMiddleAtom(), McMd::HybridMdMove::move(), McMd::HybridNphMdMove::move(), and McMd::MdMove::move().
double McMd::SystemMove::boltzmann (double energy) [inline, protected]
Boltzmann weight associated with an energy difference.
Parameters:
energy energy or energy difference.
Returns:
Boltzmann weight exp(-beta*energy)
Definition at line 99 of file SystemMove.h.
Referenced by McMd::CfbEndBase::addEndAtom(), McMd::CfbRebridgeBase::addMiddleAtom(), McMd::CfbEndBase::deleteEndAtom(), McMd::CfbRebridgeBase::deleteMiddleAtom(), McMd::RingTetraRebridgeMove::move(), McMd::AtomDisplaceMove::move(), McMd::RingOctaRebridgeMove::move(), McMd::HomopolymerSemiGrandMove::move(), McMd::EndSwapMove::move(), McMd::HybridMdMove::move(), McMd::RigidDisplaceMove::move(), and McMd::HybridNphMdMove::move().
The documentation for this class was generated from the following files:
SystemMove.h
SystemMove.cpp