Simpatico: DdMd::DdMdConfigIo Class Reference
DdMd::DdMdConfigIo Class Reference
ConfigIos
Detailed Description
Native / default format for configuration files.
DdMdConfigIo is a ConfigIo that implements the default configuration file format for ddSim.
Definition at line 28 of file ddMd/configIos/DdMdConfigIo.h.
#include <DdMdConfigIo.h>
Public Member Functions
DdMdConfigIo ()
Default constructor.
DdMdConfigIo (Simulation &simulation)
Constructor.
virtual void readConfig (std::istream &file, MaskPolicy maskPolicy)
Read configuration file.
virtual void writeConfig (std::ostream &file)
Write configuration file.
Constructor & Destructor Documentation
DdMd::DdMdConfigIo::DdMdConfigIo ()
Default constructor.
Definition at line 45 of file ddMd/configIos/DdMdConfigIo.cpp.
DdMd::DdMdConfigIo::DdMdConfigIo (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object.
Definition at line 52 of file ddMd/configIos/DdMdConfigIo.cpp.
Member Function Documentation
void DdMd::DdMdConfigIo::readConfig (std::istream & file, MaskPolicy maskPolicy) [virtual]
Read configuration file.
This routine opens and reads a file on the master, and distributes atom data among the processors.
Parameters:
file input file stream
maskPolicy MaskPolicy to be used in setting atom masks
Implements DdMd::ConfigIo.
Definition at line 92 of file ddMd/configIos/DdMdConfigIo.cpp.
References DdMd::AtomDistributor::addAtom(), DdMd::ConfigIo::atomDistributor(), DdMd::ConfigIo::atomStorage(), Util::bcast(), DdMd::ConfigIo::bondDistributor(), DdMd::ConfigIo::bondStorage(), DdMd::ConfigIo::boundary(), DdMd::Domain::communicator(), DdMd::ConfigIo::domain(), DdMd::GroupStorage< N >::isValid(), DdMd::AtomStorage::nAtom(), DdMd::AtomDistributor::newAtomPtr(), DdMd::Atom::position(), DdMd::AtomDistributor::receive(), DdMd::AtomDistributor::send(), DdMd::ConfigIo::setAtomMasks(), DdMd::Atom::setId(), DdMd::Atom::setTypeId(), DdMd::AtomDistributor::setup(), DdMd::AtomStorage::totalAtomCapacity(), UTIL_THROW, and DdMd::Atom::velocity().
void DdMd::DdMdConfigIo::writeConfig (std::ostream & file) [virtual]
Write configuration file.
This routine opens and writes a file on the master, collecting atom data from all processors.
Parameters:
file output file stream
Implements DdMd::ConfigIo.
Definition at line 253 of file ddMd/configIos/DdMdConfigIo.cpp.
References DdMd::ConfigIo::atomCollector(), DdMd::ConfigIo::atomStorage(), DdMd::ConfigIo::bondCollector(), DdMd::ConfigIo::bondStorage(), DdMd::ConfigIo::boundary(), DdMd::AtomStorage::computeNAtomTotal(), DdMd::ConfigIo::domain(), DdMd::Atom::id(), DdMd::Atom::mask(), DdMd::AtomCollector::nextPtr(), DdMd::Atom::position(), DdMd::AtomCollector::send(), DdMd::AtomCollector::setup(), DdMd::Mask::size(), DdMd::Atom::typeId(), and DdMd::Atom::velocity().
The documentation for this class was generated from the following files:
ddMd/configIos/DdMdConfigIo.h
ddMd/configIos/DdMdConfigIo.cpp