Simpatico: DdMd::OutputStressTensor Class Reference
DdMd::OutputStressTensor Class Reference
Analyzers
Detailed Description
Periodically write (tensor) StressTensor to file.
Definition at line 26 of file OutputStressTensor.h.
#include <OutputStressTensor.h>
Public Member Functions
OutputStressTensor (Simulation &simulation)
Constructor.
virtual ~OutputStressTensor ()
Destructor.
virtual void readParameters (std::istream &in)
Read dumpPrefix and interval.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void clear ()
Clear nSample counter.
virtual void sample (long iStep)
Dump configuration to file.
Constructor & Destructor Documentation
DdMd::OutputStressTensor::OutputStressTensor (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object.
Definition at line 27 of file OutputStressTensor.cpp.
References Util::ParamComposite::setClassName().
virtual DdMd::OutputStressTensor::~OutputStressTensor () [inline, virtual]
Destructor.
Definition at line 41 of file OutputStressTensor.h.
Member Function Documentation
void DdMd::OutputStressTensor::readParameters (std::istream & in) [virtual]
Read dumpPrefix and interval.
Parameters:
in input parameter file
Reimplemented from Util::ParamComposite.
Definition at line 36 of file OutputStressTensor.cpp.
References DdMd::Simulation::fileMaster(), Util::FileMaster::openOutputFile(), DdMd::Analyzer::outputFileName(), DdMd::Analyzer::readInterval(), DdMd::Analyzer::readOutputFileName(), and DdMd::Analyzer::simulation().
void DdMd::OutputStressTensor::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from DdMd::Analyzer.
Definition at line 51 of file OutputStressTensor.cpp.
References DdMd::Simulation::fileMaster(), Util::MpiLoader< IArchive >::load(), DdMd::Analyzer::loadInterval(), DdMd::Analyzer::loadOutputFileName(), Util::FileMaster::openOutputFile(), DdMd::Analyzer::outputFileName(), and DdMd::Analyzer::simulation().
void DdMd::OutputStressTensor::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from DdMd::Analyzer.
Definition at line 69 of file OutputStressTensor.cpp.
References DdMd::Analyzer::saveInterval(), and DdMd::Analyzer::saveOutputFileName().
void DdMd::OutputStressTensor::clear () [virtual]
Clear nSample counter.
Reimplemented from DdMd::Analyzer.
Definition at line 80 of file OutputStressTensor.cpp.
void DdMd::OutputStressTensor::sample (long iStep) [virtual]
Dump configuration to file.
Parameters:
iStep MD step index
Implements DdMd::Analyzer.
Definition at line 86 of file OutputStressTensor.cpp.
References Util::Tensor::add(), DdMd::Simulation::computeKineticStress(), DdMd::Simulation::computeVirialStress(), DdMd::Simulation::domain(), DdMd::Analyzer::isAtInterval(), DdMd::Domain::isMaster(), DdMd::Simulation::kineticStress(), DdMd::Analyzer::simulation(), and DdMd::Simulation::virialStress().
The documentation for this class was generated from the following files:
OutputStressTensor.h
OutputStressTensor.cpp