Simpatico: DdMd::ExternalPotential Class Reference
DdMd::ExternalPotential Class Reference
External Potentials
Detailed Description
An ExternalPotential calculates exteranl forces for a parent Simulation.
Definition at line 30 of file ddMd/potentials/external/ExternalPotential.h.
#include <ExternalPotential.h>
Public Member Functions
ExternalPotential (Simulation &simulation)
Constructor.
ExternalPotential ()
Default constructor (for unit testing).
virtual void associate (Boundary &boundary, AtomStorage &storage)
Associate with related objects.
virtual ~ExternalPotential ()
Destructor.
Interaction interface
virtual void setNAtomType (int nAtomType)=0
Set the maximum number of atom types.
virtual double externalEnergy (const Vector &position, int i) const =0
Returns external potential energy of a single particle.
virtual void getExternalForce (const Vector &position, int type, Vector &force) const =0
Returns force caused by the external potential.
virtual std::string interactionClassName () const =0
Return name of interaction class (e.g., "TanhCosineExternal").
Protected Member Functions
Simulation & simulation ()
Get the parent Simulation by reference.
Boundary & boundary ()
Get the Boundary by reference.
AtomStorage & storage ()
Get the AtomStorage by reference.
Constructor & Destructor Documentation
DdMd::ExternalPotential::ExternalPotential (Simulation & simulation)
Constructor.
Definition at line 25 of file ExternalPotential.cpp.
References Util::ParamComposite::setClassName().
DdMd::ExternalPotential::ExternalPotential ()
Default constructor (for unit testing).
Definition at line 34 of file ExternalPotential.cpp.
DdMd::ExternalPotential::~ExternalPotential () [virtual]
Destructor.
Definition at line 51 of file ExternalPotential.cpp.
Member Function Documentation
void DdMd::ExternalPotential::associate (Boundary & boundary, AtomStorage & storage) [virtual]
Associate with related objects.
Call iff object instantiated with default constructor.
Parameters:
boundary associated Boundary object.
storage associated AtomStorage object.
Reimplemented in DdMd::ExternalPotentialImpl< Interaction >.
Definition at line 42 of file ExternalPotential.cpp.
References boundary(), and storage().
Referenced by DdMd::ExternalPotentialImpl< Interaction >::associate().
virtual void DdMd::ExternalPotential::setNAtomType (int nAtomType) [pure virtual]
Set the maximum number of atom types.
Implemented in DdMd::ExternalPotentialImpl< Interaction >.
virtual double DdMd::ExternalPotential::externalEnergy (const Vector & position, int i) const [pure virtual]
Returns external potential energy of a single particle.
Parameters:
position atomic position Vector
i atom type.
Returns:
external potential energy
Implemented in DdMd::ExternalPotentialImpl< Interaction >.
virtual void DdMd::ExternalPotential::getExternalForce (const Vector & position, int type, Vector & force) const [pure virtual]
Returns force caused by the external potential.
Parameters:
position atom position
type atom type id
force force on the atom (on output)
Implemented in DdMd::ExternalPotentialImpl< Interaction >.
virtual std::string DdMd::ExternalPotential::interactionClassName () const [pure virtual]
Return name of interaction class (e.g., "TanhCosineExternal").
Implemented in DdMd::ExternalPotentialImpl< Interaction >.
Simulation & DdMd::ExternalPotential::simulation () [inline, protected]
Get the parent Simulation by reference.
Definition at line 124 of file ddMd/potentials/external/ExternalPotential.h.
Boundary & DdMd::ExternalPotential::boundary () [inline, protected]
Get the Boundary by reference.
Definition at line 127 of file ddMd/potentials/external/ExternalPotential.h.
Referenced by associate().
AtomStorage & DdMd::ExternalPotential::storage () [inline, protected]
Get the AtomStorage by reference.
Definition at line 130 of file ddMd/potentials/external/ExternalPotential.h.
Referenced by associate().
The documentation for this class was generated from the following files:
ddMd/potentials/external/ExternalPotential.h
ExternalPotential.cpp