Simpatico: DdMd::PairPotential Class Reference
DdMd::PairPotential Class Reference abstract
Pair Potentials
Detailed Description
Abstract base class for computing nonbonded pair forces and energies.
A PairPotential has a private CellList and PairList which it can use to calculate nonbonded pair forces. Concrete subclasses of PairPotential are constructed as instances of the PairPotentialImpl class template.
Definition at line 42 of file ddMd/potentials/pair/PairPotential.h.
#include <PairPotential.h>
Public Member Functions
PairPotential (Simulation &simulation)
Constructor.
PairPotential ()
Default constructor.
virtual ~PairPotential ()
Destructor.
double skin () const
Get value of the pair list skin.
double cutoff () const
Get value of the pair list cutoff (maxPairCutoff + skin).
int methodId () const
Return integer id for algorithm (0=PAIR, 1=CELL, 2=NSQ)
Initialization and Serialization
void associate (Domain &domain, Boundary &boundary, AtomStorage &storage)
Associate with related objects.
virtual void setNAtomType (int nAtomType)=0
Set the maximum number of atom types.
void initialize (const Boundary &maxBoundary, double skin, int pairCapacity)
Set parameters and allocate memory.
void readParameters (std::istream &in)
Initialize, by reading parameters and allocating memory for PairList.
virtual void loadParameters (Serializable::IArchive &ar)
Load parameters for PairList from archive, and allocate memory.
virtual void save (Serializable::OArchive &ar)
Save internal state to an output archive.
void setMethodId (int methodId)
Set id to specify algorithm for energy, force calculations.
Interaction interface
virtual double pairEnergy (double rsq, int iAtomType, int jAtomType) const =0
Return energy for a single pair.
virtual double pairForceOverR (double rsq, int iAtomType, int jAtomType) const =0
Return force / separation for a single pair.
virtual void set (std::string name, int i, int j, double value)=0
Modify a parameter, identified by a string.
virtual double get (std::string name, int i, int j) const =0
Get a parameter value, identified by a string.
virtual double maxPairCutoff () const =0
Return maximum cutoff.
virtual std::string interactionClassName () const =0
Return pair interaction class name (e.g., "LJPair").
Pair and Cell Lists.
void buildCellList ()
Build a cell list.
void buildPairList ()
Build the Verlet Pair list.
virtual void computePairEnergies (MPI::Intracomm &communicator)=0
Compute pair energies on all processors.
DMatrix< double > pairEnergies () const
Return total pair energies, from all processors.
void unsetPairEnergies ()
Mark pair energy as unknown (nullify).
void computeNPair (MPI::Intracomm &communicator)
Compute twice the number of pairs within the force cutoff.
int nPair () const
Return twice the number of pairs within the specified force cutoff.
CellList & cellList ()
Get the CellList by reference.
PairList & pairList ()
Get the PairList by reference.
Public Member Functions inherited from DdMd::Potential
Potential ()
Constructor.
virtual ~Potential ()
Destructor.
void setReverseUpdateFlag (bool reverseUpdateFlag)
Set flag to identify if reverse communication is enabled.
bool reverseUpdateFlag () const
Get flag to identify if reverse communication is enabled.
virtual void computeForces ()=0
Add force contributions to all atomic forces.
virtual void computeEnergy (MPI::Intracomm &communicator)=0
Compute potential energy on all processors.
double energy () const
Return the total potential, from all processors.
void unsetEnergy ()
Mark the energy as unknown (nullify).
bool isEnergySet () const
Is the energy set (known)?
virtual void computeStress (MPI::Intracomm &communicator)
Compute stress on all processors.
virtual void computeForcesAndStress (MPI::Intracomm &communicator)
Compute forces and stress for all processors.
Tensor stress () const
Return the stress tensor.
double pressure () const
Return the pressure.
void unsetStress ()
Mark the stress as unknown (nullify).
bool isStressSet () const
Is the stress set (known)?
virtual bool isValid (MPI::Intracomm &communicator) const
Is the potential in a valid internal state?
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
Boundary & boundary ()
Get the PairList by const reference.
Domain & domain ()
Get the PairList by const reference.
AtomStorage & storage ()
Get the AtomStorage by reference.
void setPairEnergies (DMatrix< double > pairEnergies)
Set values for pair energies.
Protected Member Functions inherited from DdMd::Potential
void setEnergy (double energy)
Set a value for the total energy.
void setStress (const Tensor &stress)
Set a value for the total stress.
void incrementPairStress (const Vector &f, const Vector &dr, Tensor &stress) const
Add a pair contribution to the stress tensor.
void reduceEnergy (double localEnergy, MPI::Intracomm &communicator)
Add local energies from all processors, set energy on master.
void reduceStress (Tensor &localStress, MPI::Intracomm &communicator)
Add local stresses from all processors, set total on master.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
CellList cellList_
CellList to construct PairList or calculate nonbonded pair forces.
PairList pairList_
Verlet pair list, to calculate nonbonded pair forces.
Boundary maxBoundary_
Boundary used to allocate space for the cell list.
double skin_
Difference between pairlist cutoff and pair potential cutoff.
double cutoff_
Minimum cell size = pair potential cutoff + skin.
int nCellCut_
Approximate number of cells per cutoff distance in each direction.
int pairCapacity_
Maximum number of nonbonded pairs in pair list.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Constructor & Destructor Documentation
DdMd::PairPotential::PairPotential (Simulation & simulation)
Constructor.
This is the constructor used during a simulation, and is passed the parent Simulation object as a parameter.
Parameters
simulation parent Simulation object.
Definition at line 43 of file PairPotential.cpp.
References Util::ParamComposite::setClassName().
DdMd::PairPotential::PairPotential ()
Default constructor.
This constructor is provided to simplify unit testing.
Definition at line 28 of file PairPotential.cpp.
References Util::ParamComposite::setClassName().
DdMd::PairPotential::~PairPotential () virtual
Destructor.
Definition at line 69 of file PairPotential.cpp.
Member Function Documentation
void DdMd::PairPotential::associate (Domain & domain, Boundary & boundary, AtomStorage & storage)
Associate with related objects.
Required iff object instantiated with default constructor. If required, it must be called before initialize, readParameters, or loadParameters.
Parameters
domain associated Domain object.
boundary associated Boundary object.
storage associated AtomStorage object.
Definition at line 58 of file PairPotential.cpp.
References boundary(), domain(), and storage().
virtual void DdMd::PairPotential::setNAtomType (int nAtomType) pure virtual
Set the maximum number of atom types.
Required iff object instantiated with default constructor. If required, it must be called before initialize, readParameters, or loadParameters.
Parameters
nAtomType maximum number of atom types (max typeId + 1)
Implemented in DdMd::PairPotentialImpl< Interaction >.
void DdMd::PairPotential::initialize (const Boundary & maxBoundary, double skin, int pairCapacity)
Set parameters and allocate memory.
This method initializes the object by assigning parameter values and allocating memory. It provides a programmatic alternative to readParameters.
Parameters
maxBoundary largest expected Boundary (used for allocation)
skin pair list skin length
pairCapacity maximum number of pairs per processor
Definition at line 75 of file PairPotential.cpp.
References cutoff_, maxBoundary_, maxPairCutoff(), pairCapacity_, skin(), and skin_.
void DdMd::PairPotential::readParameters (std::istream & in) virtual
Initialize, by reading parameters and allocating memory for PairList.
Parameters
in input parameter stream.
Reimplemented from Util::ParamComposite.
Reimplemented in DdMd::PairPotentialImpl< Interaction >.
Definition at line 89 of file PairPotential.cpp.
References cutoff_, maxBoundary_, maxPairCutoff(), nCellCut_, pairCapacity_, and skin_.
Referenced by DdMd::PairPotentialImpl< Interaction >::readParameters().
void DdMd::PairPotential::loadParameters (Serializable::IArchive & ar) virtual
Load parameters for PairList from archive, and allocate memory.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Reimplemented in DdMd::PairPotentialImpl< Interaction >.
Definition at line 103 of file PairPotential.cpp.
References cutoff_, maxBoundary_, nCellCut_, pairCapacity_, and skin_.
Referenced by DdMd::PairPotentialImpl< Interaction >::loadParameters().
void DdMd::PairPotential::save (Serializable::OArchive & ar) virtual
Save internal state to an output archive.
Call only on master processor.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Reimplemented in DdMd::PairPotentialImpl< Interaction >.
Definition at line 120 of file PairPotential.cpp.
References cutoff_, maxBoundary_, nCellCut_, pairCapacity_, Util::Parameter::saveOptional(), and skin_.
Referenced by DdMd::PairPotentialImpl< Interaction >::save().
void DdMd::PairPotential::setMethodId (int methodId) inline
Set id to specify algorithm for energy, force calculations.
The default algorithm, methodId=0, uses a pair list that is constructed using a cell list.
Parameters
methodId algorithm id: 0=pair list, 1=cell list, 2=N^2 loop.
Definition at line 394 of file ddMd/potentials/pair/PairPotential.h.
virtual double DdMd::PairPotential::pairEnergy (double rsq, int iAtomType, int jAtomType) const pure virtual
Return energy for a single pair.
Parameters
rsq square distance between atoms in pair
iAtomType atom type index of 1st atom
jAtomType atom type index of 2nd atom
Returns
energy of pair
Implemented in DdMd::PairPotentialImpl< Interaction >.
virtual double DdMd::PairPotential::pairForceOverR (double rsq, int iAtomType, int jAtomType) const pure virtual
Return force / separation for a single pair.
Parameters
rsq square distance between atoms in pair
iAtomType atom type index of 1st atom
jAtomType atom type index of 2nd atom
Returns
repulsive force (< 0 if attractive) over distance
Implemented in DdMd::PairPotentialImpl< Interaction >.
virtual void DdMd::PairPotential::set (std::string name, int i, int j, double value) pure virtual
Modify a parameter, identified by a string.
Parameters
name parameter name
i type index of first atom
j type index of first atom
value new value of parameter
Implemented in DdMd::PairPotentialImpl< Interaction >.
virtual double DdMd::PairPotential::get (std::string name, int i, int j) const pure virtual
Get a parameter value, identified by a string.
Parameters
name parameter name
i type index of first atom
j type index of first atom
Implemented in DdMd::PairPotentialImpl< Interaction >.
virtual double DdMd::PairPotential::maxPairCutoff () const pure virtual
Return maximum cutoff.
Implemented in DdMd::PairPotentialImpl< Interaction >.
Referenced by initialize(), and readParameters().
virtual std::string DdMd::PairPotential::interactionClassName () const pure virtual
Return pair interaction class name (e.g., "LJPair").
Implemented in DdMd::PairPotentialImpl< Interaction >.
void DdMd::PairPotential::buildCellList ()
Build a cell list.
This method adds all local and ghost atoms to a cell list that is used in buildPairList() to build a Verlet pair list. On entry to this method, atomic positions must be generalized. This method should be followed by AtomStorage::transformGenToCart(Boundary&) to transform all positions back to Cartesian coordinates.
Definition at line 159 of file PairPotential.cpp.
References DdMd::AtomStorage::begin(), DdMd::CellList::build(), cellList_, DdMd::CellList::clear(), cutoff_, Util::Dimension, domain(), DdMd::Domain::domainBound(), DdMd::AtomStorage::isCartesian(), DdMd::CellList::isValid(), Util::OrthorhombicBoundary::length(), DdMd::CellList::makeGrid(), DdMd::AtomStorage::nAtom(), DdMd::CellList::nAtom(), nCellCut_, DdMd::AtomStorage::nGhost(), Util::PArrayIterator< Data >::notEnd(), DdMd::CellList::nReject(), DdMd::CellList::placeAtom(), storage(), and UTIL_THROW.
Referenced by DdMd::TwoStepIntegrator::run(), and DdMd::Integrator::setupAtoms().
void DdMd::PairPotential::buildPairList ()
Build the Verlet Pair list.
Preconditions:
Cell List must have been built, by PairPotential::buildCellList.
Atomic positions must be expressed in Cartesian coordinates.
Definition at line 206 of file PairPotential.cpp.
References DdMd::PairList::build(), cellList_, pairList_, DdMd::Potential::reverseUpdateFlag(), storage(), and UTIL_THROW.
Referenced by DdMd::TwoStepIntegrator::run(), and DdMd::Integrator::setupAtoms().
virtual void DdMd::PairPotential::computePairEnergies (MPI::Intracomm & communicator) pure virtual
Compute pair energies on all processors.
This method must be called on all processors. The resulting total is stored on the master processor, and may be retrieved by calling the pairEnergies() function on the master processor.
Implemented in DdMd::PairPotentialImpl< Interaction >.
Referenced by DdMd::PairEnergyAnalyzer::compute().
DMatrix< double > DdMd::PairPotential::pairEnergies () const
Return total pair energies, from all processors.
This method should only be called on the master (rank 0) processor, after a previous call to computePairEnergies.
Definition at line 217 of file PairPotential.cpp.
Referenced by DdMd::PairEnergyAnalyzer::value().
void DdMd::PairPotential::unsetPairEnergies ()
Mark pair energy as unknown (nullify).
Definition at line 229 of file PairPotential.cpp.
void DdMd::PairPotential::computeNPair (MPI::Intracomm & communicator)
Compute twice the number of pairs within the force cutoff.
This method must be called on all processors.
The method for distributing pairs among processors is the same as is used to distribute the energy, and depends on the value of reverseUpdateFlag().
Definition at line 236 of file PairPotential.cpp.
int DdMd::PairPotential::nPair () const
Return twice the number of pairs within the specified force cutoff.
This method should only be called on the master (rank 0) processor. The return value is computed by a previous call to computeNPair.
Definition at line 266 of file PairPotential.cpp.
CellList & DdMd::PairPotential::cellList () inline
Get the CellList by reference.
Definition at line 373 of file ddMd/potentials/pair/PairPotential.h.
PairList & DdMd::PairPotential::pairList () inline
Get the PairList by reference.
Definition at line 376 of file ddMd/potentials/pair/PairPotential.h.
Referenced by DdMd::Integrator::clear(), and DdMd::Integrator::outputStatistics().
double DdMd::PairPotential::skin () const inline
Get value of the pair list skin.
Definition at line 379 of file ddMd/potentials/pair/PairPotential.h.
Referenced by initialize().
double DdMd::PairPotential::cutoff () const inline
Get value of the pair list cutoff (maxPairCutoff + skin).
Definition at line 382 of file ddMd/potentials/pair/PairPotential.h.
int DdMd::PairPotential::methodId () const inline
Return integer id for algorithm (0=PAIR, 1=CELL, 2=NSQ)
Definition at line 397 of file ddMd/potentials/pair/PairPotential.h.
Boundary & DdMd::PairPotential::boundary () inline protected
Get the PairList by const reference.
Definition at line 385 of file ddMd/potentials/pair/PairPotential.h.
Referenced by associate().
Domain & DdMd::PairPotential::domain () inline protected
Get the PairList by const reference.
Definition at line 388 of file ddMd/potentials/pair/PairPotential.h.
Referenced by associate(), and buildCellList().
AtomStorage & DdMd::PairPotential::storage () inline protected
Get the AtomStorage by reference.
Definition at line 391 of file ddMd/potentials/pair/PairPotential.h.
Referenced by associate(), buildCellList(), and buildPairList().
void DdMd::PairPotential::setPairEnergies (DMatrix< double > pairEnergies) protected
Set values for pair energies.
Definition at line 223 of file PairPotential.cpp.
Member Data Documentation
CellList DdMd::PairPotential::cellList_ protected
CellList to construct PairList or calculate nonbonded pair forces.
Definition at line 301 of file ddMd/potentials/pair/PairPotential.h.
Referenced by buildCellList(), and buildPairList().
PairList DdMd::PairPotential::pairList_ protected
Verlet pair list, to calculate nonbonded pair forces.
Definition at line 304 of file ddMd/potentials/pair/PairPotential.h.
Referenced by buildPairList().
Boundary DdMd::PairPotential::maxBoundary_ protected
Boundary used to allocate space for the cell list.
Definition at line 307 of file ddMd/potentials/pair/PairPotential.h.
Referenced by initialize(), loadParameters(), readParameters(), and save().
double DdMd::PairPotential::skin_ protected
Difference between pairlist cutoff and pair potential cutoff.
Definition at line 310 of file ddMd/potentials/pair/PairPotential.h.
Referenced by initialize(), loadParameters(), readParameters(), and save().
double DdMd::PairPotential::cutoff_ protected
Minimum cell size = pair potential cutoff + skin.
Definition at line 313 of file ddMd/potentials/pair/PairPotential.h.
Referenced by buildCellList(), initialize(), loadParameters(), readParameters(), and save().
int DdMd::PairPotential::nCellCut_ protected
Approximate number of cells per cutoff distance in each direction.
Definition at line 316 of file ddMd/potentials/pair/PairPotential.h.
Referenced by buildCellList(), loadParameters(), readParameters(), and save().
int DdMd::PairPotential::pairCapacity_ protected
Maximum number of nonbonded pairs in pair list.
Definition at line 319 of file ddMd/potentials/pair/PairPotential.h.
Referenced by initialize(), loadParameters(), readParameters(), and save().
The documentation for this class was generated from the following files:
ddMd/potentials/pair/PairPotential.h
PairPotential.cpp