Simpatico: McMd::TrajectoryIo Class Reference
McMd::TrajectoryIo Class Reference
Trajectory File IO
Detailed Description
Trajectory file reader and writer.
A subclass of TrajectoryIo needs to implement a the pair readHeader() and readFrame() or the pair writeHedaer() and writeFrame() or both. If either pair is not implemented, calling the standard implementation will result in an error message.
Definition at line 32 of file TrajectoryIo.h.
#include <TrajectoryIo.h>
Public Member Functions
TrajectoryIo (System &system)
Constructor.
virtual ~TrajectoryIo ()
Destructor.
virtual void readHeader (std::fstream &file)
Read trajectory file header.
virtual bool readFrame (std::fstream &file)
Read a single frame.
virtual void writeHeader (std::fstream &file)
Write trajectory file header.
virtual void writeFrame (std::fstream &file)
Write a single frame.
Protected Member Functions
System & system () const
Get a reference to the parent System.
Simulation & simulation () const
Get a reference to the parent Simulation.
Boundary & boundary () const
Get the Boundary.
Protected Attributes
int atomCapacity_
Number of atoms for which space is allocated (all species)
Constructor & Destructor Documentation
McMd::TrajectoryIo::TrajectoryIo (System & system)
Constructor.
Definition at line 22 of file TrajectoryIo.cpp.
McMd::TrajectoryIo::~TrajectoryIo () [virtual]
Destructor.
Definition at line 32 of file TrajectoryIo.cpp.
Member Function Documentation
void McMd::TrajectoryIo::readHeader (std::fstream & file) [virtual]
Read trajectory file header.
This is called once to initialize the file reader.
Parameters:
file input file stream.
Reimplemented in McMd::DCDTrajectoryIo, and McMd::LammpsDumpIo.
Definition at line 38 of file TrajectoryIo.cpp.
References McMd::System::addMolecule(), atomCapacity_, McMd::Species::capacity(), McMd::Species::nAtom(), McMd::Simulation::nSpecies(), Util::ArrayStack< Data >::pop(), McMd::Species::reservoir(), simulation(), McMd::Simulation::species(), and system().
Referenced by McMd::MdSimulation::analyzeTrajectory().
bool McMd::TrajectoryIo::readFrame (std::fstream & file) [virtual]
Read a single frame.
Frames are assumed to be read consecutively. Before a call to readFrame(), the readHeader() method must be called.
Parameters:
file input file stream
Returns:
true if a frame is avaiable, false if at end of file
Reimplemented in McMd::DCDTrajectoryIo, and McMd::LammpsDumpIo.
Definition at line 64 of file TrajectoryIo.cpp.
References UTIL_THROW.
Referenced by McMd::MdSimulation::analyzeTrajectory().
void McMd::TrajectoryIo::writeHeader (std::fstream & file) [virtual]
Write trajectory file header.
Parameters:
file output file stream.
Definition at line 73 of file TrajectoryIo.cpp.
References UTIL_THROW.
void McMd::TrajectoryIo::writeFrame (std::fstream & file) [virtual]
Write a single frame.
Frames are assumed to be written consecutively.
Parameters:
file output file stream
Definition at line 81 of file TrajectoryIo.cpp.
References UTIL_THROW.
System & McMd::TrajectoryIo::system () const [inline, protected]
Get a reference to the parent System.
Definition at line 110 of file TrajectoryIo.h.
Referenced by McMd::LammpsDumpIo::readFrame(), McMd::DCDTrajectoryIo::readFrame(), McMd::DCDTrajectoryIo::readHeader(), and readHeader().
Simulation & McMd::TrajectoryIo::simulation () const [inline, protected]
Get a reference to the parent Simulation.
Definition at line 119 of file TrajectoryIo.h.
Referenced by McMd::LammpsDumpIo::readFrame(), McMd::DCDTrajectoryIo::readFrame(), McMd::DCDTrajectoryIo::readHeader(), and readHeader().
Boundary & McMd::TrajectoryIo::boundary () const [inline, protected]
Get the Boundary.
Definition at line 128 of file TrajectoryIo.h.
Referenced by McMd::LammpsDumpIo::readFrame(), and McMd::DCDTrajectoryIo::readFrame().
Member Data Documentation
int McMd::TrajectoryIo::atomCapacity_ [protected]
Number of atoms for which space is allocated (all species)
Definition at line 80 of file TrajectoryIo.h.
Referenced by McMd::LammpsDumpIo::readFrame(), McMd::LammpsDumpIo::readHeader(), McMd::DCDTrajectoryIo::readHeader(), and readHeader().
The documentation for this class was generated from the following files:
TrajectoryIo.h
TrajectoryIo.cpp