Simpatico: Util::DMatrix< Data > Class Template Reference
Util::DMatrix< Data > Class Template Reference
Matrix Containers
Detailed Description
template<typename Data>
class Util::DMatrix< Data >
Dynamically allocated Matrix.
Definition at line 24 of file DMatrix.h.
#include <DMatrix.h>
Public Member Functions
DMatrix ()
Constructor.
DMatrix (const DMatrix< Data > &other)
Copy constructor.
DMatrix< Data > & operator= (const DMatrix< Data > &other)
Assignment.
~DMatrix ()
Destructor.
void allocate (int capacity1, int capacity2)
Allocate memory for a matrix.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize a DMatrix to/from an Archive.
bool isAllocated () const
Return true if the DMatrix has been allocated, false otherwise.
Public Member Functions inherited from Util::Matrix< Data >
virtual ~Matrix ()
Destructor.
int capacity1 ()
Get number of rows (range of the first array index).
int capacity2 ()
Get number of columns (range of the second array index).
const Data & operator() (int i, int j) const
Return element (i,j) of matrix by const reference.
Data & operator() (int i, int j)
Return element (i,j) of matrix by reference.
Additional Inherited Members
Protected Member Functions inherited from Util::Matrix< Data >
Matrix ()
Default constructor.
Protected Attributes inherited from Util::Matrix< Data >
Data * data_
Pointer to 1D C array of all elements.
int capacity1_
Number of rows (range of first index).
int capacity2_
Number of columns (range of first index).
Constructor & Destructor Documentation
template<typename Data > Util::DMatrix< Data >::DMatrix ()
Constructor.
Definition at line 87 of file DMatrix.h.
template<typename Data> Util::DMatrix< Data >::DMatrix (const DMatrix< Data > & other)
Copy constructor.
Definition at line 95 of file DMatrix.h.
References Util::DMatrix< Data >::allocate(), Util::Matrix< Data >::capacity1_, Util::Matrix< Data >::capacity2_, Util::Matrix< Data >::data_, and UTIL_THROW.
template<typename Data > Util::DMatrix< Data >::~DMatrix ()
Destructor.
Delete dynamically allocated C array.
Definition at line 149 of file DMatrix.h.
Member Function Documentation
template<typename Data> DMatrix< Data > & Util::DMatrix< Data >::operator= (const DMatrix< Data > & other)
Assignment.
Exceptions
Exception if LHS and RHS dimensions do not match.
Definition at line 114 of file DMatrix.h.
References Util::Matrix< Data >::capacity1_, Util::Matrix< Data >::capacity2_, Util::Matrix< Data >::data_, and UTIL_THROW.
template<typename Data > void Util::DMatrix< Data >::allocate (int capacity1, int capacity2)
Allocate memory for a matrix.
Parameters
capacity1 number of rows (range of first index)
capacity2 number of columns (range of second index)
Definition at line 163 of file DMatrix.h.
References UTIL_THROW.
Referenced by DdMd::PairPotentialImpl< Interaction >::computePairEnergies(), Util::DMatrix< Data >::DMatrix(), McMd::Perturbation::loadParameters(), McMd::StructureFactor::loadParameters(), DdMd::OrderParamNucleation::loadParameters(), McMd::StructureFactorGrid::loadParameters(), McMd::StructureFactorPGrid::loadParameters(), DdMd::StructureFactorGrid::loadParameters(), McMd::IntraStructureFactorGrid::loadParameters(), DdMd::StructureFactor::loadParameters(), McMd::StructureFactorP::loadParameters(), DdMd::Simulation::pairEnergies(), McMd::Perturbation::readParameters(), McMd::StructureFactor::readParameters(), DdMd::OrderParamNucleation::readParameters(), McMd::StructureFactorPGrid::readParameters(), McMd::StructureFactorGrid::readParameters(), DdMd::StructureFactorGrid::readParameters(), McMd::IntraStructureFactorGrid::readParameters(), DdMd::StructureFactor::readParameters(), McMd::StructureFactorP::readParameters(), and McMd::IntraStructureFactor::readParameters().
template<class Data > template<class Archive > void Util::DMatrix< Data >::serialize (Archive & ar, const unsigned int version)
Serialize a DMatrix to/from an Archive.
Parameters
ar archive
version archive version id
Definition at line 180 of file DMatrix.h.
References UTIL_THROW.
template<class Data > bool Util::DMatrix< Data >::isAllocated () const inline
Return true if the DMatrix has been allocated, false otherwise.
Definition at line 217 of file DMatrix.h.
Referenced by Util::bcast(), Util::recv(), and Util::send().
The documentation for this class was generated from the following file:
DMatrix.h