Simpatico: DdMd::NphIntegrator Class Reference
DdMd::NphIntegrator Class Reference
MD Integrators
Detailed Description
A reversible, symplectic NPH integrator (Anderson barostat).
Integration algorithm based on Martyna,Tobias and Klein (J. Chem. Phys. 101, 4177-4189, 1994).
See also:
param file format
Definition at line 29 of file ddMd/integrators/NphIntegrator.h.
#include <NphIntegrator.h>
Public Member Functions
NphIntegrator (Simulation &simulation)
Constructor.
~NphIntegrator ()
Destructor.
void readParameters (std::istream &in)
Read required parameters.
void loadParameters (Serializable::IArchive &ar)
Load parameters from an input restart archive.
void save (Serializable::OArchive &ar)
Save state to an input restart archive.
Protected Member Functions
void initDynamicalState ()
Initialize Vector nu to zero.
void setup ()
Setup state just before integration.
virtual void integrateStep1 ()
Execute first step of two-step integrator.
virtual void integrateStep2 ()
Execute secodn step of two-step integrator.
Constructor & Destructor Documentation
DdMd::NphIntegrator::NphIntegrator (Simulation & simulation)
Constructor.
Definition at line 33 of file ddMd/integrators/NphIntegrator.cpp.
References Util::ParamComposite::setClassName().
DdMd::NphIntegrator::~NphIntegrator ()
Destructor.
Definition at line 40 of file ddMd/integrators/NphIntegrator.cpp.
Member Function Documentation
void DdMd::NphIntegrator::readParameters (std::istream & in) [virtual]
Read required parameters.
Reimplemented from DdMd::Integrator.
Definition at line 46 of file ddMd/integrators/NphIntegrator.cpp.
References Util::DArray< Data >::allocate(), Util::DArray< Data >::isAllocated(), DdMd::SimulationAccess::nAtomType(), DdMd::Simulation::nAtomType(), and DdMd::SimulationAccess::simulation().
void DdMd::NphIntegrator::loadParameters (Serializable::IArchive & ar) [virtual]
Load parameters from an input restart archive.
Reimplemented from DdMd::Integrator.
Definition at line 63 of file ddMd/integrators/NphIntegrator.cpp.
References Util::DArray< Data >::allocate(), Util::DArray< Data >::isAllocated(), Util::MpiLoader< IArchive >::load(), DdMd::SimulationAccess::nAtomType(), DdMd::Simulation::nAtomType(), and DdMd::SimulationAccess::simulation().
void DdMd::NphIntegrator::save (Serializable::OArchive & ar) [virtual]
Save state to an input restart archive.
Reimplemented from DdMd::Integrator.
Definition at line 83 of file ddMd/integrators/NphIntegrator.cpp.
void DdMd::NphIntegrator::initDynamicalState () [protected, virtual]
Initialize Vector nu to zero.
Reimplemented from DdMd::Integrator.
Definition at line 95 of file ddMd/integrators/NphIntegrator.cpp.
void DdMd::NphIntegrator::setup () [protected, virtual]
Setup state just before integration.
Implements DdMd::Integrator.
Definition at line 98 of file ddMd/integrators/NphIntegrator.cpp.
References DdMd::SimulationAccess::atomStorage(), DdMd::Simulation::atomType(), Util::bcast(), DdMd::Simulation::boundaryEnsemble(), Util::Array< Data >::capacity(), DdMd::Integrator::clear(), DdMd::Simulation::computeKineticEnergy(), DdMd::AtomStorage::computeNAtomTotal(), DdMd::SimulationAccess::domain(), DdMd::Integrator::isSetup(), DdMd::AtomType::mass(), DdMd::AtomStorage::nAtomTotal(), DdMd::SimulationAccess::nAtomType(), Util::BoundaryEnsemble::pressure(), DdMd::Integrator::setIsSetup(), DdMd::Integrator::setupAtoms(), and DdMd::SimulationAccess::simulation().
void DdMd::NphIntegrator::integrateStep1 () [protected, virtual]
Execute first step of two-step integrator.
Implements DdMd::TwoStepIntegrator.
Definition at line 134 of file ddMd/integrators/NphIntegrator.cpp.
References DdMd::SimulationAccess::atomStorage(), Util::bcast(), DdMd::AtomStorage::begin(), DdMd::Simulation::boundary(), DdMd::Simulation::boundaryEnsemble(), DdMd::Simulation::computeKineticEnergy(), DdMd::Simulation::computeKineticStress(), DdMd::Simulation::computeVirialStress(), DdMd::SimulationAccess::domain(), DdMd::Simulation::domain(), DdMd::Domain::isMaster(), DdMd::Simulation::kineticEnergy(), DdMd::Simulation::kineticStress(), Util::OrthorhombicBoundary::lengths(), Util::Vector::multiply(), Util::PArrayIterator< Data >::notEnd(), Util::BoundaryEnsemble::pressure(), Util::OrthorhombicBoundary::setOrthorhombic(), DdMd::SimulationAccess::simulation(), Util::Tensor::trace(), DdMd::Simulation::virialStress(), and Util::OrthorhombicBoundary::volume().
void DdMd::NphIntegrator::integrateStep2 () [protected, virtual]
Execute secodn step of two-step integrator.
Implements DdMd::TwoStepIntegrator.
Definition at line 266 of file ddMd/integrators/NphIntegrator.cpp.
References DdMd::SimulationAccess::atomStorage(), Util::bcast(), DdMd::AtomStorage::begin(), DdMd::Simulation::boundary(), DdMd::Simulation::computeKineticEnergy(), DdMd::Simulation::computeKineticStress(), DdMd::Simulation::computePotentialEnergies(), DdMd::Simulation::computeVirialStress(), DdMd::SimulationAccess::domain(), DdMd::Simulation::domain(), DdMd::Domain::isMaster(), DdMd::Simulation::kineticEnergy(), DdMd::Simulation::kineticStress(), Util::Vector::multiply(), Util::PArrayIterator< Data >::notEnd(), Util::Signal< T >::notify(), DdMd::Simulation::potentialEnergy(), DdMd::SimulationAccess::simulation(), Util::Tensor::trace(), DdMd::Simulation::velocitySignal(), DdMd::Simulation::virialStress(), and Util::OrthorhombicBoundary::volume().
The documentation for this class was generated from the following files:
ddMd/integrators/NphIntegrator.h
ddMd/integrators/NphIntegrator.cpp