Simpatico: Inter::LJPair Class Reference
Inter::LJPair Class Reference
Pair Interactions
Detailed Description
A cutoff Lennard-Jones nonbonded pair potential.
Member variables include interaction parameters. Member functions evaluate energy and force for an individual pair of nonbonded interacting particles.
Definition at line 29 of file LJPair.h.
#include <LJPair.h>
Public Member Functions
LJPair ()
Default constructor.
LJPair (const LJPair &other)
Copy constructor.
LJPair & operator= (const LJPair &other)
Assignment.
Mutators
void setNAtomType (int nAtomType)
Set nAtomType value.
void readParameters (std::istream &in)
Read epsilon, sigma, and cutoff, and initialize other variables.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void setEpsilon (int i, int j, double epsilon)
Set LJ interaction energy for a specific pair of Atom types.
void setSigma (int i, int j, double sigma)
Get LJ range for a specific pair of Atom types.
void set (std::string name, int i, int j, double value)
Modify a parameter, identified by a string.
Accessors
double energy (double rsq, int i, int j) const
Returns interaction energy for a single pair of particles.
double forceOverR (double rsq, int i, int j) const
Returns ratio of scalar pair interaction force to pair separation.
double maxPairCutoff () const
Get maximum of pair cutoff distance, for all atom type pairs.
double epsilon (int i, int j) const
Get LJ interaction energy for a specific pair of Atom types.
double sigma (int i, int j) const
Get LJ range for a specific pair of Atom types.
double get (std::string name, int i, int j) const
Get a parameter value, identified by a string.
Constructor & Destructor Documentation
Inter::LJPair::LJPair ()
Default constructor.
Definition at line 24 of file LJPair.cpp.
References Util::ParamComposite::setClassName().
Inter::LJPair::LJPair (const LJPair & other)
Copy constructor.
Definition at line 33 of file LJPair.cpp.
Member Function Documentation
LJPair & Inter::LJPair::operator= (const LJPair & other)
Assignment.
Definition at line 54 of file LJPair.cpp.
void Inter::LJPair::setNAtomType (int nAtomType)
Set nAtomType value.
Parameters:
nAtomType number of atom types.
Definition at line 76 of file LJPair.cpp.
References UTIL_THROW.
void Inter::LJPair::readParameters (std::istream & in) [virtual]
Read epsilon, sigma, and cutoff, and initialize other variables.
Precondition:
nAtomType must have been set, by calling setNAtomType().
Parameters:
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 155 of file LJPair.cpp.
References UTIL_THROW.
void Inter::LJPair::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 191 of file LJPair.cpp.
References UTIL_THROW.
void Inter::LJPair::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 214 of file LJPair.cpp.
References Util::BinaryFileOArchive::pack().
void Inter::LJPair::setEpsilon (int i, int j, double epsilon)
Set LJ interaction energy for a specific pair of Atom types.
Parameters:
i type of Atom 1
j type of Atom 2
epsilon LJ energy parameter
Definition at line 90 of file LJPair.cpp.
References epsilon(), and UTIL_THROW.
void Inter::LJPair::setSigma (int i, int j, double sigma)
Get LJ range for a specific pair of Atom types.
Parameters:
i atom type index 1
j atom type index 2
sigma LJ range parameter
Definition at line 121 of file LJPair.cpp.
References sigma(), and UTIL_THROW.
void Inter::LJPair::set (std::string name, int i, int j, double value)
Modify a parameter, identified by a string.
Parameters:
name parameter name
i atom type index 1
j atom type index 2
value new value of parameter
Definition at line 255 of file LJPair.cpp.
References UTIL_THROW.
double Inter::LJPair::energy (double rsq, int i, int j) const [inline]
Returns interaction energy for a single pair of particles.
Parameters:
rsq square of distance between particles
i type of particle 1
j type of particle 2
Returns:
pair interaction energy
Definition at line 205 of file LJPair.h.
double Inter::LJPair::forceOverR (double rsq, int i, int j) const [inline]
Returns ratio of scalar pair interaction force to pair separation.
Multiply this quantity by the components of the separation vector to obtain the force vector. A positive value for the return value represents a repulsive force between a pair of particles.
Parameters:
rsq square of distance between particles
i type of particle 1
j type of particle 2
Returns:
force divided by distance
Definition at line 223 of file LJPair.h.
double Inter::LJPair::maxPairCutoff () const
Get maximum of pair cutoff distance, for all atom type pairs.
Definition at line 229 of file LJPair.cpp.
double Inter::LJPair::epsilon (int i, int j) const
Get LJ interaction energy for a specific pair of Atom types.
Parameters:
i type of Atom 1
j type of Atom 2
Returns:
epsilon_[i][j]
Definition at line 235 of file LJPair.cpp.
Referenced by setEpsilon().
double Inter::LJPair::sigma (int i, int j) const
Get LJ range for a specific pair of Atom types.
Parameters:
i atom type index 1
j atom type index 2
Returns:
sigma_[i][j]
Definition at line 245 of file LJPair.cpp.
Referenced by setSigma().
double Inter::LJPair::get (std::string name, int i, int j) const
Get a parameter value, identified by a string.
Parameters:
name parameter name
i atom type index 1
j atom type index 2
Definition at line 285 of file LJPair.cpp.
References UTIL_THROW.
The documentation for this class was generated from the following files:
LJPair.h
LJPair.cpp