Simpatico: Util::MpiFileIo Class Reference
Util::MpiFileIo Class Reference
Detailed Description
Identifies whether this processor may do file I/O.
The return value of isIoProcessor() indicates whether this processor can read and write to file. If the the class is compiled with UTIL_MPI not defined, then isIoProcessor() always returns true. If the class is compiled with UTIL_MPI defined, then this method returns true if either: (1) A communicator has been set and this processor has rank 0 within that communicator, or (2) No communicator has been set.
When compiled with UTIL_MPI defined, an MpiFileIo object has a pointer to an MPI communiciator, and provides methods to set and unset (nullify) the associated communicator.
Definition at line 33 of file MpiFileIo.h.
#include <MpiFileIo.h>
Public Member Functions
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Constructor & Destructor Documentation
Util::MpiFileIo::MpiFileIo ()
Constructor.
Definition at line 18 of file MpiFileIo.cpp.
Util::MpiFileIo::MpiFileIo (const MpiFileIo & other)
Copy constructor.
Definition at line 28 of file MpiFileIo.cpp.
Member Function Documentation
bool Util::MpiFileIo::isIoProcessor () const inline
Can this processor do file I/O ?
Definition at line 92 of file MpiFileIo.h.
Referenced by Util::Manager< Data >::endReadManager(), Util::MpiLoader< IArchive >::load(), Util::Parameter::load(), Util::ParamComposite::load(), Util::Factory< Data >::loadObject(), Util::ParamComposite::loadOptional(), Util::Manager< Data >::loadParameters(), McMd::MdSimulation::readCommands(), McMd::McSimulation::readCommands(), Util::Factory< Data >::readObject(), Util::Blank::readParam(), Util::End::readParam(), Util::Begin::readParam(), Util::Parameter::readParam(), and DdMd::TrajectoryWriter::setup().
void Util::MpiFileIo::setIoCommunicator (MPI::Intracomm & communicator)
Set the communicator.
Definition at line 36 of file MpiFileIo.cpp.
Referenced by Util::Factory< Data >::setIoCommunicator(), McMd::Simulation::setIoCommunicator(), and Util::ParamComposite::setParent().
void Util::MpiFileIo::clearCommunicator ()
Clear (nullify) the communicator.
Definition at line 46 of file MpiFileIo.cpp.
bool Util::MpiFileIo::hasIoCommunicator () const inline
Does this object have an associated MPI communicator?
Definition at line 99 of file MpiFileIo.h.
Referenced by Util::Factory< Data >::hasIoCommunicator(), Util::MpiLoader< IArchive >::load(), Util::Parameter::load(), Util::Factory< Data >::loadObject(), Util::ParamComposite::loadOptional(), McMd::BennettsMethod::loadParameters(), McMd::McSimulation::loadParameters(), Util::Manager< Data >::loadParameters(), McMd::System::loadPerturbation(), McMd::MdSimulation::readCommands(), McMd::McSimulation::readCommands(), Util::Factory< Data >::readObject(), Util::Begin::readParam(), Util::Parameter::readParam(), McMd::BennettsMethod::readParameters(), Util::Factory< Data >::setIoCommunicator(), and Util::ParamComposite::setParent().
MPI::Intracomm & Util::MpiFileIo::ioCommunicator () const inline
Get the MPI communicator by reference.
Definition at line 105 of file MpiFileIo.h.
Referenced by Util::CArrayParam< Type >::bcastValue(), Util::DArrayParam< Type >::bcastValue(), Util::FArrayParam< Type, N >::bcastValue(), Util::DMatrixParam< Type >::bcastValue(), Util::DSymmMatrixParam< Type >::bcastValue(), Util::CArray2DParam< Type >::bcastValue(), Util::ScalarParam< Type >::bcastValue(), Util::MpiLoader< IArchive >::load(), Util::Parameter::load(), Util::Factory< Data >::loadObject(), Util::ParamComposite::loadOptional(), Util::Manager< Data >::loadParameters(), Util::Factory< Data >::readObject(), Util::Begin::readParam(), Util::Parameter::readParam(), Util::Factory< Data >::setIoCommunicator(), and Util::ParamComposite::setParent().
The documentation for this class was generated from the following files:
MpiFileIo.h
MpiFileIo.cpp