Simpatico: DdMd::DdTimer Class Reference
DdMd::DdTimer Class Reference
Detailed Description
Class for measuring time intervals.
Design adapted from the timer class in Lammps.
Definition at line 24 of file DdTimer.h.
#include <DdTimer.h>
Public Member Functions
void clear ()
Clear all time statistics.
void start ()
Clear statistics, mark a start time.
void stamp (int id)
Mark end of interval id.
void stop ()
Stop total time accumulation.
double time (int id) const
Get accumulated time for interval i, average per processor.
double time () const
Get total time since start time, average per processor.
void reduce (MPI::Intracomm &communicator)
Upon return, times on every processor replaced by average over procs.
Member Function Documentation
void DdMd::DdTimer::clear ()
Clear all time statistics.
Definition at line 23 of file DdTimer.cpp.
Referenced by DdMd::Integrator::clear().
void DdMd::DdTimer::start ()
Clear statistics, mark a start time.
Definition at line 31 of file DdTimer.cpp.
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::DdTimer::stamp (int id)
Mark end of interval id.
Definition at line 37 of file DdTimer.cpp.
Referenced by DdMd::Integrator::computeForces(), DdMd::Integrator::computeForcesAndVirial(), DdMd::Integrator::isExchangeNeeded(), and DdMd::TwoStepIntegrator::run().
void DdMd::DdTimer::stop ()
Stop total time accumulation.
Definition at line 44 of file DdTimer.cpp.
Referenced by DdMd::TwoStepIntegrator::run().
double DdMd::DdTimer::time (int id) const
Get accumulated time for interval i, average per processor.
Definition at line 61 of file DdTimer.cpp.
Referenced by DdMd::Integrator::outputStatistics(), DdMd::Exchanger::outputStatistics(), and DdMd::Integrator::time().
double DdMd::DdTimer::time () const
Get total time since start time, average per processor.
Definition at line 64 of file DdTimer.cpp.
void DdMd::DdTimer::reduce (MPI::Intracomm & communicator)
Upon return, times on every processor replaced by average over procs.
Definition at line 48 of file DdTimer.cpp.
The documentation for this class was generated from the following files:
DdTimer.h
DdTimer.cpp