Simpatico: McMd::EnergyCalculator Class Reference
McMd::EnergyCalculator Class Reference abstract
McMd namespace » Potential Energies
Detailed Description
Interface for a class that calculates a total energy.
Definition at line 23 of file EnergyCalculator.h.
#include <EnergyCalculator.h>
Public Member Functions
virtual void unsetEnergy ()
Mark the energy as unknown.
virtual void computeEnergy ()=0
Calculate the total nonBonded pair energy for the associated System.
double energy ()
Return the energy contribution, compute if necessary.
Member Function Documentation
void McMd::EnergyCalculator::unsetEnergy () virtual
Mark the energy as unknown.
Reimplemented in McMd::MdEwaldPairPotentialImpl< Interaction >.
Definition at line 18 of file EnergyCalculator.cpp.
Referenced by McMd::McSystem::unsetPotentialEnergies(), and McMd::MdSystem::unsetPotentialEnergy().
virtual void McMd::EnergyCalculator::computeEnergy () pure virtual
Calculate the total nonBonded pair energy for the associated System.
Implemented in McMd::AnglePotentialImpl< Interaction >, McMd::DihedralPotentialImpl< Interaction >, McMd::MdEwaldPairPotentialImpl< Interaction >, McMd::MdPairPotentialImpl< Interaction >, McMd::McPairPotentialImpl< Interaction >, McMd::BondPotentialImpl< Interaction >, and McMd::LinkPotentialImpl< Interaction >.
double McMd::EnergyCalculator::energy ()
Return the energy contribution, compute if necessary.
Return the precalculated total pair energy for this System.
If necessary, this function calls computeEnergy() and stores the value before returning stored value.
Definition at line 24 of file EnergyCalculator.cpp.
Referenced by McMd::LinkPotentialImpl< Interaction >::atomEnergy(), McMd::BondPotentialImpl< Interaction >::atomEnergy(), McMd::McPairPotentialImpl< Interaction >::atomEnergy(), McMd::DihedralPotentialImpl< Interaction >::atomEnergy(), McMd::AnglePotentialImpl< Interaction >::atomEnergy(), McMd::LinkPotentialImpl< Interaction >::computeEnergy(), McMd::BondPotentialImpl< Interaction >::computeEnergy(), McMd::McPairPotentialImpl< Interaction >::computeEnergy(), McMd::MdPairPotentialImpl< Interaction >::computeEnergy(), McMd::DihedralPotentialImpl< Interaction >::computeEnergy(), McMd::AnglePotentialImpl< Interaction >::computeEnergy(), McMd::McPairPotentialImpl< Interaction >::moleculeEnergy(), and McMd::DihedralPotentialImpl< Interaction >::save().
The documentation for this class was generated from the following files:
EnergyCalculator.h
EnergyCalculator.cpp