Simpatico: McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction > Class Template Reference
McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction > Class Template Reference
Free Energy Perturbation
Detailed Description
template<class PairInteraction, class ExternalInteraction>
class McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >
A Perturbation in the pair interaction epsilon(0,1) for any pair potential supporting setEpsilon() and in the external parameter for any external potential supporting setExternalParameter().
An McPairExternalPerturbation describes a Hamiltonian with a variable pair interaction between species 0 and 1 and with a variable external parameter. The perturbation parameter consists of the pair interaction parameter epsilon(0, 1) and the external parameter.
Definition at line 49 of file McPairExternalPerturbation.h.
#include <McPairExternalPerturbation.h>
Public Member Functions
McPairExternalPerturbation (McSystem &system, int size, int rank)
Constructor.
virtual ~McPairExternalPerturbation ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameter epsilon(0, 1) and external parameter from file.
virtual void setParameter ()
Set pair interaction parameter epsilon(0,1) and external parameter for this System.
virtual double parameter (int i) const
Return the perturbation parameter for this System.
virtual double derivative (int i) const
Return (0-1 pair energy) / (kT *epsilon(0,1)) if i is 0 or (external potential energy)/ (kT *externalParameter) if i is 1.
Constructor & Destructor Documentation
template<class PairInteraction , class ExternalInteraction > McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >::McPairExternalPerturbation (McSystem & system, int size, int rank)
Constructor.
Implementation.
Parameters:
system parent McSystem
size number of systems (communicator size).
rank id of this system (communicator rank).
Definition at line 124 of file McPairExternalPerturbation.h.
References Util::ParamComposite::setClassName().
template<class PairInteraction , class ExternalInteraction > McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >::~McPairExternalPerturbation< PairInteraction, ExternalInteraction > () [virtual]
Destructor.
Definition at line 134 of file McPairExternalPerturbation.h.
Member Function Documentation
template<class PairInteraction , class ExternalInteraction > void McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >::readParameters (std::istream & in) [virtual]
Read parameter epsilon(0, 1) and external parameter from file.
Parameters:
in input stream (file or std in).
Reimplemented from McMd::Perturbation.
Definition at line 141 of file McPairExternalPerturbation.h.
References McMd::Perturbation::getNParameters(), and McMd::Perturbation::readParameters().
template<class PairInteraction , class ExternalInteraction > void McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >::setParameter () [virtual]
Set pair interaction parameter epsilon(0,1) and external parameter for this System.
Implements McMd::Perturbation.
Definition at line 186 of file McPairExternalPerturbation.h.
template<class PairInteraction , class ExternalInteraction > double McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >::parameter (int i) const [virtual]
Return the perturbation parameter for this System.
Parameters:
i index of the perturbation parameter. In this case, i can either be 0 or 1 since nParameters = 2.
Implements McMd::Perturbation.
Definition at line 197 of file McPairExternalPerturbation.h.
References UTIL_THROW.
template<class PairInteraction , class ExternalInteraction > double McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >::derivative (int i) const [virtual]
Return (0-1 pair energy) / (kT *epsilon(0,1)) if i is 0 or (external potential energy)/ (kT *externalParameter) if i is 1.
Implements McMd::Perturbation.
Definition at line 216 of file McPairExternalPerturbation.h.
References McMd::Atom::id(), McMd::Mask::isMasked(), McMd::Atom::mask(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Atom::position(), McMd::Atom::typeId(), and UTIL_THROW.
The documentation for this class was generated from the following file:
McPairExternalPerturbation.h