Simpatico: McMd::HybridNphMdMove Class Reference
McMd::HybridNphMdMove Class Reference
Monte Carlo Moves
Detailed Description
HybridMdMove is a hybrid Molecular Dynamics MC move.
Definition at line 30 of file HybridNphMdMove.h.
#include <HybridNphMdMove.h>
Public Member Functions
HybridNphMdMove (McSystem &system)
Constructor.
~HybridNphMdMove ()
Destructor.
virtual void readParameters (std::istream &in)
Read nStep and MdSystem parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
bool move ()
Generate, attempt and accept or reject a move.
Constructor & Destructor Documentation
McMd::HybridNphMdMove::HybridNphMdMove (McSystem & system)
Constructor.
Parameters:
system parent McSystem.
Definition at line 32 of file HybridNphMdMove.cpp.
References Util::DArray< Data >::allocate(), Util::ParamComposite::setClassName(), and McMd::McMove::simulation().
McMd::HybridNphMdMove::~HybridNphMdMove ()
Destructor.
Definition at line 48 of file HybridNphMdMove.cpp.
Member Function Documentation
void McMd::HybridNphMdMove::readParameters (std::istream & in) [virtual]
Read nStep and MdSystem parameters from file.
Parameters:
in input parameter stream
Reimplemented from McMd::McMove.
Definition at line 58 of file HybridNphMdMove.cpp.
References McMd::NphIntegrator::barostatMass(), McMd::MdSystem::mdIntegrator(), McMd::NphIntegrator::mode(), Util::ParamComposite::readParamComposite(), and McMd::McMove::readProbability().
void McMd::HybridNphMdMove::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::McMove.
Definition at line 73 of file HybridNphMdMove.cpp.
References McMd::NphIntegrator::barostatMass(), Util::ParamComposite::loadParamComposite(), McMd::MdSystem::mdIntegrator(), and McMd::NphIntegrator::mode().
void McMd::HybridNphMdMove::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::McMove.
Definition at line 87 of file HybridNphMdMove.cpp.
References McMd::MdSystem::saveParameters().
bool McMd::HybridNphMdMove::move () [virtual]
Generate, attempt and accept or reject a move.
Reimplemented from McMd::McMove.
Definition at line 98 of file HybridNphMdMove.cpp.
References McMd::NphIntegrator::barostatEnergy(), McMd::System::begin(), McMd::SystemMove::boltzmann(), McMd::System::boundary(), McMd::System::boundaryEnsemble(), McMd::McPairPotential::buildCellList(), McMd::MdPairPotential::buildPairList(), McMd::MdSystem::calculateForces(), McMd::SystemMove::energyEnsemble(), McMd::System::energyEnsemble(), Util::Random::gaussian(), McMd::McMove::incrementNAccept(), McMd::McMove::incrementNAttempt(), McMd::MdSystem::kineticEnergy(), Util::OrthorhombicBoundary::lengths(), Util::Random::metropolis(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), McMd::McSystem::pairPotential(), McMd::MdSystem::pairPotential(), McMd::MdSystem::potentialEnergy(), Util::BoundaryEnsemble::pressure(), McMd::McMove::random(), McMd::Simulation::random(), McMd::MdSystem::setBoltzmannVelocities(), McMd::NphIntegrator::setEta(), Util::OrthorhombicBoundary::setOrthorhombic(), McMd::NphIntegrator::setup(), McMd::McMove::simulation(), McMd::NphIntegrator::step(), McMd::SystemMove::system(), Util::EnergyEnsemble::temperature(), UTIL_THROW, and Util::OrthorhombicBoundary::volume().
The documentation for this class was generated from the following files:
HybridNphMdMove.h
HybridNphMdMove.cpp