Simpatico: DdMd::OutputPressure Class Reference
DdMd::OutputPressure Class Reference
Diagnostics
Detailed Description
Periodically write (scalar) pressure to file.
Definition at line 25 of file OutputPressure.h.
#include <OutputPressure.h>
Public Member Functions
OutputPressure (Simulation &simulation)
Constructor.
virtual ~OutputPressure ()
Destructor.
virtual void readParameters (std::istream &in)
Read dumpPrefix and interval.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void clear ()
Clear nSample counter.
virtual void sample (long iStep)
Dump configuration to file.
Constructor & Destructor Documentation
DdMd::OutputPressure::OutputPressure (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object.
Definition at line 27 of file OutputPressure.cpp.
References Util::ParamComposite::setClassName().
virtual DdMd::OutputPressure::~OutputPressure () [inline, virtual]
Destructor.
Definition at line 40 of file OutputPressure.h.
Member Function Documentation
void DdMd::OutputPressure::readParameters (std::istream & in) [virtual]
Read dumpPrefix and interval.
Parameters:
in input parameter file
Reimplemented from Util::ParamComposite.
Definition at line 36 of file OutputPressure.cpp.
References DdMd::Simulation::fileMaster(), Util::FileMaster::openOutputFile(), DdMd::Diagnostic::outputFileName(), DdMd::Diagnostic::readInterval(), DdMd::Diagnostic::readOutputFileName(), and DdMd::Diagnostic::simulation().
void DdMd::OutputPressure::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from DdMd::Diagnostic.
Definition at line 52 of file OutputPressure.cpp.
References DdMd::Simulation::fileMaster(), Util::MpiLoader< IArchive >::load(), DdMd::Diagnostic::loadInterval(), DdMd::Diagnostic::loadOutputFileName(), Util::FileMaster::openOutputFile(), DdMd::Diagnostic::outputFileName(), and DdMd::Diagnostic::simulation().
void DdMd::OutputPressure::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from DdMd::Diagnostic.
Definition at line 70 of file OutputPressure.cpp.
References DdMd::Diagnostic::saveInterval(), and DdMd::Diagnostic::saveOutputFileName().
void DdMd::OutputPressure::clear () [virtual]
Clear nSample counter.
Reimplemented from DdMd::Diagnostic.
Definition at line 81 of file OutputPressure.cpp.
void DdMd::OutputPressure::sample (long iStep) [virtual]
Dump configuration to file.
Parameters:
iStep MD step index
Implements DdMd::Diagnostic.
Definition at line 87 of file OutputPressure.cpp.
References DdMd::Simulation::computeKineticStress(), DdMd::Simulation::computeVirialStress(), DdMd::Simulation::domain(), DdMd::Diagnostic::isAtInterval(), DdMd::Domain::isMaster(), DdMd::Simulation::kineticPressure(), DdMd::Diagnostic::simulation(), and DdMd::Simulation::virialPressure().
The documentation for this class was generated from the following files:
OutputPressure.h
OutputPressure.cpp