Simpatico: McMd::SliplinkMcModule Class Reference
McMd::SliplinkMcModule Class Reference
Detailed Description
Module for slip link simulation.
Definition at line 17 of file SliplinkMcModule.h.
#include <SliplinkMcModule.h>
Public Member Functions
SliplinkMcModule (McSimulation &sim)
Constructor.
Constructor & Destructor Documentation
McMd::SliplinkMcModule::SliplinkMcModule (McSimulation & sim)
Constructor.
Parameters
sim parent McSimulation.
Definition at line 8 of file SliplinkMcModule.cpp.
References Util::Factory< Data >::addSubfactory(), McMd::Simulation::analyzerFactory(), and McMd::McSimulation::mcMoveFactory().
The documentation for this class was generated from the following files:
SliplinkMcModule.h
SliplinkMcModule.cpp