Simpatico: DdMd::GroupCollector< N > Class Template Reference
DdMd::GroupCollector< N > Class Template Reference
DdMd namespace » MPI Communication
Detailed Description
template<int N>
class DdMd::GroupCollector< N >
Class for collecting Groups from processors to master processor.
An GroupCollector collects Group objects from all processors to the master processor in order to output a configuration file.
Usage:
GroupStorage<N> storage;
Domain domain;
Buffer buffer;
GroupCollector collector;
// Initialization
collector.associate(domain, storage, buffer);
// Communication
if (domain.gridRank() == 0) {  // if master processor
   collector.allocate(100);
   collector.setup();
   Group<N>* groupPtr = collector.nextPtr();
   while (groupPtr) {
      // Write *groupPtr to file;
      groupPtr = collector.nextPtr();
   }
} else { // if not master
   collector.send();
}
Definition at line 30 of file ddMd/analyzers/trajectory/TrajectoryWriter.h.
#include <GroupCollector.h>
Public Member Functions
GroupCollector ()
Constructor.
~GroupCollector ()
Destructor.
void associate (Domain &domain, GroupStorage< N > &storage, Buffer &buffer)
Initialize pointers to associated objects.
void setCapacity (int recvArrayCapacity)
Set size of cache for receiving groups on the master.
void setup ()
Setup master processor for receiving.
Group< N > * nextPtr ()
Return a pointer to the next available atom, or null.
void send ()
Send all groups on this processor to the master processor.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void readParameters (std::istream &in)
Read the body of parameter block, without begin and end lines.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Constructor & Destructor Documentation
template<int N> DdMd::GroupCollector< N >::GroupCollector ()
Constructor.
Definition at line 25 of file GroupCollector.tpp.
References Util::ParamComposite::setClassName().
template<int N> DdMd::GroupCollector< N >::~GroupCollector ()
Destructor.
Definition at line 41 of file GroupCollector.tpp.
Member Function Documentation
template<int N> void DdMd::GroupCollector< N >::associate (Domain & domain, GroupStorage< N > & storage, Buffer & buffer)
Initialize pointers to associated objects.
Call on all processors, only once.
Definition at line 48 of file GroupCollector.tpp.
template<int N> void DdMd::GroupCollector< N >::setCapacity (int recvArrayCapacity)
Set size of cache for receiving groups on the master.
The cache is actually allocated only on master processor, within the first call to the setup function. This function must be called once on the master. Calling it on other processors sets an unused variable, with no other effect, and thus does no harm.
Parameters
recvArrayCapacity capacity of recvArray cache on master.
Definition at line 60 of file GroupCollector.tpp.
References UTIL_THROW.
template<int N> void DdMd::GroupCollector< N >::setup ()
Setup master processor for receiving.
Call only on the master processor, just before receive loop.
Definition at line 75 of file GroupCollector.tpp.
References DdMd::Domain::isInitialized(), DdMd::Buffer::isInitialized(), DdMd::Domain::isMaster(), and UTIL_THROW.
Referenced by DdMd::ConfigIo::associate(), DdMd::SerializeConfigIo::loadConfig(), DdMd::DdMdConfigIo::readConfig(), DdMd::LammpsConfigIo::readConfig(), and DdMd::DdMdOrderedConfigIo::readConfig().
template<int N> Group< N > * DdMd::GroupCollector< N >::nextPtr ()
Return a pointer to the next available atom, or null.
Call only on the master processor, within loop over groups. This function return the address of the next available Group, or null if no more are available. Groups are returned in order of processor rank, starting with those on the master processor, then processor 1, etc.
The address returned is an address within an internal cache, which is then freed for reuse. All Group data must thus be copied to a permanent location before calling nextPtr() again.
Returns
address of next group, or null if no more are available.
Definition at line 114 of file GroupCollector.tpp.
References DdMd::Group< N >::atomPtr(), DdMd::Buffer::beginRecvBlock(), DdMd::Domain::communicator(), DdMd::Domain::grid(), DdMd::Atom::isGhost(), DdMd::Domain::isInitialized(), DdMd::Domain::isMaster(), DdMd::Buffer::recv(), DdMd::Buffer::recvSize(), Util::Grid::size(), and UTIL_THROW.
Referenced by DdMd::ConfigIo::associate(), DdMd::SerializeConfigIo::loadConfig(), DdMd::DdMdConfigIo::readConfig(), DdMd::LammpsConfigIo::readConfig(), and DdMd::DdMdOrderedConfigIo::readConfig().
template<int N> void DdMd::GroupCollector< N >::send ()
Send all groups on this processor to the master processor.
Call on all processors except the master (rank = 0) processor.
Definition at line 213 of file GroupCollector.tpp.
References DdMd::Buffer::beginSendBlock(), DdMd::Buffer::clearSendBuffer(), DdMd::Domain::communicator(), DdMd::Buffer::endSendBlock(), DdMd::Buffer::groupCapacity(), DdMd::Atom::isGhost(), DdMd::Domain::isInitialized(), DdMd::Buffer::isInitialized(), DdMd::Domain::isMaster(), DdMd::Buffer::send(), and UTIL_THROW.
Referenced by DdMd::ConfigIo::associate(), DdMd::SerializeConfigIo::loadConfig(), DdMd::DdMdConfigIo::readConfig(), DdMd::LammpsConfigIo::readConfig(), and DdMd::DdMdOrderedConfigIo::readConfig().
The documentation for this class was generated from the following files:
ddMd/analyzers/trajectory/TrajectoryWriter.h
GroupCollector.h
GroupCollector.tpp