Simpatico: McMd::EwaldRSpaceAccumulator Class Reference
McMd::EwaldRSpaceAccumulator Class Reference
McMd namespace » Potential Energies » Coulomb Potentials
Detailed Description
Utility class to store r-space Coulomb energy and stress.
Definition at line 20 of file EwaldRSpaceAccumulator.h.
#include <EwaldRSpaceAccumulator.h>
Public Member Functions
bool isSetEnergy () const
Is the r-space energy set?
bool isSetStress () const
Is the r-space stress set?
double rSpaceEnergy ()
Return the r-space energy (compute if necessary).
Tensor rSpaceStress ()
Return the r-space stress (compute if necessary).
Member Function Documentation
bool McMd::EwaldRSpaceAccumulator::isSetEnergy () const inline
Is the r-space energy set?
Definition at line 42 of file EwaldRSpaceAccumulator.h.
bool McMd::EwaldRSpaceAccumulator::isSetStress () const inline
Is the r-space stress set?
Definition at line 48 of file EwaldRSpaceAccumulator.h.
double McMd::EwaldRSpaceAccumulator::rSpaceEnergy ()
Return the r-space energy (compute if necessary).
Definition at line 13 of file EwaldRSpaceAccumulator.cpp.
References UTIL_CHECK.
Referenced by McMd::MdCoulombPotential::rSpaceEnergy().
Tensor McMd::EwaldRSpaceAccumulator::rSpaceStress ()
Return the r-space stress (compute if necessary).
Definition at line 25 of file EwaldRSpaceAccumulator.cpp.
References UTIL_CHECK.
Referenced by McMd::MdCoulombPotential::computeStress(), McMd::MdCoulombPotential::rSpaceStress(), and McMd::MdCoulombPotential::stress().
The documentation for this class was generated from the following files:
EwaldRSpaceAccumulator.h
EwaldRSpaceAccumulator.cpp