Simpatico: McMd::DCDTrajectoryReader Class Reference
McMd::DCDTrajectoryReader Class Reference
Detailed Description
TrajectoryReader for CHARMM ".dcd" data files.
It is assumed that the atoms belonging to all species and molecules of a species occur in the file consecutively. Currently it has only been tested with Hoomd generated trajectory files.
Definition at line 31 of file DCDTrajectoryReader.h.
#include <DCDTrajectoryReader.h>
Public Member Functions
DCDTrajectoryReader (System &system)
Constructor.
virtual ~DCDTrajectoryReader ()
Destructor.
void open (std::string filename)
Read trajectory file header and initialize simulation parameters.
bool readFrame ()
Read a single frame.
void close ()
Close trajectory file.
Public Member Functions inherited from McMd::TrajectoryReader
TrajectoryReader (System &system)
Constructor.
virtual ~TrajectoryReader ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from McMd::TrajectoryReader
System & system () const
Get a reference to the parent System.
Simulation & simulation () const
Get a reference to the parent Simulation.
Boundary & boundary () const
Get the Boundary.
virtual void addMolecules ()
Add all molecules to system.
Protected Attributes inherited from McMd::TrajectoryReader
int nAtomTotal_
Total number of atoms (all species)
Constructor & Destructor Documentation
McMd::DCDTrajectoryReader::DCDTrajectoryReader (System & system)
Constructor.
Definition at line 35 of file DCDTrajectoryReader.cpp.
McMd::DCDTrajectoryReader::~DCDTrajectoryReader () virtual
Destructor.
Definition at line 45 of file DCDTrajectoryReader.cpp.
Member Function Documentation
void McMd::DCDTrajectoryReader::open (std::string filename) virtual
Read trajectory file header and initialize simulation parameters.
Parameters
filename name of trajectory file
Implements McMd::TrajectoryReader.
Definition at line 55 of file DCDTrajectoryReader.cpp.
References McMd::TrajectoryReader::addMolecules(), Util::DArray< Data >::allocate(), McMd::TrajectoryReader::nAtomTotal_, and UTIL_THROW.
bool McMd::DCDTrajectoryReader::readFrame () virtual
Read a single frame.
Frames are assumed to be read consecutively.
Returns
true if this frame exists, false if at end
Implements McMd::TrajectoryReader.
Definition at line 91 of file DCDTrajectoryReader.cpp.
References McMd::Molecule::begin(), McMd::TrajectoryReader::boundary(), McMd::Species::capacity(), Util::Array< Data >::cArray(), McMd::System::molecule(), Util::ArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::OrthorhombicBoundary::setOrthorhombic(), Util::OrthorhombicBoundary::shift(), McMd::TrajectoryReader::simulation(), McMd::Simulation::species(), McMd::TrajectoryReader::system(), and UTIL_THROW.
void McMd::DCDTrajectoryReader::close () virtual
Close trajectory file.
Implements McMd::TrajectoryReader.
Definition at line 205 of file DCDTrajectoryReader.cpp.
The documentation for this class was generated from the following files:
DCDTrajectoryReader.h
DCDTrajectoryReader.cpp