Simpatico: McMd::Tether Class Reference
McMd::Tether Class Reference
Tethers
Detailed Description
A Tether represents an interaction between an Atom and an anchor position.
An active Tether has an anchor position Vector and a pointer to an associated Atom. A Tether represents an interaction that depends upon the distance between the atom and the anchor position, but does not define the interaction potential.
A Tether object may also optionally be associated with another Tether, its partner, as done in some slip-link algorithms.
All non-const mutator methods of Tether are private, and are called only by the friend class TetherMaster. Outside of the implementation of TetherMaster, a Tether is thus a read-only object.
Definition at line 37 of file Tether.h.
#include <Tether.h>
Public Member Functions
Tether ()
Constructor.
const Vector & anchor () const
Get anchor position Vector by reference.
Atom & atom () const
Get the tethered Atom by reference.
int typeId () const
Get the tether type id.
Tether & partner () const
Get the partner (if any) by reference.
bool hasAtom () const
Is this Tether associated with Atom?
bool hasPartner () const
Is Tether associated with a partner Tether?
Constructor & Destructor Documentation
McMd::Tether::Tether () [inline]
Constructor.
Definition at line 151 of file Tether.h.
Member Function Documentation
const Vector & McMd::Tether::anchor () const [inline]
Get anchor position Vector by reference.
Definition at line 197 of file Tether.h.
Referenced by McMd::McMdConfigIo::write().
Atom & McMd::Tether::atom () const [inline]
Get the tethered Atom by reference.
Definition at line 203 of file Tether.h.
Referenced by McMd::TetherMaster::isValid(), McMd::TetherMaster::removeTether(), McMd::TetherMaster::transferTether(), and McMd::McMdConfigIo::write().
int McMd::Tether::typeId () const [inline]
Get the tether type id.
Definition at line 209 of file Tether.h.
Tether & McMd::Tether::partner () const [inline]
Get the partner (if any) by reference.
Definition at line 215 of file Tether.h.
Referenced by McMd::TetherMaster::isValid().
bool McMd::Tether::hasAtom () const [inline]
Is this Tether associated with Atom?
Definition at line 221 of file Tether.h.
Referenced by McMd::TetherMaster::isValid(), McMd::TetherMaster::pairTethers(), McMd::TetherMaster::removeTether(), and McMd::TetherMaster::transferTether().
bool McMd::Tether::hasPartner () const [inline]
Is Tether associated with a partner Tether?
Definition at line 227 of file Tether.h.
Referenced by McMd::TetherMaster::isValid(), and McMd::TetherMaster::pairTethers().
The documentation for this class was generated from the following file:
Tether.h