Simpatico: McMd::RingOctaRebridgeMove Class Reference
McMd::RingOctaRebridgeMove Class Reference
Monte Carlo Moves
Detailed Description
Molecule rebridging move for a Ring species.
The exchange of positions of two closely approaching atoms is attempted. Each atom is bonded to two other atoms. The move requires that the 6 atoms form an octahedron in which the edge lengths satisfying certain distance criterions, before the exchange is attempted.
Definition at line 32 of file RingOctaRebridgeMove.h.
#include <RingOctaRebridgeMove.h>
Public Member Functions
RingOctaRebridgeMove (McSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read species to which displacement is applied.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to an archive.
virtual bool move ()
Generate and accept or reject configuration bias move.
Public Member Functions inherited from McMd::GroupRebridgeBase
GroupRebridgeBase (McSystem &system)
Constructor.
virtual ~GroupRebridgeBase ()
Destructor.
void tetraEnergy (Atom *aPtr, Atom *bPtr, Atom *cPtr, Atom *dPtr, int bondType, double &energy)
Calculate the energy cost for rebriding a tetra group.
double angleEnergy (const Atom &a, const Atom &b, const Atom &c, int type)
Calculate the angle energy for a bead triple.
void octaEnergy (Atom *aPtr, Atom *bPtr, Atom *cPtr, Atom *dPtr, Atom *mPtr, Atom *nPtr, int bondType, double &energy)
Calculate the energy cost for rebriding an octa group.
Public Member Functions inherited from McMd::SystemMove
SystemMove (McSystem &system)
Constructor.
virtual ~SystemMove ()
Destructor.
Public Member Functions inherited from McMd::McMove
McMove (Simulation &simulation)
Constructor.
virtual ~McMove ()
Destructor.
void setProbability (double probability)
Set the probability for this McMove.
virtual void setup ()
Setup before the beginning of each simulation run.
double probability () const
Return probability for this McMove.
long nAttempt () const
Return number of moves that have been attempted.
long nAccept () const
Return number of moves that have been accepted.
virtual void output ()
Output statistics for this move (called at the end of the simulation)
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
bool scanBridge (Molecule *molPtr, int mId, int &molId2, int &nId)
Scan potential rebridging sites.
int modId (int id, int n)
Shift Atom index along a Ring.
Protected Attributes
int speciesId_
Integer index for molecular species.
double upperBridge_
Upper bounds for trial length of a bridge.
double lowerBridge_
Lower bounds for trial length of a bridge.
CellList::NeighborArray neighbors_
Neighbor list around test atom.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Constructor & Destructor Documentation
McMd::RingOctaRebridgeMove::RingOctaRebridgeMove (McSystem & system)
Constructor.
Definition at line 32 of file RingOctaRebridgeMove.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::RingOctaRebridgeMove::readParameters (std::istream & in) virtual
Read species to which displacement is applied.
Reimplemented from McMd::McMove.
Definition at line 42 of file RingOctaRebridgeMove.cpp.
References lowerBridge_, McMd::McMove::readProbability(), McMd::McMove::simulation(), McMd::Simulation::species(), speciesId_, upperBridge_, and UTIL_THROW.
void McMd::RingOctaRebridgeMove::loadParameters (Serializable::IArchive & ar) virtual
Load state from an archive.
Parameters
ar loading (input) archive.
Reimplemented from McMd::McMove.
Definition at line 61 of file RingOctaRebridgeMove.cpp.
References McMd::McMove::loadParameters(), lowerBridge_, McMd::McMove::simulation(), McMd::Simulation::species(), speciesId_, upperBridge_, and UTIL_THROW.
void McMd::RingOctaRebridgeMove::save (Serializable::OArchive & ar) virtual
Save state to an archive.
Parameters
ar saving (output) archive.
Reimplemented from McMd::McMove.
Definition at line 79 of file RingOctaRebridgeMove.cpp.
References lowerBridge_, McMd::McMove::save(), speciesId_, and upperBridge_.
bool McMd::RingOctaRebridgeMove::move () virtual
Generate and accept or reject configuration bias move.
Reimplemented from McMd::McMove.
Definition at line 97 of file RingOctaRebridgeMove.cpp.
References McMd::Molecule::atom(), McMd::McSystem::atomPotentialEnergy(), McMd::SystemMove::boltzmann(), McMd::McMove::incrementNAccept(), McMd::McMove::incrementNAttempt(), Util::Random::metropolis(), McMd::System::molecule(), McMd::Molecule::nAtom(), McMd::McSystem::pairPotential(), McMd::Atom::position(), McMd::McMove::random(), McMd::System::randomMolecule(), scanBridge(), speciesId_, McMd::SystemMove::system(), Util::Random::uniformInt(), and McMd::McPairPotential::updateAtomCell().
bool McMd::RingOctaRebridgeMove::scanBridge (Molecule * molPtr, int mId, int & molId2, int & nId) protected
Scan potential rebridging sites.
Parameters
molPtr Pointer to the first molecule.
mId The middle atom Id on the first molecule.
molId2 The index of the second molecule.
nId The middle atom Id on the second molecule.
Definition at line 178 of file RingOctaRebridgeMove.cpp.
References McMd::Molecule::atom(), McMd::SystemMove::boundary(), McMd::McPairPotential::cellList(), Util::OrthorhombicBoundary::distanceSq(), McMd::CellList::getNeighbors(), McMd::Molecule::id(), McMd::Species::id(), McMd::Atom::indexInMolecule(), lowerBridge_, modId(), McMd::Atom::molecule(), McMd::System::molecule(), McMd::Molecule::nAtom(), neighbors_, McMd::McSystem::pairPotential(), McMd::Atom::position(), McMd::McMove::random(), Util::FSArray< Data, Capacity >::size(), McMd::Molecule::species(), speciesId_, McMd::SystemMove::system(), Util::Random::uniformInt(), and upperBridge_.
Referenced by move().
int McMd::RingOctaRebridgeMove::modId (int id, int n) inline protected
Shift Atom index along a Ring.
Parameters
id Atom id to be regulated, which can be negative.
n Number of atoms in the Ring.
Definition at line 102 of file RingOctaRebridgeMove.h.
Referenced by scanBridge().
Member Data Documentation
int McMd::RingOctaRebridgeMove::speciesId_ protected
Integer index for molecular species.
Definition at line 69 of file RingOctaRebridgeMove.h.
Referenced by loadParameters(), move(), readParameters(), save(), and scanBridge().
double McMd::RingOctaRebridgeMove::upperBridge_ protected
Upper bounds for trial length of a bridge.
Definition at line 72 of file RingOctaRebridgeMove.h.
Referenced by loadParameters(), readParameters(), save(), and scanBridge().
double McMd::RingOctaRebridgeMove::lowerBridge_ protected
Lower bounds for trial length of a bridge.
Definition at line 75 of file RingOctaRebridgeMove.h.
Referenced by loadParameters(), readParameters(), save(), and scanBridge().
CellList::NeighborArray McMd::RingOctaRebridgeMove::neighbors_ protected
Neighbor list around test atom.
Definition at line 78 of file RingOctaRebridgeMove.h.
Referenced by scanBridge().
The documentation for this class was generated from the following files:
RingOctaRebridgeMove.h
RingOctaRebridgeMove.cpp