Simpatico: DdMd::AtomType Class Reference
DdMd::AtomType Class Reference
Chemical Structure
Detailed Description
Descriptor for a type of Atom.
An AtomTypeType has a mass, a name string, and an integer id. [It will later acquire a charge.]
Definition at line 26 of file ddMd/chemistry/AtomType.h.
#include <AtomType.h>
Public Member Functions
AtomType ()
Constructor.
Mutators
void setId (int Id)
Set the type index.
void setMass (double mass)
Set the mass.
void setName (std::string name)
Set the name string.
Accessors
double mass () const
Get the mass.
const std::string & name () const
Get the name string.
int id () const
Get the index.
Static Public Member Functions
static void initStatic ()
Call this to guarantee initialization of static data.
Friends
std::istream & operator>> (std::istream &in, AtomType &atomType)
istream extractor (>>) for an AtomType.
std::ostream & operator<< (std::ostream &out, const AtomType &atomType)
ostream inserter (<<) for an AtomType.
template<class Archive >
void serialize (Archive &ar, AtomType &atomType, const unsigned int version)
Serialize an AtomType.
Constructor & Destructor Documentation
DdMd::AtomType::AtomType ()
Constructor.
Definition at line 20 of file ddMd/chemistry/AtomType.cpp.
Member Function Documentation
void DdMd::AtomType::setId (int Id)
Set the type index.
Parameters
Id integer index.
Definition at line 27 of file ddMd/chemistry/AtomType.cpp.
References id().
void DdMd::AtomType::setMass (double mass) inline
Set the mass.
Parameters
mass atom mass
Definition at line 106 of file ddMd/chemistry/AtomType.h.
References mass().
void DdMd::AtomType::setName (std::string name) inline
Set the name string.
Parameters
name name string
Definition at line 110 of file ddMd/chemistry/AtomType.h.
References name().
double DdMd::AtomType::mass () const inline
Get the mass.
Definition at line 114 of file ddMd/chemistry/AtomType.h.
Referenced by setMass(), DdMd::NvtIntegrator::setup(), DdMd::NveIntegrator::setup(), DdMd::NphIntegrator::setup(), and DdMd::NptIntegrator::setup().
const std::string & DdMd::AtomType::name () const inline
Get the name string.
Definition at line 118 of file ddMd/chemistry/AtomType.h.
Referenced by setName().
int DdMd::AtomType::id () const inline
Get the index.
Definition at line 122 of file ddMd/chemistry/AtomType.h.
Referenced by setId().
void DdMd::AtomType::initStatic () static
Call this to guarantee initialization of static data.
Definition at line 58 of file ddMd/chemistry/AtomType.cpp.
Referenced by DdMd::Simulation::Simulation().
Friends And Related Function Documentation
std::istream& operator>> (std::istream & in, AtomType & atomType) friend
istream extractor (>>) for an AtomType.
Format:
name mass
Parameters
in input stream
atomType AtomType to be read from stream
Returns
modified input stream
Definition at line 33 of file ddMd/chemistry/AtomType.cpp.
std::ostream& operator<< (std::ostream & out, const AtomType & atomType) friend
ostream inserter (<<) for an AtomType.
Format, one one line with no line break:
name mass
Parameters
out output stream
atomType AtomType to be written to stream
Returns
modified output stream
Definition at line 43 of file ddMd/chemistry/AtomType.cpp.
template<class Archive > void serialize (Archive & ar, AtomType & atomType, const unsigned int version) friend
Serialize an AtomType.
Parameters
ar archive
atomType object to be serialized
version archive version id
Definition at line 161 of file ddMd/chemistry/AtomType.h.
The documentation for this class was generated from the following files:
ddMd/chemistry/AtomType.h
ddMd/chemistry/AtomType.cpp