Simpatico: McMd::DiagnosticManager Class Reference
McMd::DiagnosticManager Class Reference
Managers | Diagnostics
Detailed Description
Manager for a list of Diagnostic objects.
Definition at line 25 of file mcMd/diagnostics/DiagnosticManager.h.
#include <DiagnosticManager.h>
Public Member Functions
DiagnosticManager ()
Constructor.
virtual ~DiagnosticManager ()
Destructor.
virtual void readParam (std::istream &in)
Read parameter file.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to an archive.
void setup ()
Call initialize method of each Diagnostic.
void sample (long iStep)
Call sample method of each Diagnostic.
void output ()
Call output method of each diagnostic.
Constructor & Destructor Documentation
McMd::DiagnosticManager::DiagnosticManager ()
Constructor.
Definition at line 23 of file mcMd/diagnostics/DiagnosticManager.cpp.
References Util::ParamComposite::setClassName().
McMd::DiagnosticManager::~DiagnosticManager () [virtual]
Destructor.
Definition at line 30 of file mcMd/diagnostics/DiagnosticManager.cpp.
Member Function Documentation
void McMd::DiagnosticManager::readParam (std::istream & in) [virtual]
Read parameter file.
Parameters:
in input parameter file stream.
Reimplemented from Util::Manager< Diagnostic >.
Definition at line 38 of file mcMd/diagnostics/DiagnosticManager.cpp.
References McMd::Diagnostic::baseInterval, Util::Manager< Diagnostic >::beginReadManager(), Util::Manager< Diagnostic >::endReadManager(), and Util::Manager< Diagnostic >::readChildren().
void McMd::DiagnosticManager::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from Util::Manager< Diagnostic >.
Definition at line 81 of file mcMd/diagnostics/DiagnosticManager.cpp.
References McMd::Diagnostic::baseInterval.
void McMd::DiagnosticManager::save (Serializable::OArchive & ar) [virtual]
Save state to an archive.
Parameters:
ar saving (output) archive.
Reimplemented from Util::Manager< Diagnostic >.
Definition at line 90 of file mcMd/diagnostics/DiagnosticManager.cpp.
References McMd::Diagnostic::baseInterval.
Referenced by McMd::MdSimulation::save(), and McMd::McSimulation::save().
void McMd::DiagnosticManager::setup ()
Call initialize method of each Diagnostic.
This method should be called just before the main simulation loop, after an initial configuration is known.
Definition at line 49 of file mcMd/diagnostics/DiagnosticManager.cpp.
References Util::Manager< Diagnostic >::size().
Referenced by McMd::McSimulation::analyze(), McMd::MdSimulation::analyzeDumps(), McMd::MdSimulation::analyzeTrajectory(), McMd::McSimulation::simulate(), and McMd::MdSimulation::simulate().
void McMd::DiagnosticManager::sample (long iStep)
Call sample method of each Diagnostic.
Definition at line 59 of file mcMd/diagnostics/DiagnosticManager.cpp.
References McMd::Diagnostic::baseInterval, and Util::Manager< Diagnostic >::size().
Referenced by McMd::McSimulation::analyze(), McMd::MdSimulation::analyzeDumps(), McMd::MdSimulation::analyzeTrajectory(), McMd::McSimulation::simulate(), and McMd::MdSimulation::simulate().
void McMd::DiagnosticManager::output ()
Call output method of each diagnostic.
Definition at line 71 of file mcMd/diagnostics/DiagnosticManager.cpp.
References Util::Manager< Diagnostic >::size().
Referenced by McMd::McSimulation::analyze(), McMd::MdSimulation::analyzeDumps(), McMd::MdSimulation::analyzeTrajectory(), McMd::McSimulation::simulate(), and McMd::MdSimulation::simulate().
The documentation for this class was generated from the following files:
mcMd/diagnostics/DiagnosticManager.h
mcMd/diagnostics/DiagnosticManager.cpp