Simpatico: SpAn::AnalyzerManager Class Reference
SpAn::AnalyzerManager Class Reference
Analyzers
Detailed Description
Manager for a list of Analyzer objects.
Definition at line 26 of file spAn/analyzers/AnalyzerManager.h.
#include <AnalyzerManager.h>
Public Member Functions
AnalyzerManager (Processor &processor)
Constructor.
virtual ~AnalyzerManager ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameter block (without begin and end).
void setup ()
Call setup method of each Analyzer.
void clear ()
Call clear method of each Analyzer.
void sample (long iStep)
Call sample method of each Analyzer, if scheduled.
void output ()
Call output method of each analyzer.
virtual Factory< Analyzer > * newDefaultFactory () const
Return pointer to a new default factory.
Constructor & Destructor Documentation
SpAn::AnalyzerManager::AnalyzerManager (Processor & processor)
Constructor.
Definition at line 22 of file spAn/analyzers/AnalyzerManager.cpp.
References Util::ParamComposite::setClassName().
SpAn::AnalyzerManager::~AnalyzerManager () [virtual]
Destructor.
Definition at line 30 of file spAn/analyzers/AnalyzerManager.cpp.
Member Function Documentation
void SpAn::AnalyzerManager::readParameters (std::istream & in) [virtual]
Read parameter block (without begin and end).
Parameters:
in input parameter file stream.
Reimplemented from Util::Manager< Analyzer >.
Definition at line 38 of file spAn/analyzers/AnalyzerManager.cpp.
void SpAn::AnalyzerManager::setup ()
Call setup method of each Analyzer.
Definition at line 46 of file spAn/analyzers/AnalyzerManager.cpp.
References Util::Manager< Analyzer >::size().
Referenced by SpAn::Processor::analyzeDumps().
void SpAn::AnalyzerManager::clear ()
Call clear method of each Analyzer.
Definition at line 56 of file spAn/analyzers/AnalyzerManager.cpp.
References Util::Manager< Analyzer >::size().
void SpAn::AnalyzerManager::sample (long iStep)
Call sample method of each Analyzer, if scheduled.
Calls sample methods of each analyzer only if iStep is a multiple of the analyzer interval
Parameters:
iStep time step counter
Definition at line 66 of file spAn/analyzers/AnalyzerManager.cpp.
References Util::Manager< Analyzer >::size().
Referenced by SpAn::Processor::analyzeDumps().
void SpAn::AnalyzerManager::output ()
Call output method of each analyzer.
Definition at line 78 of file spAn/analyzers/AnalyzerManager.cpp.
References Util::Manager< Analyzer >::size().
Referenced by SpAn::Processor::analyzeDumps().
Factory< Analyzer > * SpAn::AnalyzerManager::newDefaultFactory () const [virtual]
Return pointer to a new default factory.
Implements Util::Manager< Analyzer >.
Definition at line 88 of file spAn/analyzers/AnalyzerManager.cpp.
The documentation for this class was generated from the following files:
spAn/analyzers/AnalyzerManager.h
spAn/analyzers/AnalyzerManager.cpp