Simpatico: DdMd::LammpsDumpWriter Class Reference
DdMd::LammpsDumpWriter Class Reference
Detailed Description
Write a trajectory in the Lammps dump format.
Definition at line 23 of file ddMd/analyzers/LammpsDumpWriter.h.
#include <LammpsDumpWriter.h>
Public Member Functions
LammpsDumpWriter (Simulation &simulation)
Constructor.
virtual ~LammpsDumpWriter ()
Destructor.
void writeFrame (std::ofstream &file, long iStep)
Read a single frame.
Constructor & Destructor Documentation
DdMd::LammpsDumpWriter::LammpsDumpWriter (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object
Definition at line 24 of file ddMd/analyzers/LammpsDumpWriter.cpp.
DdMd::LammpsDumpWriter::~LammpsDumpWriter () [virtual]
Destructor.
Definition at line 31 of file ddMd/analyzers/LammpsDumpWriter.cpp.
Member Function Documentation
void Tools::LammpsDumpWriter::writeFrame (std::ofstream & file, long iStep) [virtual]
Read a single frame.
Frames are assumed to be read consecutively.
Parameters:
file output file stream
iStep MD time step index
Implements DdMd::TrajectoryWriter.
Definition at line 37 of file ddMd/analyzers/LammpsDumpWriter.cpp.
References DdMd::TrajectoryWriter::atomCollector(), DdMd::TrajectoryWriter::atomStorage(), DdMd::TrajectoryWriter::boundary(), DdMd::AtomStorage::computeNAtomTotal(), Util::Dimension, DdMd::TrajectoryWriter::domain(), DdMd::Atom::id(), DdMd::AtomStorage::isCartesian(), Util::OrthorhombicBoundary::lengths(), DdMd::AtomStorage::nAtomTotal(), DdMd::AtomCollector::nextPtr(), DdMd::Atom::position(), DdMd::AtomCollector::send(), DdMd::AtomCollector::setup(), Util::OrthorhombicBoundary::transformGenToCart(), and DdMd::Atom::typeId().
The documentation for this class was generated from the following files:
ddMd/analyzers/LammpsDumpWriter.h
ddMd/analyzers/LammpsDumpWriter.cpp
tools/analyzers/LammpsDumpWriter.cpp