Simpatico: Inter::HarmonicL0Bond Class Reference
Inter::HarmonicL0Bond Class Reference
Bond Interactions
Detailed Description
A harmonic bond potential with zero rest length.
See also:
HarmonicL0Bond
Bond Interaction Class Interface
Definition at line 31 of file HarmonicL0Bond.h.
#include <HarmonicL0Bond.h>
Public Member Functions
HarmonicL0Bond ()
Constructor.
HarmonicL0Bond (const HarmonicL0Bond &other)
Copy constructor.
HarmonicL0Bond & operator= (const HarmonicL0Bond &other)
Assignment.
void setNBondType (int nBondType)
Set the number of bond types.
void readParameters (std::istream &in)
Read bond interaction parameters from input stream.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
double energy (double rSq, int type) const
Returns potential energy for one bond.
double forceOverR (double rSq, int type) const
Returns force/distance for one bond, for use in MD.
double randomBondLength (Random *random, double beta, int type) const
Return bond length chosen from equilibrium distribution.
void set (std::string name, int type, double value)
Modify a parameter, identified by a string.
double stiffness (int bondType) const
Returns bond stiffness.
double get (std::string name, int type) const
Get a parameter value, identified by a string.
Constructor & Destructor Documentation
Inter::HarmonicL0Bond::HarmonicL0Bond ()
Constructor.
Definition at line 19 of file HarmonicL0Bond.cpp.
References Util::ParamComposite::setClassName().
Inter::HarmonicL0Bond::HarmonicL0Bond (const HarmonicL0Bond & other)
Copy constructor.
Definition at line 31 of file HarmonicL0Bond.cpp.
Member Function Documentation
HarmonicL0Bond & Inter::HarmonicL0Bond::operator= (const HarmonicL0Bond & other)
Assignment.
Definition at line 42 of file HarmonicL0Bond.cpp.
void Inter::HarmonicL0Bond::setNBondType (int nBondType)
Set the number of bond types.
Parameters:
nBondType number of bond types
Definition at line 54 of file HarmonicL0Bond.cpp.
References UTIL_THROW.
void Inter::HarmonicL0Bond::readParameters (std::istream & in) [virtual]
Read bond interaction parameters from input stream.
Format: kappa CArray<double>
Precondition:
nBondType must be set, by calling setNBondType().
Parameters:
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 65 of file HarmonicL0Bond.cpp.
References UTIL_THROW.
void Inter::HarmonicL0Bond::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 78 of file HarmonicL0Bond.cpp.
References UTIL_THROW.
void Inter::HarmonicL0Bond::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 90 of file HarmonicL0Bond.cpp.
References Util::BinaryFileOArchive::pack().
double Inter::HarmonicL0Bond::energy (double rSq, int type) const [inline]
Returns potential energy for one bond.
Parameters:
rSq square of distance between bonded particles.
type type of bond.
Definition at line 166 of file HarmonicL0Bond.h.
double Inter::HarmonicL0Bond::forceOverR (double rSq, int type) const [inline]
Returns force/distance for one bond, for use in MD.
A positive return value represents a repulsive radial force.
Parameters:
rSq square of distance between bonded particles.
type type of bond.
Returns:
scalar repulsive force divided by distance.
Definition at line 173 of file HarmonicL0Bond.h.
double Inter::HarmonicL0Bond::randomBondLength (Random * random, double beta, int type) const
Return bond length chosen from equilibrium distribution.
This function returns a bond length chosen from the Boltzmann distribution of lengths for bonds of random orientation. The distribution P(l) of values of the length l is proportional to l*l*exp[-beta*phi(l) ], where phi(l) is the bond energy.
Parameters:
random pointer to random number generator object.
beta inverse temperature
type bond type
Returns:
random bond length chosen from equilibrium distribution.
Definition at line 103 of file HarmonicL0Bond.cpp.
References Util::Random::gaussian().
void Inter::HarmonicL0Bond::set (std::string name, int type, double value)
Modify a parameter, identified by a string.
Parameters:
name parameter name
type bond type index
value new value of parameter
Definition at line 116 of file HarmonicL0Bond.cpp.
References UTIL_THROW.
double Inter::HarmonicL0Bond::stiffness (int bondType) const [inline]
Returns bond stiffness.
Definition at line 157 of file HarmonicL0Bond.h.
double Inter::HarmonicL0Bond::get (std::string name, int type) const
Get a parameter value, identified by a string.
Parameters:
name parameter name
type bond type index
Definition at line 128 of file HarmonicL0Bond.cpp.
References UTIL_THROW.
The documentation for this class was generated from the following files:
HarmonicL0Bond.h
HarmonicL0Bond.cpp