Simpatico: Tools::Analyzer Class Reference
Tools::Analyzer Class Reference
Analyzers
Detailed Description
Abstract base for periodic output and/or analysis actions.
The periodic action of an Analyzer can involve sampling of a physical property and adding it to statistical accumulator, outputting it to file, or both. This periodic action must be implemented by the pure virtual sample() method.
The sample() method should take the desired action only when the configuration step index is an integer multiple of the associated interval parameter.
The virtual sample() method does not take any parameters. An Analyzer must thus access its parent Configuration via a pointer, which is usually initialized in its subclass constructor.
Definition at line 45 of file tools/analyzers/Analyzer.h.
#include <Analyzer.h>
Public Member Functions
Analyzer (Configuration &configuration)
Constructor.
Analyzer (Processor &processor)
Constructor.
Analyzer (Configuration &configuration, FileMaster &fileMaster)
Constructor.
virtual ~Analyzer ()
Destructor.
virtual void setup ()
Setup before configuration.
virtual void clear ()
Clear statistical accumulators.
virtual void sample (long iStep)=0
Calculate, analyze and/or output a physical quantity.
virtual void output ()
Output any results at the end of an analysis.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Protected Member Functions
void readInterval (std::istream &in)
Read parameter interval from file.
void readOutputFileName (std::istream &in)
Read outputFileName from file.
Configuration & configuration ()
Get the parent Configuration by reference.
FileMaster & fileMaster ()
Get an associated FileMaster by reference.
const std::string & outputFileName () const
Return outputFileName string.
std::string outputFileName (const std::string &suffix) const
Return outputFileName string with added suffix.
Constructor & Destructor Documentation
Tools::Analyzer::Analyzer (Configuration & configuration)
Constructor.
Parameters:
configuration parent Configuration object
Definition at line 21 of file tools/analyzers/Analyzer.cpp.
Tools::Analyzer::Analyzer (Processor & processor)
Constructor.
Parameters:
processor parent Processor object
Definition at line 33 of file tools/analyzers/Analyzer.cpp.
Tools::Analyzer::Analyzer (Configuration & configuration, FileMaster & fileMaster)
Constructor.
Parameters:
configuration parent Configuration
fileMaster associated Util::FileMaster object
Definition at line 45 of file tools/analyzers/Analyzer.cpp.
Tools::Analyzer::~Analyzer () [virtual]
Destructor.
Definition at line 57 of file tools/analyzers/Analyzer.cpp.
Member Function Documentation
virtual void Tools::Analyzer::setup () [inline, virtual]
Setup before configuration.
This method is called just before the beginning of the main loop. It may be used to complete any initialization or checks that require knowledge of the configuration.
The default implementation is empty.
Reimplemented in Tools::TrajectoryWriter, Tools::AtomMSD, and Tools::LogStep.
Definition at line 88 of file tools/analyzers/Analyzer.h.
virtual void Tools::Analyzer::clear () [inline, virtual]
Clear statistical accumulators.
The default implementation is empty.
Reimplemented in Tools::TrajectoryWriter.
Definition at line 96 of file tools/analyzers/Analyzer.h.
virtual void Tools::Analyzer::sample (long iStep) [pure virtual]
Calculate, analyze and/or output a physical quantity.
Take an action if iStep is a multiple of interval. If iStep is not a multiple of interval, this method should do nothing and return immediately.
Parameters:
iStep current step index.
Implemented in Tools::TrajectoryWriter, Tools::AtomMSD, and Tools::LogStep.
virtual void Tools::Analyzer::output () [inline, virtual]
Output any results at the end of an analysis.
The default implementation is empty.
Reimplemented in Tools::TrajectoryWriter, Tools::AtomMSD, and Tools::LogStep.
Definition at line 115 of file tools/analyzers/Analyzer.h.
int Tools::Analyzer::interval () const [inline]
Get interval value.
Definition at line 196 of file tools/analyzers/Analyzer.h.
bool Tools::Analyzer::isAtInterval (long counter) const [inline]
Return true iff counter is a multiple of the interval.
Parameters:
counter configuration step counter
Definition at line 202 of file tools/analyzers/Analyzer.h.
Referenced by Tools::AtomMSD::sample(), and Tools::TrajectoryWriter::sample().
void Tools::Analyzer::readInterval (std::istream & in) [protected]
Read parameter interval from file.
This function throws an exception if the value of interval is not a multiple of Analyzer::baseInterval, or if baseInterval has not been set to a nonzero positive value.
Parameters:
in input parameter file stream.
Definition at line 69 of file tools/analyzers/Analyzer.cpp.
References UTIL_THROW.
Referenced by Tools::AtomMSD::readParameters(), and Tools::TrajectoryWriter::readParameters().
void Tools::Analyzer::readOutputFileName (std::istream & in) [protected]
Read outputFileName from file.
Parameters:
in input parameter file
Definition at line 88 of file tools/analyzers/Analyzer.cpp.
Referenced by Tools::AtomMSD::readParameters(), and Tools::TrajectoryWriter::readParameters().
Configuration & Tools::Analyzer::configuration () [inline, protected]
Get the parent Configuration by reference.
Definition at line 214 of file tools/analyzers/Analyzer.h.
Referenced by Tools::AtomMSD::readParameters(), Tools::AtomMSD::sample(), and Tools::AtomMSD::setup().
FileMaster & Tools::Analyzer::fileMaster () [protected]
Get an associated FileMaster by reference.
Definition at line 104 of file tools/analyzers/Analyzer.cpp.
Referenced by Tools::AtomMSD::output(), and Tools::TrajectoryWriter::setup().
const std::string & Tools::Analyzer::outputFileName () const [inline, protected]
Return outputFileName string.
Definition at line 208 of file tools/analyzers/Analyzer.h.
Referenced by Tools::AtomMSD::output(), and Tools::TrajectoryWriter::setup().
std::string Tools::Analyzer::outputFileName (const std::string & suffix) const [protected]
Return outputFileName string with added suffix.
Definition at line 94 of file tools/analyzers/Analyzer.cpp.
The documentation for this class was generated from the following files:
tools/analyzers/Analyzer.h
tools/analyzers/Analyzer.cpp