Simpatico: Util::Blank Class Reference
Util::Blank Class Reference
Parameter File IO
Detailed Description
An empty line within a parameter file.
A Param represents an empty line within a file format that is represented as a ParamComposite.
Definition at line 24 of file Blank.h.
#include <Blank.h>
Public Member Functions
Blank ()
Constructor.
virtual ~Blank ()
Virtual Destructor.
virtual void readParam (std::istream &in)
Read a blank line.
virtual void writeParam (std::ostream &out)
Write a blank line.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
virtual void load (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void resetParam ()
Nontrivial implementation provided by ParamComposite subclass.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have a communicator?
MPI::Intracomm & ioCommunicator () const
Get the communicator.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Constructor & Destructor Documentation
Util::Blank::Blank ()
Constructor.
Definition at line 17 of file Blank.cpp.
Util::Blank::~Blank () virtual
Virtual Destructor.
Definition at line 22 of file Blank.cpp.
Member Function Documentation
void Util::Blank::readParam (std::istream & in) virtual
Read a blank line.
Parameters
in input stream
Implements Util::ParamComponent.
Definition at line 30 of file Blank.cpp.
References Util::ParamComponent::echo(), Util::Log::file(), Util::MpiFileIo::isIoProcessor(), and writeParam().
Referenced by Util::ParamComposite::readBlank().
void Util::Blank::writeParam (std::ostream & out) virtual
Write a blank line.
Parameters
out output stream
Implements Util::ParamComponent.
Definition at line 46 of file Blank.cpp.
Referenced by readParam().
The documentation for this class was generated from the following files:
Blank.h
Blank.cpp