Simpatico: DdMd::TrajectoryWriter Class Reference
DdMd::TrajectoryWriter Class Reference
Analyzers
Detailed Description
Based class for classes that write trajectories to a single file.
Definition at line 39 of file ddMd/analyzers/TrajectoryWriter.h.
#include <TrajectoryWriter.h>
Public Member Functions
TrajectoryWriter (Simulation &simulation, bool isBinary=false)
Constructor.
virtual ~TrajectoryWriter ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters and initialize.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void setup ()
Open the trajectory file.
virtual void sample (long iStep)
Dump configuration to file.
virtual void clear ()
Clear nSample counter.
virtual void output ()
Close ouput file.
Protected Member Functions
bool isBinary () const
Is the file format binary (true) or text (false)?
virtual void writeHeader (std::ofstream &out)
Write data that should appear once, at beginning of the file.
virtual void writeFrame (std::ofstream &out, long iStep)=0
Write data that should appear in every frame.
Domain & domain ()
Get the Domain by reference.
Boundary & boundary ()
Get Boundary by reference.
AtomStorage & atomStorage ()
Get AtomStorage by reference.
AtomCollector & atomCollector ()
Get the AtomCollector by reference.
BondStorage & bondStorage ()
Get BondStorage by reference.
GroupCollector< 2 > & bondCollector ()
Get the bond collector by reference.
AngleStorage & angleStorage ()
Get AngleStorage by reference.
GroupCollector< 3 > & angleCollector ()
Get the angle collector by reference.
DihedralStorage & dihedralStorage ()
Get DihedralStorage by reference.
GroupCollector< 4 > & dihedralCollector ()
Get the dihedral collector by reference.
Constructor & Destructor Documentation
DdMd::TrajectoryWriter::TrajectoryWriter (Simulation & simulation, bool isBinary = false)
Constructor.
Parameters:
simulation parent Simulation object
isBinary Is the trajectory file a binary file?
Definition at line 23 of file ddMd/analyzers/TrajectoryWriter.cpp.
References DdMd::Simulation::angleStorage(), DdMd::Simulation::atomStorage(), DdMd::Simulation::bondStorage(), DdMd::Simulation::boundary(), DdMd::Simulation::dihedralStorage(), DdMd::Simulation::domain(), and Util::ParamComposite::setClassName().
virtual DdMd::TrajectoryWriter::~TrajectoryWriter () [inline, virtual]
Destructor.
Definition at line 55 of file ddMd/analyzers/TrajectoryWriter.h.
Member Function Documentation
void DdMd::TrajectoryWriter::readParameters (std::istream & in) [virtual]
Read parameters and initialize.
Parameters:
in input parameter file
Reimplemented from Util::ParamComposite.
Reimplemented in DdMd::DdMdGroupTrajectoryWriter.
Definition at line 59 of file ddMd/analyzers/TrajectoryWriter.cpp.
References DdMd::Analyzer::readInterval(), and DdMd::Analyzer::readOutputFileName().
void DdMd::TrajectoryWriter::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from DdMd::Analyzer.
Reimplemented in DdMd::DdMdGroupTrajectoryWriter.
Definition at line 69 of file ddMd/analyzers/TrajectoryWriter.cpp.
References DdMd::Analyzer::loadInterval(), and DdMd::Analyzer::loadOutputFileName().
void DdMd::TrajectoryWriter::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from DdMd::Analyzer.
Reimplemented in DdMd::DdMdGroupTrajectoryWriter.
Definition at line 79 of file ddMd/analyzers/TrajectoryWriter.cpp.
References DdMd::Analyzer::saveInterval(), and DdMd::Analyzer::saveOutputFileName().
void DdMd::TrajectoryWriter::setup () [virtual]
Open the trajectory file.
Reimplemented from DdMd::Analyzer.
Definition at line 88 of file ddMd/analyzers/TrajectoryWriter.cpp.
References DdMd::Simulation::fileMaster(), isBinary(), Util::MpiFileIo::isIoProcessor(), Util::FileMaster::openOutputFile(), DdMd::Analyzer::outputFileName(), DdMd::Analyzer::simulation(), and writeHeader().
void DdMd::TrajectoryWriter::sample (long iStep) [virtual]
Dump configuration to file.
Parameters:
iStep MC step index
Implements DdMd::Analyzer.
Definition at line 105 of file ddMd/analyzers/TrajectoryWriter.cpp.
References DdMd::Analyzer::isAtInterval(), and writeFrame().
void DdMd::TrajectoryWriter::clear () [virtual]
Clear nSample counter.
Reimplemented from DdMd::Analyzer.
Definition at line 115 of file ddMd/analyzers/TrajectoryWriter.cpp.
Referenced by output().
void DdMd::TrajectoryWriter::output () [virtual]
Close ouput file.
Reimplemented from DdMd::Analyzer.
Definition at line 125 of file ddMd/analyzers/TrajectoryWriter.cpp.
References clear().
bool DdMd::TrajectoryWriter::isBinary () const [inline, protected]
Is the file format binary (true) or text (false)?
Definition at line 220 of file ddMd/analyzers/TrajectoryWriter.h.
Referenced by setup().
virtual void DdMd::TrajectoryWriter::writeHeader (std::ofstream & out) [inline, protected, virtual]
Write data that should appear once, at beginning of the file.
Called by sample on first invocation. Default implementation is empty.
Parameters:
out output file stream
Reimplemented in DdMd::DdMdGroupTrajectoryWriter, and DdMd::DdMdTrajectoryWriter.
Definition at line 115 of file ddMd/analyzers/TrajectoryWriter.h.
Referenced by setup().
virtual void DdMd::TrajectoryWriter::writeFrame (std::ofstream & out, long iStep) [protected, pure virtual]
Write data that should appear in every frame.
Called by sample on every step.
Parameters:
out output file stream
iStep MD time step index
Implemented in DdMd::DdMdGroupTrajectoryWriter, DdMd::DdMdTrajectoryWriter, and DdMd::LammpsDumpWriter.
Referenced by sample().
Domain & DdMd::TrajectoryWriter::domain () [inline, protected]
Get the Domain by reference.
Definition at line 223 of file ddMd/analyzers/TrajectoryWriter.h.
Referenced by DdMd::LammpsDumpWriter::writeFrame(), DdMd::DdMdTrajectoryWriter::writeFrame(), DdMd::DdMdGroupTrajectoryWriter::writeFrame(), DdMd::DdMdTrajectoryWriter::writeHeader(), and DdMd::DdMdGroupTrajectoryWriter::writeHeader().
Boundary & DdMd::TrajectoryWriter::boundary () [inline, protected]
Get Boundary by reference.
Definition at line 226 of file ddMd/analyzers/TrajectoryWriter.h.
Referenced by DdMd::LammpsDumpWriter::writeFrame(), DdMd::DdMdTrajectoryWriter::writeFrame(), and DdMd::DdMdGroupTrajectoryWriter::writeFrame().
AtomStorage & DdMd::TrajectoryWriter::atomStorage () [inline, protected]
Get AtomStorage by reference.
Definition at line 229 of file ddMd/analyzers/TrajectoryWriter.h.
Referenced by DdMd::LammpsDumpWriter::writeFrame(), DdMd::DdMdTrajectoryWriter::writeFrame(), DdMd::DdMdGroupTrajectoryWriter::writeFrame(), and DdMd::DdMdTrajectoryWriter::writeHeader().
AtomCollector & DdMd::TrajectoryWriter::atomCollector () [inline, protected]
Get the AtomCollector by reference.
Definition at line 232 of file ddMd/analyzers/TrajectoryWriter.h.
Referenced by DdMd::LammpsDumpWriter::writeFrame(), DdMd::DdMdTrajectoryWriter::writeFrame(), DdMd::DdMdGroupTrajectoryWriter::writeFrame(), and DdMd::DdMdGroupTrajectoryWriter::writeHeader().
BondStorage & DdMd::TrajectoryWriter::bondStorage () [inline, protected]
Get BondStorage by reference.
Definition at line 236 of file ddMd/analyzers/TrajectoryWriter.h.
GroupCollector< 2 > & DdMd::TrajectoryWriter::bondCollector () [inline, protected]
Get the bond collector by reference.
Definition at line 239 of file ddMd/analyzers/TrajectoryWriter.h.
AngleStorage & DdMd::TrajectoryWriter::angleStorage () [inline, protected]
Get AngleStorage by reference.
Definition at line 244 of file ddMd/analyzers/TrajectoryWriter.h.
GroupCollector< 3 > & DdMd::TrajectoryWriter::angleCollector () [inline, protected]
Get the angle collector by reference.
Definition at line 247 of file ddMd/analyzers/TrajectoryWriter.h.
DihedralStorage & DdMd::TrajectoryWriter::dihedralStorage () [inline, protected]
Get DihedralStorage by reference.
Definition at line 252 of file ddMd/analyzers/TrajectoryWriter.h.
GroupCollector< 4 > & DdMd::TrajectoryWriter::dihedralCollector () [inline, protected]
Get the dihedral collector by reference.
Definition at line 255 of file ddMd/analyzers/TrajectoryWriter.h.
The documentation for this class was generated from the following files:
ddMd/analyzers/TrajectoryWriter.h
ddMd/analyzers/TrajectoryWriter.cpp