Simpatico: Util::Setable< T > Class Template Reference
Util::Setable< T > Class Template Reference
Utilities
Detailed Description
template<class T>
class Util::Setable< T >
Template for a value that can be declared null.
Definition at line 22 of file Setable.h.
#include <Setable.h>
Public Member Functions
Setable ()
Default constructor.
Setable (const Setable< T > &other)
Copy constructor.
Setable (const T &value)
Construct from T value (explciit).
Setable< T > & operator= (const Setable< T > &other)
Assignment.
Setable< T > & operator= (const T &value)
Assignment from value.
void set (const T &value)
Set the value.
void unset ()
Unset the value (mark as unknown).
bool isSet () const
Is this object set (is the value known)?
const T & value () const
Return value (if set).
bool isValid (MPI::Intracomm &communicator) const
Test consistency of states on different processors.
Constructor & Destructor Documentation
template<class T> Util::Setable< T >::Setable () [inline]
Default constructor.
Definition at line 30 of file Setable.h.
template<class T> Util::Setable< T >::Setable (const Setable< T > & other) [inline]
Copy constructor.
Parameters:
other Setable object being copied.
Definition at line 40 of file Setable.h.
template<class T> Util::Setable< T >::Setable (const T & value) [inline, explicit]
Construct from T value (explciit).
Parameters:
value value of wrapped object.
Definition at line 50 of file Setable.h.
Member Function Documentation
template<class T> Setable<T>& Util::Setable< T >::operator= (const Setable< T > & other) [inline]
Assignment.
Definition at line 58 of file Setable.h.
template<class T> Setable<T>& Util::Setable< T >::operator= (const T & value) [inline]
Assignment from value.
Definition at line 70 of file Setable.h.
template<class T> void Util::Setable< T >::set (const T & value) [inline]
Set the value.
Definition at line 80 of file Setable.h.
Referenced by DdMd::AtomStorage::computeNAtomTotal(), DdMd::Potential::setEnergy(), DdMd::PairPotential::setPairEnergies(), and DdMd::Potential::setStress().
template<class T> void Util::Setable< T >::unset () [inline]
Unset the value (mark as unknown).
Definition at line 89 of file Setable.h.
Referenced by DdMd::PairList::clearStatistics(), DdMd::Buffer::clearStatistics(), DdMd::AtomStorage::clearStatistics(), DdMd::Potential::unsetEnergy(), DdMd::AtomStorage::unsetNAtomTotal(), DdMd::PairPotential::unsetPairEnergies(), and DdMd::Potential::unsetStress().
template<class T> bool Util::Setable< T >::isSet () const [inline]
Is this object set (is the value known)?
Definition at line 95 of file Setable.h.
Referenced by DdMd::Potential::isEnergySet(), and DdMd::Potential::isStressSet().
template<class T> const T& Util::Setable< T >::value () const [inline]
Return value (if set).
Throws an Exception if value is not set.
Definition at line 103 of file Setable.h.
Referenced by DdMd::Potential::energy(), Util::Setable< Tensor >::operator=(), DdMd::PairList::outputStatistics(), DdMd::Buffer::outputStatistics(), DdMd::AtomStorage::outputStatistics(), DdMd::PairPotential::pairEnergies(), DdMd::Potential::pressure(), Util::Setable< Tensor >::set(), and DdMd::Potential::stress().
template<typename T > bool Util::Setable< T >::isValid (MPI::Intracomm & communicator) const
Test consistency of states on different processors.
If valid, return true, else throws an Exception. The state is valid if the value of isSet is the same on all processors.
Definition at line 134 of file Setable.h.
References UTIL_THROW.
Referenced by DdMd::Potential::isValid(), and DdMd::AtomStorage::isValid().
The documentation for this class was generated from the following file:
Setable.h