Simpatico: DdMd::ModifierManager Class Reference
DdMd::ModifierManager Class Reference
Modifiers
Detailed Description
Manager for a set of Modifier objects.
An ModifierManager maintains a list of Modifier objects and provides methods to execute specified actions at various points before and during the main integration loop.
Definition at line 32 of file ModifierManager.h.
#include <ModifierManager.h>
Public Member Functions
ModifierManager ()
Default constructor (for unit testing).
ModifierManager (Simulation &simulation)
Constructor (for use in Simulation).
~ModifierManager ()
Destructor.
void readParameters (std::istream &in)
Read main block of parameter file.
Factory< Modifier > * newDefaultFactory () const
Return pointer to a new default factory.
Integrator actions
void setup ()
Setup before entering the main loop.
void preIntegrate1 (long iStep)
Call just before the first step of velocity-Verlet algorithm.
void postIntegrate1 (long iStep)
Call just after the first step of velocity-Verlet algorithm.
void preTransform (long iStep)
Call on exchange steps before transforming to scaled coordinates.
void preExchange (long iStep)
Call on exchange steps after transforming, before exchanging.
void postExchange (long iStep)
Call on exchange steps after atom exchange, before reneighboring.
void postNeighbor (long iStep)
Call on exchange steps after re-building the neighbor list.
void preUpdate (long iStep)
Call on update steps before updating ghost positions.
void postUpdate (long iStep)
Call on update steps after updating ghost positions.
void preForce (long iStep)
Call after updating but before calculating forces.
void postForce (long iStep)
Call after calculating forces.
void endOfStep (long iStep)
Call after 2nd integration step, at end of the time step.
Communication functions
void packExchange (long iStep)
Pack data into buffer used to exchange atoms.
void unpackExchange (long iStep)
Unpack data from buffer used to exchange atoms.
void packUpdate (long iStep)
Pack data into buffer used to update ghost positions.
void unpackUpdate (long iStep)
Unpack data from buffer used to update ghost positions.
void packReverseUpdate (long iStep)
Pack data into buffer used to reverse update forces.
void unpackReverseUpdate (long iStep)
Unpack data from the buffer used to reverse update forces.
Public Member Functions inherited from Util::Manager< Modifier >
Manager ()
Constructor.
virtual ~Manager ()
Destructor.
void addSubfactory (Factory< Modifier > &subfactory)
Set a SubFactory for this Manager.
void setFactory (Factory< Modifier > &factory)
Associate a Factory with this Manager.
void setFactory (Factory< Modifier > *factoryPtr)
Associated a Factory with this Manager (pass by pointer).
virtual void readParam (std::istream &in)
Read and create a set of objects.
virtual void readParamOptional (std::istream &in)
Optioanlly read and create a set of objects.
virtual void loadParameters (Serializable::IArchive &ar)
Load a set of objects to an output archive.
virtual void save (Serializable::OArchive &ar)
Save a set of objects to an output archive.
void append (Modifier &data, const std::string &name)
Append a Data object to the end of the sequence.
int size () const
Get logical size.
std::string className (int i) const
Get the subclass name for object number i.
Factory< Modifier > & factory ()
Return a reference to the factory.
bool hasFactory () const
Return true if this Manager has a Factory, false otherwise.
Modifier & operator[] (int i) const
Mimic C array subscripting.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::Manager< Modifier >
void beginReadManager (std::istream &in)
Read (or attempt to read) opening line: "ManagerName{".
void endReadManager ()
Add closing bracket to output format.
void initFactory ()
Create factory if necessary.
Constructor & Destructor Documentation
DdMd::ModifierManager::ModifierManager ()
Default constructor (for unit testing).
Definition at line 22 of file ModifierManager.cpp.
References Util::ParamComposite::setClassName().
DdMd::ModifierManager::ModifierManager (Simulation & simulation)
Constructor (for use in Simulation).
Definition at line 45 of file ModifierManager.cpp.
References Util::ParamComposite::setClassName().
DdMd::ModifierManager::~ModifierManager ()
Destructor.
Definition at line 68 of file ModifierManager.cpp.
Member Function Documentation
void DdMd::ModifierManager::readParameters (std::istream & in) virtual
Read main block of parameter file.
Parameters
in input parameter file stream.
Reimplemented from Util::Manager< Modifier >.
Definition at line 76 of file ModifierManager.cpp.
References DdMd::Modifier::Flags::EndOfStep, DdMd::Modifier::Flags::Exchange, DdMd::Modifier::isSet(), DdMd::Modifier::Flags::PostExchange, DdMd::Modifier::Flags::PostForce, DdMd::Modifier::Flags::PostIntegrate1, DdMd::Modifier::Flags::PostNeighbor, DdMd::Modifier::Flags::PostUpdate, DdMd::Modifier::Flags::PreExchange, DdMd::Modifier::Flags::PreForce, DdMd::Modifier::Flags::PreIntegrate1, DdMd::Modifier::Flags::PreTransform, DdMd::Modifier::Flags::PreUpdate, Util::Manager< Data >::readParameters(), DdMd::Modifier::Flags::ReverseUpdate, DdMd::Modifier::Flags::Setup, Util::Manager< Modifier >::size(), and DdMd::Modifier::Flags::Update.
Factory< Modifier > * DdMd::ModifierManager::newDefaultFactory () const virtual
Return pointer to a new default factory.
Virtual, inherited from Manager<Modifier>.
Implements Util::Manager< Modifier >.
Definition at line 340 of file ModifierManager.cpp.
void DdMd::ModifierManager::setup ()
Setup before entering the main loop.
Definition at line 133 of file ModifierManager.cpp.
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::ModifierManager::preIntegrate1 (long iStep)
Call just before the first step of velocity-Verlet algorithm.
Definition at line 143 of file ModifierManager.cpp.
References DdMd::Modifier::isAtInterval(), and DdMd::Modifier::preIntegrate1().
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::ModifierManager::postIntegrate1 (long iStep)
Call just after the first step of velocity-Verlet algorithm.
Definition at line 155 of file ModifierManager.cpp.
References DdMd::Modifier::isAtInterval(), and DdMd::Modifier::postIntegrate1().
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::ModifierManager::preTransform (long iStep)
Call on exchange steps before transforming to scaled coordinates.
Definition at line 167 of file ModifierManager.cpp.
References DdMd::Modifier::isAtInterval(), and DdMd::Modifier::preTransform().
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::ModifierManager::preExchange (long iStep)
Call on exchange steps after transforming, before exchanging.
Definition at line 179 of file ModifierManager.cpp.
References DdMd::Modifier::isAtInterval(), and DdMd::Modifier::preExchange().
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::ModifierManager::postExchange (long iStep)
Call on exchange steps after atom exchange, before reneighboring.
Definition at line 191 of file ModifierManager.cpp.
References DdMd::Modifier::isAtInterval(), and DdMd::Modifier::postExchange().
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::ModifierManager::postNeighbor (long iStep)
Call on exchange steps after re-building the neighbor list.
Definition at line 203 of file ModifierManager.cpp.
References DdMd::Modifier::isAtInterval(), and DdMd::Modifier::postNeighbor().
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::ModifierManager::preUpdate (long iStep)
Call on update steps before updating ghost positions.
Definition at line 215 of file ModifierManager.cpp.
References DdMd::Modifier::isAtInterval(), and DdMd::Modifier::preUpdate().
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::ModifierManager::postUpdate (long iStep)
Call on update steps after updating ghost positions.
Definition at line 227 of file ModifierManager.cpp.
References DdMd::Modifier::isAtInterval(), and DdMd::Modifier::postUpdate().
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::ModifierManager::preForce (long iStep)
Call after updating but before calculating forces.
Definition at line 239 of file ModifierManager.cpp.
References DdMd::Modifier::isAtInterval(), and DdMd::Modifier::preForce().
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::ModifierManager::postForce (long iStep)
Call after calculating forces.
Definition at line 251 of file ModifierManager.cpp.
References DdMd::Modifier::isAtInterval(), and DdMd::Modifier::postForce().
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::ModifierManager::endOfStep (long iStep)
Call after 2nd integration step, at end of the time step.
Definition at line 263 of file ModifierManager.cpp.
References DdMd::Modifier::endOfStep(), and DdMd::Modifier::isAtInterval().
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::ModifierManager::packExchange (long iStep)
Pack data into buffer used to exchange atoms.
Definition at line 277 of file ModifierManager.cpp.
References DdMd::Modifier::packExchange().
void DdMd::ModifierManager::unpackExchange (long iStep)
Unpack data from buffer used to exchange atoms.
Definition at line 287 of file ModifierManager.cpp.
References DdMd::Modifier::unpackExchange().
void DdMd::ModifierManager::packUpdate (long iStep)
Pack data into buffer used to update ghost positions.
Definition at line 297 of file ModifierManager.cpp.
References DdMd::Modifier::packUpdate().
void DdMd::ModifierManager::unpackUpdate (long iStep)
Unpack data from buffer used to update ghost positions.
Definition at line 307 of file ModifierManager.cpp.
References DdMd::Modifier::unpackUpdate().
void DdMd::ModifierManager::packReverseUpdate (long iStep)
Pack data into buffer used to reverse update forces.
Used only if reverse communication is enabled.
Definition at line 317 of file ModifierManager.cpp.
References DdMd::Modifier::packReverseUpdate().
void DdMd::ModifierManager::unpackReverseUpdate (long iStep)
Unpack data from the buffer used to reverse update forces.
Used only if reverse communication is enabled.
Definition at line 327 of file ModifierManager.cpp.
References DdMd::Modifier::unpackReverseUpdate().
The documentation for this class was generated from the following files:
ModifierManager.h
ModifierManager.cpp