Simpatico: McMd::McPairPotential Class Reference
McMd::McPairPotential Class Reference
Pair Potentials
Detailed Description
A PairPotential for MC simulations (abstract).
Definition at line 30 of file McPairPotential.h.
#include <McPairPotential.h>
Public Member Functions
McPairPotential (System &system)
Constructor.
virtual ~McPairPotential ()
Destructor.
Energy, Force, Stress evaluators (pure virtual)
virtual double atomEnergy (const Atom &atom) const =0
Calculate the nonbonded pair energy for one Atom.
virtual double moleculeEnergy (const Molecule &molecule) const =0
Calculate the nonbonded pair energy for an entire Molecule.
Cell List Management
void buildCellList ()
Build the CellList with current configuration.
void addAtom (Atom &atom)
Add an Atom to the CellList.
void deleteAtom (Atom &atom)
Remove an Atom from the CellList.
void updateAtomCell (Atom &atom)
Update the cell list to reflect a new position.
void moveAtom (Atom &atom, const Vector &position)
Move an Atom position, and update the CellList.
const CellList & cellList () const
Get the cellList by const reference.
Protected Attributes
CellList::NeighborArray neighbors_
Array to hold neighbors returned by a CellList.
CellList cellList_
Cell list for atom positions.
Boundary maxBoundary_
Alias for global atoms_ DArray of parent simulation.
Constructor & Destructor Documentation
McMd::McPairPotential::McPairPotential (System & system)
Constructor.
Definition at line 27 of file McPairPotential.cpp.
References Util::ParamComposite::setClassName().
McMd::McPairPotential::~McPairPotential () [virtual]
Destructor.
Definition at line 35 of file McPairPotential.cpp.
Member Function Documentation
virtual double McMd::McPairPotential::atomEnergy (const Atom & atom) const [pure virtual]
Calculate the nonbonded pair energy for one Atom.
Parameters:
atom Atom object of interest
Returns:
nonbonded pair potential energy of atom
Implemented in McMd::McPairPotentialImpl< Interaction >.
Referenced by McMd::CfbEndBase::addEndAtom(), McMd::CfbRebridgeBase::addMiddleAtom(), McMd::McSystem::atomPotentialEnergy(), McMd::CfbEndBase::deleteEndAtom(), McMd::CfbRebridgeBase::deleteMiddleAtom(), McMd::RigidDisplaceMove::move(), and McMd::McNVTChemicalPotential::sample().
virtual double McMd::McPairPotential::moleculeEnergy (const Molecule & molecule) const [pure virtual]
Calculate the nonbonded pair energy for an entire Molecule.
The return value is the change in total pair potential upon inserting or removing a molecule. This is the sum of all inter-molecular pair interactions involving atoms of this molecule, plus an intramolecular contribution in which each pair is counted only once.
Parameters:
molecule Molecule object of interest
Returns:
nonbonded pair potential energy of molecule
Implemented in McMd::McPairPotentialImpl< Interaction >.
Referenced by McMd::EndSwapMove::move(), and McMd::HomopolymerSemiGrandMove::move().
void McMd::McPairPotential::buildCellList ()
Build the CellList with current configuration.
Calls CellList::clear() to clear the CellList, then adds every Atom in this System. Each Atom position is shifted into the primary box by Boundary::shift() before being added.
Definition at line 41 of file McPairPotential.cpp.
References McMd::CellList::addAtom(), McMd::SubSystem::begin(), McMd::SubSystem::boundary(), cellList_, McMd::CellList::clear(), McMd::CellList::makeGrid(), McMd::PairPotential::maxPairCutoff(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::OrthorhombicBoundary::shift(), and McMd::SubSystem::simulation().
Referenced by McMd::McSimulation::analyze(), McMd::McSystem::loadConfig(), McMd::HybridMdMove::move(), McMd::HybridNphMdMove::move(), McMd::MdMove::move(), McMd::DpdMove::move(), McMd::McSimulation::readCommands(), McMd::McSystem::readConfig(), and McMd::McSimulation::simulate().
void McMd::McPairPotential::addAtom (Atom & atom) [inline]
Add an Atom to the CellList.
Parameters:
atom Atom object of interest.
Definition at line 147 of file McPairPotential.h.
Referenced by McMd::CfbRebridgeBase::addSequence(), McMd::CfbEndMove::move(), McMd::CfbReptationMove::move(), and McMd::McNVTChemicalPotential::sample().
void McMd::McPairPotential::deleteAtom (Atom & atom) [inline]
Remove an Atom from the CellList.
Parameters:
atom Atom object of interest
Definition at line 151 of file McPairPotential.h.
Referenced by McMd::CfbRebridgeBase::deleteSequence(), McMd::CfbEndMove::move(), McMd::CfbReptationMove::move(), and McMd::McNVTChemicalPotential::sample().
void McMd::McPairPotential::updateAtomCell (Atom & atom) [inline]
Update the cell list to reflect a new position.
Use this to update the cell list after an Atom position has already been assigned a new value.
Parameters:
atom Atom object whose position has been modified.
Definition at line 155 of file McPairPotential.h.
References McMd::Atom::position().
Referenced by McMd::RingTetraRebridgeMove::move(), McMd::AtomDisplaceMove::move(), McMd::CfbDoubleRebridgeMove::move(), McMd::CfbRebridgeMove::move(), McMd::CfbEndMove::move(), McMd::RingOctaRebridgeMove::move(), McMd::EndSwapMove::move(), McMd::CfbRingRebridgeMove::move(), McMd::CfbReptationMove::move(), and McMd::RigidDisplaceMove::move().
void McMd::McPairPotential::moveAtom (Atom & atom, const Vector & position) [inline]
Move an Atom position, and update the CellList.
On output, atom.position() is reset to to position, and the new position is recorded in the CellList. This is equivalent to atom.position() = position and then updateAtomCell(atom).
Parameters:
atom Atom object of interest
position new position vector
Definition at line 159 of file McPairPotential.h.
References McMd::Atom::position().
const CellList & McMd::McPairPotential::cellList () const [inline]
Get the cellList by const reference.
Definition at line 166 of file McPairPotential.h.
Referenced by McMd::McSystem::isValid(), McMd::McMuExchange::sample(), McMd::McPairEnergyAverage::sample(), and McMd::RingOctaRebridgeMove::scanBridge().
Member Data Documentation
CellList::NeighborArray McMd::McPairPotential::neighbors_ [mutable, protected]
Array to hold neighbors returned by a CellList.
Definition at line 131 of file McPairPotential.h.
CellList McMd::McPairPotential::cellList_ [protected]
Cell list for atom positions.
Definition at line 134 of file McPairPotential.h.
Referenced by buildCellList().
Boundary McMd::McPairPotential::maxBoundary_ [protected]
Alias for global atoms_ DArray of parent simulation.
Maximum boundary (used to allocated memory for CellList).
Definition at line 140 of file McPairPotential.h.
The documentation for this class was generated from the following files:
McPairPotential.h
McPairPotential.cpp