Simpatico: McMd::LammpsConfigIo Class Reference
McMd::LammpsConfigIo Class Reference
Configuration File IO
Detailed Description
ConfigIo for Lammps data files.
This class reads and writes the data file format that is read by the LAMMPS read_data command. Because the Lammps data model is very different than that used in Simpatico, there are signficant restrictions on the use of such files:
1) When reading a LAMMPS data file, the maximum total number of atoms defined by the Simpatico parameter file must exactly match the number of atoms in the data file.
2) The atom ids (or tags) in the Lammps data file must appear in order, numbered from 1. This is checked.
3) The ordering of atoms in the lammps file and the topology are assumed to be consistent with that used in Simpatico. The topology information in the Lammps data file is discarded. This requires that atoms within each molecule be listed sequentially, with molecules with the same species listed sequentially, and that ordered of atoms within each molecule be consistent with the numbering scheme used in Simpatico. Thus far, none of this is checked.
Definition at line 49 of file LammpsConfigIo.h.
#include <LammpsConfigIo.h>
Public Member Functions
LammpsConfigIo (System &system)
Constructor.
virtual ~LammpsConfigIo ()
Destructor.
void read (std::istream &in)
Read configuration (particle positions) from file.
void write (std::ostream &out)
Write configuration (particle positions) to file.
Constructor & Destructor Documentation
McMd::LammpsConfigIo::LammpsConfigIo (System & system)
Constructor.
Definition at line 35 of file LammpsConfigIo.cpp.
McMd::LammpsConfigIo::~LammpsConfigIo () [virtual]
Destructor.
Definition at line 42 of file LammpsConfigIo.cpp.
Member Function Documentation
void McMd::LammpsConfigIo::read (std::istream & in) [virtual]
Read configuration (particle positions) from file.
Parameters:
in input file stream.
Implements McMd::ConfigIo.
Definition at line 45 of file LammpsConfigIo.cpp.
References McMd::System::addMolecule(), McMd::Molecule::begin(), McMd::ConfigIo::boundary(), McMd::Species::capacity(), McMd::Species::nAtom(), McMd::Species::nBond(), Util::ArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::ArrayStack< Data >::pop(), McMd::Species::reservoir(), Util::OrthorhombicBoundary::setOrthorhombic(), McMd::ConfigIo::simulation(), McMd::Simulation::species(), Util::Vector::subtract(), McMd::ConfigIo::system(), and UTIL_THROW.
void McMd::LammpsConfigIo::write (std::ostream & out) [virtual]
Write configuration (particle positions) to file.
Parameters:
out output file stream.
Implements McMd::ConfigIo.
Definition at line 167 of file LammpsConfigIo.cpp.
References McMd::System::begin(), McMd::ConfigIo::boundary(), Util::Dimension, Util::Format::initStatic(), Util::OrthorhombicBoundary::lengths(), McMd::Species::nAtom(), McMd::Simulation::nAtomType(), McMd::Species::nBond(), McMd::System::nMolecule(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::Format::setDefaultPrecision(), Util::Format::setDefaultWidth(), McMd::ConfigIo::simulation(), McMd::Simulation::species(), and McMd::ConfigIo::system().
The documentation for this class was generated from the following files:
LammpsConfigIo.h
LammpsConfigIo.cpp