Simpatico: Util::PointGroup Class Reference
Util::PointGroup Class Reference
Util namespace » Crystal
Detailed Description
Group of crystal symmetries with no translations.
Definition at line 18 of file PointGroup.h.
#include <PointGroup.h>
Public Member Functions
template<int N>
void makeStar (const IntVector &root, FSArray< IntVector, N > &star)
Generate a set of reciprocal vectors that are related by symmetry.
Public Member Functions inherited from Util::SymmetryGroup< PointSymmetry >
SymmetryGroup ()
Default constructor.
SymmetryGroup (const SymmetryGroup &other)
Copy constructor.
~SymmetryGroup ()
Destructor.
bool add (PointSymmetry &symmetry)
Add a new element to the group.
void makeCompleteGroup ()
Generate a complete group from the current elements.
const PointSymmetry * find (const PointSymmetry &symmetry) const
Find a symmetry within a group.
const PointSymmetry & identity () const
Return a reference to the identity element.
int size () const
Return number of elements in group.
SymmetryGroup & operator= (const SymmetryGroup &other)
Assignment operator.
PointSymmetry & operator[] (int i)
Element access operator (by reference).
const PointSymmetry & operator[] (int i) const
Element access operator (by reference).
bool isValid () const
Return true if valid complete group, or throw an Exception.
Friends
std::ostream & operator<< (std::ostream &out, const PointGroup &A)
Output stream inserter operator writing a PointGroup to stream.
Member Function Documentation
template<int N> void Util::PointGroup::makeStar (const IntVector & root, FSArray< IntVector, N > & star)
Generate a set of reciprocal vectors that are related by symmetry.
Parameters
root the reciprocal vector to which all others are related.
star array containing all members of the star (on ouput).
Definition at line 47 of file PointGroup.h.
References Util::FSArray< Data, Capacity >::append(), Util::FSArray< Data, Capacity >::capacity(), Util::FSArray< Data, Capacity >::clear(), Util::FSArray< Data, Capacity >::size(), Util::SymmetryGroup< PointSymmetry >::size(), and UTIL_THROW.
Referenced by McMd::StructureFactorGrid::readParameters(), McMd::StructureFactorPGrid::readParameters(), DdMd::StructureFactorGrid::readParameters(), McMd::IntraStructureFactorGrid::readParameters(), and McMd::StructureFactorPGrid::save().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const PointGroup & A) friend
Output stream inserter operator writing a PointGroup to stream.
Definition at line 8 of file PointGroup.cpp.
The documentation for this class was generated from the following file:
PointGroup.h