Simpatico: MdCf::AtomStorage Class Reference
MdCf::AtomStorage Class Reference
Storage
Detailed Description
Container for a set of atoms.
Definition at line 29 of file mdCf/storage/AtomStorage.h.
#include <AtomStorage.h>
Public Member Functions
AtomStorage ()
Constructor.
~AtomStorage ()
Destructor.
void allocate (int capacity)
Allocate and initialize memory.
Atom * newPtr ()
Return pointer to location for new atom.
void add ()
Finalize addition of atom (allows lookup by id).
void clear ()
Clear all atoms and groups.
Atom * ptr (int id)
Get a pointer to an atom by global id.
void begin (Iterator &iter)
Initialize an iterator for atoms.
int capacity () const
Get atom capacity (maximum id + 1).
int size () const
Get number of atoms.
Constructor & Destructor Documentation
MdCf::AtomStorage::AtomStorage ()
Constructor.
Definition at line 19 of file mdCf/storage/AtomStorage.cpp.
MdCf::AtomStorage::~AtomStorage ()
Destructor.
Definition at line 26 of file mdCf/storage/AtomStorage.cpp.
Member Function Documentation
void MdCf::AtomStorage::allocate (int capacity)
Allocate and initialize memory.
Parameters
capacity Maximum number of atoms
Definition at line 32 of file mdCf/storage/AtomStorage.cpp.
References clear().
Referenced by MdCf::Storage::readParameters().
Atom * MdCf::AtomStorage::newPtr ()
Return pointer to location for new atom.
Returns
pointer to location of new atom
Definition at line 42 of file mdCf/storage/AtomStorage.cpp.
References size(), and UTIL_THROW.
Referenced by MdCf::DdMdConfigIo::readConfig().
void MdCf::AtomStorage::add ()
Finalize addition of atom (allows lookup by id).
Definition at line 56 of file mdCf/storage/AtomStorage.cpp.
References MdCf::Atom::id, and UTIL_THROW.
Referenced by MdCf::DdMdConfigIo::readConfig().
void MdCf::AtomStorage::clear ()
Clear all atoms and groups.
Definition at line 69 of file mdCf/storage/AtomStorage.cpp.
References capacity().
Referenced by allocate(), and MdCf::Storage::clear().
Atom * MdCf::AtomStorage::ptr (int id) inline
Get a pointer to an atom by global id.
Definition at line 121 of file mdCf/storage/AtomStorage.h.
void MdCf::AtomStorage::begin (AtomStorage::Iterator & iter) inline
Initialize an iterator for atoms.
Definition at line 128 of file mdCf/storage/AtomStorage.h.
Referenced by MdCf::DdMdConfigIo::readConfig(), and MdCf::DdMdConfigIo::writeConfig().
int MdCf::AtomStorage::capacity () const inline
Get atom capacity (maximum id + 1).
Definition at line 115 of file mdCf/storage/AtomStorage.h.
Referenced by clear(), and MdCf::DdMdConfigIo::readConfig().
int MdCf::AtomStorage::size () const inline
Get number of atoms.
Definition at line 108 of file mdCf/storage/AtomStorage.h.
Referenced by newPtr(), and MdCf::DdMdConfigIo::writeConfig().
The documentation for this class was generated from the following files:
mdCf/storage/AtomStorage.h
mdCf/storage/AtomStorage.cpp