Simpatico: McMd::Mask Class Reference
McMd::Mask Class Reference
McMd namespace » Chemical Structure
Detailed Description
Set of Atoms for which pair interactions with a target Atom are "masked".
An Mask stores identifiers for a set of Atoms for which the non-bonded pair interactions with a single target atom are suppressed, or "masked". Each Mask object is associated with one target Atom.
A Mask could, for example, contain all atoms that are directly connected to the target atom by 2-body covalent bonds.
Definition at line 28 of file mcMd/chemistry/Mask.h.
#include <Mask.h>
Public Member Functions
Mask ()
Constructor.
void clear ()
Clear the mask set (remove all atoms).
void append (const Atom &atom)
Add an Atom to the masked set.
bool isMasked (const Atom &atom) const
True if the atom is in the masked set for the target Atom.
int size () const
Return the number of masked atoms.
Constructor & Destructor Documentation
McMd::Mask::Mask ()
Constructor.
Definition at line 19 of file mcMd/chemistry/Mask.cpp.
Member Function Documentation
void McMd::Mask::clear ()
Clear the mask set (remove all atoms).
Definition at line 30 of file mcMd/chemistry/Mask.cpp.
Referenced by McMd::CfbReptationMove::move(), and McMd::CfbReptateMove::move().
void McMd::Mask::append (const Atom & atom)
Add an Atom to the masked set.
Parameters
atom Atom to be added to the masked set.
Definition at line 41 of file mcMd/chemistry/Mask.cpp.
References isMasked(), and UTIL_THROW.
Referenced by McMd::CfbReptationMove::move(), McMd::CfbReptateMove::move(), and McMd::Simulation::save().
bool McMd::Mask::isMasked (const Atom & atom) const inline
True if the atom is in the masked set for the target Atom.
Parameters
atom Atom object to be tested.
Returns
true if atom is masked, false otherwise.
Definition at line 84 of file mcMd/chemistry/Mask.h.
Referenced by append(), McMd::McPairPotentialImpl< Interaction >::atomEnergy(), McMd::PairList::build(), McMd::McPairPotentialImpl< Interaction >::computeEnergy(), McMd::McPairPerturbation< Interaction >::derivative(), McMd::Simulation::isValid(), McMd::McPairPotentialImpl< Interaction >::moleculeEnergy(), McMd::SliplinkerEnd::move(), McMd::SliplinkerAll::move(), McMd::SliplinkMove::move(), McMd::GcSliplinkMove::move(), McMd::Sliplinker::move(), McMd::Crosslinker::sample(), McMd::McMuExchange::sample(), and McMd::McPairEnergyAverage::sample().
int McMd::Mask::size () const inline
Return the number of masked atoms.
Definition at line 96 of file mcMd/chemistry/Mask.h.
The documentation for this class was generated from the following files:
mcMd/chemistry/Mask.h
mcMd/chemistry/Mask.cpp