Simpatico: McMd::CfbEndBase Class Reference
McMd::CfbEndBase Class Reference
Monte Carlo Moves
Detailed Description
Base class for configuration bias (CFB) end regrowth moves.
This class provides methods deleteEndAtom and addEndAtom that delete or add a single atom to a specified end of a linear chain. These are the basic building blocks of CFB moves for flexible linear chains.
Definition at line 31 of file CfbEndBase.h.
#include <CfbEndBase.h>
Public Member Functions
CfbEndBase (McSystem &system)
Constructor.
virtual ~CfbEndBase ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameter nTrial.
void deleteEndAtom (Atom *endPtr, Atom *pvtPtr, int bondType, double &rosenbluth, double &energy)
CFB algorithm for deleting an end atom from a flexible chain.
void addEndAtom (Atom *endPtr, Atom *pvtPtr, int bondType, double &rosenbluth, double &energy)
Configuration bias algorithm for adding an atom to a chain end.
Protected Attributes
int nTrial_
Actual number of trial positions for each regrown atom.
Static Protected Attributes
static const int MaxTrial_ = 20
Maximum allowed number of trial positions for a regrown atom.
Constructor & Destructor Documentation
McMd::CfbEndBase::CfbEndBase (McSystem & system)
Constructor.
Definition at line 28 of file CfbEndBase.cpp.
References McMd::McSystem::hasDihedralPotential(), and UTIL_THROW.
McMd::CfbEndBase::~CfbEndBase () [virtual]
Destructor.
Definition at line 43 of file CfbEndBase.cpp.
Member Function Documentation
void McMd::CfbEndBase::readParameters (std::istream & in) [virtual]
Read parameter nTrial.
This function is used only for testing. Subclasses read the protected member nTrial directly.
Reimplemented from McMd::McMove.
Reimplemented in McMd::CfbRebridgeBase, McMd::CfbReptationMove, McMd::CfbRingRebridgeMove, McMd::CfbEndMove, McMd::CfbRebridgeMove, and McMd::CfbDoubleRebridgeMove.
Definition at line 49 of file CfbEndBase.cpp.
References MaxTrial_, nTrial_, and UTIL_THROW.
void McMd::CfbEndBase::deleteEndAtom (Atom * endPtr, Atom * pvtPtr, int bondType, double & rosenbluth, double & energy)
CFB algorithm for deleting an end atom from a flexible chain.
This function computes the energy of an end atom and a Rosenbluth factor for removing it. It does not remove the end atom from the system cell list.
Upon return:
rosenbluth is the nonbonded Rosenblush factor for the deleted atom, i.e., the sum of Boltzmann factors from nonbonded pair interactions for the initial position and nTrial_ - 1 trials.
energy is the total energy (bonded + nonbonded) of the end atom before it was deleted.
Parameters:
endPtr ptr to end atom, which we attempt to remove
pvtPtr ptr to atom next to end, or end after removal
bondType type of bond connecting pvt and end atoms
rosenbluth nonbonded Rosenbluth factor of deleted atom (out)
energy total potential energy of deleted atom (out)
Definition at line 61 of file CfbEndBase.cpp.
References Util::Vector::add(), McMd::McSystem::anglePotential(), McMd::Group< NAtom >::atom(), McMd::McPairPotential::atomEnergy(), McMd::ExternalPotential::atomEnergy(), McMd::SystemMove::boltzmann(), McMd::McSystem::bondPotential(), McMd::SystemMove::boundary(), Util::OrthorhombicBoundary::distanceSq(), Util::Vector::dot(), McMd::AnglePotential::energy(), McMd::BondPotential::energy(), McMd::McSystem::externalPotential(), McMd::Species::getAtomAngles(), McMd::Atom::molecule(), nTrial_, McMd::McSystem::pairPotential(), McMd::Atom::position(), McMd::McMove::random(), Util::OrthorhombicBoundary::shift(), Util::FSArray< Data, Capacity >::size(), McMd::Molecule::species(), McMd::SystemMove::system(), McMd::Group< NAtom >::typeId(), and Util::Random::unitVector().
Referenced by McMd::CfbRebridgeBase::deleteSequence(), McMd::CfbEndMove::move(), and McMd::CfbReptationMove::move().
void McMd::CfbEndBase::addEndAtom (Atom * endPtr, Atom * pvtPtr, int bondType, double & rosenbluth, double & energy)
Configuration bias algorithm for adding an atom to a chain end.
This function generates and computes Rosenbluth factors for nTrial trial positions, chooses one, updates the atomic position. It does not add the end atom to the system cell list.
Upon return:
rosenbluth is the nonbonded Rosenblush factor for the added atom, i.e., the sum of Boltzmann factors from nonbonded pair interactions for all nTrial_ trial positions.
energy is the total energy (bonded + nonbonded) of the new end atom in its chosen position.
Parameters:
endPtr ptr to new end atom, which we attempt to add
pvtPtr end atom of current chain, next to end
bondType type of bond connecting pvt and end atoms
rosenbluth Rosenbluth factor of added atom (out)
energy potential energy of deleted atom (out)
Definition at line 188 of file CfbEndBase.cpp.
References Util::Vector::add(), McMd::McSystem::anglePotential(), McMd::Group< NAtom >::atom(), McMd::McPairPotential::atomEnergy(), McMd::ExternalPotential::atomEnergy(), Util::EnergyEnsemble::beta(), McMd::SystemMove::boltzmann(), McMd::McSystem::bondPotential(), McMd::SystemMove::boundary(), Util::OrthorhombicBoundary::distanceSq(), Util::Vector::dot(), Util::Random::drawFrom(), McMd::BondPotential::energy(), McMd::SystemMove::energyEnsemble(), McMd::McSystem::externalPotential(), McMd::Species::getAtomAngles(), MaxTrial_, McMd::Atom::molecule(), nTrial_, McMd::McSystem::pairPotential(), McMd::Atom::position(), McMd::McMove::random(), McMd::BondPotential::randomBondLength(), Util::OrthorhombicBoundary::shift(), Util::FSArray< Data, Capacity >::size(), McMd::Molecule::species(), McMd::SystemMove::system(), McMd::Group< NAtom >::typeId(), and Util::Random::unitVector().
Referenced by McMd::CfbRebridgeBase::addSequence(), McMd::CfbEndMove::move(), and McMd::CfbReptationMove::move().
Member Data Documentation
const int McMd::CfbEndBase::MaxTrial_ = 20 [static, protected]
Maximum allowed number of trial positions for a regrown atom.
Definition at line 111 of file CfbEndBase.h.
Referenced by addEndAtom(), McMd::CfbRebridgeBase::addMiddleAtom(), McMd::CfbEndMove::loadParameters(), McMd::CfbReptationMove::loadParameters(), McMd::CfbRebridgeBase::loadParameters(), McMd::CfbEndMove::readParameters(), McMd::CfbReptationMove::readParameters(), McMd::CfbRebridgeBase::readParameters(), and readParameters().
int McMd::CfbEndBase::nTrial_ [protected]
Actual number of trial positions for each regrown atom.
Definition at line 114 of file CfbEndBase.h.
Referenced by addEndAtom(), McMd::CfbRebridgeBase::addMiddleAtom(), deleteEndAtom(), McMd::CfbRebridgeBase::deleteMiddleAtom(), McMd::CfbEndMove::loadParameters(), McMd::CfbRebridgeBase::loadParameters(), McMd::CfbReptationMove::loadParameters(), McMd::CfbEndMove::readParameters(), McMd::CfbRebridgeBase::readParameters(), McMd::CfbReptationMove::readParameters(), readParameters(), McMd::CfbEndMove::save(), McMd::CfbRebridgeBase::save(), and McMd::CfbReptationMove::save().
The documentation for this class was generated from the following files:
CfbEndBase.h
CfbEndBase.cpp