Simpatico: Util::SpeciesEnsemble Class Reference
Util::SpeciesEnsemble Class Reference
Statistical Ensembles
Detailed Description
An ensemble for the number of molecules of one Species.
An SpeciesEnsemble has a type, which can be closed or grand. If the ensemble type is grand, it stores a chemical potential.
Definition at line 29 of file SpeciesEnsemble.h.
#include <SpeciesEnsemble.h>
Public Types
enum Type
Enumeration of the allowed types of SpeciesEnsemble.
Public Member Functions
SpeciesEnsemble (Type type=UNKNOWN)
Constructor.
~SpeciesEnsemble ()
Destructor.
void setMu (double mu)
Set the chemical potential mu.
virtual void readParam (std::istream &in)
Read the type and (if appropriate) mu from file.
Accessors
bool isClosed () const
Is this a Closed ensemble?
bool isGrand () const
Is this a Grand ensemble?
double mu () const
Return the chemical potential mu.
Static Public Member Functions
static void commitMpiType ()
Commit associated MPI DataType.
Member Enumeration Documentation
enum Util::SpeciesEnsemble::Type
Enumeration of the allowed types of SpeciesEnsemble.
Definition at line 37 of file SpeciesEnsemble.h.
Constructor & Destructor Documentation
Util::SpeciesEnsemble::SpeciesEnsemble (Type type = UNKNOWN)
Constructor.
Definition at line 19 of file SpeciesEnsemble.cpp.
Util::SpeciesEnsemble::~SpeciesEnsemble ()
Destructor.
Definition at line 27 of file SpeciesEnsemble.cpp.
Member Function Documentation
void Util::SpeciesEnsemble::setMu (double mu)
Set the chemical potential mu.
Definition at line 33 of file SpeciesEnsemble.cpp.
References isGrand(), mu(), and UTIL_THROW.
void Util::SpeciesEnsemble::readParam (std::istream & in) [virtual]
Read the type and (if appropriate) mu from file.
The type is specified in the input file by a string literal "closed" or "grand".
Reimplemented from Util::ParamComposite.
Definition at line 44 of file SpeciesEnsemble.cpp.
References isGrand(), Util::ParamComposite::readBegin(), and Util::ParamComposite::readEnd().
bool Util::SpeciesEnsemble::isClosed () const [inline]
Is this a Closed ensemble?
Definition at line 126 of file SpeciesEnsemble.h.
bool Util::SpeciesEnsemble::isGrand () const [inline]
Is this a Grand ensemble?
Definition at line 130 of file SpeciesEnsemble.h.
Referenced by readParam(), and setMu().
double Util::SpeciesEnsemble::mu () const [inline]
Return the chemical potential mu.
Return the mu.
Definition at line 122 of file SpeciesEnsemble.h.
Referenced by setMu().
void Util::SpeciesEnsemble::commitMpiType () [static]
Commit associated MPI DataType.
Definition at line 103 of file SpeciesEnsemble.cpp.
References Util::MpiStructBuilder::addMember(), Util::MpiStructBuilder::commit(), and Util::MpiStructBuilder::setBase().
The documentation for this class was generated from the following files:
SpeciesEnsemble.h
SpeciesEnsemble.cpp