Simpatico: McMd::SpeciesMutator Class Reference
McMd::SpeciesMutator Class Reference
Species
Detailed Description
Mix-in class for mutable subclasses of Species.
A mutable species is a class that is derived from both Species and SpeciesMutator. A mutable species models a species in which each molecule can be in any of an enumerable number of internal states. This may be used to represent, for example, homopolymers that can change type within a semi-grand canonical simulation, or polymers that can grow or shrink within some extended ensemble simulations. Changes in internal states may change the types of atoms and bonds, and may temporarily erase, or deactivate, certain atoms and bonds.
Each molecule in a mutable species is assigned an integer state id, to specify its internal state. Each state is assigned a floating point statistical weight. The statistical weights are unnormalized, i.e., they need not add to unity. The SpeciesMutator class provides arrays that store these state variables and statistical weights, and methods to access them.
Definition at line 41 of file SpeciesMutator.h.
#include <SpeciesMutator.h>
Public Member Functions
SpeciesMutator ()
Constructor.
virtual ~SpeciesMutator ()
Destructor.
Mutators
virtual void readMoleculeState (std::istream &in, Molecule &molecule)
Read the state id for one molecule from a configuration file stream.
virtual void writeMoleculeState (std::ostream &out, const Molecule &molecule) const
Write the state id for one molecule to a configuration file stream.
virtual void setMoleculeState (Molecule &molecule, int stateId)=0
Change the state of a specific molecule.
void setWeight (int stateId, double weight)
Set the statistical weight associated with a specific state.
int moleculeStateId (const Molecule &molecule) const
Get the state id for a specific molecule.
int nState () const
Get the number of possible molecule states.
int stateOccupancy (int stateId) const
Get the number of molecules with a specified state.
double stateWeight (int stateId) const
Get the statistical weight for a specfic molecular state.
Static Public Attributes
static const int NullStateId = -1
Null value for a state index.
Protected Member Functions
void allocateSpeciesMutator (int nMolecule, int nState)
Allocate arrays of molecule state ids and statistical weights.
void setMoleculeStateId (const Molecule &molecule, int stateId)
Set the state id of a specific molecule.
Constructor & Destructor Documentation
McMd::SpeciesMutator::SpeciesMutator ()
Constructor.
The constructor sets Species::isSpeciesMutator_ to true.
Definition at line 19 of file SpeciesMutator.cpp.
McMd::SpeciesMutator::~SpeciesMutator () [virtual]
Destructor.
Definition at line 27 of file SpeciesMutator.cpp.
Member Function Documentation
void McMd::SpeciesMutator::readMoleculeState (std::istream & in, Molecule & molecule) [virtual]
Read the state id for one molecule from a configuration file stream.
Parameters:
in input stream
molecule molecule of interest
Definition at line 84 of file SpeciesMutator.cpp.
References setMoleculeState().
Referenced by McMd::McMdConfigIo::read().
void McMd::SpeciesMutator::writeMoleculeState (std::ostream & out, const Molecule & molecule) const [virtual]
Write the state id for one molecule to a configuration file stream.
Parameters:
out output stream
molecule molecule of interest
Definition at line 75 of file SpeciesMutator.cpp.
References moleculeStateId().
Referenced by McMd::McMdConfigIo::write().
virtual void McMd::SpeciesMutator::setMoleculeState (Molecule & molecule, int stateId) [pure virtual]
Change the state of a specific molecule.
The method should be used to implement MC moves that change the internal state of a molecule, after the previous stateId and bead positions are known. The method can use knowledge of the previous stateId and previous bead positions to implement transitions between a specific pairs of states.
Parameters:
molecule reference to molecule of interest.
stateId integer index of new state.
Implemented in McMd::HomopolymerSG.
Referenced by McMd::HomopolymerSemiGrandMove::move(), and readMoleculeState().
void McMd::SpeciesMutator::setWeight (int stateId, double weight) [inline]
Set the statistical weight associated with a specific state.
Parameters:
stateId integer index of state
weight desired statistical weight
Definition at line 229 of file SpeciesMutator.h.
Referenced by McMd::HomopolymerSG::readSpeciesParam().
int McMd::SpeciesMutator::moleculeStateId (const Molecule & molecule) const [inline]
Get the state id for a specific molecule.
Parameters:
molecule reference to molecule of interest.
Definition at line 201 of file SpeciesMutator.h.
References McMd::Molecule::id().
Referenced by McMd::HomopolymerSemiGrandMove::move(), and writeMoleculeState().
int McMd::SpeciesMutator::nState () const [inline]
Get the number of possible molecule states.
Definition at line 215 of file SpeciesMutator.h.
Referenced by allocateSpeciesMutator(), McMd::TypeDistribution::loadParameters(), and McMd::TypeDistribution::readParameters().
int McMd::SpeciesMutator::stateOccupancy (int stateId) const [inline]
Get the number of molecules with a specified state.
Parameters:
stateId index for specific state.
Definition at line 208 of file SpeciesMutator.h.
Referenced by McMd::SemiGrandDistribution::sample(), and McMd::TypeDistribution::sample().
double McMd::SpeciesMutator::stateWeight (int stateId) const [inline]
Get the statistical weight for a specfic molecular state.
Parameters:
stateId index for specific state.
Definition at line 222 of file SpeciesMutator.h.
Referenced by McMd::HomopolymerSemiGrandMove::move().
void McMd::SpeciesMutator::allocateSpeciesMutator (int nMolecule, int nState) [protected]
Allocate arrays of molecule state ids and statistical weights.
Parameters:
nMolecule number of molecules allocated for species.
nState number of possible internal states.
Definition at line 33 of file SpeciesMutator.cpp.
References Util::DArray< Data >::allocate(), nState(), and NullStateId.
Referenced by McMd::HomopolymerSG::readSpeciesParam().
void McMd::SpeciesMutator::setMoleculeStateId (const Molecule & molecule, int stateId) [protected]
Set the state id of a specific molecule.
This method should be called by the public method setMoleculeState. to set the state id for a molecule. It does not modify the molecule.
See also:
setMoleculeState
Parameters:
molecule reference to molecule of interest.
stateId integer index of new state.
Definition at line 57 of file SpeciesMutator.cpp.
References McMd::Molecule::id(), NullStateId, and UTIL_THROW.
Referenced by McMd::HomopolymerSG::setMoleculeState().
Member Data Documentation
const int McMd::SpeciesMutator::NullStateId = -1 [static]
Null value for a state index.
Definition at line 133 of file SpeciesMutator.h.
Referenced by allocateSpeciesMutator(), and setMoleculeStateId().
The documentation for this class was generated from the following files:
SpeciesMutator.h
SpeciesMutator.cpp