Simpatico: DdMd::DdMdOrderedConfigIo Class Reference
DdMd::DdMdOrderedConfigIo Class Reference
ConfigIos
Detailed Description
Native / default format for configuration files.
DdMdOrderedConfigIo is a ConfigIo that implements the default configuration file format for ddSim, like DdMdConfigIo, but that outputs atoms in sequential order, sorted by atom id.
Definition at line 32 of file DdMdOrderedConfigIo.h.
#include <DdMdOrderedConfigIo.h>
Classes
struct IoAtom
struct IoGroup
Public Member Functions
DdMdOrderedConfigIo ()
Default constructor.
DdMdOrderedConfigIo (Simulation &simulation)
Constructor.
virtual void readConfig (std::ifstream &file, MaskPolicy maskPolicy)
Read configuration file.
virtual void writeConfig (std::ofstream &file)
Write configuration file.
Constructor & Destructor Documentation
DdMd::DdMdOrderedConfigIo::DdMdOrderedConfigIo ()
Default constructor.
Definition at line 47 of file DdMdOrderedConfigIo.cpp.
References Util::ParamComposite::setClassName().
DdMd::DdMdOrderedConfigIo::DdMdOrderedConfigIo (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object.
Definition at line 54 of file DdMdOrderedConfigIo.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void DdMd::DdMdOrderedConfigIo::readConfig (std::ifstream & file, MaskPolicy maskPolicy) [virtual]
Read configuration file.
This routine opens and reads a file on the master, and distributes atom data among the processors.
Precondition:
There are no atoms, ghosts, or groups.
AtomStorage is set for scaled / generalized coordinates
Postcondition:
atomic coordinates are scaled / generalized
there are no ghosts
Parameters:
file input file stream
maskPolicy MaskPolicy to be used in setting atom masks
Implements DdMd::ConfigIo.
Definition at line 91 of file DdMdOrderedConfigIo.cpp.
References DdMd::AtomDistributor::addAtom(), DdMd::ConfigIo::angleDistributor(), DdMd::ConfigIo::angleStorage(), DdMd::ConfigIo::atomDistributor(), DdMd::ConfigIo::atomStorage(), Util::bcast(), DdMd::ConfigIo::boundary(), DdMd::ConfigIo::dihedralDistributor(), DdMd::ConfigIo::dihedralStorage(), DdMd::ConfigIo::domain(), DdMd::GroupStorage< N >::isValid(), DdMd::AtomDistributor::newAtomPtr(), DdMd::Atom::position(), DdMd::AtomDistributor::receive(), DdMd::AtomDistributor::send(), DdMd::ConfigIo::setAtomMasks(), DdMd::Atom::setId(), DdMd::Atom::setTypeId(), DdMd::AtomDistributor::setup(), DdMd::AtomStorage::totalAtomCapacity(), Util::OrthorhombicBoundary::transformCartToGen(), UTIL_THROW, DdMd::AtomDistributor::validate(), and DdMd::Atom::velocity().
void DdMd::DdMdOrderedConfigIo::writeConfig (std::ofstream & file) [virtual]
Write configuration file.
This routine opens and writes a file on the master, collecting atom and group data from all processors. Atoms and Groups are output in order, sorted by global id.
Parameters:
file output file stream
Implements DdMd::ConfigIo.
Definition at line 260 of file DdMdOrderedConfigIo.cpp.
References DdMd::ConfigIo::angleCollector(), DdMd::ConfigIo::angleStorage(), DdMd::ConfigIo::atomCollector(), DdMd::ConfigIo::atomStorage(), DdMd::ConfigIo::boundary(), DdMd::GroupStorage< N >::capacity(), DdMd::AtomStorage::computeNAtomTotal(), DdMd::ConfigIo::dihedralCollector(), DdMd::ConfigIo::dihedralStorage(), DdMd::ConfigIo::domain(), DdMd::Atom::id(), DdMd::AtomStorage::isCartesian(), DdMd::AtomStorage::nAtomTotal(), DdMd::AtomCollector::nextPtr(), DdMd::Atom::position(), DdMd::AtomCollector::send(), DdMd::AtomCollector::setup(), Util::OrthorhombicBoundary::transformGenToCart(), DdMd::Atom::typeId(), UTIL_THROW, and DdMd::Atom::velocity().
The documentation for this class was generated from the following files:
DdMdOrderedConfigIo.h
DdMdOrderedConfigIo.cpp