Simpatico: McMd::RingRouseAutoCorr Class Reference
McMd::RingRouseAutoCorr Class Reference
Diagnostics
Detailed Description
Autocorrelation for Rouse mode coefficients of a ring molecule.
Definition at line 30 of file RingRouseAutoCorr.h.
#include <RingRouseAutoCorr.h>
Public Member Functions
RingRouseAutoCorr (System &system)
Constructor.
virtual ~RingRouseAutoCorr ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from file, and allocate data array.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize internal state to/from archive.
virtual void setup ()
Allocate memory and initialize Rouse mode eigenvector p.
virtual void sample (long iStep)
Evaluate end-to-end vectors of all chains, add to ensemble.
virtual void output ()
Output results to file after simulation is completed.
Constructor & Destructor Documentation
McMd::RingRouseAutoCorr::RingRouseAutoCorr (System & system)
Constructor.
Parameters:
system reference to parent System
Definition at line 30 of file RingRouseAutoCorr.cpp.
References Util::ParamComposite::setClassName().
McMd::RingRouseAutoCorr::~RingRouseAutoCorr () [virtual]
Destructor.
Definition at line 47 of file RingRouseAutoCorr.cpp.
Member Function Documentation
void McMd::RingRouseAutoCorr::readParameters (std::istream & in) [virtual]
Read parameters from file, and allocate data array.
Parameters:
in input parameter stream
Reimplemented from McMd::Diagnostic.
Definition at line 53 of file RingRouseAutoCorr.cpp.
References Util::DArray< Data >::allocate(), McMd::Species::capacity(), McMd::Species::nAtom(), McMd::Diagnostic::readInterval(), McMd::Diagnostic::readOutputFileName(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::RingRouseAutoCorr::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::Diagnostic.
Definition at line 81 of file RingRouseAutoCorr.cpp.
References Util::DArray< Data >::allocate(), McMd::Species::capacity(), McMd::Species::nAtom(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::RingRouseAutoCorr::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::Diagnostic.
Definition at line 128 of file RingRouseAutoCorr.cpp.
template<class Archive > void McMd::RingRouseAutoCorr::serialize (Archive & ar, const unsigned int version)
Serialize internal state to/from archive.
Parameters:
ar archive
version id for archive version
Reimplemented from McMd::Diagnostic.
Definition at line 135 of file RingRouseAutoCorr.h.
References McMd::serialize().
void McMd::RingRouseAutoCorr::setup () [virtual]
Allocate memory and initialize Rouse mode eigenvector p.
Reimplemented from McMd::Diagnostic.
Definition at line 134 of file RingRouseAutoCorr.cpp.
References McMd::Species::nAtom(), McMd::System::nMolecule(), Util::AutoCorrArray< Data, Product >::setParam(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::RingRouseAutoCorr::sample (long iStep) [virtual]
Evaluate end-to-end vectors of all chains, add to ensemble.
Parameters:
iStep counter for number of steps
Implements McMd::Diagnostic.
Definition at line 170 of file RingRouseAutoCorr.cpp.
References McMd::Molecule::atom(), McMd::System::boundary(), Util::OrthorhombicBoundary::distanceSq(), McMd::Diagnostic::isAtInterval(), McMd::System::molecule(), Util::Vector::multiply(), McMd::Atom::position(), Util::AutoCorrArray< Data, Product >::sample(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::RingRouseAutoCorr::output () [virtual]
Output results to file after simulation is completed.
Reimplemented from McMd::Diagnostic.
Definition at line 210 of file RingRouseAutoCorr.cpp.
References McMd::Diagnostic::fileMaster(), Util::FileMaster::openOutputFile(), Util::AutoCorrArray< Data, Product >::output(), McMd::Diagnostic::outputFileName(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
RingRouseAutoCorr.h
RingRouseAutoCorr.cpp