Simpatico: DdMd::StressAutoCorrelation Class Reference
DdMd::StressAutoCorrelation Class Reference
Analyzers
Detailed Description
Periodically write (tensor) StressTensor to file.
Definition at line 27 of file ddMd/analyzers/StressAutoCorrelation.h.
#include <StressAutoCorrelation.h>
Public Member Functions
StressAutoCorrelation (Simulation &simulation)
Constructor.
virtual ~StressAutoCorrelation ()
Destructor.
virtual void readParameters (std::istream &in)
Read dumpPrefix and interval.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void clear ()
Clear nSample counter.
virtual void setup ()
Setup accumulator!
virtual void sample (long iStep)
Sample virial stress to accumulators.
virtual void output ()
Dump configuration to file.
Constructor & Destructor Documentation
DdMd::StressAutoCorrelation::StressAutoCorrelation (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object.
Definition at line 27 of file StressAutoCorrelation.cpp.
References Util::ParamComposite::setClassName().
virtual DdMd::StressAutoCorrelation::~StressAutoCorrelation () [inline, virtual]
Destructor.
Definition at line 42 of file ddMd/analyzers/StressAutoCorrelation.h.
Member Function Documentation
void DdMd::StressAutoCorrelation::readParameters (std::istream & in) [virtual]
Read dumpPrefix and interval.
Parameters:
in input parameter file
Reimplemented from Util::ParamComposite.
Definition at line 37 of file StressAutoCorrelation.cpp.
References DdMd::Analyzer::readInterval(), DdMd::Analyzer::readOutputFileName(), and Util::AutoCorrArray< Data, Product >::setParam().
void DdMd::StressAutoCorrelation::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from DdMd::Analyzer.
Definition at line 55 of file StressAutoCorrelation.cpp.
References Util::MpiLoader< IArchive >::load(), DdMd::Analyzer::loadInterval(), DdMd::Analyzer::loadOutputFileName(), Util::AutoCorrArray< Data, Product >::loadParameters(), and DdMd::Analyzer::simulation().
void DdMd::StressAutoCorrelation::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from DdMd::Analyzer.
Definition at line 73 of file StressAutoCorrelation.cpp.
References DdMd::Analyzer::saveInterval(), DdMd::Analyzer::saveOutputFileName(), and DdMd::Analyzer::simulation().
void DdMd::StressAutoCorrelation::clear () [virtual]
Clear nSample counter.
Reimplemented from DdMd::Analyzer.
Definition at line 88 of file StressAutoCorrelation.cpp.
References Util::AutoCorrArray< Data, Product >::clear(), DdMd::Analyzer::simulation(), and UTIL_THROW.
void DdMd::StressAutoCorrelation::setup () [virtual]
Setup accumulator!
Reimplemented from DdMd::Analyzer.
Definition at line 103 of file StressAutoCorrelation.cpp.
References Util::AutoCorrArray< Data, Product >::clear(), Util::AutoCorrArray< Data, Product >::setNEnsemble(), and UTIL_THROW.
void DdMd::StressAutoCorrelation::sample (long iStep) [virtual]
Sample virial stress to accumulators.
Parameters:
iStep MD step index
Implements DdMd::Analyzer.
Definition at line 117 of file StressAutoCorrelation.cpp.
References Util::Tensor::add(), Util::DArray< Data >::allocate(), DdMd::Simulation::atomStorage(), DdMd::Simulation::computeKineticEnergy(), DdMd::Simulation::computeKineticStress(), DdMd::AtomStorage::computeNAtomTotal(), DdMd::Simulation::computeVirialStress(), DdMd::Simulation::domain(), DdMd::Analyzer::isAtInterval(), DdMd::Domain::isMaster(), DdMd::Simulation::kineticPressure(), DdMd::Simulation::kineticStress(), DdMd::AtomStorage::nAtomTotal(), Util::AutoCorrArray< Data, Product >::sample(), DdMd::Analyzer::simulation(), DdMd::Simulation::virialPressure(), and DdMd::Simulation::virialStress().
void DdMd::StressAutoCorrelation::output () [virtual]
Dump configuration to file.
Reimplemented from DdMd::Analyzer.
Definition at line 160 of file StressAutoCorrelation.cpp.
References Util::AutoCorrArray< Data, Product >::average(), Util::AutoCorrArray< Data, Product >::bufferCapacity(), DdMd::Simulation::fileMaster(), Util::AutoCorrArray< Data, Product >::nSample(), Util::FileMaster::openOutputFile(), Util::AutoCorrArray< Data, Product >::output(), DdMd::Analyzer::outputFileName(), DdMd::Analyzer::simulation(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
ddMd/analyzers/StressAutoCorrelation.h
StressAutoCorrelation.cpp