Simpatico: McMd::MdConfigIo Class Reference
McMd::MdConfigIo Class Reference
Configuration File IO
Detailed Description
ConfigIo for MD simulations (includes velocities).
Definition at line 29 of file MdConfigIo.h.
#include <MdConfigIo.h>
Public Member Functions
MdConfigIo (System &system)
Constructor.
virtual ~MdConfigIo ()
Destructor.
Public Member Functions inherited from McMd::McMdConfigIo
McMdConfigIo (System &system)
Constructor.
virtual ~McMdConfigIo ()
Destructor.
virtual void read (std::istream &in)
Read configuration (particle positions) from file.
virtual void write (std::ostream &out)
Write configuration (particle positions) to file.
Public Member Functions inherited from McMd::ConfigIo
ConfigIo (System &system)
Constructor.
virtual ~ConfigIo ()
Destructor.
Protected Member Functions
virtual void readAtom (std::istream &out, Atom &atom)
Read data for one atom.
virtual void writeAtom (std::ostream &out, const Atom &atom)
Write data for one atom.
Constructor & Destructor Documentation
McMd::MdConfigIo::MdConfigIo (System & system)
Constructor.
Definition at line 24 of file MdConfigIo.cpp.
McMd::MdConfigIo::~MdConfigIo () virtual
Destructor.
Definition at line 31 of file MdConfigIo.cpp.
Member Function Documentation
void McMd::MdConfigIo::readAtom (std::istream & out, Atom & atom) protected virtual
Read data for one atom.
Implements McMd::McMdConfigIo.
Definition at line 37 of file MdConfigIo.cpp.
References McMd::ConfigIo::boundary(), McMd::Atom::position(), and McMd::Atom::velocity().
void McMd::MdConfigIo::writeAtom (std::ostream & out, const Atom & atom) protected virtual
Write data for one atom.
Implements McMd::McMdConfigIo.
Definition at line 52 of file MdConfigIo.cpp.
References Util::Dimension, McMd::Atom::position(), and McMd::Atom::velocity().
The documentation for this class was generated from the following files:
MdConfigIo.h
MdConfigIo.cpp