Simpatico: DdMd::AsymmSFGrid Class Reference
DdMd::AsymmSFGrid Class Reference
Analyzers
Detailed Description
AsymmSFGrid evaluates structure factors in Fourier space.
This class evaluates the structures factors for all wavevectors for all wavevectors within a grid, within a region in which all of the h, k, l integer wavevector components (i.e., Miller indices) has an absolute magnitude less than or equal to a parameter hMax.
The class also requires a user to specify a variable lattice of enum type LatticeSystem whose value (e.g., Cubic, Orthorhombic, Triclinic) determines the symmetry group that is used to group group equivalent wavevectors into "stars". Use Triclinic to impose no symmetry.
Example: Here is parameter file for a system with nAtomType = 2, with two monomer types 0 and 1, for calculating the total, 00, and 01 correlation functions on a grid with Miller indices up and including 5:
AsymmSFGrid{
   interval                     1000
   outputFileName     AsymmSFGrid
   nAtomTypeIdPair                  3
   atomTypeIdPairs          -1     -1
                             0      0
                             0      1
   hMax                             5
   lattice                      Cubic
}
At the end of a simulation, all of the structure factors are output in a file with a suffix *.dat. Each line in this file contains the 3 Miller indices of a wavevector, the absolute magnitude of the wavevector, and a list of nAtomTypeIdPair structure factor values for the wavevector, one for each atomTypeId pair.
Definition at line 59 of file AsymmSFGrid.h.
#include <AsymmSFGrid.h>
Public Member Functions
AsymmSFGrid (Simulation &simulation)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void output ()
Output structure factors, averaged over stars.
Public Member Functions inherited from DdMd::AsymmSF
AsymmSF (Simulation &simulation)
Constructor.
~AsymmSF ()
Destructor.
virtual void clear ()
Clear accumulators.
void sample (long iStep)
Add particles to AsymmSF accumulators.
Public Member Functions inherited from DdMd::Analyzer
Analyzer (Simulation &simulation)
Constructor.
virtual ~Analyzer ()
Destructor.
virtual void setup ()
Setup before simulation.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from DdMd::Analyzer
static void initStatic ()
Define and initialize baseInterval.
Static Public Attributes inherited from DdMd::AsymmSF
static const int Samples = 100000
Number of analyzer samples in simulation.
Protected Member Functions inherited from DdMd::AsymmSF
void makeWaveVectors ()
Update wavevectors.
Protected Attributes inherited from DdMd::AsymmSF
std::ofstream outputFile_
Output file stream.
DMatrix< double > structureFactors_
Structure factor accumulators.
DMatrix< std::complex< double > > fourierModes_
Fourier modes of concentration.
DMatrix< std::complex< double > > totalFourierModes_
Total fourier modes of concentration.
DArray< IntVector > waveIntVectors_
Array of Miller index IntVectors for wavevectors.
DArray< Vector > waveVectors_
Array of floating point wave vectors.
DMatrix< double > modes_
Array of mode vectors.
DArray< std::vector< double > > maximumValue_
Array of vector of maximum structure factor values.
DArray< std::vector< IntVector > > maximumWaveIntVector_
Array of vector of Miller index IntVector with maximum S(q).
DArray< std::vector< double > > maximumQ_
Array of vector of magnitudes of waveVector with maximum S(q).
int nWave_
Number of wavevectors.
int nMode_
Number of mode vectors.
int nSample_
Number of samples thus far.
int nAtomType_
Number of atom types, copied from Simulation::nAtomType().
bool isInitialized_
Has readParam been called?
Constructor & Destructor Documentation
DdMd::AsymmSFGrid::AsymmSFGrid (Simulation & simulation)
Constructor.
Parameters
simulation reference to parent DdMd::Simulation object
Definition at line 27 of file AsymmSFGrid.cpp.
Member Function Documentation
void DdMd::AsymmSFGrid::readParameters (std::istream & in) virtual
Read parameters from file.
Read parameters from file, and allocate data array.
Input format:
int interval sampling interval
string outputFileName output file base name
int nMode number of modes
DMatrix<double> modes mode vectors
int hMax maximum Miller index
Parameters
in input parameter stream
Reimplemented from DdMd::AsymmSF.
Definition at line 35 of file AsymmSFGrid.cpp.
References Util::SymmetryGroup< Symmetry >::add(), Util::DMatrix< Data >::allocate(), Util::DArray< Data >::allocate(), Util::Log::file(), DdMd::AsymmSF::fourierModes_, DdMd::AsymmSF::isInitialized_, Util::SymmetryGroup< Symmetry >::makeCompleteGroup(), Util::PointGroup::makeStar(), DdMd::AsymmSF::maximumQ_, DdMd::AsymmSF::maximumValue_, DdMd::AsymmSF::maximumWaveIntVector_, DdMd::AsymmSF::modes_, DdMd::Simulation::nAtomType(), DdMd::AsymmSF::nAtomType_, DdMd::AsymmSF::nMode_, DdMd::AsymmSF::nSample_, DdMd::AsymmSF::nWave_, Util::PointSymmetry::R(), DdMd::Analyzer::readInterval(), DdMd::Analyzer::readOutputFileName(), DdMd::AsymmSF::Samples, DdMd::Analyzer::simulation(), Util::FSArray< Data, Capacity >::size(), DdMd::AsymmSF::structureFactors_, DdMd::AsymmSF::totalFourierModes_, UTIL_THROW, DdMd::AsymmSF::waveIntVectors_, and DdMd::AsymmSF::waveVectors_.
void DdMd::AsymmSFGrid::output () virtual
Output structure factors, averaged over stars.
Reimplemented from DdMd::AsymmSF.
Definition at line 242 of file AsymmSFGrid.cpp.
References Util::Dimension, DdMd::Simulation::fileMaster(), DdMd::AsymmSF::maximumQ_, DdMd::AsymmSF::maximumValue_, DdMd::AsymmSF::maximumWaveIntVector_, DdMd::AsymmSF::nMode_, DdMd::AsymmSF::nSample_, Util::FileMaster::openOutputFile(), DdMd::AsymmSF::outputFile_, DdMd::Analyzer::outputFileName(), DdMd::Analyzer::simulation(), DdMd::AsymmSF::structureFactors_, DdMd::AsymmSF::waveIntVectors_, DdMd::AsymmSF::waveVectors_, and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
AsymmSFGrid.h
AsymmSFGrid.cpp