Simpatico: DdMd::LogEnergy Class Reference
DdMd::LogEnergy Class Reference
Analyzers
Detailed Description
Periodically write simulation energies to Log output.
See also:
param file format
Definition at line 26 of file LogEnergy.h.
#include <LogEnergy.h>
Public Member Functions
LogEnergy (Simulation &simulation)
Constructor.
virtual ~LogEnergy ()
Destructor.
virtual void readParameters (std::istream &in)
Read dumpPrefix and interval.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void clear ()
Clear nSample counter.
virtual void sample (long iStep)
Dump configuration to file.
Constructor & Destructor Documentation
DdMd::LogEnergy::LogEnergy (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object.
Definition at line 34 of file LogEnergy.cpp.
References Util::ParamComposite::setClassName().
virtual DdMd::LogEnergy::~LogEnergy () [inline, virtual]
Destructor.
Definition at line 41 of file LogEnergy.h.
Member Function Documentation
void DdMd::LogEnergy::readParameters (std::istream & in) [virtual]
Read dumpPrefix and interval.
Parameters:
in input parameter file
Reimplemented from Util::ParamComposite.
Definition at line 43 of file LogEnergy.cpp.
References DdMd::Analyzer::readInterval().
void DdMd::LogEnergy::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from DdMd::Analyzer.
Definition at line 52 of file LogEnergy.cpp.
References Util::MpiLoader< IArchive >::load(), and DdMd::Analyzer::loadInterval().
void DdMd::LogEnergy::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from DdMd::Analyzer.
Definition at line 63 of file LogEnergy.cpp.
References DdMd::Analyzer::saveInterval().
void DdMd::LogEnergy::clear () [virtual]
Clear nSample counter.
Reimplemented from DdMd::Analyzer.
Definition at line 72 of file LogEnergy.cpp.
void DdMd::LogEnergy::sample (long iStep) [virtual]
Dump configuration to file.
Parameters:
iStep MC step index
Implements DdMd::Analyzer.
Definition at line 78 of file LogEnergy.cpp.
References DdMd::Simulation::anglePotential(), DdMd::Simulation::bondPotential(), DdMd::Simulation::computeKineticEnergy(), DdMd::Simulation::computePotentialEnergies(), DdMd::Simulation::dihedralPotential(), DdMd::Simulation::domain(), DdMd::Potential::energy(), Util::Log::file(), DdMd::Analyzer::isAtInterval(), DdMd::Domain::isMaster(), DdMd::Simulation::kineticEnergy(), DdMd::Simulation::nAngleType(), DdMd::Simulation::nBondType(), DdMd::Simulation::nDihedralType(), DdMd::Simulation::pairPotential(), and DdMd::Analyzer::simulation().
The documentation for this class was generated from the following files:
LogEnergy.h
LogEnergy.cpp