Simpatico: McMd::PerturbDerivative Class Reference
McMd::PerturbDerivative Class Reference
Diagnostics
Detailed Description
PerturbDerivative returns average value of Perturbation::derivative().
Definition at line 28 of file PerturbDerivative.h.
#include <PerturbDerivative.h>
Public Member Functions
PerturbDerivative (System &system)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters and initialize.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Clear accumulator.
virtual void sample (long iStep)
Calculate, analyze and/or output a physical quantity.
virtual void output ()
Output results at end of simulation.
Constructor & Destructor Documentation
McMd::PerturbDerivative::PerturbDerivative (System & system)
Constructor.
Definition at line 26 of file PerturbDerivative.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::PerturbDerivative::readParameters (std::istream & in) [virtual]
Read parameters and initialize.
Reimplemented from McMd::Diagnostic.
Definition at line 34 of file PerturbDerivative.cpp.
References McMd::Diagnostic::fileMaster(), Util::Average::nSamplePerBlock(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), McMd::Diagnostic::readInterval(), McMd::Diagnostic::readOutputFileName(), and Util::Average::setNSamplePerBlock().
void McMd::PerturbDerivative::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::Diagnostic.
Definition at line 55 of file PerturbDerivative.cpp.
References McMd::Diagnostic::fileMaster(), Util::FileMaster::openOutputFile(), and McMd::Diagnostic::outputFileName().
void McMd::PerturbDerivative::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::Diagnostic.
Definition at line 71 of file PerturbDerivative.cpp.
template<class Archive > void McMd::PerturbDerivative::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Diagnostic.
Definition at line 104 of file PerturbDerivative.h.
References McMd::serialize().
void McMd::PerturbDerivative::setup () [virtual]
Clear accumulator.
Reimplemented from McMd::Diagnostic.
Definition at line 77 of file PerturbDerivative.cpp.
References Util::Average::clear(), and UTIL_THROW.
void McMd::PerturbDerivative::sample (long iStep) [virtual]
Calculate, analyze and/or output a physical quantity.
Take an action if iStep is a multiple of interval. If iStep is not a multiple of interval, this method should do nothing and return immediately.
Parameters:
iStep current simulation step index.
Implements McMd::Diagnostic.
Definition at line 89 of file PerturbDerivative.cpp.
References McMd::Diagnostic::isAtInterval(), Util::Average::sample(), and McMd::SystemDiagnostic< System >::system().
void McMd::PerturbDerivative::output () [virtual]
Output results at end of simulation.
Reimplemented from McMd::Diagnostic.
Definition at line 99 of file PerturbDerivative.cpp.
References McMd::Diagnostic::fileMaster(), Util::Average::nSamplePerBlock(), Util::FileMaster::openOutputFile(), Util::Average::output(), McMd::Diagnostic::outputFileName(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
PerturbDerivative.h
PerturbDerivative.cpp