Simpatico: McMd::Analyzer Class Reference
McMd::Analyzer Class Reference abstract
McMd namespace » Analyzers
Detailed Description
Abstract base for periodic output and/or analysis actions.
The periodic action associated with an Analyzer can involve sampling of a physical property and adding it to statistical accumulator, outputting it to file, or both. This periodic action must be implemented by the pure virtual sample() method.
The sample() method should take the desired action only when the simulation step index is an integer multiple of the associated interval parameter. The interval must be a positive integer that is a multiple of the static member Analyzer::baseInterval.
The virtual sample() method does not take any parameters. An Analyzer must thus access its parent Simulation and/or System via a pointer, which is usually initialized in its subclass constructor.
Analyzer subclasses that are associated with one System, McSystem or MdSystem (i.e., almost all of them) should be derived from the SystemAnalyzer<class SystemType> class template. This takes a reference to the parent system as parameter to its constructor. An Analyzer subclass that can be used with any System should be derived from SystemAnalyzer<System>, and one that can be used only with a MdSystem or McSystem should be derived from SystemAnalyzer<MdSystem> or SystemAnalyzer<MdSystem>, respectively.
Definition at line 52 of file mcMd/analyzers/Analyzer.h.
#include <Analyzer.h>
Public Member Functions
Analyzer ()
Default constructor.
virtual ~Analyzer ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from archive.
virtual void loadParameters (Serializable::IArchive &ar)
Load parameters from archive.
virtual void save (Serializable::OArchive &ar)
Load parameters to archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Complete any required initialization.
virtual void sample (long iStep)=0
Calculate, analyze and/or output a physical quantity.
virtual void output ()
Output any results at the end of the simulation.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Static Public Member Functions
static void initStatic ()
Define and initialize baseInterval.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Public Attributes
static long baseInterval = 1
The interval for an Analyzer must be a multiple of baseInterval.
Protected Member Functions
void setFileMaster (FileMaster &fileMaster)
Set the FileMaster to use to open files.
void readInterval (std::istream &in)
Read interval from file, with error checking.
void readOutputFileName (std::istream &in)
Read outputFileName from file.
void loadInterval (Serializable::IArchive &ar)
Load interval from archive, with error checking.
void loadOutputFileName (Serializable::IArchive &ar)
Load output file name from archive.
FileMaster & fileMaster ()
Get the FileMaster by reference.
const std::string & outputFileName () const
Return outputFileName string.
std::string outputFileName (const std::string &suffix) const
Return outputFileName string with added suffix.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
std::string outputFileName_
Base name of output file(s).
long interval_
Number of simulation steps between subsequent actions.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Constructor & Destructor Documentation
McMd::Analyzer::Analyzer ()
Default constructor.
Definition at line 27 of file mcMd/analyzers/Analyzer.cpp.
McMd::Analyzer::~Analyzer () virtual
Destructor.
Definition at line 37 of file mcMd/analyzers/Analyzer.cpp.
Member Function Documentation
void McMd::Analyzer::readParameters (std::istream & in) virtual
Read parameters from archive.
Default implementation, reads interval and outputFileName.
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Reimplemented in McMd::IntraStructureFactor, McMd::StructureFactorP, McMd::VanHove, McMd::IntraStructureFactorGrid, McMd::StructureFactorGrid, McMd::StructureFactorPGrid, McMd::BlockRadiusGyration, McMd::RadiusGyration, McMd::StructureFactor, McMd::IntraPairAutoCorr, McMd::IntraBondTensorAutoCorr< SystemType >, McMd::IntraBondTensorAutoCorr< MdSystem >, McMd::IntraBondTensorAutoCorr< McSystem >, McMd::CompositionProfile, McMd::RDF, McMd::ConfigWriter, McMd::MdPairEnergyCoefficients, McMd::BennettsMethod, McMd::IntraBondStressAutoCorr< SystemType >, McMd::LinearRouseAutoCorr, McMd::IntraBondStressAutoCorr< MdSystem >, McMd::IntraBondStressAutoCorr< McSystem >, McMd::McMuExchange, McMd::McVirialStressTensorAverage, McMd::MdVirialStressTensorAverage, McMd::RingRouseAutoCorr, McMd::McNVTChemicalPotential, McMd::McPairEnergyAverage, McMd::ClusterHistogram, McMd::PressureAverage< SystemType >, McMd::StressAutoCorr< SystemType >, McMd::StressTensorAverage< SystemType >, McMd::PressureAverage< MdSystem >, McMd::PressureAverage< McSystem >, McMd::StressAutoCorr< MdSystem >, McMd::ComMSD, McMd::BondLengthDist, McMd::AtomMSD, McMd::McEnergyOutput, McMd::AverageAnalyzer< SystemType >, McMd::AverageAnalyzer< McSystem >, McMd::MdEnergyOutput, McMd::MdKineticEnergyAverage, McMd::BoundaryAverage, McMd::TypeDistribution, McMd::MdPotentialEnergyAverage, McMd::PerturbDerivative, McMd::SemiGrandDistribution, and McMd::LogProgress.
Definition at line 43 of file mcMd/analyzers/Analyzer.cpp.
References readInterval(), and readOutputFileName().
Referenced by McMd::RDF::readParameters().
void McMd::Analyzer::loadParameters (Serializable::IArchive & ar) virtual
Load parameters from archive.
Default implementation, loads interval and outputFileName.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Reimplemented in McMd::IntraStructureFactor, McMd::StructureFactorP, McMd::VanHove, McMd::BlockRadiusGyration, McMd::IntraStructureFactorGrid, McMd::StructureFactorGrid, McMd::StructureFactorPGrid, McMd::RadiusGyration, McMd::StructureFactor, McMd::McMuExchange, McMd::CompositionProfile, McMd::IntraPairAutoCorr, McMd::ClusterHistogram, McMd::IntraBondTensorAutoCorr< SystemType >, McMd::IntraBondTensorAutoCorr< MdSystem >, McMd::IntraBondTensorAutoCorr< McSystem >, McMd::ConfigWriter, McMd::RDF, McMd::MdPairEnergyCoefficients, McMd::BennettsMethod, McMd::IntraBondStressAutoCorr< SystemType >, McMd::LinearRouseAutoCorr, McMd::IntraBondStressAutoCorr< MdSystem >, McMd::IntraBondStressAutoCorr< McSystem >, McMd::McVirialStressTensorAverage, McMd::MdVirialStressTensorAverage, McMd::RingRouseAutoCorr, McMd::McPairEnergyAverage, McMd::PressureAverage< SystemType >, McMd::StressAutoCorr< SystemType >, McMd::StressTensorAverage< SystemType >, McMd::PressureAverage< MdSystem >, McMd::PressureAverage< McSystem >, McMd::StressAutoCorr< MdSystem >, McMd::ComMSD, McMd::BondLengthDist, McMd::AtomMSD, McMd::McEnergyOutput, McMd::AverageAnalyzer< SystemType >, McMd::AverageAnalyzer< McSystem >, McMd::MdEnergyOutput, McMd::MdKineticEnergyAverage, McMd::BoundaryAverage, McMd::TypeDistribution, McMd::MdPotentialEnergyAverage, McMd::PerturbDerivative, McMd::SemiGrandDistribution, and McMd::LogProgress.
Definition at line 83 of file mcMd/analyzers/Analyzer.cpp.
References loadInterval(), and loadOutputFileName().
Referenced by McMd::SemiGrandDistribution::loadParameters(), McMd::PerturbDerivative::loadParameters(), McMd::TypeDistribution::loadParameters(), McMd::BoundaryAverage::loadParameters(), McMd::AverageAnalyzer< SystemType >::loadParameters(), McMd::McEnergyOutput::loadParameters(), McMd::ComMSD::loadParameters(), McMd::PressureAverage< SystemType >::loadParameters(), McMd::StressAutoCorr< SystemType >::loadParameters(), McMd::StressTensorAverage< SystemType >::loadParameters(), McMd::McPairEnergyAverage::loadParameters(), McMd::RingRouseAutoCorr::loadParameters(), McMd::MdVirialStressTensorAverage::loadParameters(), McMd::McVirialStressTensorAverage::loadParameters(), McMd::BennettsMethod::loadParameters(), McMd::IntraBondStressAutoCorr< SystemType >::loadParameters(), McMd::LinearRouseAutoCorr::loadParameters(), McMd::RDF::loadParameters(), McMd::ConfigWriter::loadParameters(), McMd::IntraBondTensorAutoCorr< SystemType >::loadParameters(), McMd::ClusterHistogram::loadParameters(), McMd::IntraPairAutoCorr::loadParameters(), McMd::CompositionProfile::loadParameters(), McMd::RadiusGyration::loadParameters(), McMd::StructureFactor::loadParameters(), McMd::StructureFactorGrid::loadParameters(), McMd::StructureFactorPGrid::loadParameters(), McMd::IntraStructureFactorGrid::loadParameters(), McMd::BlockRadiusGyration::loadParameters(), McMd::VanHove::loadParameters(), and McMd::StructureFactorP::loadParameters().
void McMd::Analyzer::save (Serializable::OArchive & ar) virtual
Load parameters to archive.
Default implementation saves interval and outputFileName.
Parameters
ar loading/saving archive
Reimplemented from Util::ParamComposite.
Reimplemented in McMd::IntraStructureFactor, McMd::StructureFactorP, McMd::VanHove, McMd::IntraStructureFactorGrid, McMd::BlockRadiusGyration, McMd::StructureFactorGrid, McMd::StructureFactorPGrid, McMd::RadiusGyration, McMd::StructureFactor, McMd::CompositionProfile, McMd::IntraPairAutoCorr, McMd::IntraBondTensorAutoCorr< SystemType >, McMd::IntraBondTensorAutoCorr< MdSystem >, McMd::IntraBondTensorAutoCorr< McSystem >, McMd::McMuExchange, McMd::ClusterHistogram, McMd::RDF, McMd::McNVTChemicalPotential, McMd::MdPairEnergyCoefficients, McMd::BennettsMethod, McMd::IntraBondStressAutoCorr< SystemType >, McMd::LinearRouseAutoCorr, McMd::IntraBondStressAutoCorr< MdSystem >, McMd::IntraBondStressAutoCorr< McSystem >, McMd::McVirialStressTensorAverage, McMd::MdVirialStressTensorAverage, McMd::ConfigWriter, McMd::RingRouseAutoCorr, McMd::McPairEnergyAverage, McMd::PressureAverage< SystemType >, McMd::StressAutoCorr< SystemType >, McMd::StressTensorAverage< SystemType >, McMd::PressureAverage< MdSystem >, McMd::PressureAverage< McSystem >, McMd::StressAutoCorr< MdSystem >, McMd::ComMSD, McMd::BondLengthDist, McMd::AtomMSD, McMd::McEnergyOutput, McMd::AverageAnalyzer< SystemType >, McMd::AverageAnalyzer< McSystem >, McMd::MdEnergyOutput, McMd::MdKineticEnergyAverage, McMd::BoundaryAverage, McMd::TypeDistribution, McMd::MdPotentialEnergyAverage, McMd::PerturbDerivative, and McMd::SemiGrandDistribution.
Definition at line 126 of file mcMd/analyzers/Analyzer.cpp.
References interval_, and outputFileName_.
Referenced by McMd::ClusterHistogram::save(), and McMd::CompositionProfile::save().
template<class Archive > void McMd::Analyzer::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Saves interval and outputFileName.
Parameters
ar archive
version archive version id
Definition at line 255 of file mcMd/analyzers/Analyzer.h.
Referenced by McMd::SemiGrandDistribution::serialize(), McMd::PerturbDerivative::serialize(), McMd::MdPotentialEnergyAverage::serialize(), McMd::TypeDistribution::serialize(), McMd::MdKineticEnergyAverage::serialize(), McMd::BoundaryAverage::serialize(), McMd::MdEnergyOutput::serialize(), McMd::McEnergyOutput::serialize(), McMd::AverageAnalyzer< SystemType >::serialize(), McMd::AtomMSD::serialize(), McMd::BondLengthDist::serialize(), McMd::ComMSD::serialize(), McMd::McPairEnergyAverage::serialize(), McMd::PressureAverage< SystemType >::serialize(), McMd::StressAutoCorr< SystemType >::serialize(), McMd::RingRouseAutoCorr::serialize(), McMd::BennettsMethod::serialize(), McMd::IntraBondStressAutoCorr< SystemType >::serialize(), McMd::LinearRouseAutoCorr::serialize(), McMd::ConfigWriter::serialize(), McMd::RDF::serialize(), McMd::ClusterHistogram::serialize(), McMd::IntraBondTensorAutoCorr< SystemType >::serialize(), McMd::CompositionProfile::serialize(), McMd::IntraPairAutoCorr::serialize(), McMd::RadiusGyration::serialize(), McMd::StructureFactor::serialize(), McMd::BlockRadiusGyration::serialize(), McMd::VanHove::serialize(), McMd::StructureFactorP::serialize(), and McMd::IntraStructureFactor::serialize().
virtual void McMd::Analyzer::setup () inline virtual
Complete any required initialization.
This method must be called just before the beginning of the main simulation loop, after an initial configuration is known. It may be used to complete any initialization that cannot be completed in the readParam method, because knowledge of the configuration is needed.
The default implementation is an empty function.
Reimplemented in McMd::IntraStructureFactor, McMd::StructureFactorP, McMd::VanHove, McMd::IntraStructureFactorGrid, McMd::StructureFactorGrid, McMd::StructureFactorPGrid, McMd::RadiusGyration, McMd::StructureFactor, McMd::IntraPairAutoCorr, McMd::IntraBondTensorAutoCorr< SystemType >, McMd::IntraBondTensorAutoCorr< MdSystem >, McMd::IntraBondTensorAutoCorr< McSystem >, McMd::RDF, McMd::ConfigWriter, McMd::BlockRadiusGyration, McMd::IntraBondStressAutoCorr< SystemType >, McMd::LinearRouseAutoCorr, McMd::IntraBondStressAutoCorr< MdSystem >, McMd::IntraBondStressAutoCorr< McSystem >, McMd::StressTensorAverage< SystemType >, McMd::BennettsMethod, McMd::RingRouseAutoCorr, McMd::McPairEnergyAverage, McMd::PressureAverage< SystemType >, McMd::StressAutoCorr< SystemType >, McMd::PressureAverage< MdSystem >, McMd::PressureAverage< McSystem >, McMd::StressAutoCorr< MdSystem >, McMd::ComMSD, McMd::BondLengthDist, McMd::AtomMSD, McMd::AverageAnalyzer< SystemType >, McMd::AverageAnalyzer< McSystem >, McMd::MdKineticEnergyAverage, McMd::BoundaryAverage, McMd::MdPotentialEnergyAverage, McMd::PerturbDerivative, McMd::CompositionProfile, McMd::McMuExchange, McMd::McNVTChemicalPotential, and McMd::ClusterHistogram.
Definition at line 118 of file mcMd/analyzers/Analyzer.h.
virtual void McMd::Analyzer::sample (long iStep) pure virtual
Calculate, analyze and/or output a physical quantity.
Take an action if iStep is a multiple of interval. If iStep is not a multiple of interval, this method should do nothing and return immediately.
Parameters
iStep current simulation step index.
Implemented in McMd::IntraStructureFactor, McMd::StructureFactorP, McMd::VanHove, McMd::IntraStructureFactorGrid, McMd::StructureFactorGrid, McMd::RadiusGyration, McMd::StructureFactor, McMd::IntraPairAutoCorr, McMd::IntraBondTensorAutoCorr< SystemType >, McMd::IntraBondTensorAutoCorr< MdSystem >, McMd::IntraBondTensorAutoCorr< McSystem >, McMd::RDF, McMd::ConfigWriter, McMd::BlockRadiusGyration, McMd::IntraBondStressAutoCorr< SystemType >, McMd::LinearRouseAutoCorr, McMd::IntraBondStressAutoCorr< MdSystem >, McMd::IntraBondStressAutoCorr< McSystem >, McMd::StressTensorAverage< SystemType >, McMd::BennettsMethod, McMd::RingRouseAutoCorr, McMd::StressAutoCorr< SystemType >, McMd::StressAutoCorr< MdSystem >, McMd::ComMSD, McMd::McPairEnergyAverage, McMd::MdPairEnergyCoefficients, McMd::PressureAverage< SystemType >, McMd::PressureAverage< MdSystem >, McMd::PressureAverage< McSystem >, McMd::BondLengthDist, McMd::AtomMSD, McMd::McVirialStressTensorAverage, McMd::MdVirialStressTensorAverage, McMd::BoundaryAverage, McMd::MdKineticEnergyAverage, McMd::CompositionProfile, McMd::MdPotentialEnergyAverage, McMd::PerturbDerivative, McMd::McEnergyOutput, McMd::MdEnergyOutput, McMd::TypeDistribution, McMd::SemiGrandDistribution, McMd::McMuExchange, McMd::ClusterHistogram, McMd::McNVTChemicalPotential, McMd::LogProgress, McMd::McExternalEnergyAverage, McMd::McBondEnergyAverage, and McMd::McEnergyAverage.
virtual void McMd::Analyzer::output () inline virtual
Output any results at the end of the simulation.
The default implementation is an empty function.
Reimplemented in McMd::IntraStructureFactor, McMd::StructureFactorP, McMd::VanHove, McMd::IntraStructureFactorGrid, McMd::StructureFactorGrid, McMd::StructureFactorPGrid, McMd::RadiusGyration, McMd::StructureFactor, McMd::IntraPairAutoCorr, McMd::IntraBondTensorAutoCorr< SystemType >, McMd::IntraBondTensorAutoCorr< MdSystem >, McMd::IntraBondTensorAutoCorr< McSystem >, McMd::CompositionProfile, McMd::RDF, McMd::BlockRadiusGyration, McMd::IntraBondStressAutoCorr< SystemType >, McMd::LinearRouseAutoCorr, McMd::IntraBondStressAutoCorr< MdSystem >, McMd::IntraBondStressAutoCorr< McSystem >, McMd::StressTensorAverage< SystemType >, McMd::BennettsMethod, McMd::RingRouseAutoCorr, McMd::StressAutoCorr< SystemType >, McMd::StressAutoCorr< MdSystem >, McMd::ComMSD, McMd::McPairEnergyAverage, McMd::PressureAverage< SystemType >, McMd::PressureAverage< MdSystem >, McMd::PressureAverage< McSystem >, McMd::BondLengthDist, McMd::MdPairEnergyCoefficients, McMd::AtomMSD, McMd::McVirialStressTensorAverage, McMd::MdVirialStressTensorAverage, McMd::BoundaryAverage, McMd::MdKineticEnergyAverage, McMd::MdPotentialEnergyAverage, McMd::PerturbDerivative, McMd::McEnergyOutput, McMd::AverageAnalyzer< SystemType >, McMd::AverageAnalyzer< McSystem >, McMd::MdEnergyOutput, McMd::TypeDistribution, McMd::SemiGrandDistribution, McMd::McMuExchange, McMd::ClusterHistogram, and McMd::McNVTChemicalPotential.
Definition at line 137 of file mcMd/analyzers/Analyzer.h.
int McMd::Analyzer::interval () const inline
Get interval value.
Definition at line 234 of file mcMd/analyzers/Analyzer.h.
bool McMd::Analyzer::isAtInterval (long counter) const inline
Return true iff counter is a multiple of the interval.
Parameters
counter simulation step counter
Definition at line 240 of file mcMd/analyzers/Analyzer.h.
Referenced by McMd::McEnergyAverage::sample(), McMd::McExternalEnergyAverage::sample(), McMd::McNVTChemicalPotential::sample(), McMd::ClusterHistogram::sample(), McMd::McMuExchange::sample(), McMd::SemiGrandDistribution::sample(), McMd::TypeDistribution::sample(), McMd::McEnergyOutput::sample(), McMd::MdPotentialEnergyAverage::sample(), McMd::PerturbDerivative::sample(), McMd::CompositionProfile::sample(), McMd::MdKineticEnergyAverage::sample(), McMd::McVirialStressTensorAverage::sample(), McMd::MdVirialStressTensorAverage::sample(), McMd::BoundaryAverage::sample(), McMd::AtomMSD::sample(), McMd::BondLengthDist::sample(), McMd::McPairEnergyAverage::sample(), McMd::MdPairEnergyCoefficients::sample(), McMd::PressureAverage< SystemType >::sample(), McMd::ComMSD::sample(), McMd::StressAutoCorr< SystemType >::sample(), McMd::RingRouseAutoCorr::sample(), McMd::BennettsMethod::sample(), McMd::StressTensorAverage< SystemType >::sample(), McMd::IntraBondStressAutoCorr< SystemType >::sample(), McMd::LinearRouseAutoCorr::sample(), McMd::BlockRadiusGyration::sample(), McMd::ConfigWriter::sample(), McMd::RDF::sample(), McMd::IntraBondTensorAutoCorr< SystemType >::sample(), McMd::IntraPairAutoCorr::sample(), McMd::RadiusGyration::sample(), McMd::StructureFactor::sample(), McMd::VanHove::sample(), McMd::StructureFactorP::sample(), and McMd::IntraStructureFactor::sample().
void McMd::Analyzer::initStatic () static
Define and initialize baseInterval.
Definition at line 21 of file mcMd/analyzers/Analyzer.cpp.
Referenced by McMd::Simulation::Simulation().
void McMd::Analyzer::setFileMaster (FileMaster & fileMaster) protected
Set the FileMaster to use to open files.
Definition at line 135 of file mcMd/analyzers/Analyzer.cpp.
References fileMaster().
Referenced by McMd::SystemAnalyzer< SystemType >::SystemAnalyzer().
void McMd::Analyzer::readInterval (std::istream & in) protected
Read interval from file, with error checking.
Parameters
in input parameter file stream
Definition at line 52 of file mcMd/analyzers/Analyzer.cpp.
References baseInterval, interval_, and UTIL_THROW.
Referenced by McMd::SemiGrandDistribution::readParameters(), McMd::MdPotentialEnergyAverage::readParameters(), McMd::PerturbDerivative::readParameters(), McMd::TypeDistribution::readParameters(), McMd::MdKineticEnergyAverage::readParameters(), McMd::BoundaryAverage::readParameters(), McMd::McEnergyOutput::readParameters(), McMd::AverageAnalyzer< SystemType >::readParameters(), McMd::AtomMSD::readParameters(), McMd::BondLengthDist::readParameters(), McMd::ComMSD::readParameters(), McMd::StressAutoCorr< SystemType >::readParameters(), McMd::StressTensorAverage< SystemType >::readParameters(), McMd::ClusterHistogram::readParameters(), McMd::McPairEnergyAverage::readParameters(), McMd::McNVTChemicalPotential::readParameters(), McMd::PressureAverage< SystemType >::readParameters(), McMd::RingRouseAutoCorr::readParameters(), McMd::McVirialStressTensorAverage::readParameters(), McMd::MdVirialStressTensorAverage::readParameters(), McMd::McMuExchange::readParameters(), McMd::LinearRouseAutoCorr::readParameters(), McMd::BennettsMethod::readParameters(), McMd::IntraBondStressAutoCorr< SystemType >::readParameters(), McMd::MdPairEnergyCoefficients::readParameters(), McMd::ConfigWriter::readParameters(), McMd::CompositionProfile::readParameters(), McMd::IntraBondTensorAutoCorr< SystemType >::readParameters(), McMd::IntraPairAutoCorr::readParameters(), readParameters(), McMd::RadiusGyration::readParameters(), McMd::StructureFactor::readParameters(), McMd::BlockRadiusGyration::readParameters(), McMd::StructureFactorPGrid::readParameters(), McMd::StructureFactorGrid::readParameters(), McMd::IntraStructureFactorGrid::readParameters(), McMd::VanHove::readParameters(), McMd::StructureFactorP::readParameters(), and McMd::IntraStructureFactor::readParameters().
void McMd::Analyzer::readOutputFileName (std::istream & in) protected
Read outputFileName from file.
Parameters
in input parameter file stream.
Definition at line 77 of file mcMd/analyzers/Analyzer.cpp.
References outputFileName_.
Referenced by McMd::SemiGrandDistribution::readParameters(), McMd::MdPotentialEnergyAverage::readParameters(), McMd::PerturbDerivative::readParameters(), McMd::TypeDistribution::readParameters(), McMd::MdKineticEnergyAverage::readParameters(), McMd::BoundaryAverage::readParameters(), McMd::McEnergyOutput::readParameters(), McMd::AverageAnalyzer< SystemType >::readParameters(), McMd::AtomMSD::readParameters(), McMd::BondLengthDist::readParameters(), McMd::ComMSD::readParameters(), McMd::StressAutoCorr< SystemType >::readParameters(), McMd::StressTensorAverage< SystemType >::readParameters(), McMd::ClusterHistogram::readParameters(), McMd::McPairEnergyAverage::readParameters(), McMd::McNVTChemicalPotential::readParameters(), McMd::PressureAverage< SystemType >::readParameters(), McMd::RingRouseAutoCorr::readParameters(), McMd::McVirialStressTensorAverage::readParameters(), McMd::MdVirialStressTensorAverage::readParameters(), McMd::McMuExchange::readParameters(), McMd::LinearRouseAutoCorr::readParameters(), McMd::BennettsMethod::readParameters(), McMd::IntraBondStressAutoCorr< SystemType >::readParameters(), McMd::MdPairEnergyCoefficients::readParameters(), McMd::ConfigWriter::readParameters(), McMd::CompositionProfile::readParameters(), McMd::IntraBondTensorAutoCorr< SystemType >::readParameters(), McMd::IntraPairAutoCorr::readParameters(), readParameters(), McMd::RadiusGyration::readParameters(), McMd::StructureFactor::readParameters(), McMd::BlockRadiusGyration::readParameters(), McMd::StructureFactorPGrid::readParameters(), McMd::StructureFactorGrid::readParameters(), McMd::IntraStructureFactorGrid::readParameters(), McMd::VanHove::readParameters(), McMd::StructureFactorP::readParameters(), and McMd::IntraStructureFactor::readParameters().
void McMd::Analyzer::loadInterval (Serializable::IArchive & ar) protected
Load interval from archive, with error checking.
Parameters
ar input/loading archive
Definition at line 92 of file mcMd/analyzers/Analyzer.cpp.
References baseInterval, interval_, and UTIL_THROW.
Referenced by McMd::MdPotentialEnergyAverage::loadParameters(), McMd::MdKineticEnergyAverage::loadParameters(), McMd::AtomMSD::loadParameters(), McMd::BondLengthDist::loadParameters(), McMd::MdPairEnergyCoefficients::loadParameters(), McMd::McMuExchange::loadParameters(), loadParameters(), and McMd::IntraStructureFactor::loadParameters().
void McMd::Analyzer::loadOutputFileName (Serializable::IArchive & ar) protected
Load output file name from archive.
Parameters
ar input/loading archive
Definition at line 120 of file mcMd/analyzers/Analyzer.cpp.
References outputFileName_.
Referenced by McMd::MdPotentialEnergyAverage::loadParameters(), McMd::MdKineticEnergyAverage::loadParameters(), McMd::AtomMSD::loadParameters(), McMd::BondLengthDist::loadParameters(), McMd::MdPairEnergyCoefficients::loadParameters(), McMd::McMuExchange::loadParameters(), loadParameters(), and McMd::IntraStructureFactor::loadParameters().
FileMaster & McMd::Analyzer::fileMaster () protected
Get the FileMaster by reference.
This can be used to open multiple output files.
Definition at line 141 of file mcMd/analyzers/Analyzer.cpp.
Referenced by McMd::MdPotentialEnergyAverage::loadParameters(), McMd::PerturbDerivative::loadParameters(), McMd::BoundaryAverage::loadParameters(), McMd::MdKineticEnergyAverage::loadParameters(), McMd::AverageAnalyzer< SystemType >::loadParameters(), McMd::McEnergyOutput::loadParameters(), McMd::McPairEnergyAverage::loadParameters(), McMd::PressureAverage< SystemType >::loadParameters(), McMd::StressTensorAverage< SystemType >::loadParameters(), McMd::McVirialStressTensorAverage::loadParameters(), McMd::MdVirialStressTensorAverage::loadParameters(), McMd::BennettsMethod::loadParameters(), McMd::MdPairEnergyCoefficients::loadParameters(), McMd::RadiusGyration::loadParameters(), McMd::BlockRadiusGyration::loadParameters(), McMd::McNVTChemicalPotential::output(), McMd::ClusterHistogram::output(), McMd::McMuExchange::output(), McMd::SemiGrandDistribution::output(), McMd::TypeDistribution::output(), McMd::AverageAnalyzer< SystemType >::output(), McMd::McEnergyOutput::output(), McMd::MdPotentialEnergyAverage::output(), McMd::PerturbDerivative::output(), McMd::MdKineticEnergyAverage::output(), McMd::BoundaryAverage::output(), McMd::AtomMSD::output(), McMd::MdPairEnergyCoefficients::output(), McMd::BondLengthDist::output(), McMd::McPairEnergyAverage::output(), McMd::PressureAverage< SystemType >::output(), McMd::ComMSD::output(), McMd::StressAutoCorr< SystemType >::output(), McMd::RingRouseAutoCorr::output(), McMd::BennettsMethod::output(), McMd::IntraBondStressAutoCorr< SystemType >::output(), McMd::LinearRouseAutoCorr::output(), McMd::BlockRadiusGyration::output(), McMd::RDF::output(), McMd::CompositionProfile::output(), McMd::IntraBondTensorAutoCorr< SystemType >::output(), McMd::IntraPairAutoCorr::output(), McMd::StructureFactor::output(), McMd::RadiusGyration::output(), McMd::StructureFactorGrid::output(), McMd::StructureFactorPGrid::output(), McMd::IntraStructureFactorGrid::output(), McMd::VanHove::output(), McMd::StructureFactorP::output(), McMd::IntraStructureFactor::output(), McMd::MdPotentialEnergyAverage::readParameters(), McMd::PerturbDerivative::readParameters(), McMd::MdKineticEnergyAverage::readParameters(), McMd::BoundaryAverage::readParameters(), McMd::AverageAnalyzer< SystemType >::readParameters(), McMd::McEnergyOutput::readParameters(), McMd::McNVTChemicalPotential::readParameters(), McMd::PressureAverage< SystemType >::readParameters(), McMd::McPairEnergyAverage::readParameters(), McMd::BennettsMethod::readParameters(), McMd::MdPairEnergyCoefficients::readParameters(), McMd::RadiusGyration::readParameters(), McMd::BlockRadiusGyration::readParameters(), McMd::CompositionProfile::sample(), McMd::ConfigWriter::sample(), McMd::StructureFactor::sample(), McMd::StructureFactorGrid::sample(), McMd::IntraStructureFactorGrid::sample(), and setFileMaster().
const std::string & McMd::Analyzer::outputFileName () const inline protected
Return outputFileName string.
Definition at line 246 of file mcMd/analyzers/Analyzer.h.
Referenced by McMd::MdPotentialEnergyAverage::loadParameters(), McMd::PerturbDerivative::loadParameters(), McMd::BoundaryAverage::loadParameters(), McMd::MdKineticEnergyAverage::loadParameters(), McMd::AverageAnalyzer< SystemType >::loadParameters(), McMd::McEnergyOutput::loadParameters(), McMd::McPairEnergyAverage::loadParameters(), McMd::PressureAverage< SystemType >::loadParameters(), McMd::StressTensorAverage< SystemType >::loadParameters(), McMd::McVirialStressTensorAverage::loadParameters(), McMd::MdVirialStressTensorAverage::loadParameters(), McMd::BennettsMethod::loadParameters(), McMd::MdPairEnergyCoefficients::loadParameters(), McMd::RadiusGyration::loadParameters(), McMd::BlockRadiusGyration::loadParameters(), McMd::McNVTChemicalPotential::output(), McMd::ClusterHistogram::output(), McMd::McMuExchange::output(), McMd::SemiGrandDistribution::output(), McMd::TypeDistribution::output(), McMd::AverageAnalyzer< SystemType >::output(), McMd::McEnergyOutput::output(), McMd::MdPotentialEnergyAverage::output(), McMd::PerturbDerivative::output(), McMd::MdKineticEnergyAverage::output(), McMd::BoundaryAverage::output(), McMd::MdPairEnergyCoefficients::output(), McMd::AtomMSD::output(), McMd::BondLengthDist::output(), McMd::McPairEnergyAverage::output(), McMd::PressureAverage< SystemType >::output(), McMd::ComMSD::output(), McMd::StressAutoCorr< SystemType >::output(), McMd::RingRouseAutoCorr::output(), McMd::BennettsMethod::output(), McMd::IntraBondStressAutoCorr< SystemType >::output(), McMd::LinearRouseAutoCorr::output(), McMd::BlockRadiusGyration::output(), McMd::RDF::output(), McMd::CompositionProfile::output(), McMd::IntraBondTensorAutoCorr< SystemType >::output(), McMd::IntraPairAutoCorr::output(), McMd::StructureFactor::output(), McMd::RadiusGyration::output(), McMd::StructureFactorGrid::output(), McMd::StructureFactorPGrid::output(), McMd::IntraStructureFactorGrid::output(), McMd::VanHove::output(), McMd::StructureFactorP::output(), McMd::IntraStructureFactor::output(), McMd::MdPotentialEnergyAverage::readParameters(), McMd::PerturbDerivative::readParameters(), McMd::BoundaryAverage::readParameters(), McMd::MdKineticEnergyAverage::readParameters(), McMd::AverageAnalyzer< SystemType >::readParameters(), McMd::McEnergyOutput::readParameters(), McMd::PressureAverage< SystemType >::readParameters(), McMd::McPairEnergyAverage::readParameters(), McMd::McNVTChemicalPotential::readParameters(), McMd::StressTensorAverage< SystemType >::readParameters(), McMd::MdVirialStressTensorAverage::readParameters(), McMd::McVirialStressTensorAverage::readParameters(), McMd::BennettsMethod::readParameters(), McMd::MdPairEnergyCoefficients::readParameters(), McMd::RadiusGyration::readParameters(), McMd::BlockRadiusGyration::readParameters(), McMd::CompositionProfile::sample(), McMd::ConfigWriter::sample(), McMd::StructureFactor::sample(), McMd::StructureFactorGrid::sample(), and McMd::IntraStructureFactorGrid::sample().
std::string McMd::Analyzer::outputFileName (const std::string & suffix) const protected
Return outputFileName string with added suffix.
Definition at line 150 of file mcMd/analyzers/Analyzer.cpp.
References outputFileName_.
Member Data Documentation
long McMd::Analyzer::baseInterval = 1 static
The interval for an Analyzer must be a multiple of baseInterval.
Definition at line 157 of file mcMd/analyzers/Analyzer.h.
Referenced by loadInterval(), McMd::AnalyzerManager::loadParameters(), readInterval(), McMd::AnalyzerManager::readParameters(), McMd::AnalyzerManager::sample(), McMd::AnalyzerManager::save(), McMd::McSimulation::simulate(), and McMd::MdSimulation::simulate().
std::string McMd::Analyzer::outputFileName_ protected
Base name of output file(s).
Definition at line 217 of file mcMd/analyzers/Analyzer.h.
Referenced by loadOutputFileName(), outputFileName(), readOutputFileName(), McMd::McMuExchange::save(), and save().
long McMd::Analyzer::interval_ protected
Number of simulation steps between subsequent actions.
Definition at line 220 of file mcMd/analyzers/Analyzer.h.
Referenced by loadInterval(), readInterval(), McMd::McMuExchange::save(), and save().
The documentation for this class was generated from the following files:
mcMd/analyzers/Analyzer.h
mcMd/analyzers/Analyzer.cpp