Simpatico: McMd::HomopolymerSemiGrandMove Class Reference
McMd::HomopolymerSemiGrandMove Class Reference
Monte Carlo Moves
Detailed Description
A move that changes the type of a HomopolymerSG molecule.
Definition at line 26 of file HomopolymerSemiGrandMove.h.
#include <HomopolymerSemiGrandMove.h>
Public Member Functions
HomopolymerSemiGrandMove (McSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read species to which displacement is applied.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual bool move ()
Generate and accept or reject configuration bias move.
Protected Attributes
int speciesId_
Integer index for molecular species.
HomopolymerSG * speciesPtr_
Pointer to instance of HomopolymerSG.
Constructor & Destructor Documentation
McMd::HomopolymerSemiGrandMove::HomopolymerSemiGrandMove (McSystem & system)
Constructor.
Definition at line 25 of file HomopolymerSemiGrandMove.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::HomopolymerSemiGrandMove::readParameters (std::istream & in) [virtual]
Read species to which displacement is applied.
Reimplemented from McMd::McMove.
Definition at line 33 of file HomopolymerSemiGrandMove.cpp.
References McMd::McMove::readProbability(), McMd::McMove::simulation(), McMd::Simulation::species(), speciesId_, speciesPtr_, and UTIL_THROW.
void McMd::HomopolymerSemiGrandMove::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive
Reimplemented from McMd::McMove.
Definition at line 50 of file HomopolymerSemiGrandMove.cpp.
References McMd::McMove::simulation(), McMd::Simulation::species(), speciesId_, speciesPtr_, and UTIL_THROW.
void McMd::HomopolymerSemiGrandMove::save (Serializable::OArchive & ar) [virtual]
Save state to an archive.
Parameters:
ar saving (output) archive
Reimplemented from McMd::McMove.
Definition at line 65 of file HomopolymerSemiGrandMove.cpp.
References speciesId_.
template<class Archive > void McMd::HomopolymerSemiGrandMove::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar archive
version archive version id
Reimplemented from Util::ParamComponent.
bool McMd::HomopolymerSemiGrandMove::move () [virtual]
Generate and accept or reject configuration bias move.
Reimplemented from McMd::McMove.
Definition at line 74 of file HomopolymerSemiGrandMove.cpp.
References McMd::SystemMove::boltzmann(), McMd::McMove::incrementNAccept(), McMd::McMove::incrementNAttempt(), Util::Random::metropolis(), McMd::McPairPotential::moleculeEnergy(), McMd::SpeciesMutator::moleculeStateId(), McMd::Species::mutator(), McMd::McSystem::pairPotential(), McMd::McMove::random(), McMd::System::randomMolecule(), McMd::SpeciesMutator::setMoleculeState(), speciesId_, speciesPtr_, McMd::SpeciesMutator::stateWeight(), and McMd::SystemMove::system().
Member Data Documentation
int McMd::HomopolymerSemiGrandMove::speciesId_ [protected]
Integer index for molecular species.
Definition at line 72 of file HomopolymerSemiGrandMove.h.
Referenced by loadParameters(), move(), readParameters(), and save().
HomopolymerSG* McMd::HomopolymerSemiGrandMove::speciesPtr_ [protected]
Pointer to instance of HomopolymerSG.
Definition at line 75 of file HomopolymerSemiGrandMove.h.
Referenced by loadParameters(), move(), and readParameters().
The documentation for this class was generated from the following files:
HomopolymerSemiGrandMove.h
HomopolymerSemiGrandMove.cpp