Simpatico: McMd::PairFactory Class Reference
McMd::PairFactory Class Reference
Pair Potentials
Detailed Description
Factory for subclasses MdPairPotential or McPairPotential.
This class is not derived from the Factory template because it provides a different interface, with separate mcFactory() and mdFactory() methods to create McPairPotential and MdPairPotential objects. Unlike a standard Factory, it also does not provide a readObject method, and so does not require a param communicator.
Definition at line 33 of file mcMd/potentials/pair/PairFactory.h.
#include <PairFactory.h>
Public Member Functions
PairFactory ()
Constructor.
virtual ~PairFactory ()
Destructor.
void addSubfactory (PairFactory &subfactory)
Add a new subfactory to the list.
virtual McPairPotential * mcFactory (const std::string &subclass, System &system) const
Return a pointer to a new McPairPotential, if possible.
virtual MdPairPotential * mdFactory (const std::string &subclass, System &system) const
Return a pointer to a new McPairPotential, if possible.
virtual MdPairPotential * mdFactory (McPairPotential &potential) const
Create an MdPairPotential from a McPairPotential.
Protected Member Functions
McPairPotential * tryMcSubfactories (const std::string &className, System &system) const
Search subfactories for match to McPairPotential subclass name.
MdPairPotential * tryMdSubfactories (const std::string &className, System &system) const
Search subfactories for match to MdPairPotential subclass name.
MdPairPotential * tryMdSubfactories (McPairPotential &potential) const
Search through subfactories for match for an mc potential.
Constructor & Destructor Documentation
McMd::PairFactory::PairFactory ()
Constructor.
Default constructor.
Definition at line 39 of file mcMd/potentials/pair/PairFactory.cpp.
virtual McMd::PairFactory::~PairFactory () [inline, virtual]
Destructor.
Definition at line 46 of file mcMd/potentials/pair/PairFactory.h.
Member Function Documentation
void McMd::PairFactory::addSubfactory (PairFactory & subfactory)
Add a new subfactory to the list.
If this Factory has a param communicator, this method also sets the child subfactory communicator to that of the parent.
Parameters:
subfactory New subfactory to be added
Definition at line 45 of file mcMd/potentials/pair/PairFactory.cpp.
McPairPotential * McMd::PairFactory::mcFactory (const std::string & subclass, System & system) const [virtual]
Return a pointer to a new McPairPotential, if possible.
Parameters:
subclass name of desired subclass of McPairPotential
system associated System
Definition at line 52 of file mcMd/potentials/pair/PairFactory.cpp.
Referenced by McMd::McSystem::loadParameters(), and McMd::McSystem::readParameters().
MdPairPotential * McMd::PairFactory::mdFactory (const std::string & subclass, System & system) const [virtual]
Return a pointer to a new McPairPotential, if possible.
Parameters:
subclass name of desired subclass of MdPairPotential
system associated System
Definition at line 79 of file mcMd/potentials/pair/PairFactory.cpp.
Referenced by McMd::MdSystem::loadParameters(), McMd::MdSystem::MdSystem(), and McMd::MdSystem::readParameters().
MdPairPotential * McMd::PairFactory::mdFactory (McPairPotential & potential) const [virtual]
Create an MdPairPotential from a McPairPotential.
Parameters:
potential McPairPotential to be cloned
Definition at line 106 of file mcMd/potentials/pair/PairFactory.cpp.
References McMd::PairPotential::interactionClassName().
McPairPotential * McMd::PairFactory::tryMcSubfactories (const std::string & className, System & system) const [protected]
Search subfactories for match to McPairPotential subclass name.
Parameters:
className name of subclass
system associated System
Returns:
base class pointer to new McPairPotential, or a null pointer.
Definition at line 142 of file mcMd/potentials/pair/PairFactory.cpp.
MdPairPotential * McMd::PairFactory::tryMdSubfactories (const std::string & className, System & system) const [protected]
Search subfactories for match to MdPairPotential subclass name.
Parameters:
className name of subclass
system associated System
Returns:
base class pointer to new MdPairPotential, or a null pointer.
Definition at line 156 of file mcMd/potentials/pair/PairFactory.cpp.
MdPairPotential * McMd::PairFactory::tryMdSubfactories (McPairPotential & potential) const [protected]
Search through subfactories for match for an mc potential.
Parameters:
potential McPairPotential to be cloned
Returns:
base class pointer to new MdPairPotential, or a null pointer.
Definition at line 169 of file mcMd/potentials/pair/PairFactory.cpp.
The documentation for this class was generated from the following files:
mcMd/potentials/pair/PairFactory.h
mcMd/potentials/pair/PairFactory.cpp