Simpatico: Tools::Configuration Class Reference
Tools::Configuration Class Reference
Storage
Detailed Description
An instantaneous molecular dynamics configuration.
A Configuration has:
a Util::Boundary
an AtomStorage container for atoms
a GroupStorage for each type of covalent group
Definition at line 40 of file Configuration.h.
#include <Configuration.h>
Public Member Functions
Configuration ()
Constructor.
~Configuration ()
Destructor.
void readParam (const char *filename)
Open, read, and close parameter file.
void readParameters (std::istream &in)
Read parameters.
void clear ()
Clear all atoms and groups.
Boundary & boundary ()
Get the Boundary by non-const reference.
AtomStorage & atoms ()
Get the AtomStorage.
GroupStorage< 2 > & bonds ()
Get the Bond storage.
GroupStorage< 3 > & angles ()
Get the Angle storage.
GroupStorage< 4 > & dihedrals ()
Get the Dihedral storage.
GroupStorage< 4 > & impropers ()
Get the Improper dihedral storage.
int nSpecies () const
Number of species.
Species & species (int i)
Get a particular species identified by index.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Constructor & Destructor Documentation
Tools::Configuration::Configuration ()
Constructor.
Definition at line 16 of file Configuration.cpp.
References Util::ParamComposite::setClassName().
Tools::Configuration::~Configuration ()
Destructor.
Definition at line 34 of file Configuration.cpp.
Member Function Documentation
void Tools::Configuration::readParam (const char * filename)
Open, read, and close parameter file.
Definition at line 40 of file Configuration.cpp.
void Tools::Configuration::readParameters (std::istream & in) virtual
Read parameters.
Reimplemented from Util::ParamComposite.
Definition at line 51 of file Configuration.cpp.
References Tools::AtomStorage::allocate(), and Util::DSArray< Data >::allocate().
Referenced by Tools::Processor::readParameters().
void Tools::Configuration::clear ()
Clear all atoms and groups.
Definition at line 104 of file Configuration.cpp.
References Tools::AtomStorage::clear(), and Util::DSArray< Data >::clear().
Referenced by Tools::Processor::analyzeConfigs(), and Tools::Processor::readConfig().
Boundary & Tools::Configuration::boundary () inline
Get the Boundary by non-const reference.
Definition at line 180 of file Configuration.h.
Referenced by Tools::DdMdConfigReader::readConfig(), Tools::DdMdTrajectoryReader::readFrame(), Tools::AtomMSD::sample(), Tools::PairEnergy::sample(), Tools::AtomMSD::setup(), Tools::PairEnergy::setup(), Tools::TrajectoryWriter::TrajectoryWriter(), Tools::DdMdConfigWriter::writeConfig(), and Tools::HoomdConfigWriter::writeConfig().
AtomStorage & Tools::Configuration::atoms () inline
Get the AtomStorage.
Definition at line 183 of file Configuration.h.
Referenced by Tools::ConfigReader::addAtomsToSpecies(), Tools::DdMdConfigReader::readConfig(), Tools::LammpsDumpReader::readFrame(), Tools::DdMdTrajectoryReader::readFrame(), Tools::PairEnergy::sample(), Tools::ConfigReader::setAtomContexts(), Tools::TrajectoryWriter::TrajectoryWriter(), Tools::DdMdConfigWriter::writeConfig(), and Tools::HoomdConfigWriter::writeConfig().
GroupStorage< 2 > & Tools::Configuration::bonds () inline
Get the Bond storage.
Definition at line 187 of file Configuration.h.
Referenced by Tools::HoomdConfigReader::readConfig(), and Tools::TrajectoryWriter::TrajectoryWriter().
GroupStorage< 3 > & Tools::Configuration::angles () inline
Get the Angle storage.
Definition at line 192 of file Configuration.h.
Referenced by Tools::HoomdConfigReader::readConfig(), and Tools::TrajectoryWriter::TrajectoryWriter().
GroupStorage< 4 > & Tools::Configuration::dihedrals () inline
Get the Dihedral storage.
Definition at line 197 of file Configuration.h.
Referenced by Tools::HoomdConfigReader::readConfig(), and Tools::TrajectoryWriter::TrajectoryWriter().
GroupStorage< 4 > & Tools::Configuration::impropers () inline
Get the Improper dihedral storage.
Definition at line 200 of file Configuration.h.
Referenced by Tools::HoomdConfigReader::readConfig().
int Tools::Configuration::nSpecies () const inline
Number of species.
If nSpecies == 0, all species and molecule info is disabled.
Definition at line 204 of file Configuration.h.
Referenced by Tools::ConfigReader::addAtomsToSpecies(), and Tools::ConfigReader::setAtomContexts().
Species & Tools::Configuration::species (int i) inline
Get a particular species identified by index.
Parameters
i species index
Definition at line 207 of file Configuration.h.
Referenced by Tools::ConfigReader::addAtomsToSpecies(), Tools::AtomMSD::readParameters(), Tools::AtomMSD::sample(), Tools::ConfigReader::setAtomContexts(), and Tools::AtomMSD::setup().
The documentation for this class was generated from the following files:
Configuration.h
Configuration.cpp