Simpatico: McMd::LammpsDumpIo Class Reference
McMd::LammpsDumpIo Class Reference
Trajectory File IO
Detailed Description
TrajectoryIo for Lammps dump trajectory files.
This class assumes that atom tags are ordered by molecule and species, with consecutive ids for atoms in the same molecule and consecutive blocks for molecules in the same species.
Definition at line 28 of file LammpsDumpIo.h.
#include <LammpsDumpIo.h>
Public Member Functions
LammpsDumpIo (System &system)
Constructor.
virtual ~LammpsDumpIo ()
Destructor.
void readHeader (std::fstream &file)
Setup before reading frames.
bool readFrame (std::fstream &file)
Read a single frame.
Constructor & Destructor Documentation
McMd::LammpsDumpIo::LammpsDumpIo (System & system)
Constructor.
Definition at line 28 of file LammpsDumpIo.cpp.
McMd::LammpsDumpIo::~LammpsDumpIo () [virtual]
Destructor.
Definition at line 35 of file LammpsDumpIo.cpp.
Member Function Documentation
void McMd::LammpsDumpIo::readHeader (std::fstream & file) [virtual]
Setup before reading frames.
Parameters:
file input file stream.
Reimplemented from McMd::TrajectoryIo.
Definition at line 41 of file LammpsDumpIo.cpp.
References Util::DArray< Data >::allocate(), McMd::TrajectoryIo::atomCapacity_, Util::Array< Data >::capacity(), Util::DArray< Data >::isAllocated(), and UTIL_THROW.
bool McMd::LammpsDumpIo::readFrame (std::fstream & file) [virtual]
Read a single frame.
Frames are assumed to be read consecutively.
Parameters:
file input file stream.
Returns:
true if a frame is available, false if end of file
Reimplemented from McMd::TrajectoryIo.
Definition at line 59 of file LammpsDumpIo.cpp.
References McMd::TrajectoryIo::atomCapacity_, McMd::Molecule::begin(), McMd::TrajectoryIo::boundary(), McMd::Species::capacity(), Util::checkString(), Util::Dimension, Util::getNextLine(), Util::DArray< Data >::isAllocated(), McMd::System::molecule(), Util::ArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::OrthorhombicBoundary::setOrthorhombic(), Util::OrthorhombicBoundary::shift(), McMd::TrajectoryIo::simulation(), McMd::Simulation::species(), McMd::TrajectoryIo::system(), and UTIL_THROW.
The documentation for this class was generated from the following files:
LammpsDumpIo.h
LammpsDumpIo.cpp