Simpatico: DdMd::Integrator Class Reference
DdMd::Integrator Class Reference abstract
DdMd namespace » MD Integrators
Detailed Description
An Integrator numerically integrates the equations of motion.
Definition at line 29 of file Integrator.h.
#include <Integrator.h>
Public Member Functions
Integrator (Simulation &simulation)
Constructor.
~Integrator ()
Destructor.
void readParameters (std::istream &in)
Read saveInterval and saveFileName.
void loadParameters (Serializable::IArchive &ar)
Load saveInterval and saveFileName from restart archive.
void save (Serializable::OArchive &ar)
Save saveInterval and saveFileName from restart archive.
virtual void run (int nStep)=0
Run a simulation of iStep steps.
virtual void clear ()
Set integrator to initial state and clears all statistics.
virtual void outputStatistics (std::ostream &out)
Output timing statistics from a run.
double time () const
Get average time per processor of previous run.
int iStep () const
Get current time step index.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Public Member Functions inherited from DdMd::SimulationAccess
SimulationAccess (Simulation &simulation)
Constructor.
~SimulationAccess ()
Destructor.
Simulation & simulation ()
Get the parent simulation.
Boundary & boundary ()
Get the Boundary.
AtomStorage & atomStorage ()
Get the AtomStorage.
GroupStorage< 2 > & bondStorage ()
Get the BondStorage.
GroupStorage< 3 > & angleStorage ()
Get the AngleStorage.
GroupStorage< 4 > & dihedralStorage ()
Get the angleStorage.
PairPotential & pairPotential ()
Get the PairPotential.
BondPotential & bondPotential ()
Get the PairPotential.
AnglePotential & anglePotential ()
Get the AnglePotential.
DihedralPotential & dihedralPotential ()
Get the DihedralPotential.
ExternalPotential & externalPotential ()
Get the ExternalPotential.
EnergyEnsemble & energyEnsemble ()
Get the EnergyEnsemble.
BoundaryEnsemble & boundaryEnsemble ()
Get the BoundaryEnsemble.
Random & random ()
Get the Random number generator.
Domain & domain ()
Get the Domain.
Exchanger & exchanger ()
Get the Exchanger.
FileMaster & fileMaster ()
Get the FileMaster.
int nAtomType ()
Get maximum number of atom types.
int nBondType ()
Get maximum number of bond types.
int nAngleType ()
Get maximum number of angle types.
int nDihedralType ()
Get maximum number of dihedral types.
bool hasExternal ()
Does this simulation have an external potential?
AtomType & atomType (int i)
Get an AtomType descriptor for atomtype i.
MaskPolicy maskedPairPolicy () const
Return the value of the mask policy (MaskNone or MaskBonded).
bool reverseUpdateFlag () const
Are forces evaluated by reverse communication (true) or not (false)?
Protected Types
Protected Member Functions
virtual void initDynamicalState ()
Set any internal dynamical to default initial values.
virtual void setup ()=0
Setup integrator just before integration.
void setIsSetup ()
Mark the integrator as having been setup at least once.
bool isSetup () const
Has the setup() method been called at least once previously?
void setupAtoms ()
Setup state of atoms just before integration.
void computeForces ()
Compute forces for all local atoms, with timing.
void computeForcesAndVirial ()
Compute forces for all local atoms and virial, with timing.
bool isExchangeNeeded (double skin)
Determine whether an atom exchange and reneighboring is needed.
const std::string & saveFileName () const
Get restart file base name.
int saveInterval () const
Get interval for writing a restart file.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
int iStep_
Current step number.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Member Enumeration Documentation
enum DdMd::Integrator::TimeId protected
Timestamps for loop timing.
Definition at line 119 of file Integrator.h.
Constructor & Destructor Documentation
DdMd::Integrator::Integrator (Simulation & simulation)
Constructor.
Definition at line 48 of file Integrator.cpp.
DdMd::Integrator::~Integrator ()
Destructor.
Definition at line 59 of file Integrator.cpp.
Member Function Documentation
void DdMd::Integrator::readParameters (std::istream & in) virtual
Read saveInterval and saveFileName.
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Reimplemented in DdMd::NvtLangevinIntegrator, DdMd::NptIntegrator, DdMd::NphIntegrator, DdMd::NveIntegrator, and DdMd::NvtIntegrator.
Definition at line 65 of file Integrator.cpp.
References DdMd::Analyzer::baseInterval, and UTIL_THROW.
Referenced by DdMd::NvtIntegrator::readParameters(), DdMd::NveIntegrator::readParameters(), DdMd::NphIntegrator::readParameters(), DdMd::NptIntegrator::readParameters(), and DdMd::NvtLangevinIntegrator::readParameters().
void DdMd::Integrator::loadParameters (Serializable::IArchive & ar) virtual
Load saveInterval and saveFileName from restart archive.
Parameters
ar input archive
Reimplemented from Util::ParamComposite.
Reimplemented in DdMd::NvtLangevinIntegrator, DdMd::NptIntegrator, DdMd::NveIntegrator, DdMd::NphIntegrator, and DdMd::NvtIntegrator.
Definition at line 83 of file Integrator.cpp.
References DdMd::Analyzer::baseInterval, iStep_, and UTIL_THROW.
Referenced by DdMd::NvtIntegrator::loadParameters(), DdMd::NphIntegrator::loadParameters(), DdMd::NveIntegrator::loadParameters(), DdMd::NptIntegrator::loadParameters(), and DdMd::NvtLangevinIntegrator::loadParameters().
void DdMd::Integrator::save (Serializable::OArchive & ar) virtual
Save saveInterval and saveFileName from restart archive.
Parameters
ar input archive
Reimplemented from Util::ParamComposite.
Reimplemented in DdMd::NvtLangevinIntegrator, DdMd::NptIntegrator, DdMd::NveIntegrator, DdMd::NvtIntegrator, and DdMd::NphIntegrator.
Definition at line 105 of file Integrator.cpp.
References iStep_.
Referenced by DdMd::NphIntegrator::save(), DdMd::NvtIntegrator::save(), DdMd::NveIntegrator::save(), DdMd::NptIntegrator::save(), and DdMd::NvtLangevinIntegrator::save().
virtual void DdMd::Integrator::run (int nStep) pure virtual
Run a simulation of iStep steps.
Parameters
nStep number of steps to run.
Implemented in DdMd::TwoStepIntegrator.
void DdMd::Integrator::clear () virtual
Set integrator to initial state and clears all statistics.
This method resset iStep = 0, calls initDynamicalState(), calls the AnalyzerManger::clear(), clears the internal Timer and all timing statistics, clear the additional timing statistics maintained by the Exchanger class, and clears the memory usage statistics for the Buffer, PairList, and storage classes.
Definition at line 539 of file Integrator.cpp.
References DdMd::Simulation::analyzerManager(), DdMd::SimulationAccess::angleStorage(), DdMd::SimulationAccess::atomStorage(), DdMd::SimulationAccess::bondStorage(), DdMd::Simulation::buffer(), DdMd::DdTimer::clear(), DdMd::AnalyzerManager::clear(), DdMd::PairList::clearStatistics(), DdMd::GroupStorage< N >::clearStatistics(), DdMd::Buffer::clearStatistics(), DdMd::AtomStorage::clearStatistics(), DdMd::SimulationAccess::dihedralStorage(), DdMd::Simulation::exchanger(), initDynamicalState(), iStep_, DdMd::PairPotential::pairList(), DdMd::SimulationAccess::pairPotential(), DdMd::SimulationAccess::simulation(), and DdMd::Exchanger::timer().
Referenced by DdMd::NvtIntegrator::setup(), DdMd::NphIntegrator::setup(), DdMd::NveIntegrator::setup(), DdMd::NptIntegrator::setup(), and DdMd::NvtLangevinIntegrator::setup().
void DdMd::Integrator::outputStatistics (std::ostream & out) virtual
Output timing statistics from a run.
This method may only be called on the domain master processor.
Parameters
out output stream to which to write timing statistics.
Definition at line 329 of file Integrator.cpp.
References DdMd::SimulationAccess::atomStorage(), DdMd::PairList::buildCounter(), DdMd::Domain::communicator(), DdMd::SimulationAccess::domain(), DdMd::SimulationAccess::hasExternal(), iStep_, DdMd::SimulationAccess::nAngleType(), DdMd::AtomStorage::nAtomTotal(), DdMd::SimulationAccess::nBondType(), DdMd::SimulationAccess::nDihedralType(), DdMd::PairPotential::pairList(), DdMd::SimulationAccess::pairPotential(), DdMd::DdTimer::time(), time(), and UTIL_THROW.
double DdMd::Integrator::time () const
Get average time per processor of previous run.
Definition at line 313 of file Integrator.cpp.
References DdMd::SimulationAccess::domain(), DdMd::DdTimer::reduce(), and DdMd::DdTimer::time().
Referenced by outputStatistics().
int DdMd::Integrator::iStep () const inline
Get current time step index.
Definition at line 228 of file Integrator.h.
void DdMd::Integrator::initDynamicalState () inline protected virtual
Set any internal dynamical to default initial values.
This method should be called before the main loop the first time the integrator is used, within the setup() method, and should be called by the clear() method.
Reimplemented in DdMd::NvtIntegrator, DdMd::NptIntegrator, and DdMd::NphIntegrator.
Definition at line 248 of file Integrator.h.
Referenced by clear().
virtual void DdMd::Integrator::setup () protected pure virtual
Setup integrator just before integration.
This method is always called within the run method before the main loop. It should not set arbitrary default values for any independent internal state variables that cannot be calculated from the system configuration.
Implemented in DdMd::NvtLangevinIntegrator, DdMd::NptIntegrator, DdMd::NphIntegrator, DdMd::NveIntegrator, and DdMd::NvtIntegrator.
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::Integrator::setIsSetup () inline protected
Mark the integrator as having been setup at least once.
Must be called from within the setup method.
Definition at line 240 of file Integrator.h.
Referenced by DdMd::NvtIntegrator::setup(), DdMd::NphIntegrator::setup(), DdMd::NveIntegrator::setup(), DdMd::NptIntegrator::setup(), and DdMd::NvtLangevinIntegrator::setup().
bool DdMd::Integrator::isSetup () const inline protected
Has the setup() method been called at least once previously?
Definition at line 234 of file Integrator.h.
Referenced by DdMd::NvtIntegrator::setup(), DdMd::NphIntegrator::setup(), DdMd::NveIntegrator::setup(), DdMd::NptIntegrator::setup(), and DdMd::NvtLangevinIntegrator::setup().
void DdMd::Integrator::setupAtoms () protected
Setup state of atoms just before integration.
Exchange atoms, build PairList and compute Forces. Should be called in all subclass setup methods.
Definition at line 118 of file Integrator.cpp.
References DdMd::SimulationAccess::atomStorage(), DdMd::SimulationAccess::boundary(), DdMd::SimulationAccess::boundaryEnsemble(), DdMd::PairPotential::buildCellList(), DdMd::PairPotential::buildPairList(), DdMd::AtomStorage::clearSnapshot(), DdMd::Simulation::computeForces(), DdMd::Simulation::computeForcesAndVirial(), DdMd::Exchanger::exchange(), DdMd::SimulationAccess::exchanger(), DdMd::AtomStorage::makeSnapshot(), DdMd::SimulationAccess::pairPotential(), DdMd::SimulationAccess::simulation(), DdMd::AtomStorage::transformGenToCart(), and UTIL_THROW.
Referenced by DdMd::NvtIntegrator::setup(), DdMd::NphIntegrator::setup(), DdMd::NveIntegrator::setup(), DdMd::NptIntegrator::setup(), and DdMd::NvtLangevinIntegrator::setup().
void DdMd::Integrator::computeForces () protected
Compute forces for all local atoms, with timing.
Identical to Simulation::forceCompute(), with added timing. Upon return, forces are correct for all local atoms. Values of the forces on ghost atoms are undefined. Executes reverse communication if needed, and emits Simulation::forceSignal().
Definition at line 146 of file Integrator.cpp.
References DdMd::SimulationAccess::anglePotential(), DdMd::SimulationAccess::atomStorage(), DdMd::SimulationAccess::bondPotential(), DdMd::Potential::computeForces(), DdMd::SimulationAccess::dihedralPotential(), DdMd::SimulationAccess::exchanger(), DdMd::SimulationAccess::externalPotential(), DdMd::SimulationAccess::hasExternal(), DdMd::SimulationAccess::nAngleType(), DdMd::SimulationAccess::nBondType(), DdMd::SimulationAccess::nDihedralType(), DdMd::SimulationAccess::pairPotential(), DdMd::Exchanger::reverseUpdate(), DdMd::SimulationAccess::reverseUpdateFlag(), DdMd::SimulationAccess::simulation(), DdMd::DdTimer::stamp(), UTIL_THROW, and DdMd::Simulation::zeroForces().
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::Integrator::computeForcesAndVirial () protected
Compute forces for all local atoms and virial, with timing.
Identical to Simulation::computeForcesAndVirial(), with timing. Upon return, forces are correct for all local atoms. Values of the forces on ghost atoms are undefined. Executes reverse communication if needed, and emits Simulation::forceSignal().
Definition at line 195 of file Integrator.cpp.
References DdMd::SimulationAccess::anglePotential(), DdMd::SimulationAccess::atomStorage(), DdMd::SimulationAccess::bondPotential(), DdMd::Potential::computeForces(), DdMd::Potential::computeForcesAndStress(), DdMd::SimulationAccess::dihedralPotential(), DdMd::SimulationAccess::domain(), DdMd::SimulationAccess::exchanger(), DdMd::SimulationAccess::externalPotential(), DdMd::SimulationAccess::hasExternal(), DdMd::SimulationAccess::nAngleType(), DdMd::SimulationAccess::nBondType(), DdMd::SimulationAccess::nDihedralType(), DdMd::SimulationAccess::pairPotential(), DdMd::Exchanger::reverseUpdate(), DdMd::SimulationAccess::reverseUpdateFlag(), DdMd::SimulationAccess::simulation(), DdMd::DdTimer::stamp(), UTIL_THROW, and DdMd::Simulation::zeroForces().
Referenced by DdMd::TwoStepIntegrator::run().
bool DdMd::Integrator::isExchangeNeeded (double skin) protected
Determine whether an atom exchange and reneighboring is needed.
Parameters
skin Verlet list skin length
Returns
true iff exchange is needed
Definition at line 244 of file Integrator.cpp.
References DdMd::SimulationAccess::atomStorage(), DdMd::Domain::communicator(), DdMd::SimulationAccess::domain(), DdMd::AtomStorage::maxSqDisplacement(), DdMd::DdTimer::stamp(), and UTIL_THROW.
Referenced by DdMd::TwoStepIntegrator::run().
const std::string & DdMd::Integrator::saveFileName () const inline protected
Get restart file base name.
Definition at line 259 of file Integrator.h.
Referenced by DdMd::TwoStepIntegrator::run().
int DdMd::Integrator::saveInterval () const inline protected
Get interval for writing a restart file.
Definition at line 265 of file Integrator.h.
Referenced by DdMd::TwoStepIntegrator::run().
Member Data Documentation
int DdMd::Integrator::iStep_ protected
Current step number.
Definition at line 207 of file Integrator.h.
Referenced by clear(), loadParameters(), outputStatistics(), DdMd::TwoStepIntegrator::run(), and save().
The documentation for this class was generated from the following files:
Integrator.h
Integrator.cpp