Simpatico: McMd::RadiusGyration Class Reference
McMd::RadiusGyration Class Reference
Diagnostics
Detailed Description
Radius of gyration of a molecule.
The radius of gyration R_g is the root mean-squared separation of atoms in a molecule from the molecular center of mass. For a species of molecule with N atoms, with positions , we define
where is the center of mass, and where denotes an ensemble average over all molecules of a specified species.
This class calculates the radius of gyration by accumulating an average value for the above quantity, and optionally outputs block averages to file at an interval specified by the input parameter nSamplePerBlock. No block averages are output if nSamplePerBlock = 0.
Definition at line 50 of file RadiusGyration.h.
#include <RadiusGyration.h>
Public Member Functions
RadiusGyration (System &system)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters from file, and allocate data array.
virtual void loadParameters (Serializable::IArchive &ar)
Load state to an archive.
virtual void save (Serializable::OArchive &ar)
Save state to archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Clear accumulator.
virtual void sample (long iStep)
Evaluate squared radii of gyration for all molecules, add to ensemble.
virtual void output ()
Output results at end of simulation.
Constructor & Destructor Documentation
McMd::RadiusGyration::RadiusGyration (System & system)
Constructor.
Parameters:
system reference to parent System object
Definition at line 26 of file RadiusGyration.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::RadiusGyration::readParameters (std::istream & in) [virtual]
Read parameters from file, and allocate data array.
Input format:
int interval : sampling interval
string outputFileName : base name for output file(s)
int nSamplePerBlock : interval for output of block averages
int speciesId : integer id for Species of interest
No block averages are output if nSamplePerBlock = 0. Otherwise, block averages are output to a file named (outputFileName).dat.
Parameters:
in parameter input stream
Reimplemented from McMd::Diagnostic.
Definition at line 32 of file RadiusGyration.cpp.
References Util::DArray< Data >::allocate(), Util::Average::clear(), McMd::Diagnostic::fileMaster(), McMd::Species::nAtom(), Util::Average::nSamplePerBlock(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), McMd::Diagnostic::readInterval(), McMd::Diagnostic::readOutputFileName(), Util::Average::setNSamplePerBlock(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::RadiusGyration::loadParameters (Serializable::IArchive & ar) [virtual]
Load state to an archive.
Parameters:
ar loading (input) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 62 of file RadiusGyration.cpp.
References McMd::Diagnostic::fileMaster(), McMd::Species::nAtom(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::RadiusGyration::save (Serializable::OArchive & ar) [virtual]
Save state to archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 94 of file RadiusGyration.cpp.
template<class Archive > void McMd::RadiusGyration::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Diagnostic.
Definition at line 151 of file RadiusGyration.h.
References McMd::serialize().
void McMd::RadiusGyration::setup () [virtual]
Clear accumulator.
Reimplemented from McMd::Diagnostic.
Definition at line 100 of file RadiusGyration.cpp.
References Util::Average::clear(), and UTIL_THROW.
void McMd::RadiusGyration::sample (long iStep) [virtual]
Evaluate squared radii of gyration for all molecules, add to ensemble.
Parameters:
iStep step counter
Implements McMd::Diagnostic.
Definition at line 111 of file RadiusGyration.cpp.
References McMd::Molecule::atom(), McMd::System::boundary(), Util::OrthorhombicBoundary::distanceSq(), McMd::Diagnostic::isAtInterval(), McMd::System::molecule(), McMd::System::nMolecule(), McMd::Atom::position(), Util::Average::sample(), Util::Vector::square(), Util::Vector::subtract(), and McMd::SystemDiagnostic< System >::system().
void McMd::RadiusGyration::output () [virtual]
Output results at end of simulation.
Reimplemented from McMd::Diagnostic.
Definition at line 152 of file RadiusGyration.cpp.
References McMd::Diagnostic::fileMaster(), Util::Average::nSamplePerBlock(), Util::FileMaster::openOutputFile(), Util::Average::output(), McMd::Diagnostic::outputFileName(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
RadiusGyration.h
RadiusGyration.cpp