Simpatico: Util::RingBuffer< Data > Class Template Reference
Util::RingBuffer< Data > Class Template Reference
Object Arrays
Detailed Description
template<class Data>
class Util::RingBuffer< Data >
Class for storing history of previous values in an array.
Data is stored in a circular buffer, in which, once the array is full, the newest data value overwrites the oldest.
Definition at line 31 of file RingBuffer.h.
#include <RingBuffer.h>
Public Member Functions
RingBuffer ()
Contructor.
RingBuffer (const RingBuffer< Data > &other)
Copy contructor.
RingBuffer & operator= (const RingBuffer< Data > &other)
Assignment.
virtual ~RingBuffer ()
Destructor.
void allocate (int capacity)
Allocate a new empty buffer.
void clear ()
Set previously allocated buffer to empty state.
void append (Data value)
Add a new value to the buffer.
int size () const
Return number of values currently in the buffer.
int capacity () const
Return the capacity of the buffer.
bool isAllocated () const
Return true if the RingBuffer has been allocated, false otherwise.
bool isFull ()
Return true if the RingBuffer has been allocated, false otherwise.
Data operator[] (int offset) const
Retrieve a previous value, a specified number of time steps ago.
void pack (char *&current, char *end) const
Pack this RingBuffer into a block of memory.
void unpack (char *&current, char *end)
Unpack this RingBuffer from a block of memory.
void pack (PackedData &buffer) const
Pack this RingBuffer into a PackedData object.
void unpack (PackedData &buffer)
Unpack this RingBuffer from a PackedData object.
int packedSize () const
Return packed size of this RingBuffer.
Constructor & Destructor Documentation
template<class Data > Util::RingBuffer< Data >::RingBuffer ()
Contructor.
Definition at line 172 of file RingBuffer.h.
template<class Data> Util::RingBuffer< Data >::RingBuffer (const RingBuffer< Data > & other)
Copy contructor.
Parameters:
other object to be copied.
Definition at line 187 of file RingBuffer.h.
template<class Data > Util::RingBuffer< Data >::~RingBuffer () [virtual]
Destructor.
Definition at line 251 of file RingBuffer.h.
Member Function Documentation
template<class Data> RingBuffer< Data > & Util::RingBuffer< Data >::operator= (const RingBuffer< Data > & other)
Assignment.
Parameters:
other object to be assigned.
Definition at line 214 of file RingBuffer.h.
References Util::RingBuffer< Data >::isAllocated(), and UTIL_THROW.
template<class Data > void Util::RingBuffer< Data >::allocate (int capacity)
Allocate a new empty buffer.
Allocate a new array containing capacity elements.
Throw an Exception if this RingBuffer has already been allocated - a RingBuffer can only be allocated once.
Parameters:
capacity number of elements to allocate.
Definition at line 260 of file RingBuffer.h.
References UTIL_THROW.
template<class Data > void Util::RingBuffer< Data >::clear ()
Set previously allocated buffer to empty state.
Definition at line 276 of file RingBuffer.h.
template<class Data> void Util::RingBuffer< Data >::append (Data value)
Add a new value to the buffer.
Parameters:
value new value to be added.
Definition at line 286 of file RingBuffer.h.
template<class Data > int Util::RingBuffer< Data >::size () const
Return number of values currently in the buffer.
Definition at line 306 of file RingBuffer.h.
template<class Data > int Util::RingBuffer< Data >::capacity () const
Return the capacity of the buffer.
Definition at line 313 of file RingBuffer.h.
template<class Data > bool Util::RingBuffer< Data >::isAllocated () const
Return true if the RingBuffer has been allocated, false otherwise.
Definition at line 320 of file RingBuffer.h.
Referenced by Util::RingBuffer< Data >::operator=().
template<class Data > bool Util::RingBuffer< Data >::isFull ()
Return true if the RingBuffer has been allocated, false otherwise.
Definition at line 327 of file RingBuffer.h.
template<class Data > Data Util::RingBuffer< Data >::operator[] (int offset) const
Retrieve a previous value, a specified number of time steps ago.
Parameters:
offset number of steps back in time (offset=0 is current value).
Definition at line 334 of file RingBuffer.h.
References UTIL_THROW.
template<typename Data > void Util::RingBuffer< Data >::pack (char *& current, char * end) const
Pack this RingBuffer into a block of memory.
Throws an exception if buffer would be overrun.
Parameters:
current pointer to current position in write buffer (in/out)
end pointer to end (one char* past last) of buffer
Definition at line 351 of file RingBuffer.h.
References UTIL_THROW.
template<typename Data > void Util::RingBuffer< Data >::unpack (char *& current, char * end)
Unpack this RingBuffer from a block of memory.
Throws an exception if buffer would be overrun.
Parameters:
current pointer to current position in read buffer (in/out)
end pointer to end (one char* past last) of buffer
Definition at line 377 of file RingBuffer.h.
References UTIL_THROW.
template<class Data > void Util::RingBuffer< Data >::pack (PackedData & buffer) const
Pack this RingBuffer into a PackedData object.
Parameters:
buffer PackedData object to which to write.
Definition at line 409 of file RingBuffer.h.
References Util::PackedData::pack().
template<class Data > void Util::RingBuffer< Data >::unpack (PackedData & buffer)
Unpack this RingBuffer from a PackedData object.
Parameters:
buffer PackedData object from which to read.
Definition at line 421 of file RingBuffer.h.
References Util::PackedData::unpack(), and UTIL_THROW.
template<typename Data > int Util::RingBuffer< Data >::packedSize () const
Return packed size of this RingBuffer.
Returns number of bytes required by this in a packed buffer.
Definition at line 434 of file RingBuffer.h.
The documentation for this class was generated from the following file:
RingBuffer.h