Simpatico: McMd::ExternalPotentialImpl< Interaction > Class Template Reference
McMd::ExternalPotentialImpl< Interaction > Class Template Reference
External Potentials
Detailed Description
template<class Interaction>
class McMd::ExternalPotentialImpl< Interaction >
Template implementation of ExternalPotential.
Definition at line 34 of file mcMd/potentials/external/ExternalPotentialImpl.h.
#include <ExternalPotentialImpl.h>
Public Member Functions
ExternalPotentialImpl (System &system)
Constructor.
ExternalPotentialImpl (ExternalPotentialImpl< Interaction > &other)
Constructor (copied from ExternalPotential)
virtual ~ExternalPotentialImpl ()
Destructor.
virtual void readParameters (std::istream &in)
Read param for external potential.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
Interaction & interaction ()
Return external interaction by reference.
const Interaction & interaction () const
Return external interaction by const reference.
Interaction interface
virtual double energy (const Vector &position, int typeId) const
Returns external potential energy of a single particle.
virtual void getForce (const Vector &position, int typeId, Vector &force) const
Returns force caused by the external potential.
virtual std::string interactionClassName () const
Return external interaction class name (e.g., "LamellarOrderingExternal").
System energy and force calculators
void addForces ()
Add external force of an Atom to the total force acting on it.
double energy () const
Return total external energy of this System.
double atomEnergy (const Atom &atom) const
Calculate the external energy for one Atom.
Public Member Functions inherited from McMd::ExternalPotential
ExternalPotential ()
Constructor .
virtual ~ExternalPotential ()
Destructor (does nothing)
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Public Member Functions inherited from McMd::SubSystem
SubSystem (System &parent)
Constructor.
virtual ~SubSystem ()
Destructor.
System & system () const
Get the parent System by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from McMd::SubSystem
Boundary & boundary () const
Get the Boundary by reference.
Simulation & simulation () const
Get the parent Simulation by reference.
int nMolecule (int speciesId) const
Get the number of molecules of one Species in this SubSystem.
int nAtom () const
Return the total number of atoms in this SubSystem.
bool isEmpty () const
Is this an empty SubSystem (i.e., one with no molecules) ?
void begin (int speciesId, System::MoleculeIterator &iterator)
Initialize an iterator for molecules of one species in this SubSystem.
void begin (int speciesId, System::ConstMoleculeIterator &iterator) const
Initialize a const iterator for molecules of one species in this SubSystem.
bool hasBonds () const
Does a bond potential exist?
bool hasAngles () const
Does an angle potential exist?
bool hasDihedrals () const
Does a dihedral potential exist?
bool hasLinks () const
Does a link potential exist?
bool hasExternal () const
Does an external potential exist?
Constructor & Destructor Documentation
template<class Interaction > McMd::ExternalPotentialImpl< Interaction >::ExternalPotentialImpl (System & system)
Constructor.
Definition at line 166 of file mcMd/potentials/external/ExternalPotentialImpl.h.
template<class Interaction > McMd::ExternalPotentialImpl< Interaction >::ExternalPotentialImpl (ExternalPotentialImpl< Interaction > & other)
Constructor (copied from ExternalPotential)
Definition at line 177 of file mcMd/potentials/external/ExternalPotentialImpl.h.
template<class Interaction > McMd::ExternalPotentialImpl< Interaction >::~ExternalPotentialImpl () virtual
Destructor.
Definition at line 189 of file mcMd/potentials/external/ExternalPotentialImpl.h.
Member Function Documentation
template<class Interaction > void McMd::ExternalPotentialImpl< Interaction >::readParameters (std::istream & in) virtual
Read param for external potential.
This method reads the external potential Interaction parameter block. Before calling Interaction::readParameters(), it passes simulation().nExternalType() to Interaction::setNAtomType().
Reimplemented from Util::ParamComposite.
Definition at line 196 of file mcMd/potentials/external/ExternalPotentialImpl.h.
template<class Interaction > void McMd::ExternalPotentialImpl< Interaction >::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 213 of file mcMd/potentials/external/ExternalPotentialImpl.h.
template<class Interaction > void McMd::ExternalPotentialImpl< Interaction >::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 228 of file mcMd/potentials/external/ExternalPotentialImpl.h.
template<class Interaction > double McMd::ExternalPotentialImpl< Interaction >::energy (const Vector & position, int typeId) const virtual
Returns external potential energy of a single particle.
Parameters
position atomic position Vector
typeId atom type index
Returns
external potential energy
Implements McMd::ExternalPotential.
Definition at line 241 of file mcMd/potentials/external/ExternalPotentialImpl.h.
template<class Interaction > void McMd::ExternalPotentialImpl< Interaction >::getForce (const Vector & position, int typeId, Vector & force) const virtual
Returns force caused by the external potential.
Parameters
position atom position
typeId atom type index
force force on the atom (on output)
Implements McMd::ExternalPotential.
Definition at line 249 of file mcMd/potentials/external/ExternalPotentialImpl.h.
template<class Interaction > std::string McMd::ExternalPotentialImpl< Interaction >::interactionClassName () const virtual
Return external interaction class name (e.g., "LamellarOrderingExternal").
Implements McMd::ExternalPotential.
Definition at line 315 of file mcMd/potentials/external/ExternalPotentialImpl.h.
template<class Interaction > void McMd::ExternalPotentialImpl< Interaction >::addForces () virtual
Add external force of an Atom to the total force acting on it.
Implements McMd::ExternalPotential.
Definition at line 277 of file mcMd/potentials/external/ExternalPotentialImpl.h.
References Util::ArrayIterator< Data >::notEnd(), and Util::PArrayIterator< Data >::notEnd().
template<class Interaction > double McMd::ExternalPotentialImpl< Interaction >::energy () const virtual
Return total external energy of this System.
Implements McMd::ExternalPotential.
Definition at line 257 of file mcMd/potentials/external/ExternalPotentialImpl.h.
References Util::ConstArrayIterator< Data >::notEnd(), and Util::ConstPArrayIterator< Data >::notEnd().
template<class Interaction > double McMd::ExternalPotentialImpl< Interaction >::atomEnergy (const Atom & atom) const virtual
Calculate the external energy for one Atom.
Implements McMd::ExternalPotential.
Definition at line 294 of file mcMd/potentials/external/ExternalPotentialImpl.h.
References McMd::Atom::position(), and McMd::Atom::typeId().
template<class Interaction > Interaction & McMd::ExternalPotentialImpl< Interaction >::interaction () inline
Return external interaction by reference.
Definition at line 304 of file mcMd/potentials/external/ExternalPotentialImpl.h.
Referenced by McMd::McExternalPerturbation< Interaction >::interaction().
template<class Interaction > const Interaction & McMd::ExternalPotentialImpl< Interaction >::interaction () const inline
Return external interaction by const reference.
Definition at line 308 of file mcMd/potentials/external/ExternalPotentialImpl.h.
The documentation for this class was generated from the following file:
mcMd/potentials/external/ExternalPotentialImpl.h