Simpatico: McMd::Perturbation Class Reference
McMd::Perturbation Class Reference abstract
McMd namespace » Free Energy Perturbation
Detailed Description
Model of parameter dependence in a free energy perturbation theory.
A Perturbation object defines a parameter dependent statistical weight of the type used in free energy perturbation theory, replica exchange, and extended ensemble algorithms. In all of these applications, the probability of a microstate X is given by an exponential exp(-W(X,p)), where W(X,p) = beta*H depends upon a perturbation parameter p, H is the system Hamiltonian and beta = 1/kT is inverse temperature. Either the Hamiltonian or the inverse temperature may depend upon the perturbation parameter.
This class provides a method to modify the system parameters (beta and/or the potential energy parameters) so as to correspond to a given value of p, and methods to evaluate the derivative dW(X,p)/dp and difference W(X, p') - W(X, p) for a given system configuration.
Definition at line 39 of file Perturbation.h.
#include <Perturbation.h>
Public Member Functions
Perturbation (int size, int rank)
Constructor.
virtual ~Perturbation ()
Destructor.
Mutators
void readParameters (std::istream &in)
Read perturbation parameter(s) from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void setParameter (DArray< double > parameter)
Sets the perturbation parameter value.
Accessors
double parameter (int i, int id)
Get parameter i of system id.
int getNParameters () const
Gets the number of parameters per system.
virtual double parameter (int i) const =0
Get perturbation parameter p[i] of index i for this system.
virtual double derivative (int i) const =0
Get derivative of the Boltzmann weight W(X,p) with respect to the perturbation parameter p[i] of index i.
virtual double difference (DArray< double > iPartnerParameter) const =0
Returns the difference W(X, p') - W(X, p).
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
virtual void setParameter ()=0
Sets the perturbation parameter in the associated system.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
int size_
Number of systems (e.g., communicator size)
int rank_
Index for this system (e.g., communicator size)
int nParameters_
Number of perturbation parameters associated with a System.
int mode_
mode 0: parameters of all replica systems are specified.
DArray< double > parameter_
Value of the perturbation parameter for the associated System.
DArray< double > initialParameter_
Value of the perturbation parameter for the first replica System.
DArray< double > finalParameter_
Value of the perturbation parameter for the last replica System.
DMatrix< double > parameters_
Value of the perturbation parameter for all the replica Systems.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Constructor & Destructor Documentation
McMd::Perturbation::Perturbation (int size, int rank)
Constructor.
Parameters
size number of parameter values (e.g., communicator size)
rank index of this system (e.g., communicator rank)
Definition at line 16 of file Perturbation.cpp.
References Util::ParamComposite::setClassName().
McMd::Perturbation::~Perturbation () virtual
Destructor.
Definition at line 27 of file Perturbation.cpp.
Member Function Documentation
void McMd::Perturbation::readParameters (std::istream & in) virtual
Read perturbation parameter(s) from file.
Parameters
in input stream (file or std in).
Reimplemented from Util::ParamComposite.
Definition at line 33 of file Perturbation.cpp.
References Util::DMatrix< Data >::allocate(), Util::DArray< Data >::allocate(), finalParameter_, initialParameter_, mode_, nParameters_, parameter_, parameters_, rank_, setParameter(), and size_.
Referenced by McMd::McEnergyPerturbation::readParameters(), McMd::McExternalPerturbation< Interaction >::readParameters(), McMd::McPairPerturbation< Interaction >::readParameters(), and McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >::readParameters().
void McMd::Perturbation::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Reimplemented in McMd::McPairPerturbation< Interaction >.
Definition at line 69 of file Perturbation.cpp.
References Util::DMatrix< Data >::allocate(), Util::DArray< Data >::allocate(), finalParameter_, initialParameter_, mode_, nParameters_, parameter_, parameters_, setParameter(), and size_.
Referenced by McMd::McPairPerturbation< Interaction >::loadParameters().
void McMd::Perturbation::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 91 of file Perturbation.cpp.
References finalParameter_, initialParameter_, mode_, nParameters_, parameter_, and parameters_.
Referenced by McMd::System::savePerturbation().
void McMd::Perturbation::setParameter (DArray< double > parameter)
Sets the perturbation parameter value.
This method sets the value of the member parameter, and calls the virtual void setParameter() method to modify the parameter of the associated System.
Parameters
parameter perturbation parameter value for associated System.
Definition at line 110 of file Perturbation.cpp.
References parameter(), parameter_, and setParameter().
double McMd::Perturbation::parameter (int i, int id)
Get parameter i of system id.
Parameters
i index of perturbation parameter
id id of system in a mpi simulation
Returns the value of the perturbation parameter p[i].
Definition at line 119 of file Perturbation.cpp.
References parameters_.
Referenced by McMd::LinearPerturbation< SystemType >::difference(), McMd::ReplicaMove::move(), McMd::BennettsMethod::sample(), and setParameter().
int McMd::Perturbation::getNParameters () const
Gets the number of parameters per system.
Returns the number of perturbation parameters for this system.
Definition at line 125 of file Perturbation.cpp.
References nParameters_.
Referenced by McMd::BennettsMethod::BennettsMethod(), McMd::LinearPerturbation< SystemType >::difference(), McMd::McPairPerturbation< Interaction >::loadParameters(), McMd::McEnergyPerturbation::readParameters(), McMd::McExternalPerturbation< Interaction >::readParameters(), McMd::McPairPerturbation< Interaction >::readParameters(), McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >::readParameters(), and McMd::ReplicaMove::ReplicaMove().
virtual double McMd::Perturbation::parameter (int i) const pure virtual
Get perturbation parameter p[i] of index i for this system.
Returns the value of the perturbation parameter p[i].
Implemented in McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >, McMd::McPairPerturbation< Interaction >, McMd::McExternalPerturbation< Interaction >, and McMd::McEnergyPerturbation.
virtual double McMd::Perturbation::derivative (int i) const pure virtual
Get derivative of the Boltzmann weight W(X,p) with respect to the perturbation parameter p[i] of index i.
For a system in which W(X,p) = beta*H depends on a microstate X and a parameter p, this method returns the value of dW(X, p)/dp[i] for the current system microstate (i.e., for the current particle positions).
Implemented in McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >, McMd::McPairPerturbation< Interaction >, McMd::McExternalPerturbation< Interaction >, and McMd::McEnergyPerturbation.
Referenced by McMd::LinearPerturbation< SystemType >::difference(), and McMd::ReplicaMove::move().
virtual double McMd::Perturbation::difference (DArray< double > iPartnerParameter) const pure virtual
Returns the difference W(X, p') - W(X, p).
This method returns the difference W(X, p') - W(X, p) between value of the statistical weight W(X,p[i]) = H/kT for the current microstate, where p[i] is the value of the perturbation parameter in this system, and p'[i] = iPartnerParameter is the partner perturbation parameter value that is passed to this function.
Parameters
iPartnerParameter perturbation parameters for partner system.
Implemented in McMd::LinearPerturbation< SystemType >, and McMd::LinearPerturbation< McSystem >.
Referenced by McMd::BennettsMethod::sample().
virtual void McMd::Perturbation::setParameter () protected pure virtual
Sets the perturbation parameter in the associated system.
This method modifies the parameters of the associated System so as to correspond to the value of the parameter member variable.
Implemented in McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >, McMd::McPairPerturbation< Interaction >, McMd::McExternalPerturbation< Interaction >, and McMd::McEnergyPerturbation.
Referenced by loadParameters(), readParameters(), and setParameter().
Member Data Documentation
int McMd::Perturbation::size_ protected
Number of systems (e.g., communicator size)
Definition at line 150 of file Perturbation.h.
Referenced by loadParameters(), and readParameters().
int McMd::Perturbation::rank_ protected
Index for this system (e.g., communicator size)
Definition at line 155 of file Perturbation.h.
Referenced by readParameters().
int McMd::Perturbation::nParameters_ protected
Number of perturbation parameters associated with a System.
Definition at line 160 of file Perturbation.h.
Referenced by getNParameters(), loadParameters(), readParameters(), and save().
int McMd::Perturbation::mode_ protected
mode 0: parameters of all replica systems are specified.
mode 1: parameters of first and last replica systems are specified.
Definition at line 166 of file Perturbation.h.
Referenced by loadParameters(), readParameters(), and save().
DArray<double> McMd::Perturbation::parameter_ protected
Value of the perturbation parameter for the associated System.
parameter is a DMatrix of dimensions 1xnParameters.
Definition at line 172 of file Perturbation.h.
Referenced by McMd::McExternalPerturbation< Interaction >::derivative(), McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >::derivative(), McMd::McPairPerturbation< Interaction >::derivative(), loadParameters(), readParameters(), save(), McMd::McEnergyPerturbation::setParameter(), McMd::McExternalPerturbation< Interaction >::setParameter(), McMd::McPairPerturbation< Interaction >::setParameter(), McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >::setParameter(), and setParameter().
DArray<double> McMd::Perturbation::initialParameter_ protected
Value of the perturbation parameter for the first replica System.
initialParameter is a DMatrix of dimensions 1xnParameters.
Definition at line 178 of file Perturbation.h.
Referenced by loadParameters(), readParameters(), and save().
DArray<double> McMd::Perturbation::finalParameter_ protected
Value of the perturbation parameter for the last replica System.
finalParameter is a DMatrix of dimensions 1xnParameters.
Definition at line 184 of file Perturbation.h.
Referenced by loadParameters(), readParameters(), and save().
DMatrix<double> McMd::Perturbation::parameters_ protected
Value of the perturbation parameter for all the replica Systems.
parameters is a DMatrix of dimensions nProcsxnParameters.
Definition at line 190 of file Perturbation.h.
Referenced by loadParameters(), parameter(), readParameters(), and save().
The documentation for this class was generated from the following files:
Perturbation.h
Perturbation.cpp