Simpatico: McMd::Generator Class Reference
McMd::Generator Class Reference abstract
McMd namespace » Generators
Detailed Description
Generates initial configurations for molecules of one species.
Definition at line 34 of file Generator.h.
#include <Generator.h>
Public Member Functions
Generator (Species &species, System &system)
Constructor.
virtual ~Generator ()
Destructor.
void setBondPotential (BondPotential &bondPotential)
Create an association with a BondPotential.
virtual bool generate (int nMolecule, const DArray< double > &diameters, CellList &cellList)
Generate nMolecule molecules of the associated Species.
Static Public Member Functions
static void setupCellList (int atomCapacity, Boundary &boundary, const DArray< double > &diameters, CellList &cellList)
Allocate any required memory for the cell list.
Protected Member Functions
bool attemptPlaceAtom (Atom &atom, const DArray< double > &diameters, CellList &cellList)
Attempt to place an atom.
virtual bool attemptPlaceMolecule (Molecule &molecule, const DArray< double > &diameters, CellList &cellList)=0
Attempt to insert an entire molecule (pure virtual).
const Species & species ()
Get the associated Species by reference.
Simulation & simulation ()
Get the associated Simulation by reference.
System & system ()
Get the associated System by reference.
const Boundary & boundary () const
Get the associated Boundary by reference.
const BondPotential & bondPotential ()
Get the associated BondPotential by reference.
Constructor & Destructor Documentation
McMd::Generator::Generator (Species & species, System & system)
Constructor.
Parameters
species associated Species object
system parent System
Definition at line 24 of file Generator.cpp.
McMd::Generator::~Generator () virtual
Destructor.
Definition at line 35 of file Generator.cpp.
Member Function Documentation
void McMd::Generator::setBondPotential (BondPotential & bondPotential)
Create an association with a BondPotential.
Parameters
bondPotential BondPotential
Definition at line 42 of file Generator.cpp.
References bondPotential().
Referenced by McMd::generatorFactory().
bool McMd::Generator::generate (int nMolecule, const DArray< double > & diameters, CellList & cellList) virtual
Generate nMolecule molecules of the associated Species.
Precondition
Size of diameters array == number of atom types
Parameters
nMolecule desired number of molecules
diameters array of excluded volume diameters for atomTypes
cellList CellList object
Definition at line 84 of file Generator.cpp.
References McMd::System::addMolecule(), McMd::CellList::atomCapacity(), McMd::Simulation::atomCapacity(), attemptPlaceMolecule(), Util::Log::file(), McMd::Simulation::getMolecule(), McMd::Species::id(), McMd::Species::isMutable(), McMd::Species::mutator(), McMd::System::removeMolecule(), McMd::SpeciesMutator::setMoleculeState(), simulation(), McMd::System::simulation(), species(), McMd::Simulation::species(), system(), and UTIL_CHECK.
Referenced by McMd::MdSimulation::readCommands(), and McMd::McSimulation::readCommands().
void McMd::Generator::setupCellList (int atomCapacity, Boundary & boundary, const DArray< double > & diameters, CellList & cellList) static
Allocate any required memory for the cell list.
Parameters
atomCapacity maximum allowed atom id + 1
boundary Boundary object, periodic unit cell
diameters array of excluded volume diameters
cellList CellList to be allocated
Definition at line 128 of file Generator.cpp.
References Util::Array< Data >::capacity(), McMd::CellList::setAtomCapacity(), and McMd::CellList::setup().
Referenced by McMd::MdSimulation::readCommands(), and McMd::McSimulation::readCommands().
bool McMd::Generator::attemptPlaceAtom (Atom & atom, const DArray< double > & diameters, CellList & cellList) protected
Attempt to place an atom.
The proposed position for the atom should be set upon entry. This function checks if the atom position is within the hard-core cutoff distance of any atoms that are already in the cell list. The cutoff distance for atoms of types i and j is the average of the excluded volume diameters for types i and j. If the atom position satisfies this geometrical constraint, the atom is added to the cell list and returns true. If it does not, the function returns false.
Parameters
atom new Atom, with proposed position already set
diameters array of excluded diameters for atom types
cellList CellList object containing existing atoms
Returns
true on success, false on failure.
Definition at line 49 of file Generator.cpp.
References McMd::CellList::addAtom(), boundary(), Util::OrthorhombicBoundary::distanceSq(), McMd::CellList::getNeighbors(), McMd::Atom::position(), Util::OrthorhombicBoundary::shift(), Util::FSArray< Data, Capacity >::size(), and McMd::Atom::typeId().
Referenced by McMd::PointGenerator::attemptPlaceMolecule(), and McMd::LinearGenerator::attemptPlaceMolecule().
virtual bool McMd::Generator::attemptPlaceMolecule (Molecule & molecule, const DArray< double > & diameters, CellList & cellList) protected pure virtual
Attempt to insert an entire molecule (pure virtual).
Parameters
molecule new molecule, with unknown atomic positions
diameters array of excluded volume diameters for types
cellList CellList object storing existing atoms
Returns
true on success, false on failure.
Implemented in McMd::LinearGenerator, and McMd::PointGenerator.
Referenced by generate().
const Species & McMd::Generator::species () inline protected
Get the associated Species by reference.
Definition at line 180 of file Generator.h.
Referenced by McMd::LinearGenerator::attemptPlaceMolecule(), and generate().
Simulation & McMd::Generator::simulation () inline protected
Get the associated Simulation by reference.
Definition at line 186 of file Generator.h.
Referenced by McMd::PointGenerator::attemptPlaceMolecule(), McMd::LinearGenerator::attemptPlaceMolecule(), and generate().
System & McMd::Generator::system () inline protected
Get the associated System by reference.
Definition at line 192 of file Generator.h.
Referenced by generate().
const Boundary & McMd::Generator::boundary () const inline protected
Get the associated Boundary by reference.
Definition at line 198 of file Generator.h.
Referenced by attemptPlaceAtom(), McMd::PointGenerator::attemptPlaceMolecule(), and McMd::LinearGenerator::attemptPlaceMolecule().
const BondPotential & McMd::Generator::bondPotential () inline protected
Get the associated BondPotential by reference.
Definition at line 205 of file Generator.h.
Referenced by McMd::LinearGenerator::attemptPlaceMolecule(), and setBondPotential().
The documentation for this class was generated from the following files:
Generator.h
Generator.cpp