Simpatico: Inter::SlitExternal Class Reference
Inter::SlitExternal Class Reference
External Interactions
Detailed Description
A repulsive 9-3 potential confining particles along the z direction.
 4 epsilon pi rho   / sigma^9        sigma^6       25     \
u = --------------— | ------— - 7.5 -----— + -------— | 45 sigma^(-3) \ r^9 r^6 sqrt(10) /
The coefficients are obtained by integrating the repulsive LJPair potential in a half space with default density rho = 0.7. Member variables include strength of the potential epsilon, the range of interaction sigma, and the cutoff length 0.4^(1/6) = 0.85837422. Member functions evaluate energy and force for individual particles. The internal cutoff 0.506079 = 0.129615^(1/3) is set to yield a cutoff potential of 80 for the default density 0.7.
The potential is independent on the type of atoms.
Definition at line 40 of file SlitExternal.h.
#include <SlitExternal.h>
Public Member Functions
SlitExternal ()
Default constructor.
SlitExternal (const SlitExternal &other)
Copy constructor.
SlitExternal & operator= (const SlitExternal &other)
Assignment.
Mutators
void setNAtomType (int nAtomType)
Set nAtomType value.
void setBoundary (Boundary &boundary)
Set pointer to Boundary.
void setExternalParameter (double externalParameter)
Sets external parameter.
void readParameters (std::istream &in)
Read potential parameters, and initialize other variables.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
Accessors
std::string className () const
Return name string "LJPair" for this evaluator class.
double externalParameter () const
Returns external parameter.
double energy (double d, int i) const
Returns external potential energy of a particle of type i.
double energy (const Vector &position, int i) const
Returns external potential energy of a single particle.
double forceScalar (double d, int i) const
Returns magnitude of the repulsive force.
void getForce (const Vector &position, int type, Vector &force) const
Returns force caused by the external potential.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Constructor & Destructor Documentation
Inter::SlitExternal::SlitExternal ()
Default constructor.
Definition at line 23 of file SlitExternal.cpp.
References Util::ParamComposite::setClassName().
Inter::SlitExternal::SlitExternal (const SlitExternal & other)
Copy constructor.
Definition at line 32 of file SlitExternal.cpp.
Member Function Documentation
SlitExternal & Inter::SlitExternal::operator= (const SlitExternal & other)
Assignment.
Definition at line 46 of file SlitExternal.cpp.
void Inter::SlitExternal::setNAtomType (int nAtomType)
Set nAtomType value.
Parameters
nAtomType number of atom types.
Definition at line 62 of file SlitExternal.cpp.
References UTIL_THROW.
void Inter::SlitExternal::setBoundary (Boundary & boundary)
Set pointer to Boundary.
Parameters
boundary Boundary object (used to calculate distances).
Definition at line 76 of file SlitExternal.cpp.
void Inter::SlitExternal::setExternalParameter (double externalParameter)
Sets external parameter.
Set epsilon to the externalParameter.
Parameters
externalParameter external parameter of system
Definition at line 82 of file SlitExternal.cpp.
References externalParameter(), and UTIL_THROW.
void Inter::SlitExternal::readParameters (std::istream & in) virtual
Read potential parameters, and initialize other variables.
Precondition
nAtomType must have been set, by calling setNAtomType().
Boundary must have been set, by calling setBoundary().
Parameters
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 95 of file SlitExternal.cpp.
References UTIL_THROW.
void Inter::SlitExternal::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 119 of file SlitExternal.cpp.
References UTIL_THROW.
void Inter::SlitExternal::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 139 of file SlitExternal.cpp.
std::string Inter::SlitExternal::className () const
Return name string "LJPair" for this evaluator class.
Return name string "SlitExternal" for this evaluator class.
Definition at line 160 of file SlitExternal.cpp.
double Inter::SlitExternal::externalParameter () const
Returns external parameter.
Return epsilon for externalParameter.
Returns
external parameter
Definition at line 152 of file SlitExternal.cpp.
Referenced by setExternalParameter().
double Inter::SlitExternal::energy (double d, int i) const inline
Returns external potential energy of a particle of type i.
Parameters
d distance to the nearest boundary
i type of particle (not used)
Returns
external potential energy
Definition at line 205 of file SlitExternal.h.
double Inter::SlitExternal::energy (const Vector & position, int i) const inline
Returns external potential energy of a single particle.
Parameters
position atomic position Vector
i atom type.
Returns
external potential energy
Definition at line 221 of file SlitExternal.h.
double Inter::SlitExternal::forceScalar (double d, int i) const inline
Returns magnitude of the repulsive force.
Multiply this quantity by the components of the separation vector to obtain the force vector.
Parameters
d distance from the nearest wall.
i atom type id (not used)
Returns
force scalar
Definition at line 232 of file SlitExternal.h.
void Inter::SlitExternal::getForce (const Vector & position, int type, Vector & force) const inline
Returns force caused by the external potential.
Parameters
position atom position
type atom type id
force force on the atom (on output)
Definition at line 249 of file SlitExternal.h.
The documentation for this class was generated from the following files:
SlitExternal.h
SlitExternal.cpp