Simpatico: DdMd::VirialStressTensor Class Reference
DdMd::VirialStressTensor Class Reference
Analyzers
Detailed Description
Periodically write (tensor) StressTensor to file.
Definition at line 27 of file VirialStressTensor.h.
#include <VirialStressTensor.h>
Public Member Functions
VirialStressTensor (Simulation &simulation)
Constructor.
virtual ~VirialStressTensor ()
Destructor.
virtual void readParameters (std::istream &in)
Read dumpPrefix and interval.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void clear ()
Clear nSample counter.
virtual void sample (long iStep)
Sample virial stress to accumulators.
Constructor & Destructor Documentation
DdMd::VirialStressTensor::VirialStressTensor (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object.
Definition at line 24 of file VirialStressTensor.cpp.
References Util::ParamComposite::setClassName().
virtual DdMd::VirialStressTensor::~VirialStressTensor () [inline, virtual]
Destructor.
Definition at line 42 of file VirialStressTensor.h.
Member Function Documentation
void DdMd::VirialStressTensor::readParameters (std::istream & in) [virtual]
Read dumpPrefix and interval.
Parameters:
in input parameter file
Reimplemented from Util::ParamComposite.
Definition at line 33 of file VirialStressTensor.cpp.
References DdMd::Simulation::fileMaster(), Util::FileMaster::openOutputFile(), DdMd::Analyzer::outputFileName(), DdMd::Analyzer::readInterval(), DdMd::Analyzer::readOutputFileName(), and DdMd::Analyzer::simulation().
void DdMd::VirialStressTensor::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from DdMd::Analyzer.
Definition at line 51 of file VirialStressTensor.cpp.
References DdMd::Simulation::fileMaster(), Util::MpiLoader< IArchive >::load(), DdMd::Analyzer::loadInterval(), DdMd::Analyzer::loadOutputFileName(), Util::FileMaster::openOutputFile(), DdMd::Analyzer::outputFileName(), and DdMd::Analyzer::simulation().
void DdMd::VirialStressTensor::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from DdMd::Analyzer.
Definition at line 71 of file VirialStressTensor.cpp.
References DdMd::Analyzer::saveInterval(), and DdMd::Analyzer::saveOutputFileName().
void DdMd::VirialStressTensor::clear () [virtual]
Clear nSample counter.
Reimplemented from DdMd::Analyzer.
Definition at line 82 of file VirialStressTensor.cpp.
References UTIL_THROW.
void DdMd::VirialStressTensor::sample (long iStep) [virtual]
Sample virial stress to accumulators.
Parameters:
iStep MD step index
Implements DdMd::Analyzer.
Definition at line 93 of file VirialStressTensor.cpp.
References Util::Tensor::add(), DdMd::Simulation::computeKineticStress(), DdMd::Simulation::computeVirialStress(), DdMd::Analyzer::isAtInterval(), DdMd::Simulation::kineticStress(), DdMd::Analyzer::simulation(), and DdMd::Simulation::virialStress().
The documentation for this class was generated from the following files:
VirialStressTensor.h
VirialStressTensor.cpp