Simpatico: DdMd::LammpsOrderedConfigIo Class Reference
DdMd::LammpsOrderedConfigIo Class Reference
ConfigIos
Detailed Description
Native / default format for configuration files.
LammpsOrderedConfigIo is a ConfigIo that implements the default configuration file format for ddSim.
Definition at line 32 of file LammpsOrderedConfigIo.h.
#include <LammpsOrderedConfigIo.h>
Classes
struct IoAtom
struct IoGroup
Public Member Functions
LammpsOrderedConfigIo ()
Default constructor.
LammpsOrderedConfigIo (Simulation &simulation)
Constructor.
virtual void readConfig (std::istream &file, MaskPolicy maskPolicy)
Read configuration file.
virtual void writeConfig (std::ostream &file)
Write configuration file.
Constructor & Destructor Documentation
DdMd::LammpsOrderedConfigIo::LammpsOrderedConfigIo ()
Default constructor.
Definition at line 45 of file LammpsOrderedConfigIo.cpp.
DdMd::LammpsOrderedConfigIo::LammpsOrderedConfigIo (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object.
Definition at line 52 of file LammpsOrderedConfigIo.cpp.
References DdMd::Simulation::nAtomType(), and DdMd::Simulation::nBondType().
Member Function Documentation
void DdMd::LammpsOrderedConfigIo::readConfig (std::istream & file, MaskPolicy maskPolicy) [virtual]
Read configuration file.
This routine opens and reads a file on the master, and distributes atom data among the processors.
Parameters:
file input file stream
maskPolicy MaskPolicy to be used in setting atom masks
Implements DdMd::ConfigIo.
Definition at line 95 of file LammpsOrderedConfigIo.cpp.
References DdMd::AtomDistributor::addAtom(), DdMd::ConfigIo::atomDistributor(), DdMd::ConfigIo::atomStorage(), Util::bcast(), DdMd::ConfigIo::bondDistributor(), DdMd::ConfigIo::bondStorage(), DdMd::ConfigIo::boundary(), DdMd::Domain::communicator(), DdMd::ConfigIo::domain(), DdMd::GroupStorage< N >::isValid(), DdMd::AtomStorage::nAtom(), DdMd::AtomDistributor::newAtomPtr(), DdMd::Atom::position(), DdMd::AtomDistributor::receive(), DdMd::AtomDistributor::send(), DdMd::ConfigIo::setAtomMasks(), DdMd::Atom::setId(), Util::OrthorhombicBoundary::setOrthorhombic(), DdMd::Atom::setTypeId(), DdMd::AtomDistributor::setup(), Util::Vector::subtract(), DdMd::AtomStorage::totalAtomCapacity(), Util::OrthorhombicBoundary::transformCartToGen(), and UTIL_THROW.
void DdMd::LammpsOrderedConfigIo::writeConfig (std::ostream & file) [virtual]
Write configuration file.
This routine opens and writes a file on the master, collecting atom data from all processors.
Parameters:
file output file stream
Implements DdMd::ConfigIo.
Definition at line 333 of file LammpsOrderedConfigIo.cpp.
References DdMd::ConfigIo::atomCollector(), DdMd::ConfigIo::atomStorage(), DdMd::ConfigIo::bondCollector(), DdMd::ConfigIo::bondStorage(), DdMd::ConfigIo::boundary(), DdMd::AtomStorage::computeNAtomTotal(), DdMd::GroupStorage< N >::computeNTotal(), Util::Dimension, DdMd::ConfigIo::domain(), DdMd::Atom::id(), Util::OrthorhombicBoundary::lengths(), DdMd::AtomStorage::nAtomTotal(), DdMd::AtomCollector::nextPtr(), DdMd::Atom::position(), DdMd::AtomCollector::send(), DdMd::AtomCollector::setup(), Util::OrthorhombicBoundary::transformGenToCart(), DdMd::Atom::typeId(), and UTIL_THROW.
The documentation for this class was generated from the following files:
LammpsOrderedConfigIo.h
LammpsOrderedConfigIo.cpp