Simpatico: Simp::DpdPair Class Reference
Simp::DpdPair Class Reference
Simp namespace » Interactions » Pair Interactions
Detailed Description
Soft pair potential used in dissipative particle dynamics (DPD) simulations of Groot, Warren et al.
See also
Parameter file format
Pair Interaction Class Interface
Pair Interactions
Definition at line 31 of file DpdPair.h.
#include <DpdPair.h>
Public Member Functions
DpdPair ()
Constructor.
DpdPair (const DpdPair &other)
Copy constructor.
DpdPair & operator= (const DpdPair &other)
Assignment.
Mutators
void setNAtomType (int nAtomType)
Set nAtomType value.
void readParameters (std::istream &in)
Read epsilon and sigma, initialize other variables.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void setEpsilon (int i, int j, double epsilon)
Set LJ interaction energy for a specific pair of Atom types.
void setSigma (int i, int j, double sigma)
Get LJ range for a specific pair of Atom types.
void set (std::string name, int i, int j, double value)
Modify a parameter, identified by a string.
Accessors (required)
double energy (double rsq, int i, int j) const
Returns interaction energy for a single pair of particles.
double forceOverR (double rsq, int i, int j) const
Returns ratio of scalar pair interaction force to pair separation.
double cutoffSq (int i, int j) const
Get square of cutoff distance for specific type pair.
double maxPairCutoff () const
Get maximum of pair cutoff distance, for all atom type pairs.
double get (std::string name, int i, int j) const
Get a parameter value, identified by a string.
Accessors (extra)
double epsilon (int i, int j) const
Get interaction energy for a specific pair of Atom types.
double sigma (int i, int j) const
Get range for a specific pair of Atom types.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Constructor & Destructor Documentation
Simp::DpdPair::DpdPair ()
Constructor.
Definition at line 22 of file DpdPair.cpp.
References Util::ParamComposite::setClassName().
Simp::DpdPair::DpdPair (const DpdPair & other)
Copy constructor.
Definition at line 31 of file DpdPair.cpp.
Member Function Documentation
DpdPair & Simp::DpdPair::operator= (const DpdPair & other)
Assignment.
Definition at line 51 of file DpdPair.cpp.
void Simp::DpdPair::setNAtomType (int nAtomType)
Set nAtomType value.
Parameters
nAtomType number of atom types.
Definition at line 149 of file DpdPair.cpp.
References UTIL_THROW.
void Simp::DpdPair::readParameters (std::istream & in) virtual
Read epsilon and sigma, initialize other variables.
Precondition
nAtomType must be set, by calling setNAtomType().
Parameters
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 72 of file DpdPair.cpp.
References UTIL_THROW.
void Simp::DpdPair::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 105 of file DpdPair.cpp.
References UTIL_THROW.
void Simp::DpdPair::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 136 of file DpdPair.cpp.
References Util::BinaryFileOArchive::pack().
void Simp::DpdPair::setEpsilon (int i, int j, double epsilon)
Set LJ interaction energy for a specific pair of Atom types.
Parameters
i type of Atom 1
j type of Atom 2
epsilon LJ energy parameter
Definition at line 163 of file DpdPair.cpp.
References epsilon(), and UTIL_THROW.
void Simp::DpdPair::setSigma (int i, int j, double sigma)
Get LJ range for a specific pair of Atom types.
Parameters
i atom type index 1
j atom type index 2
sigma LJ range parameter
Definition at line 191 of file DpdPair.cpp.
References sigma(), and UTIL_THROW.
void Simp::DpdPair::set (std::string name, int i, int j, double value)
Modify a parameter, identified by a string.
Parameters
name parameter name
i atom type index 1
j atom type index 2
value new value of parameter
Definition at line 249 of file DpdPair.cpp.
References UTIL_THROW.
double Simp::DpdPair::energy (double rsq, int i, int j) const inline
Returns interaction energy for a single pair of particles.
Parameters
rsq square of distance between particles
i type of particle 1
j type of particle 2
Returns
pair interaction energy
Definition at line 229 of file DpdPair.h.
double Simp::DpdPair::forceOverR (double rsq, int i, int j) const inline
Returns ratio of scalar pair interaction force to pair separation.
Multiply this quantity by the components of the separation vector to obtain the force vector. A positive value for the return value represents a repulsive force between a pair of particles.
Precondition: The square separation rsq must be less than cutoffSq. If rsq > cutoffSq, the return value is undefined (i.e., wrong). Usage: Test for rsq < cutoffSq before calling this function
if (rsq < interaction.cutoffSq(i, j)) {
   f = forceOverR(rsq, i, j);
   .....
}
Parameters
rsq square of distance between particles
i type of particle 1
j type of particle 2
Returns
force divided by distance
Definition at line 243 of file DpdPair.h.
double Simp::DpdPair::cutoffSq (int i, int j) const inline
Get square of cutoff distance for specific type pair.
Parameters
i type of Atom 1
j type of Atom 2
Returns
cutoffSq_[i][j]
Definition at line 255 of file DpdPair.h.
double Simp::DpdPair::maxPairCutoff () const
Get maximum of pair cutoff distance, for all atom type pairs.
Definition at line 243 of file DpdPair.cpp.
double Simp::DpdPair::get (std::string name, int i, int j) const
Get a parameter value, identified by a string.
Parameters
name parameter name
i atom type index 1
j atom type index 2
Definition at line 266 of file DpdPair.cpp.
References UTIL_THROW.
double Simp::DpdPair::epsilon (int i, int j) const
Get interaction energy for a specific pair of Atom types.
Parameters
i type of Atom 1
j type of Atom 2
Returns
epsilon_[i][j]
Definition at line 223 of file DpdPair.cpp.
Referenced by setEpsilon().
double Simp::DpdPair::sigma (int i, int j) const
Get range for a specific pair of Atom types.
Parameters
i atom type index 1
j atom type index 2
Returns
sigma_[i][j]
Definition at line 233 of file DpdPair.cpp.
Referenced by setSigma().
The documentation for this class was generated from the following files:
DpdPair.h
DpdPair.cpp