Simpatico: McMd::MdPotentialEnergyAverage Class Reference
McMd::MdPotentialEnergyAverage Class Reference
MD Analyzers
Detailed Description
MdPotentialEnergyAverage averages of total potential energy.
Definition at line 25 of file MdPotentialEnergyAverage.h.
#include <MdPotentialEnergyAverage.h>
Public Member Functions
MdPotentialEnergyAverage (MdSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters and initialize.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Clear accumulator.
virtual void sample (long iStep)
Calculate, analyze and/or output a physical quantity.
virtual void output ()
Output results at end of simulation.
Constructor & Destructor Documentation
McMd::MdPotentialEnergyAverage::MdPotentialEnergyAverage (MdSystem & system)
Constructor.
Definition at line 22 of file MdPotentialEnergyAverage.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::MdPotentialEnergyAverage::readParameters (std::istream & in) [virtual]
Read parameters and initialize.
Reimplemented from McMd::Analyzer.
Definition at line 32 of file MdPotentialEnergyAverage.cpp.
References McMd::Analyzer::fileMaster(), Util::Average::nSamplePerBlock(), Util::FileMaster::openOutputFile(), McMd::Analyzer::outputFileName(), McMd::Analyzer::readInterval(), McMd::Analyzer::readOutputFileName(), and Util::Average::setNSamplePerBlock().
void McMd::MdPotentialEnergyAverage::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from McMd::Analyzer.
Definition at line 49 of file MdPotentialEnergyAverage.cpp.
References McMd::Analyzer::fileMaster(), McMd::Analyzer::loadInterval(), McMd::Analyzer::loadOutputFileName(), Util::FileMaster::openOutputFile(), and McMd::Analyzer::outputFileName().
void McMd::MdPotentialEnergyAverage::save (Serializable::OArchive & ar) [virtual]
Save state to an archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::Analyzer.
Definition at line 66 of file MdPotentialEnergyAverage.cpp.
template<class Archive > void McMd::MdPotentialEnergyAverage::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Analyzer.
Definition at line 98 of file MdPotentialEnergyAverage.h.
References McMd::serialize().
void McMd::MdPotentialEnergyAverage::setup () [virtual]
Clear accumulator.
Reimplemented from McMd::Analyzer.
Definition at line 73 of file MdPotentialEnergyAverage.cpp.
References Util::Average::clear().
void McMd::MdPotentialEnergyAverage::sample (long iStep) [virtual]
Calculate, analyze and/or output a physical quantity.
Take an action if iStep is a multiple of interval. If iStep is not a multiple of interval, this method should do nothing and return immediately.
Parameters:
iStep current simulation step index.
Implements McMd::Analyzer.
Definition at line 79 of file MdPotentialEnergyAverage.cpp.
References McMd::Analyzer::isAtInterval(), Util::Average::sample(), and McMd::SystemAnalyzer< MdSystem >::system().
void McMd::MdPotentialEnergyAverage::output () [virtual]
Output results at end of simulation.
Reimplemented from McMd::Analyzer.
Definition at line 89 of file MdPotentialEnergyAverage.cpp.
References McMd::Analyzer::fileMaster(), Util::Average::nSamplePerBlock(), Util::FileMaster::openOutputFile(), Util::Average::output(), McMd::Analyzer::outputFileName(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
MdPotentialEnergyAverage.h
MdPotentialEnergyAverage.cpp