Simpatico: Inter::GeneralPeriodicExternal Class Reference
Inter::GeneralPeriodicExternal Class Reference
External Interactions
Detailed Description
A clipped cosine potential that induces ordering along directions specified by waveIntVectors, w_i.
                                            /              /                    /     /      w_i.(x-shifts_[0])    w_i.(y-shifts_[1])    w_i.(z-shifts_[2])            \  \  \ \
u = prefactor[atomType] externalParameter tanh | clipParameter| Sum Prefactor_[i] | cos | 2 pi ---------------— + ---------------— + ---------------— + phase_i | | | | \ \ i \ \ Lx Ly Lz / / / /
Prefactor (which depends on the atomType), externalParameter, waveIntVectors, interfaceWidth and periodicity are given as inputs in the parameter file. ClipParameter is the inverse of 2*pi*periodicity*interfaceWidth.
Definition at line 37 of file GeneralPeriodicExternal.h.
#include <GeneralPeriodicExternal.h>
Public Member Functions
GeneralPeriodicExternal ()
Default constructor.
GeneralPeriodicExternal (const GeneralPeriodicExternal &other)
Copy constructor.
GeneralPeriodicExternal & operator= (const GeneralPeriodicExternal &other)
Assignment.
void setNAtomType (int nAtomType)
Set nAtomType value.
void setExternalParameter (double externalParameter)
Sets external parameter.
void setBoundary (Boundary &boundary)
Set pointer to Boundary.
void readParameters (std::istream &in)
Read potential parameters, and initialize other variables.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
double externalParameter () const
Returns external parameter.
double energy (const Vector &position, int i) const
Returns external potential energy of a single particle.
void getForce (const Vector &position, int type, Vector &force) const
Returns force caused by the external potential.
std::string className () const
Return name string "GeneralPeriodicExternal".
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Constructor & Destructor Documentation
Inter::GeneralPeriodicExternal::GeneralPeriodicExternal ()
Default constructor.
Definition at line 20 of file GeneralPeriodicExternal.cpp.
References Util::ParamComposite::setClassName().
Inter::GeneralPeriodicExternal::GeneralPeriodicExternal (const GeneralPeriodicExternal & other)
Copy constructor.
Definition at line 33 of file GeneralPeriodicExternal.cpp.
References Util::DArray< Data >::allocate(), and Util::Dimension.
Member Function Documentation
GeneralPeriodicExternal & Inter::GeneralPeriodicExternal::operator= (const GeneralPeriodicExternal & other)
Assignment.
Definition at line 65 of file GeneralPeriodicExternal.cpp.
References Util::Dimension.
void Inter::GeneralPeriodicExternal::setNAtomType (int nAtomType)
Set nAtomType value.
Parameters
nAtomType number of atom types.
Definition at line 94 of file GeneralPeriodicExternal.cpp.
References UTIL_THROW.
void Inter::GeneralPeriodicExternal::setExternalParameter (double externalParameter)
Sets external parameter.
Parameters
externalParameter external parameter of system
Definition at line 105 of file GeneralPeriodicExternal.cpp.
References externalParameter(), and UTIL_THROW.
void Inter::GeneralPeriodicExternal::setBoundary (Boundary & boundary)
Set pointer to Boundary.
Parameters
boundary Boundary object (used to calculate length along perpendicular direction).
Definition at line 119 of file GeneralPeriodicExternal.cpp.
void Inter::GeneralPeriodicExternal::readParameters (std::istream & in) virtual
Read potential parameters, and initialize other variables.
Precondition
nAtomType must have been set, by calling setNAtomType().
Boundary must have been set, by calling setBoundary().
Parameters
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 125 of file GeneralPeriodicExternal.cpp.
References Util::DArray< Data >::allocate(), Util::Dimension, and UTIL_THROW.
void Inter::GeneralPeriodicExternal::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 160 of file GeneralPeriodicExternal.cpp.
References Util::DArray< Data >::allocate(), Util::Dimension, and UTIL_THROW.
void Inter::GeneralPeriodicExternal::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 189 of file GeneralPeriodicExternal.cpp.
double Inter::GeneralPeriodicExternal::externalParameter () const
Returns external parameter.
Returns
external parameter
Definition at line 239 of file GeneralPeriodicExternal.cpp.
Referenced by setExternalParameter().
double Inter::GeneralPeriodicExternal::energy (const Vector & position, int i) const inline
Returns external potential energy of a single particle.
Parameters
position atomic position Vector
i atom type.
Returns
external potential energy
Definition at line 187 of file GeneralPeriodicExternal.h.
References Util::Dimension, Util::Vector::dot(), and Util::Vector::zero().
void Inter::GeneralPeriodicExternal::getForce (const Vector & position, int type, Vector & force) const inline
Returns force caused by the external potential.
Parameters
position atom position
type atom type id
force force on the atom (on output)
Definition at line 218 of file GeneralPeriodicExternal.h.
References Util::Dimension, Util::Vector::dot(), and Util::Vector::zero().
std::string Inter::GeneralPeriodicExternal::className () const
Return name string "GeneralPeriodicExternal".
Definition at line 247 of file GeneralPeriodicExternal.cpp.
The documentation for this class was generated from the following files:
GeneralPeriodicExternal.h
GeneralPeriodicExternal.cpp