Simpatico: McMd::DdMdTrajectoryReader Class Reference
McMd::DdMdTrajectoryReader Class Reference
Detailed Description
TrajectoryReader for a DdMd trajectory file.
This class assumes that atom tags are ordered by molecule and species, with consecutive ids for atoms in the same molecule and consecutive blocks for molecules in the same species.
Definition at line 31 of file mcMd/trajectory/DdMdTrajectoryReader.h.
#include <DdMdTrajectoryReader.h>
Public Member Functions
DdMdTrajectoryReader (System &system)
Constructor.
virtual ~DdMdTrajectoryReader ()
Destructor.
void open (std::string filename)
Open trajectory file, read header, and allocate memory.
bool readFrame ()
Read a single frame.
void close ()
Close trajectory file.
Public Member Functions inherited from McMd::TrajectoryReader
TrajectoryReader (System &system)
Constructor.
virtual ~TrajectoryReader ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from McMd::TrajectoryReader
System & system () const
Get a reference to the parent System.
Simulation & simulation () const
Get a reference to the parent Simulation.
Boundary & boundary () const
Get the Boundary.
virtual void addMolecules ()
Add all molecules to system.
Protected Attributes inherited from McMd::TrajectoryReader
int nAtomTotal_
Total number of atoms (all species)
Constructor & Destructor Documentation
McMd::DdMdTrajectoryReader::DdMdTrajectoryReader (System & system)
Constructor.
Definition at line 29 of file mcMd/trajectory/DdMdTrajectoryReader.cpp.
McMd::DdMdTrajectoryReader::~DdMdTrajectoryReader () virtual
Destructor.
Definition at line 36 of file mcMd/trajectory/DdMdTrajectoryReader.cpp.
Member Function Documentation
void McMd::DdMdTrajectoryReader::open (std::string filename) virtual
Open trajectory file, read header, and allocate memory.
Parameters
filename trajectory file name
Implements McMd::TrajectoryReader.
Definition at line 42 of file mcMd/trajectory/DdMdTrajectoryReader.cpp.
References McMd::TrajectoryReader::addMolecules(), McMd::TrajectoryReader::nAtomTotal_, and UTIL_THROW.
bool McMd::DdMdTrajectoryReader::readFrame () virtual
Read a single frame.
Frames are assumed to be read consecutively.
Returns
true if this frame is available, false if end of file
Implements McMd::TrajectoryReader.
Definition at line 76 of file mcMd/trajectory/DdMdTrajectoryReader.cpp.
References McMd::Molecule::begin(), McMd::TrajectoryReader::boundary(), McMd::Species::capacity(), Util::Dimension, McMd::System::molecule(), McMd::TrajectoryReader::nAtomTotal_, Util::ArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), McMd::TrajectoryReader::simulation(), McMd::Simulation::species(), McMd::TrajectoryReader::system(), Util::OrthorhombicBoundary::transformGenToCart(), and UTIL_THROW.
void McMd::DdMdTrajectoryReader::close () virtual
Close trajectory file.
Implements McMd::TrajectoryReader.
Definition at line 134 of file mcMd/trajectory/DdMdTrajectoryReader.cpp.
The documentation for this class was generated from the following files:
mcMd/trajectory/DdMdTrajectoryReader.h
mcMd/trajectory/DdMdTrajectoryReader.cpp