Simpatico: Util::Begin Class Reference
Util::Begin Class Reference
Parameter File IO
Detailed Description
Beginning line of a composite parameter block.
Definition at line 23 of file Begin.h.
#include <Begin.h>
Public Member Functions
Begin (const char *label)
Constructor.
virtual void readParam (std::istream &in)
Read a comment.
virtual void writeParam (std::ostream &out)
Read a comment.
std::string string ()
Return comment string.
virtual void resetParam ()
Do-nothing implementation of virtual resetParam function.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
virtual void load (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have a communicator?
MPI::Intracomm & ioCommunicator () const
Get the communicator.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Constructor & Destructor Documentation
Util::Begin::Begin (const char * label)
Constructor.
Definition at line 20 of file Begin.cpp.
Member Function Documentation
void Util::Begin::readParam (std::istream & in) virtual
Read a comment.
Parameters
in input stream
Implements Util::ParamComponent.
Definition at line 27 of file Begin.cpp.
References Util::ParamComponent::echo(), Util::Log::file(), Util::MpiFileIo::isIoProcessor(), UTIL_THROW, and writeParam().
Referenced by Util::ParamComposite::readBegin().
void Util::Begin::writeParam (std::ostream & out) virtual
Read a comment.
Parameters
out output stream
Implements Util::ParamComponent.
Definition at line 53 of file Begin.cpp.
References Util::ParamComponent::indent().
Referenced by Util::ParamComposite::load(), Util::Factory< Data >::readObject(), and readParam().
std::string Util::Begin::string () inline
Return comment string.
Definition at line 69 of file Begin.h.
void Util::Begin::resetParam () virtual
Do-nothing implementation of virtual resetParam function.
Reimplemented from Util::ParamComponent.
Definition at line 61 of file Begin.cpp.
The documentation for this class was generated from the following files:
Begin.h
Begin.cpp