Simpatico: McMd::Molecule Class Reference
McMd::Molecule Class Reference
McMd namespace » Chemical Structure
Detailed Description
A physical molecule (a set of covalently bonded Atoms).
Definition at line 38 of file mcMd/chemistry/Molecule.h.
#include <Molecule.h>
Public Types
typedef ArrayIterator< Atom > AtomIterator
Iterator for Atoms within a Molecule.
typedef ConstArrayIterator< Atom > ConstAtomIterator
Iterator for const Atoms within a Molecule.
typedef ArrayIterator< Bond > BondIterator
Iterator for Bonds within a Molecule.
typedef ConstArrayIterator< Bond > ConstBondIterator
Iterator for const Bonds within a Molecule.
typedef ArrayIterator< Angle > AngleIterator
Iterator for Angles within a Molecule.
typedef ConstArrayIterator< Angle > ConstAngleIterator
Iterator for const Angles within a Molecule.
typedef ArrayIterator< Dihedral > DihedralIterator
Iterator for Dihedrals within a Molecule.
typedef ConstArrayIterator< Dihedral > ConstDihedralIterator
Iterator for const Dihedrals within a Molecule.
Public Member Functions
Molecule ()
Constructor.
Mutators
void setSpecies (Species &species)
Set the parent Species.
void setSystem (System &system)
Set the parent System.
void unsetSystem ()
Set the parent System pointer to null (no System).
void setId (int id)
Set the integer index for this molecule.
void setFirstAtom (Atom &atom)
Set the first Atom.
void setNAtom (int nAtom)
Set the number of Atoms per molecule.
void setFirstBond (Bond &bond)
Set the first Bond.
void setNBond (int nBond)
Set the number of Bonds per molecule.
void setFirstAngle (Angle &angle)
Set the first Angle.
void setNAngle (int nAngle)
Set the number of Angles per molecule.
void setFirstDihedral (Dihedral &dihedral)
Set the first Dihedral.
void setNDihedral (int nDihedral)
Set the number of Dihedrals per molecule.
Accessors
Species & species () const
Get the molecular Species by reference.
System & system () const
Get the parent System.
int id () const
Get the index for this Molecule (unique in species).
int nAtom () const
Get the number of Atoms in this Molecule.
int nBond () const
Get the number of Bonds in this Molecule.
int nAngle () const
Get the number of Angles in this Molecule.
int nDihedral () const
Get the number of Dihedrals in this Molecule.
const Atom & atom (int localId) const
Get a specific Atom in this Molecule.
Atom & atom (int localId)
Get a specific Atom in this Molecule.
Bond & bond (int localId)
Get a specific Bond in this Molecule by non-const reference.
const Bond & bond (int localId) const
Get a specific Bond in this Molecule by const reference.
Angle & angle (int localId)
Get a specific Angle in this Molecule by non-const reference.
const Angle & angle (int localId) const
Get a specific Angle in this Molecule by const reference.
Dihedral & dihedral (int localId)
Get a specific Dihedral in this Molecule by reference.
const Dihedral & dihedral (int localId) const
Get a specific Dihedral in this Molecule by const reference.
Iterator Interface
void begin (AtomIterator &iterator)
Set an Molecule::AtomIterator to first Atom in this Molecule.
void begin (ConstAtomIterator &iterator) const
Set an Molecule::ConstAtomIterator to first Atom in this Molecule.
void begin (BondIterator &iterator)
Set a Molecule::BondIterator to first Bond in this Molecule.
void begin (ConstBondIterator &iterator) const
Set a Molecule::ConstBondIterator to first Bond in this Molecule.
void begin (AngleIterator &iterator)
Set a Molecule::AngleIterator to first Angle in this Molecule.
void begin (ConstAngleIterator &iterator) const
Set a Molecule::ConstAngleIterator to first Angle in this Molecule.
void begin (DihedralIterator &iterator)
Set a Molecule::DihedralIterator to first Dihedral in this Molecule.
void begin (ConstDihedralIterator &iterator) const
Set a Molecule::ConstDihedralIterator to first Dihedral in this Molecule.
Static Public Attributes
static const int NullIndex = -1
Null value for molecule id.
Member Typedef Documentation
typedef ArrayIterator<Atom> McMd::Molecule::AtomIterator
Iterator for Atoms within a Molecule.
Definition at line 46 of file mcMd/chemistry/Molecule.h.
typedef ConstArrayIterator<Atom> McMd::Molecule::ConstAtomIterator
Iterator for const Atoms within a Molecule.
Definition at line 49 of file mcMd/chemistry/Molecule.h.
typedef ArrayIterator<Bond> McMd::Molecule::BondIterator
Iterator for Bonds within a Molecule.
Definition at line 53 of file mcMd/chemistry/Molecule.h.
typedef ConstArrayIterator<Bond> McMd::Molecule::ConstBondIterator
Iterator for const Bonds within a Molecule.
Definition at line 56 of file mcMd/chemistry/Molecule.h.
typedef ArrayIterator<Angle> McMd::Molecule::AngleIterator
Iterator for Angles within a Molecule.
Definition at line 61 of file mcMd/chemistry/Molecule.h.
typedef ConstArrayIterator<Angle> McMd::Molecule::ConstAngleIterator
Iterator for const Angles within a Molecule.
Definition at line 64 of file mcMd/chemistry/Molecule.h.
typedef ArrayIterator<Dihedral> McMd::Molecule::DihedralIterator
Iterator for Dihedrals within a Molecule.
Definition at line 69 of file mcMd/chemistry/Molecule.h.
typedef ConstArrayIterator<Dihedral> McMd::Molecule::ConstDihedralIterator
Iterator for const Dihedrals within a Molecule.
Definition at line 72 of file mcMd/chemistry/Molecule.h.
Constructor & Destructor Documentation
McMd::Molecule::Molecule ()
Constructor.
Definition at line 21 of file mcMd/chemistry/Molecule.cpp.
Member Function Documentation
void McMd::Molecule::setSpecies (Species & species) inline
Set the parent Species.
Parameters
species parent Species object.
Definition at line 656 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::Simulation::save().
void McMd::Molecule::setSystem (System & system) inline
Set the parent System.
Parameters
system parent System object.
Definition at line 662 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::System::addMolecule().
void McMd::Molecule::unsetSystem () inline
Set the parent System pointer to null (no System).
Definition at line 668 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::System::removeMolecule().
void McMd::Molecule::setId (int id) inline
Set the integer index for this molecule.
Parameters
id integer array index.
Definition at line 728 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::Simulation::save().
void McMd::Molecule::setFirstAtom (Atom & atom) inline
Set the first Atom.
Parameters
atom first Atom in molecule.
Definition at line 674 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::Simulation::save().
void McMd::Molecule::setNAtom (int nAtom) inline
Set the number of Atoms per molecule.
Parameters
nAtom number of Atoms in the molecule.
Definition at line 680 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::Simulation::save().
void McMd::Molecule::setFirstBond (Bond & bond) inline
Set the first Bond.
Parameters
bond first Bond in molecule.
Definition at line 687 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::Simulation::save().
void McMd::Molecule::setNBond (int nBond) inline
Set the number of Bonds per molecule.
Parameters
nBond number of Bonds in the molecule.
Definition at line 693 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::Simulation::save().
void McMd::Molecule::setFirstAngle (Angle & angle) inline
Set the first Angle.
Parameters
angle first Angle in molecule.
Definition at line 701 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::Simulation::save().
void McMd::Molecule::setNAngle (int nAngle) inline
Set the number of Angles per molecule.
Parameters
nAngle number of Angles in molecule.
Definition at line 707 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::Simulation::save().
void McMd::Molecule::setFirstDihedral (Dihedral & dihedral) inline
Set the first Dihedral.
Parameters
dihedral first Dihedral in molecule.
Definition at line 715 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::Simulation::save().
void McMd::Molecule::setNDihedral (int nDihedral) inline
Set the number of Dihedrals per molecule.
Parameters
nDihedral number of Dihedrals in molecule.
Definition at line 721 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::Simulation::save().
Species & McMd::Molecule::species () const inline
Get the molecular Species by reference.
Definition at line 414 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::CfbLinear::addAtom(), McMd::System::addMolecule(), McMd::Activate::deactivate(), McMd::getAtomAngles(), McMd::getAtomBonds(), McMd::getAtomDihedrals(), McMd::Simulation::isValid(), McMd::System::moleculeId(), McMd::Activate::reactivate(), McMd::System::removeMolecule(), McMd::Simulation::returnMolecule(), McMd::MdPairEnergyCoefficients::sample(), McMd::RingOctaRebridgeMove::scanBridge(), and McMd::McMdConfigIo::write().
System & McMd::Molecule::system () const inline
Get the parent System.
Definition at line 423 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::System::isValid(), and McMd::System::removeMolecule().
int McMd::Molecule::id () const inline
Get the index for this Molecule (unique in species).
Definition at line 556 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::ClusterIdentifier::initialize(), McMd::Simulation::isValid(), McMd::SpeciesMutator::moleculeStateId(), McMd::CfbReptationMove::move(), McMd::CfbReptateMove::move(), McMd::MdPairEnergyCoefficients::sample(), McMd::RingOctaRebridgeMove::scanBridge(), and McMd::SpeciesMutator::setMoleculeStateId().
int McMd::Molecule::nAtom () const inline
Get the number of Atoms in this Molecule.
Definition at line 432 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::Activate::activate(), McMd::CfbLinear::addAtom(), McMd::CfbLinear::deleteAtom(), McMd::McPairPotentialImpl< Interaction >::moleculeEnergy(), McMd::CfbDoubleRebridgeMove::move(), McMd::CfbEndMove::move(), McMd::AtomDisplaceMove::move(), McMd::CfbRebridgeMove::move(), McMd::RingOctaRebridgeMove::move(), McMd::CfbLinearEndMove::move(), McMd::CfbReptationMove::move(), McMd::EndSwapMove::move(), McMd::CfbRingRebridgeMove::move(), McMd::CfbReptateMove::move(), McMd::Activate::reactivate(), McMd::McMdConfigIo::read(), McMd::McNVTChemicalPotential::sample(), McMd::RingOctaRebridgeMove::scanBridge(), and McMd::HomopolymerSG::setMoleculeState().
int McMd::Molecule::nBond () const inline
Get the number of Bonds in this Molecule.
Definition at line 439 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::Activate::activate(), McMd::getAtomBonds(), and McMd::Simulation::isValid().
int McMd::Molecule::nAngle () const inline
Get the number of Angles in this Molecule.
Definition at line 447 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::Activate::activate(), McMd::getAtomAngles(), and McMd::Simulation::isValid().
int McMd::Molecule::nDihedral () const inline
Get the number of Dihedrals in this Molecule.
Definition at line 455 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::Activate::activate(), McMd::getAtomDihedrals(), and McMd::Simulation::isValid().
const Atom & McMd::Molecule::atom (int localId) const inline
Get a specific Atom in this Molecule.
Returns the atom with local integer index 0 <= localId < nAtom.
Parameters
localId local index of desired atom within this Molecule.
Definition at line 473 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::Activate::activate(), McMd::PointGenerator::attemptPlaceMolecule(), McMd::LinearGenerator::attemptPlaceMolecule(), McMd::Activate::deactivate(), McMd::CfbLinear::deleteAtom(), McMd::getAtomAngles(), McMd::getAtomBonds(), McMd::getAtomDihedrals(), McMd::Simulation::isValid(), McMd::McNVTChemicalPotential::load(), McMd::McPairPotentialImpl< Interaction >::moleculeEnergy(), McMd::RingTetraRebridgeMove::move(), McMd::CfbDoubleRebridgeMove::move(), McMd::CfbEndMove::move(), McMd::AtomDisplaceMove::move(), McMd::CfbRebridgeMove::move(), McMd::RingOctaRebridgeMove::move(), McMd::CfbLinearEndMove::move(), McMd::EndSwapMove::move(), McMd::CfbReptationMove::move(), McMd::CfbRingRebridgeMove::move(), McMd::CfbReptateMove::move(), McMd::RigidDisplaceMove::move(), McMd::ComMSD::output(), McMd::Activate::reactivate(), McMd::McMdConfigIo::read(), McMd::McNVTChemicalPotential::sample(), McMd::AtomMSD::sample(), McMd::ComMSD::sample(), McMd::RingRouseAutoCorr::sample(), McMd::LinearRouseAutoCorr::sample(), McMd::BlockRadiusGyration::sample(), McMd::IntraPairAutoCorr::sample(), McMd::RadiusGyration::sample(), McMd::Simulation::save(), McMd::RingOctaRebridgeMove::scanBridge(), McMd::RingTetraRebridgeMove::scanBridge(), McMd::HomopolymerSG::setMoleculeState(), McMd::AtomMSD::setup(), and McMd::ComMSD::setup().
Atom & McMd::Molecule::atom (int localId) inline
Get a specific Atom in this Molecule.
Returns the atom with local integer index 0 <= localId < nAtom.
Parameters
localId local index of desired atom within this Molecule.
Definition at line 462 of file mcMd/chemistry/Molecule.h.
Bond & McMd::Molecule::bond (int localId) inline
Get a specific Bond in this Molecule by non-const reference.
Returns the bond with local integer index 0 <= localId < nBond.
Parameters
localId local index of desired bond within this Molecule.
Definition at line 485 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::Activate::activate(), McMd::CfbLinear::addAtom(), McMd::Activate::deactivate(), McMd::CfbLinear::deleteAtom(), McMd::getAtomBonds(), McMd::Simulation::isValid(), McMd::McNVTChemicalPotential::load(), McMd::RingTetraRebridgeMove::move(), McMd::CfbDoubleRebridgeMove::move(), McMd::CfbEndMove::move(), McMd::CfbRebridgeMove::move(), McMd::CfbRingRebridgeMove::move(), McMd::Activate::reactivate(), and McMd::McNVTChemicalPotential::sample().
const Bond & McMd::Molecule::bond (int localId) const inline
Get a specific Bond in this Molecule by const reference.
Returns the bond with local integer index 0 <= localId < nBond.
Parameters
localId local index of desired bond within this Molecule.
Definition at line 496 of file mcMd/chemistry/Molecule.h.
Angle & McMd::Molecule::angle (int localId) inline
Get a specific Angle in this Molecule by non-const reference.
Returns the angle with local integer index 0 <= localId < nAngle.
Parameters
localId local index of desired angle within this Molecule.
Definition at line 509 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::Activate::activate(), McMd::Activate::deactivate(), McMd::getAtomAngles(), McMd::Simulation::isValid(), McMd::McNVTChemicalPotential::load(), McMd::Activate::reactivate(), and McMd::McNVTChemicalPotential::sample().
const Angle & McMd::Molecule::angle (int localId) const inline
Get a specific Angle in this Molecule by const reference.
Returns the angle with local integer index 0 <= localId < nAngle.
Parameters
localId local index of desired angle within this Molecule.
Definition at line 520 of file mcMd/chemistry/Molecule.h.
Dihedral & McMd::Molecule::dihedral (int localId) inline
Get a specific Dihedral in this Molecule by reference.
Returns the dihedral with local integer index 0 <= localId < nDihedral.
Parameters
localId local index of desired dihedral within this Molecule.
Definition at line 533 of file mcMd/chemistry/Molecule.h.
Referenced by McMd::Activate::activate(), McMd::Activate::deactivate(), McMd::getAtomDihedrals(), McMd::Simulation::isValid(), McMd::McNVTChemicalPotential::load(), and McMd::Activate::reactivate().
const Dihedral & McMd::Molecule::dihedral (int localId) const inline
Get a specific Dihedral in this Molecule by const reference.
Returns the dihedral with local integer index 0 <= localId < nDihedral.
Parameters
localId local index of desired dihedral within this Molecule.
Definition at line 544 of file mcMd/chemistry/Molecule.h.
void McMd::Molecule::begin (AtomIterator & iterator) inline
Set an Molecule::AtomIterator to first Atom in this Molecule.
Parameters
iterator on output, points to first Atom.
Definition at line 562 of file mcMd/chemistry/Molecule.h.
References Util::ArrayIterator< Data >::setCurrent(), and Util::ArrayIterator< Data >::setEnd().
Referenced by McMd::ClusterIdentifier::initialize(), McMd::System::loadConfig(), McMd::McMdConfigIo::read(), McMd::DdMdConfigIo::read(), McMd::LammpsConfigIo::read(), McMd::LammpsDumpReader::readFrame(), McMd::DdMdTrajectoryReader::readFrame(), and McMd::DCDTrajectoryReader::readFrame().
void McMd::Molecule::begin (ConstAtomIterator & iterator) const inline
Set an Molecule::ConstAtomIterator to first Atom in this Molecule.
Parameters
iterator on output, points to first Atom.
Definition at line 573 of file mcMd/chemistry/Molecule.h.
References Util::ConstArrayIterator< Data >::setCurrent(), and Util::ConstArrayIterator< Data >::setEnd().
void McMd::Molecule::begin (BondIterator & iterator) inline
Set a Molecule::BondIterator to first Bond in this Molecule.
Parameters
iterator on output, points to first Bond.
Definition at line 585 of file mcMd/chemistry/Molecule.h.
References Util::ArrayIterator< Data >::setCurrent(), and Util::ArrayIterator< Data >::setEnd().
void McMd::Molecule::begin (ConstBondIterator & iterator) const inline
Set a Molecule::ConstBondIterator to first Bond in this Molecule.
Parameters
iterator on output, points to first Bond.
Definition at line 596 of file mcMd/chemistry/Molecule.h.
References Util::ConstArrayIterator< Data >::setCurrent(), and Util::ConstArrayIterator< Data >::setEnd().
void McMd::Molecule::begin (AngleIterator & iterator) inline
Set a Molecule::AngleIterator to first Angle in this Molecule.
Parameters
iterator on output, points to first Angle.
Definition at line 609 of file mcMd/chemistry/Molecule.h.
References Util::ArrayIterator< Data >::setCurrent(), and Util::ArrayIterator< Data >::setEnd().
void McMd::Molecule::begin (ConstAngleIterator & iterator) const inline
Set a Molecule::ConstAngleIterator to first Angle in this Molecule.
Parameters
iterator on output, points to first Angle.
Definition at line 620 of file mcMd/chemistry/Molecule.h.
References Util::ConstArrayIterator< Data >::setCurrent(), and Util::ConstArrayIterator< Data >::setEnd().
void McMd::Molecule::begin (DihedralIterator & iterator) inline
Set a Molecule::DihedralIterator to first Dihedral in this Molecule.
Parameters
iterator on output, points to first Dihedral.
Definition at line 633 of file mcMd/chemistry/Molecule.h.
References Util::ArrayIterator< Data >::setCurrent(), and Util::ArrayIterator< Data >::setEnd().
void McMd::Molecule::begin (ConstDihedralIterator & iterator) const inline
Set a Molecule::ConstDihedralIterator to first Dihedral in this Molecule.
Parameters
iterator on output, points to first Dihedral.
Definition at line 644 of file mcMd/chemistry/Molecule.h.
References Util::ConstArrayIterator< Data >::setCurrent(), and Util::ConstArrayIterator< Data >::setEnd().
Member Data Documentation
const int McMd::Molecule::NullIndex = -1 static
Null value for molecule id.
Definition at line 76 of file mcMd/chemistry/Molecule.h.
The documentation for this class was generated from the following files:
mcMd/chemistry/Molecule.h
mcMd/chemistry/Molecule.cpp