Simpatico: McMd::EndSwapMove Class Reference
McMd::EndSwapMove Class Reference
Monte Carlo Moves
Detailed Description
A move that swaps the ends of a linear hetero-polymer.
This move changes the energy if of a linear heteropolymer by reversing the sequence of atom types. When applied to a diblock copolymer, is swaps the A and B blocks. It is pointless if applied to a homopolymer, or to a symmetric ABA triblock.
See also:
param file format
Definition at line 35 of file EndSwapMove.h.
#include <EndSwapMove.h>
Public Member Functions
EndSwapMove (McSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read species to which displacement is applied.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual bool move ()
Generate and accept or reject configuration bias move.
Protected Attributes
int speciesId_
Integer index for molecular species.
DArray< int > atomTypeIds_
Array of atom type indices.
DArray< Vector > positions_
Array of atomic positions (temporary).
Constructor & Destructor Documentation
McMd::EndSwapMove::EndSwapMove (McSystem & system)
Constructor.
Definition at line 27 of file EndSwapMove.cpp.
References McMd::McSystem::hasAnglePotential(), McMd::McSystem::hasDihedralPotential(), Util::ParamComposite::setClassName(), and UTIL_THROW.
Member Function Documentation
void McMd::EndSwapMove::readParameters (std::istream & in) [virtual]
Read species to which displacement is applied.
Reimplemented from McMd::McMove.
Definition at line 54 of file EndSwapMove.cpp.
References Util::DArray< Data >::allocate(), atomTypeIds_, McMd::Species::nAtom(), positions_, McMd::McMove::readProbability(), McMd::McMove::simulation(), McMd::Simulation::species(), speciesId_, and UTIL_THROW.
void McMd::EndSwapMove::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::McMove.
Definition at line 84 of file EndSwapMove.cpp.
References Util::DArray< Data >::allocate(), atomTypeIds_, McMd::Species::isMutable(), McMd::Species::nAtom(), positions_, McMd::McMove::simulation(), McMd::Simulation::species(), speciesId_, and UTIL_THROW.
void McMd::EndSwapMove::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::McMove.
Definition at line 110 of file EndSwapMove.cpp.
References atomTypeIds_, and speciesId_.
bool McMd::EndSwapMove::move () [virtual]
Generate and accept or reject configuration bias move.
Reimplemented from McMd::McMove.
Definition at line 120 of file EndSwapMove.cpp.
References McMd::Molecule::atom(), McMd::ExternalPotential::atomEnergy(), atomTypeIds_, McMd::SystemMove::boltzmann(), McMd::McSystem::externalPotential(), McMd::McMove::incrementNAccept(), McMd::McMove::incrementNAttempt(), Util::Random::metropolis(), McMd::McPairPotential::moleculeEnergy(), McMd::Molecule::nAtom(), McMd::McSystem::pairPotential(), McMd::Atom::position(), positions_, McMd::McMove::random(), McMd::System::randomMolecule(), McMd::Atom::setTypeId(), speciesId_, McMd::SystemMove::system(), McMd::Atom::typeId(), and McMd::McPairPotential::updateAtomCell().
Member Data Documentation
int McMd::EndSwapMove::speciesId_ [protected]
Integer index for molecular species.
Definition at line 72 of file EndSwapMove.h.
Referenced by loadParameters(), move(), readParameters(), and save().
DArray<int> McMd::EndSwapMove::atomTypeIds_ [protected]
Array of atom type indices.
Definition at line 75 of file EndSwapMove.h.
Referenced by loadParameters(), move(), readParameters(), and save().
DArray<Vector> McMd::EndSwapMove::positions_ [protected]
Array of atomic positions (temporary).
Definition at line 78 of file EndSwapMove.h.
Referenced by loadParameters(), move(), and readParameters().
The documentation for this class was generated from the following files:
EndSwapMove.h
EndSwapMove.cpp