Simpatico: McMd::StructureFactor Class Reference
McMd::StructureFactor Class Reference
MC/MD Analyzers
Detailed Description
StructureFactor evaluates structure factors in Fourier space.
A structure factor for a wavevector k and mode m defined as an expectation value
where, V is system volume, and is a Fourier component
in which the sum is taken over all particles, a is the atom type of particle i, and v(m, a) is a coefficient for atom type a for mode m. The matrix v(m, a) of mode coefficients is input by the user.
This class can evaluate one or modes for multiple wavevectors. The input format thus requires the user to specify one or more mode vectors, and one or more wavevectors. Each wavevector is specified as an IntVector containing the integer Miller indices of a reciprocal lattice vector. These are the coeficients in an expansion of a reciprocal lattice wavevector as a sum of recprocal lattice basis vectors for the periodic unit cell.
See also:
parameter file format
Definition at line 55 of file mcMd/analyzers/system/StructureFactor.h.
#include <StructureFactor.h>
Public Member Functions
StructureFactor (System &system)
Constructor.
~StructureFactor ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Clear accumulators.
virtual void sample (long iStep)
Add particles to StructureFactor accumulators.
virtual void output ()
Output results to predefined output file.
Protected Member Functions
void makeWaveVectors ()
Update wavevectors.
Protected Attributes
std::ofstream outputFile_
Output file stream.
DMatrix< double > structureFactors_
Structure factor accumulators.
DMatrix< std::complex< double > > fourierModes_
Instantaneous Fourier amplitudes (temporary)
DArray< IntVector > waveIntVectors_
Array of Miller index IntVectors for wavevectors.
DArray< Vector > waveVectors_
Array of floating point wave vectors (temporary).
DMatrix< double > modes_
Array of mode vectors.
int nWave_
Number of wavevectors.
int nMode_
Number of mode vectors.
int nSample_
Number of samples thus far.
int nAtomType_
Number of atom types, copied from Simulation::nAtomType().
bool isFirstStep_
Is this the first step?
Constructor & Destructor Documentation
McMd::StructureFactor::StructureFactor (System & system)
Constructor.
Parameters:
system reference to parent System object
Definition at line 30 of file mcMd/analyzers/system/StructureFactor.cpp.
References Util::ParamComposite::setClassName().
McMd::StructureFactor::~StructureFactor ()
Destructor.
Definition at line 39 of file mcMd/analyzers/system/StructureFactor.cpp.
Member Function Documentation
void McMd::StructureFactor::readParameters (std::istream & in) [virtual]
Read parameters from file.
Parameters:
in input parameter stream
Reimplemented from McMd::Analyzer.
Reimplemented in McMd::StructureFactorGrid.
Definition at line 45 of file mcMd/analyzers/system/StructureFactor.cpp.
References Util::DMatrix< Data >::allocate(), Util::DArray< Data >::allocate(), fourierModes_, modes_, McMd::Simulation::nAtomType(), nAtomType_, nMode_, nWave_, McMd::Analyzer::readInterval(), McMd::Analyzer::readOutputFileName(), McMd::System::simulation(), structureFactors_, McMd::SystemAnalyzer< System >::system(), waveIntVectors_, and waveVectors_.
void McMd::StructureFactor::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from McMd::Analyzer.
Reimplemented in McMd::StructureFactorGrid.
Definition at line 67 of file mcMd/analyzers/system/StructureFactor.cpp.
References Util::DMatrix< Data >::allocate(), Util::DArray< Data >::allocate(), fourierModes_, modes_, McMd::Simulation::nAtomType(), nAtomType_, nMode_, nSample_, nWave_, McMd::System::simulation(), structureFactors_, McMd::SystemAnalyzer< System >::system(), UTIL_THROW, waveIntVectors_, and waveVectors_.
void McMd::StructureFactor::save (Serializable::OArchive & ar) [virtual]
Save state to archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::Analyzer.
Reimplemented in McMd::StructureFactorGrid.
Definition at line 102 of file mcMd/analyzers/system/StructureFactor.cpp.
template<class Archive > void McMd::StructureFactor::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Analyzer.
Reimplemented in McMd::StructureFactorGrid.
Definition at line 187 of file mcMd/analyzers/system/StructureFactor.h.
References McMd::serialize().
void McMd::StructureFactor::setup () [virtual]
Clear accumulators.
Reimplemented from McMd::Analyzer.
Reimplemented in McMd::StructureFactorGrid.
Definition at line 108 of file mcMd/analyzers/system/StructureFactor.cpp.
References nMode_, nSample_, nWave_, structureFactors_, and UTIL_THROW.
void McMd::StructureFactor::sample (long iStep) [virtual]
Add particles to StructureFactor accumulators.
Parameters:
iStep step counter
Implements McMd::Analyzer.
Reimplemented in McMd::StructureFactorGrid.
Definition at line 129 of file mcMd/analyzers/system/StructureFactor.cpp.
References McMd::System::begin(), McMd::System::boundary(), Util::Vector::dot(), McMd::Analyzer::fileMaster(), fourierModes_, Util::Constants::Im, McMd::Analyzer::isAtInterval(), isFirstStep_, makeWaveVectors(), modes_, nMode_, Util::ConstArrayIterator< Data >::notEnd(), Util::ConstPArrayIterator< Data >::notEnd(), nSample_, McMd::Simulation::nSpecies(), nWave_, Util::FileMaster::openOutputFile(), outputFile_, McMd::Analyzer::outputFileName(), Util::product(), McMd::System::simulation(), structureFactors_, McMd::SystemAnalyzer< System >::system(), Util::OrthorhombicBoundary::volume(), waveIntVectors_, and waveVectors_.
void McMd::StructureFactor::output () [virtual]
Output results to predefined output file.
Reimplemented from McMd::Analyzer.
Reimplemented in McMd::StructureFactorGrid.
Definition at line 239 of file mcMd/analyzers/system/StructureFactor.cpp.
References Util::Dimension, McMd::Analyzer::fileMaster(), nMode_, nSample_, nWave_, Util::FileMaster::openOutputFile(), outputFile_, McMd::Analyzer::outputFileName(), structureFactors_, Util::toString(), waveIntVectors_, waveVectors_, and Util::ParamComposite::writeParam().
void McMd::StructureFactor::makeWaveVectors () [protected]
Update wavevectors.
Definition at line 221 of file mcMd/analyzers/system/StructureFactor.cpp.
References McMd::System::boundary(), Util::Dimension, nWave_, Util::OrthorhombicBoundary::reciprocalBasisVector(), McMd::SystemAnalyzer< System >::system(), waveIntVectors_, waveVectors_, and Util::Vector::Zero.
Referenced by sample().
Member Data Documentation
std::ofstream McMd::StructureFactor::outputFile_ [protected]
Output file stream.
Definition at line 124 of file mcMd/analyzers/system/StructureFactor.h.
Referenced by output(), McMd::StructureFactorGrid::output(), and sample().
DMatrix<double> McMd::StructureFactor::structureFactors_ [protected]
Structure factor accumulators.
First index is wavevector, second is a mode index.
Definition at line 131 of file mcMd/analyzers/system/StructureFactor.h.
Referenced by loadParameters(), McMd::StructureFactorGrid::loadParameters(), output(), McMd::StructureFactorGrid::output(), readParameters(), McMd::StructureFactorGrid::readParameters(), sample(), and setup().
DMatrix< std::complex<double> > McMd::StructureFactor::fourierModes_ [protected]
Instantaneous Fourier amplitudes (temporary)
First index is wavevector, second is mode index.
Definition at line 138 of file mcMd/analyzers/system/StructureFactor.h.
Referenced by loadParameters(), McMd::StructureFactorGrid::loadParameters(), readParameters(), McMd::StructureFactorGrid::readParameters(), sample(), and McMd::StructureFactorGrid::sample().
DArray<IntVector> McMd::StructureFactor::waveIntVectors_ [protected]
Array of Miller index IntVectors for wavevectors.
Definition at line 143 of file mcMd/analyzers/system/StructureFactor.h.
Referenced by loadParameters(), McMd::StructureFactorGrid::loadParameters(), makeWaveVectors(), output(), McMd::StructureFactorGrid::output(), readParameters(), McMd::StructureFactorGrid::readParameters(), sample(), and McMd::StructureFactorGrid::sample().
DArray<Vector> McMd::StructureFactor::waveVectors_ [protected]
Array of floating point wave vectors (temporary).
Definition at line 148 of file mcMd/analyzers/system/StructureFactor.h.
Referenced by loadParameters(), McMd::StructureFactorGrid::loadParameters(), makeWaveVectors(), output(), McMd::StructureFactorGrid::output(), readParameters(), McMd::StructureFactorGrid::readParameters(), sample(), and McMd::StructureFactorGrid::sample().
DMatrix<double> McMd::StructureFactor::modes_ [protected]
Array of mode vectors.
First index is mode, second is atomType.
Definition at line 155 of file mcMd/analyzers/system/StructureFactor.h.
Referenced by loadParameters(), McMd::StructureFactorGrid::loadParameters(), readParameters(), McMd::StructureFactorGrid::readParameters(), and sample().
int McMd::StructureFactor::nWave_ [protected]
Number of wavevectors.
Definition at line 158 of file mcMd/analyzers/system/StructureFactor.h.
Referenced by loadParameters(), McMd::StructureFactorGrid::loadParameters(), makeWaveVectors(), output(), readParameters(), McMd::StructureFactorGrid::readParameters(), sample(), and setup().
int McMd::StructureFactor::nMode_ [protected]
Number of mode vectors.
Definition at line 161 of file mcMd/analyzers/system/StructureFactor.h.
Referenced by loadParameters(), McMd::StructureFactorGrid::loadParameters(), output(), McMd::StructureFactorGrid::output(), readParameters(), McMd::StructureFactorGrid::readParameters(), sample(), McMd::StructureFactorGrid::sample(), and setup().
int McMd::StructureFactor::nSample_ [protected]
Number of samples thus far.
Definition at line 164 of file mcMd/analyzers/system/StructureFactor.h.
Referenced by loadParameters(), McMd::StructureFactorGrid::loadParameters(), output(), McMd::StructureFactorGrid::output(), McMd::StructureFactorGrid::readParameters(), sample(), and setup().
int McMd::StructureFactor::nAtomType_ [protected]
Number of atom types, copied from Simulation::nAtomType().
Definition at line 167 of file mcMd/analyzers/system/StructureFactor.h.
Referenced by loadParameters(), McMd::StructureFactorGrid::loadParameters(), readParameters(), and McMd::StructureFactorGrid::readParameters().
bool McMd::StructureFactor::isFirstStep_ [protected]
Is this the first step?
Definition at line 175 of file mcMd/analyzers/system/StructureFactor.h.
Referenced by sample(), and McMd::StructureFactorGrid::sample().
The documentation for this class was generated from the following files:
mcMd/analyzers/system/StructureFactor.h
mcMd/analyzers/system/StructureFactor.cpp