Simpatico: McMd::Link Class Reference
McMd::Link Class Reference
Detailed Description
A Link represents a crosslink between two Atoms.
All non-const mutator methods of Link are private, and are called only by the friend class LinkMaster. Outside of the implementation of LinkMaster, a Link is thus a read-only object.
Definition at line 30 of file Link.h.
#include <Link.h>
Public Member Functions
Link ()
Constructor.
const Atom & atom0 () const
Get Atom0 connected to a Link.
Atom & atom0 ()
Get Atom0 connected to a Link.
const Atom & atom1 () const
Get Atom1 connected to a Link.
Atom & atom1 ()
Get Atom1 connected to a Link.
int typeId () const
Get the typeId for this Link.
int tag () const
Get a permanent integer identifier for this object.
bool isActive () const
Is this Link active?
void setIsActive (bool isActive)
Activate or deactivate the Link.
Constructor & Destructor Documentation
McMd::Link::Link () inline
Constructor.
Definition at line 138 of file Link.h.
References atom0(), and atom1().
Member Function Documentation
const Atom & McMd::Link::atom0 () const inline
Get Atom0 connected to a Link.
Definition at line 159 of file Link.h.
Referenced by McMd::LinkPotentialImpl< Interaction >::addForces(), McMd::LinkPotentialImpl< Interaction >::atomEnergy(), McMd::LinkPotentialImpl< Interaction >::computeEnergy(), McMd::LinkMaster::isValid(), Link(), McMd::SliplinkerAll::move(), McMd::SliplinkerEnd::move(), McMd::SliplinkMove::move(), McMd::GcSliplinkMove::move(), McMd::Sliplinker::move(), McMd::LinkMaster::removeLink(), McMd::LinkMaster::reSetAtom(), McMd::LinkMaster::reSetAtoms(), McMd::LinkLengthDist::sample(), McMd::SSChainDist::sample(), McMd::LinkLTPos::sample(), McMd::LinkMSD::sample(), McMd::InterIntraLink::sample(), and McMd::McMdConfigIo::write().
Atom & McMd::Link::atom0 () inline
Get Atom0 connected to a Link.
Definition at line 165 of file Link.h.
const Atom & McMd::Link::atom1 () const inline
Get Atom1 connected to a Link.
Definition at line 171 of file Link.h.
Referenced by McMd::LinkPotentialImpl< Interaction >::addForces(), McMd::LinkPotentialImpl< Interaction >::atomEnergy(), McMd::LinkPotentialImpl< Interaction >::computeEnergy(), McMd::LinkMaster::isValid(), Link(), McMd::SliplinkerAll::move(), McMd::SliplinkerEnd::move(), McMd::SliplinkMove::move(), McMd::GcSliplinkMove::move(), McMd::Sliplinker::move(), McMd::LinkMaster::removeLink(), McMd::LinkMaster::reSetAtom(), McMd::LinkMaster::reSetAtoms(), McMd::LinkLengthDist::sample(), McMd::SSChainDist::sample(), McMd::LinkLTPos::sample(), McMd::LinkMSD::sample(), McMd::InterIntraLink::sample(), and McMd::McMdConfigIo::write().
Atom & McMd::Link::atom1 () inline
Get Atom1 connected to a Link.
Definition at line 177 of file Link.h.
References typeId().
int McMd::Link::typeId () const inline
Get the typeId for this Link.
Definition at line 189 of file Link.h.
Referenced by McMd::LinkPotentialImpl< Interaction >::addForces(), atom1(), McMd::LinkPotentialImpl< Interaction >::atomEnergy(), McMd::LinkPotentialImpl< Interaction >::computeEnergy(), McMd::GcSliplinkMove::move(), McMd::SliplinkMove::move(), and McMd::McMdConfigIo::write().
int McMd::Link::tag () const inline
Get a permanent integer identifier for this object.
Definition at line 213 of file Link.h.
Referenced by McMd::LinkLTPos::sample(), McMd::LinkMSD::sample(), and setIsActive().
bool McMd::Link::isActive () const inline
Is this Link active?
Definition at line 195 of file Link.h.
Referenced by McMd::LinkMaster::isValid(), McMd::LinkMaster::reSetAtom(), McMd::LinkMaster::reSetAtoms(), and setIsActive().
void McMd::Link::setIsActive (bool isActive) inline
Activate or deactivate the Link.
Parameters
isActive true (active) or false (inactive)
Definition at line 201 of file Link.h.
References isActive(), and tag().
Referenced by McMd::LinkMaster::addLink().
The documentation for this class was generated from the following file:
Link.h