Simpatico: Util::XdrFileIArchive Class Reference
Util::XdrFileIArchive Class Reference
Util namespace » Serialization
Detailed Description
Loading / input archive for binary XDR file.
XDR is a standard protocol for writing and reading binary in a portable format. This archive saves data to an associated file in XDR format. It depends on the unix xdr library <rpc/xdr.h>. Because this library is written in C (not C++), this archive uses a standard C library file handle, not a C++ iostream.
Definition at line 39 of file XdrFileIArchive.h.
#include <XdrFileIArchive.h>
Public Member Functions
XdrFileIArchive ()
Constructor.
XdrFileIArchive (std::string filename)
Constructor.
XdrFileIArchive (std::ofstream &file)
Constructor.
virtual ~XdrFileIArchive ()
Destructor.
void init (FILE *file)
Initialize by associating with an open file.
template<typename T >
XdrFileIArchive & operator& (T &data)
Load one object.
template<typename T >
XdrFileIArchive & operator>> (T &data)
Load one object.
FILE * file ()
Get the underlying file handle.
XDR * xdrPtr ()
Get a pointer to the enclosed XDR object.
Static Public Member Functions
static bool is_saving ()
Returns false.
static bool is_loading ()
Returns true.
Constructor & Destructor Documentation
Util::XdrFileIArchive::XdrFileIArchive ()
Constructor.
Definition at line 17 of file XdrFileIArchive.cpp.
Util::XdrFileIArchive::XdrFileIArchive (std::string filename)
Constructor.
Parameters
filename name of file to open for reading.
Definition at line 27 of file XdrFileIArchive.cpp.
References UTIL_THROW.
Util::XdrFileIArchive::XdrFileIArchive (std::ofstream & file)
Constructor.
Parameters
file output file
Util::XdrFileIArchive::~XdrFileIArchive () virtual
Destructor.
Definition at line 45 of file XdrFileIArchive.cpp.
Member Function Documentation
bool Util::XdrFileIArchive::is_saving () inline static
Returns false.
Definition at line 121 of file XdrFileIArchive.h.
bool Util::XdrFileIArchive::is_loading () inline static
Returns true.
Definition at line 124 of file XdrFileIArchive.h.
void Util::XdrFileIArchive::init (FILE * file)
Initialize by associating with an open file.
Parameters
file C library file handle, must be open for reading.
Definition at line 51 of file XdrFileIArchive.cpp.
References file(), and xdrPtr().
template<typename T > XdrFileIArchive & Util::XdrFileIArchive::operator& (T & data) inline
Load one object.
Definition at line 133 of file XdrFileIArchive.h.
template<typename T > XdrFileIArchive & Util::XdrFileIArchive::operator>> (T & data) inline
Load one object.
Definition at line 143 of file XdrFileIArchive.h.
FILE * Util::XdrFileIArchive::file () inline
Get the underlying file handle.
Definition at line 152 of file XdrFileIArchive.h.
Referenced by init().
XDR * Util::XdrFileIArchive::xdrPtr () inline
Get a pointer to the enclosed XDR object.
Definition at line 158 of file XdrFileIArchive.h.
References xdrPtr().
Referenced by init(), and xdrPtr().
The documentation for this class was generated from the following files:
XdrFileIArchive.h
XdrFileIArchive.cpp