Simpatico: McMd::HomoRing Class Reference
McMd::HomoRing Class Reference
Species
Detailed Description
A HomoRing species of loop molecules.
Definition at line 23 of file HomoRing.h.
#include <HomoRing.h>
Public Member Functions
HomoRing ()
Default constructor.
virtual ~HomoRing ()
Destructor.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
Protected Member Functions
virtual void readSpeciesParam (std::istream &in)
Read nAtom_ and the loop type.
virtual void loadSpeciesParam (Serializable::IArchive &ar)
Load species structure from an Archive.
virtual int calculateAtomTypeId (int index) const
Return the same type for any particle in any loop.
virtual int calculateBondTypeId (int index) const
Return same bond type for any bond in any loop.
virtual int calculateAngleTypeId (int index) const
Return same angle type for any homogeneous ring.
virtual int calculateDihedralTypeId (int index) const
Return same dihedral type for any homogeneous ring.
Protected Attributes
int type_
Particle type id for every particle of every molecule of this species.
Constructor & Destructor Documentation
McMd::HomoRing::HomoRing ()
Default constructor.
Definition at line 21 of file HomoRing.cpp.
References Util::ParamComposite::setClassName().
virtual McMd::HomoRing::~HomoRing () [inline, virtual]
Destructor.
Definition at line 32 of file HomoRing.h.
Member Function Documentation
void McMd::HomoRing::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::Species.
Definition at line 63 of file HomoRing.cpp.
References McMd::Species::id_, McMd::Species::moleculeCapacity_, McMd::Species::nAtom_, and type_.
void McMd::HomoRing::readSpeciesParam (std::istream & in) [protected, virtual]
Read nAtom_ and the loop type.
Parameters:
in input stream
Reimplemented from McMd::Species.
Definition at line 29 of file HomoRing.cpp.
References McMd::Ring::buildRing(), McMd::Species::nAngle_, McMd::Species::nAtom_, McMd::Species::nBond_, McMd::Species::nDihedral_, and type_.
void McMd::HomoRing::loadSpeciesParam (Serializable::IArchive & ar) [protected, virtual]
Load species structure from an Archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::Species.
Definition at line 46 of file HomoRing.cpp.
References McMd::Ring::buildRing(), McMd::Species::nAngle_, McMd::Species::nAtom_, McMd::Species::nBond_, McMd::Species::nDihedral_, and type_.
int McMd::HomoRing::calculateAtomTypeId (int index) const [protected, virtual]
Return the same type for any particle in any loop.
Parameters:
index atom index, in range 0, ..., nAtom_ - 1
Returns:
atom type index
Implements McMd::Ring.
Definition at line 74 of file HomoRing.cpp.
References type_.
int McMd::HomoRing::calculateBondTypeId (int index) const [protected, virtual]
Return same bond type for any bond in any loop.
Parameters:
index bond index, in range 0, ..., nBond_ - 1
Returns:
bond type index
Implements McMd::Ring.
Definition at line 80 of file HomoRing.cpp.
int McMd::HomoRing::calculateAngleTypeId (int index) const [protected, virtual]
Return same angle type for any homogeneous ring.
Angle i of a ring molecule connects atoms: (i)-(i+1)-(i+2), where atom indices mod to nAtom_.
Parameters:
index local angle index, in the range 0, ... , nAngle_ - 1
Returns:
type of the specified angle
Implements McMd::Ring.
Definition at line 87 of file HomoRing.cpp.
int McMd::HomoRing::calculateDihedralTypeId (int index) const [protected, virtual]
Return same dihedral type for any homogeneous ring.
Angle i of a ring molecule connects atoms: (i)-(i+1)-(i+2)-(i+3), where atom indices mod to nAtom_.
Parameters:
index local dihedral index, in the range 0, ... , nDihedral_ - 1
Returns:
type of the specified dihedral
Implements McMd::Ring.
Definition at line 95 of file HomoRing.cpp.
Member Data Documentation
int McMd::HomoRing::type_ [protected]
Particle type id for every particle of every molecule of this species.
Definition at line 47 of file HomoRing.h.
Referenced by calculateAtomTypeId(), loadSpeciesParam(), readSpeciesParam(), and save().
The documentation for this class was generated from the following files:
HomoRing.h
HomoRing.cpp