Simpatico: McMd::NvtNhIntegrator Class Reference
McMd::NvtNhIntegrator Class Reference
Molecular Dynamics Integrators
Detailed Description
A Nose-Hoover NVT molecular dynamics integrator.
The step() method implements a reversible velocity-verlet MD NVT integrator step for the Nose-Hoover equations, as described by Winkler, Kraus, and Reineker, J. Chem. Phys. 102, 9018 (1995).
Variables names imitate the notation used in the book by D. Frenkel and B. Smit, "Understanding Molecular Simulation," Academic Press, 1996. Chapter 6 (Eqs. 6.1.24 - 6.1.27).
Definition at line 35 of file NvtNhIntegrator.h.
#include <NvtNhIntegrator.h>
Public Member Functions
NvtNhIntegrator (MdSystem &system)
Constructor.
virtual ~NvtNhIntegrator ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from file and initialize.
virtual void loadParameters (Serializable::IArchive &ar)
Load the internal state to an archive.
virtual void save (Serializable::OArchive &ar)
Save the internal state to an archive.
virtual void setup ()
Setup auxiliary parameters of integrator, just before main loop.
virtual void step ()
Take a complete NVT MD integration step.
Public Member Functions inherited from McMd::MdIntegrator
MdIntegrator (MdSystem &system)
Constructor.
virtual ~MdIntegrator ()
Destructor.
Boundary & boundary ()
Get Boundary of parent System.
MdSystem & system ()
Get parent MdSystem by reference.
Simulation & simulation ()
Get parent Simulation.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
std::string className () const
Get class name string.
virtual void readParam (std::istream &in)
Read a parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an archive.
void resetParam ()
Resets ParamComposite to its empty state.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add a new Param < Type > object, and read its value.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add a C array parameter, and read its elements.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and read its elements.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n)
Add and read a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
Begin & readBegin (std::istream &in, const char *label)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a child ParamComposite.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add a new Param < Type > object, and load its value.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add a C array parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and load its elements.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n)
Add and load a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a DMatrix < Type > C two-dimensional matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
template<typename Type >
ScalarParam< Type > & add (const char *label, Type &value)
Add a new Param < Type > object to the format array.
template<typename Type >
CArrayParam< Type > & addCArray (const char *label, Type *value, int n)
Add a C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (const char *label, DArray< Type > &array, int n)
Add a DArray<Type> parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (const char *label, FArray< Type, N > &array)
Add a FArray<Type> parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (const char *label, Type *value, int m, int n)
Add a C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & addDMatrix (const char *label, DMatrix< Type > &matrix, int m, int n)
Add a C two-dimensional array parameter.
Begin & addBegin (const char *label)
Add a class label and opening bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Add a new Blank object, representing a blank line.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have a communicator?
MPI::Intracomm & ioCommunicator () const
Get the communicator.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
Protected Attributes inherited from McMd::MdIntegrator
double dt_
Integrator time step.
Constructor & Destructor Documentation
McMd::NvtNhIntegrator::NvtNhIntegrator (MdSystem & system)
Constructor.
Definition at line 30 of file NvtNhIntegrator.cpp.
References McMd::System::energyEnsemble(), Util::EnergyEnsemble::isIsothermal(), Util::ParamComposite::setClassName(), Util::EnergyEnsemble::temperature(), and UTIL_THROW.
McMd::NvtNhIntegrator::~NvtNhIntegrator () virtual
Destructor.
Definition at line 58 of file NvtNhIntegrator.cpp.
Member Function Documentation
void McMd::NvtNhIntegrator::readParameters (std::istream & in) virtual
Read parameters from file and initialize.
Parameters
in input file stream.
Reimplemented from Util::ParamComposite.
Definition at line 64 of file NvtNhIntegrator.cpp.
References Util::DArray< Data >::allocate(), McMd::MdIntegrator::dt_, Util::DArray< Data >::isAllocated(), McMd::Simulation::nAtomType(), McMd::MdIntegrator::simulation(), and Util::EnergyEnsemble::temperature().
void McMd::NvtNhIntegrator::loadParameters (Serializable::IArchive & ar) virtual
Load the internal state to an archive.
Parameters
ar archive object.
Reimplemented from Util::ParamComposite.
Definition at line 84 of file NvtNhIntegrator.cpp.
References McMd::MdIntegrator::dt_.
void McMd::NvtNhIntegrator::save (Serializable::OArchive & ar) virtual
Save the internal state to an archive.
Parameters
ar archive object.
Reimplemented from Util::ParamComposite.
Definition at line 99 of file NvtNhIntegrator.cpp.
References McMd::MdIntegrator::dt_.
void McMd::NvtNhIntegrator::setup () virtual
Setup auxiliary parameters of integrator, just before main loop.
This method must be called before the beginning of an MD loop to initialize private variables used by step() method.
Reimplemented from McMd::MdIntegrator.
Definition at line 111 of file NvtNhIntegrator.cpp.
References McMd::Simulation::atomType(), McMd::MdIntegrator::dt_, McMd::MdSystem::kineticEnergy(), McMd::AtomType::mass(), McMd::System::nAtom(), McMd::Simulation::nAtomType(), McMd::MdIntegrator::simulation(), McMd::MdIntegrator::system(), and Util::EnergyEnsemble::temperature().
void McMd::NvtNhIntegrator::step () virtual
Take a complete NVT MD integration step.
Implements McMd::MdIntegrator.
Definition at line 136 of file NvtNhIntegrator.cpp.
References McMd::System::begin(), McMd::MdPairPotential::buildPairList(), McMd::MdSystem::calculateForces(), McMd::MdIntegrator::dt_, McMd::MdSystem::kineticEnergy(), Util::Vector::multiply(), McMd::System::nAtom(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), McMd::MdSystem::pairPotential(), McMd::MdIntegrator::simulation(), McMd::MdIntegrator::system(), and Util::EnergyEnsemble::temperature().
The documentation for this class was generated from the following files:
NvtNhIntegrator.h
NvtNhIntegrator.cpp