Simpatico: McMd::ConfigIo Class Reference
McMd::ConfigIo Class Reference abstract
McMd namespace » Configuration File IO
Detailed Description
System configuration file reader and writer.
A ConfigIo object is used by a System to read and write the configuration file for the System. The configuration file contains the Boundary dimensions, the number of molecules of each Species, and the atomic positions for every Atom in that System.
The ConfigIo class defines default implementations of the virtual read() and write() methods. These define the default config file format for Simpatico. Other formats may be read and written by using an instance of a subclass of ConfigIo, for which the overridden read() and write() methods must define the desired file format.
A System holds a pointer to a ConfigIo, which may be set by the System::setConfigIo() method. By default, if no ConfigIo is set explicitly, the System will create and use an instance of ConfigIo when needed.
Definition at line 45 of file mcMd/configIos/ConfigIo.h.
#include <ConfigIo.h>
Public Member Functions
ConfigIo (System &system)
Constructor.
virtual ~ConfigIo ()
Destructor.
virtual void read (std::istream &in)=0
Read configuration (particle positions) from file.
virtual void write (std::ostream &out)=0
Write configuration (particle positions) to file.
Protected Member Functions
System & system () const
Get a reference to the parent System.
Simulation & simulation () const
Get a reference to the parent Simulation.
Boundary & boundary () const
Get the Boundary.
Constructor & Destructor Documentation
McMd::ConfigIo::ConfigIo (System & system)
Constructor.
Definition at line 19 of file mcMd/configIos/ConfigIo.cpp.
McMd::ConfigIo::~ConfigIo () virtual
Destructor.
Definition at line 28 of file mcMd/configIos/ConfigIo.cpp.
Member Function Documentation
virtual void McMd::ConfigIo::read (std::istream & in) pure virtual
Read configuration (particle positions) from file.
Parameters
in input file stream.
Implemented in McMd::LammpsConfigIo, McMd::DdMdConfigIo, and McMd::McMdConfigIo.
Referenced by McMd::System::readConfig().
virtual void McMd::ConfigIo::write (std::ostream & out) pure virtual
Write configuration (particle positions) to file.
Parameters
out output file stream.
Implemented in McMd::LammpsConfigIo, McMd::DdMdConfigIo, and McMd::McMdConfigIo.
Referenced by McMd::System::writeConfig().
System & McMd::ConfigIo::system () const inline protected
Get a reference to the parent System.
Definition at line 100 of file mcMd/configIos/ConfigIo.h.
Referenced by McMd::MdEnergyOutput::output(), McMd::McMdConfigIo::read(), McMd::DdMdConfigIo::read(), McMd::LammpsConfigIo::read(), McMd::MdEnergyOutput::sample(), McMd::McMdConfigIo::write(), McMd::DdMdConfigIo::write(), and McMd::LammpsConfigIo::write().
Simulation & McMd::ConfigIo::simulation () const inline protected
Get a reference to the parent Simulation.
Definition at line 109 of file mcMd/configIos/ConfigIo.h.
Referenced by McMd::McMdConfigIo::read(), McMd::DdMdConfigIo::read(), McMd::LammpsConfigIo::read(), McMd::McMdConfigIo::write(), McMd::DdMdConfigIo::write(), and McMd::LammpsConfigIo::write().
Boundary & McMd::ConfigIo::boundary () const inline protected
Get the Boundary.
Definition at line 118 of file mcMd/configIos/ConfigIo.h.
Referenced by McMd::McMdConfigIo::read(), McMd::LammpsConfigIo::read(), McMd::MdConfigIo::readAtom(), McMd::McConfigIo::readAtom(), McMd::McMdConfigIo::write(), and McMd::LammpsConfigIo::write().
The documentation for this class was generated from the following files:
mcMd/configIos/ConfigIo.h
mcMd/configIos/ConfigIo.cpp