Simpatico: McMd::MdSystem Class Reference
McMd::MdSystem Class Reference
McMd namespace » Systems
Detailed Description
A System for Molecular Dynamics simulation.
An MdSystem is a System that also has:
Associated Potential objects (MdPairPotential, BondPotential, etc.)
Associated MdIntegrator and MdIntegratorFactory objects.
It provides methods to compute forces, total energy, and stress.
Definition at line 61 of file MdSystem.h.
#include <MdSystem.h>
Public Member Functions
MdSystem ()
Constructor.
MdSystem (McSystem &system)
Constructor, copy from McSystem.
virtual ~MdSystem ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from input file.
virtual void loadParameters (Serializable::IArchive &ar)
Load parameters from an archive, without configuration.
virtual void saveParameters (Serializable::OArchive &ar)
Save parameters to an archive, without configuration.
virtual void readConfig (std::istream &in)
Read system configuration from file.
virtual void loadConfig (Serializable::IArchive &ar)
Load the MdSystem configuration from an archive.
Force, Energy and Stress calculators
void calculateForces ()
Compute all forces in this System.
double kineticEnergy () const
Compute and return total kinetic energy.
double potentialEnergy ()
Compute and return total potential energy.
template<typename T >
void computeStress (T &stress) const
Compute total pressure (T=double), xyz pressures (T=Vector) or stress (T=Tensor).
template<typename T >
void computeVirialStress (T &stress) const
Compute total virial stress, from all forces.
template<typename T >
void computeKineticStress (T &stress) const
Compute kinetic stress mvv, arising from velocities.
Potential energy accessors
MdPairPotential & pairPotential () const
Return MdPairPotential by reference.
bool hasBondPotential () const
Does a bond potential exist?.
BondPotential & bondPotential () const
Return BondPotential by reference.
bool hasAnglePotential () const
Does angle potential exist?.
AnglePotential & anglePotential () const
Return AnglePotential by reference.
bool hasDihedralPotential () const
Does a dihedral potential exist?.
DihedralPotential & dihedralPotential () const
Return DihedralPotential by reference.
bool hasLinkPotential () const
Does a link potential exist?.
BondPotential & linkPotential () const
Return link potential by reference.
bool hasExternalPotential () const
Does an external potential exist?.
ExternalPotential & externalPotential () const
Return ExternalPotential by reference.
Mutators
void setZeroForces ()
Set all atomic forces to zero.
void setZeroVelocities ()
Set all atomic velocities to zero.
void setBoltzmannVelocities (double temperature)
Set all velocities to Boltzmann distributed random values.
Vector removeDriftVelocity ()
Subtract average velocity from all atomic velocities.
void shiftAtoms ()
Shift all atoms into primary cell.
Accessors
MdIntegrator & mdIntegrator ()
Return the MdIntegrator by reference.
Factory< MdIntegrator > & mdIntegratorFactory ()
Return the MdIntegrator Factory by reference.
virtual bool isValid () const
Return true if valid, or throw Exception.
Public Member Functions inherited from McMd::System
System ()
Default constructor.
System (const System &other)
Copy constructor.
virtual ~System ()
Destructor.
void setId (int Id)
Set the integer Id for this System.
void setSimulation (Simulation &simulation)
Set the parent Simulation.
void setFileMaster (FileMaster &filemaster)
Set the FileMaster.
void saveParameters (Serializable::OArchive &ar)
Save internal state from an archive.
Factory< ConfigIo > & configIoFactory ()
Get the configuration file reader/writer factory by reference.
void setConfigIo (std::string &classname)
Create a new configuration file reader/writer.
void writeConfig (std::ostream &out)
Write system configuration to a specified ostream.
void saveConfig (Serializable::OArchive &ar)
Save configuration.
Factory< TrajectoryReader > & trajectoryReaderFactory ()
Get the trajectory reader/writer factory by reference.
void addMolecule (Molecule &molecule)
Add a Molecule to this System.
void removeMolecule (Molecule &molecule)
Remove a specific molecule from this System.
void removeAllMolecules ()
Remove all molecules from this System.
void subscribeMoleculeSetChange (MoleculeSetObserver &observer)
Subscribe to moleculeSet change signal.
void unsubscribeMoleculeSetChange (MoleculeSetObserver &observer)
Unsubscribe from moleculeSet change signal.
int nMolecule (int speciesId) const
Get the number of molecules of one Species in this System.
int nAtom () const
Return the total number of atoms in this System.
bool isEmpty () const
Is this an empty System (i.e., one with no molecules) ?
int moleculeId (const Molecule &molecule) const
Get the index of a Molecule within its Species in this System.
Molecule & molecule (int speciesId, int moleculeId)
Get a specific Molecule in this System, by integer index.
Molecule & randomMolecule (int speciesId)
Get a random Molecule of a specified species in this System.
void begin (int speciesId, MoleculeIterator &iterator)
Initialize an iterator for molecules of one species in this System.
void begin (int speciesId, ConstMoleculeIterator &iterator) const
Initialize a const iterator for molecules of one species in this System.
PairFactory & pairFactory ()
Get the PairFactory by reference.
std::string pairStyle () const
Return nonbonded pair style string.
Factory< BondPotential > & bondFactory ()
Get the associated Factory<BondPotential> by reference.
std::string bondStyle () const
Return covalent bond style string.
Factory< AnglePotential > & angleFactory ()
Get the associated AngleFactory by reference.
std::string angleStyle () const
Return angle potential style string.
Factory< DihedralPotential > & dihedralFactory ()
Get the associated Dihedral Factory by reference.
std::string dihedralStyle () const
Return dihedral potential style string.
Factory< ExternalPotential > & externalFactory ()
Get the associated ExternalPotential factory by reference.
std::string externalStyle () const
Return external potential style string.
Factory< BondPotential > & linkFactory ()
Get the associated Link factory by reference.
std::string linkStyle () const
Return link potential style string.
LinkMaster & linkMaster () const
Get the LinkMaster by reference.
Factory< Perturbation > & perturbationFactory ()
Get the perturbation factory by reference.
void setExpectPerturbation ()
Set to expect a Perturbation in the parameter file.
bool expectPerturbation () const
Return true if we expect a perturbation.
bool hasPerturbation () const
Does this system have an associated Perturbation?
Perturbation & perturbation () const
Get the associated Perturbation by reference.
bool hasReplicaMove () const
Does this system have an associated ReplicaMove?
ReplicaMove & replicaMove () const
Get the associated ReplicaMove by reference.
int id () const
Get integer index for this System.
Simulation & simulation () const
Get the parent Simulation by reference.
Boundary & boundary () const
Get the Boundary by reference.
EnergyEnsemble & energyEnsemble () const
Get the EnergyEnsemble by reference.
BoundaryEnsemble & boundaryEnsemble () const
Get the BoundaryEnsemble by reference.
FileMaster & fileMaster () const
Get the associated FileMaster by reference.
bool isCopy () const
Was this System instantiated with the copy constructor?
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
virtual ConfigIo * newDefaultConfigIo ()
Return a pointer to a new MdConfigIo object.
Protected Member Functions inherited from McMd::System
Boundary & maxBoundary () const
Get the maximum Boundary by reference.
virtual Factory< ConfigIo > * newDefaultConfigIoFactory ()
Return a pointer to a new default ConfigIoFactory.
virtual Factory< TrajectoryReader > * newDefaultTrajectoryReaderFactory ()
Return a pointer to a new default TrajectoryReaderFactory.
virtual Factory< Perturbation > * newDefaultPerturbationFactory ()
Return a pointer to the default perturbation Factory.
void readPerturbation (std::istream &in)
Read the perturbation parameter block (if any)
void loadPerturbation (Serializable::IArchive &ar)
Load the perturbation parameter block (if any)
void savePerturbation (Serializable::OArchive &ar)
Save the perturbation parameter block (if any)
void readReplicaMove (std::istream &in)
Read the ReplicaMove parameter block (if any)
void loadReplicaMove (Serializable::IArchive &ar)
Read the ReplicaMove parameter block (if any)
void saveReplicaMove (Serializable::OArchive &ar)
Save the ReplicaMove parameter block (if any)
void allocateMoleculeSets ()
Allocate and initialize molecule sets for all species.
void readFileMaster (std::istream &in)
Read FileMaster parameters, if none yet exists.
void loadFileMaster (Serializable::IArchive &ar)
Load FileMaster data from archive, if necessary.
void saveFileMaster (Serializable::OArchive &ar)
If necessary, save FileMaster to archive.
void readPotentialStyles (std::istream &in)
Read potential style parameter strings.
void loadPotentialStyles (Serializable::IArchive &ar)
Load potential style strings from an archive.
void savePotentialStyles (Serializable::OArchive &ar)
Save potential style strings.
void readEnsembles (std::istream &in)
Read energy and boundary ensemble parameters.
void loadEnsembles (Serializable::IArchive &ar)
Load energy and boundary ensembles from archive.
void saveEnsembles (Serializable::OArchive &ar)
Save energy and boundary ensembles.
void readLinkMaster (std::istream &in)
Read the LinkMaster parameters.
void loadLinkMaster (Serializable::IArchive &ar)
Load the LinkMaster.
void saveLinkMaster (Serializable::OArchive &ar)
Save the LinkMaster.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from McMd::System
typedef ArraySet< Molecule > MoleculeSet
A set of molecules of one Species in a System.
typedef PArrayIterator< Molecule > MoleculeIterator
Iterator for a MoleculeSet.
typedef ConstPArrayIterator< Molecule > ConstMoleculeIterator
Const Iterator for a MoleculeSet.
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Constructor & Destructor Documentation
McMd::MdSystem::MdSystem ()
Constructor.
Definition at line 61 of file MdSystem.cpp.
References Util::ParamComposite::setClassName().
McMd::MdSystem::MdSystem (McSystem & system)
Constructor, copy from McSystem.
Used to create child MdSystem for Hybrid MD/MC move.
Parameters
system System object to be cloned.
Definition at line 92 of file MdSystem.cpp.
References McMd::McSystem::anglePotential(), McMd::McSystem::bondPotential(), McMd::McSystem::dihedralPotential(), McMd::McSystem::externalPotential(), McMd::McSystem::hasAnglePotential(), McMd::McSystem::hasBondPotential(), McMd::McSystem::hasDihedralPotential(), McMd::McSystem::hasExternalPotential(), McMd::McSystem::hasLinkPotential(), McMd::McSystem::linkPotential(), McMd::PairFactory::mdFactory(), McMd::System::pairFactory(), McMd::McSystem::pairPotential(), Util::ParamComposite::setClassName(), and UTIL_THROW.
McMd::MdSystem::~MdSystem () virtual
Destructor.
Definition at line 162 of file MdSystem.cpp.
References McMd::System::isCopy().
Member Function Documentation
void McMd::MdSystem::readParameters (std::istream & in) virtual
Read parameters from input file.
This method calls System::readParameters(in), reads potentials, and allocates the pairList.
Parameters
in file stream.
Reimplemented from McMd::System.
Definition at line 213 of file MdSystem.cpp.
References McMd::System::allocateMoleculeSets(), McMd::System::angleFactory(), McMd::System::angleStyle(), McMd::System::bondFactory(), McMd::System::bondStyle(), Util::ParamComposite::className(), McMd::System::dihedralFactory(), McMd::System::dihedralStyle(), McMd::System::externalFactory(), McMd::System::externalStyle(), Util::Factory< Data >::factory(), McMd::System::isCopy(), McMd::System::linkFactory(), McMd::System::linkStyle(), McMd::PairFactory::mdFactory(), McMd::System::pairFactory(), McMd::System::pairStyle(), McMd::System::readEnsembles(), McMd::System::readFileMaster(), McMd::System::readLinkMaster(), Util::Factory< Data >::readObject(), Util::ParamComposite::readParamComposite(), McMd::System::readPerturbation(), McMd::System::readPotentialStyles(), McMd::System::simulation(), and UTIL_THROW.
void McMd::MdSystem::loadParameters (Serializable::IArchive & ar) virtual
Load parameters from an archive, without configuration.
Parameters
ar input/loading archive
Reimplemented from McMd::System.
Definition at line 338 of file MdSystem.cpp.
References McMd::System::allocateMoleculeSets(), McMd::System::angleFactory(), McMd::System::angleStyle(), McMd::System::bondFactory(), McMd::System::bondStyle(), Util::ParamComposite::className(), McMd::System::dihedralFactory(), McMd::System::dihedralStyle(), McMd::System::externalFactory(), McMd::System::externalStyle(), Util::Factory< Data >::factory(), McMd::System::isCopy(), McMd::System::linkFactory(), McMd::System::linkStyle(), McMd::System::loadEnsembles(), McMd::System::loadFileMaster(), McMd::System::loadLinkMaster(), Util::Factory< Data >::loadObject(), Util::ParamComposite::loadParamComposite(), McMd::System::loadPerturbation(), McMd::System::loadPotentialStyles(), McMd::PairFactory::mdFactory(), McMd::System::pairFactory(), McMd::System::pairStyle(), McMd::System::simulation(), and UTIL_THROW.
void McMd::MdSystem::saveParameters (Serializable::OArchive & ar) virtual
Save parameters to an archive, without configuration.
Parameters
ar output/saving archive
Definition at line 462 of file MdSystem.cpp.
References Util::ParamComposite::className(), McMd::System::isCopy(), Util::ParamComposite::save(), McMd::System::saveEnsembles(), McMd::System::saveFileMaster(), McMd::System::saveLinkMaster(), McMd::System::savePerturbation(), McMd::System::savePotentialStyles(), and McMd::System::simulation().
Referenced by McMd::HybridMdMove::save(), McMd::HybridNphMdMove::save(), McMd::DpdMove::save(), McMd::MdMove::save(), and McMd::MdSimulation::save().
void McMd::MdSystem::readConfig (std::istream & in) virtual
Read system configuration from file.
This calls System::readConfig(), followed by pairPotential().buildPairList() and calculateForces().
Parameters
in configuration file input stream
Reimplemented from McMd::System.
Definition at line 518 of file MdSystem.cpp.
References McMd::MdPairPotential::buildPairList(), calculateForces(), McMd::MdPairPotential::clearPairListStatistics(), pairPotential(), and McMd::System::readConfig().
Referenced by McMd::MdSimulation::analyzeConfigs(), and McMd::MdSimulation::readCommands().
void McMd::MdSystem::loadConfig (Serializable::IArchive & ar) virtual
Load the MdSystem configuration from an archive.
This calls System::loadConfig(ar), followed by pairPotential().buildPairList() and calculateForces().
Parameters
ar input (loading) archive object.
Reimplemented from McMd::System.
Definition at line 532 of file MdSystem.cpp.
References McMd::MdPairPotential::buildPairList(), calculateForces(), McMd::MdPairPotential::clearPairListStatistics(), McMd::System::loadConfig(), and pairPotential().
Referenced by McMd::MdSimulation::loadParameters().
void McMd::MdSystem::calculateForces ()
Compute all forces in this System.
This method zero all forces and then calls the addForces() method of each of the potential objects (pair, bond, etc.). The McPairPotential::addForces() method updates the pair list if necessary before calculating pair forces. On exit, all atomic forces are updated to values corresponding to current positions.
Definition at line 659 of file MdSystem.cpp.
References McMd::MdPairPotential::addForces(), McMd::ExternalPotential::addForces(), McMd::BondPotential::addForces(), McMd::DihedralPotential::addForces(), McMd::AnglePotential::addForces(), anglePotential(), bondPotential(), dihedralPotential(), externalPotential(), hasAnglePotential(), hasBondPotential(), hasDihedralPotential(), hasExternalPotential(), hasLinkPotential(), linkPotential(), pairPotential(), and setZeroForces().
Referenced by loadConfig(), McMd::HybridMdMove::move(), McMd::HybridNphMdMove::move(), McMd::MdMove::move(), McMd::DpdMove::move(), readConfig(), McMd::NvtDpdVvIntegrator::setup(), McMd::MdSimulation::simulate(), McMd::NveVvIntegrator::step(), McMd::NvtLangevinIntegrator::step(), McMd::NvtDpdVvIntegrator::step(), McMd::NvtNhIntegrator::step(), and McMd::NphIntegrator::step().
double McMd::MdSystem::kineticEnergy () const
Compute and return total kinetic energy.
Definition at line 744 of file MdSystem.cpp.
References anglePotential(), McMd::Simulation::atomType(), McMd::System::begin(), bondPotential(), McMd::System::boundary(), computeKineticStress(), McMd::PairPotential::computeStress(), McMd::BondPotential::computeStress(), McMd::DihedralPotential::computeStress(), McMd::AnglePotential::computeStress(), computeVirialStress(), dihedralPotential(), hasAnglePotential(), hasBondPotential(), hasDihedralPotential(), hasLinkPotential(), linkPotential(), McMd::AtomType::mass(), Util::Vector::multiply(), Util::ConstArrayIterator< Data >::notEnd(), Util::ConstPArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), pairPotential(), Util::setToZero(), McMd::System::simulation(), and Util::OrthorhombicBoundary::volume().
Referenced by McMd::HybridMdMove::move(), McMd::HybridNphMdMove::move(), McMd::NvtNhIntegrator::setup(), and McMd::NvtNhIntegrator::step().
double McMd::MdSystem::potentialEnergy ()
Compute and return total potential energy.
Definition at line 702 of file MdSystem.cpp.
References anglePotential(), bondPotential(), dihedralPotential(), McMd::PairPotential::energy(), McMd::AnglePotential::energy(), McMd::BondPotential::energy(), McMd::ExternalPotential::energy(), McMd::DihedralPotential::energy(), externalPotential(), hasAnglePotential(), hasBondPotential(), hasDihedralPotential(), hasExternalPotential(), hasLinkPotential(), linkPotential(), and pairPotential().
Referenced by McMd::HybridMdMove::move(), and McMd::HybridNphMdMove::move().
template<typename T > void McMd::MdSystem::computeStress (T & stress) const
Compute total pressure (T=double), xyz pressures (T=Vector) or stress (T=Tensor).
In this and all other stress / pressure calculator method templates, typename T must be double to obtain total pressure, Util::Vector to obtain the x, y, and z diagonal pressure components, or Util::Tensor to obtain the full stress tensor. These templates work only for these three types. The function parameter "stress" is set to the desired value.
The total stress is the sum of the virial stress, from interatomic forces, and a kinetic stress arising from the atomic velocities.
Parameters
stress (output) pressure, xyz pressures or stress Tensor.
Referenced by McMd::NphIntegrator::step().
template<typename T > void McMd::MdSystem::computeVirialStress (T & stress) const
Compute total virial stress, from all forces.
The virial stress is the sum of all pair and bonded stress components. It excludes the kinetic stress.
See also
MdSystem::computeStress(T&) regarding allowed types for T.
Parameters
stress (output) pressure, pressures or Tensor.
Referenced by McMd::MdStressAutoCorr::computeStress(), kineticEnergy(), and McMd::MdVirialStressTensorAverage::sample().
template<typename T > void McMd::MdSystem::computeKineticStress (T & stress) const
Compute kinetic stress mvv, arising from velocities.
See also
MdSystem::computeStress(T&) regarding allowed types for T.
Parameters
stress (output) pressure, pressures or Tensor.
Referenced by McMd::MdStressAutoCorr::computeStress(), and kineticEnergy().
MdPairPotential & McMd::MdSystem::pairPotential () const inline
Return MdPairPotential by reference.
Definition at line 410 of file MdSystem.h.
Referenced by McMd::MdSimulation::analyzeConfigs(), McMd::MdSimulation::analyzeTrajectory(), calculateForces(), kineticEnergy(), loadConfig(), McMd::NvtDpdVvIntegrator::loadParameters(), McMd::HybridMdMove::move(), McMd::HybridNphMdMove::move(), McMd::MdMove::move(), McMd::DpdMove::move(), potentialEnergy(), McMd::MdSimulation::readCommands(), readConfig(), McMd::NvtDpdVvIntegrator::readParameters(), McMd::NvtDpdVvIntegrator::setup(), McMd::MdSimulation::simulate(), McMd::NveVvIntegrator::step(), McMd::NvtLangevinIntegrator::step(), McMd::NvtDpdVvIntegrator::step(), McMd::NvtNhIntegrator::step(), and McMd::NphIntegrator::step().
bool McMd::MdSystem::hasBondPotential () const inline
Does a bond potential exist?.
Definition at line 421 of file MdSystem.h.
Referenced by calculateForces(), kineticEnergy(), and potentialEnergy().
BondPotential & McMd::MdSystem::bondPotential () const inline
Return BondPotential by reference.
Definition at line 429 of file MdSystem.h.
Referenced by calculateForces(), McMd::generatorFactory(), kineticEnergy(), potentialEnergy(), and McMd::MdSimulation::readCommands().
bool McMd::MdSystem::hasAnglePotential () const inline
Does angle potential exist?.
Definition at line 440 of file MdSystem.h.
Referenced by calculateForces(), kineticEnergy(), and potentialEnergy().
AnglePotential & McMd::MdSystem::anglePotential () const inline
Return AnglePotential by reference.
Definition at line 448 of file MdSystem.h.
Referenced by calculateForces(), kineticEnergy(), potentialEnergy(), and McMd::MdSimulation::readCommands().
bool McMd::MdSystem::hasDihedralPotential () const inline
Does a dihedral potential exist?.
Definition at line 459 of file MdSystem.h.
Referenced by calculateForces(), kineticEnergy(), and potentialEnergy().
DihedralPotential & McMd::MdSystem::dihedralPotential () const inline
Return DihedralPotential by reference.
Definition at line 467 of file MdSystem.h.
Referenced by calculateForces(), kineticEnergy(), potentialEnergy(), and McMd::MdSimulation::readCommands().
bool McMd::MdSystem::hasLinkPotential () const inline
Does a link potential exist?.
Definition at line 478 of file MdSystem.h.
Referenced by calculateForces(), kineticEnergy(), and potentialEnergy().
BondPotential & McMd::MdSystem::linkPotential () const inline
Return link potential by reference.
Definition at line 486 of file MdSystem.h.
Referenced by calculateForces(), kineticEnergy(), and potentialEnergy().
bool McMd::MdSystem::hasExternalPotential () const inline
Does an external potential exist?.
Definition at line 497 of file MdSystem.h.
Referenced by calculateForces(), and potentialEnergy().
ExternalPotential & McMd::MdSystem::externalPotential () const inline
Return ExternalPotential by reference.
Definition at line 505 of file MdSystem.h.
Referenced by calculateForces(), and potentialEnergy().
void McMd::MdSystem::setZeroForces ()
Set all atomic forces to zero.
Definition at line 566 of file MdSystem.cpp.
References McMd::System::begin(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), and McMd::System::simulation().
Referenced by calculateForces().
void McMd::MdSystem::setZeroVelocities ()
Set all atomic velocities to zero.
Definition at line 582 of file MdSystem.cpp.
References McMd::System::begin(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), and McMd::System::simulation().
void McMd::MdSystem::setBoltzmannVelocities (double temperature)
Set all velocities to Boltzmann distributed random values.
Parameters
temperature temperature used in Boltzmann distribution
Definition at line 599 of file MdSystem.cpp.
References McMd::Simulation::atomType(), McMd::System::begin(), Util::Dimension, Util::Random::gaussian(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), McMd::Simulation::random(), and McMd::System::simulation().
Referenced by McMd::HybridMdMove::move(), McMd::HybridNphMdMove::move(), McMd::MdMove::move(), and McMd::MdSimulation::readCommands().
Vector McMd::MdSystem::removeDriftVelocity ()
Subtract average velocity from all atomic velocities.
Upon return, the system has a vanishing center-of-mass momentum.
Returns
value of drift velocity before subtraction
Definition at line 627 of file MdSystem.cpp.
References McMd::System::begin(), McMd::System::nAtom(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), and McMd::System::simulation().
Referenced by McMd::MdSimulation::readCommands().
void McMd::MdSystem::shiftAtoms ()
Shift all atoms into primary cell.
Shifts all atom positions into the primary image of the periodic boundary.
Definition at line 545 of file MdSystem.cpp.
References McMd::System::begin(), McMd::System::boundary(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::OrthorhombicBoundary::shift(), and McMd::System::simulation().
Referenced by McMd::MdSimulation::simulate().
MdIntegrator & McMd::MdSystem::mdIntegrator () inline
Return the MdIntegrator by reference.
Definition at line 523 of file MdSystem.h.
Referenced by McMd::HybridNphMdMove::loadParameters(), McMd::HybridMdMove::move(), McMd::MdMove::move(), McMd::DpdMove::move(), McMd::HybridNphMdMove::readParameters(), McMd::DpdMove::setup(), and McMd::MdSimulation::simulate().
Factory< MdIntegrator > & McMd::MdSystem::mdIntegratorFactory ()
Return the MdIntegrator Factory by reference.
Definition at line 198 of file MdSystem.cpp.
bool McMd::MdSystem::isValid () const virtual
Return true if valid, or throw Exception.
Reimplemented from McMd::System.
Definition at line 903 of file MdSystem.cpp.
References McMd::PairList::isValid(), McMd::System::isValid(), and McMd::MdPairPotential::pairList().
Referenced by McMd::MdSimulation::isValid().
ConfigIo * McMd::MdSystem::newDefaultConfigIo () protected virtual
Return a pointer to a new MdConfigIo object.
Reimplemented from McMd::System.
Definition at line 915 of file MdSystem.cpp.
The documentation for this class was generated from the following files:
MdSystem.h
MdSystem.cpp