Simpatico: McMd::System Class Reference
McMd::System Class Reference
McMd namespace » Systems
Detailed Description
A set of interacting Molecules enclosed by a Boundary.
A System has:
a Boundary, which defines the System dimensions.
an ArraySet of Molecule objects of each Species.
an EnergyEnsemble and a BoundaryEnsemble
a ConfigIo, which can read and write a configuration file
a FileMaster, to manage associated input and output files
A System must be associated with a parent Simulation, which owns many of the data structures used by a System.
The MdSystem and McSystem subclasses of System are designed for use in MD and MC simulations, respectively, and provide methods to evaluate energies and forces.
Definition at line 106 of file System.h.
#include <System.h>
Public Types
typedef ArraySet< Molecule > MoleculeSet
A set of molecules of one Species in a System.
typedef PArrayIterator< Molecule > MoleculeIterator
Iterator for a MoleculeSet.
typedef ConstPArrayIterator< Molecule > ConstMoleculeIterator
Const Iterator for a MoleculeSet.
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Public Member Functions
System ()
Default constructor.
System (const System &other)
Copy constructor.
virtual ~System ()
Destructor.
Initialization
void setId (int Id)
Set the integer Id for this System.
void setSimulation (Simulation &simulation)
Set the parent Simulation.
void setFileMaster (FileMaster &filemaster)
Set the FileMaster.
virtual void readParameters (std::istream &in)
Read parameter file.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
void saveParameters (Serializable::OArchive &ar)
Save internal state from an archive.
Config File IO
Factory< ConfigIo > & configIoFactory ()
Get the configuration file reader/writer factory by reference.
void setConfigIo (std::string &classname)
Create a new configuration file reader/writer.
virtual void readConfig (std::istream &in)
Read system configuration from file.
void writeConfig (std::ostream &out)
Write system configuration to a specified ostream.
virtual void loadConfig (Serializable::IArchive &ar)
Load configuration.
void saveConfig (Serializable::OArchive &ar)
Save configuration.
Trajectory File IO
Factory< TrajectoryReader > & trajectoryReaderFactory ()
Get the trajectory reader/writer factory by reference.
Molecule Set Mutators
void addMolecule (Molecule &molecule)
Add a Molecule to this System.
void removeMolecule (Molecule &molecule)
Remove a specific molecule from this System.
void removeAllMolecules ()
Remove all molecules from this System.
void subscribeMoleculeSetChange (MoleculeSetObserver &observer)
Subscribe to moleculeSet change signal.
void unsubscribeMoleculeSetChange (MoleculeSetObserver &observer)
Unsubscribe from moleculeSet change signal.
Molecule Set Accessors
int nMolecule (int speciesId) const
Get the number of molecules of one Species in this System.
int nAtom () const
Return the total number of atoms in this System.
bool isEmpty () const
Is this an empty System (i.e., one with no molecules) ?
int moleculeId (const Molecule &molecule) const
Get the index of a Molecule within its Species in this System.
Molecule & molecule (int speciesId, int moleculeId)
Get a specific Molecule in this System, by integer index.
Molecule & randomMolecule (int speciesId)
Get a random Molecule of a specified species in this System.
void begin (int speciesId, MoleculeIterator &iterator)
Initialize an iterator for molecules of one species in this System.
void begin (int speciesId, ConstMoleculeIterator &iterator) const
Initialize a const iterator for molecules of one species in this System.
Potential Energy Factories and Styles
PairFactory & pairFactory ()
Get the PairFactory by reference.
std::string pairStyle () const
Return nonbonded pair style string.
Factory< BondPotential > & bondFactory ()
Get the associated Factory<BondPotential> by reference.
std::string bondStyle () const
Return covalent bond style string.
Factory< AnglePotential > & angleFactory ()
Get the associated AngleFactory by reference.
std::string angleStyle () const
Return angle potential style string.
Factory< DihedralPotential > & dihedralFactory ()
Get the associated Dihedral Factory by reference.
std::string dihedralStyle () const
Return dihedral potential style string.
Factory< ExternalPotential > & externalFactory ()
Get the associated ExternalPotential factory by reference.
std::string externalStyle () const
Return external potential style string.
Factory< BondPotential > & linkFactory ()
Get the associated Link factory by reference.
std::string linkStyle () const
Return link potential style string.
LinkMaster & linkMaster () const
Get the LinkMaster by reference.
Free Energy Perturbation Theory
Factory< Perturbation > & perturbationFactory ()
Get the perturbation factory by reference.
void setExpectPerturbation ()
Set to expect a Perturbation in the parameter file.
bool expectPerturbation () const
Return true if we expect a perturbation.
bool hasPerturbation () const
Does this system have an associated Perturbation?
Perturbation & perturbation () const
Get the associated Perturbation by reference.
bool hasReplicaMove () const
Does this system have an associated ReplicaMove?
ReplicaMove & replicaMove () const
Get the associated ReplicaMove by reference.
Accessors (Miscellaneous)
int id () const
Get integer index for this System.
Simulation & simulation () const
Get the parent Simulation by reference.
Boundary & boundary () const
Get the Boundary by reference.
EnergyEnsemble & energyEnsemble () const
Get the EnergyEnsemble by reference.
BoundaryEnsemble & boundaryEnsemble () const
Get the BoundaryEnsemble by reference.
FileMaster & fileMaster () const
Get the associated FileMaster by reference.
bool isCopy () const
Was this System instantiated with the copy constructor?
virtual bool isValid () const
Return true if valid, or throw Exception.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
Boundary & maxBoundary () const
Get the maximum Boundary by reference.
virtual ConfigIo * newDefaultConfigIo ()
Return a pointer to a new default ConfigIo.
virtual Factory< ConfigIo > * newDefaultConfigIoFactory ()
Return a pointer to a new default ConfigIoFactory.
virtual Factory< TrajectoryReader > * newDefaultTrajectoryReaderFactory ()
Return a pointer to a new default TrajectoryReaderFactory.
virtual Factory< Perturbation > * newDefaultPerturbationFactory ()
Return a pointer to the default perturbation Factory.
void readPerturbation (std::istream &in)
Read the perturbation parameter block (if any)
void loadPerturbation (Serializable::IArchive &ar)
Load the perturbation parameter block (if any)
void savePerturbation (Serializable::OArchive &ar)
Save the perturbation parameter block (if any)
void readReplicaMove (std::istream &in)
Read the ReplicaMove parameter block (if any)
void loadReplicaMove (Serializable::IArchive &ar)
Read the ReplicaMove parameter block (if any)
void saveReplicaMove (Serializable::OArchive &ar)
Save the ReplicaMove parameter block (if any)
void allocateMoleculeSets ()
Allocate and initialize molecule sets for all species.
void readFileMaster (std::istream &in)
Read FileMaster parameters, if none yet exists.
void loadFileMaster (Serializable::IArchive &ar)
Load FileMaster data from archive, if necessary.
void saveFileMaster (Serializable::OArchive &ar)
If necessary, save FileMaster to archive.
void readPotentialStyles (std::istream &in)
Read potential style parameter strings.
void loadPotentialStyles (Serializable::IArchive &ar)
Load potential style strings from an archive.
void savePotentialStyles (Serializable::OArchive &ar)
Save potential style strings.
void readEnsembles (std::istream &in)
Read energy and boundary ensemble parameters.
void loadEnsembles (Serializable::IArchive &ar)
Load energy and boundary ensembles from archive.
void saveEnsembles (Serializable::OArchive &ar)
Save energy and boundary ensembles.
void readLinkMaster (std::istream &in)
Read the LinkMaster parameters.
void loadLinkMaster (Serializable::IArchive &ar)
Load the LinkMaster.
void saveLinkMaster (Serializable::OArchive &ar)
Save the LinkMaster.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Member Typedef Documentation
typedef ArraySet<Molecule> McMd::System::MoleculeSet
A set of molecules of one Species in a System.
Definition at line 114 of file System.h.
typedef PArrayIterator<Molecule> McMd::System::MoleculeIterator
Iterator for a MoleculeSet.
Definition at line 117 of file System.h.
typedef ConstPArrayIterator<Molecule> McMd::System::ConstMoleculeIterator
Const Iterator for a MoleculeSet.
Definition at line 120 of file System.h.
Constructor & Destructor Documentation
McMd::System::System ()
Default constructor.
Definition at line 69 of file System.cpp.
McMd::System::System (const System & other)
Copy constructor.
Definition at line 155 of file System.cpp.
McMd::System::~System () virtual
Destructor.
Definition at line 237 of file System.cpp.
References isCopy().
Member Function Documentation
void McMd::System::setId (int Id)
Set the integer Id for this System.
Set id to zero for Simulation objects with one System.
Parameters
Id integer System index.
Definition at line 737 of file System.cpp.
References id().
Referenced by McMd::McSimulation::McSimulation(), and McMd::MdSimulation::MdSimulation().
void McMd::System::setSimulation (Simulation & simulation)
Set the parent Simulation.
Parameters
simulation parent Simulation object.
Definition at line 747 of file System.cpp.
References simulation().
Referenced by McMd::McSimulation::McSimulation(), and McMd::MdSimulation::MdSimulation().
void McMd::System::setFileMaster (FileMaster & filemaster)
Set the FileMaster.
Is normally used to set the FileMaster to that of the parent Simulation.
Parameters
filemaster FileMaster object.
Definition at line 756 of file System.cpp.
References fileMaster().
Referenced by McMd::McSimulation::McSimulation(), and McMd::MdSimulation::MdSimulation().
void McMd::System::readParameters (std::istream & in) virtual
Read parameter file.
Only reads parameters if this System is not a copy (i.e., was not constructed with the copy constructor). If it is a copy, this function does nothing and returns normally.
Parameters
in pararameter file input stream
Reimplemented from Util::ParamComposite.
Reimplemented in McMd::MdSystem, and McMd::McSystem.
Definition at line 323 of file System.cpp.
References allocateMoleculeSets(), isCopy(), readEnsembles(), readFileMaster(), readLinkMaster(), and readPotentialStyles().
void McMd::System::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Reimplemented in McMd::MdSystem, and McMd::McSystem.
Definition at line 345 of file System.cpp.
References allocateMoleculeSets(), isCopy(), loadEnsembles(), loadFileMaster(), loadLinkMaster(), and loadPotentialStyles().
void McMd::System::saveParameters (Serializable::OArchive & ar)
Save internal state from an archive.
Parameters
ar output/saving archive
Definition at line 364 of file System.cpp.
References isCopy(), saveEnsembles(), saveFileMaster(), saveLinkMaster(), and savePotentialStyles().
Factory< ConfigIo > & McMd::System::configIoFactory ()
Get the configuration file reader/writer factory by reference.
Definition at line 767 of file System.cpp.
References newDefaultConfigIoFactory().
void McMd::System::setConfigIo (std::string & classname)
Create a new configuration file reader/writer.
This function allows one to choose from among several subclasses of ConfigIo, identified by subclass name. The implementation uses a Factory<ConfigIo> object to instantiate a new object. If setConfigIoFactory() has not been called, an instance of the default class ConfigIoFactory is created and used.
Parameters
classname name of desired ConfigIo subclass.
Definition at line 784 of file System.cpp.
References Util::Factory< Data >::factory(), newDefaultConfigIoFactory(), and UTIL_THROW.
Referenced by McMd::MdSimulation::readCommands(), and McMd::McSimulation::readCommands().
void McMd::System::readConfig (std::istream & in) virtual
Read system configuration from file.
The configuration file contains the dimensions of the Boundary, the number of molecules of each Species, and the atomic positions for all atoms of all molecules in this System.
This function uses a ConfigIo object that is registered with this System. If a ConfigIo object has not been registered by calling setConfigIo(std::string&), this function creates and uses an instance of the ConfigIo base class.
Precondition: The System and its Parent Simulation must have been initialized by calling their readParam function.
Parameters
in configuration file input stream
Reimplemented in McMd::MdSystem, and McMd::McSystem.
Definition at line 705 of file System.cpp.
References isEmpty(), isValid(), newDefaultConfigIo(), McMd::ConfigIo::read(), and removeAllMolecules().
Referenced by McMd::McSystem::readConfig(), and McMd::MdSystem::readConfig().
void McMd::System::writeConfig (std::ostream & out)
Write system configuration to a specified ostream.
Like readConfig(), this function will create and use a ConfigIo object if none has been registered previously.
Parameters
out configuration file output stream
Definition at line 722 of file System.cpp.
References newDefaultConfigIo(), and McMd::ConfigIo::write().
Referenced by McMd::MdSimulation::readCommands(), McMd::McSimulation::readCommands(), and McMd::ConfigWriter::sample().
void McMd::System::loadConfig (Serializable::IArchive & ar) virtual
Load configuration.
Parameters
ar input/loading archive
Reimplemented in McMd::MdSystem, and McMd::McSystem.
Definition at line 625 of file System.cpp.
References addMolecule(), McMd::Molecule::begin(), boundary(), McMd::Simulation::getMolecule(), molecule(), Util::ArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::OrthorhombicBoundary::shift(), simulation(), and UTIL_THROW.
Referenced by McMd::McSystem::loadConfig(), and McMd::MdSystem::loadConfig().
void McMd::System::saveConfig (Serializable::OArchive & ar)
Save configuration.
Parameters
ar output/save archive
Definition at line 664 of file System.cpp.
References begin(), boundary(), nMolecule(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::OrthorhombicBoundary::shift(), and simulation().
Referenced by McMd::MdSimulation::save(), and McMd::McSimulation::save().
Factory< TrajectoryReader > & McMd::System::trajectoryReaderFactory ()
Get the trajectory reader/writer factory by reference.
Definition at line 804 of file System.cpp.
References newDefaultTrajectoryReaderFactory().
Referenced by McMd::MdSimulation::analyzeTrajectory(), and McMd::McSimulation::analyzeTrajectory().
void McMd::System::addMolecule (Molecule & molecule)
Add a Molecule to this System.
This function adds a Molecule to the set of Molecules of the same Species in this System, and calls Molecule::setSystem(*this).
The molecule to be added should first be popped off the Species reservoir or removed from another System.
Parameters
molecule Molecule to be added to this System.
Definition at line 981 of file System.cpp.
References McMd::Species::id(), McMd::Molecule::setSystem(), McMd::Molecule::species(), and UTIL_THROW.
Referenced by McMd::TrajectoryReader::addMolecules(), McMd::Generator::generate(), loadConfig(), McMd::McMdConfigIo::read(), McMd::DdMdConfigIo::read(), McMd::LammpsConfigIo::read(), and McMd::McNVTChemicalPotential::sample().
void McMd::System::removeMolecule (Molecule & molecule)
Remove a specific molecule from this System.
This function removes a Molecule from the set of molecules of the same Species in this System, and calls Molecule::unsetSystem().
The removed Molecule should be pushed onto the Species reservoir or added to another System.
Parameters
molecule Molecule to be removed from this System.
Definition at line 999 of file System.cpp.
References McMd::Species::id(), McMd::Molecule::species(), McMd::Molecule::system(), McMd::Molecule::unsetSystem(), and UTIL_THROW.
Referenced by McMd::Generator::generate(), removeAllMolecules(), and McMd::McNVTChemicalPotential::sample().
void McMd::System::removeAllMolecules ()
Remove all molecules from this System.
Remove all molecules of every species from this System, and push each onto the reservoir for the appropriate Species.
Definition at line 1030 of file System.cpp.
References McMd::LinkMaster::clear(), linkMaster(), molecule(), nMolecule(), McMd::Simulation::nSpecies(), removeMolecule(), McMd::Simulation::returnMolecule(), and simulation().
Referenced by McMd::MdSimulation::analyzeConfigs(), McMd::McSimulation::analyzeConfigs(), and readConfig().
void McMd::System::subscribeMoleculeSetChange (MoleculeSetObserver & observer) inline
Subscribe to moleculeSet change signal.
Parameters
observer the observer
Definition at line 1120 of file System.h.
void McMd::System::unsubscribeMoleculeSetChange (MoleculeSetObserver & observer) inline
Unsubscribe from moleculeSet change signal.
Parameters
observer the observer
Definition at line 1126 of file System.h.
int McMd::System::nMolecule (int speciesId) const inline
Get the number of molecules of one Species in this System.
Parameters
speciesId integer Id for a Species.
Returns
number of molecules of specified Species in this System.
Definition at line 1036 of file System.h.
Referenced by isEmpty(), McMd::ClusterIdentifier::isValid(), isValid(), McMd::CfbDoubleRebridgeMove::move(), nAtom(), McMd::CfbReptationMove::output(), McMd::CfbReptateMove::output(), randomMolecule(), removeAllMolecules(), McMd::BlockRadiusGyration::sample(), McMd::RadiusGyration::sample(), saveConfig(), McMd::McMuExchange::setup(), McMd::AtomMSD::setup(), McMd::ComMSD::setup(), McMd::RingRouseAutoCorr::setup(), McMd::LinearRouseAutoCorr::setup(), McMd::IntraPairAutoCorr::setup(), McMd::McMdConfigIo::write(), McMd::DdMdConfigIo::write(), and McMd::LammpsConfigIo::write().
int McMd::System::nAtom () const
Return the total number of atoms in this System.
Definition at line 1083 of file System.cpp.
References McMd::Species::nAtom(), nMolecule(), McMd::Simulation::nSpecies(), simulation(), and McMd::Simulation::species().
Referenced by McMd::McSystem::potentialEnergy(), McMd::MdSystem::removeDriftVelocity(), McMd::NvtNhIntegrator::setup(), and McMd::NvtNhIntegrator::step().
bool McMd::System::isEmpty () const
Is this an empty System (i.e., one with no molecules) ?
Definition at line 1017 of file System.cpp.
References nMolecule(), McMd::Simulation::nSpecies(), and simulation().
Referenced by readConfig().
int McMd::System::moleculeId (const Molecule & molecule) const
Get the index of a Molecule within its Species in this System.
This function returns the current (mutable) index of the molecule within the set of molecules of the same Species in this System, in the range 0 <= moleculeId < nMolecule(speciesId). This is the index required as the second argument of molecule(int, int).
Note: The id returned by this function is not the same as the id returned by Molecule::id(), which is a permanent identifier for each molecule that is set immediately after allocation.
Parameters
molecule Molecule object of interest.
Returns
index for molecule within its Species and System.
Definition at line 1056 of file System.cpp.
References McMd::Species::id(), and McMd::Molecule::species().
Referenced by McMd::CfbDoubleRebridgeMove::move(), randomMolecule(), and McMd::McMdConfigIo::write().
Molecule & McMd::System::molecule (int speciesId, int moleculeId) inline
Get a specific Molecule in this System, by integer index.
The moleculeId must be in range 0 <= moleculeId < nMolecule(speciesId). The index associated with a molecule is mutable, and can change when another molecule of the same Species is removed from this System. The value of this index is returned by System::moleculeId().
Parameters
speciesId integer id of the desired Species
moleculeId integer id of molecule within Species and System
Returns
reference to the molecule
Definition at line 1045 of file System.h.
Referenced by loadConfig(), McMd::CfbDoubleRebridgeMove::move(), McMd::RingOctaRebridgeMove::move(), McMd::ComMSD::output(), randomMolecule(), McMd::McMdConfigIo::read(), McMd::LammpsDumpReader::readFrame(), McMd::DdMdTrajectoryReader::readFrame(), McMd::DCDTrajectoryReader::readFrame(), removeAllMolecules(), McMd::AtomMSD::sample(), McMd::ComMSD::sample(), McMd::RingRouseAutoCorr::sample(), McMd::LinearRouseAutoCorr::sample(), McMd::BlockRadiusGyration::sample(), McMd::IntraPairAutoCorr::sample(), McMd::RadiusGyration::sample(), McMd::RingOctaRebridgeMove::scanBridge(), McMd::AtomMSD::setup(), and McMd::ComMSD::setup().
Molecule & McMd::System::randomMolecule (int speciesId)
Get a random Molecule of a specified species in this System.
Parameters
speciesId integer id of the desired Species.
Returns
const reference to the chosen molecule
Definition at line 1067 of file System.cpp.
References Util::Log::file(), molecule(), moleculeId(), nMolecule(), McMd::Simulation::random(), simulation(), Util::Random::uniformInt(), and UTIL_THROW.
Referenced by McMd::RingTetraRebridgeMove::move(), McMd::CfbDoubleRebridgeMove::move(), McMd::AtomDisplaceMove::move(), McMd::CfbEndMove::move(), McMd::CfbRebridgeMove::move(), McMd::RingOctaRebridgeMove::move(), McMd::CfbLinearEndMove::move(), McMd::EndSwapMove::move(), McMd::HomopolymerSemiGrandMove::move(), McMd::CfbReptationMove::move(), McMd::CfbRingRebridgeMove::move(), McMd::CfbReptateMove::move(), and McMd::RigidDisplaceMove::move().
void McMd::System::begin (int speciesId, MoleculeIterator & iterator) inline
Initialize an iterator for molecules of one species in this System.
Parameters
speciesId integer Id for the desired Species (input)
iterator molecule iterator (output)
Definition at line 1055 of file System.h.
Referenced by McMd::McExternalPerturbation< Interaction >::derivative(), McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >::derivative(), McMd::ClusterIdentifier::identifyClusters(), McMd::ClusterIdentifier::isValid(), McMd::MdSystem::kineticEnergy(), McMd::HybridMdMove::move(), McMd::HybridNphMdMove::move(), McMd::ReplicaMove::move(), McMd::McSimulation::readCommands(), McMd::MdSystem::removeDriftVelocity(), McMd::McExternalEnergyAverage::sample(), McMd::McMuExchange::sample(), McMd::CompositionProfile::sample(), McMd::RDF::sample(), McMd::StructureFactor::sample(), McMd::VanHove::sample(), McMd::StructureFactorP::sample(), McMd::IntraStructureFactor::sample(), saveConfig(), McMd::MdSystem::setBoltzmannVelocities(), McMd::MdSystem::setZeroForces(), McMd::MdSystem::setZeroVelocities(), McMd::MdSystem::shiftAtoms(), McMd::NveVvIntegrator::step(), McMd::NvtLangevinIntegrator::step(), McMd::NvtDpdVvIntegrator::step(), McMd::NvtNhIntegrator::step(), McMd::NphIntegrator::step(), McMd::McMdConfigIo::write(), McMd::DdMdConfigIo::write(), and McMd::LammpsConfigIo::write().
void McMd::System::begin (int speciesId, ConstMoleculeIterator & iterator) const inline
Initialize a const iterator for molecules of one species in this System.
Parameters
speciesId integer Id for the desired Species (input)
iterator molecule iterator (output)
Definition at line 1065 of file System.h.
PairFactory & McMd::System::pairFactory ()
Get the PairFactory by reference.
Definition at line 1096 of file System.cpp.
Referenced by McMd::McSystem::loadParameters(), McMd::MdSystem::loadParameters(), McMd::MdSystem::MdSystem(), McMd::McSystem::readParameters(), and McMd::MdSystem::readParameters().
std::string McMd::System::pairStyle () const
Return nonbonded pair style string.
Definition at line 1108 of file System.cpp.
Referenced by McMd::McSystem::loadParameters(), McMd::MdSystem::loadParameters(), McMd::McSystem::readParameters(), and McMd::MdSystem::readParameters().
Factory< BondPotential > & McMd::System::bondFactory ()
Get the associated Factory<BondPotential> by reference.
Definition at line 1116 of file System.cpp.
Referenced by McMd::McSystem::loadParameters(), McMd::MdSystem::loadParameters(), McMd::McSystem::readParameters(), and McMd::MdSystem::readParameters().
std::string McMd::System::bondStyle () const
Return covalent bond style string.
Definition at line 1128 of file System.cpp.
Referenced by McMd::McSystem::loadParameters(), McMd::MdSystem::loadParameters(), McMd::McSystem::readParameters(), and McMd::MdSystem::readParameters().
Factory< AnglePotential > & McMd::System::angleFactory ()
Get the associated AngleFactory by reference.
Definition at line 1136 of file System.cpp.
Referenced by McMd::McSystem::loadParameters(), McMd::MdSystem::loadParameters(), McMd::McSystem::readParameters(), and McMd::MdSystem::readParameters().
std::string McMd::System::angleStyle () const
Return angle potential style string.
Definition at line 1148 of file System.cpp.
Referenced by McMd::McSystem::loadParameters(), McMd::MdSystem::loadParameters(), McMd::McSystem::readParameters(), and McMd::MdSystem::readParameters().
Factory< DihedralPotential > & McMd::System::dihedralFactory ()
Get the associated Dihedral Factory by reference.
Definition at line 1156 of file System.cpp.
Referenced by McMd::McSystem::loadParameters(), McMd::MdSystem::loadParameters(), McMd::McSystem::readParameters(), and McMd::MdSystem::readParameters().
std::string McMd::System::dihedralStyle () const
Return dihedral potential style string.
Definition at line 1168 of file System.cpp.
Referenced by McMd::McSystem::loadParameters(), McMd::MdSystem::loadParameters(), McMd::McSystem::readParameters(), and McMd::MdSystem::readParameters().
Factory< ExternalPotential > & McMd::System::externalFactory ()
Get the associated ExternalPotential factory by reference.
Definition at line 1177 of file System.cpp.
Referenced by McMd::McSystem::loadParameters(), McMd::MdSystem::loadParameters(), McMd::McSystem::readParameters(), and McMd::MdSystem::readParameters().
std::string McMd::System::externalStyle () const
Return external potential style string.
Definition at line 1189 of file System.cpp.
Referenced by McMd::McSystem::loadParameters(), McMd::MdSystem::loadParameters(), McMd::McSystem::readParameters(), and McMd::MdSystem::readParameters().
Factory< BondPotential > & McMd::System::linkFactory ()
Get the associated Link factory by reference.
Definition at line 1197 of file System.cpp.
Referenced by McMd::McSystem::loadParameters(), McMd::MdSystem::loadParameters(), McMd::McSystem::readParameters(), and McMd::MdSystem::readParameters().
std::string McMd::System::linkStyle () const
Return link potential style string.
Definition at line 1209 of file System.cpp.
Referenced by McMd::McSystem::loadParameters(), McMd::MdSystem::loadParameters(), McMd::McSystem::readParameters(), and McMd::MdSystem::readParameters().
LinkMaster & McMd::System::linkMaster () const inline
Get the LinkMaster by reference.
Definition at line 982 of file System.h.
Referenced by McMd::McMdConfigIo::read(), removeAllMolecules(), and McMd::McMdConfigIo::write().
Factory< Perturbation > & McMd::System::perturbationFactory () inline
Get the perturbation factory by reference.
Return the perturbation factory by reference.
Definition at line 1081 of file System.h.
void McMd::System::setExpectPerturbation ()
Set to expect a Perturbation in the parameter file.
Definition at line 823 of file System.cpp.
References hasPerturbation(), newDefaultPerturbationFactory(), and UTIL_THROW.
Referenced by loadPerturbation(), McMd::MdSimulation::setOptions(), and McMd::McSimulation::setOptions().
bool McMd::System::expectPerturbation () const inline
Return true if we expect a perturbation.
Should this system create a Perturbation?
Definition at line 1075 of file System.h.
bool McMd::System::hasPerturbation () const inline
Does this system have an associated Perturbation?
Definition at line 1087 of file System.h.
Referenced by loadReplicaMove(), readPerturbation(), readReplicaMove(), McMd::ReplicaMove::ReplicaMove(), savePerturbation(), saveReplicaMove(), and setExpectPerturbation().
Perturbation & McMd::System::perturbation () const inline
Get the associated Perturbation by reference.
Definition at line 1093 of file System.h.
Referenced by McMd::BennettsMethod::BennettsMethod(), McMd::ReplicaMove::move(), McMd::ReplicaMove::ReplicaMove(), and McMd::BennettsMethod::sample().
bool McMd::System::hasReplicaMove () const inline
Does this system have an associated ReplicaMove?
Definition at line 1103 of file System.h.
ReplicaMove & McMd::System::replicaMove () const inline
Get the associated ReplicaMove by reference.
Definition at line 1109 of file System.h.
Referenced by McMd::McSimulation::simulate().
int McMd::System::id () const inline
Get integer index for this System.
Definition at line 957 of file System.h.
Referenced by setId().
Simulation & McMd::System::simulation () const inline
Get the parent Simulation by reference.
Definition at line 963 of file System.h.
Referenced by allocateMoleculeSets(), McMd::BennettsMethod::BennettsMethod(), McMd::McExternalPerturbation< Interaction >::derivative(), McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >::derivative(), McMd::McPerturbationFactory::factory(), McMd::Generator::generate(), McMd::ClusterIdentifier::initialize(), isEmpty(), McMd::MdSimulation::isValid(), isValid(), McMd::MdSystem::kineticEnergy(), loadConfig(), loadLinkMaster(), McMd::SemiGrandDistribution::loadParameters(), McMd::TypeDistribution::loadParameters(), McMd::AtomMSD::loadParameters(), McMd::CfbLinearEndMove::loadParameters(), McMd::ComMSD::loadParameters(), McMd::RingTetraRebridgeMove::loadParameters(), McMd::RingRouseAutoCorr::loadParameters(), McMd::LinearRouseAutoCorr::loadParameters(), McMd::MdPairEnergyCoefficients::loadParameters(), McMd::RDF::loadParameters(), McMd::McSystem::loadParameters(), McMd::IntraPairAutoCorr::loadParameters(), McMd::CompositionProfile::loadParameters(), McMd::McMuExchange::loadParameters(), McMd::RadiusGyration::loadParameters(), McMd::StructureFactor::loadParameters(), McMd::MdSystem::loadParameters(), McMd::ReplicaMove::loadParameters(), McMd::BlockRadiusGyration::loadParameters(), McMd::StructureFactorP::loadParameters(), McMd::IntraStructureFactor::loadParameters(), loadPotentialStyles(), McMd::ReplicaMove::move(), nAtom(), randomMolecule(), readLinkMaster(), McMd::SemiGrandDistribution::readParameters(), McMd::TypeDistribution::readParameters(), McMd::AtomMSD::readParameters(), McMd::CfbLinearEndMove::readParameters(), McMd::RingTetraRebridgeMove::readParameters(), McMd::ComMSD::readParameters(), McMd::RingRouseAutoCorr::readParameters(), McMd::McMuExchange::readParameters(), McMd::LinearRouseAutoCorr::readParameters(), McMd::MdPairEnergyCoefficients::readParameters(), McMd::RDF::readParameters(), McMd::CompositionProfile::readParameters(), McMd::McSystem::readParameters(), McMd::IntraPairAutoCorr::readParameters(), McMd::RadiusGyration::readParameters(), McMd::StructureFactor::readParameters(), McMd::BlockRadiusGyration::readParameters(), McMd::StructureFactorGrid::readParameters(), McMd::StructureFactorPGrid::readParameters(), McMd::MdSystem::readParameters(), McMd::ReplicaMove::readParameters(), McMd::IntraStructureFactorGrid::readParameters(), McMd::VanHove::readParameters(), McMd::StructureFactorP::readParameters(), McMd::IntraStructureFactor::readParameters(), readPotentialStyles(), removeAllMolecules(), McMd::MdSystem::removeDriftVelocity(), McMd::ReplicaMove::ReplicaMove(), McMd::McExternalEnergyAverage::sample(), McMd::CompositionProfile::sample(), McMd::MdPairEnergyCoefficients::sample(), McMd::RDF::sample(), McMd::StructureFactor::sample(), McMd::VanHove::sample(), McMd::StructureFactorP::sample(), McMd::ReplicaMove::save(), saveConfig(), saveLinkMaster(), McMd::McSystem::saveParameters(), McMd::MdSystem::saveParameters(), savePotentialStyles(), McMd::MdSystem::setBoltzmannVelocities(), setSimulation(), McMd::MdSystem::setZeroForces(), McMd::MdSystem::setZeroVelocities(), McMd::MdSystem::shiftAtoms(), McMd::DdMdConfigIo::write(), and McMd::MdPairEnergyCoefficients::~MdPairEnergyCoefficients().
Boundary & McMd::System::boundary () const inline
Get the Boundary by reference.
Definition at line 972 of file System.h.
Referenced by McMd::McPairPerturbation< Interaction >::derivative(), McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >::derivative(), McMd::ClusterIdentifier::identifyClusters(), McMd::ClusterIdentifier::initialize(), McMd::MdSystem::kineticEnergy(), loadConfig(), McMd::CompositionProfile::makeWaveVectors(), McMd::StructureFactor::makeWaveVectors(), McMd::StructureFactorP::makeWaveVectors(), McMd::HybridNphMdMove::move(), McMd::ReplicaMove::move(), McMd::ComMSD::output(), McMd::McSystem::potentialEnergy(), McMd::DdMdConfigIo::read(), McMd::MdSimulation::readCommands(), McMd::McSimulation::readCommands(), McMd::CompositionProfile::sample(), McMd::BoundaryAverage::sample(), McMd::AtomMSD::sample(), McMd::BondLengthDist::sample(), McMd::McPairEnergyAverage::sample(), McMd::ComMSD::sample(), McMd::RingRouseAutoCorr::sample(), McMd::LinearRouseAutoCorr::sample(), McMd::BlockRadiusGyration::sample(), McMd::RDF::sample(), McMd::IntraPairAutoCorr::sample(), McMd::StructureFactor::sample(), McMd::RadiusGyration::sample(), McMd::StructureFactorGrid::sample(), McMd::VanHove::sample(), McMd::StructureFactorP::sample(), McMd::IntraStructureFactor::sample(), saveConfig(), McMd::RingTetraRebridgeMove::scanBridge(), McMd::AtomMSD::setup(), McMd::ComMSD::setup(), McMd::MdSystem::shiftAtoms(), McMd::NphIntegrator::step(), and McMd::DdMdConfigIo::write().
EnergyEnsemble & McMd::System::energyEnsemble () const inline
Get the EnergyEnsemble by reference.
Definition at line 1003 of file System.h.
Referenced by McMd::McExternalPerturbation< Interaction >::derivative(), McMd::McPairPerturbation< Interaction >::derivative(), McMd::McPairExternalPerturbation< PairInteraction, ExternalInteraction >::derivative(), McMd::HybridNphMdMove::move(), McMd::NvtDpdVvIntegrator::NvtDpdVvIntegrator(), McMd::NvtNhIntegrator::NvtNhIntegrator(), McMd::McEnergyPerturbation::parameter(), McMd::McSystem::potentialEnergy(), McMd::McMuExchange::sample(), McMd::McEnergyPerturbation::setParameter(), McMd::NvtLangevinIntegrator::setup(), McMd::NvtDpdVvIntegrator::setup(), McMd::SystemMove::SystemMove(), and McMd::McStressAutoCorrelation::~McStressAutoCorrelation().
BoundaryEnsemble & McMd::System::boundaryEnsemble () const inline
Get the BoundaryEnsemble by reference.
Definition at line 1012 of file System.h.
Referenced by McMd::HybridNphMdMove::move(), and McMd::NphIntegrator::step().
FileMaster & McMd::System::fileMaster () const inline
Get the associated FileMaster by reference.
Definition at line 1021 of file System.h.
Referenced by McMd::CfbReptationMove::output(), McMd::CfbReptateMove::output(), McMd::MdVirialStressTensorAverage::readParameters(), McMd::McVirialStressTensorAverage::readParameters(), McMd::ReplicaMove::ReplicaMove(), and setFileMaster().
bool McMd::System::isCopy () const inline
Was this System instantiated with the copy constructor?
Definition at line 1030 of file System.h.
Referenced by McMd::MdSystem::loadParameters(), loadParameters(), McMd::MdSystem::readParameters(), readParameters(), McMd::MdSystem::saveParameters(), saveParameters(), McMd::MdSystem::~MdSystem(), and ~System().
bool McMd::System::isValid () const virtual
Return true if valid, or throw Exception.
Reimplemented in McMd::MdSystem, and McMd::McSystem.
Definition at line 1236 of file System.cpp.
References McMd::LinkMaster::isValid(), nMolecule(), McMd::Simulation::nSpecies(), simulation(), McMd::Molecule::system(), and UTIL_THROW.
Referenced by McMd::McSystem::isValid(), McMd::MdSystem::isValid(), and readConfig().
Boundary& McMd::System::maxBoundary () const protected
Get the maximum Boundary by reference.
ConfigIo * McMd::System::newDefaultConfigIo () protected virtual
Return a pointer to a new default ConfigIo.
Reimplemented in McMd::MdSystem.
Definition at line 699 of file System.cpp.
Referenced by readConfig(), and writeConfig().
Factory< ConfigIo > * McMd::System::newDefaultConfigIoFactory () protected virtual
Return a pointer to a new default ConfigIoFactory.
Definition at line 778 of file System.cpp.
Referenced by configIoFactory(), and setConfigIo().
Factory< TrajectoryReader > * McMd::System::newDefaultTrajectoryReaderFactory () protected virtual
Return a pointer to a new default TrajectoryReaderFactory.
Definition at line 815 of file System.cpp.
Referenced by trajectoryReaderFactory().
virtual Factory<Perturbation>* McMd::System::newDefaultPerturbationFactory () inline protected virtual
Return a pointer to the default perturbation Factory.
Reimplemented in McMd::McSystem.
Definition at line 606 of file System.h.
Referenced by setExpectPerturbation().
void McMd::System::readPerturbation (std::istream & in) protected
Read the perturbation parameter block (if any)
Parameters
in input parameter stream
Definition at line 855 of file System.cpp.
References Util::ParamComposite::className(), hasPerturbation(), Util::Factory< Data >::readObject(), and UTIL_THROW.
Referenced by McMd::McSystem::readParameters(), and McMd::MdSystem::readParameters().
void McMd::System::loadPerturbation (Serializable::IArchive & ar) protected
Load the perturbation parameter block (if any)
Parameters
ar input/saving archive
Definition at line 874 of file System.cpp.
References Util::ParamComposite::className(), Util::MpiFileIo::hasIoCommunicator(), Util::Factory< Data >::loadObject(), setExpectPerturbation(), and UTIL_THROW.
Referenced by McMd::McSystem::loadParameters(), and McMd::MdSystem::loadParameters().
void McMd::System::savePerturbation (Serializable::OArchive & ar) protected
Save the perturbation parameter block (if any)
Parameters
ar output/saving archive
Definition at line 899 of file System.cpp.
References Util::ParamComposite::className(), hasPerturbation(), and McMd::Perturbation::save().
Referenced by McMd::McSystem::saveParameters(), and McMd::MdSystem::saveParameters().
void McMd::System::readReplicaMove (std::istream & in) protected
Read the ReplicaMove parameter block (if any)
Parameters
in input parameter stream
Definition at line 914 of file System.cpp.
References hasPerturbation(), and Util::ParamComposite::readParamComposite().
Referenced by McMd::McSystem::readParameters().
void McMd::System::loadReplicaMove (Serializable::IArchive & ar) protected
Read the ReplicaMove parameter block (if any)
Parameters
ar input/loading archive
Definition at line 931 of file System.cpp.
References hasPerturbation(), and Util::ParamComposite::loadParamComposite().
Referenced by McMd::McSystem::loadParameters().
void McMd::System::saveReplicaMove (Serializable::OArchive & ar) protected
Save the ReplicaMove parameter block (if any)
Parameters
ar output/saving archive
Definition at line 948 of file System.cpp.
References hasPerturbation(), and McMd::ReplicaMove::save().
Referenced by McMd::McSystem::saveParameters().
void McMd::System::allocateMoleculeSets () protected
Allocate and initialize molecule sets for all species.
This function is called within the Simulation::initialize() private member function to allocate and initialize an array of MoleculeSet objects for all Species for this System.
Preconditions: This System must be associated with a parent Simulation, and all Species objects must have been initialized by calling SpeciesManager::readParameters().
Definition at line 963 of file System.cpp.
References McMd::Simulation::allocateMoleculeSet(), McMd::Simulation::nSpecies(), and simulation().
Referenced by McMd::McSystem::loadParameters(), McMd::MdSystem::loadParameters(), loadParameters(), McMd::McSystem::readParameters(), McMd::MdSystem::readParameters(), and readParameters().
void McMd::System::readFileMaster (std::istream & in) protected
Read FileMaster parameters, if none yet exists.
If no FileMaster exists, create and read one.
If no FileMaster exists, this function creates one and reads paramters to initialize one. If there is already a FileMaster, it does nothing.
Invoked in implementation of readParameters().
Parameters
in input parameter stream
Definition at line 382 of file System.cpp.
References Util::ParamComposite::readParamComposite().
Referenced by McMd::McSystem::readParameters(), McMd::MdSystem::readParameters(), and readParameters().
void McMd::System::loadFileMaster (Serializable::IArchive & ar) protected
Load FileMaster data from archive, if necessary.
Parameters
ar input/loading archive
Definition at line 401 of file System.cpp.
References Util::ParamComposite::loadParamComposite().
Referenced by McMd::McSystem::loadParameters(), McMd::MdSystem::loadParameters(), and loadParameters().
void McMd::System::saveFileMaster (Serializable::OArchive & ar) protected
If necessary, save FileMaster to archive.
Parameters
ar output/saving archive
Definition at line 418 of file System.cpp.
References Util::FileMaster::save().
Referenced by McMd::McSystem::saveParameters(), McMd::MdSystem::saveParameters(), and saveParameters().
void McMd::System::readPotentialStyles (std::istream & in) protected
Read potential style parameter strings.
Parameters
in input parameter stream
Definition at line 428 of file System.cpp.
References McMd::Simulation::hasExternal(), McMd::Simulation::nAngleType(), McMd::Simulation::nBondType(), McMd::Simulation::nDihedralType(), McMd::Simulation::nLinkType(), and simulation().
Referenced by McMd::McSystem::readParameters(), McMd::MdSystem::readParameters(), and readParameters().
void McMd::System::loadPotentialStyles (Serializable::IArchive & ar) protected
Load potential style strings from an archive.
Parameters
ar input/loading archive
Definition at line 468 of file System.cpp.
References McMd::Simulation::hasExternal(), McMd::Simulation::nAngleType(), McMd::Simulation::nBondType(), McMd::Simulation::nDihedralType(), McMd::Simulation::nLinkType(), and simulation().
Referenced by McMd::McSystem::loadParameters(), McMd::MdSystem::loadParameters(), and loadParameters().
void McMd::System::savePotentialStyles (Serializable::OArchive & ar) protected
Save potential style strings.
Parameters
ar output/saving archive
Definition at line 508 of file System.cpp.
References simulation().
Referenced by McMd::McSystem::saveParameters(), McMd::MdSystem::saveParameters(), and saveParameters().
void McMd::System::readEnsembles (std::istream & in) protected
Read energy and boundary ensemble parameters.
Parameters
in input parameter stream
Definition at line 548 of file System.cpp.
References Util::ParamComposite::readParamComposite().
Referenced by McMd::McSystem::readParameters(), McMd::MdSystem::readParameters(), and readParameters().
void McMd::System::loadEnsembles (Serializable::IArchive & ar) protected
Load energy and boundary ensembles from archive.
Parameters
ar input/loading archive
Definition at line 557 of file System.cpp.
References Util::ParamComposite::loadParamComposite().
Referenced by McMd::McSystem::loadParameters(), McMd::MdSystem::loadParameters(), and loadParameters().
void McMd::System::saveEnsembles (Serializable::OArchive & ar) protected
Save energy and boundary ensembles.
Parameters
ar output/saving archive
Definition at line 566 of file System.cpp.
References Util::BoundaryEnsemble::save(), and Util::EnergyEnsemble::save().
Referenced by McMd::McSystem::saveParameters(), McMd::MdSystem::saveParameters(), and saveParameters().
void McMd::System::readLinkMaster (std::istream & in) protected
Read the LinkMaster parameters.
Parameters
in input parameter stream
Definition at line 573 of file System.cpp.
References Util::ParamComposite::readParamComposite(), and simulation().
Referenced by McMd::McSystem::readParameters(), McMd::MdSystem::readParameters(), and readParameters().
void McMd::System::loadLinkMaster (Serializable::IArchive & ar) protected
Load the LinkMaster.
Parameters
ar input archive.
Definition at line 581 of file System.cpp.
References Util::ParamComposite::loadParamComposite(), and simulation().
Referenced by McMd::McSystem::loadParameters(), McMd::MdSystem::loadParameters(), and loadParameters().
void McMd::System::saveLinkMaster (Serializable::OArchive & ar) protected
Save the LinkMaster.
Parameters
ar output archive.
Definition at line 589 of file System.cpp.
References Util::ParamComposite::loadParamComposite(), Util::ParamComposite::readParamComposite(), Util::ParamComposite::save(), and simulation().
Referenced by McMd::McSystem::saveParameters(), McMd::MdSystem::saveParameters(), and saveParameters().
The documentation for this class was generated from the following files:
System.h
System.cpp