Simpatico: Util::SSet< Data, Capacity > Class Template Reference
Util::SSet< Data, Capacity > Class Template Reference
Pointer Arrays
Detailed Description
template<typename Data, int Capacity>
class Util::SSet< Data, Capacity >
Statically allocated array of pointers to an unordered set.
An SSet is a statically allocated array that holds pointers to a set of objects. It implements the same interface as PArray and FPArray, plus additional remove() and index() methods. As for any pointer array container, the [] operator returns an associated object by reference .
An SSet holds a set of pointers in a contiguous array. The size is the number of pointers now in the container, and the Capacity is the maximum number it can hold. The class is implemented as a wrapper for a statically allocated C array of Capacity elements.
The append method adds a pointer to the end of the sequence. The remove method removes an object from the set, or throws an exception if the object is not found in the set. As for an ArraySet, the remove method repacks the sequence of pointers by moving the last element to the position of the element that is being removed. Removal of an element thus generally changes the order in which the remaining elements are stored.
Definition at line 43 of file SSet.h.
#include <SSet.h>
Public Member Functions
SSet ()
Default constructor.
SSet (const SSet< Data, Capacity > &other)
Copy constructor.
SSet< Data, Capacity > & operator= (const SSet< Data, Capacity > &other)
Assignment, element by element.
~SSet ()
Destructor.
void append (Data &data)
Add an object to the set.
void remove (const Data &data)
Remove an object from the set.
void clear ()
Set logical size to zero and nullify all elements.
int capacity () const
Return physical capacity of array.
int size () const
Return logical size of this array.
bool isElement (const Data &data) const
Is an object an element of the set?
int index (const Data &data) const
Return the current index of an object within the set, if any.
void begin (PArrayIterator< Data > &iterator)
Set a PArrayIterator to the beginning of this Array.
void begin (ConstPArrayIterator< Data > &iterator) const
Set a ConstPArrayIterator to the beginning of this Array.
Data & operator[] (int i)
Mimic C array subscripting.
const Data & operator[] (int i) const
Mimic C array subscripting.
Protected Attributes
Data * ptrs_ [Capacity]
Array of pointers to Data objects.
int size_
Logical size of array (number of elements used).
Constructor & Destructor Documentation
template<typename Data , int Capacity> Util::SSet< Data, Capacity >::SSet () [inline]
Default constructor.
Constructor.
Definition at line 177 of file SSet.h.
template<typename Data , int Capacity> Util::SSet< Data, Capacity >::SSet (const SSet< Data, Capacity > & other)
Copy constructor.
Copies all pointers.
Parameters:
other the SSet to be copied.
Definition at line 185 of file SSet.h.
References Util::SSet< Data, Capacity >::ptrs_, and Util::SSet< Data, Capacity >::size_.
template<typename Data , int Capacity> Util::SSet< Data, Capacity >::~SSet () [inline]
Destructor.
Definition at line 240 of file SSet.h.
Member Function Documentation
template<typename Data , int Capacity> SSet< Data, Capacity > & Util::SSet< Data, Capacity >::operator= (const SSet< Data, Capacity > & other)
Assignment, element by element.
Parameters:
other the rhs SSet
Definition at line 209 of file SSet.h.
References Util::SSet< Data, Capacity >::size_, and UTIL_THROW.
template<typename Data , int Capacity> void Util::SSet< Data, Capacity >::append (Data & data) [inline]
Add an object to the set.
Append data to the end of the array.
Appends a pointer to the object to the end of the sequence.
Parameters:
data Data to add to end of array.
data Data to add to end of array.
Definition at line 315 of file SSet.h.
References UTIL_THROW.
template<typename Data , int Capacity> void Util::SSet< Data, Capacity >::remove (const Data & data)
Remove an object from the set.
Removal of an object generally changes the storage order of the remaining objects.
Exceptions:
Exception if object data is not in the Set.
Parameters:
data object to be removed.
Definition at line 340 of file SSet.h.
References UTIL_THROW.
template<typename Data , int Capacity> void Util::SSet< Data, Capacity >::clear () [inline]
Set logical size to zero and nullify all elements.
Clear out the container.
Definition at line 328 of file SSet.h.
template<typename Data , int Capacity> int Util::SSet< Data, Capacity >::capacity () const [inline]
Return physical capacity of array.
Definition at line 247 of file SSet.h.
template<typename Data , int Capacity> int Util::SSet< Data, Capacity >::size () const [inline]
Return logical size of this array.
Definition at line 254 of file SSet.h.
Referenced by McMd::LinkPotentialImpl< Interaction >::atomEnergy().
template<typename Data , int Capacity> bool Util::SSet< Data, Capacity >::isElement (const Data & data) const
Is an object an element of the set?
Return true if an object is in the set, false otherwise.
Parameters:
data object of interest.
Definition at line 372 of file SSet.h.
template<typename Data , int Capacity> int Util::SSet< Data, Capacity >::index (const Data & data) const
Return the current index of an object within the set, if any.
Return the current index of an element within the set, or return -1 if the element is not in the set.
This method returns the current index of the pointer to object data within this SSet, in the range 0 < index < size() - 1. The method returns -1 if data is the object is not in the set.
Throws an exception if data is not in the associated array.
Parameters:
data object of interest.
Returns:
current index of pointer to element within this SSet.
Definition at line 393 of file SSet.h.
template<typename Data , int Capacity> void Util::SSet< Data, Capacity >::begin (PArrayIterator< Data > & iterator) [inline]
Set a PArrayIterator to the beginning of this Array.
Parameters:
iterator PArrayIterator, initialized on output.
Definition at line 263 of file SSet.h.
References Util::PArrayIterator< Data >::setCurrent(), and Util::PArrayIterator< Data >::setEnd().
template<typename Data , int Capacity> void Util::SSet< Data, Capacity >::begin (ConstPArrayIterator< Data > & iterator) const [inline]
Set a ConstPArrayIterator to the beginning of this Array.
Set a PArrayIterator to the beginning of this Array.
Parameters:
iterator ConstPArrayIterator, initialized on output.
iterator PArrayIterator, initialized on output.
Definition at line 275 of file SSet.h.
References Util::ConstPArrayIterator< Data >::setCurrent(), and Util::ConstPArrayIterator< Data >::setEnd().
template<typename Data , int Capacity> Data & Util::SSet< Data, Capacity >::operator[] (int i) [inline]
Mimic C array subscripting.
Parameters:
i array index
Returns:
reference to element i
Definition at line 288 of file SSet.h.
template<typename Data , int Capacity> const Data & Util::SSet< Data, Capacity >::operator[] (int i) const [inline]
Mimic C array subscripting.
Parameters:
i array index
Returns:
const reference to element i
Definition at line 302 of file SSet.h.
Member Data Documentation
template<typename Data, int Capacity> Data* Util::SSet< Data, Capacity >::ptrs_[Capacity] [protected]
Array of pointers to Data objects.
Definition at line 164 of file SSet.h.
Referenced by Util::SSet< Data, Capacity >::SSet().
template<typename Data, int Capacity> int Util::SSet< Data, Capacity >::size_ [protected]
Logical size of array (number of elements used).
Definition at line 167 of file SSet.h.
Referenced by Util::SSet< Data, Capacity >::operator=(), and Util::SSet< Data, Capacity >::SSet().
The documentation for this class was generated from the following file:
SSet.h