Simpatico: McMd::McWriteRestart Class Reference
McMd::McWriteRestart Class Reference
Diagnostics
Detailed Description
Periodically write restart file.
Definition at line 26 of file McWriteRestart.h.
#include <McWriteRestart.h>
Public Member Functions
McWriteRestart (McSimulation &simulation)
Constructor.
virtual ~McWriteRestart ()
Destructor.
virtual void readParameters (std::istream &in)
Read interval and output file name.
void sample (long iStep)
Write restart file.
Constructor & Destructor Documentation
McMd::McWriteRestart::McWriteRestart (McSimulation & simulation)
Constructor.
Parameters:
simulation parent McSimulation object.
Definition at line 26 of file McWriteRestart.cpp.
References Util::ParamComposite::setClassName().
virtual McMd::McWriteRestart::~McWriteRestart () [inline, virtual]
Destructor.
Definition at line 41 of file McWriteRestart.h.
Member Function Documentation
void McMd::McWriteRestart::readParameters (std::istream & in) [virtual]
Read interval and output file name.
Parameters:
in input parameter file
Reimplemented from McMd::Diagnostic.
Definition at line 34 of file McWriteRestart.cpp.
References McMd::Diagnostic::readInterval(), and McMd::Diagnostic::readOutputFileName().
void McMd::McWriteRestart::sample (long iStep) [virtual]
Write restart file.
Parameters:
iStep MC step index
Implements McMd::Diagnostic.
Definition at line 46 of file McWriteRestart.cpp.
References McMd::Diagnostic::isAtInterval(), McMd::Diagnostic::outputFileName(), and McMd::McSimulation::writeRestart().
The documentation for this class was generated from the following files:
McWriteRestart.h
McWriteRestart.cpp