Simpatico: Inter::HarmonicBond Class Reference
Inter::HarmonicBond Class Reference
Bond Interactions
Detailed Description
A harmonic covalent bond potential.
Implements a harmonic potential with a nonzero rest length.
See Also
HarmonicBond
Bond Interaction Class Interface
Definition at line 35 of file HarmonicBond.h.
#include <HarmonicBond.h>
Public Member Functions
HarmonicBond ()
Default constructor.
HarmonicBond (const HarmonicBond &other)
Copy constructor.
HarmonicBond & operator= (const HarmonicBond &other)
Assignment.
void setNBondType (int nBondType)
Set the number of bond types.
void readParameters (std::istream &in)
Read bond interaction parameters from input stream.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
double energy (double rSq, int type) const
Returns potential energy for one bond.
double forceOverR (double rSq, int type) const
Returns force/distance for one bond, for use in MD.
double randomBondLength (Random *random, double beta, int type) const
Return bond length chosen from equilibrium distribution.
void set (std::string name, int type, double value)
Modify a parameter, identified by a string.
double stiffness (int bondType) const
Returns bond stiffness.
double length (int bondType) const
Returns bond length.
double get (std::string name, int type) const
Get a parameter value, identified by a string.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value, bool isRequired)
Add a new ScalarParam < Type > object, and read its value.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired)
Add and read a C array parameter.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired)
Add and read a DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a required DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and read a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > C 2D array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add a DArray < Type > parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Constructor & Destructor Documentation
Inter::HarmonicBond::HarmonicBond ()
Default constructor.
Definition at line 22 of file HarmonicBond.cpp.
References Util::ParamComposite::setClassName().
Inter::HarmonicBond::HarmonicBond (const HarmonicBond & other)
Copy constructor.
Definition at line 35 of file HarmonicBond.cpp.
Member Function Documentation
HarmonicBond & Inter::HarmonicBond::operator= (const HarmonicBond & other)
Assignment.
Definition at line 47 of file HarmonicBond.cpp.
void Inter::HarmonicBond::setNBondType (int nBondType)
Set the number of bond types.
Parameters
nBondType number of bond types
Definition at line 60 of file HarmonicBond.cpp.
References UTIL_THROW.
void Inter::HarmonicBond::readParameters (std::istream & in) virtual
Read bond interaction parameters from input stream.
Format: kappa CArray<double> length CArray<double>
Precondition
nBondType must be set, by calling setNBondType().
Parameters
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 71 of file HarmonicBond.cpp.
References UTIL_THROW.
void Inter::HarmonicBond::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 87 of file HarmonicBond.cpp.
References UTIL_THROW.
void Inter::HarmonicBond::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 101 of file HarmonicBond.cpp.
References Util::BinaryFileOArchive::pack().
double Inter::HarmonicBond::energy (double rSq, int type) const inline
Returns potential energy for one bond.
Parameters
rSq square of distance between bonded particles.
type type of bond.
Definition at line 186 of file HarmonicBond.h.
double Inter::HarmonicBond::forceOverR (double rSq, int type) const inline
Returns force/distance for one bond, for use in MD.
A positive return value represents a repulsive radial force.
Parameters
rSq square of distance between bonded particles.
type type of bond.
Returns
scalar repulsive force divided by distance.
Definition at line 196 of file HarmonicBond.h.
double Inter::HarmonicBond::randomBondLength (Random * random, double beta, int type) const
Return bond length chosen from equilibrium distribution.
This function returns a bond length chosen from the Boltzmann distribution of lengths for bonds of random orientation. The distribution P(l) of values of the length l is proportional to l*l*exp[-beta*phi(l) ], where phi(l) is the bond energy.
Parameters
random pointer to random number generator object.
beta inverse temperature
type bond type
Returns
random bond length chosen from equilibrium distribution.
Definition at line 133 of file HarmonicBond.cpp.
References Util::Random::gaussian(), and Util::Random::uniform().
void Inter::HarmonicBond::set (std::string name, int type, double value)
Modify a parameter, identified by a string.
Parameters
name parameter name
type bond type index
value new value of parameter
Definition at line 156 of file HarmonicBond.cpp.
References UTIL_THROW.
double Inter::HarmonicBond::stiffness (int bondType) const inline
Returns bond stiffness.
Definition at line 168 of file HarmonicBond.h.
double Inter::HarmonicBond::length (int bondType) const inline
Returns bond length.
Definition at line 177 of file HarmonicBond.h.
double Inter::HarmonicBond::get (std::string name, int type) const
Get a parameter value, identified by a string.
Parameters
name parameter name
type bond type index 1
Definition at line 171 of file HarmonicBond.cpp.
References UTIL_THROW.
The documentation for this class was generated from the following files:
HarmonicBond.h
HarmonicBond.cpp