Simpatico: McMd::SliplinkMcMoveFactory Class Reference
McMd::SliplinkMcMoveFactory Class Reference
Detailed Description
Custom McMoveFactory.
Definition at line 17 of file SliplinkMcMoveFactory.h.
#include <SliplinkMcMoveFactory.h>
Public Member Functions
SliplinkMcMoveFactory (McSimulation &simulation, McSystem &system)
Constructor.
virtual McMove * factory (const std::string &className) const
Return pointer to a new McMove object.
Public Member Functions inherited from McMd::McMoveFactory
McMoveFactory (McSimulation &simulation, McSystem &system)
Constructor.
Public Member Functions inherited from Util::Factory< McMove >
Factory ()
Constructor.
virtual ~Factory ()
Destructor.
void addSubfactory (Factory< McMove > &subfactory)
Add a new subfactory to the list.
McMove * readObject (std::istream &in, ParamComposite &parent, std::string &className, bool &isEnd)
Read a class name, instantiate an object, and read its parameters.
McMove * loadObject (Serializable::IArchive &ar, ParamComposite &parent, std::string &className)
Load a class name, instantiate an object, and load the object.
Additional Inherited Members
Protected Member Functions inherited from McMd::McMoveFactory
McSimulation & simulation () const
Return reference to parent Simulation.
McSystem & system () const
Return reference to parent McSystem.
Protected Member Functions inherited from Util::Factory< McMove >
McMove * trySubfactories (const std::string &className) const
Search through subfactories for match.
void setIoCommunicator (MPI::Intracomm &communicator)
Set associated Mpi communicator.
bool hasIoCommunicator () const
Does this factory have a param communicator?
Constructor & Destructor Documentation
McMd::SliplinkMcMoveFactory::SliplinkMcMoveFactory (McSimulation & simulation, McSystem & system)
Constructor.
Parameters
simulation parent simulation
system parent system
Definition at line 20 of file SliplinkMcMoveFactory.cpp.
Member Function Documentation
McMove * McMd::SliplinkMcMoveFactory::factory (const std::string & className) const virtual
Return pointer to a new McMove object.
Parameters
className name of a subclass of McMove.
Returns
base class pointer to a new instance of className.
Reimplemented from McMd::McMoveFactory.
Definition at line 28 of file SliplinkMcMoveFactory.cpp.
References McMd::McMoveFactory::factory(), McMd::McMoveFactory::system(), and Util::Factory< McMove >::trySubfactories().
The documentation for this class was generated from the following files:
SliplinkMcMoveFactory.h
SliplinkMcMoveFactory.cpp