Simpatico: Inter::CompensatedPair< BarePair, LinkPotential > Class Template Reference
Inter::CompensatedPair< BarePair, LinkPotential > Class Template Reference
Detailed Description
template<class BarePair, class LinkPotential>
class Inter::CompensatedPair< BarePair, LinkPotential >
Compensated pair potential for transient gel.
This class is intended for use in a model with transient crosslinks that can be created or destroyed at fixed chemical potential.
Definition at line 32 of file CompensatedPair.h.
#include <CompensatedPair.h>
Public Member Functions
CompensatedPair ()
Constructor.
Mutators
void readParam (std::istream &in)
Read epsilon and sigma, initialize other variables.
void setNAtomType (int nAtomType)
Set nAtomType value.
void setEpsilon (int i, int j, double epsilon)
Set LJ interaction energy for a specific pair of Atom types.
void set (std::string name, int i, int j, double value)
Modify a parameter, identified by a string.
Accessors
double maxPairCutoff () const
Get maximum of pair cutoff distance, for all atom type pairs.
double energy (double rsq, int i, int j) const
Returns interaction energy for a single pair of particles.
double forceOverR (double rsq, int i, int j) const
Returns ratio of scalar pair interaction force to pair separation.
Other Accessors
double epsilon (int i, int j) const
Get LJ interaction energy for a specific pair of Atom types.
double get (std::string name, int i, int j) const
Get a parameter value, identified by a string.
std::string className () const
Return name of instantiated class.
Constructor & Destructor Documentation
template<class BarePair , class LinkPotential > Inter::CompensatedPair< BarePair, LinkPotential >::CompensatedPair ()
Constructor.
Definition at line 176 of file CompensatedPair.h.
Member Function Documentation
template<class BarePair , class LinkPotential > void Inter::CompensatedPair< BarePair, LinkPotential >::readParam (std::istream & in) [virtual]
Read epsilon and sigma, initialize other variables.
Precondition:
nAtomType must be set, by calling setNAtomType().
Parameters:
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 208 of file CompensatedPair.h.
References Util::End::readParam(), Util::Begin::readParam(), and Util::ParamComponent::setIndent().
template<class BarePair , class LinkPotential > void Inter::CompensatedPair< BarePair, LinkPotential >::setNAtomType (int nAtomType)
Set nAtomType value.
Parameters:
nAtomType number of atom types.
Definition at line 258 of file CompensatedPair.h.
template<class BarePair , class LinkPotential > void Inter::CompensatedPair< BarePair, LinkPotential >::setEpsilon (int i, int j, double epsilon)
Set LJ interaction energy for a specific pair of Atom types.
Parameters:
i type of Atom 1
j type of Atom 2
epsilon LJ energy parameter
Definition at line 268 of file CompensatedPair.h.
template<class BarePair , class LinkPotential > void Inter::CompensatedPair< BarePair, LinkPotential >::set (std::string name, int i, int j, double value)
Modify a parameter, identified by a string.
Parameters:
name parameter name
i atom type index 1
j atom type index 2
value new value of parameter
Definition at line 313 of file CompensatedPair.h.
References UTIL_THROW.
template<class BarePair , class LinkPotential > double Inter::CompensatedPair< BarePair, LinkPotential >::maxPairCutoff () const
Get maximum of pair cutoff distance, for all atom type pairs.
Definition at line 276 of file CompensatedPair.h.
template<class BarePair , class LinkPotential > double Inter::CompensatedPair< BarePair, LinkPotential >::energy (double rsq, int i, int j) const [inline]
Returns interaction energy for a single pair of particles.
Parameters:
rsq square of distance between particles
i type of particle 1
j type of particle 2
Returns:
pair interaction energy
Definition at line 284 of file CompensatedPair.h.
template<class BarePair , class LinkPotential > double Inter::CompensatedPair< BarePair, LinkPotential >::forceOverR (double rsq, int i, int j) const [inline]
Returns ratio of scalar pair interaction force to pair separation.
Multiply this quantity by the components of the separation vector to obtain the force vector. A positive value for the return value represents a repulsive force between a pair of particles.
Parameters:
rsq square of distance between particles
i type of particle 1
j type of particle 2
Returns:
force divided by distance
Definition at line 299 of file CompensatedPair.h.
template<class BarePair, class LinkPotential> double Inter::CompensatedPair< BarePair, LinkPotential >::epsilon (int i, int j) const
Get LJ interaction energy for a specific pair of Atom types.
Parameters:
i type of Atom 1
j type of Atom 2
Returns:
epsilon_[i][j]
template<class BarePair , class LinkPotential > double Inter::CompensatedPair< BarePair, LinkPotential >::get (std::string name, int i, int j) const
Get a parameter value, identified by a string.
Parameters:
name parameter name
i atom type index 1
j atom type index 2
Definition at line 327 of file CompensatedPair.h.
References UTIL_THROW.
template<class BarePair , class LinkPotential > std::string Inter::CompensatedPair< BarePair, LinkPotential >::className () const
Return name of instantiated class.
Definition at line 342 of file CompensatedPair.h.
The documentation for this class was generated from the following file:
CompensatedPair.h