Simpatico: Util::Constants Class Reference
Util::Constants Class Reference
Mathematics
Detailed Description
Mathematical constants.
Definition at line 22 of file Constants.h.
#include <Constants.h>
Static Public Member Functions
static void initStatic ()
Initialize static constants.
Static Public Attributes
static const double Pi = 2.0*acos(0.0)
Trigonometric constant Pi.
static const std::complex< double > Im = std::complex<double>(0.0, 1.0)
Square root of -1.
Member Function Documentation
void Util::Constants::initStatic () [static]
Initialize static constants.
Definition at line 22 of file Constants.cpp.
Referenced by Util::initStatic().
Member Data Documentation
const double Util::Constants::Pi = 2.0*acos(0.0) [static]
Trigonometric constant Pi.
Definition at line 35 of file Constants.h.
Referenced by Util::MonoclinicBoundary::isValid(), Util::OrthorhombicBoundary::isValid(), Util::MonoclinicBoundary::MonoclinicBoundary(), Util::OrthorhombicBoundary::OrthorhombicBoundary(), Inter::CosineSqAngle::randomAngle(), Inter::HarmonicAngle::randomAngle(), Inter::CosineAngle::randomAngle(), Inter::CosineSqAngle::readParameters(), Inter::HarmonicAngle::readParameters(), and DdMd::OrderParamNucleation::sample().
const std::complex< double > Util::Constants::Im = std::complex<double>(0.0, 1.0) [static]
Square root of -1.
Definition at line 40 of file Constants.h.
Referenced by McMd::StructureFactor::sample(), DdMd::AsymmSF::sample(), DdMd::StructureFactor::sample(), DdMd::VanHove::sample(), McMd::VanHove::sample(), McMd::StructureFactorP::sample(), and McMd::IntraStructureFactor::sample().
The documentation for this class was generated from the following files:
Constants.h
Constants.cpp