Simpatico: DdMd::NveIntegrator Class Reference
DdMd::NveIntegrator Class Reference
MD Integrators
Detailed Description
A velocity-Verlet constant energy integrator.
Definition at line 24 of file NveIntegrator.h.
#include <NveIntegrator.h>
Public Member Functions
NveIntegrator (Simulation &simulation)
Constructor.
~NveIntegrator ()
Destructor.
void readParam (std::istream &in)
Read required parameters.
void setup ()
Setup state just before integration.
Protected Member Functions
virtual void integrateStep1 ()
Execute first step of two-step integrator.
virtual void integrateStep2 ()
Execute secodn step of two-step integrator.
Constructor & Destructor Documentation
DdMd::NveIntegrator::NveIntegrator (Simulation & simulation)
Constructor.
Definition at line 29 of file NveIntegrator.cpp.
DdMd::NveIntegrator::~NveIntegrator ()
Destructor.
Definition at line 36 of file NveIntegrator.cpp.
Member Function Documentation
void DdMd::NveIntegrator::readParam (std::istream & in) [virtual]
Read required parameters.
For velocity-verlet algorithm, reads the time step dt.
Reimplemented from Util::ParamComposite.
Definition at line 42 of file NveIntegrator.cpp.
References Util::DArray< Data >::allocate(), Util::DArray< Data >::isAllocated(), DdMd::Simulation::nAtomType(), DdMd::SimulationAccess::nAtomType(), and DdMd::SimulationAccess::simulation().
void DdMd::NveIntegrator::setup () [virtual]
Setup state just before integration.
Must be called before run() method.
Implements DdMd::Integrator.
Definition at line 55 of file NveIntegrator.cpp.
References DdMd::SimulationAccess::atomStorage(), DdMd::Simulation::atomType(), DdMd::SimulationAccess::boundary(), DdMd::PairPotential::buildCellList(), DdMd::PairPotential::buildPairList(), Util::Array< Data >::capacity(), DdMd::AtomStorage::clearSnapshot(), DdMd::Simulation::computeForces(), DdMd::Simulation::diagnosticManager(), DdMd::Exchanger::exchange(), DdMd::SimulationAccess::exchanger(), DdMd::AtomStorage::makeSnapshot(), DdMd::AtomType::mass(), DdMd::SimulationAccess::nAtomType(), DdMd::SimulationAccess::pairPotential(), DdMd::DiagnosticManager::setup(), DdMd::Integrator::setupAtoms(), DdMd::SimulationAccess::simulation(), and DdMd::AtomStorage::transformGenToCart().
void DdMd::NveIntegrator::integrateStep1 () [protected, virtual]
Execute first step of two-step integrator.
Implements DdMd::TwoStepIntegrator.
Definition at line 83 of file NveIntegrator.cpp.
References DdMd::SimulationAccess::atomStorage(), DdMd::AtomStorage::begin(), Util::Vector::multiply(), and Util::PArrayIterator< Data >::notEnd().
void DdMd::NveIntegrator::integrateStep2 () [protected, virtual]
Execute secodn step of two-step integrator.
Implements DdMd::TwoStepIntegrator.
Definition at line 103 of file NveIntegrator.cpp.
References DdMd::SimulationAccess::atomStorage(), DdMd::AtomStorage::begin(), Util::Vector::multiply(), Util::PArrayIterator< Data >::notEnd(), Util::Signal< T >::notify(), DdMd::SimulationAccess::simulation(), and DdMd::Simulation::velocitySignal().
The documentation for this class was generated from the following files:
NveIntegrator.h
NveIntegrator.cpp