Simpatico: Tools::TypeMap Class Reference
Tools::TypeMap Class Reference
Tools namespace » Storage
Detailed Description
Map between type names and type ids.
Definition at line 26 of file TypeMap.h.
#include <TypeMap.h>
Public Member Functions
TypeMap ()
Constructor.
~TypeMap ()
Destructor.
void insert (int id, const std::string &name)
Add typeId / type name pair to the container.
void read (std::istream &in)
Read pairs from file.
int id (const std::string &name) const
Get type id associated with a type name.
const std::string & name (int id) const
Get type name associated with an integer id.
int size () const
Number of a pairs in map.
Constructor & Destructor Documentation
Tools::TypeMap::TypeMap ()
Constructor.
Definition at line 19 of file TypeMap.cpp.
Tools::TypeMap::~TypeMap ()
Destructor.
Definition at line 25 of file TypeMap.cpp.
Member Function Documentation
void Tools::TypeMap::insert (int id, const std::string & name)
Add typeId / type name pair to the container.
Parameters
id integer type id
name type names string
Definition at line 28 of file TypeMap.cpp.
References UTIL_THROW.
void Tools::TypeMap::read (std::istream & in)
Read pairs from file.
Parameters
in input stream.
Definition at line 42 of file TypeMap.cpp.
Referenced by Tools::HoomdConfigWriter::readAuxiliaryFile(), and Tools::HoomdConfigReader::readAuxiliaryFile().
int Tools::TypeMap::id (const std::string & name) const inline
Get type id associated with a type name.
Definition at line 82 of file TypeMap.h.
References UTIL_THROW.
const std::string & Tools::TypeMap::name (int id) const inline
Get type name associated with an integer id.
Definition at line 92 of file TypeMap.h.
References UTIL_THROW.
Referenced by Tools::HoomdConfigWriter::writeConfig().
int Tools::TypeMap::size () const inline
Number of a pairs in map.
Definition at line 102 of file TypeMap.h.
The documentation for this class was generated from the following files:
TypeMap.h
TypeMap.cpp