Simpatico: McMd::DdMdConfigIo Class Reference
McMd::DdMdConfigIo Class Reference
McMd namespace » Configuration File IO
Detailed Description
ConfigIo for DdMd data files.
This class reads and writes the data file format that is read by the LAMMPS read_data command. Because the DdMd data model is very different than that used in Simpatico, there are signficant restrictions on the use of such files:
1) When reading a LAMMPS data file, the maximum total number of atoms defined by the Simpatico parameter file must exactly match the number of atoms in the data file.
2) The atom ids (or tags) in the DdMd data file must appear in order, numbered from 1. This is checked.
3) The ordering of atoms in the lammps file and the topology are assumed to be consistent with that used in Simpatico. The topology information in the DdMd data file is discarded. This requires that atoms within each molecule be listed sequentially, with molecules with the same species listed sequentially, and that ordered of atoms within each molecule be consistent with the numbering scheme used in Simpatico. Thus far, none of this is checked.
Definition at line 48 of file mcMd/configIos/DdMdConfigIo.h.
#include <DdMdConfigIo.h>
Public Member Functions
DdMdConfigIo (System &system, bool hasMolecules=false)
Constructor.
virtual ~DdMdConfigIo ()
Destructor.
void read (std::istream &in)
Read configuration (particle positions) from file.
void write (std::ostream &out)
Write configuration (particle positions) to file.
Public Member Functions inherited from McMd::ConfigIo
ConfigIo (System &system)
Constructor.
virtual ~ConfigIo ()
Destructor.
Additional Inherited Members
Protected Member Functions inherited from McMd::ConfigIo
System & system () const
Get a reference to the parent System.
Simulation & simulation () const
Get a reference to the parent Simulation.
Boundary & boundary () const
Get the Boundary.
Constructor & Destructor Documentation
McMd::DdMdConfigIo::DdMdConfigIo (System & system, bool hasMolecules = false)
Constructor.
Definition at line 32 of file mcMd/configIos/DdMdConfigIo.cpp.
McMd::DdMdConfigIo::~DdMdConfigIo () virtual
Destructor.
Definition at line 40 of file mcMd/configIos/DdMdConfigIo.cpp.
Member Function Documentation
void McMd::DdMdConfigIo::read (std::istream & in) virtual
Read configuration (particle positions) from file.
Parameters
in input file stream.
Implements McMd::ConfigIo.
Definition at line 43 of file mcMd/configIos/DdMdConfigIo.cpp.
References McMd::System::addMolecule(), McMd::Molecule::begin(), McMd::System::boundary(), McMd::Species::capacity(), McMd::Simulation::getMolecule(), McMd::Species::nAtom(), McMd::Species::nBond(), Util::ArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), McMd::ConfigIo::simulation(), McMd::Simulation::species(), McMd::ConfigIo::system(), and UTIL_THROW.
void McMd::DdMdConfigIo::write (std::ostream & out) virtual
Write configuration (particle positions) to file.
Parameters
out output file stream.
Implements McMd::ConfigIo.
Definition at line 116 of file mcMd/configIos/DdMdConfigIo.cpp.
References McMd::System::begin(), McMd::System::boundary(), Util::Format::initStatic(), McMd::Species::nAngle(), McMd::Species::nAtom(), McMd::Species::nBond(), McMd::Species::nDihedral(), McMd::System::nMolecule(), Util::ArrayIterator< Data >::notEnd(), Util::PArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), McMd::ConfigIo::simulation(), McMd::System::simulation(), McMd::Simulation::species(), and McMd::ConfigIo::system().
The documentation for this class was generated from the following files:
mcMd/configIos/DdMdConfigIo.h
mcMd/configIos/DdMdConfigIo.cpp