Simpatico: Inter::PeriodicExternal Class Reference
Inter::PeriodicExternal Class Reference
External Interactions
Detailed Description
A clipped cosine potential that induces ordering along directions specified by waveIntVectors, w_i.
/ / / / w_i.(x-shift_[0]) w_i.(y-shift_[1]) w_i.(z-shift_[2]) \ \ \ \ u = prefactor[atomType] externalParameter tanh | clipParameter| C_ + Sum | cos | 2 pi ------------------ + ------------------ + ------------------ + phase_i | | | | \ \ i \ \ Lx Ly Lz / / / /
Prefactor (which depends on the atomType), externalParameter, waveIntVectors, interfaceWidth and periodicity are given as inputs in the parameter file. ClipParameter is the inverse of 2*pi*periodicity*interfaceWidth.
Definition at line 37 of file PeriodicExternal.h.
#include <PeriodicExternal.h>
Public Member Functions
PeriodicExternal ()
Default constructor.
PeriodicExternal (const PeriodicExternal &other)
Copy constructor.
PeriodicExternal & operator= (const PeriodicExternal &other)
Assignment.
void setNAtomType (int nAtomType)
Set nAtomType value.
void setExternalParameter (double externalParameter)
Sets external parameter.
void setBoundary (Boundary &boundary)
Set pointer to Boundary.
void readParameters (std::istream &in)
Read potential parameters, and initialize other variables.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
double externalParameter () const
Returns external parameter.
double energy (const Vector &position, int i) const
Returns external potential energy of a single particle.
void getForce (const Vector &position, int type, Vector &force) const
Returns force caused by the external potential.
std::string className () const
Return name string "PeriodicExternal".
Constructor & Destructor Documentation
Inter::PeriodicExternal::PeriodicExternal ()
Default constructor.
Definition at line 23 of file PeriodicExternal.cpp.
References Util::ParamComposite::setClassName().
Inter::PeriodicExternal::PeriodicExternal (const PeriodicExternal & other)
Copy constructor.
Definition at line 37 of file PeriodicExternal.cpp.
References Util::DArray< Data >::allocate(), and Util::Dimension.
Member Function Documentation
PeriodicExternal & Inter::PeriodicExternal::operator= (const PeriodicExternal & other)
Assignment.
Definition at line 69 of file PeriodicExternal.cpp.
References Util::DArray< Data >::allocate(), and Util::Dimension.
void Inter::PeriodicExternal::setNAtomType (int nAtomType)
Set nAtomType value.
Parameters:
nAtomType number of atom types.
Definition at line 100 of file PeriodicExternal.cpp.
References UTIL_THROW.
void Inter::PeriodicExternal::setExternalParameter (double externalParameter)
Sets external parameter.
Parameters:
externalParameter external parameter of system
Definition at line 111 of file PeriodicExternal.cpp.
References externalParameter(), and UTIL_THROW.
void Inter::PeriodicExternal::setBoundary (Boundary & boundary)
Set pointer to Boundary.
Parameters:
boundary Boundary object (used to calculate length along perpendicular direction).
Definition at line 125 of file PeriodicExternal.cpp.
void Inter::PeriodicExternal::readParameters (std::istream & in) [virtual]
Read potential parameters, and initialize other variables.
Precondition:
nAtomType must have been set, by calling setNAtomType().
Boundary must have been set, by calling setBoundary().
Parameters:
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 131 of file PeriodicExternal.cpp.
References Util::DArray< Data >::allocate(), and UTIL_THROW.
void Inter::PeriodicExternal::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 163 of file PeriodicExternal.cpp.
References Util::DArray< Data >::allocate(), and UTIL_THROW.
void Inter::PeriodicExternal::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 185 of file PeriodicExternal.cpp.
double Inter::PeriodicExternal::externalParameter () const
Returns external parameter.
Returns:
external parameter
Definition at line 199 of file PeriodicExternal.cpp.
Referenced by setExternalParameter().
double Inter::PeriodicExternal::energy (const Vector & position, int i) const [inline]
Returns external potential energy of a single particle.
Parameters:
position atomic position Vector
i atom type.
Returns:
external potential energy
Definition at line 180 of file PeriodicExternal.h.
References Util::Vector::dot().
void Inter::PeriodicExternal::getForce (const Vector & position, int type, Vector & force) const [inline]
Returns force caused by the external potential.
Parameters:
position atom position
type atom type id
force force on the atom (on output)
Definition at line 204 of file PeriodicExternal.h.
References Util::Vector::dot(), and Util::Vector::zero().
std::string Inter::PeriodicExternal::className () const
Return name string "PeriodicExternal".
Reimplemented from Util::ParamComposite.
Definition at line 207 of file PeriodicExternal.cpp.
The documentation for this class was generated from the following files:
PeriodicExternal.h
PeriodicExternal.cpp