Simpatico: Util::EnergyEnsemble Class Reference
Util::EnergyEnsemble Class Reference
Detailed Description
A statistical ensemble for energy.
An energy ensemble has a type, which can be adiabatic or isothermal, and stores a temperature and inverse temperature beta if the type is isothermal.
Definition at line 28 of file EnergyEnsemble.h.
#include <EnergyEnsemble.h>
Public Types
enum Type
Enumeration of the allowed types of EnergyEnsemble.
Public Member Functions
EnergyEnsemble (Type type=UNKNOWN)
Constructor.
void setTemperature (double temperature)
Set the temperature.
virtual void readParameters (std::istream &in)
Read the type and (if necessary) temperature from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
Accessors
bool isAdiabatic () const
Is this an Adiabatic ensemble?
bool isIsothermal () const
Is this an Isothermal ensemble?
double temperature () const
Return the temperature.
double beta () const
Return the inverse temperature.
Static Public Member Functions
static void commitMpiType ()
Commit MPI data type for an EnergyEnsemble.
Member Enumeration Documentation
enum Util::EnergyEnsemble::Type
Enumeration of the allowed types of EnergyEnsemble.
Definition at line 36 of file EnergyEnsemble.h.
Constructor & Destructor Documentation
Util::EnergyEnsemble::EnergyEnsemble (Type type = UNKNOWN)
Constructor.
Definition at line 23 of file EnergyEnsemble.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void Util::EnergyEnsemble::setTemperature (double temperature)
Set the temperature.
Definition at line 32 of file EnergyEnsemble.cpp.
References isIsothermal(), temperature(), and UTIL_THROW.
Referenced by McMd::McEnergyPerturbation::setParameter().
void Util::EnergyEnsemble::readParameters (std::istream & in) [virtual]
Read the type and (if necessary) temperature from file.
The type is specified in the input file by a string literal "adiabatic" or "isothermal".
Reimplemented from Util::ParamComposite.
Definition at line 44 of file EnergyEnsemble.cpp.
References isIsothermal().
void Util::EnergyEnsemble::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 56 of file EnergyEnsemble.cpp.
References isIsothermal().
void Util::EnergyEnsemble::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 68 of file EnergyEnsemble.cpp.
References isIsothermal().
Referenced by McMd::System::saveEnsembles().
bool Util::EnergyEnsemble::isAdiabatic () const [inline]
Is this an Adiabatic ensemble?
Definition at line 150 of file EnergyEnsemble.h.
bool Util::EnergyEnsemble::isIsothermal () const [inline]
Is this an Isothermal ensemble?
Definition at line 156 of file EnergyEnsemble.h.
Referenced by loadParameters(), McMd::NvtDpdVvIntegrator::NvtDpdVvIntegrator(), DdMd::NvtIntegrator::NvtIntegrator(), McMd::NvtNhIntegrator::NvtNhIntegrator(), readParameters(), save(), and setTemperature().
double Util::EnergyEnsemble::temperature () const [inline]
Return the temperature.
Definition at line 138 of file EnergyEnsemble.h.
Referenced by DdMd::NvtIntegrator::integrateStep1(), DdMd::NptIntegrator::integrateStep1(), DdMd::NvtIntegrator::integrateStep2(), McMd::HybridNphMdMove::move(), McMd::NvtDpdVvIntegrator::NvtDpdVvIntegrator(), McMd::NvtNhIntegrator::NvtNhIntegrator(), McMd::McEnergyPerturbation::parameter(), McMd::NvtNhIntegrator::readParameters(), setTemperature(), DdMd::NvtIntegrator::setup(), DdMd::NptIntegrator::setup(), McMd::NvtDpdVvIntegrator::setup(), McMd::NvtNhIntegrator::setup(), and McMd::NvtNhIntegrator::step().
double Util::EnergyEnsemble::beta () const [inline]
Return the inverse temperature.
Definition at line 144 of file EnergyEnsemble.h.
Referenced by McMd::CfbEndBase::addEndAtom(), and McMd::CfbRebridgeBase::addMiddleAtom().
void Util::EnergyEnsemble::commitMpiType () [static]
Commit MPI data type for an EnergyEnsemble.
Definition at line 125 of file EnergyEnsemble.cpp.
References Util::MpiStructBuilder::addMember(), Util::MpiStructBuilder::commit(), and Util::MpiStructBuilder::setBase().
The documentation for this class was generated from the following files:
EnergyEnsemble.h
EnergyEnsemble.cpp