Simpatico: McMd::IntraBondTensorAutoCorr< SystemType > Class Template Reference
McMd::IntraBondTensorAutoCorr< SystemType > Class Template Reference
Diagnostics
Detailed Description
template<class SystemType>
class McMd::IntraBondTensorAutoCorr< SystemType >
Autocorrelation for bond stress of a molecule.
Definition at line 34 of file IntraBondTensorAutoCorr.h.
#include <IntraBondTensorAutoCorr.h>
Public Member Functions
IntraBondTensorAutoCorr (SystemType &system)
Constructor.
virtual ~IntraBondTensorAutoCorr ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from file.
virtual void save (Serializable::OArchive &ar)
Save internal state to file.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Set number of molecules and clear accumulator.
virtual void sample (long iStep)
Evaluate end-to-end vectors of all chains, add to ensemble.
virtual void output ()
Output results after simulation is completed.
Constructor & Destructor Documentation
template<class SystemType> McMd::IntraBondTensorAutoCorr< SystemType >::IntraBondTensorAutoCorr (SystemType & system)
Constructor.
Parameters:
system reference to parent System
Definition at line 31 of file IntraBondTensorAutoCorr.tpp.
template<class SystemType > McMd::IntraBondTensorAutoCorr< SystemType >::~IntraBondTensorAutoCorr () [virtual]
Destructor.
Definition at line 46 of file IntraBondTensorAutoCorr.tpp.
Member Function Documentation
template<class SystemType > void McMd::IntraBondTensorAutoCorr< SystemType >::readParameters (std::istream & in) [virtual]
Read parameters from file.
Parameters:
in input parameter stream
Reimplemented from McMd::Diagnostic.
Definition at line 53 of file IntraBondTensorAutoCorr.tpp.
References UTIL_THROW.
template<class SystemType > void McMd::IntraBondTensorAutoCorr< SystemType >::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from file.
Parameters:
ar input/loading archive
Reimplemented from McMd::Diagnostic.
Definition at line 89 of file IntraBondTensorAutoCorr.tpp.
References McMd::Diagnostic::loadParameters(), and UTIL_THROW.
template<class SystemType > void McMd::IntraBondTensorAutoCorr< SystemType >::save (Serializable::OArchive & ar) [virtual]
Save internal state to file.
Parameters:
ar output/saving archive
Reimplemented from McMd::Diagnostic.
Definition at line 131 of file IntraBondTensorAutoCorr.tpp.
template<class SystemType > template<class Archive > void McMd::IntraBondTensorAutoCorr< SystemType >::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Diagnostic.
Reimplemented in McMd::McIntraBondTensorAutoCorr, and McMd::MdIntraBondTensorAutoCorr.
Definition at line 146 of file IntraBondTensorAutoCorr.h.
References McMd::serialize().
template<class SystemType > void McMd::IntraBondTensorAutoCorr< SystemType >::setup () [virtual]
Set number of molecules and clear accumulator.
Reimplemented from McMd::Diagnostic.
Definition at line 138 of file IntraBondTensorAutoCorr.tpp.
References UTIL_THROW.
template<class SystemType > void McMd::IntraBondTensorAutoCorr< SystemType >::sample (long iStep) [virtual]
Evaluate end-to-end vectors of all chains, add to ensemble.
Parameters:
iStep counter for number of steps
Implements McMd::Diagnostic.
Definition at line 154 of file IntraBondTensorAutoCorr.tpp.
References Util::Dimension, Util::OrthorhombicBoundary::distanceSq(), Util::Tensor::dyad(), Util::ConstArrayIterator< Data >::notEnd(), Util::ConstPArrayIterator< Data >::notEnd(), Util::Tensor::trace(), UTIL_THROW, and Util::Vector::versor().
template<class SystemType > void McMd::IntraBondTensorAutoCorr< SystemType >::output () [virtual]
Output results after simulation is completed.
Reimplemented from McMd::Diagnostic.
Definition at line 202 of file IntraBondTensorAutoCorr.tpp.
The documentation for this class was generated from the following files:
IntraBondTensorAutoCorr.h
IntraBondTensorAutoCorr.tpp