Simpatico: DdMd::OutputPairEnergies Class Reference
DdMd::OutputPairEnergies Class Reference
Diagnostics
Detailed Description
Periodically write pair energies to file.
Definition at line 25 of file OutputPairEnergies.h.
#include <OutputPairEnergies.h>
Public Member Functions
OutputPairEnergies (Simulation &simulation)
Constructor.
virtual ~OutputPairEnergies ()
Destructor.
virtual void readParameters (std::istream &in)
Read interval and output file name.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void clear ()
Clear nSample counter.
virtual void sample (long iStep)
Compute and output pair energies periodically.
Constructor & Destructor Documentation
DdMd::OutputPairEnergies::OutputPairEnergies (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object.
Definition at line 27 of file OutputPairEnergies.cpp.
References Util::ParamComposite::setClassName().
virtual DdMd::OutputPairEnergies::~OutputPairEnergies () [inline, virtual]
Destructor.
Definition at line 40 of file OutputPairEnergies.h.
Member Function Documentation
void DdMd::OutputPairEnergies::readParameters (std::istream & in) [virtual]
Read interval and output file name.
Parameters:
in input parameter file
Reimplemented from Util::ParamComposite.
Definition at line 36 of file OutputPairEnergies.cpp.
References DdMd::Simulation::fileMaster(), Util::FileMaster::openOutputFile(), DdMd::Diagnostic::outputFileName(), DdMd::Diagnostic::readInterval(), DdMd::Diagnostic::readOutputFileName(), and DdMd::Diagnostic::simulation().
void DdMd::OutputPairEnergies::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from DdMd::Diagnostic.
Definition at line 50 of file OutputPairEnergies.cpp.
References DdMd::Simulation::fileMaster(), DdMd::Diagnostic::loadInterval(), DdMd::Diagnostic::loadOutputFileName(), Util::FileMaster::openOutputFile(), DdMd::Diagnostic::outputFileName(), and DdMd::Diagnostic::simulation().
void DdMd::OutputPairEnergies::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from DdMd::Diagnostic.
Definition at line 64 of file OutputPairEnergies.cpp.
References DdMd::Diagnostic::saveInterval(), and DdMd::Diagnostic::saveOutputFileName().
void DdMd::OutputPairEnergies::clear () [virtual]
Clear nSample counter.
Reimplemented from DdMd::Diagnostic.
Definition at line 75 of file OutputPairEnergies.cpp.
void DdMd::OutputPairEnergies::sample (long iStep) [virtual]
Compute and output pair energies periodically.
Parameters:
iStep MC step index
Implements DdMd::Diagnostic.
Definition at line 81 of file OutputPairEnergies.cpp.
References DdMd::Simulation::computePairEnergies(), DdMd::Simulation::domain(), DdMd::Diagnostic::isAtInterval(), DdMd::Domain::isMaster(), DdMd::Simulation::nAtomType(), DdMd::Simulation::pairEnergies(), and DdMd::Diagnostic::simulation().
The documentation for this class was generated from the following files:
OutputPairEnergies.h
OutputPairEnergies.cpp