Simpatico: CompositeBond< BareBond, BarePair > Class Template Reference
CompositeBond< BareBond, BarePair > Class Template Reference
Bond Interactions
Detailed Description
template<class BareBond, class BarePair>
class Inter::CompositeBond< BareBond, BarePair >
Composite bond potential.
This class template creates a bond potential energy which is the sum of a BareBond bond potential and a BarePair pair potential. This is intended for use in models in which the nonbonded pair interactions between bonded atoms are masked, to allow the pair potential to be explicitly added back in.
Definition at line 38 of file CompositeBond.h.
#include <CompositeBond.h>
Public Member Functions
CompositeBond ()
Constructor.
void setNBondType (int nBondType)
Set nAtomType value.
void readParam (std::istream &in)
Read epsilon and sigma, initialize other variables.
void set (std::string name, int type, double value)
Modify a parameter, identified by a string.
double energy (double rsq, int type) const
Returns interaction energy for a single pair of particles.
double forceOverR (double rsq, int bondTypeId) const
Returns ratio of bond force to atom separation.
double randomBondLength (Random *randomPtr, double beta, int type) const
Throws exception if called.
double get (std::string name, int type) const
Get a parameter value, identified by a string.
std::string className () const
Return name of instantiated class, with no spaces.
Constructor & Destructor Documentation
CompositeBond ()
Constructor.
Definition at line 146 of file CompositeBond.h.
Member Function Documentation
void setNBondType (int nBondType)
Set nAtomType value.
Parameters:
nBondType number of atom types.
Definition at line 202 of file CompositeBond.h.
void readParam (std::istream & in) [virtual]
Read epsilon and sigma, initialize other variables.
Precondition:
nAtomType must be set, by calling setNAtomType().
Parameters:
in input stream
Reimplemented from ParamComposite.
Definition at line 172 of file CompositeBond.h.
References End::readParam(), Begin::readParam(), and ParamComponent::setIndent().
void set (std::string name, int type, double value)
Modify a parameter, identified by a string.
Parameters:
name parameter name
type bond type index
value new value of parameter
Definition at line 239 of file CompositeBond.h.
References UTIL_THROW.
double energy (double rsq, int type) const [inline]
Returns interaction energy for a single pair of particles.
Parameters:
rsq square of distance between pair of atoms
type type index for bond.
Returns:
bond interaction energy
Definition at line 213 of file CompositeBond.h.
double forceOverR (double rsq, int bondTypeId) const [inline]
Returns ratio of bond force to atom separation.
Multiply this quantity by the separation vector to obtain the force vector. A positive value for the return value represents a repulsive bond force.
Parameters:
rsq square of distance between particles
bondTypeId type index for bond.
Returns:
force divided by distance
Definition at line 226 of file CompositeBond.h.
double randomBondLength (Random * randomPtr, double beta, int type) const
Throws exception if called.
Parameters:
randomPtr pointer to a random number generator
beta inverse absolute temperature (inverse energy)
type type index for bond.
Definition at line 268 of file CompositeBond.h.
References UTIL_THROW.
double get (std::string name, int type) const
Get a parameter value, identified by a string.
Parameters:
name parameter name
type bond type index
Returns:
value of parameter
Definition at line 249 of file CompositeBond.h.
References UTIL_THROW.
std::string className () const
Return name of instantiated class, with no spaces.
Definition at line 259 of file CompositeBond.h.
The documentation for this class was generated from the following file:
CompositeBond.h