Simpatico: SpAn::Species Class Reference
SpAn::Species Class Reference
Chemical Structure
Detailed Description
A set of identical molecules.
Definition at line 27 of file spAn/chemistry/Species.h.
#include <Species.h>
Public Member Functions
Species ()
Constructor.
void setId (int id)
Set the index for this species.
void initialize (int nAtom, int capacity)
Initialize memory for this species and set sizes.
void addAtom (Atom &atom)
Add an atom to the species.
void clear ()
Clear all molecules, reset to empty.
void begin (Iterator &iterator)
Initialize an iterator over molecules.
Molecule & molecule (int i)
Return a specific molecule by reference.
int id () const
Return integer id for this species.
int nAtom () const
Return number of atoms per molecule.
int size () const
Return number of molecules in this species (=maximum id + 1)
int capacity () const
Return maximum number of molecules in this species.
bool isValid () const
Return true if valid, or throw Exception.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
Friends
std::istream & operator>> (std::istream &in, Species &species)
istream extractor (>>) for a Species.
std::ostream & operator<< (std::ostream &out, const Species &species)
ostream inserter (<<) for a Species.
Constructor & Destructor Documentation
SpAn::Species::Species ()
Constructor.
Definition at line 22 of file spAn/chemistry/Species.cpp.
Member Function Documentation
void SpAn::Species::setId (int id)
Set the index for this species.
Parameters:
id species index
Definition at line 30 of file spAn/chemistry/Species.cpp.
References id().
void SpAn::Species::initialize (int nAtom, int capacity)
Initialize memory for this species and set sizes.
Parameters:
nAtom number of atoms per molecule (exact)
capacity maximum number of molecules in species
Definition at line 33 of file spAn/chemistry/Species.cpp.
References capacity(), initialize(), nAtom(), and UTIL_THROW.
Referenced by initialize(), and SpAn::operator>>().
void SpAn::Species::addAtom (Atom & atom)
Add an atom to the species.
Parameters:
atom Atom object to be added, must have AtomContext info.
Definition at line 102 of file spAn/chemistry/Species.cpp.
References SpAn::Atom::atomId, SpAn::Atom::moleculeId, Util::DSArray< Data >::resize(), Util::DSArray< Data >::size(), SpAn::Atom::speciesId, and UTIL_THROW.
Referenced by SpAn::DdMdConfigIo::readConfig().
void SpAn::Species::clear ()
Clear all molecules, reset to empty.
Definition at line 88 of file spAn/chemistry/Species.cpp.
References Util::Array< Data >::capacity(), Util::DSArray< Data >::resize(), and Util::DSArray< Data >::size().
Referenced by SpAn::DdMdConfigIo::readConfig().
void SpAn::Species::begin (Iterator & iterator)
Initialize an iterator over molecules.
Definition at line 135 of file spAn/chemistry/Species.cpp.
References Util::DSArray< Data >::begin().
Referenced by SpAn::AtomMSD::sample(), and SpAn::AtomMSD::setup().
Molecule & SpAn::Species::molecule (int i) [inline]
Return a specific molecule by reference.
Parameters:
i molecule index
Definition at line 180 of file spAn/chemistry/Species.h.
int SpAn::Species::id () const [inline]
Return integer id for this species.
Definition at line 186 of file spAn/chemistry/Species.h.
Referenced by setId().
int SpAn::Species::nAtom () const [inline]
Return number of atoms per molecule.
Definition at line 192 of file spAn/chemistry/Species.h.
Referenced by initialize(), and SpAn::AtomMSD::readParameters().
int SpAn::Species::size () const [inline]
Return number of molecules in this species (=maximum id + 1)
Definition at line 198 of file spAn/chemistry/Species.h.
Referenced by SpAn::AtomMSD::setup().
int SpAn::Species::capacity () const [inline]
Return maximum number of molecules in this species.
Definition at line 204 of file spAn/chemistry/Species.h.
Referenced by initialize(), and SpAn::AtomMSD::readParameters().
bool SpAn::Species::isValid () const
Return true if valid, or throw Exception.
Definition at line 141 of file spAn/chemistry/Species.cpp.
References SpAn::Atom::atomId, Util::Array< Data >::capacity(), Util::DSArray< Data >::capacity(), SpAn::Molecule::id(), SpAn::Atom::moleculeId, Util::DSArray< Data >::size(), SpAn::Atom::speciesId, and UTIL_THROW.
Referenced by SpAn::DdMdConfigIo::readConfig().
template<class Archive > void SpAn::Species::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Definition at line 211 of file spAn/chemistry/Species.h.
Friends And Related Function Documentation
std::istream& operator>> (std::istream & in, Species & species) [friend]
istream extractor (>>) for a Species.
Parameters:
in input stream
species Species to be read from stream
Returns:
modified input stream
Definition at line 203 of file spAn/chemistry/Species.cpp.
std::ostream& operator<< (std::ostream & out, const Species & species) [friend]
ostream inserter (<<) for a Species.
Format on one line with no line break:
Parameters:
out output stream
species Species to be written to stream
Returns:
modified output stream
Definition at line 214 of file spAn/chemistry/Species.cpp.
The documentation for this class was generated from the following files:
spAn/chemistry/Species.h
spAn/chemistry/Species.cpp