Simpatico: Tools::DdMdTrajectoryReader Class Reference
Tools::DdMdTrajectoryReader Class Reference
Trajectory File Readers
Detailed Description
Reader for lammps dump trajectory file format.
Definition at line 24 of file DdMdTrajectoryReader.h.
#include <DdMdTrajectoryReader.h>
Public Member Functions
DdMdTrajectoryReader (Configuration &configuration)
Constructor.
virtual ~DdMdTrajectoryReader ()
Destructor.
virtual void readHeader (std::ifstream &file)
Read the header.
virtual bool readFrame (std::ifstream &file)
Read a frame.
Constructor & Destructor Documentation
Tools::DdMdTrajectoryReader::DdMdTrajectoryReader (Configuration & configuration)
Constructor.
Parameters:
configuration parent Configuration object
Definition at line 24 of file DdMdTrajectoryReader.cpp.
References Util::ParamComposite::setClassName().
Tools::DdMdTrajectoryReader::~DdMdTrajectoryReader () [virtual]
Destructor.
Definition at line 31 of file DdMdTrajectoryReader.cpp.
Member Function Documentation
void Tools::DdMdTrajectoryReader::readHeader (std::ifstream & file) [virtual]
Read the header.
Parameters:
file input file
Reimplemented from Tools::TrajectoryReader.
Definition at line 34 of file DdMdTrajectoryReader.cpp.
bool Tools::DdMdTrajectoryReader::readFrame (std::ifstream & file) [virtual]
Read a frame.
Parameters:
file input file
Returns:
true if a frame was found, false if end of file
Implements Tools::TrajectoryReader.
Definition at line 44 of file DdMdTrajectoryReader.cpp.
References Tools::Configuration::atoms(), Tools::Configuration::boundary(), Tools::TrajectoryReader::configuration(), Util::Dimension, Tools::Atom::position, Tools::AtomStorage::ptr(), and UTIL_THROW.
The documentation for this class was generated from the following files:
DdMdTrajectoryReader.h
DdMdTrajectoryReader.cpp