Simpatico: McMd::McMdConfigIo Class Reference
McMd::McMdConfigIo Class Reference abstract
Configuration File IO
Detailed Description
Base class for default Mc and Md configIos.
Definition at line 30 of file McMdConfigIo.h.
#include <McMdConfigIo.h>
Public Member Functions
McMdConfigIo (System &system)
Constructor.
virtual ~McMdConfigIo ()
Destructor.
virtual void read (std::istream &in)
Read configuration (particle positions) from file.
virtual void write (std::ostream &out)
Write configuration (particle positions) to file.
Public Member Functions inherited from McMd::ConfigIo
ConfigIo (System &system)
Constructor.
virtual ~ConfigIo ()
Destructor.
Protected Member Functions
virtual void readAtom (std::istream &out, Atom &atom)=0
Read data for one atom.
virtual void writeAtom (std::ostream &out, const Atom &atom)=0
Write data for one atom.
Protected Member Functions inherited from McMd::ConfigIo
System & system () const
Get a reference to the parent System.
Simulation & simulation () const
Get a reference to the parent Simulation.
Boundary & boundary () const
Get the Boundary.
Constructor & Destructor Documentation
McMd::McMdConfigIo::McMdConfigIo (System & system)
Constructor.
Definition at line 35 of file McMdConfigIo.cpp.
McMd::McMdConfigIo::~McMdConfigIo () virtual
Destructor.
Definition at line 42 of file McMdConfigIo.cpp.
Member Function Documentation
void McMd::McMdConfigIo::read (std::istream & in) virtual
Read configuration (particle positions) from file.
Parameters
in input file stream.
Implements McMd::ConfigIo.
Definition at line 48 of file McMdConfigIo.cpp.
References McMd::LinkMaster::addLink(), McMd::System::addMolecule(), McMd::Molecule::atom(), McMd::Molecule::begin(), McMd::ConfigIo::boundary(), Util::Log::file(), McMd::Species::isMutable(), McMd::System::linkMaster(), McMd::System::molecule(), McMd::Species::mutator(), McMd::Molecule::nAtom(), Util::ArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), Util::ArrayStack< Data >::pop(), readAtom(), McMd::SpeciesMutator::readMoleculeState(), McMd::Species::reservoir(), McMd::ConfigIo::simulation(), McMd::Simulation::species(), McMd::ConfigIo::system(), and UTIL_THROW.
void McMd::McMdConfigIo::write (std::ostream & out) virtual
Write configuration (particle positions) to file.
Parameters
out output file stream.
Implements McMd::ConfigIo.
Definition at line 185 of file McMdConfigIo.cpp.
References McMd::Link::atom0(), McMd::Link::atom1(), McMd::System::begin(), McMd::ConfigIo::boundary(), McMd::Species::id(), McMd::Atom::indexInMolecule(), McMd::Species::isMutable(), McMd::LinkMaster::link(), McMd::System::linkMaster(), McMd::Atom::molecule(), McMd::System::moleculeId(), McMd::Species::mutator(), McMd::LinkMaster::nLink(), McMd::System::nMolecule(), Util::ConstArrayIterator< Data >::notEnd(), Util::ConstPArrayIterator< Data >::notEnd(), McMd::Simulation::nSpecies(), McMd::ConfigIo::simulation(), McMd::Molecule::species(), McMd::Simulation::species(), McMd::ConfigIo::system(), McMd::Link::typeId(), writeAtom(), and McMd::SpeciesMutator::writeMoleculeState().
virtual void McMd::McMdConfigIo::readAtom (std::istream & out, Atom & atom) protected pure virtual
Read data for one atom.
Implemented in McMd::McConfigIo, and McMd::MdConfigIo.
Referenced by read().
virtual void McMd::McMdConfigIo::writeAtom (std::ostream & out, const Atom & atom) protected pure virtual
Write data for one atom.
Implemented in McMd::McConfigIo, and McMd::MdConfigIo.
Referenced by write().
The documentation for this class was generated from the following files:
McMdConfigIo.h
McMdConfigIo.cpp