Simpatico: McMd::IntraStructureFactor Class Reference
McMd::IntraStructureFactor Class Reference
MC/MD Analyzers
Detailed Description
Intramolecular contribution to the structure factor S(k)
The intramolecular contribution to the structure factor S(k) for a wavevector k is defined as an expectation value
in which the sum is taken over all molecules m of a specified species, V is system volume, and is a Fourier component
in which the sum is taken over all particles in a set defined by the particle type index a on a specific molecule m.
If 0 <= a < nAtomType, then, is given by a sum over all atoms of type a on molecule m.
If a < 0, then is given by a sum over all atoms on molecule m, including those of all types. By convention, we use a = -1 to indicate this.
This class can evaluate multiple types of structures factors, corresponding to different choices for the type pair ab, for multiple wavevectors. The input format thus requires the user to specify one or more atom typeId pairs, and one or more wavevectors. Each wavevector is specified as an IntVector containing integer Miller indices. These are the coeficients in an expansion of a reciprocal lattice wavevector in terms of recprocal lattice basis vectors for the periodic unit cell.
In a system with nAtomType = 2, with two monomer types 0 and 1, the parameter file input for calculating the total, 00 and 01 correlation functions for 5 wavevectors along the x axis in an orthorhombic unit cell might look like this:
 IntraStructureFactor{
    interval                     1000
    outputFileName     IntraStructureFactor
    nAtomTypeIdPair                  3
    atomTypeIdPairs          -1     -1
                              0      0
                              0      1
    nWave                            5
    waveIntVectors     8      0      0
                       9      0      0
                      10      0      0
                      11      0      0
                      12      0      0
 }
At the end of a simulation, all of the structure factors are output in a file with a suffix *.dat. Each line in this file contains the 3 Miller indices of a wavevector, the absolute magnitude of the wavevector, and a list of nAtomTypeIdPair structure factor values for the wavevector, one for each atomTypeId pair.
Definition at line 90 of file IntraStructureFactor.h.
#include <IntraStructureFactor.h>
Public Member Functions
IntraStructureFactor (System &system)
Constructor.
~IntraStructureFactor ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive.
virtual void save (Serializable::OArchive &ar)
Save state to archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Clear accumulators.
void sample (long iStep)
Add particle pairs to IntraStructureFactor histogram.
virtual void output ()
Output results to predefined output file.
Protected Attributes
std::ofstream outputFile_
Output file stream.
DMatrix< double > structureFactors_
Structure factor accumulators.
DMatrix< double > structureFactorDelta_
Contribution of current time step to structure factor average.
DMatrix< std::complex< double > > fourierModes_
Fourier modes.
int speciesId_
Index for molecular species.
int nWave_
Number of wavevectors.
int nAtomTypeIdPair_
Number of selected atom type pairs.
int nSample_
Number of samples thus far.
int nAtomType_
Number of atom types, copied from Simulation::nAtomType().
Constructor & Destructor Documentation
McMd::IntraStructureFactor::IntraStructureFactor (System & system)
Constructor.
Parameters:
system reference to parent System object
Definition at line 30 of file IntraStructureFactor.cpp.
References Util::ParamComposite::setClassName().
McMd::IntraStructureFactor::~IntraStructureFactor ()
Destructor.
Definition at line 38 of file IntraStructureFactor.cpp.
Member Function Documentation
void McMd::IntraStructureFactor::readParameters (std::istream & in) [virtual]
Read parameters from file.
Input format:
int interval sampling interval
string outputFileName output file base name
int nAtomTypeIdPair number of Atom typeId pairs
DArray<Pair<int>> atomTypeIdPairs integer typeId pairs
int nWave number of wavevectors
DArray<IntVector> waveIntVectors IntVector wavevectors
Parameters:
in input parameter stream
Reimplemented from McMd::Analyzer.
Reimplemented in McMd::IntraStructureFactorGrid.
Definition at line 44 of file IntraStructureFactor.cpp.
References Util::DMatrix< Data >::allocate(), Util::DArray< Data >::allocate(), fourierModes_, McMd::Simulation::nAtomType(), nAtomType_, nAtomTypeIdPair_, nWave_, McMd::Analyzer::readInterval(), McMd::Analyzer::readOutputFileName(), McMd::System::simulation(), speciesId_, structureFactorDelta_, structureFactors_, and McMd::SystemAnalyzer< System >::system().
void McMd::IntraStructureFactor::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from archive.
Parameters:
ar loading (input) archive.
Reimplemented from McMd::Analyzer.
Reimplemented in McMd::IntraStructureFactorGrid.
Definition at line 71 of file IntraStructureFactor.cpp.
References Util::DArray< Data >::allocate(), fourierModes_, McMd::Analyzer::loadInterval(), McMd::Analyzer::loadOutputFileName(), McMd::Simulation::nAtomType(), nAtomType_, nAtomTypeIdPair_, nSample_, nWave_, McMd::System::simulation(), speciesId_, structureFactors_, McMd::SystemAnalyzer< System >::system(), and UTIL_THROW.
void McMd::IntraStructureFactor::save (Serializable::OArchive & ar) [virtual]
Save state to archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::Analyzer.
Reimplemented in McMd::IntraStructureFactorGrid.
Definition at line 104 of file IntraStructureFactor.cpp.
template<class Archive > void McMd::IntraStructureFactor::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar saving or loading archive
version archive version id
Reimplemented from McMd::Analyzer.
Reimplemented in McMd::IntraStructureFactorGrid.
Definition at line 228 of file IntraStructureFactor.h.
References McMd::serialize().
void McMd::IntraStructureFactor::setup () [virtual]
Clear accumulators.
Reimplemented from McMd::Analyzer.
Reimplemented in McMd::IntraStructureFactorGrid.
Definition at line 110 of file IntraStructureFactor.cpp.
References nAtomTypeIdPair_, nSample_, nWave_, structureFactors_, and UTIL_THROW.
void McMd::IntraStructureFactor::sample (long iStep) [virtual]
Add particle pairs to IntraStructureFactor histogram.
Parameters:
iStep step counter
Implements McMd::Analyzer.
Reimplemented in McMd::IntraStructureFactorGrid.
Definition at line 132 of file IntraStructureFactor.cpp.
References McMd::System::begin(), McMd::System::boundary(), Util::Vector::dot(), fourierModes_, Util::Constants::Im, McMd::Analyzer::isAtInterval(), nAtomType_, nAtomTypeIdPair_, Util::ConstArrayIterator< Data >::notEnd(), Util::ConstPArrayIterator< Data >::notEnd(), nSample_, nWave_, Util::product(), speciesId_, structureFactorDelta_, structureFactors_, McMd::SystemAnalyzer< System >::system(), and Util::OrthorhombicBoundary::volume().
void McMd::IntraStructureFactor::output () [virtual]
Output results to predefined output file.
Reimplemented from McMd::Analyzer.
Reimplemented in McMd::IntraStructureFactorGrid.
Definition at line 227 of file IntraStructureFactor.cpp.
References Util::Dimension, McMd::Analyzer::fileMaster(), nAtomTypeIdPair_, nSample_, nWave_, Util::FileMaster::openOutputFile(), outputFile_, McMd::Analyzer::outputFileName(), structureFactors_, and Util::ParamComposite::writeParam().
Member Data Documentation
std::ofstream McMd::IntraStructureFactor::outputFile_ [protected]
Output file stream.
Definition at line 169 of file IntraStructureFactor.h.
Referenced by McMd::IntraStructureFactorGrid::output(), and output().
DMatrix<double> McMd::IntraStructureFactor::structureFactors_ [protected]
Structure factor accumulators.
First index denotes wavevector, second denotes an atom typeId pair.
Definition at line 176 of file IntraStructureFactor.h.
Referenced by McMd::IntraStructureFactorGrid::loadParameters(), loadParameters(), McMd::IntraStructureFactorGrid::output(), output(), McMd::IntraStructureFactorGrid::readParameters(), readParameters(), sample(), and setup().
DMatrix<double> McMd::IntraStructureFactor::structureFactorDelta_ [protected]
Contribution of current time step to structure factor average.
Definition at line 181 of file IntraStructureFactor.h.
Referenced by McMd::IntraStructureFactorGrid::readParameters(), readParameters(), McMd::IntraStructureFactorGrid::sample(), and sample().
DMatrix< std::complex<double> > McMd::IntraStructureFactor::fourierModes_ [protected]
Fourier modes.
First index is wavevector, second is atom type.
Definition at line 186 of file IntraStructureFactor.h.
Referenced by McMd::IntraStructureFactorGrid::loadParameters(), loadParameters(), McMd::IntraStructureFactorGrid::readParameters(), readParameters(), and sample().
int McMd::IntraStructureFactor::speciesId_ [protected]
Index for molecular species.
Definition at line 198 of file IntraStructureFactor.h.
Referenced by loadParameters(), McMd::IntraStructureFactorGrid::readParameters(), readParameters(), and sample().
int McMd::IntraStructureFactor::nWave_ [protected]
Number of wavevectors.
Definition at line 201 of file IntraStructureFactor.h.
Referenced by McMd::IntraStructureFactorGrid::loadParameters(), loadParameters(), output(), McMd::IntraStructureFactorGrid::readParameters(), readParameters(), sample(), and setup().
int McMd::IntraStructureFactor::nAtomTypeIdPair_ [protected]
Number of selected atom type pairs.
Definition at line 204 of file IntraStructureFactor.h.
Referenced by McMd::IntraStructureFactorGrid::loadParameters(), loadParameters(), McMd::IntraStructureFactorGrid::output(), output(), McMd::IntraStructureFactorGrid::readParameters(), readParameters(), McMd::IntraStructureFactorGrid::sample(), sample(), and setup().
int McMd::IntraStructureFactor::nSample_ [protected]
Number of samples thus far.
Definition at line 207 of file IntraStructureFactor.h.
Referenced by McMd::IntraStructureFactorGrid::loadParameters(), loadParameters(), McMd::IntraStructureFactorGrid::output(), output(), McMd::IntraStructureFactorGrid::readParameters(), sample(), and setup().
int McMd::IntraStructureFactor::nAtomType_ [protected]
Number of atom types, copied from Simulation::nAtomType().
Definition at line 210 of file IntraStructureFactor.h.
Referenced by McMd::IntraStructureFactorGrid::loadParameters(), loadParameters(), McMd::IntraStructureFactorGrid::readParameters(), readParameters(), and sample().
The documentation for this class was generated from the following files:
IntraStructureFactor.h
IntraStructureFactor.cpp