Simpatico: DdMd::PairIterator Class Reference
DdMd::PairIterator Class Reference
Nonbonded Neighbors
Detailed Description
Iterator for pairs in a PairList.
A loop over atom pairs, such as that required to calculated forces or energies, can take the following form:
    PairList     pairList;
    PairIterator iter;
    // [build the PairList]
    // Loop over pairs
    Atom* atom1Ptr;
    Atom* atom2Ptr;
    for (pairList.begin(iter); iterator.notEnd(); ++iter) {
       iterator.getPair(atom1Ptr, atom2Ptr);
       // [Do something with atom1Ptr and atom2Ptr]
       ++iter;
    }
Definition at line 48 of file ddMd/neighbor/PairIterator.h.
#include <PairIterator.h>
Public Member Functions
PairIterator ()
Default constructor.
PairIterator (const PairList &pairList)
Initializing constructor.
PairIterator & operator++ ()
Increment to next pair.
bool isEnd () const
Return true if at end of PairList.
bool notEnd () const
Return true if not at end of PairList.
void getPair (Atom *&atom1Ptr, Atom *&atom2Ptr) const
Get pointers for current pair of Atoms.
Constructor & Destructor Documentation
DdMd::PairIterator::PairIterator () [inline]
Default constructor.
Creates an uninitialized iterator, which is not associated with a parent PairList.
Definition at line 133 of file ddMd/neighbor/PairIterator.h.
DdMd::PairIterator::PairIterator (const PairList & pairList) [inline]
Initializing constructor.
Creates an initialized iterator, for which the current pair is the first pair in a parent PairList.
Parameters:
pairList parent PairList object.
Definition at line 146 of file ddMd/neighbor/PairIterator.h.
References DdMd::PairList::begin().
Member Function Documentation
PairIterator & DdMd::PairIterator::operator++ () [inline]
Increment to next pair.
Definition at line 172 of file ddMd/neighbor/PairIterator.h.
bool DdMd::PairIterator::isEnd () const [inline]
Return true if at end of PairList.
When isEnd() is true, the current pair is already one past past the end of the pairlist, and is thus invalid.
Definition at line 188 of file ddMd/neighbor/PairIterator.h.
bool DdMd::PairIterator::notEnd () const [inline]
Return true if not at end of PairList.
If notEnd(), continue iteration loop. Equivalent to not isEnd().
Definition at line 194 of file ddMd/neighbor/PairIterator.h.
Referenced by DdMd::PairPotentialImpl< Interaction >::computeForcesAndStress(), DdMd::PairPotentialImpl< Interaction >::computePairEnergies(), and DdMd::PairPotentialImpl< Interaction >::computeStress().
void DdMd::PairIterator::getPair (Atom *& atom1Ptr, Atom *& atom2Ptr) const [inline]
Get pointers for current pair of Atoms.
Parameters:
atom1Ptr pointer to current atom 1.
atom2Ptr pointer to current atom 2.
Definition at line 159 of file ddMd/neighbor/PairIterator.h.
Referenced by DdMd::PairPotentialImpl< Interaction >::computeForcesAndStress(), DdMd::PairPotentialImpl< Interaction >::computePairEnergies(), and DdMd::PairPotentialImpl< Interaction >::computeStress().
The documentation for this class was generated from the following file:
ddMd/neighbor/PairIterator.h