Simpatico: McMd::McPairEnergyAverage Class Reference
McMd::McPairEnergyAverage Class Reference
Analyzers
Detailed Description
McPairEnergyAverage averages of total potential energy.
Definition at line 30 of file McPairEnergyAverage.h.
#include <McPairEnergyAverage.h>
Public Member Functions
McPairEnergyAverage (McSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters and initialize.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Clear accumulator.
virtual void sample (long iStep)
Calculate, analyze and/or output a physical quantity.
virtual void output ()
Output results at end of simulation.
Constructor & Destructor Documentation
McMd::McPairEnergyAverage::McPairEnergyAverage (McSystem & system)
Constructor.
Parameters:
system parent McSystem
Definition at line 31 of file McPairEnergyAverage.cpp.
References McMd::PairSelector::setAvoidDoubleCounting(), and Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::McPairEnergyAverage::readParameters (std::istream & in) [virtual]
Read parameters and initialize.
Parameters:
in input parameter stream
Reimplemented from McMd::Analyzer.
Definition at line 46 of file McPairEnergyAverage.cpp.
References McMd::Analyzer::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Analyzer::outputFileName(), McMd::Analyzer::readInterval(), McMd::Analyzer::readOutputFileName(), and Util::Average::setNSamplePerBlock().
void McMd::McPairEnergyAverage::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive
Reimplemented from McMd::Analyzer.
Definition at line 65 of file McPairEnergyAverage.cpp.
References McMd::Analyzer::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Analyzer::outputFileName(), and UTIL_THROW.
void McMd::McPairEnergyAverage::save (Serializable::OArchive & ar) [virtual]
Save state to an archive.
Parameters:
ar saving (output) archive
Reimplemented from McMd::Analyzer.
Definition at line 86 of file McPairEnergyAverage.cpp.
template<class Archive > void McMd::McPairEnergyAverage::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar archive
version archive version id
Reimplemented from McMd::Analyzer.
Definition at line 113 of file McPairEnergyAverage.h.
References McMd::serialize().
void McMd::McPairEnergyAverage::setup () [virtual]
Clear accumulator.
Reimplemented from McMd::Analyzer.
Definition at line 92 of file McPairEnergyAverage.cpp.
References Util::Average::clear().
void McMd::McPairEnergyAverage::sample (long iStep) [virtual]
Calculate, analyze and/or output a physical quantity.
Take an action if iStep is a multiple of interval. If iStep is not a multiple of interval, this method should do nothing and return immediately.
Parameters:
iStep current simulation step index.
Implements McMd::Analyzer.
Definition at line 98 of file McPairEnergyAverage.cpp.
References McMd::System::boundary(), McMd::McPairPotential::cellList(), McMd::CellList::getCellNeighbors(), McMd::Analyzer::isAtInterval(), McMd::Mask::isMasked(), McMd::Atom::mask(), McMd::PairSelector::match(), McMd::McSystem::pairPotential(), McMd::Atom::position(), Util::Average::sample(), Util::FSArray< Data, Capacity >::size(), McMd::SystemAnalyzer< McSystem >::system(), McMd::CellList::totCells(), and McMd::Atom::typeId().
void McMd::McPairEnergyAverage::output () [virtual]
Output results at end of simulation.
Reimplemented from McMd::Analyzer.
Definition at line 152 of file McPairEnergyAverage.cpp.
References McMd::Analyzer::fileMaster(), Util::Average::nSamplePerBlock(), Util::FileMaster::openOutputFile(), Util::Average::output(), McMd::Analyzer::outputFileName(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
McPairEnergyAverage.h
McPairEnergyAverage.cpp