Simpatico: DdMd::DiagnosticManager Class Reference
DdMd::DiagnosticManager Class Reference
Diagnostics
Detailed Description
Manager for a list of Diagnostic objects.
Definition at line 27 of file ddMd/diagnostics/DiagnosticManager.h.
#include <DiagnosticManager.h>
Public Member Functions
DiagnosticManager (Simulation &simulation)
Constructor.
virtual ~DiagnosticManager ()
Destructor.
virtual void readParam (std::istream &in)
Read parameter file.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void setup ()
Call setup method of each Diagnostic.
void clear ()
Call clear method of each Diagnostic.
void sample (long iStep)
Call sample method of each Diagnostic.
void output ()
Call output method of each diagnostic.
virtual Factory< Diagnostic > * newDefaultFactory () const
Return pointer to a new default factory.
Public Member Functions inherited from Util::Manager< Diagnostic >
Manager ()
Constructor.
virtual ~Manager ()
Destructor.
void addSubfactory (Factory< Diagnostic > &subfactory)
Set a SubFactory for this Manager.
void setFactory (Factory< Diagnostic > &factory)
Associate a Factory with this Manager.
void setFactory (Factory< Diagnostic > *factoryPtr)
Associated a Factory with this Manager (pass by pointer).
void append (Diagnostic &data, const std::string &name)
Append a Data object to the end of the sequence.
int size () const
Get logical size.
std::string className (int i) const
Get the subclass name for object number i.
Factory< Diagnostic > & factory ()
Return a reference to the factory.
bool hasFactory () const
Return true if this Manager has a Factory, false otherwise.
Diagnostic & operator[] (int i) const
Mimic C array subscripting.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
std::string className () const
Get class name string.
virtual void readParameters (std::istream &in)
Read body of parameter block, without opening and closing lines.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an archive.
void resetParam ()
Resets ParamComposite to its empty state.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add a new Param < Type > object, and read its value.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add a C array parameter, and read its elements.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and read its elements.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n)
Add and read a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
Begin & readBegin (std::istream &in, const char *label)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a child ParamComposite.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add a new Param < Type > object, and load its value.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add a C array parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and load its elements.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n)
Add and load a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a DMatrix < Type > C two-dimensional matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
template<typename Type >
ScalarParam< Type > & add (const char *label, Type &value)
Add a new Param < Type > object to the format array.
template<typename Type >
CArrayParam< Type > & addCArray (const char *label, Type *value, int n)
Add a C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (const char *label, DArray< Type > &array, int n)
Add a DArray<Type> parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (const char *label, FArray< Type, N > &array)
Add a FArray<Type> parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (const char *label, Type *value, int m, int n)
Add a C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & addDMatrix (const char *label, DMatrix< Type > &matrix, int m, int n)
Add a C two-dimensional array parameter.
Begin & addBegin (const char *label)
Add a class label and opening bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Add a new Blank object, representing a blank line.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have a communicator?
MPI::Intracomm & ioCommunicator () const
Get the communicator.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::Manager< Diagnostic >
void beginReadManager (std::istream &in)
Read opening line: "ManagerName{".
void readChildren (std::istream &in)
Read child blocks, return when closing bracket encountered.
void endReadManager ()
Add closing bracket to output format.
void initFactory ()
Create factory if necessary.
Constructor & Destructor Documentation
DdMd::DiagnosticManager::DiagnosticManager (Simulation & simulation)
Constructor.
Definition at line 22 of file ddMd/diagnostics/DiagnosticManager.cpp.
References Util::ParamComposite::setClassName().
DdMd::DiagnosticManager::~DiagnosticManager () virtual
Destructor.
Definition at line 30 of file ddMd/diagnostics/DiagnosticManager.cpp.
Member Function Documentation
void DdMd::DiagnosticManager::readParam (std::istream & in) virtual
Read parameter file.
Parameters
in input parameter file stream.
Reimplemented from Util::Manager< Diagnostic >.
Definition at line 38 of file ddMd/diagnostics/DiagnosticManager.cpp.
References DdMd::Diagnostic::baseInterval, Util::Manager< Diagnostic >::beginReadManager(), Util::Manager< Diagnostic >::endReadManager(), and Util::Manager< Diagnostic >::readChildren().
void DdMd::DiagnosticManager::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::Manager< Diagnostic >.
Definition at line 49 of file ddMd/diagnostics/DiagnosticManager.cpp.
References DdMd::Diagnostic::baseInterval, and Util::Manager< Data >::loadParameters().
void DdMd::DiagnosticManager::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::Manager< Diagnostic >.
Definition at line 58 of file ddMd/diagnostics/DiagnosticManager.cpp.
References DdMd::Diagnostic::baseInterval, and Util::Manager< Data >::save().
void DdMd::DiagnosticManager::setup ()
Call setup method of each Diagnostic.
Definition at line 68 of file ddMd/diagnostics/DiagnosticManager.cpp.
References Util::Manager< Diagnostic >::size().
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::DiagnosticManager::clear ()
Call clear method of each Diagnostic.
Definition at line 78 of file ddMd/diagnostics/DiagnosticManager.cpp.
References Util::Manager< Diagnostic >::size().
Referenced by DdMd::Integrator::clear().
void DdMd::DiagnosticManager::sample (long iStep)
Call sample method of each Diagnostic.
Definition at line 88 of file ddMd/diagnostics/DiagnosticManager.cpp.
References DdMd::Diagnostic::baseInterval, and Util::Manager< Diagnostic >::size().
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::DiagnosticManager::output ()
Call output method of each diagnostic.
Definition at line 102 of file ddMd/diagnostics/DiagnosticManager.cpp.
References Util::Manager< Diagnostic >::size().
Factory< Diagnostic > * DdMd::DiagnosticManager::newDefaultFactory () const virtual
Return pointer to a new default factory.
Implements Util::Manager< Diagnostic >.
Definition at line 112 of file ddMd/diagnostics/DiagnosticManager.cpp.
The documentation for this class was generated from the following files:
ddMd/diagnostics/DiagnosticManager.h
ddMd/diagnostics/DiagnosticManager.cpp