Simpatico: DdMd::AnalyzerManager Class Reference
DdMd::AnalyzerManager Class Reference
Analyzers
Detailed Description
Manager for a list of Analyzer objects.
Definition at line 27 of file ddMd/analyzers/AnalyzerManager.h.
#include <AnalyzerManager.h>
Public Member Functions
AnalyzerManager (Simulation &simulation)
Constructor.
virtual ~AnalyzerManager ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameter block (without begin and end).
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void setup ()
Call setup method of each Analyzer.
void clear ()
Call clear method of each Analyzer.
void sample (long iStep)
Call sample method of each Analyzer, if scheduled.
void output ()
Call output method of each analyzer.
virtual Factory< Analyzer > * newDefaultFactory () const
Return pointer to a new default factory.
Constructor & Destructor Documentation
DdMd::AnalyzerManager::AnalyzerManager (Simulation & simulation)
Constructor.
Definition at line 22 of file ddMd/analyzers/AnalyzerManager.cpp.
References Util::ParamComposite::setClassName().
DdMd::AnalyzerManager::~AnalyzerManager () [virtual]
Destructor.
Definition at line 30 of file ddMd/analyzers/AnalyzerManager.cpp.
Member Function Documentation
void DdMd::AnalyzerManager::readParameters (std::istream & in) [virtual]
Read parameter block (without begin and end).
Parameters:
in input parameter file stream.
Reimplemented from Util::Manager< Analyzer >.
Definition at line 38 of file ddMd/analyzers/AnalyzerManager.cpp.
References DdMd::Analyzer::baseInterval.
void DdMd::AnalyzerManager::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from Util::Manager< Analyzer >.
Definition at line 47 of file ddMd/analyzers/AnalyzerManager.cpp.
References DdMd::Analyzer::baseInterval.
void DdMd::AnalyzerManager::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from Util::Manager< Analyzer >.
Definition at line 56 of file ddMd/analyzers/AnalyzerManager.cpp.
References DdMd::Analyzer::baseInterval.
void DdMd::AnalyzerManager::setup ()
Call setup method of each Analyzer.
Definition at line 66 of file ddMd/analyzers/AnalyzerManager.cpp.
References Util::Manager< Analyzer >::size().
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::AnalyzerManager::clear ()
Call clear method of each Analyzer.
Definition at line 76 of file ddMd/analyzers/AnalyzerManager.cpp.
References Util::Manager< Analyzer >::size().
Referenced by DdMd::Integrator::clear().
void DdMd::AnalyzerManager::sample (long iStep)
Call sample method of each Analyzer, if scheduled.
Calls sample methods of each analyzer only if:
Analyzer::baseInterval is positive
iStep is a multiple of Analyzer::baseInterval
iStep is a multiple of the analyzer interval
Parameters:
iStep time step counter
Definition at line 86 of file ddMd/analyzers/AnalyzerManager.cpp.
References DdMd::Analyzer::baseInterval, and Util::Manager< Analyzer >::size().
Referenced by DdMd::TwoStepIntegrator::run().
void DdMd::AnalyzerManager::output ()
Call output method of each analyzer.
Definition at line 102 of file ddMd/analyzers/AnalyzerManager.cpp.
References Util::Manager< Analyzer >::size().
Factory< Analyzer > * DdMd::AnalyzerManager::newDefaultFactory () const [virtual]
Return pointer to a new default factory.
Implements Util::Manager< Analyzer >.
Definition at line 112 of file ddMd/analyzers/AnalyzerManager.cpp.
The documentation for this class was generated from the following files:
ddMd/analyzers/AnalyzerManager.h
ddMd/analyzers/AnalyzerManager.cpp