Simpatico: McMd::SemiGrandDistribution Class Reference
McMd::SemiGrandDistribution Class Reference
Diagnostics
Detailed Description
Calculate distribution of type indices for mutable species.
Definition at line 27 of file SemiGrandDistribution.h.
#include <SemiGrandDistribution.h>
Public Member Functions
SemiGrandDistribution (McSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read output file and nStepPerSample.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
void sample (long iStep)
Evaluate energy and print.
virtual void output ()
Output final summary and file format.
Constructor & Destructor Documentation
McMd::SemiGrandDistribution::SemiGrandDistribution (McSystem & system)
Constructor.
Definition at line 28 of file SemiGrandDistribution.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::SemiGrandDistribution::readParameters (std::istream & in) [virtual]
Read output file and nStepPerSample.
Reimplemented from McMd::Diagnostic.
Definition at line 41 of file SemiGrandDistribution.cpp.
References Util::IntDistribution::clear(), McMd::Diagnostic::readInterval(), McMd::Diagnostic::readOutputFileName(), Util::IntDistribution::setParam(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemDiagnostic< McSystem >::system(), and UTIL_THROW.
void McMd::SemiGrandDistribution::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 65 of file SemiGrandDistribution.cpp.
References McMd::Species::capacity(), McMd::Species::isMutable(), McMd::Species::mutator(), McMd::Simulation::nSpecies(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemDiagnostic< McSystem >::system(), and UTIL_THROW.
void McMd::SemiGrandDistribution::save (Serializable::OArchive & ar) [virtual]
Save state to an archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 92 of file SemiGrandDistribution.cpp.
template<class Archive > void McMd::SemiGrandDistribution::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar archive
version archive version id
Reimplemented from McMd::Diagnostic.
Definition at line 101 of file SemiGrandDistribution.h.
References McMd::serialize().
void McMd::SemiGrandDistribution::sample (long iStep) [virtual]
Evaluate energy and print.
Implements McMd::Diagnostic.
Definition at line 99 of file SemiGrandDistribution.cpp.
References McMd::Diagnostic::isAtInterval(), Util::IntDistribution::sample(), and McMd::SpeciesMutator::stateOccupancy().
void McMd::SemiGrandDistribution::output () [virtual]
Output final summary and file format.
Reimplemented from McMd::Diagnostic.
Definition at line 109 of file SemiGrandDistribution.cpp.
References McMd::Diagnostic::fileMaster(), Util::FileMaster::openOutputFile(), Util::IntDistribution::output(), and McMd::Diagnostic::outputFileName().
The documentation for this class was generated from the following files:
SemiGrandDistribution.h
SemiGrandDistribution.cpp