Simpatico: McMd::CfbRingRebridgeMove Class Reference
McMd::CfbRingRebridgeMove Class Reference
Monte Carlo Moves
Detailed Description
Configuration bias rebridge moves for ring molecules.
An interior bridge of atoms with length nRegrow is randomly selected and is regrown using the configuration biased moves. The first nRegrow-1 atoms are re-grown using the same biasing function as those for end atom moves, and the last atom is re-grown using the crank-shaft like trimer re-growth algorithm.
Definition at line 34 of file CfbRingRebridgeMove.h.
#include <CfbRingRebridgeMove.h>
Public Member Functions
CfbRingRebridgeMove (McSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read species to which displacement is applied.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to an archive.
virtual bool move ()
Generate and accept or reject configuration bias move.
Protected Attributes
DArray< Vector > oldPos_
Array of old positions of temporarily deleted atoms.
int speciesId_
Integer index for molecular species.
int nRegrow_
Number of particles at end to attempt to regrow.
Constructor & Destructor Documentation
McMd::CfbRingRebridgeMove::CfbRingRebridgeMove (McSystem & system)
Constructor.
Definition at line 29 of file CfbRingRebridgeMove.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::CfbRingRebridgeMove::readParameters (std::istream & in) [virtual]
Read species to which displacement is applied.
Parameters:
in input parameter stream
Reimplemented from McMd::CfbRebridgeBase.
Definition at line 38 of file CfbRingRebridgeMove.cpp.
References Util::DArray< Data >::allocate(), nRegrow_, oldPos_, McMd::McMove::readProbability(), McMd::CfbRebridgeBase::setup(), McMd::McMove::simulation(), McMd::Simulation::species(), speciesId_, and UTIL_THROW.
void McMd::CfbRingRebridgeMove::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive
Reimplemented from McMd::CfbRebridgeBase.
Definition at line 65 of file CfbRingRebridgeMove.cpp.
References Util::DArray< Data >::allocate(), nRegrow_, oldPos_, McMd::CfbRebridgeBase::setup(), McMd::McMove::simulation(), McMd::Simulation::species(), speciesId_, and UTIL_THROW.
void McMd::CfbRingRebridgeMove::save (Serializable::OArchive & ar) [virtual]
Save state to an archive.
Parameters:
ar saving (output) archive
Reimplemented from McMd::CfbRebridgeBase.
Definition at line 87 of file CfbRingRebridgeMove.cpp.
References nRegrow_, and speciesId_.
bool McMd::CfbRingRebridgeMove::move () [virtual]
Generate and accept or reject configuration bias move.
Reimplemented from McMd::McMove.
Definition at line 112 of file CfbRingRebridgeMove.cpp.
References McMd::Molecule::atom(), McMd::Molecule::bond(), McMd::McMove::incrementNAccept(), McMd::McMove::incrementNAttempt(), Util::Random::metropolis(), McMd::Molecule::nAtom(), nRegrow_, oldPos_, McMd::McSystem::pairPotential(), McMd::Atom::position(), McMd::McMove::random(), McMd::System::randomMolecule(), speciesId_, McMd::SystemMove::system(), McMd::Group< NAtom >::typeId(), Util::Random::uniformInt(), McMd::McPairPotential::updateAtomCell(), and UTIL_THROW.
Member Data Documentation
DArray<Vector> McMd::CfbRingRebridgeMove::oldPos_ [protected]
Array of old positions of temporarily deleted atoms.
Definition at line 73 of file CfbRingRebridgeMove.h.
Referenced by loadParameters(), move(), and readParameters().
int McMd::CfbRingRebridgeMove::speciesId_ [protected]
Integer index for molecular species.
Definition at line 76 of file CfbRingRebridgeMove.h.
Referenced by loadParameters(), move(), readParameters(), and save().
int McMd::CfbRingRebridgeMove::nRegrow_ [protected]
Number of particles at end to attempt to regrow.
Definition at line 79 of file CfbRingRebridgeMove.h.
Referenced by loadParameters(), move(), readParameters(), and save().
The documentation for this class was generated from the following files:
CfbRingRebridgeMove.h
CfbRingRebridgeMove.cpp