Simpatico: McMd::PointGenerator Class Reference
McMd::PointGenerator Class Reference
McMd namespace » Generators
Detailed Description
Generator for monoatomic molecules (atoms).
Definition at line 32 of file PointGenerator.h.
#include <PointGenerator.h>
Public Member Functions
PointGenerator (Simp::Species &species, System &system)
Constructor.
Public Member Functions inherited from McMd::Generator
Generator (Species &species, System &system)
Constructor.
virtual ~Generator ()
Destructor.
void setBondPotential (BondPotential &bondPotential)
Create an association with a BondPotential.
virtual bool generate (int nMolecule, Array< double > const &diameters, CellList &cellList)
Generate nMolecule molecules of the associated Species.
Protected Member Functions
bool attemptPlaceMolecule (Molecule &molecule, Array< double > const &diameters, CellList &cellList)
Attempt to place an "molecule" (i.e., an atom).
Protected Member Functions inherited from McMd::Generator
bool attemptPlaceAtom (Atom &atom, const Array< double > &diameters, CellList &cellList)
Attempt to place an atom.
virtual bool attemptPlaceMolecule (Molecule &molecule, const Array< double > &diameters, CellList &cellList)=0
Attempt to insert an entire molecule (pure virtual).
const Species & species ()
Get the associated Species by reference.
Simulation & simulation ()
Get the associated Simulation by reference.
System & system ()
Get the associated System by reference.
const Boundary & boundary () const
Get the associated Boundary by reference.
const BondPotential & bondPotential ()
Get the associated BondPotential by reference.
Additional Inherited Members
Static Public Member Functions inherited from McMd::Generator
static void setupCellList (int atomCapacity, Boundary &boundary, const Array< double > &diameters, CellList &cellList)
Allocate any required memory for the cell list.
Constructor & Destructor Documentation
McMd::PointGenerator::PointGenerator (Simp::Species & species, System & system)
Constructor.
Parameters
species molecular Species to be generated
system parent System object
Definition at line 20 of file PointGenerator.cpp.
Member Function Documentation
bool McMd::PointGenerator::attemptPlaceMolecule (Molecule & molecule, Array< double > const & diameters, CellList & cellList) protected
Attempt to place an "molecule" (i.e., an atom).
If successful, the atom is added to the CellList.
Parameters
molecule reference to Molecule object
diameters array of hard-core exclusion diameters
cellList CellList object, modified if successful.
Returns
true for success, false for failure
Definition at line 28 of file PointGenerator.cpp.
References McMd::Molecule::atom(), McMd::Generator::attemptPlaceAtom(), McMd::Generator::boundary(), McMd::Atom::position(), Simp::OrthorhombicBoundary::randomPosition(), and McMd::Generator::simulation().
The documentation for this class was generated from the following files:
PointGenerator.h
PointGenerator.cpp