Simpatico: McMd::StructureFactorPGrid Class Reference
McMd::StructureFactorPGrid Class Reference
MC/MD Analyzers
Detailed Description
StructureFactorPGrid evaluates structure factors in Fourier space.
This class evaluates the structures factors for all wavevectors for all wavevectors within a grid, within a region in which all of the h, k, l integer wavevector components (i.e., Miller indices) has an absolute magnitude less than or equal to a parameter hMax.
The class also requires a user to specify a variable lattice of enum type LatticeSystem whose value (e.g., Cubic, Orthorhombic, Triclinic) determines the symmetry group that is used to group group equivalent wavevectors into "stars". Use Triclinic to impose no symmetry.
Example: Here is parameter file for a system with nAtomType = 2, with two monomer types 0 and 1, for calculating the total, 00, and 01 correlation functions on a grid with Miller indices up and including 5:
 StructureFactorPGrid{
    interval                     1000
    outputFileName     StructureFactorPGrid
    nAtomTypeIdPair                  3
    atomTypeIdPairs          -1     -1
                              0      0
                              0      1
    hMax                             5
        lattice                      Cubic
 }
At the end of a simulation, all of the structure factors are output in a file with a suffix *.dat. Each line in this file contains the 3 Miller indices of a wavevector, the absolute magnitude of the wavevector, and a list of nAtomTypeIdPair structure factor values for the wavevector, one for each atomTypeId pair.
See also:
parameter file format
Definition at line 61 of file StructureFactorPGrid.h.
#include <StructureFactorPGrid.h>
Public Member Functions
StructureFactorPGrid (System &system)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Set up before a simulation.
virtual void output ()
Output structure factors, averaged over stars.
Constructor & Destructor Documentation
McMd::StructureFactorPGrid::StructureFactorPGrid (System & system)
Constructor.
Parameters:
system reference to parent System object
Definition at line 24 of file StructureFactorPGrid.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::StructureFactorPGrid::readParameters (std::istream & in) [virtual]
Read parameters from file.
Input format:
int interval sampling interval
string outputFileName output file base name
int nAtomTypeIdPair number of Atom typeId pairs
DArray<Pair<int>> atomTypeIdPairs integer typeId pairs
int hMax maximum Miller index
Parameters:
in input parameter stream
Reimplemented from McMd::StructureFactorP.
Definition at line 35 of file StructureFactorPGrid.cpp.
References Util::SymmetryGroup< Symmetry >::add(), Util::DMatrix< Data >::allocate(), Util::DArray< Data >::allocate(), McMd::StructureFactorP::atomTypeIdPairs_, Util::SymmetryGroup< Symmetry >::makeCompleteGroup(), Util::PointGroup::makeStar(), McMd::Simulation::nAtomType(), McMd::StructureFactorP::nAtomType_, McMd::StructureFactorP::nAtomTypeIdPair_, McMd::StructureFactorP::nSample_, McMd::StructureFactorP::nWave_, Util::PointSymmetry::R(), McMd::Analyzer::readInterval(), McMd::Analyzer::readOutputFileName(), McMd::System::simulation(), Util::FSArray< Data, Capacity >::size(), McMd::StructureFactorP::structureFactors_, McMd::SystemAnalyzer< System >::system(), UTIL_THROW, McMd::StructureFactorP::waveIntVectors_, and McMd::StructureFactorP::waveVectors_.
void McMd::StructureFactorPGrid::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from McMd::StructureFactorP.
Definition at line 132 of file StructureFactorPGrid.cpp.
References Util::DMatrix< Data >::allocate(), Util::DArray< Data >::allocate(), McMd::StructureFactorP::atomTypeIdPairs_, McMd::StructureFactorP::nAtomType_, McMd::StructureFactorP::nAtomTypeIdPair_, McMd::StructureFactorP::nSample_, McMd::StructureFactorP::nWave_, McMd::StructureFactorP::structureFactors_, McMd::SystemAnalyzer< System >::system(), UTIL_THROW, McMd::StructureFactorP::waveIntVectors_, and McMd::StructureFactorP::waveVectors_.
void McMd::StructureFactorPGrid::save (Serializable::OArchive & ar) [virtual]
Save state to an archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::StructureFactorP.
Definition at line 171 of file StructureFactorPGrid.cpp.
template<class Archive > void McMd::StructureFactorPGrid::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar archive
version archive version id
Reimplemented from McMd::StructureFactorP.
Definition at line 149 of file StructureFactorPGrid.h.
References McMd::serialize().
void McMd::StructureFactorPGrid::setup () [virtual]
Set up before a simulation.
Reimplemented from McMd::StructureFactorP.
Definition at line 237 of file StructureFactorPGrid.cpp.
void McMd::StructureFactorPGrid::output () [virtual]
Output structure factors, averaged over stars.
Reimplemented from McMd::StructureFactorP.
Definition at line 240 of file StructureFactorPGrid.cpp.
References McMd::StructureFactorP::atomTypeIdPairs_, Util::Dimension, McMd::Analyzer::fileMaster(), McMd::StructureFactorP::nAtomTypeIdPair_, McMd::StructureFactorP::nSample_, Util::FileMaster::openOutputFile(), McMd::StructureFactorP::outputFile_, McMd::Analyzer::outputFileName(), McMd::StructureFactorP::structureFactors_, Util::toString(), McMd::StructureFactorP::waveIntVectors_, McMd::StructureFactorP::waveVectors_, and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
StructureFactorPGrid.h
StructureFactorPGrid.cpp