Simpatico: Inter::FeneBond Class Reference
Inter::FeneBond Class Reference
Bond Interactions
Detailed Description
A finitely-extensible nonlinear element (FENE) bond potential.
Finitely extensible nonlinear element (FENE) bond potential V(r) = -0.5*kappa*r0^2 log(1 - (r^2/r0^2)) with a spring constant kappa and maximum bond length r0.
This implementation uses the FENE potential for distances less than a cutoff rl at which the FENE potentail reaches a parameter energyCutoff, and a linear potential for all r > rl.
Definition at line 36 of file FeneBond.h.
#include <FeneBond.h>
Public Member Functions
FeneBond ()
Default constructor.
FeneBond (const FeneBond &other)
Copy constructor.
FeneBond & operator= (const FeneBond &other)
Assignment.
void setNBondType (int nBondType)
Set the number of bond types.
void readParameters (std::istream &in)
Read bond interaction parameters from input stream.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void set (std::string name, int type, double value)
Modify a parameter, identified by a string.
double energy (double rSq, int type) const
Returns potential energy for one bond.
double forceOverR (double rSq, int type) const
Returns force/distance for one bond, for use in MD.
double randomBondLength (Random *random, double beta, int type) const
Return bond length chosen from equilibrium distribution.
double get (std::string name, int type) const
Get a parameter value, identified by a string.
Constructor & Destructor Documentation
Inter::FeneBond::FeneBond ()
Default constructor.
Definition at line 22 of file FeneBond.cpp.
References Util::ParamComposite::setClassName().
Inter::FeneBond::FeneBond (const FeneBond & other)
Copy constructor.
Definition at line 42 of file FeneBond.cpp.
Member Function Documentation
FeneBond & Inter::FeneBond::operator= (const FeneBond & other)
Assignment.
Definition at line 61 of file FeneBond.cpp.
void Inter::FeneBond::setNBondType (int nBondType)
Set the number of bond types.
Parameters:
nBondType number of bond types
Definition at line 82 of file FeneBond.cpp.
References UTIL_THROW.
void Inter::FeneBond::readParameters (std::istream & in) [virtual]
Read bond interaction parameters from input stream.
Format: kappa CArray<double> length CArray<double> energyCutoff double
Precondition:
nBondType must be set, by calling setNBondType().
Parameters:
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 93 of file FeneBond.cpp.
References UTIL_THROW.
void Inter::FeneBond::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 128 of file FeneBond.cpp.
References UTIL_THROW.
void Inter::FeneBond::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 149 of file FeneBond.cpp.
References Util::BinaryFileOArchive::pack().
void Inter::FeneBond::set (std::string name, int type, double value)
Modify a parameter, identified by a string.
Parameters:
name parameter name
type bond type index
value new value of parameter
Definition at line 202 of file FeneBond.cpp.
References UTIL_THROW.
double Inter::FeneBond::energy (double rSq, int type) const [inline]
Returns potential energy for one bond.
Parameters:
rSq square of distance between bonded particles.
type type of bond.
Definition at line 189 of file FeneBond.h.
Referenced by randomBondLength().
double Inter::FeneBond::forceOverR (double rSq, int type) const [inline]
Returns force/distance for one bond, for use in MD.
A positive return value represents a repulsive radial force.
Parameters:
rSq square of distance between bonded particles.
type type of bond.
Returns:
scalar repulsive force divided by distance.
Definition at line 204 of file FeneBond.h.
double Inter::FeneBond::randomBondLength (Random * random, double beta, int type) const
Return bond length chosen from equilibrium distribution.
This function returns a bond length chosen from the Boltzmann distribution of lengths for bonds of random orientation. The distribution P(l) of values of the length l is proportional to l*l*exp[-beta*phi(l) ], where phi(l) is the bond energy.
Parameters:
random pointer to random number generator object.
beta inverse temperature
type bond type
Returns:
random bond length chosen from equilibrium distribution.
Definition at line 176 of file FeneBond.cpp.
References energy(), Util::Random::gaussian(), and Util::Random::uniform().
double Inter::FeneBond::get (std::string name, int type) const
Get a parameter value, identified by a string.
Parameters:
name parameter name
type bond type index
Definition at line 230 of file FeneBond.cpp.
References UTIL_THROW.
The documentation for this class was generated from the following files:
FeneBond.h
FeneBond.cpp