Simpatico: Util::APArray< Data > Class Template Reference
Util::APArray< Data > Class Template Reference
Pointer Arrays
Detailed Description
template<typename Data>
class Util::APArray< Data >
Automatically resizable PArray.
An APArray is a PArray that grows as needed as objects are appended. Like any PArray, it holds pointers to objects, rather than objects. The associated objects are not destroyed when a PArray is deallocated or destroyed.
Definition at line 28 of file APArray.h.
#include <APArray.h>
Public Member Functions
APArray ()
Constructor.
APArray (const APArray< Data > &other)
Copy constructor, copy pointers.
APArray< Data > & operator= (const APArray< Data > &other)
Assignment, element by element.
virtual ~APArray ()
Destructor.
void append (Data &data)
Append an element to the end of the sequence.
void reserve (int capacity)
Reserve memory for specified number of elements.
void deallocate ()
Deallocate (delete) underlying array of pointers.
void clear ()
Reset to empty state.
Constructor & Destructor Documentation
template<typename Data > Util::APArray< Data >::APArray () [inline]
Constructor.
Definition at line 108 of file APArray.h.
template<typename Data> Util::APArray< Data >::APArray (const APArray< Data > & other)
Copy constructor, copy pointers.
Allocates new Data* array and copies pointers to Data objects.
Parameters:
other the APArray to be copied.
Allocates a new Data* array and copies all pointer values.
Parameters:
other the APArray to be copied.
Definition at line 120 of file APArray.h.
References Util::PArray< Data >::capacity_, Util::PArray< Data >::ptrs_, and Util::PArray< Data >::size_.
template<typename Data > Util::APArray< Data >::~APArray () [inline, virtual]
Destructor.
Deletes array of pointers, if allocated previously. Does not delete the associated Data objects.
Definition at line 170 of file APArray.h.
Member Function Documentation
template<typename Data> APArray< Data > & Util::APArray< Data >::operator= (const APArray< Data > & other)
Assignment, element by element.
Preconditions:
Both this and other APArrays must be allocated.
Capacity of this APArray must be >= size of RHS APArray.
Parameters:
other the rhs APArray
Definition at line 156 of file APArray.h.
References Util::PArray< Data >::size_.
template<typename Data> void Util::APArray< Data >::append (Data & data)
Append an element to the end of the sequence.
Resizes array if space is inadequate.
Parameters:
data Data object to be appended
Definition at line 217 of file APArray.h.
Referenced by DdMd::Exchanger::exchangeAtoms().
template<typename Data > void Util::APArray< Data >::reserve (int capacity)
Reserve memory for specified number of elements.
Resizes and copies array if requested capacity is less than the current capacity. Does nothing if requested capacity is greater than current capacity.
Parameters:
capacity number of elements for which to reserve space.
Definition at line 181 of file APArray.h.
References UTIL_THROW.
Referenced by DdMd::Exchanger::allocate().
template<typename Data > void Util::APArray< Data >::deallocate ()
Deallocate (delete) underlying array of pointers.
Definition at line 204 of file APArray.h.
template<typename Data > void Util::APArray< Data >::clear ()
Reset to empty state.
Definition at line 240 of file APArray.h.
Referenced by DdMd::Exchanger::exchangeAtoms().
The documentation for this class was generated from the following file:
APArray.h