Simpatico: DdMd::ExternalPotentialImpl< Interaction > Class Template Reference
DdMd::ExternalPotentialImpl< Interaction > Class Template Reference
DdMd namespace » Potential Energies » External Potentials
Detailed Description
template<class Interaction>
class DdMd::ExternalPotentialImpl< Interaction >
Implementation template for a ExternalPotential.
Definition at line 33 of file ddMd/potentials/external/ExternalPotentialImpl.h.
#include <ExternalPotentialImpl.h>
Public Member Functions
ExternalPotentialImpl (Simulation &simulation)
Constructor.
ExternalPotentialImpl ()
Default constructor (for unit testing).
virtual ~ExternalPotentialImpl ()
Destructor.
virtual void associate (Boundary &boundary, AtomStorage &storage)
Associate with related objects.
virtual void setNAtomType (int nAtomType)
Set the maximum number of atom types.
virtual void readParameters (std::istream &in)
Read external potential interaction.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from archive and initialize, for restart.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive, for restart.
Interaction interface
virtual double externalEnergy (const Vector &position, int typeId) const
Returns external potential energy of a single atom.
virtual void getExternalForce (const Vector &position, int typeId, Vector &force) const
Computes external force on one atom.
void set (std::string name, double value)
Modify a pair interaction parameter, identified by a string.
double get (std::string name) const
Get a parameter value, identified by a string.
virtual std::string interactionClassName () const
Return external interaction class name (e.g., "LamellarOrderingExternal").
Interaction & interaction ()
Return external interaction by reference.
const Interaction & interaction () const
Return external interaction by const reference.
Total Energy and Forces
virtual void computeForces ()
Calculate external forces for all atoms in this Simulation.
virtual void computeEnergy (MPI::Intracomm &communicator)
Compute the total external energy for all processors.
Public Member Functions inherited from DdMd::ExternalPotential
ExternalPotential (Simulation &simulation)
Constructor.
ExternalPotential ()
Default constructor (for unit testing).
virtual ~ExternalPotential ()
Destructor.
Public Member Functions inherited from DdMd::Potential
Potential ()
Constructor.
virtual ~Potential ()
Destructor.
void setReverseUpdateFlag (bool reverseUpdateFlag)
Set flag to identify if reverse communication is enabled.
bool reverseUpdateFlag () const
Get flag to identify if reverse communication is enabled.
double energy () const
Return the total potential, from all processors.
void unsetEnergy ()
Mark the energy as unknown (nullify).
bool isEnergySet () const
Is the energy set (known)?
virtual void computeStress (MPI::Intracomm &communicator)
Compute stress on all processors.
virtual void computeForcesAndStress (MPI::Intracomm &communicator)
Compute forces and stress for all processors.
Tensor stress () const
Return the stress tensor.
double pressure () const
Return the pressure.
void unsetStress ()
Mark the stress as unknown (nullify).
bool isStressSet () const
Is the stress set (known)?
virtual bool isValid (MPI::Intracomm &communicator) const
Is the potential in a valid internal state?
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > C matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > C matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Create and add a Begin object representing a class name and bracket.
End & addEnd ()
Create and add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from DdMd::ExternalPotential
Simulation & simulation ()
Get the parent Simulation by reference.
Boundary & boundary ()
Get the Boundary by reference.
AtomStorage & storage ()
Get the AtomStorage by reference.
Protected Member Functions inherited from DdMd::Potential
void setEnergy (double energy)
Set a value for the total energy.
void setStress (const Tensor &stress)
Set a value for the total stress.
void incrementPairStress (const Vector &f, const Vector &dr, Tensor &stress) const
Add a pair contribution to the stress tensor.
void reduceEnergy (double localEnergy, MPI::Intracomm &communicator)
Add local energies from all processors, set energy on master.
void reduceStress (Tensor &localStress, MPI::Intracomm &communicator)
Add local stresses from all processors, set total on master.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Constructor & Destructor Documentation
template<class Interaction > DdMd::ExternalPotentialImpl< Interaction >::ExternalPotentialImpl (Simulation & simulation)
Constructor.
Definition at line 211 of file ddMd/potentials/external/ExternalPotentialImpl.h.
References DdMd::Simulation::boundary(), DdMd::ExternalPotentialImpl< Interaction >::interaction(), DdMd::Simulation::nAtomType(), and DdMd::ExternalPotentialImpl< Interaction >::setNAtomType().
template<class Interaction > DdMd::ExternalPotentialImpl< Interaction >::ExternalPotentialImpl ()
Default constructor (for unit testing).
Definition at line 225 of file ddMd/potentials/external/ExternalPotentialImpl.h.
template<class Interaction > DdMd::ExternalPotentialImpl< Interaction >::~ExternalPotentialImpl () virtual
Destructor.
Definition at line 235 of file ddMd/potentials/external/ExternalPotentialImpl.h.
Member Function Documentation
template<class Interaction > void DdMd::ExternalPotentialImpl< Interaction >::associate (Boundary & boundary, AtomStorage & storage) virtual
Associate with related objects.
Call iff object instantiated with default constructor.
Parameters
boundary associated Boundary object.
storage associated AtomStorage object.
Reimplemented from DdMd::ExternalPotential.
Definition at line 249 of file ddMd/potentials/external/ExternalPotentialImpl.h.
References DdMd::ExternalPotential::associate(), and DdMd::ExternalPotentialImpl< Interaction >::interaction().
template<class Interaction > void DdMd::ExternalPotentialImpl< Interaction >::setNAtomType (int nAtomType) virtual
Set the maximum number of atom types.
Set the maximum number of atom types (for unit testing).
Call iff object instantiated with default constructor.
Parameters
nAtomType maximum number of atomTypes (max index+1)
Implements DdMd::ExternalPotential.
Definition at line 259 of file ddMd/potentials/external/ExternalPotentialImpl.h.
References DdMd::ExternalPotentialImpl< Interaction >::interaction().
Referenced by DdMd::ExternalPotentialImpl< Interaction >::ExternalPotentialImpl().
template<class Interaction > void DdMd::ExternalPotentialImpl< Interaction >::readParameters (std::istream & in) virtual
Read external potential interaction.
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 266 of file ddMd/potentials/external/ExternalPotentialImpl.h.
References Util::ParamComposite::addParamComposite(), DdMd::ExternalPotentialImpl< Interaction >::interaction(), and UTIL_CHECK.
template<class Interaction > void DdMd::ExternalPotentialImpl< Interaction >::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from archive and initialize, for restart.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 279 of file ddMd/potentials/external/ExternalPotentialImpl.h.
References Util::ParamComposite::addParamComposite(), DdMd::ExternalPotentialImpl< Interaction >::interaction(), and UTIL_CHECK.
template<class Interaction > void DdMd::ExternalPotentialImpl< Interaction >::save (Serializable::OArchive & ar) virtual
Save internal state to an archive, for restart.
Call only on master processor.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 292 of file ddMd/potentials/external/ExternalPotentialImpl.h.
References DdMd::ExternalPotentialImpl< Interaction >::interaction().
template<class Interaction > double DdMd::ExternalPotentialImpl< Interaction >::externalEnergy (const Vector & position, int typeId) const virtual
Returns external potential energy of a single atom.
Parameters
position atomic position Vector
typeId atom type index
Returns
external potential energy
Implements DdMd::ExternalPotential.
Definition at line 300 of file ddMd/potentials/external/ExternalPotentialImpl.h.
References DdMd::ExternalPotentialImpl< Interaction >::interaction().
template<class Interaction > void DdMd::ExternalPotentialImpl< Interaction >::getExternalForce (const Vector & position, int typeId, Vector & force) const virtual
Computes external force on one atom.
Parameters
position atom position (input)
typeId atom type index (input)
force force on the atom (output)
Implements DdMd::ExternalPotential.
Definition at line 309 of file ddMd/potentials/external/ExternalPotentialImpl.h.
References DdMd::ExternalPotentialImpl< Interaction >::interaction().
template<class Interaction> void DdMd::ExternalPotentialImpl< Interaction >::set (std::string name, double value) inline virtual
Modify a pair interaction parameter, identified by a string.
Parameters
name parameter name
value new value of parameter
Implements DdMd::ExternalPotential.
Definition at line 123 of file ddMd/potentials/external/ExternalPotentialImpl.h.
template<class Interaction> double DdMd::ExternalPotentialImpl< Interaction >::get (std::string name) const inline virtual
Get a parameter value, identified by a string.
Parameters
name parameter name
Implements DdMd::ExternalPotential.
Definition at line 131 of file ddMd/potentials/external/ExternalPotentialImpl.h.
template<class Interaction > std::string DdMd::ExternalPotentialImpl< Interaction >::interactionClassName () const virtual
Return external interaction class name (e.g., "LamellarOrderingExternal").
Implements DdMd::ExternalPotential.
Definition at line 317 of file ddMd/potentials/external/ExternalPotentialImpl.h.
References DdMd::ExternalPotentialImpl< Interaction >::interaction().
template<class Interaction > Interaction & DdMd::ExternalPotentialImpl< Interaction >::interaction ()
Return external interaction by reference.
Return underlying interaction object by reference.
Definition at line 334 of file ddMd/potentials/external/ExternalPotentialImpl.h.
Referenced by DdMd::ExternalPotentialImpl< Interaction >::associate(), DdMd::ExternalPotentialImpl< Interaction >::externalEnergy(), DdMd::ExternalPotentialImpl< Interaction >::ExternalPotentialImpl(), DdMd::ExternalPotentialImpl< Interaction >::getExternalForce(), DdMd::ExternalPotentialImpl< Interaction >::interactionClassName(), DdMd::ExternalPotentialImpl< Interaction >::loadParameters(), DdMd::ExternalPotentialImpl< Interaction >::readParameters(), DdMd::ExternalPotentialImpl< Interaction >::save(), and DdMd::ExternalPotentialImpl< Interaction >::setNAtomType().
template<class Interaction > const Interaction & DdMd::ExternalPotentialImpl< Interaction >::interaction () const
Return external interaction by const reference.
Return underlying interaction object by const reference.
Definition at line 324 of file ddMd/potentials/external/ExternalPotentialImpl.h.
template<class Interaction > void DdMd::ExternalPotentialImpl< Interaction >::computeForces () virtual
Calculate external forces for all atoms in this Simulation.
Implements DdMd::Potential.
Definition at line 344 of file ddMd/potentials/external/ExternalPotentialImpl.h.
Referenced by DdMd::ExternalPotentialImpl< Interaction >::computeEnergy().
template<class Interaction > void DdMd::ExternalPotentialImpl< Interaction >::computeEnergy (MPI::Intracomm & communicator) virtual
Compute the total external energy for all processors.
Call on all processors.
Implements DdMd::Potential.
Definition at line 353 of file ddMd/potentials/external/ExternalPotentialImpl.h.
References DdMd::AtomStorage::begin(), DdMd::ExternalPotentialImpl< Interaction >::computeForces(), DdMd::Potential::energy(), Util::PArrayIterator< Data >::notEnd(), DdMd::Potential::reduceEnergy(), DdMd::Potential::setEnergy(), and DdMd::ExternalPotential::storage().
The documentation for this class was generated from the following file:
ddMd/potentials/external/ExternalPotentialImpl.h