Simpatico: McMd::StructureFactorGrid Class Reference
McMd::StructureFactorGrid Class Reference
McMd namespace » Analyzers » MC/MD Analyzers
Detailed Description
StructureFactorGrid evaluates structure factors in Fourier space.
This class evaluates the structures factors for all wavevectors for all wavevectors within a grid, within a region in which all of the h, k, l integer wavevector components (i.e., Miller indices) has an absolute magnitude less than or equal to a parameter hMax.
The class also requires a user to specify a variable lattice of enum type LatticeSystem whose value (e.g., Cubic, Orthorhombic, Triclinic) determines the symmetry group that is used to group group equivalent wavevectors into "stars". Use Triclinic to impose no symmetry.
Example: Here is parameter file for a system with nAtomType = 2, with two monomer types 0 and 1, for calculating the total, 00, and 01 correlation functions on a grid with Miller indices up and including 5:
StructureFactorGrid{
   interval                     1000
   outputFileName     StructureFactorGrid
   nAtomTypeIdPair                  3
   atomTypeIdPairs          -1     -1
                             0      0
                             0      1
   hMax                             5
   lattice                      Cubic
}
At the end of a simulation, all of the structure factors are output in a file with a suffix *.dat. Each line in this file contains the 3 Miller indices of a wavevector, the absolute magnitude of the wavevector, and a list of nAtomTypeIdPair structure factor values for the wavevector, one for each atomTypeId pair.
See also
parameter file format
Definition at line 61 of file mcMd/analyzers/system/StructureFactorGrid.h.
#include <StructureFactorGrid.h>
Public Member Functions
StructureFactorGrid (System &system)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Set up before a simulation.
virtual void output ()
Output structure factors, averaged over stars.
virtual void sample (long iStep)
Add particles to StructureFactor accumulators.
Public Member Functions inherited from McMd::StructureFactor
StructureFactor (System &system)
Constructor.
~StructureFactor ()
Destructor.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
Public Member Functions inherited from McMd::SystemAnalyzer< System >
SystemAnalyzer (System &system)
Constructor.
virtual ~SystemAnalyzer ()
Destructor.
Public Member Functions inherited from McMd::Analyzer
Analyzer ()
Default constructor.
virtual ~Analyzer ()
Destructor.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from McMd::Analyzer
static void initStatic ()
Define and initialize baseInterval.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Public Attributes inherited from McMd::Analyzer
static long baseInterval = 0
The interval for an Analyzer must be a multiple of baseInterval.
Protected Member Functions inherited from McMd::StructureFactor
void makeWaveVectors ()
Update wavevectors.
Protected Member Functions inherited from McMd::SystemAnalyzer< System >
System & system ()
Return reference to parent system.
Protected Member Functions inherited from McMd::Analyzer
void setFileMaster (FileMaster &fileMaster)
Set the FileMaster to use to open files.
void readInterval (std::istream &in)
Read interval from file, with error checking.
void readOutputFileName (std::istream &in)
Read outputFileName from file.
void loadInterval (Serializable::IArchive &ar)
Load interval from archive, with error checking.
void loadOutputFileName (Serializable::IArchive &ar)
Load output file name from archive.
FileMaster & fileMaster ()
Get the FileMaster by reference.
const std::string & outputFileName () const
Return outputFileName string.
std::string outputFileName (const std::string &suffix) const
Return outputFileName string with added suffix.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes inherited from McMd::StructureFactor
std::ofstream outputFile_
Output file stream.
DMatrix< double > structureFactors_
Structure factor accumulators.
DMatrix< std::complex< double > > fourierModes_
Instantaneous Fourier amplitudes (temporary)
DArray< IntVector > waveIntVectors_
Array of Miller index IntVectors for wavevectors.
DArray< Vector > waveVectors_
Array of floating point wave vectors (temporary).
DMatrix< double > modes_
Array of mode vectors.
int nWave_
Number of wavevectors.
int nMode_
Number of mode vectors.
int nSample_
Number of samples thus far.
int nAtomType_
Number of atom types, copied from Simulation::nAtomType().
bool isFirstStep_
Is this the first step?
Protected Attributes inherited from McMd::Analyzer
std::string outputFileName_
Base name of output file(s).
long interval_
Number of simulation steps between subsequent actions.
Constructor & Destructor Documentation
McMd::StructureFactorGrid::StructureFactorGrid (System & system)
Constructor.
Parameters
system reference to parent System object
Definition at line 25 of file mcMd/analyzers/system/StructureFactorGrid.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::StructureFactorGrid::readParameters (std::istream & in) virtual
Read parameters from file.
Input format:
int interval sampling interval
string outputFileName output file base name
int nMode number of modes
DMatrix<double> modes mode vectors
int hMax maximum Miller index
Parameters
in input parameter stream
Reimplemented from McMd::StructureFactor.
Definition at line 36 of file mcMd/analyzers/system/StructureFactorGrid.cpp.
References Util::SymmetryGroup< Symmetry >::add(), Util::DMatrix< Data >::allocate(), Util::DArray< Data >::allocate(), McMd::StructureFactor::fourierModes_, Util::SymmetryGroup< Symmetry >::makeCompleteGroup(), Util::PointGroup::makeStar(), McMd::StructureFactor::modes_, McMd::Simulation::nAtomType(), McMd::StructureFactor::nAtomType_, McMd::StructureFactor::nMode_, McMd::StructureFactor::nSample_, McMd::StructureFactor::nWave_, Util::PointSymmetry::R(), McMd::Analyzer::readInterval(), McMd::Analyzer::readOutputFileName(), McMd::System::simulation(), Util::FSArray< Data, Capacity >::size(), McMd::StructureFactor::structureFactors_, McMd::SystemAnalyzer< System >::system(), UTIL_THROW, McMd::StructureFactor::waveIntVectors_, and McMd::StructureFactor::waveVectors_.
void McMd::StructureFactorGrid::loadParameters (Serializable::IArchive & ar) virtual
Load state from an archive.
Parameters
ar loading (input) archive.
Reimplemented from McMd::StructureFactor.
Definition at line 235 of file mcMd/analyzers/system/StructureFactorGrid.cpp.
References Util::DMatrix< Data >::allocate(), Util::DArray< Data >::allocate(), McMd::StructureFactor::fourierModes_, McMd::Analyzer::loadParameters(), McMd::StructureFactor::modes_, McMd::StructureFactor::nAtomType_, McMd::StructureFactor::nMode_, McMd::StructureFactor::nSample_, McMd::StructureFactor::nWave_, McMd::StructureFactor::structureFactors_, McMd::SystemAnalyzer< System >::system(), UTIL_THROW, McMd::StructureFactor::waveIntVectors_, and McMd::StructureFactor::waveVectors_.
void McMd::StructureFactorGrid::save (Serializable::OArchive & ar) virtual
Save state to archive.
Parameters
ar saving (output) archive.
Reimplemented from McMd::StructureFactor.
Definition at line 286 of file mcMd/analyzers/system/StructureFactorGrid.cpp.
template<class Archive > void McMd::StructureFactorGrid::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters
ar saving or loading archive
version archive version id
Definition at line 157 of file mcMd/analyzers/system/StructureFactorGrid.h.
References McMd::StructureFactor::serialize().
void McMd::StructureFactorGrid::setup () virtual
Set up before a simulation.
Reimplemented from McMd::StructureFactor.
Definition at line 289 of file mcMd/analyzers/system/StructureFactorGrid.cpp.
void McMd::StructureFactorGrid::output () virtual
Output structure factors, averaged over stars.
Reimplemented from McMd::StructureFactor.
Definition at line 338 of file mcMd/analyzers/system/StructureFactorGrid.cpp.
References Util::Dimension, McMd::Analyzer::fileMaster(), McMd::StructureFactor::nMode_, McMd::StructureFactor::nSample_, Util::FileMaster::openOutputFile(), McMd::StructureFactor::outputFile_, McMd::Analyzer::outputFileName(), McMd::StructureFactor::structureFactors_, McMd::StructureFactor::waveIntVectors_, McMd::StructureFactor::waveVectors_, and Util::ParamComposite::writeParam().
void McMd::StructureFactorGrid::sample (long iStep) virtual
Add particles to StructureFactor accumulators.
Parameters
iStep step counter
Reimplemented from McMd::StructureFactor.
Definition at line 292 of file mcMd/analyzers/system/StructureFactorGrid.cpp.
References McMd::System::boundary(), Util::Dimension, McMd::Analyzer::fileMaster(), McMd::StructureFactor::fourierModes_, McMd::StructureFactor::isFirstStep_, McMd::StructureFactor::nMode_, Util::FileMaster::openOutputFile(), McMd::Analyzer::outputFileName(), McMd::StructureFactor::sample(), McMd::SystemAnalyzer< System >::system(), Simp::OrthorhombicBoundary::volume(), McMd::StructureFactor::waveIntVectors_, and McMd::StructureFactor::waveVectors_.
The documentation for this class was generated from the following files:
mcMd/analyzers/system/StructureFactorGrid.h
mcMd/analyzers/system/StructureFactorGrid.cpp