Simpatico: McMd::CfbDoubleRebridgeMove Class Reference
McMd::CfbDoubleRebridgeMove Class Reference
Monte Carlo Moves
Detailed Description
configuration bias trimer double rebridge moves, to reconnect two chains.
Definition at line 28 of file CfbDoubleRebridgeMove.h.
#include <CfbDoubleRebridgeMove.h>
Public Member Functions
CfbDoubleRebridgeMove (McSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read species to which displacement is applied.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual bool move ()
Generate and accept or reject configuration bias move.
Protected Attributes
DArray< Vector > iOldPos_
Array of old positions of temporarily deleted atoms (iMol).
DArray< Vector > jOldPos_
Array of old positions of temporarily deleted atoms (jMol).
int speciesId_
Integer index for molecular species.
int nRegrow_
Number of particles at end to attempt to regrow.
double bridgeLength_
upper bound for trial lenght of a bridge.
Constructor & Destructor Documentation
McMd::CfbDoubleRebridgeMove::CfbDoubleRebridgeMove (McSystem & system)
Constructor.
Definition at line 29 of file CfbDoubleRebridgeMove.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::CfbDoubleRebridgeMove::readParameters (std::istream & in) [virtual]
Read species to which displacement is applied.
Reimplemented from McMd::CfbRebridgeBase.
Definition at line 39 of file CfbDoubleRebridgeMove.cpp.
References Util::DArray< Data >::allocate(), bridgeLength_, iOldPos_, jOldPos_, nRegrow_, McMd::McMove::readProbability(), McMd::CfbRebridgeBase::setup(), McMd::McMove::simulation(), McMd::Simulation::species(), speciesId_, and UTIL_THROW.
void McMd::CfbDoubleRebridgeMove::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from McMd::CfbRebridgeBase.
Definition at line 68 of file CfbDoubleRebridgeMove.cpp.
References Util::DArray< Data >::allocate(), bridgeLength_, iOldPos_, jOldPos_, nRegrow_, McMd::CfbRebridgeBase::setup(), McMd::McMove::simulation(), McMd::Simulation::species(), speciesId_, and UTIL_THROW.
void McMd::CfbDoubleRebridgeMove::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from McMd::CfbRebridgeBase.
Definition at line 95 of file CfbDoubleRebridgeMove.cpp.
References bridgeLength_, nRegrow_, and speciesId_.
bool McMd::CfbDoubleRebridgeMove::move () [virtual]
Generate and accept or reject configuration bias move.
Reimplemented from McMd::McMove.
Definition at line 118 of file CfbDoubleRebridgeMove.cpp.
References McMd::CfbRebridgeBase::addSequence(), McMd::Molecule::atom(), McMd::Molecule::bond(), McMd::CfbRebridgeBase::deleteSequence(), McMd::McMove::incrementNAccept(), McMd::McMove::incrementNAttempt(), iOldPos_, jOldPos_, Util::Random::metropolis(), McMd::System::molecule(), McMd::Molecule::nAtom(), nRegrow_, McMd::McSystem::pairPotential(), McMd::Atom::position(), McMd::McMove::random(), speciesId_, McMd::SystemMove::system(), McMd::Group< NAtom >::typeId(), and McMd::McPairPotential::updateAtomCell().
Member Data Documentation
DArray<Vector> McMd::CfbDoubleRebridgeMove::iOldPos_ [protected]
Array of old positions of temporarily deleted atoms (iMol).
Definition at line 65 of file CfbDoubleRebridgeMove.h.
Referenced by loadParameters(), move(), and readParameters().
DArray<Vector> McMd::CfbDoubleRebridgeMove::jOldPos_ [protected]
Array of old positions of temporarily deleted atoms (jMol).
Definition at line 68 of file CfbDoubleRebridgeMove.h.
Referenced by loadParameters(), move(), and readParameters().
int McMd::CfbDoubleRebridgeMove::speciesId_ [protected]
Integer index for molecular species.
Definition at line 71 of file CfbDoubleRebridgeMove.h.
Referenced by loadParameters(), move(), readParameters(), and save().
int McMd::CfbDoubleRebridgeMove::nRegrow_ [protected]
Number of particles at end to attempt to regrow.
Definition at line 74 of file CfbDoubleRebridgeMove.h.
Referenced by loadParameters(), move(), readParameters(), and save().
double McMd::CfbDoubleRebridgeMove::bridgeLength_ [protected]
upper bound for trial lenght of a bridge.
Definition at line 77 of file CfbDoubleRebridgeMove.h.
Referenced by loadParameters(), readParameters(), and save().
The documentation for this class was generated from the following files:
CfbDoubleRebridgeMove.h
CfbDoubleRebridgeMove.cpp