Simpatico: DdMd::VirialStressTensorAverage Class Reference
DdMd::VirialStressTensorAverage Class Reference
Analyzers
Detailed Description
Periodically write (tensor) StressTensor to file.
See also:
param file format
Definition at line 29 of file VirialStressTensorAverage.h.
#include <VirialStressTensorAverage.h>
Public Member Functions
VirialStressTensorAverage (Simulation &simulation)
Constructor.
virtual ~VirialStressTensorAverage ()
Destructor.
virtual void readParameters (std::istream &in)
Read dumpPrefix and interval.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void clear ()
Clear nSample counter.
virtual void sample (long iStep)
Sample virial stress to accumulators.
virtual void output ()
Dump configuration to file.
Constructor & Destructor Documentation
DdMd::VirialStressTensorAverage::VirialStressTensorAverage (Simulation & simulation)
Constructor.
Parameters:
simulation parent Simulation object.
Definition at line 24 of file VirialStressTensorAverage.cpp.
References Util::ParamComposite::setClassName().
virtual DdMd::VirialStressTensorAverage::~VirialStressTensorAverage () [inline, virtual]
Destructor.
Definition at line 44 of file VirialStressTensorAverage.h.
Member Function Documentation
void DdMd::VirialStressTensorAverage::readParameters (std::istream & in) [virtual]
Read dumpPrefix and interval.
Parameters:
in input parameter file
Reimplemented from Util::ParamComposite.
Definition at line 42 of file VirialStressTensorAverage.cpp.
References DdMd::Simulation::fileMaster(), Util::FileMaster::openOutputFile(), DdMd::Analyzer::outputFileName(), DdMd::Analyzer::readInterval(), DdMd::Analyzer::readOutputFileName(), Util::Average::setNSamplePerBlock(), and DdMd::Analyzer::simulation().
void DdMd::VirialStressTensorAverage::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters:
ar input/loading archive
Reimplemented from DdMd::Analyzer.
Definition at line 68 of file VirialStressTensorAverage.cpp.
References DdMd::Simulation::fileMaster(), DdMd::Analyzer::loadInterval(), DdMd::Analyzer::loadOutputFileName(), Util::Average::loadParameters(), Util::FileMaster::openOutputFile(), DdMd::Analyzer::outputFileName(), and DdMd::Analyzer::simulation().
void DdMd::VirialStressTensorAverage::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters:
ar output/saving archive
Reimplemented from DdMd::Analyzer.
Definition at line 94 of file VirialStressTensorAverage.cpp.
References DdMd::Analyzer::saveInterval(), DdMd::Analyzer::saveOutputFileName(), and DdMd::Analyzer::simulation().
void DdMd::VirialStressTensorAverage::clear () [virtual]
Clear nSample counter.
Reimplemented from DdMd::Analyzer.
Definition at line 117 of file VirialStressTensorAverage.cpp.
References Util::Average::clear(), DdMd::Analyzer::simulation(), and UTIL_THROW.
void DdMd::VirialStressTensorAverage::sample (long iStep) [virtual]
Sample virial stress to accumulators.
Parameters:
iStep MD step index
Implements DdMd::Analyzer.
Definition at line 139 of file VirialStressTensorAverage.cpp.
References Util::Tensor::add(), DdMd::Simulation::computeKineticStress(), DdMd::Simulation::computeVirialStress(), DdMd::Simulation::domain(), DdMd::Analyzer::isAtInterval(), DdMd::Domain::isMaster(), DdMd::Simulation::kineticStress(), Util::Average::sample(), DdMd::Analyzer::simulation(), and DdMd::Simulation::virialStress().
void DdMd::VirialStressTensorAverage::output () [virtual]
Dump configuration to file.
Reimplemented from DdMd::Analyzer.
Definition at line 166 of file VirialStressTensorAverage.cpp.
References Util::AverageStage::average(), Util::AverageStage::error(), and DdMd::Analyzer::simulation().
The documentation for this class was generated from the following files:
VirialStressTensorAverage.h
VirialStressTensorAverage.cpp