Simpatico: McMd::ComMSD Class Reference
McMd::ComMSD Class Reference
Diagnostics
Detailed Description
Molecular center of mass mean squared displacement.
Definition at line 30 of file ComMSD.h.
#include <ComMSD.h>
Public Member Functions
ComMSD (System &system)
Constructor.
virtual void readParameters (std::istream &in)
Read parameters from file.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
virtual void setup ()
Determine number of molecules and allocate memory.
virtual void sample (long iStep)
Evaluate center of mass displacement of all chains and add to ensemble.
virtual void output ()
Output results to file after simulation is completed.
Public Member Functions inherited from McMd::SystemDiagnostic< System >
SystemDiagnostic (System &system)
Constructor.
virtual ~SystemDiagnostic ()
Destructor.
Public Member Functions inherited from McMd::Diagnostic
Diagnostic ()
Default constructor.
virtual ~Diagnostic ()
Destructor.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
std::string className () const
Get class name string.
virtual void readParam (std::istream &in)
Read a parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an archive.
void resetParam ()
Resets ParamComposite to its empty state.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add a new Param < Type > object, and read its value.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add a C array parameter, and read its elements.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and read its elements.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n)
Add and read a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a DMatrix < Type > C two-dimensional matrix parameter.
Begin & readBegin (std::istream &in, const char *label)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a child ParamComposite.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add a new Param < Type > object, and load its value.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add a C array parameter, and load its elements.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add a DArray < Type > parameter, and load its elements.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n)
Add and load a CArray2DParam < Type > C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a DMatrix < Type > C two-dimensional matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
template<typename Type >
ScalarParam< Type > & add (const char *label, Type &value)
Add a new Param < Type > object to the format array.
template<typename Type >
CArrayParam< Type > & addCArray (const char *label, Type *value, int n)
Add a C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (const char *label, DArray< Type > &array, int n)
Add a DArray<Type> parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (const char *label, FArray< Type, N > &array)
Add a FArray<Type> parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (const char *label, Type *value, int m, int n)
Add a C two-dimensional array parameter.
template<typename Type >
DMatrixParam< Type > & addDMatrix (const char *label, DMatrix< Type > &matrix, int m, int n)
Add a C two-dimensional array parameter.
Begin & addBegin (const char *label)
Add a class label and opening bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Add a new Blank object, representing a blank line.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have a communicator?
MPI::Intracomm & ioCommunicator () const
Get the communicator.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from McMd::Diagnostic
static void initStatic ()
Define and initialize baseInterval.
Static Public Attributes inherited from McMd::Diagnostic
static long baseInterval = 1
The interval for a Diagnostic must be a multiple of baseInterval.
Protected Member Functions inherited from McMd::SystemDiagnostic< System >
System & system ()
Return reference to parent system.
Protected Attributes inherited from McMd::Diagnostic
std::string outputFileName_
Base name of output file(s).
long interval_
Number of simulation steps between subsequent actions.
Constructor & Destructor Documentation
McMd::ComMSD::ComMSD (System & system)
Constructor.
Parameters
system reference to parent System
Definition at line 30 of file ComMSD.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::ComMSD::readParameters (std::istream & in) virtual
Read parameters from file.
Parameters
in input parameter stream
Reimplemented from McMd::Diagnostic.
Definition at line 47 of file ComMSD.cpp.
References McMd::Species::capacity(), McMd::Species::nAtom(), McMd::Diagnostic::readInterval(), McMd::Diagnostic::readOutputFileName(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::ComMSD::loadParameters (Serializable::IArchive & ar) virtual
Load state from an archive.
Parameters
ar loading (input) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 82 of file ComMSD.cpp.
References McMd::Species::capacity(), McMd::Diagnostic::loadParameters(), McMd::System::simulation(), McMd::Simulation::species(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::ComMSD::save (Serializable::OArchive & ar) virtual
Save state to archive.
Parameters
ar saving (output) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 124 of file ComMSD.cpp.
template<class Archive > void McMd::ComMSD::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters
ar saving or loading archive
version archive version id
Definition at line 134 of file ComMSD.h.
References McMd::Diagnostic::serialize().
void McMd::ComMSD::setup () virtual
Determine number of molecules and allocate memory.
Reimplemented from McMd::Diagnostic.
Definition at line 130 of file ComMSD.cpp.
References McMd::Molecule::atom(), McMd::System::boundary(), McMd::System::molecule(), McMd::System::nMolecule(), McMd::Atom::position(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::ComMSD::sample (long iStep) virtual
Evaluate center of mass displacement of all chains and add to ensemble.
Parameters
iStep counter for number of steps
Implements McMd::Diagnostic.
Definition at line 158 of file ComMSD.cpp.
References McMd::Molecule::atom(), McMd::System::boundary(), Util::Dimension, McMd::Diagnostic::isAtInterval(), McMd::System::molecule(), McMd::Atom::position(), McMd::SystemDiagnostic< System >::system(), and UTIL_THROW.
void McMd::ComMSD::output () virtual
Output results to file after simulation is completed.
Reimplemented from McMd::Diagnostic.
Definition at line 204 of file ComMSD.cpp.
References McMd::Diagnostic::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
ComMSD.h
ComMSD.cpp