Simpatico: DdMd::Mask Class Reference
DdMd::Mask Class Reference
Chemical Structure
Detailed Description
Set of Atoms for which pair interactions with a target Atom are "masked".
A Mask stores int identifiers for a set of Atoms for which the non-bonded pair interactions with a single target atom are suppressed, or "masked". Each Mask object is associated with one target Atom.
A Mask could, for example, contain all atoms that are directly connected to the target atom by 2-body covalent bonds.
Definition at line 30 of file ddMd/chemistry/Mask.h.
#include <Mask.h>
Public Member Functions
Mask ()
Constructor.
void clear ()
Clear the masked set (remove all atoms).
void append (int id)
Add an Atom to the masked set.
bool isMasked (int id) const
True if the atom is in the masked set for the target Atom.
int operator[] (int i) const
Return value of atom index number i.
int size () const
Return the number of masked atoms.
Static Public Attributes
static const int Capacity = 4
Maximum number of masked atoms per target atom.
Constructor & Destructor Documentation
DdMd::Mask::Mask ()
Constructor.
Definition at line 23 of file ddMd/chemistry/Mask.cpp.
References Capacity.
Member Function Documentation
void DdMd::Mask::clear ()
Clear the masked set (remove all atoms).
Definition at line 34 of file ddMd/chemistry/Mask.cpp.
References Capacity.
Referenced by DdMd::Atom::clear(), and DdMd::Buffer::unpackAtom().
void DdMd::Mask::append (int id)
Add an Atom to the masked set.
Parameters:
id global index (tag) of atom to be added
Definition at line 45 of file ddMd/chemistry/Mask.cpp.
References Capacity, isMasked(), and UTIL_THROW.
Referenced by DdMd::ConfigIo::setAtomMasks(), and DdMd::Buffer::unpackAtom().
bool DdMd::Mask::isMasked (int id) const [inline]
True if the atom is in the masked set for the target Atom.
Parameters:
id integer id of atom to be tested
Returns:
true if atom is masked, false otherwise
Definition at line 88 of file ddMd/chemistry/Mask.h.
Referenced by append(), and DdMd::PairList::build().
int DdMd::Mask::operator[] (int i) const [inline]
Return value of atom index number i.
Parameters:
i array index for desired atom index
Definition at line 105 of file ddMd/chemistry/Mask.h.
int DdMd::Mask::size () const [inline]
Return the number of masked atoms.
Definition at line 99 of file ddMd/chemistry/Mask.h.
Referenced by DdMd::Buffer::packAtom(), DdMd::Buffer::unpackAtom(), and DdMd::DdMdConfigIo::writeConfig().
Member Data Documentation
const int DdMd::Mask::Capacity = 4 [static]
Maximum number of masked atoms per target atom.
Definition at line 36 of file ddMd/chemistry/Mask.h.
Referenced by append(), clear(), and Mask().
The documentation for this class was generated from the following files:
ddMd/chemistry/Mask.h
ddMd/chemistry/Mask.cpp