Simpatico: McMd::McEnergyOutput Class Reference
McMd::McEnergyOutput Class Reference
Diagnostics
Detailed Description
Diagnostic to output total potential energy.
Definition at line 24 of file McEnergyOutput.h.
#include <McEnergyOutput.h>
Public Member Functions
McEnergyOutput (McSystem &system)
Constructor.
virtual void readParameters (std::istream &in)
Read output file and nStepPerSample.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
void sample (long iStep)
Evaluate energy and print.
virtual void output ()
Output final summary and file format.
Constructor & Destructor Documentation
McMd::McEnergyOutput::McEnergyOutput (McSystem & system)
Constructor.
Parameters:
system parent McSystem.
Definition at line 24 of file McEnergyOutput.cpp.
References Util::ParamComposite::setClassName().
Member Function Documentation
void McMd::McEnergyOutput::readParameters (std::istream & in) [virtual]
Read output file and nStepPerSample.
Parameters:
in input parameter stream
Reimplemented from McMd::Diagnostic.
Definition at line 31 of file McEnergyOutput.cpp.
References McMd::Diagnostic::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), McMd::Diagnostic::readInterval(), and McMd::Diagnostic::readOutputFileName().
void McMd::McEnergyOutput::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters:
ar loading (input) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 41 of file McEnergyOutput.cpp.
References McMd::Diagnostic::fileMaster(), Util::FileMaster::openOutputFile(), and McMd::Diagnostic::outputFileName().
void McMd::McEnergyOutput::save (Serializable::OArchive & ar) [virtual]
Save state to an archive.
Parameters:
ar saving (output) archive.
Reimplemented from McMd::Diagnostic.
Definition at line 50 of file McEnergyOutput.cpp.
template<class Archive > void McMd::McEnergyOutput::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters:
ar archive
version archive version id
Reimplemented from McMd::Diagnostic.
Definition at line 87 of file McEnergyOutput.h.
References McMd::serialize().
void McMd::McEnergyOutput::sample (long iStep) [virtual]
Evaluate energy and print.
Implements McMd::Diagnostic.
Definition at line 56 of file McEnergyOutput.cpp.
References McMd::McSystem::anglePotential(), McMd::McSystem::bondPotential(), McMd::McSystem::dihedralPotential(), McMd::PairPotential::energy(), McMd::AnglePotential::energy(), McMd::BondPotential::energy(), McMd::ExternalPotential::energy(), McMd::DihedralPotential::energy(), McMd::McSystem::externalPotential(), McMd::Diagnostic::isAtInterval(), McMd::McSystem::linkPotential(), McMd::McSystem::pairPotential(), and McMd::SystemDiagnostic< McSystem >::system().
void McMd::McEnergyOutput::output () [virtual]
Output final summary and file format.
Reimplemented from McMd::Diagnostic.
Definition at line 108 of file McEnergyOutput.cpp.
References McMd::Diagnostic::fileMaster(), Util::FileMaster::openOutputFile(), McMd::Diagnostic::outputFileName(), McMd::SystemDiagnostic< McSystem >::system(), and Util::ParamComposite::writeParam().
The documentation for this class was generated from the following files:
McEnergyOutput.h
McEnergyOutput.cpp