Simpatico: Generators
Generators
McMd namespace
Detailed Description
Classes that generate random initial configurations.
Classes
class McMd::Generator
Generates initial configurations for molecules of one species.
class McMd::LinearGenerator
Generates random configurations for linear molecules.
class McMd::PointGenerator
Generator for monoatomic molecules (atoms).
Functions
Generator * McMd::generatorFactory (Species &species, McSystem &system)
Instantiates generator for on species in an McSystem.
Generator * McMd::generatorFactory (Species &species, MdSystem &system)
Instantiates generator for on species in an MdSystem.
Function Documentation
Generator * McMd::generatorFactory (Species & species, McSystem & system)
Instantiates generator for on species in an McSystem.
Returns a pointer to the new generator, or null if no appropriate generator is found.
Parameters
species Species object
system parent McSystem
Definition at line 25 of file generatorFactory.cpp.
References McMd::McSystem::bondPotential(), and McMd::Generator::setBondPotential().
Referenced by McMd::MdSimulation::readCommands(), and McMd::McSimulation::readCommands().
Generator * McMd::generatorFactory (Species & species, MdSystem & system)
Instantiates generator for on species in an MdSystem.
Returns a pointer to the new generator, or null if no appropriate generator is found.
Parameters
species Species object
system parent McSystem
Definition at line 41 of file generatorFactory.cpp.
References McMd::MdSystem::bondPotential(), and McMd::Generator::setBondPotential().