Simpatico: Mathematics
Mathematics
Util namespace
Detailed Description
Mathematical constants and utilities.
Classes
class Util::Binomial
Class for binomial coefficients (all static members)
class Util::CardinalBSpline
A cardinal B-spline basis function.
class Util::Constants
Mathematical constants.
class Util::Polynomial< T >
A Polynomial (i.e,.
class Util::Rational
A Rational number (a ratio of integers).
Functions
bool Util::feq (double x, double y, double eps=1.0E-10)
Are two floating point numbers equal to within round-off error?
int Util::gcd (int a, int b)
Compute greatest common divisor (gcd) of two integers.
Function Documentation
bool Util::feq (double x, double y, double eps = 1.0E-10) inline
Are two floating point numbers equal to within round-off error?
Returns true if eps > fabs(x-y)*c/(fabs(x)+fabs(y)+c), c=1.05E-5.
Parameters
x first real argument
y second real argument
eps maximum tolerance for nominally "equal" values
Returns
true if equal to within tolerance, false otherwise
Definition at line 27 of file feq.h.
Referenced by Simp::OrthoRegion::isValid(), Simp::MonoclinicBoundary::isValid(), Simp::OrthorhombicBoundary::isValid(), McMd::BondLengthDist::loadParameters(), McMd::RDF::loadParameters(), Util::RadialDistribution::loadParameters(), Util::Distribution::loadParameters(), and Util::Distribution::serialize().
int Util::gcd (int a, int b) inline
Compute greatest common divisor (gcd) of two integers.
Uses Euclidean algorithm to compute gcd. Always returns a non-negative integer. If one argument is zero, the absolute value of the other is returned. Returns zero if and only if both integers are zero.
Parameters
a 1st integer
b 2nd integer
Returns
greatest common divisor of a and b
Definition at line 30 of file gcd.h.
Referenced by Util::Rational::serialize().