Simpatico: Miscellaneous Utilities
Miscellaneous Utilities
Util namespace
Detailed Description
Miscellaneous utility classes and functions.
Classes
class Util::Bit
Represents a specific bit location within an unsigned int.
class Util::Exception
A user-defined exception.
class Util::FileMaster
A FileMaster manages input and output files for a simulation.
class Util::FlagSet
A set of boolean variables represented by characters.
class Util::Log
A static class that holds a log output stream.
class Util::Memory
Provides method to allocate array.
class Util::Notifier< Event >
Abstract template for a notifier (or subject) in the Observer design pattern.
class Util::Observer< Event >
Abstract class template for observer in the observer design pattern.
class Util::Setable< T >
Template for a value that can be set or declared null (i.e., unknown).
class Util::Timer
Wall clock timer.
Functions
std::string Util::toString (int n)
Return string representation of an integer.
int Util::rStrip (std::string &string)
Strip trailing whitespace from a string.
void Util::checkString (std::istream &in, const std::string &expected)
Extract string from stream, and compare to expected value.
bool Util::getLine (std::istream &in, std::stringstream &line)
Read the next line into a stringstream.
bool Util::getNextLine (std::istream &in, std::string &line)
Read the next non-empty line into a string, strip trailing whitespace.
bool Util::getNextLine (std::istream &in, std::stringstream &line)
Read the next non-empty line into a stringstream, strip trailing whitespace.
template<typename D , typename B , typename M >
ptrdiff_t Util::memberOffset (D &object, M B::*memPtr)
Template for calculating offsets of data members.
Function Documentation
std::string Util::toString (int n)
Return string representation of an integer.
Parameters
n integer to be converted.
Definition at line 52 of file ioUtil.cpp.
Referenced by McMd::StructureFactor::output(), McMd::StructureFactorPGrid::output(), McMd::VanHove::output(), McMd::StructureFactorP::output(), McMd::ClusterHistogram::sample(), DdMd::ConfigWriter::sample(), and McMd::ConfigWriter::sample().
int Util::rStrip (std::string & string)
Strip trailing whitespace from a string.
Parameters
string string (stripped upon return).
Returns
length of stripped string.
Definition at line 18 of file ioUtil.cpp.
Referenced by Util::getNextLine(), and Util::XmlAttribute::match().
void Util::checkString (std::istream & in, const std::string & expected)
Extract string from stream, and compare to expected value.
Exceptions
Exception if input value differs from expected value.
Parameters
in input stream
expected expected value of string read from stream
Definition at line 37 of file ioUtil.cpp.
References Util::Log::file(), and UTIL_THROW.
Referenced by Tools::HoomdConfigWriter::readAuxiliaryFile(), Tools::HoomdConfigReader::readAuxiliaryFile(), Tools::LammpsDumpReader::readFrame(), and McMd::LammpsDumpReader::readFrame().
bool Util::getLine (std::istream & in, std::stringstream & line)
Read the next line into a stringstream.
Variant of std::getline(). Does not strip trailing whitespace.
Parameters
in input stream from which to read.
line stringstream containing line, on output.
Definition at line 62 of file ioUtil.cpp.
bool Util::getNextLine (std::istream & in, std::string & line)
Read the next non-empty line into a string, strip trailing whitespace.
Variant of std::getline() that skips empty lines.
Parameters
in input stream from which to read.
line string with next non-empty line, on output.
Returns
true if not end-of-file, false if end-of-file.
Definition at line 79 of file ioUtil.cpp.
References Util::rStrip().
Referenced by Tools::HoomdConfigWriter::readAuxiliaryFile(), Tools::HoomdConfigReader::readAuxiliaryFile(), McMd::MdSimulation::readCommands(), McMd::McSimulation::readCommands(), DdMd::Simulation::readCommands(), Tools::HoomdConfigReader::readConfig(), Tools::LammpsDumpReader::readFrame(), and McMd::LammpsDumpReader::readFrame().
bool Util::getNextLine (std::istream & in, std::stringstream & line)
Read the next non-empty line into a stringstream, strip trailing whitespace.
Variant of std::getline() that skips empty lines and uses stringstream.
Parameters
in input stream from which to read.
line stringstream containing next non-empty line, on output.
Returns
true if not end-of-file, false if end-of-file.
Definition at line 100 of file ioUtil.cpp.
References Util::rStrip().
template<typename D , typename B , typename M > ptrdiff_t Util::memberOffset (D & object, M B::* memPtr)
Template for calculating offsets of data members.
Types: D - derived class B - base class M - member type
Definition at line 27 of file Offset.h.