Simpatico: McMd Namespace Reference
McMd Namespace Reference
Classes for Monte Carlo (MC) and molecular dynamics (MC) simulation.
Classes
class Analyzer
Abstract base for periodic output and/or analysis actions.
class AnalyzerManager
Manager for a list of Analyzer objects.
class McAnalyzerFactory
AnalyzerFactory for an McSimulation.
class McBondEnergyAverage
McBondEnergyAverage averages of bond potential energy.
class McEnergyAverage
McEnergyAverage averages of total potential energy.
class McEnergyOutput
Analyzer to output total potential energy.
class McExternalEnergyAverage
McExternalEnergyAverage averages of total external energy.
class McIntraBondStressAutoCorr
Autocorrelation for bond stress of a molecule.
class McIntraBondTensorAutoCorr
Autocorrelation for bond stress of a molecule.
class McNVTChemicalPotential
McEnergyAverage averages of total potential energy.
class McPairEnergyAverage
McPairEnergyAverage averages of total potential energy.
class McPressureAverage
Analyzer to calculate average isotropic pressure.
class McStressAutoCorr
Shear stress autocorrelation function.
class McVirialStressTensorAverage
Periodically write (tensor) StressTensor to file.
class MdAnalyzerFactory
AnalyzerFactory for an MdSimulation.
class MdEnergyOutput
Analyzer to output total potential and kinetic energies.
class MdIntraBondStressAutoCorr
Autocorrelation for bond stress of a molecule.
class MdIntraBondTensorAutoCorr
Autocorrelation for bond stress of a molecule.
class MdKineticEnergyAverage
MdKineticEnergyAverage averages of total kinetic energy.
class MdPairEnergyCoefficients
Analyzer to output the total pair energy and the sum of squares of the monomeric and molecular pair energy.
class MdPotentialEnergyAverage
MdPotentialEnergyAverage averages of total potential energy.
class MdPressureAverage
Calculate average scalar pressure for an MdSystem.
class MdVirialStressTensorAverage
Periodically write (tensor) StressTensor to file.
class SemiGrandDistribution
Calculate distribution of type indices for mutable species.
class TypeDistribution
Calculate distribution of type indices for mutable species.
class BennettsMethod
Bennett's method estimates free energy difference between two states.
class PerturbDerivative
PerturbDerivative returns average value of Perturbation::derivative().
class LogProgress
Periodically write step number to a Log file.
class AtomMSD
Autocorrelation for vector separation of two atoms on a molecule.
class BlockRadiusGyration
Radius of gyration of different blocks in a molecule.
class BondLengthDist
BondLengthDist evaluates the distribution function of the lengths of the bonds.
class BoundaryAverage
Average of boundary lengths and volume of simulation cell.
class ComMSD
Molecular center of mass mean squared displacement.
class CompositionProfile
CompositionProfile evaluates the distribution of monomer positions along several user-specified directions.
class DumpConfig
Periodically dump system configuration to a new file.
class IntraBondStressAutoCorr
Autocorrelation for bond stress of a molecule.
class IntraBondTensorAutoCorr
Autocorrelation for bond stress of a molecule.
class IntraPairAutoCorr
Autocorrelation for vector separation of any two monomers on a molecule.
class IntraStructureFactor
Intramolecular contribution to the structure factor S(k)
class IntraStructureFactorGrid
IntraStructureFactorGrid evaluates structure factors in Fourier space.
class LinearRouseAutoCorr
Autocorrelation for Rouse mode coefficients of a linear molecule.
class MigratingVanHove
MigratingVanHove class evaluates VanHove function of a configuration by monitoring its trajectory through different states in space.
class PressureAverage
PressureAverage evaluates average pressure.
class RadiusGyration
Radius of gyration of a molecule.
class RDF
RDF evaluates the atomic radial distribution function.
class RingRouseAutoCorr
Autocorrelation for Rouse mode coefficients of a ring molecule.
class StructureFactor
StructureFactor evaluates structure factors in Fourier space.
class StructureFactorGrid
StructureFactorGrid evaluates structure factors in Fourier space.
class StructureFactorP
StructureFactorP evaluates partial structure factors in Fourier space.
class StructureFactorPGrid
StructureFactorPGrid evaluates structure factors in Fourier space.
class SystemAnalyzerFactory
AnalyzerFactory for any System (for mc or md).
class VanHove
Evaluates the van Hove function S(k,t) for one or more wavevector k.
class SystemAnalyzer
Template for Analyzer associated with one System.
class AverageAnalyzer
AverageAnalyzer averages of total potential energy.
class PairSelector
Selection rule for pairs of Atoms.
class Atom
A point particle within a Molecule.
class AtomType
Descriptor for a type of Atom.
class Group
A group of covalently interacting atoms.
class Mask
Set of Atoms for which pair interactions with a target Atom are "masked".
class Molecule
A physical molecule (a set of covalently bonded Atoms).
class SpeciesGroup
A Group of covalently interacting atoms within any molecule of one Species.
class ConfigIo
System configuration file reader and writer.
class ConfigIoFactory
Default Factory for subclasses of ConfigIo.
class DdMdConfigIo
ConfigIo for DdMd data files.
class LammpsConfigIo
ConfigIo for Lammps data files.
class McConfigIo
ConfigIo for MC simulations (no atom velocities).
class McMdConfigIo
Base class for default Mc and Md configIos.
class MdConfigIo
ConfigIo for MD simulations (includes velocities).
class PmcConfigIo
ConfigIo for PMC configuration files.
class Link
A Link represents a crosslink between two Atoms.
class LinkAddEvent
Event signalling addition of Link to the LinkMaster.
class LinkResetEvent
Event signalling reset of Link to the LinkMaster.
struct LinkRemoveEvent
Event signalling removal of a Link from the LinkMaster.
struct ReSetAtomEvent
Event signalling the reset of an atom from the LinkMaster.
class LinkMaster
Manages all Link objects in a System.
class CfbEndBase
Base class for configuration bias (CFB) end regrowth moves.
class CfbRebridgeBase
Base class configuration bias moves internal segment regrowth moves.
class GroupRebridgeBase
Base class for rebridging a group of atoms forming a tetrahedron.
class AtomDisplaceMove
Random displacement of one atom.
class DpdMove
DpdMove is a short dissipative particle dynamics (DPD) simulation.
class HybridMdMove
HybridMdMove is a hybrid Molecular Dynamics MC move.
class HybridNphMdMove
HybridMdMove is a hybrid Molecular Dynamics MC move.
class MdMove
MdMove is a simple NVE molecular Dynamics MC move.
class RigidDisplaceMove
Random rigid displacement of a molecule.
class CfbDoubleRebridgeMove
configuration bias trimer double rebridge moves, to reconnect two chains.
class CfbEndMove
Configuration bias end regrowth move for flexible linear chains.
class CfbRebridgeMove
Config-bias move for internal segment of a flexible linear polymer.
class CfbReptationMove
Configuration bias reptation move for a Linear species.
class EndSwapMove
A move that swaps the ends of a linear hetero-polymer.
class McMove
McMove is an abstract base class for Monte Carlo moves.
class McMoveFactory
McMoveFactory for an McSimulation.
class McMoveManager
Manager for a set of McMove objects.
class CfbRingRebridgeMove
Configuration bias rebridge moves for ring molecules.
class RingOctaRebridgeMove
Molecule rebridging move for a Ring species.
class RingTetraRebridgeMove
Molecule move that attempt the exchange of interior pieces of one close rings.
class HomopolymerSemiGrandMove
A move that changes the type of a HomopolymerSG molecule.
class SystemMove
An McMove that acts on one McSystem.
class McAnalyzerManager
Manager for Analyzer objects in an McSimulation.
class McModule
Abstract Module for an McSimulation.
class McSimulation
A Monte-Carlo simulation of one McSystem.
class McSystem
A System for use in a Markov chain Monte Carlo simulation.
class MdIntegrator
Abstract base for molecular dynamics integrators.
class MdIntegratorFactory
Default Factory for subclasses of MdIntegrator.
class NphIntegrator
An explictly reversible/measure-preserving Parrinello-Rahman type NPH integrator.
class NveVvIntegrator
An NVE Verlet molecular dynamics integrator.
class NvtDpdVvIntegrator
A velocity-Verlet DPD integerator.
class NvtNhIntegrator
A Nose-Hoover NVT molecular dynamics integrator.
class MdAnalyzerManager
Manager for Analyzer objects in an MdSimulation.
class MdModule
A Module for an MdSimulation.
class MdSimulation
A molecular dynamics simulation of a single MdSystem.
class MdSystem
A System for Molecular Dynamics simulation.
class Cell
A set of Atoms in a small region.
class CellList
A cell list for Atom objects in a periodic system boundary.
class CellTag
Location of the pointer to a particular Atom in a CellList.
class PairIterator
Iterator for pairs in a PairList.
class PairList
A Verlet neighbor list.
class LinearPerturbation
A Perturbation that is a linear function of a parameter.
class McEnergyPerturbation
A Perturbation with a variable inverse temperature.
class McExternalPerturbation
A Perturbation in the external potential external parameter.
class McPairExternalPerturbation
A Perturbation in the pair interaction epsilon(0,1) for any pair potential supporting setEpsilon() and in the external parameter for any external potential supporting setExternalParameter().
class McPairPerturbation
A Perturbation in the pair interaction epsilon(0,1) for any pair potential supporting setEpsilon().
class McPerturbationFactory
Default Factory for subclasses of Perturbation.
class Perturbation
Model of parameter dependence in a free energy perturbation theory.
class ReplicaMove
Replica exchange Monte Carlo move using Gibbs sampling.
class AngleFactory
Factory for subclasses of AnglePotential.
class AnglePotential
Interface for a Angle Interaction.
class AnglePotentialImpl
Implementation template for an AnglePotential.
class BondFactory
Factory for BondPotential objects.
class BondPotential
Abstract Bond Potential class.
class BondPotentialImpl
Implementation template for a BondPotential.
class DihedralFactory
Factory for subclasses of DihedralPotential.
class DihedralPotential
Interface for a Dihedral Potential.
class DihedralPotentialImpl
Implementation template for an DihedralPotential.
class ExternalFactory
Factory for subclasses MdExternalPotential or McExternalPotential.
class ExternalPotential
Abstract External Potential class.
class ExternalPotentialImpl
Template implementation of ExternalPotential.
class LinkFactory
Factory for subclasses of MdBondPotential or McBondPotential.
class LinkPotentialImpl
Template implementation of an BondPotential for links.
class McPairPotential
A PairPotential for MC simulations (abstract).
class McPairPotentialImpl
Implementation template for an McPairPotential.
class MdPairPotential
An PairPotential for MD simulation.
class MdPairPotentialImpl
Implementation template for an MdPairPotential.
class PairFactory
Factory for subclasses MdPairPotential or McPairPotential.
class PairPotential
Interface for a Pair Potential.
class Simulation
The main object in a simulation, which coordinates others.
class SubSystem
A SubSystem is a partial copy of a System that has:
class MoleculeSetObserver
Observer interface.
class System
A set of interacting Molecules enclosed by a Boundary.
class Diblock
A linear diblock copolymer chain.
class Homopolymer
A Homopolymer species of chain molecules.
class HomopolymerSG
A Homopolymer with a mutable type, for semigrand ensemble.
class HomoRing
A HomoRing species of loop molecules.
class Linear
A Species of linear polymers (abstract).
class Point
A Species in which each Molecule contains only one Atom.
class Ring
A Species of ring polymers (abstract).
class Species
A Species represents a set of chemically similar molecules.
class SpeciesFactory
Default Factory for subclasses of Species.
class SpeciesManager
A Manager for a set of Species objects.
class SpeciesMutator
Mix-in class for mutable subclasses of Species.
class DCDTrajectoryIo
TrajectoryIo for CHARMM ".dcd" data files.
class TrajectoryIo
Trajectory file reader and writer.
class TrajectoryIoFactory
Default Factory for subclasses of TrajectoryIo.
Typedefs
typedef Group< 3 > Angle
Group of 3 Atoms involved in an angle potential.
typedef Group< 2 > Bond
A Group of 2 covalently bonded Atoms.
typedef Group< 4 > Dihedral
Group of the 4 Atoms in a dihedral interaction.
typedef Pair< int > sendRecvPair
A pair of receiving and sending partner ranks.
Enumerations
enum MaskPolicy
Enumeration of policies for suppressing ("masking") some pair interactions.
Functions
std::istream & operator>> (std::istream &in, PairSelector &selector)
istream extractor (>>) for a PairSelector object.
std::ostream & operator<< (std::ostream &out, const PairSelector &selector)
ostream inserter (<<) for a PairSelector object.
std::istream & operator>> (std::istream &in, PairSelector::PairType &type)
istream extractor (>>) for a PairSelector::PairType enum.
std::ostream & operator<< (std::ostream &out, const PairSelector::PairType &type)
ostream inserter (<<) for a PairSelector::PairType enum.
template<class Archive >
void serialize (Archive &ar, PairSelector &selector, const unsigned int version)
Serialize a PairSelector.
template<class Archive >
void serialize (Archive &ar, PairSelector::PairType &type, const unsigned int version)
Serialize a PairSelector.
std::istream & operator>> (std::istream &in, AtomType &atomType)
istream extractor (>>) for an AtomType.
std::ostream & operator<< (std::ostream &out, const AtomType &atomType)
ostream inserter (<<) for an AtomType.
template<class Archive >
void serialize (Archive &ar, AtomType &atomType, const unsigned int version)
Serialize an AtomType.
std::istream & operator>> (std::istream &in, MaskPolicy &policy)
istream extractor for a MaskPolicy.
std::ostream & operator<< (std::ostream &out, MaskPolicy policy)
ostream inserter for an MaskPolicy.
template<class Archive >
void serialize (Archive &ar, MaskPolicy &policy, const unsigned int version)
Serialize a MaskPolicy.
template<int NAtom>
std::istream & operator>> (std::istream &in, SpeciesGroup< NAtom > &speciesGroup)
istream extractor for a SpeciesGroup.
template<int NAtom>
std::ostream & operator<< (std::ostream &out, const SpeciesGroup< NAtom > &speciesGroup)
ostream inserter for a SpeciesGroup.
template<class Archive , int NAtom>
void serialize (Archive &ar, SpeciesGroup< NAtom > &speciesGroup, const unsigned int version)
Serialize one SpeciesGroup<NAtom>.
void commitMpiTypes ()
Commit all MPI data types needed for Mc and Md simulations.
Detailed Description
Classes for Monte Carlo (MC) and molecular dynamics (MC) simulation.
Typedef Documentation
typedef Pair<int> McMd::sendRecvPair
A pair of receiving and sending partner ranks.
Definition at line 30 of file ReplicaMove.h.
Function Documentation
std::istream & McMd::operator>> (std::istream & in, PairSelector & selector)
istream extractor (>>) for a PairSelector object.
Format: pairType atom1TypeId atom2TypeId
Parameters
in input stream
selector PairSelector to be read from stream
Returns
modified input stream
Definition at line 78 of file PairSelector.cpp.
std::ostream & McMd::operator<< (std::ostream & out, const PairSelector & selector)
ostream inserter (<<) for a PairSelector object.
Format: pairType atom1TypeId atom2TypeId
Parameters
out output stream
selector PairSelector to be written to stream
Returns
modified output stream
Definition at line 89 of file PairSelector.cpp.
References Util::Parameter::Width.
std::istream & McMd::operator>> (std::istream & in, PairSelector::PairType & type)
istream extractor (>>) for a PairSelector::PairType enum.
Parameters
in input stream
type PairType to be read from stream
Returns
modified input stream
Definition at line 103 of file PairSelector.cpp.
References UTIL_THROW.
std::ostream & McMd::operator<< (std::ostream & out, const PairSelector::PairType & type)
ostream inserter (<<) for a PairSelector::PairType enum.
Parameters
out output stream
type PairSelector::PairType to be written to stream
Returns
modified output stream
Definition at line 124 of file PairSelector.cpp.
References UTIL_THROW.
template<class Archive > void McMd::serialize (Archive & ar, PairSelector & selector, const unsigned int version)
Serialize a PairSelector.
Default implementation calls serialize method of data object. Can be overridden by any explicit specialization.
Parameters
ar archive object
selector object to be serialized
version archive version id
Definition at line 167 of file PairSelector.h.
template<class Archive > void McMd::serialize (Archive & ar, PairSelector::PairType & type, const unsigned int version)
Serialize a PairSelector.
Default implementation calls serialize method of data object. Can be overridden by any explicit specialization.
Parameters
ar archive object
type object to be serialized
version archive version id
Definition at line 203 of file PairSelector.h.
References Util::serializeEnum().
std::istream & McMd::operator>> (std::istream & in, AtomType & atomType)
istream extractor (>>) for an AtomType.
Format:
name mass
Parameters
in input stream
atomType AtomType to be read from stream
Returns
modified input stream
Definition at line 37 of file mcMd/chemistry/AtomType.cpp.
std::ostream & McMd::operator<< (std::ostream & out, const AtomType & atomType)
ostream inserter (<<) for an AtomType.
Format, one one line with no line break:
name mass
Parameters
out output stream
atomType AtomType to be written to stream
Returns
modified output stream
Definition at line 47 of file mcMd/chemistry/AtomType.cpp.
References Util::Parameter::Precision, and Util::Parameter::Width.
template<class Archive > void McMd::serialize (Archive & ar, AtomType & atomType, const unsigned int version)
Serialize an AtomType.
Parameters
ar archive object
atomType object to be serialized
version archive version id
Definition at line 160 of file mcMd/chemistry/AtomType.h.
std::istream & McMd::operator>> (std::istream & in, MaskPolicy & policy)
istream extractor for a MaskPolicy.
Parameters
in input stream
policy MaskPolicy to be read
Returns
modified input stream
Definition at line 34 of file mcMd/chemistry/MaskPolicy.cpp.
References UTIL_THROW.
std::ostream & McMd::operator<< (std::ostream & out, MaskPolicy policy)
ostream inserter for an MaskPolicy.
Parameters
out output stream
policy MaskPolicy to be written
Returns
modified output stream
Definition at line 52 of file mcMd/chemistry/MaskPolicy.cpp.
template<class Archive > void McMd::serialize (Archive & ar, MaskPolicy & policy, const unsigned int version)
Serialize a MaskPolicy.
Parameters
ar archive object
policy object to be serialized
version archive version id
Definition at line 57 of file mcMd/chemistry/MaskPolicy.h.
References Util::serializeEnum().
template<int NAtom> std::istream & McMd::operator>> (std::istream & in, SpeciesGroup< NAtom > & speciesGroup)
istream extractor for a SpeciesGroup.
The format is as follows:
 atomIds[0] atomIds[1] ...  atomId[NAtom-1]  typeId
Parameters
in input stream
speciesGroup SpeciesGroup to be read from stream
Returns
modified input stream
Definition at line 27 of file SpeciesGroup.tpp.
template<int NAtom> std::ostream & McMd::operator<< (std::ostream & out, const SpeciesGroup< NAtom > & speciesGroup)
ostream inserter for a SpeciesGroup.
The format is as follows, output one one line with no line break:
 atomIds[0] atomIds[1] ...  atomId[NAtom-1] typeId
Parameters
out output stream
speciesGroup SpeciesGroup to be written to stream
Returns
modified output stream
Definition at line 41 of file SpeciesGroup.tpp.
References Util::Parameter::Width.
template<class Archive , int NAtom> void McMd::serialize (Archive & ar, SpeciesGroup< NAtom > & speciesGroup, const unsigned int version)
Serialize one SpeciesGroup<NAtom>.
Default implementation calls serialize method of data object. Can be overridden by any explicit specialization.
Parameters
ar archive object
speciesGroup object to be serialized
version archive version id
void McMd::commitMpiTypes ()
Commit all MPI data types needed for Mc and Md simulations.
Definition at line 50 of file McMd_mpi.cpp.
References Util::Pair< Data >::commitMpiType(), McMd::PairSelector::commitMpiType(), McMd::SpeciesGroup< NAtom >::commitMpiType(), Util::IntVector::commitMpiType(), and Util::Vector::commitMpiType().
Referenced by McMd::Simulation::Simulation().