Simpatico: DdMd Namespace Reference
DdMd Namespace Reference
Parallel domain decomposition (DD) MD simulation.
Classes
class Analyzer
Abstract base for periodic output and/or analysis actions.
class AnalyzerFactory
Factory for DdMd::Analyzer objects.
class AnalyzerManager
Manager for a list of Analyzer objects.
class AngleFactory
Factory for AnglePotential objects.
class AnglePotential
Abstract base class for computation of angle force and energies.
class AnglePotentialImpl
Implementation template for a AnglePotential.
class AngleStorage
Container for Group<3> (angle) objects.
class Atom
A point particle in an MD simulation.
class AtomArray
An array of Atom objects.
class AtomCollector
Class for collecting Atoms from processors to master processor.
struct AtomContext
Descriptor for context of an Atom within a molecule and species.
class AtomDistributor
Class for distributing Atoms among processors.
class AtomIterator
Iterator for all atoms owned by an AtomStorage.
class AtomMap
Associative container for finding atoms identified by integer id.
class AtomStorage
A container for all the atoms and ghost atoms on this processor.
class AtomType
Descriptor for a type of Atom.
class AutoCorrAnalyzer
Compute an autocorrelation function for a sequence of Data values.
class AverageAnalyzer
Analyze average and block averages of a single floating point variable.
class BondFactory
Factory for BondPotential objects.
class BondPotential
Abstract base class for computing bond forces and energies.
class BondPotentialImpl
Implementation template for a BondPotential.
class BondStorage
Container for for Group<2> (bond) objects.
class BondTensorAutoCorr
Calculate stress autocorrelation function.
class Buffer
Buffer for interprocessor communication.
class Cell
A single Cell in a CellList.
class CellAtom
Data for an atom in a CellList.
class CellList
A cell list used only to identify nearby atom pairs.
class ConfigIo
Abstract reader/writer for configuration files.
class ConfigIoFactory
Default Factory for subclasses of ConfigIo.
class ConfigWriter
Periodically write simulation configuration to a new file.
class ConstAtomIterator
Const iterator for all atoms owned by an AtomStorage.
class ConstGhostIterator
Iterator for all ghost atoms owned by an AtomStorage.
class ConstGroupIterator
Const iterator for all Group < N > objects owned by a GroupStorage < N >.
class DdMdConfigIo
Native / default format for configuration files.
class DdMdGroupTrajectoryWriter
Native binary trajectory format for ddSim, for one group.
class DdMdOrderedConfigIo
Native / default format for configuration files.
class DdMdTrajectoryWriter
Native binary trajectory format for ddSim.
class DdTimer
Class for measuring time intervals.
class DihedralFactory
Factory for DihedralPotential objects.
class DihedralPotential
Abstract base class for computing dihedral forces and energies.
class DihedralPotentialImpl
Implementation template for a DihedralPotential.
class DihedralStorage
Container for Group<4> (dihedral) objects.
class Domain
Decomposition of the system into domains associated with processors.
class EnergyAnalyzer
Compute averages and output block averages of energy components.
class Exchanger
Class for exchanging Atoms, Ghosts and Groups between processors.
class ExternalEnergyAnalyzer
Output and evaluate average of external energy.
class ExternalEnergyAverage
Periodically write simulation energies to Log output.
class ExternalFactory
Factory for ExternalPotential objects.
class ExternalPotential
Calculates external forces and energies for a parent Simulation.
class ExternalPotentialImpl
Implementation template for a ExternalPotential.
class GhostIterator
Iterator for all ghost atoms owned by an AtomStorage.
class Group
A group of covalently interacting atoms.
class GroupCollector
Class for collecting Groups from processors to master processor.
class GroupDistributor
Class template for distributing Group<N> objects among processors.
class GroupExchanger
Interface for a GroupStorage<N> for use in Exchanger.
class GroupIterator
Iterator for all Group < N > objects owned by a GroupStorage< N >.
class GroupStorage
A container for all the Group<N> objects on this processor.
class Integrator
An Integrator numerically integrates the equations of motion.
class IntegratorFactory
Factory for subclasses of Integrator (i.e., MD integrators).
class KineticEnergyAnalyzer
Output and evaluate average of kinetic energy.
class LammpsConfigIo
Lammps data file format for configuration files.
class LammpsDumpWriter
Write a trajectory in the Lammps dump format.
class LogEnergy
Periodically write simulation energies to Log output.
class Mask
Set of Atoms for which pair interactions with a parent Atom are "masked".
class Modifier
A Modifier can modify the time evolution of the simulation.
class ModifierFactory
Factory for DdMd::Modifier objects.
class ModifierManager
Manager for a set of Modifier objects.
class NphIntegrator
A reversible, symplectic NPH integrator (Anderson barostat).
class NptIntegrator
A reversible symplectic NPT integrator.
class NveIntegrator
A velocity-Verlet constant energy integrator.
class NvtIntegrator
A Nose-Hoover constant temperature, constant volume integrator.
class NvtLangevinIntegrator
A NVT molecular dynamics integrator with a Langevin thermostat.
class OrderParamNucleation
OrderParamNucleation is designed to evaluate a sort of composition profile in the specific case of nucleating a lamellar ordered phase in a small region at the center of a simulation cell.
class OutputBoxdim
Periodically write Boundary dimensions to file.
class OutputEnergy
Periodically write simulation energies to file.
class OutputPairEnergies
Periodically write pair energies to file.
class OutputPressure
Periodically write (scalar) pressure to file.
class OutputStressTensor
Periodically write (tensor) StressTensor to file.
class OutputTemperature
Periodically output kinetic temperature to file.
class PairEnergyAnalyzer
Compute and analyze pair energies.
class PairEnergyAverage
Compute average of pair energy.
class PairFactory
Factory for PairPotential objects.
class PairIterator
Iterator for pairs in a PairList.
class PairList
A Verlet nonbonded pair list.
class PairPotential
Abstract base class for computing nonbonded pair forces and energies.
class PairPotentialImpl
Implementation template for a PairPotential.
class Plan
Communication plan.
class Potential
A Potential represents a potential energy contribution.
class PressureAnalyzer
Sample and evaluate average of total pressure.
class SerializeConfigIo
Save / load configuration from / to an archive.
class Simulation
Main object for a domain-decomposition MD simulation.
class SimulationAccess
Provides access to members of Simulation object.
class StressAnalyzer
Output and evaluate average of stress tensor.
class StressAutoCorr
Compute stress autocorrelation function for a liquid.
class StressAutoCorrelation
Compute the shear stress autocorrelation function.
class StructureFactor
StructureFactor evaluates structure factors in Fourier space.
class StructureFactorGrid
StructureFactorGrid evaluates structure factors in Fourier space.
class SymmTensorAverageAnalyzer
Analyzer that computes average of a sequence of symmetric Tensor values.
class TensorAverageAnalyzer
Analyzer that computes averages and block averages of a single Tensor.
class TrajectoryWriter
Base class to write a trajectory to a single file.
class TwoStepIntegrator
A two-step velocity-Verlet style integrator.
class VanHove
Evaluates the van Hove function S(k,t) for one or more wavevector k.
class VirialStressAnalyzer
Output and evaluate average of virial stress tensor.
class VirialStressTensor
Periodically write virial stress tensor components to file.
class VirialStressTensorAverage
Compute average and output block averages of virial stress tensor.
Enumerations
Functions
std::istream & operator>> (std::istream &in, AtomType &atomType)
istream extractor (>>) for an AtomType.
std::ostream & operator<< (std::ostream &out, const AtomType &atomType)
ostream inserter (<<) for an AtomType.
template<class Archive >
void serialize (Archive &ar, AtomType &atomType, const unsigned int version)
Serialize an AtomType.
template<int N>
std::istream & operator>> (std::istream &in, Group< N > &group)
istream extractor (>>) for a Group.
template<int N>
std::ostream & operator<< (std::ostream &out, const Group< N > &group)
ostream inserter (<<) for a Group.
template<class Archive , int N>
void serialize (Archive &ar, Group< N > &group, const unsigned int version)
Serialize one Group<N>.
std::istream & operator>> (std::istream &in, MaskPolicy &policy)
istream extractor for a MaskPolicy.
std::ostream & operator<< (std::ostream &out, MaskPolicy policy)
ostream inserter for an MaskPolicy.
template<class Archive >
void serialize (Archive &ar, MaskPolicy &policy, const unsigned int version)
Serialize a MaskPolicy.
std::istream & operator>> (std::istream &in, Plan &plan)
istream extractor (>>) for a Plan.
std::ostream & operator<< (std::ostream &out, const Plan &plan)
ostream inserter (<<) for a Plan.
void initStatic ()
Guarantee initialization of all static class members in DdMd namespace.
Detailed Description
Parallel domain decomposition (DD) MD simulation.
Function Documentation
std::istream & DdMd::operator>> (std::istream & in, AtomType & atomType)
istream extractor (>>) for an AtomType.
Format:
name mass
Parameters
in input stream
atomType AtomType to be read from stream
Returns
modified input stream
Definition at line 34 of file ddMd/chemistry/AtomType.cpp.
std::ostream & DdMd::operator<< (std::ostream & out, const AtomType & atomType)
ostream inserter (<<) for an AtomType.
Format, one one line with no line break:
name mass
Parameters
out output stream
atomType AtomType to be written to stream
Returns
modified output stream
Definition at line 44 of file ddMd/chemistry/AtomType.cpp.
References Util::Parameter::Precision, and Util::Parameter::Width.
template<class Archive > void DdMd::serialize (Archive & ar, AtomType & atomType, const unsigned int version)
Serialize an AtomType.
Parameters
ar archive
atomType object to be serialized
version archive version id
Definition at line 161 of file ddMd/chemistry/AtomType.h.
template<int N> std::istream & DdMd::operator>> (std::istream & in, Group< N > & group)
istream extractor (>>) for a Group.
Parameters
in input stream
group Group to be read from stream
Returns
modified input stream
Definition at line 378 of file ddMd/chemistry/Group.h.
template<int N> std::ostream & DdMd::operator<< (std::ostream & out, const Group< N > & group)
ostream inserter (<<) for a Group.
Format on one line with no line break:
Parameters
out output stream
group Group to be written to stream
Returns
modified output stream
Definition at line 392 of file ddMd/chemistry/Group.h.
References DdMd::Group< N >::serialize.
template<class Archive , int N> void DdMd::serialize (Archive & ar, Group< N > & group, const unsigned int version)
Serialize one Group<N>.
Default implementation calls serialize method of data object. Can be overridden by any explicit specialization.
Parameters
ar archive object
group object to be serialized
version archive version id
std::istream & DdMd::operator>> (std::istream & in, MaskPolicy & policy)
istream extractor for a MaskPolicy.
Parameters
in input stream
policy MaskPolicy to be read
Returns
modified input stream
Definition at line 31 of file ddMd/chemistry/MaskPolicy.cpp.
References UTIL_THROW.
std::ostream & DdMd::operator<< (std::ostream & out, MaskPolicy policy)
ostream inserter for an MaskPolicy.
Parameters
out output stream
policy MaskPolicy to be written
Returns
modified output stream
Definition at line 49 of file ddMd/chemistry/MaskPolicy.cpp.
References UTIL_THROW.
template<class Archive > void DdMd::serialize (Archive & ar, MaskPolicy & policy, const unsigned int version)
Serialize a MaskPolicy.
Parameters
ar archive object
policy MaskPolicy enum value to be serialized
version archive version id
Definition at line 57 of file ddMd/chemistry/MaskPolicy.h.
References Util::serializeEnum().
std::istream & DdMd::operator>> (std::istream & in, Plan & plan)
istream extractor (>>) for a Plan.
Parameters
in input stream
plan Plan to be read from stream
Returns
modified input stream
Definition at line 22 of file Plan.cpp.
References DdMd::Plan::clearExchange(), DdMd::Plan::clearGhost(), Util::Dimension, DdMd::Plan::setExchange(), and DdMd::Plan::setGhost().
std::ostream & DdMd::operator<< (std::ostream & out, const Plan & plan)
ostream inserter (<<) for a Plan.
Format, one one line with no line break:
Parameters
out output stream
plan Plan to be written to stream
Returns
modified output stream
Definition at line 58 of file Plan.cpp.
References Util::Dimension, DdMd::Plan::exchange(), and DdMd::Plan::ghost().
void DdMd::initStatic ()
Guarantee initialization of all static class members in DdMd namespace.
Definition at line 18 of file ddMd/misc/initStatic.cpp.
References DdMd::Modifier::initStatic().