Simpatico: Util Namespace Reference
Util Namespace Reference
Utility classes for scientific computation.
Classes
class AutoCorr
Auto-correlation function for one sequence of Data values.
class AutoCorrArray
Auto-correlation function for an ensemble of sequences.
class Average
Calculates the average and variance of a sampled property.
class AverageStage
A hierarchical block average algorithm.
class Distribution
A distribution (or histogram) of values for a real variable.
class IntDistribution
A distribution (or histogram) of values for an int variable.
class MeanSqDispArray
Mean-squared displacement (MSD) vs.
class RadialDistribution
Distribution (or histogram) of values for particle separations.
class BinaryFileIArchive
Saving archive for binary istream.
class BinaryFileOArchive
Saving archive for binary ostream.
class MemoryCounter
Archive to computed packed size of a sequence of objects, in bytes.
class MemoryIArchive
Input archive for packed heterogeneous binary data.
class MemoryOArchive
Save archive for packed heterogeneous binary data.
class Serializable
Abstract class for serializable objects.
class TextFileIArchive
Saving archive for binary istream.
class TextFileOArchive
Saving archive for character based ostream.
class MonoclinicBoundary
A monoclinic periodic unit cell.
class MpiTraits< MonoclinicBoundary >
Explicit specialization MpiTraits<MonoclinicBoundary>.
struct OrthoRegion
A region with orthogonal edges parallel to the x, y, and z axes.
class OrthorhombicBoundary
An orthorhombic periodic unit cell.
class MpiTraits< Util::OrthorhombicBoundary >
Explicit specialization MpiTraits<OrthorhombicBoundary>.
class APArray
Automatically resizable PArray.
class Array
Array container class template.
class ArrayIterator
Forward iterator for an Array or a C array.
class ArraySet
A container for pointers to a subset of elements of an associated array.
class ArrayStack
A stack of fixed capacity.
class ConstArrayIterator
Forward const iterator for an Array or a C array.
class ConstPArrayIterator
Forward iterator for a PArray.
class DArray
Dynamically allocatable Array class template.
class DMatrix
Dynamically allocated Matrix.
class DPArray
A dynamic array that only holds pointers to its elements.
class DRaggedMatrix
Dynamically allocated RaggedMatrix.
class DSArray
Dynamically allocated array with variable logical size.
class FArray
A fixed size array.
class FMatrix
Fixed Size Matrix.
class FPArray
Statically allocated pointer array.
class FSArray
A fixed capacity array with a variable logical size.
class List
Linked list class template.
class ListArray
An array of objects that are accessible by one or more linked List objects.
class ListIterator
Bidirectional iterator for a List.
class Matrix
Two-dimensional array container template (abstract).
class Node
Linked List Node, class template.
class PackedData
Memory block for packed heterogeneous binary data.
class Pair
An array of exactly 2 objects.
class PArray
An array that only holds pointers to its elements.
class PArrayIterator
Forward iterator for a PArray.
class RaggedMatrix
A 2D array in which different rows can have different lengths.
class RArray
An Array that acts as a reference to another Array or C array.
class RingBuffer
Class for storing history of previous values in an array.
class SSet
Statically allocated array of pointers to an unordered set.
class MpiTraits< Util::LatticeSystem >
Explicit specialization MpiTraits<LatticeSystem>.
class PointGroup
Group of crystal symmetries with no translations.
class PointSymmetry
A PointSymmetry represents a crystallographic point group symmetry.
class SymmetryGroup
Class template for a group of elements of type Symmetry.
class BoundaryEnsemble
Statistical ensemble for changes in the periodic unit cell size.
class MpiTraits< BoundaryEnsemble >
Explicit specialization MpiTraits<BoundaryEnsemble>.
class MpiTraits< BoundaryEnsemble::Type >
Explicit specialization MpiTraits<BoundaryEnsemble::Type>.
class EnergyEnsemble
A statistical ensemble for energy.
class MpiTraits< EnergyEnsemble >
Explicit specialization MpiTraits<EnergyEnsemble>.
class MpiTraits< EnergyEnsemble::Type >
Explicit specialization MpiTraits<EnergyEnsemble::Type>.
class SpeciesEnsemble
An ensemble for the number of molecules of one Species.
class MpiTraits< SpeciesEnsemble >
Explicit specialization MpiTraits<SpeciesEnsemble>.
class MpiTraits< SpeciesEnsemble::Type >
Explicit specialization MpiTraits<SpeciesEnsemble::Type>.
class Bool
Wrapper for an bool value, for formatted ostream output.
class Dbl
Wrapper for a double precision number, for formatted ostream output.
class Format
Base class for output wrappers for formatted C++ ostream output.
class Int
Wrapper for an int, for formatted ostream output.
class Lng
Wrapper for a long int, for formatted ostream output.
class Str
Wrapper for a std::string, for formatted ostream output.
class Constants
Mathematical constants.
class Memory
Provides method to allocate array.
class MpiFileIo
Identifies whether this processor may do file I/O.
class MpiLogger
Allows information from every processor in a communicator, to be output in rank sequence.
class MpiStructBuilder
A MpiStructBuilder objects is used to create an MPI Struct datatype.
class MpiTraits
Default MpiTraits class.
class MpiTraits< char >
MpiTraits<char> explicit specialization.
class MpiTraits< unsigned char >
MpiTraits<unsigned char> explicit specialization.
class MpiTraits< short >
MpiTraits<short> explicit specialization.
class MpiTraits< int >
MpiTraits<int> explicit specialization.
class MpiTraits< long >
MpiTraits<long> explicit specialization.
class MpiTraits< unsigned short >
MpiTraits<unsigned short> explicit specialization.
class MpiTraits< unsigned int >
MpiTraits<unsigned int> explicit specialization.
class MpiTraits< unsigned long >
MpiTraits<unsigned long> explicit specialization.
class MpiTraits< float >
MpiTraits<float> explicit specialization.
class MpiTraits< double >
MpiTraits<double> explicit specialization.
class MpiTraits< long double >
MpiTraits<long double> explicit specialization.
class MpiTraits< bool >
MpiTraits<bool> explicit specialization.
class Begin
Beginning line of a composite parameter block.
class Blank
An empty line within a parameter file.
class CArray2DParam
A Parameter associated with a 2D built-in C array.
class CArrayParam
A Parameter associated with a 1D C array.
class DArrayParam
A Parameter associated with a DArray container.
class DMatrixParam
A Parameter associated with a 2D built-in C array.
class End
End bracket of a ParamComposite parameter block.
class Factory
Factory template.
class FArrayParam
A Parameter associated with a FArray container.
class Label
A label string in a file format.
class Manager
Template container for pointers to objects with a common base class.
class ParamComponent
Abstract base class for classes that input and ouput parameters to file.
class ParamComposite
An object that can read multiple parameters from file.
class Parameter
A single variable in a parameter file.
class ScalarParam
Template for a Parameter object associated with a scalar variable.
class TextComposite
A text representation of a ParamComposite.
class FlexPtr
A pointer that may or may not own the object to which it points.
class ScopedPtr
A very simple RAII pointer.
class Ar1Process
Generator for a discrete AR(1) Markov process.
class MTRand_int32
Mersenne Twister random number generator engine.
class MTRand
Generates double floating point numbers in the half-open interval [0, 1)
class MTRand_closed
Generates double floating point numbers in the closed interval [0, 1].
class MTRand_open
Generates double floating point numbers in the open interval (0, 1).
class MTRand53
generates 53 bit resolution doubles in the half-open interval [0, 1)
class Random
Random number generator.
class IFunctor
Interface for functor that wraps a void function with one argument (abstract).
class IFunctor< void >
Interface for functor that wraps a void function with no arguments (abstract).
class MethodFunctor
Functor that wraps a one-argument class member function.
class MethodFunctor< Object, void >
Functor that wraps a class member function with no arguments.
class Signal
Notifier (or subject) in the Observer design pattern.
class Signal< void >
Notifier (or subject) in the Observer design pattern (zero parameters).
class Grid
A grid of points indexed by integer coordinates.
class IntVector
An IntVector is an integer Cartesian vector.
class MpiTraits< IntVector >
Explicit specialization MpiTraits<IntVector>.
class Tensor
A Tensor represents a Cartesian tensor.
class MpiTraits< Tensor >
Explicit specialization MpiTraits<Tensor>.
class Vector
A Vector is a Cartesian vector.
class MpiTraits< Vector >
Explicit specialization MpiTraits<Vector>.
class Exception
A user-defined exception.
class Log
A static class that holds a log output stream.
class Notifier
Abstract template for a notifier (or subject) in the Observer design pattern.
class Observer
Abstract class template for observer in the observer design pattern.
class Setable
Template for a value that can be declared null.
class Timer
Wall clock timer.
class MpiTraits< McMd::AtomType >
Explicit specialization MpiTraits<AtomType>.
class MpiTraits< McMd::MaskPolicy >
Explicit specialization MpiTraits<MaskPolicy>.
class MpiTraits< McMd::PairSelector >
Explicit specialization MpiTraits<PairSelector>.
class MpiTraits< McMd::PairSelector::PairType >
Explicit specialization MpiTraits<PairSelector::PairType>.
class MpiTraits< McMd::SpeciesGroup< 4 > >
Explicit specialization MpiTraits< SpeciesGroup<4> >.
class MpiTraits< McMd::SpeciesGroup< 3 > >
Explicit specialization MpiTraits< SpeciesGroup<3> >.
class MpiTraits< McMd::SpeciesGroup< 2 > >
Explicit specialization MpiTraits< SpeciesGroup<2> >.
class MpiTraits< Pair< int > >
Explicit specialization MpiTraits< Pair<int> >.
class MpiTraits< DdMd::AtomType >
Explicit specialization MpiTraits<AtomType>.
class MpiTraits< DdMd::MaskPolicy >
Explicit specialization MpiTraits<MaskPolicy>.
Typedefs
typedef unsigned char Byte
Define a "Byte" type.
Enumerations
enum LatticeSystem
Enumeration of the 7 possible Bravais lattice systems.
Functions
float product (float a, float b)
Product for float Data.
double product (double a, double b)
Product for double Data.
double product (const Vector &a, const Vector &b)
Dot product for Vector Data.
double product (const Tensor &a, const Tensor &b)
Double contraction for Tensor Data.
complex< float > product (complex< float > a, complex< float > b)
Inner product for complex<float> Data.
complex< double > product (complex< double > a, complex< double > b)
Inner product for complex<double> Data.
void setToZero (float &value)
Set a float variable to zero.
void setToZero (double &value)
Set a double variable to zero.
void setToZero (Vector &value)
Set a Vector variable to zero.
void setToZero (Tensor &value)
Set a Vector variable to zero.
void setToZero (complex< float > &value)
Set a complex<float> variable to zero.
void setToZero (complex< double > &value)
Set a complex<double> variable to zero.
template<>
void serialize (BinaryFileIArchive &ar, std::string &data, const unsigned int version)
Load a std::string from a BinaryFileIArchive.
template<>
void serialize (BinaryFileIArchive &ar, bool &data, const unsigned int version)
Load a bool from a BinaryFileIArchive.
template<>
void serialize (BinaryFileIArchive &ar, char &data, const unsigned int version)
Load a char from a BinaryFileIArchive.
template<>
void serialize (BinaryFileIArchive &ar, unsigned int &data, const unsigned int version)
Save an unsigned int from a BinaryFileIArchive.
template<>
void serialize (BinaryFileIArchive &ar, int &data, const unsigned int version)
Save an int from a BinaryFileIArchive.
template<>
void serialize (BinaryFileIArchive &ar, unsigned long &data, const unsigned int version)
Load an unsigned long int from a BinaryFileIArchive.
template<>
void serialize (BinaryFileIArchive &ar, long &data, const unsigned int version)
Load a long int from a BinaryFileIArchive.
template<>
void serialize (BinaryFileIArchive &ar, float &data, const unsigned int version)
Load a float from a BinaryFileIArchive.
template<>
void serialize (BinaryFileIArchive &ar, double &data, const unsigned int version)
Save an double from a BinaryFileIArchive.
template<>
void serialize (BinaryFileIArchive &ar, std::complex< float > &data, const unsigned int version)
Load a std::complex<float> from a BinaryFileIArchive.
template<>
void serialize (BinaryFileIArchive &ar, std::complex< double > &data, const unsigned int version)
Load a std::complex<double> from a BinaryFileIArchive.
template<>
void serialize (BinaryFileIArchive &ar, Vector &data, const unsigned int version)
Load a Util::Vector from a BinaryFileIArchive.
template<>
void serialize (BinaryFileIArchive &ar, IntVector &data, const unsigned int version)
Load a Util::IntVector from a BinaryFileIArchive.
template<>
void serialize (BinaryFileOArchive &ar, bool &data, const unsigned int version)
Save a bool to a BinaryFileOArchive.
template<>
void serialize (BinaryFileOArchive &ar, char &data, const unsigned int version)
Save a char to a BinaryFileOArchive.
template<>
void serialize (BinaryFileOArchive &ar, unsigned int &data, const unsigned int version)
Save an unsigned int to a BinaryFileOArchive.
template<>
void serialize (BinaryFileOArchive &ar, int &data, const unsigned int version)
Save an int to a BinaryFileOArchive.
template<>
void serialize (BinaryFileOArchive &ar, unsigned long &data, const unsigned int version)
Save an unsigned long int to a BinaryFileOArchive.
template<>
void serialize (BinaryFileOArchive &ar, long &data, const unsigned int version)
Save a long int to a BinaryFileOArchive.
template<>
void serialize (BinaryFileOArchive &ar, float &data, const unsigned int version)
Save a float to a BinaryFileOArchive.
template<>
void serialize (BinaryFileOArchive &ar, double &data, const unsigned int version)
Save an double to a BinaryFileOArchive.
template<>
void serialize (BinaryFileOArchive &ar, std::complex< float > &data, const unsigned int version)
Save a std::complex<float> to a BinaryFileOArchive.
template<>
void serialize (BinaryFileOArchive &ar, std::complex< double > &data, const unsigned int version)
Save a std::complex<double> to a BinaryFileOArchive.
template<>
void serialize (BinaryFileOArchive &ar, std::string &data, const unsigned int version)
Save a std::string to a BinaryFileOArchive.
template<>
void serialize (BinaryFileOArchive &ar, Vector &data, const unsigned int version)
Save a Util::Vector to a BinaryFileOArchive.
template<>
void serialize (BinaryFileOArchive &ar, IntVector &data, const unsigned int version)
Save a Util::IntVector to a BinaryFileOArchive.
template<typename T >
int memorySize (T &data)
Function template to compute memory size of one object.
template<>
void serialize (MemoryIArchive &ar, char &data, const unsigned int version)
Load a char from a MemoryIArchive.
template<>
void serialize (MemoryIArchive &ar, bool &data, const unsigned int version)
Load a bool from a MemoryIArchive.
template<>
void serialize (MemoryIArchive &ar, unsigned int &data, const unsigned int version)
Load an unsigned int from a MemoryIArchive.
template<>
void serialize (MemoryIArchive &ar, int &data, const unsigned int version)
Load an int from a MemoryIArchive.
template<>
void serialize (MemoryIArchive &ar, unsigned long &data, const unsigned int version)
Load an unsigned long int from a MemoryIArchive.
template<>
void serialize (MemoryIArchive &ar, long &data, const unsigned int version)
Load a long int from a MemoryIArchive.
template<>
void serialize (MemoryIArchive &ar, float &data, const unsigned int version)
Load a float from a MemoryIArchive.
template<>
void serialize (MemoryIArchive &ar, double &data, const unsigned int version)
Load an double from a MemoryIArchive.
template<>
void serialize (MemoryIArchive &ar, std::complex< float > &data, const unsigned int version)
Load a std::complex<float> from a MemoryIArchive.
template<>
void serialize (MemoryIArchive &ar, std::complex< double > &data, const unsigned int version)
Load a std::complex<double> from a MemoryIArchive.
template<>
void serialize (MemoryIArchive &ar, Vector &data, const unsigned int version)
Load a Util::Vector from a MemoryIArchive.
template<>
void serialize (MemoryIArchive &ar, IntVector &data, const unsigned int version)
Load a Util::IntVector from a MemoryIArchive.
template<>
void serialize (MemoryOArchive &ar, bool &data, const unsigned int version)
Save a bool to a MemoryOArchive.
template<>
void serialize (MemoryOArchive &ar, char &data, const unsigned int version)
Save a char to a MemoryOArchive.
template<>
void serialize (MemoryOArchive &ar, unsigned int &data, const unsigned int version)
Save an unsigned int to a MemoryOArchive.
template<>
void serialize (MemoryOArchive &ar, int &data, const unsigned int version)
Save an int to a MemoryOArchive.
template<>
void serialize (MemoryOArchive &ar, unsigned long &data, const unsigned int version)
Save a unsigned long int to a MemoryOArchive.
template<>
void serialize (MemoryOArchive &ar, long &data, const unsigned int version)
Save a long int to a MemoryOArchive.
template<>
void serialize (MemoryOArchive &ar, float &data, const unsigned int version)
Save a float to a MemoryOArchive.
template<>
void serialize (MemoryOArchive &ar, double &data, const unsigned int version)
Save an double to a MemoryOArchive.
template<>
void serialize (MemoryOArchive &ar, std::complex< float > &data, const unsigned int version)
Save a std::complex<float> to a MemoryOArchive.
template<>
void serialize (MemoryOArchive &ar, std::complex< double > &data, const unsigned int version)
Save a std::complex<double> to a MemoryOArchive.
template<>
void serialize (MemoryOArchive &ar, std::string &data, const unsigned int version)
Save a std::string to a MemoryOArchive.
template<>
void serialize (MemoryOArchive &ar, Vector &data, const unsigned int version)
Save a Util::Vector to a MemoryOArchive.
template<>
void serialize (MemoryOArchive &ar, IntVector &data, const unsigned int version)
Save a Util::IntVector to a MemoryOArchive.
template<class Archive , typename T >
void serialize (Archive &ar, T &data, const unsigned int version)
Serialize one object of type T.
template<class Archive , typename T >
void serializeEnum (Archive &ar, T &data, const unsigned int version=0)
Serialize an enumeration value.
template<class Archive , typename T >
void serializeCheck (Archive &ar, T &data, const char *label="")
Save a value, or save and check correctness on loading.
template<>
void serialize (TextFileIArchive &ar, std::string &data, const unsigned int version)
Load a std::string from a TextFileIArchive.
template<>
void serialize (TextFileIArchive &ar, bool &data, const unsigned int version)
Load a bool from a TextFileIArchive.
template<>
void serialize (TextFileIArchive &ar, char &data, const unsigned int version)
Load a char from a TextFileIArchive.
template<>
void serialize (TextFileIArchive &ar, unsigned int &data, const unsigned int version)
Save an unsigned int from a TextFileIArchive.
template<>
void serialize (TextFileIArchive &ar, int &data, const unsigned int version)
Save an int from a TextFileIArchive.
template<>
void serialize (TextFileIArchive &ar, unsigned long &data, const unsigned int version)
Load an unsigned long int from a TextFileIArchive.
template<>
void serialize (TextFileIArchive &ar, long &data, const unsigned int version)
Load a long int from a TextFileIArchive.
template<>
void serialize (TextFileIArchive &ar, float &data, const unsigned int version)
Load a float from a TextFileIArchive.
template<>
void serialize (TextFileIArchive &ar, double &data, const unsigned int version)
Save an double from a TextFileIArchive.
template<>
void serialize (TextFileIArchive &ar, std::complex< float > &data, const unsigned int version)
Load a std::complex<float> from a TextFileIArchive.
template<>
void serialize (TextFileIArchive &ar, std::complex< double > &data, const unsigned int version)
Load a std::complex<double> from a TextFileIArchive.
template<>
void serialize (TextFileIArchive &ar, Vector &data, const unsigned int version)
Load a Util::Vector from a TextFileIArchive.
template<>
void serialize (TextFileIArchive &ar, IntVector &data, const unsigned int version)
Load a Util::IntVector from a TextFileIArchive.
template<>
void serialize (TextFileOArchive &ar, bool &data, const unsigned int version)
Save a bool to a TextFileOArchive.
template<>
void serialize (TextFileOArchive &ar, char &data, const unsigned int version)
Save a char to a TextFileOArchive.
template<>
void serialize (TextFileOArchive &ar, unsigned int &data, const unsigned int version)
Save an unsigned int to a TextFileOArchive.
template<>
void serialize (TextFileOArchive &ar, int &data, const unsigned int version)
Save an int to a TextFileOArchive.
template<>
void serialize (TextFileOArchive &ar, unsigned long &data, const unsigned int version)
Save an unsigned long int to a TextFileOArchive.
template<>
void serialize (TextFileOArchive &ar, long &data, const unsigned int version)
Save a long int to a TextFileOArchive.
template<>
void serialize (TextFileOArchive &ar, float &data, const unsigned int version)
Save a float to a TextFileOArchive.
template<>
void serialize (TextFileOArchive &ar, double &data, const unsigned int version)
Save an double to a TextFileOArchive.
template<>
void serialize (TextFileOArchive &ar, std::complex< float > &data, const unsigned int version)
Save a std::complex<float> to a TextFileOArchive.
template<>
void serialize (TextFileOArchive &ar, std::complex< double > &data, const unsigned int version)
Save a std::complex<double> to a TextFileOArchive.
template<>
void serialize (TextFileOArchive &ar, std::string &data, const unsigned int version)
Save a std::string to a TextFileOArchive.
template<>
void serialize (TextFileOArchive &ar, Vector &data, const unsigned int version)
Save a Util::Vector to a TextFileOArchive.
template<>
void serialize (TextFileOArchive &ar, IntVector &data, const unsigned int version)
Save a Util::IntVector to a TextFileOArchive.
std::istream & operator>> (std::istream &in, MonoclinicBoundary &boundary)
istream extractor for a MonoclinicBoundary.
std::ostream & operator<< (std::ostream &out, const MonoclinicBoundary &boundary)
ostream inserter for an MonoclinicBoundary.
template<>
void send< MonoclinicBoundary > (MPI::Comm &comm, MonoclinicBoundary &data, int dest, int tag)
Send an MonoclinicBoundary via MPI.
template<>
void recv< MonoclinicBoundary > (MPI::Comm &comm, MonoclinicBoundary &data, int source, int tag)
Receive an MonoclinicBoundary via MPI.
template<>
void bcast< MonoclinicBoundary > (MPI::Intracomm &comm, MonoclinicBoundary &data, int root)
Broadcast an MonoclinicBoundary via MPI.
template<class T >
void send (MPI::Comm &comm, T &data, int dest, int tag)
Send a single T value.
template<class T >
void recv (MPI::Comm &comm, T &data, int source, int tag)
Receive a single T value.
template<class T >
void bcast (MPI::Intracomm &comm, T &data, int root)
Broadcast a single T value.
std::istream & operator>> (std::istream &in, OrthorhombicBoundary &boundary)
istream extractor for a OrthorhombicBoundary.
std::ostream & operator<< (std::ostream &out, const OrthorhombicBoundary &boundary)
ostream inserter for an OrthorhombicBoundary.
template<>
void send< Util::OrthorhombicBoundary > (MPI::Comm &comm, Util::OrthorhombicBoundary &data, int dest, int tag)
Send an OrthorhombicBoundary via MPI.
template<>
void recv< Util::OrthorhombicBoundary > (MPI::Comm &comm, Util::OrthorhombicBoundary &data, int source, int tag)
Receive an OrthorhombicBoundary via MPI.
template<>
void bcast< Util::OrthorhombicBoundary > (MPI::Intracomm &comm, Util::OrthorhombicBoundary &data, int root)
Broadcast an OrthorhombicBoundary via MPI.
template<typename Data >
std::istream & operator>> (std::istream &in, Pair< Data > &pair)
Input a Pair from an istream.
template<typename Data >
std::ostream & operator<< (std::ostream &out, const Pair< Data > &pair)
Output a Pair to an ostream, without line breaks.
home david code simpatico src
util crystal LatticeSystem cpp
std::istream & operator>> (std::istream &in, LatticeSystem &lattice)
istream extractor for a LatticeSystem.
std::ostream & operator<< (std::ostream &out, LatticeSystem lattice)
ostream inserter for an LatticeSystem.
home david code simpatico src
util crystal PointGroup cpp
std::ostream & operator<< (std::ostream &out, const PointGroup &g)
Output stream inserter operator writing a PointGroup to stream.
bool operator== (const PointSymmetry &A, const PointSymmetry &B)
Are two PointSymmetry objects equivalent?
PointSymmetry operator* (const PointSymmetry &A, const PointSymmetry &B)
Return the product A*B of two symmetry objects.
IntVector operator* (const PointSymmetry &S, const IntVector &V)
Return the IntVector product S*V of a rotation matrix and an IntVector.
IntVector operator* (const IntVector &V, const PointSymmetry &S)
Return the IntVector product V*S of an IntVector and a rotation matrix.
std::ostream & operator<< (std::ostream &out, const PointSymmetry &A)
Output stream inserter for a PointSymmetry.
bool operator!= (const PointSymmetry &A, const PointSymmetry &B)
Are two PointSymmetry objects not equivalent?
std::istream & operator>> (std::istream &in, BoundaryEnsemble::Type &type)
istream extractor for an BoundaryEnsemble::Type enum value.
std::ostream & operator<< (std::ostream &out, const BoundaryEnsemble::Type &type)
ostream inserter for a BoundaryEnsemble::Type enum value.
std::istream & operator>> (std::istream &in, EnergyEnsemble::Type &type)
istream extractor for an EnergyEnsemble::Type enum value.
std::ostream & operator<< (std::ostream &out, const EnergyEnsemble::Type &type)
ostream inserter for a EnergyEnsemble::Type enum value.
std::istream & operator>> (std::istream &in, SpeciesEnsemble::Type &type)
istream extractor for an SpeciesEnsemble::Type enum value.
std::ostream & operator<< (std::ostream &out, const SpeciesEnsemble::Type &type)
ostream inserter for a SpeciesEnsemble::Type enum value.
std::istream & operator>> (std::istream &in, Bool &object)
Input stream extractor for an Bool object.
std::ostream & operator<< (std::ostream &out, const Bool &object)
Output stream inserter for an Bool object.
std::istream & operator>> (std::istream &in, Dbl &object)
Input stream extractor for an Dbl object.
std::ostream & operator<< (std::ostream &out, const Dbl &object)
Output stream inserter for an Dbl object.
std::istream & operator>> (std::istream &in, Int &object)
Input stream extractor for an Int object.
std::ostream & operator<< (std::ostream &out, const Int &object)
Output stream inserter for an Int object.
std::istream & operator>> (std::istream &in, Lng &object)
Input stream extractor for an Lng object.
std::ostream & operator<< (std::ostream &out, const Lng &object)
Output stream inserter for an Lng object.
std::istream & operator>> (std::istream &in, Str &object)
Input stream extractor for an Str object.
std::ostream & operator<< (std::ostream &out, const Str &object)
Output stream inserter for an Str object.
template<>
home david code simpatico src
util format write cpp void write (std::ostream &out, double data)
Explicit specialization of write for double data.
template<>
void write (std::ostream &out, std::complex< double > data)
Explicit specialization of write for double data.
template<>
void write (std::ostream &out, int data)
Explicit specialization of write for int data.
template<>
void write (std::ostream &out, long data)
Explicit specialization of write for long data.
template<>
void write (std::ostream &out, bool data)
Explicit specialization of write for bool data.
template<typename Type >
void write (std::ostream &out, Type data)
Function template for output in a standard format.
template<>
void write (std::ostream &out, std::string data)
Explicit specialization of write for std::string data.
bool feq (double x, double y, double eps=1.0E-12)
Are two floating point numbers equal to within round-off error?
template<>
void send< bool > (MPI::Comm &comm, bool &data, int dest, int tag)
Explicit specialization of send for bool data.
template<>
void recv< bool > (MPI::Comm &comm, bool &data, int source, int tag)
Explicit specialization of recv for bool data.
template<>
void bcast< bool > (MPI::Intracomm &comm, bool &data, int root)
Explicit specialization of bcast for bool data.
template<>
void send< std::string > (MPI::Comm &comm, std::string &data, int dest, int tag)
Explicit specialization of send for std::string data.
template<>
void recv< std::string > (MPI::Comm &comm, std::string &data, int source, int tag)
Explicit specialization of recv for std::string data.
template<>
void bcast< std::string > (MPI::Intracomm &comm, std::string &data, int root)
Explicit specialization of bcast for std::string data.
template<typename T >
void send (MPI::Comm &comm, T *array, int count, int dest, int tag)
Send a C-array of T values.
template<typename T >
void recv (MPI::Comm &comm, T *array, int count, int source, int tag)
Receive a C-array of T objects.
template<typename T >
void bcast (MPI::Intracomm &comm, T *array, int count, int root)
Broadcast a C-array of T objects.
template<typename T >
void send (MPI::Comm &comm, DArray< T > &array, int count, int dest, int tag)
Send a DArray<T> container.
template<typename T >
void recv (MPI::Comm &comm, DArray< T > &array, int count, int source, int tag)
Receive a DArray<T> container.
template<typename T >
void bcast (MPI::Intracomm &comm, DArray< T > &array, int count, int root)
Broadcast a DArray<T> container.
template<typename T >
void send (MPI::Comm &comm, DMatrix< T > &matrix, int m, int n, int dest, int tag)
Send a DMatrix<T> container.
template<typename T >
void recv (MPI::Comm &comm, DMatrix< T > &matrix, int m, int n, int source, int tag)
Receive a DMatrix<T> container.
template<typename T >
void bcast (MPI::Intracomm &comm, DMatrix< T > &matrix, int m, int n, int root)
Broadcast a DMatrix<T> container.
std::istream & operator>> (std::istream &in, Label label)
Extractor for Label.
std::ostream & operator<< (std::ostream &out, Label label)
Inserter for Label.
template<typename T >
bool isNull (FlexPtr< T > p)
Return true iff the enclosed built-in pointer is null.
template<typename T >
bool isNull (T *ptr)
Return true iff a built-in pointer is null.
template<typename T >
bool isNull (ScopedPtr< T > p)
Return true iff the enclosed built-in pointer is null.
bool operator== (const IntVector &v1, const IntVector &v2)
Equality for IntVectors.
bool operator== (const IntVector &v1, const int *v2)
Equality of IntVector and C array.
bool operator== (const int *v1, const IntVector &v2)
Equality of C array and IntVector.
bool operator!= (const IntVector &v1, const IntVector &v2)
Inequality of two IntVectors.
bool operator!= (const IntVector &v1, const int *v2)
Inequality of IntVector and C array.
bool operator!= (const int *v1, const IntVector &v2)
Inequality of C array and IntVector.
std::istream & operator>> (std::istream &in, IntVector &vector)
istream extractor for a IntVector.
std::ostream & operator<< (std::ostream &out, const IntVector &vector)
ostream inserter for a IntVector.
bool operator== (const Tensor &t1, const Tensor &t2)
Equality for Tensors.
bool operator== (const Tensor &t1, const double t2[][Dimension])
Equality of Tensor and 2D C array.
bool operator== (const double t1[][Dimension], const Tensor &t2)
Equality of C array and Tensor.
bool operator!= (const Tensor &t1, const Tensor &t2)
Inequality of two Tensors.
bool operator!= (const Tensor &t1, const double t2[][Dimension])
Inequality of Tensor and C array.
bool operator!= (const double t1[][Dimension], const Tensor &t2)
Inequality of C array and Tensor.
std::istream & operator>> (std::istream &in, Tensor &tensor)
istream extractor for a Tensor.
std::ostream & operator<< (std::ostream &out, const Tensor &tensor)
ostream inserter for a Tensor.
bool operator== (const Vector &v1, const Vector &v2)
Equality for Vectors.
bool operator== (const Vector &v1, const double *v2)
Equality of Vector and C array.
bool operator== (const double *v1, const Vector &v2)
Equality of C array and Vector.
bool operator!= (const Vector &v1, const Vector &v2)
Inequality of two Vectors.
bool operator!= (const Vector &v1, const double *v2)
Inequality of Vector and C array.
bool operator!= (const double *v1, const Vector &v2)
Inequality of C array and Vector.
std::istream & operator>> (std::istream &in, Vector &vector)
istream extractor for a Vector.
std::ostream & operator<< (std::ostream &out, const Vector &vector)
ostream inserter for a Vector.
home david code simpatico src
util util initStatic cpp void initStatic ()
Guarantee initialization of all static class members in Util namespace.
home david code simpatico src
util util ioUtil cpp int rStrip (std::string &string)
Strip trailing whitespace from a string.
void checkString (std::istream &in, std::string &expected)
Read string, and compare to expected value.
std::string toString (int n)
Return string representation of an integer.
void getNextLine (std::istream &in, std::string &line)
Get the next non-empty line of input, skipping any empty lines.
void getLine (std::istream &in, std::stringstream &line)
Read the next line into a stringstream.
void getNextLine (std::istream &in, std::stringstream &line)
Read the next non-empty line into a stringstream.
template<typename D , typename B , typename M >
ptrdiff_t memberOffset (D &object, M B::*memPtr)
Template for calculating offsets of data members.
template<typename D , typename B >
ptrdiff_t baseOffset (D &object)
Template for calculating offsets of base class subobjects.
template<>
void send< McMd::AtomType > (MPI::Comm &comm, McMd::AtomType &data, int dest, int tag)
Send an AtomType (wrapper for MPI Send).
template<>
void recv< McMd::AtomType > (MPI::Comm &comm, McMd::AtomType &data, int source, int tag)
Receive an AtomType (wrapper for MPI Recv).
template<>
void bcast< McMd::AtomType > (MPI::Intracomm &comm, McMd::AtomType &data, int root)
Broadcast an AtomType (wrapper for MPI Bcast).
Variables
home david code simpatico src
util boundary Boundary h
typedef OrthorhombicBoundary Boundary
Boundary is an alias for the periodic boundary condition class.
const int Dimension = 3
Dimensionality of space.
const int DimensionSq = Dimension*Dimension
Square of Dimensionality of space.
Detailed Description
Utility classes for scientific computation.
Typedef Documentation
typedef unsigned char Util::Byte
Define a "Byte" type.
Definition at line 19 of file Byte.h.
Function Documentation
float Util::product (float a, float b) [inline]
Product for float Data.
Definition at line 22 of file product.h.
Referenced by Util::AutoCorr< Data, Product >::autoCorrelation(), Util::AutoCorrArray< Data, Product >::corrTime(), Util::AutoCorr< Data, Product >::corrTime(), Util::AutoCorrArray< Data, Product >::output(), Util::AutoCorr< Data, Product >::output(), McMd::VanHove::sample(), McMd::StructureFactorP::sample(), DdMd::StructureFactor::sample(), McMd::StructureFactor::sample(), McMd::MigratingVanHove::sample(), McMd::IntraStructureFactor::sample(), McMd::CompositionProfile::sample(), Util::AutoCorrArray< Data, Product >::sample(), and Util::AutoCorr< Data, Product >::sample().
double Util::product (double a, double b) [inline]
Product for double Data.
Definition at line 28 of file product.h.
double Util::product (const Vector & a, const Vector & b) [inline]
Dot product for Vector Data.
Definition at line 34 of file product.h.
References Util::Vector::dot().
double Util::product (const Tensor & a, const Tensor & b) [inline]
Double contraction for Tensor Data.
Definition at line 40 of file product.h.
References Dimension.
complex<float> Util::product (complex< float > a, complex< float > b) [inline]
Inner product for complex<float> Data.
Definition at line 55 of file product.h.
complex<double> Util::product (complex< double > a, complex< double > b) [inline]
Inner product for complex<double> Data.
Definition at line 61 of file product.h.
void Util::setToZero (float & value) [inline]
Set a float variable to zero.
Parameters:
value value to be zeroed.
Definition at line 25 of file setToZero.h.
Referenced by Util::AutoCorr< Data, Product >::AutoCorr(), Util::AutoCorrArray< Data, Product >::AutoCorrArray(), Util::MeanSqDispArray< Data >::clear(), Util::AutoCorrArray< Data, Product >::clear(), Util::AutoCorr< Data, Product >::clear(), Util::AutoCorrArray< Data, Product >::corrTime(), and Util::AutoCorr< Data, Product >::corrTime().
void Util::setToZero (double & value) [inline]
Set a double variable to zero.
Parameters:
value value to be zeroed.
Definition at line 33 of file setToZero.h.
void Util::setToZero (Vector & value) [inline]
Set a Vector variable to zero.
Parameters:
value value to be zeroed.
Definition at line 41 of file setToZero.h.
References Util::Vector::zero().
void Util::setToZero (Tensor & value) [inline]
Set a Vector variable to zero.
Parameters:
value value to be zeroed.
Definition at line 49 of file setToZero.h.
References Util::Tensor::zero().
void Util::setToZero (complex< float > & value) [inline]
Set a complex<float> variable to zero.
Parameters:
value value to be zeroed.
Definition at line 57 of file setToZero.h.
void Util::setToZero (complex< double > & value) [inline]
Set a complex<double> variable to zero.
Parameters:
value value to be zeroed.
Definition at line 65 of file setToZero.h.
template<> void Util::serialize (BinaryFileIArchive & ar, std::string & data, const unsigned int version)
Load a std::string from a BinaryFileIArchive.
Definition at line 45 of file BinaryFileIArchive.cpp.
Referenced by Util::TextFileOArchive::operator&(), Util::TextFileIArchive::operator&(), Util::MemoryOArchive::operator&(), Util::MemoryIArchive::operator&(), Util::BinaryFileOArchive::operator&(), Util::BinaryFileIArchive::operator&(), Util::TextFileOArchive::operator<<(), Util::MemoryOArchive::operator<<(), Util::BinaryFileOArchive::operator<<(), Util::TextFileIArchive::operator>>(), Util::MemoryIArchive::operator>>(), and Util::BinaryFileIArchive::operator>>().
template<> void Util::serialize (BinaryFileIArchive & ar, bool & data, const unsigned int version) [inline]
Load a bool from a BinaryFileIArchive.
Definition at line 141 of file BinaryFileIArchive.h.
template<> void Util::serialize (BinaryFileIArchive & ar, char & data, const unsigned int version) [inline]
Load a char from a BinaryFileIArchive.
Definition at line 149 of file BinaryFileIArchive.h.
template<> void Util::serialize (BinaryFileIArchive & ar, unsigned int & data, const unsigned int version) [inline]
Save an unsigned int from a BinaryFileIArchive.
Definition at line 157 of file BinaryFileIArchive.h.
template<> void Util::serialize (BinaryFileIArchive & ar, int & data, const unsigned int version) [inline]
Save an int from a BinaryFileIArchive.
Definition at line 165 of file BinaryFileIArchive.h.
template<> void Util::serialize (BinaryFileIArchive & ar, unsigned long & data, const unsigned int version) [inline]
Load an unsigned long int from a BinaryFileIArchive.
Definition at line 173 of file BinaryFileIArchive.h.
template<> void Util::serialize (BinaryFileIArchive & ar, long & data, const unsigned int version) [inline]
Load a long int from a BinaryFileIArchive.
Definition at line 181 of file BinaryFileIArchive.h.
template<> void Util::serialize (BinaryFileIArchive & ar, float & data, const unsigned int version) [inline]
Load a float from a BinaryFileIArchive.
Definition at line 189 of file BinaryFileIArchive.h.
template<> void Util::serialize (BinaryFileIArchive & ar, double & data, const unsigned int version) [inline]
Save an double from a BinaryFileIArchive.
Definition at line 197 of file BinaryFileIArchive.h.
template<> void Util::serialize (BinaryFileIArchive & ar, std::complex< float > & data, const unsigned int version) [inline]
Load a std::complex<float> from a BinaryFileIArchive.
Definition at line 208 of file BinaryFileIArchive.h.
template<> void Util::serialize (BinaryFileIArchive & ar, std::complex< double > & data, const unsigned int version) [inline]
Load a std::complex<double> from a BinaryFileIArchive.
Definition at line 217 of file BinaryFileIArchive.h.
template<> void Util::serialize (BinaryFileIArchive & ar, Vector & data, const unsigned int version) [inline]
Load a Util::Vector from a BinaryFileIArchive.
Definition at line 234 of file BinaryFileIArchive.h.
template<> void Util::serialize (BinaryFileIArchive & ar, IntVector & data, const unsigned int version) [inline]
Load a Util::IntVector from a BinaryFileIArchive.
Definition at line 242 of file BinaryFileIArchive.h.
template<> void Util::serialize (BinaryFileOArchive & ar, bool & data, const unsigned int version) [inline]
Save a bool to a BinaryFileOArchive.
Definition at line 141 of file BinaryFileOArchive.h.
template<> void Util::serialize (BinaryFileOArchive & ar, char & data, const unsigned int version) [inline]
Save a char to a BinaryFileOArchive.
Definition at line 149 of file BinaryFileOArchive.h.
template<> void Util::serialize (BinaryFileOArchive & ar, unsigned int & data, const unsigned int version) [inline]
Save an unsigned int to a BinaryFileOArchive.
Definition at line 157 of file BinaryFileOArchive.h.
template<> void Util::serialize (BinaryFileOArchive & ar, int & data, const unsigned int version) [inline]
Save an int to a BinaryFileOArchive.
Definition at line 165 of file BinaryFileOArchive.h.
template<> void Util::serialize (BinaryFileOArchive & ar, unsigned long & data, const unsigned int version) [inline]
Save an unsigned long int to a BinaryFileOArchive.
Definition at line 173 of file BinaryFileOArchive.h.
template<> void Util::serialize (BinaryFileOArchive & ar, long & data, const unsigned int version) [inline]
Save a long int to a BinaryFileOArchive.
Definition at line 181 of file BinaryFileOArchive.h.
template<> void Util::serialize (BinaryFileOArchive & ar, float & data, const unsigned int version) [inline]
Save a float to a BinaryFileOArchive.
Definition at line 189 of file BinaryFileOArchive.h.
template<> void Util::serialize (BinaryFileOArchive & ar, double & data, const unsigned int version) [inline]
Save an double to a BinaryFileOArchive.
Definition at line 197 of file BinaryFileOArchive.h.
template<> void Util::serialize (BinaryFileOArchive & ar, std::complex< float > & data, const unsigned int version) [inline]
Save a std::complex<float> to a BinaryFileOArchive.
Definition at line 208 of file BinaryFileOArchive.h.
template<> void Util::serialize (BinaryFileOArchive & ar, std::complex< double > & data, const unsigned int version) [inline]
Save a std::complex<double> to a BinaryFileOArchive.
Definition at line 217 of file BinaryFileOArchive.h.
template<> void Util::serialize (BinaryFileOArchive & ar, std::string & data, const unsigned int version) [inline]
Save a std::string to a BinaryFileOArchive.
Definition at line 225 of file BinaryFileOArchive.h.
template<> void Util::serialize (BinaryFileOArchive & ar, Vector & data, const unsigned int version) [inline]
Save a Util::Vector to a BinaryFileOArchive.
Definition at line 240 of file BinaryFileOArchive.h.
template<> void Util::serialize (BinaryFileOArchive & ar, IntVector & data, const unsigned int version) [inline]
Save a Util::IntVector to a BinaryFileOArchive.
Definition at line 248 of file BinaryFileOArchive.h.
template<typename T > int Util::memorySize (T & data)
Function template to compute memory size of one object.
Definition at line 130 of file MemoryCounter.h.
References Util::MemoryCounter::size().
Referenced by McMd::ReplicaMove::move(), and McMd::MigratingVanHove::update().
template<> void Util::serialize (MemoryIArchive & ar, char & data, const unsigned int version) [inline]
Load a char from a MemoryIArchive.
Definition at line 280 of file MemoryIArchive.h.
References Util::MemoryIArchive::unpack().
template<> void Util::serialize (MemoryIArchive & ar, bool & data, const unsigned int version) [inline]
Load a bool from a MemoryIArchive.
Definition at line 288 of file MemoryIArchive.h.
References Util::MemoryIArchive::unpack().
template<> void Util::serialize (MemoryIArchive & ar, unsigned int & data, const unsigned int version) [inline]
Load an unsigned int from a MemoryIArchive.
Definition at line 296 of file MemoryIArchive.h.
References Util::MemoryIArchive::unpack().
template<> void Util::serialize (MemoryIArchive & ar, int & data, const unsigned int version) [inline]
Load an int from a MemoryIArchive.
Definition at line 304 of file MemoryIArchive.h.
References Util::MemoryIArchive::unpack().
template<> void Util::serialize (MemoryIArchive & ar, unsigned long & data, const unsigned int version) [inline]
Load an unsigned long int from a MemoryIArchive.
Definition at line 312 of file MemoryIArchive.h.
References Util::MemoryIArchive::unpack().
template<> void Util::serialize (MemoryIArchive & ar, long & data, const unsigned int version) [inline]
Load a long int from a MemoryIArchive.
Definition at line 320 of file MemoryIArchive.h.
References Util::MemoryIArchive::unpack().
template<> void Util::serialize (MemoryIArchive & ar, float & data, const unsigned int version) [inline]
Load a float from a MemoryIArchive.
Definition at line 328 of file MemoryIArchive.h.
References Util::MemoryIArchive::unpack().
template<> void Util::serialize (MemoryIArchive & ar, double & data, const unsigned int version) [inline]
Load an double from a MemoryIArchive.
Definition at line 336 of file MemoryIArchive.h.
References Util::MemoryIArchive::unpack().
template<> void Util::serialize (MemoryIArchive & ar, std::complex< float > & data, const unsigned int version) [inline]
Load a std::complex<float> from a MemoryIArchive.
Definition at line 344 of file MemoryIArchive.h.
References Util::MemoryIArchive::unpack().
template<> void Util::serialize (MemoryIArchive & ar, std::complex< double > & data, const unsigned int version) [inline]
Load a std::complex<double> from a MemoryIArchive.
Definition at line 352 of file MemoryIArchive.h.
References Util::MemoryIArchive::unpack().
template<> void Util::serialize (MemoryIArchive & ar, Vector & data, const unsigned int version) [inline]
Load a Util::Vector from a MemoryIArchive.
Definition at line 367 of file MemoryIArchive.h.
References Util::MemoryIArchive::unpack().
template<> void Util::serialize (MemoryIArchive & ar, IntVector & data, const unsigned int version) [inline]
Load a Util::IntVector from a MemoryIArchive.
Definition at line 375 of file MemoryIArchive.h.
References Util::MemoryIArchive::unpack().
template<> void Util::serialize (MemoryOArchive & ar, bool & data, const unsigned int version) [inline]
Save a bool to a MemoryOArchive.
Definition at line 259 of file MemoryOArchive.h.
template<> void Util::serialize (MemoryOArchive & ar, char & data, const unsigned int version) [inline]
Save a char to a MemoryOArchive.
Definition at line 267 of file MemoryOArchive.h.
template<> void Util::serialize (MemoryOArchive & ar, unsigned int & data, const unsigned int version) [inline]
Save an unsigned int to a MemoryOArchive.
Definition at line 275 of file MemoryOArchive.h.
template<> void Util::serialize (MemoryOArchive & ar, int & data, const unsigned int version) [inline]
Save an int to a MemoryOArchive.
Definition at line 283 of file MemoryOArchive.h.
template<> void Util::serialize (MemoryOArchive & ar, unsigned long & data, const unsigned int version) [inline]
Save a unsigned long int to a MemoryOArchive.
Definition at line 291 of file MemoryOArchive.h.
template<> void Util::serialize (MemoryOArchive & ar, long & data, const unsigned int version) [inline]
Save a long int to a MemoryOArchive.
Definition at line 299 of file MemoryOArchive.h.
template<> void Util::serialize (MemoryOArchive & ar, float & data, const unsigned int version) [inline]
Save a float to a MemoryOArchive.
Definition at line 307 of file MemoryOArchive.h.
template<> void Util::serialize (MemoryOArchive & ar, double & data, const unsigned int version) [inline]
Save an double to a MemoryOArchive.
Definition at line 315 of file MemoryOArchive.h.
template<> void Util::serialize (MemoryOArchive & ar, std::complex< float > & data, const unsigned int version) [inline]
Save a std::complex<float> to a MemoryOArchive.
Definition at line 325 of file MemoryOArchive.h.
template<> void Util::serialize (MemoryOArchive & ar, std::complex< double > & data, const unsigned int version) [inline]
Save a std::complex<double> to a MemoryOArchive.
Definition at line 333 of file MemoryOArchive.h.
template<> void Util::serialize (MemoryOArchive & ar, std::string & data, const unsigned int version) [inline]
Save a std::string to a MemoryOArchive.
Definition at line 341 of file MemoryOArchive.h.
template<> void Util::serialize (MemoryOArchive & ar, Vector & data, const unsigned int version) [inline]
Save a Util::Vector to a MemoryOArchive.
Definition at line 356 of file MemoryOArchive.h.
template<> void Util::serialize (MemoryOArchive & ar, IntVector & data, const unsigned int version) [inline]
Save a Util::IntVector to a MemoryOArchive.
Definition at line 364 of file MemoryOArchive.h.
template<class Archive , typename T > void Util::serialize (Archive & ar, T & data, const unsigned int version) [inline]
Serialize one object of type T.
Default implementation calls serialize method of data object. Can be overridden by any explicit specialization.
Parameters:
ar archive object
data object to be serialized
version archive version id
Definition at line 27 of file util/archives/serialize.h.
template<class Archive , typename T > void Util::serializeEnum (Archive & ar, T & data, const unsigned int version = 0) [inline]
Serialize an enumeration value.
Parameters:
ar archive object
data object to be serialized
version archive version id
Definition at line 38 of file util/archives/serialize.h.
Referenced by McMd::NphIntegrator::load(), McMd::NphIntegrator::save(), and Util::OrthorhombicBoundary::serialize().
template<class Archive , typename T > void Util::serializeCheck (Archive & ar, T & data, const char * label = "") [inline]
Save a value, or save and check correctness on loading.
Parameters:
ar archive object
data object to be serialized
label label C-string for object.
Definition at line 58 of file util/archives/serialize.h.
References UTIL_THROW.
Referenced by McMd::NvtDpdVvIntegrator::load(), McMd::NvtDpdVvIntegrator::save(), McMd::VanHove::serialize(), McMd::StructureFactorP::serialize(), McMd::StructureFactor::serialize(), McMd::RDF::serialize(), McMd::MigratingVanHove::serialize(), McMd::MdPotentialEnergyAverage::serialize(), McMd::MdPairEnergyCoefficients::serialize(), McMd::MdKineticEnergyAverage::serialize(), McMd::McStressAutoCorr::serialize(), McMd::McPairEnergyAverage::serialize(), McMd::McExternalEnergyAverage::serialize(), McMd::LinearRouseAutoCorr::serialize(), McMd::IntraStructureFactor::serialize(), McMd::IntraPairAutoCorr::serialize(), McMd::IntraBondTensorAutoCorr< SystemType >::serialize(), McMd::IntraBondStressAutoCorr< SystemType >::serialize(), McMd::ComMSD::serialize(), McMd::BondLengthDist::serialize(), McMd::BlockRadiusGyration::serialize(), and McMd::AtomMSD::serialize().
template<> void Util::serialize (TextFileIArchive & ar, std::string & data, const unsigned int version)
Load a std::string from a TextFileIArchive.
Definition at line 45 of file TextFileIArchive.cpp.
template<> void Util::serialize (TextFileIArchive & ar, bool & data, const unsigned int version) [inline]
Load a bool from a TextFileIArchive.
Definition at line 157 of file TextFileIArchive.h.
template<> void Util::serialize (TextFileIArchive & ar, char & data, const unsigned int version) [inline]
Load a char from a TextFileIArchive.
Definition at line 165 of file TextFileIArchive.h.
template<> void Util::serialize (TextFileIArchive & ar, unsigned int & data, const unsigned int version) [inline]
Save an unsigned int from a TextFileIArchive.
Definition at line 173 of file TextFileIArchive.h.
template<> void Util::serialize (TextFileIArchive & ar, int & data, const unsigned int version) [inline]
Save an int from a TextFileIArchive.
Definition at line 181 of file TextFileIArchive.h.
template<> void Util::serialize (TextFileIArchive & ar, unsigned long & data, const unsigned int version) [inline]
Load an unsigned long int from a TextFileIArchive.
Definition at line 189 of file TextFileIArchive.h.
template<> void Util::serialize (TextFileIArchive & ar, long & data, const unsigned int version) [inline]
Load a long int from a TextFileIArchive.
Definition at line 197 of file TextFileIArchive.h.
template<> void Util::serialize (TextFileIArchive & ar, float & data, const unsigned int version) [inline]
Load a float from a TextFileIArchive.
Definition at line 205 of file TextFileIArchive.h.
template<> void Util::serialize (TextFileIArchive & ar, double & data, const unsigned int version) [inline]
Save an double from a TextFileIArchive.
Definition at line 213 of file TextFileIArchive.h.
template<> void Util::serialize (TextFileIArchive & ar, std::complex< float > & data, const unsigned int version) [inline]
Load a std::complex<float> from a TextFileIArchive.
Definition at line 224 of file TextFileIArchive.h.
template<> void Util::serialize (TextFileIArchive & ar, std::complex< double > & data, const unsigned int version) [inline]
Load a std::complex<double> from a TextFileIArchive.
Definition at line 233 of file TextFileIArchive.h.
template<> void Util::serialize (TextFileIArchive & ar, Vector & data, const unsigned int version) [inline]
Load a Util::Vector from a TextFileIArchive.
Definition at line 250 of file TextFileIArchive.h.
template<> void Util::serialize (TextFileIArchive & ar, IntVector & data, const unsigned int version) [inline]
Load a Util::IntVector from a TextFileIArchive.
Definition at line 258 of file TextFileIArchive.h.
template<> void Util::serialize (TextFileOArchive & ar, bool & data, const unsigned int version) [inline]
Save a bool to a TextFileOArchive.
Definition at line 154 of file TextFileOArchive.h.
template<> void Util::serialize (TextFileOArchive & ar, char & data, const unsigned int version) [inline]
Save a char to a TextFileOArchive.
Definition at line 162 of file TextFileOArchive.h.
template<> void Util::serialize (TextFileOArchive & ar, unsigned int & data, const unsigned int version) [inline]
Save an unsigned int to a TextFileOArchive.
Definition at line 170 of file TextFileOArchive.h.
template<> void Util::serialize (TextFileOArchive & ar, int & data, const unsigned int version) [inline]
Save an int to a TextFileOArchive.
Definition at line 178 of file TextFileOArchive.h.
template<> void Util::serialize (TextFileOArchive & ar, unsigned long & data, const unsigned int version) [inline]
Save an unsigned long int to a TextFileOArchive.
Definition at line 186 of file TextFileOArchive.h.
template<> void Util::serialize (TextFileOArchive & ar, long & data, const unsigned int version) [inline]
Save a long int to a TextFileOArchive.
Definition at line 194 of file TextFileOArchive.h.
template<> void Util::serialize (TextFileOArchive & ar, float & data, const unsigned int version) [inline]
Save a float to a TextFileOArchive.
Definition at line 202 of file TextFileOArchive.h.
template<> void Util::serialize (TextFileOArchive & ar, double & data, const unsigned int version) [inline]
Save an double to a TextFileOArchive.
Definition at line 210 of file TextFileOArchive.h.
template<> void Util::serialize (TextFileOArchive & ar, std::complex< float > & data, const unsigned int version) [inline]
Save a std::complex<float> to a TextFileOArchive.
Definition at line 221 of file TextFileOArchive.h.
template<> void Util::serialize (TextFileOArchive & ar, std::complex< double > & data, const unsigned int version) [inline]
Save a std::complex<double> to a TextFileOArchive.
Definition at line 230 of file TextFileOArchive.h.
template<> void Util::serialize (TextFileOArchive & ar, std::string & data, const unsigned int version) [inline]
Save a std::string to a TextFileOArchive.
Definition at line 238 of file TextFileOArchive.h.
template<> void Util::serialize (TextFileOArchive & ar, Vector & data, const unsigned int version) [inline]
Save a Util::Vector to a TextFileOArchive.
Definition at line 252 of file TextFileOArchive.h.
template<> void Util::serialize (TextFileOArchive & ar, IntVector & data, const unsigned int version) [inline]
Save a Util::IntVector to a TextFileOArchive.
Definition at line 260 of file TextFileOArchive.h.
std::istream & Util::operator>> (std::istream & in, MonoclinicBoundary & boundary)
istream extractor for a MonoclinicBoundary.
istream extractor
Parameters:
in input stream
boundary MonoclinicBoundary to be read from stream
Returns:
modified input stream
Definition at line 165 of file MonoclinicBoundary.cpp.
References UTIL_THROW.
std::ostream & Util::operator<< (std::ostream & out, const MonoclinicBoundary & boundary)
ostream inserter for an MonoclinicBoundary.
ostream inserter
Parameters:
out output stream
boundary MonoclinicBoundary to be written to stream
Returns:
modified output stream
Definition at line 182 of file MonoclinicBoundary.cpp.
template<> void Util::send< MonoclinicBoundary > (MPI::Comm & comm, MonoclinicBoundary & data, int dest, int tag)
Send an MonoclinicBoundary via MPI.
Definition at line 192 of file MonoclinicBoundary.cpp.
template<> void Util::recv< MonoclinicBoundary > (MPI::Comm & comm, MonoclinicBoundary & data, int source, int tag)
Receive an MonoclinicBoundary via MPI.
Definition at line 200 of file MonoclinicBoundary.cpp.
template<> void Util::bcast< MonoclinicBoundary > (MPI::Intracomm & comm, MonoclinicBoundary & data, int root)
Broadcast an MonoclinicBoundary via MPI.
Definition at line 211 of file MonoclinicBoundary.cpp.
template<class T > void Util::send (MPI::Comm & comm, T & data, int dest, int tag)
Send a single T value.
Throws an Exception if no associated MPI data type is available, i.e., if MpiTraits<T>::hasType is false.
Parameters:
comm MPI communicator
data value
dest MPI rank of receiving processor in comm
tag user-defined integer identifier for message
Definition at line 96 of file MpiSendRecv.h.
References UTIL_THROW.
template<class T > void Util::recv (MPI::Comm & comm, T & data, int source, int tag)
Receive a single T value.
Throws an Exception if no associated MPI data type is available, i.e., if MpiTraits<T>::hasType is false.
Parameters:
comm MPI communicator
data value
source MPI rank of sending processor in comm
tag user-defined integer identifier for message
Definition at line 115 of file MpiSendRecv.h.
References UTIL_THROW.
template<class T > void Util::bcast (MPI::Intracomm & comm, T & data, int root)
Broadcast a single T value.
Throws an Exception if no associated MPI data type is available, i.e., if MpiTraits<T>::hasType is false.
Parameters:
comm MPI communicator
data value
root MPI rank of root (sending) processor in comm
Definition at line 133 of file MpiSendRecv.h.
References UTIL_THROW.
std::istream & Util::operator>> (std::istream & in, OrthorhombicBoundary & boundary)
istream extractor for a OrthorhombicBoundary.
istream extractor
Parameters:
in input stream
boundary OrthorhombicBoundary to be read from stream
Returns:
modified input stream
Definition at line 149 of file OrthorhombicBoundary.cpp.
References Util::OrthoRegion::maxima_, and UTIL_THROW.
std::ostream & Util::operator<< (std::ostream & out, const OrthorhombicBoundary & boundary)
ostream inserter for an OrthorhombicBoundary.
ostream inserter
Parameters:
out output stream
boundary OrthorhombicBoundary to be written to stream
Returns:
modified output stream
Definition at line 181 of file OrthorhombicBoundary.cpp.
References Util::OrthoRegion::lengths_.
template<> void Util::send< Util::OrthorhombicBoundary > (MPI::Comm & comm, Util::OrthorhombicBoundary & data, int dest, int tag)
Send an OrthorhombicBoundary via MPI.
Definition at line 199 of file OrthorhombicBoundary.cpp.
template<> void Util::recv< Util::OrthorhombicBoundary > (MPI::Comm & comm, Util::OrthorhombicBoundary & data, int source, int tag)
Receive an OrthorhombicBoundary via MPI.
Definition at line 207 of file OrthorhombicBoundary.cpp.
template<> void Util::bcast< Util::OrthorhombicBoundary > (MPI::Intracomm & comm, Util::OrthorhombicBoundary & data, int root)
Broadcast an OrthorhombicBoundary via MPI.
Definition at line 216 of file OrthorhombicBoundary.cpp.
template<typename Data > std::istream& Util::operator>> (std::istream & in, Pair< Data > & pair)
Input a Pair from an istream.
Parameters:
in istream from which to read
pair Pair to be read
Definition at line 44 of file Pair.h.
template<typename Data > std::ostream& Util::operator<< (std::ostream & out, const Pair< Data > & pair)
Output a Pair to an ostream, without line breaks.
Parameters:
out ostream to which to write
pair Pair to be written
Definition at line 57 of file Pair.h.
std::istream & Util::operator>> (std::istream & in, LatticeSystem & lattice)
istream extractor for a LatticeSystem.
Parameters:
in input stream
lattice LatticeSystem to be read
Returns:
modified input stream
Definition at line 21 of file LatticeSystem.cpp.
References Util::Log::file(), and UTIL_THROW.
std::ostream & Util::operator<< (std::ostream & out, LatticeSystem lattice)
ostream inserter for an LatticeSystem.
Parameters:
out output stream
lattice LatticeSystem to be written
Returns:
modified output stream
Definition at line 57 of file LatticeSystem.cpp.
References UTIL_THROW.
std::ostream & Util::operator<< (std::ostream & out, const PointGroup & g)
Output stream inserter operator writing a PointGroup to stream.
Definition at line 12 of file PointGroup.cpp.
bool Util::operator== (const PointSymmetry & A, const PointSymmetry & B)
Are two PointSymmetry objects equivalent?
Parameters:
A First object
B Second object
Returns:
True if A == B, false otherwise
Definition at line 98 of file PointSymmetry.cpp.
References Dimension.
PointSymmetry Util::operator* (const PointSymmetry & A, const PointSymmetry & B)
Return the product A*B of two symmetry objects.
Parameters:
A First object
B Second object
Returns:
product A*B
Definition at line 114 of file PointSymmetry.cpp.
References Dimension.
IntVector Util::operator* (const PointSymmetry & S, const IntVector & V)
Return the IntVector product S*V of a rotation matrix and an IntVector.
Parameters:
S PointSymmetry
V Integer Vector
Returns:
product S*V
Definition at line 132 of file PointSymmetry.cpp.
References Dimension.
IntVector Util::operator* (const IntVector & V, const PointSymmetry & S)
Return the IntVector product V*S of an IntVector and a rotation matrix.
Parameters:
S PointSymmetry
V Integer Vector
Returns:
product S*V
Definition at line 148 of file PointSymmetry.cpp.
References Dimension.
std::ostream & Util::operator<< (std::ostream & out, const PointSymmetry & A)
Output stream inserter for a PointSymmetry.
Parameters:
out output stream
A PointSymmetry object to be output
Returns:
modified output stream
Definition at line 164 of file PointSymmetry.cpp.
References Dimension.
bool Util::operator!= (const PointSymmetry & A, const PointSymmetry & B) [inline]
Are two PointSymmetry objects not equivalent?
Parameters:
A First object
B Second object
Returns:
True if A != B, false otherwise
Definition at line 164 of file PointSymmetry.h.
std::istream & Util::operator>> (std::istream & in, BoundaryEnsemble::Type & type)
istream extractor for an BoundaryEnsemble::Type enum value.
Parameters:
in input stream
type BoundaryEnsemble::Type enum value to be read from stream
Returns:
modified input stream
Definition at line 55 of file BoundaryEnsemble.cpp.
References UTIL_THROW.
std::ostream & Util::operator<< (std::ostream & out, const BoundaryEnsemble::Type & type)
ostream inserter for a BoundaryEnsemble::Type enum value.
Parameters:
out output stream
type BoundaryEnsemble::Type enum value to be written to stream
Returns:
modified output stream
Definition at line 73 of file BoundaryEnsemble.cpp.
std::istream & Util::operator>> (std::istream & in, EnergyEnsemble::Type & type)
istream extractor for an EnergyEnsemble::Type enum value.
Parameters:
in input stream
type EnergyEnsemble::Type enum value to be read from stream
Returns:
modified input stream
Definition at line 59 of file EnergyEnsemble.cpp.
References UTIL_THROW.
std::ostream & Util::operator<< (std::ostream & out, const EnergyEnsemble::Type & type)
ostream inserter for a EnergyEnsemble::Type enum value.
Parameters:
out output stream
type EnergyEnsemble::Type enum value to be written to stream
Returns:
modified output stream
Definition at line 77 of file EnergyEnsemble.cpp.
std::istream & Util::operator>> (std::istream & in, SpeciesEnsemble::Type & type)
istream extractor for an SpeciesEnsemble::Type enum value.
Parameters:
in input stream
type SpeciesEnsemble::Type enum value to be read from stream
Returns:
modified input stream
Definition at line 55 of file SpeciesEnsemble.cpp.
References UTIL_THROW.
std::ostream & Util::operator<< (std::ostream & out, const SpeciesEnsemble::Type & type)
ostream inserter for a SpeciesEnsemble::Type enum value.
Parameters:
out output stream
type SpeciesEnsemble::Type enum value to be written to stream
Returns:
modified output stream
Definition at line 73 of file SpeciesEnsemble.cpp.
std::istream & Util::operator>> (std::istream & in, Bool & object)
Input stream extractor for an Bool object.
Parameters:
in input stream
object Bool object to be read from stream
Returns:
modified input stream
Definition at line 52 of file Bool.cpp.
std::ostream & Util::operator<< (std::ostream & out, const Bool & object)
Output stream inserter for an Bool object.
Parameters:
out output stream
object Bool to be written to stream
Returns:
modified output stream
Definition at line 61 of file Bool.cpp.
std::istream & Util::operator>> (std::istream & in, Dbl & object)
Input stream extractor for an Dbl object.
Parameters:
in input stream
object Dbl object to be read from stream
Returns:
modified input stream
Definition at line 77 of file Dbl.cpp.
std::ostream & Util::operator<< (std::ostream & out, const Dbl & object)
Output stream inserter for an Dbl object.
Parameters:
out output stream
object Dbl to be written to stream
Returns:
modified output stream
Definition at line 90 of file Dbl.cpp.
std::istream & Util::operator>> (std::istream & in, Int & object)
Input stream extractor for an Int object.
Parameters:
in input stream
object Int object to be read from stream
Returns:
modified input stream
Definition at line 75 of file Int.cpp.
std::ostream & Util::operator<< (std::ostream & out, const Int & object)
Output stream inserter for an Int object.
Parameters:
out output stream
object Int to be written to stream
Returns:
modified output stream
Definition at line 88 of file Int.cpp.
std::istream & Util::operator>> (std::istream & in, Lng & object)
Input stream extractor for an Lng object.
Parameters:
in input stream
object Lng object to be read from stream
Returns:
modified input stream
Definition at line 57 of file Lng.cpp.
std::ostream & Util::operator<< (std::ostream & out, const Lng & object)
Output stream inserter for an Lng object.
Parameters:
out output stream
object Lng to be written to stream
Returns:
modified output stream
Definition at line 70 of file Lng.cpp.
std::istream & Util::operator>> (std::istream & in, Str & object)
Input stream extractor for an Str object.
Parameters:
in input stream
object Str object to be read from stream
Returns:
modified input stream
Definition at line 53 of file Str.cpp.
std::ostream & Util::operator<< (std::ostream & out, const Str & object)
Output stream inserter for an Str object.
Parameters:
out output stream
object Str to be written to stream
Returns:
modified output stream
Definition at line 62 of file Str.cpp.
template<> void Util::write (std::ostream & out, double data)
Explicit specialization of write for double data.
Definition at line 24 of file write.cpp.
template<> void Util::write (std::ostream & out, std::complex< double > data)
Explicit specialization of write for double data.
Definition at line 28 of file write.cpp.
template<> void Util::write (std::ostream & out, int data)
Explicit specialization of write for int data.
Definition at line 32 of file write.cpp.
template<> void Util::write (std::ostream & out, long data)
Explicit specialization of write for long data.
Definition at line 36 of file write.cpp.
template<> void Util::write (std::ostream & out, bool data)
Explicit specialization of write for bool data.
Definition at line 40 of file write.cpp.
template<> void Util::write (std::ostream & out, std::string data)
Explicit specialization of write for std::string data.
template<> void Util::send< bool > (MPI::Comm & comm, bool & data, int dest, int tag)
Explicit specialization of send for bool data.
Definition at line 21 of file MpiSendRecv.cpp.
template<> void Util::recv< bool > (MPI::Comm & comm, bool & data, int source, int tag)
Explicit specialization of recv for bool data.
Definition at line 28 of file MpiSendRecv.cpp.
template<> void Util::bcast< bool > (MPI::Intracomm & comm, bool & data, int root)
Explicit specialization of bcast for bool data.
Definition at line 36 of file MpiSendRecv.cpp.
template<> void Util::send< std::string > (MPI::Comm & comm, std::string & data, int dest, int tag)
Explicit specialization of send for std::string data.
Definition at line 50 of file MpiSendRecv.cpp.
template<> void Util::recv< std::string > (MPI::Comm & comm, std::string & data, int source, int tag)
Explicit specialization of recv for std::string data.
Definition at line 66 of file MpiSendRecv.cpp.
template<> void Util::bcast< std::string > (MPI::Intracomm & comm, std::string & data, int root)
Explicit specialization of bcast for std::string data.
Definition at line 82 of file MpiSendRecv.cpp.
template<typename T > void Util::send (MPI::Comm & comm, T * array, int count, int dest, int tag)
Send a C-array of T values.
Throws an exception if their exists neither an associated MPI data type nor an explicit specialization of the scalar send<T>.
Parameters:
comm MPI communicator
array address of first element in array
count number of elements in array
dest MPI rank of destination (receiving) processor in comm
tag user-defined integer identifier for this message
Definition at line 155 of file MpiSendRecv.h.
template<typename T > void Util::recv (MPI::Comm & comm, T * array, int count, int source, int tag)
Receive a C-array of T objects.
Throws an exception if their exists neither an associated MPI data type nor an explicit specialization of the scalar recv<T>.
Parameters:
comm MPI communicator
array address of first element in array
count number of elements in array
source MPI rank of source (sending) processor in comm
tag user-defined integer identifier for this message
Definition at line 181 of file MpiSendRecv.h.
template<typename T > void Util::bcast (MPI::Intracomm & comm, T * array, int count, int root)
Broadcast a C-array of T objects.
Throws an exception if their exists neither an associated MPI data type nor an explicit specialization of the scalar bcast<T>.
Parameters:
comm MPI communicator
array address of first element in array
count number of elements in array
root MPI rank of root (sending) processor in comm
Definition at line 206 of file MpiSendRecv.h.
Referenced by DdMd::NptIntegrator::integrateStep1(), DdMd::NphIntegrator::integrateStep1(), DdMd::NvtIntegrator::integrateStep2(), DdMd::NptIntegrator::integrateStep2(), DdMd::NphIntegrator::integrateStep2(), DdMd::Simulation::isValid(), DdMd::DdMdConfigIo::readConfig(), DdMd::NvtIntegrator::setup(), DdMd::NptIntegrator::setup(), and DdMd::NphIntegrator::setup().
template<typename T > void Util::send (MPI::Comm & comm, DArray< T > & array, int count, int dest, int tag)
Send a DArray<T> container.
Throws an exception if their exists neither an associated MPI data type nor an explicit specialization of the scalar send<T>.
Parameters:
comm MPI communicator
array address of first element in array
count number of elements in array
dest MPI rank of destination (receiving) processor in comm
tag user-defined integer identifier for this message
Definition at line 234 of file MpiSendRecv.h.
template<typename T > void Util::recv (MPI::Comm & comm, DArray< T > & array, int count, int source, int tag)
Receive a DArray<T> container.
Throws an exception if their exists neither an associated MPI data type nor an explicit specialization of the scalar recv<T>.
Parameters:
comm MPI communicator
array address of first element in array
count number of elements in array
source MPI rank of source (sending) processor in comm
tag user-defined integer identifier for this message
Definition at line 260 of file MpiSendRecv.h.
template<typename T > void Util::bcast (MPI::Intracomm & comm, DArray< T > & array, int count, int root)
Broadcast a DArray<T> container.
Throws an exception if their exists neither an associated MPI data type nor an explicit specialization of the scalar bcast<T>.
Parameters:
comm MPI communicator
array address of first element in array
count number of elements in array
root MPI rank of root (sending) processor in comm
Definition at line 285 of file MpiSendRecv.h.
template<typename T > void Util::send (MPI::Comm & comm, DMatrix< T > & matrix, int m, int n, int dest, int tag)
Send a DMatrix<T> container.
Throws an exception if their exists neither an associated MPI data type nor an explicit specialization of the scalar send<T>.
Parameters:
comm MPI communicator
matrix address of first element in matrix
m number of rows in matrix
n number of columns in matrix
dest MPI rank of destination (receiving) processor in comm
tag user-defined integer identifier for this message
Definition at line 314 of file MpiSendRecv.h.
template<typename T > void Util::recv (MPI::Comm & comm, DMatrix< T > & matrix, int m, int n, int source, int tag)
Receive a DMatrix<T> container.
Throws an exception if their exists neither an associated MPI data type nor an explicit specialization of the scalar recv<T>.
Parameters:
comm MPI communicator
matrix address of first element in matrix
m number of rows in matrix
n number of columns in matrix
source MPI rank of source (sending) processor in comm
tag user-defined integer identifier for this message
Definition at line 344 of file MpiSendRecv.h.
template<typename T > void Util::bcast (MPI::Intracomm & comm, DMatrix< T > & matrix, int m, int n, int root)
Broadcast a DMatrix<T> container.
Throws an exception if their exists neither an associated MPI data type nor an explicit specialization of the scalar bcast<T>.
Parameters:
comm MPI communicator
matrix address of first element in matrix
m number of rows in matrix
n number of columns in matrix
root MPI rank of root (sending) processor in comm
Definition at line 374 of file MpiSendRecv.h.
std::istream & Util::operator>> (std::istream & in, Label label)
Extractor for Label.
Parameters:
in input stream
label Label to be read from file
Definition at line 51 of file Label.cpp.
References Util::Log::file(), and UTIL_THROW.
std::ostream & Util::operator<< (std::ostream & out, Label label)
Inserter for Label.
Parameters:
out output stream
label Label to be written to file
Definition at line 67 of file Label.cpp.
References Util::Label::LabelWidth.
template<typename T > bool Util::isNull (FlexPtr< T > p) [inline]
Return true iff the enclosed built-in pointer is null.
Definition at line 144 of file FlexPtr.h.
template<typename T > bool Util::isNull (T * ptr) [inline]
Return true iff a built-in pointer is null.
Definition at line 18 of file isNull.h.
template<typename T > bool Util::isNull (ScopedPtr< T > p) [inline]
Return true iff the enclosed built-in pointer is null.
Definition at line 90 of file ScopedPtr.h.
References Util::ScopedPtr< T >::get().
bool Util::operator== (const IntVector & v1, const IntVector & v2)
Equality for IntVectors.
Definition at line 28 of file IntVector.cpp.
References Dimension.
bool Util::operator== (const IntVector & v1, const int * v2)
Equality of IntVector and C array.
Definition at line 39 of file IntVector.cpp.
References Dimension.
bool Util::operator== (const int * v1, const IntVector & v2)
Equality of C array and IntVector.
Definition at line 49 of file IntVector.cpp.
bool Util::operator!= (const IntVector & v1, const IntVector & v2)
Inequality of two IntVectors.
Definition at line 54 of file IntVector.cpp.
bool Util::operator!= (const IntVector & v1, const int * v2)
Inequality of IntVector and C array.
Definition at line 58 of file IntVector.cpp.
bool Util::operator!= (const int * v1, const IntVector & v2)
Inequality of C array and IntVector.
Definition at line 62 of file IntVector.cpp.
std::istream & Util::operator>> (std::istream & in, IntVector & vector)
istream extractor for a IntVector.
Input elements of a vector from stream, without line breaks.
Parameters:
in input stream
vector IntVector to be read from stream
Returns:
modified input stream
Definition at line 68 of file IntVector.cpp.
References Dimension.
std::ostream & Util::operator<< (std::ostream & out, const IntVector & vector)
ostream inserter for a IntVector.
Output elements of a vector to stream, without line breaks.
Parameters:
out output stream
vector IntVector to be written to stream
Returns:
modified output stream
Definition at line 79 of file IntVector.cpp.
References Dimension.
bool Util::operator== (const Tensor & t1, const Tensor & t2)
Equality for Tensors.
Definition at line 40 of file Tensor.cpp.
References DimensionSq.
bool Util::operator== (const Tensor & t1, const double a2[][Dimension])
Equality of Tensor and 2D C array.
Definition at line 50 of file Tensor.cpp.
References Dimension.
bool Util::operator== (const double a1[][Dimension], const Tensor & t2)
Equality of C array and Tensor.
Definition at line 64 of file Tensor.cpp.
bool Util::operator!= (const Tensor & t1, const Tensor & t2)
Inequality of two Tensors.
Definition at line 69 of file Tensor.cpp.
bool Util::operator!= (const Tensor & t1, const double a2[][Dimension])
Inequality of Tensor and C array.
Definition at line 72 of file Tensor.cpp.
bool Util::operator!= (const double a1[][Dimension], const Tensor & t2)
Inequality of C array and Tensor.
Definition at line 75 of file Tensor.cpp.
std::istream & Util::operator>> (std::istream & in, Tensor & tensor)
istream extractor for a Tensor.
Input elements of a tensor from stream, without line breaks.
Parameters:
in input stream
tensor Tensor to be read from stream
Returns:
modified input stream
Definition at line 81 of file Tensor.cpp.
References DimensionSq.
std::ostream & Util::operator<< (std::ostream & out, const Tensor & tensor)
ostream inserter for a Tensor.
Output elements of a tensor to stream, without line breaks.
Parameters:
out output stream
tensor Tensor to be written to stream
Returns:
modified output stream
Definition at line 92 of file Tensor.cpp.
References DimensionSq.
bool Util::operator== (const Vector & v1, const Vector & v2)
Equality for Vectors.
Definition at line 30 of file Vector.cpp.
References Dimension.
bool Util::operator== (const Vector & v1, const double * v2)
Equality of Vector and C array.
Definition at line 40 of file Vector.cpp.
References Dimension.
bool Util::operator== (const double * v1, const Vector & v2)
Equality of C array and Vector.
Definition at line 52 of file Vector.cpp.
bool Util::operator!= (const Vector & v1, const Vector & v2)
Inequality of two Vectors.
Definition at line 57 of file Vector.cpp.
bool Util::operator!= (const Vector & v1, const double * v2)
Inequality of Vector and C array.
Definition at line 60 of file Vector.cpp.
bool Util::operator!= (const double * v1, const Vector & v2)
Inequality of C array and Vector.
Definition at line 63 of file Vector.cpp.
std::istream & Util::operator>> (std::istream & in, Vector & vector)
istream extractor for a Vector.
Input elements of a vector from stream, without line breaks.
Parameters:
in input stream
vector Vector to be read from stream
Returns:
modified input stream
Definition at line 69 of file Vector.cpp.
References Dimension.
std::ostream & Util::operator<< (std::ostream & out, const Vector & vector)
ostream inserter for a Vector.
Output elements of a vector to stream, without line breaks.
Parameters:
out output stream
vector Vector to be written to stream
Returns:
modified output stream
Definition at line 80 of file Vector.cpp.
References Dimension.
void Util::initStatic ()
Guarantee initialization of all static class members in Util namespace.
Definition at line 29 of file initStatic.cpp.
References Util::Tensor::initStatic(), Util::IntVector::initStatic(), Util::Vector::initStatic(), Util::Constants::initStatic(), Util::ParamComponent::initStatic(), Util::Memory::initStatic(), Util::Format::initStatic(), and Util::Log::initStatic().
Referenced by DdMd::Simulation::Simulation(), and McMd::Simulation::Simulation().
int Util::rStrip (std::string & string)
Strip trailing whitespace from a string.
Parameters:
string string (stripped upon return).
Returns:
length of stripped string.
Definition at line 22 of file ioUtil.cpp.
Referenced by Util::TextComposite::readParam().
void Util::checkString (std::istream & in, std::string & expected)
Read string, and compare to expected value.
Exceptions:
Exception if input value differs from expected value.
Parameters:
in input stream
expected expected value of string read from stream
Definition at line 41 of file ioUtil.cpp.
References Util::Log::file(), and UTIL_THROW.
std::string Util::toString (int n)
Return string representation of an integer.
Parameters:
n integer to be converted.
Definition at line 56 of file ioUtil.cpp.
Referenced by McMd::VanHove::output(), McMd::StructureFactorPGrid::output(), McMd::StructureFactorP::output(), McMd::StructureFactorGrid::output(), McMd::StructureFactor::output(), DdMd::WriteConfig::sample(), and McMd::DumpConfig::sample().
void Util::getNextLine (std::istream & in, std::string & line)
Get the next non-empty line of input, skipping any empty lines.
Variant of std::getline() that skips empty lines.
Parameters:
in input stream from which to read.
line string with next non-empty line, on output.
Definition at line 67 of file ioUtil.cpp.
Referenced by McMd::MdSimulation::readCommands(), and McMd::McSimulation::readCommands().
void Util::getLine (std::istream & in, std::stringstream & line)
Read the next line into a stringstream.
Parameters:
in input stream from which to read.
line stringstream containing line, on output.
Definition at line 81 of file ioUtil.cpp.
void Util::getNextLine (std::istream & in, std::stringstream & line)
Read the next non-empty line into a stringstream.
Variant of std::getline() that skips empty lines and uses stringstream.
Parameters:
in input stream from which to read.
line stringstream containing next non-empty line, on output.
Definition at line 92 of file ioUtil.cpp.
template<typename D , typename B > ptrdiff_t Util::baseOffset (D & object)
Template for calculating offsets of base class subobjects.
Types: D - derived class B - base class
Definition at line 40 of file Offset.h.
template<> void Util::send< McMd::AtomType > (MPI::Comm & comm, McMd::AtomType & data, int dest, int tag)
Send an AtomType (wrapper for MPI Send).
Definition at line 65 of file mcMd/chemistry/AtomType.cpp.
template<> void Util::recv< McMd::AtomType > (MPI::Comm & comm, McMd::AtomType & data, int source, int tag)
Receive an AtomType (wrapper for MPI Recv).
Definition at line 74 of file mcMd/chemistry/AtomType.cpp.
template<> void Util::bcast< McMd::AtomType > (MPI::Intracomm & comm, McMd::AtomType & data, int root)
Broadcast an AtomType (wrapper for MPI Bcast).
Definition at line 85 of file mcMd/chemistry/AtomType.cpp.