Simpatico: Simp Namespace Reference
Simp Namespace Reference
Classes used by all simpatico molecular simulations.
Classes
struct Bend
A Bend calculates the angle between two vectors.
struct BendForce
A BendForce computes derivatives of the angle between two vectors.
class BoundaryEnsemble
Statistical ensemble for changes in the periodic unit cell size.
class BoxExternal
A repulsive 9-3 potential confining particles within a box.
class CompensatedPair
Compensated pair potential for transient gel.
class CompositeBond
Composite bond potential.
class CosineAngle
A three body angle potential, as a function of angle cosine.
class CosineDihedral
A dihedral potential proportional to cos(phi).
class CosineSqAngle
A three body angle potential, as a function of angle cosine.
class Diblock
A linear diblock copolymer chain.
class DpdPair
Soft pair potential used in dissipative particle dynamics (DPD) simulations of Groot, Warren et al.
class EnergyEnsemble
A statistical ensemble for energy.
class EwaldInteraction
Implementation of r-space and k-space Ewald Coulomb interactions.
class FeneBond
A finitely-extensible nonlinear element (FENE) bond potential.
class GeneralPeriodicExternal
A clipped cosine potential that induces ordering along directions specified by waveIntVectors, w_i.
class HarmonicAngle
A angle potential that is harmonic in the angle.
class HarmonicBond
A harmonic covalent bond potential.
class HarmonicL0Bond
A harmonic bond potential with zero rest length.
class Homopolymer
A Homopolymer species of chain molecules.
class HomoRing
A species of homogeneous ring molecules.
class LamellarOrderingExternal
A clipped cosine potential that induces lamellar ordering along the direction specified by perpDirection_.
class Linear
A Species of linear polymers (abstract).
class LJPair
A cutoff, shifted Lennard-Jones nonbonded pair interaction.
class LocalLamellarOrderingExternal
A clipped cosine potential that induces lamellar ordering along the direction specified by perpDirection_ in only a fraction of box specified by the parameter fraction along box length in parallelDirection_.
class MonoclinicBoundary
A monoclinic periodic unit cell.
class Multiblock
A linear MULTIBLOCK copolymer chain.
class MultiHarmonicDihedral
A truncated Fourier series dihedral potential.
class NucleationExternal
A clipped cosine potential that induces ordering along directions specified by waveIntVectors, w_i.
class OrthoBoxExternal
A repulsive 9-3 potential confining particles inside an orthogonal box along directions specified by indConfine_.
struct OrthoRegion
A region with orthogonal edges parallel to the x, y, and z axes.
class OrthorhombicBoundary
An orthorhombic periodic unit cell.
class PeriodicExternal
A clipped cosine potential that induces ordering along directions specified by waveIntVectors, w_i.
class Point
A Species in which each Molecule contains only one Atom.
class Ring
A Species of ring polymers (abstract).
class SimplePeriodicExternal
A clipped cosine potential that induces ordering along directions specified by waveIntVectors, w_i.
class SlitExternal
A repulsive 9-3 potential confining particles along the z direction.
class Species
A Species represents a set of chemically similar molecules.
class SpeciesEnsemble
An ensemble for the number of molecules of one Species.
class SpeciesGroup
A Group of covalently interacting atoms within any molecule of one Species.
class SphericalTabulatedExternal
The potential is independent on the type of atoms.
struct Torsion
Computes dihedral / torsion angle involving 3 bonds.
struct TorsionForce
Computes derivatives of dihedral angle with respect to bond vectors.
class WcaPair
A Weeks-Chandler-Anderson (WCA) repulsive LJ interaction.
Typedefs
typedef OrthorhombicBoundary Boundary
Boundary is an alias for the periodic boundary condition class.
Functions
std::istream & operator>> (std::istream &in, MonoclinicBoundary &boundary)
istream extractor for a MonoclinicBoundary.
std::ostream & operator<< (std::ostream &out, const MonoclinicBoundary &boundary)
ostream inserter for an MonoclinicBoundary.
std::istream & operator>> (std::istream &in, OrthorhombicBoundary &boundary)
istream extractor for a OrthorhombicBoundary.
std::ostream & operator<< (std::ostream &out, const OrthorhombicBoundary &boundary)
ostream inserter for an OrthorhombicBoundary.
std::istream & operator>> (std::istream &in, BoundaryEnsemble::Type &type)
istream extractor for an BoundaryEnsemble::Type enum value.
std::ostream & operator<< (std::ostream &out, const BoundaryEnsemble::Type &type)
ostream inserter for a BoundaryEnsemble::Type enum value.
template<class Archive >
void serialize (Archive &ar, BoundaryEnsemble::Type &data, const unsigned int version)
Serialize a BoundaryEnsemble::Type enum value.
std::istream & operator>> (std::istream &in, EnergyEnsemble::Type &type)
istream extractor for an EnergyEnsemble::Type enum value.
std::ostream & operator<< (std::ostream &out, EnergyEnsemble::Type const &type)
ostream inserter for a EnergyEnsemble::Type enum value.
template<class Archive >
void serialize (Archive &ar, EnergyEnsemble::Type &data, const unsigned int version)
Serialize a EnergyEnsemble::Type enum value.
std::istream & operator>> (std::istream &in, SpeciesEnsemble::Type &type)
istream extractor for an SpeciesEnsemble::Type enum value.
std::ostream & operator<< (std::ostream &out, const SpeciesEnsemble::Type &type)
ostream inserter for a SpeciesEnsemble::Type enum value.
template<class Archive >
void serialize (Archive &ar, SpeciesEnsemble::Type &data, const unsigned int version)
Serialize a SpeciesEnsemble::Type enum value.
void commitMpiSpeciesGroupTypes ()
Commit all MPI SpeciesGroup data types.
template<int NAtom>
std::istream & operator>> (std::istream &in, SpeciesGroup< NAtom > &speciesGroup)
istream extractor for a SpeciesGroup.
template<int NAtom>
std::ostream & operator<< (std::ostream &out, const SpeciesGroup< NAtom > &speciesGroup)
ostream inserter for a SpeciesGroup.
template<class Archive , int NAtom>
void serialize (Archive &ar, SpeciesGroup< NAtom > &speciesGroup, const unsigned int version)
Serialize one SpeciesGroup<NAtom>.
Detailed Description
Classes used by all simpatico molecular simulations.
Function Documentation
std::istream & Simp::operator>> (std::istream & in, MonoclinicBoundary & boundary)
istream extractor for a MonoclinicBoundary.
istream extractor
Parameters
in input stream
boundary MonoclinicBoundary to be read from stream
Returns
modified input stream
Definition at line 161 of file MonoclinicBoundary.cpp.
References UTIL_THROW.
std::ostream & Simp::operator<< (std::ostream & out, const MonoclinicBoundary & boundary)
ostream inserter for an MonoclinicBoundary.
ostream inserter
Parameters
out output stream
boundary MonoclinicBoundary to be written to stream
Returns
modified output stream
Definition at line 178 of file MonoclinicBoundary.cpp.
Referenced by operator>>().
std::istream & Simp::operator>> (std::istream & in, OrthorhombicBoundary & boundary)
istream extractor for a OrthorhombicBoundary.
istream extractor
Parameters
in input stream
boundary OrthorhombicBoundary to be read from stream
Returns
modified input stream
Definition at line 157 of file OrthorhombicBoundary.cpp.
References Simp::OrthoRegion::maxima_, and UTIL_THROW.
std::ostream & Simp::operator<< (std::ostream & out, const OrthorhombicBoundary & boundary)
ostream inserter for an OrthorhombicBoundary.
ostream inserter
Parameters
out output stream
boundary OrthorhombicBoundary to be written to stream
Returns
modified output stream
Definition at line 189 of file OrthorhombicBoundary.cpp.
References Simp::OrthoRegion::lengths_.
std::istream & Simp::operator>> (std::istream & in, BoundaryEnsemble::Type & type)
istream extractor for an BoundaryEnsemble::Type enum value.
Parameters
in input stream
type BoundaryEnsemble::Type enum value to be read from stream
Returns
modified input stream
Definition at line 79 of file BoundaryEnsemble.cpp.
References UTIL_THROW.
std::ostream & Simp::operator<< (std::ostream & out, const BoundaryEnsemble::Type & type)
ostream inserter for a BoundaryEnsemble::Type enum value.
Parameters
out output stream
type BoundaryEnsemble::Type enum value to be written to stream
Returns
modified output stream
Definition at line 97 of file BoundaryEnsemble.cpp.
template<class Archive > void Simp::serialize (Archive & ar, BoundaryEnsemble::Type & data, const unsigned int version) inline
Serialize a BoundaryEnsemble::Type enum value.
Parameters
ar archive object
data enum value to be serialized
version archive version id
Definition at line 162 of file BoundaryEnsemble.h.
References Util::serializeEnum().
std::istream & Simp::operator>> (std::istream & in, EnergyEnsemble::Type & type)
istream extractor for an EnergyEnsemble::Type enum value.
Parameters
in input stream
type EnergyEnsemble::Type enum value to be read from stream
Returns
modified input stream
Definition at line 85 of file EnergyEnsemble.cpp.
References operator<<(), and UTIL_THROW.
std::ostream& Simp::operator<< (std::ostream & out, EnergyEnsemble::Type const & type)
ostream inserter for a EnergyEnsemble::Type enum value.
Parameters
out output stream
type EnergyEnsemble::Type enum value to be written to stream
Returns
modified output stream
template<class Archive > void Simp::serialize (Archive & ar, EnergyEnsemble::Type & data, const unsigned int version) inline
Serialize a EnergyEnsemble::Type enum value.
Parameters
ar archive object
data enum value to be serialized
version archive version id
Definition at line 175 of file EnergyEnsemble.h.
References Util::serializeEnum().
std::istream & Simp::operator>> (std::istream & in, SpeciesEnsemble::Type & type)
istream extractor for an SpeciesEnsemble::Type enum value.
Parameters
in input stream
type SpeciesEnsemble::Type enum value to be read from stream
Returns
modified input stream
Definition at line 59 of file SpeciesEnsemble.cpp.
References UTIL_THROW.
std::ostream & Simp::operator<< (std::ostream & out, const SpeciesEnsemble::Type & type)
ostream inserter for a SpeciesEnsemble::Type enum value.
Parameters
out output stream
type SpeciesEnsemble::Type enum value to be written to stream
Returns
modified output stream
Definition at line 77 of file SpeciesEnsemble.cpp.
template<class Archive > void Simp::serialize (Archive & ar, SpeciesEnsemble::Type & data, const unsigned int version) inline
Serialize a SpeciesEnsemble::Type enum value.
Parameters
ar archive object
data enum value to be serialized
version archive version id
Definition at line 140 of file SpeciesEnsemble.h.
References Util::serializeEnum().
void Simp::commitMpiSpeciesGroupTypes ()
Commit all MPI SpeciesGroup data types.
Definition at line 38 of file SpeciesGroup.cpp.
References commitMpiSpeciesGroupTypes(), and Simp::SpeciesGroup< NAtom >::commitMpiType().
Referenced by commitMpiSpeciesGroupTypes(), and McMd::commitMpiTypes().
template<int NAtom> std::istream & Simp::operator>> (std::istream & in, SpeciesGroup< NAtom > & speciesGroup)
istream extractor for a SpeciesGroup.
The format is as follows:
 atomIds[0] atomIds[1] ...  atomId[NAtom-1]  typeId
Parameters
in input stream
speciesGroup SpeciesGroup to be read from stream
Returns
modified input stream
Definition at line 27 of file SpeciesGroup.tpp.
template<int NAtom> std::ostream & Simp::operator<< (std::ostream & out, const SpeciesGroup< NAtom > & speciesGroup)
ostream inserter for a SpeciesGroup.
The format is as follows, output one one line with no line break:
 atomIds[0] atomIds[1] ...  atomId[NAtom-1] typeId
Parameters
out output stream
speciesGroup SpeciesGroup to be written to stream
Returns
modified output stream
Definition at line 41 of file SpeciesGroup.tpp.
template<class Archive , int NAtom> void Simp::serialize (Archive & ar, SpeciesGroup< NAtom > & speciesGroup, const unsigned int version)
Serialize one SpeciesGroup<NAtom>.
Default implementation calls serialize member function of data object. Can be overridden by any explicit specialization.
Parameters
ar archive object
speciesGroup object to be serialized
version archive version id