Simpatico: McMd::ClusterLink Struct Reference
McMd::ClusterLink Struct Reference
Detailed Description
Molecule in a cluster.
A cluster is defined by a linked list of ClusterLink objects.
Definition at line 22 of file ClusterLink.h.
#include <ClusterLink.h>
Public Member Functions
void clear ()
Set to default state.
void setMolecule (Molecule &molecule)
Set pointer to associated molecule.
Molecule & molecule () const
Get associated molecule by reference.
ClusterLink * next () const
Get pointer to next link in linked list.
int clusterId () const
Get cluster identifier.
Member Function Documentation
void McMd::ClusterLink::clear () inline
Set to default state.
Definition at line 69 of file ClusterLink.h.
Referenced by McMd::Cluster::clear().
void McMd::ClusterLink::setMolecule (Molecule & molecule) inline
Set pointer to associated molecule.
Definition at line 78 of file ClusterLink.h.
References molecule().
Molecule & McMd::ClusterLink::molecule () const inline
Get associated molecule by reference.
Definition at line 83 of file ClusterLink.h.
Referenced by McMd::Cluster::clusterCOM(), McMd::ClusterIdentifier::identifyClusters(), McMd::ClusterIdentifier::initialize(), McMd::ClusterIdentifier::isValid(), McMd::Cluster::momentTensor(), McMd::ClusterHistogram::sample(), and setMolecule().
ClusterLink * McMd::ClusterLink::next () const inline
Get pointer to next link in linked list.
Definition at line 88 of file ClusterLink.h.
Referenced by McMd::Cluster::clear(), McMd::Cluster::clusterCOM(), McMd::Cluster::isValid(), McMd::Cluster::momentTensor(), McMd::ClusterHistogram::sample(), and McMd::Cluster::setId().
int McMd::ClusterLink::clusterId () const inline
Get cluster identifier.
Definition at line 93 of file ClusterLink.h.
Referenced by McMd::ClusterIdentifier::identifyClusters(), McMd::ClusterIdentifier::initialize(), McMd::Cluster::isValid(), and McMd::ClusterIdentifier::isValid().
The documentation for this struct was generated from the following file:
ClusterLink.h