# ==========================================================================
# test species directory 

SPECIES_DIR=$(SRC_DIR)/mcMd/species
 
# Targets
SpeciesTest=$(SPECIES_DIR)/tests/SpeciesTest
HomopolymerTest=$(SPECIES_DIR)/tests/HomopolymerTest
HomoRingTest=$(SPECIES_DIR)/tests/HomoRingTest

 
$(SpeciesTest).h: $(Species).h
	touch $@

$(HomopolymerTest).h: $(Homopolymer).h
	touch $@

$(HomoRingTest).h: $(HomoRing).h
	touch $@

# ==========================================================================
