# ---------------------------------------------------------------------
# File: src/simp/patterns.mk
#
# This makefile contains the pattern rule used to compile all source
# files in the src/simp directory tree. This file is included by all 
# makefile files in the src/simp directory tree. 
#
# This file should be included in other makefiles after inclusion of 
# the main config.mk in the build directory, and the util/config.mk 
# and simp/config.mk namespace level config files. 
#-----------------------------------------------------------------------
# Include makefile fragments

# Namespace level build configuration files
# Define *_DEFS macro definitions, paths to libraries and executables
include $(BLD_DIR)/util/config.mk
include $(BLD_DIR)/simp/config.mk

# Namespace level source file lists
# Include recipes for library targets
include $(SRC_DIR)/util/sources.mk
include $(SRC_DIR)/simp/sources.mk

#-----------------------------------------------------------------------
# Makefile variable definitions

# Lists of all macro definitions required in different contexts
UTIL_ADEF=$(UTIL_DEFS)
SIMP_ADEF=$(UTIL_DEFS) $(SIMP_DEFS)

# Dependencies on build configuration files
# These are added to dependency lists generated by $(MAKEDEP)
UTIL_CFGS= -A$(BLD_DIR)/config.mk
UTIL_CFGS+= -A$(BLD_DIR)/util/config.mk
SIMP_CFGS=$(UTIL_CFGS)
SIMP_CFGS+= -A$(BLD_DIR)/simp/config.mk

# All libraries needed to link executable files in src/simp/
LIBS= $(simp_LIB) $(util_LIB)

#-----------------------------------------------------------------------
# Pattern rules

# Rule to compile all *.cpp class source files in src/simp
$(BLD_DIR)/simp/%.o: $(SRC_DIR)/simp/%.cpp
	$(CXX) $(INCLUDES) $(SIMP_ADEF) $(CXXFLAGS) -c -o $@ $<
ifdef MAKEDEP
	$(MAKEDEP) $(INCLUDES) $(SIMP_ADEF) $(CXXFLAGS) $(SIMP_CFGS) -S$(SRC_DIR) -B$(BLD_DIR) $<
endif

# Rule to compile all *.cpp class source files in src/util
$(BLD_DIR)/util/%.o: $(SRC_DIR)/util/%.cpp
	$(CXX) $(INCLUDES) $(UTIL_ADEF) $(CXXFLAGS) -c -o $@ $<
ifdef MAKEDEP
	$(MAKEDEP) $(INCLUDES) $(UTIL_ADEF) $(CXXFLAGS) $(UTIL_CFGS) -S$(SRC_DIR) -B$(BLD_DIR) $<
endif

# Rule to compile all *.cc test programs in src/simp/tests
$(BLD_DIR)/%.o: $(SRC_DIR)/%.cc
	$(CXX) $(INCLUDES) $(SIMP_ADEF) $(TESTFLAGS) -c -o $@ $<
ifdef MAKEDEP
	$(MAKEDEP) $(INCLUDES) $(SIMP_ADEF) $(TESTFLAGS) $(SIMP_CFGS) -S$(SRC_DIR) -B$(BLD_DIR) $<
endif

# Rule to link all *.cc test programs in src/simp/tests
$(BLD_DIR)/%: $(BLD_DIR)/%.o $(LIBS)
	$(CXX) -o $@ $@.o $(LIBS) $(LDFLAGS)
