# ==========================================================================
# test math directory 

POTENTIAL_TEST_DIR=$(SRC)/mcMd/potentials/tests
 
# File macros
COSINETORSION_TEST=$(POTENTIAL_TEST_DIR)/torsion/CosineTorsionTest
LJPAIR_TEST=$(POTENTIAL_TEST_DIR)/pair/LJPairTest
HARMONICBOND_TEST=$(POTENTIAL_TEST_DIR)/bond/HarmonicBondTest
HARMONICL0BOND_TEST=$(POTENTIAL_TEST_DIR)/bond/HarmonicL0BondTest
POTENTIAL_TEST_COMPOSITE=$(POTENTIAL_TEST_DIR)/PotentialTestComposite

# Targets

$(COSINETORSION_TEST).h: $(COSINETORSION_TEST).h $(UNIT_TEST).h
	touch $@
 
$(LJPAIR_TEST).h: $(LJPAIR).h $(UNIT_TEST).h
	touch $@
 
$(HARMONICBOND_TEST).h: $(HARMONICBOND).h $(UNIT_TEST).h
	touch $@
 
$(HARMONICL0BOND_TEST).h: $(HARMONICL0BOND).h $(UNIT_TEST).h
	touch $@
 
$(POTENTIAL_TEST_COMPOSITE).h: $(LJPAIR_TEST).h $(COSINETORSION_TEST).h \
        $(HARMONICBOND_TEST).h $(HARMONICL0BOND_TEST).h \
        $(COMPOSITE_TEST_RUNNER).h
	touch $@
 
# ==========================================================================
